### ISSUE TITLE
xSchedule Crashing

### ISSUE THREAD

**Issue by wwid4christ** [smeighan/xLights#1002]
Running xSchedule on a windows 10 pc, loaded with 8gb ram and 2.4ghz i3 processor. It is the only thing running on the computer and for some reason every 24 hours or so the program crashes or stops transmitting dmx. The crashes occur about 50/50 between when the software is dormant and when it should be running. Also, I save my schedule every time I open the software, but it never actually saves. Any Ideas? Again, I'm still new to this, so it's possible I've got something wrong

**Comment by keithsw1111** [comment]
You dont make it clear which version you are running and you didnt attach any crash logs. It is kind of hard to speculate about an issue with so little information.

**Comment by keithsw1111** [comment]
Insufficient information.
