### ISSUE TITLE
Mac Crash

### ISSUE THREAD

**Issue by GMANFRE57** [smeighan/xLights#1004]
I have mac yosemite 10.10 running xlights version 33 and try to install version 39 but i have problem
![screen shot 2017-
[mac.pdf](https://github.com/smeighan/xLights/files/1523521/mac.pdf)
12-01 at 8 57 08 pm](https://user-images.githubusercontent.com/31975835/33511106-ca2620b8-d6da-11e7-9a4b-9d244b78ef26.png)

**Comment by keithsw1111** [comment]
With no additional information provided I am going to have to close this ticket.
