### ISSUE TITLE
Allow Negative Value in the Tilt Orientation Field

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#1005]
Moving heads with a Tilt Degree of Rotation greater than 180 degrees need to have a negative value in the Tilt Orientation field in order to accurately show in the preview that the mid-point of the tilt value range is straight up.

**Comment by idleup** [comment]
Also, it appears this is just a UI problem as setting the value negative in the XML file seems to render everything correctly on the xLights preview.

**Comment by AzGilrock** [comment]
I think this is a user understanding problem unless you can show me why positive values don't work.  The tilt orientation value is 0-360 which covers all possible positions.  Its supposed to be set to the angle your head is when set to 0.  You mentioned you wanted to set it to -36 degrees.  Well that's the same as 360-36 so 324 degrees would work exactly the same.  I just tested setting a head to 324 with a 252 degree of rotation which allows a 36 degree dip on both sides and the midpoint value of 128 points it straight up.  Show me all the exact configuration numbers you are using and help me understand why 360 minus the number of degrees you want doesn't work.

**Comment by AzGilrock** [comment]
So using a calculator you can confirm that the sin or cos of X equals that of (360 - X) so negative values are not needed.
