### ISSUE TITLE
Unable to delete models from the Sequence Element Screen

### ISSUE THREAD

**Issue by smeighan** [smeighan/xLights#101]
You can add models, the Delete Model button does not work.
![delete_models](https://cloud.githubusercontent.com/assets/1583730/6796241/060ebfb4-d1b5-11e4-8530-5912b86a6b66.png)

**Comment by AzGilrock** [comment]
Technically I'd call it an enhancement.  No code was ever written for that button so it's behaving as expected.  There's a ton of more things like Move Up and Move Down aren't coded up.  The View functionality isn't coded up.  We should just leave things greyed out until we connect them up.
