### ISSUE TITLE
Cannot close "Select Show Directory" or shut down Xlights

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#1010]
downloaded .39 version of xlights and it tried to open a directory that no longer exists and it said to chose another one. I don't have another one on my new computer and it does not allow you to close the "Select Show Directory" (it just closes and pops back open) nor can I close xlights by right mousing over the icon in my taskbar and choosing "Close Window".

**Comment by keithsw1111** [comment]
Ok ... so what should we do in this instance? Maybe close xLights? That would seem to be the only sensible course of action as we cant continue without a show directory set.

**Comment by jimswinder** [comment]
That's the problem...It won't allow me to close down xlights...had to shut off my computer...



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
