### ISSUE TITLE
xLights new sequence setup view selection failure

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#1011]
This video demonstrates the problem when trying to select a 'view' different from the default during a new sequence creation.
https://youtu.be/pYY1RHwZitQ

**Comment by AzGilrock** [comment]
I do that all the time so it must be some of factor causing it.

**Comment by keithsw1111** [comment]
It is a bug ... but its not the bug I think you think it is.

I dont think the new sequence dropdown should let you select master view. Master view is a sequence construct and at this point you are creating a sequence and not surprisingly it doesnt have any models in it.

Changing the master view in one sequence has no impact on any other sequence.

Your best approach is to create a new view "MyMasterMasterView" and base new sequences off that.

Meanwhile I think we should take Master View out of the list of available views in the new sequence wizard
