### ISSUE TITLE
6 Ch Realy Board DMX address not receiving data

### ISSUE THREAD

**Issue by DGHayes** [smeighan/xLights#1012]
Have a weird problem I seem to have narrowed down to the layout configuration from xLights. 
Using this board: https://www.facebook.com/photo.php?fbid=10155666655268046&set=gm.1559512484129240&type=3&theater&ifg=1 

I had the start address set to 73 via the dip switches (next address free in my setup) and the board worked fine using the test output from xLights.

Setup two models (it just switches 24V AC out to them via the relay board) and test went fine and added to sequence and it also worked.

Next day after all equipment powered down, these two props didn’t work, nor did they respond to the xLights test function. So, I changed the DMX start address to 128 (have nothing in that range on my setup) reprogramed props for new DMX address (128/129) and all worked again including the sequence output.

Next day same thing happened, not working after shutdown. The board is receiving the data stream and the data light is flashing. Knowing I had data for another model coming out on DMX channel 1 & 2, I simply changed the dip switch address on the relay board to channel 1, and the relays turned on, proving the data steam was OK and the board was getting data.

Next, I changed the models to another DMX channel after resetting the board to address 128, i.e. I set the models to 131 and 132 (any number works here), saved the props, reedited back to the original DMX 128/129 channel, save and run xLight test, and it worked. Also, sequence worked OK after this.

Confirmed this tonight as xSchedule started the show, no relay board working, so did the above procedure, (save models to an unused channel and then back to the correct ones), and xLight test work and just turned on the lights output from xschedule as the show was running and it worked fine.

Not sure why this needs to be reset every day, but hence this post with a strange issue. Logs attached from shortly after the changes to the models and back again tonight.

Thanks in advance,
Dave

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/1534660/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
Looking in your file your networks setup only shows 129 channels configured ... surely this should be more ... in fact I would suggest you just make it 512. I suspect this is your problem but it is impossible to know for sure.

**Comment by DGHayes** [comment]
Hi Keith, I'll set it to 512 and test, but the reson I only have 129, is that I have two x 36 ch Hanson DMX boards (1-32 and 33-72), one 3 ch relay board (not connected) and one 6 ch (128-133) relay board and one DMX smoke/bubble machine 8 channels (100-107). Very simple setup.
Is there a way to capture the data stream (like Ethereal for TCIP packet sniffing)? Using a USB to DMX dongle on Comm port 4.

**Comment by keithsw1111** [comment]
You can download virtual comm port software which has the ability to sniff the data. Product names I dont remember. All of them cost money but have free periods which can give you enough time to troubleshoot.

**Comment by keithsw1111** [comment]
Right ... so its set to 129 ... but you are using up to 133 ... I see a problem.

**Comment by DGHayes** [comment]
True, but only using 128 and 129 (first two relay channels), so hence not set to 133. I'll set to 512 tonight so all are covered and let you know if this fixes the data stream issue.

**Comment by DGHayes** [comment]
Do I need to redo the FSEQ files after the changes to the setup (networks file) Keith?

**Comment by keithsw1111** [comment]
Yes

**Comment by DGHayes** [comment]
Hi Keith,

Have not nutted this one out yet. 

Friday I changed the setup to 512 and the show ran (no redo of the FSEQ file). 

Saturday, I modifed the two show files and the show refused to run both the relay board (128/129) and the DMX smoke machine (100-107) from the scheduler, but the lights test worked and so did the xLights sequencer output, so ended up looping just one show from the sequencer for the night. 

Sunday, deleted and re-added the two show (FSEQ) files to the scheduler, show started but no realy or DMX smoke machine output. Left the scheduler running and turned off the lights output, fired up xLights and used test light function to test the two relay channels 128/129, and they worked (note: did not test the DMX machine output), exited xLights and just turned back on the light output from the scheduler, and both the relay board and DMX smoke machine now worked!  

So from the Sunday test, just turning off the scheduler light output, testing two channels and turning on the light output from scheduler, all worked. Will see what it does tonight with no changes at all.

**Comment by keithsw1111** [comment]
Whenever you have issues you need to run Check Schedule and verify you get a clean bill of health.

In order for your xLights vs xSchedule test to be valid:

1. You should be running on the same machine
2. Both xLights and xSchedule must be using the same show directory ... this is because we look at the xlights_networks.xml to decide what to send out.
3. You must be pointing to the right FSEQ file. FSEQ files are only created when you render all and save a sequence.
4. Clicking on an effect while ouputting to lights is not necessarily a representation of what will be displayed. Render all then play to see what it actually looks like.

We know this works so there is something you are doing but not communicaying which is likely causing the issue.

If you jump into zoom we may be able to see what and help.

**Comment by DGHayes** [comment]
Hi Keith,

1 = Yes it is (default) user home documents
2 = Yes they are
3 = Yes and have re-rendered files
4 = Understand, have done that too

On Zoom meeting now

**Comment by keithsw1111** [comment]
Check sequence is not the same as check schedule. They do different things.

I cant jump in for at least 30 mins now.

**Comment by DGHayes** [comment]
OK, will stay on. Check schedule = Errors: 0. Warnings: 1, warning is No password set on website

**Comment by DGHayes** [comment]
This is the update from the xScheduler tonight. Had set light output to off (as it does not turn off as noted at end of show), show started but relay board (128/129) didn't start. Simply turned off the light output and then back on in xSchedule and the relay board worked. So as you said Keith, resetting the port by turning the output off and on worked.

Will now load the special software revision for data logging you have sent via Dropbox.

**Comment by DGHayes** [comment]
So after applying your custom build of xSchedule (V40) and the map file to the location specified, started the new scheduler, the show resumed as was programmed to start at 7:30 and the relay board didn't work. Again turned off the output to lights in the scheduler and back on, relay board functioned again. 

So if there is a log file you need, please let me know which one? Time is just after 8 in the logs.

**Comment by keithsw1111** [comment]
I need the xSchedule log

**Comment by DGHayes** [comment]
[xLightsProblem_1012.zip](https://github.com/smeighan/xLights/files/1547616/xLightsProblem_1012.zip)
[xSchedule_l4cpp.log](https://github.com/smeighan/xLights/files/1547625/xSchedule_l4cpp.log)

**Comment by DGHayes** [comment]
Log position for new debug is:

2017-12-11 19:58:55,155 8512 log_base [INFO] Version: 2017.40

**Comment by keithsw1111** [comment]
Ok. Need to add some more logging which I will do tonight ... but it wont be later.

**Comment by DGHayes** [comment]
Interesting, not touching the setup came home tonight and the relay board is active. This is after the on/off/on from the prevoiuse day.

**Comment by keithsw1111** [comment]
David ... no word on this for some time. Does that mean we resolved it?

**Comment by DGHayes** [comment]
Hi Keith,
Sorry, been away and only got back last night. The problem seems to be related to opening and closing the USB port. If you (either in xLights and xSchedule) turn the lights on/off/on, the board will work. I haven't upgraded from version 40, where I see you fixed the port not closing in the scheduler in V41. That will be my next test, upgrade to the latest and then try a program change, re-render and set in the scheduler. Once the scheduler is running and the on/off/on is done, it will work until any changes are done.

**Comment by keithsw1111** [comment]
An upgrade and retest would be in order ... let me know how it goes?

**Comment by keithsw1111** [comment]
Can I close this one now?

**Comment by DGHayes** [comment]
Yes please Keith, I have not had time to test as I'm in Coffs looking after my Uncle with a terminal disease. I'll reopen if needed.
