### ISSUE TITLE
xSchedule Mac Crash

### ISSUE THREAD

**Issue by therichardsons** [smeighan/xLights#1018]
Hi everyone... I'm having some trouble with xSchedule crashing as soon as I click "Play Selected".
I'm unable to make it work at all.....

Tried 2017.39 and 2017.40

I'm on a Mac mini with 8gb ram, running 10.11

See error log attached.
Any help would be appreciated!

Thanks

[error message.txt](https://github.com/smeighan/xLights/files/1542176/error.message.txt)

**Comment by keithsw1111** [comment]
Where is the rest of the crash report? This tells me the crash occurred when trying to load the audio ... but that's all I can tell 

PlayListItemFSEQ::LoadAudio()

**Comment by keithsw1111** [comment]
With no further information to help us progress resolution of this problem I am going to have to close it. If you have anything else please attach it and reopen the ticket.
