### ISSUE TITLE
IP Addresses for MultiSync

### ISSUE THREAD

**Issue by gothambeat** [smeighan/xLights#1019]
Would it be possible to maintain a column in XL for the IP address even if it is Multisync.  It is good to see what IP address a prop is on for troubleshooting.  When you upload to the FPP, it overwrites the IP address field with BLANKS when the line item is set to MULTISYNC.   I like the Controller upload option but it keeps overwriting all my IP Addresses.

**Comment by keithsw1111** [comment]
Not easily. We would have to download the configuration and to be honest the FPP guys are telling us they will have an API at some point we can use for this so I am not inclined to invest more in our current approach. Besides if you know the IP address why wouldnt you just unicast to it.

**Comment by gothambeat** [comment]
Keith  Thanks for the feedback.  Some of my units (wireless) act up and bring the network down if I'm using unicast.  I troubleshoot from the FPP.  I'll wait till the api.  Thanks for all you do.

**Comment by keithsw1111** [comment]
With Dan's recent FPP Upload changes I think this is now redundant
