### ISSUE TITLE
Win 7/8.1 issue

### ISSUE THREAD

**Issue by BobinWV** [smeighan/xLights#102]
Have NC 4.02 installed on a Win 7 and Win 8.1 machines.  Aero off on both machines.  Same routine on both machines..On Win 7 all models play in the sequencer tab as well as the preview tab.
On Win 8.1 only one model will play (my mega tree) all others only show a single pixel blinking.
All models play as expected on  the  preview tab.

**Comment by AzGilrock** [comment]
There is a misconception that Aero is the source of our rendering problems and that turning off Aero in Win8 can fix issues.  The real problem is not Aero...it's Desktop Window Management (DWM).  So we still have a rendering problem when DWM is utilized.  I'm pretty sure you're not turning off DWM in Win8. In Win7 DWM is only enabled if you run an Aero theme.  In Win8 DWM is on all the time so turning off Aero in Win8 does nothing to fix our rendering issue.  There are hacks that can turn off DWM in Win8 but it's gets into low level scary stuff for the average user so that's why I'm not recommending those workarounds.  Here's more info on the DWM topic:
https://msdn.microsoft.com/en-us/library/windows/desktop/hh848042(v=vs.85).aspx

**Comment by dkulp** [comment]
Gil,

I just committed some new OpenGL init code for Windows for you to experiment with.   It’s just a start.   For me, if I change the iPixelFormat variable on line 85 to various values, it then displays correctly (un-clipped)  on Windows8.  For me “max” is 44, it auto selects 7.   It displays fine with 9 and 10, (I’ve only tested up to 10)  I haven’t had time to figure out what the differences are between all of them, but I thought I’d let you experiment a bit as well.

I have cub scouts tonight (den leader) so I may not get a chance to look at this for a bit.

Dan



> On Mar 24, 2015, at 1:35 PM, Gil Jones <notifications@github.com> wrote:
> 
> There is a misconception that Aero is the source of our rendering problems and that turning off Aero in Win8 can fix issues. The real problem is not Aero...it's Desktop Window Management (DWM). So we still have a rendering problem when DWM is utilized. I'm pretty sure you're not turning off DWM in Win8. In Win7 DWM is only enabled if you run an Aero theme. In Win8 DWM is on all the time so turning off Aero in Win8 does nothing to fix our rendering issue. There are hacks that can turn off DWM in Win8 but it's gets into low level scary stuff for the average user so that's why I'm not recommending those workarounds. Here's more info on the DWM topic:
> https://msdn.microsoft.com/en-us/library/windows/desktop/hh848042(v=vs.85).aspx
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Daniel Kulp
dan@kulp.com - http://dankulp.com/blog

**Comment by AzGilrock** [comment]
After this and one more change Dan made it appears the OpenGL rendering problem in Win7 Aero and Win8 is FIXED.   We all owe Dan some huge applause for this.

**Comment by BobinWV** [comment]
I am still having the  same problem-

**Comment by dpitts** [comment]
Thanks Dan. You are the man. 

 

David

**Comment by AzGilrock** [comment]
Bobin did you use version 4.0.4?

**Comment by BobinWV** [comment]
sure did.� one model plays and the others have
      single pixels
    
    On 3/24/2015 10:56 PM, Gil Jones wrote:
    
    
      Bobin did you use version 4.0.4?
      �
        Reply to this email directly or view
          it on GitHub.

**Comment by AzGilrock** [comment]
Ok we didn't fix the Model Preview window yet.  Dan fixed the EffectsGrid.  If that works for everyone we can roll the changes over to the other OpenGL windows.

**Comment by BobinWV** [comment]
ok thanks
    
    On 3/24/2015 10:59 PM, Gil Jones wrote:
    
    
      Ok we didn't fix the Model Preview window yet. Dan fixed the
        EffectsGrid. If that works for everyone we can roll the changes
        over to the other OpenGL windows.
      �
        Reply to this email directly or view
          it on GitHub.
