### ISSUE TITLE
Problems with Mac version 41

### ISSUE THREAD

**Issue by Michaelillingby** [smeighan/xLights#1023]
Just downloaded the new 41 to try tonight, tried to remake a sequence that I had just finished in 40. when I went to IMPORT EFFECT, and then tried to load my MAPPING file, only the first node of each thing loaded, making it essentially useless. I five different ways, not working. Is this a known bug? I will stick with 40 until it's fixed I suppose

**Comment by keithsw1111** [comment]
Its not a known bug. Can you send us something so we can reproduce it.

**Comment by Michaelillingby** [comment]
is this what you mean, or do you want a video of it happening?

I had to ZIP it as it was too large

**Comment by keithsw1111** [comment]
I dont see an attachment. Best thing to do is put it in a drop box and PM us a link. A video of what you are doing would also help.

**Comment by keithsw1111** [comment]
I believe this has been fixed.

**Comment by Michaelillingby** [comment]
Great l will Try lT
