### ISSUE TITLE
webinterface freezes partway through serving bootstrap.min.css

### ISSUE THREAD

**Issue by rsandoz** [smeighan/xLights#1027]
I am on ubuntu 17.10.
I can render the webinterface locally from the ubuntu desktop, but when I tried to access it externally from my laptop in window 10 and chrome, it gets stuck on a blank page (spinning).  When I view source, I clicked all the linked items and all loaded except bootstrap.min.css which renders about 80% of the file then gets stuck (spinning).  I worked around this issue by splitting the file then editing index.html and replacing the reference:
```
<link href="css/bootstrap.min.css" rel="stylesheet">
```
with:
```
    <link href="css/bootstrap.min1.css" rel="stylesheet">
    <link href="css/bootstrap.min2.css" rel="stylesheet">

**Comment by AzGilrock** [comment]
Ok I'm lost as to what web interface you are talking about.  Is this for xSchedule?  xLights doesn't have a web interface.

**Comment by rsandoz** [comment]
yes, sorry, xSchedule

**Comment by keithsw1111** [comment]
Is this still an issue ... i suspect it is now fixed.
