### ISSUE TITLE
App Crashed Now Cant Edit Sequence

### ISSUE THREAD

**Issue by chrisgeb** [smeighan/xLights#1028]
I am getting a message now of Internal Error:  Unable to find: ID_CHOICE_Text_Font
[xLights_dbgrpt-784-20171214T184339.zip](https://github.com/smeighan/xLights/files/1561146/xLights_dbgrpt-784-20171214T184339.zip)

**Comment by AzGilrock** [comment]
So what version of xLights are you using?  The field with the ID of ID_CHOICE_Text_Font was just added into version 2017.30  Sep  29, 2017.

**Comment by computergeek1507** [comment]
The log file says 2017.6

**Comment by AzGilrock** [comment]
Actually the log file shows he upgraded from 2017.6 to 2017.41 sometime between 17:48 and 18:22 on 12/14.   So you created a sequence under version 2017.41 and then somehow tried to open it under version 2017.6.

**Comment by chrisgeb** [comment]
That’s a likely statement however not sure how both versions still exist on my computer.  I will double check when I get home.  Thank you all  for all your hard work!  

Thanks,
Chris Gebhardt

**Comment by AzGilrock** [comment]
Pretty sure the only way to get this message is to open a newer sequence in an older version of xLights.  Reopen if you find it still an issue.
