### ISSUE TITLE
Model preview

### ISSUE THREAD

**Issue by jcmarksafb** [smeighan/xLights#103]
Model preview only has one pixel in it. When I have the output to lights box checked, my actual display acts like the model preview should, and will only display the model selected  when you click play.

**Comment by AzGilrock** [comment]
Are you running Windows 8?  If so this is really a duplicate of issue #102 that was written a couple hours ago.  I've got some detail there you might be interested in.

**Comment by jcmarksafb** [comment]
no, win 7 64 pro, bluzvik and i are having the same problem with the model preview only one pixel showing
 


     On Tuesday, March 24, 2015 12:41 PM, Gil Jones <notifications@github.com> wrote:
   

 Are you running Windows 8? If so this is really a duplicate of issue #102 that was written a couple hours ago. I've got some detail there you might be interested in.—

**Comment by AzGilrock** [comment]
Yeah so #95 covers this no reason to open another one.

**Comment by jcmarksafb** [comment]
ok, no problem, just trying to help. I know you guys are working as hard as you can and it is a great program. I'm really glad you released it so we could see it and play with it. Thank all of you very much.John
 


     On Tuesday, March 24, 2015 1:01 PM, Gil Jones <notifications@github.com> wrote:
   

 Yeah so #95 covers this no reason to open another one.—

**Comment by AzGilrock** [comment]
If someone is still seeing this issue can you tell us what type of model it is and what effect you are dropping on it that shows as a single pixel?  I thought I had recreated this but it turned out I used the wrong settings for an effect and is caused it to show as a single pixel.

**Comment by stevegiron** [comment]
Hello, I'm helping sort the issues and determine which issues are still valid. 
As of May-14 we are version 4.0.31. Is this issue still occurring?

**Comment by AzGilrock** [comment]
Closing.  I don't believe this issue exists any longer.
