### ISSUE TITLE
Gradient stops working on "Bars" effect when using "Additive" blending

### ISSUE THREAD

**Issue by burnt-past** [smeighan/xLights#1032]
Gradient becomes inactive when using additive mixing with the bars effect.

**Comment by stevegiron** [comment]
In verifying this, it gradient appears to go inactive with Top-Bottom, Average, Left-Right, Min,Max, Subtractive as well.

**Comment by AzGilrock** [comment]
I added the gradient feature but I'm not sure how the blending mode can have any effect because blending is done post render.  Inside the render routine for Bars that I modified we don't even know the blend mode.

**Comment by AzGilrock** [comment]
Actually I might see where it could happen.  Would it be correct that it works in any blend mode that does Alpha blending?  Cause it looks like maybe the gradient color blending is being done one line too late for non-alpha blends cause the color has already been converted to an HSV value.

**Comment by burnt-past** [comment]
This is a current issue, that has been confirmed. Why was this closed?

After rendered this still existed.

**Comment by stevegiron** [comment]
Click on the C7ED871 link to see the code checkin  and comment for the fix. 
![image](https://user-images.githubusercontent.com/10568498/34088707-e667bf2a-e35f-11e7-849f-78ccc4d248e9.png)

**Comment by burnt-past** [comment]
Copy, sorry for the misunderstanding.

**Comment by AzGilrock** [comment]
Yep when we checkin code if we put "#Fixes XYZ" the tool will automatically close the issue that we said was fixed by the checkin.
