### ISSUE TITLE
fseq file huge

### ISSUE THREAD

**Issue by medic6578** [smeighan/xLights#1034]
Hi, Jay here. I have a sequence of harry potter the fseq file is normally about 582 megs. I went to save it today and xLights crashed attached is the crash file and the fseq file. After restarting xLights I went to save the file and the fseq file is now 2.5 gigabytes and will not play on my  FPP. I went and updated xLights to version .
[xLights_dbgrpt-12228-20171218T143012.zip](https://github.com/smeighan/xLights/files/1569850/xLights_dbgrpt-12228-20171218T143012.zip)
[xLights_dbgrpt-12228-20171218T143012.zip](https://github.com/smeighan/xLights/files/1569853/xLights_dbgrpt-12228-20171218T143012.zip)

42 and it still does the same thing.

**Comment by keithsw1111** [comment]
Run check sequence.

**Comment by keithsw1111** [comment]
Check sequence shows some very serious errors ... it also explains why the file is so large ...
    WARN: Model 'Arch 1' starts at channel 3055 leaving a block of 2238 of unused channels between this and the prior model 'Pumpkin 1'.
    WARN: Model 'Mini Tree 1' starts at channel 15000 leaving a block of 6984 of unused channels between this and the prior model 'Window Right'.
    WARN: Model 'Matrix' starts at channel 31265 leaving a block of 11190 of unused channels between this and the prior model 'Mega Tree'.
    ERR: Model 'Spot 3' starts at channel 328001 leaving a block of 291936 of unused channels between this and the prior model 'Matrix'.

Large blocks of unused channels ... and yours are huge ... inflate the size of the FSEQ. Fix that and you will be good.
