### ISSUE TITLE
Upgrading to 2017.44

### ISSUE THREAD

**Issue by Roger55119** [smeighan/xLights#1039]
Ever since I did the update the show runs but the audio does NOT!!! I tried rendering and reloading but still nothing.It does run fine on xlights....any help would be great

**Comment by keithsw1111** [comment]
We need to see your xSchedule logs.

**Comment by Roger55119** [comment]
[xSchedule_l4cpp.pdf](https://github.com/smeighan/xLights/files/1577766/xSchedule_l4cpp.pdf)

**Comment by Roger55119** [comment]
sorry thought i included them.

**Comment by keithsw1111** [comment]
There are no audio related errors in the log ... but it does look like you have your schedules setup in quite a confusing manner. It seems that you have 2 active playlists and because of that I suspect the one without audio is overriding the one with audio. Should one maybe be a background and thus not scheduled at all?

**Comment by Roger55119** [comment]
It did not over ride before. but i will clear all sched. and start over.... also i did do a light reduction and it still says 100% at the top. Is this normal?

**Comment by keithsw1111** [comment]
You mean an output process ... then yes.

Likely your schedules all have the same priority. The one you want to play has to have a priority that is a larger number than anything else. If the priorities are the same then who wins is not guaranteed.

**Comment by Roger55119** [comment]
thanks for looking into this. it was a bit frustrating.

**Comment by keithsw1111** [comment]
So it worked?

**Comment by Roger55119** [comment]
doing it now I will Let you know in a min.

**Comment by Roger55119** [comment]
Is there a way to select a specific audio card so the xlights scheduler can run on the USB  fm transmitter and the computer can still use it own sound card for normal day to day stuff?

**Comment by Roger55119** [comment]
It did NOT work ....runs the lights but no sound...you can look if you want

**Comment by keithsw1111** [comment]
What if you stop all and just play it. Could it be the audio is going to the wrong device? Set your speakers to default and restart scheduler

**Comment by Roger55119** [comment]
tried that also and now again no output at all

**Comment by Roger55119** [comment]
and if i open it in xlights it plays fine both ways..fm or computer

**Comment by keithsw1111** [comment]
I may be able to hop into zoom in about 2 hours to take a look

**Comment by Roger55119** [comment]
do you think it would be worth it to uninstall and then reinstall

**Comment by keithsw1111** [comment]
no

**Comment by Roger55119** [comment]
ok thought i would check....i will gladly take the help when you are able..

**Comment by keithsw1111** [comment]
Will be in zoom in 10 mins

**Comment by keithsw1111** [comment]
So the problem here is the feature that lets you choose your audio device is not working ... while the list displays the call to open the device (as opposed to the default device) just does not seem to work.

**Comment by Roger55119** [comment]
thanks again for looking!!!Happy holidays
