### ISSUE TITLE
Too many play buttons

### ISSUE THREAD

**Issue by jcmarksafb** [smeighan/xLights#104]
In the preview tab, there are two play buttons, I wasted a lot of time clicking on the play button at the top next to the green gear not realizing there was another play button. Minor problem but can cause a first time user a lot of grief.

**Comment by bluzervic** [comment]
I think this is probably fine. The problem that JC seemed to have is when he was in the Preview tab.

Preview Tab:

hitting play underneath the Open button just above the select model groups button did not have the same results when hitting the play button up in the tool bar as far as what it was displaying in the preview.

Probably what needs to happen is that when the Preview tab is selected, the play button in the tool bar should check for it and if it is the current tab selected then the toolbar play button should work the same routine the Play button in the Preview button is running.

**Comment by AzGilrock** [comment]
What I really wanted was the preview to display in place of the sequencer grid and then the waveform and timeline could be used to control playback for the large preview.  All the stuff you do on the side could be moved to side panels.  So basically it would be like a Perspective change.   But there isn't developer agreement on this idea.  Also with the apparent issue of the AuiManager causing rendering issues with DWM it would just bring the Preview into that world of problems.

**Comment by stevegiron** [comment]
Only one set of play buttons exists now.
