### ISSUE TITLE
Enhancement Request (Easy One lol)

### ISSUE THREAD

**Issue by n19bmw** [smeighan/xLights#1041]
Can we please add the ability in the Candycane model to pick the number of rows in the cane shape. That way we can easily set up a Corocane from Holiday coro or Boscoyo without using a custom model.  Thanks

**Comment by AzGilrock** [comment]
The nodes probably wouldn't align the same as the ones you bought.  Its best to just use a custom model and most of these are already created so you don't even have to do any work.

**Comment by keithsw1111** [comment]
I don’t think this makes sense. Too many variables and between a custom model and appropriate submodels all of which can be shared this is a bunch of code to maintain for no incremental value.
