### ISSUE TITLE
Playlist immediately played if scheduled in next year

### ISSUE THREAD

**Issue by DLBeckwith** [smeighan/xLights#1048]
I schedule a playlist to start 1/1/2018 and end 1/1/2018 but it gets scheduled immediately.  This happens to any date next year.

Start Date 1/1/2018
End Date: 1/2/2018
Every Year unchecked
On Time: 00:01:30
Off Time: 23:59:00
Loop checked
Priority: 5
Windows

**Comment by keithsw1111** [comment]
This will be fixed in 2018.1
