### ISSUE TITLE
Xscheduler crashing

### ISSUE THREAD

**Issue by Djnathan1983** [smeighan/xLights#1050]
my scheduler crashed last night at 9pm when the show is supposed to stop and switch to the night sequence. has been working fine since November 24. I downloaded newest version and no luck. had to change my MacBook clock to 2 hours after the show ends to be able to open again. only way to keep from crashing was to change the start date to dec1 instead of nov 24. now this morning its crashed again. i will attach the log.
[xSchedule_dbgrpt-1509-20171229T073717.zip](https://github.com/smeighan/xLights/files/1593179/xSchedule_dbgrpt-1509-20171229T073717.zip)

**Comment by Djnathan1983** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<report version="1.0" kind="user">
  <system description="macOS Sierra Version 10.12.6 (Build 16G1114)"/>
  <stack>
    <frame level="0" function="handleCrash(void*) " offset="00000000"/>
    <frame level="1" function="wxFatalSignalHandler " offset="00000000"/>
    <frame level="2" function="_sigtramp " offset="00000000"/>
    <frame level="3" function="0x00000001 " offset="00000000"/>
    <frame level="4" function="wxDateTime::Set(unsigned short, wxDateTime::Month, int, unsigned short, unsigned short, unsigned short, unsigned short) " offset="00000000"/>
    <frame level="5" function="wxDateTime::SetYear(int) " offset="00000000"/>
    <frame level="6" function="Schedule::CheckActiveAt(wxDateTime const&amp;) " offset="00000000"/>
    <frame level="7" function="Schedule::GetNextTriggerTime() " offset="00000000"/>
    <frame level="8" function="xScheduleFrame::GetScheduleName(Schedule*, std::__1::list&lt;RunningSchedule*, std::__1::allocator&lt;RunningSchedule*&gt; &gt; const&amp;) const " offset="00000000"/>
    <frame level="9" function="xScheduleFrame::UpdateTree() const " offset="00000000"/>
    <frame level="10" function="xScheduleFrame::LoadSchedule() " offset="00000000"/>
    <frame level="11" function="xScheduleFrame::xScheduleFrame(wxWindow*, std::__1::basic_string&lt;char, std::__1::char_traits&lt;char&gt;, std::__1::allocator&lt;char&gt; &gt; const&amp;, std::__1::basic_string&lt;char, std::__1::char_traits&lt;char&gt;, std::__1::allocator&lt;char&gt; &gt; const&amp;, int) " offset="00000000"/>
    <frame level="12" function="xScheduleApp::OnInit() " offset="00000000"/>
    <frame level="13" function="wxApp::CallOnInit() " offset="00000000"/>
    <frame level="14" function="wxEntry(int&amp;, wchar_t**) " offset="00000000"/>
    <frame level="15" function="main " offset="00000000"/>
    <frame level="16" function="start " offset="00000000"/>
    <frame level="17" function="0x00000001 " offset="00000000"/>
  </stack>
</report>

**Comment by Djnathan1983** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<report version="1.0" kind="user">
  <system description="macOS Sierra Version 10.12.6 (Build 16G1114)"/>
  <stack>
    <frame level="0" function="handleCrash(void*) " offset="00000000"/>
    <frame level="1" function="wxFatalSignalHandler " offset="00000000"/>
    <frame level="2" function="_sigtramp " offset="00000000"/>
    <frame level="3" function="0x00000001 " offset="00000000"/>
    <frame level="4" function="wxDateTime::Set(unsigned short, wxDateTime::Month, int, unsigned short, unsigned short, unsigned short, unsigned short) " offset="00000000"/>
    <frame level="5" function="wxDateTime::SetYear(int) " offset="00000000"/>
    <frame level="6" function="Schedule::CheckActiveAt(wxDateTime const&amp;) " offset="00000000"/>
    <frame level="7" function="Schedule::GetNextTriggerTime() " offset="00000000"/>
    <frame level="8" function="xScheduleFrame::GetScheduleName(Schedule*, std::__1::list&lt;RunningSchedule*, std::__1::allocator&lt;RunningSchedule*&gt; &gt; const&amp;) const " offset="00000000"/>
    <frame level="9" function="xScheduleFrame::UpdateTree() const " offset="00000000"/>
    <frame level="10" function="xScheduleFrame::LoadSchedule() " offset="00000000"/>
    <frame level="11" function="xScheduleFrame::xScheduleFrame(wxWindow*, std::__1::basic_string&lt;char, std::__1::char_traits&lt;char&gt;, std::__1::allocator&lt;char&gt; &gt; const&amp;, std::__1::basic_string&lt;char, std::__1::char_traits&lt;char&gt;, std::__1::allocator&lt;char&gt; &gt; const&amp;, int) " offset="00000000"/>
    <frame level="12" function="xScheduleApp::OnInit() " offset="00000000"/>
    <frame level="13" function="wxApp::CallOnInit() " offset="00000000"/>
    <frame level="14" function="wxEntry(int&amp;, wchar_t**) " offset="00000000"/>
    <frame level="15" function="main " offset="00000000"/>
    <frame level="16" function="start " offset="00000000"/>
    <frame level="17" function="0x00000001 " offset="00000000"/>
  </stack>
</report>

**Comment by Djnathan1983** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<report version="1.0" kind="user">
  <system description="macOS Sierra Version 10.12.6 (Build 16G1114)"/>
  <stack>
    <frame level="0" function="handleCrash(void*) " offset="00000000"/>
    <frame level="1" function="wxFatalSignalHandler " offset="00000000"/>
    <frame level="2" function="_sigtramp " offset="00000000"/>
    <frame level="3" function="0x00000001 " offset="00000000"/>
    <frame level="4" function="wxDateTime::Set(unsigned short, wxDateTime::Month, int, unsigned short, unsigned short, unsigned short, unsigned short) " offset="00000000"/>
    <frame level="5" function="wxDateTime::SetYear(int) " offset="00000000"/>
    <frame level="6" function="Schedule::CheckActiveAt(wxDateTime const&amp;) " offset="00000000"/>
    <frame level="7" function="Schedule::GetNextTriggerTime() " offset="00000000"/>
    <frame level="8" function="xScheduleFrame::GetScheduleName(Schedule*, std::__1::list&lt;RunningSchedule*, std::__1::allocator&lt;RunningSchedule*&gt; &gt; const&amp;) const " offset="00000000"/>
    <frame level="9" function="xScheduleFrame::UpdateTree() const " offset="00000000"/>
    <frame level="10" function="xScheduleFrame::LoadSchedule() " offset="00000000"/>
    <frame level="11" function="xScheduleFrame::xScheduleFrame(wxWindow*, std::__1::basic_string&lt;char, std::__1::char_traits&lt;char&gt;, std::__1::allocator&lt;char&gt; &gt; const&amp;, std::__1::basic_string&lt;char, std::__1::char_traits&lt;char&gt;, std::__1::allocator&lt;char&gt; &gt; const&amp;, int) " offset="00000000"/>
    <frame level="12" function="xScheduleApp::OnInit() " offset="00000000"/>
    <frame level="13" function="wxApp::CallOnInit() " offset="00000000"/>
    <frame level="14" function="wxEntry(int&amp;, wchar_t**) " offset="00000000"/>
    <frame level="15" function="main " offset="00000000"/>
    <frame level="16" function="start " offset="00000000"/>
    <frame level="17" function="0x00000001 " offset="00000000"/>
  </stack>
</report>

**Comment by keithsw1111** [comment]
I think I have fixed this for 2018.1. Problem was I was setting the day before the month ... so the 31st of November did not work.
