### ISSUE TITLE
Enhancement: Config - export/import

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#1051]
Similar to the package log files, create a Export xLights Config option. The intent will be for users to easily export, import configurations from PC to PC or from user to user.   Granted most mid level and above users know which files to xfer over.

**Comment by AzGilrock** [comment]
What files need to be included that aren't already part of Package Log Files or Package Sequence?

**Comment by stevegiron** [comment]
xlights_keybindings.xml

**Comment by AzGilrock** [comment]
Yeah I know personally I don't really want the keys mapped the way someone else did it but I guess it could be added to the current packaging. See what Keith thinks.

**Comment by stevegiron** [comment]
The thought behind this was to provide a method for n00bs to easily get an xlights config from one PC to another since most households have more than one PC. It would be nice to answer the question of "How do I get my config/models from one PC to another?"  With.. just export your config and import the config under the Tools menu.

**Comment by AzGilrock** [comment]
But if you're dealing with people that can't even do a simple copy of a directory I'm not sure anything will help.
