### ISSUE TITLE
Enhancement: Auto populate face file names

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#1057]
Once the first face mouth shape is selected for AI, is it possible to search the same folder for the same filenames with the appropriate file ending and have them fill in.

![image](https://user-images.githubusercontent.com/10568498/34549353-ea65e39e-f0bc-11e7-8d7c-b8973edbcb68.png)

![image](https://user-images.githubusercontent.com/10568498/34549349-deccb206-f0bc-11e7-9247-e07b24ab6255.png)

**Comment by keithsw1111** [comment]
Implemented.
