### ISSUE TITLE
layout print house an error dialog show when canceled

### ISSUE THREAD

**Issue by cp16net** [smeighan/xLights#1058]
So i was testing out the new functionality and when i cancel the print i still get an error dialog saying "Image capture Error: Error capturing preview image" 
If i canceled the print then i would expect it should not have shown an error.

**Comment by cp16net** [comment]
i tried a `printer.GetAbort()` to fix this but it never returned `true` for some reason only `false`.

**Comment by keithsw1111** [comment]
Fixed
