### ISSUE TITLE
4.0.4 3-24 Crash every time I save this sequence

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#106]
The sequence at http://www.stevesimages.com/xl4/1-UTF.xml

Crashes seemed to happen going from 4.0 4/20 to 4/23 version OR adding Morph effect to the megatree model.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	xLights.exe
  Application Version:	0.0.0.0
  Application Timestamp:	55121280
  Fault Module Name:	StackHash_a21a
  Fault Module Version:	6.1.7601.18229
  Fault Module Timestamp:	51fb1072
  Exception Code:	c0000374
  Exception Offset:	000ce753
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	a21a
  Additional Information 2:	a21a22a8b06c1381620bae2f9addb085
  Additional Information 3:	06f6
  Additional Information 4:	06f6a6caaa505e9d10badde6d5cd59f2

**Comment by AzGilrock** [comment]
I don't think I had any copies of your xlights_networks.xml or rgbeffects.xml files.  Without those nobody can open your sequence without it asking to delete all the elements.

**Comment by stevegiron** [comment]
The xml file is in the same folder as the sequence, and other informational items from previous tickets.
http://www.stevesimages.com/xl4

**Comment by stevegiron** [comment]
Not crashing with 4.0.5. Closing ticket.
