### ISSUE TITLE
Select Options for Bulk Edit

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#1061]
Now that there is bulk editing for more than just the colors, having the ability to select multiple effects without having to either click on them individually or draw a box around them could be useful.  

The ones that jump to mind would be:
- Select all Effects
- Select previously selected effects (good if you changed something, then accidentally clicked elsewhere and deselected it)
- Select all effects on a model or group
- Invert Selection
- Select all effects of a certain type

**Comment by keithsw1111** [comment]
1,3 and 5 make sense to me. 1 and 5 were already on my list.

**Comment by deplanche** [comment]
Awesome, thanks.

#2 was something that I have found useful in other programs when I accidentally deselect everything, and want to go back to what I had selected.  Mainly when I have clicked on several things to get that, and don't want to have to do that again.  With the others, it might not be all that useful. Same with #4.

Thanks again.

**Comment by computergeek1507** [comment]
1 has been implemented, 3 has been partially implemented. 5 is next on my todo list.

**Comment by keithsw1111** [comment]
I am keen that for number 5 we use a panel or something that lets you select all of multiple effect types ... not just all of one effect. In fact something that acted like a filter which hid non matching effects such that you could then click and drag the effects displayed would be useful.
Interestingly this is one are where the Vixen team has done some interesting work. I have watched the video but not actually used it and I am not saying what they have done is the ideal but it may give you ideas. https://www.dropbox.com/s/vrok7b9v7l1xx0h/New%20Features.mp4?dl=0

**Comment by keithsw1111** [comment]
Jon I think this is about as done as it is going to be ... can I close this.

**Comment by deplanche** [comment]
Yes.  Thanks for adding it.
