### ISSUE TITLE
2018.1 Layout Tab Preview dropdown - must lose focus to change value

### ISSUE THREAD

**Issue by mararunr** [smeighan/xLights#1064]
Preface - my layout is 300+ models (and numerous submodels to those) as well as 60+ groups.

In 2018.1 Layout Tab, when trying to use the Preview dropdown box, I have to click on the Setup Tab or Sequencer tab (or some other program whether by clicking or simple alt-tab) for the selection to take effect.  This includes create new preview.  You can tell it has to do with losing focus because the second you switch away in any manner, the selection takes effect.  network and rgbeffects in link below

https://1drv.ms/u/s!AqnznLfBvV_QhNg06erCbOKiISAomg
https://1drv.ms/u/s!AqnznLfBvV_QhNg16D1gWmNeh6nF4Q

For a little background, I'm trying to modify my complete Christmas 2018 layout to become my Halloween layout (straight copy from Christmas folder to Halloween folder then slowly replacing Christmas elements with Halloween elements while trying to keep as much of Christmas as possible to eliminate transition work).
Yes I know the channels are currently messed up but I don't fix the channel assignments until all the models are placed (less work even though I have to deal with the pop-ups constantly - I used to fix the channel assignments as I went but it actually ended up being more work as I moved things around until I got to final layout.  Now I just leave channel assignment fixing to the very last.)

Hope this helps.  Since I know how to work around it, it's just a pain not a broke :-)  Thank you all for everything you do (and yes I hope to be more active this year).

Lastly, if this is just user error, I do apologize for any inconvenience.

**Comment by AzGilrock** [comment]
Yep someone reported this on the forum.  The only version I can see this in is if I download the official 2018.1 build Sean compiled.  All the builds that Keith and I have built since then don't show the problem so we kinda just need Sean to build again and see if it goes away.

**Comment by mararunr** [comment]
Thank you Gil

**Comment by mararunr** [comment]
Just so you know, the issue existed in 2017.45 as well.  Went back to 2017.44 and layout tab preview dropdown works correctly.  (I am referring to the 64 bit Windows version of xLights.)

**Comment by AzGilrock** [comment]
Yeah I don't even know how you could cause that behavior in code even if we wanted to.

**Comment by keithsw1111** [comment]
It has to be sean's build environment doesnt it?

**Comment by AzGilrock** [comment]
I'd say lets make sure he does a full clean before next rebuild.

**Comment by AzGilrock** [comment]
That could be buried in the wxWidgets.dll. Might have to get him to rebuild that.

**Comment by keithsw1111** [comment]
I believe this was fixed in 2018.2
