### ISSUE TITLE
RGB Sub models default colors

### ISSUE THREAD

**Issue by JMHaro** [smeighan/xLights#1068]
Hi, I had just discussed this on the zoom conference and it was recommended that I bring this up as a possible enhancement.  Here is my back story for why I'm making this request.

I have some different wire frame displays that are currently using leds.  Either the leds have color caps on them or they are tinted leds to produce a fixed color.  For example one of my props is a drummer that I currently use 7 separate channels on it.  Body, mouth open, mouth closed, each arm either in up or down positions.  I want to convert this over to pixels to get away from the AC controllers running them.

My big issue on converting it to pixels, is that different parts of the body are lit in different colors.  See attached image.  What I would like to be able to do is create sub models for the different parts that certain colors.  But when I want the over all drummer to be lit, I would just like to use an ON effect to turn it on and all the sub models should know their correct colors to be used.  Same with the arms (which consists of 2 different colors, one for arm and one for the hand and sticks).  When I want to move the arm up or down, it would be nice to be able to have to just set an ON effect for that arm position desired instead of having to set two separate ON effects for the different colors needed.  These drummers I have their arms move a lot with the drum beats of several songs so it would be a pain to have to do the two color settings for every single arm movement.

I've got a crystal angle that also uses white for most of it's body but has some highlights of yellow in the horn, hair, halo, and skirt highlights.  This would be another one that would be great to use this capability.

I wold appreciate if this might be considered for an enhancement, because I really don't want to convert these items over to pixels until I can do something like this.  I appreciate the possible consideration.  If there is someway to already do this, I would appreciate find out how also, since no one else on the zoom conference knew if it could be done.  (Don't know why the image is coming over sideways).
![img_1620](https://user-images.githubusercontent.com/3945942/34806934-775c6e24-f64b-11e7-8a47-7d289e59019c.JPG)

**Comment by keithsw1111** [comment]
Have you considered model states and the state effect. It likely could do everything you are asking for.

**Comment by JMHaro** [comment]
No I haven't, haven't heard of that.  I'll try doing some searches to see see if I can find out how to use it.  Thank you.

**Comment by AzGilrock** [comment]
Yep using State effect is the way the accomplish this.
