### ISSUE TITLE
xLights 2017.45+ versions crash when changing Start channel in Layout tab to be circular or duplicate

### ISSUE THREAD

**Issue by Vlad-Star** [smeighan/xLights#1077]
![xlights_2017_45_screenshot](https://user-images.githubusercontent.com/19923088/35122015-6c1308ea-fc6b-11e7-921e-46015a62c981.jpg)
![xlights_2017_44_screenshot](https://user-images.githubusercontent.com/19923088/35122016-6c219ed2-fc6b-11e7-9725-999110a8fce0.jpg)

See attached screenshots. In layout tab, when I change "Star #N" models to have their start channel as ">Star #2:1", 2017.44 version behaves as expected and shows duplicates, 2017.45 and all further versions crash.

Please, fix.

**Comment by AzGilrock** [comment]
Can you do a Tools -> Package Sequence and post the zip file?  That will give us an easy way to be already in position to reproduce the problem.  Have the layout in the state just before and then tell us which model to change to cause the problem.

**Comment by Vlad-Star** [comment]
[xLights_bug_1077.zip](https://github.com/smeighan/xLights/files/1644668/xLights_bug_1077.zip)

Layout tab -> "Star #2" model, change "Start Channel" field to ">Star #2:1"
Doesn't cause issues on 2017.44, but crashes 2017.45 and all further versions, tested up to 2018.2

**Comment by keithsw1111** [comment]
Fixed in .3
