### ISSUE TITLE
xLights Warning Window 

### ISSUE THREAD

**Issue by CFOLMichelle** [smeighan/xLights#1081]
I keep this warning when xLights opens, when I open new sequences, or make any changes in xLights.  We do not have a duplicate "Joe" in that file path that I can see.  Anything I can do to make this warning stop popping up?

![screen shot 2018-01-23 at 10 34 18 am](https://user-images.githubusercontent.com/35736312/35284545-1b462a66-0029-11e8-88af-82adacd48e22.png)

**Comment by AzGilrock** [comment]
Strange I did a search for the word "appears" in GitHub and can't find it used in any xLights messages.  Is that details button expanded?

**Comment by stevegiron** [comment]
and "xLights" is not punctuated correctly in the dialogue box too!

**Comment by CFOLMichelle** [comment]
Here is a picture of the expanded window.  All the text is to much to fit so I will copy it and paste it in as well.
![screen shot 2018-01-23 at 12 10 55 pm](https://user-images.githubusercontent.com/35736312/35289917-b4cf196a-0036-11e8-820f-fd8782db760f.png)

**Comment by CFOLMichelle** [comment]
Sorry hit the wrong button :)   Here is the copied text.

12:09:50: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 87: key 'Joe' was first found at line 85.
12:09:50: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:50: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 88: key 'Joe' was first found at line 85.
12:09:50: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:50: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 89: key 'Joe' was first found at line 85.
12:09:50: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:50: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 90: key 'Joe' was first found at line 85.
12:09:50: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:50: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 91: key 'Joe' was first found at line 85.
12:09:50: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:50: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 87: key 'Joe' was first found at line 85.
12:09:50: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:50: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 88: key 'Joe' was first found at line 85.
12:09:50: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:50: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 89: key 'Joe' was first found at line 85.
12:09:50: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:50: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 90: key 'Joe' was first found at line 85.
12:09:50: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:50: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 91: key 'Joe' was first found at line 85.
12:09:50: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 87: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 88: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 89: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 90: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 91: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 87: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 88: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 89: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 90: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 91: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 87: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 88: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 89: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 90: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 91: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 87: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 88: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 89: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 90: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 91: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 87: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 88: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 89: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 90: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'
12:09:51: file '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences', line 91: key 'Joe' was first found at line 85.
12:09:51: entry 'Joe' appears more than once in group '/Users/CFOL/Desktop/CFOL/Custom Set Ups'

**Comment by AzGilrock** [comment]
I have no idea some weird Mac stuff going on.  I've never heard of that "Bookmarks Preferences" area.  What is "Custom Set Ups" is that your show folder?

**Comment by CFOLMichelle** [comment]
Yes the custom set ups is the folder I use for sequences and lyric tracks I do for others.  Inside the custom set up folder is a show folder for each client.  I have looked all through the folder and can not find two Joe’s in there.  I have been ignoring the warning but it’s popping up more since the new releases.

**Comment by dkulp** [comment]
Can you delete the  '/Users/CFOL/Library/Preferences/xLights-Bookmarks Preferences' file and see if that makes it go away?

**Comment by CFOLMichelle** [comment]
I’m not home at the moment but I can try when we get back home and let you know.

**Comment by CFOLMichelle** [comment]
I can't find that file anywhere.

**Comment by kppankratz** [comment]
Under the Go menu (Finder) hold down the Option Key and the Library folder option will appear.  Click on that to open the hidden Library folder.  You should be able to navigate and find that file then.

**Comment by CFOLMichelle** [comment]
That worked!  Thanks Kevin for telling me how to get into the hidden folder.  No more warning popping up.
