### ISSUE TITLE
xLights 18.3 crash - Appears to be DMXModel with defined channels outside # specified

### ISSUE THREAD

**Issue by Charle2** [smeighan/xLights#1083]
I'm new to xLights and completed setup and loaded home image for layout. I started creating models and xLights 18.3 crashed. It keeps on crashing whenever I open it. Herewith my debug report for the first and last times it crashed. 
[xLights_dbgrpt-340-20180124T143509.zip](https://github.com/smeighan/xLights/files/1661663/xLights_dbgrpt-340-20180124T143509.zip)
[xLights_dbgrpt-6784-20180124T145740.zip](https://github.com/smeighan/xLights/files/1661664/xLights_dbgrpt-6784-20180124T145740.zip)

your assistance would be appreciated.

**Comment by AzGilrock** [comment]
You appear to be using the Flood model.  Something is crashing in its draw routine.  I just added that last week so it is brand new untested code that's crashing.  I'll have to try to use your file to reproduce the problem.

**Comment by Charle2** [comment]
Thanks. I got to the same conclusion. I've removed the layout file and restarted a new layout. The moment I added the DMX Flood model it crashed. See screen shot attached. Is there any other model that could be used for a RGB Flood light?
![xlights dmx crash](https://user-images.githubusercontent.com/35782062/35358081-15717198-011b-11e8-9354-11a90785c344.jpg)

**Comment by AzGilrock** [comment]
Well I see one problem in the screenshot.  You allocated the Blue Channel to channel 4 but you only allocated 3 channels to the model.  I'll have to add code to protect against you violating the total channels available would be my guess.

**Comment by Charle2** [comment]
Thank you for picking that up. I started the layout from scratch and added the DMX Flood model (suppose to start at channel 2) with three channesl RGB and saved without any issues. 

My luck to pick a bug on my first attempt to setup xLights...lol.  Any suggestions on souces with info on how to import Vixen 2 into Xlights?

Thank you again for your quick response.

**Comment by AzGilrock** [comment]
Yeah generally inside a model everything is referenced from 1 when it comes to channels.  That way you can make several copies of the model and they all work as an offset from the start channel you define.

I'd start with videos.xlights.org and do search term for Vixen.

**Comment by AzGilrock** [comment]
Just checked in a fix for this tonight.
