### ISSUE TITLE
"Tools -> Check Sequence" erroneously detect broadcast addresses

### ISSUE THREAD

**Issue by Vlad-Star** [smeighan/xLights#1084]
When I run "Tools" -> "Check sequence", I am getting the following errors. 
172.16.x.x are not broadcast, but completely valid regular IP addresses of my controllers, configured in Unicast mode.

Invalid controller IP addresses
    ERR: IP address '172.16.0.12' on controller 'E682-12v' universe 11 is a broadcast address.
    ERR: IP address '172.16.0.12' on controller 'E682-12v' universe 12 is a broadcast address.
    ERR: IP address '172.16.0.12' on controller 'E682-12v' universe 13 is a broadcast address.
[...]
    ERR: IP address '172.16.0.5' on controller 'E682-5v' universe 31 is a broadcast address.
    ERR: IP address '172.16.0.5' on controller 'E682-5v' universe 32 is a broadcast address.
[...]

The sequence package was uploaded to the bug #1077, you can use it to reproduce the error. I probably changed universe numbering since then, but was getting exactly the same type of error.
https://github.com/smeighan/xLights/files/1644668/xLights_bug_1077.zip

**Comment by keithsw1111** [comment]
Not according to this article ... https://en.wikipedia.org/wiki/Broadcast_address

172.16.0.5 is broadcast address for universe 5 and should not be used for unicast traffic.

There error is correct.

**Comment by dkulp** [comment]
No...  172.16.0.0 IS a valid subnet for private networks:

https://en.wikipedia.org/wiki/Private_network

Thus, it should be usable without errors.

**Comment by keithsw1111** [comment]
They are only check sequence errors ... using ip address ranges that clash with multicast broadcast addresses does not seem advisable.

But for clarity ... it will still output the data ... and there are no error produced when you output to lights.

**Comment by Vlad-Star** [comment]
@dkulp - thank you for reopening the ticket

@keithsw1111 ,

You've misread the article. Each defined network has a "network address" (first address of the network) and a "broadcast address" (last address of the network), calculated by applying "or" function to the "network address" and the inversed network mask. All addresses in between are usable IP addresses, that can be configured on your hosts.

In the link you posted above they give you an example how broadcast address is calculated: "172.16.0.0 | 0.15.255.255 = 172.31.255.255", where 0.15.255.255 is the inversed 255.240.0.0 netmask 

If you translate decimals to binaries, they will look like:
10101100 00010000 00000000 00000000 (network address of 10101100 0001 network)
10101100 00011111 11111111 11111111 (broadcast address of 10101100 0001 network)
Note, that the network address has exactly 12 bits, which defines this network as /12 in CIDR notation.

To make the situation worse :) the networks can be split into sub-networks. For example, I can have valid 192.168.1.128/29 network. This means, that my "network address" will be 192.168.1.128, my network mask will be 255.255.255.248 (/29) and the broadcast will be 192.168.1.135 (192.168.1.128 | 0.0.0.7)

P.S. This is actually part of my job :)

**Comment by Vlad-Star** [comment]
Looking through the Setup tab, I realized that there is no field for the network mask whatsoever, so you can't calculate neither the actual network address, nor broadcast address. I suggest to drop broadcast check and implement multicast check instead, against the range provided above.

**Comment by Vlad-Star** [comment]
@dkulp 
How about doing the same check for 172, as for the other private networks? 172.31.255.255 will be default broadcast address for 172.16.0.0/12 network.
if (ip1 == 172 && ip2 == 31) {
  if (ip3 == 255 && ip4 == 255) {
  // error
  }
  // else is valid
}

**Comment by AzGilrock** [comment]
Check Sequence is like the Check Engine light on your car.  Sometimes it comes on and means nothing.  Lets not make a big deal about it.
