### ISSUE TITLE
Latest Xlights displays memory issue when loading older sequence

### ISSUE THREAD

**Issue by smartaleciam** [smeighan/xLights#1085]
Latest Xlights 2018.3 displays memory issue when loading older sequence an then crash's
yet version 2017.32 works just fine
Using latest Ubuntu (linux), 8gig ram

**Comment by swb0417** [comment]
Alec, is that the latest LTS (stable) release which is 16.04.3 or the latest build which is 17.10.1?

**Comment by keithsw1111** [comment]
So I loaded your show on my windows PC. It uses a fair bit of memory ... over 1GB ... I then did a render and the memory usage went up by about 200MB but dropped back to around the same 1GB number. I then left the sequence open for an hour in xLights and the memory consumption did not change.

To progress this can you please do exactly the same thing and report back on memory consumption.

We need to anchor in on what activity is driving the memory use.

**Comment by keithsw1111** [comment]
Alec ... has this gotten any better in recent releases?

**Comment by keithsw1111** [comment]
Closing due to no response
