### ISSUE TITLE
Exit issue

### ISSUE THREAD

**Issue by dconley1964** [smeighan/xLights#1086]
This occurs every time I exit the program.  Running the latest Linux Mint Mate x64.  [xLights_dbgrpt-13398-20180128T191134.zip](https://github.com/smeighan/xLights/files/1675022/xLights_dbgrpt-13398-20180128T191134.zip)

**Comment by AzGilrock** [comment]
Well at least that problem has an obvious workaround. :)

**Comment by AzGilrock** [comment]
Well I was joking that you could just never exit the program but I was hoping maybe our Linux guru would take a look.  The stack trace doesn't show any obvious reason for the crash to me.

**Comment by dconley1964** [comment]
No worries.  It was a version issue.  It works fine now.  I'm not sure if
it was an xlights issue or an issue with my OS>  I recently wiped and
rebuilt.  All is good now. xLights 2018.5 and Linux Mint Mate 64bit Sylvia.
