### ISSUE TITLE
Singing faces positioning

### ISSUE THREAD

**Issue by kmacmaster** [smeighan/xLights#1087]
![frosty](https://user-images.githubusercontent.com/20920979/35589121-caaa5570-05d0-11e8-88e7-628180759b5b.PNG)
If you create a 200x200 matrix, add a singing snowman (measuring 78x80) and select centered, when rendered, it does not center, it scales.
![timeline](https://user-images.githubusercontent.com/20920979/35589117-c8ebae96-05d0-11e8-8075-cb3ef76f6d4a.PNG)

**Comment by keithsw1111** [comment]
In .5
