### ISSUE TITLE
No Icon displayed

### ISSUE THREAD

**Issue by bluzervic** [smeighan/xLights#109]
In Xlights 4.0.5 after building it and installing, the Icon looks like a piece of paper

-Blu

**Comment by smeighan** [comment]
corrected in 4.0.6

**Comment by smeighan** [comment]
fixed in 4.0.7

**Comment by AzGilrock** [comment]
I installed the 4.0.8 release and I also got a piece of paper for an icon.  I went to properties for the shortcut and hit change icon and it said it couldn't locate xLights4.ico.  But the file is in the directory with the xlights.exe so I manually had to navigate there to select the file to fix the icon.
