### ISSUE TITLE
XLights 2018.5 changing Preview on group disables Model/Group panel

### ISSUE THREAD

**Issue by DevDavidW** [smeighan/xLights#1090]
On the Layout tab, after I select a group and change the Preview from Default to something else, the Model/Group panel no longer takes input and cannot scroll the list.

**Comment by AzGilrock** [comment]
I just tried what you described and I'm not seeing a problem.  Might need to show us a video.

**Comment by DevDavidW** [comment]
I made a video showing the issue., I tried the same steps on my laptop and was able to reproduce it there as well with the same version. I am running Windows 7 64 bit if that matters.

Video Link: [https://youtu.be/mOD4a1-ECrU](url)

**Comment by AzGilrock** [comment]
This is why a picture is better than a description.  I thought you were talking about the preview setting I circled here:
![image](https://user-images.githubusercontent.com/2024669/36008144-298f49fe-0d03-11e8-807b-e4a38efaea3e.png)

**Comment by AzGilrock** [comment]
Yeah this is frustrating cause that was all working when I first designed it.

**Comment by AzGilrock** [comment]
In fact this was working in 2018.3 and then broke in 2018.4.

**Comment by DevDavidW** [comment]
Ah right. Yeah I knew I should have provided a video or at least a screenshot. I'll do that next time or at least be more descriptive.

**Comment by AzGilrock** [comment]
I already see what broke it.  Some code was added to improve sorting speed and its leaving the list frozen.
