### ISSUE TITLE
model preview and house preview not functioning properly

### ISSUE THREAD

**Issue by RalphDeweil** [smeighan/xLights#1092]
my model preview works fine for all of my models except for any floodlights.. Once I add my floodlights and I click on the floodlight the model preview does not show the floodlight and then when I run the sequence I'm just speaking about a test 30 seconds worth of color fade for the floodlight only in the house preview the floodlight shows up just barely in the lower left-hand corner of the house preview screen but once I stop sequence is positioned back where I put it about center screen but lower half. I've tried several times moving the floodlight in different places once or twice the floodlight did show on the house preview and then it disappears into the corner again sorry for the jumpy explanation is the best way I can explain it.

**Comment by AzGilrock** [comment]
So what do you expect us to do based on that description?

**Comment by dkulp** [comment]
FYI: I see the same thing... The "Flood" style DMX model is placed correctly on the Layout panel, but doesn't display at all on the Model Preview and is always centered on the lower left corner of the House Preview.

**Comment by AzGilrock** [comment]
Ok I can work with that description...lol.

**Comment by AzGilrock** [comment]
I'm not at home but inspecting the code I pass in the exact same center coordinates as the other 2 DMX drawing types so I don't see how it could be different.

**Comment by AzGilrock** [comment]
If it doesn't show up at all then I gotta ask did you actually define the Red, Green, and Blue channel numbers?  And are you only using On and ColorWash or the DMX Effect?  None of the other effects work on DMX models

**Comment by dkulp** [comment]
<img width="720" alt="screen shot 2018-02-08 at 12 04 29 pm" src="https://user-images.githubusercontent.com/91569/35986883-4a55fb32-0cc8-11e8-82fa-aea9e84fc1e4.png">
<img width="761" alt="screen shot 2018-02-08 at 12 04 52 pm" src="https://user-images.githubusercontent.com/91569/35986890-4ee76532-0cc8-11e8-8674-2675caf2557d.png">

Couple of screen shots...  One shows that "Red" on the DMX is working, but it's in the lower corner of the House preview and not in the model preview.  The other shows that if another model/effect is selected and the flood should be off, it's showing in the right place on the House preview, but white and not off.

**Comment by AzGilrock** [comment]
Yes currently all DMXModels show white when all zeroes.  I was already looking into a fix for that already.  The fix is easy but I found that some users wanted to see some type of feedback as to where the beam would be pointing even when it was off.  I don't see how the position could be wrong unless its wrong for all DMXModels types.

**Comment by RalphDeweil** [comment]
​Sorry Gill i did what i could to explain what was happening to me. but
happy the others said it better.  ​

Thank You,

Ralph Deweil
