### ISSUE TITLE
xScheduler Crashed on Startup on Mac since 2018-4

### ISSUE THREAD

**Issue by andy-hopkins** [smeighan/xLights#1093]
xScheduler on MacOS 10.13.3 consistently crashes on startup since 2018-4.

First attempt to run it, it crashes "cleanly" leaving no process running. A second attempt crashes and leaves a process running which requires a Force Quit.

Only the first attempt to execute sends any to the log (attached)

[xSchedule_l4cpp.log](https://github.com/smeighan/xLights/files/1721958/xSchedule_l4cpp.log)

**Comment by keithsw1111** [comment]
There are no errors in this log.

Can I suggest you send us your schedule and networks files.

**Comment by andy-hopkins** [comment]
I've been doing a little more playing around. 

Replaced the network with a single, large NULL ...

<?xml version="1.0" encoding="UTF-8"?>
<Networks computer="study">
  <network NetworkType="NULL" MaxChannels="99000"/>
</Networks>

Loaded xScheduler 2018-3, removed all the sequences, saved & exit. 
Run xSchedule 2018-4 - issue still exists

Up until now my Light Shows directory is a symbolic link to a directory on my NAS. I've removed that and copied all the file locally - same issue

I'm a bit of a noobie to this, though I am computer literate, so if you need anything, please be specific about filenames and I'll get them

Cheers

**Comment by keithsw1111** [comment]
Dan seems to have checked in a change for .6 which may fix your issue (the symptoms sound similar) ... although there is no obvious reason for his change to make any difference - which he acknowledges..

**Comment by keithsw1111** [comment]
Is this now fixed?

**Comment by keithsw1111** [comment]
Stuart tells me as of .7 this is working again. Please reopen if that is not the case for you.
