### ISSUE TITLE
Crash moving face effect vertically

### ISSUE THREAD

**Issue by ebuechner** [smeighan/xLights#1096]
[xLights_dbgrpt-3200-20180218T061146.zip](https://github.com/smeighan/xLights/files/1734684/xLights_dbgrpt-3200-20180218T061146.zip)
I'm running 2018.5 64-bit.
While using a face effect on a matrix with multiple layers if you use the arrow keys to move the face vertically in the grid you get a crash.

**Comment by AzGilrock** [comment]
The statement you are making is not 100% true so we need you to provide a scenario that will cause the crash.  The crash file indicates the Effect Assist panel was involved in the crash.

**Comment by ebuechner** [comment]
[xLights_dbgrpt-13064-20180218T113310.zip](https://github.com/smeighan/xLights/files/1734931/xLights_dbgrpt-13064-20180218T113310.zip)

**Comment by ebuechner** [comment]
I added another file where the only thing I did was move the face effect.

**Comment by ebuechner** [comment]
I'm able to reproduce this crash quite easily by moving a face effect up and down a layer on the matrix. 
If it doesn't crash immediately it would crash when I go to make a change to any of the effects settings.
Let me know if there's anything I can do to help. 
Obviously this isn't a critical problem and I can easily work around it.

**Comment by AzGilrock** [comment]
With the new file I got 1 crash but I wasn't in the debugger.  Trying to cause it in the debugger I didn't see it mainly cause it was taking so freaking long to accomplish anything cause things are 20 times slower in the debugger.  With that sequence I was getting over 1.2 gig of RAM usage and it was taking forever just to process clicking on the effect.  I went back to non-debug mode and I can get it to move with the arrow if I do a render all and let it complete before I try doing any moves.  My guess is its still rendering something when the move happens and that causes a problem.

**Comment by ebuechner** [comment]
Yes I know the file is huge because I'm running it at 25 ms which obviously isn't helping. 
There's many things that I do while sequencing that I know it's rendering in the background and I don't get a crash, only when I move a face vertically that I have a problem. 
I appreciate you looking at this and I'm not to put out by the problem I'm just going by what Keith said one time that Xlight should never crash. 
So I thought I would make you guys aware of it.

**Comment by keithsw1111** [comment]
Can you try this in .7 when it comes out

**Comment by ebuechner** [comment]
No problem I'll give it a try.
Thanks for looking at it.

**Comment by ebuechner** [comment]
I still get a crash
[xLights_dbgrpt-9252-20180312T111708.zip](https://github.com/smeighan/xLights/files/1803630/xLights_dbgrpt-9252-20180312T111708.zip)

**Comment by keithsw1111** [comment]
Ok ... I think i got this ... .8 it is.
