### ISSUE TITLE
2018.5 Download Model XML Parsing Error when importing same model more than once

### ISSUE THREAD

**Issue by loneb82** [smeighan/xLights#1097]
When using the new"ish" Download Model to import a Boscoyo Model it will error out when you've imported it more than once.  If you import a model it will be successful the first time.  It occurs if you delete it and try to import the same model. It will also occur if you try to add another of the same model.  I tried with several of the Star models and receive the same results.  I've tried on brand new layouts and existing layouts and I'm able to repeat the issue.
![xlightscustom](https://user-images.githubusercontent.com/8631964/36355562-124de5fe-14b3-11e8-87f4-0ac8431a31c8.PNG)
![xlightsxmlparse](https://user-images.githubusercontent.com/8631964/36355563-15462fb4-14b3-11e8-9cba-fc2e78984677.PNG)

**Comment by AzGilrock** [comment]
Yeah if you follow our conversations on the forum and Facebook this was reported and fixed 11 days ago.  Until the next release you just need to clear the Vendor cache to get past this error.
![image](https://user-images.githubusercontent.com/2024669/36356057-cc3e640c-14a9-11e8-920c-3b9f9ac82caf.png)
