### ISSUE TITLE
MAC Version Locks up when Editing Labels (Versions 2018.x)

### ISSUE THREAD

**Issue by gizmohd** [smeighan/xLights#1099]
When editing /adding labels on timing tracks that are sometimes densely packed, the UI will become unresponsive to mouse clicks.

Command-{keys} work, but mouse operations do not always register.   The only way to fix this is the following key combinations:

Command-S
Command-Q

then restart the application.

**Comment by keithsw1111** [comment]
Is this still happening

**Comment by AzGilrock** [comment]
Closing due to lack of feedback.   Reopen if there is new information.
