### ISSUE TITLE
4.0.6 Hard Crash on opening subsequent sequence

### ISSUE THREAD

**Issue by mararunr** [smeighan/xLights#110]
SCREENCAST in bottom comment now...files in public one drive folder (link in one of comments below).  Can repeat this hard crash over and over.

![image](https://cloud.githubusercontent.com/assets/11252070/6859546/0d1b64da-d3e8-11e4-9a27-737a113772ef.png)

Let me see if I can recreate...I can't recreate and here's a debug (although I spent too long trying to recreate the hard crash so not sure if the time on this debug is the correct one)...o, well, sharing anyway in case maybe it triggers another thought looking at it...

0x00567071              EffectLayer::HitTestEffect(int, int&, int&)
0x005687f3              EffectsGrid::RunMouseOverHitTests(Element*, int, int, int)
0x0056abdf              EffectsGrid::mouseMoved(wxMouseEvent&)
0x6a08333a ZNK16wxAppConsoleBase11HandleEventEP12wxEvtHandlerMS0_FvR7wxEventES3_
0x6a083777 ZNK16wxAppConsoleBase16CallEventHandlerEP12wxEvtHandlerR14wxEventFunctorR7wxEvent
0x6a236036 ZN12wxEvtHandler23ProcessEventIfMatchesIdERK21wxEventTableEntryBasePS_R7wxEvent
0x6a3490c7 ZN8wxWindow15HandleMouseMoveEiij
0x6a35062d ZN8wxWindow16MSWHandleMessageEPljjl
0x70990b96
0x767b6b34 gapfnScSendMessage
0x767b6b00 gapfnScSendMessage
0x6ac7b919 ZN9LexerBaseC2Ev
0x6a34b3f3 ZN8wxWindow16MSWDefWindowProcEjjl
0x767b6a8c gapfnScSendMessage
0x70990b64
0x767decfb SetLayeredWindowAttributes
0x6ac7b919 ZN9LexerBaseC2Ev
0x6a339140 ZN8wxWindow13MSWWindowProcEjjl
0x6a3479bc Z9wxWndProcP6HWND__jjl

**Comment by mararunr** [comment]
Happened again.  I was working in one sequence titled testing sequence.  Was in preview tab watching sequence.  Went back to sequence tab and hit open icon to open another sequence (palladio 1).  I believe the dialog to open the file was open when it crashed.  Debug file does not get created.  Will keep trying.  Have posted all pertinent files at time of crash here (https://onedrive.live.com/redir?resid=D05FBDC1B79CF3A9%21105)

![image](https://cloud.githubusercontent.com/assets/11252070/6860841/9b679d22-d3fb-11e4-9d42-6b0cb9c0ee20.png)

**Comment by mararunr** [comment]
3rd time...started xLights, opened testing sequence, went to preview to watch it, went back to sequence tab (without stopping preview), clicked on open icon, hard crash with open file dialog up.

**Comment by mararunr** [comment]
4th time...can repeat sequence over and over to make it hard crash now...will screencast.

**Comment by mararunr** [comment]
screencast loaded to public one drive and youtube (https://www.youtube.com/watch?v=WJIF8UfVxEU)

**Comment by smeighan** [comment]
i have used your rgb_effects, rgb_networks and palladio1.xml files. I used my audio file. everything works fine PREVIEW, SEQUENCER.

Can you send me your audio file to xlights@meighan.net? Ill try with that.
these are all on 4.0.6

**Comment by mararunr** [comment]
The crash happens while "testing sequence" is open and then I go to open another sequence.  "Testing sequence" is an an animation only sequence without audio.  Originally I thought it was crashing during the opening of the second or subsequent sequence (thus palladio1 in the drive folder), but it crashes upon the window file open box (never have to move the cursor or anything and it crashes).  Hope this helps.

**Comment by AzGilrock** [comment]
Does it happen if you do the same steps without 12 cups of coffee? :)

**Comment by mararunr** [comment]
LOL....I'm actually not a coffee drinker...just happen to be on call this week (you know as IT person what I mean) and happen to see Sean's response.  Went ahead and replied while up for a work issue anyway :-)

**Comment by AzGilrock** [comment]
No I was laughing cause in the video you clicked so many things in 5 seconds I could barely follow the clicks.  We've added some new logic to clear things out when opening a new sequence so we may have to wait and let you try again after next release.

**Comment by mararunr** [comment]
O - that's a problem with Screen Cast O Matic that I haven't figured out how to fix.  It doesn't record in real time, it only records a frame when it recognizes activity so the result is always fast forward speed.  The videos come out like a Laurel & Hardy routine - sorry about that.  Got to figure out how to force it to record in real time.

**Comment by AzGilrock** [comment]
Ok that explains a couple videos I've seen.  I laughed and said wow he's working hard to crash it. :)

**Comment by mararunr** [comment]
What do you use?  Your screencast videos of the morph effect looked to be in normal time?

**Comment by AzGilrock** [comment]
I'm using Screen Cast O Matic also.  Maybe it the talking that triggers activity and slows it down.

**Comment by AzGilrock** [comment]
I paid for Pro now so I could record the PC audio with the voiceover and so far my PC audio keeps coming out with a ton of crackling.

**Comment by mararunr** [comment]
I wondered.  So if I turn on the microphone that should fix it.  Yea, I went for Pro as well.  Thanks Gil.  (PS I"m going to delete my part of this conversation since it's not relevant to the bug :-)

**Comment by mararunr** [comment]
Ok, I'll wait for next release and try again.  Thanks Gil!

**Comment by mararunr** [comment]
Fixed in 4.0.7.  Closing.

**Comment by mararunr** [comment]
Re-tested with 4.0.9 - no issue
