### ISSUE TITLE
Model Edit Of Name

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#1103]
In Layout tab, select a model, in the bottom window, I go to the Description field, click twice, and back space to remove the information that I want.  Type in the new info, hit tab, click save, and in the window above, it still displays the old description   
Ver 2018.6    64 bit

**Comment by AzGilrock** [comment]
Try Enter instead of Tab.

**Comment by JoelDearing** [comment]
I tried Enter instead of Tab and it made no difference.
Tried removing the description completely  and re-entered text and hit Enter and did not change the old label.

**Comment by AzGilrock** [comment]
Ok I read it too quick the first time I thought you meant the Name field.  I'll have to try it when I get home.  You didn't say which OS just in case it matters.

**Comment by JoelDearing** [comment]
Win 7

**Comment by keithsw1111** [comment]
I think you are mixing up the name and description. The name is what appears in the list. The description is just a text field where you can store anything that might be useful to you ... it doesnt change the model name. I am going to close this ... if i have it wrong you can re-open it but you need to provide either a video or some images showing what you mean.
