### ISSUE TITLE
Difference between xLights effect and xScheduler output, it is upside down

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#1105]
In xLights I created a Matrix. 
Set up tab NUL 20,100 channels
Start channel 4113
End Channel 24212
----------------------
Layout tab
Dir Horizontal
Strings 64
Nodes / string 100
Strands1
Starting location Bottom Left
Ind Start Ch  un checked
Start Ch 4113
Next four options, no adjustment
Sub models, created 4 sub models that are 25% of the matrix, an upper left, upper right, lower left and lower right.
No other items tweaked for Matrix in Layout tab
-----------------
Sequence tab
In sub model 
Upper Left applied  On effect, selected white
Upper Right Red
Lower Left Green
Lower Right Blue
It looks as it should in model preview

Rendered, saved as matrix test 031518

In xScheduler
From Edit menu / Virtual Matrix
Height 64
Width 100
Rotation None
Quality High
Start Channel 4113
Topmost window box checked
Created Playlist, added FSEQ matrix test 031518
In right pane, clicked on matrix test 031518
Four sub models output to the projector, BUT it was upside down.  
upper left white was on lower left.
Also when I applied the fire effect to all four sub models, the effect was upside down.

back to xLights:
Render style at Default
Transformation set to None

Let me know what else you need.

**Comment by keithsw1111** [comment]
Virtual matrices always start top left and are 1 strand/string. You cannot change that and it doesn't make sense to. The virtual matrix is a prop and you model it in xLights the way it is. 

The virtual matrix is not there so you can visualise a matrix you may have that is wired differently.
