### ISSUE TITLE
Odd behavior well vectoring face effect.

### ISSUE THREAD

**Issue by ebuechner** [smeighan/xLights#1107]
I'm using the face effect and trying to move a matrix face across a p10 panel. 
I'm doing this by using the value curves in the edit section of the buffer. 
I can get the face effect to go across the panel perfectly but the face within the effect disappears out of frame while it's moving. 
The length of the affect seems to alter how far out of frame it gets, if I make it a very short affect the face only goes slightly out of frame but if I make it a long affect the face will go completely out of frame. 
Value curve left ramp -25 to 100.
Value curve right ramp 0 to 125.
I've tried a couple other effects with the same settings and I don't see the same behavior as I do with a face effect. 
Correction, I see the same behavior with a picture effect if it's set to, scale to fit but not if it's set to, scale keep aspect ratio.

**Comment by ebuechner** [comment]
https://youtu.be/DM0CXdtufWY

**Comment by keithsw1111** [comment]
Ed can you ping me a sample sequence for this.

**Comment by keithsw1111** [comment]
The face effect instance of this problem has been fixed as a result of a performance fix in .9 ... but the picture effect problem remains. Spent 4 hours on it last night and still have not gotten to the bottom of it. If you use a picture that has colours that go all the way to the left edge you will see not only is it cutting off the right of the image but it is over sampling the left edge and thus smearing the left edge as much as it is cutting off the right edge.

**Comment by ebuechner** [comment]
The face effect would be the important one as far as I'm concerned. 
I included the picture effect in the test sequence to show all instances that were acting up.
The picture effect has its own built-in way to Vector an image so I can't see needing to move the picture effect by way of using the value Curves in the buffer( but I could be wrong).
I see that in .9 the face effect is working but it's a little jerky.
Gil stated that the face effect uses the picture effect internally so I find it strange that now one would be affected but not the other.

**Comment by keithsw1111** [comment]
As a result of the performance optimisation the face effect now calls the picture effect less often as the result is cached which avoids the problem.

**Comment by keithsw1111** [comment]
Ok ... found and i believe fixed.
