### ISSUE TITLE
4.0.6 File, New sequence does not scrub screen from previous sequence

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#111]
After working on a sequence, I saved it and did File, New sequence.
The sequencer tab left all the effects up from the previous sequence.
Play did not render the effects, however highlighting and deleting an effect caused a crash.

**Comment by AzGilrock** [comment]
This is fixed by a checkin from Dan 21 hours ago...will be in next build.  The only thing not clearing is the audio waveform still shows if you switch from a media to an animation.  If you go media to media it's not a problem.

**Comment by stevegiron** [comment]
Cool!  I did switch from media to animation and the waveform was gone.

**Comment by AzGilrock** [comment]
We'll I've tried doing it by having a media sequence that displayed a waveform and then creating a new sequence of type animation and it doesn't clear out the waveform drawing.
