### ISSUE TITLE
MIDI Pitch Bend Crash - xScheduler

### ISSUE THREAD

**Issue by GrizAF** [smeighan/xLights#1110]
I was trying out functions of the MIDI Events in xScheduler and received consistent crashes when using the Pitch Bend function.  When pressing a key on the piano, then using a pitch slider, the crash occurred.  This is not a critical item for me, but I thought I would pass along the info in case it becomes an issue in the future.  Please let me know if you have any questions - thanks for all you do. 

-----------Crash Report------------
<?xml version="1.0" encoding="UTF-8"?>
<xSchedule>
  <Options AudioDevice="" WWWRoot="xScheduleWeb" Password="" WebServerPort="80" PasswordTimeout="30" ARTNetTimeCodeFormat="1">
    <Button Label="Play Selected" Command="Play selected playlist" Parameters="" Hotkey="~" Color="green"/>
    <Button Label="Stop All" Command="Stop all now" Parameters="" Hotkey="~" Color="red"/>
    <Button Label="Reset All Schedules" Command="Restart all schedules" Parameters="" Hotkey="~" Color="default"/>
    <Button Label="Next Step" Command="Next step in current playlist" Parameters="" Hotkey="~" Color="default"/>
    <Button Label="End Gracefully" Command="Jump to play once at end at end of current step and then stop" Parameters="" Hotkey="~" Color="red"/>
    <Button Label="Add 10 Mins To Schedule" Command="Add to the current schedule n minutes" Parameters="10" Hotkey="~" Color="default"/>
    <Events>
      <EventMIDI Device="Yamaha Portable G-1 [MMSystem] 1" Status="0xEn - Pitch Bend" Channel="ANY" Data1="ANY" Command="Play specified playlist" Name="1" CommandParm1="Test" CommandParm2="" CommandParm3="" Condition="Equals" Threshold="255"/>
    </Events>
    <OSC MasterPath="/Timecode/%STEPNAME%" RemotePath="/Timecode/%STEPNAME%" IP="255.255.255.255" Time="Seconds (float)" Frame="Default (int)" ServerPort="9000" ClientPort="9000" TimeBased="True"/>
  </Options>
  <PlayList Name="Test">
    <PlayListStep Name="">
      <PLIFSEQ FSEQFile="C:\Users\Home\Documents\xLights\Test\singlestrand.fseq" ApplyMethod="0" StartChannel="1" Channels="0" Delay="0" Name="" Priority="1"/>
    </PlayListStep>
  </PlayList>
</xSchedule>

**Comment by GrizAF** [comment]
[xSchedule_l4cpp.log](https://github.com/smeighan/xLights/files/1840201/xSchedule_l4cpp.log)

**Comment by keithsw1111** [comment]
Unfortunately there is no crash in that log ... possibly too much happened between when it crashed and when you grabbed the log.

**Comment by keithsw1111** [comment]
Can you please reproduce the problem and send me the log again

**Comment by GrizAF** [comment]
Was able to replicate the crash again.  It's only when I execute a pitch bend that I get this crash.  Here's all the info - thanks!
[backtrace.txt](https://github.com/smeighan/xLights/files/1882491/backtrace.txt)
[notes.txt](https://github.com/smeighan/xLights/files/1882492/notes.txt)
[xSchedule_l4cpp.log](https://github.com/smeighan/xLights/files/1882493/xSchedule_l4cpp.log)

**Comment by keithsw1111** [comment]
So from the log the crash has nothing to do with MIDI. In theory it would have crashed either way. Can you post your .xschedule file?

**Comment by GrizAF** [comment]
[xSchedule_dbgrpt-12716-20180408T203908.zip](https://github.com/smeighan/xLights/files/1888096/xSchedule_dbgrpt-12716-20180408T203908.zip)

Was able to recreate the crash - but, I believe this is only crashing when "ANY" is selected from the two dropdown menus.  Once I input the correct/specified key the pitch bend worked fine.  The event triggered a short playlist with a 30sec fseq file, and when the "stop all" button was pushed, the rest of xschedule began to lag, which was not seen previously.   Thanks for all the help.

**Comment by keithsw1111** [comment]
This crash has nothing to do with MIDI ... it is a crash associated with playing the video. The reason the video crashed was you passed it a wave file (what were you thinking) C:\Users\Home\Documents\xLights\Radar Love2.wav 

I believe this is the case in all the examples above. I have made some changes in .11 which hopefully will manage this better ... ie not crash. But to work around it please not .wav files are not videos.

**Comment by GrizAF** [comment]
Awesome!  Thanks, Keith.  I was using that .wav file just testing out playlists, but will steer away in the future.  Thank you.
