### ISSUE TITLE
Bug: Slider values vs Value Curve values

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#1111]
I happened to notice that setting a speed of 3 on the slider does not correspond to the same value of 3 when applying a flat value curve to the speed.  This seems to be the case across the board on all effects, not just the Spiral effect shown in the attached video.  I could replicate this with the cycles on Bars too.

I also noticed that the scale indicators are not in their proper locations either.  The top value is at the top of the chart, but the lower value is directly below it and not at the bottom.

<img width="490" alt="screen shot 2018-03-24 at 11 01 01 am" src="https://user-images.githubusercontent.com/12144876/37866151-a5c4065e-2f54-11e8-9012-9d390ece93dc.png">

[VC Difference.mp4.zip](https://github.com/smeighan/xLights/files/1844550/VC.Difference.mp4.zip)

**Comment by keithsw1111** [comment]
Fixed
