### ISSUE TITLE
Issue with 2018.9  64Bit Windows ( Ctrl + 0-9 Tags )

### ISSUE THREAD

**Issue by BrianRees** [smeighan/xLights#1113]
I placed 3 tags on my sequence ( 0, 1, 2 ) 
Pressing Ctrl + ( any number ) will always jump to position 0

**Comment by keithsw1111** [comment]
I cant reproduce this. What OS are you using?

**Comment by BrianRees** [comment]
Thank you.   I am running Windows 10.
I retried this and realized I was pressing the number pad digits, not the keyboard digits. 
Pressing the keyboard numbers works.
Pressing the number pad digits does not.   
I am closing this ticket since it does work using the keyboard. 
Thank you!

**Comment by AzGilrock** [comment]
That means you didn't have NumLock active on the keypad.
