### ISSUE TITLE
Bug: Shape Effect & Value Curves

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#1114]
Applying a Value Curve to the X or Y location does not produce the intended, or even expected behavior.  For example, when applying applying a ramp from 0 - 100, the shape stays stationary at the 0 point of the VC for the majority of the effect length, then immediately jumps to the end point of the curve.

<img width="486" alt="screen shot 2018-04-03 at 7 50 29 pm" src="https://user-images.githubusercontent.com/12144876/38283066-7313e986-3779-11e8-869c-4f91ce362102.png">
[Bokeh.zip](https://github.com/smeighan/xLights/files/1873976/Bokeh.zip)

**Comment by keithsw1111** [comment]
This happens because the location is locked in when the shape is created ... I have changed it so that if it isnt random then it updates which should fix the issue
