### ISSUE TITLE
Enh: Add group render styles to sub-models

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#1115]
Use case: Straight legs of a snowflake as sub-models.

Added them to a group just to get render styles available only to a group.
Cool   Would be nice if the group render modes were available to sub-models by default.

**Comment by keithsw1111** [comment]
It would only work in a limited set of circumstances ... and not enough to be worth the hassle. And it isnt hard to create the group.

**Comment by keithsw1111** [comment]
If submodels were strictly mutually exclusive ... maybe ... but they arent.

**Comment by stevegiron** [comment]
True story Gil ??

**Comment by AzGilrock** [comment]
I'm not completely familiar with submodels.  I just tested one of mine and it appears that a submodel already has "Default", "Per Preview", "Single Line", and "As Pixel" which are probably the buffers that make sense for a single submodel.  What other render mode would you use for a single submodel?  If you want it to apply to a group of submodels well then your stuck putting them in a group anyways.
