### ISSUE TITLE
Output upload to FPP Cape/Hat (Crash)

### ISSUE THREAD

**Issue by kd7hgt** [smeighan/xLights#1122]
I was trying to upload my layout that I need to go to my F8 Controller from Dan. 
Right Click on line, upload to Controller, Output, FPP Capes/Hat, F8-B (8 Serial) It does give me the popup to say Yes, Then it give's me a Debug Report and crashes.  Tried several time's. I even rebooted my controller that I can access just fine through the web page UI.
[xLights_dbgrpt-143712-20180424T183831.zip](https://github.com/smeighan/xLights/files/1944821/xLights_dbgrpt-143712-20180424T183831.zip)

**Comment by keithsw1111** [comment]
Its an 8 port serial controller? But you are uploading an RGB star.

**Comment by kd7hgt** [comment]
I want my tree on port 1,2,3,4 Mega tree star on 5 and my arch's on port 8.  I am trying to re configure all my universes and channels in xlights now.

**Comment by kd7hgt** [comment]
[xLights_dbgrpt-161016-20180424T193024.zip](https://github.com/smeighan/xLights/files/1944947/xLights_dbgrpt-161016-20180424T193024.zip)

Here is the file with the newest version I just tried and still Fail's

**Comment by dkulp** [comment]
Is the F8-B updated to the latest master code?   This requires the latest code on the FPP's.

**Comment by kd7hgt** [comment]
Yes I have all 4 beagle's on  v2.x-master-575-g1df135b5

**Comment by keithsw1111** [comment]
It is a divide by zero error Dan. This calc results in a zero for his mega tree star.

            int zz = (*model)->GetNumStrings() / (*model)->GetNumStrands();

**Comment by keithsw1111** [comment]
Line 538 in FPP.cpp

**Comment by dkulp** [comment]
Yea... looking at it.   Also occurs with the tree itself.   None of my models use the zigzag stuff so didn't hit it.

**Comment by keithsw1111** [comment]
Num strings is 1. Num strands is 3 which is the number of layers of the star. 1/3 => 0

**Comment by kd7hgt** [comment]
is that on the 2nd file I uploaded?  It doesn't matter If I try to upload the whole group or 1 line at a time.  Always crashes.  I just did it all manually and matched up my channel numbers.

**Comment by keithsw1111** [comment]
I am curious why you are uploading zig zags. For all the other controllers we dont

**Comment by keithsw1111** [comment]
kd7hgt ... its ok ... I think we have this.

**Comment by keithsw1111** [comment]
Normally you zig zag in the controller or in xLights ... not both.

**Comment by dkulp** [comment]
Very good point.   That probably should just be set to 0.

**Comment by keithsw1111** [comment]
Dan fixed this for .12
