### ISSUE TITLE
UI Elements sized incorrectly on Surface book

### ISSUE THREAD

**Issue by craiz** [smeighan/xLights#1127]
xLights 2018.11 64-bit on a Surface Book running Windows 10

I notice several UI elements are not sized correctly.

1. Render Style drop down options.
2. Import Effects dialog
3. Text on the bottom of the layout and sequencer tab where it shows the file name or effect time and duration information.
4. Display Elements dialog.

![bottom of layout tab](https://user-images.githubusercontent.com/8462504/39796466-7e12b058-530b-11e8-9b0f-d06cac8949c0.JPG)
![bottom of sequencer tab](https://user-images.githubusercontent.com/8462504/39796467-7e2bd196-530b-11e8-869a-dd48e13782fd.JPG)
![import effects dialog](https://user-images.githubusercontent.com/8462504/39796468-7e41d1d0-530b-11e8-9ec2-e69f01ed1a9c.JPG)
![renderstyleoptions](https://user-images.githubusercontent.com/8462504/39796469-7e560d80-530b-11e8-827b-268d89065558.jpg)
![displayelements dialog](https://user-images.githubusercontent.com/8462504/39796890-1e92f4b4-530e-11e8-91b6-e34749b5ebb9.JPG)

**Comment by keithsw1111** [comment]
I believe this is fixed
