### ISSUE TITLE
Bug: Jukebox Window Buttons

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#1130]
macOS 10.13.4
xLights 2018.12 (pre-release)

I compiled the Mac code to check out the new Jukebox feature and I noticed that the button numbers are not all visible, no matter how large I increase the window.  Only the first digit is viewable.

This very well could be an issue on my end with settings and compiling.

<img width="980" alt="screen shot 2018-05-10 at 5 06 06 pm" src="https://user-images.githubusercontent.com/12144876/39897876-e15c9196-5479-11e8-8eca-894da6243668.png">

**Comment by keithsw1111** [comment]
This should be fixed.

**Comment by kppankratz** [comment]
Yes, it's displaying as expected now.
