### ISSUE TITLE
Enhancement Request: Roto-Zoom Addition

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#1133]
In using the Canvas Blend mode with the Off effect, there is no easy way to easily move the entire canvas animation across the buffer as a group.  At one point I asked if a X/Y position could be added to the Off effect, but was told that would not work as I was expecting.

My new proposal, if possible and not hard to implement, is to add the X/Y position sliders with value curve options to the Roto-Zoom layer setting.  This could possibly be the solution to make the canvas blend mode be more dynamic in the 2D realm.

**Comment by AzGilrock** [comment]
If you're still around can you post a sample.  I forget this whole canvas with off effect technique.

**Comment by kppankratz** [comment]
Yes, I'm still around, just haven't been posting a lot of look what xLights can do for a while.

This is an old request so I hope I'm remembering correctly.  I've attached a video that is 10 layers using a lot of the Roto-Zoom functions.  I believe at the time I was looking for a way to apply some additional movement to the entire animation as a whole along the X & Y axis without having to go into each effect on each layer and manipulate the X/Y positions to move it across the buffer.

While the canvas is a powerful tool at our disposal, in reality I'm not sure how many people use this advanced feature?  I've answered one question in the last few years about how it's used for animations in the FB group.

This could probably be closed in my opinion.

https://user-images.githubusercontent.com/12144876/103190601-4cc25d80-4897-11eb-9806-d4aa35be217a.mov

**Comment by AzGilrock** [comment]
Thanks I’ll take a look.  I wanted to put the x and y into the render buffer years ago but when I looked into it the problem was it moves the data after the effect renders which leaves black space somewhere.  But combined with zooming it’s possible it could be useful.
