### ISSUE TITLE
Content in Export House Preview Video is 1/4 of video frame

### ISSUE THREAD

**Issue by craiz** [smeighan/xLights#1134]
2018.11 64-bit,  Windows 10, Surface Book with 3000x2000 display
I've tried using the Export House Preview Video option and the resulting video has the house preview content in the bottom left corner of the video frame.  It looks like somehow the content size is cut in half horizontally and vertically and the resulting size in the video is 1/4th.

**Comment by KMojek** [comment]
Okay, I'm able to repro this on Windows using a lower-res display with high DPI settings. @dkulp it looks like what's going on is that the house preview is rendered at the reported window dimensions (not scaled up by GetContentScaleFactor()) so the video exporter should just use the unscaled dimensions. Does that make sense for Mac?

**Comment by KMojek** [comment]
I'll verify on a Surface Book but I'm pretty sure this should be fixed with the next release.
