### ISSUE TITLE
Feature Request: xSchedule Single Channel Matrices

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#1140]
Currently xSchedule matrices assume the matrix is RGB while in xLights you can specify models as single-channel or RGB nodes. Adding this ability in xSchedule would allow non-RGB matrices to still benefit from post-render scrolling text, overlays and other xSchedule features.

**Comment by keithsw1111** [comment]
I dont understand this request. What sort of matrix are you talking about. Typically single channel matrices are one channel per string ... there is not much you can do to display test on that.

**Comment by jholmes09** [comment]
Here is my specific example:

A grid of C9 screw-in bulbs (single-color) that each has their down dedicated circuit back to a controller.
It is effectively a single-color, AC matrix where each 'pixel' is a standard light bulb.

You can't change colors but you can fade, run effects, or scroll text.

**Comment by AzGilrock** [comment]
Do you actually build all the weird stuff you request or just look for missing features? haha

**Comment by jholmes09** [comment]
I actually build it :). I never ask for something until I'm plugging along on a project and hit a road-block.

**Comment by AzGilrock** [comment]
Yeah I seem to remember last time it was an RGBW matrix.

**Comment by jholmes09** [comment]
You are correct sir! That was made-up of RGBW Flood Lights :)

**Comment by keithsw1111** [comment]
I am not convinced enough people would ever use this feature so sorry but i am closing it. If you can make the case that several people need it maybe i will reconsider.

**Comment by jholmes09** [comment]
I understand. Thank you for the consideration :)
