### ISSUE TITLE
Bug: xSchedule (Linux) Crash when switching Show Folder

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#1142]
Please see attached log. I consistently see xSchedule (Linux) crashing when switching show folders.
[switching_directory_crash_log.log](https://github.com/smeighan/xLights/files/2048529/switching_directory_crash_log.log)

**Comment by keithsw1111** [comment]
I think I have this fixed for .15. A sequence was playing when you switched show folders.
