### ISSUE TITLE
Bug: Linux xSchedule UI Resizing

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#1143]
Please see attached images.

The 'Play List' editor window in xSchedule is supposed to divide into two equal sections.
However, it opens as the 'left window' 100% (see Image 1). You have to click and drag on the far right to resize the window and see both sections.

EDIT: I can't figure out why the photos are uploading upside down. Sorry.

![image1flipped](https://user-images.githubusercontent.com/18503894/40752033-b4dbda06-643b-11e8-94c4-c34c62be832e.jpg)
![image2flipped](https://user-images.githubusercontent.com/18503894/40752034-b4ecb0ba-643b-11e8-8068-8e17ea388bac.jpg)

**Comment by cjd** [comment]
Can you please give us a bit of background on your setup.
Which Linux distro/version are you running?
What desktop environment are you using?
Which linux packages/binary/build are you running for xLights (ie: appimage, ubuntu package, custom compile)

**Comment by jholmes09** [comment]
Oh I'm sorry! I completely forgot to paste that.

Lubuntu 18.04 LTS
Linux 4.15.0-22-generic x86_64

Installing xLights via Ubuntu PPA
xLights 2018.14
64-Bit

**Comment by keithsw1111** [comment]
Jeff can I close this one now Chris has regressed GTK.

**Comment by jholmes09** [comment]
Yes I have not noticed any issues since the regression.
