### ISSUE TITLE
Enhacement Request: Faces Effect - Add Button To Randomize Eye Blinks

### ISSUE THREAD

**Issue by danvisibleman** [smeighan/xLights#1147]
Multiple faces can be set to the same timing track, such as in the case of back-up singers. But often times their Eye blinks, when on Auto, are all at the same time, or in a very specific repeating pattern such that all the backup singers blink in sequence, one after another, every time. Would it be prohibitively difficult to add a button to randomize the eye blinks for a selected Face effect? Go through and Randomize each backup singer a few times until you get a pattern you like, rinse and repeat for the remaining ones, so that in the end they all look a bit more natural. #

**Comment by keithsw1111** [comment]
They are already random ... based on when the face is at rest. To re-randomise just re-render.
