### ISSUE TITLE
2 crashes in 1 afternoon

### ISSUE THREAD

**Issue by MagicMe** [smeighan/xLights#1149]
First of all, thanks for all of the improvements you've made to xLights. I especially love the bulk edit feature. It really makes sequencing go faster. 

My xLights has been working perfectly since I removed McAfee from my computer last month - until today. This afternoon it's generated 2 crash reports. Everything works perfectly until the crash window pops up. 

[xLights_dbgrpt-7240-20180605T174147.zip](https://github.com/smeighan/xLights/files/2074114/xLights_dbgrpt-7240-20180605T174147.zip)
[xLights_dbgrpt-9244-20180605T085844.zip](https://github.com/smeighan/xLights/files/2074115/xLights_dbgrpt-9244-20180605T085844.zip)

**Comment by keithsw1111** [comment]
What were you doing ... or what had you just done when it crashed. We have seen these crashes before but we dont know how to reproduce them ... and until we can it will be very difficult to fix them. Any hints you can provide would help.

The crashes are not the same so there may be 2 causes here or one cause showing up in a couple of locations. Most likely cause is you deleted or moved something between rows.

**Comment by MagicMe** [comment]
I'm just doing small changes as I edit my song. I'll make a note when it happens again so I can tell you specifically what I was doing.

**Comment by keithsw1111** [comment]
I think i have fixed the first one. Not so sure about the second. I am closing this though as without more information on exactly what was going on we are not going to fix it. We will continue to monitor crash logs.

**Comment by MagicMe** [comment]
Thanks.
