### ISSUE TITLE
Error message when audio file missing

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#116]
I copied a sequence XML file from one computer to another.  When opening the sequence on the new computer, the app gave a mpg123 error message code 22.  Verbose "Audio File Missing" would have helped too, but I knew it had something to do with the audio file name was different.

I went to Settings/Sequence settings and chose the correct media file. 
The waveform did not show until I saved the sequence and re-opened.

Issue: Error message could be more user friendly
Issue: Waveform does not display unless save/reopen is performed

**Comment by AzGilrock** [comment]
The error messages seem fine to me.  First you got the mpg123 error which comes directly from their library code.  Then when you closed that window you got our error message which said "Invalid Media File".

**Comment by AzGilrock** [comment]
Also I just caused this to happen and it did load the new audio waveform.  The only thing I see is the zoom was all the way in when it loaded the new waveform.

**Comment by AzGilrock** [comment]
Ok I fixed the waveform zoom when loading an audio file after a sequence is already open and I combined all the error messages from the mpg123 library by pushing them up to the caller so I display our message with their message included as details which helps us with debugging.  That mpg123 library has 48 possible return codes.

**Comment by AzGilrock** [comment]
So now it will look like this:
![file_error](https://cloud.githubusercontent.com/assets/2024669/6883730/70f5f0ec-d578-11e4-8cda-d3484286b649.jpg)
