### ISSUE TITLE
Feature Request: xSchedule use ping to ascertain if controller is online

### ISSUE THREAD

**Issue by andy-hopkins** [smeighan/xLights#1164]
Would it be possible to have xSchedule optionally use ping instead of an HTTP request to ascertain if a controller is available/on-line

I don't know how many controllers don't have an HTTP service running, my home built Arduino based controllers don't and while it most likely is possible to include an HTTP service, the additional memory it would take would adversely impact the number of pixels it could control.

Thanks for considering

**Comment by keithsw1111** [comment]
It already does on windows. Ping is not something that can be developed in a platform independent manner so it would need Linux & OSX specific development to change it to use ping on those platforms.

**Comment by andy-hopkins** [comment]
Thanks Keith, so is that something that can be done sometime in the future?

**Comment by AzGilrock** [comment]
Anything can be done in the future.  What OS are you using so we can tell you who you would need to bribe? :)

**Comment by andy-hopkins** [comment]
mmm.. that was a bit silly of me missing that piece of info.

OSX

Cheers

**Comment by keithsw1111** [comment]
Then you need Dan ... although it is possible the OSX and Linux stuff is quite similar
