### ISSUE TITLE
Bug: xLights claims another instance is running when its not

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#1166]
Hello:

After updating to xLights 2018.15 64bit (Linux) I am getting an error stating that another instance of xSchedule is already running anytime I attempt to run xSchedule. However I have checked the System Monitor and I've done a GREP search only to find that nothing is running. 

I have no log file to provide because I can't get into the program (which is usually how I find the log).
At the time of writing, there is no 2018.16 version for Linux.

Please let me know if I can provide any further information.

**System Information:**
OS: Linux 4.15.0-22-generic x86_64
64 bit
Little Endian
Ubuntu 18.04 bionic Ubuntu 18.04 LTS

**Comment by keithsw1111** [comment]
That is not what it claims ... what it claims is either another xSchedule is running or xLights is running and outputting to lights.

The other time this can occur is if xLights or xSchedule crashes while outputting to lights.

The error will not stop lights from outputting but is designed to explain to users why their lights may be behaving oddly.

**Comment by jholmes09** [comment]
Hi Keith,

Just to be sure, I rebooted my computer and then attempted to run xSchedule.
The error reads as follows:

"Another instance of xSchedule is already running. A second instance is now allowed. Exiting."

**Comment by keithsw1111** [comment]
Ah ok ... that isnt the output to lights then ... that is the wxWidgets single instance check playing up. I dont know where that is stored on Linux

**Comment by jholmes09** [comment]
Is this something I can disable or is this a @cjd question?

**Comment by keithsw1111** [comment]
You can work this out yourself if you invest a little time.

Go to the source code.
Search for a part of the error message in the source "Another instance of xSchedule is running"
This shows it is in xScheduleApp.cpp
If you look nearby you can see it is using wxSingleInstanceChecker
Google wxSingleInstanceChecker and Linux ...
Reading a couple of them http://trac.wxwidgets.org/ticket/17046?cversion=0&cnum_hist=10 seems to hint at where the file might be and what it might be named.

**Comment by jholmes09** [comment]
Thanks for the tips! As I am not a programmer, this little nudge is very helpful! I'll go digging :)

**Comment by keithsw1111** [comment]
Sure ... but you don't have to be able to write code to read it and find some things to google.

**Comment by dkulp** [comment]
It looks like on unix it's creating a file in your home dir like:

Create(wxTheApp->GetAppName() + '-' + wxGetUserId());

Check your home dir for a file that matches something similar and delete it.

**Comment by jholmes09** [comment]
Found it. Deleted it. Problem seems to have gone away. Thank you both for your help and the education :).
If the issue pops up again I'll report back.
