### ISSUE TITLE
Bug: 'Refired' Sequences stop after 1 minute when lower priority playlist is present

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#1168]
In xSchedule I created three playlists:

- Intermission (scheduled to run 24/7, Priority 5)
- Skating (run from 6-11 PM, ReFired on the Hour, Priority 9)
- Polar Express (run from 6-11 PM, Refired every 30 min, Priority 7)

In theory, the intermission should play all the time and then pause when the higher priority playlists are triggered. I have set Polar Express to a lower priority than Skating because I only want it to run at the bottom of the hour and this is the best way to achieve that.

While both higher priority playlists are triggering properly, exactly 60 seconds later the sequence stops and intermission unpauses. 

This error does not occur if I create multiple, non-looping schedules for 7 PM, 7:30 PM, 8 PM, 8:30 PM, etc., with higher priority than the intermission.

System is Windows 10.
xLights 2018.16 64 Bit.

xlights.xschedule and log file included in the .zip
[xschedule_refire_error_files.zip](https://github.com/smeighan/xLights/files/2125559/xschedule_refire_error_files.zip)

**Comment by keithsw1111** [comment]
Yeah I need to rework some of the schedule stuff as there are several bugs and i am not happy with the behaviour.

I am going to make the refire interval relative to the start time ... so in the case above you would fire polar hourly but have the schedule start 30 mins later.

I also plan on fixing the stop all not preventing refiring.

It may break some folks schedules but that should be a minor inconvenience.

**Comment by jholmes09** [comment]
Thanks for the feedback! I'll move on from the schedule and move to testing commands & buttons.
