### ISSUE TITLE
Lockup when selecting single color string.

### ISSUE THREAD

**Issue by dconley1964** [smeighan/xLights#1171]
Trying to assign single color to a 12 strand prop and xlights locks up.  Did a screen shot to show you.

[simplescreenrecorder-2018-06-24_15.05.56.mp4.zip](https://github.com/smeighan/xLights/files/2131123/simplescreenrecorder-2018-06-24_15.05.56.mp4.zip)

**Comment by keithsw1111** [comment]
There is no audio in the video and my attempt to reproduce the problem did not lock up.

**Comment by dconley1964** [comment]
I didn't have audio.  I'm using the Linux version.  Should have mentioned
that.  Sorry.

**Comment by keithsw1111** [comment]
Yeah because there was no audio I am not actually sure what you were doing or when it locked up so I cant be sure if there is a broader bug here or not.

**Comment by cjd** [comment]
I tried to reproduce with the version of xlights (2018.15 on linux) you were running but was unsuccessful.
Can you please re-try with a newer version (2018.22 is out now) and if it fails then grab the /tmp/xLights_l4cpp.log file so we can see a bit more about what is happening

**Comment by keithsw1111** [comment]
Any update on this ... or do i close it?
