### ISSUE TITLE
Music plays in background when end of track reached

### ISSUE THREAD

**Issue by Pfad** [smeighan/xLights#1172]
this happens either at the end of a track, or at the end of a highlighted section of the track.  When the end is reached the track will start to play with no indication.  Pausing then stopping the track works to stop it.  Went back to .16 no problem, reinstall .17 same problem though it did not immediately happen.

**Comment by Pfad** [comment]
Closed?  Did you find the issue?

**Comment by AzGilrock** [comment]
Did you download the today's release and try it before asking?  Normally if he closes without a comment it's because the fix is checked in and will be available next release but they released today.  I see an audio fix related checkin.

**Comment by Pfad** [comment]
Gil,

I did not see a resolution... that is why the question was asked.  Figuring
it is better to ask then to assume.

No I am out of town and have not loaded the .18... did not even know one
existed.

Thank you for your response, much appreciated.

Robert
