### ISSUE TITLE
Effect Assist Window Blank

### ISSUE THREAD

**Issue by Dazzled1** [smeighan/xLights#1173]
I have the Effect Assist window set to toggle so when I drop a Morph effect into a sequence it pops up but is completely blank. There is no grid and no X Y dots in the window. I checked with Keith and the windows version seems to be ok. I'm on a Mac using OSX 10.13.5

**Comment by AzGilrock** [comment]
I'm 95% sure its probably just that your model is too large.  It wasn't really meant for huge models like if you use it on a group which defaults to 400x400 you won't see the grid show up unless you enlarge the assist window to fill the screen.  Try pulling the panel out on its own and make it really big and it should show up.

**Comment by kppankratz** [comment]
The Effect Assist window is working fine for me on macOS.  I'm running 10.13.5 too and 2018.18 for xLights.  Tested on a default matrix model.

**Comment by Dazzled1** [comment]
Gil you are actually 100% correct it was the size of the model. I should have known that was the problem I must have been having a brain fade moment.

**Comment by keithsw1111** [comment]
Fake news.

**Comment by AzGilrock** [comment]
To be fair I've been wanting to rework that window so that it would still show a big model by adding zoom capability but it always seems like something else is more important.

**Comment by Dazzled1** [comment]
Hey Gil don't worry about the zoom thing just keep working on that 3D stuff thanks. LOL!!!

**Comment by adamcoulombe** [comment]
I think also effect assist window doesnt work on groups, correct?

**Comment by keithsw1111** [comment]
It does ... it depends on the effect not the element the effect is dropped on.
