### ISSUE TITLE
Xlights 2018.18_Linux version_Crash after renaming model(s)

### ISSUE THREAD

**Issue by extremeskillz** [smeighan/xLights#1175]
Updated to the latest Linux version of Xlights. It fixed issues from .14 but I'm still experiencing crashing when renaming models or groups of models. I have attached a crash log.
[xLights_dbgrpt-7312-20180627T211255.zip](https://github.com/smeighan/xLights/files/2143391/xLights_dbgrpt-7312-20180627T211255.zip)
[xLights_dbgrpt-7419-20180627T211327.zip](https://github.com/smeighan/xLights/files/2143392/xLights_dbgrpt-7419-20180627T211327.zip)

**Comment by extremeskillz** [comment]
Sounds good.

**Comment by cjd** [comment]
I've had to revert to gtk2 as backend for wxwidgets to get around this.
Builds for 2018.22 are back on gtk2 and work for renaming models again
