### ISSUE TITLE
Bug: Warp Effect - Treatment drop down

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#1177]
I noticed that when using certain warp types that every time you click on the effect in the grid, the treatment reverts back to the constant option.  Circle Reveal, Banded Swirl, Ripple and Circular Swirl all exhibit this behavior.

Dissolve and Drop reverts back to constant as well in the drop down choices, but the treatment stays at what was selected even though it reads constant.

Running xLights 2018.18 under macOS 10.13.5

**Comment by keithsw1111** [comment]
Wasn’t that fixed in .19

**Comment by kppankratz** [comment]
I compiled the code earlier today and noticed this behavior, then went back to. .18 to make sure it wasn't an issue on my end.

**Comment by keithsw1111** [comment]
Then I need a better description of the steps to recreate it.

**Comment by kppankratz** [comment]
Drop the Warp effect on to the grid.

Select Circle Reveal as the type, and then under the Treatment drop down, select in or out.

Now click the Warp effect on the grid again and you'll notice that the Treatment option has reverted automatically back to the constant option.

The three other warp types I mentioned in the OP exhibit this same behavior.  With the Dissolve and Drop types, the treatment reverts back to constant in the drop down menu, but is actually still what you had selected (in or out).

**Comment by keithsw1111** [comment]
Fixed for .20 ... there is a sequencing issue with the order in which properties were being loaded ... but we have a standard fix for that.
