### ISSUE TITLE
Version 17+ On any prop only 1 pixel lights

### ISSUE THREAD

**Issue by jspiker77** [smeighan/xLights#1179]
When using version 17+ when I drop an effect on any prop only 1 pixel lights up. This is true on the preview and the output to lights. I have a few other people test this with the same result. Attached is my packaged sequence for reference. 
[red_white_blue.zip](https://github.com/smeighan/xLights/files/2152347/red_white_blue.zip)

**Comment by keithsw1111** [comment]
I dont see a problem. The single strand works fine. I dropped other effects with no problems.

**Comment by darylc** [comment]
I can also replicate this

**Comment by keithsw1111** [comment]
Even with Daryl’s file I still can’t replicate the problem in .19.

**Comment by keithsw1111** [comment]
Maybe try a -w and reset all options.

**Comment by jspiker77** [comment]
That seemed to resolve the issue. Thanks Keith!

**Comment by keithsw1111** [comment]
I dont understand why it solved the issue and speaking with Daryl last night it didnt help his display.
