### ISSUE TITLE
Linux make failing after 2018.14

### ISSUE THREAD

**Issue by cybie257** [smeighan/xLights#1182]
I believe the last version I was able to successfully compile on Linux is 2018.14. 

I am getting the following errors. Am I doing something wrong, or is there an issue with the script? Nothing changes on my system since success and I've even tried using VMs with 16.10 clean with just git/compile tools as listed on the README.Linux file. 

Here are the errors I am getting now:
 
xLights.cbp.mak:1134: recipe for target 'out_linux_release' failed
make[1]: *** [out_linux_release] Error 1
make[1]: Leaving directory '/home/shawn/xLights/xLights'
Makefile:30: recipe for target 'xLights' failed
make: *** [xLights] Error 2

If more info is needed, please let me know. I would like to update via git/make. 
Thanks for any help with this....

**Comment by cjd** [comment]
The makefiles on linux were not updated
I have fixed this now
If you have cbp2make installed the build will automatically update the makefiles and so avoid this for when I forget to update :)

**Comment by cybie257** [comment]
Awesome! Thank you. Although, now I have an issue with libsdl2 lol. I ran this on a fresh VM install of Mint Linux 19 and it was successful. Time to update my Bare Metal Box. :)

**Comment by cjd** [comment]
The version of libsdl2 in ubuntu 16.10 was too old - I've had to stop building packages for it even (and move from debian oldstable to debian stable for the appimages) because of this.
I'll update the docs accordingly
