### ISSUE TITLE
Enhancement Request: Canvas Blend

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#1184]
With the addition of the Warp effect and the possibilities available, could the ability of allowing layers not selected for Canvas blend mode be allowed to come through or even explored further?  This was discussed under #1106 briefly, then closed.  Since that ticket I believe Dan performed some code optimization to increase the render speed for Canvas blend.  Maybe the speed increase could allow for the other layers now?

I'm attaching a Halloween sequence that's utilizing the Warp effect to have the text image "drop" away.  But because of how the Canvas blend mode currently works, all other elements of the sequence disappear.

I have tried the various blending modes to no avail. 

The effect in question is located at the end of the 15 second sequence.

[Halloween Scene.mov.zip](https://github.com/smeighan/xLights/files/2161541/Halloween.Scene.mov.zip)

**Comment by keithsw1111** [comment]
Why cant they come through ... as long as they are above the canvas ... or are you looking for the canvas blacks to not hide stuff?

**Comment by kppankratz** [comment]
When you word it that way, then yes, a way to allow the canvas blacks/background to be transparent?  Maybe a checkbox toggle to turn on and off?  A drawback I can foresee, is if the item being manipulated already has black in it (graphic/picture with transparent background).

I've attached a before and after capture of applying the Warp effect.  The entire background disappears which I'm trying to avoid, and the different layer blends are mixed results at best.  Moving the Warp effect with Canvas blend below the other effects ends up hiding the Warp effect.  The closest I can come allows the background to come through as the Warp effect is applied, but a ghost image of the original element remains.
<img width="404" alt="before" src="https://user-images.githubusercontent.com/12144876/42278262-cd7af6de-7f5f-11e8-83eb-ba441a1858d6.png">
<img width="413" alt="after" src="https://user-images.githubusercontent.com/12144876/42278269-d339d7f2-7f5f-11e8-9487-fc4ae5b20ee8.png">
<img width="406" alt="layer blending" src="https://user-images.githubusercontent.com/12144876/42278281-ddf36636-7f5f-11e8-9e79-28aa8aea0360.png">

**Comment by AzGilrock** [comment]
I'm not even sure how to use the Warp effect to help check into this.  Do you have to turn on Canvas blend more in Settings for the entire sequence?  That was my impression and why I never even considered using it because canvas blend mode causes a ton of issue and is why its not the default anymore.

**Comment by kppankratz** [comment]
The Canvas blend mode is different from the cross model blending that's located on the sequence settings window.  Canvas is used with the Off and Warp effects only to my knowledge.

**Comment by AzGilrock** [comment]
Yeah I'm asking are you doing it by going into Settings and changing "Render Mode" from "Erase Mode" to "Canvas Mode"?  A lot of folks don't know the history behind why those options exist.

**Comment by kppankratz** [comment]
The Canvas mode I'm referring to is found on the Layer Blending window.  This is not the Render Mode Canvas setting located under the Settings menu.  I always leave the Render Mode set to erase.

**Comment by AzGilrock** [comment]
Ah ok. Yeah from the start of hearing about the Warp effect I kept thinking why would anyone want to run in canvas mode.

**Comment by keithsw1111** [comment]
Try something like this

Off Layer with canvas taking layer X only and normal blend mode
Picture Layer
Warp Layer with Melt - layer X
Text Layer

**Comment by kppankratz** [comment]
From my playing around, you cannot layer multiple Canvas blend modes due to it blanking out everything below it, no matter the blend options.

Maybe I haven't stumbled upon the correct secret sauce to make this work yet?  Here's the sequence file if want to take a stab at it, if you have the time or ambition to look into this.

[Matrix Transistion Halloween 03.zip](https://github.com/smeighan/xLights/files/2164376/Matrix.Transistion.Halloween.03.zip)

**Comment by keithsw1111** [comment]
Here you go ... no change to xLights ... just the right layers and blendings.

[Matrix Transistion Halloween 03_FIXED.zip](https://github.com/smeighan/xLights/files/2169417/Matrix.Transistion.Halloween.03_FIXED.zip)
