### ISSUE TITLE
If you cancel while creating new sequence, xLights hangs (crashed once but can't repeat)

### ISSUE THREAD

**Issue by mararunr** [smeighan/xLights#119]
Had testing sequence open and was messing with it.  Went to create a new sequence (using the icon button), got to the last step and instead of hitting "done" or "close", I chose to hit Cancel and the sequence tab is just basically hung (first time I did it, got a soft crash)....will screencast and post that and the backtrace in my One Drive public folder in next couple minutes.

**Comment by mararunr** [comment]
Pertinent files here...https://onedrive.live.com/redir?resid=d05fbdc1b79cf3a9%21105

**Comment by AzGilrock** [comment]
Once that new sequence dialog is displayed the previous sequence is gone.  Looks like you are just seeing some refresh artifacts after cancelling.  To be sure drag your window off screen and back.  The New Sequence logic does attempt to prompt for a save if you've made changes but right now I don't think everyone has been marking the file as changed so you could accidentally lose work right now if you hit that button accidentally.  Not sure why yours crashed.  I've done those same steps when I was developing the ability to cancel.  Prior to creating the cancel button you were stuck with error messages if you didn't select media and chose not to create the sequence.  Try actually stopping your rendering first..hit the Stop button.  I notice you like to try to leave things playing when you do new things.  I mean I know we want fix things like that so it depends on whether your trying to cause a problem.  But if you just want to actually do work there are ways to use the program fairly crash free.

**Comment by stevegiron** [comment]
Hello, I'm helping sort the issues and determine which issues are still valid. 
As of May-14 we are version 4.0.31. Is this issue still occurring?

**Comment by mararunr** [comment]
Trivial = not important = close it.  No it does not seem to exist in the latest version.  Sorry I didn't close it earlier.  With all the beta testers, I have been spending more time on prop building lately versus sequencing.  Thanks for pointing it out.
