### ISSUE TITLE
Issues with VSA Import and Skull model playback

### ISSUE THREAD

**Issue by AzGilrock** [smeighan/xLights#1190]
This is to document a few issues with VSA import that need correcting:
1)  Import doesn't work if there are inactive tracks in the VSA file before the last active track.
2)  Playback doesn't look smooth.  If I open a sequence that worked a year ago it doesn't have smooth motion.  Need to investigate if the value curve data is not updating properly.
3)  Need to add Power to the channel assignments so it will import the command to turn on the servos.

Reference issue #1188

**Comment by AzGilrock** [comment]
Keith this demonstrates what I'm seeing.  I have a sequence from May of 2017 and I opened the same file in versions 2017.7 and 2018.20 and started playback at the same time (not exact but close).  You can see how the old one on top moves really smooth.  I'm thinking something changed with the value curves that is messing up the motion.
https://youtu.be/Y20BkuiBJhk

**Comment by AzGilrock** [comment]
I posted this on the forum but before I proceed any further we have to decide if we want to configure all the default channels so that start is 1.  That would mean the model would go from being assigned 18 channels to 26 and I  would need to add yet another tab to the DMX effect.  Also it might make it easy for a user to accidentally drop a DMX effect and twiddle those first 8 channels that are for configuration.

**Comment by skulltronix** [comment]
I wouldn’t worry too much about the first 8 channels. The board goes into config mode when the hex “DEADBEEF” is sent to fmx channels 0-7 in one command. Or maybe you can just make those channels unusable in dmx. ?   Thanks for your help. I’ll try to test it tomorrow.

**Comment by AzGilrock** [comment]
Ok to be clear the 2018.22 release has fixes for the VSA import but I have not moved the default channel assignments yet.  I needed another day to get the work done.

**Comment by skulltronix** [comment]
Thank you!  I’ll be testing in an hour!

**Comment by skulltronix** [comment]
I'm back!  Well... good news and bad news.  The import effects now works. But the animation using 50ms is very choppy.
I tried importing to a 20ms sequence and it was much worse.  
In VSA I tried changing the vsa Timing Settings from 33ms/f to 50ms/f and got similar results. In fact, VSA would not open the jaw at all when set to 50ms.  
I'll look for an option in xlights to use 33ms/f.

**Comment by skulltronix** [comment]
Update... I tried creating a new sequence from scratch using the 33ms and get the same choppy behavior.  So it isn't a simple issue of frames per second.  I'll try switching from Open to Pro DMX adaptors. :(

**Comment by skulltronix** [comment]
Pro DMX was slightly smoother.  But no cigar.  Here are two videos. In the VSA example the mouth closes after the word "begun". In the xlights example it stays open.
 
https://www.dropbox.com/sh/xvmgak2wxaoj6ds/AAD2fapXCFf-QBOYlJ3xPcMya?dl=0

**Comment by skulltronix** [comment]
BTW, that dropbox  link has all the files I'm working with.

**Comment by skulltronix** [comment]
Interesting. In the VSA routine the jaw track event that closes the mouth at that exact point has a value below the minimum value of 500.  VSA just sets it to the minimum. Perhaps xlights is just tossing the event all together.  I'll try setting the xlights skulltronix jaw values to a wider value to see if it passes the data, If it does, then the BOC board limits will take care of trimming it.

**Comment by skulltronix** [comment]
Progress!  I changed the jaw settings in both vsa and xlights to 250-1250 and eliminated the "exceed limits" error.  Now the jaw closes after the word "begun".  So my suggestions is to not trim values out of bounds,  just let the boc/soc boards do that.  
Now I'm getting jerky pan motion and I'm pretty sure it is a frame rate issue.   I'll try again with the 33ms timing now that I have the jaw issue fixed.

**Comment by skulltronix** [comment]
33ms didn't fix the issue of jerkiness.

**Comment by skulltronix** [comment]
Not sure what happened in the last two minutes but suddenly it is working ok.  Even with the Open interface.  Whew.... 
Now to move it to the Pi/picap.

**Comment by AzGilrock** [comment]
Even though you are selecting a Skulltronix Skull in the DMXModel that does not mean every user is using a Skulltronix skull so I'm still going to honor whatever servo limits the user enters because I don't want xLights responsible for causing damage.

By the way when I import the effects from a VSA file 33ms is a hard-coded multiplication because I don't remember there being a field I could read.  If I can determine the timing from the bytes read I need to know which bytes define the timing.

**Comment by skulltronix** [comment]
Hi
I understand your first comment and can live with it. But it looks like you are tossing values out of range, not trimming them.  Is that right?  

I’m not familiar with the xlights file format but I know someone who is. I’ll reach out and let you know. 

I really appreciate all your help on this. Thank you!

**Comment by AzGilrock** [comment]
1)  No I'm not tossing them out.  I convert to a percentage and if it's less than zero I set it to zero and if its greater than 100% I set it to 100%.
![image](https://user-images.githubusercontent.com/2024669/42426263-77709f80-82db-11e8-9e4b-b69cc6c28612.png)

2)  Did you mean to say VSA file format?  I know the xLights format. ;)

**Comment by skulltronix** [comment]
Hi. I have contact info for getting the answers about vsa file format. He will share with Gil only. I have no contact info for Gil. I don’t see a way to message privately on github.

**Comment by AzGilrock** [comment]
Go back to the post in the xLights forum.
![image](https://user-images.githubusercontent.com/2024669/42428539-f8b146f0-82e8-11e8-891e-bbaf506bce40.png)

**Comment by skulltronix** [comment]
Thx

**Comment by AzGilrock** [comment]
I actually figured out where the timing byte is on my own.  What's funny about only wanting to share with me is that now anyone could technically look in the xLights source code right here on GitHub and pretty much figure out the VSA format since I have a nice class designed that reads it.  I'm not reading every single piece of the file but I've got it figured out enough to skip over the parts I didn't need like the audio and video sections.

**Comment by skulltronix** [comment]
He doesn't want to keep it a secret, he just doesn't want to be swamped with questions.

**Comment by AzGilrock** [comment]
Yep I can understand that.

**Comment by AzGilrock** [comment]
So if you want all the checkins I did yesterday I'm afraid you'll need to go find another must fix bug in the program.  Otherwise very few people want/need my changes and they are trying to lock down which version will be the one that goes into the Expo.

**Comment by skulltronix** [comment]
It’s working fine now except for the power issue. I should be able to fix that by adding another dmx model. 
I usually have to turn power on by running a vsa routine that leaves the power on at the end of the routine and then run the xlights routine before the self shutdown timer runs out. One minute.

**Comment by AzGilrock** [comment]
The power channel is now included in the default model but you either need to build the code yourself or wait for next release.

**Comment by AzGilrock** [comment]
In fact I tested doing the import of the power channel and it worked.  The only hiccup was the I Like Nightmares file had the power channel named "Power 7" so my channel name matching code did not find it and you have to manually fix it in the import dialog.

**Comment by skulltronix** [comment]
Thank you!  I can wait!  :). 
Btw, I’ve bedn using the import for simple 3 servo animatronic characters so far. Just jaw, nod, pan. 
FYI, it is common in vsa to use waveform analysis to generate the movements. But to get the movements to look good I often have to tell vsa the movement ranges are outside the actual ranges limited by the board and xlights settings. Which simply means a lot of values get trimmed by the board/xlights. It’s just the nature of the waveform analysis.

**Comment by AzGilrock** [comment]
Jerry those servo limits are user-defined in xLights so feel free to make it whatever you like.  I just set the defaults to be what came with my board but you can change them.
