### ISSUE TITLE
rendering issue

### ISSUE THREAD

**Issue by Djnathan1983** [smeighan/xLights#1191]
One of my songs will crash each time I try to render. I will attach the crash log.
[xLights_dbgrpt-888-20180708T203353.zip](https://github.com/smeighan/xLights/files/2174336/xLights_dbgrpt-888-20180708T203353.zip)

[backtrace.txt](https://github.com/smeighan/xLights/files/2174337/backtrace.txt)
[notes.txt](https://github.com/smeighan/xLights/files/2174338/notes.txt)
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/2174339/xLights_l4cpp.log)

**Comment by keithsw1111** [comment]
For some reason I cant reproduce this problem in .22

**Comment by Djnathan1983** [comment]
Ok I will update tonight and see if that fixes it. It’s the only sequence that crashes it. Even downgraded to .11 that I last used it on and it crashed as soon as I hit render.

**Comment by keithsw1111** [comment]
Update? According to the log you were already on .22 ... maybe there is something else in your environment causing the issue other than the sequence itself ... or maybe interacting with that effect in that sequence ... really not sure what though.

**Comment by Djnathan1983** [comment]
Sorry I was thinking I was still at .21. I ended up deleting the file and saving a new one from last year's sequence and that took care of the problem. Thanks
