### ISSUE TITLE
Shape Effect Emoji Glitch

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#1196]
While playing with the Shape Effect built-in emoji font I noticed there is a glitch when the size value of 70 is reached.  In the attached video I applied a simple value curve to the size from 60 - 80 and whenever 70 is displayed the emoji gets really small on the screen then jumps back to the size expected.

Is this a bug within xLights or the emoji font itself?

Running macOS High Sierra 10.13.8 & xLights 2018.23

[Emoji Glitch.mov.zip](https://github.com/smeighan/xLights/files/2243259/Emoji.Glitch.mov.zip)

**Comment by keithsw1111** [comment]
I cant reproduce it ... maybe share with me your sequence.

**Comment by dkulp** [comment]
It's a bug in wxWidgets:

https://trac.wxwidgets.org/ticket/18185#ticket

**Comment by dkulp** [comment]
Note: the Text effect is also effected.  No fonts of size 70 work.

**Comment by kppankratz** [comment]
Thanks for looking into this.  Hopefully it will get fixed.
