### ISSUE TITLE
Bug: Render Cache & Pictures Effect

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#1199]
I noticed when the Render Cache is enabled, the transparency of the images I'm using get all funky.  I've attached two images showing the change with the setting and the packaged sequence.

Running v26 and macOS.

<img width="404" alt="screen shot 2018-08-10 at 5 32 18 pm" src="https://user-images.githubusercontent.com/12144876/43984681-a08e190a-9cc7-11e8-8a60-b30e19b7c6f1.png">
<img width="410" alt="screen shot 2018-08-10 at 5 31 38 pm" src="https://user-images.githubusercontent.com/12144876/43984683-a37822be-9cc7-11e8-83f5-4b169ec44353.png">
[Archive.zip](https://github.com/smeighan/xLights/files/2279691/Archive.zip)

**Comment by kppankratz** [comment]
[Matrix Transistion Halloween 01.zip](https://github.com/smeighan/xLights/files/2280310/Matrix.Transistion.Halloween.01.zip)

**Comment by dkulp** [comment]
Fixed in 9842f2b056f8a6d6d722a5b9c45dd4794953d359
