### ISSUE TITLE
Crash on trying to load Steve Gase's 6,000 effects xml

### ISSUE THREAD

**Issue by mararunr** [smeighan/xLights#120]
Found this post from last December where Steve Gase created a 6,000 effect xml.  Tried loading it into xLights 4 (renaming his MegaPixelTree50 to my t1_megatree1) and using Mr_Roboto.mp3 as media file.  Get conistent crash every time.  Debug (9:07pm timestamp) is in my public OneDrive folder along with the merged.xml

**Comment by smeighan** [comment]
those 6000 effects did load in xlights 3.6.x, but xlights 4.0 is a complete rewrite into the guts of the rendering engine. Why not try 100,500,1000,3000 effects and let us know at what value ti fails. Most people will not have 6000 effects. You might take a look at the memory consumed with the various sizes.

**Comment by mararunr** [comment]
Fair enough.  I'll try editing the xml down and check it out.  I just found something to stress test and gave it a whirl.

**Comment by dkulp** [comment]
I'm able to load the file fine.  It takes a VERY LONG time to load and convert (2 minutes or so) during which xLights is completely unresponsive (the v3 converter is not threaded), but it does work.

**Comment by mararunr** [comment]
wontfix = close it.  This was from alpha testing - was just trying to stress test.  Haven't tried recently.
