### ISSUE TITLE
Bulk Edit memory overflow

### ISSUE THREAD

**Issue by madsci1016** [smeighan/xLights#1202]
Bulk edit on a model group with a superstar import (meaning hundreds of effects across 50 rows) results in a memory overflow till the PC crashes. 

Version 2018.27

Video of crash and how to trigger it: https://www.youtube.com/watch?v=zTt82UAdVZE

Package Sequence:
[LightsofChristmasDebug.zip](https://github.com/smeighan/xLights/files/2281079/LightsofChristmasDebug.zip)

**Comment by madsci1016** [comment]
Selecting smaller portions (40 rows by 30 seconds) RAM jumps up to 12 GB but it then recovers and completes the operation.

**Comment by madsci1016** [comment]
Log looks like a clue. 
![rendercrash](https://user-images.githubusercontent.com/1082294/44005674-d05dbc96-9e3c-11e8-81dd-049b50159a84.PNG)

I'm guessing the bulk edit is touching every effect, which then fires off a render for every effect and takes up memory for the render cache. Maybe don't render during bulk edits?

**Comment by keithsw1111** [comment]
Yeah nah. Render Cache doesnt work that way. To try to prove it turn it off.

**Comment by keithsw1111** [comment]
Also render cache wont give it back until the sequence is closed.

**Comment by madsci1016** [comment]
So what takes and gives memory during bulk edits?

**Comment by keithsw1111** [comment]
Not sure but not render cache ... the 8000 frames is not surprising. render inflation occurs when you have long running effects on groups which overlap with models.

**Comment by madsci1016** [comment]
Could this be fixed by not rendering during a group edit change?

**Comment by keithsw1111** [comment]
This could be fixed by actually analysing what is going on rather than guessing a fix. Give me time to look tonight.

**Comment by madsci1016** [comment]
Assuming you figured it out? What was it?

**Comment by keithsw1111** [comment]
We were firing render events for each effect changed ... but the render loop was not consolidating/cancelling overlapping events so we ended up with lots of parallel renders when one would have been enough. I didnt get to the bottom of the memory usage (for other reasons) but by consolidating the renders into a single render the problem resolves itself.
