### ISSUE TITLE
3D OSX Bugs

### ISSUE THREAD

**Issue by zcloutier** [smeighan/xLights#1203]
I’ve come across a few issues on the OSX build where the viewpoints in the sequencer side won’t change to the saved ones i created in the layout view, also the render style doesn’t seam to be working properly it sonly applying to some of my models in my whole house preview, lastly i can’t seam to get the blended circle to rotate 90 degrees to sit on the end wall of my house I’ve tried a couple of different models but still nothing. Also is there going to be an option where you could dim the green grid like how we can dim the background image?

Files:
http://3dxlights.cloutierchristmaslights.com

Videos:
ViewPoints- https://vimeo.com/user88392982/review/284777289/4beec2d4a1
Render Style- https://vimeo.com/user88392982/review/284783295/16c702bee3 
Floods- https://vimeo.com/user88392982/review/284782705/1b04db3f9f

**Comment by AzGilrock** [comment]
Vimeo links aren't working for me.  I'll try again from my home PC later.

**Comment by zcloutier** [comment]
Sorry here are some different links not sure why those didn't work that is what vimeo gave me when i uploaded them.

Videos:
ViewPoints- https://vimeo.com/284777289 
Render Style- https://vimeo.com/284783295 
Floods- https://vimeo.com/284782705

**Comment by AzGilrock** [comment]
So the Flood issue I believe is common to all pixels we draw.  When you make them bigger in appearance they are not inheriting scale or rotation values.  That is something we need to fix.  Dan had already documented the scale aspect of this but I didn't realize it also included rotation.  I'm typing up issues like this over in the project cards so others can read them in one spot to know what we've found.   Still looking into the other issues.

BTW if you use the DMXModel and select the Flood light option it does honor the rotation.  I remember spending time on that.

**Comment by zcloutier** [comment]
No it doesn't jump it just moves like if I didn't try to change it. Also my floods are ws2811 so the DMX option won't work for those.

**Comment by AzGilrock** [comment]
Well technically you can run ws2811 with the DMXModel but currently only On and ColorWash effects work.  We probably should make it where all effects would do something.  You just tell the DMXModel it's 3 channels and set red=1, green=2, and blue=3.

**Comment by AzGilrock** [comment]
Ok I found the RenderStyle problem.  I wasn't properly handling groups within groups.  I had it clearing out the nodes when it encountered a model group when creating the render buffer so if you had nested groups it was running into a group partway down and then blowing away all the previous nodes.

**Comment by dkulp** [comment]
All 3 issues should now be fixed.
