### ISSUE TITLE
3D Ground Level Enhancement

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#1204]
Add the ability to be able to turn on/off the ground level green grid, particularly on the house preview window.  Perhaps add the ability to change the color too.

**Comment by AzGilrock** [comment]
Yep already on my radar with something I'm working right now.  There will be many type of "view" objects you will be able to add.  The initial one is an image object which will be used for having ground images or house images.  I was going to make this grid another type of user placeable object.  In all cases you will be able to drop down an unlimited number of them and translate, scale, and rotate them.

I'm going to close this and move the idea onto the project cards.
