### ISSUE TITLE
3D Custom Model Enhancement

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#1205]
I didn't see this on the To Do list, but thinking a new model for making custom 3D models would be useful for some of the props that people have (Boscoyo's ChromaGlow Presents, wire frames, some of the unique balls/spheres, etc). 

There might be a better way to do this, but I was thinking somelike like the attached image where the user defines the number of pixels, and then inputs the X, Y, and Z of each point.  Would be nice if it could show the 3D model as you do that, with the ability to rotate around to view it too, but not sure if that can be done or not.  

![image](https://user-images.githubusercontent.com/17793531/44106675-4eb00cde-9fc3-11e8-8127-938c07dfd00b.png)

**Comment by AzGilrock** [comment]
Yeah technically all we really need is a helper editor window for the PolyLine model.  It already has all the capabilities to accomplish this.

**Comment by deplanche** [comment]
From what I was seeing with the polyline, the location of the pixels are based on a line segment which is between two points, with the number of pixels evenly distributed on that line segment.   What I was thinking with the above is a way of putting a single pixel at the points rather than on a line between the points.   There might be a way to do that with the polyline already, but I wasn't able to figure that out.   The helper window might take care of that.
