### ISSUE TITLE
Model and House Preview Middle Mouse Button Move Bug

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#1206]
On both the House and Model Previews, if you are holding down the middle mouse button to move the model(s) around, and accidentally drag it off the preview window, the window "remembers" that you had the middle button pressed.  This means that if you go back over that window with the mouse, the models move around as if they are still selected.  If you are not over those windows, everything still seems to function normally.  Probably not a problem for most, but if you don't realize that you were middle clicking and dragging, you can't get that to stop moving the models around in those windows unless you middle click.  Other mouse buttons or ESC don't stop it.  

The video shows this as best I could, but if you have questions let me know.  

I did have this issue happen to me before I realized the middle button was used for moving too.  So I am not sure if the locked movement with the mouse can be triggered in other ways too, or if I just happened to click on that without realizing it and then couldn't repeat the problem.

Thanks.

[zoom_1.zip](https://github.com/smeighan/xLights/files/2289041/zoom_1.zip)

**Comment by AzGilrock** [comment]
Thanks...yes its happened to me a few times.  I was probably always busy with something else so I never tackled it.
