### ISSUE TITLE
3D revD Mac - Sub models not showing if off "green grid"

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1207]
so I notice if I move my entire layout off the green grid and to the left so the back area is my ground and background that a few of my sub models no longer work

you can see in the video below that I render a sequence (happens in a few sequences so not just this one) and play it everything looks fine, I then go to layout and move the models off the green area, save it, render again and play and half of my sub models do not show anymore.. 

also you can see in the video at times on the Mac version I can not click and drag the 3D area around , it jumps all over, again you will see what I mean in the video

Video -  http://youtu.be/gSXBai_6wD0?hd=1

packaged sequence - https://drive.google.com/file/d/15izEG9RKsGPlcFJ_vRkdtgbP5Jty3D2N/view?usp=sharing

please let me know if there is anything else you need

**Comment by AzGilrock** [comment]
I can't dig too deep into this right now but a couple questions.  Are the submodels having problems inside model groups?  I've already said we have some render buffer issues to fix for model groups.  Where you using a Per Preview render style?  2D or a camera?

When the display wouldn't rotate was it rendering over on the grid?  Does the movement ever mess up when no sequence is open?

**Comment by AzGilrock** [comment]
You won't be able to move the House Preview without a sequence open.  It needs an active effect on the grid currently.

So you are dropping effects directly on the submodel and not a model group containing the submodels?

**Comment by bchiaino** [comment]
thanks Gil, even with a sequence loaded the movement is really delayed, I can click and drag right and like 30 seconds later it finally moves

the effect is dropped right on the models submodel, I hope I'm saying that right, lol.. I did another quick video for you to show how I have it on the sequence 

http://youtu.be/Rdtc0YjRHkc?hd=1

**Comment by AzGilrock** [comment]
Well try a mouse.  You see how nice it works on my PC.  If its still bad maybe you have a 2D machine.

**Comment by bchiaino** [comment]
I meant when I was having the issues in the last video trying to "shift" slide to the left I couldn't and I was using a trackpad, I know with a mouse you can center click the track wheel to move it left and right

the machine I am on is a 2017 MacBook Pro, 2.5 i7 with 16gb of ram and 1tb of storage so im sure it can handle most stuff thrown at it, lol..

**Comment by AzGilrock** [comment]
Apparently not.

**Comment by bchiaino** [comment]
maybe Dan can mess with it on his end on his Mac, what will the minimum specs have to be then LOL

whats weird is sometimes I open it and everything is smooth and then later that day it will be locking up trying to spin

**Comment by AzGilrock** [comment]
I just loaded your sequence and the preview motion is very fluid for me.

**Comment by bchiaino** [comment]
ok cool, and sometimes it is for me too but other times like you see in the video its very delayed, Maybe something on just a Mac end... Most of the day today when I was playing at work it was great and then once in a while it was moving like 20 seconds at a clip after I click and drag. Once im at work tomorrow ill try and see if can test more and see if theres and steps that are being done that are maybe triggering an issue

**Comment by bchiaino** [comment]
should I make a separate post for the house preview issue with a better video?

**Comment by AzGilrock** [comment]
I expect things to get better as we go and if its a problem for Dan he will find a cure.

No don't need another post.  I'm not really gonna spend too much time until after I fix our render buffers and make sure that's not the issue.

**Comment by bchiaino** [comment]
ok awesome! thanks again Gil!

**Comment by bchiaino** [comment]
Hey Gil, just to add something, this morning when I got into work I opened revD again and it was freezing on the house preview but whats interesting is I closed D, opened REV-C and everything is smooth as can be, went back to D and thats smooth too so definitely something strange. Just wanted to let you know in case you were passing info along

**Comment by AzGilrock** [comment]
Ok.  I'll just add that even after we have things fixed how I want them you are not going to be able to drag all your junk off away from the preview origin and expect things to work the same in a Per Preview 2D effect.  Think about it how does a Per Preview effect determine the size of the buffer.  It's always been based on those width and height values where you put the Background image in layout.  Whenever you use Per Preview 2D its expected you still have a layout in 2D mode that looks like it used to but we do try make sure things don't blow up.  If you start placing stuff outside your defined 2D width and height boundaries they are not going to work.

**Comment by AzGilrock** [comment]
Yeah when you use camera viewpoints we are forcing everything into a 400x400 buffer.  The 2D Per Preview needs to be fixed because now that the playground is unlimited size I've seen render buffers for Per Preview come out near 4 million pixels.  So that's why people might see some effect rendering slowness.

**Comment by bchiaino** [comment]
gotcha ok, thanks for the info.

**Comment by bchiaino** [comment]
one last test I did gill and did a video for you guys, I noticed that if im playing the actual sequence then I can freely and fluidly move the house around and so on but once I stop the sequence then it freezes me from being able to move anything.

here is a video showing it - http://youtu.be/cycubCGhX4Y?hd=1

**Comment by AzGilrock** [comment]
I don't need a video I thought I had said that before.  It currently needs an effect render loop to be causing updates.  I have a way to make it move when rendering is not updating but then it causes a bunch of annoying flashing as you move the scene.  Everything flashes white every time it updates while you are dragging.  So right now it was a pick your poison and chose to make it look good but only update when rendering is occurring.  If we find a better way it will change.

**Comment by bchiaino** [comment]
gotcha, ok, thanks!

**Comment by AzGilrock** [comment]
I think everything we discussed here has been handled except maybe some lag that was happening on the newer MacOS.

**Comment by AzGilrock** [comment]
Ok I'll close this one.  I forgot I was supposed to try to load your layout from the other issue.  I"ll try to remember that tonight.

**Comment by bchiaino** [comment]
awesome, thanks.
