### ISSUE TITLE
Crash Report from Sub Model Edit

### ISSUE THREAD

**Issue by DGHayes** [smeighan/xLights#1208]
[xLights_dbgrpt-39812-20180816T215831.zip](https://github.com/smeighan/xLights/files/2293610/xLights_dbgrpt-39812-20180816T215831.zip)

**Comment by AzGilrock** [comment]
We don't really need crash reports posted here unless you are going to add some useful information along with it.  We already get the crash reports loaded to a server.  If you can't reproduce it yourself and tell us the steps then we are left with just looking at what function crashed and we can do that without seeing this posted.

**Comment by AzGilrock** [comment]
So at least give us a model name so we know where to look for the submodel.  Many users are doing that same operation without crashing so its something specific with that one.

**Comment by computergeek1507** [comment]
looking at the log, it looks more related to rendering, not the renaming of sub-models

**Comment by keithsw1111** [comment]
So you are editing submodels while the sequencer is trying to use them to render onto ... I wonder why that might crash. Its kind of like changing the oil while driving down the freeway.

**Comment by keithsw1111** [comment]
Although from the log that doesnt look like what happened. It looks like you clicked on a single strand effect on PPD Mini Trees at the 34.3 second mark.

**Comment by DGHayes** [comment]
Yes, its happended a few times Keith, edit the submodel, go back to sequenceing, click on the single strand to sequence, and crash. It was always after editing a submodel, which was the poly line(s).
