### ISSUE TITLE
Skew Audio Track

### ISSUE THREAD

**Issue by DGHayes** [smeighan/xLights#1209]
Hi Keith,
Would it be possible to add a feature, so the audio track can be moved left or right like the shift effects? I believe its called skew track in LOR.  
Reason for request is that I have had issues importing sequences from the USA (PPD) as the MP3’s that accompany the sequence are not able to be downloaded from Amazon. 
When you purchase an MP3 from a different site, the length may often be different, thus it does not match the imported sequence.
Using the shift effects will move the sequence but not the imported timing marks, so the timing becomes useless.
The workaround is of course to import the MP3’s into an audio editor and shave off the required dead space and re-import and see if the audio now matches the sequence/timing marks (tedious).
Talking to Rob and Clyde at PPD, they do the same thing and in discussing this they said a skew audio track was in LOR feature and makes it easy to align the song to the imported timing marks and sequence, thus saving audio track edit time,

**Comment by AzGilrock** [comment]
I wrote the Shift Effects code so that's why its best to not address any particular developer.  This is come up before and didn't change so not sure Keith has had a change of heart.  I've always felt why not adjust effects to the audio instead of the other way around.  Are you saying Shift Effects does not move your timing marks?  Maybe that's what needs to be fixed I would have thought we were already moving them.

**Comment by keithsw1111** [comment]
I thought shift effects moved every thing ... timing marks included. There is also a shift effects that just works for a single row on the sequencer grid ... but it does just as advertised. I agree with Gil if it isnt moving timing marks that is the bug but from memory it does.

We are not going to skew the audio. That is a can of worms that impacts all sorts of things negatively.

**Comment by DGHayes** [comment]
I'll retry the select all effects and move effects to confirm guys... Not unless I missed somthing to select timing marks somehow?

**Comment by keithsw1111** [comment]
Move all effects in the edit menu does not require you to select them. Move selected effects does require you to select them.

**Comment by DGHayes** [comment]
Yes, the timing marks also move when you, as you say Keith use the Move all effects in the edit menu. I think I was doing it wrong by selecting all effects!
