### ISSUE TITLE
House preview screen in the sequencer tab version 4.0.10

### ISSUE THREAD

**Issue by RichardRennII** [smeighan/xLights#121]
I am getting duplicate models in the lower left side of the House preview screen being used in the sequencer. I noticed it in 4.0.9

![image](https://cloud.githubusercontent.com/assets/11212370/6933294/16ecc7d8-d7f3-11e4-9c1b-1ada2e0bc927.png)

**Comment by smeighan** [comment]
That is the whole house preview got the "Part of My display" turned on. It should never be on in the preview window. Select the whole house preview (it turns yellow), right click and click "Model properties". Unlick "Part of my display"

**Comment by RichardRennII** [comment]
I forgot I even had that checked Thanks Sean
