### ISSUE TITLE
Sound wave marks not saving

### ISSUE THREAD

**Issue by dszoka** [smeighan/xLights#1210]
MAC 2018.27

Marks save, but when you close xlights and reopen they all move to the start of track 

[Video ](https://drive.google.com/open?id=1zu5IDZmF1gG--5804lFv702Nx4Z_g5nT)

**Comment by keithsw1111** [comment]
What are you opening the fseq?

**Comment by dszoka** [comment]
Yes.. I’m opening the fseq file

**Comment by keithsw1111** [comment]
But why?  Does it work when you open the XML.

**Comment by dszoka** [comment]
Just tried XML file, same problem

**Comment by AzGilrock** [comment]
I just watched this video cause I mainly wanted to know what a sound wave mark was...lol.
The issue I see is apparently on MAC the filters are not working when you get the Open File dialog.  It's supposed to filter it down to only XML files like it does on Windows:
![image](https://user-images.githubusercontent.com/2024669/44301599-d37dcd80-a2ce-11e8-8b59-1a61b348f1ba.png)

**Comment by AzGilrock** [comment]
Cause you really shouldn't be opening FSEQ files.  That was something that is only there to support older xlights 3 features.

**Comment by dszoka** [comment]
Thanks guys... I’ll make sure I open XML files only
