### ISSUE TITLE
Submodel Subbuffer box not resizable

### ISSUE THREAD

**Issue by brianweb16** [smeighan/xLights#1212]
I am on a Lenovo Yoga 13.9" laptop running 1920 x 1080.  When I try to set a subbuffer in a submodel, the left hand side handles are not on the screen and not able to be used.  Can a reset button be added to resize the yellow box to the size of the black work area?

<img width="960" alt="subbuffer box 2" src="https://user-images.githubusercontent.com/24864433/44294897-9ed92a00-a26c-11e8-88f4-a4f8273ccae2.PNG">
<img width="960" alt="subbuffer box" src="https://user-images.githubusercontent.com/24864433/44294898-9ed92a00-a26c-11e8-9236-bd8eeef21f5c.PNG">

**Comment by AzGilrock** [comment]
Double-click inside the black area...it resets.
