### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by thespica93** [smeighan/xLights#1218]
I’m not sure this is the right spot because I am new to this. I am asking for a feature request. Is there a way in XSchedule to make my sequence stop at an exact time. I know I can run a stop all command after so many seconds. But I have a few playlist in loops, etc. and the timings dont seem to be working properly. I have the lights in a step to go on at 730 pm and scheduled to turn off after 16200 seconds but the timing is off. The lights stay on way past midnight. So I think a command to turn off at a specific time based on the xlights clock would be useful. 
Thank you. 
-Nick

**Comment by keithsw1111** [comment]
Why not just create another playlist with a single step that issues the stop all command and schedule it at the time you want the show to turn off and make it a higher priority. Done.
