### ISSUE TITLE
Bug? Layout - Distribute Horizontal

### ISSUE THREAD

**Issue by JP-Jackson** [smeighan/xLights#1219]
I didn't see this as a current issue so, here it goes... I found that distribute Horizontal does not seem to work when I select multiple models in the Layout using the "CNTRL + Click" method. It works if I select multiple models using "Click + Drag" method.
See short video here:
[https://youtu.be/ftbGFwyxC1Y](url)
Thank You, 
JP

**Comment by AzGilrock** [comment]
All the alignment and distribute logic has changed for the 3D update coming soon so I'd rather nobody go touching this code because it will just make merging it with the 3D branch more of a mess.
