### ISSUE TITLE
Not able to delete models in sequencer

### ISSUE THREAD

**Issue by DanJacobsen** [smeighan/xLights#122]
I am able to add models in sequencer but when I click on delete models, there is nothing available in the popup so I am not able to delete any models     danj on NC forum

**Comment by mararunr** [comment]
Have you tried clicking "show all" first.  That box comes up empty at first but if you hit "show all" it will display the models you have added to your sequence.  Then you can select one and hit delete.

**Comment by DanJacobsen** [comment]
As noted on the forum last night this seems to be specific to this one file.   I can add & delete models "at will" in my other files.

**Comment by DanJacobsen** [comment]
I am showing my total ignorance of github....  I accidentally closed this one.  I re-opened the file and clicked "show all". That may have done the trick...    I am now  seeing all models to add or delete.  I will keep playing around with the file

**Comment by AzGilrock** [comment]
You gotta select the models before you hit the delete button.
