### ISSUE TITLE
Snap to timing marks. 

### ISSUE THREAD

**Issue by ebuechner** [smeighan/xLights#1221]
I have the snap to timing marks feature enabled and I've noticed that it's not accurate until you zoom in on your timing grid. 
I've dropped an effect on to my timing grid before I fully zoom in then try to adjust it, to find when I zoom in on it that it's not snapped to the timing mark.
I've also had effects dropped on and adjusted that overshoot the timing mark slightly then when you drop your next effect on it makes the previous effect disappear.

**Comment by AzGilrock** [comment]
Yeah its probably nothing to do with accuracy its either snapping or it isn't.  It's got to get within 10ms to snap.  I just created a sequence with a 3.5 minute song and it snaps just fine fully zoomed out.  If you do something like create really short timing marks you are always going to need to zoom in a bit to work with them because there isn't even enough room for the all the hotspots on an effect.  You need to show a picture of this so we can see song length and timing durations.

**Comment by ebuechner** [comment]
Okay, that makes sense.
Breaking this down just a little further, all of my sequences are set at 25ms and when zoomed out it doesn't seem to want to hit all the timing points until I zoom in making it so that I can't get it within 10ms.
It seems to fight me and want to skip four or five points. This seems like newer Behavior to me but I should mention I also got a monitor recently with a higher resolution.
Could the monitor and or driver be what I'm fighting?
This is also making it harder to fine-tune the placement of effects outside of the timing marks until I zoom in.

**Comment by AzGilrock** [comment]
Yes I think if you made a video it would help me see what you're experiencing.  It's possible we could adjust that hard-coded 10ms range based on zoom level it just seemed like it was working at all zoom levels for me so that's where I left it.

**Comment by ebuechner** [comment]
https://youtu.be/-zGW7ta1doQ

**Comment by ebuechner** [comment]
https://drive.google.com/open?id=1D_pW_jWwIG_GpdXHoRlPmIcj3vAyR--n

**Comment by AzGilrock** [comment]
I probably only needed to know the 25ms and what durations the timing marks were spaced.   I already see what's wrong.  The effect resize function takes a position value and not an absolute time so in certain situations the calculated pixels doesn't fall on the timing mark.  I'm probably gonna need to rework it so I can call the function with the absolute time value.
