### ISSUE TITLE
Crash - after updating universes and ports ran "TEST"

### ISSUE THREAD

**Issue by darylerwin** [smeighan/xLights#1223]
v30
Note  I did not have controller hooked up at the time.

[xLights_dbgrpt-8936-20180826T215623.zip](https://github.com/smeighan/xLights/files/2322145/xLights_dbgrpt-8936-20180826T215623.zip)

**Comment by darylerwin** [comment]
also ran check sequence a number of times as I move my universes and ports.

**Comment by keithsw1111** [comment]
What were you actually doing when it crashed? I opened up test panel and it didnt crash so without more information I am going to have to close this. Can you reproduce the problem. Can you be specific about the steps you followed.

**Comment by darylerwin** [comment]
Hard for me to duplicate this as I was moving things around my layout changing universes and running check sequence a number of times. Perhaps that is the route of the issue .. check sequence leaking?  I will keep an eye out..

**Comment by keithsw1111** [comment]
Check sequence is not related to this issue.
