### ISSUE TITLE
30-1 does not work.

### ISSUE THREAD

**Issue by dconley1964** [smeighan/xLights#1225]
Installed the latest update yesterday (30-1) and it does not run.  xcapture and xfade run, but xlights and xschedule do not.  Restored to version 25 and all is well again.  Running Linux Mint 19 Tara.

**Comment by AzGilrock** [comment]
I'm not sure where the log4cpp log is stored on Linux but we would need to see that to know where in the startup process things are halting.

**Comment by dconley1964** [comment]
I'll try a reinstall if I can locate that log file and send it.

**Comment by AzGilrock** [comment]
You might just be able to pull up the log from within version .25.  I don't believe we erase anything so the old boot messages should be there.

**Comment by cjd** [comment]
Are you running xlights from the ubuntu ppa or the appimage?

**Comment by dconley1964** [comment]
ppa.

**Comment by cjd** [comment]
Whoops - that build looks to have only had a partial fix for some logging issues.
I am building 2018.30.1 now which should fix that

**Comment by cjd** [comment]
2018.30.1 is built now - can you please re-test with that release?

**Comment by dconley1964** [comment]
Just updated to the fixed release.  It appears to be working fine now.
Thanks.
