### ISSUE TITLE
xCapture crashes when designating universe range (Windows)

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#1226]
Please see zipped video (attached).
The audio quality is not great so let me summarize:

xLights 2018.30
Windows 10

Attempting to "Add" a universe range in xCapture will crash the program.
Pressing the add button opens the dialog box but upon pressing "OK," the program dies.

This was discovered while attempting to capture sACN from my own computer.
I have tried outputting both multicast & unicast sent to my computer's IP and the 127.0.0.1 loop back.
xCapture does not see any universes though my other SACNViewer app acknowledges the data. One of Keith's videos suggested this was because I needed to specify specific universes but, due to this crash, that is not possible at this time.

[xCapture_Crash.zip](https://github.com/smeighan/xLights/files/2329106/xCapture_Crash.zip)

**Comment by keithsw1111** [comment]
Does it crash when you dont have the viewer running. Generally only one thing can listen to a particular data stream at a time. It shouldnt crash but that would explain why you are ending up in some poorly tested code. Is the data unicast or multicast?

**Comment by jholmes09** [comment]
Yes. The viewer was the last thing I added simply to determine whether any data was being received/sent at all.

I have tried sending the data both Unicast & Multicast, though I am not entirely sure what the IP address should be, hence why I tried my own (192.168.33.15) and the loopback (127.0.0.1)

**Comment by keithsw1111** [comment]
Ok ... so not sure if i have fixed it. I have added some error checking on the creation of the listeners so you may now get an error if it cant listen. Try it out in .31 and let me know how it goes.

**Comment by keithsw1111** [comment]
Any update on this one?

**Comment by jholmes09** [comment]
Looks good :)
