### ISSUE TITLE
Crashes when opening Large Model/Group on Layout Page

### ISSUE THREAD

**Issue by TomL8345** [smeighan/xLights#1227]
Using both xLights 2018.30 & .31

I open xLights, change to the Layout Page, select Model/Group called All Pixels.  The lights change to yellow for the group on the visual display, but the lists of components never populate
 at the bottom of the page.  This does not happen with smaller Models.  I have left it run in this state for over 5 minutes without change.
I get a Non Responsive window and have to close the application and reopen to continue.  I do not see a crash file.

[xLightsProblem083018.zip](https://github.com/smeighan/xLights/files/2336874/xLightsProblem083018.zip)
[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/2336889/xlights_rgbeffects.zip)
[xLights Crash Log 8-30-18 - All Pixels Model Crash.zip](https://github.com/smeighan/xLights/files/2336925/xLights.Crash.Log.8-30-18.-.All.Pixels.Model.Crash.zip)

**Comment by AzGilrock** [comment]
Looking at the fix Keith checked in it looked like you caused this by having nested groups that included the same model groups multiple times.  Like most things we fix it so it doesn't crash but it doesn't mean what you are doing is best practice.

**Comment by TomL8345** [comment]
Thanks Guys,

I was actually going in to clean up that model group when I hit this 
issue.  This is my second year of working with xLights, and I am just 
STARTING to discover some of the power and possibilities of the the 
program.  I am also discovering how to better create my models and 
groups to facilitate my sequencing.

Thanks Guys for all you do!

Tom Little
TomL8345 on the forums, sorry I don't Facebook.

Gil Jones wrote on 9/7/2018 9:26 AM:
