### ISSUE TITLE
Select Render Cache Location- Feature Request

### ISSUE THREAD

**Issue by mikedahm** [smeighan/xLights#1237]
I would like to request a feature to be able to set the Render Cache location and/or FSEQ file save location.  For those of us who use file sharing programs like Dropbox or Google Drive the Render Cache and FSEQ files are very large and takes up a lot of space or bogs down internet connections.  The ability to have that saved other than in the project folder would help keep it local so the file sharing programs are not constantly trying to upload them.  

Currently many pause sync then delete FSEQ and Render Cache before resuming sync for file sharing.

We do not need the FSEQ or render cache to be uploaded to the file sharing as we can just re-render the first time on our other computer and have those cache/FSEQ saved locally outside of the show #folder.

**Comment by dkulp** [comment]
This can already be done.  On the setup page the Subfolders button can be used to set alternate storage locations for a bunch of things.

**Comment by mikedahm** [comment]
Thank you very much, I will check that out.

**Comment by dkulp** [comment]
It's supposed to put the rendercache directories as subdirectories of wherever the fseq files are set.

**Comment by tmeyermn** [comment]
Oh, that's it thank you!!   I thought it was putting them in the media directories.
