### ISSUE TITLE
3D.31 - Crash when trying to delete layout image

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1238]
on my MacBook Pro, I set  a new show directory as a test and I put in my background image and sized it all and it looked great. Now I change it back to my main show directory so all my models are there and when I try to delete an image I added under 3D objects, XLights crashes and never deletes the file I need deleted to get the house image out of the way so I can configure it properly in the background image area 

heres a video showing whats going on - https://youtu.be/SkJ6d33Wa4Y

heres the logs saved when it crashed

https://drive.google.com/file/d/1YkEz9Rg9KmK0waN3XQY_-nxHI_OTlnku/view?usp=sharing
https://drive.google.com/file/d/1WnFWrU7-NWF6irzaCcKHdKlcElfcNoQS/view?usp=sharing

**Comment by AzGilrock** [comment]
The image you deleted wasn't your background image.  I'm wondering if the problem was because you actually didn't have an image selected in that image object.  You'll notice the filename was blank.  To delete the 2D background image you need to delete the image name in the background parameters.

**Comment by bchiaino** [comment]
sorry, what I meant was I added "image" in 3D objects and picked a background as a test so that really wasn't my real background image so to speak, sorry, I know Its confusing, lol

I just went and tried to delete the the path and the actual  image went away as it should but I still cannot add or delete an image in the 3D object area where you can "ADD OBJ" and choose image, once I do that it crashes. and if I do finally get to add one, trying to delete it will crash it again. 

I was able to recover an older xlights_rgbeffects from goolge drive before I added images and was able to get my background to look ok

**Comment by AzGilrock** [comment]
Yes I'm just saying you didn't actually have an image selected.  See the red arrow in this pic from the video.
![image](https://user-images.githubusercontent.com/2024669/45271803-54f3f600-b45e-11e8-8e0d-72841245fc88.png)

**Comment by AzGilrock** [comment]
Either way though I just tried it and I can delete an image whether it's been defined or not.  I don't have time to grab your files right now cause I'm in the middle of changes so I'll come back to it later.

**Comment by bchiaino** [comment]
I just tried that too, I added a pic by clicking the box you're point to, the image appears which is great but if I want to delete it it crashes, not the end of the world being the image worked but just reporting if people wanted to delete that in the Object/Group list, it may crash, or adding another image by licking "ADD OBJ" box crashed it also. I have only tested on my MacBook so far, I will try on my pc if I get a chance in a little bit

**Comment by bchiaino** [comment]
on my PC it works perfect, I can add or date multiple images in 3d object area so im sure you may have to wait for Dan to look at this all for Mac users.

**Comment by keithsw1111** [comment]
Can you try again in .34 3D

**Comment by bchiaino** [comment]
.343D will not open past splash screen, I will try ,34 non 3D

all others meaning I have beta 3 3D and that opens fine and .33 non 3D also opens fine but .34 3D just sits at splash screen, never actually loads the app to allow me to open a sequence. 

No log file pops up after I force quit, is there a hidden one somewhere I can send you?

**Comment by keithsw1111** [comment]
Yeah I dont recall where the mac stores its log files.

**Comment by bchiaino** [comment]
I found this in diagnostic log area in Library
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/2435745/xLights_l4cpp.log)

**Comment by AzGilrock** [comment]
I would rename the show folder to force it to start up empty. If that works then we may need to see your show files

**Comment by bchiaino** [comment]
I tried that Gil, was just going to post that, No luck either

**Comment by bchiaino** [comment]
video is kinda useless but shows what I mean lol, 

on Mojave I don't even get a splash/startup screen. 
https://youtu.be/pt99LITTsqY

**Comment by AzGilrock** [comment]
We still need your xlights_rgbeffects.xml file.

**Comment by bchiaino** [comment]
sorry Gil, I didn't know you were waiting for it,  here it is https://drive.google.com/file/d/1mFJWH66lvtC6NtW6JH09emQyMPQNqFrF/view?usp=sharing

**Comment by AzGilrock** [comment]
We might not need it.  Its usually only needed 90% of the time a user has problems... :)

**Comment by bchiaino** [comment]
cool, usually user error, LOL.... please let know if you guys need anything else. thank you

**Comment by AzGilrock** [comment]
I don't know I was able to open up your Layout although none of the images show up because they are all pointing to a google drive.  I also notice it looks like you used ImageModels for everything.  Things like the ground should be able to be switched to ImageObjects now.

**Comment by bchiaino** [comment]
im going to try it all again once the lated 3D version can open on my Mac, I did image/models being the objects weren't working right yet but once I can get the next release from dan to open (if he's working on it) then I can try it all again and report back
