### ISSUE TITLE
Linux Build Bug?

### ISSUE THREAD

**Issue by m00dawg** [smeighan/xLights#1239]
I've been having trouble building xLights off the master branch for a while now (couple months even?). As of `4a709d1eeb9e171568f473f3dcfaf23e12144748` I am getting:

```
make
...
AudioManager.cpp:(.text+0xa4a): undefined reference to `SDL_DequeueAudio'
collect2: error: ld returned 1 exit status
xLights.cbp.mak:1143: recipe for target 'out_linux_release' failed
make[1]: *** [out_linux_release] Error 1
make[1]: Leaving directory '/nfs/home/tim/git/xLights/xLights'
Makefile:30: recipe for target 'xLights' failed
make: *** [xLights] Error 2
```

I took a peak at line 1143 and while there's an odd OS X reference for Linux after that line, the line itself looks pretty ok to me?

```
out_linux_release: before_linux_release $(OBJ_LINUX_RELEASE) $(DEP_LINUX_RELEASE)
    $(LD) $(LIBDIR_LINUX_RELEASE) -o $(OUT_LINUX_RELEASE) $(OBJ_LINUX_RELEASE)  $(LDFLAGS_LINUX_RELEASE) $(LIB_LINUX_RELEASE)

$(OBJDIR_LINUX_RELEASE)/osx_utils/TouchBars.o: osx_utils/TouchBars.cpp
    $(CXX) $(CFLAGS_LINUX_RELEASE) $(INC_LINUX_RELEASE) -c osx_utils/TouchBars.cpp -o $(OBJDIR_LINUX_RELEASE)/osx_utils/TouchBars.o
```

**Comment by AzGilrock** [comment]
I don't know much about the Linux build so may need to wait for Chris.  But what I can say is if you view the commit list there is a green checkmark beside almost every commit because its setup to run a Linux build automatically to verify the commits.  You can click on that green checkmark and see the build log so not sure if any of that information could help show you what build differences you may have.

**Comment by computergeek1507** [comment]
I have run into the same issue on Fedora 28, I think newer versions of ffmpeg have removed some of the older SDL librarys xLights uses.

**Comment by computergeek1507** [comment]
The travis build server, I think still uses ubuntu 16.04 which has the older libraries still.

**Comment by m00dawg** [comment]
Yeah I didn't think to look at the CI build server, good call Az! I played around with the SDL stuff and I think you're onto something. I now get this:

```
.objs_lr/AudioManager.o: In function `SDL::PurgeAllButInputAudio(int)':
AudioManager.cpp:(.text+0x854): undefined reference to `SDL_DequeueAudio'
.objs_lr/AudioManager.o: In function `SDL::GetInputMax(int)':
AudioManager.cpp:(.text+0x934): undefined reference to `SDL_DequeueAudio'
.objs_lr/AudioManager.o: In function `SDL::GetInputSpectrum[abi:cxx11](int)':
AudioManager.cpp:(.text+0xa4a): undefined reference to `SDL_DequeueAudio'
collect2: error: ld returned 1 exit status
xLights.cbp.mak:1143: recipe for target 'out_linux_release' failed
make[1]: *** [out_linux_release] Error 1
make[1]: Leaving directory '/nfs/home/tim/git/xLights/xLights'
Makefile:30: recipe for target 'xLights' failed
make: *** [xLights] Error 2
```

I'll have to see what changes have been made there. I've only been doing regular `apt-get upgrades` for the most part so I suspect one of those must've upgraded something to break things.

**Comment by cjd** [comment]
Which distro/version are you building on?
Which libsdl2-dev packages are you using?
xlights only builds easily on bionic (18.04) and cosmic (18.10) currently because it needs sdl/ffmpeg packages that aren't available prior to those.
The appimage binaries (and the travis build server) are based on Debian stable + a bunch of updates from jessie-backports/stretch

**Comment by m00dawg** [comment]
Hopefully this helps! I have read Linux Mint 18.1 is based on Ubuntu 16.04, but since ffmpeg was mentioned, I'm guessing that could perhaps be part of the issue (I recall running into shenanigans with it, although first time I've run into it with xLights).

Upgrading to Mint 19 is on my list which is based on 18.04 I believe so if that may fix it I can double up on those efforts. Fortunately I have a working xLights version installed, it's just a little dated.

```
tim@lindawg ~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena
tim@lindawg ~ $ 

tim@lindawg /etc/apt $ dpkg -s libsdl2-dev
Package: libsdl2-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 3802
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: libsdl2
Version: 2.0.4+dfsg1-2ubuntu2
Replaces: libsdl-1.3-dev
Depends: libasound2-dev, libdbus-1-dev, libegl1-mesa-dev, libgl1-mesa-dev, libgles2-mesa-dev, libglu1-mesa-dev, libmirclient-dev, libpulse-dev, libsdl2-2.0-0 (= 2.0.4+dfsg1-2ubuntu2), libsndio-dev, libudev-dev, libwayland-dev, libx11-dev, libxcursor-dev, libxext-dev, libxi-dev, libxinerama-dev, libxkbcommon-dev, libxrandr-dev, libxss-dev, libxt-dev, libxv-dev, libxxf86vm-dev
Conflicts: libsdl-1.3-dev
Description: Simple DirectMedia Layer development files
 SDL is a library that allows programs portable low level access to a video
 framebuffer, audio output, mouse, and keyboard.
 .
 This package contains the files needed to compile and link programs which
 use SDL.
Original-Maintainer: Debian SDL packages maintainers <pkg-sdl-maintainers@lists.alioth.debian.org>
Homepage: http://www.libsdl.org/
```

**Comment by cjd** [comment]
Ahh - that would be it.
Linux Mint 18.3 is based on Ubuntu 16.04 - which sadly is too old now to build xLights now (in particular the version of SDL that it has is too old to support some features needed by xLights - it must be 2.0.6 or newer)
You will need to either upgrade or use the appimage builds instead as they run on pretty much any linux

**Comment by m00dawg** [comment]
Doh ok, thanks for clearing that one up cjd - very much appreciated! Sounds like it's time for me to upgrade! But I'll give those AppImage builds a try in the meantime. Looks like I have paths forward so I'll close this out. Again thanks everyone for the help and amazing tool!
