### ISSUE TITLE
Trouble moving some models in the Preview window

### ISSUE THREAD

**Issue by JonB256** [smeighan/xLights#124]
I'm using Windows 8.1 and version 4.0.10 (March 31) but have had this problem in earlier versions.

Particularly with Straight Lines, it is very hard to "find" the handle needed to move the model. By randomly clicking around the Straight Line, I'll eventually find it (at about 11 o'clock) based on the center. Other models are easier to find. 

Is this a Windows 8.1 peculiarity?  I was watching the very latest video and Sean did NOT seem to have any problems finding the handle.

Just went back to "try to find" the handle again but this time am having no luck. It will show if I click the name in the list, but just can't find it by clicking. And, even when highlighted, as soon as I try to rotate by clicking, the highlighting disappears.

If I highlight it from the list, then go above the straight line model approximately twice the height of the vertical rotator stick, then click "around" to the left or right, I'll eventually get a "grip" on the model. I have yet to be able to rotate it with the mouse.

**Comment by xlights** [comment]
what is your vertical resolution in the preview. i had to change mine to 700 to make selection better

**Comment by AzGilrock** [comment]
Try hitting the Set Size button and making it 1280x720.  Larger sizes cause problems with the selection.  We haven't looked into it yet but there is an issue with mapping screen coordinates to the selection coordinates at higher sizes.

**Comment by xlights** [comment]
the x direction doesnt seem to effect it, the y certainly does. on ,y laptop i had to set y to 650

**Comment by JonB256** [comment]
It was at 1280x720 when I was having so much trouble. I tried many sizes. At 1100x550 I'm having better luck, but that straight line model is still tough to grab. Resizing with the mouse is still not working. Sean's video example of rotating and resizing on the house eaves with just the mouse is very hard. (impossible at 1280x720 but doable at 1100x550)

**Comment by JonB256** [comment]
Using 4.0.12 Apr 2 version now, preview resolution of 1100x550. It is now letting me click directly on the "single line" model and selecting it without problem. Did something change in this revision or did a restart of Nutcracker make the difference? It still doesn't work well in 1280x720.

**Comment by klyneshouse** [comment]
This was driving me crazy yesterday, tried many resolutions. seemed worse with smaller/simple models. Large stuff worked fine.

**Comment by TKW1969** [comment]
Having the same issue. It's only a issue for me when the model has only 1 string. If I have 2 or more strings it works fine.

**Comment by tombmatt** [comment]
I had same problem hard to grab any object and could only resize by changing the value in the box and could not rotate objects either. just reset my screen to 1100x550 and can resize and rotate all objects now.
