### ISSUE TITLE
Artist Name in Meta Data produces "XML error at line 9"

### ISSUE THREAD

**Issue by jdormanCA** [smeighan/xLights#1240]
In xLights Mac 2018.33 (although I noticed it first in 2018.32), if the artist name is populated in the Sequence Settings under Meta Data, it produces an XML error.  I've come up with a workaround involving opening the offending XML file and deleting the artist name (if I didn't catch it before saving the sequence in the first place).

To not delete the artist name makes the XML file unable to be opened by xLights.

**Comment by jdormanCA** [comment]
Not that I could see: one was Casting Crowns and another Pentatonix.   There were no spaces before or after their names.  

Sent from my Verizon iPhone
Please forgive the brevity and inevitable typos and autocorrects.

**Comment by AzGilrock** [comment]
Well I typed in a name saved and opened and it worked so I guess we are at an impasse since I can't actually see what you have in your file.

**Comment by jdormanCA** [comment]
That’s interesting.  I can reproduce it every time on my configuration.  In the morning, I can send you one of my xml files. 

Sent from my Verizon iPhone
Please forgive the brevity and inevitable typos and autocorrects.

**Comment by AzGilrock** [comment]
That would help.  It could be MAC only issue if its not any special characters.

**Comment by jdormanCA** [comment]
Here's an example that gives me the XML error code at line 9.

[Thats What Christmas Means to Me.xml.zip](https://github.com/smeighan/xLights/files/2385810/Thats.What.Christmas.Means.to.Me.xml.zip)

**Comment by AzGilrock** [comment]
Are you typing in the name or pasting it cause it does have a special character?  When I open the file in Notepad++ I see that "SOH" special character after the name.
![image](https://user-images.githubusercontent.com/2024669/45587588-a10ac480-b8bc-11e8-8b87-919eae744ab3.png)

**Comment by jdormanCA** [comment]
I didn’t add or correct anything.  It populated the line from the MP3 file.    

Sent from my Verizon iPhone
Please forgive the brevity and inevitable typos and autocorrects.

**Comment by jdormanCA** [comment]
This is what I see in the XML file (no special character or anything after the name)

![screen shot 2018-09-15 at 8 01 14 am](https://user-images.githubusercontent.com/43285681/45587655-8be26580-b8bd-11e8-8424-56b2e10d3114.png)

**Comment by AzGilrock** [comment]
Special character are usually hidden unless you use an editor capable of showing them.  Try retyping the entire line and then deleting the one that's there and I bet it won't crash.  The solution will be we will have to add code to remove bad characters like we've done in other places but you'll need to fix it manually for now.

**Comment by jdormanCA** [comment]
Thanks!  My workaround was deleting the artist name altogether because I personally don’t need it one way or another.  But now I know what’s happening.

Sent from my Verizon iPhone
Please forgive the brevity and inevitable typos and autocorrects.
