### ISSUE TITLE
Copy and paste row will only paste to the first layer

### ISSUE THREAD

**Issue by reelpilot** [smeighan/xLights#1241]
This issue occurs when copying and pasting a row of effects onto a model or group with multiple layers. When you right click a layer and select >Row>Copy Effects and then go to your layer (in a model with multiple layers) that you want to paste that row to, it will always paste the entire row of effects to the first layer in that model or group regardless of which layer you selected to during the paste.

**Comment by AzGilrock** [comment]
A row is only 1 layer its working how it should.

**Comment by AzGilrock** [comment]
You need to use Model > Copy Effects if you want all the layers of a model.

**Comment by reelpilot** [comment]
Here's a short video that should better illustrate the problem. 

[https://youtu.be/YwW6NLCKc7o](url)
