### ISSUE TITLE
Feature Request - Video/Photo Directory Location

### ISSUE THREAD

**Issue by RyanKasperCook** [smeighan/xLights#1244]
As more and more of us are using video and picture effects, wondering if it would be possible to add a "Asset" or "Videos/Photos" Directory to the Subfolders pop up in the Setup screen.  Basically user could point this Videos/Photos Directory to the location of their photos or videos folder if different than their show directory.

This would help a lot of people who share sequences with broken video/image links, could also work for signing faces... or more importantly, if you rearrange your show directories on your pc it would be so nice to just point to the right directory instead of having to update each effect individually.

Thanks!!!

**Comment by keithsw1111** [comment]
This is not a great idea. Placing such assets under the show folder already handles the issues you are talking about. Adding a separate folder would actually make the situation worse.
