### ISSUE TITLE
Curtain on Arch 

### ISSUE THREAD

**Issue by JimmieNC** [smeighan/xLights#1245]
I am trying to use a Curtain Effect on an Arch and it is not lighting all the lights when it does any of the chase types.  The elements are Arches. (12 nodes, 3 lights per node),(17 nodes, 3 lights per node),(21 nodes, 3 lights per node).  The 12 node works the other two miss the far left node.

**Comment by keithsw1111** [comment]
Can you create a simple sequence which just shows the problem and package it and upload it

**Comment by JimmieNC** [comment]
[SingleStrandError.zip](https://github.com/smeighan/xLights/files/2457822/SingleStrandError.zip)

It is not a Curtain. it is a Single Strand effect.

**Comment by keithsw1111** [comment]
The subbuffer is not set to full which prevents it from drawing on that node. Select the effect and double click on the circled black box in the image below to fix it.

![image](https://user-images.githubusercontent.com/10283944/46798689-5fc3e280-cd9e-11e8-935e-d3fa96945870.png)
