### ISSUE TITLE
model export to csv - groups have incorrect end channel

### ISSUE THREAD

**Issue by darylerwin** [smeighan/xLights#1246]
v .33 when I export to csv and sort by controller connection and end channel I can see that end channels for groups is miscalculated. It almost seems like it generates channel numbers like they are themselves models rather then grouping of existing models.
Could be groups of groups that is causing this.
The last few rows of the spreadsheet show the way too high channel numbers..The first few rows represent the end of the list of valid models and channels.
`

Arches-4RR |   | Arches | RGB Nodes | 1 | 150 | 150 | 9 | 3 | 450 | >Arches-3R:1 | 5431 | 5880 | 150 x 1 | Default
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Eaves - Lower - C9 Lights | C9 Lights | Single Line | RGB Nodes | 1 | 50 | 50 | 3 | 3 | 150 | #42:1 | 20911 | 21060 | 50 x 1 | Default
Vertical - 1 |   | Single Line | RGB Nodes | 1 | 28 | 28 | 1.68 | 3 | 84 | >Eaves - Lower - C9 Lights:1 | 21061 | 21144 | 28 x 1 | Default
Rail - 1 |   | Single Line | RGB Nodes | 1 | 34 | 34 | 2.04 | 3 | 102 | >Vertical - 1:1 | 21145 | 21246 | 34 x 1 | Default
Group - Mega Tree and Topper | AA Mega Tree, Mega Star - 01 | ModelGroup |   |   |   |   |   |   | 3960 |   | 1 | 3960 | 73 x 129 | Default
Group - Arches | Arches-1LL, Arches-2L, Arches-3R, Arches-4RR | ModelGroup |   |   |   |   |   |   | 1800 |   | 4081 | 5880 | 376 x 37 | Default
...

Group - Eaves | Eaves - Lower - C9 Lights | ModelGroup |   |   |   |   |   |   | 150 |   | 20911 | 21060 | 296 x 4 | Default
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Group - Roof | Eaves - Lower - C9 Lights | ModelGroup |   |   |   |   |   |   | 150 |   | 20911 | 21060 | 296 x 4 | Default
Group - Railings | Rail - 1, Rail - 2, Rail - 3, Rail - 4, Rail - 5 | ModelGroup |   |   |   |   |   |   | 2376 |   | 21145 | 23520 | 313 x 8 | Default
02a Whole House Minus MegaMiniMatrix | Garage Outline - 01L, Garage Outline - 02R, Group - House Verticals, Group - Windows, Group - Snowflakes, Group - Arches, Group - Driveway Lights, Group - Railings, Group - Roof, Tree branches, tree trunk | ModelGroup |   |   |   |   |   |   | 17166 |   | 6697 | 23862 | 400 x 108 | Default
02b Whole House Minus Mega and Matrix | Garage Outline - 01L, Garage Outline - 02R, Group - House Verticals, Group - Windows, Boscoyo ChromaFlake 36 3 Prong - 01L, Boscoyo ChromaFlake 36 3 Prong - 02R, Group - Railings, Group - Eaves, Group - Trees, Group - Trees - Medium, Group - Trees - Large, Group - Spiral Trees, Group - Windows - Bottom, Group - Arches, Md Star - 01, Md Star - 02, Lg Star - 01, Lg Star - 02, Group - Driveway Lights | ModelGroup |   |   |   |   |   |   | 17166 |   | 6697 | 23862 | 400 x 88 | Default
03 Whole House No Matrix | Group - Arches, Group - Driveway Lights, Group - Eaves, Group - Home Front, Group - House Horizontals, Group - House Verticals, Group - Spiral Trees, Group - Trees, Group - Windows, Group - Trees - Large, Group - Trees - Medium, Lg Star - 01, Lg Star - 02, Md Star - 01, Md Star - 02, Mega Star - 01, AA Mega Tree, Group - Railings | ModelGroup |   |   |   |   |   |   | 21246 |   | 4081 | 25326 | 400 x 88 | Default
04 Whole House w Matrix | Group - Arches, Group - Driveway Lights, Group - Eaves, Group - Home Front, Group - House Horizontals, Group - Railings, Group - House Verticals, Group - Matrixes, Group - Spiral Trees, Group - Trees, Group - Windows, Group - Trees - Large, Group - Trees - Medium, AA Mega Tree, Lg Star - 01, Lg Star - 02, Md Star - 01, Md Star - 02, Mega Star - 01 | ModelGroup |   |   |   |   |   |   | 21246 |   | 4081 | 25326 | 400 x 88 | Default
Group - House Horizontals | Eaves - Lower - C9 Lights, Group - Windows - Top, Group - Windows - Bottom, Group - Railings, Garage Outline - 01L/Horizontal, Garage Outline - 02R/Horizontal | ModelGroup |   |   |   |   |   |   | 14415 |   | 20911 | 35325 | 400 x 92 | Default
Group - House Verticals | Vertical - 1, Vertical - 2, Vertical - 3, Vertical - 4, Vertical - 5, Vertical - 6, Group - Windows - Left, Group - Windows - Right, Garage Outline - 01L/Left Side, Garage Outline - 01L/Right Side, Garage Outline - 02R/Left Side, Garage Outline - 02R/Right Side | ModelGroup |   |   |   |   |   |   | 14448 |   | 21061 | 35508 | 400 x 115 | Default
01 Whole House NO YARD | Group - Home Front, Group - House Verticals, Group - Railings, Group - Windows, Boscoyo ChromaFlake 36 3 Prong - 01L, Boscoyo ChromaFlake 36 3 Prong - 02R, Matrix - 1L, Matrix - 2R | ModelGroup |   |   |   |   |   |   | 15126 |   | 20911 | 36036 | 400 x 115 | Default
Group - Home Front | Eaves - Lower - C9 Lights, Group - Windows, Garage Outline - 01L, Garage Outline - 02R, Group - House Verticals, Group - Railings, Boscoyo ChromaFlake 36 3 Prong - 01L, Boscoyo ChromaFlake 36 3 Prong - 02R | ModelGroup |   |   |   |   |   |   | 15126 |   | 20911 | 36036 | 400 x 115 | Default
`

**Comment by darylerwin** [comment]
btw .. my xml might still be around from prior issues but I can upload if needed.

**Comment by keithsw1111** [comment]
Can you package logs on tools menu and add it.

**Comment by darylerwin** [comment]
[models_20180925.zip](https://github.com/smeighan/xLights/files/2415625/models_20180925.zip)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/2415632/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
Can you be more specific about which group looks wrong?

**Comment by darylerwin** [comment]
Looking at my models, the Tune To should be the last model at channel 20721.
But the groups show:
01 Whole House - starting at 19891 and ending at 35016??
02a starts at 5677  (might be right) but ending as 22317 - doesnt match any model.
03 same thing ending at 24801
04 ditto
Group Home Front starts at 19891 and ends at 35016 ?

Groups of models appear to be okay..
Group Trees Large - appears fine 7291 to 8970
