### ISSUE TITLE
Labels when doing lyrics and faces does not understand non english letters

### ISSUE THREAD

**Issue by Evilfish2000** [smeighan/xLights#1247]
I am from Denmark and we have a bit of a different alphabet. I have built my own user_directory of all my Danish words to use with the CMUDICT system and is work really well, except for æ ø å, which are Danish letters.

I added a picture so the following explanation might be easier to track:

When I right+dobbel click on a section on my timing track to fill in the sentence, those letters will not show on the label. However, when to right+dobbelclick again on the same label the letter æ ø å will appear in the dialog box that pops up. So it seems that the displaying of the label fails. When I try to break down the sentence the words that come up still has the right æøå letters when I double-click on them, but the label still doesn't display them. And finally when I break down the Word to the actual face command, the commands are missing. I assume that it tries to look for the label text in the user-dictionary file, and not the actual text data behind? It seems that way

Here is a sample of words from the dictionary that won't work:

BESTÅR  B IH1 S D OW1
BJØRN  B EH1 OW1 R N
FRÆK  F R AE1 G
FÆLGE  F EY2 L EH1

![xlightsdkcharserrorpapagayo](https://user-images.githubusercontent.com/14344191/45782978-c86ae400-bc64-11e8-9305-f7ebfce9a1b5.jpg)

**Comment by Evilfish2000** [comment]
And it just dawned on me that I should probably have given the word I used as an example to the sample word list, so here it is:

EFTERÅR  EY2 F D OW1 OW1

**Comment by dkulp** [comment]
Pretty much any letters that don't fall into the lower 128 chars of the ASCII alphabet will not work.   Everything is rendered with OpenGL which does not have any concept of "fonts" so we actually have to pretty much hand create textures for letters and we have only done so for the lower characters.

**Comment by Evilfish2000** [comment]
That makes sense GUI wise, and I can see that supporting other chars than the ASCII alphabet visually might not be feasible. But since the data is still intact behind the GUI, wouldn't it be possible to just use that to look up words instead of the rendered text, or does that data also have an ASCII limit?

**Comment by AzGilrock** [comment]
It's not using the rendered text to do the word lookups.  What you really need to do is a Package Sequence and post it here.  It only needs to be a small sample that has the issue from the screenshot.  We will also need your user dictionary since that  doesn't get packaged.

**Comment by dkulp** [comment]
We load the user dictionary via the default wxTextInputStream constructor which should look at the first byte of the stream for a BOM character.   Whatever program you are using to create the user dictionary, you may want to make sure it's saving it as either UTF-8 or, if there is an option, one of the UTF's with a BOM.

**Comment by Evilfish2000** [comment]
I checked the file encoding and it is in UTF-8. Here is the requested small sequence with the issue, plus my user_dictionary file:
[IssueWithCharsSequence.zip](https://github.com/smeighan/xLights/files/2401909/IssueWithCharsSequence.zip)

I tested a hack last night which worked. I could when I was done compiling my dictionary replace all "exotic" chars to a number like:

æ=1
ø=2
å=3

So a Word like EFTERÅR became EFTER1R. Then when I import lyrics I replace according to the rules and that works okay, however not really pretty editor wise when reading the lyrics. The can cause issues as we have in danish words like "ø" (Island) or "å"(creek/river) which becomes "2" and "3" respectively. But what would the system now do? Translate the representation of "ø" or translate it to "2".

**Comment by dkulp** [comment]
Well, I can confirm that there is a bug in wxWidgets.  :(    The wxTextInputStream, according to the docs, should assume UTF-8 if there is no BOM.   Well, it doesn't actually work.  It starts to assume UTF-8, but eventually flips to ISO-8859-1.

**Comment by AzGilrock** [comment]
The dictionaries were just copied from Papagayo.  All those character formats is an area I've never understood.
