### ISSUE TITLE
Galaxy Effect:  Inward check box

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#1248]
Been using the Galaxy effect and can't seen to discriminate what happens when using the "inward" check box.  There seems to be no change what so ever.  I would anticipate that this function would reverse the start and end points of the effect so in fact you are creating a reverse of the effect.  Gil would you look at that, or am I missing the reasoning for the "inward" function? 
Thanks
Clyde

**Comment by AzGilrock** [comment]
It works.  You won't see any difference unless you have overlapping edges.  It will make the overlapping edges appear such that it's spiraling into the screen instead of out of the screen coming at you.

**Comment by Clyde-L** [comment]
Ok, I see what you mean.   

So can you enhance the effect with a "Swap start and end points" like for the Morph effect then?

**Comment by AzGilrock** [comment]
What?  Someone put a swap on my Morph?

**Comment by Clyde-L** [comment]
LOL :P  Noooooooo!
![image](https://user-images.githubusercontent.com/12719816/45888549-5392c980-bd8c-11e8-9308-930b7725050a.png)

**Comment by AzGilrock** [comment]
Yeah at least its just a button that move the sliders for you and not a checkbox.

**Comment by Clyde-L** [comment]
So you're saying you will add a Swap Start and End Points button?  Geee Gil, you're the greatest!

**Comment by AzGilrock** [comment]
So then should it only swap the start and end radius?  What about the start and end width?

**Comment by Clyde-L** [comment]
Wohhhh, so another button for the width?  That's a cool Idea too!

**Comment by AzGilrock** [comment]
You know I understood the need to have a swap for Morph.  It was 4 points that had X and Y values each.  For these galaxy settings you only have to swap 2 numbers.  So you have a radius of 10 and 20 and you need a button to swap them?  Now I'm leaning away from the idea.

**Comment by Clyde-L** [comment]
I know, the programming is not worth the effort for such a simple change any user can do.

**Comment by AzGilrock** [comment]
The programming for that is really simple.  Let me look at the panel later to see if it would look cluttered to add a button.

**Comment by computergeek1507** [comment]
Shhhh don't tell Gil, I touched his morph effect.

**Comment by Clyde-L** [comment]
Scott!  Be careful!  He has a meat cleaver and he's not afraid to use it!

**Comment by Clyde-L** [comment]
Lots of room for a button under the Options tab in the Galaxy Effect
![image](https://user-images.githubusercontent.com/12719816/45889812-5b07a200-bd8f-11e8-9dc4-ae4797ab761e.png)
