### ISSUE TITLE
Resizing effects then deleting - Effect still shows in preview

### ISSUE THREAD

**Issue by buzzdude** [smeighan/xLights#125]
Hi
Create a musical sequence and add one Element.  Add a timing mark and then add an effect.  Play sequence, effects show in preview.  Resize the last effect, shrinking it from left to right, Play sequence. Delete resized effect.  Play sequence and the deleted effect will still show in preview.  Deleting the resized timing mark still does not remove from preview when played.

![untitled](https://cloud.githubusercontent.com/assets/11732991/6935887/a52f14fc-d897-11e4-962d-73e601e31989.jpg)

Thanks
Shane

**Comment by AzGilrock** [comment]
Are you spying on our checkins?  Dan just checked in a change yesterday to fix this.   We've talked about it in several places that effects can leave artifacts in the data.  Before that change think of it as a painting canvas.  The old paint doesn't go away unless you paint over top of it.

**Comment by buzzdude** [comment]
Thanks, I have tried painting over it, by creating a new timing mark and effect, but all that happens is I get two (old and new).  I'll look forward to the next release....
