### ISSUE TITLE
Word Breakdown

### ISSUE THREAD

**Issue by dszoka** [smeighan/xLights#1250]
If a word has a '   like "let's" wont breakdown word until ' Removed 

![screen shot 2018-09-22 at 1 57 52 pm](https://user-images.githubusercontent.com/42435862/45913099-c3c64b80-be6f-11e8-9367-4ef3a8255dd8.png)

![screen shot 2018-09-22 at 1 58 02 pm](https://user-images.githubusercontent.com/42435862/45913080-a1ccc900-be6f-11e8-9294-fe65e83b8365.png)
![screen shot 2018-09-22 at 1 58 12 pm](https://user-images.githubusercontent.com/42435862/45913081-a4c7b980-be6f-11e8-99db-f70d861d52e5.png)
![screen shot 2018-09-22 at 1 58 18 pm](https://user-images.githubusercontent.com/42435862/45913085-a98c6d80-be6f-11e8-9c12-6c728ad1ffa2.png)

![screen shot 2018-09-22 at 1 58 25 pm](https://user-images.githubusercontent.com/42435862/45913100-c9bc2c80-be6f-11e8-9a65-f61b2df2b9bc.png)

Hope that makes sense

**Comment by dszoka** [comment]
Sorry using .33 on Mac

**Comment by keithsw1111** [comment]
.34 seems to work fine. Dan updated the dictionary.
