### ISSUE TITLE
Feature Request: Allow selection of which preview to export video from. 

### ISSUE THREAD

**Issue by madsci1016** [smeighan/xLights#1254]
Quite simply, for those of use that use one profile for Halloween and Christmas, and therefore a Halloween and Christmas preview, are missing out on using "Export preview video" feature because we don't use the whole house preview. 

Can we make it pop up and ask us which preview to render from? Pretty please?

**Comment by AzGilrock** [comment]
I wish I had never added that multiple preview feature.  It was really only to solve the issue of seeing your yard from multiple angles and now camera views in 3D are solving that problem.

**Comment by madsci1016** [comment]
How do you recommend we approach using one profile to cover two different display configurations (shows) Gil? 

80% of my models stay the same, if I use two profiles it doubles my work when ever I want to make a change to a model that is shared by both shows.

**Comment by AzGilrock** [comment]
I always intended different shows to be in different show folders but its too late now you're not the only one that decided to use it that feature for different shows.   Cause also now I'd like to change it so that all models in the show folder always get added to sequence so that we could eliminate all the "master view" confusion.   So then if you had halloween only models they will be listed in your christmas sequences.

**Comment by madsci1016** [comment]
Like I said different show folders does not afford me the time savings of only making a change to a shared model once and having it updated on both, without doing manual risky profile file copies.

I think you should embrace this usage case as it's actually really nice for people like me, I can effortlessly plan both shows and easily switch between previews. 

I don't think this negates eliminating master view btw, as I have a halloween and christmas view. I find it an unnecessary extra step to add new models to the master view first, and then to my show view. It would be nice if all models were automatically available to be added to any custom view.

**Comment by AzGilrock** [comment]
But the feature added a ton of complexity inside the code and every time the layout has to be refreshed it goes through complex routine to figure out what models to display.  Not a big deal with smaller shows but once you get a lot of models you will notice the screen starts turning black and delaying when you make a change.  So you are paying for that time savings in other ways.

**Comment by AzGilrock** [comment]
Back to the original issue request.  I don't see what the problem is.  Yes the export only uses the House Preview window but you can switch that window to display any preview you've defined.

**Comment by madsci1016** [comment]
Look at that! Did not know I could change house preview. I always close it and do View -> Previews and select the current holiday.

**Comment by AzGilrock** [comment]
Yeah I thought that might work but I had to wait till I could test it first since I didn't write the video export.

**Comment by AzGilrock** [comment]
So did you use xLights video export to create the Ghostbusters video you just posted?

**Comment by madsci1016** [comment]
No that was a 3rd party screen grab I did yesterday.
