### ISSUE TITLE
3D.31 - (MAC) Mojave issues

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1255]
Hey guys, not sure where this left off and if any changes were made yet to support Mojave betas that were out for a while but now that the release is official I tested it and its pretty buggy so just wanted to report the issues in case it was thought that it runs ok

Issues - 
Layout screen is not allowing you to do much, it freezes a lot
House preview while playing back sequences is very laggy when you try and move the preview around

Im sure it is not built yet for Mojave but figured I would add a thread people can follow if theres updates

Thanks!

**Comment by AzGilrock** [comment]
Yeah well Apple thought it was a great idea to start requiring Metal and deprecate OpenGL so they are being abandoned by a wave of developers.

**Comment by bchiaino** [comment]
oh damn, bastards!  

Glad I kept mine partitioned so I can boot to Sierra when I need XLights for now.  thanks Gil

**Comment by dkulp** [comment]
This is mostly stuff down in wxWidgets.  In Dark mode, Mojave rendering and window layout is VERY VERY different internally and wxWidgets is just beginning to handle some of it.   I've submitted some patches to wxWidgets, but a lot of it is beyond my expertise.

**Comment by AzGilrock** [comment]
We had talked about possibly switching to Qt in the future so I'm not sure how well it supports Metal.  I've also wondered if we could switch to using the Ogre3D render engine which appears to already support Metal and may already handle a lot of the 3D rendering stuff I was trying to add like I'm sure it already supports importing a ton of different 3D formats.  I'm just not familiar with Ogre3D enough to know how hard it is to mix it with wxWidgets or Qt.

**Comment by AzGilrock** [comment]
I'd open a new issue if anything is still a problem.
