### ISSUE TITLE
Issue with saving a sequence

### ISSUE THREAD

**Issue by marciuliani** [smeighan/xLights#1258]
[xLights_dbgrpt-5645-20180927T142951.zip](https://github.com/smeighan/xLights/files/2425390/xLights_dbgrpt-5645-20180927T142951.zip)

**Comment by keithsw1111** [comment]
Can you reproduce the problem at will. While we appreciate people wanting to report bugs we dont need bugs which are one offs reported to github. If you click ok when it crashes we already receive the crash log and will look at them all. When it really helps is when you can reproduce the problem and describe the steps or make a video and show us the steps AND we can reproduce it. Once that happens the bug gets solved generally pretty quickly.

In this case while you may have seen the issue when saving the sequence that is actually coincidental ... the crash actually is a rendering crash and judging from the stack trace this is not going to be an easy one to nail down unless you have a way to crash it often.

**Comment by keithsw1111** [comment]
Can you package the sequence and send it to me. Can you also video you opening the sequence tweaking something and saving it and causing the crash ... if it is as reproducible as you say i should be able to work it out.

**Comment by marciuliani** [comment]
Keith/Sean,


It must have fixed itself - I no longer get the failure and was able to 
save it.  My guess is that something was stuck in cache - on my 
computer, but just guessing.


Nonetheless - you could close this case out

On Mon, Oct 01, 2018 at 04:33 PM, Keith Westley wrote:

Can you package the sequence and send it to me. Can you also video you 
opening the sequence tweaking something and saving it and causing the 
crash ... if it is as reproducible as you say i should be able to work 
it out.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/smeighan/xLights/issues/1258#issuecomment-426052724> 
, or mute the thread
