### ISSUE TITLE
Downloaded DMX model states and characters  

### ISSUE THREAD

**Issue by Hilights360** [smeighan/xLights#1260]
Some if not all of the downloadable DMX model states have characters that keep them from working. Most notably any with Caps and spaces. They look fine, do not prompt or warn of the problem, but will not function as downloaded on either version .33 or .34 on two different PC's. It took me a while to catch the problem after a couple of hours of trying to get what was downloaded to actually work. The only way it would function was to edit the downloaded States and remove the offending characters. At least when editing the States, the software actually prompts the user to the bad characters. This was the only way I caught on.

**Comment by keithsw1111** [comment]
New models uploaded.
