### ISSUE TITLE
xSchedule Animation FSEQ Playback Too Fast - Linux

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#1264]
Good afternoon,

Lubuntu 18.04.1 LTS
Installing xLights via Ubuntu PPA
xLights 2018.34
64-Bit

Playing an animation FSEQ that is not associated with any audio track results in faster-than-expected playback. Looking at the countdown clock, every 3 or 4 seconds the system will skip (i.e. 45, 44, 42, 41, 40, 38, etc). This does not appear to be an issue on FSEQs with audio.

See logs attached. I am available to compile & test branches as needed.

[xSchedule_l4cpp.log](https://github.com/smeighan/xLights/files/2451886/xSchedule_l4cpp.log)

**Comment by keithsw1111** [comment]
But does it actually play fast ... the UI updates every second so it is entirely plausible it would skip a second but that doesnt mean the packets are actually fast.

**Comment by keithsw1111** [comment]
Jeff?

**Comment by coolas21** [comment]
Hi, I’m running on flights 2018.44 and having the same issue. I timed it in scheduler and it is way off, like twice as fast. I use it to run 14,000 lights on a singing Christmas Tree at our church and have very many coments that it’s the best light show they’ve ever seen. Thanks so much for all you do.

**Comment by keithsw1111** [comment]
Then coolas21 you need to upgrade. We dont look at issues in older versions. While Jeff didnt respond to this I spoke to him over the weekend and I am pretty sure this is not an ongoing problem.

**Comment by coolas21** [comment]
Thanks for the quick reply. We are done with our show this week and everything went great. I made the sequences twice as long on some songs that had this issue. I’ll update it on my end and try to let you know what mine does by next week.

**Comment by keithsw1111** [comment]
So it was particular sequences ... are you able to share one of them?

**Comment by coolas21** [comment]
Yes it is. I have timed other sequences that work fine, but one is really fast. How do I share it? Also it might be latter in the week as I’m at home for the night.

**Comment by keithsw1111** [comment]
Most people reach out on fb messenger or nutcracker forum messages

**Comment by coolas21** [comment]
Hi, got it updated today and the timing is now working properly. Thanks for the fix.
