### ISSUE TITLE
'Flip Horz' Button on Custom Model Missing

### ISSUE THREAD

**Issue by sdkraemer** [smeighan/xLights#1265]
I was watching this video https://youtu.be/cVXI6sBr6jI?t=238 , which shows how to flip a custom model using the Model Data edit dialog, but I no longer see the 'Flip Horz' button. Was this functionality moved?

**Comment by AzGilrock** [comment]
It was moved to the right-click menu.

**Comment by sdkraemer** [comment]
Future reference for anyone else looking for this option. The right-click menu @AzGilrock is mentioning is located when you right click on the grid of the 'Custom Model' dialog. Initially I thought it would be the right click context menu of the model in the preview panel. I had to dig through the code to figure this one out.
