### ISSUE TITLE
Move user_directory to showfolder

### ISSUE THREAD

**Issue by Evilfish2000** [smeighan/xLights#1267]
If you have created your own dictionary for Papagayo in the user_dictionary file which is inside the programs files folder on windows and you update Xlights, the user_dictionary is replaced with the standard one and you lose the changes you made.

It would make more sense to place the user_dictionary in the show folder as every time you make changes you have to edit a file inside the programs folder which is not the best practice and you have to have Admin privileges. Plus, the user_dictionary is a user specific thing and also a show specific thing. It makes more sense to have it inside the show folder.

**Comment by keithsw1111** [comment]
So put it in the show folder ... xlights will already read it from there IF you put it there.
