### ISSUE TITLE
Moving effects with up/down arrow keys isn't correct after scrolling with mouse wheel

### ISSUE THREAD

**Issue by MikeSoukup** [smeighan/xLights#1268]
1. add more models than fit on the screen vertically
2. select an effect
3. scroll up or down with the mouse wheel
4. press the up/down key to move the effect
5. effect doesn't move to the next/previous model, it moves based on where the model was before scrolling with the mouse

**Comment by AzGilrock** [comment]
At least you know the workaround.  I swear I'm so tired of trying to get that moving effects up and down to handle all the possible scenarios I should just delete the feature.

**Comment by keithsw1111** [comment]
I think this is now fixed.
