### ISSUE TITLE
Bulk Edit Feature Request

### ISSUE THREAD

**Issue by zcloutier** [smeighan/xLights#1269]
I’ve got a feature request I would like the ability to bulk edit the layer blending settings. Here is a video of what is going on and why it would be a handy feature https://vimeo.com/294255561. It would be nice if it had a similar update bouton like the effect settings page as well as the colors page. Also, if the layer settings page could get the same feature that would be great.

**Comment by zcloutier** [comment]
OK Thanks Keith I was not sure of how that feature worked I tried right clicking in several places but nothing came up. Thank you for the clarification on the update bouton I was unaware I caused so much confusion, but I can understand how it could.

**Comment by keithsw1111** [comment]
I just double checked ... it is definitely bulk edit enabled ... just know you MUST have multiple effects selected to enable bulk edit. And you must right click on the choice box or slider or text box to access the function.
Bulk edit works on almost all settings on all panels.

**Comment by zcloutier** [comment]
OK Thank you for the clarification that worked.

**Comment by adamcoulombe** [comment]
Thanks for clarification on the bulk edit and update buttons! I was looking for a way to do this  and I'm glad this feature is in there :)
