### ISSUE TITLE
Can't Reorder the Timing Tracks in the Edit Display Elements dialog

### ISSUE THREAD

**Issue by AzGilrock** [smeighan/xLights#1272]
We used to be able to reorder timing tracks in the old version of the dialog using the Move Up and Move Down buttons.  We lost that ability with the drag and drop features.  Also when creating a new View it should order the timings in the order they are dropped not reorder them based on Master.  Each view should be allowed to have its own timing order.   Let me know if there was a reason we started preventing that maybe I forgot.

**Comment by keithsw1111** [comment]
Yeah this has been on my todo list for a while ... one day ...

**Comment by AzGilrock** [comment]
This is mainly to record my findings for my own references.  I went back to a 2017 version to see how we handled moving the timings around.  It appears you could only move the timings in the Master View.  Timings are sequence specific and are only stored in the sequence file and they only keep track of the views they are a member of there is no mechanism to track order per view.  Views are stored in the rgbeffects file and keep track of which models exist in each view.  That makes it possible for sequences to be out of sync with the view since they can be added/deleted while sequences are closed so timings can list views that don't exist but we seem to handle that just fine.

I've got the ability to move timings around in the master view working so I might go with that for now.

**Comment by AzGilrock** [comment]
I believe I have the timing track reordering working for master view and also fixed some drag/drop issues mainly when dropping models onto timing track or past the end it was reversing the order of the model selections.
