### ISSUE TITLE
Crash when modifying Networks / E1.31 / Universe configuration

### ISSUE THREAD

**Issue by nmiller0113** [smeighan/xLights#1273]
I'm running the latest version 2018.35 64bit Mac version and I found that after modifying the Networks / E1.31 / Universe configuration setup tab and then closing out xLights will sometimes crash.  I've been able to reproduce it twice.  Crash report attached.
[xLights_dbgrpt-30464-20181010T002301.zip](https://github.com/smeighan/xLights/files/2474313/xLights_dbgrpt-30464-20181010T002301.zip)

**Comment by nmiller0113** [comment]
> Info for developers: I didn't get the crash but I was able to recreate the stack trace when closing xLights. If you are on the Setup tab and then exit xLights an event fires the OnNotebook1PageChanging function after the OnClose method has already been called so I believe there is a race condition where it's trying to RecalcModels at the same time everything is being destroyed.

A race condition makes sense since I couldn't reproduce it consistently.

**Comment by keithsw1111** [comment]
Ok. I did make a change to the page changing code. To disable audio controls.

**Comment by keithsw1111** [comment]
I think I have fixed this for .37
