### ISSUE TITLE
crash when rendering

### ISSUE THREAD

**Issue by abigda** [smeighan/xLights#1275]
[xLights_dbgrpt-5656-20181013T014041.zip](https://github.com/smeighan/xLights/files/2475524/xLights_dbgrpt-5656-20181013T014041.zip)
I've tried to render this around 10 times with the same result, had the same response on released .35 as well

**Comment by AzGilrock** [comment]
Is your OS really 32-bit cause you are running the 32-bit version of xLights and might be running into the memory limit for a process?  If your OS is 64-bit install the 64-bit version of xLights.

**Comment by keithsw1111** [comment]
Can you package the sequence and post a link to that in a dropbox
