### ISSUE TITLE
Output to Lights Toggle Crashes

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#128]
USING OSX 4.0.8

Created a sequence
Toggled ON output to lights
Clicked the Audio rewind to beginning
Click Play
Xlights Crashed

If I toggle output to lights BEFORE I start my sequence, Xlights does not crash

**Comment by dkulp** [comment]
Do you have the crash reports for these?   If you click on the OK on the crash report dialog, it should create a xLights_dbgrpt-*.zip file in your show directory that contains useful info for us.  Main thing would be the backtraces.

**Comment by LightsOnHudson** [comment]
I believe I just get the pinwheel of death and the application just closes.. I'll check and see if it does give a crash dialog report.

**Comment by AzGilrock** [comment]
I was able to cause a crash last night but the crash report didn't have any of our code listed...it was all windows functions.  It seemed like the key to causing the crash is to start playback, stop, hit back to first frame, then hit play again.  Not sure if it matter whether output to lights is selected before or during.

**Comment by LightsOnHudson** [comment]
Pinwheel of death
Created a new musical sequence
Added a 30 second MP3
Added an empty timing track
Added 4 random timing marks
Added 4 individual effects, Life, Balls, Meteors, spirograph
Click on Output to lights
Immediately it prompted that 'Atos needs permission about to generate a bug report'

Pinwheel of death and Xlights is not clickable anymore. I have to use ForceQuit. No bug report.

**Comment by stevegiron** [comment]
It crashes on different computers for me. One of them had a Windows firewall popup as soon asI hit output to lights. Thinking it was TCP related, I deleted my E131 config and added 30,000 channels of DMX on COM1. Crash still occurs.  The offending module reported is NTDLL.DLL

**Comment by dkulp** [comment]
I just stuck a new OSX 4.0.9 build up on my site.  Can you give that a try?  

All the crashes related to the "Output" button that I've been able to reproduce end up deep inside the wxAuiToolbar and/or wxAuiManager class.  I'm wondering if one or both of them is having issues with non-AuiToolbarItems stuck on the toolbar.   This build changes the output toolbar to just use the AuiToolbarItems.  Unfortunately, that ONLY means bitmap buttons so I had to create some hokey icons for them instead of the text.   If it works, we can have Sean (aka: the graphics designer) do something better.  (unless you like my choices)  Alternatively, we'd have to create some bitmaps that just have the text written on them.

**Comment by LightsOnHudson** [comment]
I just downloaded 4.0.9b from your site Dan. The console sees it a 4.0.10.
I created a new musical sequence, and placed about 6 timing marks and at the end of placing the last element in the last timing mark, i clicked on the OUTPUT to lights Icon... And the matrix lit up just fine.

No Crash.

The Matrix and preview window were showing the last placed element (wave effect in this case).

I pressed the rewind audio button and then play, and it played the sequences out to my matrix.

When It was finished I turned OUTPUT TO LIGHTS OFF, and the matrix went dark.

I did encounter something new though.

When I turned the OUTPUT TO LIGHTS back on, the elements did not play out to the matrix that it was currently on. The effect that the sequencer was on before pressing the'outoutput to lights' button, the matrix went dark. And turning output to lights back on, there was no output. I had to click on a different effect in a different timing mark to 'wake up' the matrix output and then I clicked back to the last effect it was on and that was now going out to the lights.

'make sense?'

**Comment by AzGilrock** [comment]
It sounds like its working the way it was designed.  There are 2 play modes...effect play and model play.  Model play is the one that plays music.  Effect play just plays a single effect.  Effect play starts when you drop an effect on the grid or when you click on an effect but you can stop and pause effect play. When you start model play and hit stop it doesn't revert back into effect play unless you click on an effect.

**Comment by LightsOnHudson** [comment]
Ok. Makes sense.

**Comment by dkulp** [comment]
Should be fixed in 4.0.10.
