### ISSUE TITLE
Lag In View

### ISSUE THREAD

**Issue by samstone11** [smeighan/xLights#1281]
When I enter or make changes to models, add new models, create groups, etc, these alterations sometimes do not show in the previews until I completely sign out and back in. I have had a couple of instances where I think the changes have been applied to the wrong model as well, but that also corrects itself when signing back in. This entire issue may well be my unfamiliarity with the program and I'm willing to accept my responsibility if that is the case. Thanks for any input.

**Comment by AzGilrock** [comment]
Sounds to me like you just need to hit the Render All button.  Unless you have a set of files to provide with specific instructions on how to reproduce an issue we can't do anything.  Reopen if Render All doesn't fix it AND you have something to give us.

**Comment by samstone11** [comment]
Apologies for not providing what you needed. Please note:
- Your response was terse and unsympathetic
- I am an older person
- I'm just learning the differences in protocol from LOR, midi sequencing, and E131/DMX.
- If I wanted to be chastised I would still be with LOR 
- I have almost 40 years experience as a hobbyist, but there are many differences as I'm sure you are well aware
- I was recently involuntarily forced into disability retirement
- Before that, I was a business consultant and owner most of my adult life. I helped many men and women build successful, highly lucrative careers for themselves and their families
- My IQ is so high the doctor who administered that test informed me he had a legal obligation to verify it--no problem there-- then register me with the CDC. 

None of that means anything and I'm not asking for any special treatment. I am, however, going to make an observation that I highly recommend you seriously consider: watch your tone. I will give you the benefit of a doubt that you were unaware your response seemed quite rude, unprofessional, condescending, and certainty not  the manner you would want to represent the best group of enthusiasts I've ever seen. 

Still, I sincerely appreciate your suggestion and if I understand the remedy you mentioned I will try it the next time I encounter the issue. In the meantime, I respectfully request you explain the concept/process more thoroughly including instructions where to find and apply it. 

Finally, do not use that tone with me or anyone else again unless you are content to potentially alienate good people with good intentions. X-Lights, and by extension you as well,  have a deserved stellar reputation. Your attitude, intentionally or otherwise, will not be tolerated by some but as I mentioned earlier, I prefer to believe you was unaware your approach could be interpreted negativity.

I wish you and yours well, and will be looking for the details requested above.

Regards,
Sam Stone

**Comment by keithsw1111** [comment]
I really dont think Gils reply was as bad as you are making it out to be. Sure it was short but he directed you to the most common fix and he gave you a follow up avenue if you had additional information. The written word is never perfect as a way to imply tone and you have read a whole bunch into Gil's response that quite frankly I dont see.
