### ISSUE TITLE
Some windows not populating when changing show directory

### ISSUE THREAD

**Issue by ebuechner** [smeighan/xLights#1283]
There was an earlier issue that was fixed by Keith when changing sequences with multiple monitors that house preview model preview and other windows would not populate until forced by clicking on the house preview button.
The same thing is still happening with multiple monitors but only when you're changing show directories.

**Comment by keithsw1111** [comment]
I need video Ed

**Comment by ebuechner** [comment]
This is really a minor issue but I thought I would document it.

**Comment by AzGilrock** [comment]
For this...every show directory has it's own set of perspectives so how do we know the directory you switched into was setup to have those windows displayed out there?
