### ISSUE TITLE
3D.31 - MAC - Changing DMX style immediately crashes Xlights

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1285]
I just started messing with DMX lights so I added one to the layout and wanted to change the style to flood and it immediately crashes Xlights every time on my MacBook, seems ok in older versions on my pc

here is a video showing it all step by step on a fresh Xlights folder - https://youtu.be/2j0Po9kk69k

I attached the crash report that shows up, not sure if that helps at all

Please let me know if there's any files you need to test
[crash.txt](https://github.com/smeighan/xLights/files/2497661/crash.txt)

also confirmed this does not happen on the PC version, only Mac

**Comment by dkulp** [comment]
I believe this was fixed in 34
