### ISSUE TITLE
ESEQ is creating 1 channel higher

### ISSUE THREAD

**Issue by nmiller0113** [smeighan/xLights#1289]
I am creating a bunch of single channel A/C elements and make them ESEQ's to run in the background.  They are triggering the model 1 channel higher than the model I created the ESEQ in.  I've confirmed the channel is correctly set up in the layout and controller, and in the FSEQ's or by manually triggering the model in the Test tool, both work fine.  I'd be happy to provide an ESEQ for review.

**Comment by nmiller0113** [comment]
This was just reported on Facebook and it seems, based on the video here https://www.facebook.com/groups/xLights/permalink/1965422423493503/ ,that it is not the same problem as last time, it just seems very similar.  The ESEQ appears to work correctly in FPP but not in xSchedule.  So maybe it is due to a problem in the way xSchedule is reading the ESEQ file.

**Comment by bchiaino** [comment]
here's a video showing what was going wrong from exporting a eseq and playing in xschedule vs FPP

https://youtu.be/4yYVit8XSfg
