### ISSUE TITLE
Edit Display Elements window not full view

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#129]
USING OSX 4.0.8

When opening the Edit Display Elements window, it is not in full view. 
You have to grab the edge and drag it to be a bit bigger then it 'pop's' to the right size to see the elements on the item. 
See attachment.
![screen shot 2015-03-31 at 8 55 56 am](https://cloud.githubusercontent.com/assets/10136122/6942095/6397c0c0-d842-11e4-8c7b-8e06f8a3d6fc.png)

**Comment by LightsOnHudson** [comment]
I did notice though, that if I went back into the Display Elements window after I had resized it the first time, it was sized properly. It was just small on the first opening of the window that had the issue.

**Comment by LightsOnHudson** [comment]
This is not fixed in 4.0.11 build on Dan's website that I just downloaded.

**Comment by dkulp** [comment]
You MAY need to edit your xlights_rgbeffects.xml file and delete the perspectives.  The size of the windows are part of the perspectives so if you have a perspective with the smaller sizes saved, you'll still get the smaller window.

**Comment by LightsOnHudson** [comment]
I just deleted the whole XML file, and re-opened xLIGHTS and yes, the window is visible now.

I did open a different ticket about other docked panels that are having the same issue. Maybe your fix will work over there as well??
