### ISSUE TITLE
Xlights 2018.37 Linux version Render buffer getting stuck

### ISSUE THREAD

**Issue by extremeskillz** [smeighan/xLights#1293]
Just updated to this version and the rendering engine is not rendering effects correctly on the linux version, especially on layers. When hitting rendering all it just gets stuck and apparently jumps out when I hit F5. Windows version is not experiencing this.

**Comment by AzGilrock** [comment]
"especially on layers"  effects only exist on layers.  Everywhere you place an effect is a layer.

**Comment by cjd** [comment]
Can you please grab/attach the /tmp/xLights_l4cpp.log file?
Are you using a self-compiled or pre-compiled version?
Also - what linux distro/version are you on?

**Comment by extremeskillz** [comment]
HI Chris. I will do later today. AZGilrock, what I mean is when an effect is applied to the layers I am making they disappear. As soon as I render all, the render engine freezes, effects disappear from the preview, and the render engine is or looks like its frozen. I hit F5 and the render engine stops and I still don't have any effects on my layer(s). I will do a screen grab video to show this. 

Chris to answer your question: Ubuntu 18.04LTS.

**Comment by extremeskillz** [comment]
[Video and Log.zip](https://github.com/smeighan/xLights/files/2506194/Video.and.Log.zip)

Attached file of screencast and log per Chris' request.

**Comment by extremeskillz** [comment]
Seems the issue I had here is fixed in .41. Can be closed. Thanks.
