### ISSUE TITLE
xSchedule - Countdown a set of playlist items

### ISSUE THREAD

**Issue by tmeyermn** [smeighan/xLights#1297]
I would like the ability to countdown a subset of playlist items.  I have a loop of 10 playlist items and the first 3 are a "preshow" where I have a countdown to the actual lightshow running.  I know there is a countdown per playlist item but I'd like one for X playlist items.

**Comment by keithsw1111** [comment]
As described no ... but maybe a countdown/up for a specified number of seconds ... and you can work out how many that should be.

**Comment by tmeyermn** [comment]
I think that would work as long as the count up/down runs for the specified
number of seconds (displayed in m:ss) and then stops so it doesn't
interrupt the regular show.

**Comment by tmeyermn** [comment]
Thanks Keith!
