### ISSUE TITLE
Layout tab, Start Channel Window - cancel does nothing..

### ISSUE THREAD

**Issue by darylerwin** [smeighan/xLights#1299]
Forces you to hit OK .. Cancel should just return you to the prior screen hopefully without taking any changes done on at that window.

**Comment by AzGilrock** [comment]
When you post here quit trying to tell us what something "should" do.  We determine that not you.

**Comment by darylerwin** [comment]
Not meaning to .. I wont want to say its broken if that is the expected behaviour.

**Comment by AzGilrock** [comment]
Ok peace.  The last couple issues sounded like orders from my boss...lol.  Anyways I'm signing off my computer and heading to a 4 day vacation so I'll be forgetting about xLights for a few days.
