### ISSUE TITLE
Bug: Changing Sequence Timing doesn't actually do anything

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#1301]
Good evening, I am on xLights 2018.34 - 64 Bit on a Windows 10 machine.

I recently switched a sequence from 40ms to 50ms using the Settings > Sequence Timing dialog box.
However, upon playing the song in xSchedule, the listed frame-rate did not change.

I tested this multiple times:
Once simply saving the XML but not re-rendering.
Once saving the XML and "Rendering on Save."
Once manually deleting the FSEQ and then "Rendering on Save."

In all instances, the Settings menu states my new refresh-rate but the playback result is no different.

**Comment by keithsw1111** [comment]
I just tried it and it seems to work fine.

**Comment by keithsw1111** [comment]
This should be fixed.
