### ISSUE TITLE
USB-DMX end channel limit - teensy 3.2+octows2811

### ISSUE THREAD

**Issue by CiviCest** [smeighan/xLights#1303]
I was able to get teensy 3.2+octows2811 running with xlights using FastLed and Octows2811 library and in xlights I set up the controller as USB - DMX protocol but now I ran into end channel limit on that controller. Octows library allows 8 different outputs at the same time and i have 200 pixel nodes on each output so total channels needed are 4800 but channel limit in xlights is 3036 - is there a way to increase it to 4800 channels?

**Comment by CiviCest** [comment]
Thats a no then?

**Comment by keithsw1111** [comment]
I dont understand. https://github.com/smeighan/xLights/commit/f6e16d2a06f2e303b3ccaf7b9f6c532176b81f75

**Comment by CiviCest** [comment]
I see u change it for the future releases-Thank you! 🥇
