### ISSUE TITLE
xLights closes *sometimes* after model export (ESEQ)

### ISSUE THREAD

**Issue by nmiller0113** [smeighan/xLights#1304]
Sometimes when I create an ESEQ xLights just closes when it completes.  It doesn't crash, it just closes.  But it doesn't always do it.  Sometimes it just make the sequencing grid go all black.  Sometimes, it works just fine.  It's strange.  I've checked the log (attached), and it doesn't even show me making an ESEQ even when it doesn't close or do anything out of the ordinary.  Shouldn't there be a log of that?  Anyway...the attached log here doesn't show anything about creating the 5 ESEQ's I just created.
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/2522150/xLights_l4cpp.log)

**Comment by keithsw1111** [comment]
We log what we find useful ... not every action.

As for the crash I need to sequence and instructions about how to reproduce the problem.

**Comment by gizmohd** [comment]
I have a very simple sequence that does it every time I export an ESEQ file.... 
[backgroundsequence.zip](https://github.com/smeighan/xLights/files/2523378/backgroundsequence.zip)

Whenever i export the simple effect from Floods for example.. it causes xlights to exit very non-ceremoniously

**Comment by keithsw1111** [comment]
So it turns out this bug is really really specific and if you hadnt shared the specific sequence i doubt i would have found it. It only occurs when you export an ESEQ for a model which has less than 20 channels. And the more times you export the model the more likely a crash becomes ... and it can crash pretty much anywhere.

**Comment by nmiller0113** [comment]
Wow, glad you were able to find it.  Thanks Keith!

**Comment by gizmohd** [comment]
Great work Keith!
