### ISSUE TITLE
Possible import or render bug?

### ISSUE THREAD

**Issue by nmiller0113** [smeighan/xLights#1305]
Dan, Keith and Gil.  I also sent you a PM on this but I'm not sure if you actually see those, so I'm sending here as well.  I can reproduce this every time, on multiple computers, on the latest version of xLights for both Windows and Mac.  Here's my issue.

I'm noticing an import effect or render issue of imported effects.  I use this feature to import sequences I buy from holidaysequences.com.  I use the import effects option rather than the data layer option because I need to scale it to larger models and I don't want to have to tweak channels in Lightorama to make this work.  I know we can import raw .SUP files but it's not a perfect 1to1, Gil and I have actually discussed this, as an example things like Fan effects don't always map across correctly.  So I use the import effects option with a mapping file I created.  Since it significantly impacts render times due to that type of import I usually save that once and then create another sequence and import the xLights sequence I just created from the first import and save it as a data layer in the new one....no render delays.  I've been doing this for years without issue for my megatree and it has worked amazingly until now when trying to do the exact same thing to map to a matrix for one of the halloween matrix sequences I purchased from holidaysequences.

When I import and map all seems to go well.  Then I rendered and tested, and there are large blank (off) sections in the matrix.  I even expanded down to the node level just to confirm.  Just to make sure I wasn't going crazy I modified my livwinmat model, the one I'm importing to, to match the channels to the LMS file, since I can't do any mapping into a data layer..and then imported into the data layer.  I tested again and this time everything played perfectly.  I expanded the model down to the node level and it was very clear there was a difference between the import effects results and the import into the data layer results.  I'm not sure if it is an import issue or a rendering issue but something isn't right.

Dan, Keith and Gil, I've included all the files you need in a google drive I've PM'd you since it includes a paid sequence to test / reproduce with.  I've included the saved sequence (xml) of both the import effects option and the import to data layer option...as well as every other file I thought you may need.  By the way, in order to test the import into the data layer you'll need to modify the livwinmat model to be 24 strings of 50 nodes, horizontally, starting from the bottom left and each string is its own DMX universe 1 thru 24, 150 channels in each left to right.  My mapping file should give you a good idea.

Hopefully, and if you have the time, you'll be able to see what is failing and why.  I know I can workaround by changing the channels on my matrix and but I'd rather not have to do that and also change the channels and configuration of everything else in my display.  The channel mapping import effects feature has worked so well for me so far and I'm hoping to keep using this option :)  Thank you again for your amazing work and support and please let me know if you have any questions or if I wasn't clear.

**Comment by nmiller0113** [comment]
I did some additional testing as I also bought 3 more holidaysequences Matrix sequences and they all imported without a problem, though their xml file size was significantly smaller.  I even recreated the LMS file in Superstar from the SUP and still nothing.  But I don't believe it's the SUP or LMS since when I import it as a data layer it works just fine.  It's only when I use the Import Effects option.  Also, just because it may be a size thing, I took one of my largest XML files and rebuilt it.  It is for my megatree but similar to this in that I'm taking a holidaysequences SUP file, turning it into an LMS and then importing and mapping it.  It worked no problem, so it's not a size thing.  I've got no idea why xLights will not properly import the effects from and render this one sequence but there is definitely something wrong somewhere...I suspect it's something in the sequence that xLights isn't liking.  Maybe it's the resulting FSEQ file size?  Who knows...but I'd love to get to the bottom of this as it's strange!
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/2522152/xLights_l4cpp.log)

**Comment by nmiller0113** [comment]
@keithsw1111 - I sent you a PM response on this but also thought I'd mention it here.  I was wondering if you'd like to get on a zoom call so I can further explain this issue and add some clarity.  Thanks!

**Comment by keithsw1111** [comment]
Sure but timezones arent friendly. Apart from Friday and Saturday evenings your time I am either asleep or at work.

**Comment by nmiller0113** [comment]
@keithsw1111, I understand.  I manage a team in Australia.  I'm more than happy to take a call at odd time, on my end, to accommodate your availability...even during the week.  I'm usually up at strange hours :) You name a time, and I'll make it work :)

**Comment by nmiller0113** [comment]
Fixed, thanks @keithsw1111
