### ISSUE TITLE
crash when renaming model in layout tab

### ISSUE THREAD

**Issue by reenx** [smeighan/xLights#1306]
I start xlights.
Switch to layout tab.
select a model. ("raam-3")
change the name of the model in the properties column.
press enter or tab to change focus from the name. 
crash.
This happens every time. So 100% reproducable.

I can fix it by editing the xml file manually. After that xlights uses the new name without any problems. Just the action of renaming will crash xlights.

Other crashes happen for instance when I add a group. Or copy a model. (not always).
This is on a Fedora linux machine with a build of commit id: ea7b9d84110a8f605ff5579df1d9b048f8fe9552

Any ideas?
Regards,
Erik Rakhorst

[xLights_dbgrpt-17795-20181027T231005.zip](https://github.com/smeighan/xLights/files/2522220/xLights_dbgrpt-17795-20181027T231005.zip)

**Comment by keithsw1111** [comment]
I cannot reproduce the problem with the steps above on windows.

**Comment by reenx** [comment]
The problem is solved.
I did a make clean, but unfortunately it did not clean the wxwidget dir. 
I had still an old wxwidget build. (I build xlights myself). By deleting the wxwidget directory and building it again my crash is gone.
