### ISSUE TITLE
Right Click "Show All Effects" doesnt show/reveal effects hidden inside groups.

### ISSUE THREAD

**Issue by darylerwin** [smeighan/xLights#1308]
Not sure this is always the case - as I see it does show / expand most groups.

![fullexpandedmanually](https://user-images.githubusercontent.com/25016569/47678685-bf8cfc80-db98-11e8-885f-9a31c410d1bf.jpg)
![showalleffects](https://user-images.githubusercontent.com/25016569/47678686-bf8cfc80-db98-11e8-85d3-bf20d74c7f3b.jpg)
![layout with effects collapsed](https://user-images.githubusercontent.com/25016569/47678688-bf8cfc80-db98-11e8-9977-8f708a98840e.jpg)

**Comment by darylerwin** [comment]
Bottom pic is collapsed, Middle is after the right click show all effects. Top pic is what is really there - the group snowflakes didnt expand.

**Comment by darylerwin** [comment]
Sounds good thanks for the explanation.

**Comment by gerryhernandez** [comment]
I'm experiencing the same problem, but it's not working as described. Effects do, in fact, remain fully hidden until I manually expand subgroups. I've double and triple checked; the "Show All Effects" feature is not simply showing *one* instance of the effect, as described. This is as of 2018.50.

**Comment by keithsw1111** [comment]
I consider that expected behaviour. Problem is if I open groups and someone has the models and groups listed (which is extremely common) then both would be shown. That is not very useful.

**Comment by darylerwin** [comment]
We had a user on zoom last night and their lights were coming on at a certain spot and he couldnt find the reason. We did show all effects and it didnt appear .. we had to hunt and drill down the various models to the strand/node level to find the actual "effects".

**Comment by keithsw1111** [comment]
Daryl .... Just add back in all the models into the master view and try it again.
