### ISSUE TITLE
Crash when uploading to F16v2

### ISSUE THREAD

**Issue by ehgilman** [smeighan/xLights#1309]
When I upload E1.31 no problem, when I upload output it crashes.  xlight v 2018.40 64 bit.  This github will not recognize the dump file.

**Comment by keithsw1111** [comment]
You should be able to upload the .zip crash dump file.

**Comment by AzGilrock** [comment]
Yeah look at issue #1275 he attached the zip file no problem.

**Comment by ehgilman** [comment]
[xLights_dbgrpt-8808-20181030T133244.zip](https://github.com/smeighan/xLights/files/2531472/xLights_dbgrpt-8808-20181030T133244.zip)
I got it now. strange... but here it is

**Comment by keithsw1111** [comment]
This will be fixed in .41.
