### ISSUE TITLE
ENHANCEMENT: Output to lights display current position on timeline

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#131]
OSX 4.0.10
Currently when output to lights is enabled, or the preview window is enabled and viewable, the effects that are visible are only the effects that have the focus. 

It would be nice to be able to click in the timeline and the position of the mouse in the timeline reflects what to output to the lights/preview window by displaying the effects below the cursor location. 

Much like as you are playing the sequence with music, as the bar is moving along it is displaying/ sending out what is below it. That same effect to see when you are manually positioned anywhere in the timeline.

**Comment by AzGilrock** [comment]
I think now that we can preview the whole house this one is satisfied.  You can click anywhere in the timeline and hit play and see the whole house preview.
