### ISSUE TITLE
Ubuntu 18.04.1 LTS - unable to open appImage .41

### ISSUE THREAD

**Issue by tgodfrey73** [smeighan/xLights#1312]
Previous appImages work fine. Unable to open .41. Probably need to update something locally but not sure what. 

From [xLights_l4cpp.log](https://github.com/smeighan/xLights/files/2545578/xLights_l4cpp.log): 
2018-11-03 23:45:56,782 140259968879488 log_base [DEBUG]                     Creating GL Canvas for TimeDisplay
2018-11-03 23:45:56,785 140259968879488 log_opengl [INFO] TimeDisplay - glVer:  (null)  ((null))((null))
2018-11-03 23:45:56,785 140259968879488 log_base [CRIT] Crash handler called.
[xlights41-2018-11-03_23.45.21.zip](https://github.com/smeighan/xLights/files/2545580/xlights41-2018-11-03_23.45.21.zip)

tom@Server-705:~$ glxinfo | grep "OpenGL version"
OpenGL version string: 3.0 Mesa 18.2.2

**Comment by cjd** [comment]
The commit leading to the crash seems to be https://github.com/smeighan/xLights/commit/d3f20d4a58544593089074126fc82b6e6967154a
In particular the change at line 141/142 from
xlColor c(wxSystemSettings::GetColour(wxSYS_COLOUR_BTNFACE));
to
xlColor c(ColorManager::instance()->GetColor(ColorManager::COLOR_ROW_HEADER));

**Comment by cjd** [comment]
Strangely the appimage works on my debian-based systems but not ubuntu ones

**Comment by extremeskillz** [comment]
Yes, experiencing the same issue here for .41 on ubuntu 18.04. I reverted back to .37 for now.

**Comment by cjd** [comment]
Checked on another system - problem is not contained to appimage as it also occurs on local compile from source

**Comment by cjd** [comment]
My original thought was wrong (unclean rebuilds)
I just bisected and found the problem commit as ec7b3fb2b06af90f39053b1f2108e6a19edfd53d
If I revert that commit it works - will see best way to fix

**Comment by cjd** [comment]
Can you try re-downloading the appimage for .41 ?
I have applied a quick fix to get it working and it has been successful so far for me

**Comment by tgodfrey73** [comment]
Yes - it opens now and looks like it's working. Thanks!

![screenshot from 2018-11-04 21-38-56](https://user-images.githubusercontent.com/5660614/47976836-21a69f80-e07a-11e8-91c3-70c1cba26f3c.png)

**Comment by extremeskillz** [comment]
Works for me now after the fix. Thanks!!
