### ISSUE TITLE
Background showing upside down

### ISSUE THREAD

**Issue by mmedrano360** [smeighan/xLights#1315]
Hello, 
I'm new to this but I'm trying to use an image of my house as a background but it shows upside down.
I'm using window 64bit

**Comment by nmiller0113** [comment]
@mmedrano360, dumb question but did you confirm the picture wasn't upside down?  Sorry, wasn't trying to sound rude, but I'm using the same version and not experiencing that at all.

**Comment by mmedrano360** [comment]
No, 
I have it right but when it pulls the image, it shows it upside down.
![20181105_174258](https://user-images.githubusercontent.com/44791279/48037720-b32a1600-e13b-11e8-8882-70c7f63da53d.jpg)


![image](https://user-images.githubusercontent.com/44791279/48037754-d48b0200-e13b-11e8-9c1a-899387c2fca2.png)

**Comment by keithsw1111** [comment]
So why was this closed? Can you upload the original image.

**Comment by AzGilrock** [comment]
I got the email so I know it was closed because he uploaded the photo to show it was correct before putting it into xLights and it posted upside down on GitHub...lol.

**Comment by mmedrano360** [comment]
Hello, 
No, i closet it beacuse I solved it. For some reason ,other than the picture being upside down, I was grabbing it upside down. What i did to fix it was convert it tho bitmap and then it worked. Again, the picture was in the right orientation but when it created the link   on the software, it turned it upside down.

**Comment by AzGilrock** [comment]
Yeah well you can say whatever but I've got the email where you tried to show us the picture was correct and it posted upside down.  You say the "picture was in the right orientation" but do you really know how picture rotation is stored?   Just Google "Why Your Photos Don't Always Appear Correctly Rotated ".

**Comment by mmedrano360** [comment]
Can you tell me why it does that? I'm no trying to argue with anybody. I'm learning how to use the software. I took a pic of my house, saved it into my computer and tried to upload it to the software.  Also, when I tried to show what was happening it did the same on this website uploader so I figured there was something wrong with the picture. When I looked at the pic, it was oriented right but when created the link, it was upside down.

**Comment by AzGilrock** [comment]
I would need the file to determine it.  Rotation orientation is usually stored in the EXIF information of a photo.
