### ISSUE TITLE
Xlights Freezes when trying to edit a Sub-Model

### ISSUE THREAD

**Issue by DewaltGuy** [smeighan/xLights#1318]
When I try and edit the sub-models of any of my custom models Xlights freezes and will not let me do anything.  

I tried creating a brand new model. When I finished putting the model data into it I selected the Sub Models edit icon and it immediately froze again.

**Comment by DewaltGuy** [comment]
I tried setting up a new show directory that was empty.  Added a null controller with 20,000 channels.  Created a new model - pasted in the model data from excel.  Then went to Sub-Models and Xlights froze again.  Just wanted to see if what any of my configuration files.

I just tried this on another computer using the same data and it worked fine. So this appears to be computer specific.

**Comment by AzGilrock** [comment]
Obviously this is not happening for hundreds of users so would it be too much trouble to tell us what version you are running, what OS you are using, and provide the models file?

**Comment by AzGilrock** [comment]
Might be a long shot but I'd do a Package Log File and post it so we can see if there are any messages.

**Comment by DewaltGuy** [comment]
Xlights Version 2018.42
Windows 10 Enterprise (Version 1703)

I added the model
I also include the packaged log file.

[Snowflake.zip](https://github.com/smeighan/xLights/files/2554600/Snowflake.zip)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/2554603/xLightsProblem.zip)

**Comment by computergeek1507** [comment]
This normally happens when the sub model dialog opens off screen.

**Comment by computergeek1507** [comment]
If you go to the menu bar and select "View" -> "Windows" -> "Reset to Defaults" should fix it.

**Comment by DewaltGuy** [comment]
You are right..  The screen was off screen somewhere.   I should have realized that!  Thanks everyone for your assistance.  Brain obviously wasn't working.
