### ISSUE TITLE
Memory leak on Mac? 

### ISSUE THREAD

**Issue by dusty-dad** [smeighan/xLights#1319]
When using picture effect and effect is repeating so changes can be made the memory blooms to take over all available memory. Maxed the memory pressure causing a force quit, I restarted the computer and in half hour was in the same situation.  When I monitor the activity monitor xlights is always on top and grows as long as it runs and never drops back unless application is quit and restarted. I posted pictures on the fb forum and they suggested I submit here.  I am running v41, 2018 have been using xlights for over a year. I have never had this “out of memory’ error until now.  Memory is fine loading and running a sequence but once it uses memory  to Save, rende, it make changes it does not seem to let go. I am not a computer guy but if you have more questions I will try and answer.

**Comment by keithsw1111** [comment]
Can you package the sequence and maybe make a video showing us what you are doing.

**Comment by dusty-dad** [comment]
What does package the sequence mean? Do you want me to shoot the video with my phone?
Dave

Sent from my iPhone

On Nov 6, 2018, at 2:41 PM, Keith Westley <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you package the sequence and maybe make a video showing us what you are doing.

**Comment by keithsw1111** [comment]
Package sequence is in the tools menu. Open the sequence which has the issue and then go to the tools menu and package the sequence up into a zip file and post it here. That lets us load up your show and see if we can reproduce it.

Video with a phone works ... its not great. Recording a video of your screen directly is better as it gives us a clearer picture. Either way ... just make sure you speak in the video explaining what you are doing and what you are seeing. Start from the point you open the sequence so we dont miss something you are doing that may be triggering the problem.

**Comment by dusty-dad** [comment]
On Nov 6, 2018, at 3:04 PM, Keith Westley <notifications@github.com<mailto:notifications@github.com>> wrote:


Package sequence is in the tools menu. Open the sequence which has the issue and then go to the tools menu and package the sequence up into a zip file and post it here. That lets us load up your show and see if we can reproduce it.

Video with a phone works ... its not great. Recording a video of your screen directly is better as it gives us a clearer picture. Either way ... just make sure you speak in the video explaining what you are doing and what you are seeing. Start from the point you open the sequence so we dont miss something you are doing that may be triggering the problem.

**Comment by dusty-dad** [comment]
The video was to large  even after I compressed the file so I sent via ,mail drop I think there is no record of it going out so let me know if there is a screen capture program and I can try that.

Dave
On Nov 6, 2018, at 3:04 PM, Keith Westley <notifications@github.com<mailto:notifications@github.com>> wrote:


Package sequence is in the tools menu. Open the sequence which has the issue and then go to the tools menu and package the sequence up into a zip file and post it here. That lets us load up your show and see if we can reproduce it.

Video with a phone works ... its not great. Recording a video of your screen directly is better as it gives us a clearer picture. Either way ... just make sure you speak in the video explaining what you are doing and what you are seeing. Start from the point you open the sequence so we dont miss something you are doing that may be triggering the problem.

**Comment by dusty-dad** [comment]
Attachment available until Dec 6, 2018
Here is the video
Click to Download<https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAfh_SOq94lrvjFvH4ZVv8ESyWsbwAcbDGbnAqzu2pL7rH8rJcgLrHvyh%2F%24%7Bf%7D%3Fo%3DAiAdWpw-uP7Gbwe3QLj4eYKfn3zT9UZuWYEjqhiLSESL%26v%3D1%26x%3D3%26a%3DB5Kf97DhLkUO_dpH7PyuxBfbBWzrAzasRwEACAHIAP9ksMjlA3YDRw%26e%3D1544132468%26k%3D%24%7Buk%7D%26fl%3D%26r%3DD47A438C-C8F3-4CF1-A528-F292C0EDC824-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D33F39882-40F1-4A8C-B1BC-9F9A7372A930%26p%3D60%26s%3D1J_JZ5yT_4NhbX4g1-_9NroPLjI&uk=owrMnyZHH0QHEBa0N8zI1A&f=IMG_6439.MOV.zip&sz=788795465>
IMG_6439.MOV.zip
788.8 MB

On Nov 6, 2018, at 3:04 PM, Keith Westley <notifications@github.com<mailto:notifications@github.com>> wrote:


Package sequence is in the tools menu. Open the sequence which has the issue and then go to the tools menu and package the sequence up into a zip file and post it here. That lets us load up your show and see if we can reproduce it.

Video with a phone works ... its not great. Recording a video of your screen directly is better as it gives us a clearer picture. Either way ... just make sure you speak in the video explaining what you are doing and what you are seeing. Start from the point you open the sequence so we dont miss something you are doing that may be triggering the problem.

**Comment by keithsw1111** [comment]
I see the video ... but no packaged sequence

**Comment by dusty-dad** [comment]
[I am Santa Clause .zip](https://github.com/smeighan/xLights/files/2559148/I.am.Santa.Clause.zip)

**Comment by keithsw1111** [comment]
I took a look at this last night and I do think there is an issue here with looping GIFs and possibly video as well.

Challenge is i am struggling with my dev tools and isolating exactly how the way we are handling images is leaking the memory. But i am pretty sure that is what is happening. The leak is not as obvious when we dont loop the GIFs.

I think video is similar because I had a user running numerous videos in xSchedule which blew memory utilisation out massively. 192GB from memory. The video reader/cache does similar things to the GIF reader when it comes to handling images.

**Comment by dkulp** [comment]
There is a serious reference count bug on the Mac.  I read the specs on a function wrong.

**Comment by dusty-dad** [comment]
ok so what do I do to fix? Or do I do nothing until another version come out.  Will purging the cache help or do I just monitor and when memory pressure gets close save, quit and then restart?

**Comment by dkulp** [comment]
I'm working on getting a 2018.42b up soon.

**Comment by dusty-dad** [comment]
ok, Thanks! 
thank you so much for all the work love the program and have enjoyed getting out of my comfort zone to do a cool display the last 2 years this has been wonderful for me and my boys.  
 Have a great season!
Merry Christmas !

Dave

**Comment by dkulp** [comment]
It's up now.   Should stay under 900MB now.

**Comment by keithsw1111** [comment]
Is the bug OS X only dan?
