### ISSUE TITLE
GIF Crash

### ISSUE THREAD

**Issue by dconley1964** [smeighan/xLights#1323]
I had the same problem on .41 on three different computers and any GIF I try to use.

[xLights_dbgrpt-13852-20181109T151247.zip](https://github.com/smeighan/xLights/files/2567366/xLights_dbgrpt-13852-20181109T151247.zip)
![happy_thanksgiving_gif-1](https://user-images.githubusercontent.com/35935662/48285749-94749980-e431-11e8-8dc7-5baf93d7ad78.gif)

**Comment by dconley1964** [comment]
Just downloaded and tried the same thing in .44.  Same issue.

**Comment by keithsw1111** [comment]
Yeah ... @cjd is going to have to take a look ... this crash appears to only occur on Linux.

**Comment by ghormann** [comment]
I just did a custom compile 2019.15 on Ubuntu 18.04.02 and it worked. I'm assuming others have the problem using AppImage?

**Comment by dconley1964** [comment]
I just ran a test on the appimage of 2019.14.  Running Mint 19 .1 with kernel 4.18.  Animated gifs run fine in the house preview with output to show turned on.  I don't have my matrix hooked up right now so I can't verify function there.  No crashes.

**Comment by ghormann** [comment]
I tested 2019.14. in AppImange with Unbutu 18.04.   Also no problems.

Seems like we can close this issue.
