### ISSUE TITLE
Crash on open when clicking on .xml file. 

### ISSUE THREAD

**Issue by Bill-Paulus** [smeighan/xLights#1324]
When clicking on a sequence .xml file in the show folder it fails to open and gives the program has stopped working error. It doesn"t get far enough to create a crash log file that I can see. This started with .42 and is still the same with .43. The program opens fine when using icon and the open file button. Went back to .40 and it works fine.

**Comment by keithsw1111** [comment]
Without a copy of your files this is not going to get fixed.

**Comment by Bill-Paulus** [comment]
Not sure what files you need Keith, it doesn’t get far enough to do a crash report that I can see if that’s what you are talking about.

**Comment by keithsw1111** [comment]
Package the sequence in .40 ... and i can try and load it in .44.

**Comment by keithsw1111** [comment]
What file are you trying to open. I opened mary did you know ... no issues.

Can you maybe post the crash log. I got nothing so far to go on.

**Comment by Bill-Paulus** [comment]
As far as I can tell it doesn't get far enough to create a crash log. Here is a video of what happens.
https://www.dropbox.com/s/sm1scsvnz7sxmts/IMG_8854.MOV?dl=0

**Comment by keithsw1111** [comment]
If after you "crash it" you go back to old version and then package logs ... that will still give me the logs showing where it failed.

**Comment by Bill-Paulus** [comment]
[xLightsProblem.45.zip](https://github.com/smeighan/xLights/files/2591908/xLightsProblem.45.zip)
[xLightsProblem.40.zip](https://github.com/smeighan/xLights/files/2591909/xLightsProblem.40.zip)

**Comment by Bill-Paulus** [comment]
Sorry for the delay life got in the way

**Comment by keithsw1111** [comment]
I may have this fixed in .47 ... try instead opening the xml file after you start xlights ... instead of opening it the way you do in the video.

**Comment by Bill-Paulus** [comment]
It has always worked that way it just stopped working the way in the video with .42.
I usually opened sequences this way while working on them. I am getting by that way just a PIA being used to doing it the other way.

**Comment by keithsw1111** [comment]
Sure ... but as I say I have a fix which will be in .47.

**Comment by Bill-Paulus** [comment]
Thanks Keith!

**Comment by Bill-Paulus** [comment]
All Fixed!!! Thanks again Keith!!
