### ISSUE TITLE
Disabled function keys on the Mac

### ISSUE THREAD

**Issue by kwalkerk** [smeighan/xLights#1325]
I'm using the latest version of xLights running under OS X 10.13.6.

After using xLights and closing the program the function keys on my mac no longer work.  Specifically the ones dealing with sound and volume

**Comment by keithsw1111** [comment]
We dont do anything with them

**Comment by AzGilrock** [comment]
Doesn't appear like a problem we can fix.  I'm sure our Mac developer would not be putting up with this if it was occurring.
