### ISSUE TITLE
Bezier curve not working on existing models in 2018.43. Works in 2018.42.

### ISSUE THREAD

**Issue by jtrpop** [smeighan/xLights#1326]
Posted in Official xLights Support Group by Jason Rasmussen.
Just upgraded from 2017.42 to 2018.43 and one part (circled green) in my poly line does not curve where it should be (red arrow pointing to purple curve). I try bending it back but it's all out of wack.
![image](https://user-images.githubusercontent.com/44937396/48309297-dd107d80-e52b-11e8-9e68-6978f21327a2.png)

It used to curve, but after the upgrade it's straight and will not bend properly (brightness 100%, ignore arch in white). Notice how the bezier curve still shows, but the poly line doesn't follow. 
![image](https://user-images.githubusercontent.com/44937396/48309308-0204f080-e52c-11e8-8887-6ca458d7e7de.png)

Installed 2018.42 and I was able to bezier curve back properly now.
![image](https://user-images.githubusercontent.com/44937396/48309315-1648ed80-e52c-11e8-9103-4e124ba057fa.png)

**Comment by keithsw1111** [comment]
I'm going to need your show files ... I cant reproduce the problem.

**Comment by jtrpop** [comment]
Hi Keith,

I just re-installed 2018.43 and my bezier curve was wrong. Downgraded to 2018.42 and bezier curve is back.  Show files attached. Thanks again for all you do!
[2018-11-11-000323 (2018.43).zip](https://github.com/smeighan/xLights/files/2569160/2018-11-11-000323.2018.43.zip)

**Comment by keithsw1111** [comment]
As a workaround select individual segements
