### ISSUE TITLE
Copy error

### ISSUE THREAD

**Issue by tobrien82** [smeighan/xLights#1327]
Can not copy/paste model or row effects.

**Comment by tobrien82** [comment]
weird, i rebooted, deleted the model and was able to paste. If there are previous effects already on the model it won't replace (I could have sworn it did before).

**Comment by keithsw1111** [comment]
Copy and paste has never overwritten existing effects.

**Comment by tobrien82** [comment]
Thanks Keith!

I could have sworn I did it before..lol


Get Outlook for Android<https://aka.ms/ghei36>

________________________________
