### ISSUE TITLE
Enhancement - Model List - Start & End channels on each model

### ISSUE THREAD

**Issue by Xenialights** [smeighan/xLights#133]
When the Model List box is displayed, would it be possible to add a second and third column that would be the start and end channel for each model.

**Comment by Xenialights** [comment]
Inadvertently closed

**Comment by stevegiron** [comment]
That information is already presented in two other locations within the application. It's on the Test page and on the modify model page.

**Comment by Xenialights** [comment]
I understand the info is available in two other locations but when you are building a new models you are constantly opening and closing other models to check channel numbers.  If they displayed on the model list it would greatly speed up model building and reduce errors from incorrect channel ranges or overlapping of channels.

**Comment by LightsOnHudson** [comment]
Would it be of benefit that the start channel of a new model being created is the next available channel from available 'pool' of channels taking in consideration the total channels already configured?

if you have 5 models already taking up channels 1-4800. When you click on a NEW model the start channel is already populated 4801 for you?

**Comment by stevegiron** [comment]
Would not work for me as sometimes models are made up of multiple other existing models to get different effects. Take for example the whole house model.

**Comment by AzGilrock** [comment]
We are showing this info on the model list now.
