### ISSUE TITLE
media sequence not playing

### ISSUE THREAD

**Issue by 1991mustang50** [smeighan/xLights#1333]
open xlights, I am in my show directory. go open sequence(xml file). it brings everything up press play it doesnt play. i notice that the fps will jump around a bit. i have tried saving(rendering) it, updating xlights(from 41 to 45), even uninstalling and reinstalling xlights. the only way i can get it to play is if i go to setting and change it from media to animation (this removing mp3 song). go back to sequence press play and it plays without music. not sure what i can upload. let me know what i can do thanks

**Comment by 1991mustang50** [comment]
closed xlights and restarted laptop fixed it. must of been a update on laptop. sorry

**Comment by keithsw1111** [comment]
Typically this happens when your audio drivers are broken. Reboot may have fixed them
