### ISSUE TITLE
No crash report, but crashes

### ISSUE THREAD

**Issue by ellceywaup** [smeighan/xLights#1334]
I had .37, updated to .46. Trying to bring new models into last years sequences. Opened a sequence and selected render all because visualizer wouldn't show up. Crashed every time i went to render all... Tried going back to .44 and same issues.

**Comment by ellceywaup** [comment]
64 bit on windows10

**Comment by keithsw1111** [comment]
Package the sequence ... and package the logs and send both to us.

**Comment by ellceywaup** [comment]
Updated back to .46 and all seems fine. I'm not sure what to tell you guys? Sorry?
