### ISSUE TITLE
Controller Connection Enhancement in Layout Screen

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#1335]
Been seeing lots of people having problems with uploading to controllers because they have model set up with numerous strings (ports), and then have a later model also using that port.  If the relatively new controller connection list on the layout screen could have either the end port or the number of ports being used for each model, that would help find the problem faster when troubleshooting (especially when on zoom for other people's show).

**Comment by keithsw1111** [comment]
You know that info is already available in the node layout dialog?

**Comment by deplanche** [comment]
Yes, but that requires extra clicking to be able to see the node layout, or even going thru an selecting each model to see how many strings are on each model.  Noticing a few people over the weekend setting up the Boscoyo mini-trees that use 100 pixels maximum with 8 or 10 strings, and then getting lots of errors when they uploaded to the controllers.  The errors would be on the ports after those models, and they didn't think to look at the ports before those listed in the error report.  Was thinking if there was something a bit more in their face, they might be able to see the problem or the fix.  No big deal if not worth adding since it is easy enough to find in other ways.

**Comment by keithsw1111** [comment]
I did make a change.

**Comment by deplanche** [comment]
Thanks as always.
