### ISSUE TITLE
Models match layout when you open a new sequance

### ISSUE THREAD

**Issue by kd7hgt** [smeighan/xLights#1336]
When you open a new sequence Is there a way to make the models match how you have them setup in the layout tab every time without doing it manually?  Yes it does place your groups at the top of the list but it would be nice if they did all stay in order as you have them in the layout tab screen so you didn't have to go in and change the order every time you open a new sequence.  Is this passable to fix?

**Comment by keithsw1111** [comment]
It isnt broken ... as long as you have a view defined with the models in the desired order you can select that view when you create the sequence. Its the drop down just above the quick start button that most people never look at.
