### ISSUE TITLE
XML Parsing error when trying to download models

### ISSUE THREAD

**Issue by tobrien82** [smeighan/xLights#1337]
XML Parsing Error "Unclosed token" at line 1769
XML Parsing Error "Unclosed CDATA Section" at line 29905

Same error in 2018.46 and 2018.47

![image](https://user-images.githubusercontent.com/14241498/48901532-23b77f00-ee2c-11e8-87dd-37815ac2caab.png)

**Comment by tobrien82** [comment]
Is there any update on this? Or a fix?

I'm unable to download models on three different machines.. all running on ver 47.


Tim O'Brien
________________________________

**Comment by keithsw1111** [comment]
Yeah the fix will be in .48

**Comment by tobrien82** [comment]
Excellent! Thanks.

Tim O'Brien
________________________________
