### ISSUE TITLE
FPP upload fails with single quote in sequence name

### ISSUE THREAD

**Issue by MikeSoukup** [smeighan/xLights#1338]
I'm using 2018.46 and I see that there was a fix in 2018.45 (4a4bb0c2eaff01b42ba5b36c146abd95b1dc1f97)

> bug (dkulp) FPP Connect – failure to unzip fseq if name contains certain special characters

but I'm having trouble with the filename "Santa's Coming For Us.fseq".  The .gz gets uploaded, but it doesn't unzip.

**Comment by dkulp** [comment]
Requires 2.4.2 on the FPP side.  Make sure you update FPP as well.

**Comment by MikeSoukup** [comment]
I'm already on 2.4.2:

> FPP Version: | v2.4.2
FPP OS Build: | v2.2
OS Version: | Raspbian GNU/Linux 9 (stretch)
Kernel Version: | 4.14.71-v7+
Git Branch: | v2.4
Local Git Version: | e90daf9 ChangeLog
Remote Git Version: | e90daf9

**Comment by MikeSoukup** [comment]
I see there was a commit after 2.4.2 that may have fixed it. Do I need to move to master? https://github.com/FalconChristmas/fpp/commit/82fef93ecee626252fd1c27cceedbcff404bbba5
