### ISSUE TITLE
Model Preview floating box no edges

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#134]
OSX 4.0.10
It is very difficult to see/find the edges of the Model Preview box when it is floating over the sequence screen. The sides and bottom do not have any defined outline thus making - finding the edges to make it bigger difficult. See attached screengrab.
![screen shot 2015-04-01 at 1 12 43 pm](https://cloud.githubusercontent.com/assets/10136122/6949326/fb17cd40-d870-11e4-89ad-84ffbee9b5e4.png)

**Comment by dkulp** [comment]
Not sure there is anything we can do about this.   The floating window appearance is determined by wxWidgets, particularly the wxAuiManager.   It uses a wxMiniFrame for this and that's how the wxMiniFrame appears on OSX.   Hmm....

**Comment by LightsOnHudson** [comment]
The elements display properties are not editable? 

I've not done wxWidgets coding before. back in my 'vb days' and using visual b the different windows had display properties and I could put some shadowing around them, make them a little thicker? Is the Model Preview a full size element frame? Could the frame that is showing what is going on, be placed on top of a 'slightly larger' element that does / can have defined edges?
