### ISSUE TITLE
xSchedule playlist in playlist crash

### ISSUE THREAD

**Issue by nmiller0113** [smeighan/xLights#1341]
I don't know if this is a bug but I can reproduce it every time and it crashes xSchedule...crash report attached.  I'm running 2018.47 x64 on Windows.  I needed multiple items to trigger in a playlist, only once, in the beginning and the end.  I thought the way to do this was via a command step to call another playlist as my first and last step.  When running the playlist it crash xSchedule every time.  While I'm sure that crashing isn't the intent, it probably should have just failed, but that's why I'm reporting it.

What I ended up doing, which was probably the right way afterall though I'm open to suggestions for better ways, is created a step with multiple items inside the step itself...I had forgotten you could do that.  Anyway, all is working and nothing urgent here, just thought I'd note it for the future after the craziness of the holidays...don't think this is urgent by any means, and there are probably bigger problems that need addressing.  Thanks!
[xSchedule_dbgrpt-15964-20181123T131123.zip](https://github.com/smeighan/xLights/files/2611754/xSchedule_dbgrpt-15964-20181123T131123.zip)

**Comment by keithsw1111** [comment]
I may have fixed this for the next release. Not sure.

**Comment by nmiller0113** [comment]
Ok.  I was curious if the way I was doing it was the best way.  I'm also not sure of the difference between these different API options "Run event playlist step" and "Play specified playlist".  Thanks!

**Comment by keithsw1111** [comment]
Run specified playlist suspends any existing playlist that might be playing. Event playlists play over the top of any existing playing sequence.

**Comment by keithsw1111** [comment]
Can i close this?
