### ISSUE TITLE
Text Color Issue

### ISSUE THREAD

**Issue by NWF-Geek** [smeighan/xLights#1348]
In the text effect, when I rotate the text using the "Effect" setting, xLights stops using all of the colors selected in the color palette.  It seems to only use the first color that's checked.

**Comment by keithsw1111** [comment]
Yeah ... the reason it works that way is because it relies on a different text drawing API which wont let us use multiple colours. If you want that outcome use normal and rotozoom.

**Comment by AzGilrock** [comment]
I think it will work if you switch to the xLights fonts I added instead of using the OS fonts because I handle the drawing and can use the colors whereas the OS font drawing relies on 3rd party code.
