### ISSUE TITLE
Cannot move effects between layers (Bug or Enhancement?)

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#135]
OSX 4.0.10
Created an effect in Layer 0 (Images/Pictures - set of 1200 png files)
Added a second Layer, Added an effect (balls)

Saved, and rendered all.
Press Play, the output to Lights was blank. (Are image sequences not yet working??) 

I removed the Pictures effect, thus leaving the Balls effect in the layer just below it. 
Saved the sequence. re-rendered the sequence.
Rewound the sequence to the beginning
Pressed play, Still no output of the only effect now - balls to the matrix or Model Preview.

Attempted to click and drag the Balls effect from Layer 1 to Layer 0 and it would not move? Should / could we have this ability as the layers are rendered top down it would be nice to be able to rearrange them? If you drag one up, it pushes all effects in the lower layers down?
That's why I'm not sure if it is a bug, or could be an enhancement.

**Comment by LightsOnHudson** [comment]
After removing Layer 0, and rewinding the sequence to the beginning and pressing play, the Balls then appeared to go out the matrix and the Model Preview.

**Comment by stevegiron** [comment]
Highlight the effect and use the up/down arrow keys to move between layers

**Comment by stevegiron** [comment]
Moving effects between layers is a current feature. If you delete the layer 1 effect and the effect on layer two is set to layer1, then effect 2 will not display.
