### ISSUE TITLE
Preview SHOW ALL doesn't quite work as expected

### ISSUE THREAD

**Issue by NWF-Geek** [smeighan/xLights#1350]
Tools->Preview->Show All does not quite work as one would expect.  It appears that the intention is to provide a convenient way of displaying/hiding all views simultaneously, but as implemented it is non-intuitive because it can appear checked even when not all views are displayed.  In other words, unless all views are shown, this button should not be checked.  When using multiple views, it is easy to get into a configuration where one can't tell what selecting the button will actually do, because the checkbox doesn't reflect the true state of the interface.

Suggest removing the checkbox functionality from "Show All" and supplementing the menu with a "Hide All" function, so it has both.  This would be much more intuitive, and provide what I believe is the intended functionality.

**Comment by AzGilrock** [comment]
If you see a checkmark then it will hide all the previews when you click it.  If you don't see a checkmark then it will show all the previews when you click it.  No it doesn't change state if you start closing preview windows after doing a show all.  Its just a toggle.
