### ISSUE TITLE
xScheduler won't loop playlist

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#1352]
We have been working through the lip synch issue, and potential memory leak issue.  and for the last two nights I have stopped the playlist at the last event during a playlist play, closed the software and restarted it.  With the restart, the playlist will not loop.  It plays once and tops.  The playlist green bar goes from the last element to the first element but nothing happens.    Note that the step from library playlist to show playlist worked fine, and the show playlist looped as it should until I shut down and restarted the software..
Here is the log, even though I restarted the sdoftware, and RAM  dropped to lower levels, most of the log is 
2018-11-29 20:03:25,828 5096 log_base [WARN] Frame interval greater than 200% of what it should have been [50] 155
2018-11-29 20:03:25,985 5096 log_base [WARN] Frame interval greater than 200% of what it should have been [50] 157
[Dearing xSchedule_l4cpp 1129 812p.txt](https://github.com/smeighan/xLights/files/2631609/Dearing.xSchedule_l4cpp.1129.812p.txt)

**Comment by keithsw1111** [comment]
Until we fix your performance issues ... the log errors are going to hide any other problem. You can tell if it is looping by the green loop icon in toolbar. If it is grey then it isnt set to loop.

**Comment by JoelDearing** [comment]
I have looked for the FB message and have not seen it.  Was it through messenger, or a reply to a post?

**Comment by JoelDearing** [comment]
From our zoom meeting and follow up in the main zoom room, the playlist will get to the end, and not loop back even though loop is on.  I also noticed that the main playlist window is not showing the title correctly.   See the spelling of the word Happy.  
![image](https://user-images.githubusercontent.com/25068648/49334696-de245000-f5a9-11e8-8a1e-5255ddd67393.png)
But in the window where you build playlists it shows OK.  Here is that screen shot
![image](https://user-images.githubusercontent.com/25068648/49334720-b71a4e00-f5aa-11e8-8a7e-3eca021ddaa0.png)

From the log file here is what caught my eye.  Look how it displays the word Happy in the log file. 
2018-12-01 20:24:50,294 2208 log_base [ERROR] FSEQ file C:\Users\Joel\Documents\Show Directory\SEC 1-A_Winter_Hapy_Land_Let_It_B_Xmas.fseq could not be opened.
2018-12-01 20:24:50,294 2208 log_base [INFO] FSEQ file C:\Users\Joel\Documents\Show Directory\SEC 1-A_Winter_Hapy_Land_Let_It_B_Xmas.fseq closed.
2018-12-01 20:24:50,350 2208 log_base [DEBUG] Asking pinging thread COM3 LOR to stop

Here is the log file
[Dearing xSchedule_l4cpp.txt](https://github.com/smeighan/xLights/files/2636515/Dearing.xSchedule_l4cpp.txt)

**Comment by JoelDearing** [comment]
As a follow up to the last post, I stopped the playlist.  Clicked on the list, clicked play selected.  The list started, loop icon was off.  Clicked it to green.  "Happy" was correct.   Here is the screen shot
![image](https://user-images.githubusercontent.com/25068648/49334849-debee580-f5ad-11e8-96d9-f6b4235a54ea.png)

Schedule still labeled as Stopped

**Comment by keithsw1111** [comment]
What is going on with the filename: A_Winter_Hap�y_Land_Let_It_B_Xmas.fseq

**Comment by keithsw1111** [comment]
From the log you have several illegal file names: SEC 1-A_Winter_Hapy_Land_Let_It_B_Xmas.fseq

You cant see it easily but the second p in happy is not a legal character.

I wonder why that happens or where it came from. I wonder if rebuilding your playlists might help clean up these issues.

**Comment by JoelDearing** [comment]
It did clear up later.  I will watch it tonight and see if it comes back.  1st time I have seen it.

**Comment by JoelDearing** [comment]
So try this and see if you get the same results.  Create a library list, set a schedule to run from day 1 at 10:01p to 5:27p the next day.  Current version will leak memory, and this may be a factor, ...maybe..  2nd schedule (the show schedule) starts at 5:30p on day 2.  Memory should be just about gone.  During the first sequence exit out of the program by just closing the window, don't stop the sequence, just X out, then reload the program after the memory drops.  The show sequence starts again.  For me it does not loop, it gets to the end of the playlist, highlights the 1st item in the list as green, but nothing plays, it just sits there and the green loop icon is lit as green.  I exit out, reload, click the loop icon a time or two and last night it started to loop again.    Home this helps.

**Comment by keithsw1111** [comment]
When you say current version do you mean .51 or .52.

I need to see logs and the xschedule file ... that will tell me why you are seeing what you are seeing.

**Comment by JoelDearing** [comment]
A follow up
At the end of the show schedule, the sequence did not end.  The manual icon was lit  instead of the schedule grid icon.   
Here is the log
[Dearing log save 120518 1005p xSchedule_l4cpp.txt](https://github.com/smeighan/xLights/files/2651563/Dearing.log.save.120518.1005p.xSchedule_l4cpp.txt)

**Comment by keithsw1111** [comment]
I am pretty sure this was resolved. Reopen if not.
