### ISSUE TITLE
xScheduler Crash Reports After Changing The Library Playlists

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#1353]
As suggested, I removed the .wav files from the library folder.  I then rebuilt the library playlist and loaded in the trimmed Christmas audio folder, about 400 plus titles, I also rebuilt the schedules for weekday and weekends.  I exited the program, reloaded, realized I made an error in the schedule, edited the date info, exited the program and on reload it crashed.  Three times.   The files are attached
[xSchedule_dbgrpt-4268-20181130T125743.zip](https://github.com/smeighan/xLights/files/2634512/xSchedule_dbgrpt-4268-20181130T125743.zip)
[xSchedule_dbgrpt-4524-20181130T125810.zip](https://github.com/smeighan/xLights/files/2634513/xSchedule_dbgrpt-4524-20181130T125810.zip)
[xSchedule_dbgrpt-5108-20181130T125059.zip](https://github.com/smeighan/xLights/files/2634514/xSchedule_dbgrpt-5108-20181130T125059.zip)

**Comment by keithsw1111** [comment]
You are still running .48. This is a bug I have been working on for several releases. I need to know if it still crashes in .50 and see those logs as I have added extra logging. If you are still able to reliably reproduce it then i want to know because I want to get to the bottom of this one.

**Comment by keithsw1111** [comment]
I presume this is fixed ... if not please reopen

**Comment by JoelDearing** [comment]
Yes it has been a while since I looked at this one as well.  I will take a more detailed look closer to the season.
