### ISSUE TITLE
Bug: xLights Model start channel on layout tab is 9999 for set 10000 start channel. End channel correct

### ISSUE THREAD

**Issue by oldrob57** [smeighan/xLights#1357]
![xlightsbug](https://user-images.githubusercontent.com/33273610/49406943-4131f600-f714-11e8-8e25-2480e576af73.png)

This was OK in version 49. When updated to 2018.51, the model displayed in the layout tab is 1 less than the set start channel.

**Comment by keithsw1111** [comment]
Fixed

**Comment by oldrob57** [comment]
Thanks. So, version 2018.52 will have the fix?

**Comment by keithsw1111** [comment]
Yes
