### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by sfuzer** [smeighan/xLights#1358]
Approximately every 3-5 minutes, xlights will stop responding and the screen will turn gray/white.  After approximately 30 seconds to a minute, xlights will then function normally again.  I am running the most current version (2018.51) on a brand new laptop running Windows 10 (4GB RAM).  Additionally, when I do a render all, it can take over a minute to complete.  As a note, I have turned off "Render All on Save" so it is not that.  It seems almost like xlights is auto-saving every 3-5 min and it causes xlights to say "not responding" in the title bar and basically freeze.  This happens with multiple sequences and seems to be occurring once I import LMS files from purchased 16 string mega tree sequences from Holidaycoro.

**Comment by keithsw1111** [comment]
I do not consider this a bug. Best practice is to bring files like that in as a data layer to minimise impact on rendering. Problem is bringing in LMS files as an import generates thousands of effects at the node level which takes forever to render and causes file saving slowness issues ... exactly what you are experiencing. I strongly suggest in future not buying 16 string LMS tree sequences but instead get either superstar or xLights sequences. For now either turn off backup or reduce its frequency.

**Comment by nmiller0113** [comment]
@sfuzer, as @keithsw1111 mentioned, import them as a data layer.  That's what I do for about 15 different sequences I've purchased from Holiday Sequences.  Works great.  The initial save sucks but after it's saved, it's saved.  Then I add the saved one into the DL and all is well.
