### ISSUE TITLE
Models Preview not showing models

### ISSUE THREAD

**Issue by kalebmitchell** [smeighan/xLights#1359]
Under layout and I create any model (tree,matrix, etc)and when I click to drag and make the all that shows is a single vertical line.  You can change all the settings for the model, but no model actually shows in the Model Preview under layout or sequence.  The house preview under sequence shows the correct model image.

**Comment by keithsw1111** [comment]
Version? Screenshot?

**Comment by keithsw1111** [comment]
Try updating your video drivers to the latest from the manufacturer. That is the most common fix for that issue.

**Comment by kalebmitchell** [comment]
That took care of it.. apparently I was one version back, and I thought it was current.  Thank You for the help!
