### ISSUE TITLE
Enhancement - Models - Arches - single color

### ISSUE THREAD

**Issue by Xenialights** [smeighan/xLights#136]
When building a traditional single color arch, could the following work to depict the arch model in the preview?

Display as   Aches
Type of String  Single Color ______
Number of Arches
Number of Channels/Segments per arch
Number of lights per Channel/Segment

So 4 arches with 8 segments/channels would need 32 channels, lights per segment are irrelevant except that they fill out the preview effect much like in single string effects.

"#" When I tried to use"#" it changes font size  in this note.  So i wrote number instead.

**Comment by TomL8345** [comment]
I would like to see this implemented as well

**Comment by dkulp** [comment]
Done

**Comment by Xenialights** [comment]
Thanks, Dan
