### ISSUE TITLE
Scheduler crashes

### ISSUE THREAD

**Issue by tuppetsdad** [smeighan/xLights#1360]
Running version 2018 54 64 bit Crashed several times today. If I try to roll back to an earlier version then XLights does not trun- exception issue.

**Comment by tuppetsdad** [comment]
Windows 10,
Have 6 shows scheduled 
let me know what files you want

**Comment by keithsw1111** [comment]
I need to see the crash reports or debug logs or some information about when it crashed. Maybe your xschedule file would also be useful to see.

**Comment by tuppetsdad** [comment]
Hi Keith

files attached
where do I find the crash files?

Regards
Bruce

**Comment by keithsw1111** [comment]
I dont see any files ... if you responded to the email with them attached then they get stripped when your response is posted to github.
Crashes if they were produced are typically in your show folder. If they are not there at least send me your xSchedule log files.

**Comment by greerfamilylights** [comment]
same here, i keep getting crashes in scheduler
[xSchedule_dbgrpt-17888-20181209T180102.zip](https://github.com/smeighan/xLights/files/2661112/xSchedule_dbgrpt-17888-20181209T180102.zip)

**Comment by nmiller0113** [comment]
@keithsw1111 glad you found it.  My show is going to start in about an hour...and I won't be home to monitor it.  Should I be concerned about it crashing while I'm out?

**Comment by nmiller0113** [comment]
@keithsw1111, I actually haven't experienced it, so didn't know if I needed to.

**Comment by greerfamilylights** [comment]
Thanks so much Keith and thank you for the timely response

**Comment by tuppetsdad** [comment]
This is latest
[backtrace.txt](https://github.com/smeighan/xLights/files/2661387/backtrace.txt)
[xSchedule_l4cpp.log](https://github.com/smeighan/xLights/files/2661388/xSchedule_l4cpp.log)

[xSchedule_l4cpp.log](https://github.com/smeighan/xLights/files/2661389/xSchedule_l4cpp.log)


 crash file

**Comment by tuppetsdad** [comment]
And a previous one

[backtrace.txt](https://github.com/smeighan/xLights/files/2661398/backtrace.txt)
[xSchedule_l4cpp.log](https://github.com/smeighan/xLights/files/2661399/xSchedule_l4cpp.log)
