### ISSUE TITLE
Ubuntu 18.04: Xlights .53: Issues 

### ISSUE THREAD

**Issue by extremeskillz** [smeighan/xLights#1361]
Hey Guys,
1st issue. Ubuntu 18.04 latest install of Xlights 2018.53 won't install and update the last version installed. I run the Appimage and before once I launch it it would ask to add to launch bar and want not and with this version it not do that. It is working but I'm not able to add to launch bar.

2nd issue, I'm currently working on a new sequence for next year and I made a 15 minute track to sequence. About 1 minute in as I drop effects on the timing it will stop displaying effect previews. I would then rerender and the rendering engine will start to render it but stop (or at least appear to stop) rendering and I can't move past that. I hit f5 numerous times and it will update the progress but would seize to render further and I would have to stop and restart xlights. It did not generate a error log so I wasn't able to further troubleshoot this. I'm just reporting my experience at the moment.

**Comment by cjd** [comment]
Can re-download - I just rebuilt the image and re-uploaded with a hopeful fix for the start issue
For the second issue - can you re-produce and then grab/attach the /tmp/xLights_l4cpp.log for us

**Comment by extremeskillz** [comment]
Chris,
This all set with the latest versions. Seems to be working better now.
