### ISSUE TITLE
Xschedule crashing

### ISSUE THREAD

**Issue by jaycanter** [smeighan/xLights#1362]
Window 10 with xchedule running runs all night just animation sequencer then on the hour have nine musical sequences run 2nd or 3rd song the lights stop moving but still on like it's paused the music keeps going. check xschedule and it's crashed and have to restart it.
[xSchedule_dbgrpt-1572-20181209T181656.zip](https://github.com/smeighan/xLights/files/2661231/xSchedule_dbgrpt-1572-20181209T181656.zip)
[xSchedule_dbgrpt-14556-20181209T190718.zip](https://github.com/smeighan/xLights/files/2661232/xSchedule_dbgrpt-14556-20181209T190718.zip)
[xSchedule_dbgrpt-14740-20181209T183802.zip](https://github.com/smeighan/xLights/files/2661233/xSchedule_dbgrpt-14740-20181209T183802.zip)

**Comment by greerfamilylights** [comment]
i reported as well. Keith responded in another thread and is going to try and release an update tonight to resolve.

**Comment by jaycanter** [comment]
Thanks for the heads up. I am just learning how this works and wasn't sure it wasn't something i did wrong. Lol
