### ISSUE TITLE
Non Rush - RGB test with dmx incorrect colors

### ISSUE THREAD

**Issue by robbaldwin12** [smeighan/xLights#1363]
Setup tab
16 channels on a dmx/lor dongle set to channels 1-16 these are single color
followed by any number of universes of rgb on one or more controllers starting at channel 17 absolute

when using tools>test
Turn all outputs on and set to RGB tab with background only bullet checked and any one of the sliders on background up.

when the usb is enabled the colors become mixed up on the rgb things later on. 
when the usb is disabled the colors become correct. 

I do notice that if the usb is set to a full universe of 510 this does not happen.

**Comment by AzGilrock** [comment]
I don't think this is going to change.  In test mode for things like this the channels just all get lumped together in a big array and the colors are allocated in sets of 3 with no regard to whether it's crossing a model boundary so if you have something like that with 16 channels which is not divisible by 3 it will cause a color shift for the remaining channels.  If you select just the channels for what you want to test it should work fine.
