### ISSUE TITLE
Layout does not show pixel lights

### ISSUE THREAD

**Issue by tuppetsdad** [smeighan/xLights#1365]
Have copied complete show directory and files to another PC but when I open X lights the layout display does not show the pixel models (it shows the RGB models ) and these do display when testing a show with House Preview.
If I seletct the model in the Layout  by drilling down into a group It then shows the position of the model and the data looks OK but still does not show th model

Any suggestions?

**Comment by keithsw1111** [comment]
Did this help? Can I close this?

**Comment by AzGilrock** [comment]
Closing due to lack of response.
