### ISSUE TITLE
Possible xLights error on .55 3D Beta

### ISSUE THREAD

**Issue by DeerValleyLights** [smeighan/xLights#1366]
Hello,

When in xlights layout tab, I have 4 channels (Roof lights) in AC settings where I have channel numbers 4-7 in .33 3D Beta. Once I upgraded to .55 3D Beta these channels add 50 channels on top of them making it 54-57 overlapping with other props in my show. I think it has to do with something # Lights section at the top of the set-up prop area. When trying to edit "# Lights" xLights crashes every time. I have posted a picture below. 

![xlightserror](https://user-images.githubusercontent.com/45842755/49923164-3f84d280-fe78-11e8-9ca8-0705b3c3a07f.PNG)

Thanks so much,
Steven

**Comment by AzGilrock** [comment]
Yeah that sounds like a bug that might be in the main branch when it was merged into the 3D branch.  You need to post a Package Log Files from the .33 3D version so we can inspect what happens when it upgrades.

**Comment by DeerValleyLights** [comment]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/2681833/xLightsProblem.zip)

Here is the file. I mis-typed my version, I upgraded from .31 not .33. The difference is very little in the versions, but thought I would mention that now.

**Comment by DeerValleyLights** [comment]
Hey Keith, been working with 2019.2 for about 3 or 4 hours now. Everything seems to be working fine in regards to the channel numbers. Thanks so much!
