### ISSUE TITLE
Mac mouse loses focus - forced to restart

### ISSUE THREAD

**Issue by Terrevue** [smeighan/xLights#1368]
Using the latest version, after a random amount of time editing, the mouse loses focus and I can't click anything in the application.  The only items I can click are the app menus.  If I attempt to quit xlights without saving, I can't click the "Save Changes" button in the dialog either.  All of the windows' toolbars are greyed out as well.  I have tried hitting ESC, as well as any key+click combo I can think of.  Nothing restores the ability to click other than a restart.

**Comment by keithsw1111** [comment]
It sounds like the app had hung ... is this still a problem.
