### ISSUE TITLE
Sequence Settings - Metadata information

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#137]
OSX 4.0.10
Is the "# of Models" label to show the number of models currently used in a Sequence?

In this case I have 1 + 1 (Whole house model) . Should this show 2?

See attachment.
![screen shot 2015-04-01 at 2 57 52 pm](https://cloud.githubusercontent.com/assets/10136122/6952524/c4dbbbd8-d87f-11e4-91c3-bab8ffafe633.png)

**Comment by AzGilrock** [comment]
It's the number of models you had in the XML file when it was opened.  It doesn't really serve a purpose so I'd rather delete it altogether if only updating it during open is a problem.

**Comment by LightsOnHudson** [comment]
Ahh.. When it was opened. Because it was confusing, that there is an XML file  - When I saved the xml file before opening this window, so I thought it would reflect the active models in the sequence. 

Just filing the bug here. that it didn't make sense that I had an active model and it was showing just Zero.

**Comment by AzGilrock** [comment]
Initially that dialog was only for conversions so it was showing how many models were converted.
