### ISSUE TITLE
XML parsing error: 'no element found' at line 1689

### ISSUE THREAD

**Issue by bronc70** [smeighan/xLights#1371]
on Xlights 2018.55 I received this error when selecting the piano effect. I tried closing/rebooting PC and same error when I try to open the XML file. any ideas?

**Comment by bronc70** [comment]
here is the text version of the sequence
[fresh test extra.txt](https://github.com/smeighan/xLights/files/2689020/fresh.test.extra.txt)

**Comment by keithsw1111** [comment]
Thats because the file stops at 1689. The file has been truncated/corrupted at some point by something.

**Comment by bronc70** [comment]
Is there a fix for this?

**Comment by keithsw1111** [comment]
Yeah ... find a backup copy. There is nothing i can do to repair the file.

**Comment by bronc70** [comment]
There is no backup. This sequence was not stored in the show directory for Xlights to backup. Could there be another backup somewhere?

**Comment by AzGilrock** [comment]
No if you choose to store files in a non-standard location you are taking the backup responsibilities into your own hands.  Do you not run backups for your computer?  I have a full backup once a weekend and delta backups executing nightly.  Once you lose some critical data you realize you need it.
