### ISSUE TITLE
Enh: Save the Audio Setting

### ISSUE THREAD

**Issue by darylerwin** [smeighan/xLights#1373]
Nice to have .. if I have set the audio to quiet - keep it that way between restarts. I believe that is not happening now (or perhaps its me switching show directories and such?)

**Comment by darylerwin** [comment]
Not sure I understand you .. this is during sequence development (or hoping on zoom :-) ) when you play the volume you want it to be set to "quiet" and not boom out thru the headset/zoom mtg.

**Comment by nmiller0113** [comment]
You're talking about within xLights itself, not xSchedule.  I see.  Not sure how doable this is as there isn't a volume setting within xLights, it's controlled in the OS sound settings.  I'll let the devs reply.

**Comment by darylerwin** [comment]
I just mean the audio setting in xlights. The one u set to quiet.

**Comment by computergeek1507** [comment]
Added by Lee in May 2019
