### ISSUE TITLE
FPP upload check boxes staying checked

### ISSUE THREAD

**Issue by kd7hgt** [smeighan/xLights#1374]
I like the new fpp upload options.  Here is the issue.  When you upload you check the options and sequence you want to upload that is good.  The problem is when it is finished the check marks don't uncheck so if you are not looking when you upload again and upload something new both get uploaded and assed to the playlist again.  is there a way this can get fixed please.

**Comment by computergeek1507** [comment]
This will be fixed in the next release. https://github.com/smeighan/xLights/commit/0f76112f53a5b0dbb802c6fb7bec0c3f7bbc1127
