### ISSUE TITLE
Just downloaded .57 and it crashed twice. just wanted to upload the debug reports

### ISSUE THREAD

**Issue by buddyd2006** [smeighan/xLights#1377]
[xLights_dbgrpt-2652-20181227T101419.zip](https://github.com/smeighan/xLights/files/2712872/xLights_dbgrpt-2652-20181227T101419.zip)
[xLights_dbgrpt-7232-20181227T101941.zip](https://github.com/smeighan/xLights/files/2712873/xLights_dbgrpt-7232-20181227T101941.zip)

**Comment by AzGilrock** [comment]
If you hit the OK button when the crash dialog comes up we already have the debug files so unless you are adding additional info like what you were doing and how to reproduce the crash it doesn't help to post it again here.

**Comment by buddyd2006** [comment]
Ok I was unaware. Both times it happened when I hit the save button

**Comment by keithsw1111** [comment]
Can you package the sequence and send it to me.

**Comment by keithsw1111** [comment]
Closing due lack of response.
