### ISSUE TITLE
Rendered?

### ISSUE THREAD

**Issue by Drew262** [smeighan/xLights#1378]
I create sequences and save them. But when I open them back up in xlights they are all out of wack and not playing what it should be. I click render and it fixes it but if I save it, it gets all messed up again. Any ideas?

**Comment by AzGilrock** [comment]
Not sure when someone will be able to look but pretty sure we will need you to package an example sequence that does this and provide it so we can get your exact show folder setup.

**Comment by Drew262** [comment]
Maybe that is what I did. I created a new setup folder for another house. When I went back I must have messed something up. How in the world do I fix it!?

**Comment by dkulp** [comment]
I think there is an issue in .56.  Stick with .56 for now.   I’ll look at it next week.  

Daniel Kulp

**Comment by Drew262** [comment]
Went back to .56 and it works. Thank you.

**Comment by darylerwin** [comment]
Just another me too .. was helping a lady on zoom where things were just funky on the actual lights. She made a couple of minor changes + the upgrade and things went awry. Had her go back to .56, re-render/save/upload and she was back in business.

**Comment by keithsw1111** [comment]
Building .58 now which should fix this.
