### ISSUE TITLE
Allow eseq files in FPP Connect

### ISSUE THREAD

**Issue by jnealand** [smeighan/xLights#1382]
With an eseq file for each sequence to announce song name and artist it would be nice to select all the eseqs to upload.   I also have a lot of script files that are needed in order to invoke the eseqs so both file types and maybe others should be allowed.   A simple filter with allowed extensions (fseq, eseq, mp3, etc) could be added to the file selection window.

**Comment by keithsw1111** [comment]
I really dont think we should be doing this. FPP Connect is not designed to be a replacement for FPP's already great upload capabilities. Uploading sequences makes sense because that is what we are all about. Uploading a miscelaneous set of files selectively to specific Pis is better dealt with through the Pis UI

**Comment by dkulp** [comment]
I'm working on completely re-doing the FPP connect dialog so I'll throw this in as a possible update.  It's a bit tricky though as the eseq is something that is more FPP  instance specific (which FPP instance has the model) so I'm not sure if I will get to it.   We'll see.    I'm actually thinking more that when an eseq is created, we can add a field right there to specify which FPP instance/host to upload it to, maybe not even save it to the local disk.

**Comment by jnealand** [comment]
FPPs great upload capabliites do not have the rsync capability which is what caused me to put this in the queue.  When one has an eseq for a matrix they can become very large and take a bit to upload.  In my case they only have to be uploaded to my BBB but the script to cause the event to start must go to the master.  The scripts are tiny so the big issue for me is the number of eseqs.  The data compression that FPP connect offers is the reason I requested this enhancement.

**Comment by dkulp** [comment]
FPP is likely to change the eseq files to use the new "v2" FSEQ format which support compression natively.  Would require FPP 2.6 (or 2.7, not sure yet) though.

**Comment by dartunder** [comment]
Please close this.
