### ISSUE TITLE
2019.1 Mac - Update Available Dialog

### ISSUE THREAD

**Issue by jarogers** [smeighan/xLights#1383]
Just installed 2019.1 on MacOS Mojave 10.14.3.

Upon starting up xLights.app, the "xLights Update Available" dialog is displayed with the following text:

You are currently running xLights 2019.1
Whereas the current release is - 1970/01/01

With available options of:
Download new release
Ignore this version
Skip this time

N.B. "Download new release" option takes you to "https://dankulp.com/xlights/" via default web browser.

**Comment by jarogers** [comment]
@dkulp So this is closed, but no comments left.  Does that mean you've fixed this?

**Comment by dkulp** [comment]
Yes... it was an issue on the server side that was looking for the tar.gz instead of the dmg.   Now fixed so the dialog should be working correctly.
