### ISSUE TITLE
2019.1 

### ISSUE THREAD

**Issue by bobswinterwonderland** [smeighan/xLights#1385]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/2719122/xLightsProblem.zip)
having issues since i installed xlights 2019.1 upgraded from 2018.44

**Comment by keithsw1111** [comment]
What issues? Posting this is not a quality bug report.

**Comment by keithsw1111** [comment]
Close xLights, delete xLights_keybindings.xml file in your show folder.

**Comment by bobswinterwonderland** [comment]
delete xlights & keybindings.xml file
