### ISSUE TITLE
[2019.1] Undo in 3D Model Layout

### ISSUE THREAD

**Issue by TimRoenicke** [smeighan/xLights#1386]
The issue can be seen here: https://www.youtube.com/watch?v=CfL8iCblF4E

When aligning a model to the ground or bulk aligning, distributing or resizing; if you attempt to "CTRL+Z"  it blows out all of the objects under the **3D Objects** table.

**Comment by AzGilrock** [comment]
Yeah I've been telling everyone don't use Undo with the Objects.  This is a bad title for the issue it should be something related to Undo.  The function you did before the undo doesn't have much to do with the problem.

**Comment by TimRoenicke** [comment]
Gotcha, wasn't sure if you were aware was all. Just tryin to help.
