### ISSUE TITLE
Cancel Save Changes still closes xLights

### ISSUE THREAD

**Issue by BrianRees** [smeighan/xLights#1388]
Minor Issue/Suggestion.

Create a sequence.  Press the "X" Close button to exit xLights.
Message box:  Sequence has unsaved changes.... Press Save Changes.
Press Cancel.    ( Want to go back to edit )
xLights closes.     ( After pressing Cancel. I would assume the message box would still be displayed. )

**Comment by computergeek1507** [comment]
tested in version 2019.2, Pressing Cancel returns to main window and doesn't close the software on my windows 10 machine. Do you have more information or a video of this happening?

**Comment by BrianRees** [comment]
Zip File contains a screen capture, as requested.

[Issue_1388.zip](https://github.com/smeighan/xLights/files/2722579/Issue_1388.zip)

**Comment by computergeek1507** [comment]
I wasn't following the steps he used, after watching his video, it does close if you click cancel on the save file dialog. As it is currently, the user would loose there new unsaved sequence if they did this. If we change the savesequence to return a status we could fix this. I do agree it is a user error but I do have a little sympathy for the noobs.
