### ISSUE TITLE
Matrix on 3D House Preview

### ISSUE THREAD

**Issue by AleXthePunK** [smeighan/xLights#1392]
When you render a sequence, and put the house preview to 3D, they show up as lines, not actual images.

**Comment by AzGilrock** [comment]
The pixels are so packed together on a matrix it can look weird if you don't have the view looking directly at it.  You can change your viewing angle and/or zoom in and you will see it change.  I've looked at this weeks ago and don't believe there is anything we can change.

**Comment by AleXthePunK** [comment]
Thank you for taking time to look at this.
