### ISSUE TITLE
Crash When Resizing Image on Layout

### ISSUE THREAD

**Issue by lcshankle** [smeighan/xLights#1394]
In Release 2019.2, using Windows 7 - 64 bit, I have an image on the layout panel. Resizing the image by increasing the height using the arrow buttons causes XLights to crash. The crash occurred after a few increases. Image initially had black border along the top. I may be exceeding that size to cause the crash.

**Comment by keithsw1111** [comment]
Can you make a video. I tried it and didnt see a crash

**Comment by lcshankle** [comment]
I hate it when someone tells me they have a crash and then try to show me and they can't reproduce it (I am a software engineer). Guess I am that person now. I did get it to crash a couple of times before as I wanted to make sure it was an issue. I can't get it to happen now, so I am embarrassed. 

One issue I do see with this version (haven't checked the latest version which looks like it came out today) is that the brightness value doesn't work. I believe the display is stuck at 100, even when the value is changed. Related to this, when using the arrow for this value, it allows the value to be changed beyond the acceptable range, though it flags this as an error, the arrow buttons shouldn't allow the value to be changed outside of the range. Does that restore some of my integrity some?

Sorry for the report that I couldn't reproduce again. And a BIG THANK YOU  for all the work that you do on some excellent software.

Louis

--------------------------------------------
On Sat, 1/5/19, Keith Westley <notifications@github.com> wrote:

 Subject: Re: [smeighan/xLights] Crash When Resizing Image on Layout (#1394)
 To: "smeighan/xLights" <xLights@noreply.github.com>
 Cc: "lcshankle" <lcshankle@sbcglobal.net>, "Author" <author@noreply.github.com>
 Date: Saturday, January 5, 2019, 6:42 PM
 
 Can you make a video. I tried it
 and didnt see a crash
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by AzGilrock** [comment]
Those arrows are working the default way wxWidgets coded them to.  So since we didn't write that code your complaining about I'll just guess that its not running the validation during every arrow click.  I guess its a trade off you could validate every single number and slow the scrolling speed down 10 times.

**Comment by keithsw1111** [comment]
Which brightness value doesnt work?

**Comment by lcshankle** [comment]
The one for the background image (and I can reproduce it 😉). See attached with two very different values but the image is the same.

**Comment by AzGilrock** [comment]
The field turns red to indicate an error when it goes out of bounds.  That's good enough for me.  I just tested and Brightness for the background image is working fine.  You didn't attach any photos either.

**Comment by keithsw1111** [comment]
Yeah I dont see a problem here. The red stuff is default wxWidgets behaviour I am not going to change. The rest of this I cant reproduce and I see no images attached. Reopen if you have something that really shows the problem.
