### ISSUE TITLE
Mac 2019.2 OBJ imort issue

### ISSUE THREAD

**Issue by TylerNodine93** [smeighan/xLights#1395]
When importing a obj (from sketchup export) you can only import it when viewing the "default" preview window. If you try to add any OBJ objects to a "new" preview they do not work. Nothing populates under the 3D objects menu. and it will not show a sketchup OBJ file. It does not pop up and report any errors, it just simply doesn't work as i would expect it to.

Used Xlights MAC 2019.2 and SketchUp Make 2017 Exported as OBJ file with all Export option check boxes selected.

**Comment by AzGilrock** [comment]
Yeah well technically you should only need one world of objects with 3D.  I wish I had never added that additional preview option it was mainly to allow you to see other angles of your house which you can now do in 3D.  If someone wants to dive into this fine but I'd just assume the whole multi-preview feature get deleted now.

**Comment by TylerNodine93** [comment]
My thought process was to have a Christmas “preview” and a Halloween “preview” which I believe can still be done but after thinking about that a little deeper I am going to do 2 separate show folders instead anyways. So doing everything in a default view since it’s now 3D is understandable.
