### ISSUE TITLE
XSchedule64 not outputing to lights

### ISSUE THREAD

**Issue by sluther1130** [smeighan/xLights#1396]
XSchedule64 does not output to lights after upgrading to 2019.2.  I tried to re-render FSEQ files to no avail.  I attempted delete the playlist and schedule and re-create.  Again, to no avail.

Xschedule64 looks like everything should work and it plays.  Just no output to lights.

I had to revert back to 2018.59.

**Comment by keithsw1111** [comment]
SHould be fixed in .3
