### ISSUE TITLE
2019.2 Background image disappears in 3D mode

### ISSUE THREAD

**Issue by lwillis** [smeighan/xLights#1398]
When I select 3D mode in layout, the background image of my house disappears. All the models are displayed, but the background image is gone. I have included before and after screen shots.

<img width="1051" alt="2d mode" src="https://user-images.githubusercontent.com/41842355/50726941-dc3a3900-10e1-11e9-8cca-601a998c858e.png">

<img width="1051" alt="3d mode" src="https://user-images.githubusercontent.com/41842355/50726944-eeb47280-10e1-11e9-8b80-1cec21c499e5.png">

**Comment by keithsw1111** [comment]
Yes you need to add it in if you want it in 3d
