### ISSUE TITLE
When I move from sequencer to preview popups remain

### ISSUE THREAD

**Issue by DanJacobsen** [smeighan/xLights#140]
My "default" perspective in the sequencer panel is to have two popup windows open over the sequencer area--a whole house model and colors.   When I move from the sequencer to the preview screen, these popups remain in place.   When I "x" them out to close them then they don't show up when I go back to the sequencer.   Maybe this is how these are going to work in XL4?

**Comment by DanJacobsen** [comment]
I also noticed it doesn't matter what tab I go to, these popup boxes remain in place no matter where I am--sequencer, preview, setup, etc etc

**Comment by stevegiron** [comment]
Duplicate issue. See # 87 Suggest this one be closed.

**Comment by stevegiron** [comment]
Closing as it's a dupe issue.
