### ISSUE TITLE
All 3D objects become active when adding a model

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#1400]
It appears that when adding a model in 3D, all of the 3D objects will become active even if previously unchecked so they wouldn't be shown when starting to draw the model.  This appears to happen when adding or editing any model.   Happening on version 2019.3.  

Before adding a model
![image](https://user-images.githubusercontent.com/17793531/50731926-77143100-113d-11e9-8024-20d01e1c40ee.png)

After drawing an arch.
![image](https://user-images.githubusercontent.com/17793531/50731933-8a270100-113d-11e9-92e7-0a5b35ff1714.png)

![image](https://user-images.githubusercontent.com/17793531/50731940-98751d00-113d-11e9-9ae9-e66e6a94688e.png)

**Comment by AzGilrock** [comment]
Yep I confirmed this when you wrote it.  Must not be saving or loading the active state properly.

**Comment by keithsw1111** [comment]
I cannot reproduce this ... maybe a video would help?
