### ISSUE TITLE
2019.2 Scheduler not passing data to controllers

### ISSUE THREAD

**Issue by RyanKasperCook** [smeighan/xLights#1401]
I upgraded from 2019.1 to 2019.2 and have a simple flood light sequence that runs each night, working correctly in 2019.1.  After upgrading to 2019.2, scheduler will not output to the controllers.  I can output to the lights correctly from xLights directly, scheduler is showing proper ip address, it sees all the controllers in green, output to lights is on, no errors in check schedule... simply no data getting to controllers.  Switched back to 2019.1 and all working again as normal, so something between .1 and .2 that is doing it.  Thanks!

**Comment by AzGilrock** [comment]
Try 2019.3.  I know something got broken when the reading/writing to FSEQ files was changed and Keith fixed it 2 days ago.

**Comment by RyanKasperCook** [comment]
Thanks Gil, I did attempt that before posting this, however the .3 link is still downloading .2 package

**Comment by AzGilrock** [comment]
Yeah you're probably a MAC or Linux user I just downloaded the PC version just now.

**Comment by RyanKasperCook** [comment]
Haven't tried on the Mac yet, I was attempting on PC... I will try again, maybe the link is fixed now.  thanks!

**Comment by keithsw1111** [comment]
This was fixed in .3
