### ISSUE TITLE
xLights issue/keybindings

### ISSUE THREAD

**Issue by oakridgelights** [smeighan/xLights#1402]
I received an error message when closing xLights 2019.3 stating that my keybindings appears to be corrupt. Message requested I use the Package Logs option and send the file.

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/2731344/xLightsProblem.zip)

It was suggested already that I delete the file then reopen xLights, and that does seem to have worked in resolving the issue.

**Comment by keithsw1111** [comment]
Thankyou ... unfortunately your keybindings were previously corrupted so this didnt help ... but it if happens again please let us know.
