### ISSUE TITLE
Custom model with more than one port connection problem - fails upload to controller

### ISSUE THREAD

**Issue by Duramadmax** [smeighan/xLights#1403]
I made 2 custom models (each matrix made to "fit" my upper windows) that do not follow the typical preset matrix model. In other words, my matrix is 16w x 51h with 7 port connections (6@204 nodes and 1 at 102 nodes). If it was another 102 nodes and and had even groupings, I would have used he standard matrix preset to design my model. So when I go under the controller connections of my custom model to set port say at 1, the upload to controller feature thinks I am uploading 1326 nodes one port and says it exceeds the max port amount of 1024 and then fails to upload. So for now I have to set the complete controller string ports up manually, which is not a deal breaker. Is there  way to designate how many ports used and the amount of nodes used on each port to let xlights tell the controller the proper port info for a custom model? Using 2018.53

**Comment by deplanche** [comment]
Update to 2019.03 - uploading with multiple ports for a custom model was just recently added and that will solve your problem here.  Keith's video covers how to use it.... http://videos.xlights.org/xlights-201854-20193-release-update_6af2841cc.html

**Comment by Duramadmax** [comment]
Ok I will give it a whirl and see how that works. Thanks

**Comment by Duramadmax** [comment]
Ok it does work for custom models but has channel/universe error. The issue has been put into another listing. Thanks
