### ISSUE TITLE
Node Layout showing wrong controller listed for that model

### ISSUE THREAD

**Issue by Duramadmax** [smeighan/xLights#1404]
When going to node layout for a particular model, I noticed that the controller listed was not for that model in question. Have noticed some models are correct but some are not. Have not discovered the pattern or offset causing it.

**Comment by deplanche** [comment]
You are going to need to post more information like screenshots or the file to get help with that.  Right now there is not enough information to be able to track down that problem.
 
A possible cause may be that you have a model that is using more ports (strings) than you anticipated on a low numbered port, that is spilling to everything after it.  But that is just a guess without seeing the details of your set up.

**Comment by Duramadmax** [comment]
I will provide a screen short soon. I will look and see what you suggested is the issue. Thanks

**Comment by AzGilrock** [comment]
Yeah if you don't provide the xlights_rgbeffects.xml with the model in question we aren't going to just randomly start creating models and see if the controller looks wrong.  I personally don't even use that feature.

**Comment by keithsw1111** [comment]
Closing as no files have been provided. When you have the files and you can reproduce the problem on the latest version please reopen.
