### ISSUE TITLE
Entire model showing selected on layout when only submodel group is selected

### ISSUE THREAD

**Issue by reelpilot** [smeighan/xLights#1405]
On 2019.3 in the layout tab anytime I select a group that contains submodels, the entire model turns yellow and is not isolated to the specific submodel as it should. If more than one model is in the group, then the first model in the group will be entirely selected and the remaining models will show the appropriate submodels. This appears to only be a layout issue, when sequencing it works as expected on the submodels.

**Comment by AzGilrock** [comment]
Sorry ssumodels are not a selectable entity in the layout

**Comment by reelpilot** [comment]
If you read what I wrote you would see that I mentioned group with submodels.

**Comment by AzGilrock** [comment]
Could you show a picture of what you mean?  All I'm saying is I don't believe we have a way to highlight only a submodel yellow.  You're description makes it sound like you see submodels highlighting yellow.  The "selected" property exists in the model class so there is no way to mark a submodel as selected in the code.  You can select a list item that may be a submodel but that marks the whole model selected.   Submodels are somewhat of a hack I doubt there will be improvements to this.

**Comment by keithsw1111** [comment]
I am not so sure ... I worked on an issue a short time back with similar symptoms but in 2D.

**Comment by AzGilrock** [comment]
I did test what was described.  I'm sure there is some selection wackiness but I did not see the submodel for remaining models highlight yellow.  It does select the model.
![image](https://user-images.githubusercontent.com/2024669/50875724-e16be200-1386-11e9-8840-4e03118e3285.png)

**Comment by AzGilrock** [comment]
The more concerning issue is try to move that selection.

**Comment by reelpilot** [comment]
Ok so here's a video showing the issue and it appears to be limited to custom models. However I did find a new issue with the perspective of my mega tree submodels. I have not yet done anything with 3D at this time, so this is all in 2D.

https://youtu.be/nB2kWxI7EY4

**Comment by derwin12** [comment]
Came here to post the same enh. (for me 2d) Click on submodel of snowflake for example (eg. spokes). The entire model highlights in the layout window. Would make for a quick way to verify submodels are correct.

**Comment by keithsw1111** [comment]
I think this is now done.
