### ISSUE TITLE
2019.3 Mac - obj import axis translation

### ISSUE THREAD

**Issue by jarogers** [smeighan/xLights#1407]
Seems that obj's imported do not respect the axis which they were originally built in.  From some limited testing so far it seems that the Z and Y axes are interchanged.

**Comment by AzGilrock** [comment]
I'm sure with some clever thinking you can make it work.  I know for SketchUp I invert the Y axis on export.  You didn't say which software you're using.  I'd say just rotate the object in your program and re-export it.  Luckily it should only be a one time operation.  I just used an OBJ file loader function I found and I don't want to add a ton of options to handle every possible scenario.

**Comment by jarogers** [comment]
Actually it doesn't even take some clever thinking to come up with a workaround.  However that wasn't the point of me reporting the issue.  Anyways, so far I've tested with Esprit, ModelMill, AlphaCam, SketchUp, and MakeHuman.  The issue still stands with each of them.

I've also just noticed now that I've started using the 3D modeling in xLights, that the standard OOB models are also placed laying down on the Y axis as well as those imported.

**Comment by AzGilrock** [comment]
Dude I want to argue with you.  There are a bunch of us that have it working just fine so I can't guess what you are doing different.

**Comment by AzGilrock** [comment]
Also the Y axis is vertical in xLights.  I know some people like to use Z for vertical but ours is designed to match up with the 2D axes.

**Comment by AzGilrock** [comment]
I got home and verified everything.  xLights is reading the OBJ file correctly because the vertex format is in the order X, Y, Z and we read in that order.  SketchUp allows the Y / Z swap on export and that's shown in the export options I've given out.
![image](https://user-images.githubusercontent.com/2024669/50942956-b7c6bf80-1447-11e9-934a-2595094f7883.png)
