### ISSUE TITLE
2019.3 Mac Crash Report 

### ISSUE THREAD

**Issue by dszoka** [smeighan/xLights#1408]
Just starting to setup my layout in 3d.. Zoom to far out.. Crashed 

[xLights_dbgrpt-52255-20190110T151709.zip](https://github.com/smeighan/xLights/files/2743579/xLights_dbgrpt-52255-20190110T151709.zip)

**Comment by dszoka** [comment]
[xLights_dbgrpt-52655-20190110T153756.zip](https://github.com/smeighan/xLights/files/2743615/xLights_dbgrpt-52655-20190110T153756.zip)
and again.. I'll stop now

**Comment by keithsw1111** [comment]
I can see the crash but not why and I zoomed a long long way out .. can you make a video of the steps to make it crash

**Comment by cp16net** [comment]
i just attempted this and could not crash it zooming way in or out on latest mac code.

**Comment by dszoka** [comment]
I spent 2 hours recording my screen as I played in xlights... can’t make it crash again 2019.3

I have upgrade to .4 will see what happens
