### ISSUE TITLE
Clear all Data before Render ALL

### ISSUE THREAD

**Issue by smeighan** [smeighan/xLights#141]
Add an Option to Settings "Clear All Data Before Render All" 
If the is checked then do a mem clear of all data when render all is clicked.

Process would be
1) Clear all data in sequence buffer if the checkbox is set
2) Load in iseq layer files (If users had LOR/Vixen data to be imported)
3) Re-render all Nutcracker effects.

This would fix artifacts when a user changes teh starting channel of a model. There were a number of issues last year in 3.6.x where this happened.

**Comment by dkulp** [comment]
Thinking about this, I wonder if in the "Layers" tab of the settings:

![screen shot 2015-04-09 at 2 36 29 pm](https://cloud.githubusercontent.com/assets/91569/7074157/519ca6d0-dec6-11e4-8577-3d8a8f421b66.png)

the "Data" line could be double clicked to toggle between "<rendered>" and "<cleared and rendered>" or similar.

**Comment by AzGilrock** [comment]
Checkin today closes this...forgot the fixes syntax.
