### ISSUE TITLE
Crash when moving group on z axis - Mac

### ISSUE THREAD

**Issue by elliottohara** [smeighan/xLights#1411]
[xLights_dbgrpt-1339-20190112T000906.zip](https://github.com/smeighan/xLights/files/2751754/xLights_dbgrpt-1339-20190112T000906.zip)

Attempted to move a group. This group was composed of 3 singing props, but only submodels (smiling singing faces). Tried to drag it back (smaller values) on z axis and got a crash. Noted that the z axis said "inf" on the model properties.

When I re-opened xlights, I got a "could not load rgbeffects file, using default" of course that meant I had lost all my work. :)

**Comment by elliottohara** [comment]
Yep... I figured it was related to that. That's why I mentioned it.  Thanks!

**Comment by elliottohara** [comment]
@keithsw1111, would you like me to make another Issue for a feature request to disallow moving of submodels in layout?

**Comment by AzGilrock** [comment]
Keith closed this with a checkin which means code was changed.  So wait till next release and try again it should be fixed.

**Comment by elliottohara** [comment]
Duh! Sorry about that. Yeah, looks like he no-opped the move on submodels. That should fix it!

I'll test try it on next release. Thanks!
