### ISSUE TITLE
2019.4 crashes Windows 64 bit

### ISSUE THREAD

**Issue by monstrousmike** [smeighan/xLights#1413]
I noticed a couple of minor repeatable bugs in 2019.4 (Windows 64bit).

1. When trying to edit the "# Lights" for an AC string, xLights crashes. Workaround: Change the string type to RGB, edit the number of lights, then change it back to Single Color.
2. When trying to move some models from the Default preview to a custom preview, xLights crashes. (See the screen shot attached.) It did not crash for all models, just two so far. (I am rearranging my layout by moving models to a new preview, then shifting them around the layout.) Workaround: Moving models from the All Models preview to a custom preview seems to work fine.

Note: By "moving models" from one preview to another I mean changing the Preview value in the model properties pane. (See screen shot attached.)

The problem is repeatable with all of the 2019 versions of xLighst for Windows 64bit. I tried going back to 2018.59 and .58, but the layout is completely out of whack - models stretched all across the screen.

I am continuing to work with 2019.4.

Thank you in advance!

![xlightscrashreport](https://user-images.githubusercontent.com/46628259/51075017-0ea0e480-1654-11e9-95b9-5259c3a4002f.JPG)

![previewsetting](https://user-images.githubusercontent.com/46628259/51075018-12cd0200-1654-11e9-8965-94997f0ff137.jpg)

**Comment by keithsw1111** [comment]
I have tried all those things and cant get it to crash once. Can you package your logs

**Comment by deplanche** [comment]
I am saving the same problem as described above.  When trying to changing the number of lights on a polyline that is single color, xlights will crash.  Logs are below from the crash.

[xLights_dbgrpt-4216-20190115T210054.zip](https://github.com/smeighan/xLights/files/2762321/xLights_dbgrpt-4216-20190115T210054.zip)

**Comment by deplanche** [comment]
Posting this from Randal, who brought this to my attention, but didn't have a github account so posting for him.  Same problem, single color lights on a poyline chases xlights when changing the number of lights.
[xLights_dbgrpt-3212-20190115T195152.zip](https://github.com/smeighan/xLights/files/2762345/xLights_dbgrpt-3212-20190115T195152.zip)

**Comment by monstrousmike** [comment]
Sure thing. Here you go, and thank you for looking into this.

- MonstrousMike

facebook.com/monstrousmike

 

    On ‎Monday‎, ‎January‎ ‎14‎, ‎2019‎ ‎04‎:‎59‎:‎03‎ ‎AM‎ ‎EST, Keith Westley <notifications@github.com> wrote:  
 
 
I have tried all those things and cant get it to crash once. Can you package your logs

**Comment by keithsw1111** [comment]
Isnt this fixed in .5?

**Comment by deplanche** [comment]
Randal and I both had the crashes in 2019.5.

**Comment by monstrousmike** [comment]
I hadn't updated to .5 when I submitted the bug report. I am on .6 now and gave it a try. It seems to be working. Thanks again for checking into this.

- MonstrousMike

facebook.com/monstrousmike

 

    On ‎Friday‎, ‎January‎ ‎18‎, ‎2019‎ ‎03‎:‎11‎:‎14‎ ‎AM‎ ‎EST, Keith Westley <notifications@github.com> wrote:  
 
 
Isnt this fixed in .5?
