### ISSUE TITLE
xlights crashes after installing 2019_04 and saving rgbeffects 

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#1415]
Installed xlights . Did not do anything . Quit. Selected yes when prompted to save effects. Then Quit. Crash on Quit (File->Quit)

Second time, Opended and immediately Quit (Slected File->Quit)

Previous version was 2014_40
  
[xLights_dbgrpt-8436-20190113T184825.zip](https://github.com/smeighan/xLights/files/2752901/xLights_dbgrpt-8436-20190113T184825.zip)
[xLights_dbgrpt-13636-20190113T183719.zip](https://github.com/smeighan/xLights/files/2752902/xLights_dbgrpt-13636-20190113T183719.zip)

**Comment by keithsw1111** [comment]
Maybe a video driver issue. Can you ensure you are running the latest from you video card supplier.

I loaded your show folder, quit, saved and it exited ok.

**Comment by gerry4** [comment]
Thanks Keith,

Installed it on my work laptop as per usual  -so all the video drivers would be as per the company installation and probably locked down.

I was able to open a sequence (Animation only) , render all , save , pay, close , open another (with media) , repeat previous steps etc
Also use FPPconnect to upload the entire setup (channels) to an upgraded (2,6) Pi

Closed sequence. No problem. Then File, Quit and it crashed.

So the crash seems to be only when Quitting. If that is the only problem, I can leave with it and will cancel the debug prompt.

Regards


Gerard

________________________________

**Comment by keithsw1111** [comment]
Tried it again ... still cant crash it ... and again log files suggest it is openGL related and most of those issues are driver related ... you can try lowering the openGL version as well.

**Comment by gerry4** [comment]
Hello Keith

I tried 2.0 , rebooted, open xl, then 1.0 rebooted , open xl and in both cases it still crashed.

Could it be anything to do with xlights registry settings that may not have been updated/created at install - as they have started locking such things ..

If not.. please leave/close for now unless u want me to try something else . Subsequent upgrades may address  ..or as I start to sequence I may notice something else. Currently am upgrading all my PIs and BBB from 1.x to 2.6 which is time consuming. then will start doing stuff in xlights.

thanks

Regards



Gerard

________________________________

**Comment by keithsw1111** [comment]
If you want to wipe all your xlights settings run it with the -w command line option and it will be like a fresh install.

If its show folder related. Create a small sequence and package it and post it and we can try that out.

**Comment by gerry4** [comment]
Hi Keith,

I installed the 64 bit version .. but it did not help. Still crashes on exit.
Also installed it into an empty directory.

regards



Gerard

________________________________

**Comment by keithsw1111** [comment]
Then I can only assume it is a driver issue.

**Comment by gerry4** [comment]
Hello Keith

To cut a long saga short .. I have today managed to upgrade my work laptop to Windows 10 as one of the Beta users (full initialise of hard disk and fresh install of Windows ) and after installing 2019.06 of xlights, the problem has gone away ie no crash at all and have been working on it for a hour

Many thanks



Gerard

________________________________
