### ISSUE TITLE
Unable to load sequence: fseq

### ISSUE THREAD

**Issue by medic61** [smeighan/xLights#1416]
2019.4 64-bit

Upon opening a sequence I receive the Error: Unable to load sequence: path\filename.fseq

Once you click OK, it opens the sequence, I re-render, save, quit, reopen and get the same error. Also noticed the fseq file seems really small in size.

Thanks!
[fseq error.zip](https://github.com/smeighan/xLights/files/2753150/fseq.error.zip)

**Comment by keithsw1111** [comment]
I am pretty sure this is already fixed for .5

**Comment by lithgowlights** [comment]
It appears to be fixed in .5 for me. I was also experiencing this issue on files saved as V2 FSEQ files, but no issue with V1 FSEQ files.
