### ISSUE TITLE
Corrupt keybindings on latest release

### ISSUE THREAD

**Issue by camguy52** [smeighan/xLights#1417]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/2753291/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
To fix this shutdown xlights. delete the xlights_keybindings.xml file in your show folder and restart xLights. If it happens again please repost your logs.

**Comment by camguy52** [comment]
Thanks Keith, that fixed the problem.

 

Quick question, is there any way to wirelessly drive a string (remotly powered) using a Rasberry Pi (Wifi) with FPP software?  I have an isolated location that I can't get wiring to.

 

Xlights has been a game changer.  I went thru Lightshow Pro, Lightjams and many others until I found xlights.  It lights my house all year round!

 

Doug Hurrell
