### ISSUE TITLE
Fill effect on a single strand

### ISSUE THREAD

**Issue by ebuechner** [smeighan/xLights#1418]
On 2019 .4 when dropping the fill effect on a single string on my Mega tree the effect won't work and the ones that were already there in the sequence don't work properly and when selected can't be changed. 
I tried to fill effect on a few different things it seems to work until you open up the model and try to apply it to a single string.

**Comment by keithsw1111** [comment]
Can you attach a simple sequence that shows the problem.

**Comment by ebuechner** [comment]
https://youtu.be/iYd-FHuRHF8

**Comment by ebuechner** [comment]
https://drive.google.com/open?id=1vz6sUzqLRVTx4Ag1YS-lxKDa-Gp8VmVb

**Comment by keithsw1111** [comment]
You duplicate strand names are also causing issues

**Comment by ebuechner** [comment]
I'm not sure how the duplicate strand names got in there but thanks for pointing that out.

**Comment by keithsw1111** [comment]
I am only pointing it out because it seems to create selection issues when working on the effects. I think it looks up the row by name and the duplicate means the wrong effect is being selected.
