### ISSUE TITLE
Upload Controller configuration via FPP Connect

### ISSUE THREAD

**Issue by lithgowlights** [smeighan/xLights#1420]
The new FPP Connect dialogue does not allow uploading of the configuration to an FPP Master controller. If you select the tick box called UDP Out it actually erases the outputs for the master. Currently the only way to upload the configuration to the master is to install 2019.3 and upload it the old way

There is also a box between Playlist and Pixel Hat/Cap that has no title, and is unable to be ticked

**Comment by keithsw1111** [comment]
Isnt this now fixed?

**Comment by lithgowlights** [comment]
As far as I am aware it was. I’ll try again in 30 mins with .11 as it could have been broken again since the fix was implemented 

Dave

**Comment by jdormanCA** [comment]
I'm still not seeing the upload controller configuration and I'm on 2019.34.  I keep 2019.3 installed so I use it's FPP Connect tool

**Comment by AzGilrock** [comment]
Pretty sure this is all worked out.  Reopen if still a problem.
