### ISSUE TITLE
Moved objects in 3d Rotate bug

### ISSUE THREAD

**Issue by SniperMunyShotz** [smeighan/xLights#1422]
I am able to select a group for instance and move them all at once when selected, but not able to rotate them all at once, it only rotates the one it happens to select in rotation.

**Comment by AzGilrock** [comment]
Yeah I forgot to disable the rotate tool when a group is selected.  So not really a bug but just a feature that wasn't created yet.  Probably wouldn't be that hard to add it because we only need to rotate the base world position for each model.

**Comment by keithsw1111** [comment]
Is that what people would expect ... each model to rotate independently ... or the whole group to rotate around the group midpoint, I suspect some would expect the latter ... but that is not going to be so simple to do. Personally I am not fussed either way.

**Comment by keithsw1111** [comment]
Fair enough ... but i think i will leave that for you to implement ... its beyond my abilities.

**Comment by AzGilrock** [comment]
Issue #1509 is pretty much this same issue and has better info so closing this one.  BTW I've worked on fixing it and didn't find a solution that didn't have bugs so far.
