### ISSUE TITLE
2019.5 Mac - Timing track and model with same name

### ISSUE THREAD

**Issue by jarogers** [smeighan/xLights#1425]
xLights allows creating a timing track with the same name as a model.  Everything seems fine until you save the sequence, close, and re-open it later.  Now the model seems to have been merged into the timing track, now appearing to be lyric/phrase sub track.

Similarly, if you start with a timing track, and then add a model with the same name, the Display Elements pane will indicate that the model is already added to the sequence, and when you go to change the model name in Layout, it also changes the name of the timing track of the same name.

Yes yes, you might say that you just shouldn't name models and timing tracks the same, that's fine in hindsight - but it's sure a kick in the pants after spending days creating a sequence with timing tracks of the same name as models, only to find out all has gone to pot the next time you open the sequence file.

**Comment by AzGilrock** [comment]
See Issue #434 for some light reading on pretty much the same topic.  I dove in to fix the problem and ran into some roadblocks.  Problem is you can change model names while there are no sequences open at all so then how do you handle opening a sequence and then discovering you've changed a model name and it now clashes.  The Show directory has no clue which sequences are tied to that rgbeffects file.

**Comment by jeffla** [comment]
Typical identity management problem. You'd need to assign everything an internal (never changing) ID instead of relying on names. Not sure if you want to go down that road tho.

**Comment by jarogers** [comment]
@AzGilrock yes, pretty much the same thing.  I too created a bunch of models prior to even looking at sequences, then moved to sequences and happily created timing tracks for every musical instrument in the audio, which some corresponded to a lot of the models.

Perhaps some sort of 'internal name' for models and timing tracks, like a GUID, and then the UI name just becomes a label?  Or some sort of namespace taxonomy?  model.tuba and timing_track.tuba, etc.?

**Comment by jarogers** [comment]
Yep, beat me to it @jeffla

**Comment by jarogers** [comment]
No problem whatsoever @AzGilrock, please don't hesitate to reach out anytime you hit a roadblock again and need some more advice.  It would be my pleasure.
