### ISSUE TITLE
Channel to pixel map issue

### ISSUE THREAD

**Issue by dennis6675** [smeighan/xLights#1426]
Added DDP contoller (minleon WEC).  Testing a simple RGB string...  Pixel #1 channel #1 tests green, pixel #1 channel #2 test blue, pixel #1 channel #3 jumps to pixel #2 and tests red.  The issue cascades down the string.  So, can't make red on pixel #1  and grouping is incorrect.

The issue cropped up after an update prior to that all worked as expected.  I can't isolate whether it's software or hardware.  

Using the minleon controller interface pixel #1 can make red.

**Comment by keithsw1111** [comment]
You are going to need to share a lot more for us to do anything with this.

**Comment by keithsw1111** [comment]
Is this test mode? Is this scheduler?

**Comment by dennis6675** [comment]
New to this world.  My work around satisfies me.  However, I'm willing to give you whatever details you wish.

I used test mode channel by channel.  Pixel 1 (absolute pixel address #1 only) can't produce red in Xlights (test mode or with sequences).  Channel 3 test shows up as red on Pixel #2 (and then on and on).  Pixel #1 appears to only use 2 channels.  The anomaly appears regardless of the string I test.  Pixel #1 can produce red when I test directly with the minleon controller.  DDP or Artnet produce the same result.  The controller is not E1.31.

**Comment by keithsw1111** [comment]
Can you package your logs (tools menu) and attach them so we can see how it is configured. Most likely this is a config issue on your hardware.

**Comment by dennis6675** [comment]
This is the simple config that I tried to isolate the problem with...  This works with my hardware except pixel #1.  I would not even raise the issue except it worked before and now it doesn't.  

[dennis6675 xLightsProblem.zip](https://github.com/smeighan/xLights/files/2770601/dennis6675.xLightsProblem.zip)

**Comment by dennis6675** [comment]
This is not a big enough issue to bring in Wireshark.

I tried numerous Xlights versions that were known to work.  They do not work either.  Turning off "Keep Channel Numbers" checkbox reproduces the anomaly.  Since it's 1 pixel at the beginning of a string I can easily compensate.

I believe you are right and it's a hardware issue.  There's almost no user control of the minleon config (protocol and lights only for DDP).  I do have an inquiry into minleon, maybe they will respond.  Thanks for the time.

Your software is awesome.
