### ISSUE TITLE
extend song sequence by changing sequence duration

### ISSUE THREAD

**Issue by darylerwin** [smeighan/xLights#1427]
From zoom tonight...

Is there a technical reason why you cant extend a sequence by increasing the "Sequence Duration"? Of course you can extend the song via song tools but then anyone having that sequence would need to also do this song hack. You can currently shorten it simply enough, but you can't lengthen.

If you increase the value the sequence simply stops at the song end.

Probably more of a question of why this wasnt possible than a request to have it done...

**Comment by keithsw1111** [comment]
It is NOT possible because when we are using audio we key our position in the song off the audio position as it plays (dropping frames if necessary to stay in sync) ... no audio ... no position ... so it stops when the song stops. This is not going to change.
