### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by mararunr** [smeighan/xLights#1429]
Removed.......knew I shouldn't have been posting yesterday (cold and flu meds).  Sorry for taking up your time.

**Comment by deplanche** [comment]
You need to remember that the universe contains the start channel, so it's not just subtraction on that, you add 1 to the difference. For example, universe 1 is 1 to 512, that is 512 - 1 = 511 + 1 = 512.

Likewise Universe 2 is 513 to 1024, that is 1024 - 513 = 511 + 1 = 512.

So for universe 6 you have shown, which is 2563 to 3074, that is 3074 - 2563 = 511 + 1 = 512.  

All the same thing.

**Comment by keithsw1111** [comment]
I dont see a bug here. It sounds to me like you should be using 510 channels for you universe. Can we see more evidence there is a bug.

**Comment by mararunr** [comment]
I can't even follow my own dribble from yesterday.  Feeling better today and no, there is no issue.  My humblest apologies.  I can't seem to delete this so I just removed everything.
