### ISSUE TITLE
Keybindings appear corrupt.

### ISSUE THREAD

**Issue by TomL8345** [smeighan/xLights#1430]
I am getting the following message as I go to exit xLights 2019.6 64 bit.

Your keybindings appear corrupt.  Can you please use the tools menu Package Logs option and send us the file so we can work out why.

Here you go!
[xLightsProblem - Keybinding corrupt.zip](https://github.com/smeighan/xLights/files/2785349/xLightsProblem.-.Keybinding.corrupt.zip)

**Comment by gizmohd** [comment]
Here's another one.
[KeyBindingsCorruptNotice.zip](https://github.com/smeighan/xLights/files/2785433/KeyBindingsCorruptNotice.zip)

**Comment by keithsw1111** [comment]
Shutdown xlights, delete the keybindings file and restart xlights.

The error originates from last year and thus these logs dont help.
