### ISSUE TITLE
Poly Line limited to 1 light

### ISSUE THREAD

**Issue by Jbrehm22** [smeighan/xLights#1432]
After upgrading to the 3d version (2019.6) I opened my layout and several models that were poly lines had been changed to include only 1 light. Every time I go to increase the number of lights, it crashes. 

[xLights_dbgrpt-3952-20190123T061559.zip](https://github.com/smeighan/xLights/files/2787127/xLights_dbgrpt-3952-20190123T061559.zip)

**Comment by Jbrehm22** [comment]
My upgrade was drastic, I was using 2018.5 and went to 2019.6

I will look for the file you requested.
Thanks,
        John

**Comment by Jbrehm22** [comment]
[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/2787567/xlights_rgbeffects.zip)

**Comment by AzGilrock** [comment]
Thanks I'll try to remember to look at it tonight so if I don't reply by tomorrow feel free to bump the thread if another developer hasn't jumped on it.  I've got a couple new toys being delivered tonight that might distract me. :)

**Comment by Jbrehm22** [comment]
Thanks for your quick responses, I’m in no hurry. This is why I’m trying to learn this software now instead of in November!
        John

**Comment by keithsw1111** [comment]
Exactly which property are you changing.

**Comment by AzGilrock** [comment]
I seem to remember there was a recent change in PolyLine to accommodate single color strings.  Maybe it affected the upgrade path.

**Comment by AzGilrock** [comment]
The file you gave me has already gone through the upgrade.  I need a version before you saved it in the 3D version so I can see what it looked like before it upgraded.  You should have backup folders.

**Comment by Jbrehm22** [comment]
I will look as soon as I get home.

**Comment by AzGilrock** [comment]
Ok nevermind I see the issue but don't know the solution but I don't need any files.  If you create a simple PolyLine and set it to 1 node and 50 lights per node it just displays 1 node which is broken from how it worked last year.  I might have messed that up as part of the 3D updates since it's not something normally tested.

**Comment by AzGilrock** [comment]
Took a quick look and I'm pretty sure I messed this up when I was adding the ability for PolyLine to drop icicles.  I forgot about the single node multiple light scenario and didn't test it.

**Comment by Jbrehm22** [comment]
I'm not sure how relevant this is, but I tried copying my show folder over to my macbook and the polylines behaved the exact same way and the mac version crashed at the same exact point as the PC version. Again, I'm not sure how helpful this is but thought I would let you all know.
   Thanks,
         John

**Comment by AzGilrock** [comment]
I still think this is broken.  This fix works for Single Color string type but in RGB mode Lights/Node is still broken.

**Comment by sirdevan** [comment]
This is still broken. If i make ANY Poly Line and set the "Lights/Node" to anything other than 1 the count is off. example. set a Poly Line (can be straight or multiple angles) and set Lights/Node to 3 and Nodes to 10 and the line will only have 10 pixels.
