### ISSUE TITLE
2019.6 FSEQ Files not being created

### ISSUE THREAD

**Issue by jspiker77** [smeighan/xLights#1437]
Not really an issue this time of year but in 2019.6 the FSEQ files are not being created on new sequences, all the cache file are there just no fseq file.

**Comment by AzGilrock** [comment]
That is an option you can turn off so you sure Save FSEQ on Save is checked?

**Comment by jspiker77** [comment]
So, I turned render on save back on, and checked save fseq on save and it is working again. The render though does not create an fseq file although it shows in the status bar.

**Comment by darylerwin** [comment]
Believe that is the expected behaviour. Its up to you to do a save after the render all.

**Comment by keithsw1111** [comment]
Render never creates a FSEQ file ... only the save
