### ISSUE TITLE
Enhancement: Snap to mesh vertices, edges, and faces

### ISSUE THREAD

**Issue by jarogers** [smeighan/xLights#1438]
When adding/moving models, particularly in 3D, it would be nice to snap to vertices, edges, and faces.

**Comment by DoctorWiz** [comment]
I would like to see this enhancement as well.  Thanks!

**Comment by AzGilrock** [comment]
I just don't see a feature like this worth the time and trouble.  You are not designing parts for a 3D printer so you do not need that type of accuracy.

**Comment by DoctorWiz** [comment]
I agree that we don't **_need_** that degree of accuracy, but I am hardly the only light enthusiast who is also a bit of a perfectionist.  Also, it's a pretty standard feature on most any CAD or vector drawing program so anyone above novice level kinda expects it.
No need to make it a priority, but while you are in that section working on something related... well...

(I've worked hard to make my model preview to scale and as accurate as reasonably possible, even down to manually editing the XML file)

Thanks and Kudos for all your hard work though!  I'm having a blast with this!

**Comment by AzGilrock** [comment]
Well I like my software to run fast so my first thought it imagining having to iterate through a list of vertices, edges, and faces to do hit detection every millisecond and how that will introduce lag when you are dragging something around.  Then we get complaints about how the program is slow because of features like this.  This isn't a CAD or vector program.

Also for the record it does no good to post that you also want a feature unless you are famous or have made a significant contribution to the program.  Otherwise its just annoying.  In most cases if you don't see a feature implemented the first week it's posted then none of us really want to add it.

**Comment by jarogers** [comment]
It's also a matter of workflow efficiency.  Having models snap would allow for much faster layout (without having to fiddle around with 3D Dimensions to get it to look right from various perspectives).

I'd rather spend more time where it matters most - sequencing, all while still having a 3D layout that looks reasonably accurate.  Without snap, I end up having to spend more time to get to that level of reasonableness for my layouts.

Not to mention accuracy in layouts now will certainly aid in future software goals of including photometrics in layouts.

**Comment by jarogers** [comment]
> Well I like my software to run fast so my first thought it imagining having to iterate through a list of vertices, edges, and faces to do hit detection every millisecond and how that will introduce lag when you are dragging something around. 

I have every confidence in your ability to solve that problem on your own Gil, a great many lesser developers have been able to come up with solutions to that problem in other software far more used than xLights.

**Comment by AzGilrock** [comment]
All I can say is I will not be coding this I have better things to do.

**Comment by jarogers** [comment]
> All I can say is I will not be coding this I have better things to do.

Then why would you comment on issues that you have no intent on improving?

[http://static.nautil.us/10977_7ca5eb06feca2d4d2029ef99de456a25.jpg](url)

**Comment by AzGilrock** [comment]
Because it lets the other developers know that I'm not going to work on this and then if they also don't like the idea they can close it.

**Comment by DoctorWiz** [comment]
I'm a retired developer and I know all about feature creep, and setting priorities, but I thought there was a good chance you were using a 3rd-party library for the 3D stuff, and that such library might already contain snap functionality.  If it's gonna be ton of work, then yeah, screw it.  Having to iterate thru all the points did not occur to me, although (not to be a smart-ass) it doesn't seem to be a serious issue for other vector programs.  I would assume it's handled by a low priority background thread.
Again, I appreciate your work!  (I plan to make a $$$ contribution to you guys soon, at the very least you can have the $30 I was gonna spend to upgrade LOR)
