### ISSUE TITLE
Boscoyo Props Node Layout Fail

### ISSUE THREAD

**Issue by MGoBlue102** [smeighan/xLights#1439]
Many, not all Boscoyo props will not let you view node layout.  I have issue with snowflakes, and letters.  Jay has issue with singing bulbs.

**Comment by MGoBlue102** [comment]
Yes, specifically in version 7, boscoyo props will not allow you to view
the node layout.  Wiring layout works fine but not node layout.
Specifically, I have 12", 18", 36" snowflakes, all the letters from boscoyo
to spell MERRY CHRISTMAS.  None of which allow node layout.  I have Chroma
Bells and they work fine.  Another user on Zoom instantly reported
yesterday that he has the chroma bulb singing faces and they too will not
let you view node layout.  Later in the evening last night another user has
a custom model light bulb singing face and he cannot view node layout.  All
of us can view wiring layout, just not node layout.

**Comment by AzGilrock** [comment]
Has node layout ever worked for custom models?  I normally just hit the ... button to view the data and that shows the node layout.

**Comment by AzGilrock** [comment]
I think everyone is expecting a feature that has never existed.  Show me a screenshot of ANY custom model's node layout.

**Comment by MGoBlue102** [comment]
I'm not positive about the custom. When he shared his screen Saturday he
indicated that he has always been able to right click on it and show node
layout.  Personally I did not experience that particular prop issue.  All
mine and others in Zoom Saturday were specific to certain Boscoyo props but
not all of them.  I opened a new layout tab and downloaded the letters over
again yesterday just to make sure that it was not my prop.

**Comment by MGoBlue102** [comment]
If the boscoyo products import as custom models then yes they have always
had that ability.  When the other guy first displayed his screen I thought
he was displaying a Boscoyo singing face bulb but he indicated that it was
not.  I have three different boscoyo products currently on my house.
Snowflakes, letters and bells.    The bells display as they always have
when I select node layout but the other two will not.

**Comment by AzGilrock** [comment]
So I guess hoping for a screenshot isn't going to happen...lol

**Comment by keithsw1111** [comment]
I will look at this tonight ... I clearly broke it when i added the 3d custom model which was a challenge to represent in 2D.

**Comment by AzGilrock** [comment]
I wouldn't rush it's only a minor inconvenience since users have 2 other ways to see the same data.

**Comment by MGoBlue102** [comment]
Works fine in 6.  Not 7.  Users in zoom right now are sharing.  I am on
mobile device remote.  Trying to get screen shot.

**Comment by MGoBlue102** [comment]
Ok.  Screenshot of error attached.
