### ISSUE TITLE
Optionally delete "unused" effects on conversion from 3.X

### ISSUE THREAD

**Issue by PLLaberge** [smeighan/xLights#144]
In order to reduce the clutter and increase the usability in the sequencer window, it would be great if on conversion of the XML from 3.X if there was a way to delete all "unused" effects. (I was sloppy in 3.X and never paid any particular attention to the other layer unless I was using both layers.) Specifically, if the blend mode is set to "Effect 1", any effect on Layer 2 would be deleted and vice versa. All other blend modes would keep effects on both layers. After running this filter, only "live" effects would remain in the sequencer window.

**Comment by AzGilrock** [comment]
We are already doing this.  Do you have an example where it looks like we aren't?
Here's some of the things we fix:
If you have mode Effect 1 and the blend slider is 0 we delete effect 2.
If you have mode Effect 2 and the blend slider is 100 we delete effect 1.
We remove all None effects and we delete all empty layers.

**Comment by PLLaberge** [comment]
Hmmm... Doesn't seem to be working for me. Just converted a fresh sequence and you can see below that the Blend mode is Effect 2, yet Effect 1 still exists in the first cell of M24TREE120. 
![blend-mode-1](https://cloud.githubusercontent.com/assets/11765690/6958202/99f80c9e-d8bd-11e4-89c9-488f10cab666.jpg)

If you want to test with one of my sequences, grab Carol of the Bells from http://nutcracker123.com/forum/index.php?topic=794.0

**Comment by dpitts** [comment]
Is the blend slider 100?

**Comment by PLLaberge** [comment]
No, it's set to 0. As far as I can tell, in 3.6.15, the blend slider is independent of the blend mode. It seems to be perfectly valid to have the blend slider = 0 for blend mode Effect 1 or Effect 2. I think the algorithm needs to also delete effect 1 when blend mode = Effect 2 and blend slide = 0.

Now that I look more closely, the algorithm seems to be doing a better job with cleaning up effect 2 when blend mode = Effect 1 but I'm still seeing quite a few cases where it's not catching these. I'm seeing this with the Carol of the Bells mentioned above. I'll dig a bit more closely to see the setting of the blend slider.

**Comment by PLLaberge** [comment]
Here's what I see in 3.6.15 for my megatree during the first 20 seconds of Carol of the Bells. Effect 2 is selected: blend slider = 0.
![cotb - 3 6 15 - effect 2](https://cloud.githubusercontent.com/assets/11765690/6978520/4be580fa-d989-11e4-9de9-f891df354bd9.jpg)

Here's what I see it 4.0.12 - a faithful reproduction - both effect 1 and effect 2 are present. Ideally only effect 2 would remain.
![cotb - 4 0 12 - effect 2](https://cloud.githubusercontent.com/assets/11765690/6978523/555f3a40-d989-11e4-9f12-a1f61b549e14.jpg)

A little later on, in 3.6.15 with Effect 1 selected: blend slider = 0 
![cotb - 3 6 15 - effect 1](https://cloud.githubusercontent.com/assets/11765690/6978532/7a3a54a8-d989-11e4-9351-4b81ddc77d07.jpg)

And the same thing in 4.0.12. Ideally, only effect 1 would remain.
![cotb - 4 0 12 - effect 1](https://cloud.githubusercontent.com/assets/11765690/6978549/a49f63be-d989-11e4-84bc-5b9bf8956d6b.jpg)

Not a big deal, just a nice to have.

**Comment by smeighan** [comment]
can you mail your xlights_rgbeffects.xml and the sequence.xml to xlights@meighan.net
We will use yours as a test case.
thanks

**Comment by stevegiron** [comment]
I too have the same unused effects in my sequences. Sometimes it's accidental and sometimes it's done on purpose so that I can copy effects elsewhere when sequencing especially with time consuming effects.

**Comment by AzGilrock** [comment]
I was reading this one again.  I showed what the algorithm is above.  If it's incorrect all someone needs to do is run the old version and figure out what our conversion decisions should be.  I just copied what Sean gave me in his conversion awk script.  I've never used effect 2 in the old version so it didn't matter to me.

**Comment by PLLaberge** [comment]
Gil, I've PM'ed you and Sean the sequence file above.

**Comment by AzGilrock** [comment]
What I wanted was for someone else to do the home work.  I'm not at home and I don't want to install old versions on this laptop.  All you gotta do is run 3.6.15 and tell me when you have 2 effects and set it to Effect 1 at 0 and 100 percent blend which effect shows and then do the same thing when you have it set to Effect2 at 0 and 100 percent.  My suspicion is it was supposed to be 0 percent instead of 100 for Effect2.

**Comment by PLLaberge** [comment]
Will do.
    
    On 2015-06-09 06:08, Gil Jones wrote:
    
    
      What I wanted was for someone else to do the home work. I'm not
        at home and I don't want to install old versions on this laptop.
        All you gotta do is run 3.6.15 and tell me when you have 2
        effects and set it to Effect 1 at 0 and 100 percent blend which
        effect shows and then do the same thing when you have it set to
        Effect2 at 0 and 100 percent. My suspicion is it was supposed to
        be 0 percent instead of 100 for Effect2.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
      No virus
        found in this message.
        Checked by AVG - www.avg.com
        Version: 2015.0.5961 / Virus Database: 4355/9978 - Release Date:
        06/09/15

**Comment by PLLaberge** [comment]
Here you go. Results below. Issues with everything but Effect 1, Slider=0.

![sliders - 3 6 15](https://cloud.githubusercontent.com/assets/11765690/8073996/5dba1bbe-0ee1-11e5-9998-4522871eb250.jpg)
![sliders - 4 1 3](https://cloud.githubusercontent.com/assets/11765690/8073999/6213f806-0ee1-11e5-9dc2-648bb08c6a5f.jpg)

**Comment by PLLaberge** [comment]
Awesome! Thanks!
