### ISSUE TITLE
Enhancement for Shared/Imported Sequences using 3D per preview render styles

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#1444]
With the ability to render from a 3D viewpoint now being added, I am thinking it would be beneficial to add some type of indication in a file if it contains effects that are using the 3D per preview render styles.  Otherwise someone bringing that into 2D only, or 3D without the same viewpoints are likely going to get some odd looking effects.   I am thinking mainly for sequences that are being shared freely on the google drive.  It's easy to see if the models are in 3D, and if 3D viewpoints have been created, but time consuming to check each effect to see if it is rendered from a 3D viewpoint.  

Associated with this, for any of the shared downloads I can make a comments in the text as to them using 3D viewpoint so people are aware before they download.  But would a checkbox or simple Y/N indication sort of like lyrics or sequence be more beneficial?

**Comment by keithsw1111** [comment]
So there are 2 proposals here.

1. an enhancement to the XML metadata re shared sequences. I need some convincing that this is a good idea ... it seems kind of arbitrary.
2. an enhancement say to Check Sequence to highlight areas of concern that may make a sequence hard to import as they are not part of the sequence but part of the layout. Such as dependencies on viewpoints or states or faces,

**Comment by AzGilrock** [comment]
The odds of 2 different users having compatible multiple views seems really low.  Only thing I could see is a dialog that lets you decide where you are going to route all the views.  Really people should not be sharing sequences that have multiple viewpoint effects.

**Comment by keithsw1111** [comment]
I definitely dont want to be popping up dialogs asking people how they would like to map a missing viewpoint.

**Comment by AzGilrock** [comment]
Seems like its the same as popping up a dialog when the model name doesn't exist.

**Comment by keithsw1111** [comment]
But its not if you are mapping sequences ... only if you are opening sequences on a layout that has changed ... similar but different use-case.

**Comment by deplanche** [comment]
I wasn't sure about adding the line to the information for a shared sequence download, so probably can't make a great case to add it.   Was just thinking there are going to be 2D sequences and 3D sequences eventually, and might be worthwhile to have something under the Type, Creator, etc to indicate which it would was.   Would be just as easy to just add a note if there was a shared one with 3D viewpoints that is being shared.  But all of that really depends on how 3D viewpoint imports get handled, or if they really should even be shared. 
![image](https://user-images.githubusercontent.com/17793531/51950336-13a8b680-23fe-11e9-8f50-bae428d7ebf3.png)

**Comment by keithsw1111** [comment]
Its not really our position to say do or dont share a sequence so I dont see how we can say no 3D. I can make it easy for you to tell that a sequence has dependencies on faces, states and viewpoints ... it is then up to the importer to either make them exist ... or fix them up after import ... or not import those elements (although i am not going to show effect/models that use these things).
