### ISSUE TITLE
Moving props on stage v2019.9

### ISSUE THREAD

**Issue by kmacmaster** [smeighan/xLights#1452]
See the attached gif. As I move an item on the stage, the position of the mouse does not stay over the prop. It looks as if it moves in a parabolic relation to the mouse pointer.

![ezgif-1-9b29caa3cb8d](https://user-images.githubusercontent.com/20920979/52237492-a7173700-2897-11e9-851b-24bc9b74cbf5.gif)

**Comment by kmacmaster** [comment]
Just tried it again at multiple zoom levels and it was still present.  Something to consider, I changed the stage to 500x500 before realizing that I was in a new version where the whole stage stayed black at all times.  Does changing the stage area cause this?

Last, is there a way to see the extents of the stage area?  Since this is in 2D, the stage may matter?

**Comment by keithsw1111** [comment]
There is a checkbox on the background properties to draw the green stage box

**Comment by AzGilrock** [comment]
I thought we had a green box around the stage area but maybe we determined it wasn't useful and it got deleted.  Yeah I know I remember running into this but only for 2D.  I'd have to dig into it again to remember why it wasn't a quick fix.

**Comment by kmacmaster** [comment]
OK, found the bounding box, very helpful.

**Comment by AzGilrock** [comment]
Yeah that reminds me I need to test that bounding box theory again.  I could swear any model in a model group that fell outside that boundary wouldn't render.  Just can't remember last time I tested if I made sure it wasn't an individual model.  Otherwise not sure how we would have guaranteed that the 2D rendering wasn't impacted for Per Preview renderings.

**Comment by keithsw1111** [comment]
I think it works for minimal grid ... but probably not for the one that renders as if the whole screen is a grid ... as that was linked to the green box.

**Comment by keithsw1111** [comment]
i think this is fixed in .20
