### ISSUE TITLE
Mesh of property does not render

### ISSUE THREAD

**Issue by thekameleon** [smeighan/xLights#1454]
I can add the mesh of the property but it comes up invisible unless I select the Mesh Only check box in which I see the green wireframe mesh.  When I open it in AutoCad MeshMixer, it renders as expected. The obj was created using Pix4d

[House_simplified_3d_mesh2.zip](https://github.com/smeighan/xLights/files/2838860/House_simplified_3d_mesh2.zip)

**Comment by AzGilrock** [comment]
It's not going to work without the material file referenced inside that OBJ file you provided.  You need to get all the files involved (OBJ, MTL, PNG, JPG, etc.) and put them all into the same directory and then point xLights to that OBJ file.  I would also recommend don't name things with spaces just tends to cause trouble.

**Comment by thekameleon** [comment]
Correct.  They are actually in the same directory?  Should I use a specific directory?  Like the show directory?

**Comment by thekameleon** [comment]
OK that is exactly my issue.  I removed the space and put all the files under the show directory and it worked perfectly... Thank you guys
