### ISSUE TITLE
2019.10 Ubuntu 18.04lts Crashing on new custom model

### ISSUE THREAD

**Issue by extremeskillz** [smeighan/xLights#1456]
Hi Guy,
I updated to the latest version on Ubuntu 18.04lts with the appimage and get a crash report when I begin making new custom model. I wanted to report as its cause me not to move forward. Thanks.
[xLights_dbgrpt-4348-20190207T201011.zip](https://github.com/smeighan/xLights/files/2843263/xLights_dbgrpt-4348-20190207T201011.zip)
[xLights_dbgrpt-4459-20190207T201442.zip](https://github.com/smeighan/xLights/files/2843264/xLights_dbgrpt-4459-20190207T201442.zip)
[xLights_dbgrpt-7738-20190205T201456.zip](https://github.com/smeighan/xLights/files/2843265/xLights_dbgrpt-7738-20190205T201456.zip)
![screenshot from 2019-02-07 20-15-46](https://user-images.githubusercontent.com/40648180/52453495-b1466900-2b15-11e9-9c8f-d55894b3ea6e.png)

**Comment by cjd** [comment]
Confirmed in appimage and source compile

**Comment by cjd** [comment]
Issue introduced with https://github.com/smeighan/xLights/commit/b37799b9d52ca715819dae45abd5e7cecd6809ad
when "Add 3D to custom model" was added.
The problem is in CustomModelDialog::GetActiveGrid
Looking into why

**Comment by extremeskillz** [comment]
Thanks Chris.

**Comment by ghormann** [comment]
Fixed by #1516

**Comment by ghormann** [comment]
@keithsw1111  Patch has been applied. I believe we can close this one.
