### ISSUE TITLE
3D objects (images) transparency

### ISSUE THREAD

**Issue by RichM-CO** [smeighan/xLights#1459]
In xlights 2019.7 I have a 2D image that use for the house. I put the image in 3D objects, placed it mid depth on z axis and set the transparency to 50%. I can see my models through the image just fine. When I updated to the latest xlights 2019.11 I can no longer see my models behind the image. The transparency is still set for 50%. I can see the grid behind the image but no models. When I rotate to look behind the image the models are still there. I went back and tried all previous versions of xlights 2019.1 thru .10 and it appears to start happening in version 2019.8. I included two screen shots I hope will help. ![xlights 2019 7](https://user-images.githubusercontent.com/47505521/52538281-18d70100-2d2e-11e9-9822-5e9b5a7c708f.png)
![xlights 2019 11](https://user-images.githubusercontent.com/47505521/52538287-2e4c2b00-2d2e-11e9-84ad-57b7f5f3ab1a.png)
This is my first time using GitHub to report issues and apologize if I did this wrong. I looked for anyone else having this issue but couldn't find any results.

**Comment by RichM-CO** [comment]
Here is one more screenshot to show what I'm looking at. ![xlights 2019 11b](https://user-images.githubusercontent.com/47505521/52538520-fb576680-2d30-11e9-949b-6c91ae755507.png)

**Comment by AzGilrock** [comment]
Yep I confirmed it.  I was still running 2019.7 so I just upgraded and saw it change.

**Comment by AzGilrock** [comment]
There was a checkin 13 days ago that says it improves the drawing of transparent objects.  Wonder its only a problem on Windows because Dan tests on Mac or this scenario wasn't tested.
