### ISSUE TITLE
Polyline with curve when rotated on the z axis 2019.10

### ISSUE THREAD

**Issue by thekameleon** [smeighan/xLights#1460]
This could be by design, I am not sure.  However if I have a 3 segment poly line.  The one's on the left and right are vertical.  The one in the middle is an arch.  When I try to rotate the entire.  The top of the arch bends backwards at the top of the arch.  I wouldn't expect it.  I can fix obviously it but it would be nice if the arched line didn't bend.

**Comment by AzGilrock** [comment]
There are several rotation issues in the program that I've wasted 5 days trying to fix.  Not too many things are found that I don't already know about.

**Comment by AzGilrock** [comment]
Ok I took another look at this with a clear head and it had nothing to do with the other rotation problem I was fighting with.  The PolyLine model was completely ignoring rotating the curve handles so I think I've got that fixed.  Thanks for catching this.  Sorry it took so long to fix.
