### ISSUE TITLE
Enhancement Request: Relative Cone and Square Grab Icons

### ISSUE THREAD

**Issue by thekameleon** [smeighan/xLights#1461]
Unless I am missing a setting, it would be great if the cone and square icons I can use to grab, pull, drag, rotate, resize, etc.  were sized relative to the screen as oppose to absolute values.  This way when I zoom in these icons would resize as opposed to getting bigger and bigger.

**Comment by AzGilrock** [comment]
I thought this was asked for before.  Its been on my wish list to do but its not something that's easy to modify.

**Comment by thekameleon** [comment]
I got through it though.

**Comment by keithsw1111** [comment]
Can I close this now?

**Comment by thekameleon** [comment]
Absolutely. Thanks you guys

Sent from Yahoo Mail on Android 
 
  On Wed, Apr 3, 2019 at 15:25, Keith Westley<notifications@github.com> wrote:   
Can I close this now?
