### ISSUE TITLE
Enhancement Request: Custom Rendering Planes / Paths

### ISSUE THREAD

**Issue by thekameleon** [smeighan/xLights#1462]
I honestly may be wording this poorly, so please forgive me. From what I can tell, the rendering plane is two dimensional and along the back of the layout.  In other words.  The Bars effect with a Horizontal Compress comes from the left and right of the screen inward. With my idea, I could draw a path that would be say a half circle that the effect would effectively render on.  In the image attached to this, I would envision having a path that would be a half circle that would cut through the houses so if I did a Bars H-Compress effect.  It would start with the two houses on the ends and meet in the middle of the court.  Hope I am explaining correctly.

![lightsonkingarthur](https://user-images.githubusercontent.com/1361317/52543975-72155380-2d73-11e9-9aa0-e59de05d1c59.PNG)

**Comment by AzGilrock** [comment]
The options we provide already are what you are going to have.  You can rotate to be looking birds eye top down view, save it as a camera position, then select Per Preview rendering and select that camera angle.

**Comment by thekameleon** [comment]
Reading your response, I realize I didnt explain it well. I'm looking for the bar effect to run across the front of the houses as it goes around the court. I suppose in a 2D world I would create a panaroma image from the center of the court... am I making sense?

**Comment by AzGilrock** [comment]
Yeah that will be one of these requests that sits here forever and never gets implemented.  The code uses a 2D projection based on camera angle to create a 2D plane for the render buffers.
