### ISSUE TITLE
Crash on open when clicking on .xml file again 

### ISSUE THREAD

**Issue by Bill-Paulus** [smeighan/xLights#1463]
Keith xlights is crashing on open when clicking on .xml file again just like it did in ticket #1324.  running 
[xLightsProblem2019.11.64.zip](https://github.com/smeighan/xLights/files/2849772/xLightsProblem2019.11.64.zip)
2019.11 64 bit

**Comment by keithsw1111** [comment]
I am going to need the sequence

**Comment by Bill-Paulus** [comment]
[Werewolves of London Bill Paulus.zip](https://github.com/smeighan/xLights/files/2852880/Werewolves.of.London.Bill.Paulus.zip)

**Comment by keithsw1111** [comment]
I loaded this ok ... and I dont see anything in the logs ... maybe you could describe the problem or make a video of it

**Comment by Bill-Paulus** [comment]
https://www.dropbox.com/s/jdcyksuaqdx3o8v/IMG_9110.MOV?dl=0

**Comment by Bill-Paulus** [comment]
Also it does open fine if xlights is open first just like the last time this bug happened

**Comment by AzGilrock** [comment]
Why do you insist on opening your sequences this way?  I'd just block this behavior folks should not be associating xLights with XML files.

**Comment by Bill-Paulus** [comment]
Normally by opening it this way Xlights automatically changes the show folder to the correct one for that sequence. This way I can see what it looks like when the other person made it.

**Comment by Bill-Paulus** [comment]
I can do it the other way but it just more steps

**Comment by AzGilrock** [comment]
I can't access dropbox from work so I can't see what you shared right now.  Are you trying to double-click a sequence XML for a different show folder while you have xLights open?  If so then there have always been crashes that occur occasionally when you switch show folders.  I still have it happen to me and we've never tracked down all the reasons.  Also sequences are not required to live in the show folder so I'm surprised to hear xLights even switches show folders.

**Comment by Bill-Paulus** [comment]
No I do not have Xlights open when I do this and yes if I click on the sequence XML file it normally would switch to that sequences show folder (ie ppd or Xtreme club sequences)  and will open so I can see what it looks like in the way it was made before mapping it to mine.  I also have a show holder for doing my lyrics tracks where I have four large dense matrixes so I can get precise on the mouth movements when I make my lyrics tracks. The Dropbox was the movie because it was too big to directly lay here and all it shows is me going to the show folder clicking on the XML for the sequence and the window that comes up that says  Xlights has stopped working  along with the window that says windows is trying to find a cure & close program. This happened last year around the 2018.44-45 version and Keith fixed it in 2018.47 and was good up until 2019.11

**Comment by AzGilrock** [comment]
Yeah I wasn't aware we had code now that would switch from the Show directory stored in the registry to the one a sequence is in automatically.

**Comment by Bill-Paulus** [comment]
So I started going back and checking previous versions in 2019.07 is the last one that worked

**Comment by Bill-Paulus** [comment]
[xLightsProblem2019.7 works.zip](https://github.com/smeighan/xLights/files/2863184/xLightsProblem2019.7.works.zip)
log files just incase

**Comment by Bill-Paulus** [comment]
All Fixed again Thanks Keith!
