### ISSUE TITLE
Crash when trying to import a song into XLights.

### ISSUE THREAD

**Issue by Ddaniels2020** [smeighan/xLights#1464]
I'm following the instructions in this video on how to import a song into XLights and add timing tracks.
https://www.youtube.com/watch?v=3vUYknVejnc&fbclid=IwAR1YdUYtzMAJ4wP9aBZijT_Aqz5p5_BFvXfyO5YLa42yTsOIiarwPIMYSAc&app=desktop
When I try to import a song, I get a crash message each time.  I've downloaded the most current version of XLights today.  I'm on a Mac OS High Sierra.  The music I'm trying to download is in my iTunes/Apple Music file.  Thanks.

![screen shot 2019-02-10 at 8 04 53 pm](https://user-images.githubusercontent.com/47511845/52546396-6aaa7600-2d84-11e9-89a8-56e7ffb94d50.png)

**Comment by keithsw1111** [comment]
I need the crash log and the audio file to reproduce it.

**Comment by Ddaniels2020** [comment]
Here's the error message I'm getting now and I've attached the music file below.  Thanks.

![screen shot 2019-02-11 at 6 35 28 am](https://user-images.githubusercontent.com/47511845/52563847-1b863480-2dc8-11e9-8835-8d27338e05fa.png)

https://itunes.apple.com/us/album/ghostbusters/904002810?i=904002821

**Comment by AzGilrock** [comment]
Yes because M4P has digital rights protection.  Convert your audio to MP3.  I doubt Keith will buy the song to fix your problem.  He may just block M4P to fix the crash.

**Comment by Ddaniels2020** [comment]
Thank you, Gil.  Appreciate the response!
