### ISSUE TITLE
Stability issue with Artnet Timecode Tracking

### ISSUE THREAD

**Issue by shmorgan** [smeighan/xLights#1466]
When xSchedule is freshly loaded, the sequence will track fine and I see very few corrections, but about 20s or so into the song, it starts getting more and more sync corrections, until it is overloaded toward the end of the song and can't seem to get sync'd up. In addition, I am seeing Glib-Critical errors : Source ID xxxxxxx was not found when attempting to remove it. Possible resource leak or event handler not keeping up?

[xlight.log.zip](https://github.com/smeighan/xLights/files/2852790/xlight.log.zip)

**Comment by shmorgan** [comment]
Adding wireshark trace with artnet packet capture

**Comment by keithsw1111** [comment]
Is this still a problem?

**Comment by shmorgan** [comment]
Yes, leads to major delays and hangs of xschedule.

**Comment by patdelaney** [comment]
I am currently employed. PLease remove me from this list.

Thanks

Pat Delaney

**Comment by keithsw1111** [comment]
We can't Pat ... you have to do that. At some point you told github you wanted notifications.

**Comment by jholmes09** [comment]
When I try this, over the course of a 20-60s I start to get the little turtle icon. The GUI refresh slows to a crawl and physically connected lights refresh every couple of seconds (versus 40ms or 33ms). Stopping the Timecode source seems to resolve the GUI but as soon as you start sending timecode again, the problem returns to roughly the same "crawl" it was  (versus slowly building up again overtime).

**Comment by shmorgan** [comment]
This is what I was seeing too, almost like there was some kind of resource leak happening or the event messages were getting queued/lost.Thanks,Stephen MorganCell: 770-633-6007


-------- Original Message --------
Subject: Re: [smeighan/xLights] Stability issue with Artnet Timecode
Tracking (#1466)

**Comment by keithsw1111** [comment]
So I have moved all the logging during sync to it's own logger which seems to get rid of the turtles except during song transition which is what i would expect. This will be in .41 with sync loggin by default mostly off.

**Comment by keithsw1111** [comment]
I did not see the UI slowing to a crawl. Note I was testing with 2 copies of xLights ... not timelord as it does some weird stuff like broadcasting on 192.255.255.255 which my router wont forward and xlights does not seem to pick up. If you are using a different timecode source it may be down to those differences.

**Comment by keithsw1111** [comment]
I may have an even better fix which ignores timecode for 1/2 second to minimise over processing.

**Comment by shmorgan** [comment]
I was thinking about that, it really only needs to update every half second or so. Not every frame.

**Comment by keithsw1111** [comment]
I am closing this ... please reopen if you continue to have issues after 2019.42

**Comment by keithsw1111** [comment]
I have made additional changes to timecode in .15 which I believe makes what xLights sends out more compliant.
