### ISSUE TITLE
Play Range Duration

### ISSUE THREAD

**Issue by jonash326** [smeighan/xLights#1469]
If the playhead region is under .125 seconds, ignore the selected region and just play the darn thing. (: This is an issue I've had for years, and it especially exists for those using a trackpad. Quite often when moving the playhead, or selecting a new time to play from, a very small part is highlighted. Then when you hit the spacebar to play, you get a very short blip. It often takes 4-5 times of clicking on the waveform to not select a very small region and actually play. Thanks!

**Comment by AzGilrock** [comment]
If all you want to do is play from a point just click in the timeline zone above the waveform.

**Comment by jonash326** [comment]
Duh, thanks.

**Comment by AzGilrock** [comment]
Yeah when you write issues with "just play the darn thing" and respond with "duh Thanks" I'm not changing a "darn" thing.  Better go suck up to Keith.

**Comment by jonash326** [comment]
So sorry. By "duh" I was referring to myself and a solution I should have thought of, quickly realized that wasn't apparent and changed my response. I'm sorry for any slight or offense given.

**Comment by AzGilrock** [comment]
Ok peace... :)

**Comment by keithsw1111** [comment]
I think this was done a while back
