### ISSUE TITLE
Saving Taking Forever?

### ISSUE THREAD

**Issue by WhimsicalMatt** [smeighan/xLights#1470]
Hey all, quick question... I'm rather new to xLights, but never had an issue like this before. I updated to the newest version today... And every since I updated... My sequences are taking 25+ minutes to "save" and once they "save" they aren't really saved, because I'll go to open it, and it says "There is an auto-save that seems to be more recent. Would you like to open that one instead? 

Anyone else having this issue? I have no idea how to fix this. This issue has never happened before.

**Comment by computergeek1507** [comment]
do "Package Sequence" and Upload the Zip so we can look into it.

**Comment by keithsw1111** [comment]
Is this still an issue?

**Comment by WhimsicalMatt** [comment]
It's not actually... Turns out I had the "render on save" option turned
on... so it was taking longer than what I was use to. Sorry about this...
I'm still trying to learn xLights.

Thanks for all your help!

*Matt Stout, Realtor**® and** CNE**®*
*Matt Stout Realtors & Co.*
*Multi-Million Dollar Producer*
*Cell: 479.806.2796*
Keller Williams Platinum Realty
7301 Phoenix Ave.
Fort Smith, AR 72903
479.434.3000
