### ISSUE TITLE
Crash on Delete Node Polyline

### ISSUE THREAD

**Issue by kmacmaster** [smeighan/xLights#1472]
When I right click on the handle (didn't know it was a handle at the time) and delete the node, it crashes.  See attached video and crash report
[Crash on Polyline.zip](https://github.com/smeighan/xLights/files/2867447/Crash.on.Polyline.zip)

**Comment by AzGilrock** [comment]
LOL...never thought about anyone trying to delete a boundary handle

**Comment by kmacmaster** [comment]
Yeah, I was a bit confused as to why there were points and no nodes. My naivety is everyone else's profit.
