### ISSUE TITLE
2019.12 Model images fades/transparency

### ISSUE THREAD

**Issue by RichM-CO** [smeighan/xLights#1476]
Hello, 
I updated to 2019.12. All my model images have disappeared in the layout and house preview. The model is still there in the list but no image is visible in layout. I have transparency set to 50%. I then changed transparency to 0% and the model appears in layout again. In the sequencer I tried using fades on the image model and it only comes on when the value is 100%, I cannot fade in or out. The string properties are set to single color white. This does not cause a crash. Is there more info I should include?
Thank you, 
Rich

**Comment by keithsw1111** [comment]
This seems to be working in the dev build so pls retest in .13

**Comment by RichM-CO** [comment]
Update: I tested this in 2019.13 and getting the same issue. I am using a windows machine. Here are a couple of screenshots where the only change is to transparency. Any value other than zero makes the model disappear. I'm still not able to fade the model on and off in the sequencer.
![xlights 2019 13](https://user-images.githubusercontent.com/47505521/53217141-2cc71080-3614-11e9-9716-7cf0ffbe7e92.png)
![xlights 2019 13b](https://user-images.githubusercontent.com/47505521/53217150-36507880-3614-11e9-936b-b293a14eda9f.png)

**Comment by dkulp** [comment]
Just a note:  keith's change didn't fix this (his change only modified 2d rendering and the screens shots are obviously 3d).   Should be fixed now.

**Comment by keithsw1111** [comment]
Hmmm ... yeah ok ... mine fixed 2d.
