### ISSUE TITLE
Crash when Importing Sketch with 2019.12

### ISSUE THREAD

**Issue by itsayceecee** [smeighan/xLights#1477]
Very new User to xLights , using SketchUp trying out the 3D Feature.
Had been working fine importing Sketch file (Sketch_8) however upgrading to the latest version of xLights results in an immediate crash. 
I thought it was changes I had made to the sketch (Sketch_9) but the original sketch now crashes xLights on import - it's was fine until I updated to 2019.12

Easily reproducible if you need more info.

 (Sketch files included in crash report)
[xLights_dbgrpt-7358-20190216T223533 2.zip](https://github.com/smeighan/xLights/files/2872444/xLights_dbgrpt-7358-20190216T223533.2.zip)

**Comment by AzGilrock** [comment]
I think from the log your on a MAC.  It helps to list MAC or Linux in the bug title because it's not as common and it alerts the experts in those areas.  I tried it on Windows and it's importing without issues.  I tried 2019.11 and 2019.12.  Only option now is usually someone with a MAC to try it.

**Comment by dkulp** [comment]
I’m able to get it to crash, but it’s a strange one.  Where it’s crashing (even in the debugger) is completely unrelated to anything.   There’s some sort of memory corruption or something happening.   I have to keep reloading the obj file 3 or 4 times to get it to crash as well.

**Comment by dkulp** [comment]
I just pushed a fix that MIGHT fix this....  It's not loading an obj that's an issue.. it's replacing an obj with another.   If you delete the mesh and then recreate it, it likely would be OK.  However, you would need to reposition everything which would kind of suck.

**Comment by jayceecee** [comment]
Thank's folks , I'll try again on my Win machine.
Will also delete the mesh and reposition - not too worried about the repositioning - it's a good learning curve :-)
feel free to close the issue
