### ISSUE TITLE
Renaming Models and  Groups Slow

### ISSUE THREAD

**Issue by thekameleon** [smeighan/xLights#1478]
Its taking 30 to 45 seconds whenever I rename a model or group. I noticed it appeared to be working on a single thread.  I have been working on renaming my models for this upcoming season and I have been at it for about 3 hours now.

**Comment by AzGilrock** [comment]
Mine doesn't take that long.  Not much I can do with what you told us.

**Comment by thekameleon** [comment]
I'm running 3D 2019.12, I did notice it appears the naming process is single threaded and some disk activity. Nothing major though. The memory did seem to spike by about 1 GB for the xlights process... I can send you the rgb effects file. I can video capture the event. Let me know, what you would like from me.

**Comment by AzGilrock** [comment]
Yeah its kinda funny you expected the rename to be multi-threaded.  You should do a Package Log Files and post it here that's what we always ask for.  You never know which one of us will grab the files and test it.

**Comment by thekameleon** [comment]
I wouldn't call it funny. I'll get the package to you in the morning.

Sent from Yahoo Mail on Android 
 
  On Sun, Feb 17, 2019 at 23:15, Gil Jones<notifications@github.com> wrote:   
Yeah its kinda funny you expected the rename to be multi-threaded. You should do a Package Log Files and post it here that's what we always ask for. You never know which one of us will grab the files and test it.

**Comment by thekameleon** [comment]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/2876324/xLightsProblem.zip)

There you go

**Comment by DoctorWiz** [comment]
I have also noticed that renaming seems pretty slow, slower than pretty much any other operation.  And I have a very fast and powerful computer (dual Xeons, 48GB RAM, NVMe SSD).  I've also noticed the object being renamed flashes several times.  Perhaps the slowness is due to several unnecessary refreshes?

**Comment by AzGilrock** [comment]
In his case its easy to see in the log that whenever he renamed a model it reloaded his 5 house mesh models and for some reason it loads the whole set 5 times in a row.  I've just been busy on other things to have any time to dig into issues.

**Comment by thekameleon** [comment]
Thanks for looking into this Gil. 

Sent from Yahoo Mail on Android 
 
  On Thu, Apr 4, 2019 at 12:10, Gil Jones<notifications@github.com> wrote:   
In his case its easy to see in the log that whenever he renamed a model it reloaded his 5 house mesh models and for some reason it loads the whole set 5 times in a row. I've just been busy on other things to have any time to dig into issues.

**Comment by keithsw1111** [comment]
I think i have it fixed ... fingers crossed there are no bad side effects.
