### ISSUE TITLE
2019.12 App Crash with no error message

### ISSUE THREAD

**Issue by dennismccreery** [smeighan/xLights#1479]
Event log shows what looks like Heap Corruption:  

Faulting application name: xLights.exe, version: 0.0.0.0, time stamp: 0x5c67d796
Faulting module name: ntdll.dll, version: 10.0.17134.471, time stamp: 0x7e614c22
Exception code: 0xc0000374
Fault offset: 0x00000000000f47fb
Faulting process id: 0x197d0
Faulting application start time: 0x01d4c7167798d1f6
Faulting application path: C:\Program Files\xLights\xLights.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: e12a9a25-a2aa-424e-b8c8-73f8a8d15788
Faulting package full name: 
Faulting package-relative application ID:

So far I haven't been able to repro it.  I'm attempting (somewhat successfully) to import a .VIX 2.1 file from Vixen 3.5U4 into XLights.  I made sure the channels matched and created a blank sequence with the same audio.  At creation I successfully imported the .VIX file as a data layer (which shows in the sequencer and plays successfully).  I've been in the process of replacing some of the imported data layer stuff with XLights effects when the crashes started happening.

Attached please find the Sequence information as well as a dump of the XLights Logs.

[Wizards of Winter.zip](https://github.com/smeighan/xLights/files/2874034/Wizards.of.Winter.zip)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/2874036/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
This is not very useful. Either we need a way to reproduce it ... or we really cant help.

**Comment by dennismccreery** [comment]
Added zipped 
[Wizards of Winter.zip](https://github.com/smeighan/xLights/files/2876287/Wizards.of.Winter.zip)
.VIX file.

**Comment by dennismccreery** [comment]
Reproduced the crash.  Here's a link to the video from Zoom: 

https://1drv.ms/v/s!Aj3J0O38KlwJgoRv1m8Qs8RKFkpDZQ

Crash happened apparently after copy/pasting some "On" effects on top of some imported data from the .VIX file and then hitting "Render All".  You can see it about 2:55 onward.  After I hit "Render All" XLights locked up, and when I tried to scroll up it disappeared (crashed).  Here's the system Application Event Log entry at that time (Exception code: 0xc0000374 is heap corruption):

Faulting application name: xLights.exe, version: 0.0.0.0, time stamp: 0x5c67d796
Faulting module name: ntdll.dll, version: 10.0.17134.471, time stamp: 0x7e614c22
Exception code: 0xc0000374
Fault offset: 0x00000000000f47fb
Faulting process id: 0x8a68
Faulting application start time: 0x01d4c7b185eae6cd
Faulting application path: C:\Program Files\xLights\xLights.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 6518ecfd-5e03-424f-b5b5-8ecaf3b7f160
Faulting package full name: 
Faulting package-relative application ID:

**Comment by keithsw1111** [comment]
I pasted the on effect over 100 times and i cant get it to hang

**Comment by dennismccreery** [comment]
Clicking "Render All" after pasting seemed to trigger the fault for me.

**Comment by dennismccreery** [comment]
Tried to repro it on 2019.13 and it seems to work now.  I wonder if this fix affected it?

2019.13 February 21, 2019
...
   -- bug (dkulp)   Fix an occasional crash when loading a mesh

**Comment by AzGilrock** [comment]
Dan's fix was for loading a mesh over top of an existing mesh and that is not what you were doing.
