### ISSUE TITLE
Creating submodel in .12 adds multiple lines when it should only be one

### ISSUE THREAD

**Issue by SniperMunyShotz** [smeighan/xLights#1481]
![spinner selection](https://user-images.githubusercontent.com/22962428/52972545-41dc3f00-3389-11e9-8dc0-0787f7e9dc87.JPG)
![spinner results](https://user-images.githubusercontent.com/22962428/52972553-46085c80-3389-11e9-89e5-bff78be05a2e.JPG)

**Comment by computergeek1507** [comment]
Don't use the the Draw Model button. Double click the single row or row header if you on want one row populated.

**Comment by keithsw1111** [comment]
So should this be closed @computergeek1507
