### ISSUE TITLE
kaleidoscope effect crash

### ISSUE THREAD

**Issue by TKW1969** [smeighan/xLights#1483]
Put the new kaleidoscope effect on top of a pin wheel effect on a matrix. changed size fine but when I try and change the x or y location it crashes.
I have repeated this on different models. Here is a video.
https://vimeo.com/318780187

[xLights_dbgrpt-3144-20190221T081517.zip](https://github.com/smeighan/xLights/files/2889645/xLights_dbgrpt-3144-20190221T081517.zip)

**Comment by TKW1969** [comment]
I have tried different effects under the kaleidoscope effect and when trying to change the X or Y I'm crashing with them also.

**Comment by POPPIE1215** [comment]
Similar to TKW1969 above but it crashed when I increased the size.  I too tried different effects. There is one thing that worked however. When I tried to make a video it worked perfectly.

[xLights_dbgrpt-51644-20190221T080927.zip](https://github.com/smeighan/xLights/files/2889661/xLights_dbgrpt-51644-20190221T080927.zip)

**Comment by bstrickland1** [comment]
!st time using GitHub; don't know that I did this correctly or if you already get these files.

[xLights_dbgrpt-6980-20190221T143339.zip](https://github.com/smeighan/xLights/files/2891745/xLights_dbgrpt-6980-20190221T143339.zip)
[xLights_dbgrpt-3452-20190221T142326.zip](https://github.com/smeighan/xLights/files/2891746/xLights_dbgrpt-3452-20190221T142326.zip)

**Comment by bstrickland1** [comment]
Crash happened with .13 and trying new Kaleidescope effect with several other effects.

**Comment by POPPIE1215** [comment]
Thanks. I did get to see several effects before the crash. Cool stuff. Thanks again. 

Bill Arms
717-587-3850
_________________
Every day I beat my previous record of consecutive days I've stayed alive.


On Feb 21, 2019, at 6:45 PM, bstrickland1 <notifications@github.com> wrote:

Crash happened with .13 and trying new Kaleidescope effect with several other effects.

**Comment by keithsw1111** [comment]
I have this fixed

**Comment by POPPIE1215** [comment]
Thank you sir!

Bill Arms
717-587-3850
_________________
Every day I beat my previous record of consecutive days I've stayed alive.


On Feb 22, 2019, at 6:23 AM, Keith Westley <notifications@github.com> wrote:

I have this fixed
