### ISSUE TITLE
DMX Moving Head Grouping Acting Strange

### ISSUE THREAD

**Issue by Spankyty** [smeighan/xLights#1485]
It seems I cannot put my 2 DMX moving heads in a group. Only Pan works with both. In the second video, it shows that pan-x and pan are doing some weird things. they both are using Channel 1 for some reason? And only the right moving head is working correctly when I use them in a group. I can use both of them just fine without a group. I just would like a group to make it easier. I couldn't find any help besides this video: https://youtu.be/9FiuwY65eZg

Here's what's happening...
https://photos.app.goo.gl/bFuPMqpzWYxSMNYK8
https://photos.app.goo.gl/yjno2jtwbBBXEdQG6

XML (Updated):
[Wish Liszt.zip](https://github.com/smeighan/xLights/files/2891978/Wish.Liszt.zip)

**Comment by AzGilrock** [comment]
We can't look at anything with what you provided.  You need to do a package sequence under tools.

**Comment by Spankyty** [comment]
> We can't look at anything with what you provided. You need to do a package sequence under tools.
Sorry about that.

[Wish Liszt.zip](https://github.com/smeighan/xLights/files/2891980/Wish.Liszt.zip)

**Comment by AzGilrock** [comment]
Ok what you've found is the "Per Model Default" render style does not seem to be working correctly.  I tested in a really old version 2017.44 and channel 3 moves both heads.  In the current version it doesn't so the "Per Model Default" behavior must have changed.  Someone should fix that... :)

**Comment by twodoglights** [comment]
I am seeing the same thing.... as a group it acts totally strange  individually seems fine....

[ScreenCapture_3-2-2019 6.22.29 PM.zip](https://github.com/smeighan/xLights/files/2922704/ScreenCapture_3-2-2019.6.22.29.PM.zip)
