### ISSUE TITLE
Skulltronix no Torso in VSA import

### ISSUE THREAD

**Issue by tuppetsdad** [smeighan/xLights#1490]
Just trying out new Skulltronix unit by importing two of the sample VSA files they supply with the head. In the import definition its includes Pan, Tilt etc but no option to link to Torso. 

When I run the shows the tilt does not work, the pan has too high acceleration and the nod is very limited. 

Checked the settings and the ones in the model match the skulltronix config. 

I am assuming the max deg/sec setting for the pan is only applicable to shows written with XLights and not imported from VSA? Tried 30 but did not seem to make any changes to the movement.

**Comment by AzGilrock** [comment]
When someone sends me a free Torso I'll add it.  The torso servos really just need to be mapped to any generic servo since I'm not going to try to draw some special torso animation.  Those deg/sec are really to limit the animations to match reality so they don't mean anything.  Servos are going to move based on how the hardware reacts to the input commands.  If its not working why not contact Jerry he made money from the sale not us and I know he's run his stuff in xLights.  You can just drop down a second skull and use the servo definitions for the torso stuff.

**Comment by tuppetsdad** [comment]
Hi Gil

sorry to ask you a dumb question.

Thanks for supporting Skulltronics skulls much appreciated.

Regards
Bruce

**Comment by AzGilrock** [comment]
I never said it was a dumb question.  I think you can make the servos work with what's there but it might not be clean like you might be using a Pan servo of a second model to control the extra servos.  I also did not close the issue which means I was leaving the possibility of something being done later.

**Comment by tuppetsdad** [comment]
Hi Gil

I am the one who said it was a dumb question. Too much excitement after
getting the skull out of the box. Should have tested the skull first!

Will be using this skull on  a body with some other moving parts (arms
etc). My target is to have a talking skull interviewing a talking tree
(using faces)  explaining our Halloween set up so I no longer get those
eternal questions......

How long does it take to put up?
How many lights are there?
How much power does it use?
When does the show run?


Thanks Bruce

**Comment by AzGilrock** [comment]
I'm sure we can get it running for you.  Sometimes I'm replying when I'm barely awake.  One thing that might be worth it is to get the VSA program.  I think its about $80 and it was what everyone had been using to run the skulls.  It will run all the VSA files that Jerry gives you or you buy.  I bought it and used it to compare my xLights results with VSA and it can help let you know that its at least working and you can also go in and view channel assignments and click on effects and see the settings.  Sometimes some VSA files are mapped different than others and it caused me to need to import differently or I had to delete some of the unused tracks.

**Comment by tuppetsdad** [comment]
Thanks Gil will give VSA software a try.

Regards
Bruce
