### ISSUE TITLE
Star Model

### ISSUE THREAD

**Issue by SniperMunyShotz** [smeighan/xLights#1492]
Star model seems to be broken when doing a simple 5 point 5 node star.  It only shows 4 points and node 3 is missing in the l
![issuestar](https://user-images.githubusercontent.com/22962428/53372053-df9eb380-391f-11e9-8fab-fe6eb7728c56.JPG)
ayout.

**Comment by computergeek1507** [comment]
Node three and four are just on top of each other. I would use a 5 arm spinner with one node on each arm to model this better.

**Comment by SniperMunyShotz** [comment]
Thanks Scott, will let Jana know
