### ISSUE TITLE
Cube Model - String Settings

### ISSUE THREAD

**Issue by priemd** [smeighan/xLights#1493]
I have built an 8 x 8 x 8 cube and have not been able to accomplish the wiring layout that I used with the current string settings.

My cube was built where each layer is wired like a matrix model with zig zag each layer stacked on top of each other and all connected with the output of prior layer being the input of the next layer.

Here is the sample node layout for a 4 x 4 x 4 using the same wiring pattern:

Layer 1 (starts on back bottom left):

| 1 | 8 | 9 | 16 |
|-------|-------|-------|-------|
| __2__ | __7__ |__10__ |__15__ | 
| __3__ | __6__ |__11__ |__14__ | 
| __4__ | __5__ |__12__ |__13__ |

Layer 2 (stacks on top of layer 1, connect to output of layer 1 N16 on the back):

| 32 | 25 | 24 | 17 |
|-------|-------|-------|-------|
| __31__ | __26__ |__23__ |__18__ | 
| __30__ | __27__ |__22__ |__19__ | 
| __29__ | __28__ |__21__ |__20__ |

These layers would continue to stack on top of each other with the last node of each layer output to 1st node of the layer above it.

I was able to also create a custom 3d model which works perfectly for how my cube is built which I've attached.  I tried all combos of wiring options for 'cube' model >> export as custom model >> import and view 'model data' but none matched the layout I needed and created with custom 3d model.

Am I missing something in terms of the wiring or is this layout not supported with the current set of options?

[Cube.xmodel.zip](https://github.com/smeighan/xLights/files/2906906/Cube.xmodel.zip)

**Comment by keithsw1111** [comment]
Yeah ... its not a currently supported wiring model for the cube. You managed to avoid one of the 184 patterns we do support.

**Comment by AzGilrock** [comment]
Yeah the only reason I didn't drop the hammer about building something not supported is it did seem like the logical way anyone would wire up a cube if they had one long string of pixels.

**Comment by priemd** [comment]
Honestly I assumed that is what Start: Back/Bottom Left, Direction: Horizontal Front/Back, zigzag meant, but instead it seems to mean vertical slices from left to right.  I guess you might call the Direction option for what I've built 'Layered Front/Back' / 'Layered Left/Right'?

I put a lot of thought into the design as I wanted to keep the wire clutter between each layer to a minimum + also have the nodes all facing up so they are always viewable from all sides.  The only wire clutter between layers is the output/input between each layer and that is on the back side only.  Each layer can be taken out individually for repair/storage as well.

Might take a shot at a pull request if I can figure out the pattern for the transformations array in CubeModel ;) But the custom 3d model is also working just fine, keep up the good work fellas.

Here is a pic of it all finished.  
![cube](https://user-images.githubusercontent.com/2279532/53505672-53f16800-3a82-11e9-9d61-66a2bd02da03.jpg)

**Comment by AzGilrock** [comment]
Are those screen doors? :)

**Comment by priemd** [comment]
Yep pretty much!  They are build-your-own window screen frames from HD, 4' sections cut in half, was the strongest, thinnest and cheapest thing I could find to make perfect squares.  The mesh holding the lights is just that 1/2" plastic garden fencing, I think I saw Dan used the same material for his matrix, cut into individual strips and pulled as tight as I could get them across.

**Comment by keithsw1111** [comment]
You will have to create a custom 3D model and live with the less useful buffer options.

Folks should always check the xlights model first before building. It makes things so much easier.

Sent from my iPhone

On 28 Feb 2019, at 4:36 am, priemd <notifications@github.com<mailto:notifications@github.com>> wrote:


Yep pretty much! They are build-your-own window screen frames from HD, 4' sections cut in half, was the strongest, thinnest and cheapest thing I could find to make perfect squares. The mesh holding the lights is just that 1/2" plastic garden fencing, I think I saw Dan used the same material for his matrix, cut into individual strips and pulled as tight as I could get them across.

**Comment by priemd** [comment]
Totally understand your point, check the wiring diagram before you build something.

Just trying to give some feedback from someone who has actually built a cube, as I hadn’t seen one done since the model was released and through working out the design I originally built a few rows using the up/down or down/up pattern available in xLights with both bullet and square nodes and it sorta defeated the purpose of 3D...if you position them upright with all the wires in the way blocking the lights around and you lose a good inch of wire in terms of trying to space them out and it was even worse just hanging them letting them lay on their side any way they wanted to go as you couldn’t even see half the lights depending on viewing angle.

Appreciate the feedback and taking a look, I’m happy to stick with the custom 3D model with out the extra buffers for rendering the sides.

**Comment by AzGilrock** [comment]
Keith...I just looked at this model for the first time...  It sure looks like your options already give what he asked for.  Doesn't this work?

![image](https://user-images.githubusercontent.com/2024669/53677301-ea807d80-3c6a-11e9-8359-6d0baeb00068.png)

**Comment by AzGilrock** [comment]
I assume the first 16 squares overlay the second 16 squares for the layers.

**Comment by keithsw1111** [comment]
overlay down the z axis ... he wants overlaid up the y axis ... I only build x and z.

**Comment by AzGilrock** [comment]
Yeah I didn't realize he was stacking bottom to top.  Seems like something easy to provide...Guess I can look at it.

**Comment by priemd** [comment]
I believe I have the code worked out to add this wiring option.  Would 'Stacked Left/Right' and 'Stacked Front/Back' be an appropriate name for the 'Direction' property?
