### ISSUE TITLE
Single Strand + Per preview off by One?

### ISSUE THREAD

**Issue by ghormann** [smeighan/xLights#1495]
I'd like to use a Perview render stile for a group of line models that make up my house line.   However, I've noticed that the starting vertical segment is not rendered, however the end vertical segment is rendered.

I'm attaching a video of the bug as well as a test sequence. When "Default" render stile is used, but left and right are displayed, but when "Per Preview" used, only right is displayed.

Side note.  (Figured out after I packaged files up).  If I use "Per Preview and a 3D Camera that is in front of my house it works as expected.) 

[single_strand_render_bug.zip](https://github.com/smeighan/xLights/files/2922263/single_strand_render_bug.zip)

Video: https://youtu.be/-hGphDdfQno

xLights: 2019.15, 64 bit, Windows

**Comment by AzGilrock** [comment]
Going through older issues.  I just tried this out and didn't see a problem.
