### ISSUE TITLE
Enhancement Request: Easier Canvas Layers Selection

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#1497]
This is probably a limited user case scenario but when there are many layers involved, trying to select only a few layer numbers for the Off, Warp or Kaleidoscope effects can be cumbersome.  There is a potential to have to deselect a large number of layers.

My request is to either add a couple buttons, or right click menu options to the Layers selection window.  All of the layers are select by default currently.

Select All
Deselect All
Select Layers Only With Effects

<img width="488" alt="image" src="https://user-images.githubusercontent.com/12144876/53696652-d3d34700-3d8e-11e9-92f9-e997d8c78100.png">

**Comment by computergeek1507** [comment]
Added in a60c82c99bec6ce8e2b403e42ec5f1e11b219640 let me know if you run into any issues.

**Comment by kppankratz** [comment]
This works awesome and speeds the process of selecting the correct layers.  Thank you.

**Comment by computergeek1507** [comment]
Keith pointed out an issues that it will select layers with any effects over the whole sequence length not just the time interval of canvas type effect. I will try to update the code soon to fix this.
