### ISSUE TITLE
vamp plugins will not install on win7

### ISSUE THREAD

**Issue by bmft97** [smeighan/xLights#1499]
I tried to install the plugin to no avail, Clyde Lindsey (was at the Florida mini) tried installing everything (xlights, C++, Vamp plugin) fresh and still no success.
Windows 7 Home Premium 64-bit SP1
Intel Core i5 560M @ 2.67GHz
8.00GB Dual-Channel DDR3 @ 532MHz

**Comment by AzGilrock** [comment]
Have you searched on Google?  We are not the authors of the vamp plugins.

**Comment by keithsw1111** [comment]
when you say it wont install ... how do you know?

I need to see screen print of where it is installed along with xlights log AFTER you try to add a timing to a musical sequence.

**Comment by bmft97** [comment]
![tim](https://user-images.githubusercontent.com/48191013/53846666-d9da4b00-3f7b-11e9-90f7-88388c8c2632.JPG)
after install these are the only choices.
![vamp](https://user-images.githubusercontent.com/48191013/53846871-916f5d00-3f7c-11e9-95b0-29e9c47aa60a.JPG)
this is the notification that it is installed. i don't know where it is located on the hard drive. 
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/2933757/xLights_l4cpp.log)

**Comment by bmft97** [comment]
![location](https://user-images.githubusercontent.com/48191013/53848484-815a7c00-3f82-11e9-981a-140c7e9d7fe5.JPG)

**Comment by keithsw1111** [comment]
SO it installed just fine. Your problem is it is trying to load the 32 bit version. maybe delete vamp plugins from c:\program files (x86)\vamp plugins

**Comment by keithsw1111** [comment]
Actually your fundamental problem is VAMPPATH environment variable is set to "c:\program files (x86)\vamp plugins" ... this needs to be fixed on your end.

**Comment by bmft97** [comment]
This was the fix.
To change or delete the VAMP_PATH variable, go to 
    Computer -> Properties -> Advanced -> Environment Variables
This variable could be set as a user variable or system variable.

I chose to delete the VAMP_PATH variable and then install the 64-bit version of the VAMP plugin from the Xlights download.  Restart xLights and the VAMP plugin works!
