### ISSUE TITLE
Pressing UPDATE (F5) when Playback is running - Marker stops, Music continues

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#150]
See the attached screen shot.
When pressing the UPDATE button while playback was happening (I was updating Text in a Text field) I thought that the update would happen. However; in Sean's tutorial he describes that updates to the settings of an effect take place real time, so is the UPDATE/F5 Button necessary now?

However; When I pressed the UPDATE button, the progress bar at the top stopped but the music kept playing to the end.

![screen shot 2015-04-02 at 12 52 49 pm](https://cloud.githubusercontent.com/assets/10136122/6971120/7932db5e-d937-11e4-83d6-30ad4d5996b1.png)

**Comment by stevegiron** [comment]
Is this issue still valid as of  5-18-15?

**Comment by LightsOnHudson** [comment]
I will test and let you know

**Comment by LightsOnHudson** [comment]
No. this is Fixed!
