### ISSUE TITLE
Key bindings error

### ISSUE THREAD

**Issue by nickjohnson450** [smeighan/xLights#1500]
while rendering a sequence, xlights crashed and a crash report was created.  xLights was closing after crash report and a dialogue box appeared, noted I had a key bindings error and to package log files then submit for analysis.  Attached are the log files and crash report.  Please let me know if any more details information is needed.  Thanks Nick Johnson
[xLights_dbgrpt-99092-20190303T180407.zip](https://github.com/smeighan/xLights/files/2923896/xLights_dbgrpt-99092-20190303T180407.zip)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/2923898/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
To fix the keybindings error just close xlights and delete the keybindings file

**Comment by keithsw1111** [comment]
As for the crash i may have it fixed. you desperately need to run check sequence .... as you have an astonishing number of setup errors

**Comment by nickjohnson450** [comment]
Thanks Keith
I will delete keybindings file and see what's goin on with errors in check sequence.  
    On ‎Monday‎, ‎March‎ ‎4‎, ‎2019‎ ‎04‎:‎05‎:‎09‎ ‎AM‎ ‎CST, Keith Westley <notifications@github.com> wrote:  
 
 
As for the crash i may have it fixed. you desperately need to run check sequence .... as you have an astonishing number of setup errors

**Comment by AzGilrock** [comment]
This keybindings problem seems to be happening to a lot of people including me all the time.  I'm about to just add a menu option to automatically delete it.

**Comment by nickjohnson450** [comment]
Thanks Gil. At least I know how to fix the problem until you add the delete option

**Comment by nickjohnson450** [comment]
[xLights_dbgrpt-6992-20190305T105657.zip](https://github.com/smeighan/xLights/files/2932024/xLights_dbgrpt-6992-20190305T105657.zip)

Keith, Can you look at this again?  I have a new crash report.  I cleared all errors and warnings in check sequence.  I am running version 2019.15  I recreated the crash 3 times this morning.  It only happens while rendering "Little Drummer Boy" sequence only. The sequence renders for about 2 hours before crashing.  Let me know if this enough information 

Thanks, Nick

**Comment by keithsw1111** [comment]
Gil ... I have never seen a recently created keybindings error. Every single one dates back to last year. People just notice it now because I tell them about it.

**Comment by keithsw1111** [comment]
Why am i looking at the crash again ... I said I think i fixed it ... so unless you are building it from the source code then you are still running .15 which does NOT have the fix.

**Comment by nickjohnson450** [comment]
The problem that you noticed- would it happen on some sequences or all?  The issues I have only happens with 1 sequence, all of the others are good

 

    On Wednesday, March 6, 2019 3:26 AM, Keith Westley <notifications@github.com> wrote:
 

 Why am i looking at the crash again ... I said I think i fixed it ... so unless you are building it from the source code then you are still running .15 which does NOT have the fix.—

**Comment by keithsw1111** [comment]
yes.

**Comment by nickjohnson450** [comment]
Thanks Keith!!
