### ISSUE TITLE
Enhancement: Buffer respects camera angle in 3D (ViewPoint)

### ISSUE THREAD

**Issue by TimRoenicke** [smeighan/xLights#1502]
Provide the ability to render the buffer from a specific ViewPoint (camera).  

For example, when dividing the buffer in half, having the ability to specify which angle the "half" is taken from. 

Quick video if you need more context based on our needs and layout: https://www.youtube.com/watch?v=idwYIq9H5-4

**Comment by keithsw1111** [comment]
It is a fair ask ... just not sure how hard it will be to do. I would not expect any action on this quickly ... but equally I dont want to dismiss it.

**Comment by TimRoenicke** [comment]
Did a little bit of testing. It looks like @AzGilrock fixed this in .33. Thank you!
