### ISSUE TITLE
Adding Faces In The Face Definition Tab

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#1503]
When clicking on the top cell under "Eyes Open" in the "Face Definition" tab nothing happens (supposed to open file location of faces). If you click any of the other cells it works correctly. If clicking one of the other cells and then go back to the upper cell of "Eyes Open" it then works as it should.

![untitled-2](https://user-images.githubusercontent.com/13740582/53714119-18e49100-3e02-11e9-8df7-64b6490954c2.jpg)

**Comment by keithsw1111** [comment]
That is just the behaviour of the grid we use.

**Comment by AzGilrock** [comment]
Its been a long time so I forget how I did it but I'm pretty sure I fixed this quirky grid behavior when I created the VSA Import Dialog.
