### ISSUE TITLE
2019.16 crash while rendering 

### ISSUE THREAD

**Issue by nickjohnson450** [smeighan/xLights#1506]
[xLights_dbgrpt-13728-20190308T224019.zip](https://github.com/smeighan/xLights/files/2948351/xLights_dbgrpt-13728-20190308T224019.zip)

**Comment by ghormann** [comment]
@nickjohnson450 

The crash occurred in RenderCacheItem::AddFrame(RenderBuffer*).  Did you try clearing you render cache dir to see if that fixes it?   

I'm not an expert, but I'm thinking it was was processing "for KING &amp; COUNTRY - Little Drummer Boy   LIVE from Phoenix.mp4" at the time.  As that file wasn't included, it may be difficult for developers to debug.

**Comment by nickjohnson450** [comment]
I have not cleared render cache directory. I will try that and see if fixes the problem. Thanks

**Comment by keithsw1111** [comment]
I am pretty sure this is a memory issue due to the liquid effect consuming a lot of memory.

**Comment by keithsw1111** [comment]
Ok ... unless you have a huge amount of memory in your system this is always going to crash at some point. It literally requires 10s of gigabytes of RAM. I suggest you dont use per model with the liquid effect. I will try to reduce the odds of a crash but it is incredibly hard to do.

**Comment by keithsw1111** [comment]
Actually ... the problem is a memory cache issue ... too much memory is being used for the liquid effect frame saving. I have changed it now so it will abandon render caching if memory usage falls to less than 100MB.

**Comment by nickjohnson450** [comment]
Thanks Keith. The sequence was a purchased sequence. I will make adjustments to liquid effect and see how it reacts.   Thanks again for your time and effort with xLights
