### ISSUE TITLE
Linux: Model data for downloaded Models

### ISSUE THREAD

**Issue by AleXthePunK** [smeighan/xLights#1507]
Hello. Someone in the zoom chat had a problem with the linux version. When they click on model data, of a downloaded model, it crashes. Attached is the bug report.
[xLights_dbgrpt-10332-20190312T111356.zip](https://github.com/smeighan/xLights/files/2957494/xLights_dbgrpt-10332-20190312T111356.zip)

**Comment by computergeek1507** [comment]
Duplicate of #1456

**Comment by AleXthePunK** [comment]
Sorry, I read that thread as a new custom image. I didn't realize it was the model data. Thanks for looking.

**Comment by ghormann** [comment]
@keithsw1111  Patch has been applied. I believe we can close this one too.
