### ISSUE TITLE
Enhancement:  Ability to rotate multiple models 

### ISSUE THREAD

**Issue by skulltronix** [smeighan/xLights#1509]
Following on my last post about handles..  can we get the ability to move and rotate groups of models?

**Comment by AzGilrock** [comment]
You can already move groups.  I spent over a week trying to get rotate to work correctly and I gave up on that also.  Rotate is currently broken for individual models as well in my opinion.  If you rotate 90 around X and then rotate around Y the object rotates around Z.   That behavior totally messes up a group rotation where you really need object to rotate about the axis you are dragging.  To fix it requires using the rotation parameters we store as Euler angles, converting to rotation matrices, applying the rotation around the axis using matrix rotation, and then converting back to Euler angles to store in the parameter fields.  It runs into gimbal lock issues at the 90 degrees poles for the Y axis and starts to show errors near the poles.  I could not get the math to work right where the positions did not start to blow up as you rotate.  So good idea but I've wasted at least 40 hours and failed to get it working.

**Comment by skulltronix** [comment]
Thanks. I can’t even imagine the complexity of it. 

I’ve spent a similar amount of time getting 24 models organized around a core sphere and now I need to rotate the entire group.  :(. 

Jerry Jewell
Skulltronix.com
916 600 2295

**Comment by skulltronix** [comment]
Thank you!  Floating window?

It may be that I always seem to scale my models at 15-25 instead of a smaller number. 

Jerry Jewell
Skulltronix.com
916 600 2295

**Comment by AzGilrock** [comment]
Finally got this working in the new version 2019.73.  There's no text box to move the group with typing but select them all and the rotation handles will properly rotate the group now.
