### ISSUE TITLE
All Arches group not showing effects in model preview window

### ISSUE THREAD

**Issue by denniskuntz** [smeighan/xLights#1510]
Hopefully I'm not doing something wrong and wasting your time but my All Arches group is not showing anything in the model preview window. I am attaching a packaged sequence that demos this. The arches do show in the house preview window during playback. All other models and groups are showing in the model preview window. Not sure if it is related or a different issue or not but I have also tried adding effects to the all arches group from different camera views and the effects (butterfly for example) seem to render exactly the same. 
[demo.zip](https://github.com/smeighan/xLights/files/2959255/demo.zip)

**Comment by ghormann** [comment]
I can reproduce the problem in 2019.16 and suspect it is a bug.  All your arches are stacked up far to the left hand side.  I think the preview window is not calculating correctly the boundary of the model group when displaying and actually just rendering black space..  I noticed that if I did anything of the following, the group would start to render in the preview window. 

1) Add an element that had a very different X value to the group  (Example: Circle-3)
2) Move one of the arches (Example "Driveway Arch 1) to be in the Center of the house
3) Move the entire group of arches to be in the center of the house.
