### ISSUE TITLE
Conversion Log display not expanding

### ISSUE THREAD

**Issue by jakabo27** [smeighan/xLights#1513]
I think on the conversion view that the text area is set to a fixed size instead of resizing with the window.  It would be nice if then making the window bigger you could see more log entries at a time.  This happened after importing a LOR sequence 
[https://i.postimg.cc/YCn29t1R/pic1.png](url)

**Comment by computergeek1507** [comment]
fixed with 21d6cc71ad42f488cc6cbeebe9c57412640b7e51
