### ISSUE TITLE
Spiral Wraps min / max values

### ISSUE THREAD

**Issue by leelindquist** [smeighan/xLights#1520]
Is there any particular reason why the spiral wraps are limited to +/- 20 currently? I was testing some different arrangements and models for a big tree I'd like to pixelate, and I think a spiral model might look the best, but with the size that I'm wanting to build I would need something like 125 spiral wraps to make it look right.

I changed those min / max in my local copy, recompiled and it seems to work just fine. Is that something that we could look at changing for the release versions?

**Comment by keithsw1111** [comment]
Changing the range of sliders is a risky operation and thus has been largely avoided for a long time despite the acknowledged need to do so with ever increasing pixel density of some props (particularly matrices).
While changing the slider itself is pretty trivial and new sequences work perfectly well ... it is previously created sequences where problems can arise ... particularly where value curves are involved.
A change was made about 18 months ago which tried to address this and lay the groundwork for a future where changes like this can be made but it had issues. These issues have been partially addressed at best and thus it remains likely that some users will have unplanned and undesirable side effects from such a change. Consequently I am not in a hurry to change the range of any sliders.

**Comment by dkulp** [comment]
I'm also concerned if that's really what you want...  A single strand wrapped 125 times around would be a VERY VERY long strand...  My gut feeling would be to do 16 strands with 10 wraps or something that would be more representative of how it would actually be wired.   I also don't think most effects would look very good on a spiral mega tree.   Text and images would certainly not work very well.   Gut feeling is almost nothing would look "right".

**Comment by AzGilrock** [comment]
The biggest motivation to not put huge numbers in there from the start was because it makes using the slider useless because there are a finite number of pixels representing the slider.  If you have a slider that goes 0-1000 there are usually numbers you cannot hit while dragging the slider.  If most of the time you use 0-5 then you end up having to type in the text box.

**Comment by leelindquist** [comment]
Thanks for the feedback. A few points:

Unless I'm missing something, the property I'm referring to, "Spiral Wraps" is not a slider. It's a box that can be typed in, with up / down arrows beside it.

Defining the tree model as a spiral with a single long strand doesn't seem to cause any issues with any effects I have tried. Text looks fine. Granted, it wouldn't actually be wired as a single long string of pixels on a single port, it would be broken up onto multiple outputs, but from an installation standpoint it could be built up with rings or bands around the tree that were just offset vertically at the end as they stepped up on top of the previous ring.

In this video example I modeled 2 different large trees, both with 9000 pixels. One was with a bunch of vertical strands, and the other was with a single spiral wrapped 125 times. Personally, I think the spiral looks a lot more organic, and is exactly the look I am going for in the physical model.

[https://www.youtube.com/watch?v=R7bXch3zojU](url)

**Comment by leelindquist** [comment]
Now that I'm rereading Keith's comment, I believe it's clear to me where the disconnect is. I'm referring to the "Spiral Wraps" property of the Tree Model, not of the Spirals effect.

**Comment by AzGilrock** [comment]
Yep you're right.  That's what happens when I try to answer from work and can't see the program.  But my comment would apply to anything with a slider.   For those we try to make them as big as we think is needed but don't go overboard and lose resolution.

**Comment by leelindquist** [comment]
I've played with the single long spiral model some more this morning, and Dan's right. There are some effects that don't look as expected. I hadn't put much thought into the shape of the buffers for a typical string tree, and how effects (especially the spirals effect) are transferred onto the model. I'll dig into that a bit more before posing any more questions.
