### ISSUE TITLE
Enhancement: Allow a group to be broken up to multiple ports for Falcon ""upload to controller"" 

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1523]
I have a group of 8 arches on a falcon receiver board off an F48. I do the following in my setup wiring wise 

arches 1 and 2 - Receiver board port1
arches 3 and 4 - Receiver board port2
arches 5 and 6 - Receiver board port3
arches 7 and 8 - Receiver board port4

In Xlights I have "arches" set to "8" on controller port 1 but theres no way to tell Xlights that the rest of the arches from 3-8 are in controller port 2,3 and 4 so when we upload to the F48 it lays all 400 pixels on port 1 and we would manually have to configure 2,3,4 and edit port 1 so it all matches

Not a big deal at all but would be easier if theres a way (maybe by the "individual channels" area in xlights to add a port area there too?

thanks guys!
![Screen Shot 2019-04-01 at 10 19 03 AM](https://user-images.githubusercontent.com/40632971/55334641-a0f0a180-5467-11e9-9cc8-16d758cdee64.png)
![Screen Shot 2019-04-01 at 10 18 02 AM](https://user-images.githubusercontent.com/40632971/55334642-a0f0a180-5467-11e9-9051-0ad5b6ebeb8a.png)

**Comment by keithsw1111** [comment]
I dont think we will implement this change. If you want to upload create 4 pairs as the complexity it would introduce is not a good tradeoff for the benefit.

**Comment by bchiaino** [comment]
thats exactly what I did Keith, Created 4 pairs and remapped too old. I forgot I even had this open still or I would've closed myself. thanks!
