### ISSUE TITLE
Enhancement: Model and / or House Preview scrub along with audio?

### ISSUE THREAD

**Issue by leelindquist** [smeighan/xLights#1525]
When scrubbing the audio waveform slowly back and forth (holding command key and selecting over the waveform) it would be handy to have the model and / or house previews displayed in sync with the audio. It would be particularly nice for checking lyric tracks with the face effect.

**Comment by Clyde-L** [comment]
Lee, I like to use the double-click on the label track to check the lyrics as I space them out.  xLights will play the selected timing for that label.  Also, there is an audio speed for 3/4, 1/2, 1/4-time to slow down help with lyrics.
