### ISSUE TITLE
3d Custom Model rotation

### ISSUE THREAD

**Issue by SniperMunyShotz** [smeighan/xLights#1528]
I imported the boscoyo 96" snowflake and I am not able to rotate the model to lay on the roof.  The red and the blue rotations bar do the same thing.

**Comment by SniperMunyShotz** [comment]
Okay so it seems if you reset all the positions to 0, then do the rotation it works.

**Comment by keithsw1111** [comment]
Yeah this is a known problem ... but exceptionally difficult to solve.

**Comment by AzGilrock** [comment]
I know it been awhile but I just tried this and rotation seemed fine.  Sure if you do a bunch of rotations it can get strange but when you import the model the rotations are already 0 by default so you had to have messed with it to be having trouble.
