### ISSUE TITLE
DMX model enhancement

### ISSUE THREAD

**Issue by darylc** [smeighan/xLights#1529]
My DMX moving heads have 2 channels for each of Red, Green, Blue, White.  The DMX model only accepts a single channel so only half of it's LEDs light up for each color.  It would be nice to be able to accept multiple channels per colour.

![image](https://user-images.githubusercontent.com/7511887/55528963-63e61280-56e6-11e9-8dfb-b4c54f81ad80.png)

**Comment by keithsw1111** [comment]
Yeah ... there are pretty much an infinite array of channel layouts for DMX models ... we cant support them all. So get creative. Create 2 models (same channel range) each setting colours to one of the channels ... then put them in a group and sequence the group.

**Comment by AzGilrock** [comment]
Yeah this doesn't seem generic enough to implement.  Each already that supports the DMX model would need to be modified to support multiple channels and the code would be kinda ugly.  I consider the DMX model to be useful for basic DMX devices and for the irregular ones users need to set channels manually.
