### ISSUE TITLE
Panel Layout/Perspectives - not allowing saving without sequence active.

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#153]
Using OSX 4.0.10

I found putting a few panels to the right side of the screen would make it easier to work in the tool.

I moved various panels to the right, and there only remained the Perspectives panel in the left. It was all greyed out. 
It was not until I started a new sequence that the Perspectives panel was enabled.

I thought that the panels 'remembered' their last placement even without this feature.

Once I had the sequence built, I was able to Add a new perspecitve and in this case call it ' Right Side '

I closed Xlights, and Re-opened

All the panels were back to their default left side location. 

The Perspectives box did have my 'Right Side' option in it, but it was 'greyed out'

I just randomly opened a sequence, and the Perspectives box opened. 

I double clicked on my 'right side' Perspective and the panels just remained in their same location. Nothing changed.

See Screen shot with Perspectives ' greyed out '

![screen shot 2015-04-02 at 1 17 02 pm](https://cloud.githubusercontent.com/assets/10136122/6971681/6a3206ee-d93b-11e4-8e0f-eed76f050798.png)

**Comment by stevegiron** [comment]
As you noted, perspectives functionality is active when a sequence is opened.

**Comment by LightsOnHudson** [comment]
Yes, but also when selecting the perspective they did not go to the place where they were when I had saved the perspective. Is that fixed?
