### ISSUE TITLE
xLights Not Responding WIN10

### ISSUE THREAD

**Issue by Tinkerman61** [smeighan/xLights#1530]
I recently upgraded my PC and now when I try to run xLights, it locks up every time I click on Layout or Sequencer (Not Responding).  I tried different show directories and uninstalling and re-installing.  xLights was running fine on my previous system (WIN7).  
I am now running the following: 
Asus - ROG STRIX X470-F Gaming ATX AM4 Motherboard
XFX - Radeon RX 580 8 GB GTS XXX ED Video Card
AMD - Ryzen 5 2600X 3.6 GHz 6-Core Processor
G.Skill - Flare X Series 16 GB (2 x 8 GB) DDR4-3200 Memory.
WIN10 64Bit

Any ideas what could be causing this?  All other programs I run on this PC work fine.  Thanks!

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3041762/xLightsProblem.zip)

[xLights Windows Event Error.zip](https://github.com/smeighan/xLights/files/3041777/xLights.Windows.Event.Error.zip)

**Comment by keithsw1111** [comment]
London to a brick its a video card driver issue. Ensure you are running the absolute latest from your video card vendor ... not from windows update.

**Comment by Tinkerman61** [comment]
Keith,  I just updated the video card driver to the latest version from the manufacturer and I am still having the same issue with xLights.
Bob

**Comment by keithsw1111** [comment]
Maybe try setting the open gl version to a lower version and package logs again

**Comment by Tinkerman61** [comment]
I tried the different OpenGL settings in xLights with no difference.
For some reason version 20 started working for a week or two up until last week, then it stopped.  I installed v21 and no difference.
I recently updated all the video and motherboard drivers and Bios to the current versions and still having the Not Responding issue with xLights.

[xLightsProblem1.zip](https://github.com/smeighan/xLights/files/3100830/xLightsProblem1.zip)
[xLights Windows Event Error 1.zip]

(https://github.com/smeighan/xLights/files/3100832/xLights.Windows.Event.Error.1.zip)

**Comment by Tinkerman61** [comment]
[xLights Windows Event Error 1.zip](https://github.com/smeighan/xLights/files/3100833/xLights.Windows.Event.Error.1.zip)

**Comment by keithsw1111** [comment]
I dont see any evidence it has been recently working. And I dont see any change ... it is still crashing on OpenGL create which is typically a video related issue.
Try removing all external monitors. Resetting perspectives and see if it still crashes.

**Comment by Tinkerman61** [comment]
Thank you Keith.  I will try those.
This is a desktop using 2 monitors.
Where in the logs are you seeing the OpenGL error for my own troubleshooting?
Thanks!

**Comment by keithsw1111** [comment]
Its not what I am seeing ... its what i am not seeing.

The best way to resolve issues like this is on zoom ... with possibly a series of special builds that progressively isolate the problem.

**Comment by keithsw1111** [comment]
Does this still need to be open

**Comment by Tinkerman61** [comment]
Keith,

I have tried some different troubleshooting and no change. I have not had a
chance to get on zoom yet to try to solve this. You can close it if you
wish. Thanks!

**Comment by keithsw1111** [comment]
If the problem persists then i will leave it open

**Comment by AJ240-Aus** [comment]
keith, I am having a similar issue. Very similar hardware as well. MSI X470 Carbon Pro, AMD Ryzen 7 2700x, 32g Corsair ram, Gigabyte GX 1660 ti video card. From what I have been able to diagnose so far, there is something wrong with OpenGL.
I have all the latest drivers installed.  Currently running V.33 Xlights.
It takes over 30secs to load Xlights (6secs on a core I7 laptop). If I look in Task manager I can see that GPU-0 keeps toggling on and off every-time I try and do something like select an effect in a sequence, in between the mouse click and the final recovery, Xlights hangs or shows not responding.
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/3379742/xLights_l4cpp.log)
Looking at the log file there is a definite time pause.
2019-07-11 09:38:04,896 13520 log_base [DEBUG]                     Creating GL Canvas for Preview
2019-07-11 09:38:04,904 13520 log_base [DEBUG]         Effects.
2019-07-11 09:38:04,923 13520 log_base [DEBUG]         Effect settings.
2019-07-11 09:38:20,983 13520 log_base [DEBUG]                     Creating GL Canvas for panel
2019-07-11 09:38:36,912 13520 log_base [DEBUG]         Effect assist.
2019-07-11 09:38:36,914 13520 log_base [DEBUG]         Color.
2019-07-11 09:38:37,338 13520 log_base [DEBUG]         Timing.
2019-07-11 09:38:39,055 13520 log_base [DEBUG]         Buffer.
2019-07-11 09:38:40,308 13520 log_base [DEBUG]         Perspective.
2019-07-11 09:38:40,349 13520 log_base [DEBUG]         Effect.
2019-07-11 09:38:40,665 13520 log_base [DEBUG]         Jukebox.
2019-07-11 09:38:40,915 13520 log_base [DEBUG]         Display Elements.

Is there any other information you would like from me ? I really need to get this sorted as it is a real pain trying sequence when it runs this bad. I set this PC up specifically for sequencing and it runs worse than my 5 year old laptop. It has to be either hardware or a software setting local to the new PC.

**Comment by Tinkerman61** [comment]
Any update on this issue?
Thanks!

**Comment by keithsw1111** [comment]
No one is working on this issue as we don't have anything to work on.
Every look at this so far has pointed at a video card issue. Without any evidence to the contrary we cant progress.

It really comes down to you progressing it by trying a few things.

Try removing complexity ... open a new show folder does it still crash?
No then maybe import some models from the old layout ... does one in particular trigger issues.
Try removing monitors ... does it work better with just the one.

Lots of things you can try.

**Comment by keithsw1111** [comment]
Closing due to lack of any follow up information
