### ISSUE TITLE
Arches RotateX keeps resetting to 0

### ISSUE THREAD

**Issue by DoctorWiz** [smeighan/xLights#1531]
The RotateX parameter of Arches keeps resetting to zero (not being saved??), when you change some other parameters or when you save/exit and come back.
**Steps to Reproduce:**

1. Draw some arches.
2. Change RotateX parameter to 180 so you have swags instead or arches.
3. Change the name, or most any other parameter (other than X, Y, Z).
4. Swags will flip over to become arches again and RotateX parameter is reset to 0.

I can readily reproduce this in a new blank show folder using Linux version 2019.19 64-bit.
(I can submit files if needed, but since I can so easily reproduce it, I didn't feel that was necessary.)

**Comment by AzGilrock** [comment]
Yep looks like you must be the first person to try to rotate an arch around the X axis.  The TwoPointScreenLocation models are not reading or writing the RotateX parameter to XML.  Its an easy fix.  I'll try to get to it if no one else fixes it sooner.

**Comment by DoctorWiz** [comment]
A simple workaround is to set the 'Arch Tilt' parameter to 180 instead.  That appears to make the 'RotateX' parameter redundant (?)

**Comment by AzGilrock** [comment]
Yeah we could probably delete that Arch Tilt but I'd need to research deeper.

**Comment by keithsw1111** [comment]
I believe this is fixed.
