### ISSUE TITLE
Bulk Edit with Mac and Windows path not working....

### ISSUE THREAD

**Issue by bwhite80** [smeighan/xLights#1532]

**Comment by bwhite80** [comment]
Bulk edit insert Mac path without replacing Windows path........

**Comment by darylerwin** [comment]
![2019-04-09 21_27_50-Start](https://user-images.githubusercontent.com/25016569/55845088-68f3f900-5b0e-11e9-960b-a438fd725774.png)

**Comment by darylerwin** [comment]
Took an imported sequence from g-drive and went to bulk edit the paths. The result was the above. It appears as though it just prepended the new mac path rather then replacing the path.

**Comment by keithsw1111** [comment]
I need more information and sample sequences. Was the source or the target windows or mac. Attach the sequence after the import but before the bulk edit. Include a link to the sequence you were importing.

**Comment by darylerwin** [comment]
Hi Keith.. Barry and I were on Zoom with this. Perhaps he can attach the exact sequence but it was the Trolls September from the gdrive and importing from Windows to his Mac.

**Comment by darylerwin** [comment]
https://drive.google.com/open?id=122AmdeUOkFWGnBud9t_QBPyjeA9KUL0D

**Comment by keithsw1111** [comment]
I imported logans sequence on windows (ie with his OSX paths) and then bulk edited and replaced with a windows path and it worked fine ... can you make a video of it not working so i can see what you are doing different.

**Comment by AleXthePunK** [comment]
Attached is a recording Keith. You are reproducing this backwards. The problem is bulk edit path on a mac, not a PC. When  you bulk edit, it adds the MAC path to the location, but doesn't remove the pc.

I hope this helps
[recording.zip](https://github.com/smeighan/xLights/files/3084167/recording.zip)

**Comment by keithsw1111** [comment]
I cant help with that.

**Comment by bwhite80** [comment]
Thanks

**Comment by dkulp** [comment]
I’ll take a look next week when I’m back from vacation. 

Daniel Kulp
