### ISSUE TITLE
Shockwave, Galaxy and per model rendering problems

### ISSUE THREAD

**Issue by BMurray-HHH** [smeighan/xLights#1534]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3075524/xLightsProblem.zip)
The Shockwave and Galaxy effect are not working correctly. No matter how wide I make the radius or width after setting the X/Y where I want it it does not render to the "whole" house as per my group. It will only expand out a little bit. I would estimate it only expands out to a 1/3 percentage wise instead of widening out over the "whole display". This is a "purchased" sequence through "xTreme Sequences". The effects are set and work correctly through the available files sent over with the sequence on his setup. I have already reached out to Ron Howard and he attempted to correct or find the issue for about 2 hours but could not and suggested I reach out to the developers. Also for the "Per Model Per preview" again it does not seem to render correctly. The render will correctly work on several models but then render over several as a "group" instead of "per model". I am running the latest xLights 2019.20 Windows 64bit. Thank You!

**Comment by AzGilrock** [comment]
Ok I tried your show directory.  Created a new sequence and dropped a Shockwave effect on the "House - ENTIRE DISPLAY Group" model.  Set the Radius2 to 250 and the Shockwave sweeps across the entire display.   So I'm not seeing a problem.  Are you sure the effect has completed rendering?  Click render all and wait for it to finish.

**Comment by BMurray-HHH** [comment]
I believe it was due to the Render Cache. Once I deleted it and re-did the sequence render all was good. I remembered having issues with the render cache with lasts years sequences as well and had to delete them all and re render to correct all the errors that were occuring with those sequences.
