### ISSUE TITLE
Enh: Can sorting be added to the Controller Connection in Layout tab

### ISSUE THREAD

**Issue by darylerwin** [smeighan/xLights#1535]
Can be useful to find ports not used when assigning ports.

**Comment by keithsw1111** [comment]
i dont see how that would be useful. all port 1s across all my controllers together?

**Comment by keithsw1111** [comment]
Closing unless you have an answer.

**Comment by darylerwin** [comment]
Cant disagree with your point but it would work nice on my F48 :-)
