### ISSUE TITLE
Issue - Arches Group with alternative wiring locations incorrectly rendering with single strand effect  

### ISSUE THREAD

**Issue by LawrenceDriveLights** [smeighan/xLights#1536]
Hi xLights team, I am having a issue with the way my group of arches are rendering with the single strand effect when it is applied to the group of arches which have different wiring staring locations (some with blue starting location some with green starting location) when using the Per Model Per Preview render style with the Chase type "Bounce from Left" or "Bounce from Right" applied.

I also tried rolling back to pre 2019 xLights release and the Arches Group rendered as I wanted as in all in the same direction ie bouncing all left to right.

Here is a video of me trying to explain: https://vimeo.com/331496524https://vimeo.com/331496524
I packaged the basic layout and sequence here:https://vimeo.com/331496524

Thanks guys and I appreciate all the work you are doing with xLights

**Comment by keithsw1111** [comment]
Is this now fixed?

**Comment by LawrenceDriveLights** [comment]
Hi Keith, I just checked using version 2019.38 and it appears to now be
fixed

👍
Thanks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
