### ISSUE TITLE
Assigning Pixels to Phonemes

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#1538]
I placed my pixels into a Custom Model for a Singing Christmas Tree.
When I go to assign the pixels to their corresponding phonemes, some pixels are no longer in the custom model (it has deleted pixels 81,82,and 83 from the left hand side of the mouth and renumbered all of the eye pixels).
This is happening around cell A20 thru A22 of the lower picture..

see attached pic.
![Phoneme Bug](https://user-images.githubusercontent.com/13740582/56637655-01b36a00-6621-11e9-8019-84fd7c4568ec.jpg)

**Comment by keithsw1111** [comment]
There is not enough information here to know what is going on.

**Comment by jimswinder** [comment]
What other info do you need?



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by computergeek1507** [comment]
Run check sequence and verify your custom model is not skipping node numbers.

**Comment by computergeek1507** [comment]
Also export the custom model as a xmodel file and attach the file to this issue.

**Comment by computergeek1507** [comment]
Based on the pictures, you have no 72, 73, and 74 nodes which is causing the re-number issue.

**Comment by jimswinder** [comment]
Ok...ill check that when i get home...figured it was operator error...thanks!



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by jimswinder** [comment]
Thanks Scott...that was the problem...thought I had double checked that I had them all...sorry for the inconvenience...

________________________________
