### ISSUE TITLE
Generate Custom Model is not working as expected.

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#1539]
Running 2019.20 Generate Custom Model is having trouble processing a model video. I see nothing wrong with the video, it was made per the instructions and when it starts it looks correct however it is reporting that it 'Looks Wrong'.

The video file can be downloaded here:
https://www.dropbox.com/s/iz7soz9n162v34k/20190423213021.MP4?dl=0

**Comment by AJ240-Aus** [comment]
I don't think this process will accept a 3D model. It cannot process **depth** from the video. It was designed for flat 2D custom models.
