### ISSUE TITLE
OSX version 2019.22 Crashing

### ISSUE THREAD

**Issue by tmestemacher** [smeighan/xLights#1540]
sequence created with OSX version 2019.22.  Closed application.  Opened application and tried to continue working on sequence but, now loading the fseq file causes the xLights to crash… everytime

**Comment by tmestemacher** [comment]
[xLights_dbgrpt-2004-20190426T185815.zip](https://github.com/smeighan/xLights/files/3123310/xLights_dbgrpt-2004-20190426T185815.zip)

**Comment by keithsw1111** [comment]
Dan has made some changes and added some logging so please try again when .23 comes out. In the meantime if you need to open the sequence delete the fseq file.

**Comment by keithsw1111** [comment]
I suggest you delete the FSEQ File. Upgrade to .23. Change the FSEQ file format to V1 ... until .24 comes out.

**Comment by keithsw1111** [comment]
We believe this is fixed in .24.
