### ISSUE TITLE
Visualise controller splits megatree across multiple pixel ports

### ISSUE THREAD

**Issue by AJ240-Aus** [smeighan/xLights#1542]
Megatree created with 21 strands of 91 nodes using universes 5-16. This is outputted on ports 3 and 4 of a Falcon 16v3. Strings 1-11 on output 3 Strings 12-21 on output 4.
When selecting visualise controller, it spreads each strand across individual pixel outputs.
How do I get it to correctly show the megatree across outputs 3 and 4 only.
Screen shots attached.
![2019-04-27 14_56_19-xLights (Ver 2019 22 64bit) April 21, 2019](https://user-images.githubusercontent.com/44983381/56844970-e7b5a800-68fc-11e9-935d-60cdf88a70c5.png)
![2019-04-27 14_56_51-xLights (Ver 2019 22 64bit) April 21, 2019](https://user-images.githubusercontent.com/44983381/56844971-e7b5a800-68fc-11e9-9186-da3adb4e4bff.png)
![2019-04-27 14_57_46-xLights (Ver 2019 22 64bit) April 21, 2019](https://user-images.githubusercontent.com/44983381/56844972-e7b5a800-68fc-11e9-8a82-f94dfb6effee.png)

**Comment by computergeek1507** [comment]
The "# of Strings" is the physical number of connections to the controller. So in your case two. You would then set the "Stands/String" to the number of zig-zags. But since you are using a odd number of string this will not work with the xLights controller upload function or visualiser. To get it to work you have to change your model to 20 stands and set "Stands/String" to 10, "# of Strings" to 2, and "Nodes/String" to 991. If not you will have to setup your controller manually outside xLights and not use this feature.

**Comment by dkulp** [comment]
The odd number of strands per string should work... if not, that would be a bug.   Thus, it should be 2 stings, 11 strands per string, 1001 nodes per string.

**Comment by computergeek1507** [comment]
Based on original post he wanted 21 strands total and that cannot be divided by two, so he needs to add one for 22 total or remove one for 20 total. The 22 stands for a 21 stand tree would work it would just render pixels that don't exist.

**Comment by AJ240-Aus** [comment]
Thanks guys. That fixes the visualiser but then screws up my layout.
With 21 strings I get the correct layout of my strings on screen (Matches physical layout), but with 2 strings I get a horizontal layout instead of vertical. See attached.
![21 strings](https://user-images.githubusercontent.com/44983381/56845766-9c55c680-6909-11e9-8e04-a8867b82ee50.png)
![21 string tree ](https://user-images.githubusercontent.com/44983381/56845767-9c55c680-6909-11e9-85cb-70332e6f805d.png)
![2 strings](https://user-images.githubusercontent.com/44983381/56845768-9cee5d00-6909-11e9-9f5d-3752e1a3d2a0.png)
![2 strings tree](https://user-images.githubusercontent.com/44983381/56845769-9cee5d00-6909-11e9-9b79-0b944f13fcd7.png)

**Comment by computergeek1507** [comment]
10 strands per string

**Comment by AJ240-Aus** [comment]
Fixed it. My fault.
Stands per string should have been 10. 2 strings of 10 = 20 strings. Duh..
![stands per string](https://user-images.githubusercontent.com/44983381/56845918-bc868500-690b-11e9-944f-68651f163831.png)

**Comment by AJ240-Aus** [comment]
Layout issue resolved. Visualiser works as intended.

**Comment by corydorning** [comment]
@dkulp and @computergeek1507 How would i accomplish something similar for a matrix? I have 1,050 pixel matrix that is 35 pixels wide by 30 pixels tall. Port 15 on my falcon is a single strand that contains 680 of the 1,050 pixels, to use the ports full capacity. This results in...

Port 15: Row 1-19 + 15 pixels in the 20th row (19 rows x 35 pixels = 665 + 15 pixels in row 20 = 680 pixels)
Port 16: 20 pixels in the  20th row, row 21-30 (20 pixels in row 20 + 10 rows x 35 pixels = 370 pixels)

**Comment by computergeek1507** [comment]
You have to create a custom model if you want to use unbalanced string lengths

**Comment by corydorning** [comment]
would i create a custom model for each port?

**Comment by computergeek1507** [comment]
The easiest way, in my opinion. First create a matrix, set the string length to 1050. Set the strings per strand to 30. Then export the matrix as a custom model. Import that custom model and set the string count to 2, check indiv start nodes and set string2 to 681

**Comment by corydorning** [comment]
just to clarify, the initial matrix would be:

# strings: 1
nodes/string: 1050
strands/string: 30

**Comment by computergeek1507** [comment]
> just to clarify, the initial matrix would be:
> 
> ```
> # strings: 1
> nodes/string: 1050
> strands/string: 30
> ```

Yes

**Comment by corydorning** [comment]
ok cool. have that setup and looks like that will work great! Much appreciated!
