### ISSUE TITLE
2019.22 Crashing

### ISSUE THREAD

**Issue by ericg2000** [smeighan/xLights#1543]
OSX 2019.22 crashing.  it's been crashing the last few versions.  when i open the program it crashes.  i've deleted fseq files, tried again, after rendering, it still crashes.  
[xLights_dbgrpt-1259-20190427T113741.zip](https://github.com/smeighan/xLights/files/3124099/xLights_dbgrpt-1259-20190427T113741.zip)

**Comment by keithsw1111** [comment]
Can you post the xml and fseq files for the song.

**Comment by ericg2000** [comment]
here you go... these two are giving me problems.  the two with rev 1 in the name are sequences that have imported effects

**Comment by ericg2000** [comment]
[git hub uploads.zip](https://github.com/smeighan/xLights/files/3124275/git.hub.uploads.zip)

**Comment by keithsw1111** [comment]
There are no fseq files in that zip file

**Comment by ericg2000** [comment]
sorry here you go
[fseq.zip](https://github.com/smeighan/xLights/files/3124316/fseq.zip)

**Comment by keithsw1111** [comment]
I suggest you delete the FSEQ file upgrade to .23 and switch to use the V1 file until .24 comes out.

**Comment by keithsw1111** [comment]
We believe this is fixed in .24.
