### ISSUE TITLE
Feature Request:  Dark Mode

### ISSUE THREAD

**Issue by jakabo27** [smeighan/xLights#1547]
It would be great to have a "dark mode" for Windows/Linux within xLights.  Make the white background into a nice dark gray, text either white or a light gray.

**Comment by extremeskillz** [comment]
I second that.

**Comment by keithsw1111** [comment]
This will happen when wxWidgets/Windows makes dark mode a manageable option on Windows ... not before. As such there is little point in holding a ticket open in our bug tracker.

**Comment by dkulp** [comment]
This is not something that can be done without either completely changing from wxWidgets to a different library (major major undertaking) or major changes within wxWidgets.   wxWidgets uses the native controls from the OS for pretty much everything whenever possible so until Windows provides a dark mode for the native controls, this is not something that is likely to happen.

On the Mac, Mojave does provide dark mode native controls and wxWidgets can take advantage of those.    I think the gtk stuff on Linux can also be themed and wxWidgets would pick it up.   Thus, it works on OSX, possibly works on Linux in some set of use cases (not sure), but Windows would require work from Microsoft and wxWidgets.
