### ISSUE TITLE
Enhancement: Single Strand Triggered by Timing Event

### ISSUE THREAD

**Issue by MCStoff** [smeighan/xLights#1548]
Current procedure when applying the single strand effect to arches and other display elements requires counting beats and matching the effect cycles to the number of beats.  When the number of cycles is maximized, another single strand effect must be added.  This enhancement would allow the user to identify a Timing Track that would trigger the effect, much like the VU Meter Timing Event triggers.  This would eliminate having to match the number of cycles to the beats and would reduce the number of times the single strand effect must be added.

**Comment by keithsw1111** [comment]
So not the first time i have seen this asked for. Adding to single strand would be difficult because of how that effect works but i added some variants to timing event sweep which should deal with some common scenarios.
