### ISSUE TITLE
Enhancement: Ability to type in duration of effect in Timing/Layer Window

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#155]
Since the effects do not have to be kept within the timing marks, the ability to enter in an effect time would be beneficial.

In the screen shot example, I may want the effect (fireworks) to run to the end of the show. So the ability to enter in the remaining 18 seconds in a timing box would be great.

ADDITIONALLY: If the current position of the effect plus the 'desired duration' of the effect is greater than the total duration of the sequence, have the effect stop at the end time of the sequence :)

![screen shot 2015-04-02 at 5 54 25 pm](https://cloud.githubusercontent.com/assets/10136122/6976076/be8c4198-d961-11e4-862f-541d80b42534.png)

**Comment by keithsw1111** [comment]
This will be in .23 ... right click on an effect and select timing.
