### ISSUE TITLE
Feature Request: Export Music Value Curve

### ISSUE THREAD

**Issue by kmacmaster** [smeighan/xLights#1550]
Feature request:

When using the music value curve, allow exporting of the curve that was created by the music so the curve can be used elsewhere and not be tied to the music.

**Comment by keithsw1111** [comment]
Its not as simple as that ... problem is music changes intensity 44,100 times per second ... how do you want to turn that into a value curve of no more than 100 points ... when the music is there it uses the frame timing to decide how to summarise it ... once you decouple it from the music it doesnt mean much.
Maybe you can explain why this would be useful.

**Comment by keithsw1111** [comment]
Closed due to no response
