### ISSUE TITLE
Picture Effects created in 2D appear totally different in 3D w/Render style Per Preview/2D

### ISSUE THREAD

**Issue by phoenixrob2015** [smeighan/xLights#1551]
I posted this issue (with video) on the xLights Official Facebook page & Gil recommended that I open an issue here.  This is my first Github post, so I hope this is the correct method. 

This is the link for the Facebook post describing the issue & showing it in a video: https://www.facebook.com/groups/xLights/permalink/2247818261920583/

My display has a group of 5 circle matrices in a group.  There are picture effects that were created before 3D functionality was added to xLights.  Now that I've converted to 3D (currently using version 2019.24), the images are all messed up and look very different than they did in 2D.

I created a test sequence with several picture effects, and packaged the same sequence in 2018.59, and also in 2019.24, but Github won't let me attach them since they're > 10mb.  Perhaps I can email them? 

In the test sequence, the primary effect that's messed up can be found on the Circle Matrixes group at around 41 seconds.  It's supposed to be an animation of several elves passing presents to each other.  

I've also noticed that other picture effects look totally different in 2019.24, such as the ones at 1:23 and 2:13.  In addition, some standard effects also look different, such as the wave effect at :17.  These effects all appear to be zoomed in further than before.  So this issue seems to be related to the way xLights is handling the effects placed on groups internally. 

The affected models are all using Per Preview rendering style, camera 2D.  So I would expect these effects to look the same as they did in 2D.

Thanks in advance for taking a look at this issue.  Hopefully there's a simple solution.

**Comment by keithsw1111** [comment]
Can you use the tools menu package sequence ... the files should not be large.

**Comment by phoenixrob2015** [comment]
I used package sequence option but the gif files used in the picture effects are large... 13mb.  I just sent them to your email (2 separate emails).  Hope that's OK.  Thanks again!

**Comment by keithsw1111** [comment]
I looked at the sequence and i don't see what you think is wrong ... it seems to display exactly as I would expect it to. What exactly is the issue? The video is pretty useless ... its blury and has no audio explaining the problem.

**Comment by phoenixrob2015** [comment]
I made a new video with a better comparison.  I emailed it to you... it won't let me attach an MP4 here.  In the video, the top of the screen shows the model preview of the group of 5 circle matrices displayed in 2018.59 in 2D.  This is how it's supposed to look (elves passing presents to each other).

The bottom of the screen shows the same group with the same unchanged effect in 2019.24 in 3D and it's totally different, and is all scrambled.  

Are you saying that the effect looked like the top half of the video (correct) when you tried it in 3D in 2019.24?

Thanks so much for checking.

**Comment by keithsw1111** [comment]
So this is .24 ... after I reset your model appearance settings for the circles on the left. My guess you changed the appearance to remove the moire effect in 3d and then were surprised it looks different back in 2d. This will have absolutely no impact on how it displays on your lights.

![image](https://user-images.githubusercontent.com/10283944/57605729-aa167780-75aa-11e9-9673-1e21765031cd.png)

**Comment by phoenixrob2015** [comment]
Keith, I appreciate you working with me on this, but the issue still remains.  Changing the pixel appearance size/type helped (Thank you for pointing that out), but it did NOT solve the issue.  There's still an underlying problem that can be seen in the Effect Assist window that's unrelated to the appearance.  The internal grids within xLights are totally different. 

I used a different image in this example to show the issue more clearly.  I've attached 6 JPG files showing the Effect Assist windows for both versions.  You can also see the model preview in the background and it's clear that the images are not even close to being the same.  2 of the attached images show only the grid from the Effect Assist windows (a close-up).  The grid for the 3D version seems like it's truncated.  

The IMAGE SIZE and MODEL SIZE is shown in 2 of the attached files as well, in case it's relevant. 
I also made smaller versions of the 2 sequences by removing the large gifs, and attached them.

Thanks again for the help!  


[Circle Matrix Group-Issue2 With Images-Ver 2018-59-2D.zip](https://github.com/smeighan/xLights/files/3173403/Circle.Matrix.Group-Issue2.With.Images-Ver.2018-59-2D.zip)
[Circle Matrix Group-Issue2 With Images-Ver 2019-24-3D.zip](https://github.com/smeighan/xLights/files/3173404/Circle.Matrix.Group-Issue2.With.Images-Ver.2019-24-3D.zip)
![Image Effect Issue 2018 59 Effect Assist Grid 2D-Sizes](https://user-images.githubusercontent.com/12240505/57630128-05c11080-756b-11e9-8510-4be4f109d5db.JPG)
![Image Effect Issue 2019 24 Effect Assist Grid 3D-Sizes](https://user-images.githubusercontent.com/12240505/57630129-05c11080-756b-11e9-9f92-ec8e5e62f0f1.JPG)
![Image Effect Issue 2019 24 Effect Assist Grid CLOSEUP 3D](https://user-images.githubusercontent.com/12240505/57630130-05c11080-756b-11e9-9ed0-396bf58bc732.JPG)
![Image Effect Issue 2018 59 Effect Assist Grid CLOSEUP 2D](https://user-images.githubusercontent.com/12240505/57630131-05c11080-756b-11e9-8915-b63fafe78c8c.JPG)
![Image Effect Issue 2018 59 Effect Assist Grid 2D](https://user-images.githubusercontent.com/12240505/57630133-05c11080-756b-11e9-9b4d-8d0266324ce8.JPG)
![Image Effect Issue 2019 24 Effect Assist Grid 3D](https://user-images.githubusercontent.com/12240505/57630134-0659a700-756b-11e9-9f46-ead17ad99224.JPG)

**Comment by AzGilrock** [comment]
I think there are 2 different issues here that are unrelated.  One is the display of the Effect Assist might be messed up since we went to 3D but that doesn't mean the underlying buffer is that much different.  You can see the entire ornament is displayed in the effect even though only the bottoms show up in Effect Assist.  If you look at just the final result of the effect the 3D one looks more correct because you chose the "Scale Keep Aspect Ratio" option and the 2D one did not maintain the aspect ratio.  It's possible a Picture effect bug about aspect ratio was fixed and now it's correct.  Not sure why the buffer size is off by 1 now.   We keep having these off by one issues and then someone reduces a size by 1 to fix a bug and then it shows up elsewhere like this.

**Comment by keithsw1111** [comment]
The effect assist issue needs to be moved into a separate ticket. One issue per ticket ... if you put multiple then we get to choose which one gets addressed.
