### ISSUE TITLE
Scrolling timing  tracks needed

### ISSUE THREAD

**Issue by steveking16** [smeighan/xLights#1552]
I'm working on a 'This is Halloween" sequence using the timing tracks from the free Lyrics on the google drive.  There are 20 Lyric tracks-that's 60 timing track lines when expanded.  There is no access to the effects section of the sequencer window.  I had to collapse the lyric lines and then expand the window to full screen height to see my effects. If the timing tracks lines take up the full window, there is zero access to editing effects--the scroll bar is not usable.  We need to be able to move the timing/effects divider and then be able to scroll the timing tracks.

**Comment by keithsw1111** [comment]
Why not just create a view and omit the timing tracks?


On 12 May 2019, at 11:23 am, steveking16 <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm working on a 'This is Halloween" sequence using the timing tracks from the free Lyrics on the google drive. There are 20 Lyric tracks-that's 60 timing track lines when expanded. There is no access to the effects section of the sequencer window. I had to collapse the lyric lines and then expand the window to full screen height to see my effects. If the timing tracks lines take up the full window, there is zero access to editing effects--the scroll bar is not usable. We need to be able to move the timing/effects divider and then be able to scroll the timing tracks.

**Comment by steveking16** [comment]
Keith –

That works.  I had to research how to do that -- feature I have never used.  I was surprised to import and then have no access to editing effects.

I love xLights and all you do.

THANK YOU

Steve King
steveKing16@outlook.com
