### ISSUE TITLE
Waveform disappears at maximum zoom

### ISSUE THREAD

**Issue by HansonElectronics** [smeighan/xLights#1555]
When zoomed into the maximum timeline zoom the audio waveform disappears.
Present on 2019.25 32 bit. 
System is 32 bit Windows 7.

**Comment by AzGilrock** [comment]
Can you show a screenshot?  I just tried this and I still see the waveform.  Granted at max zoom your waveform is way stretched out so there will be parts of the song like the intro that look empty.

**Comment by keithsw1111** [comment]
Closed due to lack of a response.
