### ISSUE TITLE
Keybindings Error on Exit

### ISSUE THREAD

**Issue by LightsGuy84** [smeighan/xLights#1559]
I keep getting a keybindings error on exit with a message to package and send the logs which I have attached. 
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3184124/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
Fix. Shut xlights. in your show folder delete xlights_keybindings.xml and restart xlights.
The keybinding file appears to have been already corrupt in that directory and deleting it and restarting xlights will rebuilt it.
