### ISSUE TITLE
enh: Show existing song & path when prompted to replace media

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#1561]
Not sure if this is easy/possible but my scenario is I have moved music around and when I first open a sequence it of course prompts me to pick my (missing) music. Problem is I don't know what it was before - this can help for downloaded sequences as well. The workaround is to open the xml in notepad to view it and get some idea of what the exact song title was.

**Comment by computergeek1507** [comment]
Fixed with e9c4b1d634b24328cafef292348dcf28ceb5d3a3
