### ISSUE TITLE
2019.25 Mac Crash

### ISSUE THREAD

**Issue by leelindquist** [smeighan/xLights#1562]
If xLights is freshly launched and currently displaying the "Setup" or "Layout" tab (without first navigating to the "Sequencer" tab) then navigating to View->Windows->Display Elements menu item, xLights will crash. If xLights is currently displaying the "Sequencer" tab, the action works as expected. 

If the "Sequencer" tab has been selected during a particular launch instance, and then then the user navigates back to the "Setup" or "Layout" tab, then the menu action works as expected without crashing.

https://youtu.be/PRFnuiOFAq0

[xLights_dbgrpt-45336-20190521T142940.zip](https://github.com/smeighan/xLights/files/3204138/xLights_dbgrpt-45336-20190521T142940.zip)

**Comment by leelindquist** [comment]
After some more testing, I've found that it crashes with the "Video Preview" selection in the View->Windows menu as well.

**Comment by keithsw1111** [comment]
@Dkulp i think you are going to need to look at this one as i have tried it on windows and it doesnt crash.
