### ISSUE TITLE
Falcon Node Slider setting for F16/F48

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#1563]
I dont know if this is a bug or what ..I have both an F16 and F48. On the F16 I pixel packed so I have one output with 700+pixels. The slider thing that determines how many nodes to feed on each bank(?) seems to get set at this high number - should it be set to the max number on the banks of the F48 and just ignore the outputs of the F16?

**Comment by computergeek1507** [comment]
The slider only appears if you select the a expansion board option from the drop-down in the top left on your F16v3

**Comment by derwin12** [comment]
I have both .. so it appears .. it just seems like it is using the node counts on my higher F16 node counts to set the values.

**Comment by computergeek1507** [comment]
If you are not using an expansion board with your F16v3 you shouldn't select the expansion board option. The only edge case where you may need to enable the expansion option without a physical expansion board is for when you are using a remote reciever board off the serial ports.

**Comment by computergeek1507** [comment]
This is my understanding of how the F16v3 works based on conversations with Dave. Node: I made this document quick and have not verified it contents with him. [Falcon.pptx](https://github.com/smeighan/xLights/files/3207877/Falcon.pptx)

**Comment by derwin12** [comment]
Sorry I was confusing web pages between fpp and f48 - there is no problem .. only me being confused :-) Thanks for the help..
