### ISSUE TITLE
Transition: Wipe - issue

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#1568]
Not sure when it started, but the Wipe transition is no longer wiping from top-to-bottom or bottom-to-top.  It works correctly when changing the slider from left to right.  I have been using a mask along with the Fill effect to create my "wipe" transitions for some time now.  Just getting around to reporting it.  Current version .25 not working.  Didn't check on .26.  

Thanks
Clyde

**Comment by keithsw1111** [comment]
It seems to work for me
