### ISSUE TITLE
Images not rendering during playback

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#157]
I have a movie file that I have carved up to the size of my matrix at 20 fps.

The images start out in black and then progressively reveal Saint Nick himself.

If I use a static image - frame 28 - I see him, but if I set the start of the pictures to the first frame - 1 - which is in black, the playback only stays in black.
If I use frame 28, the static image stays on throughout the entire effect duration.

I have the 'movie is 20 fps' checked. 

![screen shot 2015-04-03 at 8 30 06 am](https://cloud.githubusercontent.com/assets/10136122/6983498/eaeaedb4-d9db-11e4-8f54-e3e9e120c6c2.png)
![screen shot 2015-04-03 at 8 29 31 am](https://cloud.githubusercontent.com/assets/10136122/6983501/f000eb50-d9db-11e4-99a7-6733ba81f7e6.png)

**Comment by LightsOnHudson** [comment]
At 1 second and change during effect playback, St Nick should be visible and you can see in the top screen shot, the model preview is still in black. I have movement set to None as I want him to stay right in the middle of the model.

I have attempted to save the sequence, etc to get it to save the images and have also saved the .fseq file and loaded it onto a PI with the same result - no images playback.

**Comment by stevegiron** [comment]
Do you have fade in for that timing cell enabled by any chance?

**Comment by LightsOnHudson** [comment]
I'll have to check but if it is enabled by default then maybe. When I used XL 3.x it was working properly with image sequences. and I watched Sean make a video/tutorial using image sequences. I'll test in the newer version. it should work yes? Where is the fade in on the Images/Picures effect?

**Comment by stevegiron** [comment]
Fade is on the Layer/Timing control box.   
By the way, we are down to 70 open issues, of which 24 are yours. Kindly go through all your open issues and close any that have been resolved. I'm sure you can appreciate the workload with only  two active developers.

**Comment by LightsOnHudson** [comment]
It is not enabled by default in x. 4.0.30 . but I dont have any still image sequences on my work laptop right now. I'll be home tomorrow.

**Comment by LightsOnHudson** [comment]
Using the latest OSX 4.1.7 this is working fine now.
