### ISSUE TITLE
xFade Master Brightness Locked into Left and Right

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#1570]
After assigning a MIDI slider to each of the 3 brightness levels in xFade (Left, Right, and Master), I am able to set the individual level of brightness.  However the fade-up on the master also locks in the same value to the Left and Right Brightness sliders.  

There are instances where a user wants to have all 3 sliders at the lowest intensity, say for example to prepare an effect on one side.  However when pushing up the Master brightness, both the Left and Right are locked to the main.  Can this be unlocked?  So I want everything dark, and while it's dark (all three sliders down) I bring up only the Master.  Then I can prepare either my Left or Right effect and fade-in my Left or Right effect.  I realize I may have to first pull up my master brightness first, then activate either my Left or Right slider.
See video for demo

https://www.dropbox.com/s/9e2dn8su4kgr8w9/video-1558898368.mp4?dl=0

**Comment by keithsw1111** [comment]
The behaviour is intentional. My thinking went something along the lines of if you wanted to keep then in synch you would use the master ... if you wanted them different you would control them individually. I see what you mean but I am not sure it is better ... just different.

**Comment by Clyde-L** [comment]
I understand that point.  I had a different experience using it live, but can tailor it to my use knowing now that is how it is written.
