### ISSUE TITLE
Enhancement Request, color curve tool tips

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#1572]
Can a tool tip be added to view the name of the file that created it?  I find a lot of uses for these but sharing with others who are color blind may be a bit more challenging.

![Screenshot 2019-05-31 18 05 22](https://user-images.githubusercontent.com/12719816/58737323-1082fe80-83cf-11e9-8fe7-bbca052c1e19.png)

**Comment by computergeek1507** [comment]
Added with c62c86077c9fc15ea01def2fc256b3a9c34b2a79
