### ISSUE TITLE
Audio Settings Bug

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#1573]
When I open xLights the audio selection from my previous xLights session is saved.  However, I still have to go back and click on the setting again for the action to take place.  Audio runs at loudest settings as if it is ignoring your "saved setting" from your previous xLights session.

Running in Windows 10, 2019.28.  

![image](https://user-images.githubusercontent.com/12719816/59148922-bdb3d300-89dc-11e9-9ff2-3c1f61c9966b.png)

**Comment by keithsw1111** [comment]
Are you sure this was .28 ... because i thought i just fixed it. I think i will just remove it as i never wanted it in the first place.

**Comment by Clyde-L** [comment]
Yes I'm quite sure.  You can see the Shader effect in the image I attached.

**Comment by computergeek1507** [comment]
I tried this in 28 and it worked as expected. Do you have a video or demo of this?
