### ISSUE TITLE
Enh: Right click effect and quick options (like fade in / fade out?)

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#1574]
Thoughts on having some perhaps configurable right click options on an effect. Perhaps fade in or fade out or other common choices that you might place on effects?

Just a thought as I do some sequencing.

**Comment by computergeek1507** [comment]
I thought about added this to the keybindings file. I think adding more right click options would clutter the menu too much.

**Comment by computergeek1507** [comment]
I added the ability to the keyboard shortcuts for this to be easier now
