### ISSUE TITLE
Modify FPP Connect to generate FSEQ containing only channel data configured on the target remote

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#1578]
Modify FPP connect so when it uploads FSEQ to an FPP remote, it always starts at channel 1 and generates an fseq file specifically for that target containing only channel data for channels configured on that target FPP remote.

**Comment by dkulp** [comment]
Closing this as this is "almost" what it currently does.    It does generate an fseq file that is specific for that remote.   They just aren't numbered from channel 1.  But that should be irrelevant from an xLights and FPP perspective if the config on the FPP instance matches what xLights is using.
