### ISSUE TITLE
Custom Colors not saving

### ISSUE THREAD

**Issue by JMHaro** [smeighan/xLights#1579]
I was just trying to create some custom colors in the Models States area and the Custom Colors do not save, requiring me to have to set up the same color manually each time I want to use it.  Can these get saved for reuse?  Attached is a short video clip showing the problem.
[Custom Colors.zip](https://github.com/smeighan/xLights/files/3317068/Custom.Colors.zip)

**Comment by keithsw1111** [comment]
Fixed
