### ISSUE TITLE
Enhancement request: Undo

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#158]
Kindly requesting an undo button to correct the whoops moments on the sequence tab.

**Comment by smeighan** [comment]
This has been requested by many people. We will do it, question is when. My guess is we will try to get it by june

**Comment by gerry4** [comment]
As a new user , would definitely second this request.
LSP (which I am used to) has this as a setting and you can specify how many undos it should support . Obviously the more you have , the bigger the performance hit. As of now , I save every 5 minutes and if I do something unintended , I exit NC and start again.

**Comment by stevegiron** [comment]
Undo is here. Thank you! Closing issue.
