### ISSUE TITLE
ZCPP Description Bugs

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#1581]
A few things that I have noticed with the ZCPP, that I think are bugs or at least could use some enhancements.  These are all related to the description, so grouping them in a single issue for this.

- If the Description is left blank in the ZCPP window, you can't use it when setting up a model as it doesn't appear in the drop down.  Would suggest making it required to have a description for this.
- Multiple ZCPPs can have the same description even for different IP addresses.  So if someone has multiple F16v3 controllers, and uses "F16v3" as the description for all of them, there is only 1 listing of F16v3 in the dropdown for the controller connection.  There doesn't seem to be an warning or error in the check sequence to indicate this is a problem.  Should probably be something to make sure each controller description is unique.
- I have seen lots of people use the description previously as what is being connected to each universe (things like Megatree, arches, matrix, etc).  For the ZCPP, the description is more for the controller.  Not sure there is a good way to emphasize that, but might be helpful if there was.

**Comment by keithsw1111** [comment]
I agree with some of these.
I have changes ZCPP to insist IP and Description are unique amongst ZCPP outputs
