### ISSUE TITLE
v2019.31 - MAC - Layout issues

### ISSUE THREAD

**Issue by itsayceecee** [smeighan/xLights#1585]
In the layout tab for this release the following options are "not visible" - blanked out white,until you click into them.
- Model Chain (under Start Channel)
- Port (under Controller Connection)
- Protocol (under Smart Remote)
See attached screenshot.I have clicked into the Port field , it then becomes visible.

<img width="621" alt="Screenshot 2019-06-27 at 21 15 11" src="https://user-images.githubusercontent.com/47702782/60298153-ba4ba180-9921-11e9-9757-cdf22017bc5b.png">

**Comment by dkulp** [comment]
Fixed this yesterday....  will be in .32.  Keith has a habit of setting backgrounds of things to White which doesn't work on the Mac when the text is White.

**Comment by itsayceecee** [comment]
Thank's @dkulp
