### ISSUE TITLE
Phoneme Selection Enhancement

### ISSUE THREAD

**Issue by Duramadmax** [smeighan/xLights#1594]
Is there a way that when you select the second line of the lyric track (ie the individual word) that it can highlight or maybe change the color of the phoneme "stack" below so I can better select which phoneme is associated with the word. I see that when I click the word that the line between the vertical borders changes to purple.  

Or even more cool would be when you move the word, the lower list of phonemes moves the same distance. Keep the together.

**Comment by keithsw1111** [comment]
This would be a huge change as right now the layers are really quite independent. A phoneme has no idea which word it came from .... and may not have even come from a word ... I really dont think this is likely to ever be changed.

**Comment by AzGilrock** [comment]
Keith is right there is no association between phrases, words, and phonemes once the breakdown occurs.  You are not even required to have words.  Once you get the 3 layers you could manually place phoneme's without even having words or phrases.
