### ISSUE TITLE
[Request] Change media file directory for sequence

### ISSUE THREAD

**Issue by jakabo27** [smeighan/xLights#1597]
It would be great if in the Tools section there was a "Specify picture/video location" to allow us to use a different folder than the sequence's _lost folder for the files.  This would also be great if someone moved their xLights directory from D:/ to C:/ and then all the video links are broken - just allow a simple function to direct to a different folder for the gifs, pictures, and videos used in that sequence.  Depending on how you implement this it could also allow us to use a single directory for all media used across sequences

**Comment by computergeek1507** [comment]
If you keep your you video and picture files in a subfolder of your show folder, xLights will find the files. The "_lost" folder is only created if files are being stored outside the show directly and you do package sequence. Maybe if you can give more insight into your issue, we can suggest other ways to do it and/or verify xLights is working as intended.

**Comment by keithsw1111** [comment]
This is so not a bug ... root cause ... user error by sequence vendors and their customers.

This is kind of like solving poverty by printing money and giving it to the poor ... the side effects would be stupid bad.
