### ISSUE TITLE
2018 MacBook Pro - Video display issues on "House Preview"

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1598]
I started using my MacBook Pro again to edit some sequences while traveling and notice once I move the preview window out of the small window to make it bigger it looks ok but once I put it back the video is now gone unless I move some of the bars around like you can see in the video. Also sometime when I make the house preview bigger is only shows on the top half of the window cutting off most of the house as you can see about 1:30 into the video

https://youtu.be/S0DnXAFVIMM

I attached a screenshot of my specs and I also have .19 on my MacBook with the same results so this is not just newer versions
<img width="583" alt="Screen Shot 2019-07-07 at 8 56 16 PM" src="https://user-images.githubusercontent.com/40632971/60776379-c1c93280-a0f9-11e9-8924-51f264d43c3c.png">

**Comment by dkulp** [comment]
I believe this is now fixed in .37b

**Comment by bchiaino** [comment]
Awesome thanks. I’ll check it out tonight
