### ISSUE TITLE
Enhancement request: Add degrees dialog to Sphere model

### ISSUE THREAD

**Issue by ModernDayGriswolds** [smeighan/xLights#1599]
I made a huge 48" diameter 270 degree Coro Sphere to go on top of my 270 degree Mega Tree and come to find out I can not model a 270 Sphere. Image attached (viewed from the back)
Enh request: Add a degrees dialog box (much like the Mega Tree) to the sphere model so they can be modeled as partial Spheres.
![270 Sphere](https://user-images.githubusercontent.com/52804053/61091487-f134b380-a407-11e9-9bc4-eb262e9b8fb0.PNG)

**Comment by keithsw1111** [comment]
Why not build it as if it was a 360 with extra pixels ... then export as a custom model and then delete the excess nodes.

**Comment by ModernDayGriswolds** [comment]
Obviously because that would make too much darn sense to do that.
Thanks Keith, just figured I would make the suggestion.

**Comment by keithsw1111** [comment]
Unless dozens of people start to build them I dont see it being worth adding as every parameter adds complexity and risk of bugs caused by that complexity.
