### ISSUE TITLE
Current calculation issues

### ISSUE THREAD

**Issue by HansonElectronics** [smeighan/xLights#1600]
When changing the lights per pixel from 1 to 3 like for 12V strip or 12V modules the current triples when it should stay the same. ie 20 nodes calculates as 1.2A but if changing to 20 12V 3led/pixel then xlights calculates as 3.6A
  Also on a related issue when calculating the current for a matrix the assumption is made that the pixels are 60mA each or 30.72A per P10 panel. With 1/8 scan which is the most common indoor panels the current is closer to 2.5A. Without an additional radio button/s or lots of addition selection options I don't see an easy way to implement something to correct the current per pixel.

**Comment by keithsw1111** [comment]
I really dont think I am going to do anything with this. As you say its a rabbit warren of complexity ... its an estimate only.

**Comment by computergeek1507** [comment]
If it is too misleading, I would just remove it.
