### ISSUE TITLE
Crash when deleting and replacing DMX model

### ISSUE THREAD

**Issue by leelindquist** [smeighan/xLights#1602]
I haven't tried to narrow this down any farther yet, but these are the steps I take to reliably reproduce the crash:

Launch xLights
In Setup tab, Create new empty show folder
Switch to Layout tab, Drop a DMX model into the layout
Switch to Sequencer tab, Create new sequence
Drop a DMX effect onto the DMX model
Switch back to Layout tab, Delete DMX model, answering YES in dialog box
Drop an "Import" model with a previously-saved xmodel file
Switch back to Sequencer tab
--CRASH--

https://youtu.be/kNxuqUGvKrE

xLights crash log and the .xmodel file I was attempting to import are attached.

[xLights_dbgrpt-2726-20190712T162436.zip](https://github.com/smeighan/xLights/files/3388037/xLights_dbgrpt-2726-20190712T162436.zip)

[Alpha Beam 700.xmodel.zip](https://github.com/smeighan/xLights/files/3388039/Alpha.Beam.700.xmodel.zip)

**Comment by keithsw1111** [comment]
Good catch ... I am not sure if this is all the causes but this was causing one of the crashes i have been chasing for a long time. Problem seems to be when we delete the model and effects we were not clearing the selected effect so when the next render event occurred we were trying to render the deleted effect. I have now added unselect of the current effect on all model delete events inlayout which should at least fix this cause.
