### ISSUE TITLE
.34 Crash

### ISSUE THREAD

**Issue by kd7hgt** [smeighan/xLights#1603]
When I click the Discover button I am getting a debug report.  Tried 4 times same result.  Then tried FPP Connect and also get a Debug report.
[xLights_dbgrpt-15448-20190713T182451.zip](https://github.com/smeighan/xLights/files/3389282/xLights_dbgrpt-15448-20190713T182451.zip)
[xLights_dbgrpt-108-20190713T180937.zip](https://github.com/smeighan/xLights/files/3389283/xLights_dbgrpt-108-20190713T180937.zip)

**Comment by dkulp** [comment]
I believe this is fixed in bd773bd10b3ac50adb9c183bdfd68c8c243f2aac, but I'm really not sure as I'm not sure why this would have worked previously and I've also not been able to reproduce it on a Mac.

**Comment by kd7hgt** [comment]
I reverted back to .33 and worked fine. I will try to go back to 34 again.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dkulp** [comment]
This is now fixed.
