### ISSUE TITLE
Model State nodes not saving when using grid selection 

### ISSUE THREAD

**Issue by JMHaro** [smeighan/xLights#1604]
I'm in the Model States and selecting nodes using the image grid.  After selecting the desired nodes I click OK, the state definition screen shows the selected nodes.  I click OK, and then save my changes on the layout screen.  I go back to the State Definition screen the previous selected nodes are gone.  ONLY nodes that I manually type in get saved.
[StateDefinitionsNotSaving.zip](https://github.com/smeighan/xLights/files/3389420/StateDefinitionsNotSaving.zip)

**Comment by JMHaro** [comment]
Hi Keith, I see this was closed but no comments.  Was I doing something wrong?

**Comment by AzGilrock** [comment]
He closed it using a checkin
