### ISSUE TITLE
.34 crash

### ISSUE THREAD

**Issue by TxBillbr** [smeighan/xLights#1606]
Newly installed .34 working in layout tab with 3D. Selected two objects that were locked.  I don't remember if I right-clicked or left-clicked, but the crash occurred at click time.

[xLights_dbgrpt-6372-20190714T153509.zip](https://github.com/smeighan/xLights/files/3390486/xLights_dbgrpt-6372-20190714T153509.zip)

**Comment by keithsw1111** [comment]
It looks open GL related. Unless you can reliably reproduce this problem there is not much we can do at this point.

**Comment by keithsw1111** [comment]
Do you have anything more Bill or should we just close this one.

**Comment by TxBillbr** [comment]
Keith,
Go ahead and close. That was opened before we went through bug reporting at the expo.

Thanks,
Bill
