### ISSUE TITLE
Release Notes Mac 

### ISSUE THREAD

**Issue by temeyers** [smeighan/xLights#1607]
Release notes do not open correctly/at all in texteditor on Mac

**Comment by keithsw1111** [comment]
I need a lot more than this ... what exactly is the problem ... it is a pure text file so it should open.

**Comment by dkulp** [comment]
This is from the menu item on the help menu.  I think it's looking for the README.txt in the same directory as the executable, but it doesn't exist there on the Mac.   I'll need to embed the README into the app for this to work I think.   That said, do we really need the entire 285K file?

**Comment by temeyers** [comment]
The Mac gentleman in class saw it and said it was a iris pro graphic issue and he will asses
