### ISSUE TITLE
Drag and drop crash

### ISSUE THREAD

**Issue by rugerboy58** [smeighan/xLights#161]
Using 4.0.13 and when I highlight an effect and try to drag and drop the effect icon next to the F5 button 
xlights crashes. If highlight and drag and drop from the effect toolbar all is good. I have the file generated from the crash but did not see anywhere to attach. Email below if you want me to send file.
![4 0 13 crash](https://cloud.githubusercontent.com/assets/11798658/6993555/40e93032-dac6-11e4-9f9f-b5d097817084.jpg)

Thanks,
Ed Slonka Jr
rugerboy58@yahoo.com

**Comment by AzGilrock** [comment]
Please try again with 4.0.14 when Sean releases it today.  I know I fixed a couple drag and drop crash situations last night.

**Comment by rugerboy58** [comment]
Will do.
Thanks Gil!

**Comment by aalsterskersthuisje** [comment]
Just had the same problem. Thanks for resolving this so soon. Will keep you up to date as soon as i try the 4.0.14. Awesome job guys

**Comment by AzGilrock** [comment]
Yeah I'm not 100% sure this particular scenario is fixed.  I just know I had it crash if I dropped below the bottom row and that was fixed and I put protection around a couple other pointer where we weren't checking to make sure they were valid before using them.  Sometimes we call functions that can return null pointers and we forget to do the check on the calling side.

**Comment by aalsterskersthuisje** [comment]
As rugerboy58 describes, when drag and dropped from the effect toolbar, all is good, no issues :)  
I'm new into rgb so i have to learn everything from scratch, but your tutorial is awesome and makes it so easy to understand. I'm working 4 years with LOR now, so i'm allready into sequencing.
Just wanna say thanks for all your great work you put into this!!

**Comment by rugerboy58** [comment]
Gil,
Just installed 4.0.14 and the issue from above is fixed. Tried several times.
Thanks to you, Sean, dkulp, and djulien for all you hard and fantastic work. What a great product 
and such unselfishness to share with us!!!
Ed Slonka Jr

**Comment by smeighan** [comment]
closing as the user says it is fixed.
