### ISSUE TITLE
Bug xLights on version update

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#1610]
Steps:
Open ver 34,
get the update message
click the update button
file downloads,
click to run,
updates as it should until the last second and I get two errors that looks like it is having trouble creating the desktop links
the path on the installing window is
c:\users\public\desktop
the error is
IPersistfile::Save failed; code  0x80070002 The system cannot file the file specified
I also get a similar error when I click OK.
It appears to be having a problem on creating the desktop icons.  
I tried to take a screen shot, but it did not paste into this post.

**Comment by keithsw1111** [comment]
I dont think these are our problem. This is in the install and if there are problems there they have always been environmental

**Comment by JoelDearing** [comment]
I understand.  I have xLights on 3 computers, and the new Win 10 desktop is the only one when it upgrades is where I get the error.
