### ISSUE TITLE
Check sequence warning on text effect by lyrics

### ISSUE THREAD

**Issue by kwoodard** [smeighan/xLights#1611]
Version 2019.35 gives a error during check sequence for text effects with no Text if the text effect was selected to use Text From Lyrics.

Exact Error: ERR: Text effect has no actual text. Model 'MegaTree', Start 0:45.400

**Comment by computergeek1507** [comment]
Does your timing track contain lyrics?

**Comment by kwoodard** [comment]
Yes, it contains lyric tracks and I've selected one of the lyric tracks for the Text Effect to use.  The text shows up on the display items, but I get these errors in the Check Sequence.
