### ISSUE TITLE
lights crash when changing shader effect directory of mapped sequence

### ISSUE THREAD

**Issue by jamesski2** [smeighan/xLights#1615]
xlights crashes when changing shader effect directory of mapped sequence.
mapped a downloaded sequence with a shader effect, when I went to change the shader effect directory, xlights crashes when I click OK on the new location
[xLights_dbgrpt-59627-20190727T194429.zip](https://github.com/smeighan/xLights/files/3438027/xLights_dbgrpt-59627-20190727T194429.zip)

**Comment by keithsw1111** [comment]
Is it reproducible ... and if so how exactly do you do it. One off crashes are not really helpful to report ... we can pick those up in the crash logs.

**Comment by keithsw1111** [comment]
Closing due to lack of user response.
