### ISSUE TITLE
Sequencer Tab only partially rendered in V36 on Mac

### ISSUE THREAD

**Issue by symbiotic1** [smeighan/xLights#1616]
When switching to the Sequencer tab the center View section is entirely blank. No model names are listed and no timeline is shown. I attempted multiple project folders and sequence files as well as new sequences.
![Screen Shot 2019-07-27 at 10 39 45 AM](https://user-images.githubusercontent.com/53378752/61997783-ca0ef080-b05b-11e9-88f3-25fa1a85bd90.png)

**Comment by dkulp** [comment]
Can you try with the 2019.37c build I uploaded?

**Comment by symbiotic1** [comment]
Hi Dan,
I can test it for you next week. I reverted to the v35 release and I've got
an event I'm using the app for this weekend so I don't want to change
anything on my computer until after.

Best,
Aaron

**Comment by dkulp** [comment]
I believe this is now fixed.
