### ISSUE TITLE
Crash opening custom submodel on osx .36

### ISSUE THREAD

**Issue by edalquist** [smeighan/xLights#1618]
I consistently get a crash when trying to open the submodel ui on a custom model.

[xLights_dbgrpt-9854-20190727T235516.zip](https://github.com/smeighan/xLights/files/3438905/xLights_dbgrpt-9854-20190727T235516.zip)

**Comment by dkulp** [comment]
I uploaded a 2019.36b build yesterday afternoon that fixed this.
