### ISSUE TITLE
Pictures issue from 30 to 36

### ISSUE THREAD

**Issue by akareaper** [smeighan/xLights#1619]
Upgraded from .30 to .36 and pictures appearing on matrix now appear washed out.
![30_36_fade_png](https://user-images.githubusercontent.com/53411335/62013687-e39b5f80-b163-11e9-9b3a-840f13ea8de1.png)

**Comment by keithsw1111** [comment]
Yes ... this was warned about in the release announcement post ... I think I have a fix for .37.

It only impacts what you see on the screen. It should not impact your LEDs.

**Comment by akareaper** [comment]
Thanks Keith!
