### ISSUE TITLE
Enhancement request: Effect icon sizes

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#162]
Here's a conceptual rendering of the buttons rescaled to 180% and they fit in the same pane.
I would have to squint less and have a better chance of selecting the correct effect.

![image](https://cloud.githubusercontent.com/assets/10568498/6993811/c0224e3a-dab5-11e4-8f1c-1cfa86af5c8d.png)

**Comment by BobinWV** [comment]
Amen---us older folks would appreciate this:)

**Comment by stevegiron** [comment]
Issue addressed in 4.0.15 "New Vision" release. Thank you team!
