### ISSUE TITLE
Arches direction backwards on first layer

### ISSUE THREAD

**Issue by reelpilot** [smeighan/xLights#1620]
On the arch model placing an effect with directional movement such as single strand, bars or spirals; the direction of movement is backwards from desired on the first layer of arches. The issue is present on individual arches with the single line render style and groups of arches with single line, per model default, per model per preview and per model single line.

**Comment by AzGilrock** [comment]
Yeah I don't think so.  You must have drawn the arch backwards.  xLights expects you to draw it with the green square starting on the left.

**Comment by reelpilot** [comment]
I love how you completely discount me as being wrong. Check out the video then and explain to me how the direction of movement is changing based on whether the effect is on layer one or layer two with no other changes being made. This is on 2019.36

https://youtu.be/sialyX78W30

**Comment by AzGilrock** [comment]
I didn't discount it I spent time to download the latest version and then I tested it based on what you said and I could not see a problem.  You provided no evidence in the original post.  You see how great my technique works.  I just tell users they are wrong and then I get the proof that should have been in the original post.  I've been using this technique for years.  I know it causes some of you to cry but it works....lol.

**Comment by reelpilot** [comment]
I checked with a few other people yesterday before I opened this report and they all had the same issue, so I assumed it was easily reproducible. That being said I just created a new layout with arches and did not have the issue, so apparently there is something else at work which is creating the issue. I also traced the start of the problem back to 2019.14, prior to that release my arches work properly. Attached is a link to my layout.

https://www.dropbox.com/s/3n475jmuaguofls/Arch%20Test.zip?dl=0

**Comment by temeyers** [comment]
V36 and V37 are having a TON of problems for everyone on our team as well. Some of our effects are reversing. We reverted to v35 and everything seems okay

**Comment by AzGilrock** [comment]
Just got home so I can actually try out the files.  Yes it appears to be broken.  That's weird I wouldn't have believed it could render differently just being on a different layer.  When you originally said different layers I thought you meant different arches like when you expand an arch group.  That's why it helps to see a video and have the layout.

**Comment by AzGilrock** [comment]
For anyone that can troubleshoot this I attached a very simple scenario that shows the problem.  Both effects are exactly the same but they render differently based on which layer they are on.
[arch_test.zip](https://github.com/smeighan/xLights/files/3449287/arch_test.zip)

Also I went back to 2019.1 and it still behaves this way.  Not sure how long its been working this way.  I also notice that the order you place the models into the group changes they order they will render when using the Single Line render style.  You can see this by dragging the models into a different order in the Layout and watching how the same model always renders first no matter whether you put it on the right left or middle.  That's just how that render style is going to work.  You need to use Per Preview if you want a group to follow the direction they are laid out on the screen.

Finally to other developers I notice if I rendered and saved in 2019.36 and then tried to open in 2019.1 it crashes every time trying to open the fseq file.  I know going backwards is not a normal operation but seems like some protection in the code could help.

**Comment by dkulp** [comment]
The bug was introduces somewhere between 2018.3 and 2018.4.   However, I believe its because the <=2018.3 behavior was wrong in that it renders both exactly like how the recent builds render the second layer which I'm assuming is the behavior we considered wrong.   That said, it should at least render the same no matter which layer it's on.
