### ISSUE TITLE
Xlights v36 and v37 

### ISSUE THREAD

**Issue by temeyers** [smeighan/xLights#1621]
There was an issue with the timeline not repopulating after pausing a playing sequence, this error appeared to be related to the IRIS pro graphics and also appears to have been fixed in this release, however now my other MacBook cannot show anything on the timeline as far as effects go or the model and house previews, You can however drop effects blindly and then open then sequence on a working machine and see them. Radeon Pro 560x 4gb is now not working whereas IRIS Pro is. 

This issue was shown to a man in the Florida class. 

We played with all Open GL Settings as well and then reverted back to version 35 on said machine.

**Comment by dkulp** [comment]
Please try with the 37b build I uploaded this afternoon.

**Comment by temeyers** [comment]
Will do thanks, but seriously, what do you guys want me to upload for a situation like this, it doesn’t necessarily fall under a typical category and I don’t like posting things that waste your time/make me look like an ass. 

And I’ll do whatever’s needed on my end next time.

**Comment by dkulp** [comment]
At this point, if you can either attach the ~/Library/Logs/xLights_l4cpp.log file or at least look in there for any OpenGL related errors toward the bottom, that would be great.   With the 37 builds, the OpenGL debug stuff is on (so performance is slightly worse) so I'll hopefully be able to get some more information.

**Comment by temeyers** [comment]
Thanks man ! I’ll reinstall tomorrow and if I run into any issues I will attach said files. 

Thanks yet again and it was cool to meet you in Florida man.
