### ISSUE TITLE
V37 Render Cache Failure 

### ISSUE THREAD

**Issue by temeyers** [smeighan/xLights#1622]
V37 cannot properly render any mega tree data on three separate machines, Revision 35 seems to be the only current stable build currently available for Macs

**Comment by dkulp** [comment]
Without a reproducible test case, this issue will be closed and ignored.

**Comment by temeyers** [comment]
Fair enough, can’t argue with that, however I’m not to sure what to submit to you to be more helpful, all it did was pull up an error dialog, in that sort of situation do you want a screen shot or some form of log file ? 

Just want to be sure I’m not posting nonsense

**Comment by keithsw1111** [comment]
Why do you call this a Render Cache failure when the problem doesn't provide any statement as to why that is the issue. The Render Cache is a very specific piece of functionality ... there must be some reason you attributed blame to it for your problem.

**Comment by temeyers** [comment]
Simply because that’s word for word what the error said, but to follow up, is there a log file you would prefer or a screenshot of the error ?

**Comment by keithsw1111** [comment]
Logs would be great. Screenshots good. Video good as well. Anything that gives us a basis to start from.

**Comment by temeyers** [comment]
Awesome thanks guys, close away, revision 37C seems to have shut me up with every aspect of my findings thus far.
