### ISSUE TITLE
Print Node Layout does print entire model

### ISSUE THREAD

**Issue by HowardShank** [smeighan/xLights#1623]
xLights Version: 2019.37 64bit
Windows 10
Using Boscoyo DayCoro 22" Spinner downloaded within xLights

Selecting a model and viewing the node layout for printing does not allow the whole model to print. In this case it prints pages 1-3 which is only the left half of the prop layout.

5 Screenshots provided in order of each step.
Select Node Layout from Model:
![PrintNodeLayout_1](https://user-images.githubusercontent.com/20245176/62164328-37d04c00-b2ea-11e9-86cf-87b252c1ea60.PNG)

View entire layout:
![PrintNodeLayout_2](https://user-images.githubusercontent.com/20245176/62164324-37d04c00-b2ea-11e9-9071-5d1855c45c71.PNG)

Click Print and you can only see pages 1 through 3: Will not allow landscape or scaling, therefore everything off the right of the page will not print.
![PrintNodeLayout_3](https://user-images.githubusercontent.com/20245176/62164325-37d04c00-b2ea-11e9-90a6-28fef20a1949.PNG)

![PrintNodeLayout_4](https://user-images.githubusercontent.com/20245176/62164326-37d04c00-b2ea-11e9-84b0-b4f23d79ca86.PNG)

![PrintNodeLayout_5](https://user-images.githubusercontent.com/20245176/62164327-37d04c00-b2ea-11e9-9b99-3b30695b828b.PNG)

Thank you,
Howard

**Comment by keithsw1111** [comment]
We should remove the print function.
