### ISSUE TITLE
Crash report xLights 2019.37

### ISSUE THREAD

**Issue by magish01** [smeighan/xLights#1625]
[xLights_dbgrpt-12488-20190730T210809.zip](https://github.com/smeighan/xLights/files/3449815/xLights_dbgrpt-12488-20190730T210809.zip)

**Comment by keithsw1111** [comment]
Please stop raising bug reports like this. They add zero value. 

Bugs should only be raised if you can:

1. Reliably reproduce the problem
2. Describe in detail or even better demonstrate in a video how to reproduce the problem
3. Attach the files necessary to demonstrate the problem ... and ideally just the problem ... ie remove all the extraneous stuff.
