### ISSUE TITLE
xLights Freezes When Trying to add groups

### ISSUE THREAD

**Issue by PixelNut78** [smeighan/xLights#1626]
**Describe the bug**
When I right click in the model group in the layout tab, xLights will freeze and not recover

**To Reproduce**
It does this in every preview, Running 2019.37. 

**Expected behavior**
Expected drop down to add or modify groups.

**Screenshots**

**Versions (please complete the following information):**
 -Windows 10
 - xLights version 2019.37

**Additional context**

**Attachments**
Crash Dump Report https://www.dropbox.com/sh/r76u0foejurzudp/AADHkkVsH0JA5jVrqCgDZLoYa?dl=0
Package Log Files

https://www.dropbox.com/sh/w01d2v64qmy4uw6/AADmPfy3jTBJuuNuZ9_jF9bZa?dl=0

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by derwin12** [comment]
Your layout seems out of this world for channel and universe counts.. Are you sure that is correct?
~1 million channels?
~3600 Universes?

This is likely what is making it blow up..

**Comment by keithsw1111** [comment]
I am not sure .... but this may be fixed in .38.
