### ISSUE TITLE
Video effect looks washed out when using .36 and .37 after render. 

### ISSUE THREAD

**Issue by n19bmw** [smeighan/xLights#1631]
I rendered a sequence with the newest versions .36 and .37 and the videos look washed out when playing house preview in full screen.  It looks ok when zooming in but something changed when watching from the whole house previews. I am currently on .37 and it also happened on .36   Here is a link to my screen recording. Hope this helps.   Please let me know if you need anything from me.  I tried to package the sequence but it is too big to attach.  I can send it if needed.  Thanks so much for all the great work.
https://vimeo.com/351723972

**Comment by keithsw1111** [comment]
I believe this is fixed in .38
