### ISSUE TITLE
render cache and OneDrive

### ISSUE THREAD

**Issue by ItsFitz** [smeighan/xLights#1633]
**Describe the bug**
I use Microsoft OneDrive on my Windows PC and Mac Laptop.  My show folder is located in a OneDrive managed directory.  I primarily use my Mac for most sequencing ... and I do use Render Cache.  On my Windows PC, my xLights show folders are set to be Online Only, which downloads the files on-demand (or as they are opened).  The Render Cache for some of my sequences can have 50 - 300 files and some can be very large.

When a sequence is opened on my Windows PC, I can see xLights downloading each Render Cache file (one-by-one).  If I close the sequence before all of the Render Cache files are downloaded, xLights will become "not responding".  Once all files are downloaded, xLights will wake up and close the file and go be to working as normal.

**To Reproduce**
1.  Open an existing sequence file on Mac, select Render All.  Save and close the sequence.
2.  Open the same sequence file on the Windows computer.  You can see the Render Cache files downloading from the OneDrive status icon in the Windows notification area.
3.  Select File -> Close Sequence from xLights.  xLights will become "Not Responding".
4.  After all the Render Cache files are downloaded, xLights will close the sequence and become responsive again.

**Expected behavior**
xLights should terminate the thread opening the Render Cache files when the File -> Close Sequence action is performed.  Thread should also be terminated if xLights is Quit.

**Versions (please complete the following information):**
MacBook Air:  MacOS 10.13.6,   OneDrive 19.103.0527,      xLights 2019.34
Windows PC:   Windows 10 Home, OneDrive 19.103.0527.0003, xLights 2019.34

**Additional context**
Normally, the OneDrive Online-Only feature does not affect my normal usage of xLights.
In this particular case, I was trying to find an effect I had used in a sequence.  Thus, I did not keep the sequence file open very long.
This problem is not specific to a particular sequence.  It is a general issue impacting xLights Render Cache when using the OneDrive Online-Only feature.

**Comment by dkulp** [comment]
The recommendation is  "Do NOT save the RenderCache (or fseq) files onto a cloud shared directory".   Particularly the  RenderCache make no sense to save there.   Certain things that are machine specific (like paths to video files) or similar that are part of the seq settings and are updated when the sequence is loaded makes some of the stuff in the RenderCache not usable from machine to machine.  Thus, syncing it via the cloud is pointless.

**Comment by keithsw1111** [comment]
I agree with Dan ... the fix here is dont place render cache on one drive or any other drive sharing service.

**Comment by ItsFitz** [comment]
Since OneDrive is an automatic upload of all files in a directory hierarchy, the RenderCache folder (which is in my Show Folder) will get uploaded to OneDrive.  Is there a mechanism in xLights to specify a different subfolder loctaion for the RenderCache?

**Comment by keithsw1111** [comment]
Sure there is. In .38 hit the subfolders button on the setup tab and set your file locations.

**Comment by ItsFitz** [comment]
I guess I need to keep on top of these updates.  The Render Cache location was added 4 days before I opened this issue.  Thanks for that.
