### ISSUE TITLE
Crash on trying to upload to F4v3 from set up tab

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#1635]
**Describe the bug**
It is described in the attached bug report from Vers 35 
In VERSION 37
Crash when wanting to send config to controller
**To Reproduce**
My steps are outlined in the attached bug report for er 35

In VERSION 37
Open xLights
On open get an error that models are not correct.  (as expected since I am changing models to sep controllers.  
Go to set up tab
right click to upload to Falcon
Select Output Falcon F4v3.  The last selection in the list.  And CRASH
If I select any of the selections to upload to controller, it crashes.  The zip files from each crash are attached
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**
![image](https://user-images.githubusercontent.com/25068648/62425719-564b9400-b6aa-11e9-8e40-d0298963400b.png)

![image](https://user-images.githubusercontent.com/25068648/62425722-6e231800-b6aa-11e9-913d-c8bb5f39a0ba.png)

**Versions (please complete the following information):**
 - OS: Windows 7
 - xLights version [e.g. 2019.37]
- Falcon firmware 2.5
**Additional context**

**Attachments**
PLEASE PM ME.  Will be happy to send that way
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
going to need packaged logs and which controller to upload to

**Comment by JoelDearing** [comment]
[xLights_l4cpp Log File Dearing 080419.txt](https://github.com/smeighan/xLights/files/3477470/xLights_l4cpp.Log.File.Dearing.080419.txt)

Also sent the zip files from the crash via we transfer.  Also I was trying to upload to a Falcon F4 v3 firmware 2.5

**Comment by keithsw1111** [comment]
Joel I really need you to use package logs on the tools menu. It does a lot more than just send a log file. It runs check sequence, dumps your models and includes the setup and layout tab configurations for me to troubleshoot with.

**Comment by JoelDearing** [comment]
[xLightsProblem dearing 080719_7p_et.zip](https://github.com/smeighan/xLights/files/3479197/xLightsProblem.dearing.080719_7p_et.zip)

Here ya go.

**Comment by keithsw1111** [comment]
I couldnt get it to crash but there is definitely errors here. Can you try again in .40 when it comes out.

**Comment by keithsw1111** [comment]
Please reopen if there is still an issue.
