### ISSUE TITLE
States Won't Delete From Sequence Model List

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#1638]
**Describe the bug**
I deleted some states that I had created but they still show up in the Model List under the Sequence Tab

How I Got There:
Created a Custom Model Snowman consisting of 16 different LED Strings
To control each string I created 16 "States" within my Snowman Model (3 hats, 6 arms, Scarf, etc)
When I put an "ON" effect on the snowman model which, put that effect on ALL 16 states, I was hoping of deleting the effect from certain States...but found I could not, So decided to delete the 16 states and created 16 sub-models instead. Side Note: The on effect pretty much was for the whole 60 seconds of the sequence and had a fade in and fade out of 1 second at each end.
This is where I am not sure...not sure if I deleted the effect before I deleted the state...but the States continue to show up in my Model List under the Sequence Tab when I double click on my Snowman Model. I tried Re-Rendering, rebooting xlights and even creating a new sequence, the deleted States still show up. They do not show up under the Layout Tab when I open "States" within the Snowman model. Another strange issue is within the sequence I was working on when I noticed this. The only effect I put on the Snowman model was a simple "ON" with fades at both ends. Now in that sequence,  the states have what appears to be a long fade up from the beginning to the end (see attached)

![Snowman States 3](https://user-images.githubusercontent.com/13740582/62595038-9456dc80-b891-11e9-8746-2ee5aeec53d3.jpg)

**Expected behavior**
I thought deleting states from within a model in the Layout Tab would also delete them from the sequence. More than likely user error...

**Versions (please complete the following information):**
Windows 10
xLights version 2019.38

**Comment by keithsw1111** [comment]
States never show up there ... what you are looking at are submodels.

**Comment by keithsw1111** [comment]
I would need your rgbeffects file to prove it.

**Comment by jimswinder** [comment]
Nope...my submodels are above these...and named differently



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by jimswinder** [comment]
Ok...will send them to you when i get home tonight



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by keithsw1111** [comment]
Can you package the sequence which shows the states.

**Comment by jimswinder** [comment]
Will do...



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by jimswinder** [comment]
Hey Keith...

Attached a few photos that show what I am seeing...would not be surprised if on your machine everything works as expected!!  LOL

Snowman Sequence Submodels and States - Picture from the Sequence Tab showing the submodels on top and the States below them. The states had a State Definition name  of "hat1" so everything below "hat1" were what I deleted from the "States Data" section under the Layout Tab.

Snowman Submodels and Submodels - Shows the submodels from the Layout tab in the Models listing and from the SubModel "Click To Edit" area.

Snowman Submodels and States - Shows the Submodels from the Layout tab listed in the Model List and the States Defintion open with nothing showing in it.

Thanks for taking the time to look at this...more than likely its operator error...as usual...

Let me know f you need anything else...

Jim



________________________________

**Comment by keithsw1111** [comment]
You cant attach things by responding to an email from github. You need to visit the site and upload it. I need the packaged sequence. Photos are optional.

**Comment by jimswinder** [comment]
Oh...okay...sorry...will do that tonight...



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by jimswinder** [comment]
ummm...tried to drag my rgbeffects file here and it says it does not support that file type??

**Comment by keithsw1111** [comment]
I dont want your rgbeffects ... I WANT YOU TO PACKAGE A SEQUENCE ... put it in a dropbox and paste a link.

**Comment by jimswinder** [comment]
you said earlier you wanted them...lol

I would need your rgbeffects file to prove it.

**Comment by keithsw1111** [comment]
That was ages ago ... last 2 posts asked for a PACKAGED SEQUENCE.

**Comment by keithsw1111** [comment]
Did you send this ... I dont recall seeing it.

**Comment by jimswinder** [comment]
Yes...will do it again...and all you need is the seaunce, , right?



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by jimswinder** [comment]
Here is the link I believe:

https://www.dropbox.com/sh/bcow8kocfago0gj/AACxuSdRzm0MiXIJcskLvexVa?dl=0

Thanks for being so patient...not a big user of DropBox.

**Comment by jimswinder** [comment]
ok...think it is there now....didn't know which file of the sequence you needed so all three are there.

2019 Announcement Facebook

**Comment by keithsw1111** [comment]
I give up ... I have asked 3 times for a packaged sequence and i just get random files.

**Comment by jimswinder** [comment]
Keith..i asked several times what you needed...and all i got was a "Packaged sequence"...what the hell does that mean?

We arent all developers like you are...you need to be more exact in asking what you need.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by computergeek1507** [comment]
Open any Sequence in xLight (or create a New Blank Sequence), and select Tools->Package Sequence. Attach or send link to the resulting Zip file.

![image](https://user-images.githubusercontent.com/2293065/62950395-eded6880-bdb5-11e9-8327-9b2e44add402.png)

**Comment by jimswinder** [comment]
Thank you Scott..



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by jimswinder** [comment]
I dont know if it will do any good now to package a sequence as i have since deleted the custom model that was giving me the problems and recreated it.  I can send it if you think it will help though.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by computergeek1507** [comment]
If we can not reproduce the problem with the files then there is no reason to send them. It is hard to fix an "issue" with no data. We will not spend hours of our time chasing down "bugs" that may not be present. Based on your original comments, I believe you are just seeing the strand/node names not the states. But without the models data, I am just guessing. 
![image](https://user-images.githubusercontent.com/2293065/62959431-c81c8f80-bdc6-11e9-8ff9-771a9a71f5c8.png)

**Comment by jimswinder** [comment]
I will see if i can recreate the problem tonight



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by jimswinder** [comment]
Hey Scott...I have tried to reproduce the results I was seeing but to no avail.

Sorry for wasting you guys' valuable time...

Jim

**Comment by jimswinder** [comment]
Hey Keith...

You asked me to send you a Packaged Sequence in regards to this Facebook post:

https://www.facebook.com/groups/xLights/2519484478087292/?comment_id=2519886991380374&reply_comment_id=2522026377833102&notif_id=1570608373127899&notif_t=group_comment
[https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-0/c31.0.200.200a/p200x200/13770240_10209709168710930_5021485671869979849_n.jpg?_nc_cat=101&_nc_oc=AQm_3JYGeVgHn_sEpd-qdXiPrBcxQ7KpVs1ReghNDYZb0c68HQIXP5pbySYudmYcTJw&_nc_ht=scontent-sea1-1.xx&oh=da2b3dc059c36391b58bd774d5160800&oe=5E1E33CA]<https://www.facebook.com/groups/xLights/2519484478087292/?comment_id=2519886991380374&reply_comment_id=2522026377833102&notif_id=1570608373127899&notif_t=group_comment>
Official xLights Support Group<https://www.facebook.com/groups/xLights/2519484478087292/?comment_id=2519886991380374&reply_comment_id=2522026377833102&notif_id=1570608373127899&notif_t=group_comment>
This group is dedicated to helping you get the most out of xLights. We will cover how to use xlights to create your shows, how to use the falcon player or xScheduler to run your show, and be a...
www.facebook.com

**Comment by keithsw1111** [comment]
Ok ... but there is no attachment in your post. The link that may be the attachment does not go anywhere.

**Comment by jimswinder** [comment]
That's strange...because I can go back to my SENT folder and click on both the attachment and link and they both work...

but the subject line was not the one above (States Won't Delete From Sequence Model List (#1638))...it was (For Keith - LOR:channel=1)

I'll resend...

________________________________

**Comment by keithsw1111** [comment]
I got nothing.
________________________________

**Comment by jimswinder** [comment]
Strange...got a different email i could try sending it to?



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by keithsw1111** [comment]
No just this one.

Just put it in a drop box and send me a link.

________________________________

**Comment by jimswinder** [comment]
Ok..



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
