### ISSUE TITLE
Enhancement request : Meteors fade out

### ISSUE THREAD

**Issue by prof-1** [smeighan/xLights#164]
Currently the meteor effect just stops mid stream when the effect ends. Towards the end of the effect I would like to see new meteors stop being produced leaving the existing meteors to fade out.

**Comment by stevegiron** [comment]
Set color #4 to black.  It will fade out.

**Comment by stevegiron** [comment]
You can do this by putting Meteors on the top layer and Curtain on the second layer. Set the layer/timing to Layer2 is Mask. Set curtains to edge:bottom, effect:close. Single color(any).

Set your meteor fade out to your own liking and you'll have what you described. The cool thing is that you can use the curtain to basically "pull the window shade down" on any effect with this method.

You will need to start the curtain effect 1/2 to 3/4 way through the meteor effect.

![image](https://cloud.githubusercontent.com/assets/10568498/8149887/cbf930a0-1289-11e5-9018-17464a084c6a.png)
