### ISSUE TITLE
Crash on Startup after 3d Modeling, closed, re opened and failed to load backround

### ISSUE THREAD

**Issue by electramatic** [smeighan/xLights#1640]
**Describe the bug**

Tonight I setup a 3D House Model using Drone Deploy, All was great, created and layout my models/props and addressed everything, saved and closed the software, re opened 1 hr later and the following bug was happening Failed to load background image then immediate crash report

**To Reproduce**

Open the software and it crashes

(and/or link to a short video showing the problem with audio track describing what you are doing)

1. Click on Xlights to open, then click the layout tab and the debug report will show up.

2. See error

**Expected behavior**
A clear and concise description of what you expected to happen and why.

Xlights to open 

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10]
 - xLights version [e.g. 2019.38]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

https://www.dropbox.com/sh/f7hyrl9g413y0w0/AAAd43tLJneDb3wwKDJP0OUPa?dl=0

Thanks for your help

Regards Brad

**Comment by keithsw1111** [comment]
i dont understand. what is '...'? where is the '...'? There is no chance the crashlogs are enough to reproduce the problem ... at a minimum i need

    ERR: Image object 'Image' cant find image file 'C:\Users\brad_000\Downloads\modelThuAug08091640.479160\scene_mesh_textured_material_00_map_Kd.jpg'
    ERR: Mesh object 'Mesh' cant find obj file 'C:\Users\brad_000\Documents\xlights 3d\modelThuAug08091640.479160\scene_mesh_decimated_textured.obj'

and any associated material files

Even then i doubt i can fix as it has all the symptoms of a video driver issue.

**Comment by electramatic** [comment]
Hi Keith, 

thanks for your quick reply, I have been playing with xlights for 12 mths or so but only just started to play with 3d, everything was working great, i saved the layout, closed the software the opened later and it generated the crash report as soon as i tried to open the layout tab, I experimented today and found that if I'm quick and delete the mesh obj object and turn 3 d off then save, re open then click 3d it works ok, without the mesh file, as soon as I add the mesh obj file and it freezes again, I also tried on another pc and was able to set up my whole display 3 models etc and it worked just fine but then same thing happened, closed software and re opened and the same symptoms on my Mac, i have shared a drop box link to my show folder, it seems that saving the mesh file does something to screw it up.

I created the Mesh OBJ file using drone deploy, that file is in my show folder "3d Model"

I am a newbie and appreciate your patients, I could be doing some thing wrong or have settings wrong somewhere
As i have said I can still use xlights without the back round image, so issue is not urgent, i will keep trying things here too

https://www.dropbox.com/s/cdssvk11lhvfcq5/xlights%203d.zip?dl=0
