### ISSUE TITLE
"Non contiguous channels on controller ports" when setting up smart receivers

### ISSUE THREAD

**Issue by DonMc33** [smeighan/xLights#1645]
**Describe the bug**
When running Check Sequence after setting up smart receivers, it returns the Error -  "Non contiguous channels on controller ports" 

**To Reproduce**

1. In the Layout Tab, set up a new model, setting up the start channel and then the port and Smart remote settings.  Do this for the models that will be placed on the "A", "B" and "C" smart receivers, insuring that the correct port and smart remote designation is selected.
2. Run Check Sequence
3. Error "Non contiguous channels on controller ports" occurs, an example for my files would be " ERR: Model 'Eave Lower 4' and Model 'Flood 3' are on controller IP '192.168.0.55' Output Connection 'WS2811:1:SmartRemote=1' but there is a gap of 558 channels between them."

**Expected behavior**
Running Check Sequence results in no errors relating to the setup of the smart receivers.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.39
[Don McCrosky xLightsProblem.zip](https://github.com/smeighan/xLights/files/3490333/Don.McCrosky.xLightsProblem.zip)
![Summary](https://user-images.githubusercontent.com/53984565/62838431-9fb75880-bc41-11e9-9dc1-b6a76310126a.jpg)
![Eave Lower 4](https://user-images.githubusercontent.com/53984565/62838434-a645d000-bc41-11e9-8ca8-2e72055d43a1.jpg)
![Flood 3](https://user-images.githubusercontent.com/53984565/62838437-aa71ed80-bc41-11e9-885e-8f1c525ee6d7.jpg)

**Comment by DonMc33** [comment]
Attaching a blank "packaged sequence"
[Sequence packaged.zip](https://github.com/smeighan/xLights/files/3490363/Sequence.packaged.zip)

**Comment by keithsw1111** [comment]
There are a few things going on here.
1. The gaps are real but they should not be errors ... warnings maybe.
2. The falcon upload is broken ... Dave at some point changed the smart string id ... so that is fixed.
