### ISSUE TITLE
Bug: Setup Tab

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#1648]
**Describe the bug**
1.  Cannot ping controller hiding behind the FPP proxy from the right click menu.

2.  Cannot open controller hiding behind the FPP proxy from the right click menu.

3.  Upload to controller seems to complete, but no information is populated on the controller screens except the universe count under the E131 Setup screen.  Trying to manually enter information within the web browser through the FPP proxy does not work either.  Maybe this one is a FPP bug?

**To Reproduce**
1.  Highlight the controller under the setup tab, right click and select "ping controller."  Times out with an error.

2.  Highlight the controller under the setup tab, right click and select "open controller."  Opens a browser window using the IP address from the Port # column in xLights, but cannot locate the controller.

3.  Highlight the controller under the setup tab, right click and select "upload to controller - ".  The various options seem complete on the xLights side.

**Expected behavior**
1.  To be able to ping the controller hiding behind the FPP proxy like other standalone FPP instances.

2.  Opening the controller using a FPP proxy from xLights should be using (in my instance) the IP address http://192.168.0.38/proxy/192.168.1.1/ not the current way xLights handles this with http://192.168.1.1

3.  Transfer the xLights controller configuration to the controller.  Again, this may be happening correctly from xLights, but I can't see it in the web browser and this could be a FPP bug.

**Screenshots**
Attached below

**Versions (please complete the following information):**
 - OS: 10.14.6 (18G87)
 - xLights version 2019.40

**Attachments**
<img width="1264" alt="Screen Shot 2019-08-12 at 6 41 20 PM" src="https://user-images.githubusercontent.com/12144876/62906918-847a4500-bd36-11e9-8a95-4c7cd2787a2f.png">
<img width="1008" alt="Screen Shot 2019-08-12 at 6 42 22 PM" src="https://user-images.githubusercontent.com/12144876/62906924-8b08bc80-bd36-11e9-85ae-43900ca427cb.png">
<img width="1255" alt="Screen Shot 2019-08-12 at 6 43 31 PM" src="https://user-images.githubusercontent.com/12144876/62906932-92c86100-bd36-11e9-80f4-5bfdd3801c70.png">
<img width="710" alt="Screen Shot 2019-08-12 at 6 43 56 PM" src="https://user-images.githubusercontent.com/12144876/62906937-978d1500-bd36-11e9-9133-9e3cadd52ed5.png">
<img width="710" alt="Screen Shot 2019-08-12 at 6 56 37 PM" src="https://user-images.githubusercontent.com/12144876/62906944-9d82f600-bd36-11e9-8be7-6dfc47dffc0d.png">
<img width="710" alt="Screen Shot 2019-08-12 at 7 14 03 PM" src="https://user-images.githubusercontent.com/12144876/62906950-a1af1380-bd36-11e9-9fde-feef254fffdb.png">

**Comment by kppankratz** [comment]
Update

Item #3: xLights does indeed upload controller information.  Accessing the controller directly through the browser does show this.  Accessing the controller through the FPP proxy does not show anything.  So it's a FPP bug.

<img width="1016" alt="Screen Shot 2019-08-13 at 7 07 50 PM" src="https://user-images.githubusercontent.com/12144876/62985654-f073b080-bdfd-11e9-8794-6542ac1e2bfa.png">

**Comment by dkulp** [comment]
It's kind of a bug in the Falcon firmware as well.    2.5.x works fine, but the earlier versions do not.  Unfortunately, I don't think there is a 2.5.x version for the v2's yet.   

That said, FPP 3.1 has updated the proxy stuff a bit.   I'm not sure if it helps (I don't have any older controllers to test with), but it may.  I'm not really sure.   If you go to /developer.php on the fpp instance and flip to master branch (and let it take a long time to do so), then reboot (required), then the proxy stuff may work better as it tries to adjust some of the resulting html to work better within the proxy URL.    (The issue is the firmware specifically tries to load things like "/status.xml" instead of "status.xml".)

**Comment by kppankratz** [comment]
I've compiled the code and I can now open the controller in a browser window, but the ping option is greyed out.

<img width="710" alt="Screen Shot 2019-08-15 at 7 59 20 PM" src="https://user-images.githubusercontent.com/12144876/63136351-2ef0a300-bf97-11e9-9e55-09b606bf9310.png">

**Comment by dkulp** [comment]
Which is correct...   A controller behind the proxy cannot be pinged.

**Comment by keithsw1111** [comment]
I have restored the ping by having it make a root web page request on the controller through the proxy.
