### ISSUE TITLE
Printing visualized controller fails to print everything

### ISSUE THREAD

**Issue by TxBillbr** [smeighan/xLights#1649]
I have A PBScroller (2x3 P5), and three FP40D controllers with roughly 20 ports filled on each. I did a visualize -> print on each. Running version .40. There are three separate problems that exhibited with this.
1. The printout only printed a single page that stopped on PixelPort14 
  (the max that would fit on US 8.5x11 paper.) [bug.pdf](https://github.com/smeighan/xLights/files/3499334/bug.pdf)
2. All pixel ports after PixelPort5 were printed as empty.
  ![image](https://user-images.githubusercontent.com/44479016/62985643-e9e53900-bdfd-11e9-9bcb-e55bbea523db.png)
  Note the mixture of tune-to, and other controller props.
3. Visual presented all three controllers melded together.

This is fairly easily reproduced. 
1. Add three DDP controllers type F40D no-serial to the setup.
2. Go to the layout and assign something to half the ports on each controller
3. Save
4. Go back to setup and Visualize Controller for the first one. All the assignments will show on the screen. 
5. Right-click and select print.
6. Repeat for the other two controllers.

Here is my setup screen
![image](https://user-images.githubusercontent.com/44479016/62985696-1dc05e80-bdfe-11e9-8d8e-971544b6efa9.png)

I can break this into three issues if it is easier to manage for the team.

**Comment by TxBillbr** [comment]
I figured out why all three controllers were screwed together. I had 512 channels in each controller in setup. Using the auto start, the program got confused about where to assign stuff. So props assigned to the second controller was using channels from the first controller. I am not surprised that the printing code got very confused. So was I. The logical fix for this is to pop a warning dialog or do the red-background in the entry box when doing the layout if channels assigned will not fit in the controller they are assigned to...

Bill

**Comment by computergeek1507** [comment]
Channels overlap is a bigger issue that what this dialog is intended for. If you have a specific feature request please open a new enhancement request

**Comment by TxBillbr** [comment]
Hi Scott. Thanks for looking at this. I haven't tried to reproduce the issue on the latest versions. It may be a moot issue given some of the recent fixes.
