### ISSUE TITLE
Request - Model preview resize  - stretch along only x or only y

### ISSUE THREAD

**Issue by klyneshouse** [smeighan/xLights#165]
Would it be feasible to simply stretch existing models up/down or side to side when fitting into preview to accommodate irregular shapes?
Without having to custom model of course, which is still often difficult to get a "perfect fit" .

A good example would be using "arches" as doorway arch, I would like to elongate along y axis only.(see pic)

Another option/possibility for irregular shapes would be a 2nd custom option, similar to vixen preview that is pretty much "direct inject" onto the preview by ch#. 
I think this would be easier for simple low channel count objects.
I have a 12 ch mega tree star using dumb RGB+W strips, I cannot find a good fit for without having to do a custom model for it. 

![2015-04-05 10_59_58-xl4 beta ver 4 0 12 apr2](https://cloud.githubusercontent.com/assets/11807314/6997510/54227682-db83-11e4-90c5-1049cf479270.png)

**Comment by jcmarksafb** [comment]
I agree with that, and would add that it would be nice to be able to move the models with the arrow buttons as well as with the mouth. When you get a bunch of small models very close or on top of each other, it's hard to move them with the mouse.
 


     On Sunday, April 5, 2015 9:28 AM, klyneshouse <notifications@github.com> wrote:
   

 Would it be feasible to simply stretch existing models up/down or side to side when fitting into preview to accommodate irregular shapes?
Without having to custom model of course, which is still often difficult to get a "perfect fit" .A good example would be using "arches" as doorway arch, I would like to elongate along y axis only.(see pic)Another option/possibility for irregular shapes would be a 2nd custom option, similar to vixen preview that is pretty much "direct inject" onto the preview by ch#. 
I think this would be easier for simple low channel count objects.
I have a 12 ch mega tree star using dumb RGB+W strips, I cannot find a good fit for without having to do a custom model for it. —

**Comment by jcmarksafb** [comment]
haha, the mouse, not mouth
 


     On Sunday, April 5, 2015 9:41 AM, John Marksbury <jcmarksafb@yahoo.com> wrote:
   

 I agree with that, and would add that it would be nice to be able to move the models with the arrow buttons as well as with the mouth. When you get a bunch of small models very close or on top of each other, it's hard to move them with the mouse.
 


     On Sunday, April 5, 2015 9:28 AM, klyneshouse <notifications@github.com> wrote:
   

 Would it be feasible to simply stretch existing models up/down or side to side when fitting into preview to accommodate irregular shapes?
Without having to custom model of course, which is still often difficult to get a "perfect fit" .A good example would be using "arches" as doorway arch, I would like to elongate along y axis only.(see pic)Another option/possibility for irregular shapes would be a 2nd custom option, similar to vixen preview that is pretty much "direct inject" onto the preview by ch#. 
I think this would be easier for simple low channel count objects.
I have a 12 ch mega tree star using dumb RGB+W strips, I cannot find a good fit for without having to do a custom model for it. —

**Comment by smeighan** [comment]
This would be nice. It is an enhancment. Dave originally brought this up a few months ago. Dave is the person who created the first preview with the ability to drag and drop using the mouse.

**Comment by stevegiron** [comment]
Done
