### ISSUE TITLE
Visualize Controller - Add controller information to the screen and print.

### ISSUE THREAD

**Issue by TxBillbr** [smeighan/xLights#1650]
**Is your feature request related to a problem? Please describe.**
Since my controllers are all the same except for port and description (and of course connection), determining which print/spreadsheet belongs to what controller is a bit of spelunking exercise.

**Describe the solution you'd like**
It would be very helpful to have the appropriate information line from the setup window printed at the top of the page/top row of the spreadsheet. This would remove any ambiguity at a glance.

**Describe alternatives you've considered**
I tend to print, then go in the other room and scribble the controller name on the printout. I can also export and "clean-up" the spreadsheet(s). I use the printed sheets to work through my layout and connections as well as doing my power balancing. 

**Additional context**
This is clearly not earth-shattering, but would be a very nice addition to the visualize magic. Thanks for the consideration.

**Comment by computergeek1507** [comment]
Added 3e028b2954ee66b2a1e72d45332b165fdeca2321

**Comment by TxBillbr** [comment]
Scott, Thanks! that was fast.
