### ISSUE TITLE
Automatic Model Processing Problem 

### ISSUE THREAD

**Issue by temeyers** [smeighan/xLights#1651]
When I create a custom model it finds all of the bulbs properly and then manages to save the file whilst missing 300 or so pixels, video included to demo.   @keithsw1111 [https://youtu.be/QFkZyA0ZSME](url)

**Comment by temeyers** [comment]
I 668 Pixels the max for the Custom Model @keithsw1111 ?

**Comment by keithsw1111** [comment]
Can you send me a dropbox link to the video you were processing.

**Comment by temeyers** [comment]
Yes sir thank you 

https://www.dropbox.com/s/5q85oa7vzx7ak9g/Video%20Aug%2014%2C%202%2014%2048%20PM.mov?dl=0

**Comment by temeyers** [comment]
Just so you are aware this is a 9 foot snowflake and the camera is on the ceiling of the garage

**Comment by keithsw1111** [comment]
That is not the video that you were processing.

**Comment by temeyers** [comment]
Okay, im pretty sure it is, but either way v40 won’t go over 688 pixels with the auto map after you save it and then open your model it doesn’t matter how many nodes it found it will chop hundreds of nodes out and leave you with around 688, I reverted back to 39 and got it done, either way there’s an issue there. This model has about 900 nodes

**Comment by temeyers** [comment]
Okay right dumbass move, I uploaded the demonstration of the problem that was stupid on my part, I don’t have the file anymore I’ve resolved the problem for now, but there’s something up with it when you have to many pixels

**Comment by keithsw1111** [comment]
Without a file to test I cant confirm the problem and so cant do much about this.

Nothing changed in .40 that could have impacted this so closing.

**Comment by temeyers** [comment]
I’ll upload a whole a folder for you to look at on monday

**Comment by keithsw1111** [comment]
I dont need your whole folder. I need the video you were processing. The model file that was generated as well ... I need both.
