### ISSUE TITLE
Mac- Losing ability to click on anything after sequencing for about 10-20 minutes

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1652]
in the last few versions I notice I keep losing the ability to click and drag some items after a few minutes of sequencing, it only happens sometimes, maybe every other day but it forces me to have to close Lights and start over . this is on both my iMac and MacBook pro's running 10.14.6 and XLights 2019.40. I have noticed this in the last few releases, not exactly sure which release this started in. I made a quick video (had to shoot from my phone, sorry) so you can see what's going on. 

https://youtu.be/0erTJ23xjOA

**Comment by keithsw1111** [comment]
Without a way to reproduce the problem this is likely to be unresolved until a developer sees it ... and even then without a way to force it to happen it may be really hard to find and fix.

**Comment by bchiaino** [comment]
I agree 100%, figured I would put it out there hoping other Mac sequencers see this and try and reproduce also. It seems to have started once the OpenGL changes came into effect the last few versions like Daniel had mentioned a week or so ago
