### ISSUE TITLE
F16V2 upload failing

### ISSUE THREAD

**Issue by SniperMunyShotz** [smeighan/xLights#1653]
Was working with Bill in getting his E131 page and outputs uploaded to a f16V2 but was seeing issues with it.  Tried with controller defined and F16v2 and without and would have a 90 second or so delay when trying to upload with xlight complaining it could not find E131.HTM and outputs appears to be working, but would not actually push the data.
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3507603/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
Not sure ... I just uploaded 192.168.1.204 to a test V2 controller running v1.11 b006 ... maybe the problem is your firmware version.

**Comment by keithsw1111** [comment]
Closing due to lack of response.
