### ISSUE TITLE
Foreign charagter strip on FPP Connect 

### ISSUE THREAD

**Issue by lithgowlights** [smeighan/xLights#1654]
**Describe the bug**
 I noted an error that did not cause issues last year with FPP Connect and FPP 2.x. In the description of my universes I had a group of 4 Boscoyo 22" Spinners - yes I had the " in the description. On uploading to FPP the universe list never imported, with no real obvious cause of the error. It was not until I went and looked at the /home/fpp/media/config/co-universes.json to find the " in the description was causing the file to fail to be created properly.

Is there any way to check the upload for character errors like that, and simply remove it as the file is created (Or better yet move everyone to imperial as 55cm does not have the same issue lol)

**To Reproduce**
Add " to a item description, such as 22" snowflake

**Expected behavior**
Strip out the " character. That will not cause issues as it is only an item or group description, not a requirement

**Versions (please complete the following information):**
-FPP 3.0 and above
-xLights 2019.28 and above

**Additional context**

**Attachments**

**Comment by computergeek1507** [comment]
fixed b79c4d331ccc90c28302ec2a9fb12c1ff0521006
