### ISSUE TITLE
XSchedule crashing after a few hours of looping a few playlists

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1656]
I created 4 new FSEQ files and added them to XSchedule to loop to test long connectivity to the F48 for DavidP. I noticed each time I came back to my iMac to see if im still pinging the controller that XSchedule had crashed. It plays through definitely a few times so I don't believe is one of the FSEQ files crashing it being they all play fine for a while. 

I have attached the ZIP file it creates in the xlights folder when it crashes, Please let me know if you need any more info, I have about  10 of the rashes zip files being every time I try and run this it crashes after some time

I also attached a pic of the xschedule setup I have and the only change I make is to set XSchedule to MODES/MASTER/FPP BROADCAST so it triggers my 2 Pi's for my matrix screens
![Screen Shot 2019-08-17 at 9 03 49 AM](https://user-images.githubusercontent.com/40632971/63212137-01f2dc00-c0ce-11e9-8561-87b34424f5ae.png)
![Screen Shot 2019-08-17 at 9 03 43 AM](https://user-images.githubusercontent.com/40632971/63212138-01f2dc00-c0ce-11e9-8f0c-53a51e12fe6f.png)
[xSchedule_dbgrpt-4786-20190816T145509.zip](https://github.com/smeighan/xLights/files/3512021/xSchedule_dbgrpt-4786-20190816T145509.zip)

**Comment by keithsw1111** [comment]
Yeah ... looks like a leak in the ping which I have fixed by replacing it all with our new web access pattern so this should be fixed. I have also enabled the ping through proxy functionality.
