### ISSUE TITLE
Enh: FPP Connect - clear selection - only highlighted rows

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#1657]
When I go FPP Connect, I right click and select all. Can I select the top 10-20 whatever rows and unclick them? I tried Shift click to highlight  them and then right click, clear selection and it clears all of them. Can it be an option to clear all and perhaps clear selection only clears the highlighted rows?

**Comment by keithsw1111** [comment]
Did you try pressing the space bar after the shift clck?

**Comment by derwin12** [comment]
That just clears the first one .. unless I am doing it wrong?
![image](https://user-images.githubusercontent.com/4643499/63559204-43e0af80-c51e-11e9-84e5-634cc4bb9518.png)

**Comment by computergeek1507** [comment]
Added with 25b52a4ec16bda2d4d26588dd804db43ec7bfd6c
