### ISSUE TITLE
Batch render in V2 vs V1 for smaller size

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1658]
I notice if im in V2 in rendering my files save around 40MB now vs 1GB or so which is awesome but if I do a batch render they are all 300-400MB which is weird.

testing with one sequence here are my results V1 vs V2

V1
Save in xlights as normal the FSEQ file is 1.2gb.
Batch render in V1 the FSEQ file is 1.5GB.

V2
save in xlights as normal the FSEQ file is 4MB.
Batch render in V2 the FSEQ file is 350MB.

**Comment by keithsw1111** [comment]
I have tested this and it just isnt true ... I set to v2 batch render < 1MB. Set to V1 batch render >169MB. Changed back to V2 again batch render < 1MB. I would need evidence as I dont believe this is true.

**Comment by bchiaino** [comment]
no problem, ill do a video later tonight once im home. I am however on a Mac and you are on a pc im assuming so it may be a Mac thing. I will be home in 4-5 hours and ill test on both Mac and pc and make videos to show ya.

**Comment by bchiaino** [comment]
I see what's going on on my end, if I open a sequence make a small change and save the file size is 40MB but this is because I didn't render after I opened the sequence, once I render and save again then its 300MB which is what it should be
