### ISSUE TITLE
Enh: House and Model Preview to Maximize Outside of xLights Snap-to Windows

### ISSUE THREAD

**Issue by AJR214** [smeighan/xLights#1659]
In the snap-to window for House and Model Preview, there is a minimize and maximize button within xLights. If the preview window is moved outside of xLights, there is only a close button. Many of us work on 2 or 3 screens and like to have the preview window(s) on other screens. Currently, the window needs to be sized manually by dragging the edges.

This was brought up to Keith at the Expo during a class and he mentioned it would be looked into.

![Snap-In Window vs Pulled Out](https://user-images.githubusercontent.com/54226031/63220016-06120e80-c14d-11e9-9887-9c65d85d3a46.png)

**Comment by keithsw1111** [comment]
We cant add a maximise button but if you double click on your house it will maximuse

**Comment by AJR214** [comment]
Thank you Keith. FYI to those reading this... the double click your house preview bar at the top doesn't maximize the window to the screen (and the Minimize/Maximize right-click options are grayed out). However, if you double click anywhere inside the House Preview window, the window will maximize.
