### ISSUE TITLE
Unable to set Setup to network attached device

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#166]
Using OSX 4.0.14
I'm unable to set the setup tab to a network attached drive. Previously I was able to set the Images folder to a shared folder on a network mounted drive. 
Finder shows the shared and connected devices
However, the Setup / configure tab does not show the same devices during browse.

One screen shot is just Finder: The other is the Setup tab configuring the different folders. 
![screen shot 2015-04-05 at 10 46 54 am](https://cloud.githubusercontent.com/assets/10136122/6997652/3293ffb0-db81-11e4-8dec-5728811e3b8a.png)
![screen shot 2015-04-05 at 10 47 11 am](https://cloud.githubusercontent.com/assets/10136122/6997653/37fc39e0-db81-11e4-84e2-8d8a75f6b695.png)

**Comment by LightsOnHudson** [comment]
I did notice though, that the file chooser for when creating a new Musical Sequence, it does show all the network attached devices. So, the function or driver for selecting a folder, could be different than that of the Setup Tab Selection buttons to set the folders?

**Comment by LightsOnHudson** [comment]
This appears to be resolved. I was able to point to my network attached storage.

**Comment by stevegiron** [comment]
Thanks for the update. Closing issue.
