### ISSUE TITLE
Converted controller from zcpp to e131, deleted and readded zcpp, xlights crashed

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#1660]
**Describe the bug**
Had a previous config of ZCPP that i hit convert to e131 on,
Decided i wanted to go back to ZCPP, so deleted the controller and 
added a manual zcpp controller, (controller wasnt plugged in, so entered details manually)
 hit visualise, and crash report opened, 

*edit* Now xlights will not load, splash screen displays and disappears, but xlights doesnt open,

*edit* as i was working with controllers last, iv deleted xlights_networks.xml, and xlights will now open,
networks xml is bundled in this archeive,

**To Reproduce**
NA - Although it appears the e131 controller is still in the networks conf file,

**Versions (please complete the following information):**
 - OS: win10 64
 - xLights version 2019.41

**Attachments**
[xLights_dbgrpt-15536-20190818T222221.zip](https://github.com/smeighan/xLights/files/3513018/xLights_dbgrpt-15536-20190818T222221.zip)

**Comment by cathelest** [comment]
I restored my config files from the backup folder,

seems if i convert the zcpp to e131, delete it and readded zcpp, then click visualise all without hitting save, it will crash, guessing that as im not hitting save its not over-writting the conf, 
but the visualise button must read the conf? and as its still got the e131 line it must not like it,

If i save and reopen the config dialog and hit visualise it works fine,

**Comment by cathelest** [comment]
Just tested on 2019.43


If you add a ZCPP, as xlights_networks.xml hasnt been updated, and you hit visualise xlights crashes,

Maybe you can have the visualise also save to xlights_networks.xml before trying to visualise,

**Comment by keithsw1111** [comment]
Yeah i think i already have this fixed for .44
