### ISSUE TITLE
2019.41 breaks some groups in layout tab

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1663]
on my Mac and tested also pn my pc in .41 I noticed all of a sudden my house trim group was missing from all of my "ALL" and WHOLE HOUSE groups, I went back to .40 and everything is fine again

I go to .41 and add the "house trim" back in and save but when I reopen .41 'house trim" in any group I add it to is gone again. Not sure if its because its a group in a group but its only happening in ,41 as you can see in the video

https://youtu.be/Gvtt44HVxgI

I attached a packaged sequence too even though im sure you have a folder for me already, lol
[RUDOLPH.zip](https://github.com/smeighan/xLights/files/3517445/RUDOLPH.zip)

**Comment by keithsw1111** [comment]
Ok ... i think i know why this happened.

**Comment by bchiaino** [comment]
cool, shoot me any tests if you want and ill try on my pc. thanks Keith

**Comment by keithsw1111** [comment]
I think i have this fixed in .42

**Comment by bchiaino** [comment]
looks good in ,42, thanks Keith!
