### ISSUE TITLE
Enhancements to value curve popup window and sliders.

### ISSUE THREAD

**Issue by reelpilot** [smeighan/xLights#1665]
It would be useful when selecting a value curve for the resulting popup window to fully display within the screen. As it is now the widows are almost always partially cutoff and one has to always drag the value curve window into the screen's real estate. 

With regard to slider operation I would like to see the feature added where double clicking on a slider would return whatever the current value is to the default setting. This feature is used a lot in photo and video editing software and I would see this useful in xlights as well. 

Here's a short video illustrating the two enhancement requests. 

https://youtu.be/ZBLRig6DU2c

**Comment by keithsw1111** [comment]
Not going to make value curve dialog full screen but happy to make it bigger.

As for the second that is not possible as the UI framework does not support that.

In future please one request per issue

**Comment by reelpilot** [comment]
Will do in the future. Also I wasn't saying I want the value curve dialog box full screen or even bigger. I would just like the entire value curve box, at it current size, to open fully inside the existing window so it's not partially cutoff and I don't have to drag it into position each time. This likely has to do with running multiple monitors since when I did a quick test on my laptop everything seemed to open within the one screen. So I'm not sure if there is anything you can do for helping the box not be partially cutoff in multi monitor setups. However any help in this regard would be much appreciated.

**Comment by keithsw1111** [comment]
That makes more sense than the original bug report. Fixed for .44.
