### ISSUE TITLE
Aligning & Sizing Custom Models - Pixels are Offset

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#1666]
**Describe the bug**
When using the Match Size tool and Align tools, custom models appear offset when the # of pixels wide (x-axis) do not match between models. It is most noticeable when trying to match size & align models with both even & odd width values.

**To Reproduce**
1) Create 4+ models, each 1 row high and varying pixel widths (both even & odd values).
2) Select All > Right Click > Resize > Match Size
3) Select All > Right Click > Align > Align Horizontal Center
4) Note Results
5) Select All > Right Click > Align > Left
6 Note Results

**Expected behavior**
I expect all the pixels to be spread evenly across the space in alignment with their fellow models.

**Screenshots**
I'm submitting two screen-shots; first how I expect it to look, second how it actually looks.

Note in my screenshots: 
The top two models have the same # of pixels (35).
The 3rd model has 27 lights
The 4th model has 20 lights

![Good Alignment](https://user-images.githubusercontent.com/18503894/63381942-b0657e00-c367-11e9-8b48-3dc13740f642.png)
![Bad Alignment](https://user-images.githubusercontent.com/18503894/63381943-b0657e00-c367-11e9-964a-e4ffb1d2b810.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.42

**Additional context**
Single Line Model is not an option for me, but since I figure somebody will ask, I attempted the same test and discovered that, while Single Line models do align more appropriately, the single lines with less pixels are still shorter, despite "match-size" set to the larger string.

**Comment by keithsw1111** [comment]
This is because we match the size of the container but there are small differences in the actual end point locations. I have made a minor change in .43 which will improve it but it wont be perfect.

**Comment by jholmes09** [comment]
Thank you, I appreciate it :)

**Comment by keithsw1111** [comment]
Ok ... I think i have it working correctly ...
