### ISSUE TITLE
Bulk edit changes to non-selected effects and movement of multiple effects with arrow keys

### ISSUE THREAD

**Issue by reelpilot** [smeighan/xLights#1667]
When using the mouse to drag a selection box of multiple effects for bulk editing, the previously selected effect is also being impacted by the bulk edit despite not being selected. 

Also when selecting multiple effects and trying to move them with the keyboard arrow keys up and down, sometimes the effects won't move despite having open layers to move.

Attached video better illustrates the bugs. 

https://youtu.be/mp7_cyuaft0

[Bulk Edit.zip](https://github.com/smeighan/xLights/files/3527504/Bulk.Edit.zip)

**Comment by keithsw1111** [comment]
Interested bug ... its actually got nothing to do with bulk edit. When you select an effect and then click off the effect and then change a setting the setting still impacts the effect ... even though it doesnt look selected.
