### ISSUE TITLE
Resize on Layout tab

### ISSUE THREAD

**Issue by drakkar20d** [smeighan/xLights#1669]
The model resize on layout tab no longer seems to work, 

**To Reproduce**

1. Go to 'Layout Tab'
2.  select a number of models
3. Right click
4. select resize
5 select any of the choices , match height , match width or match size
6. nothing happens

**Expected behavior**
models should resize to chosen option in 5. above

No screen shot necessary , easy enough to test on your own windows pc 

**Versions **

 - xLights version  2019.43 (though hasn't worked for quite a few previous versions either)

**Comment by keithsw1111** [comment]
This is only partially true and suffers from lacking specifics. I have fixed what i can see but if you have specific issues once .44 comes out then please raise a new issue with those specifics.
