### ISSUE TITLE
Models window Alphabetizing?

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#167]
Using OSX 4.0.14
Unzipped 4.0.14 this morning and the default installation has a few models in it - :) . 
I created a new model called 2x3 - my Horizontal Matrix.
It put the model at the TOP of the models window. I assume that the Models screen is alphabetizing the names automatically? 
I ask this because in the Preview window / Models screen, you have to use this screen to move models up or down on the Sequencer window. If it is going to alphabetize automatically, that may mess up or not be in the same order as the Sequencer window.

I'll open a different enhancement to be able to move models up or down on the Sequencer window without having to go to the Models / Preview window to move them up or down.

**Comment by AzGilrock** [comment]
You don't use the Preview screen to reorder models in the Sequencer page.
You re-order the display elements using the Sequence Elements window.  Goto View -> Windows if you don't see it.  No enhancement needed.
![elements](https://cloud.githubusercontent.com/assets/2024669/6998436/a707c47e-db97-11e4-99df-2c15ee21360f.jpg)

**Comment by LightsOnHudson** [comment]
Correct. Thanks.
