### ISSUE TITLE
3 Channel RGB Models Off in Layout Tab

### ISSUE THREAD

**Issue by RevRob** [smeighan/xLights#1670]
**Describe the bug**
I opened xlights today after doing the last update and noticed my tombstones and singing pumpkin looked funny in the layout tab. They have random pixels out of place. If I look at the model data they are fine but the wiring diagram is off and on the layout tab. These are 3 channel RGB nodes but not sure why that would change anything. 

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.43

![Layout](https://user-images.githubusercontent.com/54488961/63644598-4542e100-c6b2-11e9-8466-3a034320a0b0.jpg)
![Tombstone 7](https://user-images.githubusercontent.com/54488961/63644599-48d66800-c6b2-11e9-99be-7cb8f164365a.png)
![Tombstone](https://user-images.githubusercontent.com/54488961/63644600-51c73980-c6b2-11e9-9466-6efbb8613625.jpg)

**Comment by keithsw1111** [comment]
Fixed
