### ISSUE TITLE
Singing Faces defintions not working correctly

### ISSUE THREAD

**Issue by gleaminx** [smeighan/xLights#1671]
Face definitions not rendering correctly during sequence.

**To Reproduce**
Video showing issue:
https://youtu.be/qjrsbhiY3i0

**Expected behavior**
Face definition pixels should render during sequence correctly, not randomly.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version [e.g. 2019.43]

**Additional context**

**Attachments**
https://www.dropbox.com/s/aydl2h34xjq8j52/EZ%20Pirates%20Medley.zip?dl=0

**Comment by keithsw1111** [comment]
This is actually a custom model problem in .43.

**Comment by gleaminx** [comment]
Thank you Keith.

**Comment by gleaminx** [comment]
Keith, I figured out the problem.  I had the singing faces set as per preview under layer settings.  If I changed them to default and render the sequence.  BOOM, they are fixed!

Thanks,
Justin

Sent from Mail for Windows 10
