### ISSUE TITLE
V43 messing models up in layout tab

### ISSUE THREAD

**Issue by TKW1969** [smeighan/xLights#1672]
**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by TKW1969** [comment]
Models are changing in version 43 they are good in v42. see attached pictures. I also attached RGB files.
![star in 42](https://user-images.githubusercontent.com/11807646/63654716-e332bc00-c743-11e9-8862-52186cc1205d.JPG)
![star in 43](https://user-images.githubusercontent.com/11807646/63654720-e5951600-c743-11e9-8075-453040b15560.JPG)
![singing faces in 42](https://user-images.githubusercontent.com/11807646/63654722-e9289d00-c743-11e9-8bf8-40d762c6fcba.JPG)
![singing faces in 43](https://user-images.githubusercontent.com/11807646/63654724-ec238d80-c743-11e9-9adb-3779e2ad839e.JPG)
[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/3538522/xlights_rgbeffects.zip)

**Comment by keithsw1111** [comment]
Known and fixed.
