### ISSUE TITLE
Custom model with repeating channel numbers displayed wrong

### ISSUE THREAD

**Issue by ItsFitz** [smeighan/xLights#1674]
**Describe the bug**
Viewing Custom 2D Model Data and clicking OK will enlarge the model on the Preview.
Also, Custom 2D models with the same number (like all 1's) will have the one of the repeating numbers scaled out (offset) from the rest of the nodes in the preview.   If you alternate with node numbers 1 and 2, then 2 pixels will be offset from the other nodes.

**To Reproduce**
1. In Layout tab, add Custom model.
2. Select Model data for a 5 by 5 by 1 model size
3. Select Active (but not Auto increment) and create a square with all 5 nodes on each side having the number 1.
4. Click OK.
5. Error:  The upper left node of the square is much higher from the rest of the pixels.
To make matters worse, Edit the model data again, don't change anything, just clik OK, and the model view enlarges.

**Expected behavior**
All nodes should stay like the model data create and the model should not re-scale each time it is updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/45466718/63661375-ec417e80-c77f-11e9-97e0-1e9ee6230e34.png)
![image](https://user-images.githubusercontent.com/45466718/63661383-f2cff600-c77f-11e9-8bb8-f87789f23d2d.png)
![image](https://user-images.githubusercontent.com/45466718/63661394-fe232180-c77f-11e9-8a61-bd91bbd51b7e.png)
![image](https://user-images.githubusercontent.com/45466718/63661397-01b6a880-c780-11e9-87b6-1ae56a0676f1.png)

**Versions (please complete the following information):**
 - OS: Issue happens with both Windows 10 and MacOS 10
 - xLights version 2019.43 (last version I tested was 2019.34)

**Additional context**
None.

**Attachments**
- No crash associated with this issue.

**Comment by keithsw1111** [comment]
Known problem which has already been fixed.
