### ISSUE TITLE
Have House Preview window default to 3D if xLights Layout tab is set to 3D

### ISSUE THREAD

**Issue by tomhammond** [smeighan/xLights#1676]
If I create a layout in 3D (enabling the 3D checkbox), then create a sequence, then open the House Preview window, it defaults to 2D.  I must manually right-click the House Preview window to display it in 3D.  This must be done each time that I open xLights, even if the 3D checkbox is set in the Layout tab.

It would be helpful if the House Preview window defaults to 3D view if the Layout 3D checkbox is set.

Thanks for considering this feature!

Tom Hammond
tominohio@gmail.com

**Comment by keithsw1111** [comment]
This has already been implemented. Will be in .44.
