### ISSUE TITLE
Distortion on Virtual Matrix 

### ISSUE THREAD

**Issue by temeyers** [smeighan/xLights#1679]
**Describe the bug**
When outputting to a virtual matrix there is distortion at the top of the matrix that appears to be effects from other models crammed into about 5 lines across the top. @dkulp I am not sure if this is limited to Macs I have not tried it on my other Mac however this Mac has the iris pro graphics if that helps 

https://youtu.be/cl1j1wxCY2I

**To Reproduce**
Create a virtual matrix and be sure that other models have data on them as well, then verify that you have no channel overlap issues that could cause the issue. The effect does not occur if there is no data on other models. 
**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**
Please see youtube video 
https://youtu.be/cl1j1wxCY2I

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
Mac OS 10.14
 - xLights version [e.g. 2019.37]
2019.43

**Additional context**

**Attachments**
https://youtu.be/cl1j1wxCY2I

**Comment by keithsw1111** [comment]
Looks like a start channel issue.

**Comment by temeyers** [comment]
The start channel correspondes to the proper start channel, i thought this
at first as well and then went as far as to ensure it began in its own
universe as well and tried that also. Same effect promise

**Comment by keithsw1111** [comment]
I would need evidence ... because it looks exactly like i would expect it to if that was the problem.

**Comment by temeyers** [comment]
Agreed let me gather what i can sir

**Comment by temeyers** [comment]
I believe 3.1 checking and updating if so now, will report findings
