### ISSUE TITLE
Enhancement - Move models up / down in Sequencer window

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#168]
It would be nice to have the ability to move models up or down on the sequencer tab without having to go to the preview window / models and move them up or down.

**Comment by smeighan** [comment]
i agree a click and drag models in sequencer window would be nice.

we will see when we might be able to do such a thing

**Comment by AzGilrock** [comment]
We already provide a way to do it and people shouldn't need to reorder very often.

**Comment by LightsOnHudson** [comment]
Thanks Sean. I have been using the Move Up / Down from the elements display window for now. However; i found a new issue that I'm reporting that adding all my models to the sequencer window through the ADD Elements. The sequencer does not allow you to scroll to those that are not visible off the bottom of that screen. You have to go back into the display elements window and then out then you can see them / scroll to them.

**Comment by keithsw1111** [comment]
I am going to close this issue for 2 reasons:

1. The display elements window is now drag and drop.
2. The display elements window can be left open at all times ... like all the other panels ... so there is no need to open anything up if you want to dedicate some screen real estate to this. 

The complexity of adding drag and drop into the sequencer itself does not seem to offer any significant payoff that is worth what would be a huge amount of code complexity.
