### ISSUE TITLE
Audio Track 5.1 Output From Sequence

### ISSUE THREAD

**Issue by Kamal-Sonani** [smeighan/xLights#1680]
I've audio track with 5.1 channel.

Firstly I tried with Right & left channel to verify that audio output is sterio or mono.

I got singel output merged with Right & Left channel.

Is if possible to get 5.1 output from xlights?

◆ can i trigger other software like VLC player ? At the starting of sequence?

Using that it can be helpful at this moment.

**Comment by keithsw1111** [comment]
We do not support anything more than stereo output at this time. Its on the todo list but not high on the list.

**Comment by Kamal-Sonani** [comment]
I only get mono output .
What should i check for cross verify?

**Comment by Kamal-Sonani** [comment]
Confirmed in new version that audio output is stereo.
