### ISSUE TITLE
ON command color change error

### ISSUE THREAD

**Issue by lithgowlights** [smeighan/xLights#1682]
**Describe the bug**
Changing the color on the On effect not working on sub models. V 44 only, 43 and earlier appear to work correctly 

**To Reproduce**
Place on effect at the start of a sub model with White and Red turned on. 
On effect is white as expected.
Deselect white on the color panel but item stays white. 
Any changes to colors in any way on the sub models using the ON command simply don't work as expected

**Expected behavior**
When white is deselected the item should turn red as it does on groups, and the individual items, but this is not the case on the sub models

**Screenshots**

**Versions (please complete the following information):**
2019.44

**Additional context**
https://youtu.be/WG7mHFaX-G0
This is a video of the issue in action with the ON and Bars effects showing the issue at strand and sib-model level, but not on the normal item.

**Attachments**

**Comment by keithsw1111** [comment]
The problem with this bug report is it assumes that because you see it it occurs in all situations with the attributes you describe.

This is why we prefer to have a sequence attached with a specific model that has the issue. That lets us reproduce it quickly and fix it quickly.

Not doing so adds 10 mins to 5 weeks to the resolution timeframe.

That is why we ask for these things.

**Comment by leelindquist** [comment]
I have reproduced the problem using the built-in matrix model. It's also not just isolated to submodels, it is happening with on effects placed at the strand level as well.

If you haven't identified it yet, a video of how I set it up is linked below:

https://youtu.be/yqB7bISpA44

**Comment by lithgowlights** [comment]
More information and a video can be found here:

https://youtu.be/WG7mHFaX-G0

It also affects the bars, and likely more effects and it appears as though the color selection is not done "live" as it was before, but requires the update button to be pressed on the strand/sub model level to alter the color selections, but the selections are done "live" on the actual model level
