### ISSUE TITLE
Erroneous scale adjustment

### ISSUE THREAD

**Issue by Hilights360** [smeighan/xLights#1683]
When adjusting models, especially by manually entering X, Y and Z positions, the X, Y and Z scaler autonomously sets to zero. The model will disappear leaving only the gimbal in the design preview and will disappear entirely in the sequence previews. It currently can be temporarily worked around by re-entering the scale after the model is moved.

**Comment by keithsw1111** [comment]
i cannot reproduce this

**Comment by Hilights360** [comment]
My original issue is lacking enough specificities. From a new show folder with a generic network, open the setup tab and drop a DMX fixture:. The initial scale will be set by the cursor. When you change the fixture to Moving Head 3D, the scale goes to zero and the fixture will disappear:


![DMX Error 1](https://user-images.githubusercontent.com/35340265/64026481-da0f6980-cb0c-11e9-8af1-e5d6d34257bb.JPG)

When the scale is manually reset, the fixture will reappear:
![DMX Error 2](https://user-images.githubusercontent.com/35340265/64026549-fb705580-cb0c-11e9-8602-94d11fd9bff1.JPG)

If you manually enter a new coordinate, the fixture will disappear again:
![DMX Error 3](https://user-images.githubusercontent.com/35340265/64026609-180c8d80-cb0d-11e9-9df1-dfa7dd391032.JPG)

It also happens when the DMX Style is set to any other setting from the initial DMX Style "Moving Head Top"  used by default when a new DMX fixture is placed in the preview. It seems to do this in both 2D and 3D views.
