### ISSUE TITLE
Lost Models in Layout and House Preview with MAC xlights-2019.44

### ISSUE THREAD

**Issue by Jacalynmal** [smeighan/xLights#1684]
**Describe the bug**
Upgraded to xlights-2019.44 for MAC and I lost the ability to view 6 of my models.  One is a custom model and the other 5 are imports from Boscoyo (ghosts).  The physical models are listed with all configurations in layout and the sequence file but do not show on the layout screen or the house preview in sequence tab.  I tried to go back to previous versions to see if they show up again but they do not.
![Dancing Skeleton Missing.

![Dancing Skeleton Missing](https://user-images.githubusercontent.com/54683818/63966688-6a907000-ca61-11e9-88dd-616313eac0d9.jpg)

**Comment by keithsw1111** [comment]
try looking at the z scale ... if it says inf then change it to 1

**Comment by keithsw1111** [comment]
failing that send us the files

**Comment by Jacalynmal** [comment]
Thanks Keith - that fixed it.
