### ISSUE TITLE
Text Effect with Downloaded Prop (Boscoyo Megastone Matrix)

### ISSUE THREAD

**Issue by BrianRees** [smeighan/xLights#1686]
I downloaded the Boscoyo MegaStone Matrix.  I added a text effect to the RIP Sub Model, and it doesn't save the text.  

I copied an older text effect from a different sequence,  When I pasted that effect to the downloaded; the text was there, but I wasn't able to change it.  ( I could change it by editing the  XML )

**Comment by keithsw1111** [comment]
this has been already fixed for .45
