### ISSUE TITLE
Incorrect transition rendering on old sequence

### ISSUE THREAD

**Issue by MikeSoukup** [smeighan/xLights#1687]
**Describe the bug**
I opened up a sequence for the first time this year (last time the sequence was saved was with 2018.46) and some of my in & out transitions aren't rendering properly.  Specifically the From Middle transition on a Living Light Shows 34" snowflake.  It looks like it's originating from and collapsing to the bottom of the model, not the middle.  If I change any properties of the transition (type or time) and then go back to my original properties, it renders correctly.

**To Reproduce**
Will provide a sequence via PM.

**Expected behavior**
I'd expect it to render correctly without adjusting the settings.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.46

**Attachments**
Will provide a sequence via PM.

**Comment by keithsw1111** [comment]
I havent seen a sequence

**Comment by MikeSoukup** [comment]
I thought someone would ask me to PM it to them.  I didn't know who to send it to.  I can get it to you this evening.

**Comment by MikeSoukup** [comment]
... I don't see any mechanism for sending a PM.  How do I send it to you?

**Comment by AzGilrock** [comment]
Its best to not give us an entire sequence.  Recreate the problem in a small sample sequence and post it here for all developers to have the opportunity to fix.

**Comment by MikeSoukup** [comment]
[transition bug.zip](https://github.com/smeighan/xLights/files/3577206/transition.bug.zip)

Here you go.  The transition works correctly on Snowflake Garage 1 and not on Snowflake Garage 2.  The difference is that I edited the transition settings on the first one using 2019.46, but did not edit any settings the second one since running on 2018.46.

I dug into the XML a bit and it looks like the effects are identical except the ones that work have the parameter `T_SLIDER_In_Transition_Adjust=50`.  Perhaps that value needs to default to 50 if it's missing.

**Comment by keithsw1111** [comment]
I looked at the code and the history and it always defaulted to zero including back then. on that basis the bug was last year not saving the value but it saves it now so i consider this resolved.

**Comment by MikeSoukup** [comment]
Just because I'm curious... why do you think the transition rendered correctly (or I guess a better word is differently) with 2018.46 with the parameter missing if it was using a value of 0?

**Comment by AzGilrock** [comment]
xLights is like the stock market.  Past performance cannot predict future results. :)
