### ISSUE TITLE
Skip Size not working correctly for Marquee on Single Line

### ISSUE THREAD

**Issue by MikeSoukup** [smeighan/xLights#1688]
**Describe the bug**
The Skip Size parameter doesn't appear to work correctly when Marquee is applied to a Single Line.  It should increase the number of off pixels between the lighted ones, but it looks like it's rendering two separate groups of lighted pixels that start at opposite ends of the Line.  It gets more apparent when the Speed is > 0 and the lighted pixels move in both directions instead of just one.

**To Reproduce**
1. Create layout with a Single Line model
2. Apply Marquee effect to model
3. Set Render Style to Default
4. Keep increasing the Skip Size

**Expected behavior**
Gap between lighted pixels should be equal to the Skip Size.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.46

**Attachments**
https://www.dropbox.com/s/llcg5gzxzzey0c6/marquee.zip?dl=0

**Comment by keithsw1111** [comment]
Not q bug ... this is intended behaviour. To get what you want oversize the buffer by setting the top to 200.

**Comment by dkulp** [comment]
On the single line model, using the Single Strand/Skips effect likely will be close to what you want.

**Comment by AzGilrock** [comment]
I meant to take a look at this because I use the Marquee on Single Lines all the time in my show.  A Marquee is meant to be drawn as a square so you end up with the top and bottom of the square drawn on the same line.  Maybe its an odd/even number of pixels thing that I haven't seen before.  In any case it doesn't sound like something will be changed in code.  Use Dan's suggestion.

**Comment by MikeSoukup** [comment]
I'll take a look at my sequences tonight to see what works best.  I think I've looked at Single Strand before and it was lacking something, possibly the ability to set the starting offset.  Or maybe the speed wasn't as easy to configure.

I assume something changed in the code since last year, since this rendered the way I wanted it to with the 2018 versions, but it's different now without any changes to my sequences.  I also use Marquee on Single Line a lot and have never seen this behavior before.

**Comment by AzGilrock** [comment]
If the behavior changed that's something we would want to look at.  Its easier if you can do the research and tell us to compare version 2018.xx with 2019.xx instead of us trying to guess at the versions.

**Comment by MikeSoukup** [comment]
Same versions as the other issue that I reported.  old is 2018.46, new is 2019.46.  I'm just dusting off my sequences from last year and updating them for this year, so this is the first time I'm using the 2019 versions.

**Comment by AzGilrock** [comment]
I traced this down to working in 2019.11 and fails in 2019.12.  The offending code appears to be a fundamental change to how alpha is handled.  I commented out the new code and Marquee works like it should again.

`void RenderBuffer::SetPixel(int x, int y, const xlColor &color, bool wrap, bool useAlpha)
{
    if (wrap) {
        while (x < 0) {
            x += BufferWi;
        }
        while (y < 0) {
            y += BufferHt;
        }
        while (x > BufferWi) {
            x -= BufferWi;
        }
        while (y > BufferHt) {
            y -= BufferHt;
        }
    }
    
    // I dont like this ... it should actually never happen
    if (x >= 0 && x < BufferWi && y >= 0 && y < BufferHt && y*BufferWi + x < pixels.size())
    {
        /*if (color.alpha == 0)
        {
            // transparent ... dont do anything
        }
        else if (useAlpha && color.Alpha() != 255)
        {
            xlColor pnew = color;
            xlColor pold = pixels[y*BufferWi + x];

            xlColor c;
            int r = pnew.red + pold.red * (255 - pnew.alpha) / 255;
            if (r > 255) r = 255;
            c.red = r;
            int g = pnew.green + pold.green * (255 - pnew.alpha) / 255;
            if (g > 255) g = 255;
            c.green = g;
            int b = pnew.blue + pold.blue * (255 - pnew.alpha) / 255;
            if (b > 255) b = 255;
            c.blue = b;
            int a = pnew.alpha + pold.alpha * (255 - pnew.alpha) / 255;
            if (a > 255) a = 255;
            c.alpha = a;

            pixels[y*BufferWi + x] = c;
        }
        else
        {*/
            pixels[y*BufferWi + x] = color;
       // }
    }
}`

**Comment by AzGilrock** [comment]
I really think it should be changed back to require the useAlpha flag to get the new behavior because we might not have been setting the alpha channel everywhere properly.
