### ISSUE TITLE
2019-46 AppImage complaining about libgtk3.so.0

### ISSUE THREAD

**Issue by m00dawg** [smeighan/xLights#1689]
**Describe the bug**
It started on 2019.42 but the latest also seems to have the issue where trying to start xLights using the AppImage throws a libgtk3 error:

tim@lindawg ~ $ /opt/appimage/xLights-2019.46-x86_64.AppImage 
./src/common/stdpbase.cpp(62): assert ""traits"" failed in Get(): create wxApp before calling this
./src/common/stdpbase.cpp(62): assert ""traits"" failed in Get(): create wxApp before calling this
/opt/appimage/xLights-2019.46-x86_64.AppImage: symbol lookup error: /tmp/.mount_xLighte5t9Rd/usr/bin/../lib/libgtk-3.so.0: undefined symbol: g_log_structured

2019.41 works, although I'm having issues saving model updates on that version which prompted me to try and get 42 or newer working.

This is on Linux Mint 18.3 although the error seems to be related to xLight's built-in libgtk from the AppImage pack in looking at the error.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Grab a copy of the xLights 2019.46 app image.
2. Make the file executable and put whereve you put AppImages (in my case it's /opt/appimage)
3. Attempt to open as a non-root user (e.g. /opt/appimage/xLights-2019.46-x86_64.AppImage)

**Expected behavior**
xLights starts up

**Screenshots**
tim@lindawg ~ $ /opt/appimage/xLights-2019.46-x86_64.AppImage 
./src/common/stdpbase.cpp(62): assert ""traits"" failed in Get(): create wxApp before calling this
./src/common/stdpbase.cpp(62): assert ""traits"" failed in Get(): create wxApp before calling this
/opt/appimage/xLights-2019.46-x86_64.AppImage: symbol lookup error: /tmp/.mount_xLighte5t9Rd/usr/bin/../lib/libgtk-3.so.0: undefined symbol: g_log_structured

**Versions (please complete the following information):**
 - OS: Linux Mint 18.3 (Based on Ubuntu 16.04)
 - xLights version 2019.46 (though versions as old as 2019.42 may have this issue)

**Additional context**
I can try to compile from the source though have been using AppImages for qutie a while instead since they seem to work a lot better. I was running into dependency issues on some of the later builds last time I tried to fully build from source.

**Attachments**
N/A

**Comment by cjd** [comment]
There looks to be some missing libraries in appimage since moving to gtk3
While I figure that out I've moved the appimage build back to gtk2
I've uploaded a replacement 2019.46 appimage to 
https://www.adebenham.com/wp-content/uploads/xlights/xLights-2019.46-x86_64.AppImage
Can you give that a test for me?

**Comment by m00dawg** [comment]
+1

w00t! That did it, thanks Chris!
