### ISSUE TITLE
Bug? - xml not saving -(fseq is)

### ISSUE THREAD

**Issue by klyneshouse** [smeighan/xLights#169]
When I hit "save" it appears to make a xml and a fseq by default I think.
I ran into this twice yesterday in 2 different show folders, and am pretty sure its probably user error.
After about an hour I finally recreated in a 3rd show folder this morning but not real sure what was different. I will try to narrow it down to exact steps.

The initial create, edit and first saves make both a FSEQ and a XML as expected.
Simple whole house sequence ~ 12K channels, 25ms with audio.

As I was updating a sequence saving multiple times. (just clicking save).
If I close and re open xlights, the only xml available was the original first saved.
While the fseq was updated to the last save and played in preview fine.

Time stamps on the files are different. 
As if the xml is locked by a process when I am trying to save ??.

**Comment by LightsOnHudson** [comment]
Which version were you using?

**Comment by klyneshouse** [comment]
4.12

**Comment by smeighan** [comment]
can u try the current 4.0.16, i cant duplicate this behavior

**Comment by LightsOnHudson** [comment]
I just used OSX 4.0.16 and the FSEQ and XML had the same data. I closed Xlights after adding data, and opened that version and it had my changes in it.

**Comment by stevegiron** [comment]
Klyneshouse, I'm helping sort the issues and determine which issues are still valid. 
As of May-14 we are version 4.0.31. Is this issue still occurring?

**Comment by klyneshouse** [comment]
I finally got back into this and with 4.0.33 I had the same thing happen again.
2nd and subsequent manual saves during a session will not update the xml.
 
After closing and reopening the sequence editor, its only the "first" save that comes up.
I will try to get an exact repeatable method in the next days, but seems if its playing in preview while saving it makes it happen.

**Comment by stevegiron** [comment]
I think we can close this one now. Can you confirm klyneshouse.

**Comment by klyneshouse** [comment]
Sorry guys I have been distracted with pyro lately.

I went and grabbed 4.1.10 today.

 

Seems if I do this:

 

Create a new sequence.

Add one effect.

Save as new name. (both xml and fseq are created)

 

Open the layout tab, open the new sequence, and play.

 

Then back to sequencer tab, add 2 more effects, hit file +save, shows saving a fseq at bottom.

But the xml does not save. (note timestamps are off in attachment)

 

Close xlights completely and reopen sequence,  only 1 effect is there.

In layout (which I guess plays the fseq?) its all intact, It plays all 3 effects..

 

I realize now this is sort of a “don’t do this” scenario, but  hate to see others loose a few hours because they forget to stop it in  “layout” tab.

 

Looking forward to seeing you guys in Ft Worth next weekend.

 

 

Klyne
