### ISSUE TITLE
Xlights Crashing during rendering - 2 different PC's - New PPD sequence

### ISSUE THREAD

**Issue by jefft0825** [smeighan/xLights#1691]
At the same point during rendering, xlights crashes on 2 different PC's - 1 of them is a brand new computer build we just completed last week.    

xLights_dbgrpt-3976-20190901T112216
xLights_dbgrpt-11280-20190901T111724
xLights_dbgrpt-1776-20190901T111540
xLights_dbgrpt-780-20190901T111306

**Comment by keithsw1111** [comment]
None of these are debug reports ... they are just file names.

**Comment by keithsw1111** [comment]
This is fixed in 47
