### ISSUE TITLE
F16v3 2.52 ZCPP String Ports doubling/errors

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#1692]
This has also been posted on Falcon Forums, as wasnt sure if its a controller or xlights issue,

Xlights 2019.46

I realise ZCPP is still new and in the works, but thought best to post an issue,
I have setup a F16v3 with 2.52 firmware (was also happening on 2.51)

When using ZCPP with Xlights, and you output to lights, the outputs are doubled with a bunch of incorrect string lengths, brightness settings etc, but the status page is correct,

The layout is just a test layout, with 100 nodes on each controller port,

Thanks

See attached.

![xlights](https://user-images.githubusercontent.com/52036639/64109323-8b8af500-cdc2-11e9-97b7-8e36cb1f0660.png)
![statuspage](https://user-images.githubusercontent.com/52036639/64109328-8f1e7c00-cdc2-11e9-9282-1aab136521c3.png)
![stringports](https://user-images.githubusercontent.com/52036639/64109330-8fb71280-cdc2-11e9-8321-b17f63c71aa3.png)

**Comment by keithsw1111** [comment]
How do i reproduce it though?

**Comment by cathelest** [comment]
This is a basic test setup iv done,

Setup Tab
Added f16 ZCPP (just the ipaddress and name) (192.168.1.50 f16)

Layout Tab
Added 16 single light strings of 100 nodes each,
On each string, iv gone thru and selected the controller name, and then the bottom port hightlights red, and iv set the port,
(Iv also bulk edited the brightness to 30%)

Sequence
Made a basic colourwash sequence and output to lights.
The attached screenshots are the outcome,

Maybe i can show you on zoom if your free?

**Comment by cathelest** [comment]
Uploaded the test show folder and test sequence, not sure if it will help though,
[Test.zip](https://github.com/smeighan/xLights/files/3566276/Test.zip)

Alternatively, let me know if you want me to do a video recording, or meet up on zoom,
Thanks

**Comment by keithsw1111** [comment]
Maybe you can show me Friday night

**Comment by keithsw1111** [comment]
If this is a bug this is a falcon firmware bug as the main page shows the ZCPP outputs correctly.
