### ISSUE TITLE
Feature Request: xSchedule Events from Raw UDP String

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#1694]
**Describe the solution you'd like**
I would to create xSchedule Events that are triggered when the program receives a specific UDP string on a specific port, both of which I specify. 

For example, I could specify that if the string "play_h" arrived on port 2200, xSchedule would trigger an event that played my Halloween sequence.

**Describe alternatives you've considered**
There are other input protocols available (such as sACN) but that often requires a specific header and packet structure which is much bulkier than simply sending a simple 8-bit string.

**Additional context**
This opens up xSchedule to be triggered by a wide variety of programs, not just lighting systems that output sACN.

**Comment by keithsw1111** [comment]
Why not just use one of the many other event protocols there. There does not seem to be any need to invent yet another one given many of them are super simple and do everything you need. There is the Artnet triggers, FPP events, e131/Artnet data, OSC ... all of which are to varying degrees established standards.
