### ISSUE TITLE
xSchedule SMS Plugin Crash logs from 09.04.19

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#1696]
**Versions (please complete the following information):**
 - OS:
Win 7 32 bit   Yes, using an old computer to do the SMS function.  
 - xLights version
2019.46
**Attachments**
Sent the crash logs to wetransfer with your 1111@hotmail address.  Check the e-mail for the link to download.

Sorry, Drop Box is a hog with our current business accounts, and adding more will make it worse.

**Comment by keithsw1111** [comment]
Closing this one as we dont need three cases.
