### ISSUE TITLE
GECE single strand

### ISSUE THREAD

**Issue by Tom19669** [smeighan/xLights#1699]
**Describe the bug**
I have 4 renard 'espixelsticks' powering 4 strings of 63 'node' GECE lights.  The 1st 3 strings run fine, the 4th does the same pattern in reverse and using defaults lights up 2x the nodes the other strings are lighting up.
**To Reproduce**
take 4 renard espixelstick controllers (e 1.31), setup 1-4, on the layout create a group (Roof), add 4 string models "along the roof"
[Xlights issue.docx](https://github.com/smeighan/xLights/files/3584948/Xlights.issue.docx)
, in sequencer, do a simple animation (single strand) select 'all colors', and in preview windows AND hallway (I have all 4 strings running down hallway approx 60') the 1st 3 strings run fine, the 4th is really "OFF".  I have started over several times, and from each end of the preview, no luck, the 4th string will not cooperate.... BTW, I might be doing something wrong... this is my 1st shot at this!!

**Expected behavior**
just want the lights to 'chase' together from end to end; ie. all lights red, then start at one end and turn blue in a chasing manner, then next color, etc.

**Screenshots**
see attached screen shot (
[Xlights issue.pdf](https://github.com/smeighan/xLights/files/3584975/Xlights.issue.pdf)
, especially the last one it shows BOTH line 3 and 4 merging into right corner of house... they should be chasing like line 1-3 do.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version [2019.46 64bit]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
Did you check your espixelsticks settings? Does it work correctly with the espixelsticks built in test mode?

**Comment by keithsw1111** [comment]
Not convinced this is a bug ... it sounds like a setup issue. I suggest you post in forums or facebook. Feel free to reopen if there is evidence that there is a software problem.
