### ISSUE TITLE
Movine Models

### ISSUE THREAD

**Issue by jcmarksafb** [smeighan/xLights#170]
Would it be possible to move the selected models with the arrow keys as well as the mouse? For example I have a singing tree, it has 8 models to it, the outline, eyes open/closed and 5 mouth movements which are separate models. Once all of them are sized and placed within the outline, it is next to imopssible to move say just the eyes open or mouth movements exactly where  you want them. When you click on any of them the tree outline is picked.

**Comment by LightsOnHudson** [comment]
What about the Layers within the model? Will all the Layers move with the model as well? 

What if you have a model with 4 layers in it, and another model with 5 layers in it. And you DRAG the model with 4 to the 'middle' of the model with 5 layers, will it insert there and all the layers below the insert point now attach to the new model? Or will the model just snap to the bottom of the layer stack?

Moving models, and moving Layers - separate things?

**Comment by stevegiron** [comment]
The ability to move a model with the arrow keys now exists.
