### ISSUE TITLE
.46 - model preview changes when I go to save the preset

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#1700]
This is not a big deal as the end result is fine, but I have a pinwheel effect that I want to save as a preset. In the model preview it shows fine but once I go to New Preset, it switches in the model preview to just be a single(?) pinwheel.

![image](https://user-images.githubusercontent.com/4643499/64476140-55020100-d159-11e9-8e1b-22bf3cc5e128.png)

![image](https://user-images.githubusercontent.com/4643499/64476114-03597680-d159-11e9-98a2-f3f97b75ef96.png)
![image](https://user-images.githubusercontent.com/4643499/64476116-0bb1b180-d159-11e9-92de-80199027b491.png)

**Comment by keithsw1111** [comment]
I just tried it and it seemed to work. Can you make a video of the problem

**Comment by derwin12** [comment]
I cant reproduce either - perhaps the restart/update to .47 from .46 has fixed it.
