### ISSUE TITLE
Xlights crash adding ploy line. 

### ISSUE THREAD

**Issue by Jed3176** [smeighan/xLights#1701]
**Describe the bug**
Adding a single line to layout, crash when selecting protocol. PLease see video.  

**To Reproduce**

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3587972/xLightsProblem.zip)

**Comment by computergeek1507** [comment]
I think I fixed it. Keith may want to review why this happens? 2cfd58619c9f66c4ec070357bb4150db2c2e0703

**Comment by keithsw1111** [comment]
I have reversed your fix. You were treating the symptoms ... not the cause. The cause is a bug in the ZCPP conversion to E131. I have fixed the bug and added a bunch of repair logic. to hopefully fix things.
