### ISSUE TITLE
Check sequence causes abort.

### ISSUE THREAD

**Issue by TxBillbr** [smeighan/xLights#1702]
On windows10 in 3D mode. Xlights 47. Most everything is working nominally.I can open xlights and immediately do a check sequence and xlights will abort.  If I don't do a check sequence, no abort occurs. I can work for hours (saving, etc) with no problem. The moment I try to do a check sequence the abort happens. I've attached core show files in hopes that it will help to isolate the issue. This showed up fo me somewhere in the last several releases.

[check_sequence_crash.zip](https://github.com/smeighan/xLights/files/3588035/check_sequence_crash.zip)

**Comment by keithsw1111** [comment]
This does not crash for me ... can you crash it and then package the log files.

**Comment by TxBillbr** [comment]
Keith,
I will do that this evening (Central US time).

Bill

**Comment by derwin12** [comment]
Is this the abort/retry/cancel prompt we saw a couple nights ago on zoom? ie. Not the typical xlights abort screen? It created the tmp check sequence txt file but aborted when it tried to display it.

**Comment by TxBillbr** [comment]
Xlights appears to not catch the exception. I get an Abort, Retry, Ignore dialog that seems to be a system one. Clicking Abort causes it to show a second one.

Bill

**Comment by TxBillbr** [comment]
Here is the ARI box
![image](https://user-images.githubusercontent.com/44479016/64574502-5be56b00-d335-11e9-8a41-bcc5e2bfe570.png)

I get that twice and then
![image](https://user-images.githubusercontent.com/44479016/64574531-6e5fa480-d335-11e9-9e55-c50b7ee0c626.png)

Then I get a list of all my props as not being able to calculate start channels.
![image](https://user-images.githubusercontent.com/44479016/64574592-a9fa6e80-d335-11e9-9a13-38e674015be7.png)
and then the program exits.

I don't find anything it the windows event logs.

The only modified file in the directory is xlights.keybindings.xml
No new files are created. There are no .bkup files and no text files. nothing. Searching xlights on my whole machine for files name *xlights*.*  modified today yields
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/3593117/xLights_l4cpp.log)
and xlights_keybindings.xml.

Cleared Appdata\temp with no effect.

Looking at the log it appears that it is generating the data for the check sequence. The last instance of startup, I pressed ignore to see what would occur and got the "Could not calculate start channels" logged at 2019-09-09 19:28:48,587 for startup at 2019-09-09 19:27:32,100

Previous run that aborted on or about 2019-09-09 19:10:31,516 was started at 2019-09-09 19:06:27,748.

I will change the image file paths to point to the local show directory and try it again.

**Comment by TxBillbr** [comment]
After careful examination, I have found that my prop "peacecube" configuration is very confused.  It is supposed to be a 7x7x10 cube. Looking at the prop layout I see this:

![image](https://user-images.githubusercontent.com/44479016/64576406-02356e80-d33e-11e9-9534-6ab77ef9402e.png)

There should be 490 nodes (not 489) and quite a lot of the node map doesn't make much sense (especially the empty one). I cannot delete the prop from my layout. The program seems to ignore my atempts. I have selected and pressed the DEL key as well as right-clicked and chosen 'delete' from the menu. I may try excising it manually from the xml file.

**Comment by TxBillbr** [comment]
Manually deleting the prop from my layout did not help. I have adjusted everything in the layout mentioned in the log from check sequence (except for large blocks of channels skipped) and still it aborts. FWIW package log files aborts as well... I'm out of ideas.
Latest log: 
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/3593261/xLights_l4cpp.log)

**Comment by keithsw1111** [comment]
I only looked at your check sequence crash which the log file helped me locate. If problems persist with other items please raise separate tickets.

**Comment by keithsw1111** [comment]
If you want to you can grab this version with a fix https://www.dropbox.com/s/e777zct5ztdz9s7/xLights64_2019_48.exe?dl=0

**Comment by TxBillbr** [comment]
Thanks Keith. I confirm that resolves my issue.
