### ISSUE TITLE
Effects on Single line & Poly Line direction change in .47

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#1703]
**Describe the bug**
On Single Line and Poly Line Models, the direction of an effect on them appears to be dependent on the location of the starting location (either green square or blue square) setting on the model properties.  It used to be that the effect was always assuming that the green square was on the left side and the blue on the right side - with the starting location just where the channel count was starting.  Effects still appear to act the old way on the arch model, regardless of the starting location selected.  

**To Reproduce**
See the attached file that has the single line, polyline, and arch models in it.  There are 2 of each model, each are identical to one another except for the starting square location - one model set to green, one model set to blue.  A few different effects are placed on each of these models, all effects for a given time period are identical.  The arch models act as expected, with the direction going the same way regardless of the starting square location selected.  The line models change with the selected square locations, which is not as it has been in the past.

**Expected behavior**
All models should act like the arches, where it does not change the effect based on the start location being the green or blue square.

**Versions (please complete the following information):**
 - xLights version 2019.47
[Bug File.zip](https://github.com/smeighan/xLights/files/3588560/Bug.File.zip)

**Comment by keithsw1111** [comment]
So this is both right and wrong. Yeah the single line model recently changed and I screwed it up. That is fixed.
The polyline is much harder as it has always worked that way ... but I agree with you it is wrong. Problem is changing it will annoy a whole bunch of users ... but its the right thing to do.

**Comment by deplanche** [comment]
Thanks for the fix Keith.

**Comment by keithsw1111** [comment]
Can you check this version. Dan says my last fix was problematic and he made some changes ... I tested with your layout and it looks ok. https://www.dropbox.com/s/e777zct5ztdz9s7/xLights64_2019_48.exe?dl=0

**Comment by deplanche** [comment]
Downloaded that and tested, and everything acts as I would expect.  Thanks again.
