### ISSUE TITLE
Sates effect enhancement

### ISSUE THREAD

**Issue by zcloutier** [smeighan/xLights#1704]
**Is your feature request related to a problem? Please describe.**
On the sates effect, there is no way to set intensity or DMX values. It has just started to become annoying because I am adding DMX bracelets to all my existing sequences and I am having to set each channel manually to the value it needs to turn them on.

**Describe the solution you'd like**
I think there should be the ability to choose intensity for each preset along with being able to set DMX values.

**Describe alternatives you've considered**
Currently, I just manually set them with the on effect or with the DMX effect.

**Additional context**
This feature would be very useful for those with DMX models that require channels to be set to specific values for them to function.

**Comment by keithsw1111** [comment]
This already exists ... set the state colour to a grey where the r=g=b=desired value.
