### ISSUE TITLE
Xlights/sequencer fail to output show data to lights

### ISSUE THREAD

**Issue by leighmierke** [smeighan/xLights#1708]
I connected a 1200pixel matrix to an alpha pix 16 controller to be used with Xlights. After setting up the controller and matrix I was able to run a successful "Test sequence" through X lights. However after building a sequence in the sequencer and turning "Output" to on nothing output to my lights. I tried saving the sequence and outputting using X scheduler and same thing, the sequence would run but no data was being output to my pixels.  Im not sure if its a settings issue or a bug. 

Like I said my controller successfully ran a ping test, and an RBG test, so I know x lights is talking with the controller but I get nothing from live sequencer or scheduler.  

Thanks for the help

**Comment by keithsw1111** [comment]
We would need evidence there is really a problem here. Hundreds of users struggle with exactly this sort of problem and they fix it through facebook/forum/zoom. Please use one of those avenues first. If you get experts claiming there is an issue then by all means raise a bug report.
