### ISSUE TITLE
Enhancement sms texting

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#1710]
**Is your feature request related to a problem? Please describe.**
Looking for a smoother experience in the output of the display

**Describe the solution you'd like**
When the default message is running it will pause, stop, just start over and end prematurely. I think this is based on events in the background (incoming texts, polling for updates, mouse movements)   Also text messages will just end when the time is finished, and will also jump and stutter like the default messages when a new message comes in.

Would like to see a message play to end before the next message begins, or the next element happens, like a poll or process of an incoming text.  If it slows down the display by a second, where the display is black, that would be ok.

**Describe alternatives you've considered**

**Additional context**

Thanks in advance for giving this consideration.

**Comment by keithsw1111** [comment]
You may want to try putting the text element in a background playlist

**Comment by JoelDearing** [comment]
While I was able to put the playlist in a background sequence, I was not able to see where i would put the text element into a background mode.  When I put the playlist with the text element in it into background mode the output does not show anything.
