### ISSUE TITLE
Enh: fpp connect/upload - filter the choices

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#1711]
Not likely to be used often but came across a use for this..
When you upload and do FPP Connect and upload the sequences and songs can the filter be added similar to the batch render.
Show Folder Only, Only Show Directory etc.

**Comment by jayceecee** [comment]
Would also be great if the duplicates (Sequence & Media) listed in the FPP ListBox could be removed.
I can send a screenshot if required or open a new Issue.

**Comment by computergeek1507** [comment]
Added with https://github.com/smeighan/xLights/commit/f33c755da73b4048461ac9c58bc03bbde1007f4c
