### ISSUE TITLE
Model Groups which include sub models are not displaying all sub models when selected.

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#1712]
**Describe the bug**
I select a model group of sub models and the submodels are not showing up in the preview screen.

**To Reproduce**
This is a video of what I am seeing.
https://www.youtube.com/watch?v=ng44lK2cifw

**Expected behavior**
I would have expected all selected models and or sub models in the group to be shown in the Default preview screen.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.50, 49, 48, .....

**Comment by AzGilrock** [comment]
Yeah we've never had the concept of highlighting sub-models that I know of.  The Selected property is at the Model level.

**Comment by MrChristmas2000** [comment]
So  does that mean that I'll just have to live with it not showing up to confirm all my selections. Should I rebuild all my models with individual lines for example a window frame made of individual lines instead of the 'window' built in model with sub models? The same goes for poly lines as well, with not being able to group by sub models and viewing them in the view screen I would also need to build with individual line models in order to be able to group and have them show up in the 'view'.

**Comment by AzGilrock** [comment]
I have no idea if someone will code the change.  I haven't really kept track of changes for several months so it could be easy it could be hard...who knows.  There really isn't coordination between developers much so never think that one developer making a statement means anything.  Many time I'd say we will never make that change and then someone codes it up the next day.  Heck I've been know to say it just to see if I could goad someone into coding something....lol.

**Comment by MrChristmas2000** [comment]
After doing some further research, I have discovered that sometime between 2018.41 and 2019.50 this functionality has become broken. It has worked in the past, you can even select one of the sub models in the list and it will be highlight the associated pixels in the default view.

**Comment by keithsw1111** [comment]
How about some more research and tell use exactly which release broke it.

**Comment by MrChristmas2000** [comment]
Looks like it started failing in 2019.1
I have included the associated rgb_effects.xml (xlights_rgbeffects.xml.txt) file I tested with.

When you select the group with submodels the first model shows everything but the rest shows the correct sub models.
However if you select one of the sub models it displays the incorrect sub model in default view.
In my test I selected 'Window Sides' Model/Group then Window Frame 1/Left Side Vertical and it shows the Horizontal submodels. 

[xlights_rgbeffects.xml.txt](https://github.com/smeighan/xLights/files/3613791/xlights_rgbeffects.xml.txt)

**Comment by AzGilrock** [comment]
Oh it used to work.  Might wanna lead with that.  Yeah so pretty much when the entire Layout logic was redone for 3D.  I'd have to think about how to deal with that because objects we show as selected are supposed to be objects you can click on and manipulate which is not true of submodels.

**Comment by MrChristmas2000** [comment]
Gill I take it that you will be the one to solve this dilemma.

**Comment by AzGilrock** [comment]
Who knows. Some issues just stay here forever.

**Comment by keithsw1111** [comment]
Closing this ... I think I have it working except when choosing the All models preview.

**Comment by keithsw1111** [comment]
So some more testing ... 3D is also not working correctly ... not sure why yet.
