### ISSUE TITLE
Submodel Renders Different with Model vs Group

### ISSUE THREAD

**Issue by TKW1969** [smeighan/xLights#1713]
- xLights version [e.g. 2019.50]

Here is a matrix model with 4 submodels (smaller matrix). If you put a picture/spiral, or pinwheel on the submodels and then a curtain on the model it shows curtain on all 4 submodels. If you put the curtain affect on a group containing the model the 1st submodel with an effect will not show the curtain effect. If you move the 1st submodel effect to another submodel it changes. See attached sequence.
[Submodel Issues.zip](https://github.com/smeighan/xLights/files/3613017/Submodel.Issues.zip)

**Comment by keithsw1111** [comment]
It has something to do with the allow blending between models option ... when you turn it on it behaves as expected. When you turn it off it doesn't.

@dkulp interested in your thoughts on this

**Comment by dkulp** [comment]
Definitely a bug someplace.   The first submodel to render doesn't seem to be blending, but the subsequent submodels are.   I'll look into it.

**Comment by dkulp** [comment]
Actually, blending between models is off, thus, the first submodel is rendering correctly, the others are not.
