### ISSUE TITLE
Constant random crashes

### ISSUE THREAD

**Issue by Scubado** [smeighan/xLights#1715]
Been having lots of crashes lately with several releases of Xlights.  Tonight I started a new sequence in .47.  created new sequence, import sequence, created new map and saved.  hit OK, when I hit render, xlights closed.  So I upgraded to .50 to hopefully not have more crashes.  Opened xlights, created new song, selected music and 40fps and done, xlights crashes several times at this point.  If it made it past this point it crashes trying to load the mapping file.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
There is nothing we can use here to troubleshoot your problem. Please either add some information as requested or close the ticket.

**Comment by Scubado** [comment]
[xLights_dbgrpt-6980-20190908T203214.zip](https://github.com/smeighan/xLights/files/3619114/xLights_dbgrpt-6980-20190908T203214.zip)

**Comment by Scubado** [comment]
Tonight I did the same thing and got as far as rendering when it closed on me.

**Comment by keithsw1111** [comment]
This is almost certainly a video driver issue on your machine.

**Comment by Scubado** [comment]
I removed second video card and haven't had a crash yet.  :)  But now I'm down to 2 monitors again.

**Comment by keithsw1111** [comment]
You dont need to uninstall the card necessarily ... just update the drivers to the absolute latest available from the card vendor ... do not get them from Microsoft ... these are very very rarely the latest.
