### ISSUE TITLE
E1.31 Output Bug

### ISSUE THREAD

**Issue by djred2000** [smeighan/xLights#1716]
It looks like there may be a bug in the way E1.31 is output. I am outputting 7 universes unicast to an ESP32 for a special controller I am building and the universes are not being sent in the correct order. When I print the universe being received to the serial port (for debugging) they are not showing in sequential order. They are showing in a seemingly random order.  This is causing a pixel matrix I have connected to my custom controller to not display properly. If I use Vixen, da_Tester, or FPP 3.2 with the same output configuration, the universes are received in sequential order and the matrix displays properly. Vixen, xLights, and da_Tester are all running from the same Windows 10 Pro machine. FPP is running on a Raspi 4. Let me know if I can provide more information.

**Comment by dpitts** [comment]
I do not remember seeing a mandatory order in the e131 spec. They do however have a sync packet which xlights supports. That is correct method to sync a frame to not a particular data universe.

**Comment by keithsw1111** [comment]
As Dave says there is nothing that requires universes to be sent in any particular order and even if there was it would not guarantee delivery order. Consequently it is a bug in your implementation of a e131 client to rely on the delivery order.

That being said xLights will generally send them in the order they are defined except where parallel sending is enabled. With parallel sending the order becomes indeterminate.

Sync universes are the right way to determine end of frame.

**Comment by djred2000** [comment]
I tested again with the [ESPAsyncE131](https://github.com/forkineye/ESPAsyncE131) library and I get the same result. How can I see if parallel sending is enabled/disabled?

**Comment by keithsw1111** [comment]
it is only an option from memory in xschedule. xlights sends out the data in the order on the setup tab ... but i say again the spec in no way guarantees order so it is a defect to expect them to arrive in a particular order.

**Comment by dkulp** [comment]
Also note:   it's parallel by "line" on the Outputs page.   Thus, if you need a particular controller to be in order, use a single e1.31 line on the output page with multiple universes.    Doesn't change the fact that the implementation on your controller is defective, but it may be a workaround.
