### ISSUE TITLE
.50 - xlights hangs on switching to a seq show folder

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#1717]
A few of us tried this google drive sequence and when we 
download the sequence, unzip then change the show folder to that directory it simply hangs with  the spinning busy icon.

[Update .. it didnt completely hang .. it just took a long time]

Care to try and confirm for us? (Never got to open the sequence - just trying to chg to the show folder)

https://drive.google.com/file/d/1tl9DspjuYR1sx7XYvtDZ7PItwFRLZECw/view?usp=sharing&fbclid=IwAR3mAEAf0rdAyzNXUSqxfdMW4O0z_YMEL1l6Bc1OAF7p40ONtytgYL4UZqY

Some folks were able to load the layout in +5 minutes. 

After 12 mins got a warning but it did complete..

Could not process model group C-Cane Spinner Shadow due to models not being found.
The following models will be removed from the group:
<Nothing listed>

**Comment by keithsw1111** [comment]
Yeah ... it hasnt hung but it is crazy big and has issues. i did make one change to speed up the initial load.
