### ISSUE TITLE
Sub Model not displaying as expected

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#1718]
**Describe the bug**
A picture effect placed on a sub model of a grid does not display correctly.

**To Reproduce**
See attached test sequence MegaGridSubModelTesting1.xml

**Expected behavior**
The picture as applied to the full Mega Grid model should appear on the Mega Grid Sub model just reduced in size.

**Screenshots**
A video 'MegaGridSubModelTesting1.mp4' is included in the sequence package

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version [e.g. 2019.50]

**Additional context**

**Attachments**
[MegaGridSubModelTesting1.zip](https://github.com/smeighan/xLights/files/3626657/MegaGridSubModelTesting1.zip)

**Comment by dkulp** [comment]
This is a bug in how you have the sub-buffer defined.  You have the sub buffer defined as a single row with a ton of nodes.   Thus, the image is "scaled" to one pixel high and then scrolled across that row.   If you use the "Subbuffer" tab to select the rectangular area, it would properly create a 2D buffer and it works.

<img width="1063" alt="Screen Shot 2019-09-18 at 9 55 19 AM" src="https://user-images.githubusercontent.com/91569/65155026-82249e00-d9fa-11e9-9e81-2e24b10308de.png">

**Comment by MrChristmas2000** [comment]
Dan, that did it. I have not used that control before and that is something good to know when splitting up a mega grid on a universal basis. I will close this with a big Thanks.
