### ISSUE TITLE
.50 breaking submodels

### ISSUE THREAD

**Issue by PeteyHall** [smeighan/xLights#1720]
**Describe the bug**
Upgraded to .50 last week and immediately noticed that my submodels weren't working as expected.  For my house, I have multiple submodels defined (verticals, eaves, etc.) and what I noticed is that before .50, my verticals would be using pixels 1-15 and the eave would be 16-50.  After upgrading to .50 from .48, the submodels became the vertical using 36-50 and the eave using 1-35 (it basically flipped them). 

I've confirmed that the starting pixel is correct.

I've been using these submodels for a couple of years now without issue.  

**To Reproduce**
Using .48, have a simple string of lights with submodels then upgrade to .50 and see how it flips the sub models.

**Versions (please complete the following information):**
Windows 10

**Comment by keithsw1111** [comment]
Files?

**Comment by PeteyHall** [comment]
On Friday, September 20, 2019, 09:52:15 AM EDT, Keith Westley <notifications@github.com> wrote:  
 
 
Files?

**Comment by keithsw1111** [comment]
Do you have something that shows the problem.

**Comment by PeteyHall** [comment]
Keith, I've zipped up screenshots and my upgraded to .50 files.
Within the zip you'll find 2 sets of pictures for my 'Front addition' string, both the top and verticals under .48 and the same ones after upgrading to .50.  
You'll clearly see that the pixel layout clearly changed after the upgrade to .50
   
Let me know if you don't get the zip file. On Friday, September 20, 2019, 10:12:57 AM EDT, Keith Westley <notifications@github.com> wrote:  
 
 
Do you have something that shows the problem.

**Comment by AzGilrock** [comment]
I would do a Package Log Files in version .48 and post that zip file.  That gives us everything to recreate your show directory.  Nobody is going to start creating models and submodels from scratch to troubleshoot something in most cases cause when we do it usually doesn't show a problem because it's specific to something in the users' layout.

**Comment by PeteyHall** [comment]
On Friday, September 20, 2019, 12:41:59 PM EDT, Gil Jones <notifications@github.com> wrote:  
 
 
I would do a Package Log Files in version .48 and post that zip file. That gives us everything to recreate your show directory. Nobody is going to start creating models and submodels from scratch to troubleshoot something in most cases cause when we do it usually doesn't show a problem because it's specific to something in the users' layout.

**Comment by AzGilrock** [comment]
Dude you gotta log into GitHub to add attachments.  And we don't need to see copies of what we posted in your replies.

**Comment by PeteyHall** [comment]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3637118/xLightsProblem.zip)

**Comment by dkulp** [comment]
This is working as designed and was a bug in <=.48.   Node numbers are always supposed to start at the "green square" and pretty much go left->right ish.   Otherwise all kind of problems occur when the model get put into groups.

**Comment by dkulp** [comment]
That said, there is definitely a bug with dropping effects on the strands if "Indiv Segments" isn't turned on...... Looking into that.

**Comment by PeteyHall** [comment]
So it ignores the start at blue then?  we should never use that and always start at green?
    On Friday, September 20, 2019, 02:14:35 PM EDT, Daniel Kulp <notifications@github.com> wrote:  
 
 
This is working as designed and was a bug in <=.48. Node numbers are always supposed to start at the "green square" and pretty much go left->right ish. Otherwise all kind of problems occur when the model get put into groups.

**Comment by AzGilrock** [comment]
Don't feel bad I'm not sure I know how our own software works now either.  The node layout clearly shows node 50 as the green square.
![image](https://user-images.githubusercontent.com/2024669/65374524-a02f1000-dc3f-11e9-947b-ffb6e4c9b29f.png)

**Comment by PeteyHall** [comment]
Agreed Gil but it's been working this way forever so I understand, the 'bug' just let me continue using my bad behavior.
