### ISSUE TITLE
2019.51 breaks model chains

### ISSUE THREAD

**Issue by mattyams** [smeighan/xLights#1722]
**Describe the bug**
I have a chain of snowflakes that all now have the same start and end channel numbers after moving to .51 when using the ZCPP setup. Rolled back to .50 and the problem is gone.  Could not see this reported anywhere else nor does the changelog have anything that stood out to me that would cause this. 

**To Reproduce**
1. Create 2 models.
2. Select Model 1 and change Model Chain to Beginning, controller to Controller 1, Controller Port 8, Protocol WS2811
3. Select Model 2 and change Model Chain to >Model 1, controller to Controller 1, Controller Port 8, Protocol WS2811
4. Channel numbers do not increase but duplicate Model 1's channel numbers.

**Expected behavior**
Channels to automatically increment by X amount of channels required.

**Screenshots**
![image](https://user-images.githubusercontent.com/16708009/65379433-c8495e00-dc95-11e9-9e54-79028bcd12c8.png)
![image](https://user-images.githubusercontent.com/16708009/65379435-ced7d580-dc95-11e9-8874-c5fe049869c6.png)

**Versions (please complete the following information):**
 - OS: Windows 10 1903
 - xLights version: 2019.51

**Additional context**
Rolling back to 2019.50 cleared the issue.

Let me know if I am missing any information.

**Comment by mattyams** [comment]
I looked more into it and it actually affects all my model chains.  Look at the Mini-Tree 1-3 and Star 1-3 (the stars above the mini trees), they have the same numbers too instead of incrementing.

**Comment by keithsw1111** [comment]
Can you attach your files.

**Comment by mattyams** [comment]
[xLights - 3D.zip](https://github.com/smeighan/xLights/files/3639345/xLights.-.3D.zip)
 Here you go, let me know if I'm missing any.
