### ISSUE TITLE
single line model start square/no rainbow

### ISSUE THREAD

**Issue by lanceandfrank** [smeighan/xLights#1723]
Hello,
On single line model in the layout tab when i select blue square as the start location it still uses the green square in the sequencer tab as well as the out put on the actual lights. Also the rainbow vs. pallet color option on single strand effect doesn't show rainbow, it just turns the lights white in the sequencer as well out the output to the actual lights. 2019.51  64bit

thank you

**Comment by AzGilrock** [comment]
I was just discussing this with folks on FB.  The sequencer will still show node 1 on the same side no matter which square is start but the data does get reversed and I had users verify its working on actual hardware.  Its best to talk about 1 issue at a time so if you have some files, videos, or screenshots to provide for the rainbow claim open an issue for that.
