### ISSUE TITLE
Auto channeling issue in release 2019_51

### ISSUE THREAD

**Issue by Docbrew** [smeighan/xLights#1724]
**Describe the bug**
When chaining models using ZCPP the start channel is not updating to the next channel number.  It's using the start channel of the model you are chaining it to.  I've downloaded xlights ver 2019_49 and it does work as expected as shown in tutorial videos.

**To Reproduce**
[YouTube video](https://youtu.be/QcFRUtd-WzA)

This also happens when not using the smart remote boards.

**Expected behavior**
 I would expect the chained model to start at the next available channel after the model I attached it to the end of.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019_51

**Comment by computergeek1507** [comment]
This will be fixed in the next release, Keith already fixed this.
