### ISSUE TITLE
Couple of bugs on MAC

### ISSUE THREAD

**Issue by ncosper** [smeighan/xLights#1725]
Have a couple of issues in the layout tab in the Mac version. ON 51 if you open xlights all models that are uploading to the same controller port reset their start channels to all match the first model. You can have a string of models maintain their start channels. I've seen this before but always had a hard time duplicating it, this is on startup. 

Secondly in the layout tab if you check 3d you lose all layouts except default. This has gone back a few versions it seems. 
Here is youtube link (no sound) displaying the issues im seeing. 

Thanks!

https://youtu.be/8-MHDk8UV98

**Comment by keithsw1111** [comment]
The first is a known bug that has been fixed for .52. Roll back to .51 in the interim.
The second item is by design.

**Comment by ncosper** [comment]
Thanks Keith, Im curious how you go about placing models that are in layouts other than default in 3d space after the change. Do you have to change them back to default layout to move them then revert back to the intended layout?

**Comment by keithsw1111** [comment]
You dont ... 3D is only supported on Default. It was a bug and misleading to show it previously and led to the erroneous assumption that you could place them in 3D.
