### ISSUE TITLE
Bug with .52

### ISSUE THREAD

**Issue by PeteyHall** [smeighan/xLights#1726]
**Describe the bug**
Just downloaded and installed .52.  I went into the layout tab and simply moved one of my props (front house) and xlights crashed and here's the report.

**To Reproduce**
Open the Layout tab and move a prop.

**Comment by PeteyHall** [comment]
[xLights_dbgrpt-65344-20190923T074044.zip](https://github.com/smeighan/xLights/files/3641935/xLights_dbgrpt-65344-20190923T074044.zip)

**Comment by keithsw1111** [comment]
I think .53 fixes this
