### ISSUE TITLE
Effect Presets "preview" feature

### ISSUE THREAD

**Issue by tomhammond** [smeighan/xLights#1727]
Hello,

I use the Effects Presets feature a lot and have quite a library of presets that I've saved from public domain sequences, my own sequences, and through the Create Random Sequence feature.  It's quite a time saver and allows me to build a library of effects.  Nice feature!

When I have many presets in a list, describing effects via a text name is difficult, based on how complicated effects can look.  It's like trying to describe the shape of water.  

Could you consider adding a feature to the presets window so that a screenshot of the effect is captured created when the preset is made?  Such as taking a screenshot of the Model Preview window a few seconds into the effect's animation?  This would make it a lot easier to distinguish one preset from another when browsing a large list of presets.  It can just be a picture; it doesn't need to be animated.

Thanks,
Tom Hammond
tominohio@gmail.com

**Comment by computergeek1507** [comment]
I did start working on this feature, I may finish it for you.

**Comment by AzGilrock** [comment]
I kinda hate this idea.  What are you going to do store tons of screenshots.  I hope you don't plan on packaging them up when we share show folders.  Also the chances of know what an effect does from a single screenshot is like slim to none.

**Comment by tomhammond** [comment]
Scott, I would like that very much!  You are making nice improvements to
the UI, among other things.  Let me know if I can help in any way.

Thanks,
Tom

**Comment by idleup** [comment]
@computergeek1507 Scott, did you ever finish this functionality? and does it support animated GIF's? I know OP said it does not need to be animated but I think it really does in order to truly distinguish between two presets...

**Comment by computergeek1507** [comment]
I will have something added real soon, I need to clean up the code a little bit.

**Comment by tomhammond** [comment]
I am looking forward to this feature as well!

**Comment by stevegiron** [comment]
This sounds like a good idea, but could create a mess. Some presets look good on certain models and not others. When one sends a preset to another, what model should it create the preview on?  Organizing your presets is the key. I have 200+ presets and no need to have this feature and I'm the one who originally requested presets.

**Comment by keithsw1111** [comment]
Steve ... the preview would be a small matrix ... as that maps easily to an icon. Sure the preview may not be designed for that but that is just one of those things.

**Comment by microcyb** [comment]
This would be a fantastic feature

**Comment by computergeek1507** [comment]
Added in 2021.2
