### ISSUE TITLE
Off Effect Not Freezing Last Frame of Previous Effect

### ISSUE THREAD

**Issue by jdm7999** [smeighan/xLights#1728]
**Describe the bug**
When using an "off" effect, which is butted up to a prior effect (for instance, a garlands effect), then selecting the "Persistent" and "Transparent" settings on the "off" effect, the "off" effect does not hold the last frame from the prior effect. If you "render all" on the sequence, and DO NOT select the "off" effect, the "off" effect will hold the last frame of the previous effect. However, clicking on the "off" effect will make it 'lose' the last frame and go dark. Thus requiring a complete "render all" to 'grab' the last frame of the Garlands effect onto the "off" effect.

**To Reproduce**
On a new animation...
1. Drop a garland effect (or any effect) onto a prop.
2. Drop an "Off" effect immediately following the previous effect onto the same prop.
3. Select "Transparent" (under Effect Settings) and "Persistent" (under Layer Settings) on the "Off" effect.
    To my understanding, the "Off" effect should now be holding the last frame of the Garland.
4. It doesn't matter what effect is selected but you can "Render all"
5. Now when you play the animation, the "Off" effect holds the last frame of the Garland. Selecting anything OTHER than the "Off" effect won't cause the "Off" effect to lose the last Garland frame.
6. Click on the "Off" effect. There is a brief flash of the last frame of the Garland effect (that should be 'frozen') then the prop goes dark. Any playing of the sequence or playing of the "off" effect will not show the last frame of the Garland effect, which should be held throughout.
7. A "render all" is required to get the "off" effect to hold the last frame of the Garland effect, just as before.

**Expected behavior**
The "Off" effect to hold the last frame of the previous effect, whether or not I select the "off" effect, and not requiring constant "Render All"s to re-capture the last frame.

**Versions (please complete the following information):**
 - OS: [e.g. Windows 7 Pro]
 - xLights version [e.g. 2019.53] but I've noticed this in several previous versions (including last year's versions)

**Attachments**
No sequence attached as this was reproducible by several people and on several sequences.

**Comment by keithsw1111** [comment]
if you want us to look at this you must provide a sequence

**Comment by jdm7999** [comment]
[NoFreeze.zip](https://github.com/smeighan/xLights/files/3655945/NoFreeze.zip)

**Comment by AzGilrock** [comment]
There have always been cases where clicking on effects doesn't always show the final results.  A Render All and then playing is always required to see everything.

**Comment by jdm7999** [comment]
I'm unsure how to take the comment. Is that the "fix"?

I've experimented more with this issue this morning and it appears that the "Render Style" on the "Off" effect must match the render style of the prior effect, or the "off" won't hold the last frame. I was trying to make all my "off" effects "Default" Render Style and it wasn't having the desired results (such as only a small portion of the prop holding the last frame).

**Comment by AzGilrock** [comment]
I have no idea if Keith will look at it and decide to change something.  You are trying to point out something as a "bug" that was never intended to be a program feature.  We never designed the Off effect as a way to freeze a previous effect.  When you click on an effect it rendered the duration of that effect so that is why it might not have data from outside that range.  If something is changed to make this do what you want it probably will be at the expense of application speed.  Heck we used to not even show the blending between models until the full render.  I think that was changed but it sure made the interface speed kinda suck now.

**Comment by jdm7999** [comment]
I don't mean to belabor the point but I do believe this is a bug. Keith even made a video (http://videos.xlights.org/xlights-freeze-an-effect-part-way-through_4c384dc6d.html) describing how to achieve the desired freeze and I think I've found a "hitch" with it.

**Comment by AzGilrock** [comment]
You said if you do a render all then everything comes out as expected so my opinion is its not a bug.

**Comment by keithsw1111** [comment]
There is no sequence in that zip file ... so again ... nothing i can do.

**Comment by jdm7999** [comment]
Hmm, how odd. I just did a regular "package sequence"...

Here it is again but I've updated it to show the problems with the "not-matching" Render Styles between the two effects; the first set of "off" effects are all set to "default" and the second set are set to match the previous effects.

[NoFreeze.zip](https://github.com/smeighan/xLights/files/3663013/NoFreeze.zip)

Thanks!

**Comment by dkulp** [comment]
Bug or not, this is completely working as designed and is NOT likely to be change anytime soon.

When you click on an effect or change the effects settings, only the timeframe for that specific effect is rendered and only for the models/groups that overlap with the model/group on which the effect is placed.   This is as designed specifically keep performance reasonable.    To "fix" this, we'd need to also render the effect in front of it (and on all models/groups with overlaps) and that may then depend on the effect in front of it, etc...   Also, it only renders the specific time frame of the effect.   effects and such on other models/groups that overlap may have a "randomness" that will also not look correct once rendered this way.   That is why we ALWAYS say to do a render all before using the fseq for the show.   

Anyway, this will not change anytime soon.

**Comment by keithsw1111** [comment]
The history here is up until the 25/2/2019 we used to expand the render size but as Dan says this is horribly inefficient as it expands the amount of rendering being done which is almost never needed. What we need to do is be smarter about when to expand the render range (as there are very few times when it is necessary).

**Comment by stevegiron** [comment]
I logged this as an issue last year.  The explanation and fix is in #1412
