### ISSUE TITLE
Exporting/Importing Poly Line from show folder to another show folder.

### ISSUE THREAD

**Issue by Jed3176** [smeighan/xLights#1729]
[Xlight_bug_2.zip](https://github.com/smeighan/xLights/files/3659987/Xlight_bug_2.zip)

**Comment by keithsw1111** [comment]
What is the actual problem?

**Comment by keithsw1111** [comment]
Watched the video ... saw the crash but i dont get a crash when i export and import mine so how about you provide the actual files and give us a chance to reproduce the problem.

**Comment by Jed3176** [comment]
Sorry I forgot to add the report. Here you go

**Comment by keithsw1111** [comment]
??? I see no change

**Comment by keithsw1111** [comment]
I also think you are doing this wrong ... you dont need to export models ... you can instead import them directly from the other rgb effects file.

**Comment by Jed3176** [comment]
Thanks Keith. I'll report back later. Getting ready to go to work. Eight
more hours to go before my Friday night starts.

**Comment by keithsw1111** [comment]
Closing due to lack of response.
