### ISSUE TITLE
Deleted some effects, hit render and crashes

### ISSUE THREAD

**Issue by Scubado** [smeighan/xLights#1732]
[xLights_dbgrpt-12980-20190929T131833.zip](https://github.com/smeighan/xLights/files/3667913/xLights_dbgrpt-12980-20190929T131833.zip)
I had pasted some effects into a song, rendered and saved.  Later deleted the effects and when I hit render, it creates crash report.  Did it twice in same spot. 
**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
[xLights_dbgrpt-9048-20190929T132051.zip](https://github.com/smeighan/xLights/files/3667914/xLights_dbgrpt-9048-20190929T132051.zip)

**Comment by keithsw1111** [comment]
You have not really provided a way for us to reproduce the issue so we can only guess as to what is going on. Generally I need a sequence and the specific steps that lead to the crash. Intermittent or occasional crashes we cannot help with ... at least not this way.

**Comment by keithsw1111** [comment]
does this still happen in 55. i could see only one way this may happen and tried to stop it

**Comment by keithsw1111** [comment]
Closing due to lack of response
