### ISSUE TITLE
Crashes when I hit Render on certain sequences but not others

### ISSUE THREAD

**Issue by Jbrehm22** [smeighan/xLights#1734]
I purchased the Christmas Can Can from Tom's Magical light show website, and when I had everything in it, it would crash on render. I then started a new sequence and imported effects one at a time and I had several effect groups imported and it was rendering as I saved. Once I added "ALL" it crashed as soon as I saved. 

[xLights_dbgrpt-1345-20190930T204909.zip](https://github.com/smeighan/xLights/files/3673938/xLights_dbgrpt-1345-20190930T204909.zip)

**Comment by Jbrehm22** [comment]
I'm on the latest version of xlights, .54 and I'm using a Mac

**Comment by keithsw1111** [comment]
Pls package the sequence and send it to me on facebook

**Comment by Jbrehm22** [comment]
do I send the packaged file to you through messenger? Or is there some other place you want me to send it?

**Comment by Jbrehm22** [comment]
[Christmas Can Can BREHM .zip](https://github.com/smeighan/xLights/files/3674148/Christmas.Can.Can.BREHM.zip)

It wouldn't upload the packaged sequence to facebook.

**Comment by keithsw1111** [comment]
I believe I have stopped it crashing ... I am less sure the fix is the right fix.

**Comment by AzGilrock** [comment]
Thanks for the sequence.  You should remove it now.

**Comment by Jbrehm22** [comment]
Sorry, I don't understand. Do you have my sequence I can re-download that is stable?
or will this fix be in an upcoming update?

Also- when it says remove it now, what should I remove? 
Sorry for the questions, but I really appreciate all of the help.
      Thanks,
          John

**Comment by keithsw1111** [comment]
It will be in the next release when Dan gets back.

**Comment by AzGilrock** [comment]
John,
Keith took care of it.  I wasn't able to from work.  You posted a paid sequence open for anyone to download so since Keith had already fixed the problem I was saying delete the attachment since you can edit the posts here.  But Keith already deleted the whole comment so nothing to do now.

**Comment by Jbrehm22** [comment]
Thanks!
      John
