### ISSUE TITLE
Extreme Render Times .54c (OSX)

### ISSUE THREAD

**Issue by bacarudaguy** [smeighan/xLights#1735]
2019.54c extreme render times - experiencing super long render times with the latest release. I've been trying to dial a Kaleidoscope effect in across about a 10 sec range and using "render selected region", it's taking 15-20 mins to render that small time frame. OSX 10.12.6 with 16GB of RAM and an i7 quad core.

Render times are ranging from 900+ to 1200+ secs for the 10 sec highlighted region...

**Comment by keithsw1111** [comment]
This is not a useful bug report. Where is the attached sequence? What time interval are you rendering?

**Comment by bacarudaguy** [comment]
My apologies Keith, but I don't want to publicly post the sequence... can I email it to you?

Time frame in question is ~10:23.500-10:38.500 (so I guess it's more like 15 secs).

**Comment by AzGilrock** [comment]
Why not copy the sequence and then edit it down?  If it's really just that one effect then it would be great to have a sequence with just that effect.  It's a pain for a developer to troubleshoot sequences that have 1000's of effects.

**Comment by keithsw1111** [comment]
You can email or PM it to me. As Gil says cutting the sequence down to just the problem is a good thing to do.

**Comment by keithsw1111** [comment]
Closing due to lack of response
