### ISSUE TITLE
Wrong colors with on effect and test mode

### ISSUE THREAD

**Issue by Medel** [smeighan/xLights#1736]
i create a tree with 2 strings, 400 nodes/string and 8 stands/string

With the on effect and the red, green or blue color is it OK. 

If I choose yellow the color starts at the first node with bright green and changes to red at the node 100 then it starts again with bright green and so on.
If I choose purple the color starts at the first node with bright purple and changes to red at the node 100 then it starts again with bright green and so on.
If I choose turquoise the color starts at the first node with bright turquoise and changes to red at the node 100 then it starts again with bright turquoise and so on.

The color at node 50, 150... is right.

Same mistake with the test mode

If I change it to only one string with 800 nodes is the same too

The effect color wash if it shows mixed color the same too

The preview is always right.

**Comment by keithsw1111** [comment]
Where is the demo sequence?

**Comment by Medel** [comment]
Here it is
[testtree1.zip](https://github.com/smeighan/xLights/files/3676401/testtree1.zip)

**Comment by keithsw1111** [comment]
If the preview is correct then 99.9% probability is a controller configuration issue or mismatch between the controller and xLights.
We would need to see all of your controller configuration as well.

**Comment by Medel** [comment]
I test it with ESP8266_ArtNet-LED-DMX-Node-1.0.4 from https://github.com/bombcheck/ESP8266_LED-DMX-ArtNetNode and ESPixelStick from https://github.com/forkineye/ESPixelStick.
Always the same mistake. 
Here is the config for the first controller (Port A, node 1 to 400)
[Artnet config.zip](https://github.com/smeighan/xLights/files/3678566/Artnet.config.zip)

**Comment by keithsw1111** [comment]
Your zip file has most of the files missing that we would need to look at this. Can you please use tools package sequence to prepare ALL the files. I also suggest you try the forums/groups in parallel because it is exceptionally unlikely this is an xlights problems.

**Comment by Medel** [comment]
I have the solution. its a Power problem
