### ISSUE TITLE
Enhancement Request: Ability for all strands to be on same channel

### ISSUE THREAD

**Issue by showse90** [smeighan/xLights#1737]
I am attempting to create some models for various props in the display and like the way the prop looks, but ours are DMX and not the standard RGB.  Every strand is the same channel, but the xLights software only seems to have the capability for strands to be on different channels.  Any way this ability could be added?

Thanks!
Shawn

**Comment by AzGilrock** [comment]
If you select the 3 channel RGB string type it should give you 3 channels for the entire prop.  What type of model are you trying to create and what settings do you have?

**Comment by computergeek1507** [comment]
If you use the candy cane model and set the strings to the number of channels and then use single channel as the string type it should work.

**Comment by keithsw1111** [comment]
As far as we can tell this is already supported. Please explain more what it is that you think is not supported.

**Comment by showse90** [comment]
Here is a screenshot with what I am working with.  It is set as a "half sphere", as I am trying to emulate a large tree in the display in 3D. The entire tree will be decorated such that the tree can go on or off in red green, or blue, but not each individual strand in the tree (will use a LOR controller as DMX).  I cannot find a way to accomplish such that all strands are the same channel, as the String Type under String Properties does not seem to have an option for all strings to be treated as 1 so to speak.   
![model scrolled](https://user-images.githubusercontent.com/56044909/65999746-069c0580-e46c-11e9-9fc9-f5e3561b2715.png)
![tree model](https://user-images.githubusercontent.com/56044909/65999747-069c0580-e46c-11e9-8655-909b4cf1a154.png)

**Comment by AzGilrock** [comment]
Did you try "3 Channel RGB" under String Properties where it says String Type and you have it set to Single Color?

**Comment by showse90** [comment]
When I try "3 Channel RGB" it shows as 60 sequenceable channels when I use 20 strands.  Would like a total of 3 sequenceable channels for those 20 strands (red, green, blue), as none of the strands are 
 individually controllable.

**Comment by keithsw1111** [comment]
Why not 1 string 20 strands per string 600 lights per string.  that would put everything on a single channel.

**Comment by AzGilrock** [comment]
Did you use "20 strands" or "20 strings"?  Like Keith says you should use "1 string" and then use "strands per string" if you need it to fold.  I'm not home to try it out to see if it gives you 3 channels when using "3 channel RGB" with 1 string defined but I believe it should.  Keith said it puts it on a single channel but I know you need 3 channels.   He may have just mistyped it.

**Comment by showse90** [comment]
I tried your method, and it seems to work great!  Thanks Keith!  Appreciate all the work done with the software.
