### ISSUE TITLE
CRASHING REPORT

### ISSUE THREAD

**Issue by jblue502** [smeighan/xLights#1738]
PLEASE SEE THE ZIP FILE FOR THE CRASH.
[xLights_dbgrpt-9964-20191001T214555.zip](https://github.com/smeighan/xLights/files/3679128/xLights_dbgrpt-9964-20191001T214555.zip)

**Comment by keithsw1111** [comment]
Closing because it does not crash for me and this bug report lacks any useful detail to help us reproduce the problem.
