### ISSUE TITLE
Change the brightness for all models

### ISSUE THREAD

**Issue by dszoka** [smeighan/xLights#1739]
**Is your feature request related to a problem? Please describe.** No 

**Describe the solution you'd like**
I would like to be able to set the Brightness under controller connection to all models, or to a group of models instead of doing them 1 at a time 
Example: right click on house outlines group - set brightness to 40% -- All models under that group are now set at 40%
Now this may have issues doing this way due to models being in more than 1 group.     

**Describe alternatives you've considered**
I understand that once you have setup your pixel outputs on your controller that unless you have brightness ticked Xlights won't change the brightness on each output (for Falcon anyway) 

Just an idea

**Comment by keithsw1111** [comment]
Why cant you do that now? Admittedly you need to have set the port/protocol but once done you can already bulk edit these properties.

**Comment by dszoka** [comment]
Hi Keith 

Can you please tell me where, under bulk edit in the setup tab doesn’t show it 



David Szoka

**Comment by keithsw1111** [comment]
On layout tab ... right click on selected models in the black area.

**Comment by dszoka** [comment]
Thank you 



Kind Regards 
David Szoka
