### ISSUE TITLE
Single strand not working when grouping all arches??

### ISSUE THREAD

**Issue by DanJacobsen** [smeighan/xLights#174]
I setup a single strand with all arches grouped in XL 3.0.x (can't remember which one...within the last 4 weeks or so...) and it worked well as a chase.   After I downloaded XL4.0.14 tonight the effect doesn't work anymore.   I am using red lights and they just "sit there" instead of producing any movement between the arches.  I just did some manipulation last night of grouping elements into models, etc, so I figured maybe I had goofed something up there--but when I checked several other sequences everything is working as expected.   I don't know how to attach any xml files in github....  Sorry

**Comment by DanJacobsen** [comment]
For info-----I tried several of my backup xml files; all produced same incorrect results...  I have only used this single strand arches effect on this particular file, so not sure if this is duplicated in other files or not...

**Comment by stevegiron** [comment]
Hello, I'm helping sort the issues and determine which issues are still valid. 
As of May-14 we are version 4.0.31. Is this issue still occurring?

**Comment by DanJacobsen** [comment]
Steve:
I am running 4.0.31.   I just setup a test sequence.   I was able to setup single strand chases but the "group all arches" does not work--the chase does not work when I go to "group all arches".
Thanks so much!

Dan E. Jacobsen
(225) 439-4284

 
Date: Mon, 18 May 2015 13:54:00 -0700

**Comment by stevegiron** [comment]
Trying to understand this...Are you expecting that when you have multiple arches that a chase will move across all arches as if it was one model ?

**Comment by DanJacobsen** [comment]
Correct.   That is what used to happen.   Maybe in xl3 though....

**Comment by stevegiron** [comment]
This now works with the model groups feature. I would create a group, add the arches and then apply the effect to the group.

**Comment by dkulp** [comment]
I believe this was fixed in 4.1.1 anyway.   From the notes:

-- bug/enh (dkulp) Lots of work on SingleStrand Chase effect to get it to work better with small models and single color models and grouped arches.
