### ISSUE TITLE
Crash-- Changing the brightness on models

### ISSUE THREAD

**Issue by dszoka** [smeighan/xLights#1740]
**Describe the bug**
Xlights crashed--  Mac 2019.54c 
Was changing brightness on model in layout tab-- under Controller Connection  

Crash Zip attached 

[xLights_dbgrpt-33439-20191002T132341.zip](https://github.com/smeighan/xLights/files/3679339/xLights_dbgrpt-33439-20191002T132341.zip)

**Comment by keithsw1111** [comment]
I am not convinced. The log trace does not indicate that. Can you reproduce the problem reliably? It looks like it crashed when you were selecting an item in the model list.

**Comment by dszoka** [comment]
Have tried to reproduce, can not..
