### ISSUE TITLE
Crash on saving mapping 2019.55

### ISSUE THREAD

**Issue by WCMougly** [smeighan/xLights#1741]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

Crash on saving mapping 2019.55 & 2019.54
Importing a purchased sequence.
After importing, clicking on Save Mapping results in the attached crash dump.

**Comment by WCMougly** [comment]
[xLights_dbgrpt-13824-20191002T162359.zip](https://github.com/smeighan/xLights/files/3683188/xLights_dbgrpt-13824-20191002T162359.zip)
[xLights_dbgrpt-13480-20191001T184659.zip](https://github.com/smeighan/xLights/files/3683189/xLights_dbgrpt-13480-20191001T184659.zip)

**Comment by computergeek1507** [comment]
can you include the sequence you are trying to import?

**Comment by keithsw1111** [comment]
we need more information. the specifics of what you were importing from and to is likely important.

**Comment by WCMougly** [comment]
Sir,

 

Unfortunately, I don't believe I can.

 

It is a purchased sequence and subject to the copyright of the owner.

 

The sequence came from https://www.xtremesequences.com/

https://www.xtremesequences.com/store/product/214-little-drummer-boy/

 

Respectfully,

Mark

mougly@comcast.net

**Comment by keithsw1111** [comment]
If your vendor wont let you send the sequence (privately - not here) to one of the xLights developers to troubleshoot then maybe its time to find a new vendor. Most of the vendors I know have no problem with it.

**Comment by keithsw1111** [comment]
Closing due to lack of information.
