### ISSUE TITLE
Missing letters when displaying text on a matrix

### ISSUE THREAD

**Issue by m00dawg** [smeighan/xLights#1742]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Using the text feature on a matrix seems to skip letters (so TURN UP only shows TR U; "ABCDE" only shows A C E)

**To Reproduce**
1. Use a 48x64 matrix (this also happens on my tree which is lower)
2. Apply a text effect
3. I found using either OS Fonts or System Fonts did not make a difference
4. Put in text, set movement to left

**Expected behavior**
Previously text rendered without issue. It kinda makes me think, since it's skipping letters, that it's maybe a UTF-8 sort of issue?

**Screenshots**
![Screenshot from 2019-10-02 15-33-02](https://user-images.githubusercontent.com/226504/66086645-4b8e6d80-e53a-11e9-8147-01f7237ffdbe.png)
![Screenshot from 2019-10-02 15-32-55](https://user-images.githubusercontent.com/226504/66086646-4b8e6d80-e53a-11e9-8ea7-078d94b988a8.png)
![Screenshot from 2019-10-02 15-32-24](https://user-images.githubusercontent.com/226504/66086647-4b8e6d80-e53a-11e9-8b26-a559e0507daa.png)

**Versions (please complete the following information):**
 - OS: Linux Mint 19.2 (based on Ubuntu 18.04)
 - xLights: Commit # 4be00096572c8de7b6d6a0b6eca01e91b9e413f9

**Additional context**
I've upgraded Linux Mint recently so it's possible something changed perhaps with font rendering or some such. I don't know for sure when it stopped working (before or after). I recall seeing references to 18.04 in the build instructions so I think I'd be more compatible over less. Either way it fails if I used the built-in fonts, system fonts, or externally installed fonts (Inconsolata is the external font I tested).

**Attachments**
[Text Test.zip](https://github.com/smeighan/xLights/files/3683662/Text.Test.zip)

**Comment by dkulp** [comment]
You have two colors selected on the color palette, one of which is black.  Thus, every other letter is using the "black" color.   It's working as designed.

**Comment by m00dawg** [comment]
*slaps forhead* man so sorry to waste your time on that one. I owe you a beer or something. Spent days upgrading Linux among other things trying to solve that to avoid filing a bug and missed something super obvious. Sorry about that @dkulp but thank you for the response! Indeed, fixing the palette shows expected behavior.
