### ISSUE TITLE
ENH: Ability to map 2 (or more) props to one prop during the import.

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#1744]
When mapping another persons props - some times they have just a couple effects on a prop. 

Would it make sense to allow one to map more than one prop to one prop. Thinking perhaps just add a layer to the mapped prop so the other effects can come in cleanly.

Of course if they are two very busy props it would be a mapped mess .. 

Right now what I do is add a few layers then repeat the mapping process to bring in those other effects onto a prop that was previously mapped.

**Comment by AzGilrock** [comment]
So it sounds like you already found the solution I was going to suggest.  The Import Effects process was designed to be able to be run more than once without messing up what's already there.

**Comment by keithsw1111** [comment]
As Gil says ... there is already a way to do this ... multi mapping will make the UI more complex as you also need to worry about how to resolve conflicts

**Comment by derwin12** [comment]
Yea . just thought I would throw it out there .. I think what I will do is save a one.xmap and a two.xmap for the cases when some creators have props that I want to map to just one of my props.
