### ISSUE TITLE
Not saving full sequence

### ISSUE THREAD

**Issue by RandyBrandy** [smeighan/xLights#1745]
**Describe the bug**
XLights is not saving my full 30 min sequence. The file size is too small. If I delete and save again, the file size changes to just a little bit larger, as if it is not fully rendering every time. When I upload to the falcon player it thinks the sequence is only a handful of seconds. I have tested a 30 second sequence to rule out the size and falcon player and the same issue presents itself. The Fseq file is way too small. I am expecting a file size of MB, not KB, based on a 30 min sequence I made last year with a previous XLights version. That one had a size of 42 MB. The one I am producing now has a top score of 420 KB. 

**Expected behavior**
This 30 min sequence should have a larger fseq file size when saved. I am expecting Falcon Player to see and play a 30 min sequence and I am only receiving about 14 seconds. 

**Screenshots**

**Versions (please complete the following information):**
 - OS:Windows 10
 - xLights version 2019.55 64bit

**Additional context**
Thanks for taking the time to go through this. I really don't believe it is a falcon player issue after seeing XLights create a different sized save file after simply re-saving. Hopefully this a simple problem or button that I am just not hitting. 

**Attachments**
[Halloween2.zip](https://github.com/smeighan/xLights/files/3693966/Halloween2.zip)

**Comment by keithsw1111** [comment]
Hmmm ... maybe ... you know this years FSEQs are a lot smaller because they are now compressed. If you want the uncompressed version in the settings choose to use the v1 FSEQ format.

**Comment by dkulp** [comment]
According to the metadata in the fseq file:

`{"Name": "Halloween2.fseq", "Version": "2.0", "ID": "1570337113511112", "StepTime": 50, "NumFrames": 36000, "MaxChannel": 1020, "ChannelCount": 1020}`

that is 1020 channels for 30 minutes.   Thus, the fseq file is correct.   Most likely, you need to upgrade your FPP instance to 3.x (or at least 2.6).

**Comment by RandyBrandy** [comment]
THANK YOU SO MUCH. See, I knew this would be a simple problem. Haha. I changed to the v1 FSEQ format, but I will update falcon player soon.
