### ISSUE TITLE
House Preview rendering issue

### ISSUE THREAD

**Issue by AzGilrock** [smeighan/xLights#1746]
The house preview rendering got broken between 2019.53 and 2019.54.  You should be able to pan the view around without interrupting the display of effects but now it flashes white and looks terrible.

**Comment by keithsw1111** [comment]
I have fixed the white flash ... but there is another problem which I can see as far back as 2019.10 and seems similar to a problem you recently fixed so hoping you know how to fix this one. Basically if in layout tab you manipulate the model preview by clicking and dragging and then you switch to sequencer and click and drag to rotate it the first movement is a jump. Same happens from custom model preview so it seems a common preview problem.

**Comment by keithsw1111** [comment]
Forget it ... I found it ... you were using local statics to store the latch position. I have moved these to class variables and it seems to work as expected.

**Comment by AzGilrock** [comment]
Cool...thanks for digging into it.

**Comment by AzGilrock** [comment]
I never tested this.  I'm not able to find any version where this works right until I go back to 2019.53.

**Comment by keithsw1111** [comment]
Gil ... I must not understand this issue. I just tried this again

Dropped a butterfly on a matrix.

In 2d zoom ... no white.
In 3d spin around ... no white.

Model play and sequence play.

How do i reproduce this?

**Comment by AzGilrock** [comment]
Oh...I just realized it's only happening during panning its fine when you spin around.

**Comment by AzGilrock** [comment]
Ok I think I fixed it.  Just had to copy your changes down into the mouse wheel down section.
