### ISSUE TITLE
Model Chain

### ISSUE THREAD

**Issue by dszoka** [smeighan/xLights#1747]
**Describe the bug**
Model Chain is a random model-- in my case Cane 48 2 --

**To Reproduce**
In Layout -- have attached Packaged Sequence 

**Versions (please complete the following information):**
Xlights 2019.55 
Mac 10.14.6

[Model Error.zip](https://github.com/smeighan/xLights/files/3699975/Model.Error.zip)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3699976/xLightsProblem.zip)

**Attachments**
Package Sequence 
Log Files 
[Link to video off Error ](https://drive.google.com/open?id=1auEyvgkf49306oc4GmaSID1PJXK4nQFY)

Screen Shot
<img width="520" alt="Screen Shot 2019-10-08 at 10 08 22 am" src="https://user-images.githubusercontent.com/42435862/66355618-a220ff00-e9b3-11e9-82da-054d06ac9a7d.png">

**Comment by keithsw1111** [comment]
Isn't it disabled ... when using start channel the model chain should be inactive. Its value is irrelevant.

**Comment by dszoka** [comment]
So its just random data -- won't affect anything-- Ok 

wasn't sure, So i reported it
