### ISSUE TITLE
Setting Directories - Justification

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#175]
Using OSX 4.0.14
Un-tar'd 4.0.14 - Ran the xLights application with a blank setup
I selected the Show Directory /Volumes/share/xLights
It set all three directories to the same
I then clicked Change for the Media directory to change it to /Volumes/share/LOR/2014/Christmas/Media - and the justification of the paths is in the attached screen shot. Was centering the paths the desired look? 

NOTE also, I was unable to directly browse to the Network shared I had to use the drop down at the top of the screen and the selection of the network attached devices was not visible on the side bar  - see other issue.

![screen shot 2015-04-06 at 9 44 01 am](https://cloud.githubusercontent.com/assets/10136122/7006842/8a99f118-dc41-11e4-9e32-8018461bccf2.png)
![screen shot 2015-04-06 at 9 41 34 am](https://cloud.githubusercontent.com/assets/10136122/7006844/8e3aff10-dc41-11e4-8f0f-6bd24424af54.png)

**Comment by AzGilrock** [comment]
Sean fixed directory justification in 7f5aecaf6f9eb6a978864700b8fb9e94d30f964c
