### ISSUE TITLE
SMS Plugin

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#1753]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When the playlist is running and I go to change options I get the error
XML Parsing error: 'not well formed (invalid token)' at line 2      
BUT no crash

**To Reproduce**
Load xScheedule
Launch SMS Plugin
Start playlist
Go to Edit / Option in the plug in and error pops up

**Versions (please complete the following information):**
 - OS:Windows 7 32 bit 
 - xLights version  2019.56

**Comment by keithsw1111** [comment]
I think i have this fixed ... a side effect of the default message change
