### ISSUE TITLE
SMS Plug In Options Window

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#1754]
**Describe the bug**
When I go into options, in the Default message field there is a stray symbol before the first letter in the first word.  To get rid of it takes two backspaces.  looks like an odd dingbat or wingding

**To Reproduce**
Open SMS plug in
Go to Edit / options, 
Look in the Default message field

**Versions (please complete the following information):**
 - OS: [e.g. Windows 7 32 bit 
 - xLights version [2019.56]

**Comment by keithsw1111** [comment]
Fixed
