### ISSUE TITLE
SMS Deamon

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#1755]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Default message does not respect the spaces inserted in the background playlist to make the message smoothly loop across the P5 matrix.
The previous bug I reported was that the words Happy Halloween from the Text tab in the format window of the add text option   Happy Halloween %TEXT% had the words Happy Halloween leading the default message.   Still does it on the Virtual Matrix and will output to the matrix before the default message starts to run.  After the default message starts to run instead of starting on the right side and scrolling to the left, it pops  up on the left side then starts the scrolling process,

**To Reproduce**
Load the SMS plug in, start the playlist
Happy Halloween plays about 5 times, then when the default message kicks in the default message pops in with the first word being at the left of the screen (instead of scrolling in from the right) followed by the rest of the default message.  It scrolls, and when completed, it pops in again the the 1st character of the default message on the left side if the screen, along with the rest of the message and then proceeds to scrool

Set up message with blank spaces in the format window of the Text tab in V.55
Upgrade to v.56

**Versions (please complete the following information):**
 - OS: Windows 7 32 bit
 - xLights version 2019.56

**Comment by keithsw1111** [comment]
This is expected behaviour. The default message does NOT use the format. You can easily add the leading/trailing spaces into the default message
