### ISSUE TITLE
Crash on Pumpkin-4 element during the render, dump attached. Version 2019.58

### ISSUE THREAD

**Issue by Vlad-Star** [smeighan/xLights#1756]
Crash on Pumpkin-4 element during the render, dump attached, reproducible. xLights version 2019.58. 

[xLights_dbgrpt-3820-20191013T070817.zip](https://github.com/smeighan/xLights/files/3721672/xLights_dbgrpt-3820-20191013T070817.zip)

**Comment by keithsw1111** [comment]
Does this happen every time you render?

**Comment by Vlad-Star** [comment]
Yes. I had to remove those (I guess, incompatible) Faces elements from the sequence and replaced them with others. The props Faces they were applied to were simple set of pixels. not the singing faces or bulbs, but this shouldn't be crashing xLights.

**Comment by keithsw1111** [comment]
We believe these problems are fixed in .61. Please reopen if the problem persists.
