### ISSUE TITLE
Bug: Layout Tab Channel Block Appearance.Pixel Size Reset 

### ISSUE THREAD

**Issue by dennismccreery** [smeighan/xLights#1757]
**Describe the bug**
XLights 2019.56
Channel Block Appearance Pixel Size is reset to default 12 when leaving and restarting XLights.

**To Reproduce**
Note: No sequence necessary, this is a layout bug.
1. Open a blank Test folder
2. Click on "Channel Block" icon
3. Create an arbitrary Channel Block
4. Change the Pixel Size in the Appearance section to anything other than the default of 12
5. Save Layout
6. Close XLights
7. Reopen XLights
8. The Pixel Size is reset to the default of 12.

**Expected behavior**
Pixel size and any other attributes changed and saved should be preserved.

**Versions (please complete the following information):**
 - OS: Windows 10 64 bit
 - xLights version 2019.56

**Comment by keithsw1111** [comment]
Fixed for .59
