### ISSUE TITLE
Layout Tab: Channel Block - Reposition Individual Props

### ISSUE THREAD

**Issue by dennismccreery** [smeighan/xLights#1758]
Layout Tab: After creating a Channel Block, Props in the Layout are part of a straight string.  Cannot reposition individual channels.

Would be nice to be able to re position individual channels into an arbitrary pattern

I can create individual single pixel Props in layout to do the same thing, but it clutters up the layout.

**Comment by keithsw1111** [comment]
That is correct and it is not going to change. If you want to re-position things then you can use the other available props to create anything your heart desires.
