### ISSUE TITLE
Ability to select multiple models from model list to aid bulk editing

### ISSUE THREAD

**Issue by reelpilot** [smeighan/xLights#1759]
I have well over 100 models in my layout and I'm wanting to bulk edit assign brightness values and controller connections to specific models. From the model list I can currently only select them one at a time. On the layout screen I can hold the control key down or drag the selection box to select multiple models in order to bulk edit brightness or controller connections among other bulk editing possibilities. However in many instances the models are tightly spaced to surrounding models and inadvertent sections are common. What would be a nice feature would be the ability to select multiple models from the model/group name list. In many cases the models I'm trying to bulk edit all have the same root name, so it would be very quick and easy to select a group of them for the bulk editing.

**Comment by dszoka** [comment]
See thread Below 
https://github.com/smeighan/xLights/issues/1731

**Comment by keithsw1111** [comment]
You can click on groups to bulk select

**Comment by reelpilot** [comment]
Thanks Keith. That's a good work around.
