### ISSUE TITLE
Effect requests (4)

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#176]
1. Reverse checkbox for Garlands
2. Fake Digital VU meter
![image](https://cloud.githubusercontent.com/assets/10568498/7014997/90917c7c-dc81-11e4-9868-d74ac15c2670.png)

3. Digital input boxes in addition to the sliders for faster fine tuning on Morph.
4. Asymmetrical option on wave effect.
![image](https://cloud.githubusercontent.com/assets/10568498/7015029/18ea632c-dc82-11e4-9c00-84f2f99ed77e.png)

**Comment by LightsOnHudson** [comment]
Sean, et all..
What is the framework necessary to make effects? I googled your software and it pointed me to a few locations about instructions on spirals, etc. and making an account with your website. But, just curious how one would go about creating a new effect from scratch. Do you have an existing tutorial on it? What software IDE do you need to program in..?

**Comment by stevegiron** [comment]
That information is on the Nutcracker Wiki page.

**Comment by stevegiron** [comment]
Cancelling this request.
