### ISSUE TITLE
was trying to use Polly line

### ISSUE THREAD

**Issue by Baf05** [smeighan/xLights#1761]
I am trying to use polly line but there seems to be an issue, then xLights crashed.

[xLights_dbgrpt-15324-20191016T143731.zip](https://github.com/smeighan/xLights/files/3732354/xLights_dbgrpt-15324-20191016T143731.zip)

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Once starting a polly line, I cant end it.  Each time a double click it just creates another point.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
press the Esc key to terminate the polyline.

**Comment by Baf05** [comment]
Oh god really??? I am so sorry. That's so obvious. I have never used it before....There still was a problem that caused xlights to crash I included the bug report Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: "Scott H." <notifications@github.com> Date: 16/10/19  3:39 pm  (GMT+10:00) To: smeighan/xLights <xLights@noreply.github.com> Cc: Baf05 <brettfitzroy@bigpond.com>, Author <author@noreply.github.com> Subject: Re: [smeighan/xLights] was trying to use Polly line (#1761) press the Esc key to terminate the polyline.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/smeighan/xLights/issues/1761?email_source=notifications\u0026email_token=ANP7I6U25BVYPIBLJMD4UHTQO2LIBA5CNFSM4JBFX4P2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBLAZTQ#issuecomment-542510286",
"url": "https://github.com/smeighan/xLights/issues/1761?email_source=notifications\u0026email_token=ANP7I6U25BVYPIBLJMD4UHTQO2LIBA5CNFSM4JBFX4P2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBLAZTQ#issuecomment-542510286",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
