### ISSUE TITLE
Cannot scroll within the View section when 15+ Lyrics tracks are set to display

### ISSUE THREAD

**Issue by Vlad-Star** [smeighan/xLights#1762]
Cannot scroll within the View section when 15+ Lyrics tracks are set to display. Looks like the are not accounted as scrolling elements. Please, find the attached screenshots.
![1](https://user-images.githubusercontent.com/19923088/66962860-186ed280-f040-11e9-99aa-d1e941c79198.jpg)
![2](https://user-images.githubusercontent.com/19923088/66962865-1ad12c80-f040-11e9-90ee-6325a3ff36d6.jpg)

**Comment by AzGilrock** [comment]
Yep I don't think that's gonna change.  Just create a view without all those timing tracks or buy a bigger monitor.  That sequence only fills up half the screen on my monitor.

**Comment by tgodfrey73** [comment]
another option is to remove the lyric tracks from the view under the 'Edit Display Elements'

**Comment by keithsw1111** [comment]
this is intended behaviour
