### ISSUE TITLE
visualize controller doesnt handle props that start on something other then #xx:1

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#1765]
.58

I have some props that start on >endofmodel:13 for example to skip over some fake null pixels.
In visualize controller it lists them as those they are on the first prop of the output.

Prop1>Prop2
Prop3>Prop4

rather then
Prop1>Prop2>Prop3>Prop4

I can upload my layout if this isnt easily replicated.

**Comment by keithsw1111** [comment]
That sounds like correct behaviour ... a gap in channels should create a new virtual string which is why it appears on a new line.

**Comment by derwin12** [comment]
I can see that .. it just makes it appear like I had models overlapping. (as I rearrange props around on ports and controllers).
What about being on the same line with a filled in box or something to show the gap?
 Feel free to close this if you think its not needed..
