### ISSUE TITLE
Groups Missing 2019.59

### ISSUE THREAD

**Issue by NashionalUS** [smeighan/xLights#1766]
I have two groups with two props in them and the groups are missing from the Layout tab. One is Spinners with spinner left and right and the other is Floods with flood left and right in it.

However, the groups appear in the sequencer tab and if I open a sequence with a changed prop name the group appears in the list to rename. 

I just can see/edit them in the Layout tab.

**Comment by AzGilrock** [comment]
You gotta attach your layout files...the moose out front shoulda told ya.

**Comment by NashionalUS** [comment]
I looked but don't see a way to export the layout? However, while playing around just now still trying to find that, I figured out that they had been assigned to a preview other than default. Problem solved. :)

**Comment by AzGilrock** [comment]
That's what I suspected but easier to see in the files than to guess.

**Comment by AzGilrock** [comment]
In the future whenever we need to duplicate your layout do a Tools -> Package Log Files and it gives us everything we need in the zip file it creates.  Or if we need to see a sequence do Tools -> Package Sequence.

**Comment by NashionalUS** [comment]
Got it. Thanks!
