### ISSUE TITLE
2019.59 - Mac - Cant render, locks up Mac

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1769]
<img width="857" alt="Screen Shot 2019-10-20 at 6 09 37 PM" src="https://user-images.githubusercontent.com/40632971/67167270-bd055300-f365-11e9-98d2-1d3837c6fc00.png">
Any version i open this small sequence up it renders fine within 10 seconds on my MacBook Pro (Running Catalina) and my Mac mini (running Mojave) but on .59 it never starts to actually render, i got a small blue start at bottom but then my MacBook fan just spins up and the CPU got to 250% and the render bar doesn't move for minutes but if i got back to .58 the same sequence renders in 10 seconds

here is the packaged sequence to test if needed  -  https://drive.google.com/file/d/1baaWiboFGBTD9tCuJTwGMtR3jxKsXFI7/view?usp=sharing

**Comment by dkulp** [comment]
Fixed in .60
