### ISSUE TITLE
Sequence Now Takes 15 Minutes to Render

### ISSUE THREAD

**Issue by dennismccreery** [smeighan/xLights#1770]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Previously (with Xlights .54) I was able to render this sequence in just a few minutes.  Now, with .59 or .60, it hangs or crashes XLights.  I dropped back to .56 and it takes 14 minutes to render.  While the sequence is backed up to OneDrive, my RenderCache is specified on a local folder.

**To Reproduce**
1. Open 'Christmas_Canon.xml' with XLights 
2. Click on "Render All"
3. Note that it renders very slowly on release 56 (14 minutes) and never completes rendering on release 58-60)

**Expected behavior**
I'd expect this sequence to Render All in just a few minutes.  Thanks.

**Versions (please complete the following information):**
 - OS: Windows 10 64-bit, latest build with 16 GB memory and GeForce GTX-970 video and Intel Core I7-2600K CPU @ 3.4 GhZ
 - xLights version 2019.56, .59, .60

**Additional context**
Here's  links to my sequence and log files if that helps.

**Attachments**
Packaged Sequence:  
https://1drv.ms/u/s!Aj3J0O38KlwJg_VTEJiLBqlEKb6G8Q?e=dIZKYD

Log Files:
https://1drv.ms/u/s!Aj3J0O38KlwJg_YRQe2lwMTWLIoeXA?e=bZhczH

**Comment by AzGilrock** [comment]
I rendered your sequence in 2019.60.....5min 40sec.
![image](https://user-images.githubusercontent.com/2024669/67177345-0912c080-f383-11e9-882c-17021a90ff85.png)

**Comment by AzGilrock** [comment]
My system doesn't seem that much different than yours:
![image](https://user-images.githubusercontent.com/2024669/67177403-3a8b8c00-f383-11e9-8283-2f85ce2fef25.png)

**Comment by keithsw1111** [comment]
Did you look in the log ...

2019-10-20 16:14:59,379 8844 log_base [ERROR] LiquidEffect Render abandoned due to insufficient memory. This is not good. Rendering will be slow.
2019-10-20 16:14:59,392 8844 log_base [ERROR] To reduce memory turn off render caching and/or change liquid effect settings.
2019-10-20 16:15:00,920 9536 log_base [ERROR] LiquidEffect Render abandoned due to insufficient memory. This is not good. Rendering will be slow.
2019-10-20 16:15:00,920 9536 log_base [ERROR] To reduce memory turn off render caching and/or change liquid effect settings.

**Comment by dkulp** [comment]
Definitely a sequence I would turn off the RenderCache.   On my Mac, with render cache turned off, it renders in 96 seconds and consumes 1.7GB memory.  With RenderCache on, it renders in 94 seconds, but consumes 28.5GB of memory.    In any case, I don't see any difference between .60 and .54.

**Comment by keithsw1111** [comment]
either that or use cache on locked effects and be really selective about what you lock.

**Comment by dennismccreery** [comment]
Copied the whole show folder locally with RenderCache turned on and render time was 21 min.  Purged  RenderCache and render time was  24 min.  Disabled RenderCache and render all took 3 min 24 sec.
