### ISSUE TITLE
2019.57 onwards crash when rendering megatree

### ISSUE THREAD

**Issue by errol-head** [smeighan/xLights#1771]
xlights crashes when i render sequence since updating to 2019.57 onwards
if i install 2019.56 renders completes successfully 

**Versions 
 - OS: Mac 10.14.6
 - xLights version 2019.57

**Additional context**

**Attachments**
package sequence 2019.56 and crash file in dropbox link below
https://www.dropbox.com/sh/c5vlhont2wzanh7/AABiKClclZqLsvrBLQBYf33Ka?dl=0

**Comment by dkulp** [comment]
Can you try with .60 as we added a bunch of tracing into the video reader which is where the crashes are occurring.

**Comment by errol-head** [comment]
Hi Daniel. No difference with 2019.60 it is still crashing
