### ISSUE TITLE
Effect Label Colors not maintained properly when adding effect

### ISSUE THREAD

**Issue by onewithhammer** [smeighan/xLights#1772]
**Describe the bug**
The Label color on a model isn't maintained when adding an effect.  It changes from orange to white.

**To Reproduce**
Load my sequence - Notice all the submodel  effect/label colors are orange. See screenshot
<img width="824" alt="Effect-Colors1" src="https://user-images.githubusercontent.com/10877476/67240729-0ca85500-f420-11e9-872b-a19de2565625.png">

Next select submodel (body) on first model (Small-Pumpkin-1) using AC mode - select area in timing marks for body - added Ramp Up effect.

<img width="804" alt="Effect-Colors2" src="https://user-images.githubusercontent.com/10877476/67240774-28136000-f420-11e9-94eb-bc547634cc26.png">

Notice the effect/label changes to white:

If you save the sequence and reload the effect/label is now orange and correct.  Xlights is saving it properly but not displaying it properly.

<img width="799" alt="Effect-Colors3" src="https://user-images.githubusercontent.com/10877476/67240851-4d07d300-f420-11e9-94e3-5008b9d3cc58.png">

**Expected behavior**
I expect the effect/label colors to remain the same color after adding the effect

**Versions (please complete the following information):**
 - OS: Mac 10.14.6
 - xLights version: 2019.60 October 20 2019

[IntroVoiceCreepy.zip](https://github.com/smeighan/xLights/files/3752780/IntroVoiceCreepy.zip)

**Comment by AzGilrock** [comment]
Yep just a display issue.  We used to always display single color channels as white.  They were changed to try to represent the color but that is purely to make the user feel better when sequencing.  The actual output isn't affect just looks like a display refresh issue.

**Comment by onewithhammer** [comment]
Okay - so this will be fixed at some point?

**Comment by AzGilrock** [comment]
I would assume so.  Its probably easy but there are so many new crash reports coming in every day things like this sometimes drop down the list.  I'm headed for a vacation so I know I won't be looking at it for a week.

**Comment by AzGilrock** [comment]
I just tested this in 2019.61 and I cannot reproduce the issue.  The colors are all staying orange.  Also when you said you did a Ramp Up the Ramp Up only works in combination with one of the other options so did you use it in combination with the On effect?

**Comment by onewithhammer** [comment]
Hi Gill - I downloaded 2019.61 and I'm not able to reproduce this issue either.  The colors are all staying the correct colors.  I assume it is fixed.  If I'm able to reproduce it, I will let you know.

**Comment by AzGilrock** [comment]
Ok.  I didn't see anything in the change descriptions to account for the fix but sometimes they sneak them in under another description.
