### ISSUE TITLE
xFade 2019.59 Crashing 

### ISSUE THREAD

**Issue by psytecaus** [smeighan/xLights#1773]
xFade appears to crash for no reason after a while of using it. I have attached the debug report.. Please help me with this as it is causing me alot of issues when running a show.

With the most recent crash i dont have any midi setup or any complex config, just 2 identical xlights 2019.59 instances running.

[xFade_dbgrpt.zip](https://github.com/smeighan/xLights/files/3759653/xFade_dbgrpt.zip)

**Comment by keithsw1111** [comment]
So you are sure they are the same ... ie same show folder.
Are you doing protocol conversion? E131->ARTNET or vice versa?
I can only see one possible reason for a crash (but it looks unlikely). If you want to try it (windows 64 only) you can access it here. https://www.dropbox.com/s/c2aj4rzl2mp3qlk/xLights64_2019_60.exe?dl=0

**Comment by psytecaus** [comment]
Yep, identical files, same show folder just running two instances of xlights at the moment to test setup and patterns

Not doing any protocol conversion, and currently have only one input and output mapped, the final setup will be to multiple devices. 


Will try the link you provided now. Thanks

**Comment by psytecaus** [comment]
Stilll having the same crash , randomly ...

[xFade_dbgrpt-20088.zip](https://github.com/smeighan/xLights/files/3763867/xFade_dbgrpt-20088.zip)

**Comment by keithsw1111** [comment]
Hmmm ... so crash is in the same place ... PacketData::CopyFrom.
Seems to happen after about 15-20 mins ... is that normally how long it takes to crash? Trying to work out how long i need to run it for before deciding i can or cannot reproduce it.

**Comment by psytecaus** [comment]
Yea, it seems likes it gets to the 20-30min mark and then just locks up and crashes. On the last test I had both instances playing a pattern and just let it run on then without changing anything and it ran for a while then died.. I'm happy to send you the xlights project privately if that would help but it's happened on other ones too

**Comment by keithsw1111** [comment]
I am running a test now. 2 xlights ... 1 universe into xFade ... lets see if it crashes.

**Comment by keithsw1111** [comment]
Almost 1.5 hrs no crash ... Maybe you do need to send me a setup and export your xfade config.

**Comment by psytecaus** [comment]
So i sent you a msg on FB as i dont really want to post my xlights project publicly , but i have 300 universes currently pushing through xfade ( will be more in the final setup ), could it be related to that? Like a var overflowing because of the high packet count?

**Comment by keithsw1111** [comment]
You said: "currently have only one input and output mapped" ... now its suddenly 300? Which is it?

**Comment by psytecaus** [comment]
Sorry i might not of explained my self too well. Out of xlights i have 1 output of 300 universes per session going to local host, then xfade mapping those to one ip/output. 
![xfadeoutput](https://user-images.githubusercontent.com/16601594/67612598-6e373d80-f7eb-11e9-9d54-3a598b6b2204.JPG)
![Xfadebugxlightoutput](https://user-images.githubusercontent.com/16601594/67612599-6e373d80-f7eb-11e9-862d-41503a65eee1.JPG)

**Comment by keithsw1111** [comment]
There is a fair chance this is fixed in .61

**Comment by psytecaus** [comment]
Thank you, I have already downloaded in and have it running now. I will let you know how it goes.

**Comment by psytecaus** [comment]
After testing it for the last 4 or so hours it has been running well, but has completely just quit on me twice without the debug report appearing, or freezing before hand soo I don't know how I can send a log for it or even if you could replicate this..

**Comment by keithsw1111** [comment]
When I run it at full speed it crashes in the wxWidgets framework. When I run it under application verifyer to try and catch anything funky going on ... it never crashes. Frustrating.

**Comment by psytecaus** [comment]
That's very weird. Is there anything i can do to assist either finding the cause of the crash or fixing it? I very much appreciate all the work you've put in to fixing this bug so far, am im hoping we ( mainly you with me testing/pestering :P ) can get it stable as I plan to use xlights/xfade on a big show coming up in November

**Comment by psytecaus** [comment]
So i just had this pop up whilst running xfade, it didnt crash, but is not sending any data anymore(sent counter stopped) but is still still receiving Not sure if it will help at all because the error is completely generic but maybe it will give you a clue as to where to look? 

Just trying to send you as much info as possible. 
![xfade20191027crash](https://user-images.githubusercontent.com/16601594/67634332-628e6880-f90a-11e9-8005-3a9f3c35bb73.JPG)

**Comment by keithsw1111** [comment]
are you really running that many universes. 

the tool i normally rely on in these situations to find hard to find memory corruption finds nothing but it also slows it down so much it may be impacting the cause.

just not sure where to go next.

**Comment by psytecaus** [comment]
Actually the final count of universes will be closer to 400 (409 currently the Max controller outputs which is 4x pixlite 16's and one pixlite x4 )  And yes, I do very big installations generally using 500M+ of strip and/or other pixels. 

And I know xlights can handle this very well(and xschudele for that matter) as I recently used it for a show with about 1km of Led strip. (358 universes) 

Could it be something like a Var overflowing due to the sheer number of packets being sent/received causing wxwidgets to crash thus xfades sudden exits without being caught 

Failing being able to find the cause, is there a way xfade could auto reconnect to xlights if it doesn't cleanly exit on next open? That way I could run a task watcher in the background and if it sees xfade unload then it would reopen it and the show would go on?

**Comment by keithsw1111** [comment]
If you have a task watcher it will auto pick up the transfer of data ... you will need to press the connect button to get the buttons connected.

It is not simple to understand why it fails in wxWidgets and it is not necessarily a wxWidgets problem but it could be. Problem with these things is you need to catch the problem either when it occurs or just before it occurs ... but it successfully processes 10s of thousands of requests and then fails in the guts of wxWidgets ... that makes it really hard to catch the cause.

I have been adding more and more protection ... but even this has a downside as it takes extra time to process every packet.

I havent given up yet.

**Comment by keithsw1111** [comment]
Try this version ... I have optimised a whole bunch of stuff and it seems more stable.

https://www.dropbox.com/s/x8zsv0jzbms2dc8/xLights64_2019_61.exe?dl=0

I am concerned about throughput though ... it seems to be CPU bound on the input side and I am not sure it is seeing all the arriving packets.

**Comment by keithsw1111** [comment]
If throughput proves to be an issue there is a change I can make to the memory locking which may help improve it ... but there is a risk it will also make it worse so I am not keen to do it unless it proves necessary.

**Comment by psytecaus** [comment]
Unfortunately i am away for my rig for a few days so cant test the throughput yet, but i did a dry run over night with xfade outputting to a e1.31 virtual receiver (not the best test) and it ran all night. I will do a proper test this weekend and let you know how it goes. Also love the option of UI performance mode :)  Thank you for all your hard work on this so far , really appreciate  it. Will keep you updated when i have access to my rig :)

**Comment by keithsw1111** [comment]
This is an experimental version with the packet handling totally rewritten. I believe it should be able to handle your 300-400 universes but like any major rewrite there is a chance i introduced new bugs.
https://www.dropbox.com/s/ik4tmhg9uz696po/xLights64_2019_61.exe?dl=0

**Comment by psytecaus** [comment]
Hey! So just started testing the newest version you send me and it's been going well so far.. But I have noticed the channel slider (to switch between A and B) is mapped backwards now.. Ie if I've got it all the way to the left(A), it's outputting the selected right (B) pattern and vice versa.

**Comment by keithsw1111** [comment]
Can you tripple check that ... it may be that you need to redo the connect to see which is which.

**Comment by keithsw1111** [comment]
The way i determine left/right by necessity needed to change but i didnt think i got it that wrong.

**Comment by keithsw1111** [comment]
Actually ... I see the problem. Fix will be in .62.

**Comment by psytecaus** [comment]
Awesome! I haven't updated to .62 yet, but the .61 version you sent me has been running for three days without issue. Once again I would like to thank you for all your hard work on this! Your a legend!
