### ISSUE TITLE
Import of LOR S5 .loredit skipping some events

### ISSUE THREAD

**Issue by davidslowik** [smeighan/xLights#1774]
Importing S5 sequence into a sequence and not all of the effects are showing up.  This is a 16*50 tree. Strand 10 is missing the events for all but the first pixel. I have opened the .loredit in LOR and verified effects are on all pixels of all strands.

1. New Sequence.
2. Import .loredit file - xmap file attached as .txt.
3. Examine the imported sequence.
4. For example, events are seen for all pixels on strand 9. Strand 10 only has the first pixel populated.  - screenshot attached.

 - OS: Windows 10
 - xLights version 2019.56

**Attachments**
[loredit-mapping.txt](https://github.com/smeighan/xLights/files/3759652/loredit-mapping.txt)
![missingeffects](https://user-images.githubusercontent.com/56902524/67351172-6d17bf00-f512-11e9-8b7a-3469b53ef1b1.PNG)

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
This is a purchased sequence, so I cannot post it publically but will provide it directly when asked.

**Comment by keithsw1111** [comment]
Going to need a full set of files to reproduce the problem. PM me on facebook or at nutcracker.com or ask on zoom for my email address.

**Comment by davidslowik** [comment]
Files sent.

**Comment by keithsw1111** [comment]
I think i have this fixed for .61

**Comment by keithsw1111** [comment]
We believe these problems are fixed in .61. Please reopen if the problem persists.
