### ISSUE TITLE
Render Cache appears to be invalidated on XLights startup

### ISSUE THREAD

**Issue by dennismccreery** [smeighan/xLights#1776]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Did a Render All in XLights, time was: 148.456 sec, closed and reopened XLights and immediately did a Render All again, time was now 654.896 seconds. Another Render All immediately after that took 148.952 seconds. So it appears that XLights is invalidating the Render Cache when it starts up. This drastically reduces any advantage that the Render Cache might bring.

**To Reproduce**
1. Open XLights and bring up test sequence below
2. Perform a Render All and note the time it takes
3. Immediately perform another Render all and note the time it takes, should be much shorter
4. Close XLights
5. Reopen XLights and load the same, unchanged sequence
6. Perform a Render All, note that the time it takes is now similar to that in step 2 above
7. Immediately perform another Render All and note that the time is much shorter, similar to that noted in step 3 

**Expected behavior**
The Render Cache contents, barring any changes to the underlying sequence or content, should persist as valid across invocations of XLights.  It appears that XLights is invalidating the contents of the Render Cache on startup, regardless.  This, I think, incurs a huge performance penalty and makes the Render Cache ineffective except during a single XLights session.  Thanks.

**Versions (please complete the following information):**
1. OS: Windows 10 64-bit, latest build with 32 GB memory and GeForce GTX-970 video and Intel Core I7-2600K CPU @ 3.4 GhZ
2. xLights version 2019.60

**Additional context**
Render Cache should not be invalidated unless the content has changed.

**Attachments**
Packaged Sequence:
https://1drv.ms/u/s!Aj3J0O38KlwJg_VTEJiLBqlEKb6G8Q?e=dIZKYD

Log Files:
https://1drv.ms/u/s!Aj3J0O38KlwJg_YRQe2lwMTWLIoeXA?e=bZhczH

**Comment by keithsw1111** [comment]
There is nothing in the log that shows that the cache is being dumped because it is invalid.

**Comment by dennismccreery** [comment]
Just started XLights 2019.60 after sitting for a few days.  No changes to the sequence from the last time Render All.  Clicked on Render All again and it took 651.406 seconds.  There were 1034 files in the Render Cache folder (C:\RenderCache\RenderCache\Christmas Canon_RENDER_CACHE).  

Closed and reopened XLights and RenderCache folder above was cleared, so it is now empty.  So it is either being cleared when XLights is shut down or on startup.

**Comment by keithsw1111** [comment]
Unless you can give me a log that spans those events then i cant help

**Comment by dennismccreery** [comment]
Here you go:

2019-10-25 15:28:49,762 13768 log_base [INFO] ******* OnInit: XLights started.
...
2019-10-25 15:30:47,564 13768 log_base [DEBUG] Opening FSEQ File at: 'C:\Users\denni\OneDrive\Documents\Xlights\Show 2019\Christmas Canon.fseq'
...
2019-10-25 15:31:03,619 13768 log_base [DEBUG] Rendering all.
...
2019-10-25 15:41:35,852 13768 log_base [INFO]    iseq above effects done. Render all complete.
...
2019-10-25 15:42:10,606 13768 log_base [DEBUG] Closing sequence.
...
2019-10-25 15:42:39,934 13768 log_base [DEBUG] Closing render cache folder C:\RenderCache\RenderCache\Christmas Canon_RENDER_CACHE.
...
<< Files in RenderCache were deleted here >>>
2019-10-25 15:42:41,224 13768 log_base [INFO] Sequence closed.

[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/3774076/xLights_l4cpp.log)

**Comment by keithsw1111** [comment]
We believe these problems are fixed in .61. Please reopen if the problem persists.

**Comment by dennismccreery** [comment]
Thanks, now no longer deletes files from RenderCache on shutdown.
Unfortunately first RenderAll after startup still takes 10+ minutes
Second one takes 144.138 seconds (a bit over 2 minutes).
Attached is log, highlights here:

2019-10-26 04:14:43,350 7240 log_base [INFO] ******* OnInit: XLights started.
2019-10-26 04:14:43,350 7240 log_base [INFO] Version: 2019.61
...
2019-10-26 04:15:55,369 7240 log_base [DEBUG] Sequence all loaded.
...
2019-10-26 04:16:06,148 7240 log_base [DEBUG] Rendering all.
...
2019-10-26 04:27:10,136 7240 log_base [INFO]    iseq above effects done. Render all complete.
<< 1st Render All took 11:04 >>
...
2019-10-26 04:31:03,865 7240 log_base [DEBUG] Rendering all.
<< 2nd Render All >>
...
2019-10-26 04:33:28,001 7240 log_base [INFO]    iseq above effects done. Render all complete.
<< 2nd Render took 2:24 >>
...
2019-10-26 04:45:08,942 7240 log_base [INFO] xLights Closed.
2019-10-26 04:46:05,719 3172 log_base [INFO] Start Time: 2019-09-26_04-46-05-383.
<< Xlights Closed and Reopened >>
...
2019-10-26 04:47:37,641 3172 log_base [INFO] LoadSequence: Loading sequence C:\Users\denni\OneDrive\Documents\Xlights\Show 2019\Christmas Canon.xml
<< Reloading Sequence >>
...
019-10-26 04:47:39,785 3172 log_base [DEBUG] Sequence all loaded.
...
2019-10-26 04:49:44,759 3172 log_base [DEBUG] Rendering all.
<< Next Render All - after XLights closed and reopend, no changes >>
2019-10-26 05:02:58,273 3172 log_base [INFO]    iseq above effects done. Render all complete.
<< Render All took 10 min 17 sec >>

Log attached.

Thanks,
Dennis
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/3774795/xLights_l4cpp.log)

**Comment by keithsw1111** [comment]
Isnt that what you would expect? Slow first render ... fast subsequent renders.

**Comment by dennismccreery** [comment]
Yes, the behavior is as expected the first time.  But once XLights is closed and reopened it forgets about the RenderCache.  Since the RenderCache is persisted to disk, I'd expect XLights to use it for the next session (after being closed and opened).  After all, nothing has changed.  What's the point of persisting the RenderCache to disk if not to allow the information to be used in subsequent sessions?

**Comment by keithsw1111** [comment]
From your log ...
2019-10-26 04:07:39,139 9152 log_base [DEBUG] Cache contained 1034 files.
2019-10-26 04:24:41,104 3584 log_base [DEBUG] Cache contained 1034 files.
2019-10-26 05:00:35,456 6268 log_base [DEBUG] Cache contained 1034 files.

Evidence it loaded the cache.

**Comment by dennismccreery** [comment]
Yes, that's what's puzzling.  It loaded the cache but apparently didn't use the information the first time after XLights is started.  Perhaps there's some information about the cache that's generated during the session but not persisted to disk that precluded using it?

**Comment by AzGilrock** [comment]
Keith I experience the same behavior after testing a couple sequences.  I render all and its 36sec. Then I do a Save.  Then I hit Render All again and it's 21sec.  Ok great.  Now close xLights and then reopen the sequence, wait a few seconds then hit Render All and its 34sec.  Then I hit Render All a second time and its 21sec.

**Comment by keithsw1111** [comment]
I have added some optional rendercache logging which will be in .62 which will tell you what is going on. You will need to edit the xlights.<platform>.properties file to turn it on. Set it to INFO or DEBUG for differering levels of logging.

**Comment by dennismccreery** [comment]
Thanks Keith.  Did the same repro sequence above with logging turned on, here's the results (attached log) starting after I updated to 2019.62.  I changed in xlights.windows.properties logging to this:

log4cpp.category.log_render_log=DEBUG, A1
log4cpp.category.log_rendercache=DEBUG, A1

It looks like XLights is loading the ENTIRE RenderCache into memory for the first RenderAll.  This is 26.4 GB or 1034 files and is what's taking the bulk of the time for the first RenderAll.  Why not "lazy load" the RenderCache only as needed if anything's changed?

Here's what I did.  
NOTE: I used the same sequence: "Christmas Canon.xml" which is unmodified for all steps

1. Opened XLights 2019.62
2. Opened Sequence "Christmas Canon.xml" 
3. Did a RenderAll (took 10 min)
4. Did another RenderALl (took about 2 min)
5. Saved the Sequence
6. Closed XLights
7. Reopened XLights
8. Reloaded the Sequence ("Christmas Canon.xml")
9. Did a RenderAll (took 10 min)
10. Did another RenderAll (took 2 min)
11. Did another RenderAll (took 2 min)

Log is attached.

Thanks.

[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/3800939/xLights_l4cpp.log)

**Comment by keithsw1111** [comment]
The log seems to prove the render cache is working exactly as expected.

**Comment by dennismccreery** [comment]
If that's the case, why does the sequence take 10 min to render with the Render Cache enabled but 3 minutes to render without it?

**Comment by keithsw1111** [comment]
It could be slow storage ... but what it definitely isnt is the render cache not being used.
