### ISSUE TITLE
xSchedule locks up playing sequence

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#1777]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Load xSchedule, 
highlight the playlist with the one item in it
hit play
enjoy the lights
in less than 1:00 the display starts to studder and  then the display freezes
About :20 later xScheduler does not see the controllers any longer
A power cycle of the controllers brings them back

**To Reproduce**
see above

**Expected behavior**
sequence should play all the way through.
fyi It does play all the way through in xLights

**Versions (please complete the following information):**
 - OS: Windows 7
 - xLights version [e.g. 2019.59 and now 60

**Additional context**

**Attachments**
here is the log
[xSchedule_l4cpp.log](https://github.com/smeighan/xLights/files/3764353/xSchedule_l4cpp.log)

**Comment by keithsw1111** [comment]
Is this reproducible. I see it in the log ... possibly contributed to by this warning during the audio load:

2019-10-23 16:23:55,604 2644 log_timer [WARN]     Waited 3 seconds for thread to lock and didnt see it ... maybe because it grabbed it early.

There is additional logging we can turn on but it is only useful if this is reproducible.

**Comment by JoelDearing** [comment]
I would think so.  If I packaged the sequence and had you load it up, run it through a switch into a falcon controller, even a 4 port controller, the lights should lock up
Is there  a config file that xSchedule has, that may give you a map on how I have this set up?  This the set up where I am using OSC and having a light board tell xSchedule to fire the sequence.   That works well, btw.  
When the light board sends the command to start the sequence in xSchedule the output to lights will show light errors and freeze at :20 seconds.  The music continues to play.
When I start the sequence in xSchedule, just clicking the play sequence button, the output to lights will show light errors and freeze at :20 seconds.  The music continues to play.
In both cases the controllers loose connectivity with xSchedule, and even at the command prompt they will not reply to a ping. We have to turn them off and back on.
We have tried going directly from my computer into the switch I always use for my show, and into the falcon controllers.  Like above, the lights freeze at :20 seconds, the music continues to play.
I thought that because the trees are 200 pixels per string and 16 strings, it was choking on the data.  In xLights I deactivated the tree controllers, rendered, saved, went back to xSchedule saw that xSchedule only say the four port controllers for the 270 node stars, played the sequence without the OSC firing, and the lights locked up even quicker,
I took a video of the lights locking, and then showing xSchedule losing the controllers if you want to see it.

**Comment by JoelDearing** [comment]
fyi, I have been running my Halloween display for the last couple of days without a problem.  Same version as above, sequences are older, but have been rendered to .60.  The only change I have made to xSchedule is to change to the Halloween directory.  The only major difference between the Halloween xSchedule and the problem mentioned above is that OSC has been activated above.
