### ISSUE TITLE
2D Sphere Model

### ISSUE THREAD

**Issue by RyanKasperCook** [smeighan/xLights#1779]
Noticed a bug in 2D with Sphere model.  Basic sphere model being used, 32 strands of 100 lights starting in bottom left.   Currently no way to set if wired clockwise or counterclockwise.  When in 3D view, Strand 1 starts in the back and Strands 2-32 go CounterClockwise... but in 2D, Strand 1 starts in the front and Strands 2-32 go Clockwise.

Would it be possible to add some variables to the layout screen to allow user input of wiring direction?  Also would be great if we could do different degrees of sphere like we can on mega trees, 180, 270 etc..  

Thank you very much for the bug/enhancement consideration!

**Comment by keithsw1111** [comment]
Is there not a start location setting?

There is no difference between 2D and 3D ... in fact the model knows nothing about 2d vs 3d at all.

**Comment by keithsw1111** [comment]
There is a start location ... can you clarify the problem because as far as i can see this is all existing functionality

**Comment by RyanKasperCook** [comment]
Sorry Keith, I was trying to get more detailed video for you to see.  I think your right, 2d and 3d are both acting the same, I have model starting on bottom left, and strands go counter clockwise… however when I am outputting to lights, the strands go clockwise, I have triple checked the networks setup screen and controller configuration and all is accurate.  This is also happening on 3 different show folders, all running .56 version.

I think simplest solution would be to add a CW CCW direction in layout parameters so it could be reversed if wired differently?  I will try to get some footage tonight to show you, just been swamped so I apologize for delay.  thank you Keith!

**Comment by keithsw1111** [comment]
We already have CW/CCW ... just choose left or right bottom

**Comment by RyanKasperCook** [comment]
Oh, that’s awesome, I wasn’t aware of that!  That will fix my issue for now, I will still try to get you more live output results so you can see how its outputting in reverse.  Otherwise only other thing that would be nice is having degree of prop like mega trees, ie 180, 270 etc… but not critical as I am sure you have more important bugs to deal with.

Thanks for everything Keith, appreciate it!
