### ISSUE TITLE
Deleting Wholehouse model in model list whilst open in sequencer crashes xlights.

### ISSUE THREAD

**Issue by buzzdude** [smeighan/xLights#178]
Hi
Create musical sequence and select whole house model. Drag effect in sequencer. Goto Preview tab, model list and delete and/or recreate whole house model.  Return to sequencer tab and click on effect.  Xlights crashes.
Thanks
Shane

**Comment by buzzdude** [comment]
Hi, now that xlights no longer crashes, (thank-you), I have found that there is still a remaining effect, similar to issue 125, in the timing mark.  Deleting the timing mark or adding a new effect, still has the old effect showing.  (not sure to whether open a new issue or this is part of the current issue), thanks.  Shane

**Comment by AzGilrock** [comment]
That's just the way the code work if you don't have any data layers.  Data rendered to the sequence is the same as if it had been read from the FSEQ file at startup.  We don't clear out that data we only render new effects over top of that data.  There is an enhancement request #141 to provide a button to clear out the data.  Personally I don't like the way its working.  Its designed for people too lazy to put imported data into a data layer.

**Comment by AzGilrock** [comment]
I looked at #141 again and I thought it was suggesting a button but it's an option which is what I was about to suggest.  So that should work out that user's can set it as a preference and it will always work however you leave it.

**Comment by dkulp** [comment]
Gill, 

Could a setting be added to the settings dialog for the "Nutcracker" layer:

![screen shot 2015-04-09 at 2 36 29 pm](https://cloud.githubusercontent.com/assets/91569/7074088/de43a076-dec5-11e4-82c5-1d0f5bf698ea.png)

so you can double click on the setting to toggle if it's "clear on render" or not?

**Comment by AzGilrock** [comment]
That was just an informational field to show the iseq filename so I just defaulted the text that that for the Nutcracker layer.  But I think we want it to be a global setting for how a user likes to work.  I think an option that when set lets the code skip over lines 303-307 in SeqFileUtilities.cpp would do the trick.

**Comment by AzGilrock** [comment]
Reading that again I'm not sure I knew what you meant.  I thought you were suggesting a user could click right there in that listbox but you also mentioned the settings dialog.  I wouldn't mind having that text change to show <Erase before render> if that's the way the setting is.  I just didn't think we wanted them to need to click that setting for every sequence they create.

**Comment by dkulp** [comment]
I would greatly prefer a "per sequence" setting of some sort (don't care what the default is).   A global setting is fine, but be able to override on a per sequence basis is important to me.

**Comment by AzGilrock** [comment]
I'm mainly trying to reduce the number of questions we've been getting from users when they don't understand why something didn't disappear.  So I don't mind it being a per sequence setting.

**Comment by dkulp** [comment]
I'm also OK with the default being "cleared and rendered" as long as that can be turned off.   Would likely eliminate most of the questions.
