### ISSUE TITLE
Import of LOR S5 .loredit crashing

### ISSUE THREAD

**Issue by davidslowik** [smeighan/xLights#1780]
This could be related to issue 1774 which is importing a .loredit and not all effects are coming over. In this case, importing causes a crash. This is a different XLights and LOR sequence.
This is a 16*50 tree that is being imported. 

Open exiting Sequence.
Import .loredit file - xmap file attached as .txt.
Crash when OK is clicked - crash report attached.

Packaged sequence and purchased .loredit file emailed separately.

OS: Windows 10
xLights version 2019.56
[mapping.txt](https://github.com/smeighan/xLights/files/3765296/mapping.txt)
[xLights_dbgrpt-9200-20191023T203855.zip](https://github.com/smeighan/xLights/files/3765298/xLights_dbgrpt-9200-20191023T203855.zip)

**Comment by keithsw1111** [comment]
This will be fixed in .61
