### ISSUE TITLE
Changing Sub-Models Crash

### ISSUE THREAD

**Issue by HiddenLakeLights** [smeighan/xLights#1783]
xLights freezes then crashes when I adjust my submodels in my layout tab. 

To reproduce:
go into your edit submodel option on a prop
adjust something
press ok
then save your layout.
xLights then crashes... for me anyway

**Comment by keithsw1111** [comment]
Can you make a video of how you are doing this ... we have tried and dont seem to be able to produce it.

**Comment by keithsw1111** [comment]
Closing due to lack of response.
