### ISSUE TITLE
.60 Crashing when applying effect to the whole house group

### ISSUE THREAD

**Issue by broomy111** [smeighan/xLights#1787]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.
Hi Xlights team-

When applying the fire effect to the whole house group around the 1:09 area, Xlights will freeze up on me.  Sometimes I can start changing the hue, and after a bit it will freeze.
**To Reproduce**

1. Applying the fire effect
2 Freezes up
3 Screen shot attached showing the location I'm dropping the effect.

 - OS: Windows 10  pro
 - xLights version 2019.60

I would rather not post my sequence, so let me know where to send the link to all the files

Thanks guys

Kevin Broomfield

broomy111@gmail.com

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
We believe these problems are fixed in .61. Please reopen if the problem persists.

**Comment by broomy111** [comment]
Thanks you
