### ISSUE TITLE
Uploading models to F48 deletes smart receiver "C" settings

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1788]
No sure if this is on the Xlights side or Falcon F48 side, Im on .61 the F48 is V2.53 which is the latest as of 10/26/19, 

I upload all my data from Xlights to the F48 and everything comes over except smart receiver "C" settings, the dumb receivers and smart receiver A and B come over but C does not upload. If I manually add "C" to the F48 and configure it all is well but if I make any changes to xlights and upload the new config, it deletes all my "C" receivers again.

Video - https://youtu.be/wfD5Uu7D7Y0

**Comment by keithsw1111** [comment]
Can you tools/package logs and post them

**Comment by bchiaino** [comment]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3775850/xLightsProblem.zip)


no problem, here you go

**Comment by keithsw1111** [comment]
So you have an odd setup. your models on c have the same start channels as the models on b so we are dropping them. while technically not invalid it is very unusual. fix will be in .62.

**Comment by bchiaino** [comment]
If they are on separate universes though shouldn't that not matter? just want to make sure im not doing something wrong. thanks Keith!
