### ISSUE TITLE
xlights ver .61 will not show video files after render

### ISSUE THREAD

**Issue by Gary6502** [smeighan/xLights#1789]
xlights ver .61 does not show any video files on the model preview nor will it render videos out on the House Preview window.

Reverted back to ver .56 and videos work normally again with output on House Preview.

Windows 10 Pro
xLights64_2019_61

Easiest way to reproduce is open last years The Greatest Show in ver .61 then render.  No video files will show in the House Preview window on playback.  Switch back to a previous version (.56 is what I'm using) and the videos will render fine and show on playback.

**Comment by jeffcreed** [comment]
I have the similar issue after upgrading from .60 to .61 - videos are not rendering correctly on my matrix.  As soon as play starts the matrix becomes pixelated.

Win10 Pro
xLights64_2019_61

**Comment by kthuet** [comment]
Me too, sometimes the whole program shuts down while rendering, happening on 3 songs now, all have videos.

**Comment by keithsw1111** [comment]
Either turn off hardware decoding or post logs.

**Comment by jeffcreed** [comment]
Mine hasn't crashed, but attached is log from loading file.  Nothing else seems affected.
[logExtract.txt](https://github.com/smeighan/xLights/files/3775596/logExtract.txt)

**Comment by keithsw1111** [comment]
So you are using hardware decoding ... have you turned it off as suggested?

**Comment by keithsw1111** [comment]
You can try this win64 version ... it may help https://www.dropbox.com/s/iuh3wirb1dkeox6/xLights64_2019_61.exe?dl=0

**Comment by jeffcreed** [comment]
Sorry Keith, crossed conversation with the sequencer here.  I have now confirmed that yes turning off the Video Decoder fixed the rendering for me.

**Comment by Gary6502** [comment]
verified turning off Hardware Video Decoder under Settings menu fixes my video problem.  Thanks Keith!
