### ISSUE TITLE
Blur v.2 

### ISSUE THREAD

**Issue by Atdj1997** [smeighan/xLights#1792]
Hi!

I just starting to use the BLUR Feature to a more blend my layer look for some of the Line stuff...

But if I turns the Blur up more then 2-3 in intensity, it starts to "Wash out" the colors too, ill like to just make the Edges more "Out of focus" if that makes sense?

So you still got a clear effect, but just lets the edges fade-blend more in from 0% / Background.! 

If there is somehow this can get achieved, let me know - else ill hope you get the meaning of this! 
Thanks.

**Comment by keithsw1111** [comment]
Maybe you can find a shader that does that ... maybe something like https://www.interactiveshaderformat.com/sketches/182

**Comment by Atdj1997** [comment]
Arhh yeah of course... didn't think about that!
Another thing, where do I find the glediator Available? 
I can't get to their webside...

**Comment by keithsw1111** [comment]
It seems like his website is offline: http://www.solderlab.de/index.php/software/glediator
