### ISSUE TITLE
eseq Render and Export issue

### ISSUE THREAD

**Issue by denniskuntz** [smeighan/xLights#1793]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
If I export my group model to eseq or or compressed eseq using the "Render and export" option the .eseq file is not correct. 

**To Reproduce**
Attached is my TuneTo sequence that is not working for me. Right click on the Tune To group model and choose Model, Render and export, choose either compressed or standard "Falcon Pi...
eseq option. The resulting .eseq file is incorrect for the few seconds where the animated gif graphic  is in the 1st layer. To keep it simple, the output, including the text, is "garbled" during the time the graphic is displayed. This is probably not a huge deal as the Model, export option seems to work correctly. For me the compressed files are 1k different in size between the Export and the Render and export options. Probably not relevant but using Falcon player 3.4.1 on a PI. Using colorlight card and P10 panels for my tune to sign. Didn't test if the issue exists if I export only a model and not a group model.

**Expected behavior**
Both the Model, export and the Model, render and export should produce working .eseq files.
**Screenshots**
NA

**Versions (please complete the following information):**
 - OS: Win 10 1809
 - xLights version : 2019.61 64bit

**Additional context**

**Attachments**
[tuneto2019.zip](https://github.com/smeighan/xLights/files/3781087/tuneto2019.zip)

Hope attachment works, (seems to for me) didn't scroll down to see the dropbox suggestion till after uploaded. I can send packaged sequence or put on dropbox if needed.

**Comment by kppankratz** [comment]
Per the FPP user manual, FPP only supports one model per eseq file.  But you can have multiple effect sequences targeting different models running at the same time.

https://falcon-player.gitbooks.io/falcon-player-manual/content/chapter_seven_status__control/effects.html

**Comment by keithsw1111** [comment]
I am not surprised ... i dont think model groups really export correctly to eseq files ... the only way they would is if all channels were contiguous.

**Comment by annjohnson** [comment]
I am having trouble creating eseq files.  I was able to create some successfully, but now every time I attempt to, the program crashes during rendering and export.

I sometimes will see a file with the name I wanted, but it has 0kb, or a file does not show up at all.  

Is this a new issue?  Should I create my own ticket?

**Comment by AzGilrock** [comment]
> I am having trouble creating eseq files.  I was able to create some successfully, but now every time I attempt to, the program crashes during rendering and export.
> I sometimes will see a file with the name I wanted, but it has 0kb, or a file does not show up at all.
> Is this a new issue?  Should I create my own ticket?

One question is are you export a single model or a model group?  We already know model groups probably won't work.

**Comment by annjohnson** [comment]
Single model.

I updated my xLights software to 2020's version, and that seemed to solve
my problem! It had been the 2018 edition.
