### ISSUE TITLE
Rendered FSEQs  dont play

### ISSUE THREAD

**Issue by JoeSchulze** [smeighan/xLights#1794]
When rendering sequences FSEQ seem to be incomplete and play only 1/2 sec then die. Hoping its just something stupid when I transferred files but cant find the problem.
Details:
[FSEQissue.zip](https://github.com/smeighan/xLights/files/3781909/FSEQissue.zip)

- Tried 2019.61. backed out to 2019.51 with still no luck.
- Seem to be able to edit sequences ok.
- Only one change to add DMX fog signal since last year.
- New PC this year so copied files from old PC.
- First time rendering new material for this year
- Seems to run ok in "output to lights" mode
- new FSEQ file is only 159Kb, old one that is working is 79Mb
- Windows 10/1903 64bit
- Tried FSEQ V1 and V2. No Luck

Help! Thanks!

**Comment by keithsw1111** [comment]
You would be better seeking help on zoom for issues like this. Odds are there are issues in your config.

**Comment by JoeSchulze** [comment]
I’ll look through configurations or hopefully someone can help on zoom. Thx
