### ISSUE TITLE
Bulk edit dimming curves is not changing the actual lights

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1797]
I noticed if I select a few props, right click>bulk edit>dimming curves and change either the brightness of gamma that the values will indeed change for all the props in Xlights but when you render and play the values are not taking effect on the actual lights on the prop but if I go back into 1 single prop and simply scroll down to dimming curves, open it, see the new setting and hit ok, then after a render the prop plays fine,

I went as far back as .56 and the same issue is there

here is a video I made explaining and showing it with a few lights - https://youtu.be/uMMPIBPMS70

**Comment by AzGilrock** [comment]
The video was private so I couldn't watch it.  I assume you are selecting a group of models in the Layout tab to do this.  So do the action and then go into the dimming curve settings for one of those models and see if it changed.  Its got to be failing there if its not working you shouldn't need to try to confirm on real lights to see the problem.

**Comment by bchiaino** [comment]
just changed it from private to unlisted, hit private by mistake


in Xlights it looks like it is working fine, you bulk edit, make the change and it saves but the physical lights on the house are not actually changing, once you edit the curves individually then the lights on the house will change,

**Comment by AzGilrock** [comment]
I'm not home to try my suggestions.  If you save the layout and close xLights and then reopen and its still showing a 2 then it would be impossible its not working.  You're showing the 2 in the settings but it doesn't appear to be latched.  I'm also wondering if you have render cache active.  I'm not sure how the caching would know you changed dimming curves on the model.  I also never see you hit a Render All after making dimming curve changes.

**Comment by bchiaino** [comment]
im game today from work so I just tried the following

doing a bulk edit, render all and play does not change the physical lights but if I close xlights and reopen like you suggest then the lights change to the correct curve value

I have render cache on locked effects only so that may not be part of it

**Comment by AzGilrock** [comment]
Ok good info.
