### ISSUE TITLE
Crashing on During Render

### ISSUE THREAD

**Issue by JEB1234567** [smeighan/xLights#1799]
**Describe the bug**
Debug report is created when trying to "render all" and xLights closes.
[xLights_dbgrpt-18372-20191030T210446.zip](https://github.com/smeighan/xLights/files/3795108/xLights_dbgrpt-18372-20191030T210446.zip)

Issue just started yesterday.

 - OS: Windows 10 Pro
 - xLights version 2019.61   64bit

**Comment by keithsw1111** [comment]
Turn off hardware video decoding.
