### ISSUE TITLE
Add Spacing to Arches

### ISSUE THREAD

**Issue by tbtgspence** [smeighan/xLights#1800]
Need to have the ability to put spacing between multiple arches.  This would allow you to create smaller arches inside larger ones, where they don't touch each other end to end.  Or, if someone just doesn't put there arches all connected.

**Comment by AzGilrock** [comment]
Yeah I thought about it years ago and never did it because its just as easy to place multiple arch models and put them in a group.  But I'll leave this open not sure if someone might want to add it.
