### ISSUE TITLE
Creating a new sequence using a Video crashes .61

### ISSUE THREAD

**Issue by PeteyHall** [smeighan/xLights#1803]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When I create a new sequence under .61 and I add a Video, Xlights crashes.  I've been able to reproduce it every time.

**To Reproduce**
Create a new sequence
Add a video to the timeline
Select video in the timeline and then select Browse to find your video.
Select the video
It crashes

**Expected behavior**
Xlights shouldn't be crashing when adding a video.

**Versions (please complete the following information):**
Xlights .61 64 bit
Windows 10

**Comment by PeteyHall** [comment]
Log package
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3797947/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
Turn off hardware video decoding.
