### ISSUE TITLE
.63 - upload to F48 main 2 ports for same smart receiver "C" port

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1806]
an issue was fixed in .63 to ix the upload of the C smart receiver but now when it uploads C, If there are 2 models sharing that same port, it makes 2 C's so I have

5C
6C
7C
8C
8C

Keith you should have my packaged info from last bug report but if you need again please let me know.
thank you

![Untitled](https://user-images.githubusercontent.com/40632971/68088769-3b66f800-fe30-11e9-8f02-dc02b9e835a1.png)

**Comment by keithsw1111** [comment]
I dont still have your files ... I delete things as soon as I am done with something.

**Comment by keithsw1111** [comment]
What I think you are seeing there is a virtual string which seems necessary as the channels are not contiguous.

**Comment by bchiaino** [comment]
the channels are all in a row, its just not uploading to the 48 that way, its flipping them, ill post a pic too

here are the packaged logs
https://drive.google.com/open?id=1YkEz9Rg9KmK0waN3XQY_-nxHI_OTlnku

**Comment by bchiaino** [comment]
its the bay window first then I have 1 pixel at the end of the window that lights up my door so its all in a row and the channels follow
<img width="920" alt="Untitled" src="https://user-images.githubusercontent.com/40632971/68091620-e804a200-fe4f-11e9-9e68-e033e6ebeb1c.png">

**Comment by keithsw1111** [comment]
Except they are in reversed order? Do you have your chaining correct?

**Comment by bchiaino** [comment]
I have them all in the correct order in xlights, my bay window is pixel 1-142 and the front door is pixel 143 in the line of pixels as it shows in xlights but when I upload to F48 it flips them

**Comment by bchiaino** [comment]
if I manually add/fix the F48 this is how it "should" look
![Screen Shot 2019-11-03 at 4 26 26 PM](https://user-images.githubusercontent.com/40632971/68092205-bc38ea80-fe56-11e9-9aa6-ab2d532219df.png)

**Comment by keithsw1111** [comment]
Can you post all the model properties for both ... or you will have to wait until i can get to a computer i can access dropbox on.

**Comment by bchiaino** [comment]
not 100% sure if this is what you mean but here's 2 screen shots

![Screen Shot 2019-11-03 at 5 42 57 PM](https://user-images.githubusercontent.com/40632971/68093226-6ddd1900-fe61-11e9-8fc3-06ac2729f8fa.png)
![Screen Shot 2019-11-03 at 5 42 37 PM](https://user-images.githubusercontent.com/40632971/68093227-6ddd1900-fe61-11e9-9b82-69f996838665.png)

**Comment by keithsw1111** [comment]
Hmmm ... not sure why it is loading backwards but I can see why it is creating virtual strings. You have checked the checkbox to set the brightness on the 2nd model ... which forces the virtual string creation.

**Comment by keithsw1111** [comment]
Your setting of start channels is a really really really strange way of doing it. You would be infinitely better off setting the second models start channel to follow the first. The way you are doing it is a maintenance nightmare ... not quite as bad as absolute ... but getting close.

**Comment by bchiaino** [comment]
I have just been setting the start channels to follow each other from model to model. Is it the gaps between some that cause the issues? I would love to learn a more efficient way

**Comment by bchiaino** [comment]
and if I uncheck the brightness setting like you said and I also unchecked the "color order" on bay window it uploads the C receiver fine now

**Comment by keithsw1111** [comment]
I have covered efficient ways of setting start channels in several videos. It is not efficient to regurgitate it repeatedly in responses to questions/issues.

**Comment by bchiaino** [comment]
OK COOL, ILL CHECK SOME OF THE LDER VIDEOS OUT, THE SHOW RUNS FINE SO MAYBE WHEN I HAVE TIME ILL REDO CHANNELS

**Comment by keithsw1111** [comment]
I tried your files and I cannot reproduce the problem (at least with visualise controller). Also the logs you included dont include an upload so i cant investigate that either.

**Comment by bchiaino** [comment]
ok, is there a different log I can send for you to help?

by simply checking and unchecking the brightness box in the "Front door" model it will cause the issue and unchecking fixes the issue so for now im just leaving it unchecked

**Comment by keithsw1111** [comment]
I need you to package the logs just AFTER you upload it and it is wrong.

**Comment by bchiaino** [comment]
here you go Keith, I did a failed upload and packaged log files immediately after

https://drive.google.com/file/d/1SBy3uzzydYhWEgx_j1DIxenalh_srCO1/view?usp=sharing

**Comment by keithsw1111** [comment]
From the log
2019-11-04 15:12:35,710 4531570112 log_base [DEBUG]     Index 18 Port 08 SmartRemote 3 Prot 0 Desc 'BAY WINDOW' Uni 4 StartChan 499 Pixels 142 Group 1 Direction Forward ColorOrder RGB Nulls 0 Brightness 100 Gamma 1.0
2019-11-04 15:12:35,710 4531570112 log_base [DEBUG]     Index 19 Port 08 SmartRemote 3 Prot 0 Desc 'FRONT DOOR' Uni 5 StartChan 415 Pixels 1 Group 1 Direction Forward ColorOrder RGB Nulls 0 Brightness 100 Gamma 1.0

p18=7&t18=0&u18=4&s18=499&c18=142&y18=BAY WINDOW&b18=0&n18=0&G18=0&o18=0&d18=0&g18=1&w18=3&
p19=7&t19=0&u19=5&s19=415&c19=1&y19=FRONT DOOR&b19=0&n19=0&G19=0&o19=0&d19=0&g19=1&w19=3&p20=8

xLights seems to be telling the falcon to load Bay Window first and then door. Maybe this is a falcon bug?

**Comment by bchiaino** [comment]
thank you Keith, should I report to David or does he check here also?

**Comment by keithsw1111** [comment]
He wont ... let me test it first before I trouble him.

**Comment by bchiaino** [comment]
sounds good, thanks Keith!

**Comment by bchiaino** [comment]
Keith is this a step in the right direction to make the channels easier for xlights?

![Screen Shot 2019-11-07 at 2 34 33 PM](https://user-images.githubusercontent.com/40632971/68421237-ded74600-016b-11ea-9bc4-790bae704938.png)

**Comment by keithsw1111** [comment]
It is not about making it easier for xLights ... xLights does not care ... it is about making it easier for you when things change in the future.

**Comment by bchiaino** [comment]
gotcha ok, I like this method, ill keep it and see how it all works out

**Comment by bchiaino** [comment]
Keith should I take out unused channels from a universe or it doesn't really matter. For example I have U11 ending at ch237, sho should I go into the setup to universe 11 and change it from 510 to 237?

**Comment by keithsw1111** [comment]
Do not removed unused channels in a universe unless you have a critical and specific reason to do so.

**Comment by keithsw1111** [comment]
I believe i have this fixed
