### ISSUE TITLE
xFade Playback Speed Control 

### ISSUE THREAD

**Issue by psytecaus** [smeighan/xLights#1808]
**Is your feature request related to a problem? Please describe.**
Not at all, just a feature I would love to see in xfade, will increase dynamic feeling of effects when using xFade

**Describe the solution you'd like**
If at all possible, it would love to see xfade include a speed slider for each channel (A/B) , i think this could be as simple as having the slider change the frame timing dynamically, ie: if running 50ms frame timing the slider could be 50ms at centre (50%) and 100ms at 100% and 25ms at 1% which would mean a effect could be 'stretched' in real time. 

**Describe alternatives you've considered**
Alternatively could this change the xlights playback speed in real time? Like the options in the audio menu..

**Additional context**
Context behind this, I love xlights and its effects and mapping, and use xfade for live events, but find it hard to create effects that can replicate the mood, so being able to speed up/ slow down the effect ( or rather the playback of it ) directly from xfade would make this x100000 times easier

**Comment by keithsw1111** [comment]
Yeah ... this is not going to happen. xFade can speed up or slow down as much as it likes ... it doesnt change the input packet speed ... and changing xlights speed would require a re-render. Sorry but this is just not possible.
