### ISSUE TITLE
Crash: Moving a SINGLE model in Sequence Elements window

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#181]
Using OSX 4.0.16
I only had a single model defined in the Sequence Elements window. I had it highlighted and clicked MOVE UP. 
Xlights Crashed

**Comment by AzGilrock** [comment]
I can't get it to crash doing these steps.  Can you repeat it?

**Comment by LightsOnHudson** [comment]
I will try to do it again this morning.

**Comment by LightsOnHudson** [comment]
This morning, I was able to make it crash.

Using 4.0.16 OSX
Start Xlights
Create New Animation Sequence
Use 50ms 
Do not import from LMS, Vixen, etc - click skip
Do not add a timing track, click close - it will add the default empty track
Right Click on Timing track to open the Sequence Elements window. 
With nothing defined in the Models, CLICK MOVE UP. This caused it to crash for me this morning.

I tested also with clicking MOVE DOWN and it crashed as well.
So I may have crashed it that way and it was masked by having a element in there previously?

**Comment by stevegiron** [comment]
Hello, I'm helping sort the issues and determine which issues are still valid. 
As of May-14 we are version 4.0.31. Is this issue still occurring?

**Comment by LightsOnHudson** [comment]
There are steps to make it crash. I'll check later, but it may take a couple of days as I'm traveling on business.

**Comment by LightsOnHudson** [comment]
The steps above still make this crash. Clicking the Move Up or Move down with no models configured causes it to crash.

**Comment by LightsOnHudson** [comment]
Just loaded OSX 4.2.0. The steps above still cause Xlights to crash.

Create a new sequence (animation 20fps)

Right click on sequencer and select Edit Display elements. 

With no models configured inthe list, click on Move Up or Move Down. xlights Crashes.. See screen shots
![screen shot 2015-08-14 at 3 10 43 pm](https://cloud.githubusercontent.com/assets/10136122/9284192/e001575c-4296-11e5-9a4e-a0282ff389f3.png)
![screen shot 2015-08-14 at 3 11 11 pm](https://cloud.githubusercontent.com/assets/10136122/9284193/e0017be2-4296-11e5-806f-85e2867c7870.png)
