### ISSUE TITLE
Issue with effects on Standard Icicle model vs. Icicle Model with alternating nodes

### ISSUE THREAD

**Issue by jimmyzdc** [smeighan/xLights#1810]
When placing the same effect on these two different types of models the outcome is different.  For example:

- Model 1 - Icicle with Drop setting of 7
- Model 2 - Icicle with Drop setting of 1,8,1 and alternating nodes checked (Gilbert Engineering Icicle Prop)
* Note Model 2 has 2 submodels.  1st is "Line" for the top row and 2nd is "Icicles" to highlight only the drops

Create a group for each type model so that more render styles are available.  The group for Model 2 only has the "Icicle" submodel.  Basically the two look exactly the same.  When applying the same effect to each group the results are different for some effects.  I have not tried all effects but the ones I see on the most are Single Strand Effect with a Vertical per model/strand render.  I have also seen the issue on Ripple effect with a Crucifix shape but I'm sure any shape would result with an issue as well.

**Comment by AzGilrock** [comment]
We aren't going to start creating layouts from scratch to try to figure out what all that text is saying.  You need to provide a layout and a sequence with some sample effects to demonstrate this.

**Comment by AzGilrock** [comment]
I'm pretty sure this will end up not resulting in any changes to the program.  I just tested what I believe you were saying and used the Vertical per model/strand render style for an effect and yes it was different.  But then I reordered the sub-model rows and got it to react exactly the same so you're just going to need to configure the sub-model right and/or expect that not all render styles will react exactly the same unless you've created the exact same type of buffer.  Here's how I arranged it for a simple 1,8,1 Icicles sub-model
![image](https://user-images.githubusercontent.com/2024669/68261459-71a5a280-fffd-11e9-91e5-4bb9d2c0caf3.png)

**Comment by jimmyzdc** [comment]
Hi Gil.  Yes, you are on the right path.  I tried so many variations of how to create the sub model buffer I think I might have gotten close to what you have but I think it fixed these single strand effects but messed up others that were working before.  Let me redo the submodels on one of my models to you method and then I will run a full sequence to see if it solves the problem.  I guess the key is trying to understand how your standard icicles are setup with the render buffer but there isn't a way for me to see it.  Here is how I'm submodeling based on your example now.  My icicle model has 300 nodes so that first submodel goes farther than pictured.  Singles Strand with the Vertical per strand render looks the same now between both models.  Ripple looks close but the object almost looks upside down (in the screenshot the standard model is on top / alternating node model on the bottom).  I can easily remedy that by changing Transformation from None to Flip Vertical but just wanted to note it.  Be back shortly with the results of the more in depth test.  Thx

![image](https://user-images.githubusercontent.com/57422701/68267103-1a580000-0006-11ea-914b-43f34f16e163.png)

![image](https://user-images.githubusercontent.com/57422701/68267117-2d6ad000-0006-11ea-8a5e-45b637586000.png)

![image](https://user-images.githubusercontent.com/57422701/68267542-9b63c700-0007-11ea-9f11-e8e611d5cc23.png)

**Comment by jimmyzdc** [comment]
Ok running a whole sequence and all the effects are upside down.  Just doing a "Reverse Nodes" on the Icicle submodel fixed that issue.  Right now the only anomaly I'm seeing is on a Meteor effect.  Even though the direction is set to down.  It starts going down but then reverses and starts going up.

Thank you again this is very close to almost perfect!

![image](https://user-images.githubusercontent.com/57422701/68268521-622d5600-000b-11ea-9f51-e4d854b5163f.png)


![image](https://user-images.githubusercontent.com/57422701/68268494-4629b480-000b-11ea-9987-5f56b1fe4116.png)

I have attached the seq file and layout so you can see the issue.

[Icicle Test.zip](https://github.com/smeighan/xLights/files/3812509/Icicle.Test.zip)

**Comment by keithsw1111** [comment]
They look fine to me ... my bet you forgot to rerender after playing with your submodels/models.

**Comment by jimmyzdc** [comment]
So weird....I know for sure I re-rendered multiple times after every change.  But you are right its not showing that behavior now that I have opened up the sequence again.  Ok I'm going to go through my actual real layout and rebuild all my submodels based on what we have figured out here and then go through a few more sequences.  Appreciate all the very fast help with this!

**Comment by jimmyzdc** [comment]
Just did confirm all my sequences are rendering correctly now.  Is this something that may get fixed to work properly in a later build when someone selects all the icicles in one line on a submodel or uses the SubBuffer option to select only the icicles?  Wondering if I would need to continue to build my submodels this way which can be pretty tedious.

Thanks

**Comment by AzGilrock** [comment]
No it won't change.  If you select them all on one line then you end up with a buffer that is one line high.  We don't force the buffer shape we let you create it.

**Comment by jimmyzdc** [comment]
Makes sense.  Thanks again Gil for taking the time to figure out how to submodel this properly.  I know you guys are always busy especially this time of season.  :)
