### ISSUE TITLE
Matrix does not resize/stretch properly in 3D after changing model properties

### ISSUE THREAD

**Issue by tomhammond** [smeighan/xLights#1811]
**Describe the bug**
When I create a matrix model with 12 strings by 48 nodes/string in 3D mode, it displays properly.  When I change the model to 1 string of 576 nodes by 12 strands, the model displays as a single line in 3D and cannot be stretched vertically.  I have to go into 2D mode, stretch it from there, then go back into 3D mode to continue working.

**To Reproduce**
1. Create new show folder
2. Add Null network with 1728 channels
3. Turn on 3D mode
4. Add matrix model (12 strings, 48 nodes/string)
5. Save layout
6. Change matrix model to 1 string, 576 nodes/string, 12 strands/string
7. Matrix shown as single line
8. BUG: Vertical stretch handle does not reveal extra strands/lines in matrix 
9. WORKAROUND: Switch to 2D mode, stretch corner handles up/down to reveal matrix strands, go back to 3D mode.

**Expected behavior**
I should be able to stretch the vertical handle up & down to stretch the matrix model in 3D mode, but it seems stuck.

**Screenshots**
https://www.loom.com/share/0577912fdd23449cb7bd53fcb4259139

**Versions (please complete the following information):**
Windows 10
xLights 2019.63

Thanks!

**Comment by AzGilrock** [comment]
I would have left it as is Keith.  Anyone creating a one line matrix needs to be slapped not encouraged...lol.

**Comment by tomhammond** [comment]
I did not intentionally create a one-line matrix.  Originally, I made a
matrix with 12 strings of 48 nodes.  But then I discovered that the wiring
view didn't match my physical prop.  So I updated the matrix settings to be
one string of 576 nodes with 12 strands, which uses the correct wiring
view.  That's when the one-line matrix bug appeared in 3D view.

**Comment by AzGilrock** [comment]
Well it sounds so much better the second time...lol

**Comment by AzGilrock** [comment]
I just want to look more into the code fix for this.  It appears to fix the symptom and not the cause.

**Comment by keithsw1111** [comment]
I think it is the cause.

It is a side effect of a couple of things.

1. When model properties change we dont really want to change the overall size of the model ... we just spread things out or compress them (this is incompletely implemented).
2. Once a model goes to 1 high/wide this breaks down ... and the model is resized to be one high/wide.
3. When you then add rows/cols the model cant really scale back up.

This change stops the scale going to zero ... as when that happens the scale cannot be dragged and to be honest a scale of 1 and 0 are much the same.

**Comment by AzGilrock** [comment]
Yeah I didn't read the issue in detail I looked at the code change first and thought he had left it as a single line expecting it to scale.  So then when I saw he had entered strands > 1 I thought it should have fixed itself.
