### ISSUE TITLE
Enhancement - Ability to "reset" Falcon Controllers settings via xLights

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#1812]
It would be nice if there was a way to be able to reset the Universe Settings and String Port Settings on the Falcon controllers directly from xLights.  Essentially an upload or push of the default settings for the controller (not including any network settings), that would override any and all of the setup that was in there.  

The reason for this is due to a combination of factors.
- The falcon controllers have lots of settings for things like virtual strings, smart strings now added, the slider bar, and different color orders, brightnesses, etc.  If the model setup is input into xlights incorrectly, when uploaded it will put things onto ports that might not be intended to be used, or create virtual or smart strings, that weren't intended.
- With the addition of the proxy settings to FPP, it is easier to connect to a falcon controller via the FPP and push the data to the falcon.  However, when using the proxy, all of the web interface settings for the controller are not present, such as the sliders for the max number of channels, or the + and - for adding or removing smart or virtual strings.
- xLights does not overwrite or remove any data which is on the controller that new information is not being set up for.  This is good in most cases, as the may be manual configurations that users don't want overwritten.  However, when the setup came from a incorrect setup in xlights that was pushed, it is sometimes desirable to overwrite this data.  In some cases, such as if too many channels were pushed to a chained smart receiver that was not intended, the maximum number of pixels per port may be violated, and xlights will be unable to push the information to the controller.

Currently, there is no way to fix this via xLights.  The options to redo this is to perform a factory reset on the controller, which requires access to the controller as well as resetting the network settings after it is done.  The other option is to set up a route to the controller, rather than using the proxy settings in FPP, so that the full web interface is usable.  

Since this is a situation that is due to the combination of factors using xlights, FPP, and the falcon controllers, not sure which is the best place to locate this "fix" so I started here.  It may be better as an upgrade to FPP or the controllers.

**Comment by AzGilrock** [comment]
Well you've convinced me to stick with a manual setup again this year...lol.

**Comment by keithsw1111** [comment]
This would need the falcon to provide a way to tell it to reset. I am not keen to build into xLights knowledge about what a default setup looks like for several reasons ... the most important being that it actually would not be a reset which means it does not really reset everything which a reset should do.

**Comment by deplanche** [comment]
Yeah, wouldn't want it to be a full reset.  Just the ability to reset the string outputs more than anything.  It would mainly be for the person who pushed something to a controller before they should have, and now can't push anything else because they have 1000 pixels on Smart String Port 35C for example.  

Probably something that is best fixed either making the proxy interface better or different way to reset on the falcons.  Had to ask though.  Thanks.

**Comment by computergeek1507** [comment]
Full xLights Control fixes covers this issue
