### ISSUE TITLE
Can't upload correct DMX address to F48/16 if above 512

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1813]
My F48 serial port is configured as a DMX out for my wrist bands. I hanged to absolute addressing and the DMX wrist band is now channel 8671 which if I manually add to the F48 port screen it works but if I do an upload from Xlights it changes it back to "1" being I can't enter the correct address in the DMX Channel area of the controller connections which would be 8671

![Screen Shot 2019-11-07 at 5 23 38 PM](https://user-images.githubusercontent.com/40632971/68433215-01755900-0184-11ea-9700-045949340a1f.png)
![Screen Shot 2019-11-07 at 5 24 09 PM](https://user-images.githubusercontent.com/40632971/68433225-0508e000-0184-11ea-83ee-4226ad15a2c4.png)

**Comment by keithsw1111** [comment]
Can you share the log after the upload?

**Comment by bchiaino** [comment]
here's the file Keith

the issue seems to be that we cant add any number higher then 510 in the DMX address controller area

https://drive.google.com/file/d/1WZphp_Ot19El8W9ubHbYz8tLRBoJRnZf/view?usp=sharing

**Comment by keithsw1111** [comment]
Turns out this is because you have it in absolute addressing mode. I have fixed it but i really wish that was never added in.

**Comment by bchiaino** [comment]
I switched the F48 back to universe/start channel and now it uploads to the F48 as 18 ch1 and works. 

Glad its fixed though for people wanting to use absolute.

thanks again as always Keith!
