### ISSUE TITLE
Mac - xLights hanging when switching to sequencer tab

### ISSUE THREAD

**Issue by paulglavin** [smeighan/xLights#1815]
This occurs on with no sequence open on a fresh launch of xLights when using macOS Catalina with Sidecar display enabled.

**To Reproduce**

With Xlights closed, enable sidecar (I'm using an iPad Pro as my external monitor)
Open xLights and click on the sequencer tab. It has to be the first time you've clicked on the tab in this xLights session.
xlights will hang, the cursor will turn to a beachball if you hover over the bar. It will not crash or recover. The only option is to force quit and start again.

**Expected behavior**
I would have expected the sequencer tab to open

**Screenshots**
I've captured a video that I've shared here:
https://chockymonster-my.sharepoint.com/:v:/g/personal/paul_chockymonster_co_uk/ETNHbO4vgetGne-BfybIMXkBHtaW_Oc971Xy6fIbfhqxvA?e=o2tJcb 

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3825705/xLightsProblem.zip)

**Versions (please complete the following information):**
 - OS: MacOS Catalina 10.15.1
 - xLights version 2019.63 - this has happened .58 onwards

**Additional context**

**Attachments**
No crashlog is generated, I've attached the output from tools/package logs.

**Comment by nmiller0113** [comment]
I saw the same, or at least a similar issue, yesterday and it actually crashed for me.  I'm attaching the crash file.
[xLights_dbgrpt-1354-20191107T225417.zip](https://github.com/smeighan/xLights/files/3826142/xLights_dbgrpt-1354-20191107T225417.zip)

**Comment by AzGilrock** [comment]
We should just hide the damn tab when no sequence is open since people can't learn the lesson.

**Comment by paulglavin** [comment]
Gil, the same happens if you have a sequence loaded.
Open xLights with sidecar enabled, File - open sequence, choose the sequence, click on the sequence tab and xLights crashes.
The only way it doesn’t crash is if you enable sidecar after clicking on the sequence tab for the first time in that xLights session.

The video was captured with a blank layout and no sequence just to disprove an issue with the layout or the sequence.

On 11 Nov 2019, at 13:17, Gil Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


We should just hide the damn tab when no sequence is open since people can't learn the lesson.

**Comment by dkulp** [comment]
The main issue at this point is I don't have an iPad that supports Sidecar so it's not something I can attempt to reproduce.  :(     (my iPad has been out-of-support for a couple years now.  It's stuck on iOS 10)

I'll probably ask for a new iPad for Christmas.

**Comment by AzGilrock** [comment]
Well I guess you'll need a MAC fanatic to fix this.  I own a few but never liked the OS so I run Windows on all my MACs...

**Comment by paulglavin** [comment]
I’ve just tested it using airplay to an Apple TV, that crashes in an identical manner.


On 11 Nov 2019, at 14:04, Daniel Kulp <notifications@github.com<mailto:notifications@github.com>> wrote:


The main issue at this point is I don't have an iPad that supports Sidecar so it's not something I can attempt to reproduce. :( (my iPad has been out-of-support for a couple years now. It's stuck on iOS 10)

I'll probably ask for a new iPad for Christmas.

**Comment by nmiller0113** [comment]
> We should just hide the damn tab when no sequence is open since people can't learn the lesson.

Gil, which lesson is that?  I've been using xLights for years and never had this problem, but I'm also not aware of any suggestion not to click that tab when a sequence is not opened.  I also cannot reproduce this again.  It happened only once, unfortunately, but I figured I'd share my crash report since @paulglavin  had something happen as well.  Just trying to help.  I do agree that if clicking that tab when a sequence is not open is a risk of crashing...again, never has happened to me for years...I would agree that hiding it may be a good thing.  Clicking it right now though...no sequence open....no problems :)

**Comment by keithsw1111** [comment]
The crash is in 

4   xLights                             0x00000001037533f0 _ZN12ModelPreview12StartDrawingEdb + 144

I have always attributed this to display subsystem issues. On Windows i would recommend a driver update ... on OSX and using this sidecar thing who knows. Maybe there are OpenGL issues with it.

**Comment by ajmckee** [comment]
MacOS 10.1.15 with iPad acting as a sidecar for house preview. On opening sequence, or clicking on the sequence tab spinner of doom is induced. Force quit, disconnect from sidecar and relaunch fixes the issue and then allows you to sidecar. Workaround is to only enable sidecar after xlights has opened a sequence. No debug or crash report created too.

**Comment by dkulp** [comment]
Just got a new iPad.... and cannot reproduce this with the latest OS updates on both the iPad and Mac.

**Comment by dkulp** [comment]
Cancel that...  can reproduce.  If I use gfxCardStatus to lock to the integrated graphics card, then it works fine.  If it grabs the Radeon, then it locks up.
