### ISSUE TITLE
memory leak in xSchedule

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#1816]
**Describe the bug**
Load xSchedule, start a playlist, load the windows resource monitor and watch the memory be consumed.  If I unload xSchedule the memory comes back.

Memory leak.  Appears more aggressive than last year.

**To Reproduce**
1. Go to ' xSchedule
2. Click on  create a library playlist with a couple of hundred songs, let it play for a couple of days and monitor the memory loss.  The more songs in the list, the faster the memory leak.

**Versions (please complete the following information):**
 - OS: Windows 10 64 bit  i5 chip 8 gig of memory, SSD
 - xLights version 2019.63

**Additional context**
During Halloween I would run the show and then run library of a couple hundred songs.  While I was not monitoring it as closely as I have for the last couple of days, during the all night the system stopped.  Rebooted the computer and started again.
I have been prepping Christmas playlists and schedules and just letting them run, and noticed the computer stopped.  Had to unplug it to bring it back to life.
Upon start up I loaded:
xSchedule, along with Player window for the projector
TaskDaemon
Task manager
Started to run the Christmas library of 700+ songs.  Note these songs are a mix of .wav and MP3.  The library songs are not preloaded into memory.
Log of the resource monitor of memory used
8:49a  2.15g
8:25a 2.55g
9:56 a 5.22g
11:02 7.72g
Exited xSchedule, TaskDaemon restarted
11:07 a 1.60 g
12:00n 3.44g
1:30p 7.71g
2:48p 7.72g
4:21g 7.66g
5:29p 7.62g
show starts at 5:30, I exited xSchedule and TaskDaemon restarted xSchedule running the show
5:31 879 MB
6:15p 1.03g
11:00p 2.08g end of show, back to library
8:34a (next day) 7.70 g  reset

**Comment by JoelDearing** [comment]
Here is the log
[xSchedule_l4cpp 111019log.txt](https://github.com/smeighan/xLights/files/3828660/xSchedule_l4cpp.111019log.txt)

**Comment by keithsw1111** [comment]
That doesnt necessary mean there is a leak ... are you using fast start audio ... monitoring several songs i am not seeing any leak ... or if there is one it seems very slow.

**Comment by JoelDearing** [comment]
For the library playlist I am not using fast start audio.  If you create a playlist with 300+ songs, create a schedule and let it play for a few days non-stop you should see memory usage go up.

**Comment by AzGilrock** [comment]
Asking a developer to create a 300+ song list and let it play for a few days....This issue list is always good for a few laughs.

**Comment by keithsw1111** [comment]
There are a hundred things you could be doing that might impact this and I am left trying to guess what they are. As Gil hints above it is just impractical for me to test that ... I need something more specific. Take out as many variables as you can ... do you still have issues. For example looking in your logs I see lots of FSEQs being opened ... have you really stripped the config down to just one playlist and only audio and only using the default settings with no schedules? How are you playing the playlist. Are you connected to the web interface as well. All of these things create opportunities to be part of the problem ... and essentially you are saying i have  some random configuration about which I will tell you just one thing (which may or may not be significant) ... go spend time working out why i see this behaviour I dont expect. It just doesnt help narrow down if there is a problem and if there is what it is. What types of audio files are they ... all MP3s or are you doing weird stuff with WAV files and MP4s etc. All possible variables i am left guessing about.

**Comment by JoelDearing** [comment]
Gil, thanks for the snark.  You take it to an art form.

**Comment by AzGilrock** [comment]
Geez what I said was nothing...sometimes I think you guys start crying while I'm still typing.

**Comment by JoelDearing** [comment]
Keith,  Thanks for the ideas to better track it down.  I guess using the guide that was set up here didn't give you enough details.  
To address the points you bring up  In the log file I sent you there would be FSEQ files addressed since I am running a schedule with a playlist from 5:30p-9:57p for the light show, then at 10:02p it stops and executes a schedule with the library playlist to run from 10:02p-5::27p the next day. 
As you suggested, I have created a playlist with just the library songs and no schedule, it has been running for the last couple of hours and memory use has been steady between 1.55 and 1.87 gig.  The playlist is the exact same songs in the list as mentioned in the issue above.  The library is an assortment of MP3 and WAV files.  No MP4s. 
In setting up this test I created a folder in the show directory called Music Test, then had xLights and xSchedule point to it.  Further I created, in xLights, one controller to create the xLights_networks file that xSchedule was giving me an error on.

Re: Web interface.  I have never used it.  Not sure if it is set up or not.  

I took it to another step and added a schedule to this library list.  Memory started at 1.24g at 6:15p and moved up to 2.52 gig.  At 7:35p it is at 4.11g.   8:39 it is 7.63g

What next step do you want me to try next?

**Comment by keithsw1111** [comment]
So ... to play it back.

Adding just music and playing it ... no memory leak.
Adding one schedule item to the playlist ... and it leaks. Can I assume you were playing it?

Let me try to replicate creating a music playlist and adding a schedule.

When you had the schedule was it playing and if so how did you start it ... manually or the schedule triggered.

**Comment by keithsw1111** [comment]
I tried it ... no leak.

**Comment by JoelDearing** [comment]
I let the schedule trigger it.  How many songs are in your playlist?  I am finding that running a large list > 500 makes it leak faster.  The Halloween list was ~ 250 songs and it took a couple of days for it to run out of memory.

**Comment by JoelDearing** [comment]
I tried this on another computer.  Win 10 64 bit i7 12g ram.  Copied over the Christmas song folder from the i5.  Set up xSchedule with a playlist only, and there was no memory depletion, stopped the playlist, set up a schedule and at the start it showed 20% memory used at 12n, 12:15p 25%, 1:04 43%, 2:12p 58%.  What else can I do or provide for you?

**Comment by keithsw1111** [comment]
I need the xschedule file to see how you are scheduling it and your options.

**Comment by JoelDearing** [comment]
sent you the files from my Win 7 and Win 10 machine via wetransfer

**Comment by keithsw1111** [comment]
So this is frustrating ... I get the memory consumption growth in the gcc release build ... but not in the visual studio debug build ... that makes it really hard to find the problem. Visual studio is rock solid in its memory use.

**Comment by keithsw1111** [comment]
I have installed Dr-Memory and run xSchedule and as best I can tell the problem is libwinpthread-1.dll leaking when locking mutexes. xSchedule does this a huge amount. Going to need to find a newer version hopefully fixed.

**Comment by JoelDearing** [comment]
Excellent.

**Comment by keithsw1111** [comment]
I believe this is resolved
