### ISSUE TITLE
Controller Connection Still Populated On Model

### ISSUE THREAD

**Issue by nmiller0113** [smeighan/xLights#1817]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Not sure if this is a bug or intentional but after switching back to "Use Start Channel" on my models from actual controller names it is still showing the Controller Connection section populated with controller data.  If I change if back to default with "0" for the port and nothing for the Protocol section, it then is forever showing red as though it's expecting something...when it shouldn't.  I can edit the XML file, but I'd rather not do that.

**To Reproduce**
Described above

**Expected behavior**
Described above

**Versions (please complete the following information):**
 - OS: OSX 10.15.1
 - xLights version 2019.64

**Comment by keithsw1111** [comment]
I cant reproduce an issue where it is inapproprately red ... I am going to need more detailed step by step instructions.

**Comment by nmiller0113** [comment]
Essentially, I used to have the Controller Connection info specified for some of my models where I was using the controller section for the auto start channel setup.  I've since stopped using this as it is no longer needed.  When I switched the Controller section back to "Use Start Channel" and then went to modify my Controller Connection section back to Port = 0 and Protocol = Blank, I get red as it's indicating it's needed...when it is not any longer.  Pics attached.
![Screen Shot 2019-11-11 at 11 27 05 AM](https://user-images.githubusercontent.com/1048868/68615049-1d744580-0477-11ea-91e9-7b991335c3ee.png)
![Screen Shot 2019-11-11 at 11 26 47 AM](https://user-images.githubusercontent.com/1048868/68615050-1d744580-0477-11ea-9867-c560f07064e3.png)
![Screen Shot 2019-11-11 at 11 26 30 AM](https://user-images.githubusercontent.com/1048868/68615052-1d744580-0477-11ea-9c71-1b23fca7a32c.png)

**Comment by nmiller0113** [comment]
Also, here's a picture of a model that was never configured for auto start...it shows up properly without the red since it was never changed originally and then changed back like the models I mentioned before.
![Screen Shot 2019-11-11 at 11 34 45 AM](https://user-images.githubusercontent.com/1048868/68615164-64623b00-0477-11ea-9b85-5a96583f52ca.png)

**Comment by keithsw1111** [comment]
I have tested this six ways to Sunday ... I need simple step by step micro instructions because clearly you are doing something I am not doing because it works every time no matter what order i do things.

**Comment by AzGilrock** [comment]
Its best if you just package log files then either provide a video or exact steps of which model to change and exactly which change to make.

**Comment by nmiller0113** [comment]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3849397/xLightsProblem.zip)

Steps to reproduce:
1. Select the model livwinmat
2. Expand the Controller Connection section
3. Change the configuration for Port to 0
4. Change the Protocol to nothing

Everything will turn red in that section.  If you look at the megatree1 model, it is setup the same way and not red.  The livwinmat model is only red because it used to be setup by controller when I was using the auto start channel setup, which I've since stopped using...hence the reason I'm trying to remove that config from the model.  If you look in the xml file you'll see that it is trying to define that still.
Thanks!

**Comment by keithsw1111** [comment]
I suspect you converted this a while back and are impacted by bugs in the convert to e131 code that was causing issues ... either way I think I have this fixed.

**Comment by nmiller0113** [comment]
@keithsw1111 - thanks for the work, but this wasn't something I changed a long time ago.  Yes, these models have existed for a couple years but I only experimented with the auto channel option in the last few months and decided to go back to the old fashioned way a few weeks ago.  I noticed that your fix corrected the models showing up as red in the controller section but the configuration in the XML hasn't changed.  As an example, looking at my livwinmat model it still shows:

Controller="fppgrnd2" - It shouldn't show this any longer as it's configured in the Controller section to "Use Start Channel".  To confirm this I created a matching matrix and the "Controller=" section didn't even exists in its XML <model> definition.

<ControllerConnection channel="1"/> - this is also still there and in my new test model I created, a matching matrix, it showed it as <ControllerConnection/>

Sorry to be a pain about this, I'm just making sure this doesn't still come back and cause any issues in the future as it seems that xLights didn't properly cleanup when the change was made from auto start channel configurations back to the manual way.  Thanks again for your work!

**Comment by AzGilrock** [comment]
If the option is set back to "Use Start Channel" then those other fields get ignored so its not hurting anything.  Its like when I had Individual start channel fields that were staying in a record even after switching back to not using individuals.  My argument to leave them in was that if you check the box again you'd like it to come back to where you had it instead of it being deleted and you gotta recreate every time.  It also means if you make an accidental change you can switch it back without having to redefine the channel number.

**Comment by nmiller0113** [comment]
Thanks @AzGilrock, that makes perfect sense!
