### ISSUE TITLE
Xlights crashes when doing a Render and Export on model with effects on submodels

### ISSUE THREAD

**Issue by chrkov** [smeighan/xLights#1818]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
On a model with no effects on submodels and "Render and Export" works fine.  But when effects are placed submodels, performing a "Render and Export" will cause application to crash and close.   No ability to send a crash report shows.

**To Reproduce**
1.  Create a new sequence.
2.  On a model with sub models, place effects on the submodels.
3.  Right click on model, select model and Render and Export.
4.  Xlights will crash.

**Expected behavior**
a valid eseq file created.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.64

**Comment by keithsw1111** [comment]
It does not crash as described I did this and exported all the common formats ... no crash.. We need your layout. Which model you are using and what format you are exporting to.

**Comment by chrkov** [comment]
[xlight shows.zip](https://github.com/smeighan/xLights/files/3874682/xlight.shows.zip)
Sorry for the delay, I was out of town for work.

Attached is my layout and the sequence.   I do a render and export on "98 Grinch" or "85 ChromaStocking Matrix" and have the problem.

**Comment by keithsw1111** [comment]
I believe Dan has fixed this for .66

**Comment by chrkov** [comment]
I can confirm this is working fine now on .68.  Thanks!
