### ISSUE TITLE
Enhancement: Ability to name layers

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#182]
Is it possible to name the Layers that are added to models? You may want to describe the layer as ' Roof - Red' 
MegaTree - SPECIAL EFFECTS
MegaTree - SMS Control Text.

By default, can the Layer be named the same as the Model with 'MODEL NAME - L2.. L3...L4... ?

**Comment by AzGilrock** [comment]
We do these kind of enhancements for our Platinum supporters. :)

**Comment by LightsOnHudson** [comment]
:)

**Comment by AzGilrock** [comment]
We've added layer numbers now.  I consulted with Keith and I don't believe we are going to want to support naming the layers.
