### ISSUE TITLE
Crash During Serquence Render

### ISSUE THREAD

**Issue by Cboehm00** [smeighan/xLights#1822]
When trying to render a particular sequence on .65 - Xlights crashes and a debug report is generated.
To reproduce all I have to do is open the sequence and click render all, then a minute or so into the render Xlights Crashes.
Please advise what files you need from me other than the crash report.
[xLights_dbgrpt-9724-20191118T212531.zip](https://github.com/smeighan/xLights/files/3861798/xLights_dbgrpt-9724-20191118T212531.zip)

**Comment by keithsw1111** [comment]
THis will be fixed in .66
