### ISSUE TITLE
Missing APA102 option in protocol dropdown for Falcon F16v3

### ISSUE THREAD

**Issue by thilak** [smeighan/xLights#1823]
The Falcon F16v3 supports APA102, it can be set on the controllers webpage. However the dropdown in xLights is missing this option.

(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Add a falcon controller in setup
2. In the layout pane, select a string and then click on Controller Connection -> Protocol

 - OS: Ubuntu 18.04.3 LTS
 - xLights version 2019.64

Finally, I'm new to xLights and I apologize if I missed something in the settings. Awesome software by the way! Many thanks for creating and maintaining it!

**Comment by computergeek1507** [comment]
added with 1e39017e215466d75236195b9968f9ecc5b1c7ff
