### ISSUE TITLE
V2019.65 64bit - Fail to start.

### ISSUE THREAD

**Issue by Mr-Shaggy** [smeighan/xLights#1824]
**Bug**
Xlights V65 was working perfectly fine for me yesterday, November 20, 2019 but, upon attempting to start it today it stops responding after about two mins. I went ahead and fell back on V64 without an issue. Iv also tried restarting and shutting down my computer with no luck. I was able to retrieve some logs in the process.

**Specs**
OS: Windows 10 V10.0.17763
CPU: I7-8550U
RAM: 16GIG installed , 11.7 available
XLIGHT VER - 2019.65 64bit

[xLights_l4cpp(2019.65).log](https://github.com/smeighan/xLights/files/3875360/xLights_l4cpp.2019.65.log)

**Comment by keithsw1111** [comment]
The log contains nothing of use in this situation.

I need a lot more information about exactly what you were doing when it hung and I need logs at the time it hangs ... and I need to know at what time it did hang so i can find the relevant log entries.

**Comment by ssharpe83713** [comment]
I also tried to use 2019.65 after install.  I'm on OSX 10.13.6.  It was a new install on my machine.  When I answered the initial launch window (email address or no thanks), the spinning wheel of death never goes away and required a Force Quit.  I installed 2019.64, and all is well.

**Comment by keithsw1111** [comment]
Hmmm ... can you run 65 until it freezes. Then run 64 and grab us the logs ... I want to see where it stops in 65.

**Comment by ssharpe83713** [comment]
Happy to assist....can I get a few details since I'm new to xLights.   Do I
leave the spinning wheel alone when 65 freezes and independently launch 64
(they can both be installed at the same time)?  How do I "grab" the logs?

**Comment by AzGilrock** [comment]
No force quit the program after it freezes and then run 2019.64 which will allow you to do a Tools -> Package Log Files and post that zip file here.

**Comment by ssharpe83713** [comment]
Well....I launched .65 with no problem this morning.  Could it be because
.64 is already installed?
