### ISSUE TITLE
Fix color for Mac Dark Mode on the sequencer View pane

### ISSUE THREAD

**Issue by corydorning** [smeighan/xLights#1825]
**Is your feature request related to a problem? Please describe.**
on a mac, the sequencer tab  view pane is grayish-brownish with white text making it hard to read in dark mode

**Describe the solution you'd like**
Should be a slate or variant of black to make the white text legible

**Describe alternatives you've considered**
only alternative is to not use dark mode :/

**Additional context**
Screenshot added
![Screen Shot 2019-11-21 at 11 39 57 AM](https://user-images.githubusercontent.com/35460/69357992-07883100-0c7e-11ea-89cc-7e8962cc8381.png)

**Comment by AzGilrock** [comment]
Have you tried changing the background color for the row headings in the Color Manager?

**Comment by dkulp** [comment]
I believe a Reset Defaults in the color manager will fix this for you.   The colors are saved as part of your show folder setup.

**Comment by corydorning** [comment]
woo-hoo! thanks!
