### ISSUE TITLE
Start channel changes when selecting 2 strings

### ISSUE THREAD

**Issue by Jalskrause** [smeighan/xLights#1826]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When I set my wreath from 1 to 2 strings, the first string shows the start channel (in the model description itself) correctly, but in the model list it shows the start channel of my matrix. It shows correct on both when set to only 1 string, but when I set it to 2 strings it changes.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to 'garage wreath" in the layout tab
2. Click on '# of strings'
3. Scroll down from "1" to '2'

**Expected behavior**
Ok, I am running xlights version 2019.64 on windows 10, I have an issue when changing a model from 1 to 2 strings. When I set my wreath to 2 strings, the first string shows the start channel (in the model description itself) correctly, but in the model list it shows the start channel of my matrix. It shows correct on both when set to only 1 string, but when I set it to 2 strings it changes. The same happens if I change my stars to 2 strings as well. Here are the 2 models that I’m talking about. As you can see, when set to 1 string my wreath shows on the model list as start channel .52:37:1 and on the model itself it shows .52:37:1 (correct). But when changed to 2 strings the wreath shows on the model list as start channel .52:1:1 and on the model itself it shows .52:37:1 (incorrect). Is this a glitch or a bug? When playing a sequence, I have the first and only the first pixel on the "lounge matrix" and "garage wreath" doing what the other model is supposed to be doing, as if they were swapped(if that makes sense)... what’s even more weird is that when if I change it and use the IP address (.53) for my other controller it still does the same thing, it reverts back to .52:1:1.

**Screenshots**
![Xlights issue with 1 string](https://user-images.githubusercontent.com/58057145/69393164-9c4a5900-0c95-11ea-8029-8abb190a38b9.png)
![Xlights issue with 2 strings](https://user-images.githubusercontent.com/58057145/69393165-9c4a5900-0c95-11ea-97c3-f2ae2b6b9137.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.64

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3877691/xLightsProblem.zip)

**Additional context**
Let me know if my images and/or my zip file do not show. If you need a sequence, let me know.

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by deplanche** [comment]
I am not a developer, but this problem is because the total number of nodes you have defined (either 360 nodes with 1 string of lights, or 720 nodes when set for 2 strings of light) is not equal to the sum of the nodes on the layers (120+120+120+76+76+76+32+32+32 = 684).  When these aren't equal, it will give you problems with your channels every time.  If you make them equal, it will work as expected.

**Comment by Jalskrause** [comment]
I am sorry, but that is not the case, I have added another circle and without setting layers or pixel count it will have the same issue. Same with a star, if I change one of my stars from 1 to 2 strings, it does the same thing. It does not allow for specifying node count on each string. Case in point, my mega tree is 32 physical strands but due to controller limitations I had to have 11 strings, 10 with 3 strands and 1 with 2, however in my layout it shows 11 strings of the same size and I do not have any issues there.

Thanks, 

John Krause

**Comment by AzGilrock** [comment]
Actually he was correct cause I tested it.  If you change nodes per string to 342 which is half of 684 then 2 strings works and gives the correct start channel.

![image](https://user-images.githubusercontent.com/2024669/69461799-a5d6ce00-0d34-11ea-8746-7ed186c41ea8.png)

**Comment by Jalskrause** [comment]
Gil, I changed the pixels to 342 like both of you had said and yes that corrected my addressing issue but now the last 18 pixels on my first string do not light up. Picking between the lesser of two evils I’d  rather have two pixels swapped than 18 not work at all￼

Thanks for your help,

John Krause

**Comment by AzGilrock** [comment]
Well its gotta actually be physically wired with the 2nd string at pixel 343.  I think your causing your own headaches here.  Why can't you just tell xLights its one string and then wherever string 2 falls you tell your controller that's where your string starts.  The problem is you decided you wanted the 2nd string to start at universe 41 instead of letting xlights determine where the pixels land and then programming that into your controller.  If you do it your way you probably gotta switch to a custom model.
