### ISSUE TITLE
xschedule 2019.65 blank playlist view

### ISSUE THREAD

**Issue by zachcloutier** [smeighan/xLights#1827]
**Describe the bug**
Xschedule 2019.65 can't modify or create playlists. When you open xschedule and go to create or modify a playlist the window is blank.

**To Reproduce**
Open xschedule and create a playlist or edit an existing playlist.

**Screenshots**

![Screenshot (20)](https://user-images.githubusercontent.com/54337611/69397196-e8ec5f00-0caa-11ea-8f6b-2ea15282709d.png)

**Versions (please complete the following information):**
 - OS: Windows 10 i7-8700k, 64gb RAM, gtx1070 studio driver 441.28
 - xschedule 2019.65

**Additional context**
All other versions work fine and the main view renders correctly as well it is just the playlist tab the renders white as far as I can tell.

**Comment by AzGilrock** [comment]
Yeah if you haven't noticed this has been reported all over Facebook and the forum and Keith is on top of trying to fix the problems.  He warned this version 2019.65 had risks so everyone should go back to 2019.64 if they run into problems and it sounds like using xScheduler is definitely out of the question for 2019.65.

**Comment by bambam05us** [comment]
Thank you for “xScheduler” information! I’ve been searching for an online post, as this just happened to me Thursday night. I have reverted back to 2019.64 and all good for now. Much appreciated to everyone that post these issues!
