### ISSUE TITLE
Color Wash Effect : Defaults to White with no colors selected

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#183]
Using OSX 4.0.16
When I added a color wash effect to a timing mark using my 2x3 Matrix there were no colors defined and the entire matrix lit up in WHITE.

Also - The colors did not dynamically change when selecting them in the Effects setting window. I needed to click on BLUE, and then click UPDATE for the matrix to reflect the change.

If no colors are select, no color should go out to the lights. :)

**Comment by AzGilrock** [comment]
Color updates dynamically take effect now and defaulting to white is done on purpose.  When someone forgets to select a color we still want it to show an effect instead of having users complaining they dropped an effect and nothing happened.
