### ISSUE TITLE
xLights crashes when adding "%D" to the end date on Count down !to date!%fmt

### ISSUE THREAD

**Issue by troyburdett** [smeighan/xLights#1834]
I'm trying to add a custom format Count down with the Text Effect on a 17x35 matrix.
I've set the Count down to !to date!%fmt.
I enter the following into the Text field: /Wed, 25 Dec 2019 00:00:00 MST/ %D
As soon as I enter the 'D', xLights crashes.  I can leave it ending in '/' and nothing will happen, but as soon as I enter the '%' or '%D' it crashes.  The other modes seem to work fine.
Thanks!
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3890140/xLightsProblem.zip)

Update:  Just putting the '%' Symbol in the text line will cause xLights to crash, without having the count down set... simple text.  as soon as the '%' symbol is entered, it crashes...  
Thanks!!

**Comment by keithsw1111** [comment]
I have a nagging feeling this is a side effect of the move to visual studio ... I have had problems with graphicscontexts before and thread synchronisation objects - see commit https://github.com/smeighan/xLights/commit/0b753492e0ab91050beaeefde773e2e3cf7e6e39
I do wonder if they might be related

**Comment by troyburdett** [comment]
Doing all the Countdown through xSchedule.  Closing this issue.
