### ISSUE TITLE
2019.66 dll issue

### ISSUE THREAD

**Issue by Jarradleaver** [smeighan/xLights#1835]
2019.66 Down load last night. on opening received these two errors.

![error report 2](https://user-images.githubusercontent.com/58212561/69619031-e22c6600-1075-11ea-835c-8cc0f2fddf8b.png)
![error report](https://user-images.githubusercontent.com/58212561/69619044-e8224700-1075-11ea-91b5-307f609dd625.png)

rolled back to 2019.64 and redown loaded .66 received the same error trying to open.
no crash report so screen shot the error messages.

thanks

**Comment by keithsw1111** [comment]
Install the C runtime from the xlights download page
