### ISSUE TITLE
Middle-Click Panning on Timeline

### ISSUE THREAD

**Issue by adamcoulombe** [smeighan/xLights#1836]
**Describe the bug**
Middle-click + drag doesn't pan the timeline.  It still works fine on the layout tab.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to timeline tab
2. Middle-click & drag anywhere on the timeline

**Expected behavior**
Middle-click should allow you to pan across the timeline

**Versions (please complete the following information):**
 - OS:  Windows 10
 - xLights version 2019.66

**Additional context**
Unless I'm crazy, I * beleive * this was working on previous releases but does not seem to work in current versions.

I know shift+scroll lets you scroll horizontally across timeline but it is less intuitive.

Middle-click+drag works as expected on the layout tab.

**Comment by AzGilrock** [comment]
I don't remember that ever being a feature.  Might be a decent enhancement request.

**Comment by adamcoulombe** [comment]
Thanks for your reply.  A lot of programs I use make use of middle click for grabbing/panning so perhaps I just got mixed up. 

Indeed though it would be great if it was implemented on sequence tab since its already being done on the layout tab.

If I knew cpp I would contribute, but its unfortunately way out of my wheelhouse.

Thanks to all involved for this amazing open source program. Probably the best open source project I have ever encountered

**Comment by keithsw1111** [comment]
pan ... shift scroll wheel?

**Comment by adamcoulombe** [comment]
@keithsw1111 thanks, yes, that certainly works although it is much less intuitive. I never remember which way its going to scroll. Drag is a much more natural interaction

**Comment by keithsw1111** [comment]
Everyone has an opinion about what is intuitive ... that is not going to turn into 27 ways to do the same thing. like it or lump it there is a way to do it and it is not going to change.
