### ISSUE TITLE
FPP Upload Dialog Display

### ISSUE THREAD

**Issue by JMHaro** [smeighan/xLights#1837]
**Describe the bug**
Very minor bug and no priority on this, but the FPP Upload dialog box cuts the "Cancel" button off at the bottom (and if the line wraps to a second line, the Cancel button is completely hidden).  I probably only saw this, this time since I had about 5 FPP's being updated at the same time.

**To Reproduce**
Select files to be uploaded to 

**Expected behavior**
Cancel button should stay visible at bottom of dialog box.  Probably need to expand the top area for the text field to allow more white space giving the text field space to wrap when needed, and display properly even with a single line of text being displayed.

**Screenshots**
![FPP Upload Dialog-1](https://user-images.githubusercontent.com/3945942/69683522-b65faf00-107a-11ea-9108-515a53920c86.png)
![FPP Upload Dialog-2](https://user-images.githubusercontent.com/3945942/69683535-beb7ea00-107a-11ea-9841-ee906b3d5cda.png)

**Versions (please complete the following information):**
 - Windows 10
 - xLights version 2019.66 64 bit

**Comment by keithsw1111** [comment]
Yeah this is a wxWidgets bug. When they fix it and we take their code it will look awesome again.
