### ISSUE TITLE
Missing Media when uploading via FPP Connect

### ISSUE THREAD

**Issue by lithgowlights** [smeighan/xLights#1838]
Media is selected for master, up until V64 the correct location ( E:\Lithgowlights_Show\music\ ) was shown for all the media files. Now the entire list of media files is blank.

Show directory is E:\Lithgowlights_Show\ and sequences are in E:\Lithgowlights_Show\sequences\ and music is in E:\Lithgowlights_Show\music\  

![2019-11-27](https://user-images.githubusercontent.com/16928091/69711485-4114dc80-1155-11ea-82c2-0586eff06e17.png)

**Comment by computergeek1507** [comment]
I think I fixed this a couple releases ago, please let me know if this still happens
