### ISSUE TITLE
Timing Mark past end of sequence end point did not play

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#184]
Using OSX 4.0.16
Created a blank Animation sequence with a few timing marks
I had a timing mark that went past the end of the default duration of the sequence ( 30 sec)

When I pressed play, the sequence stopped right at 30 seconds, and did not continue to the end of my timining mark that ended at approximately 32.5 seconds.
Should this be the normal behaviour or should timing marks not be able to go past the end of the configured duration of the sequence?

![screen shot 2015-04-08 at 9 02 04 am](https://cloud.githubusercontent.com/assets/10136122/7048109/11c405f6-ddce-11e4-84e3-7da149b755e2.png)

**Comment by AzGilrock** [comment]
That's how I intended it to work.  If you shorten a sequence I also don't automatically truncate effects.  It allows you to leave effects on there but cut the sequence short if you want during playback.

**Comment by LightsOnHudson** [comment]
Ok.... No worries. Closeable :)

**Comment by AzGilrock** [comment]
Ok I can close it but you also have that power.  In fact it helps us if you find old issues that have been fixed that didn't get marked closed.  Sometimes we fix things but aren't sure it fixes the issue and they remain open hoping the user will confirm the fix and close it.

**Comment by LightsOnHudson** [comment]
Yes no worries. I understand I can close things as well. I like to write that it did in fact fix it. And give it some time so the developers can see that update. 

I have the same steps that I use to create items and then test the new functionality on how I would use the software and if things go awry I'll write them down. But, as a few things happen, that was the intention of the feature/function. No worries.

I'm going to enjoy using XL 4 for this year. I want more smart colors in my solution from now on. And use the older LOR AC light controls as well.
