### ISSUE TITLE
Enhancement sequence import mapping

### ISSUE THREAD

**Issue by chrisr19841** [smeighan/xLights#1841]
It would be great when importing a sequence that was not designed on your setup bring up a screen that shows all the models used in that sequance and be able to map them to your models all on that one screen. Instead of the way it currently works were it prompts you one at a time.

**Comment by computergeek1507** [comment]
this feature already exists, 

http://videos.xlights.org/xessentials-s2e20-mapping-sequences_a0689bade.html

https://manual.xlights.org/xlights/chapters/chapter-five-menus/import#importing-an-xlights-sequence

https://www.pixelprodisplays.com/mapping-a-ppd-sequence-into-your-layout/

**Comment by chrisr19841** [comment]
Great thanks totally missed that
