### ISSUE TITLE
HLS import sequence CRASHES WINDOWS

### ISSUE THREAD

**Issue by szaske** [smeighan/xLights#1842]
**Describe the bug**
I'm able to repo this bug as it has happened multiple times with the same import data. Be warned however that when Xlight crashes with this bug it will actually crash Windows. you will need to restart your machine...it's ugly.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Download the bugged data from [here](https://www.dropbox.com/s/phfe7op2b9goo4r/grinch-crash.zip?dl=0). and unzip the file into a folder.
2. Use build 67 of Xlights
3. Create a new music sequence.
4. select grinch.mp3 from zip folder.
5. make the sequence use 25ms timings.
6. Not sure it's important but I always add a 25ms timing track (I think that's what you call it).
7. Not sure it's important but I usually save the file at this point.  The sequence will work fine of course.
8. Now you need to import my data file (included in the zip file), along with the mapping file I use. The data file is called "Grinch 2016.hlsIdata" and is in the zip file. The mapping file is called "2019-full-mapping_v8.xmap" and is also included.
9. After a while xlights will finish the import, and seem to work. I was able to render the sequence and save the results. 
10. Save the sequence.  The problem occurs the next time I attempt to load this saved Xlights sequence. Saving the file seems to finish, so I'll continue with the steps to get to the crash itself.
11. Close Xlights
12. Restart Xlights.
13. Select file -> open and open the sequence you just created. WARNING!!! At this point Xlights and Windows will crash. I've tried waiting for hours and Windows never comes back, so it's not like it's just taking a long time, this actually kills Windows.  You're only recourse will be to reboot your machine.

**Expected behavior**
I expect Xlights should be able to load a file it created...and you know, not kill Windows.

**Versions (please complete the following information):**
 I'm using Windows 10 Pro, latest version.
Xlights 67, also latest.

I've attached all relevant data, including the xLights logs into the Zip file listed above. Let me know if you need any other information.

**Comment by szaske** [comment]
A bit more information.  I have 3 different sequences that all crash Windows when I attempt to load them into Xlights. All imports from previous HLS sequences.  The interesting thing is the sequences seem to play correctly in the Scheduler, I'm just not able to load or edit them after that first import. And as mentioned when I first import them I am able to use the editor, so it appears the XML files are getting corrupted and not the fseq files.

**Comment by keithsw1111** [comment]
Hmmm ... I may have this fixed. Try this build for win 64: https://www.dropbox.com/s/9ou1vxtbjd3zz7f/xLights64_2019_67a.exe?dl=0

**Comment by szaske** [comment]
I wasn't sure what to test, so I tried loading these sequences that
previously would lock windows...and this version was able to load each of
them. Thanks! I'm curious, what was the issue?  -=Steve

**Comment by keithsw1111** [comment]
The issue was the new colour panel shows all the colours in the sequence but because you imported HLS there were thousands of colours and that exhausted windows resources.
