### ISSUE TITLE
Crash on render

### ISSUE THREAD

**Issue by tbtgspence** [smeighan/xLights#1843]
No details other than it crashes when rendering.  I've tried removing anything that I can and cleaning up per the sequence check, but it still crashes.
[xLights_dbgrpt-22156-20191129T022526.zip](https://github.com/smeighan/xLights/files/3904764/xLights_dbgrpt-22156-20191129T022526.zip)

**Comment by keithsw1111** [comment]
This is already fixed in .67 and .66
