### ISSUE TITLE
Xlights not responding on Windows 10

### ISSUE THREAD

**Issue by KevD44** [smeighan/xLights#1846]
My xlights .67 has started in last 2 days not responding. it opens correctly and allows me to open or create a new sequence. But when i hit "output to lights" the bulb does not turn yellow with the arrow pointing up and also when i try to "test lights" is says not responding as well. I then have to force quit the program and open it up and still doing the same thing. My computer is new as of september 17, 2019. I cannot see that it was working fine with .43 and when i updated to newest its not working now. I have tried older versions and the same thing keeps happening

**Comment by keithsw1111** [comment]
I need to see logs
