### ISSUE TITLE
Have FPP Connect Show Last Modified Date Of Files To Upload

### ISSUE THREAD

**Issue by nmiller0113** [smeighan/xLights#1847]
**Is your feature request related to a problem? Please describe** **Describe the solution you'd like**
Not really a problem...more of a convenience request.  It would helpful for FPP Connect to show the Last Modified Date of files so that we could see ones that were recently updated and only upload those.  Right now I'm basing it on memory or just selecting all.  Just a convenience thing.

**Comment by computergeek1507** [comment]
added with cdbd24b5e1304107e8d4caddafaacb61d42479ff
