### ISSUE TITLE
Snowflake effect causing issues with other effects.

### ISSUE THREAD

**Issue by chrkov** [smeighan/xLights#1849]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Snowflake effect causing other effects at the same time to appear in unexpected locations.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
See Video Description

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**
Included video as well as sequence I am seeing this on.

**Versions (please complete the following information):**
 - OS: [Windows 10
 - xLights version :2019.68 (also was seeing it on 2019.65)

[2019-12-03_10-54-14.zip](https://github.com/smeighan/xLights/files/3917768/2019-12-03_10-54-14.zip)

[Idina Menzel, AURORA - Into the Unknown (From Frozen 2Lyric Video) issue.zip](https://github.com/smeighan/xLights/files/3917773/Idina.Menzel.AURORA.-.Into.the.Unknown.From.Frozen.2Lyric.Video.issue.zip)

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
This is not enough information for us to troubleshoot. Please reduce the sequence to just the problematic effect and be specific about model and time.

Based on the description and knowing how things work this is either very poorly described or not a bug.

**Comment by chrkov** [comment]
Attached is a basic animation.   I have the shockwave model on the "83 House" model group (which is all elements on the house itself, nothing in the yard).  I added a snowflake effect to "83 Everything No Real Trees" model group.  You can see the shockwave effect show up on the middle three candy canes (83 ChromaCane 4, 83 ChormaCane 5 and 83 ChromaCane 6) which are not part of the "83 House" group.   But, if I remove the snowflake effect from the "83 House" Group, then the Shockwave looks fine and does not light up the candy canes.

[snowflakes issues.zip](https://github.com/smeighan/xLights/files/3918378/snowflakes.issues.zip)

**Comment by chrkov** [comment]
Here is a more noticeable example using the pinwheel effect on the house.
[snowflakes issues 2.zip](https://github.com/smeighan/xLights/files/3918464/snowflakes.issues.2.zip)

**Comment by keithsw1111** [comment]
I have no idea what you think the problem is. I am sure it is obvious to you as you know all your models but i know nothing of your display and I am not going to spend a week trying to work out hundreds of models.
So i am going to wildly guess you should turn off model blending in sequence settings and it will probably fix your problem.

**Comment by chrkov** [comment]
Keith,

Here is a video breaking it down to just two groups with two effects.   Maybe I am misunderstanding how this is, but I dont believe I saw this behavior in the past.  Let me know what you think when you watch this video.
[2019-12-04_09-58-19.zip](https://github.com/smeighan/xLights/files/3922783/2019-12-04_09-58-19.zip)

**Comment by AzGilrock** [comment]
You need to Package the sequence from the video.  There are a ton of other settings we can't see in the video.

**Comment by keithsw1111** [comment]
Closed due to lack of response.
