### ISSUE TITLE
xSchedule in .67 crash

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#1850]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
xSchedule will just stop, and does not show the usual crash window from days gone by. The notice looks more like a Windows notice.  Also the program does not shut down, it just stops.  It has done it 4-5 times in the last 2 days.

**To Reproduce**
I do not know how to reproduce.  Load xSchedule and let it run ???
It has stopped during the show and during library hours.

**Versions (please complete the following information):**
 - OS: Windows 7 64 bit
 - xLights version 2019.67

**Attachments**
I will send you a wetransfer link
If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

Let me know what else I can do to help with this.

**Comment by keithsw1111** [comment]
I think this was resolved in .69
