### ISSUE TITLE
Polyline - Allow negative value in drop pattern to make droplets go up for props like peace stakes

### ISSUE THREAD

**Issue by vult2000** [smeighan/xLights#1852]
**Describe the solution you'd like**
I would like the polyline model to allow for a negative value in the drop pattern which would cause the drop direction to go up instead of down to better support props such as the Peace Pixel Stakes.

**Describe alternatives you've considered**
Tried rotating the polyline 180 degrees over the x axis but it still does not produce correct results.

**Comment by keithsw1111** [comment]
Hmmm ... dont try it in .70 ... negative numbers cause run away memory allocation and a hang.
