### ISSUE TITLE
Enhancement: Relative file paths for show elements like pictures and videos

### ISSUE THREAD

**Issue by TheMadTexan42** [smeighan/xLights#1857]
It is a common use case to move sequences from one computer to another.  This is done both for sequence sharing between users as well as individuals using multiple computers in their show architecture.

It would simplify the process if there were an option to have xLights look for video and picture files (perhaps others) relative to the show folder rather than storing the full path.  This would abstract away the layout of the filesystem above the show folder level, making portability simpler.

**Comment by computergeek1507** [comment]
If your files are in the show folder or a subdirectory of the show folder xLights will already do this. If it cannot find the file in the original file path xLights will recreate the path relative to the show directory.

**Comment by keithsw1111** [comment]
This already works ... storing references to locations outside the show folder is so staggeringly unlikely to work as to be pointless.
