### ISSUE TITLE
Create groups of pixels acting as one

### ISSUE THREAD

**Issue by jackal2477** [smeighan/xLights#1858]
Allow the ability of grouping multiple pixels together to act as one pixel. 
As an example, imagine a line of 10 'Really Big Lights'. Many people put multiple pixels in each RBL, but would like them to act as a single pixel (so every pixel within the RBL is always the same color). With grouping, you could have a line of 10. With a selection box, you could change the default group of 1 pixel per pixel (would need better naming) to 8 pixels per pixel. Then although xlights would act during rendering as a line of 10, it would actually push out data to 80 pixels, with every 8 doing the exact same thing.
This dropdown selection could be added not just to the 'line' item, but many other models as well.

**Comment by dkulp** [comment]
This is generally done via the group setting in the controller connection settings for the model and then the controller handles it.

**Comment by jackal2477** [comment]
I agree. However some controllers don't allow it. And with the proliferation of DDP, ZCPP, and controller upload, fewer people are configuring their controllers directly.

**Comment by dkulp** [comment]
ZCPP will use the "groups" setting in the controller connection stuff.   It's part of the zcpp protocol spec.  Thus, even with zcpp, the preference is to configure it in the controller connection.

**Comment by computergeek1507** [comment]
![image](https://user-images.githubusercontent.com/2293065/70359315-9e8de500-1849-11ea-802d-aa4a9e455dbf.png)

**Comment by jackal2477** [comment]
Never noticed that before. Thanks.
