### ISSUE TITLE
fpp connect crash when media not found

### ISSUE THREAD

**Issue by cp16net** [smeighan/xLights#1859]
2019.69

**Describe the bug**
Xlights crashes when attempting to upload to ffp and the xml sequence was maybe created on another computer and the file is shared. the xlights show folder is located in a different absolute path. when opening a sequence Xlights typically smartly finds the song in the show folder and uses it. But the fpp connect seems to just use the music file in the xml sequence file. 

Found that this happened on multiple computers and think i found the issue of why now.

**To Reproduce**
1. move the show folder that has a sequence and music file in it to another location folder.
2. open the new show folder with xlights
3. not nessesary i dont think but i made changes to my layout and required to rerender sequence.
4. open fpp connect and attempt to upload sequence with media to fpp
5. crash xlights with no window to share the logs and no messages in logs about anything either

**Workaround**
open the sequence and reset the media file to the right location and resave the sequence or even just edit the xml to the correct location and then attempt to upload via fpp connect.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.69

**Comment by computergeek1507** [comment]
fixed with 881c4802248d75666989414c410a6ba3cfa159bc
