### ISSUE TITLE
Xlights hanging on Mac startup.

### ISSUE THREAD

**Issue by jhparshall** [smeighan/xLights#1860]
New install. First time user. App hangs on Mac after completing dialog on startup asking for email for debugging purposes. Hangs whether email is entered or "No Thanks" is clicked. 100% repeatable.

Xlights 2019.69
OSX 10.14.6
MBP 2015

xLights_l4cpp.log: https://www.dropbox.com/s/81cjwoijbsudcro/xLights_l4cpp.log?dl=0

Thanks.

**Comment by bretterer** [comment]
Same here:

Xlights 2019.69
OSX 10.15.1
MBP Mid 2015

**Comment by nmiller0113** [comment]
Strange, I'm not seeing this at all and I'm running 10.15.1 with the same version of xLights.  Mine is MBP 2018.

**Comment by dkulp** [comment]
I cannot reproduce either.  I tried to wipe out all traces of xLights from preferences and everything and started and it asked for email and it just came up.    However, I did move the email ask to later in the process and shifted some other things around.   Can you folks try the 2019.69b build I just put up and see if that fixes it for them?

**Comment by dkulp** [comment]
If not... I would need new logs.

**Comment by bretterer** [comment]
Looks like that is working for me now.  Thanks!

**Comment by jhparshall** [comment]
I'm good now with 69d. Thanks for the quick turnaround!
