### ISSUE TITLE
p10 not working in sheduler

### ISSUE THREAD

**Issue by aalsterskersthuisje** [smeighan/xLights#1861]
Hi all,
i have a small p10 matrix that i use as a tune to sign. It works perfectly when i play a sequence in xlights. But when i run the same sequence (same fseq file) with sheduler the p10 is not outputting any data.
Pls help :)
Best regards,
Gunther

**Comment by keithsw1111** [comment]
You should jump into the zoom call for this sort of problem. There is no information included here and it is most likely a configuration issue.
