### ISSUE TITLE
.69 xLights Crashing when opening existing sequence files

### ISSUE THREAD

**Issue by RyanKasperCook** [smeighan/xLights#1863]
Running .69, xlights is crashing when attempting to open existing sequence files, not all sequence files, only certain ones.  I have attached 2 bug reports from 2 different sequence files it is happening on.  I have also tried .67 and .68, crashes on those as well.  When I revert back to .64, no crash at all.  Thanks!

[xLights_dbgrpt-3632-20191212T095511.zip](https://github.com/smeighan/xLights/files/3956683/xLights_dbgrpt-3632-20191212T095511.zip)
[xLights_dbgrpt-11136-20191212T095620.zip](https://github.com/smeighan/xLights/files/3956684/xLights_dbgrpt-11136-20191212T095620.zip)

**Comment by keithsw1111** [comment]
We really need to see the sequence ... or will need new logs once .70 comes out ... we have a problem right now where our crash logs are missing key details on some machines and yours is impacted.

**Comment by RyanKasperCook** [comment]
Thanks Keith, I downloaded .70 and got the same results.  I am attaching the .70 bug reports along with sample sequence file that is having the issue.  Thanks much!
[Sequence.zip](https://github.com/smeighan/xLights/files/3961290/Sequence.zip)
[xLights_dbgrpt-10056-20191213T084151.zip](https://github.com/smeighan/xLights/files/3961291/xLights_dbgrpt-10056-20191213T084151.zip)
[xLights_dbgrpt-5264-20191213T084046.zip](https://github.com/smeighan/xLights/files/3961292/xLights_dbgrpt-5264-20191213T084046.zip)

**Comment by keithsw1111** [comment]
Dan fixed this one.
