### ISSUE TITLE
Additional E1.31 channels in FSEQ export

### ISSUE THREAD

**Issue by pauluzs** [smeighan/xLights#1864]
**Describe the bug**
When creating a E1.31 universe with 510 channels in Xlights and playing it from xlights itself 510 channels are received on a esp8266 using this sketch:
https://github.com/forkineye/ESPAsyncE131/blob/master/examples/E131_Test/E131_Test.ino
When playing the xlights created FSEQ file from FPP it suddenly contains 512 channels.
This causes the pixeldata to be wrong after pixel170/channel510 when adding a second universe

**To Reproduce**
1 Open xLights-2019.69-x86_64.AppImage
2 Create a E1.31 universe with 510 channels in setup
3 Create a single line with 170 pixels
4 Choose any effect in sequencer(or use tools>test)
5 Click output to lights (bulb in right top corner)
6 Watch serial output from E131_Test.ino containing 510 channels
7 Export/Save the sequence and play it from FPP
8 Watch serial output from E131_Test.ino  now containing 512 channels

**Expected behavior**
Both xlights and FPP sending out 510 channels

**Versions (please complete the following information):**
 -Linux Ubuntu 18.04
 -xLights-2019.69-x86_64.AppImage

**Additional context**
I'm aware this problem could be caused by the export in xlights or by FPP.
Tried opening the FSEQ File to debug this. Only this is a binary file without cleartext.
So i can't really tell which one (xlights/fpp) contains the part where the 2 extra channels get added.

If it's the latter causing the problem please let me know and close this issue afterwards so i can forward it to FPP.

Thanks in advance, Pauluzs

**Comment by AzGilrock** [comment]
I would think any decent device receiving E1.31 should be able to throw away any extra data.  It should never be taking bytes from a packet meant for universe 1 and stuff it out a universe 2 port.

**Comment by dkulp** [comment]
What does your FPP UDP output page look like?   Is it set to send 512 or 510 channels for the universe?

The FSEQ file has no concept of universes or channel counts per universe or anything like that.   It's just a big block of channels.     The FPP config determines how that block of channels gets mapped onto various outputs.

**Comment by pauluzs** [comment]
Thanks for explaining the FSEQ part , somehow i indeed messes up this setting myself.
Will close this issue
