### ISSUE TITLE
UI becomes mostly unresponsive after editing timing marks

### ISSUE THREAD

**Issue by leelindquist** [smeighan/xLights#1866]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
After editing timing marks, most of the UI becomes unresponsive.
https://www.youtube.com/watch?v=-S16oqEetgs

**To Reproduce**
https://www.youtube.com/watch?v=-S16oqEetgs

**Expected behavior**
I expect to be able to click on things in the UI and for there to be a response.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [Mac OS 10.13.6 (17G65)]
 - xLights version [2019.70]

[Wizards in Winter.zip](https://github.com/smeighan/xLights/files/3962043/Wizards.in.Winter.zip)

**Comment by leelindquist** [comment]
Some more information that might be helpful. It doesn't appear to matter which show folder or sequence I'm working in. It happens with a fresh show folder and new sequence as well.

https://www.youtube.com/watch?v=lBrohbfPZdM

**Comment by computergeek1507** [comment]
If you check surpress render, it stops the laggyness for me. I think xLights is attempting to render something ever time you add a timing mark.

**Comment by leelindquist** [comment]
> If you check surpress render, it stops the laggyness for me. I think xLights is attempting to render something ever time you add a timing mark.

That doesn't seem to have any effect on this issue for me.

https://www.youtube.com/watch?v=bDLMr-bMoZ8

Also, I've attached a process sample, in case that's helpful for anyone to see what thread or call might be stuck.

[Sample of xLights.txt](https://github.com/smeighan/xLights/files/3962282/Sample.of.xLights.txt)

**Comment by dkulp** [comment]
Easiest way to reproduce..... if the mouse is still DOWN from the select when the Delete key is hit, it doesn't release the mouse.

**Comment by dkulp** [comment]
I believe this is now fixed in the 2019.70b I uploaded for the Mac
