### ISSUE TITLE
Crash Opening Sequence

### ISSUE THREAD

**Issue by ssharpe83713** [smeighan/xLights#1867]
Mac OS High Sierra
2019.69e

Created a test sequence with a custom view and saved it.  Closed the sequence.  Program crashed when attempting to open the sequence from the saved directory.
[xLights_dbgrpt-25976-20191213T120823.zip](https://github.com/smeighan/xLights/files/3962330/xLights_dbgrpt-25976-20191213T120823.zip)

**Comment by ssharpe83713** [comment]
Seems to be a consistent bug.  When I create a new sequence, name it the same as an existing sequence (Test.xml), and choose to overwrite it in my sequence folder, the save is uneventful.  However, when I attempt to open it, the program crashes.

**Comment by ssharpe83713** [comment]
Videos showing the sequence overwrite (01-1) and the crash (01-2).
Mac OS High Sierra
2019.70

[Bug Videos.zip](https://github.com/smeighan/xLights/files/3962535/Bug.Videos.zip)

**Comment by ssharpe83713** [comment]
FYI...it works fine in 2019.65

**Comment by dkulp** [comment]
I believe this is now fixed in the 2019.70b I uploaded for the Mac
