### ISSUE TITLE
Word breakdown issue in words that have apostrophes

### ISSUE THREAD

**Issue by Poporacer** [smeighan/xLights#1868]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
If you have a phrase that contains a word with an apostrophe in it such as I'll or you're, the breakdown process does not work correctly. When you breakdown the phrase, the word will will be shown without the apostrophe but if you open up the word edit, it shows the apostrophe. When you try to breakdown the word, it won't break it down. If you manually edit the word and delete the apostrophe and add it back, it will break down the word

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Have a phrase with a word that has an apostrophe in it
2. Breakdown the phrase
3. Breakdown the word

**Expected behavior**
The word should breakdown

**Screenshots**

**Versions (please complete the following information):**
 - Windows 10 
 - xLights version 2019.69

**Additional context**

**Attachments**
See attached video

[WordBreakdown.zip](https://github.com/smeighan/xLights/files/3963295/WordBreakdown.zip)

**Comment by keithsw1111** [comment]
Weird ... so I tested it and it works fine.

I use the ' apostrophe.
Did you use the ` quote?

**Comment by keithsw1111** [comment]
With no update in almost a month can I close this?

**Comment by Poporacer** [comment]
I replied to the email, sorry I didn't respond here. This is what I sent:

Um,  On my keyboard I only have one option? But it might be in the Unicode because I copied the lyrics from a web page and pasted them in the phrases.

I manually typed the phrase and it worked correctly.

**Comment by keithsw1111** [comment]
then i am closing because i think it is ok.
