### ISSUE TITLE
Enhancement request: Allow cut and paste from Excel into Model Start/End Grid

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#187]
When I am building a customized matrix that uses regions of the matrix, I have created an Excel sheet that calculates the start channels. I want to copy the column of data from excel and paste it into the channel grid.
![grid3](https://cloud.githubusercontent.com/assets/8147459/7053307/c1a0e766-ddf9-11e4-8e91-93ba4ee56f2d.JPG)

Hand entering 16 number isn't too bad, but as matrixes get bigger this would be helpful.
![grid4](https://cloud.githubusercontent.com/assets/8147459/7053312/c570b3e4-ddf9-11e4-8df7-2f2e2f9a7071.JPG)

Pat

**Comment by stevegiron** [comment]
Cut and paste are already there. Change the model to custom.
![image](https://cloud.githubusercontent.com/assets/10568498/7055813/7b90a638-ddfb-11e4-837a-74e974ade7d1.png)

**Comment by stevegiron** [comment]
Ok to close per Pat.
