### ISSUE TITLE
XSchedule test mode not shutting lights

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1870]
I tried .69 and .70 to start using xschedule and when I go to Modes/Test mode all my lights come on as they should but when I go to Modes/test mode to turn them off they all remain on until I reboot the F48 and F16 manually OR I run a sequence quick then all lights turn off and play the sequence as it should

**Comment by AzGilrock** [comment]
Not saying there's nothing to fix but whenever this happens to me in xLights I just send all black in test mode and then turn it off.

**Comment by bchiaino** [comment]
Thank you Gil, I have done exactly that as a workaround, set the foreground to 0 to black them out.

**Comment by AzGilrock** [comment]
Also from the Falcon manual:
1.Blank

If this checkbox is selected, this string will be sent a signal to turn off if no data is received after the number of seconds defined on the E1.31 Configuration or E1.31/Artnet Tab (Section 4.2.3.2).  This is useful as some string types will not turn off unless an off signal is received.

**Comment by bchiaino** [comment]
that works too but I have to let David know that the F48 2.55 FW doesn't save the blank boxes when checked, I checked all of them hit save, refreshed and they're all unchecked. On the f16 2.54 FW it works fine

**Comment by bchiaino** [comment]
if "send data when not playing sequence" is on in XSchedule then test mode works fine
