### ISSUE TITLE
Poly Line setting Lights/Node to anything other than 1 and count is off

### ISSUE THREAD

**Issue by sirdevan** [smeighan/xLights#1871]
**Describe the bug**
Adding ANY Poly Line to ANY sequence. The count will be for only nodes, it completely ignores lights/Node. 

**To Reproduce**
1. Goto Layout
2. Create New Poly Line
3. Set nodes to any # (10 for example)
4. Set Lights/Node to 3
5. Observe that Light Count is still only 10 and not 30 as it should be

![polyline](https://user-images.githubusercontent.com/31419848/71032767-a2d4c080-20db-11ea-988e-cd628fdd494f.JPG)

**Expected behavior**
When you set Lights/Node to anything other than 1 it should be a multiplier of the Nodes. If I choose 10 Nodes and 3 Lights/Node I should see 30 lights. Straight Line works as intended, Poly does not.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.63 64bit

**Comment by AzGilrock** [comment]
This parameter says "# Nodes" as seen in the screenshot it's not the number of lights.  And I just checked SingleLine and it also has "Nodes/String" so neither model is intending to show number of lights we really want that number to mean how many controllable nodes we have.
