### ISSUE TITLE
Crash while changing effect properties on submodel

### ISSUE THREAD

**Issue by leelindquist** [smeighan/xLights#1875]
**Describe the bug**
I have seen several crashes tonight when making changes to submodels or changing the direction of bars effect (up, down, left, right, etc) shortly after making changes to submodels.

**To Reproduce**
I haven't narrowed down an exact set of circumstances yet, but it seems to have something to do with making changes to the submodel and then re-rendering or making other changes to an existing effect. It crashed while I was recording a video for another user, but I've tried to reproduce the behavior in the same way and it's hit or miss.

https://youtu.be/HeHwcIGItas?t=164

**Expected behavior**
I would expect it to not crash.

**Versions (please complete the following information):**
 - OS: [Mac 10.13.6 (17G65)]
 - xLights version [2019.70b]

[Think Tank Crash.zip](https://github.com/smeighan/xLights/files/3981941/Think.Tank.Crash.zip)
[xLights_dbgrpt-21678-20191218T220658.zip](https://github.com/smeighan/xLights/files/3981943/xLights_dbgrpt-21678-20191218T220658.zip)
[xLights_dbgrpt-22021-20191218T225355.zip](https://github.com/smeighan/xLights/files/3981944/xLights_dbgrpt-22021-20191218T225355.zip)
[xLights_dbgrpt-22321-20191218T234844.zip](https://github.com/smeighan/xLights/files/3981945/xLights_dbgrpt-22321-20191218T234844.zip)
[xLights_dbgrpt-22413-20191218T235404.zip](https://github.com/smeighan/xLights/files/3981946/xLights_dbgrpt-22413-20191218T235404.zip)

**Comment by leelindquist** [comment]
I played around with it some more, and I am able to reproduce it fairly reliably (maybe 50% of the time) with the sequence attached above and by performing the following steps:

https://www.youtube.com/watch?v=rcjdI9AKbWg

Crash log from that video is attached below

[xLights_dbgrpt-22560-20191219T001700.zip](https://github.com/smeighan/xLights/files/3981987/xLights_dbgrpt-22560-20191219T001700.zip)

**Comment by keithsw1111** [comment]
I am not sure ... tried it a dozen times ... no crash

**Comment by leelindquist** [comment]
Odd. I just tried going back to .70 to eliminate Dan's small change as a possibility, and also opened up the sequence using a new folder from the packaged sequence .zip in case it was some render cache issue in the old show folder. I got a crash the first time I tried it. I'll try it a few times in my Windows VM and see if I can get it to crash there.

**Comment by leelindquist** [comment]
I did the same things in Windows and I can not get it to crash either.

**Comment by dkulp** [comment]
Did you have the Effect Assist window open in Windows when trying to reproduce?   That's where the crash is occurring.    The "mModel"  pointer in there still points to the old, now deleted, model.   Looking into trying to fix.

**Comment by leelindquist** [comment]
> Did you have the Effect Assist window open in Windows when trying to reproduce? That's where the crash is occurring. The "mModel" pointer in there still points to the old, now deleted, model. Looking into trying to fix.

That's strange. I tried it again just now, and when I opened up the sequence the effect assist window was initially visible, but when I clicked on the effect in the time timeline (the same bars effect on the same submodel I'd been messing with) the effect assist window disappeared. No crash, just disappeared. After I re-enabled the effect assist window and tried the same set of changes to submodels, I can now get it to crash in windows as well.

**Comment by dkulp** [comment]
Stuck a .70c up that hopefully fixes this.  Can you give it a try?

**Comment by leelindquist** [comment]
> Stuck a .70c up that hopefully fixes this. Can you give it a try?

So far, so good. I've tried it 4 different times now and it doesn't crash. I can see that it is unselecting the effect in the timeline after making a change in the submodel, so when re-clicking the effect it must now be referencing the correctly updated model. 

Thanks for the quick fix!
