### ISSUE TITLE
Show next scheduled playlist

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1876]
Is it possible to add a place where xschedule will show what schedule will be next like it does in the web interface. Its nice to see that XSchedule is ready to play the scheduled playlist at 17:00 so to speak and that the playlist after that is set in cue for 23:00.. the web interface does this but not the actual xschedule program. thanks!

<img width="759" alt="Screen Shot 2019-12-19 at 8 11 35 AM" src="https://user-images.githubusercontent.com/40632971/71176331-a0877900-2237-11ea-928b-f074b70df5a6.png">
<img width="499" alt="Screen Shot 2019-12-19 at 8 11 52 AM" src="https://user-images.githubusercontent.com/40632971/71176336-a2513c80-2237-11ea-9846-3e38d345f2b6.png">

**Comment by AzGilrock** [comment]
Every playlist is showing when it will play next.
