### ISSUE TITLE
No Audio In Xlights

### ISSUE THREAD

**Issue by Harmerdesignschristmas** [smeighan/xLights#1879]
- xLights version [e.g. 2019.70]

I downloaded newest version of Xlights and now the audio does not play. Even if I start a new sequence no Audio. 

I went back and downloaded the last version I had where everthing worked fine but still no audio.

Not sure what I did or need to do.

Thanks

**Comment by keithsw1111** [comment]
Are you the person we helped in zoom who had muted xLights in the audio mixer controls?

**Comment by Harmerdesignschristmas** [comment]
Yes thank you for the help wasn't sure how to take this down.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
