### ISSUE TITLE
Command line rendering option to specify the location of the xlights RGB/etc/network xmls

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#1880]
To have the ability to specify the folder location on the command line of rendering with xLights where the "show folder" is located. 

When working on multiple displays in separate locations with different configurations, and you want to render each, the ability to specify the working folder for all of the details would be very nice. 

Please and thank you.

**Comment by computergeek1507** [comment]
I confused by what you mean in folder location of the rendering. Render cache? Folder of multiple sequences to render?

**Comment by keithsw1111** [comment]
but you can already do this ... that is was /s does.

**Comment by LightsOnHudson** [comment]
/s on Linux?   When working on different displays with different setups. I would like the ability (and i Use linux) for this to batch render using that client's xml_rgbeffects. etc.

**Comment by cjd** [comment]
It is -s on linux
