### ISSUE TITLE
Creating sequence with audio file containing cyrillic characters crashes xLights

### ISSUE THREAD

**Issue by Cassock** [smeighan/xLights#1881]
**Describe the bug**
Selecting audio file with cyrillic characters crashes xLights
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/3991859/xLights_l4cpp.log)

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Launch xLights
2. Click on New Sequence
3. Select audio file (В ЛЕСУ РОДИЛАСЬ ЕЛОЧКА.mp3 in my case)
4. Select timing (40ms), click Quick Start

**Expected behavior**
Expect a new blank sequence to be ready to modify

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.69

**Additional context**
Renaming the same audio file to English chars lets the sequence creation succeed

**Comment by keithsw1111** [comment]
Do you want to send us an example ... producing a file with crylic characters is not that easy for me.

**Comment by Cassock** [comment]
Should be able to copy/paste the title above. Added a zipped mp3, too, in case that's easier.
[В ЛЕСУ РОДИЛАСЬ ЕЛОЧКА.zip](https://github.com/smeighan/xLights/files/3992082/default.zip)

**Comment by keithsw1111** [comment]
I have fixed the hang ... but the file wont load as we dont support the extended character set. While I can fix that reality is you will only run into issues elsewhere as the code is riddled with assumptions that we are using ascii characters ... best to stick to ascii characters in filenames.
