### ISSUE TITLE
Feature request for Lyric track for use with Servo

### ISSUE THREAD

**Issue by rogerdebolt** [smeighan/xLights#1884]
Was wondering how difficult it would be to be able to leverage Faces and Lyric tracks to control servos? I know that very few use Xlights for Animatronics, but I was thinking that it would be nice to be able to use Faces and Lyric tracks to program moving mouths for my Snowman and Presents. I know that there are quite a few that use it for Halloween displays. I am not a programmer so this may be way too difficult, but thinking if you could set a phenom for one channel and make it adjustable so that you could fine tune it for each phenom. For example have "al" at 128 and "O" at 255 or what ever value that would work with someone's set up. Making that value an adjustable setting. Any consideration would be greatly appreciated! Roger DeBolt

**Comment by keithsw1111** [comment]
Why not just use the state effect?
You would need to move the phonemes to the top layer but other than that there is no reason why you could not do that.

**Comment by rogerdebolt** [comment]
Thanks for the quick reply Keith! I am not 100% that I totally understand that, but I will definitely look into that.

 

Thanks Again,

Roger

**Comment by rogerdebolt** [comment]
Can you point me to a tutorial on the “State Effect”? 

 

Thanks,

Roger

**Comment by patdelaney** [comment]
I'm in the process of writing something  up for the FPP developers to
support the Adafruit 16 channel servo Board

**Comment by keithsw1111** [comment]
http://videos.xlights.org/xlights-state-effect_b2b0c83ed.html

**Comment by rogerdebolt** [comment]
Thanks Keith! I am going to work on it this weekend! I really do appreciate it!

 

Roger

**Comment by AzGilrock** [comment]
I actually had the same idea back when I first got my animated skull.  The thing was just making the mouth move didn't accomplish much since you still want the head to rotate 3 ways and have eye movement.  Also the jaw usually can only go up and down it can't make the shapes like a normal face.

**Comment by rogerdebolt** [comment]
Hi Gil,

 

Thanks for the reply. For me the rest of the movement (Pan, Tilt, Nod and Torso) are easily done in Trackskull and imported. It does not need to be as precise as the jaw. I also agree with the mouth movement, but different amounts of movement make a big difference in the way that it appears, in my opinion anyway. I have not been able to wrap my head around the States effect for this yet, but I am working on that as a solution.

 

Thanks,

Roger

**Comment by AzGilrock** [comment]
Yeah using the State effect for Servos will probably be a pain because in the Servo effect you set a 0 to 100% value and I automatically calculate the servo limits.  Using the state effect you would need to handle the limits yourself and you would need to specify the fine and course channels for each servo independently.  Probably not something I'd want to do manually.  Anyways this is much better video for learning how to control multiple channels at once when you're not driving simple colors:
http://videos.xlights.org/dmx-model-stateeffect_65a050d18.html

**Comment by rogerdebolt** [comment]
Thanks Gil. What you are saying makes sense. I will play around with it and see what I can come up with. 

 

Roger

**Comment by AzGilrock** [comment]
Done
