### ISSUE TITLE
Xlights 2019.72 does not launch with C++ package linked from xlights download page

### ISSUE THREAD

**Issue by franky888git** [smeighan/xLights#1885]
After installing xlights 2019.72 and attempting to launch, an error is displayed and xlights does not launch

The message is:

"The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem."

![xlights_ 72_error](https://user-images.githubusercontent.com/59310497/71543845-eed11080-29cb-11ea-8bf4-a5ccbe1cc28f.png)

At the time of updating I had the following Microsoft Visual C++ Packages currently installed:

Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161
Microsoft Visual C++ 2010 Redistributable - x64 10.0.40219
Microsoft Visual C++ 2010 Redistributable - x86 10.0.40219
Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.30501.0
Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.30501.0
Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.24212.0
Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24212.0

OS: Windows 10 1903 (Build 18362.535)

Versions 64, 70 and 71 work (64 was my 'show' version for 2019).

After installing **Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.24.28127** xlights 2019.72 launches successfully. This appears to be newer than the version linked on the xlights download page.

MS Landing Page containing download links: https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads

**Comment by taftse** [comment]
I had the same issue but updating Microsoft Visual C++ 2015 - 2019 Redistributable (x64) to version 14.24.28127 as suggested above fixed the issue

**Comment by AzGilrock** [comment]
Yep we will update the download page.

**Comment by AzGilrock** [comment]
Download link was fixed.
