### ISSUE TITLE
If a higher priority gracefully" interrupts next schedule, it doesn't allow the lead out to play

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1886]
I have a scheduled playlist set to priority 8 with a lead in to turn on a specific sign and a lead out to turn the sign off, I would love to end this a few seconds early but it seems XSchedule can only start and stop on minutes, not seconds and it carries over a few seconds to a new schedule starting at 17:00, the issue is when the 17:00 is set to go and the lower priority ends, the higher priority kicks right in and doesn't allow the lower priory to play the last step (lead out).  I thought if it was "gracefully" interrupting it would allow the previous to play the last step. its not a big deal being I just put the lead out steps on my first list to the lead in on my 2nd schedule but wanted to report it if it was a bug or intended this way

![Screen Shot 2019-12-28 at 11 41 19 AM](https://user-images.githubusercontent.com/40632971/71546832-2e661100-2968-11ea-97e1-e73b262dfa37.png)

**Comment by AzGilrock** [comment]
A graceful interrupt means it lets the current step finish so if the "lead out" is another step that hasn't started it's not going to play.

**Comment by bchiaino** [comment]
ok cool, i was just used to in a playlist if you hit "gracefully end" it will play the lead out part at least, I thought the scheduled gracefully interrupt would do the same, no big deal, I just put the lead out stuff into my lead in instead for the next scheduled playlist

**Comment by AzGilrock** [comment]
Well I guess its fair to ask if the play last step should always execute.  I didn't write it so I was just guessing based on how it seems to work when I hit the End Gracefully button.  Keith will correct me if I'm wrong.

**Comment by bchiaino** [comment]
yeah, if you it end graceful during a show it always plays the lead out part, but if a higher schedule gracefully interrupts a lower priority schedule then it doesn't play the lead out. 

we have a year to worry about it, lol

**Comment by keithsw1111** [comment]
I think this is working as intended. It is a gracefully interrupt ... so it should not play the lead out.

**Comment by bchiaino** [comment]
Using  priorities that cuts off a lower priority now sets that previous schedule to blue for “next” and also sets the schedule that’s actually set at 23:00 to blue also so the low priority that gets cut off never turns black, always shows as blue. Separate 
 issue I guess.

**Comment by keithsw1111** [comment]
Yeah the multiple blue issue should be fixed.
