### ISSUE TITLE
Tried running version 72. Get a missing dll message. VCRUNTIME_1.dll

### ISSUE THREAD

**Issue by dawalters** [smeighan/xLights#1887]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by AzGilrock** [comment]
Goto the downloads page, click this link and install it
![image](https://user-images.githubusercontent.com/2024669/71553889-044a3880-29d4-11ea-8de6-6c13fc10408e.png)

**Comment by dawalters** [comment]
Will try again.
Running 71 has no issues.

Dean

**Comment by AzGilrock** [comment]
Of course it does.  .72 needs a new DLL so follow my advice or things won't work.

**Comment by dawalters** [comment]
Worked.
