### ISSUE TITLE
Error after install xLights64_2019_72

### ISSUE THREAD

**Issue by RMelhuis** [smeighan/xLights#1888]
After installing xLights64_2019_72, I get 

"System Error

The code execution cannot proceed because
VCRUNTIME140_1.dll was not found. Reinstalling the
program may fix this problem."

I tried 3 times to reinstall same result. rolled back to version 71. I was working, then tried install again with the same Error. Had to go back to version 71.

Thanks,
Richard

**Comment by AzGilrock** [comment]
This has been talked about in every xLights forum and on Facebook.  Get out of the cave and come join us to keep us with what's happening.  Goto the downloads page, click this link, install it.

![image](https://user-images.githubusercontent.com/2024669/71557926-848b9080-2a0a-11ea-916a-6095a7852744.png)
