### ISSUE TITLE
Add seconds also to start time in Xschedule?

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1889]
Is it possible to add in a future release the ability to add seconds to "on time"? I have a pre show I was to end a few seconds before 17:00 so I would love to start it at like 16:44:50 so to speak but right now everything is set for only hours and minutes. thanks!
<img width="543" alt="Screen Shot 2019-12-29 at 2 24 12 PM" src="https://user-images.githubusercontent.com/40632971/71561628-e538be80-2a46-11ea-9d41-b8d1ec59e3b7.png">

**Comment by keithsw1111** [comment]
This is entirely unnecessary and undesirable. Learn to use priorities which can achieve what you are after.

**Comment by bchiaino** [comment]
Using priorities that cuts off a lower priority now sets that previous schedule to blue for next and the schedule that’s actually set at 23:00 for next
