### ISSUE TITLE
Effect Settings Update (F5) 

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#189]
The carry over 3.x Update (F5) doesn't work with by pressing  F5 with 4.x
Clicking the button works, but pressing F5 doesn't update the effect.

**Comment by JonB256** [comment]
I've noticed that too (but didn't report it).

**Comment by AzGilrock** [comment]
Yeah but the idea is ultimately you should never need to update the effect.  It should always be updated...we just haven't got all the kinks out yet.

**Comment by stevegiron** [comment]
So Gil, you're saying 4.x is "kinky" ?

**Comment by stevegiron** [comment]
No longer observed as an issue. Closing .
