### ISSUE TITLE
can't open after update

### ISSUE THREAD

**Issue by dmoney12** [smeighan/xLights#1890]
Just updated to 2019.72 and no longer can open the program. I get a system Error:
"The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem"

I reinstalled and still get the errir

**Comment by Trommelslager** [comment]
Same issue, same error, same troubleshooting, and same result on Windows 10 64 bit.   Uninstalled 2019.72 and downloaded 2019.68 (known to work on my machine) to get running again.

BTW  Thank you devs & betas for all of your hard work and dedication!  Happy New Year!!!

**Comment by AzGilrock** [comment]
Look at the last 2 issues I closed.
