### ISSUE TITLE
Multiple schedules marked "blue" as next

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1891]
I notice when my main show is playing that the previous show that ended is still marked as blue for next even though there is another show after the one playing. then then main show finishes at 22:00 and goes to my "showtimes" schedule at 22:00 and now the last 2 shows are marked blue as next so its not resetting back to black after played. Right now I have 2 schedules marked blue while a 3rd plays as you can see in the pic

here's my xschedule file - https://drive.google.com/file/d/1U44hhKLjiwZm2GehVC5vCASK3JWQyFpF/view?usp=sharing

![IMG_3055](https://user-images.githubusercontent.com/40632971/71567426-f1476f00-2a8c-11ea-8c3e-58d74e6af92f.JPG)

**Comment by bchiaino** [comment]
"showtimes twinkle" is over and now all 3 are makes blue as you can see BUT if I close xschedule and reopen it then "15 min pre show" is the only one blue as it should be 
![IMG_3056](https://user-images.githubusercontent.com/40632971/71567750-6320b800-2a8f-11ea-8862-daaf8b14c2b3.JPG)

after restart of Xschedule
![IMG_3057](https://user-images.githubusercontent.com/40632971/71567759-6caa2000-2a8f-11ea-8f7a-b3a78c1a3035.JPG)

**Comment by keithsw1111** [comment]
I think i have this fixed for .73
