### ISSUE TITLE
Bug: layout tab not working

### ISSUE THREAD

**Issue by GraysonLough** [smeighan/xLights#1893]
**BUG**
Layout tab does not work.

**To Reproduce**
go to layout tab.  nothing happens.

**Expected behavior**
layout tab to work.

**Screenshots**

[xlights error](https://user-images.githubusercontent.com/19726689/71632600-d4b64e80-2bd4-11ea-8f3f-0070204df9b2.png)

**Versions (please complete the following information):**
 - OS: Win 10 x64
 - xLights version 2019.74

**Additional context**
none.
[2020.zip](https://github.com/smeighan/xLights/files/4013390/2020.zip)

**Attachments**
networks and rgbeffects files.
[2020.zip](https://github.com/smeighan/xLights/files/4013390/2020.zip)

**Comment by AzGilrock** [comment]
I see your layout just fine.  Usually this means you need to update to the latest video drivers.
![image](https://user-images.githubusercontent.com/2024669/71636234-89a73600-2bea-11ea-81d9-fe5fc0f33ee8.png)

**Comment by GraysonLough** [comment]
Installed GeForce 441.66(latest), issue still persists.

**Comment by GraysonLough** [comment]
I changed openGL settings to 3.x and this fixed it.

**Comment by AzGilrock** [comment]
Only other suggestion is drop down the OpenGL version. 
![image](https://user-images.githubusercontent.com/2024669/71636675-a5153f80-2bf0-11ea-8189-af0b8201eb7e.png)

**Comment by AzGilrock** [comment]
Ok so what was it on before that "Auto Detect"?  It should have been picking 3.x anyways so Dan might want to see the log unless you had it on 1.x/2.x.

**Comment by GraysonLough** [comment]
it was on auto detect yes.
