### ISSUE TITLE
3D MESH Scaling is broken

### ISSUE THREAD

**Issue by jasonhurd** [smeighan/xLights#1896]
**Describe the bug**
Changing the scale values for a 3D Mesh no longer works

**To Reproduce**
1. Go to Layout Tab
2. Switch to 3D view
3. Add an OBJ file, Mesh.
4. Navigate to the scale parameters under size/location.
5. Changes values for ScaleX, ScaleY, ScaleZ
6. Bounding box resizes but model does not.

**Expected behavior**
The model to adjusted it's size with the bounding box

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: 2019.74

**Comment by keithsw1111** [comment]
Yeah this is known and fixed for the next release.

**Comment by jasonhurd** [comment]
Cheers!
