### ISSUE TITLE
3D Object - Picture rotation not working

### ISSUE THREAD

**Issue by Cranzy-AU** [smeighan/xLights#1897]
**Describe the bug**
When adding an Image in 3D, then rotating it. Save and Exit. When opening it is not rotated

**To Reproduce**
1. Go to Layout Tab, select 3D checkbox
2. Add Image
3. rotate image so the RotateX is -90  (i couldn't type this in so I hadto  rotate it on screen as close to -90 as I could get it.
4. now also rotate the image so RotateX is 90   (again, you can't just type this in, it just doesn't rotate on the view.
5. Save the Layout.
6. Restart xLights

You will see the RotateX and RotateY will still be set to what it was when you saved, but the image is back to how it was when you added it.

**Expected behavior**
Expect it to be rotated as I left it.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.74

**Additional context**

**Comment by AzGilrock** [comment]
I'm not finding any issue typing in the numbers.  There was an issue with the view not refreshing after making changes to parameter fields for 3D objects but that is fixed in 2020.01.
