### ISSUE TITLE
.obj flips 180 degrees on z axis, ignores locked checkbox

### ISSUE THREAD

**Issue by fearfair** [smeighan/xLights#1898]
On layout tab the background image (.obj) will randomly flip 180 degrees on the z axis when performing other actions such as adding or changing a model, etc. this happens whether the locked checkbox is selected or not. 

**To Reproduce**
Attempt editing layout in 3D mode. 

**Versions (please complete the following information):**
 - OS: Mac Catalina
 - xLights version e.g. 2019.74

**Comment by fearfair** [comment]
Just confirmed still occurring with 2020.1

**Comment by AzGilrock** [comment]
I cannot confirm this so you need to show a video and probably Package Log Files and post the zip.

**Comment by AzGilrock** [comment]
I'm assuming you were the one on Facebook.  Since you now said its the mesh flipping I already fixed that so it will be in next release.
