### ISSUE TITLE
fseq Save Directory doesn't save to location specified.

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#190]
I am on version 4.0.1.6  I saved animation sequence, but the fseq saved in the show directory not the fseq Save Directory.

There are the settings, 

![show_dir](https://cloud.githubusercontent.com/assets/8147459/7053712/c2e3d09a-ddfc-11e4-9a11-78fe7d084ae9.JPG)

Pat

**Comment by LightsOnHudson** [comment]
Using OSX 4.0.18 

I opened a sequence 
I changed the FSEQ save directory to something else
I clicked on SAVE in the sequencer, and it saved to the previous Show directory location still.

**Comment by dkulp** [comment]
Gil removed this setting as it was never used
