### ISSUE TITLE
OSX Download

### ISSUE THREAD

**Issue by Derek9309** [smeighan/xLights#1900]
Hi guys, I am new to Xlights, been following it for a couple years and finally decided to download the application.  I am using a MacBook Pro running the Yosemite operating system.  I tried to download the latest version (2020.01) of Xlights and when I try to open it, the splash screen appears then I get the spinning color circle continuously....  The program never opens.  I have tried several times trying version 2020.01 and version 2019.74.  Please help!!

**Comment by bchiaino** [comment]
I'm going to go with your OS is too old at this point and no longer supported

**Comment by Derek9309** [comment]
Thank you sir.  I upgraded to Catalina and tried again and it seems to work fine now!

Derek Anderson
(254) 541-0481

Sent from my iPhone

On Jan 4, 2020, at 10:24 AM, bchiaino <notifications@github.com> wrote:

﻿

I'm going to go with your OS is too old at this point and no longer supported
