### ISSUE TITLE
3D Object - Picture rotation not working -Axis

### ISSUE THREAD

**Issue by Cranzy-AU** [smeighan/xLights#1901]
**Describe the bug**
When adding an Image in 3D, then rotating it. Save and Exit. When opening it is not rotated

**To Reproduce**
Here is a video
[https://nextcloud.iheartmymac.com/index.php/s/e5o6qpm5AeLxMrR](url)

**Comment by AzGilrock** [comment]
Thanks...dammit the same thing happened with the model class.  There was a hidden line of code changing the positioning version from 4 back to 3.
