### ISSUE TITLE
Circle model doesn't allow for center-out wiring

### ISSUE THREAD

**Issue by samstreak** [smeighan/xLights#1905]
My concentric ring set of WS2812's is hard-wired up starting at the center ring (1 single dot) not at the outer ring. To get the circle model in xLignts to work properly, the bounding box becomes much larger than the model itself so is a bit wonky to work with.

**To Reproduce**
1. Create circle model
2. \# of Strings: 1, Nodes per string: 61 (LEDs are in 5 concentric circles - 1+8+12+16+24=61)
3. Center %: 1 (can't put 0, but not the problem here)
4. Layer Sizes:  1, 8, 12, 16, 24  (documentation says to start with the outer ring first, but again, my rings aren't wired that way, and there is no way to reverse the pixel order in the circle model)
5. Starting Location Top Inner-CW
6. The model becomes VERY small and to get it to a usable size by stretching it out (clicking the orange center box of the model until the red/blue/green arrow heads become boxes then dragging the green box while holding CTRL), the bounding box becomes 20-times the size of the actual model

**Expected behavior**
Bounding box stays the same size as the model the same as if it were wired from outer ring to inner ring, and the model staying the same size when changing to this order.

**Screenshots**
![image](https://user-images.githubusercontent.com/28259708/71790021-32df9900-2ffc-11ea-8d8d-e17bc123019a.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: 2020.1 64-bit - Jan 3, 2020

**Comment by samstreak** [comment]
when skipping the 1 as the first value in the Layer Sizes, the model / bounding box stays close to normal size, but then the number of pixels would need to be adjusted to 60 or else the 61st pixel would wrap around to the first (center pixel)... but then the physical pixel layout doesn't match the on-screen one.

**Comment by AzGilrock** [comment]
Fixed for next release.

**Comment by AzGilrock** [comment]
![image](https://user-images.githubusercontent.com/2024669/71793536-7a652580-2ffa-11ea-9a30-d863e2fc9697.png)

**Comment by samstreak** [comment]
Awesome, thanks!
