### ISSUE TITLE
xLights Docker Compilation Terminated

### ISSUE THREAD

**Issue by waintech** [smeighan/xLights#1906]
Ran "docker build -t xlights-build https://github.com/cjd/xlights-build-docker.git" with no issues.

Ran into issues running "docker run --name buildvm xlights-build /bin/bash Recipe"

error:
g++: error: models/DmxModel.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
make[1]: *** [.objs_lr/models/DmxModel.o] Error 1
xLights.cbp.mak:1572: recipe for target '.objs_lr/models/DmxModel.o' failed
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/xLights/xlights-git/xLights'
make: *** [xLights] Error 2
Makefile:28: recipe for target 'xLights' failed

-OS Raspbian Buster Lite running Docker

**Comment by AzGilrock** [comment]
That Linux makefile update always lags the main code base.  The DmxModel filename moved to a subfolder along with a bunch of other new files.  You could fix it for us since your a Linux guy.

**Comment by waintech** [comment]
Sorry to disappoint, but I'm not a Linux guy. I (semi) know my way around linux and would call myself a hoppyist in it, but wouldn't know where to start to fix this. I tinker with Linux to learn it more.  I've given thought to just putting this on my Windows machine, but I just started working with Docker so I really wanted to get it running in there if I could.  Any other details to get me in the right direction of what would actually need to be done to "fix" it?

**Comment by AzGilrock** [comment]
I've actually never heard of Docker but I assume its building on Linux because all the other builds work.  I forget how its done but the xLights.cbp file contains all the file info and there was some way it gets converted to the xLights.cbp.mak file.  Chris usually does that updating for us.

**Comment by waintech** [comment]
Got it, Ok I think I see the issue you're referring to, but not sure how to fix it yet. the file that failed for me "models/DmxModel.cpp" is now located at "models/DMX/DmxModel.cpp". So I need to figure out how to change that in the compilation coding I guess. Will hack away at it until someone else can come along to offer more guidance. I'm sure there's other files that have moved now too so, this should be fun.

**Comment by AzGilrock** [comment]
Well it looks like Chris had updated the file on Jan 3rd so it shouldn't be too far out of date.  Yes basically the path for that file needs to change as well as a few more entries added for the other additional .cpp files I added to the DMX subdirectory.

**Comment by AzGilrock** [comment]
There is a README.linux file at the top level.  It says this is the command to do the conversion:
cbp2make -in xLights.cbp -cfg ../cbp2make.cfg -out xLights.cbp.mak --with-deps --keep-outdir --keep-objdir

**Comment by waintech** [comment]
I did see that but didn't have cbp2make installed to run, so I stopped incase that wasn't what I actually needed to do.  Wanted to post here first to get some guidance. Do you know what all was added so I can put it in the update file when I try to look into it later this week?

**Comment by AzGilrock** [comment]
You can navigate the code directories right here on GitHub.  In xLights / xLights / models / DMX there is now:
DmxColorAbility.cpp
DmxFloodlight.cpp
DmxModel.cpp
DmxMovingHead.cpp
DmxMovingHead3D.cpp
DmxPanTiltAbility.cpp
DmxSkulltronix.cpp

**Comment by cjd** [comment]
The docker image includes cbp2make built in - so it will automatically rebuild the makefiles if needed.
But the binary is only for 64-bit x86 systems - so if you were trying to build under a 32-bit kernel it would fail.
What are you building on?
Can you provide the complete output from the attempt?
I just gave it a re-test and it compiled okay. I've updated the makefile now just in case that was failing for you.

**Comment by waintech** [comment]
> The docker image includes cbp2make built in - so it will automatically rebuild the makefiles if needed

I am building in docker on a Raspberry Pi. The complete output is massive, I wouldn't want to put all of that in here. Mine is failing when it tries to grab the DmxModel.cpp because it's searching for it in /models, but according to the code that is now located in /models/DMX. I honestly am not too sure where to go at this point because if I try to run the inital code that started all of this again (docker run --name buildvm xlights-build /bin/bash Recipe) it errors because that image is already in docker now. So do I need to just recompile the image now with cbp2make or delete the image and start it over again? It took hours to do initially. When I tried to run the cbp2make it tells me that's not a valid command (assuming because it's not installed on my Pi).

**Comment by dkulp** [comment]
Raspberry Pi is 32bit.   I wouldn't bother pursuing this as we're completely phasing out all the 32bit stuff.   It wouldn't surprise me if shortly a ton of things will start crashing with a 32bit build as we're not going to test that setup anymore.

**Comment by waintech** [comment]
> Raspberry Pi is 32bit. I wouldn't bother pursuing this as we're completely phasing out all the 32bit stuff. It wouldn't surprise me if shortly a ton of things will start crashing with a 32bit build as we're not going to test that setup anymore.

10-4, made my decision for me, thanks. I'll move to using my Windows PC. Was strictly doing it on Docker and RPi just to tinker and learn with it.
