### ISSUE TITLE
Cannot rotate model in 2D

### ISSUE THREAD

**Issue by pstube731** [smeighan/xLights#1908]
I cannot rotate a model in 2D by clicking the blue square at the top of the model in the layout and trying to rotate it. If I manually put a +/- number in rotation, it WILL rotate.
Running 2020.1C on Mac. I downgraded to 2019.71 and was able to rotate, so I'm not sure the exact release where it broke.
(I mention 2D because I am successful when rotating in 3D)

**Comment by AzGilrock** [comment]
Fixed 2 days ago gotta wait till a release is done.

**Comment by dkulp** [comment]
Mac 2020.1d is up with the fix
