### ISSUE TITLE
Actions on Layout Tab cause crash

### ISSUE THREAD

**Issue by leighfiddes** [smeighan/xLights#1909]
**Describe the bug**
Loading an existing sequence using 2020.1 or 2020.2 and any actions in the Layout Tab cause a crash.

**To Reproduce**
1. Open xLights with existing sequence or change to an existing sequence.
2. Change to the Layout Tab.
3. Perform an action, e.g. select background image.
4. Crash occurs

**Expected behavior**
Not crashing. Note all versions prior to 2020.1 work fine with the same sequences.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Linux Kubuntu 18.04 LTS (latest up to date)
 - xLights version 2020.1 and 2020.2
[xLights_dbgrpt-13211-20200112T100505.zip](https://github.com/smeighan/xLights/files/4050057/xLights_dbgrpt-13211-20200112T100505.zip)

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by AzGilrock** [comment]
Not crashing on Windows.  Maybe Chris D. can try it out on Linux.

**Comment by leighfiddes** [comment]
Included in #1933 to be resolved.
