### ISSUE TITLE
in sequencer single strand lights will only show up in model windows if they are red. white,green blue will not show.

### ISSUE THREAD

**Issue by tombmatt** [smeighan/xLights#191]

**Comment by stevegiron** [comment]
Hello, I'm helping sort the issues and determine which issues are still valid. 
As of May-14 we are version 4.0.31. Is this issue still occuring?

**Comment by tombmatt** [comment]
Yes. Single strand lights only show up if set to red any other color and you can’t see string. Also when set speed or any other control for single string lights there is no change in preview

**Comment by dkulp** [comment]
What "color" is the first color on the color palette of any effects you are using on the single strand effects.   Make sure it is appropriate for the type of string you are using (or just use White as that has Red, Green, and Blue channels)

**Comment by tombmatt** [comment]
Red. The string is ican

**Comment by dkulp** [comment]
Working as designed.   A red effect on a blue strand should not light.

**Comment by tombmatt** [comment]
Never said red effect not working on blue light said white light as set in preview does not show up on sequencing screen. It does show now but can not control it. Set bars and can not affect the output

**Comment by drlucas** [comment]
Hello,
I'd  like  to show you a nice gift a  frien of  mine gave  me recently, it's something really cool)) Please  take  a  look <http://maria.alyssasuede.com/e7rhk/40>

Pardon my monkey thumbs, drlucas
