### ISSUE TITLE
"Named" Start Channels

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#1910]
## Is your feature request related to a problem? 
Would like to be able to use "Named" output settings in "Start Channel" instead of Universe Syntax. It seems this can only be used if you use tick "Use Auto Start Channels", which assume you want to upload your configuration to a controler.  Some Controlers do not support uploads. (Which ones do is not clear and also what firmware they need to be, is there a page with the details)

## Describe the solution you'd like
![image](https://user-images.githubusercontent.com/9368124/72232573-01775680-3616-11ea-9e07-7fc24cec3d2d.png)

I also find use of "port" confusing under "Controler" Section of a model, I think of it as network port, is there more words or different name could be used.

May be "Use Auto Start Channels" should be a drop down. With option of Fixed, Auto

## Describe alternatives you've considered
Another option is to "Add Controlers" then Add "Outputs", where Outputs have the settings for WS2811 etc, instead of placing them under the model definition.  You should be able to use Multicast yet still define the target controler to up load the configs. 
E.g.
```
<Controler Name>
* ReadOnly Tick Box <xlights never update configs on controler>
* Text Description
* IP/DNS Name/Discover Method
* Protocol:  E1.31|Null|LOR|DDP|ZCPP
* Upload Seq File Tick Box,  e.g. For P10 Pannel, you could send live output, but for the show use the Seq File. (It would be nice if FFP Support Bridge Mode and Remote at the same time)
* Output N/Label
**<TYPE>  e.g. 1CH, 2CH, 3CH, 4CH, DMX, RGB, RGBW, WS2811 etc
**<Number Of> 
etc
```
RGBW could help xlights,  i.e. Xlights could convert RGB to W when required.

## Additional context
Seem image above.

# Thanks
For all the teams hard work

**Comment by computergeek1507** [comment]
This feature already exists, click the ellipse button the the start channel box to open the start channel dialog. Then the last option allows you to select the controller name.

**Comment by damon-atkins** [comment]
![image](https://user-images.githubusercontent.com/9368124/72233627-93825d80-361c-11ea-8aee-aaf64d8c4b65.png)

Thats a bit confusing. Its not where you look, because now there is a line for it. Maybe it should open the same dialog box, instead of being a drop down.

**Comment by AzGilrock** [comment]
Its easy as is I vote no change.

**Comment by computergeek1507** [comment]
There are currently two methods to define start channels in xLights. The original "Use Start Channel" method, where the user defines the start channels and "Auto Start Channel" where xLights figures it all out and you the user just setup the controller outputs. Use "Auto Start Channel" is intended to be the "easy mode" and that why, when enabled, it appears in the main settings grid. In the future we are hoping to change xLights so "Auto Start Channel" is the default option and the "Use Start Channel" is "advance users" only.
