### ISSUE TITLE
Highlight models on the same controller.

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#1913]
**Is your feature request related to a problem? Please describe.**
With the move away from universe/start channel and to more controller and port based numbers, it would be convenient to be able to highlight all of the models that are connected to the same controller on the layout tab.  This would be useful in checking to see all of the models are going to the correct controller, and not mixed up or left out.  

**Describe the solution you'd like**
A toggle like the check for overlaps on the layout tab, where all of the models that are on the same controller as the model selected would be highlighted (say in blue for example).  A more advanced feature would be to have another window where you could select a highlight color for each controller and then select each controller be toggled on/off as needed.

**Describe alternatives you've considered**
The controller name is shown in the text on the start channel, so can always be read from that.  This would just make it more obvious for checking.

**Additional context**
None.

**Comment by keithsw1111** [comment]
If you sort on the controller connection column it will group by controller and port.

**Comment by deplanche** [comment]
That is nice, but there isn't a way to select multiple models from that list and highlight them.  For the more visually based people (rather than those who like lists), I think it could be helpful to be able to see everything on one controller all at once.  Sort of like the visual controller does, but on the layout screen.

**Comment by keithsw1111** [comment]
This is now possible on the controller tab.
