### ISSUE TITLE
Access violation on process shutdown on Windows

### ISSUE THREAD

**Issue by PeteMatthews** [smeighan/xLights#1917]
**Describe the bug**
Access violation on xLights process shutdown under certain conditions - 
Exception thrown at 0x00007FF87284B300 (oleaut32.dll) in Xlights.exe: 0xC0000005: Access violation reading location 0x0000000000000021. occurred

**To Reproduce**
Follow steps in README.windows to build Windows debug version, using Windows 10 with VS2019 community (16.4.2)
 - Download, patch, build wxWidgets 3.1.3 for x64 debug
 - Set appropriate environment variable
 - Clone xlights from master branch (reproduced here with commit be0c274a1, although I have reproduced with versions back to 2020.01 to eliminate any of my messing with memory leaks)
 - Build xLights for x64 "Debug with Boost"
 - Start xLights with new empty show folder 
 - Create arch model
 - Create new sequence (animation, 40fps, Quick start)
 - Add butterfly effect to arch (don't think it matters which effect, just something)
 - Close xLights, saving the sequence as "1.xml" on the way down

At this point, the VS debugger will leap into action, showing exe_common.inl with the following details:
Exception thrown at 0x00007FF87284B300 (oleaut32.dll) in Xlights.exe: 0xC0000005: Access violation reading location 0x0000000000000021. occurred
A screenshot of this is attached for reference.

Crash can be repeated using the same show directory - 
 - Open xLights with same show directory
 - Create new sequence
 - Add effect to the arch
 - Close xLights, saving the new sequence on the way down

The exception is always exactly the same (trying to read location 21), which might point to a reproducible heap corruption?

Note that the same problem does not occur if you open an existing sequence, edit it and save when closing xLights.

Log from the VS output console is attached.
Zip of show directory is also attached.
Happy to provide a complete zip of my build environment on request, or just built binaries, etc.

Git is happy that my build dir is clean with no modifications:
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

$ git log -1
commit be0c274a163af62e74c9ea8ea940eba7e6e086a9 (HEAD -> master, origin/master, origin/HEAD)
Author: Gil Jones <gil@threebuttes.com>
Date:   Wed Jan 15 17:21:19 2020 -0700

    Hopefully fix Travis build

$

Just to be sure I wasn't going mad - I just went back and repeated this all with 2020.01, git commit e77f992a6a61170e8606ef219e051be768721009 with the same results.

Attached files:
![vs debugger](https://user-images.githubusercontent.com/7393265/72526929-6a054400-385f-11ea-8806-419dc03cbb59.png)
[vs output console.txt](https://github.com/smeighan/xLights/files/4071247/vs.output.console.txt)
[show.zip](https://github.com/smeighan/xLights/files/4071248/show.zip)

**Comment by PeteMatthews** [comment]
Started a rough binary chop on this... so far, 2019.10 is OK, 2019.70 fails. 

Trying to narrow it down, but it's going to be slow going.

**Comment by AzGilrock** [comment]
I'm using VS 2019 50 times a day with the latest xLights code and I'm not getting this on exit.  I don't use "Debug with Boost" whatever that is.

**Comment by PeteMatthews** [comment]
The dreaded "It only breaks on my machine" then :)

the "Debug with Boost" thing is the default build profile (on mine, at least) when I opened the solution/project in VS. Same results if I just pick "Debug" or "Release".

I'll keep poking around then. Entirely possible this is caused by something else I have installed (it's a corporate laptop with god-only-knows what system monitoring on). 

Thanks for the info, though... It's all helpful :)

**Comment by PeteMatthews** [comment]
2019.66 works, 2019.67 breaks... Taking apart the commits between them now.

**Comment by PeteMatthews** [comment]
2019.65 works, 2019.66 breaks. Taking apart the intermediate commits now...

**Comment by AzGilrock** [comment]
Well I know Boost is a package of classes but I don't think we use them.

**Comment by PeteMatthews** [comment]
The commit in question seems to be 491e8c1a0, which is pretty frustrating, as it's a bunch of binary library changes (among other things) :)

I'll have a play and see if I can isolate the problem. It's slow, but it does feel like progress :)

**Comment by AzGilrock** [comment]
At least that commit says it only changed 183 files... :)

**Comment by AzGilrock** [comment]
You know when you run from your own build in VS I've always had to manually copy the needed DLLs into the folders that it runs from the project doesn't seem to put them there automatically.  Maybe one got updated if you had an older version.

**Comment by PeteMatthews** [comment]
> At least that commit says it only changed 183 files... :)
No kidding - Thank god for decent tree diff tools :) It looks like a lot of it is shifting versions of wxWidgets, which definitely won't be to blame, I'm sure ;)

The DLL copy thing - having clean built about 30 different versions of xLights today, I needed to copy them for some older builds, but the more recent ones didn't seem to need it (don't think it lines up with working/crashing versions for me though). Of course, that might mean it's using some from installed things on my laptop (good old Windows DLL Hell). I might try copying/isolating things better and making sure I'm not doing anything (too) dumb. This commit does have a bunch of dependency library changes in the vcxproj file too, so it might be that it's linking things from different places.

Summary of the above rambling - It's a big complex commit that causing me issues, and it's going to take me a while to dig through it. On the upside, it seems it's only affecting me, and then only in a very specific scenario, so to a large extent it's not that important :)

I don't see it on released binaries that I run though... Are the released versions built with MinGW/CodeBlocks? That'll be a whole different pile of compile/link fun which might be immune.

(On the upside - As I know it's just me, other stuff I've been doing is presumably OK, which is nice. Completely understand if you folks still want to hold off on PRs from me until I can work this out.)

**Comment by AzGilrock** [comment]
Keith is doing the releases using VS now and I believe that was the whole goal of the commit in question.  I currently have an issue preventing me from building CodeBlocks builds and I used to be 100% CodeBlocks.

**Comment by AzGilrock** [comment]
In fact the build_scripts directory contains what he is using to build.

**Comment by PeteMatthews** [comment]
Realised too late that I knew it was VC based these days - People having issues with the VC runtime installer on update should have tipped me off to that one. Apologies.

Minor interesting update though - Released versions do actually exhibit the same behaviour for me. I was playing around last night, and I was starting my built executables from Windows Explorer or a cmd prompt, and when it's not attached to a debugger, it didn't show any visible sign of this crash. I started to wonder if it was related to having the debugger attached (I've seen dumber things :) ). At some point (and I forget why), I started it from a git bash session. While it didn't signal the crash in the GUI at all, I did get a "segmentation fault" message in the console when the process came down.

I just tried running my installed release (2020.01, 64 bit), and I got the same message...
>MINGW64 /c/Program Files/xLights
$ ./xLights.exe
Segmentation fault
$

To verify, I started my installed copy and attached the VS debugger to the process manually - it trips over exactly the same exception.

So we can ignore all my confusion above - The official released versions do seem to exhibit the same crash, they're just much more subtle about it :) Quite what this means, I don't know, but thought it was worth mentioning.

(Still doesn't make this worthy of anyone's time investigating it, given where it occurs and the total lack of people complaining about it :) )

**Comment by keithsw1111** [comment]
So using your show folder and following the instructions I can reproduce the crash. The challenge is it is crashing right at the death ... xLights is all gone and the C runtime is cleaning up.

So now I tried to start finessing your steps.

If i dont create a sequence ... no crash.
If I dont drop an effect ... it still crashes (so that is not a factor)
If I discard the sequence ... it does not crash ... I think this is super critical.
The save process pops up the save as dialog ... and it includes an infinite amount of windows plugins etc.

So some googling ... not sure this is the problem but I do wonder if it isn't something kind of like this ... https://peteronprogramming.wordpress.com/2017/12/06/i-hope-you-dont-mind-if-some-of-your-globals-destructors-are-not-called/ ... again not the specifics but similar interference from these sorts of plugins. If your machine is anything like mine i have explorer plugin modules galore and any of them could be the problem.

The next question becomes is it something we have done (or are not doing).

I am not sure where to go next.

**Comment by patdelaney** [comment]
Not that I am a "real" developer in any way, I was able to build/compile
xLights with Visual Studio Community yesterday.

**Comment by PeteMatthews** [comment]
Possibly helpful - The stack trace for the crash included oleacc.dll symbols, and google tells me they're related to Windows Accessibility related stuff. I started to wonder if the wxWidgets accessibility code is relying on something we're freeing too soon or something like that so I went poking around.

Turns out that if you rebuild wxWidgets with the accessibility stuff disabled (define wxUSE_ACCESSIBILITY to 0 in setup.h, alongside the current patches), the crash goes away. Which is nice. 

Not sure what the next step is... Are there any accessibility features actually used in xLights at the mo? I had a quick search but couldn't find any implemented. We could just amend the supplied binaries/build instructions to disable it and move on with life?

(Given the lack of code in xLights for accessibility, I suspect it's wxWidgets doing something unpleasant without our influence... Google's not finding anyone else complaining though)

> If your machine is anything like mine i have explorer plugin modules galore and any of them could be the problem.

Yeah, it is a working development laptop, with all manner of crap installed by me. It's also company owned, so also has whatever our IT department see fit to include... I dread to think ;)

**Comment by PeteMatthews** [comment]
Or, from the look of it, we could override the message handling to drop WM_GETOBJECT before wxWidgets gets its hands on it...

https://forums.wxwidgets.org/viewtopic.php?p=48190#48190

(Not tested this, speculation only, wxWidgets may be breaking things in a way that doesn't require it to have received a GETOBJECT message :) )

**Comment by keithsw1111** [comment]
I suspect this was a compiler error and there was a recent release of MSVC that I believe fixed this. It had to do with static object deletion.
