### ISSUE TITLE
Compiled version of xLights and xScheduler for Pi

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#1919]
## Is your feature request related to a problem? 
No

## Describe the solution you'd like
Compile xLights and xSchedular for the Pi
The Pi has been able to run desktop apps for some years now, the last Pi4 has improved this again.
xSchedular may benefit from the GPIO/Bluetooth

## Describe alternatives you've considered
xlights is already available for other platforms including Linux on Intel.

## Extra Info
https://github.com/abhiTronix/raspberry-pi-cross-compilers#optimization-flags-involved

**Comment by AzGilrock** [comment]
Why don't you do it yourself?  I did last night and I knew nothing about building this in Linux.  I bought a new Pi 4 with 4gig of ram.  It started up with NOOBS that came with the kit and I installed Debian for Pi.  Then I followed the Linux build instructions right in the xLights top folder.  It takes a long time but I left it running overnight and it built xLights and xSchedule by this morning.  I tested real quick and xSchedule launched up.  Probably pointless to try xLights on a Pi but I think xScheduler should be fine.  I was surprised the Pi was a snappy little computer I was reading my emails and surfing the net while it was compiling until I decided to leave it overnight.

**Comment by damon-atkins** [comment]
Referances
* https://github.com/smeighan/xLights/blob/master/README.linux
* https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html#adding-packages-to-debian

**Comment by damon-atkins** [comment]
Thanks for trying it out.

**Comment by AzGilrock** [comment]
Trying what out?  I closed it because you didn't say anything in reply to me you just posted links with no explanation of what or why.   It sounds like you know enough to tackle this its an open project.

**Comment by damon-atkins** [comment]
Thanks for buying a Pi, Compiling, testing, it out and discovery it works fine.  i.e. Trying it on a Pi.
Referance are their to help other who might come across this issue. Happy for it to be closed.

**Comment by AzGilrock** [comment]
Ok but what I did wasn't really related to this issue we've had this kind of thing on the radar for a long time.
