### ISSUE TITLE
Importing effects, highlight groups blue

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#1926]
On the Map Channels dialog when importing effects, 
The left hand list highlights groups in blue text, 
is it possible to highlight groups in the right hand list aswell?

I am guessing maybe not as it doesnt appear to record groups in the xml currently, 
And if ever introduced only newer rendered xmls would be updated.

**Comment by keithsw1111** [comment]
This is not possible as the importer does not know the element type it is importing from.
