### ISSUE TITLE
Unable to retrieve any faces

### ISSUE THREAD

**Issue by jdmaag** [smeighan/xLights#1927]
Newbie here. I have been using xlights for a while and learning how it works. I am at the point where i want to learn how to do talking faces. When i open faces under layout and try to download images i keep getting "unable to retrieve any faces". what am i doing wrong.
John

**Comment by AzGilrock** [comment]
Hard to say.  Can you bring up this file in a browser to verify your web access?
http://nutcracker123.com/xlights/faces/xlights_faces.xml

I'd also try Tools -> Purge Download Cache first

**Comment by jdmaag** [comment]
Thank you that worked, purging download cache. And yes i could open
ttp://nutcracker123.com/xlights/faces/xlights_faces.xml
<http://nutcracker123.com/xlights/faces/xlights_faces.xml> before purging
