### ISSUE TITLE
changing faces

### ISSUE THREAD

**Issue by jdmaag** [smeighan/xLights#1929]
the only way i can change a face is to delete the face effect and add it back. Then it will only let me do it one time. Is there a fix for this?

**Comment by computergeek1507** [comment]
A video would be helpful

**Comment by derwin12** [comment]
Might  this be when you update say someface_E_eo.png image file - I have found the only way to get it to see the updated .png file is to delete the entire face then re-add it. Is there a better/easier way?

**Comment by keithsw1111** [comment]
I just tried it and it seems to change the image file just fine. Can we either get the video requested or we are going to have to close this issue.

**Comment by jdmaag** [comment]
I found out yesterday that if i import a sequence and then go back to my
sequences this happens. to correct it i have to close xlights and reboot my
computer, open xlights and then i can add faces to my sequences

**Comment by AzGilrock** [comment]
Ok I'd believe it if you only said close and reopen xLights.  I don't believe rebooting can change anything in xLights unless you end up with a locked file that won't clear.  So again we don't really believe you unless you show video proof.  Last chance.

**Comment by jdmaag** [comment]
believe it or not. that is what works for me. I dont believe you have never
had this problem before or you just ignored it

**Comment by AzGilrock** [comment]
Sorry but we have nothing to go on for troubleshooting.

**Comment by jdmaag** [comment]
trying to up load a video

**Comment by jdmaag** [comment]
https://youtu.be/W5AqNR4FTug

here is the video

**Comment by AzGilrock** [comment]
So here's the problem.  You've made 2 statements here.  1)  You have to delete the Face effect and add a new one to get it to allow you to add faces.  2)  Then you switched the statement to say after importing a sequence you have to close xlights and reboot to be able to download faces.

So in this video I see neither of these things occurring you don't show the deletion of a face and then it starts working nor did you show a reboot fixing anything.

I probably won't be the one looking into this anyways I'm just trying to help get the relevant info.

**Comment by jdmaag** [comment]
my fault on the first, i meant change the face. I think I know where the
problem lies. My show is stored on dropbox and in learning xlights and
helpful person can look at what i have done to see if it is ok. I am
wondering if when he opens one of my sequences and makes a change, renders
it and saves it, that causes the problem.
