### ISSUE TITLE
ZCPP Setup Limited to 16384 Channels. F48 Supports 49152 Channels

### ISSUE THREAD

**Issue by publiux** [smeighan/xLights#1930]
When adding Zero Configuration Pixel controller such as the F48, the "# of Channels" spinner maxes out at 16384 channels. The F48 can control 16384 pixels maximum, meaning 49152 channels.

**Comment by computergeek1507** [comment]
fixed with 48a6d3bd2cfad2182ca74c84903269e4361105ae
