### ISSUE TITLE
Auto Phenomes for chromabulbs

### ISSUE THREAD

**Issue by Baf05** [smeighan/xLights#1931]
We have auto functions for eyes in Chromabulbs. Which is great.

I would like to see the same thing for Phenomes.  Perhaps with the ability to chose which phenoms you would like to use.  

Currently to do something like this I need to create timing marks and manually change the phenome each time.  Its a tad arduous.  It would be easier if this could be done automatically.  |

I would still do it manually at times because someone times I want the bulb to convey the emotion of the song, but other times simply changing the mouth shape from time to time gives the bulb the life I need.  

I am just trying to give my bubs a little life when they are not suppressed.

**Comment by keithsw1111** [comment]
So you just want us to randomly move the mouth ... I really dont think there is a general need for this. And as you say if you want it to do that you can do it. I dont want to add a bunch of code for something that I really only think you would use.
