### ISSUE TITLE
Enhancement: Ability to play/stop sequence with spacebar (or other key in keybindings file)

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#194]
Can we have the ability to map the PLAY/STOP buttons on the toolbar to the spacebar. Various other editors (Final Cut Pro, that i'm used to) allows to use spacebar to play/stop the timeline.

Thanks

**Comment by stevegiron** [comment]
'Cha talkin about Willis?  It works that way for me right now!

**Comment by LightsOnHudson** [comment]
You know it does.. BUT... I was in another effects window.. The effects window had the 'focus' of the mouse and when I pressed space bar it did nothing.. it beepted at me.

Using OSX 4.0.17

If i clicked in the sequencer window and then pressed space bar, then it did play and stop.

So, The spacebar needs to have global focus to trigger the playback --- well.. unless you are in the Text effect, then it wouldn't work if you wanted to put a space in your text.

Hmmmmmmmmmmm. I guess it works as planned, it just was not working when I had focus on something else...

**Comment by stevegiron** [comment]
Closing this one as it works as designed.
