### ISSUE TITLE
New Controller Tab - "Open" with multicast

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#1940]
On the controller tab in 2020.4 BETA, if the controller is set to multicast, the little green or red dot for pinging the controller goes away, but the button to open the controller remains.  If the button is pressed, it tries to open something, but nothing opens up.  Seems like the open button should be disabled when in multicast, since no specific controller is specified.

**Comment by keithsw1111** [comment]
Fixed ... also stopped open for controllers that i know dont have web user interfaces. Thanks JD for trying it out.
