### ISSUE TITLE
Add zig zag under controller connection

### ISSUE THREAD

**Issue by ebuechner** [smeighan/xLights#1944]
With the current setup in xlights with a mega tree for instance, if I do a traditional setup letting xlights do the reversing of the strands that zigzag it has those strands reversed while sequencing.
Many times I sequence down to the Strand on my mega tree because it's easier than using the buffer or effect assist.
If I want a morph effect to up the tree and copy and paste that other strands it doesn't behave consistently across all the strands some of them are reversed. 
Because of this I've always let the controller handle the zigzag and then do a custom set up in the tree but with the changes that are being made this won't allow for the visualize controller or upload to controller to work properly in this scenario. 
Adding a zig zag to the controller connections should allow for everything to behave consistently and possibly be useful for other situations where string zigzagging is needed.

**Comment by computergeek1507** [comment]
I don't see how one parameter would fix your issues. I assume you are creating a tree with double the amount of strings in xLights then the ports you are using on the controller and connecting the strings together. How would xLights know all of this? The easiest way is to create a dummy model with the correct settings for uploading and setup the same start channel as your "sequence" model, then just remove the controller port from the sequence model

**Comment by AzGilrock** [comment]
I think a video would have helped because I'm still not following the original issue you are trying to work around.  The Strands Per String setting should not cause data to look wrong in xLights so if it does I'd like to see why.  Reversing data in xLights should just change the order the bytes are sent to the controller or written into the FSEQ file it should not change the direction you see things on the screen.

**Comment by ebuechner** [comment]
https://youtu.be/PixWmLL6sIk

**Comment by AzGilrock** [comment]
Thanks.  I actually got home and tried it out before I noticed you had replied.  Yeah I see when you put an effect on the strand level the buffer created is kinda dumb.  It creates a horizontal buffer even though the strands are vertical and like you said it doesn't honor the direction the strand really goes.  Its things like that make we wonder why the hell are we doing it that way as well.

**Comment by ebuechner** [comment]
If we could get all the strands to act the same without doing the zig zag that would be fine by me as well. Maybe a checkbox to change the behavior so it doesn't break people's sequences.
I just thought that adding the zig zag to the controller connections would be the easiest route without disrupting work people have already done
I hopped onto to zoom and there was somebody else trying to sequence at the Strand level and having the same issues. 
Shared sequences that are sequenced at the Strand level are not going to work consistently across all trees with the way it works now.

**Comment by AzGilrock** [comment]
Well it seems like you can just leave it like you had it with all the strands going up and then just manually set the zig-zag in the controller.  Your post made it sound like this is a big pain in the ass issue but it just seems like its a convenience issue to having the auto upload set one field that you can set manually.

**Comment by ebuechner** [comment]
You're right this is nothing more than a convenience issue for me but it's something I think we need to address as we're moving towards controller connections and uploads.
The pain in the ass when the buffer does not act consistent across all of the strands and like I said this might be an issue for sharing sequences that have effects at the Strand level.
