### ISSUE TITLE
Serial Output upload to Falcon Controller

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#1945]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When uploading serial port information to the F48, the start channel universe/start channel mode does not seem correct unless it's the first universe on the controller, regardless of the universe number.  Not sure if this changed with the new controller tab setup, or just something I stumbled across when testing some things with that.  

**To Reproduce**
See the video, and xlights xml files attached.  Note that the file is basic to try to isolate the problem.  I wasn't sure if my actual setup was a problem, where I run DMX off serial 2 and 3 only.  But problem seems consistent regardless of setup.

Video Link https://youtu.be/jcMxcpwaMqY

**Expected behavior**
I would expect the start channels to be the same for any universe, not to change depending on which universe it is.

**Versions (please complete the following information):**
 F48 v 2.52
 - xLights version 2020.04 BETA

**Comment by keithsw1111** [comment]
So ... not a new bug ... turns out it always didnt work if you uploaded more than one serial output. It has been fixed.
