### ISSUE TITLE
2020.5 x64 Crahses When Opening Preferences

### ISSUE THREAD

**Issue by publiux** [smeighan/xLights#1946]
**Describe the bug**
XLights crahses when I open the preferences dialog.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Start xLights x64
2. Select Preferences...

**Expected behavior**
Should not crash

**Screenshots**
Debug zip attached.
[xLights_dbgrpt-8308-20200222T081354.zip](https://github.com/smeighan/xLights/files/4239393/xLights_dbgrpt-8308-20200222T081354.zip)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.5

**Comment by AJ240-Aus** [comment]
Openning the preferences tab causes this crash, I have attached the debug.
Anything else you need let me know.
This is also happening on my laptop (intel) and my Desktop (AMD). Both windows 10 64bit.

[xLights_dbgrpt-17780-20200223T085729.zip](https://github.com/smeighan/xLights/files/4240071/xLights_dbgrpt-17780-20200223T085729.zip)

**Comment by SaaltFam** [comment]
Yep I read it and had to try.
And yes it does crash.
[xLights_dbgrpt-10320-20200203T195519.zip](https://github.com/smeighan/xLights/files/4240581/xLights_dbgrpt-10320-20200203T195519.zip)
[xLights_dbgrpt-20716-20200223T135015.zip](https://github.com/smeighan/xLights/files/4240582/xLights_dbgrpt-20716-20200223T135015.zip)

**Comment by keithsw1111** [comment]
I've looked at the traces and tried to reproduce it and I am not seeing the problem.
Any chance someone could dump the following registry key (and all its sub keys)
Computer\HKEY_CURRENT_USER\Software\Xlights to a text file as this is the most likely cause of the problem.

**Comment by AJ240-Aus** [comment]
[xlights regkey export.txt](https://github.com/smeighan/xLights/files/4247079/xlights.regkey.export.txt)
Keith, I have attached mine for you as well. I am just down in Narellan if you need to see it locally.

**Comment by keithsw1111** [comment]
Can you try this version ... I am not sure I have fixed anything but this seems more stable on my machine: https://www.dropbox.com/s/7anetj7430enf8s/xLights64_2020_06.exe?dl=0

**Comment by SaaltFam** [comment]
Thank you Keith
Preference tab work

Cheers
Aaron

**Comment by AJ240-Aus** [comment]
works for me too. Now I have another issue. Intel I7 laptop loads Xlights in about 10 seconds. More powerful AMD desktop takes about 40sec to load Xlights. ???? Seems to take a loooong time to build GL Canvas. If it really anoys me I will raise a seperate issue.

**Comment by publiux** [comment]
Morning. I upgraded to 2020.6 but the preferences window still causes a crash. I tried both with a sequence loaded and without. Running it as admin in Windows 10 allowed me to access preferences. I am attaching the registry export as a text below.

[xlights.txt](https://github.com/smeighan/xLights/files/4266891/xlights.txt)
