### ISSUE TITLE
2020.5 Universe/ID not staying the same

### ISSUE THREAD

**Issue by zachcloutier** [smeighan/xLights#1947]
**Describe the bug**
After setting up Universes the Universe/ID reverts back to 1 when auto size is enabled.

**To Reproduce**
1. Go to Controllers
2. Add Controllers
3. Set ID
4. Set to Auto Size
5. Go to Layout
6. Add prop and set its start channel
7. Go back to Controllers to see bug

This does not happen when Auto Size is disabled.

I also think there is a problem with auto size it does not grow with adding props to the controller.

**Expected behavior**
My Universe/ID to stay the same.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.5

**Additional context**
This is a new xLights directory I am setting up.

**Attachments**
[Layout.zip](https://github.com/smeighan/xLights/files/4241977/Layout.zip)

**Comment by computergeek1507** [comment]
I'll look at it tonight

**Comment by computergeek1507** [comment]
fixed with c160bc9654bcd289bf2afbf1fac1ca72d994e04c
