### ISSUE TITLE
2020.5 x64 ArtNET

### ISSUE THREAD

**Issue by KuhnDaniel** [smeighan/xLights#1948]
the option with ArtNET start from Univers 0 is no longer possible? 
There are controllers that start at 0 and not at 1 !!!!
(DMxFreak controller by Ulrich Radig egsp)

Thanks Daniel

**Comment by computergeek1507** [comment]
fixed with f6f6bcee818e6369b181143b66dd944b00aa90d5

**Comment by harueg** [comment]
Hi @computergeek1507 

I am having problems with the ArtNet 4096 Kanal LED Pixel Controller from Radig. After a few seconds the ethernet ( artnet ) breaks down. It works perfectly with Jinx!. I have a separate Ethernet board, no switch in between. Same with my office network over switch.
Are there any known issues ?
Thanks
Harald

**Comment by KuhnDaniel** [comment]
Hello #harueg 
its done? Powerproblem?

**Comment by harueg** [comment]
Hello @KuhnDaniel 
Yes !
Sorry, I forgot to mention ! Yes in jinx! the master was on 50 %, so it worked there.
Thank you

Harald
