### ISSUE TITLE
Bars Effects: Custom Horz/Vert Value Curve Bug

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#1949]
While attempting to use the Custom Horiz/Vert Direction in the Bars effect, the center point slider works.  However, adding a value curve to that field does not show a change in the center point.  

![image](https://user-images.githubusercontent.com/12719816/75120149-2b7d5900-5657-11ea-9674-a3ac799f2928.png)

**Comment by keithsw1111** [comment]
It seems to work for me.

**Comment by Clyde-L** [comment]
Upgraded to .6 today.  Restarted computer... all works fine now.  Thanks for looking.
