### ISSUE TITLE
2020.6 Auto size not growing.

### ISSUE THREAD

**Issue by zachcloutier** [smeighan/xLights#1951]
**Describe the bug**
When auto size is selected the universe does not grow to fit what is allocated to that universe.

**To Reproduce**
1. Go to controllers
2. Add controller and select auto size
3. Add props to controller universe

**Expected behavior**
I expect the universes to grow when I add props that exceed the current number of channels and universes to the controller.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.6

**Additional context**
This also occurred in 2020.5

**Attachments**
[Layout.zip](https://github.com/smeighan/xLights/files/4245269/Layout.zip)

**Comment by computergeek1507** [comment]
You have to assign the controller and controller port. I don't think it works if you are using universe start channeling.

**Comment by keithsw1111** [comment]
I think this is working.

**Comment by keithsw1111** [comment]
Closing due to no response.
