### ISSUE TITLE
Make Icicles Formable

### ISSUE THREAD

**Issue by rogerdebolt** [smeighan/xLights#1952]
Not sure how difficult it would be to make Icicles able to change shape. For example I have driveway arches and hang icicles from them. I would like to make the icicles form to the curves in the layout.

**Comment by AzGilrock** [comment]
Already a feature....add icicle drops to a PolyLine model
![image](https://user-images.githubusercontent.com/2024669/75302741-f6f6d200-57fb-11ea-9712-6f4cd5372f20.png)
