### ISSUE TITLE
2020.6 Autosize skipping channel 1, and skipping string 1

### ISSUE THREAD

**Issue by AleXthePunK** [smeighan/xLights#1953]
This is not the same issue someone else reported.

When you turn on autosize, it recalculates your props, starts at channel 2, and removes a string.

There is a video attached.

[zoom_0.zip](https://github.com/smeighan/xLights/files/4252778/zoom_0.zip)

**Comment by computergeek1507** [comment]
I have a fix I will check in tonight.

**Comment by computergeek1507** [comment]
fixed with dec60495bbd1a5c784fd831c6727bc5aa6dcd965
