### ISSUE TITLE
Model Chaining doesn't appear to be working on multi port models

### ISSUE THREAD

**Issue by Poporacer** [smeighan/xLights#1957]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When you have a model that spans ports on a controller and want to add a different model to the end of the first model, it appears that the chaining isn't working because the Model Chain for the second model does not update to the correct Model Chain selected.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Define a Model that spans more than one port
2.Assign a new model to the same controller/last Port of the first model
3. Select the Model Chain to follow the first model

**Expected behavior**
The Model properties should reflect the correct Model Chaining

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
[ModelChaining.zip](https://github.com/smeighan/xLights/files/4270542/ModelChaining.zip)

**Comment by keithsw1111** [comment]
Chaining two multi-port models has undefined behaviour right now.

**Comment by Poporacer** [comment]
The second model is not a multi-port model, it is a one port model.

**Comment by Poporacer** [comment]
Version 2020.9 did not fix this problem. You can use the visualizer to assign the model correctly but assigning the Model manually from the Layout tab does not appear to be working correctly.

**Comment by keithsw1111** [comment]
Yeah ... going to need a video because 99% chance if the visualiser works then you are doing something wrong as the visualiser just sets the manual settings (but correctly)

**Comment by Poporacer** [comment]
I included a video with the original post that reflects the problem. The Model does get assigned when you are in the layout tab but the layout tab does not reflect the correct configuration. When you assign the second model to chain after the tree, the layout tab will still show it at the beginning, but the visualizer will show it after the tree.

**Comment by keithsw1111** [comment]
That is correct. The star is the first thing on the port but models from prior ports come first. I don’t think this is going to change.

Sent from my iPhone

On 13 Mar 2020, at 12:49 am, Poporacer <notifications@github.com> wrote:

﻿

I included a video with the original post that reflects the problem. The Model does get assigned when you are in the layout tab but the layout tab does not reflect the correct configuration. When you assign the second model to chain after the tree, the layout tab will still show it at the beginning, but the visualizer will show it after the tree.

**Comment by Poporacer** [comment]
I think I am tracking. The tree is assigned to port 1 but spans 8 ports. When you assign the star to port 8 it is technically the beginning of port 8 but after what was previously assigned. It just seemed confusing because normally you would chain your models and you can select the tree as a model to chain after but it isn't really a valid option. Maybe hide the tree from the chain?
