### ISSUE TITLE
Expand universe tickbox request

### ISSUE THREAD

**Issue by lithgowlights** [smeighan/xLights#1958]
**Is your feature request related to a problem? Please describe.**

In the latest releases when clicking on a controller you have the option to expand the universe list and then type in a new channel count for each universe. 

**Describe the solution you'd like**

Can there be a check so that when you untick this box and you HAVE changed the channel count for at least one universe, have the program bring a popup box saying do you wish to reset all universe sizes to default (Wherever you have in the main screen for that controller) channels with a Yes/Cancel option - yes unticks and resets, cancel leaves the box ticked and does not change any universe sizes

**Describe alternatives you've considered**
No real alternatives as saving any typed in info would be a waste when the box is not ticked

**Comment by keithsw1111** [comment]
ok
