### ISSUE TITLE
Crash when copying and pasting phoneme 2020.07

### ISSUE THREAD

**Issue by rmbowman819** [smeighan/xLights#1960]
I experience a crash when doing the following in a lyric track:
1. Changing the length of a phoneme
2. deleting a phoneme
3. Copying a different phoneme and pasting it.
4. Doing this for a second time in at a different time without selecting re-copying a phoneme first.

**Comment by gayde2** [comment]
I am also seeing crashes whenever I try to paste something that isn't allowed. For example, if I try to paste an effect from another line into a region that is slightly smaller than the effect, xLights crashes. If I try to paste some effects over another effect, it crashes. These should silently fail and not crash the program. Maybe there's some assertion or check that a pasted effect can't overwrite another effect?
