### ISSUE TITLE
Compile on Linux Ubuntu Command Line Failing during Linker Stage

### ISSUE THREAD

**Issue by shmorgan** [smeighan/xLights#1965]
Compiling 2020.09 at the command line on Ubuntu 18.04 LTS with all os patches installed.

I'm seeing a large number of errors that report an undefined reference to log4cpp::Appender

I hand downloaded, compiled and installed log4cpp just to make sure that was not an issue, that did not correct the errors.

Linker Command:
make[1]: Entering directory '/usr/local/src/xLights.2020.09/xLights'
g++  -o ../bin/xLights .objs_lr/outputs/Controller.o .objs_lr/models/ViewObject.o .objs_lr/models/ViewObjectManager.o .objs_lr/models/WholeHouseModel.o .objs_lr/models/WindowFrameModel.o .objs_lr/models/WreathModel.o .objs_lr/osx_utils/TouchBars.o .objs_lr/outputs/ArtNetOutput.o .objs_lr/outputs/ControllerEthernet.o .objs_lr/outputs/ControllerNull.o .objs_lr/outputs/ControllerSerial.o .objs_lr/outputs/DDPOutput.o .objs_lr/outputs/DMXOutput.o .objs_lr/outputs/E131Output.o .objs_lr/outputs/IPOutput.o .objs_lr/models/PolyLineModel.o .objs_lr/models/MeshObject.o .objs_lr/models/Model.o .objs_lr/models/ModelGroup.o .objs_lr/models/ModelManager.o .objs_lr/models/ModelScreenLocation.o .objs_lr/models/Node.o .objs_lr/models/ObjectManager.o .objs_lr/outputs/LOROptimisedOutput.o .objs_lr/models/Shapes.o .objs_lr/models/SingleLineModel.o .objs_lr/models/SphereModel.o .objs_lr/models/SpinnerModel.o .objs_lr/models/StarModel.o .objs_lr/models/SubModel.o .objs_lr/models/TreeModel.o .objs_lr/preferences/SequenceFileSettingsPanel.o .objs_lr/outputs/xxxSerialOutput.o .objs_lr/preferences/BackupSettingsPanel.o .objs_lr/preferences/ColorManagerSettingsPanel.o .objs_lr/preferences/EffectsGridSettingsPanel.o .objs_lr/preferences/OtherSettingsPanel.o .objs_lr/preferences/OutputSettingsPanel.o .objs_lr/preferences/RandomEffectsSettingsPanel.o .objs_lr/outputs/xxxEthernetOutput.o .objs_lr/preferences/ViewSettingsPanel.o .objs_lr/preferences/xLightsPreferences.o .objs_lr/sequencer/DragEffectBitmapButton.o .objs_lr/sequencer/Effect.o .objs_lr/sequencer/EffectDropTarget.o .objs_lr/sequencer/EffectLayer.o .objs_lr/sequencer/EffectsGrid.o .objs_lr/outputs/OutputManager.o .objs_lr/outputs/LOROutput.o .objs_lr/outputs/LorController.o .objs_lr/outputs/LorControllers.o .objs_lr/outputs/NullOutput.o .objs_lr/outputs/OpenDMXOutput.o .objs_lr/outputs/OpenPixelNetOutput.o .objs_lr/outputs/Output.o .objs_lr/models/MatrixModel.o .objs_lr/outputs/PixelNetOutput.o .objs_lr/outputs/RenardOutput.o .objs_lr/outputs/SerialOutput.o .objs_lr/outputs/TestPreset.o .objs_lr/outputs/ZCPPOutput.o .objs_lr/outputs/serial.o .objs_lr/effects/TreePanel.o .objs_lr/effects/TwinkleEffect.o .objs_lr/effects/TwinklePanel.o .objs_lr/effects/VUMeterEffect.o .objs_lr/effects/VUMeterPanel.o .objs_lr/effects/VideoEffect.o .objs_lr/effects/VideoPanel.o .objs_lr/effects/WarpEffect.o .objs_lr/effects/WarpPanel.o .objs_lr/effects/WaveEffect.o .objs_lr/effects/WavePanel.o .objs_lr/effects/assist/AssistPanel.o .objs_lr/effects/assist/PicturesAssistPanel.o .objs_lr/effects/assist/xlGridCanvasEmpty.o .objs_lr/effects/assist/xlGridCanvasMorph.o .objs_lr/effects/StatePanel.o .objs_lr/effects/SnowstormEffect.o .objs_lr/effects/SnowstormPanel.o .objs_lr/effects/SpiralsEffect.o .objs_lr/effects/SpiralsPanel.o .objs_lr/effects/SpirographEffect.o .objs_lr/effects/SpirographPanel.o .objs_lr/effects/StateEffect.o .objs_lr/effects/assist/xlGridCanvasPictures.o .objs_lr/effects/StrobeEffect.o .objs_lr/effects/StrobePanel.o .objs_lr/effects/TendrilEffect.o .objs_lr/effects/TendrilPanel.o .objs_lr/effects/TextEffect.o .objs_lr/effects/TextPanel.o .objs_lr/effects/TreeEffect.o .objs_lr/models/DMX/Servo.o .objs_lr/models/DMX/DmxPanTiltAbility.o .objs_lr/models/DMX/DmxServo.o .objs_lr/models/DMX/DmxServo3D.o .objs_lr/models/DMX/DmxShutterAbility.o .objs_lr/models/DMX/DmxSkull.o .objs_lr/models/DMX/DmxSkulltronix.o .objs_lr/models/DMX/Mesh.o .objs_lr/models/DMX/DmxMovingHead3D.o .objs_lr/models/DMX/ServoConfigDialog.o .objs_lr/models/DMX/SkullConfigDialog.o .objs_lr/models/GridlinesObject.o .objs_lr/models/IciclesModel.o .objs_lr/models/ImageModel.o .objs_lr/models/ImageObject.o .objs_lr/models/CubeModel.o .objs_lr/heartbeat.o .objs_lr/kiss_fft/kiss_fft.o .objs_lr/kiss_fft/tools/kiss_fftr.o .objs_lr/models/ArchesModel.o .objs_lr/models/BaseObject.o .objs_lr/models/CandyCaneModel.o .objs_lr/models/ChannelBlockModel.o .objs_lr/models/CircleModel.o .objs_lr/models/CustomModel.o .objs_lr/models/DMX/DmxColorAbility.o .objs_lr/models/DMX/DmxFloodArea.o .objs_lr/models/DMX/DmxFloodlight.o .objs_lr/models/DMX/DmxImage.o .objs_lr/models/DMX/DmxModel.o .objs_lr/models/DMX/DmxMovingHead.o .objs_lr/xlColorCanvas.o .objs_lr/xLightsApp.o .objs_lr/xLightsImportChannelMapDialog.o .objs_lr/xLightsMain.o .objs_lr/xLightsTimer.o .objs_lr/xLightsVersion.o .objs_lr/xLightsXmlFile.o .objs_lr/xlColorPicker.o .objs_lr/xlColorPickerFields.o .objs_lr/xlGLCanvas.o .objs_lr/xlGridCanvas.o .objs_lr/xlLockButton.o .objs_lr/xlSlider.o .objs_lr/vamp-hostsdk/RealTime.o .objs_lr/vamp-hostsdk/PluginBufferingAdapter.o .objs_lr/vamp-hostsdk/PluginChannelAdapter.o .objs_lr/vamp-hostsdk/PluginHostAdapter.o .objs_lr/vamp-hostsdk/PluginInputDomainAdapter.o .objs_lr/vamp-hostsdk/PluginLoader.o .objs_lr/vamp-hostsdk/PluginSummarisingAdapter.o .objs_lr/vamp-hostsdk/PluginWrapper.o .objs_lr/vamp-hostsdk/acsymbols.o .objs_lr/vamp-hostsdk/host-c.o .objs_lr/wxCheckedListCtrl.o .objs_lr/wxModelGridCellRenderer.o .objs_lr/sequencer/Element.o .objs_lr/sequencer/MainSequencer.o .objs_lr/sequencer/RowHeading.o .objs_lr/sequencer/SequenceElements.o .objs_lr/sequencer/TimeLine.o .objs_lr/sequencer/UndoManager.o .objs_lr/sequencer/Waveform.o .objs_lr/sequencer/tabSequencer.o .objs_lr/support/EzGrid.o .objs_lr/support/FastComboEditor.o .objs_lr/support/GridCellChoiceRenderer.o .objs_lr/support/VectorMath.o .objs_lr/tmGridCell.o .objs_lr/vamp-hostsdk/Files.o .objs_lr/effects/SnowflakesPanel.o .objs_lr/NoteImportDialog.o .objs_lr/ModelPreview.o .objs_lr/ModelStateDialog.o .objs_lr/MultiControllerUploadDialog.o .objs_lr/MusicXML.o .objs_lr/NewTimingDialog.o .objs_lr/NodeSelectGrid.o .objs_lr/NodesGridCellEditor.o .objs_lr/NoteRangeDialog.o .objs_lr/OpenGLShaders.o .objs_lr/OptionChooser.o .objs_lr/OutputModelManager.o .objs_lr/PaletteMgmtDialog.o .objs_lr/Parallel.o .objs_lr/PathGenerationDialog.o .objs_lr/PerspectivesPanel.o .objs_lr/MIDI/Binasc.o .objs_lr/LayerSelectDialog.o .objs_lr/LayoutGroup.o .objs_lr/LayoutPanel.o .objs_lr/LinkJukeboxButtonDialog.o .objs_lr/LorConvertDialog.o .objs_lr/LyricUserDictDialog.o .objs_lr/LyricsDialog.o .objs_lr/MIDI/MidiEvent.o .objs_lr/MIDI/MidiEventList.o .objs_lr/MIDI/MidiFile.o .objs_lr/MIDI/MidiMessage.o .objs_lr/MatrixFaceDownloadDialog.o .objs_lr/ModelChainDialog.o .objs_lr/ModelDimmingCurveDialog.o .objs_lr/ModelFaceDialog.o .objs_lr/ModelGroupPanel.o .objs_lr/SelectTimingsDialog.o .objs_lr/SeqElementMismatchDialog.o .objs_lr/SeqExportDialog.o .objs_lr/SeqFileUtilities.o .objs_lr/SeqSettingsDialog.o .objs_lr/SequenceData.o .objs_lr/SequenceVideoPanel.o .objs_lr/SequenceVideoPreview.o .objs_lr/SequenceViewManager.o .objs_lr/SevenSegmentDialog.o .objs_lr/ShaderDownloadDialog.o .objs_lr/SplashDialog.o .objs_lr/StartChannelDialog.o .objs_lr/StrandNodeNamesDialog.o .objs_lr/SubBufferPanel.o .objs_lr/Render.o .objs_lr/PhonemeDictionary.o .objs_lr/PixelBuffer.o .objs_lr/PixelTestDialog.o .objs_lr/PreviewModels.o .objs_lr/PreviewPane.o .objs_lr/RemapDMXChannelsDialog.o .objs_lr/RenameTextDialog.o .objs_lr/LOREdit.o .objs_lr/RenderBuffer.o .objs_lr/RenderCache.o .objs_lr/RenderProgressDialog.o .objs_lr/ResizeImageDialog.o .objs_lr/SaveChangesDialog.o .objs_lr/SelectPanel.o .objs_lr/CheckboxSelectDialog.o .objs_lr/Color.o .objs_lr/ColorCurve.o .objs_lr/ColorCurveDialog.o .objs_lr/ColorManager.o .objs_lr/ColorPanel.o .objs_lr/ColoursPanel.o .objs_lr/ControllerConnectionDialog.o .objs_lr/CharMapDialog.o .objs_lr/ControllerModelDialog.o .objs_lr/ConvertDialog.o .objs_lr/ConvertLogDialog.o .objs_lr/CurrentPreviewModels.o .objs_lr/CustomModelDialog.o .objs_lr/CustomTimingDialog.o .objs_lr/DataLayer.o .objs_lr/BitmapCache.o .objs_lr/__/xSchedule/wxJSON/jsonreader.o .objs_lr/__/xSchedule/wxJSON/jsonval.o .objs_lr/__/xSchedule/wxJSON/jsonwriter.o .objs_lr/AlignmentDialog.o .objs_lr/AudioManager.o .objs_lr/BatchRenderDialog.o .objs_lr/DimmingCurve.o .objs_lr/BufferPanel.o .objs_lr/BufferSizeDialog.o .objs_lr/BulkEditControls.o .objs_lr/BulkEditFontPickerDialog.o .objs_lr/BulkEditSliderDialog.o .objs_lr/CachedFileDownloader.o .objs_lr/ChannelLayoutDialog.o .objs_lr/Image.o .objs_lr/FlickerFreeBitmapButton.o .objs_lr/FolderSelection.o .objs_lr/FontManager.o .objs_lr/GenerateCustomModelDialog.o .objs_lr/GenerateLyricsDialog.o .objs_lr/HousePreviewPanel.o .objs_lr/IPEntryDialog.o .objs_lr/FileConverter.o .objs_lr/Image_Loader.o .objs_lr/ImportPreviewsModelsDialog.o .objs_lr/JobPool.o .objs_lr/JukeboxPanel.o .objs_lr/KeyBindings.o .objs_lr/LMSImportChannelMapDialog.o .objs_lr/EffectListDialog.o .objs_lr/DimmingCurvePanel.o .objs_lr/DissolveTransitionPattern.o .objs_lr/DragColoursBitmapButton.o .objs_lr/DragValueCurveBitmapButton.o .objs_lr/DrawGLUtils.o .objs_lr/DrawGLUtils31.o .objs_lr/EffectAssist.o .objs_lr/EffectIconPanel.o .objs_lr/SubModelGenerateDialog.o .objs_lr/EffectTimingDialog.o .objs_lr/EffectTreeDialog.o .objs_lr/EffectsPanel.o .objs_lr/EmailDialog.o .objs_lr/ExportModelSelect.o .objs_lr/FSEQFile.o .objs_lr/effects/KaleidoscopeEffect.o .objs_lr/effects/KaleidoscopePanel.o .objs_lr/effects/LifeEffect.o .objs_lr/effects/LifePanel.o .objs_lr/effects/LightningEffect.o .objs_lr/effects/LightningPanel.o .objs_lr/effects/LinesEffect.o .objs_lr/effects/LinesPanel.o .objs_lr/effects/LiquidEffect.o .objs_lr/effects/LiquidPanel.o .objs_lr/effects/MarqueeEffect.o .objs_lr/effects/MarqueePanel.o .objs_lr/effects/MeteorsEffect.o .objs_lr/effects/MeteorsPanel.o .objs_lr/effects/MorphEffect.o .objs_lr/effects/FireworksPanel.o .objs_lr/effects/FanEffect.o .objs_lr/effects/FanPanel.o .objs_lr/effects/FillEffect.o .objs_lr/effects/FillPanel.o .objs_lr/effects/FireEffect.o .objs_lr/effects/FirePanel.o .objs_lr/effects/FireworksEffect.o .objs_lr/effects/MorphPanel.o .objs_lr/effects/GIFImage.o .objs_lr/effects/GalaxyEffect.o .objs_lr/effects/GalaxyPanel.o .objs_lr/effects/GarlandsEffect.o .objs_lr/effects/GarlandsPanel.o .objs_lr/effects/GlediatorEffect.o .objs_lr/effects/GlediatorPanel.o .objs_lr/effects/RippleEffect.o .objs_lr/effects/RipplePanel.o .objs_lr/effects/ServoEffect.o .objs_lr/effects/ServoPanel.o .objs_lr/effects/ShaderEffect.o .objs_lr/effects/ShaderPanel.o .objs_lr/effects/ShapeEffect.o .objs_lr/effects/ShapePanel.o .objs_lr/effects/ShimmerEffect.o .objs_lr/effects/ShimmerPanel.o .objs_lr/effects/ShockwaveEffect.o .objs_lr/effects/ShockwavePanel.o .objs_lr/effects/SingleStrandEffect.o .objs_lr/effects/SingleStrandPanel.o .objs_lr/effects/SnowflakesEffect.o .objs_lr/effects/PianoPanel.o .objs_lr/effects/MusicEffect.o .objs_lr/effects/MusicPanel.o .objs_lr/effects/OffEffect.o .objs_lr/effects/OffPanel.o .objs_lr/effects/OnEffect.o .objs_lr/effects/OnPanel.o .objs_lr/effects/PianoEffect.o .objs_lr/effects/FacesPanel.o .objs_lr/effects/PicturesEffect.o .objs_lr/effects/PicturesPanel.o .objs_lr/effects/PinwheelEffect.o .objs_lr/effects/PinwheelPanel.o .objs_lr/effects/PlasmaEffect.o .objs_lr/effects/PlasmaPanel.o .objs_lr/effects/RenderableEffect.o .objs_lr/VendorModelDialog.o .objs_lr/VendorMusicDialog.o .objs_lr/VendorMusicHelpers.o .objs_lr/VideoExporter.o .objs_lr/VideoReader.o .objs_lr/ViewObjectPanel.o .objs_lr/ViewpointDialog.o .objs_lr/ViewpointMgr.o .objs_lr/ViewsModelsPanel.o .objs_lr/Vixen3.o .objs_lr/VsaImportDialog.o .objs_lr/WiringDialog.o .objs_lr/XlightsDrawable.o .objs_lr/controllers/AlphaPix.o .objs_lr/controllers/BaseController.o .objs_lr/UpdaterDialog.o .objs_lr/SubModelsDialog.o .objs_lr/SuperStarImportDialog.o .objs_lr/TabConvert.o .objs_lr/TabPreview.o .objs_lr/TabSequence.o .objs_lr/TabSetup.o .objs_lr/TimingPanel.o .objs_lr/TopEffectsPanel.o .objs_lr/TraceLog.o .objs_lr/controllers/ControllerCaps.o .objs_lr/UtilFunctions.o .objs_lr/VAMPPluginDialog.o .objs_lr/VSAFile.o .objs_lr/ValueCurve.o .objs_lr/ValueCurveButton.o .objs_lr/ValueCurveDialog.o .objs_lr/ValueCurvesPanel.o .objs_lr/effects/ButterflyEffect.o .objs_lr/effects/ButterflyPanel.o .objs_lr/effects/CandleEffect.o .objs_lr/effects/CandlePanel.o .objs_lr/effects/CirclesEffect.o .objs_lr/effects/CirclesPanel.o .objs_lr/effects/ColorWashEffect.o .objs_lr/effects/ColorWashPanel.o .objs_lr/effects/CurtainEffect.o .objs_lr/effects/CurtainPanel.o .objs_lr/effects/DMXEffect.o .objs_lr/effects/DMXPanel.o .objs_lr/effects/EffectManager.o .objs_lr/effects/EffectPanelUtils.o .objs_lr/effects/FacesEffect.o .objs_lr/controllers/J1Sys.o .objs_lr/controllers/ControllerUploadData.o .objs_lr/controllers/ESPixelStick.o .objs_lr/controllers/FPP.o .objs_lr/controllers/FPPConnectDialog.o .objs_lr/controllers/Falcon.o .objs_lr/controllers/HinksPix.o .objs_lr/controllers/HinksPixExportDialog.o .objs_lr/__/xSchedule/md5.o .objs_lr/controllers/Pixlite16.o .objs_lr/controllers/SanDevices.o .objs_lr/controllers/WebSocketClient.o .objs_lr/djdebug.o .objs_lr/__/xFade/wxLED.o .objs_lr/effects/BarsEffect.o .objs_lr/effects/BarsPanel.o  -lGL -lGLU -lglut -ldl -lX11 -lcurl `pkg-config --libs libavformat libavcodec libavutil  libswresample libswscale` `pkg-config --libs log4cpp` `sdl2-config --libs` `wx-config --version=3.1 --libs std,media,gl,aui,propgrid` `pkg-config --libs gstreamer-1.0 gstreamer-video-1.0` -lexpat -rdynamic -lz -lzstd  ../lib/linux/libliquidfun.a

Errors I am seeing...

.objs_lr/sequencer/RowHeading.o: In function `_GLOBAL__sub_I__ZN10RowHeading13sm_eventTableE':
RowHeading.cpp:(.text.startup+0x14c): undefined reference to `log4cpp::Appender::AppenderMapStorageInitializer::AppenderMapStorageInitializer()'
RowHeading.cpp:(.text.startup+0x153): undefined reference to `log4cpp::Appender::AppenderMapStorageInitializer::~AppenderMapStorageInitializer()'
.objs_lr/SequenceData.o: In function `_GLOBAL__sub_I__ZN9FrameData10_constzeroE':
SequenceData.cpp:(.text.startup+0x32): undefined reference to `log4cpp::Appender::AppenderMapStorageInitializer::AppenderMapStorageInitializer()'
SequenceData.cpp:(.text.startup+0x39): undefined reference to `log4cpp::Appender::AppenderMapStorageInitializer::~AppenderMapStorageInitializer()'
.objs_lr/PhonemeDictionary.o: In function `_GLOBAL__sub_I__ZN17PhonemeDictionary16LoadDictionariesERK8wxStringP8wxWindow':
PhonemeDictionary.cpp:(.text.startup+0xc): undefined reference to `log4cpp::Appender::AppenderMapStorageInitializer::AppenderMapStorageInitializer()'
PhonemeDictionary.cpp:(.text.startup+0x13): undefined reference to `log4cpp::Appender::AppenderMapStorageInitializer::~AppenderMapStorageInitializer()'
.objs_lr/outputs/Controller.o: In function `__static_initialization_and_destruction_0(int, int) [clone .constprop.195]':
Controller.cpp:(.text.startup+0x62): undefined reference to `log4cpp::Appender::AppenderMapStorageInitializer::AppenderMapStorageInitializer()'
Controller.cpp:(.text.startup+0x69): undefined reference to `log4cpp::Appender::AppenderMapStorageInitializer::~AppenderMapStorageInitializer()'
.objs_lr/outputs/ArtNetOutput.o: In function `_GLOBAL__sub_I__ZN12ArtNetOutput5(int, E *)':
ArtNetOutput.cpp:(.text.startup+0x32): undefined reference to `log4cpp::Appender::AppenderMapStorageInitializer::AppenderMapStorageInitializer()'
ArtNetOutput.cpp:(.text.startup+0x39): undefined reference to `log4cpp::Appender::AppenderMapStorageInitializer::~AppenderMapStorageInitializer()'

**Comment by cjd** [comment]
Which version of log4cpp are you compiling/using?

**Comment by shmorgan** [comment]
I believe it was 1.1, I executed the commands from the make file myself to download, compile and install it.

**Comment by cjd** [comment]
It has to be log4cpp 1.1.3 (or greater) - but sadly when you run 'pkg-config --modversion log4cpp' it will always only show 1.1 (not the subversion)
Where did you install log4cpp to (ie: /usr or /usr/local ?)
Can you check if you have another version of log4cpp installed somewhere?

**Comment by shmorgan** [comment]
I was able to remove the old log4cpp and compile and install the 1.1.3 version. The compile is now successful. however, when launching xlights, I get a Floating point exception (core dumped). xSchedule, xFade and xCapture will start with no issues. Also I am not getting any log entries on xSchedule.

**Comment by shmorgan** [comment]
I found this entry in the system log
Mar 16 12:30:45 ShowHQv4 kernel: [574110.225990] traps: xLights[20177] trap divide error ip:7fddd2697f2a sp:7ffc8fec73e0 error:0 in libwx_gtk2u-3.1.so.3.0.0[7fddd2128000+11e9000]

**Comment by shmorgan** [comment]
I just noticed that the list of packages required to install has been changed and log4cpp has been removed. I also see that the tested version is listed at 18.10, did you mean 19.10? I don't see an archive on Ubuntu's site for an 18.10 version, only 18.04.03 - Latest LTS.

**Comment by shmorgan** [comment]
This can be closed.
