### ISSUE TITLE
Generate Random Effects Crash

### ISSUE THREAD

**Issue by computergeek1507** [smeighan/xLights#1967]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Generate Random Effects Crashed xLights 2020.9 and no crash handler will appear

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Create a New Sequence
2. Add a timing track
3. Select some timing cells
4. Right Click and select Generate Random Effects

**Expected behavior**
Not Terminate xLights.

**Screenshots**
![random](https://user-images.githubusercontent.com/2293065/76427150-561f1f80-6382-11ea-9438-c698b1dc9aed.gif)

**Versions (please complete the following information):**
 - OS: Windows 10 Home
 - xLights version 2020.9, 2020.8, 2020.7, 2020.6, 2020.5, 2020.4, 2020.3, 2020.2, 2020.1, 2019.74, 2019.65

**Comment by keithsw1111** [comment]
I can generate them scott ... maybe there is something funky in your random effect settings?

**Comment by computergeek1507** [comment]
When I opened the preference dialog, all the effects to use were unselected, I selected some effects, save and then it worked. I reopen the preferences and unselected all the effects and it didn't crash. I looked at the code and Generate Random Effects will default to a off effect if none are selected, I will look into this more and see if I can find anything.

**Comment by computergeek1507** [comment]
fixed with ccaec81422b605cd06427fcc9630d7ef74ce44c8
