### ISSUE TITLE
Experience Report: 2020.09 and model with trailing space in name

### ISSUE THREAD

**Issue by steveking16** [smeighan/xLights#1969]
I'm reporting my experience with opening in 2020.09 when one of my models had a trailing space in its name.  

After the 09 update, when I opened my show folder, xLights reported about half of my props with overlapping channels. Even though the broken models showed they were chained correctly in the Start Channel field, the ending channel was simply the models channel count.

I sorted the models in the layout tab by start channel and could narrow where the chaining issues began.  When I changed the first faulty model's start channel fro "End of the previous model" to the correct "absolute value", the rest of my models reported correctly - I knew where to look.

From your change log, I knew to look for a trailing or leading space, but did not see that as an issue for this prop.  I closed xLights and opened the xlights_rgbeffects.xml file in VSCode.  There I found the a trailing space in the name of preceding model -- the model just prior to what I thought was the broken model.  I edit out the space, but when I opened xLights it wanted to drop that model from all the groups to which it belonged.

I exited back out of xLights, with out saving. Reopened the xlights_rgbeffects.xml file and edited the model name in all the groups, saved, and then reopened xLights.  

All is now rainbows and sunshine.

So while 09 may have updated the name of a model in the start channel of the trailing prop, it did not change the original model name, nor update the name in the model groups.

(In this process, I discovered I was not backing up to an existing directory, so thanks for that)

**Comment by keithsw1111** [comment]
Can you share your files that caused the problem? Without files we struggle to reproduce and fix your issues.

**Comment by steveking16** [comment]
Keith -- 

Here is a version that had the issue.  The bad model is "W1VR Sewing Room Window Right ", the right side of the window in the center of the house.

I see now, that when you sort by start channel, it is the last one on the list on the Main F48 with a "good" start channel.  Also, if you rename it there in xLights, all is good -- if you can find it.

I knew where to start looking from the Visualize on the controller, Port 5 is messed up - "House Snowflake 3" should be after "Eave 03 Sewing".  It's when I couldn't see anything obvious with these files that I opened the rgbeffects file.

xml files attached - with a ".txt" extension to get them to upload.

Let me know if you need any more information.

-- Steve

[xlights_rgbeffects.xml.txt](https://github.com/smeighan/xLights/files/4325609/xlights_rgbeffects.xml.txt)
![House Front](https://user-images.githubusercontent.com/7817380/76548504-0dcc3400-644c-11ea-9f04-9f20376ea213.JPG)
[xlights_keybindings.xml.txt](https://github.com/smeighan/xLights/files/4325610/xlights_keybindings.xml.txt)
[xlights_networks.xml.txt](https://github.com/smeighan/xLights/files/4325611/xlights_networks.xml.txt)
