### ISSUE TITLE
crashing when exporting

### ISSUE THREAD

**Issue by wdmilkie** [smeighan/xLights#197]
When I create a sequence; 
I right click "export sequence", the drop down menu displays a LOR clipboard file .lcb
I click OK, XL4 crashes, close's 
It said it sent an error report but I didn't catch where it went
this happens 9 out of 10 times

**Comment by wdmilkie** [comment]
no longer will export clipboard data for some reason

**Comment by wdmilkie** [comment]
Installing 4.20 XL4
open sequence
go to sequencer menu
previous model already loaded(mega tree)
right click, export model
format:  Lcb, LOR clipboard
name file
click OK, 
immediately crashes about 50% of the time

**Comment by wdmilkie** [comment]
I'm really sorry to bug you; so if this is closed, were you able to
re-create it? So it's not just me

**Comment by AzGilrock** [comment]
The way it works is when we check in a code change that we believe fixes the problem we use a phrase that includes the issue number and it triggers an auto close of the ticket.  You can see above where it says "dkulp closed this in 20e9d38".  You could click on that number and it would link you to the changes he did on the checkin.  So basically it means we believe we've fixed it with that checkin.  If it's still broke after next release then you can reopen the ticket.
