### ISSUE TITLE
PWM values not accurate.

### ISSUE THREAD

**Issue by skulltronix** [smeighan/xLights#1974]
When outputting servo data to i2C through FPP the values are about 40ms too low. Not sure if this is an issue on the FPP side or on the xlights side. Multiple vsa imports all have the same issue.

**Comment by AzGilrock** [comment]
I did a test yesterday and proved that xLights is creating the correct data value for the Servo effect.  I am not spending any additional time with an ambiguous issue description like this.  You can research this yourself and dig into it to figure out what data xLights is actually creating instead of just saying somewhere between VSA and FPP output things go wrong.  I'm not convinced you don't have a setup problem somewhere.

**Comment by skulltronix** [comment]
I’ve been looking at pwm meters for 2 days. All the pwm is off by about 40ms.
My jaw movement range of 1000-1500ms has to be set to 950-1470 in FPP to get the pwm meters to read 1000-1500. 
Whether that happens because of FPP or xl is difficult to determine. 

But...  new issue. 
I’m not getting servo movement  from xl when sliding the servo effect slider.   FPP shows data coming in.

 Xl will move the servos in test mode.

 FPP moves the servos in test mode and standalone mode.

 But in bridge mode no servo motion using the servo effect.  The lightbulb is checked. Rendering is done. 

As you said, it’s probably in setup. But it worked just before upgrading to the latest xl. 

I spend a lot of time trying to figure this out before asking for help. Ed helped me today via zoom and he was baffled also. 

Any help is always appreciated greatly.

Thanks!  


Jerry Jewell
Skulltronix.com
916 600 2295

**Comment by AzGilrock** [comment]
You've provided not a single thing for us to look at.  If you want to troubleshoot something like this the best thing is just create one servo effect so you know the exact value it should be.  Render it to an FSEQ file using V1 format and inspect the file to see the value of the data.  xLights just sends a 2 byte value it knows nothing about PWM.  You could use WireShark to intercept packets to see what the data looks like.  Every day you seem to describe a different issue.  For the record I've been sick and not spending much time on the computer.

**Comment by dkulp** [comment]
This is LIKELY a limitation of the pca9685 board.   The pca9685 can accept an external oscillator, but none of the "cheap" boards I have seen use one and instead rely on the internal oscillator.    That internal oscillator is a very basic RC timer circuit and is generally only accurate to about +/- 5%.   Being off by 40us in the ranges we are dealing with is definitely within the 5%.   

Since it's very board/chip etc... specific, it's not something we can correct for as one board may be -5% and another could be +5% or anywhere in between.  It's also likely somewhat temperature dependent. 

The best option is to have xLights generate an 8bit value 1-255 for the entire range you need and then have FPP config map that to values you test to work with your board and servos.

**Comment by skulltronix** [comment]
Thanks, I had not considered that there would be any pwm error through the board.  I assumed digital data kept the same values through the chain. 

Which means trying to drive servos through pca9685 is unpredictable and unusable for producing a product in any quantity unless the servo boards can be made “tunable”.  

Adding xlights into the mixture complicates everything. For my project to move forward I’ll need a way to get vsa files converted to fseq files without using xlights at all.  If I had a conversion program I could then move on to creating a new pi cap that puts out accurate pwm. 

Interested in writing such a program?  $$$??

I will try your idea of 8 bit in xlights if I can get xlights to stop crashing. Which may not happen since Gil is ill and not in a cooperative mood.  :(

Thank you. 

Jerry Jewell
Skulltronix.com
916 600 2295

**Comment by ebuechner** [comment]
I'm running 8-bit scaled and I noticed my boards are about 2% off.
If I subtract 2% from the values on the output configuration it gives me nearly a perfect value when I test it with a meter.
When I was running the servo dogs I had the same issue.
This is why I set my hard limits in the controller by playing with the values and watching the physical limits of the servo.
At 8 bit you have 255 points of resolution coming from the software and if you set limits in the software you reduce your resolution.
At 8 bits I haven't had a problem with the amount of resolution that I'm getting off of the servos. 
Most of my servos are set up to run about a 60-degree movement.

**Comment by skulltronix** [comment]
Thanks Ed.  I get 10-20% error at 16 bit but it varies unpredictably from servo to servo. The upper end can be off 20 pwm but the bottom end is off a different amount. I can’t just add or subtract a % to each end. 
I’m having a friend look at a conversion program to convert from vsa 16 bit straight to FPP fseq files without using xlights to do the conversion. 
I’ll keep everyone posted if it happens.

**Comment by AzGilrock** [comment]
There is nothing wrong with how xLights is converting the vsa data.  If it was wrong I’d fix it but you still never provided anything to show xLights is converting it wrong.  So bring proof or stay silent.

**Comment by dkulp** [comment]
Using 8bit scaled is definitely the way to go with these.   With a 12bit pwm, you have 4096 "slots" divided across the full 20ms (assuming the 50hz setting).   Assuming the servos operate from 1ms - 2ms, that gives an effective range of 205-410, or only 205 "slots" anyway.   Thus, the 256 scaled into that 205 space should work fine and not waste a bunch of channels.

**Comment by ebuechner** [comment]
Thanks Dan, this is working out so well for me I've abandoned my Servo dog set up that I have been using for quite a while.

The only thing I need now is a way to label the outputs 😉
I think all of the items on the output page need a way to be labeled.

**Comment by skulltronix** [comment]
I'm back again,,,,  I have just installed 2020.23. I have imported a simple arm movement that sets the value to VSA 750 (the arm's VSA range is 450 to 1250.  VSA 750 = 1500MS.)

 When imported to Xlights (using the same servo limits) the output is about 1250MS.  I've repeated this multiple times.  It is real. It does happen every time. 

You can check this by setting up a servo with a round servo horn.  Run the vsa file and mark the 750 position.  Run it again in Xlights and see the difference.   

I respectfully suggest that a future version of xlights changes the 0-100 slider values to either VSA values of 250-1250 OR to actual MS values of 500-2500.  Also, each servo's slider would be restricted to the movement range defined for that servo. This would make it easier for use servo folks who only think in MS and do away with any possible output errors.  

Or, perhaps all the math is correct in Xlights and its the actual dmx output that is wrong. ?????

If you'd like, I could send a pwm frequency meter for testing. 

Thank you!

[pwmtest.zip](https://github.com/smeighan/xLights/files/4740860/pwmtest.zip)

**Comment by AzGilrock** [comment]
I just tested this in xLights. Created a servo with limits of 450 to 1250 and then imported that file.  It creates a Servo effect that ramps from 0 to 37.5%.  The math is 1250-450=800, 800*0.375=300, 300 plus base of 450 is 750 so 37.5% is 750.  I saved the file and inspected the FSEQ file and its putting out a 0x02EE to the servo channels.  0x02EE is 750 decimal.  So xLights is sending 750 in the DMX output.  We can't help what happens to that command once it hits your hardware.  Again this is just wasting my time.

**Comment by skulltronix** [comment]
﻿Hi
I just looked at the math again.   750 is the vsa value, not the Pwm output value. Vsa cuts the ms in half while programming for some reason.  Vsa must be doubling their amount when outputting.  There’s no way you could have known that. 

The control board is a general Dmx board. Which means it doesn’t double vsa values. It doesn’t know vsa exists. The board takes Dmx values and converts to pwm. 

I’ll be getting together with Chuck Sommerville Monday to put the whole mess on an oscilloscope to see if what I said above is factual. 

Chuck wrote all the code for the Skulltronix boards and is a real expert on serial protocols and Dmx specifically.  We can get this all sorted out and let you know what we find. 

Best regards,


Jerry Jewell
Skulltronix.com
916 600 2295
