### ISSUE TITLE
Space in name bug

### ISSUE THREAD

**Issue by AleXthePunK** [smeighan/xLights#1975]
This is with 2020.10

The new code removes spaces at the beginning and end of the name, but if you accidently hit space and erase the name, it will remove the space and leave the name field blank. It broke my XML file when I tested it.

Otherwise, the new code seems to be working.

**Comment by AzGilrock** [comment]
I'm trying to figure out what you're saying.  Did you leave the name a space on purpose?  Are you saying when you accidentally hit the space it did not allow you to type a name?

**Comment by AleXthePunK** [comment]
If you change the name of a model to only a space, it will remove the space and save the model with no name. If you do this to multiple models, it will save them all, then break xlights.

**Comment by AzGilrock** [comment]
Yeah well stop naming models with just a space.

**Comment by computergeek1507** [comment]
I tried this on the newest code and it doesn't do this anymore, wait until the next release and see if it is fixed.
