### ISSUE TITLE
Sequence timing observations

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#198]
If I create a sequence with 25ms timing, then go to Settings/Sequence settings, the Sequence Timing resolution pull down shows 50ms. Not sure if that is just a default value and only is for changing.  How else are we to know the sequence timing value? 

Also if I create a sequence with 100ms timing, I'm still allowed 50 and 25ms fixed timing marks with no caution that the timing mark resolution is lower than the configured timing for the sequence.

**Comment by AzGilrock** [comment]
No you're right that drop down doesn't currently have any code associated with it.  Actually I think there are a boatload of issues if you did down this rabbit hole.  If you create a 100ms timing sequence I think the grid still allows 25ms resolution.  I remember asking the team if I should prevent the timing from being modifed after creation cause I'm not sure to do with existing data if you reduce resolution.
