### ISSUE TITLE
exported GIF from xlights shows purple instead of black

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#1980]
Im using 2020.10 (any of the versions I tested does this from 2020.5 up) and im upgrading my tree form a 16x50 to a 24x100 so to get the old tree effects and video exported to the new tree to look good and scaled I used the model export as gif feature, the export works and looks good if played on my mac but once I drop the new gif into Xlights and render its actually lighting up the nodes purple in areas that should be black (off). In xlights everything looks great, I did this for 20 sequences a few weeks ago and all looked but but now I hooked up a string of lights and noticed this was an issue and not of the sequences look right cause black or off is purple to the physical lights

here's a video explaining and showing it all to ya  -  https://youtu.be/mU5K1wi2l6Q

please let me know if you need any other info 

this is on my mac, haven't tested PC yet

**Comment by bchiaino** [comment]
texted this on my sons WIN10 pc, same issue, 2020.11, all brand new setup, only added a tree and reproduced the same issue

**Comment by AzGilrock** [comment]
I did a test that was more simple.  I created a 10x10 matrix with a bars effect of just black and white.  Exported to GIF and inspected in Photoshop.  You can see the white is not exactly 255,255,255 nor is the black exactly 0,0,0.  Its a very tiny number but I guess 4,2,4 shows up as a dim purple on the pixels.
![image](https://user-images.githubusercontent.com/2024669/77376151-d3587600-6d2c-11ea-8f51-73148ef9cf72.png)

**Comment by AzGilrock** [comment]
I didn't know much about it and I gotta run but my guess is its the wxQuantize call that reduces the image colors when creating the GIF file.

**Comment by bchiaino** [comment]
Thanks Gill for testing! the more info the better obviously. hope all is well man

**Comment by keithsw1111** [comment]
It is wxQuantize ... I have implemented a fix which detects an almost black r,g, and b < 5 and forces them to full black.

**Comment by bchiaino** [comment]
Keith quick question with the new update, Is the fix to turn the lights "off" on the existing GIF or will I have to re-export them again cause the fix is in the exporting part making the GIF?

I tried both ways and it looks like I need to re-export all again but wanted to confirm there's no workaround I can do before I go through all 20 sequences again, thanks for the fix!!!!!!!!!!!!

**Comment by computergeek1507** [comment]
You have to re-export all the gifs.

**Comment by bchiaino** [comment]
sounds good, thank you guys!

**Comment by keithsw1111** [comment]
With the new chromakey you could try chromakeying on black and twiddling the sensitivity but yes generally you would re export.

Sent from my iPhone

On 29 Mar 2020, at 1:55 am, bchiaino <notifications@github.com> wrote:

﻿

Keith quick question with the new update, Is the fix to turn the lights "off" on the existing GIF or will I have to re-export them again cause the fix is in the exporting part making the GIF?

I tried both ways and it looks like I need to re-export all again but wanted to confirm there's no workaround I can do before I go through all 20 sequences again, thanks for the fix!!!!!!!!!!!!

**Comment by bchiaino** [comment]
Thank you Keith!
