### ISSUE TITLE
Previous Issues have been fixed (2019.74-2020.4)

### ISSUE THREAD

**Issue by matt-torrie** [smeighan/xLights#1983]
hey Chris, good news (didn't get anything on the Facebook page) but in 2020.9 we can switch layouts and breakdown lyrics fully, good work. I was keeping an eye on the "new releases" in the xlights page and didn't notice your name mentioned on the bug fixes/enhancements/changes mentions. 

I'm not sure how far back the issue was fixed but I noticed it's all fully working in 2020.9 unless there are new effects added in I'm sticking with this version. 

keep up the good work guys.

**Comment by keithsw1111** [comment]
Did you close the issues that have been fixed?

**Comment by keithsw1111** [comment]
BTW ... not every change gets mentioned ... maybe 50% make it to the release notes. Anything technical generally does not go there unless it clearly addresses an issue I remember being called out.

**Comment by matt-torrie** [comment]
I didn't make the issues known on the other ones on here, I normally used Facebook and directly tagged Chris, as for closing the other issues I don't know if I can close issues made by others, keep up the good work guys, I really appreciate it. I'm really considering donating to the cause when I have a little expendable income.
