### ISSUE TITLE
xLights crash when rendering

### ISSUE THREAD

**Issue by eaglebob** [smeighan/xLights#1987]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When trying to render sequence I received on the google drive the program crashes, I am not sure if it is my computer, or happen to be something in the program; the sequence is very heavy in shaders. 

**To Reproduce**
I tried to render.

**Expected behavior**
I expected it to render like all the other times.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Win 10
 - xLights version 2020.11 & 12

**Additional context**

**Attachments**
[2020 Stayin Inside - Corona Virus Bee Gees Paraody.zip](https://github.com/smeighan/xLights/files/4397945/2020.Stayin.Inside.-.Corona.Virus.Bee.Gees.Paraody.zip)
[xLights_dbgrpt-17676-20200328T162239.zip](https://github.com/smeighan/xLights/files/4397946/xLights_dbgrpt-17676-20200328T162239.zip)

**Comment by keithsw1111** [comment]
It is crashing because one of your shaders is crazy slow to run. I will change .13 to give it more time. See the log file to see exactly which one is slow ... it is in there.
