### ISSUE TITLE
Model alignment doesn't appear to be working in 4.0.18

### ISSUE THREAD

**Issue by habbosrus** [smeighan/xLights#199]
I am new to xl4 and downloaded 4.0.14 and started setting up my preview. I updated to 4.0.18 this morning to continue setup and it appears that aligning models isn't working. I checked Sean's video and went back through the steps to shift, left click, drag, right click, align - but it doesn't seem to be working now (could just be me)

**Comment by stevegiron** [comment]
Hello, I'm helping sort the issues and determine which issues are still valid. 
As of May-14 we are version 4.0.31. Is this issue still occuring?

**Comment by stevegiron** [comment]
I was able to reproduce this but there is a way to get it done. You have to have one model selected while all of them are highlighted. The selected model will be the one that is used for alignment reference.
![image](https://cloud.githubusercontent.com/assets/10568498/7713085/3f444bfe-fe2a-11e4-9b59-c214d95b6a5d.png)

**Comment by AzGilrock** [comment]
Didn't the model alignment issue get fixed?

**Comment by habbosrus** [comment]
Hi, I think it did. I'm currently in hospital (& way behind with everything
after moving house and injuring my foot 6 weeks ago) but will ask my wife
to bring in my laptop so I can check. With me, it was probably just user
error.
Thanks for an awesome piece of software.

**Comment by AzGilrock** [comment]
I tested and model alignment seemed to be working.  I'm closing this but if a new issue arises feel free to log a new one or reopen this one.
