### ISSUE TITLE
Individual start channels rejected on custom models when in Universe/Channel notation

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#1990]
When creating multi string custom models and selecting "Indiv Start Nodes" it is not possible to enter the individual strings start addresses in "#10.10.17.157:17:91" notation.

**Comment by keithsw1111** [comment]
Thats because it is start nodes and not start channels. They are not the same thing.

**Comment by idleup** [comment]
Yeah, I did not realize that unlike Tree or Matrix models the 'Strings' for a Custom model are strictly for the purpose of determining when to start a new 'Port' when using the Controller Configuration upload and not for individual string start addressing. Thanks.
