### ISSUE TITLE
Exporting Models specifically "Icicles" and the "Display As" 

### ISSUE THREAD

**Issue by rosenthj01** [smeighan/xLights#1991]
When I Export Models, the "Display As" variable for Icicles does not seem to populate.

[xlights Models 2020-03-31.xlsx](https://github.com/smeighan/xLights/files/4411151/xlights.Models.2020-03-31.xlsx)

**Comment by AzGilrock** [comment]
Well its obviously got everything shifted left one cell and putting two cells into the first cell.

**Comment by keithsw1111** [comment]
Not a defect ... you have a double quote in the name which confuses excel when it loads the data,
