### ISSUE TITLE
Xlight crashing

### ISSUE THREAD

**Issue by Andyreynolds69** [smeighan/xLights#1996]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/4430710/xLightsProblem.zip)
(https://github.com/smeighan/xLights/files/4430714/Over.The.Rainbow.What.A.Wonderful.World.Medley.zip)

When opening a prevous sequence Xlights does Not show light in house preview so I render the sequence, most times during rendering it crashes or in this case when moving effects then playing sequence audio gets choppy then crashes

**Comment by wiidaddy** [comment]
I'm experiencing a similar issue, after upgrading to 2020.13.  I rolled back to 2020.12 where the issue does not exist.

One thing to note, sequences that have a singing model and/or a lyrics track are the ones that primarily crash upon re-rendering.

**Comment by keithsw1111** [comment]
I think it is blur ... at least it is in the sample provided.
