### ISSUE TITLE
State effect with DMX fixtures

### ISSUE THREAD

**Issue by bacarudaguy** [smeighan/xLights#2000]
Using Keith's video about DMX state effects (http://videos.xlights.org/dmx-model-stateeffect_65a050d18.html), I'm noticing that that moving heads are currently not reacting at all. I've attached a sample sequence with a state effect setup, along with a timing track and getting no response from the fixture... 

Thanks!
[DMX moving head states issue.zip](https://github.com/smeighan/xLights/files/4432852/DMX.moving.head.states.issue.zip)

**Comment by keithsw1111** [comment]
Yeah this was broken by some of the recent DMX changes.
