### ISSUE TITLE
ZCPP and smart receivers not working

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#2002]
not sure if this is still a work in progress but I switched over to ZCPP as a test, made sure smart receivers was checked to be supported but they do not work, its only uploading as f its a normal receiver and not splitting the ports up as it should so a prop that's on port 1A and another on 1B, if I go to 1A prop, they both light up 1A and 1B. I attached a screen shot of how it looks in E1.31 and then one n ZCPP where you can see nothing is divided up. in E1.31 it works fine
![Screen Shot 2020-04-05 at 8 30 57 PM](https://user-images.githubusercontent.com/40632971/78514344-ce5ce300-777e-11ea-86fb-f50c43ff9f82.png)
![Screen Shot 2020-04-05 at 8 44 12 PM](https://user-images.githubusercontent.com/40632971/78514352-d74db480-777e-11ea-8f08-f3ad484b5da3.png)
![Screen Shot 2020-04-05 at 8 49 17 PM](https://user-images.githubusercontent.com/40632971/78514373-f2b8bf80-777e-11ea-84c2-116d135fab67.png)
![Screen Shot 2020-04-05 at 8 52 31 PM](https://user-images.githubusercontent.com/40632971/78514448-6bb81700-777f-11ea-90ab-ddbb1694b035.png)

XLights 2020.14
F48 FW2.55

**Comment by keithsw1111** [comment]
Ping me your config ... I have newer firmware that displays the smart remote on the front screen.

**Comment by bchiaino** [comment]
thanks Keith, I sent Xlights files to you in Facebook message f that works. please let me know if that's the config yo need, would love to work on this with ya and get it going. thank you!

**Comment by keithsw1111** [comment]
I have sent you a windows build that fixes this. The bug was in the e131 upload code which was uploading even when the protocol was ZCPP which slowed down lights turn on and corrupted the controller strings table.
