### ISSUE TITLE
2020.14 - Protocol error ws2811 vs WS2811

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#2003]
I attached a packed sequence for you to check, I keep getting the following error below on my candy canes even though I keep selecting the correct protocol

![Screen Shot 2020-04-06 at 2 17 47 PM](https://user-images.githubusercontent.com/40632971/78591491-7f13c280-7811-11ea-945c-906aa98c6a4c.png)

ZCPP/DPP Checks
        Applying controller rules for F48:192.168.219.201:
ERR: Model CANDY CANE 1 on pixel port 5 has protocol ws2811 but port protocol has been set to WS2811. This is because you have mixed protocols on your models.

ERR: Model CANDY CANE 2 on pixel port 5 has protocol ws2811 but port protocol has been set to WS2811. This is because you have mixed protocols on your models.

ERR: Model CANDY CANE 3 on pixel port 6 has protocol ws2811 but port protocol has been set to WS2811. This is because you have mixed protocols on your models.

ERR: Model CANDY CANE 4 on pixel port 6 has protocol ws2811 but port protocol has been set to WS2811. This is because you have mixed protocols on your models.

ERR: Model CANDY CANE 5 on pixel port 7 has protocol ws2811 but port protocol has been set to WS2811. This is because you have mixed protocols on your models

.ERR: Model CANDY CANE 6 on pixel port 7 has protocol ws2811 but port protocol has been set to WS2811. This is because you have mixed protocols on your models.

[XLIGHTS 2.zip](https://github.com/smeighan/xLights/files/4439844/XLIGHTS.2.zip)

**Comment by bchiaino** [comment]
This can be closed unless you want to look into it a little more. My controller name was F48 (as it should be), I changed it to no controller name and then back to F48 and the errors are gone now. weird

**Comment by keithsw1111** [comment]
Yeah I have this one fixed.
