### ISSUE TITLE
Feature Request : Check box On elements for real-time On & Off (while sequence is playing)

### ISSUE THREAD

**Issue by Kamal-Sonani** [smeighan/xLights#2004]
[https://pasteboard.co/J2GH1zo.png](url) check this picture.

While sequence is running its difficult to stop particular element (send all ch value 00 ).

By adding check box its handy to do that. whichever element i want to block during show just Un_check it.
By-default all boxes are checked

Select all option is for just play music as it is and sequence go on as per timeline

Check box allowed for main layer of element only , other layers will follow as main layer's checkbox

**Comment by keithsw1111** [comment]
I dont understand why would this be useful

**Comment by keithsw1111** [comment]
No response so closing.
