### ISSUE TITLE
End channel not recalculated after adjusting a Star model in a new project.

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#2005]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I installed 2020.14 and created a fresh project. I created an e1.31 for FPP with 90 channels.
I added a star model, by default it's created as 50 nodes. I updated the node count to 30.
The End Channel for that model did not recalculate to 90 nodes. I tried to save the layout but it still did not recalculate.

I Saved the sequence and closed xLights.
I reopened xLights and opened the sequence and checked the layout and then it was now set to 90.

**Expected behavior**
A clear and concise description of what you expected to happen and why.
I would have expected top recalculate the end channel on the fly.

**Screenshots**
![wrong calc](https://user-images.githubusercontent.com/8147459/78692072-fc494100-78be-11ea-82e9-640471f5b717.jpg)

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**

**Comment by computergeek1507** [comment]
fixed with 2cc65d1df351b88789c97a9fc76cfbb49af0c38a
