### ISSUE TITLE
Adding depth in custom model

### ISSUE THREAD

**Issue by ebuechner** [smeighan/xLights#2006]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/4447119/xLightsProblem.zip)
I was working on making a custom model in .14 and noticed that when you add any numbers to the depth field xlights will close without generating an error report.
I tested back to .11 and that seems to be the last version without an issue.

**Comment by computergeek1507** [comment]
fixed with a794c7fa0d0aca371763b7dc4088c633f4145d10
