### ISSUE TITLE
MAC: Multiplied Tracking and scrolling when zoomed in layout

### ISSUE THREAD

**Issue by bedawg10** [smeighan/xLights#2007]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I am using 2020.14 on a macbook pro: My tracking and scrolling with both my trackpad and magic mouse work normally when zoomed out inside layout. However when I zoom in and try and track or scroll it's almost as if they are magnetized based on my zoom. the layout will fly off the screen and I have to zoom all the way out just to locate the image.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to 'layout' on a mac
2. Click on 'the background image and zoom to a roofline or window'
3. Move the mouse or trackpad around

**Expected behavior**
A clear and concise description of what you expected to happen and why. 
The tracking and scrolling should be smooth and should not intensify the more zoomed in you are.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Mac OS Cataline 10.15.3
 - xLights version 2020.14 (also was doing it in 2020.1b

**Additional context**

**Attachments**
I did a screen recording showing the issue. Please see the dropbox link below. 
https://www.dropbox.com/s/afbor5ussksl194/Screen%20Recording%202020-04-08%20at%201.19.47%20PM.mov?dl=0

**Comment by dkulp** [comment]
I uploaded a 2020.14b build.   Could you please test to see if it's better.   The original track pad fixes that were done in 2020.03 were only on the 3D side.   Did some of the same for the 2D side.

**Comment by bedawg10** [comment]
Works great! Thank you so much for the quick response. You guys are
awesome.
