### ISSUE TITLE
FPP Connect - Save Password

### ISSUE THREAD

**Issue by jaydonoghue** [smeighan/xLights#2009]
I use passwords on my fpp instances. When running FPP Connect, it asks for a password to connect. Each time FPP connect is run, it prompts for the password.

Would it be possible to cache/store this password for future connections from Xlights? Maybe a "Remember Password" checkbox to give people the choice

Currently using Xlights 2020.15

Thanks

**Comment by dkulp** [comment]
This is likely fixed for Windows and OSX.  It looks like the wxWidgets builds for Linux do not include the wxSecretStore  capabilities and thus it's likely not implemented there.
