### ISSUE TITLE
Crash after export

### ISSUE THREAD

**Issue by Santacarl** [smeighan/xLights#201]
When exporting to an .hlsnc file if you right click on the model that is in the SEQUENCER tab, choose export model, and hit OK the export begins but when it finishes exporting XL crashes.  However the .hlsnc file IS produced and does work.  The error page pops up but is grayed out and does not appear to send the report.

Export from the CONVERT tab works perfectly and only the 'right click' seems to problematic.

**Comment by wdmilkie** [comment]
Installing 4.20 XL4
open sequence
go to sequencer menu
previous model already loaded(mega tree)
right click, export model
format:  Lcb, LOR clipboard
name file
click OK, 
immediately crashes about 50% of the time

**Comment by AzGilrock** [comment]
Same issue as #197.
