### ISSUE TITLE
Appimage 2020.15 Crashing on new custom model creation

### ISSUE THREAD

**Issue by extremeskillz** [smeighan/xLights#2011]
Hey Guys,
I have a new issue with the 2020.15 linux appimage crashing upon creation of a new custom model. Also, any model that is new is crashing as well. Not sure when this started as it was fine in 2020.12. Im runnig Ubuntu 18.04lts.  I attached the crash logs.

[xLights_dbgrpt-26557-20200413T213946.zip](https://github.com/smeighan/xLights/files/4472678/xLights_dbgrpt-26557-20200413T213946.zip)
[xLights_dbgrpt-27278-20200413T214725.zip](https://github.com/smeighan/xLights/files/4472679/xLights_dbgrpt-27278-20200413T214725.zip)

**Comment by extremeskillz** [comment]
Tested 2020.16 and same result.

**Comment by keithsw1111** [comment]
This is way too vague a bug report to be useful. Either be specific or close it.

**Comment by extremeskillz** [comment]
With these version of xlights on Ubuntu 18.04LTS, created a custom model causes Xlights to crash. This generated crash reports attached to this ticket. This is only on new custom models not existing models that modified or changed.

**Comment by keithsw1111** [comment]
I may have this worked around ... not fixed ... this is a Linux only issue as far as i can tell.

**Comment by extremeskillz** [comment]
Sounds good. One implemented, hopefully i can move forward with my builds. I know Chris was having issues with Linux changing around the GTK themes but I would think using Ubuntu as the base system would be the rule of thumb for most distributions based on Debian.
Let me know of the fix or when its released. This crash is stopping my build progress currently.
As always, you guys are the best!
