### ISSUE TITLE
Format error causes crash in Linux debug build

### ISSUE THREAD

**Issue by leighfiddes** [smeighan/xLights#2013]
Kubuntu 18.04 LTS
xLights 2020.x Linux debug build.

Trying to edit the Model Data in a Custom Model causes a crash due to an assert.
![Screenshot_20200414_175027c](https://user-images.githubusercontent.com/59780576/79200529-eec12780-7e79-11ea-9560-ddb6c3ec013f.png)

Fairly simple issue.
In CustomModel::UpdateModel() the correct format string for "int" is "%d" not "%ld" in two cases.

**Comment by AzGilrock** [comment]
We don't release debug builds right?  So no user should ever see debug asserts.  If you want to fix code why not make the fix, test it, then submit the pull request.

**Comment by leighfiddes** [comment]
Thanks for the response Gil.
You are correct. Debug builds are not released. Release versions are shipped with (I assume) some basic testing and then further tested by the users who must submit crash reports when issues are found, which the developers must interpret to identify the cause of the issue.
As I understand the use of debug builds, it is to be less forgiving of issues which might not cause a problem in released versions (yet) but which are still bugs which might bite you in the future.
I consider this issue and #2014 to be simple coding mistakes, which we have all made, and so trivial that @keithsw1111 or someone could just add them as they are doing the next releases.

**Comment by computergeek1507** [comment]
fixed with 0d5e848d3ba9c38535e87c735f8599c8e3e20a3f

**Comment by AzGilrock** [comment]
I've been developing xLights for years but thanks for trying to explain to me how things work... haha

**Comment by leighfiddes** [comment]
I know. "Git blame" never forgets... haha. Anyway nice to know that we are on the same page. Cheers.
