### ISSUE TITLE
xLights v2020.15 "!to date!%fmt" crashes

### ISSUE THREAD

**Issue by rzwahlen** [smeighan/xLights#2016]
When using the text effect with the "!to date!%fmt" count down parameter, xLights v2020.15 crashes when attempting to add the requested date format as soon as the % is typed.

**Comment by keithsw1111** [comment]
You need to be specific ... what are you typing as it doesnt crash for me

**Comment by rzwahlen** [comment]
Even with the “Count down” set to “none”…

When I paste “/Fri, 25 Dec 2020 00:00:00 +1001/ %D” in the “Text” field, xLights immediately crashes.

**Comment by computergeek1507** [comment]
It crashed for me only if I change the direction parameter

**Comment by keithsw1111** [comment]
Found it
