### ISSUE TITLE
Tile Left/Right Movement in Picture Not Working for No Scaling

### ISSUE THREAD

**Issue by byakymyk** [smeighan/xLights#2017]
[NOTE:]
[LeftTileSeqTest.zip](https://github.com/smeighan/xLights/files/4494589/LeftTileSeqTest.zip)
 IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
In Picture effect, the Tile-Left and Tile-Right movement goes blank on a matrix when No Scaling is selected - It does work for the other two settings of Scale To Fit and Scale Keep Aspect Ratio

If I choose to us the Left or Right only movement the picture travels across the screen correctly for any of the three scale settings.

As simple animation sequence is attached.  I have a video showing but it won't upload.

OS: Mac 10.15.4 Xlights:2020.16 

(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
There is no sequence in that file. Did you save it before packaging it?

**Comment by keithsw1111** [comment]
Do you mean totally blank or partially blank ... I can see partial blankness which I can fix.

**Comment by byakymyk** [comment]
[TileLeftNoScaleIssue.zip](https://github.com/smeighan/xLights/files/4497966/TileLeftNoScaleIssue.zip)
Here is the sequence - I see totally blank
