### ISSUE TITLE
Scheduler add text movement glitch

### ISSUE THREAD

**Issue by gregg12** [smeighan/xLights#2018]
Version: Xlights Scheduler 2020.16

When adding text to a sequence in scheduler, the text movements does not render correctly when moving from "right to left" or "left to right". Instead of scrolling off the screen and then back on, it scrolls off the screen and then appears in the center and then starts to scroll. Attached is a video showing this. "top to bottom" and "bottom to top" movement renders correctly and scrolls off and on the screen. Also attached is the text setup in the scheduler.

[Matrix Video.zip](https://github.com/smeighan/xLights/files/4500693/Matrix.Video.zip)
![Capture](https://user-images.githubusercontent.com/63958611/79705018-13eed500-8282-11ea-8e57-60918b6e2495.PNG)

**Comment by keithsw1111** [comment]
You really should just add spaces before/after in the format line. The problem is if i add them then i get someone complaining about them.

**Comment by gregg12** [comment]
Will do Keith, thanks for the explanation.
