### ISSUE TITLE
Force Local IP Dropdown on Controller Tab

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#2020]
**Describe the bug**
Not sure if this should be listed as a bug or an enhancement, but noticed this while helping someone out in zoom, and it had several of us stumped in there.

On the controller tab in 2020.16, if you don't select a controller, there are some general settings displayed on the right side.  One of those is the Force Local IP.  There is a blank box there and a drop down.  You can't type a new IP in there, and if you select anything from the drop down (in this case only 1 IP was listed in the drop down), it doesn't save it.  The save button never turns red, and even if saved, if you click onto a controller and then off again, the local IP is not saved.  In order to change that, you have to go to File/Preferences, choose the Output Tab and then set the Forced Local IP there.  Then you can save it and keep it there.  

**To Reproduce**
See above

**Expected behavior**
With a drop down list of IPs on the controller tab, it would be expected that if you select one, it would be saved.  If it can't be saved, not sure if the drop down is needed, and would be a grayed out box showing a local IP if one was set or blank if not.

**Versions (please complete the following information):**
  - xLights version 2020.16

**Comment by computergeek1507** [comment]
fixed with ffe1fc1042739299508febcbf98098ca07003724
