### ISSUE TITLE
Marque Speed Crazy Fast at Low Setting

### ISSUE THREAD

**Issue by byakymyk** [smeighan/xLights#2023]
Marque Speed rapidly flickers at very low setting.  At attached is a sequence showing on a group model of Windows.  I tested on individual model and it has rapid flashing as well.

Mac OS 10.15.4 MacBook Pro 2019 16 - xLights 2020.16

[MarqueSpeedIssue.zip](https://github.com/smeighan/xLights/files/4513259/MarqueSpeedIssue.zip)
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by byakymyk** [comment]
Some how it seems to have rectified itself

**Comment by byakymyk** [comment]
It has reappeared - The issue is when Band Size is 1 - Skip Size is 1 - Speed is 1.  I believe it is not necessarily a bug but more of a choppy visual look only when Skip Size is 1.

**Comment by byakymyk** [comment]
I have found a work around by replace a Skip Size of 1 and Adding Black Colour instead.

**Comment by AzGilrock** [comment]
I haven't looked at the attachment but just based on your description my guess is we wouldn't change this because any change to the math would screw up all existing sequences.  I wrote the original algorithm for this effect.

**Comment by byakymyk** [comment]
That's fine - I found a work around that smooths it out - It is only this one setting and agree it wouldn't be worth it
