### ISSUE TITLE
DMX lights

### ISSUE THREAD

**Issue by Andyreynolds69** [smeighan/xLights#2024]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

when creating a new layout with DMX lights I posotioned them all at the same height and pointing in the same direction, all seperated by 100 front to back (z) so 
X: -900
Y: 230
Z: From 400 to -400 all seperated by 100
The issue seems to be that the z value is somehow interfeering with the beam lenght

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**when looking at in Layout and when running a sequence you cannot see the beam of light

**Screenshots**
![image](https://user-images.githubusercontent.com/63136518/79984512-46adee80-8477-11ea-8568-a3c18a6160ee.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version  2020.16 64bit

**Additional context**

[Carwash1.zip](https://github.com/smeighan/xLights/files/4516211/Carwash1.zip)

**Comment by keithsw1111** [comment]
I think this is fixed in .17
