### ISSUE TITLE
Check Sequence reports using a Subbuffer when it isn't.

### ISSUE THREAD

**Issue by Poporacer** [smeighan/xLights#2026]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I have a sequence that I was running the Check Sequence routine on and received several errors:

ERR: Effect on a model group using a 'Per Model' render buffer is also using a subbuffer. This will not work as you might expect.

Which is odd, because I rarely use the Sub Buffers. But I looked and there were several models that had an oversize buffer. I fixed all of them (I probably missed a few) and re-ran the Check Sequence and I still got the error. I looked at several of the errors identified and I could not see that there was a sub-buffer set? 
I can go into each effect and change the Render Style to default and then set the Render Style to the Per Preview and it works. 
If I select a group of effects, then Bulk Edit them to the Default Render style and save, they fall off the list. If I then go back and Bulk Edit the same effects to Per Model Per Preview, only the first effect (by time if that matters) is not on the list, the rest have returned. I can't find a way to fix them in a bulk format. 

**To Reproduce**
refer to attached sequence

**Expected behavior**
That you can bulk edit render styles and Buffers
**Screenshots**

**Versions (please complete the following information):**
 - OS:Windows 10
 - xLights version 2020.16

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
Here is the file:
https://drive.google.com/open?id=19K4hz3YvgePvfO2YmkM8vvLMI8l0CxoI
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
So this is a mixed bag. While there are some erroneously reporting the vast majority are correct. For example this error:

    ERR: Effect on a model group using a 'Per Model' render buffer is also using a subbuffer. This will not work as you might expect. Effect: SingleStrand, Model: Mini Trees Group, Start 0:00.875

	B_CHOICE_BufferStyle=Per Model Per Preview,
	B_CUSTOM_SubBuffer=-1.79x-3.57x101.39x103.57

That is a custom subbuffer ... it is close to 0x0x100x100 but close it not enough.

**Comment by Poporacer** [comment]
Thanks Keith! I knew that there were still several that were incorrect, but I wanted to leave some in the initial state so that you could duplicate the steps I took just in case you needed to. I was in the Zoom Room talking to Scott and he was looking at it at the same time you were and it was discovered that if you use set the Render Buffer to a full size buffer to several effects at the same time using the "apply to selected effects" the first effect will not have any setting saved for a sub buffer, but the rest of the effects will have a sub buffer set but with no actual buffer. Here is an example of an effect with the blank buffer:

`CopyFormat1	0	1	6	0	-1	NO_PASTE_BY_CELL
SingleStrand	B_CHOICE_BufferStyle=Per Model Per Preview,B_CUSTOM_SubBuffer=,E_CHECKBOX_Chase_3dFade1=0,
`
Just in case you wanted to know the root cause.

Thanks for your hard work.

**Comment by AzGilrock** [comment]
Effect settings are most likely optimized to leave out any settings that are the defaults.  We usually only show the settings that have been modified away from defaults.

**Comment by Poporacer** [comment]
Thanks Gil, Keith fixed the report so that they don't show up anymore, but I would think that changing a setting on several effects would be consistent among the effects? But it works now!
And Thanks for the work that you put into xLights as well!

**Comment by AzGilrock** [comment]
Well you really need to fully save a sequence and reopen it to compare the effect settings because that's when you'll see the result of all the optimization.  I could see the source effect being different because it doesn't need to change and then the other change when they go through the default optimization later.  I'm just guessing from what I remember about the effect setting logic.

**Comment by computergeek1507** [comment]
Looking at the code and some xml files, the "Bulk Edit" for video/picture paths and the buffer will set the setting map value to a empty string, I thought about changing the code to delete the map value instead but I didnt want to risk breaking anything.
