### ISSUE TITLE
Virtual Strings on f40pb for no reason

### ISSUE THREAD

**Issue by jefft0825** [smeighan/xLights#2027]
I have gone through and tried to find out why xlights keeps adding virtual strings for my candy canes and Rob V and I are stumped.

On port 17 - it goes flood 1 - candy cane 1 - candy cane 2 - candy cane 3
Port 18 - candy cane 4 - candy cane 5 - candy cane 6 

Check sequence shows everything is good - but anytime i try and daisy chain anything on the f40PB - it creates a virtual string even if they are the next prop start channel

Added a zip file of my rgb effects, network and keybindings
[Tell Xlights GITHUB.zip](https://github.com/smeighan/xLights/files/4554129/Tell.Xlights.GITHUB.zip)
![f40 outputs](https://user-images.githubusercontent.com/39816390/80639360-83558900-8a27-11ea-985b-95a67d679a26.PNG)
![xlights visualizer](https://user-images.githubusercontent.com/39816390/80639363-851f4c80-8a27-11ea-900b-ad089143c9dd.PNG)

**Comment by dkulp** [comment]
This is working as designed...   The FPP based controller will always use virtual strings for each model.   There isn't really a reason to NOT do that with FPP.

**Comment by jefft0825** [comment]
Nothing to worry about then?

**Comment by dkulp** [comment]
Correct.  It's working properly.    Ideally the F16v3 configs would do the same, but due to limitations in the F16v3, we cannot and have to merge things together.
