### ISSUE TITLE
VSA import crash

### ISSUE THREAD

**Issue by smartone1971** [smeighan/xLights#2037]
When I try to import a VSA files it crashes.
I am on a windows 10 computer, using xlights 2020.18(and did it on .17 also)
no matter how I set up the model under the skull configuration it crashes when it tries to render it.
[xLights_dbgrpt-18768-20200506T005634.zip](https://github.com/smeighan/xLights/files/4590380/xLights_dbgrpt-18768-20200506T005634.zip)
[Haunted Manison skull 1.zip](https://github.com/smeighan/xLights/files/4590382/Haunted.Manison.skull.1.zip)

**Comment by keithsw1111** [comment]
I fixed this yesterday and sent you the files. Not sure why you are raising it again?

**Comment by smartone1971** [comment]
because it is still doing it with the one you sent to me!
