### ISSUE TITLE
Universe/Channel Tool for Non Supported Controllers

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#2042]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to calculate & visualize the port to universe/absolute channel mapping for manual entry into controllers.  This could be due to using a controller that isn't natively supported in xlights.

By "calculate" I'm asking for the user to be able to enter the starting port (optional..can assume 1), number of ports,  starting universe, starting channel (or absolute numbers), number of pixels per port, and number of ports.  This could be something under the tools menu that only provides this as "informational" data in a pop-up window.

By "visualize" this could be a checkbox on the controller visualizer that would enable the display of universe information (start & stop) below the pixel count on each port.  This may not be feasible on unsupported controllers or on controllers where port assignments aren't made but we've needed to look at channels more than once and this view may be easier to read for some than looking in model layout.

**Describe alternatives you've considered**
Used one of our controllers that shows this detail on the WebUI after entering the number of pixels.  Unfortunately some controllers didn't show the stop channel so it wasn't as automatic as we hoped.

I wrote a quick and dirty python script that'll spit out a table given start port, port count, start universe/channel, and pixels per port.  This doesn't help anyone other than myself however as it's not on a website.

**Additional context**
This issue came up on a zoom call where a user had a custom matrix.  14 ports with ports 1-13 having 3 strings but port 14 had 1 string.  Jon D helped with the process custom model export/import/modification to make the matrix fit but we were still left with manually assigning the start channels.  Took us a little bit to work out the math for this.

**Comment by keithsw1111** [comment]
While I dont totally get this I am also not keen on it. It sounds really complex and I think we already have a better way.

We have put the controller specifications into the controllers folder making it easy to add new controllers including most config by just adding an XML file.

We are happy to add xml files for other suppliers ... but we only built the ones we have access to.

**Comment by keithsw1111** [comment]
After discussing this I have added the port tooltip to the visualiser which I think does everything required.

**Comment by deplanche** [comment]
Paul - one thing that will give you the same information that you were talking about above, is in the original model for the matrix (not the custom model), click on the individual start channel check box, and it will give you the start channels.  If you adjust the start channel to either absolute or universe/start channel before you click the box, all of the following ones will be in the same format.
