### ISSUE TITLE
Star Model - 2 layers with same number of pixels overlap each other

### ISSUE THREAD

**Issue by jefft0825** [smeighan/xLights#2049]
Not sequence to package = adding RGB and Networks under zip file

GE 460 Star - https://gilbertengineeringusa.com/products/star-46-460?_pos=11&_sid=7a708481b&_ss=r

It has 2 layers that are the same and it overlaps them in the wiring view - cannot tell how to wire this

[Star Issue.zip](https://github.com/smeighan/xLights/files/4631598/Star.Issue.zip)

![image](https://user-images.githubusercontent.com/39816390/81997169-9e71ec80-9614-11ea-8980-a1766b4e9726.png)
![image](https://user-images.githubusercontent.com/39816390/81997197-b184bc80-9614-11ea-8715-7483c7f09b9f.png)

**Comment by jefft0825** [comment]
Also doesnt seem to like anything more than 9 layers

**Comment by jaydonoghue** [comment]
Seeing the same issue (same type of model, different pixel counts on last layers). You can see the pixel #s overlaid on top of each other

![image](https://user-images.githubusercontent.com/17279178/82003792-3e3c7400-962f-11ea-9e5f-b1be1d0a8ae4.png)

**Comment by keithsw1111** [comment]
An interesting rabbit hole. Hard to believe no one has ever raised this before as this was fundamental to the algorithm for generating the star. I have rewritten the star routine but for maximum backward compatibility it will only kick in on stars where more than one layer is the same size.
