### ISSUE TITLE
Deleting Prop Make xlights crash with no bug report

### ISSUE THREAD

**Issue by jefft0825** [smeighan/xLights#2054]
[Deleting Prop Issue.zip](https://github.com/smeighan/xLights/files/4645696/Deleting.Prop.Issue.zip)

Trying to replace singing bulb 1 with a version where i dont have to have jumpers - anytime i go to delete singing bulb 1 or replace the model with another model, xlights closes down

created a new sequence to package my rgb and networks

**Comment by keithsw1111** [comment]
I already have this one fixed for .21
