### ISSUE TITLE
Request for a Dark Theme in xLights

### ISSUE THREAD

**Issue by hearmstinj** [smeighan/xLights#2060]
**Is your feature request related to a problem? Please describe.**
Using xLights for multiple hours at a time causes strain on the eyes due to its light theme. Most editing software nowadays have a dark theme available (e.g. Adobe Premiere, Visual Studio, Adobe Aftereffects, 3D Max, Blender) which heavily reduces the strain on the eyes over time.

**Describe the solution you'd like**
An option to enable a "Dark Mode" or "Dark Theme" in xLights which will change the UI elements to use a dark background color with a light foreground color.

**Comment by computergeek1507** [comment]
This is not going to happen anytime some see #1547 for more details.

**Comment by djulien** [comment]
FWIW, I recompiled xLights 23.x (various recent versions) from source code on a Ubuntu desktop that is using a dark theme, and now my compiled copy of xLights is using dark mode.  I didn't make any source code changes for dark mode - xLights just started using dark mode.  YMMV - maybe there is a platform setting in the Makefile that caused this.
