### ISSUE TITLE
String Limit In Custom Models

### ISSUE THREAD

**Issue by dragonzpneuma** [smeighan/xLights#2063]
I have recently created a custom matrix model.  I used the custom model feature since the matrix is of an oblong shape.  The matrix is rather large (7,200 pixels) and I want to spread it out over 48 ports on one F16-V3 with 150 pixels on each port.  This would normally be easily done however I've found that the custom model prop is limited to 30 strings.  I am aware that I could split it into two models, or even increase the pixel division to 300 pixels per port, but those are just workarounds.  My special request is to increase the max strings on the custom model to at least 48 strings.  Thank you very much for your time.

**Comment by computergeek1507** [comment]
Fixed with 47f52cebb5c0c2cdb23e8198b545c92eddb4fed1
