### ISSUE TITLE
Some effects not showing up in visualizer

### ISSUE THREAD

**Issue by DanJacobsen** [smeighan/xLights#2064]
[10 Jesus Oh What A Wonderful Child short 2020.zip](https://github.com/smeighan/xLights/files/4672115/10.Jesus.Oh.What.A.Wonderful.Child.short.2020.zip)
ed to video this, but the visualizer screen won't stay up for visual on the recorder.   What I am running into is one I haven't seen before--some of the effects obviously in the sequencer (e.g., the minitrees' effects) are not showing when I preview the sequence in the visualizer screen.   I uploaded the zip of this file; maybe you can make it do what I am seeing.  Not sure how to slay this one.  I have tried doing "update", "save", and "render"; none seem to work consistently.  THANK YOU.

**Comment by DanJacobsen** [comment]
I found this on a subsequent file opening-if i "touch" each effect by highlighting it in the sequencer, then each effect works fine.   This seems to be limited to the minitree props/models for some reason.  I have checked the models and they are all correctly mapped in XL.

**Comment by keithsw1111** [comment]
Concentrating on the garlands effects ... when I click on the garland effect nothing shows up ... but as soon as I change something (anything) it does. Not sure why yet.

**Comment by dkulp** [comment]
I now know what's going on and have the start of a fix....  I'll finish up tomorrow.

**Comment by keithsw1111** [comment]
I will hold the release then.

**Comment by DanJacobsen** [comment]
Thank you for all you do !!!
Dan J

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
