### ISSUE TITLE
Red Cross disappears when changing X or Y offset

### ISSUE THREAD

**Issue by OzAzgithub** [smeighan/xLights#2067]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When adjusting the center point for groups in the Layout tab, the red cross disappears when you increase or decrease the X or Y offset.

**To Reproduce**
When adjusting the center point for groups in the Layout tab, the red cross disappears when you increase or decrease the X or Y offset.

You then have to select a different group, then re-select the original group you were trying to change to see where the red cross has moved to.
 
Does this for all and any group, completely reproducible every time

**Expected behavior**
Red cross should move on the screen in X or Y direction as you increase or decrease offset

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.21

**Additional context**
Don't recall this happening in previous versions (before 2020.18)

**Attachments**

**Comment by keithsw1111** [comment]
This is already fixed.
