### ISSUE TITLE
Crash with no folder set 4.0.20

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#207]
I restructured my Nutcracker sequence folders so when I installed the 4.0.20 version upgrade Nutcracker.xLights presented a window stating that the sequence folder no longer exsist and clicked 'ok'. Then I accidentally clicked on the 'Sequencer' tab before clicking the "select show directory" icon and the attached bug report was generated in the 'C:\Users\Tom\AppData\Local\Temp' folder.
This crash happens only with the 'Sequencer', and 'Convert' tabs.

The crash file is here:https://dl.dropboxusercontent.com/u/28041968/Nutcracker%20Testing/xLights_dbgrpt-5356-20150414T153816.zip

**Comment by smeighan** [comment]
will be fixed in 4.0.22

**Comment by MrChristmas2000** [comment]
Still broken in  4.0.22.

**Comment by AzGilrock** [comment]
Yeah I didn't get the memo. :)
Plus this looks to be a minor low priority thing.  It falls into my "hey doc it hurts when i do this" category.

**Comment by MrChristmas2000** [comment]
Yeah, sometimes the memos get filed in the wrong place .LOL

I am probably the only one that has seen this happen. :)

**Comment by stevegiron** [comment]
Hello, I'm helping sort the issues and determine which issues are still valid. 
As of May-14 we are version 4.0.31. Is this issue still occurring?

**Comment by MrChristmas2000** [comment]
Ran a test and it looks like this definitely has been fixed. I will close the issue.
