### ISSUE TITLE
Advatek boards not valid

### ISSUE THREAD

**Issue by magish01** [smeighan/xLights#2076]
Advatek controllers when used in expanded mode show as expanded outputs not valid.

When opening xLights, it shows that Advatek MK4 II start channels (1-8)can not be calculated even though the Advatek board in expanded mode allows 8 channels.  Normal mode uses 4 channels.

To reproduce:  
1:  Open xlights
2:  1st popup "Could Not calculate start channels for models" appears.
3:   Hit OK
4:  When xLights opens, go to controllers tab and it shows expanded mode channels in red 

Screenshots in Dropbox: https://www.dropbox.com/sh/8kkbixsnga754wa/AAAmWAgewQUOGvf_54tHZ4a1a?dl=0

Version:
2020.22

**Comment by keithsw1111** [comment]
Can you attach your show files so we can reproduce and test

**Comment by magish01** [comment]
Keith,
Hope this is what you need.

Thanks,
Dave

**Comment by keithsw1111** [comment]
You didnt attach anything.

**Comment by magish01** [comment]
Keith,
Files were attached but apparantly did not go through, so I am sending again as files, zipped files and using a second email program.  Hopefully it will make it this time.
"You can believe everything on the Internet" - Abe Lincoln

Dave Nelson
magish@sbcglobal.net 

    On Saturday, June 6, 2020, 04:51:00 PM PDT, Keith Westley <notifications@github.com> wrote:  
 
 


You didnt attach anything.

**Comment by magish01** [comment]
Keith,

Files were attached but apparantly did not go through, so I am sending
again as files, zipped files and using a second email program.  Hopefully
it will make it this time.

**Comment by keithsw1111** [comment]
Replying to github emails with attachments does NOT add them to the case.

**Comment by magish01** [comment]
Sorry, this is my first time trying to submit a problem.  How do I get the
files to you.

**Comment by magish01** [comment]
Files are attached.
https://www.dropbox.com/sh/p7untskelxfdyau/AABSQfMvA4jvMxbcgwenpJEUa?dl=0

**Comment by keithsw1111** [comment]
Ok ... it seems to be ok now. See .24 release when it comes out.
