### ISSUE TITLE
Add support for KiNET

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#2077]
In addition to e.131 and Artnet add KiNET protocol as output option on Ethernet controllers. KiNET is for Philips RGB systems.

**Comment by keithsw1111** [comment]
If you really want this you need to help us locate a protocol specification ... all i can find is

#  my $strange_ck_header = join("", 
#                               '0401dc4a',     # magic, L 
#                               '0100',         # ver, H
#                               '0101',         # type, H
#                               '00000000',     # seq, L
#                               '00',           # port, B
#                               '00',           # padding, x
#                               '0000',         # flags, H
#                               'ffffffff',     # timerVal V, L
#                               '00',           # uni, B
#                              );

And that is just not enough to implement it properly.

https://opendmx.net/index.php/KiNET
https://github.com/vishnubob/kinet/blob/master/kinet/kinet.py (more here but its Python ... yuck)

**Comment by idleup** [comment]
Okay, let me see if I can get it through the manufacturer.

**Comment by keithsw1111** [comment]
The best info I can find is a reverse engineering by https://github.com/OpenLightingProject/ola/tree/d1010976c47de23dc6031749179f8d92596b7e8d/plugins/kinet

It is not a full implementation so without a device it is almost impossible to test so any build would be entirely speculative.

**Comment by keithsw1111** [comment]
This also has some links to a number of other attempts: https://github.com/OpenLightingProject/ola/issues/1544

**Comment by keithsw1111** [comment]
Reading through all of this I dont think this can be implemented correctly without a device to test with. There are clear differences across the code examples with possibly multiple protocol versions. It also talks about universes, ports and data with no way for me to know what those terms mean in this protocol.

**Comment by idleup** [comment]
I am in contact with Color Kinetics on two different fronts about getting dev documentation on the protocol and samples using C++. I will let you know what I hear as they are sometimes very slow to respond... I know they have something because MADRIX implemented KiNET. I can also see about some test hardware to send you.

**Comment by Dewb** [comment]
Hi, I'm the author of one of the "other attempts" linked in the OLA issue. I'm currently working on a Rust implementation of KiNET that tries to capture everything we know about the undocumented protocol, and I have access to some hardware to test with. Would be happy to compare notes.

**Comment by keithsw1111** [comment]
@Dewb any guidance you can provide would be appreciated.

**Comment by keithsw1111** [comment]
Closing due to no response.

**Comment by peternewman** [comment]
@keithsw1111 it might be worth you adding an OLA output so people could send via the various random protocols and dongles OLA supports, save you re-inventing the wheel for all those niche ones.

Conversely there might be some interest from some OLA users in an input plugin to your system (although I don't really know enough about it to understand how relevant/possible that is), as you seem to tick off lots of the more niche Christmas based stuff. Someone added Renard to OLA but that's about as far as we've gone in that direction.

**Comment by keithsw1111** [comment]
OLA does not seem to support all platforms so I have looked at it but not considered building it in. To build something in it generally needs to work cross platform and be simple to install. I have looked at other protocols as well that only had drivers for windows or required significant amounts of platform specific code to work and rejected those as well.

**Comment by peternewman** [comment]
> OLA does not seem to support all platforms so I have looked at it but not considered building it in.

Which platform are you referring to? All of OLA works on Linux and OS X as far as I'm aware. The vast majority of it (apart from some of the serial stuff) works on Windows and we also compile on various *BSDs (Net, Free, Dragonfly and possibly some others).

> To build something in it generally needs to work cross platform and be simple to install.

We're in apt-get, AUR, Homebrew and Macports.

There are a number of other tools which offer us for output, or use us as their main output including QLC+, Midimonster and various live coding things. Obviously it's entirely your choice.

**Comment by keithsw1111** [comment]
But its not native windows according to the documentation.

**Comment by peternewman** [comment]
> But its not native windows according to the documentation.

Glacial response, I'm not sure which docs you were looking at, but we've got a mingw32 build where quite a few of the IP based plugins work and a handful of the FTDI ones too:
https://github.com/OpenLightingProject/ola/blob/master/README.mingw32
