### ISSUE TITLE
Xlights vs. Radig ArtNet 4096 Kanal LED Pixel Controller 

### ISSUE THREAD

**Issue by harueg** [smeighan/xLights#2078]
Hi

First steps with xlights. 
I've set up the controller according to the manual. artnet, 8 universes 0- 7
IP controller 2.0.0.66  Forced local IP 2.0.0.1 on an intel ethernet card.
With test function I can do the RGB cycle and it works for about 2 seconds and the ethernet gets killed.
No more status led on the RJ45 connectors. Works again for 3 seconds after powercycling the contoller.
I had the same issue with my standard network.
The controller works perfectly with Jinx!.
Win 10 1709  xlights 2020.22 x64

Thank you

Harald

**Comment by harueg** [comment]
Mea culpa

It was a PSU problem, the master fader in Jinx! was on 50%, that's why it worked there.
with 100% the voltage dropped to 3.18 V on the controller. Definitely not enough.

**Comment by keithsw1111** [comment]
No biggies ... but you really should try to explore your issue on the forums/fb/zoom before raising things to ensure it isnt something obvious. It helps to keep the noise down.
