### ISSUE TITLE
App will crash when importing duplicate timing tracks.

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#208]
When importing a timing track that already has been imported (inadvertently of course) into a sequence, the app will crash.

**Comment by AzGilrock** [comment]
I thought someone reported this before and I tried it back then and couldn't get it to crash.  I'll try again tonight if I don't forget.

**Comment by AzGilrock** [comment]
I can't duplicate this.  Do you mean you import the exact same audacity text file twice?  When I tried the second attempt didn't add a new layer but the existing timings with that name disappeared but I clicked the radio button and they reappeared.  I saved and the XML only showed one set of timings in addition to the New Timing layer.  I might need that import file and if that doesn't crash maybe all the files involved.

**Comment by stevegiron** [comment]
Yes on the same text file twice. I tried this AM and no crash. One item to note is that with XL3 and XL4, it is prone to intermittent crashes when the system memory is low. Yesterday's crashes were near the end of my day with many apps open and high mem utilization.

**Comment by AzGilrock** [comment]
So don't load the same file twice and close some programs.  Free up some disk space.  Even if you run out of memory windows should be using a swap file.

**Comment by stevegiron** [comment]
No longer an issue. Closing ticket.
