### ISSUE TITLE
HSA FSEQ v1 error message

### ISSUE THREAD

**Issue by JBoards** [smeighan/xLights#2080]
Error message pertaining to FSEQ version selection option no longer resides in this location.

![103586554_10223397429068575_8071649891596515167_n](https://user-images.githubusercontent.com/50759694/83975391-9d954900-a8a8-11ea-9391-e5a46956b201.jpg)

**Comment by computergeek1507** [comment]
this is a "bug" in Joe's HSA app not xLights, we do not maintain his app
