### ISSUE TITLE
Opening sequence results in no effects imported and original .fseq file deleted

### ISSUE THREAD

**Issue by jayceecee** [smeighan/xLights#2084]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
A few weeks ago while preparing for the 2020 season I copied all my sequences into my "2020" folder , fixed all the file locations , rendered and saved.
I tested them and all were working fine.

Now , when I open one of these sequences ( or any of the copies I have from Dec 19) the sequence opens however there are no effects shown and in the sequences folder the .fseq file is gone.
To rectify it seems that I would have to Create a new Sequence , import the backup copy 

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. xLights -> File - > Open Sequence -> select .fseq file
2. xLights doesn't show any effects
3. Right Click on Model List -> Show All Effects = no effects
4. Render / Save and original sequence is gone and a small sized .fseq file is created.

**Expected behavior**
1. The .fseq file should open and all existing effects should be shown.
2. The existing .fseq file should NOT be deleted , **until** the user either Renders or Saves.
 - the way it is currently there is no recovery of the sequence other than from backups.
 - discarding changes while exiting xLights does not recover the original file..it's gone..

**Screenshots**
Google Drive folder with packaged sequence , log's & screenshots
https://drive.google.com/file/d/11ve3xlniucTqMEKEObjiuBGuTbLTcUEs/view
**Please ping me for access to the share folder**

**Versions (please complete the following information):**
 - OS: [Mac 10.15.5]
 - xLights version [2020.23]

**Additional context**
Was working as expected in 2020.14 , used to convert all my sequences from 2019 to 2020 folder and have updated all version since.
Only noticed this behaviour in this version however it's now reproducible in all versions I have for 2020.

**Attachments**
Google Drive with sequence , log's & screenshots
https://drive.google.com/file/d/11ve3xlniucTqMEKEObjiuBGuTbLTcUEs/view
**Please ping me for access to the share folder**

**Comment by keithsw1111** [comment]
This is a side effect of the xsq change and your unusual way of opening the sequences. Opening the fseq is not common and xlights tries to compensate for that by trying to find the xsq file but your files are still xml. I will fix it but for now just open the xml files and in future open the xsq files.
