### ISSUE TITLE
Effect has been deleted on Wholehouse zone but still shows on 1 prop

### ISSUE THREAD

**Issue by Roboman2582** [smeighan/xLights#2087]
I had a Spirals effect on the "whole House" zone but deleted it. After deleting the effect it still shows the effect only on 1 prop witch is a GE snowflake. I can seem to get rid of the effect on this flake even after render. Its on the mark 1:42 and last for approx 8 sec after.

**Comment by Roboman2582** [comment]
[Please TEST.zip](https://github.com/smeighan/xLights/files/4764723/Please.TEST.zip)

**Comment by AzGilrock** [comment]
I'm not home to look but I can view the XML and you have Strand and Node level effects on your GE FLAKE's so its most likely effects still there that you didn't show because you didn't expand to that level.  Just right-click the row heading and Show All Effects and you will find them.

**Comment by Roboman2582** [comment]
Hello... I had to go and delete all effects from the node level to fix this...

 When I deleted the effect from the "Wholehouse" it should have deleted it from all props in the group. Never had that happen before. Any idea why it didn't delete it from this 1 prop? Just trying to avoid issues in the future now  :-)

**Comment by AzGilrock** [comment]
Its totally different effects.  You can have effects on a model group, a  model, a sub-model, a strand, and a node and they are all independent effects.  The lower level effect override the whole house effect during their time periods.

**Comment by Roboman2582** [comment]
Thank You very much for your time!
