### ISSUE TITLE
Still crashes after 4.0.21; Help/about says 4.0.20

### ISSUE THREAD

**Issue by wdmilkie** [smeighan/xLights#209]
1) download and install 4.0.21; says it installed 4.0.20 in HELP
2) readme file still says 4.0.18

3) unfortunately, still crashes

**Comment by smeighan** [comment]
can you try 4.0.22 and see if this still happens. if ti does, can you film the screen (use screencastomatic or video from your phone).

**Comment by smeighan** [comment]
please dont put two issues into one ticket. For example, the label has been corrected but maybe we are working the crash.

**Comment by wdmilkie** [comment]
Both of my issues are now working, fixed

1) delete timing does NOT crash in .22 version

2) right click on model, and export does NOT crash anymore

great job, thanks guys
