### ISSUE TITLE
Unable to resize popout windows linux

### ISSUE THREAD

**Issue by TechplexEngineer** [smeighan/xLights#2093]
**Describe the bug**
The last working version is 2019.74.
When windows such as the Model Preview are detached (popped out) from the main xlights window there is a small drag corner which allows for the window to be resized. As shown in this image showing version: 2019.67
![Selection_493](https://user-images.githubusercontent.com/175873/84577331-68e22f80-ad89-11ea-803a-e11b781ced36.png)

The next version 2020.1 seems to be missing the handle in the corner of a popped out window which makes the window impossible to resize.

![Selection_494](https://user-images.githubusercontent.com/175873/84577470-6d5b1800-ad8a-11ea-86c3-08bcbb88dbf8.png)

**To Reproduce**
Use the app image builds on ubuntu based Linux https://www.adebenham.com/xlights-linux/

**Expected behaviour**
Ability to resize windows that have been popped out

**Screenshots**
See above

**Versions (please complete the following information):**
 - OS: Linux Mint 19.1 Tessa - Based on Ubuntu 18.04
 - xLights version
    - 2019.74 last working version
    - 2020.1 first broken version

**Comment by Kosh42** [comment]
Same issue here. Any window dragged out cannot be resized in 2020.26 Linux Appimage. Behaviour is as expected in Windows 2020.26.

**Comment by dkulp** [comment]
This requires updating to the latest wxWidgets "master" code.    It's fixed in the latest wxWidgets.

**Comment by TechplexEngineer** [comment]
This seems to be fixed in 2020.29
