### ISSUE TITLE
Crashing in Visualizer

### ISSUE THREAD

**Issue by brianbarrell** [smeighan/xLights#2095]
When in Visualizer.  Moving or adding a prop xLightts will freeze with a blue spinning wheel and become unresponsive and eventually crash without a crash log.  Just shuts down.  The location that you are trying to move something to will highlight in blue and stay blue. This is in version 2020.24 and did not happen in previous version.  I can recreate every time.  I do not have a sequence open, so it is not sequence related.

Windows 10
2020.24

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/4776938/xLightsProblem.zip)

**Comment by SBlackCrestron** [comment]
I'm experiencing the same thing since updating to 2020.24.  It locks up Xlights if I try and move models in the Visualizer.  Eventually the program crashes. 
 
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/4789407/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
I think I have this fixed for .25
