### ISSUE TITLE
Output processing not turning off light when show ends

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#2098]
im not 100% sure that this is how this is supposed to work or if its a bug so sorry if I'm missing something here,

I added an "Add Set" so I can have a channel turn on when the show starts and goes off when the show ends, added the channels, value and so on, started the schedule and the 1 pixel I added turns on all white as it should but when the show ends and the output to lights is off, that 1 pixel remains on, is that the way it should be or should the LED turn off that I set in output processing? I thought once the output was off the output processing would stop also. 

this is on my mac running 10.15.5
XSchedule - 2020.15 (no newer update has been released yet for mac)

![Image 6-14-20 at 8 44 PM](https://user-images.githubusercontent.com/40632971/84608480-b097b280-ae80-11ea-85cd-3c4fbb9ffaea.jpg)

**Comment by keithsw1111** [comment]
That sounds like expected behaviour. To turn it off at the end you would need your controllers to blank or as previously indicated you should instead be using event playlists to achieve what you are after.

**Comment by bchiaino** [comment]
exactly, thank you keith, I used other methods, I forgot I even posted this or I would've closed it.
