### ISSUE TITLE
crashes when add timing mark to sequencer, then click delete

### ISSUE THREAD

**Issue by wdmilkie** [smeighan/xLights#210]
when I place a timing mark, and try to delete it by clicking "delete" key, crashes

**Comment by AzGilrock** [comment]
I was about to say this works fine for me but I tried and it crashed.  I swear I was deleting timing marks in the past so I'm not sure what change caused this to creep in yet.

**Comment by wdmilkie** [comment]
I'm sure this XL4 project is takes a considerable amount of time, and
lottssss of code,

Besides, if you're trying to make it idiot proof, I'm your man!

thanks for all your work; this must be a labor of love and fun, and I'm
sure everyone who uses it
appreciates it very much

**Comment by AzGilrock** [comment]
I'm not sure if Dan has time to look at this since he's leaving for vacation soon.  Since I'm sure it was working in an older version It would help me out if someone could track down which version this broke in then I can review what changes went into that release.

**Comment by wdmilkie** [comment]
the first version I noticed it was 4.0.18 and the 4.0.21 which still says
4.0.20

I don't remember seeing it in 4.0.16

**Comment by wdmilkie** [comment]
I don't know if this helps, but when it crashes, a message pops up saying
it sent an error report back to XL4 somewhere; NOT a Windows report but
something from the XL4 team

**Comment by AzGilrock** [comment]
Nothing gets sent anywhere to us.  It saves a crash report to your PC.  Don't worry Sean already tracked down which version induced the crash and Dan fixed it.

**Comment by BobinWV** [comment]
Works for me 4.0.16

**Comment by BobinWV** [comment]
Works for me in 4.0.17  add and delete

**Comment by wdmilkie** [comment]
I think it worked ok on 4.0.16(don't remember having any problems), never
tried .17, but .18 and .20(.21) it failed
Tried it on 2 different computers, same results

**Comment by AzGilrock** [comment]
Did nobody read my last post?  I told you Dan fixed it.

**Comment by smeighan** [comment]
dan kulp fixed this in 4.0.22
