### ISSUE TITLE
DMX freeze

### ISSUE THREAD

**Issue by WolfeK77** [smeighan/xLights#2101]
I had occasional lock up using .22 and .23 but on the current release (.24) it's nearly impossible to program DMX.  With every change of the slider on a channel the program freezes.

**Comment by keithsw1111** [comment]
There is no information here that is useful. Either add information or the ticket will be closed.

**Comment by WolfeK77** [comment]
I will try to put a video together to demonstrate. Will a report show freezes in the software?


Sent from AT&T Yahoo Mail for iPhone


On Saturday, June 20, 2020, 10:21 PM, Keith Westley <notifications@github.com> wrote:




There is no information here that is useful. Either add information or the ticket will be closed.

**Comment by keithsw1111** [comment]
I need a packaged sequence and a video of you using that sequence to hang the software.

**Comment by AzGilrock** [comment]
Closed due to lack of response
