### ISSUE TITLE
Manual Entry of Timing Duration

### ISSUE THREAD

**Issue by ssharpe83713** [smeighan/xLights#2106]
V2020.24
When right clicking an effect on the sequencer and accessing the Timing menu,  the duration can be changed with the up and down arrows, but manually entering a duration in the cell has no effect.

**Comment by computergeek1507** [comment]
Did you hit the tab or enter key after changing the value?

**Comment by ssharpe83713** [comment]
Yes. After a manual entry, I pressed Enter and noted the duration didn't
change the effect. I returned to the Timing menu to find the Duration value
unchanged. After several attempts, I just used the arrows.

**Comment by computergeek1507** [comment]
Can you make a video or gif, it is working correctly for me.

![timing](https://user-images.githubusercontent.com/2293065/84968990-bb9f4c80-b0e5-11ea-9352-9caee8c27249.gif)

**Comment by ssharpe83713** [comment]
Sure. I'll do that tomorrow!

**Comment by ssharpe83713** [comment]
BTW, I forgot to mention the OS is Mac OSX...

**Comment by ssharpe83713** [comment]
In your demo video, you are changing the Start and Stop times and watching
the Duration change. Instead, only change the Duration value.

**Comment by ssharpe83713** [comment]
Here's the video of the issue...

Mac OSX 10.13.6
xLights 2020.24

Don't change the Start/End Time values; just work with the Duration value.
Arrows work; direct entry does not.

**Comment by computergeek1507** [comment]
I do not see your video, I believe you need to manually attach the file or link via github website. Do not attach it to a email response.

**Comment by ssharpe83713** [comment]
Here's the issue video.  Please note that I'm only changing the Duration value.  There's no issue when the Start/End values are changed.

[issue.mov.zip](https://github.com/smeighan/xLights/files/4800481/issue.mov.zip)
