### ISSUE TITLE
Preferences not saving for Effect Assist Window

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#2108]
I  seem to run into the issue of the Preferences for the Effects Assist to set itself to "auto toggle".   No matter how many times I try to save it to "always off", xLights won't save it to my requested settings.  I've tried saving the change by clicking OK and closing xLights.  When I reopen xLights, it resets back to "auto toggle".  

![image](https://user-images.githubusercontent.com/12719816/85170912-10ed7200-b23c-11ea-853d-1a2e64a72f4d.png)

**Comment by keithsw1111** [comment]
Try again in .25 ... there was a bunch of weirdness with effect assist and perspectives being loaded. In all the scenarios I tested it works large as i expect. The only possible anomally i can see is in toggle mode it does not disappear if you click on a toolbar item that does not require it ... but it then does disappear if you drop that effect. One could argue it could disappear earlier
