### ISSUE TITLE
Group stops working after clicking on bad effect

### ISSUE THREAD

**Issue by jstorms** [smeighan/xLights#2111]
Issue: Group stops working after clicking on an On/Off effect that isn't working. 

Steps to Reproduce:

- Start xLights 2020.25 64bit
- Load Candycanylane sequence
- Locate Group "_TYPE WHT STRINGS"
- Note at this point adding an "On/Off" effect works. The full group turns on and off as expected. Example: I added the on/off effects from 1:05.00 to ~1:22.500.
- Note this group won't play On/Off effects from earlier saves (see ~2:33)
- Now I left click on one of these non-working "On/Off" effects (see ~2:33)
- Next I add a new On/Off effect to this group and this newly added effect does not work. Seems to inherit whatever is wrong with what was loaded from an earlier save.
- Reloading the sequence does not help.
- Restarting Xlights seems to reset the problem.
- I restart Xlights, reload Candycandland, then I can add "On/Off" effect to "_TYPE WHT STRINGS" and it works until I left-click on one of the bad effects. From the point where I left-click on one of the "On/Off effects" from an earlier save it stops working.

The non-working effects were added sometime pre .23

Test repro included at: https://drive.google.com/file/d/1zcgpd88Ujrzot8lKy7Z10JSIVKG8C5lw/view?usp=sharing
[2020_MUS_CandyCanLane_groupproblem.zip](https://github.com/smeighan/xLights/files/4810223/2020_MUS_CandyCanLane_groupproblem.zip)

**Comment by keithsw1111** [comment]
This is because your Layer blending is set to 2 is unmask.

When you click on an effect and then drop the same effect it inherits the settings of the prior effect.

If instead you had clicked on a different effect then dropped the on effect it also would have worked ok.

There is no bug here.
