### ISSUE TITLE
Tree Model Wiring Direction

### ISSUE THREAD

**Issue by jonash326** [smeighan/xLights#2113]
I am interested in having a checkbox option in the model options for the Tree model that enable wiring to be vertical (default) or horizontal (box checked). This change would make the tree model much more versatile and usable for many props that are currently difficult to recreate using other models. Thanks Dev's!

**Comment by priemd** [comment]
Sorry but I have to ask size of tree you have in mind with horizontal wiring and your plans for turning horizontal strands into something that reflects a tree?  For anything other than maybe a mini tree I would guess 99% of people use straps running vertically.  So yeah now I’m curious why you just wouldn’t use vertical straps and want a horizontal option?

**Comment by computergeek1507** [comment]
I think the use case is then you could use the tree model for a tunnel with the wiring following each arch of the tunnel.

**Comment by AzGilrock** [comment]
Any use case could be modeled with a matrix so we are really just talking about a nice to have of showing it "pretty" in the GUI.  Anyone building a tunnel probably shouldn't sequence it as per preview anyways so they are really sequencing to a matrix anyways.

**Comment by jonash326** [comment]
I might suggest even making a completely new model for a tunnel, as it is a very common prop. It would be almost an exact duplication of the tree model (code wise), except some of the default values would be different like: 180 degrees around, rotated 90 degrees, and horizontal wiring. This would save tremendous time having to use 200 arch models and space them correctly. Also, to Gil's point, I think there is huge advantage to having a 3d tunnel vs sequencing. on a matrix. Thanks to our awesome dev team!

**Comment by AzGilrock** [comment]
Why wouldn’t the 3 or 4 people that build tunnels just group arch models...I’ve actually done it before you can model and group it in under 10 minutes.

**Comment by merryoncherry** [comment]
Apparently I overlooked this issue when I opened #3258.  This would appear a duplicate that could be closed as completed.
