### ISSUE TITLE
Xlights hangs when I select the layout or sequencer tab

### ISSUE THREAD

**Issue by scottishsurfer** [smeighan/xLights#2114]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Xlights crashes when I select the layout or sequencer tab
Version 2020.26 (But I tried installing older versions)  I bet it's a config issue.

**To Reproduce**
Open xlights, select any of my show folders, or even a new one.  Select any tab, just hangs.

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
Windows 10
xlights 2020.26
 - xLights version [e.g. 2019.37]

I have it working on a different computer with the same show folder.  It's always worked on my main one (the one I'm having issues with).

**Attachments**
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/4829596/xLights_l4cpp.log)
https://www.dropbox.com/s/rzgwcv0zsirxivx/wow.jpg?dl=0

**Comment by scottishsurfer** [comment]
https://www.dropbox.com/s/xmj6d7cbvxixy4f/Trolls%20Wanna%20Have%20Good%20Times%20-%20HD.xsq?dl=0

**Comment by computergeek1507** [comment]
Can you got to Tools-> Package Sequence and attach the resulting zip file. If it's too big to attach put it in dropbox or Google drive or whatever and share the link here.

**Comment by scottishsurfer** [comment]
https://www.dropbox.com/s/c7mfphjpt3glq1e/xLightsProblem.zip?dl=0
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/4829717/xLightsProblem.zip)

**Comment by scottishsurfer** [comment]
Keith told me to reinstall the video driver which I did.  This solved my issue.  Not exactly sure why installing the same driver worked, but it sure did.  Thanks guys.
