### ISSUE TITLE
Pinwheel Effect Bug With Single Arm

### ISSUE THREAD

**Issue by marklancer** [smeighan/xLights#2116]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When using the Pinwheel effect with a single arm in the clockwise direction traces of an apparent second blade appear.  

**To Reproduce**

Please see the attached sequence.  The first pinwheel effect in the CCW direction works as expected.  The second pinwheel effect in the CW direction shows the traces of a second blade.

**Expected behavior**
Only a single blade should appear when 1 arm is selected.

**Versions (please complete the following information):**
 - Windows 10 
 - xLights version 2020.26

[Pinwheel Bug.zip](https://github.com/smeighan/xLights/files/4834967/Pinwheel.Bug.zip)

**Comment by computergeek1507** [comment]
fixed with 6e656b2dd1b1d8018763f9ac10f2b50f69fde3d7
