### ISSUE TITLE
Controller setup visualizer splits 20 string megatree across 2 16 port alphapix controllers with last 4 strings on ports 17-20 of second controller.

### ISSUE THREAD

**Issue by uska9** [smeighan/xLights#2121]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
This issued occurred during setup.  Attempted to split a 20 string x 100 node megatree across 2 HC AlphaPix 16 controllers.  Each controller is configured in xlights for 16 universes of 100 nodes each.  Whether I use straight start channel or individual start channels, the 4 strings that would be on the second controller show up as strings 17-20 on visualizer.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Add two 16 output controllers (I used both HC alphapix 16s and advatek pixlite 16s as they both had the issued)
2. Configure both for 16 strings with 300 channels per universe.  (At 30% brigtness first can just fit under limit of 350W PS with some margin so is why I am using two controllers)
3. Set first with universes 1-16 and second for universes 17-32.
4. In layout create a 20 string 180 degree megatree with 100 nodes each. 
5. Set start channel of megatree to 1.
6. Go to visualizer for 1st controller and see strings are appropriately lines up with ports 1-16.
7. See error by going to 2nd controller visualizer and scroll down to where it shows the megatree strings 17-20 are assigned to second controller's non-existent ports 17-20.

**Expected behavior**
I expected that strings 17-20 would be assigned to second controller's ports 1-4.

**Screenshots**
Screenshots added below but if they don't come through they are also at the following shared dropbox link: https://www.dropbox.com/sh/kmofe1db5tksssl/AAA_3TjBWLwM-tzxG1ldPU2ba?dl=0

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.26

**Additional context**
Tried splitting with universes, individual start channels, absolute channels but all have the issue.
![Xlights visualizer port allocation issue pt 2](https://user-images.githubusercontent.com/67877269/86542481-173e4800-bee4-11ea-8c83-c62a859fb108.jpg)
![Xlights visualizer port allocation issue pt 3](https://user-images.githubusercontent.com/67877269/86542483-173e4800-bee4-11ea-968d-48edb76e630b.jpg)
![Xlights visualizer port allocation issue pt 1](https://user-images.githubusercontent.com/67877269/86542484-17d6de80-bee4-11ea-9a92-31ebbca4c8c4.jpg)

**Comment by computergeek1507** [comment]
The code for the controller port calculations was written to only work when using one controller. We assumed if you are spanning multiple controller for one model, you will configure it manually.

**Comment by keithsw1111** [comment]
This will not be changed. 

1. Demand for this is very low. Very few people set things up this way.
2. In order to support something like this we would need to add more properties to models and more complexity to visualiser ... that complexity brings with it bugs and more significantly usability issues.
