### ISSUE TITLE
Xlight 2020.26 very long to save

### ISSUE THREAD

**Issue by PtitBry** [smeighan/xLights#2122]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**_Describe the bug_**
I made the software update to 2020.26 before 2019.46, I started a sequence programmaton in 2019.46, all works properly.
After the update the save take 53min but with the 2019.46 this taken 93 sec.
I tried to recreate the sequence directly in .xsq but the problem is the same.
My sequence have a clip video on a P5 matrix (57 600px - 1,2x1,2m) and some effects.

I don't know if it a bug or juste the rendering of the P5 matrix with the video clip who very long.

**To Reproduce**
Just open and save.

**Versions (please complete the following information):**
 - OS: Windows 10 Pro
 - xLights version : 2020.26 (before 2019.46)

**Additional context**

**Attachments**

Google drive and Dropbox links are available, but I don't know if I can make them public because of the video clip.
You can MP me for have them

Many thanks,

**Comment by AzGilrock** [comment]
Did you try turning off the Video Hardware Acceleration option?

**Comment by PtitBry** [comment]
> Did you try turning off the Video Hardware Acceleration option?

Thanks for your reply.

I don't found this option, wher she is it ?

**Comment by AzGilrock** [comment]
All the options were moved to the preferences tabs.  Just search for it in the menus.

**Comment by PtitBry** [comment]
> All the options were moved to the preferences tabs. Just search for it in the menus.

![image](https://user-images.githubusercontent.com/67977676/86842754-f7568200-c0a5-11ea-9604-62751956da33.png)

![image](https://user-images.githubusercontent.com/67977676/86842825-09d0bb80-c0a6-11ea-9a20-5379470d198f.png)

**Comment by keithsw1111** [comment]
Unless you can supply us with example files there is not much we can do to help.

**Comment by PtitBry** [comment]
> Unless you can supply us with example files there is not much we can do to help.

Hi,

Here you can found the link for donwload zip file.

Googlde Drive : [https://drive.google.com/open?id=1IX-Rg9qmtissvV_X2q9uR9Lpfh5qYSah](url)

Dropbox : [https://www.dropbox.com/s/5rr4z0bwo9vwhxk/French%20Fuse%20seq.zip?dl=0](url)

I hope with this file you can help me.

**Comment by dkulp** [comment]
I see what's happening.. should have a fix committed soon.

**Comment by PtitBry** [comment]
Ok many thanks. 😁

**Comment by dkulp** [comment]
As a temporary workaround until .27, if you turn off the keep aspect ratio option on the video, it should render quickly, just not exactly what you want.

**Comment by PtitBry** [comment]
Ok thanks.
I'll try this evening (In france).

I think my other problem is the same.
Always with the vidéo clip, when I played the sequence the video clip appears on my matrix during few second and after all are black, I need to make one or more "render" for correct them, sometimes just on simple effect and not on the matrix.
I don't know if you understand all.
I'm not speak English very well 

I need to open another bug reports ?

**Comment by AzGilrock** [comment]
If the video is still rendering then you can play ahead of the render point and see black.  If in doubt hit render all and when its done it should be good.  Every time you fiddle with the effect it re-renders but there's really no indication that the background render of a single effect is complete.  I've always thought that would be a good feature kinda like how a video editor shows progress down in the corner when it's doing background work like that.

**Comment by PtitBry** [comment]
Ok.
Yes when effect are black I made another "render all". 
But in this sequence 53min for complete the rendering, it's very long 🤣🤣

Yes,  know the state of the rendu when you modify an effect can be a good idea and intersting.

**Comment by AzGilrock** [comment]
Well would you like a different color than black while its rendering? LOL
