### ISSUE TITLE
Ver 27 Clicking on Firework Effect Crashes xLights

### ISSUE THREAD

**Issue by byakymyk** [smeighan/xLights#2124]
[xLights_dbgrpt-24693-20200708T202334.zip](https://github.com/smeighan/xLights/files/4893836/xLights_dbgrpt-24693-20200708T202334.zip)

Starting with V27 on Mac OS 10.15.5 MacBook Pro 16 inch 2019

Everytime I click on Firework effect it crashes

**Comment by dkulp** [comment]
The issue is with custom value curves, not the fireworks.  Fixed on master.
