### ISSUE TITLE
.27 Wont Open

### ISSUE THREAD

**Issue by jefft0825** [smeighan/xLights#2125]
It wont get past the startup xlights logo - confirmed this with 2 others as well

Others have said it worked just fine - not sure what the hangup is

PC version

Tried from the download link in xlights as well as grabbing .27 from the webpage 

Rebooted computer - still wont open

Go back to .26 and it opens fine

**Comment by keithsw1111** [comment]
there is not enough information here for us to do anything with this. at a minimum we would need to see logs.

**Comment by jefft0825** [comment]
It won’t let us get past the beginning logo to even open up xlights

**Comment by keithsw1111** [comment]
Right ... but 26 does. install 27. Get the problem. Install 26 ... get the logs ... or just go to the folder where the logs are. On windows ... c:\users\<you>\appdata\roaming\xlights*.log should do it.

**Comment by jefft0825** [comment]
[Xlights.27 issue.zip](https://github.com/smeighan/xLights/files/4897201/Xlights.27.issue.zip)

**Comment by dkulp** [comment]
Looks like it's have problems loading the value curves in your  C:\Xlights\Xlights Show Folder\Tell Famliy Lights\valuecurves\ folder.  Can you zip those up and attach them?

**Comment by computergeek1507** [comment]
The couple people I helped, got it to work when they move the show folder out of Dropbox or Onedrive

**Comment by jefft0825** [comment]
[valuecurves.zip](https://github.com/smeighan/xLights/files/4898513/valuecurves.zip)


I was able to switch my show folder to a local folder and get xlights .27 to open, then switch back to my google drive show folder but when I open a sequence up under google drive,, it freezes

**Comment by jefft0825** [comment]
removed my value curve from my show folder temporarily and .27 opened up just fine and can render a sequence

**Comment by jefft0825** [comment]
[xLights_dbgrpt-7660-20200709T124538.zip](https://github.com/smeighan/xLights/files/4898553/xLights_dbgrpt-7660-20200709T124538.zip)


I replaced my value curves with the one i removed. then tried to render and was able to get a crash report

**Comment by dkulp** [comment]
Definitely value curve related and already fixed on master and in the 2020.27.1  OSX build.
