### ISSUE TITLE
Purchased sequences not displaying properly after update to 2020.27 (MacOS Catalina)

### ISSUE THREAD

**Issue by skydiveguy** [smeighan/xLights#2127]
**Describe the bug**
Purchased sequences are mot displaying properly after updating to 2020.27 (MacOS Catalina

**To Reproduce**
1. Create new musical sequence and add music track
2. Click on Import>Import Effects
3. Map props to the correct props in your display
4. Render all.

It seems that the images are not being mapped correctly in this new version. I did go through the steps going into Prefrences in Xlights and verified all the drive mappings/show folder, etc are correct and saved.

**Expected behavior**
Imported images should be showing up when 

**Versions (please complete the following information):**
 - OS: Mac 10.15.5
 - xLights version 2020.27

Looking at Check Sequence it is showing that the image files are not under the "show folder" which is correct, but the path to the folder where these images reside in Effect Settings is the correct path.

Im not sure if this is a bug related to the sandbox version upgrade or just a known change that was made that will require the images to now only reside under the show folder.

this is happening to all of the mega tree sequences I have purchased that use images.
![BugReportAIWFC](https://user-images.githubusercontent.com/67765665/87043795-9e7d0b80-c1c3-11ea-845c-cd33e7f3443c.png)
[AIWFC-BugSample.zip](https://github.com/smeighan/xLights/files/4896973/AIWFC-BugSample.zip)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/4896975/xLightsProblem.zip)

**Comment by AzGilrock** [comment]
Well you guessed correct...move your images under the show folder.

**Comment by skydiveguy** [comment]
fyi... i did revert back to 2020.26 and reopened the original sequence (not the sample that I included) and the images are displaying properly.
I also noticed these images are looking in the show directory (/Users/brian/Google Drive/xLights/Show/Images/AIWFC_203.png) so 2020.27 was looking in the proper location when I first discovered this issue. But that folder actually contains no images(?)

**Comment by AzGilrock** [comment]
Hopefully Dan can get you sorted out.  I hate using cloud drives for show folders and I don't waste my time trying to troubleshoot issues when they are involved because they are the source of the problem many times.

**Comment by skydiveguy** [comment]
Thanks again. I am only using cloud drives as I need to be able to switch between computers.
As for the actual drive, the folder structure is the same on any computer I use its just replicated on different PCs.
Thanks again for your help!

**Comment by dkulp** [comment]
Having stuff outside the show or media directories is definitely going to be more problematic with the sandboxing. However, there is a simple "workaround" you could try. Go to preferences, set the old directory as the media directory. Restart xLights, then go to preferences and set it back. Since you specifically give permission to xLights to access that directory by setting the media dir, we can create the bookmark and we'll save it.

**Comment by skydiveguy** [comment]
Thanks again!
