### ISSUE TITLE
4.0.2x Tall custom model causes Ok, Cancel Appearance buttons to move out of view, clickable area

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#213]
I created a custom model 50px tall. By default it became part of my display. I went to edit the model, to uncheck "Part of my display" and the window has moved the OK, Cancel, Appearance buttons to an area I can't get to. Screen resolution is 1440x900.  Need to anchor the buttons.

![image](https://cloud.githubusercontent.com/assets/10568498/7235368/ab76cfee-e742-11e4-8378-3033fab4e010.png)

**Comment by smeighan** [comment]
yep, this would be a bug.

What you can do is edit your xlights_rgbeffects.xml file. Go to the first section , which is <models>
under this are all the models you have, they will be between the xml tags <model> ... </model>

Example:
<model name="40w rgb flood-1" DisplayAs="Custom" StringType="RGB Nodes" parm1="11" parm2="11" parm3="1" StartChannel="1" StartSide="B" Dir="L" Antialias="0" ModelBrightness="0" CustomModel=",,,1,1,1,1,1,,,;,1,1,1,1,1,1,1,1,1,;,1,1,1,1,1,1,1,1,1,;1,1,1,1,1,1,1,1,1,1,1;1,1,1,1,1,1,1,1,1,1,1;1,1,1,1,1,1,1,1,1,1,1;1,1,1,1,1,1,1,1,1,1,1;1,1,1,1,1,1,1,1,1,1,1;,1,1,1,1,1,1,1,1,1,;,1,1,1,1,1,1,1,1,1,;,,,1,1,1,1,1,,," offsetXpct="0.6706" offsetYpct="0.3511" PreviewScale="0.0300" PreviewRotation="0" versionNumber="1" MyDisplay="0"/>
   

See the last entry? MyDisplay="0"
This means the model is NOT part of your display. Find your model and change MyDisplay="1" into MyDisplay="0"

save the file.
Do this edit when you are NOT in xlights.

As always, do a "File,Backup" before editing any xml files. This will backup all your setup data and all of your sequences.

**Comment by stevegiron** [comment]
I found an easier workaround for now. 
Change the model type from custom to any other type and the channel grid will change sizes. Resize the model window and change the model type back to custom.  The buttons will reappear. 

![image](https://cloud.githubusercontent.com/assets/10568498/7238468/8ab4189c-e757-11e4-9bf8-69b4caf75fec.png)
