### ISSUE TITLE
Xschedule Remote Falcon Plugin Error Clearing Playlist

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#2132]
Xlights 2020.29 (And previous)

Fetching current playing mode ...
{"viewerControlMode":"voting"}
MODE: voting
Started.
Uploading playlist to Remote Falcon.
    {"message":"Success"}
Clearing remote falcon list of songs.
    <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

    {"message":"Queue Empty"}
Updating remote falcon with the playing song: null
{"currentPlaylist":"null"}

**Comment by keithsw1111** [comment]
Without logs there is not much i can do. The server is complaining but i cant see why.

**Comment by keithsw1111** [comment]
Check you dont have apostrophe's in the step names ... it seems the remote falcon site does not like them.

**Comment by cathelest** [comment]
That fixed it, had an apostrophe in a sequence name, Many thanks,
