### ISSUE TITLE
FPP Connect Instance Sorting

### ISSUE THREAD

**Issue by reelpilot** [smeighan/xLights#2133]
When FPP Connect opens up it would be very useful for those who have many FPP instances running to have the ability to sort the order in which they are displayed. Alternatively if FPP Connect would default to showing FPP instances in order of their IP address that would serve the same purpose.

The reasoning behind this is to quickly identify any FPP instances that may not be showing up which happens from time to time. For example my show contains a master and 15 remotes. The master is 10.0.0.100 and the remotes are 10.0.0.101 - 115. Currently when FPP connect opens the order that these 16 FPPs display changes every time which makes it challenging to identify any instances that may not have automatically populated. This is especially true when you have many FPPs and one must scroll back and forth to find all the instances. If the display order of FPP instances were sorted by their IP address then it would quick and easy to identify any missing instances.

**Comment by dkulp** [comment]
Sorting by ip is now the default, popup menu on the header can be used to also sort by hostname.
