### ISSUE TITLE
Improving support for multi-holiday layouts. 

### ISSUE THREAD

**Issue by madsci1016** [smeighan/xLights#2135]
A while back Keith asked me to start this discussion here and better document how I've been doing it. Finally got around to it. I don't have a good answer for this yet, I'm just documenting my need and how I've been doing it in hopes to get the discussion going with a few others to see if we can come up with a clever idea to properly support it. 

For those that have a Halloween and Christmas display the first obvious way to do this is to just create two show folders. The downside is if there are a lot of common props used in both shows, every time you change a prop, details of the prop, prop location, etc. you have to do it twice in both show folders. My show is actually 70-80% common props, so this would happen often in my case. 

I have 'abused' some of the features in xlights currently that allow me to do both holidays in one show folder. TO be honest it has worked quite well, but the new features like ZCPP and controller config upload don't integrate well because of my abuse and thus I have not been able to use them. 

This is how I've done it:

I have both holidays worth of universes setup in my controller tab, and I will deactivate the universe not used for that holiday:
![Controllers](https://user-images.githubusercontent.com/1082294/87882204-23d29e00-c9c4-11ea-8709-156d0e35e30b.PNG)

Basically I have universes setup for both shows as if it were one show, and I simply change the controller config between seasons to change which universes they listen to for each pixel port. So the same port that listened to universe 80 for spider web changes to universe 60 for snowflakes when i change the display around. 

Changing to the layout tab, I've created two previews, one per holiday and use the same picture for both. All the common models i assign to "All Previews" and then assign Halloween specific props to Halloween and Christmas props to Christmas. Thankfully xlights will display the props assigned to "All previews" to both the halloween and christmas preview. 

![Both](https://user-images.githubusercontent.com/1082294/87882304-d9055600-c9c4-11ea-9066-79806eaab832.PNG)
![Halloween](https://user-images.githubusercontent.com/1082294/87882306-dc004680-c9c4-11ea-8f40-9bba695b92eb.PNG)
![Christmas](https://user-images.githubusercontent.com/1082294/87882308-de62a080-c9c4-11ea-9f81-41aa03ea08ca.PNG)

I then setup two different views in the sequence tab, one per holiday, with only the props visible for that holiday. 
![Views](https://user-images.githubusercontent.com/1082294/87882344-15d14d00-c9c5-11ea-94be-193d0a083c21.png)

So that's what I've been doing. I know I'm a minority somewhat, but I am starting to see more people start doing halloween songs with their existing christmas props. 

I argue the heart of the issue is I want to support multiple "configs" for the same controller, and be able to select which config is pushed from xlights. So i wonder if a simple solution to this is to add a drop-down to the setup tab to allow the user to create different setups in the same show folder, and allow controllers(or ports on a controller) to be added to one or all of these setups. Ports in the "all configs" couldn't then be added to individual configs, but ports added to an individual config can be re-added to another individual config with a different universe or prop attached to it. 

May this can be tied through to the layout tab so a master drop down changes both the setup and layouts tab if required to help coordinate what props is tied to which controller port in which selected configuration. 

Anyway, thats it. Thanks devs.

**Comment by TraceWilson** [comment]
Just found this entry, and I'd like to second/agree with/vote for enhancements in this area.  While my display is nowhere as complex as @madsci1016, I too struggle with setting up 2 shows (Halloween/Christmas) which use 90% of the same props in both.  Additionally, I'm planning to start a Veteran's Day show, which will also use 90% of the same props.

In my setup I have a large number of nested groups.
![image](https://user-images.githubusercontent.com/32341397/195990858-1c28d42a-4732-41e6-bd8e-25ae82d0c784.png)

It would be wonderful if a Preview would simply show all models in a group, and in any of it's sub-groups, regardless of what preview it's members are assigned to.  I'll look into the use of the All Previews option, and that may take care of me for now, but I'd much prefer to see the Preview simply show any assigned group's models, and the models of any sub-groups.

**Comment by djulien** [comment]
@madsci1016 Do you use physically the same controller for multiple holidays, or you swap a controller connected to the lights?  
Do you use FPP-based controllers, or something else?  I'm trying to figure out a better way to do this also.

**Comment by keithsw1111** [comment]
I just implemented a solution for this.
