### ISSUE TITLE
3d moving head in 3d mode

### ISSUE THREAD

**Issue by dustinhayes86** [smeighan/xLights#2136]
This is my first year using Xlights and i have been trying to build and convert from LOR. 
I am using the 3d moving head model in the 3d preview. I setup the first moving head everything fine. Added a second moving head and put in the channels and then I put in channels, pan orientation, tilt orientation, etc. and the model disappeared. 
Steps to what I did:
-click DMX model and select 3d moving head from list
-add second 3d moving head from DMX model
-add desired channels ( I have a 9 channel )
-adjust pan orientation 
- deselect second 3d model and select something else

![image](https://user-images.githubusercontent.com/68525545/87896710-9f593d00-ca0e-11ea-9db7-24d1a34a9c92.png)

I tried to add a picture not sure if it is viewable. Hope I gave enough information.

**Comment by AzGilrock** [comment]
The channel numbers are relative not absolute.  That allows you to have identical channel numbers for multiple heads and you only change the start channel.  When you told it you only had 9 channels and then said Pan was channel 10 that was outside the boundary so it doesn't draw.  Pan should be 1 if its the first channel.
