### ISSUE TITLE
xSchedule won't open because of Remote Falcon dll.

### ISSUE THREAD

**Issue by chuckackerman** [smeighan/xLights#2137]
Hi,

I'm a user of Remote Falcon in xSchedule.  In 2020.29 when I try to open xSchedule nothing happens.  It shows up momentarily in Windows Task Manager but then quickly goes away.  If I rename RemoteFalcon.dll to something else the problem goes away.  This temporarily lets me use xSchedule but, of course, I can't use Remote Falcon.

**Comment by computergeek1507** [comment]
Can you open "Regedit" and find the settings for "Computer\HKEY_CURRENT_USER\Software\RemoteFalcon" attach a screenshot of it. Also upload your xSchedule log file

**Comment by cathelest** [comment]
Should he censor the RemoteFalconToken? or send it privately?

**Comment by computergeek1507** [comment]
I would prefer getting the key privately. Chuck has complained multiple times on multiple public forums how this is "broken" and has done zero work to help find the issue. On my three PC's Remote Falcon works with xSchedule. At this point this ticket is useless without more information. Making "It's broken" issues tickets are a waste of our time and in my option should be closed.

**Comment by chuckackerman** [comment]
> Can you open "Regedit" and find the settings for "Computer\HKEY_CURRENT_USER\Software\RemoteFalcon" attach a screenshot of it. Also upload your xSchedule log file

Here's a screenshot.  Can you tell me where to find the log file?
https://drive.google.com/file/d/15vdM9MPCwq7UZmDeTxem1LyZIgVf5zYm/view?usp=sharing

**Comment by chuckackerman** [comment]
If you need the token I can send it privately if you indicate where to send it.

**Comment by computergeek1507** [comment]
for the log, in xSchedule go to Tools->View Log and save the resulting file and attach it or email me.

scott@scottnation.com

![image](https://user-images.githubusercontent.com/2293065/88566465-0aed6c80-d004-11ea-8c38-19c5a4dd1cfa.png)

**Comment by chuckackerman** [comment]
Scott,
Log sent.

**Comment by chuckackerman** [comment]
With the help of Scott in private emails the problem appears to be solved.  Thank, Scott, for your help.
