### ISSUE TITLE
export home preview video 

### ISSUE THREAD

**Issue by asis85** [smeighan/xLights#2139]
running Mac iOS 11 beta 3 with lights Version:  from the app store when I try and do a video export I get this error "exporting house preview video failed. 

[Screen Recording 2020-07-22 at 7.52.17 PM-1.zip](https://github.com/smeighan/xLights/files/4963659/Screen.Recording.2020-07-22.at.7.52.17.PM-1.zip)

**Comment by asis85** [comment]
[welcome.zip](https://github.com/smeighan/xLights/files/4963763/welcome.zip)
here is the file that will not let you export video

**Comment by dkulp** [comment]
The video exporter requires the audio to be in stereo.  Your audio is mono.  I have made sure the error message displays on the "failed" dialog.
