### ISSUE TITLE
Papagayo xml not displaying correctly in sequencer grid (xl4.0.23)

### ISSUE THREAD

**Issue by mararunr** [smeighan/xLights#214]
In xl4.0.23, when opening an xml with coroface effects (created in 3.6.15), the grid is populating with OFF effect rather than CoroFace effect.  Have to click on each cell in grid which will correctly show coroface in effect settings (but not sequence grid), then hit update(f5) to get grid to properly display coroeffect.  (Preview plays what is displayed on grid, not what is in effect settings).  Files to repeat results are here (https://onedrive.live.com/redir?resid=d05fbdc1b79cf3a9%21105).  In the example xml I have updated just the first cell of the sequence.  (Hitting Render all will get preview to play correctly but sequence grid still show OFF effect across the sequence.)

**Comment by stevegiron** [comment]
Is this still an issue with 4.0.31?

**Comment by mararunr** [comment]
Trivial = not important = close it.  Yes it still exists but I'll let others report it if they deem necessary.
