### ISSUE TITLE
Xschedule Remote Falcon playlist not syncing all sequences.

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#2145]
**Describe the bug**
Not all sequences are being sync'd to remotefalcon from xschedule,

**To Reproduce**
Copied a test fsq file, copied and renamed 30 times, added to test playlist,

**Screenshots**

**Versions (please complete the following information):**
 - Win10pro
 - xLights version 2020.29 64bit

**Attachments**
![testplaylist](https://user-images.githubusercontent.com/52036639/88663096-5bf18380-d11e-11ea-9c46-49448e2951cc.png)

Log Line: 2020-07-28 21:59:26,478 39984 log_base [DEBUG] {"remoteToken":"{token}","playlists":[{"playlistName":"30 Test","playlistDuration":223},{"playlistName":"29 Test","playlistDuration":223},{"playlistName":"28 Test","playlistDuration":223},{"playlistName":"27 Test","playlistDuration":223},{"playlistName":"26 Test","playlistDuration":223},{"playlistName":"25 Test","playlistDuration":223},{"playlistName":"24 Test","playlistDuration":223},{"playlistName":"23 Test","playlistDuration":223},{"playlistName":"22 Test","playlistDuration":223},{"playlistName":"21 Test","playlistDuration":223},{"playlistName":"20 Test","playlistDuration":223},{"playlistName":"19 Test","playlistDuration":223},{"playlistName":"18 Test","playlistDuration":223},{"playlistName":"17 Test","playlistDuration":223},{"playlistName":"16 Test","playlistDuration":223},{"playlistName":"15 Test","playlistDuration":223},{"playlistName":"14 Test","playlistDuration":223},{"playlistName":"13 Test","playlistDuration":223},{"playlistName":"12 Test","playlistDuration":223},{"playlistName":"11 Test","playlistDuration":223},{"playlistName":"10 Test","playlistDuration":223},{"playlistName":"9 Test","playlistDuration":223},{"playlistName":"8 Test","playlistDuration":223},{"playlistName":"7 Test","playlistDuration":223},{"playlistName":"6 Test","playlistDuration":223},{"playlistName":"5 Test","playlistDuration":223},{"playlistName":"4 Test","playlistDuration":223},{"playlistName":"3 Test","playlistDuration":0}]}

![christmasplaylist](https://user-images.githubusercontent.com/52036639/88663093-58f69300-d11e-11ea-8017-4c72a5831886.png)

Log Line: 2020-07-28 22:00:27,614 51012 log_base [DEBUG] {"remoteToken":"{token}","playlists":[{"playlistName":"Feature - Back To The Future","playlistDuration":203},{"playlistName":"Moana - Youre Welcome","playlistDuration":163},{"playlistName":"For King And Country - Little Drummer Boy","playlistDuration":275},{"playlistName":"Winter Wonderland","playlistDuration":183},{"playlistName":"Trolls - Wanna Have Good Times","playlistDuration":181},{"playlistName":"The Weeknd - Blinding Lights","playlistDuration":200},{"playlistName":"Feature - Starwars Funk","playlistDuration":222},{"playlistName":"Shake Up Christmas","playlistDuration":131},{"playlistName":"Ariana Grande - Santa Tell Me","playlistDuration":202},{"playlistName":"Skeewiff - Santa Claus is Coming To Town","playlistDuration":161},{"playlistName":"RR - Silent Night","playlistDuration":111},{"playlistName":"Lindsay Sterling - Mr Grinch","playlistDuration":168},{"playlistName":"Owl City - Lights Of Christmas","playlistDuration":224},{"playlistName":"Frozen - Let it go","playlistDuration":223},{"playlistName":"Idina Menzel - Christmas Just Aint Christmas","playlistDuration":212},{"playlistName":"Hey Come Look At My House","playlistDuration":145},{"playlistName":"Soundtrack - The Greatest Show","playlistDuration":272},{"playlistName":"The Git Up","playlistDuration":162},{"playlistName":"Tones And I - Dance Monkey","playlistDuration":141},{"playlistName":"Soundtrack - Christmas Vacation","playlistDuration":178},{"playlistName":"Lindsay Sterling - Carol Of The Bells","playlistDuration":168},{"playlistName":"Trolls - Cant Stop","playlistDuration":237},{"playlistName":"Sia - Candy Cane Lane","playlistDuration":213},{"playlistName":"Skrillex - Bangarang","playlistDuration":204}]}

[xSchedule_l4cpp.log](https://github.com/smeighan/xLights/files/4988147/xSchedule_l4cpp.log)

In the log you will see i initially had the test playlist selected in remotefalcon, it syncs all but the last 2 (2 Test, 1 Test missing)
(The files are in descending order)
When i selected the christmas playlist, the last one, "Soundtrack - Can You Feel The Love Tonight" is missing,

Originally thought it may have a limit to amount of sequences, as christmas playlist syncd 24/25,
Which is why i made the test playlist with the same fsq copied and renamed 30 times, but syncd 28/30
But not too sure,

It probably something i am doing wrong, but thought to post anyway, sorry if im wasting peoples time,

**Comment by computergeek1507** [comment]
The issue is in the hard codes size of the buffer used to send data between xSchedule and the Remote Falcon plugin. Large data strings will get cut off.  I don't know how to fix it I hope @keithsw1111 has a solution.

![image](https://user-images.githubusercontent.com/2293065/89115316-24a01100-d455-11ea-97f6-021347cc5d63.png)
