### ISSUE TITLE
Minor UI Fix

### ISSUE THREAD

**Issue by russellmcfarlandsc** [smeighan/xLights#2148]
Correct the spelling of the Gilbert Engineering model download section.  Screenshot attached.
![gilbert](https://user-images.githubusercontent.com/68972880/88855830-73357d00-d1c1-11ea-8fe2-10efdd303bb0.jpg)

**Comment by dkulp** [comment]
Not a bug in xLights...  this is a bug in GEUSA's own repo and they are in complete control of that:

https://github.com/GEUSA/xmodels/blob/master/geusa-xlights.xml
