### ISSUE TITLE
Preferences -> "Model Blending Default Off" not saving

### ISSUE THREAD

**Issue by jaydonoghue** [smeighan/xLights#2150]
**Describe the bug**
Checking the preference "Model Blending Default Off" does not retain between saves

**To Reproduce**
Go to preferences
Go to Sequences tab
Check "Model Blending Default Off"
Click OK to save changes

Open preferences again to Sequences tab. Model Blending Default Off will be unchecked

**Expected behavior**
Checkbox will be saved

**Screenshots**
![image](https://user-images.githubusercontent.com/17279178/88993866-14e9c680-d2b5-11ea-9876-540832ec3ce2.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.29

**Comment by computergeek1507** [comment]
fixed with b20e9caae43bdab47b3413232837987c264d0564, Thank for finding this.
