### ISSUE TITLE
LOR S5 importing

### ISSUE THREAD

**Issue by dustinhayes86** [smeighan/xLights#2151]
We have been importing from S5 and after we have selected a sequence and the screen appears Xlights does not break done lor's bundles (groups) down. for example: the mega tree bundle with 32 strings of lights 8- white, 8- green, 8- red, 8 blue. When converted to xlights it just comes up as the title of the bundle (group). If you drag the bundle (group) name 17ft mega tree to the left side where the xlights group is made, click ok and play,  there are not any programming available to play. However s4 converts these groups just fine.... so i have been using as much s4 as possible. But for new sequences built in s5 do not have the group break down. and this is for any groups from s5.

**Comment by computergeek1507** [comment]
Can you attach the S5 sequence, so we can use for testing?

**Comment by dustinhayes86** [comment]
tell how to attach the sequence and ill do that for you

**Comment by dustinhayes86** [comment]
[for KING & COUNTRY - Little Drummer Boy_2019 - Copy.zip](https://github.com/smeighan/xLights/files/5005090/for.KING.COUNTRY.-.Little.Drummer.Boy_2019.-.Copy.zip)

let me know if this works

**Comment by computergeek1507** [comment]
The attachment worked. Can you also run package sequence in xLights and attached the zip file so I can see your xLights models as well

**Comment by dustinhayes86** [comment]
[xLights_dbgrpt-8904-20200724T222613.zip](https://github.com/smeighan/xLights/files/5007612/xLights_dbgrpt-8904-20200724T222613.zip)
[xLights_dbgrpt-6524-20200218T192946.zip](https://github.com/smeighan/xLights/files/5007613/xLights_dbgrpt-6524-20200218T192946.zip)
[xLights_dbgrpt-4896-20200419T184258.zip](https://github.com/smeighan/xLights/files/5007614/xLights_dbgrpt-4896-20200419T184258.zip)


[for KING & COUNTRY - Little Drummer Boy.zip](https://github.com/smeighan/xLights/files/5007617/for.KING.COUNTRY.-.Little.Drummer.Boy.zip)

let me knw if i got the right one

**Comment by keithsw1111** [comment]
@computergeek1507  Scott ... did I see a checkin for this?

**Comment by computergeek1507** [comment]
Please let me know if this helps with your importing. https://www.youtube.com/watch?v=Ec88N_lQcw8

**Comment by dustinhayes86** [comment]
Thank you this is gonna help big time



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
