### ISSUE TITLE
'2 is unmask' in 3d mode leaving shadow effects on props

### ISSUE THREAD

**Issue by schulzfamilylights** [smeighan/xLights#2154]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Tom BetGeorge uses a group of all pixels placed as the bottom of seqeunces for fading shaders to all effects. 
In 2d mode, since all props are linear this does not create issues. When in 3d mode, I am seeing 'shadows' appear casue by props that are not 'on' based on viewing the whole house. I can change behaviors based on ordering of effects. For example, minitree stars are turning on and off, with the shader effect showing instead of just solid white. If there is a prop behind one of the start that is off, the full star does not show.. some of it will be 'off' 
similarly by reordering effects, the shader outline of a star can appear on say a vertical matrix behind the star that is supposed to be 'off'. I initially thought this was just an issue with the rendered output on computer, but hooked up a few props and they actually are showing the same issue.
**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
using a 'all pixels' group to apply fades/shaders to all props that are 'on' 

**Expected behavior**
I would expect the props not create shadow effects on other props.  

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: 2020.26

**Additional context**
seems to not occur if layout was created in 2d mode. I can take Tom's sequence and not see issues, but if set his layout to 3d mode and then place props in 3d space can create the same issue

**Attachments**
since this is a purchased sequence, I will upload to a share and DM the zip to Gil since seems to be 3d related. 
I am attaching screenshots and link to video showing the issue.. 
stars without shader - showup without issue
![stars-white](https://user-images.githubusercontent.com/64709591/89139116-55d71a80-d503-11ea-91e5-874da05ce762.jpg)
with the shader group overlay.. matrixes behind stars are off and thus so are some pixels on the stars
![stars-shader](https://user-images.githubusercontent.com/64709591/89139125-596aa180-d503-11ea-88a5-fd16b93cc59c.jpg)
shows the matrixes behind being displayed on the canes, minitrees, and arches
![column_matrix-oncanes_trees_archesjpg](https://user-images.githubusercontent.com/64709591/89139132-5c659200-d503-11ea-9746-233fa6a005a6.jpg)
similar screenshot highlighting the effects being shadowed from the matrixes onto the canes, minitrees and arches
![screenshot1](https://user-images.githubusercontent.com/64709591/89139144-69828100-d503-11ea-9aaf-009156b800d8.jpg)
link to house preview video
[https://vimeo.com/444105672](url)

will DM sequence link to Gil, if any other developers need it please let me know

**Comment by schulzfamilylights** [comment]
apparently Gil cannot be found on fb anymore.. please let me know who needs the sequence and i will send the link to the zip.

**Comment by AzGilrock** [comment]
I won’t have time anytime soon to dig into complex issues.  But just reading it I can’t imagine we would find something we would change we would just be explaining why it happens.  The effects always render as if the 3D box is unchecked unless you select the option to render a camera view.  So it’s most likely just the way you’ve moved the props around to make it look good in 3D.  Uncheck the 3D box and you’ll see how the models overlay and it might show why models are now in front of other models which can cause the pixels from both models to end up in the same cell which will cause what you’re seeing.

**Comment by schulzfamilylights** [comment]
hey Gil, but why would it only affect when using this unmask on this group at the bottom of a sequence is used? Again, if was just how it was output on screen wouldnt be an issue, but it actually shows up on the prop itself. Is that just how the rendering will work? so if a prop is 'off' when this fader group is set to '2 is unmask' it doesnt only affect the props that are 'on' and show the shader on that prop, but any props in front of it that are 'off'? I only moved props around in Tom's layout as was wondering why i didnt see the issue in his layout. My layout has always been 3d, before importing the sequence into my layout and see this result. Just trying to see is this something that just wont work as an effect from Tom for anyone with a fairly dense layout?

**Comment by AzGilrock** [comment]
I don't know I can't even imagine what 2 is unmask even does anymore.  Not something I've used in years.  There is a ton of factors in play once you start rendering to groups and groups of groups and have model blending on and the ordering or the models matters.  To troubleshoot something like this I don't want to dig into a sequence with 4000 effects.  So try to create a sample sequence with just 2 or 3 effects that shows the issue and then you can share it.

**Comment by schulzfamilylights** [comment]
ok, just packaged a 30second animation file with just some shockwave effects on the minitrees and minitree stars.. it starts with no fader group.. just all white and renders fine, then the shader kicks in and you will see the effect bleed into the spinarchys in the foreground.. (best to see when viewed from the side) ..  then shockwaves on the matrices behind all white (fader group off) no issues, fader group is on and the effects bleed into props in front of them..
Thank You

[renderissue.zip](https://github.com/smeighan/xLights/files/5019516/renderissue.zip)

**Comment by schulzfamilylights** [comment]
was this issue just closed as working as designed?

**Comment by ghormann** [comment]
No.  Dan committed a fix for the next build: 237cf20519cc7b8d3c9a6d90f090b5e2ebb4d473

**Comment by schulzfamilylights** [comment]
doh! i didnt even see that.. thank you guys!
