### ISSUE TITLE
DMX Heads do not display beam correctly

### ISSUE THREAD

**Issue by Hilights360** [smeighan/xLights#2155]
From a fresh layout, if a DMX head is added as a 3D Moving Head Model, the beam works correctly. If the 3D Moving Head model axis is rotated 180 to simulate the moving head being mounted inverted, the beam does not follow the model correctly. Tilt and Pan rotation direction may also be an issue. The ability to set rotation direction may need to be added for it to wok correctly with some moving heads. 

![3D_Movinghead_error](https://user-images.githubusercontent.com/35340265/89428978-f9dee280-d70a-11ea-93f7-52d43477dca8.JPG)

**Comment by AzGilrock** [comment]
Yep the DMX heads model is designed so that it uses the Pan and Tilt Orientation parameters if you need to rotate the position of the head to match reality don't use the model rotation parameters they need to be 0.  You probably can't make it look upside down currently.  Could we fix it?  Yes but who knows when that will happen so these are your workarounds.  That head you are using I created so technically someone else could create the head with the base already turned upside down if that's so important for you to visualize.  Then you wouldn't need to rotate the model in xLights.

**Comment by Hilights360** [comment]
Gil,

Thanks for the reply. I could take your model and flip it but I get the feeling the Tilt would be off afterwards. This feature was a blessing when you first added it. Now my display has grown to have 13 moving heads with 7 inverted. I was able to correctly visualize the inverted models in the 2019 iterations of xLights for my shows, but something changed and I just recently noticed it was not moving right.

To be honest, I have been with this since Nutcracker and I appreciate the tenacity you and the developers have shown. I am about to lose interest in doing the light shows altogether. Getting tired of traffic complaints and picking up cigarette butts in my yard. Modeling I can do. I really wish I was not so rusty on code or I would help if I could. I built a large (6’) persistence of vision prop and I am hung with reading the FSEQ data from the sd correctly and transmitting it to 4 wands.  Probably just a few lines of code hanging me up but I’ve about given up. Therefore the appreciation. I’ll give what you sent a try. Hope you and your family are safe. Be well.

Thanks,
Tim Nash
President
FL - EC13005579 Unlimited Electrical Contractor
NC - 30494-U Unlimited Electrical Contractor
Hilights, Inc.<http://www.hilightsinc.com/>

[HTS_Twr]
It’s impressive, what we do.
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by AzGilrock** [comment]
I'd need to check it at home but the model is really a collection of models so you don't rotate the whole model just the base.  In fact I'm pretty sure I bring each piece in a independent pieces and I thought you could rotate and scale each piece of the head.  I just try to model them so that they don't need to be moved or scaled when they are brought in.

**Comment by stealthyoshi** [comment]
Is there an easy way

> I'd need to check it at home but the model is really a collection of models so you don't rotate the whole model just the base. In fact I'm pretty sure I bring each piece in as independent pieces and I thought you could rotate and scale each piece of the head. I just try to model them so that they don't need to be moved or scaled when they are brought in.

Hey Gil!  
Thanks for all the hard work you put into the DMX side of things.

Is there an easy way to rotate the DMX made for those of us that aren't well verses enough to modify the code?  Everything is reverse in the visualizer if I use Pan/Tilt orientation. But If I rotate the model 180°, the beam rotation matches what the head is actually doing, but the body is doing the reversed.  It would help a lot to see the body orientation with the light off in the visualizer to set the head up for the next move..

**Comment by AzGilrock** [comment]
Sounds like you just need to make the degree of rotation parameter negative.  Every motion on that model is reverseable

**Comment by stealthyoshi** [comment]
Yup, that did the trick!  Thanks Gil!

**Comment by dkulp** [comment]
Has anyone checked with 2022.03 if this is still the same.  The change from drawing beam and such from world coordinates to model coordinates may have fixed this, or at least completely changed the workarounds that would be needed.

**Comment by AzGilrock** [comment]
I need to test it but yeah if it’s using model coordinates then folks who reversed the sign when they flipped a head upside down will need to swap it back.

**Comment by AzGilrock** [comment]
Fixed long time ago
