### ISSUE TITLE
Xlights breaks Bluebeam Revu 2019

### ISSUE THREAD

**Issue by Cassock** [smeighan/xLights#2156]
**Describe the bug**
Having Xlights installed on my PC prevents Bluebeam Revu 2019 from rendering PDFs correctly. There is no error when launching or using Xlights.

**To Reproduce**
Upgrade from Bluebeam Revu 2018 to Revu 2019 (or install 2019 outright). PDFs will open and page flip, but no content is displayed. 

**Expected behavior**
PDFs render correctly.

**Screenshots**
https://imgur.com/vflKMQD
Hardware rendering error in Bluebeam ^

**Versions (please complete the following information):**
 - OS: Windows 10 Enterprise LTSC
 - xLights version 2020.30

**Additional context**
Earlier 2020.x versions that I've tried have the same issue. 
Revu 2018 worked fine with Xlights installed; no conflicts or errors of any kind.

**Attachments**
None

**Comment by AzGilrock** [comment]
So not even running xLight just installing breaks this other program?  Really there is nothing in xLights that could affect other programs but the installer does install the Visual C++ runtime so maybe that's the culprit.  You could test that by installing just that C++ runtime by itself without xLights.

**Comment by keithsw1111** [comment]
You may want to edit your path to put xLights after the program with the issue. There is nothing we can do to fix this.

**Comment by stevenwmixon** [comment]
I know this thread is a couple years old but there is a fix. There is a file that both bluebeam and xlights are trying to share. I am looking from the email from bluebeam to find out which file it was. There is a workaround.

**Comment by stevenwmixon** [comment]
deleted the SDL2.dll file out of the xlights folder and hardware rendering will work again
