### ISSUE TITLE
xLights hang when making a custom model - MacOS

### ISSUE THREAD

**Issue by cmanucy** [smeighan/xLights#2157]
Version: 2020.29.1
MacOS 10.15.5

Issue:  When creating a custom model, xLights hangs and becomes non-responsive.

How to replicate:  Start a custom model (I'm in 3D, but it doesn't have to be a 3D model)  Turn on auto numbering and auto increment.  Usually by the time you get to around pixel #11, it'll hang.  Sometimes much sooner.  It might be related to how fast I'm selecting the cells?

Troubleshooting done already:  Tried 2020.26 and it works as expected.
Tried on a clean layout and that didn't matter either.
Once the model is completed in another version, it's no problem in xLights.

Also found if I only do a few (say 8 or so) pixels at a time (slowly) and save, then go back into the custom model, it'll let me continue past the point where it would have hung otherwise.

**Comment by keithsw1111** [comment]
I clicked on 50 without a hang ... maybe its one of the OSX specific bugs stemming from wxWidgets upgrade on that platform

**Comment by priemd** [comment]
I am not able to recreate either on macOS same version as you with .30 or .31.  Just clicked around as fast as I could 100 nodes, with background pic, without pic, multiple layers, show wire checked/unchecked.

Are you creating a 3d model with depth?  What is the width/height?  Background picture?

**Comment by dkulp** [comment]
I believe this is fixed in .31.   Couple more fixes in wxWidgets wxGrid event handling

**Comment by cmanucy** [comment]
Yes, fixed in .31... thanks Dan.

And @priemd, it didn't matter if it was 3d or not.  But even a simple 3x3x3 would cause it to trigger under .29.1.
