### ISSUE TITLE
You can't drag a 2nd dmx prop on Falcon Serial port in visualizer

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#2158]
**Describe the bug**
In versions 26 and forward, you can't drag more than one DMX prop onto a falcon serial port in the visualizer. We discovered this on Saturday working with a user in the Zoom room. They have a Falcon controller and then are also going to use 1 LOR box on the Serial port 3 of the Falcon F16v3 in LOR mode. (No expansion board).. See lower for the youtube link example of the problem. I have also created a sample sequence that was used to create the youtube video.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Configure Falcon controller for Auto everything mode
2. Add some RGB props (4) and add some single string props (5)
3. Go to visualizer and drag RGB props onto and Pixel port they work
4. Drag a dmx prop on to serial port 3, that works, try and drop a 2nd dmx prop onto Serial port 3 and it will not drop.

**Expected behavior**
You should be able to cascade them (This works in 2020.14)

**Screenshots**
https://youtu.be/U9OXc4QM_yk

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version [e.g. 2019.26 ->]   but appears to work in version 14. I haven't determined what version it broke in.

**Additional context**

**Attachments**
https://www.dropbox.com/s/wz6ox8a72lhgcgm/sample.zip?dl=0

**Comment by dramamoose** [comment]
I am having this same problem with the Kulp F8-B. The first prop drags fine, but the second prop breaks it. Xlights also is eating up a massive amount of CPU in that time. I let it run for about ten minutes then force closed.

Windows 10, running 2020.24 64bit June 13, 2020.

**Comment by dramamoose** [comment]
Here are my rgbeffects and networks xml files. Let me know if other files are necessary for troubleshooting.

[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/5048876/xlights_rgbeffects.zip)

**Comment by dramamoose** [comment]
Updated to the latest version last night and this is functioning, so I'm going to stop tracking this issue. (OP, you may want to try to update and see if that resolves your issue as well).

**Comment by computergeek1507** [comment]
The issues is still present. It is related to the DMX start address. When you drag a model onto a DMX port xLights defaults the DMX start address to 1. When you you drag a second model it also defaults the DMX start address to 1. xLights will then remove the second model because it has the same DMX start address. If you manually set the DMX start address in the Layout tab before using the Visualizer, It will work as expected(as long as the DMX address order matched the drag and drop chain order). I have been trying to implementing a fix for this but no luck so far.

**Comment by keithsw1111** [comment]
I believe this is fixed for .32
