### ISSUE TITLE
"Video" start times reset to 0 on all sequences, Won't save changes

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#2160]
I noticed recently (now using .31) on PC and Mac that all of my sequences that have video files in them with specific start times all reset to 0, Some of the video files i drop in and set the start time to lets say 21.4 seconds, render the sequence and save it, close and reopen it and the same video file is back to 0. I have 20 sequence with video files like this i'm going to have to go back through but don;'t want to waste the time being they are not saving the changes

when i click on the video file also you can see in the video i attached that the times just all over and at the bottom XLights is rendering props (im not rendering, xlights is doing this because i clicked on a prop, constantly rendering and i have cache off)

saved file shows start time of 21.4
![xl1](https://user-images.githubusercontent.com/40632971/89786094-64b46300-dae9-11ea-9148-5964d1e1d77b.PNG)

closed Xlights and reopened and file is back to a start time of 0
![xl2](https://user-images.githubusercontent.com/40632971/89786149-7990f680-dae9-11ea-9980-76816a66a880.PNG)

video showing the time jumping all over when i click on a prop
https://youtu.be/WGLrlmXlzrE

packed sequence, the file i click on is under "ALL" group and start time is 3:12.725
https://drive.google.com/file/d/1VUQ-FfUhAd0wJdRhAHaUAoj2QBV34pM6/view?usp=sharing

**Comment by bchiaino** [comment]
heres a step by step walk through, even on a brand new sequence it does not save start imes

I could not speak because i'm at work but what i did was
1. create new sequence and drag in a video file
2. changed the start time to 21.4
3. rendered, played saved as new sequence
4. close xlights and reopen
5. open new sequence (test keith)
6. the video starts to play at 24.1 on screen but you can see the start time once i click on the video is 0 and renders the vdeo back to 0 losing the start time of 24.1

https://drive.google.com/file/d/145naAY160YoJxlrhXJJRA4Czs7oY-TXh/view

**Comment by computergeek1507** [comment]
@dkulp Fixed this with 7bbf0bcd4ed8a3399f3e9607ebb67481741d8e21
