### ISSUE TITLE
Color Menu Sparkles Option Value Curve Issue

### ISSUE THREAD

**Issue by ssharpe83713** [smeighan/xLights#2161]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
A zero value curve does not result in zero sparkles

**To Reproduce**
(link to problem video in Screenshots below)
1. Create a simple On effect with a color of choice;
2. From the Color Menu, click on the Sparkles Value Curve button and select the Flat preset;
3. Sparkles appear on the effect, even though the level is zero on the Flat preset.

**Expected behavior**
A zero level on any value curve should result in no sparkles on an effect

**Screenshots** [Link to Google Drive Issue Video]
https://drive.google.com/file/d/1eKcEh0FXlDumQDqiRzK6xqgw3OD7ksS2/view?usp=sharing

**Versions (please complete the following information):**
 - OS: [Mac 10.13.6]
 - xLights version [2020.29.1]

**Additional context**
None

**Attachments**
None

**Comment by AzGilrock** [comment]
That's an assumption.  Once you tell the effect you want sparkles 0 means minimum.

**Comment by ssharpe83713** [comment]
Assumption, yes...since most users aren't aware of the coder's specific intentions!  However, from a logical standpoint, it seems, to me, that if a zero value in one spot equals zero sparkles (the slider), the "expectation" is that a zero related to the same effect option would give the same result.  By your assumption, if I move the Sparkle slider to the right to generate some sparkles, I have displayed my desire to use them on the effect and, therefore, they should remain when I return the slider to zero!  Clearly, that isn't the result.  Should this be moved to a Feature Request?

**Comment by AzGilrock** [comment]
Well I'm not able to look at the code right now I just know that it is possible to create an On effect without sparkles so not sure why you need to be able to create a value curve that has no sparkles.  And I know the value curves were added later so they just feed into the original effect.  Maybe there is something someone can fix so that's why I only made a comment and didn't close it.

**Comment by ssharpe83713** [comment]
The On effect was simply an example in my demo video...applies to any effect.  If I wanted to use a value curve ramp to go from no sparkles (on any effect) to some number of sparkles,  I would expect a ramp start of zero to mean "no sparkles" and as the ramp value increased, I'd get the applicable number of increasing sparkles.  You're saying that once I get into the Value Curve area, I can't get a zero sparkle condition because zero no longer represents "no sparkles", only minimal sparkles.  Seems counterintuitive since the zero value in the slider does turn them off.

**Comment by AzGilrock** [comment]
Well maybe someone will look into it.  Personally I've never used sparkles I just overlay a Twinkles effect.

**Comment by computergeek1507** [comment]
fixed with 9b3437829e119b6729a929bed896a9b184f6b5e8
