### ISSUE TITLE
Downloaded models create empty groups

### ISSUE THREAD

**Issue by jaydonoghue** [smeighan/xLights#2166]
Just a note-- I dont know if this is actually a bug in Xlights or a problem with the model data that is downloaded.

**Describe the bug**
When you download a model to your layout, it brings over empty groups. This only happens with certain models I have found (likely related to source model data) 

**To Reproduce**
1. Start with a blank layout
2. Create a new model download in your layout
3. Search for "Holiday House" and insert the "Holiday House Grande Wonder Wheel" model (one that I know exhibits the issue)
4. You will now see a bunch of empty groups appear in the models pane (see screenshot)
5. A workaround is to right click a group and choose _Delete Empty Groups_  which cleans things up

**Expected behavior**
Only model data should be brought in by the download button, not groups

**Screenshots**
![image](https://user-images.githubusercontent.com/17279178/90141879-afccb100-dd49-11ea-9ad6-4c9ed730e444.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.31

**Comment by priemd** [comment]
This should be fixed when #2163 gets merged.

**Comment by computergeek1507** [comment]
@priemd I am working on rewriting the group import today to not create duplicate group names if the group already exists I will merge in your change with it.

**Comment by computergeek1507** [comment]
fixed with 1eaf6880f598e774ad1de4fc292d381db2abcc87
