### ISSUE TITLE
Export House Video failed. 

### ISSUE THREAD

**Issue by RobertBurton1** [smeighan/xLights#2167]
[2020 Walk The Dinosaur.zip](https://github.com/smeighan/xLights/files/5072180/2020.Walk.The.Dinosaur.zip)
[Error message.zip](https://github.com/smeighan/xLights/files/5072194/Error.message.zip)

>>>>Tried Exporting House Video. I get an error message with; "Exporting house preview video failed. Video Exporter - assumes stereo input / output currently."

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by ghormann** [comment]
Known issue.   The attached audio file is mono.    Make it stereo and it will export file.

**Comment by computergeek1507** [comment]
fixed with 2ba1d9ef75316da10c4e5b452010db8eb1de3ae6
