### ISSUE TITLE
Add "Cut Effects" option to go with Copy, Paste, and Delete Effects in the right-click menu in the elements pane of the sequencer

### ISSUE THREAD

**Issue by MarkA75160** [smeighan/xLights#2170]
**Is your feature request related to a problem? Please describe.**
In the elements list of the sequencer timeline window, the right-click pop-up menu has per-model and per-row Copy, Delete, and Paste Effects.   I use these functions quite a bit, and often I want to "move" effects from one model or row to another, rather than just copy.   In most other applications, this is typically done with a Cut-and-Paste, however, there is no Cut option in this menu.  There is Delete, but that does not copy the effects to the clipboard before deleting the effect.  A Cut option would essentially be a combined Copy/Delete function.

**Describe the solution you'd like**
It would be really nice to have CUT added to this menu to go along with the existing Copy, Paste, Delete functions.  

**Describe alternatives you've considered**
A "move effects" can be done currently using the existing Copy, Paste, Delete operations, but adding Cut would be nicer, quicker and a little more intuitive (similar to other windows applications)

**Additional context**
This would be more consistent with many other applications that support quick-copy and I suspect should be fairly easy to implement since Copy Effects and Delete Effects already exist.  This would be a combination of those in one operation.
![image](https://user-images.githubusercontent.com/57245161/90337108-f585b580-dfa5-11ea-9c9b-e79a0308b534.png)

**Comment by Cryptkeeper** [comment]
@MarkA75160 this has been added in https://github.com/smeighan/xLights/pull/2259. Once a new build is released with the changes, it’ll be ready for use.

**Comment by patdelaney** [comment]
Please make sure that a description of what this does makes it to whomever
is working on the xlights manual

**Comment by MarkA75160** [comment]
Cut for Models is severely broken.  It doesn't' cut the model effect but is DELETES the top timing track.   Not cutting the model effects is a minor nuisance but deleting the top timing track is very bad.  I don't know how many times I've done this before I realized the timing tracks were getting deleted.

**Comment by computergeek1507** [comment]
fixed with 89df6b9cc3c34cd7728f197d3678ef2b4bf7f0aa
