### ISSUE TITLE
Select Effects Window does not find effects on sub-models

### ISSUE THREAD

**Issue by MarkA75160** [smeighan/xLights#2171]
**Is your feature request related to a problem? Please describe.**
The Select Effects Window does not find effects on sub-models

**Describe the solution you'd like**
The Select Effects Window is very useful for finding, selecting, editing all effects of the same type.  However, it does not find effects that are placed on sub-models.   I would like Select Effect to find and include effects that are on sub-models.

**Describe alternatives you've considered**
No known alternatives exist.

**Comment by computergeek1507** [comment]
fixed with 5cfadff087ccc98b76fc135c86882e4d7cd131c7
