### ISSUE TITLE
Single Line in 3D

### ISSUE THREAD

**Issue by Cranzy-AU** [smeighan/xLights#2172]
**Describe the bug**
On layout in 3D mode, when trying to add a Single Line, you can't drag it to give it a size.
The current workaround I do is to either adjust the X2 property under Size/Location or I switch to 2D view, drag the line and then switch back to 3D

**To Reproduce**
1. Go to the layout tab, make sure 3D is selected
2. Click on the 'Create Single Line' model
3. Create the line on the canvas by clicking and dragging.
4. The error is you can't drag on create.

**Expected behavior**
Being able to draw a line to the desired width/height

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.31

**Comment by AzGilrock** [comment]
I know you can size it during creation.  I'm only on my cell so can't test it.  Maybe try single click, let go and size then click to set.  Otherwise it's click and drag but just not working for you.

**Comment by Cranzy-AU** [comment]
@AzGilrock  Just tested it on another PC.  This pc had .28 on it and that works. Once I upgrade to .31 I cannot drag and set the size on creation.

**Comment by AzGilrock** [comment]
Ok good info.  I can't help for awhile I'm on vacation in Montana.

**Comment by Cranzy-AU** [comment]
@AzGilrock   No worries at all, easy to work around, just thought I would log the problem.
Enjoy the vacation :)

**Comment by dkulp** [comment]
This is due to f64378faac3424d3802406e9eafbf2ee187d1356  which looks wrong and will likely need to be adjusted.

The selectedModel is not null, but it's also not in the list of all the models yet (until mouse release).

**Comment by keithsw1111** [comment]
I believe this is now fixed.
