### ISSUE TITLE
s5 pixels are not coming over in the new version.

### ISSUE THREAD

**Issue by dustinhayes86** [smeighan/xLights#2175]
When importing S5 sequences with the new version, none or some of the pixels are coming through. The AC sequencing is coming through but the pixels do not. Here is the xlights sequence and S5 sequence.
[Do You Hear What I Hear_edit.zip](https://github.com/smeighan/xLights/files/5087482/Do.You.Hear.What.I.Hear_edit.zip)
[Do You Hear What I Hear_edit_2019.zip](https://github.com/smeighan/xLights/files/5087514/Do.You.Hear.What.I.Hear_edit_2019.zip)

**Comment by computergeek1507** [comment]
Can you save the mapping file and attach it so I can test your import setting on my machine. It would be helpful to get a video or pictures of the what the non working effects look like in S5. And can you attach your LOR S5 layout and setup.

**Comment by keithsw1111** [comment]
I can see the straightlines effect we dont map ... I will map it to lines but i have no idea if it is really a match.
Same with Blendedbars ... which I will map to bars.

Unless you can pay it forward and help us identify better matches unfortunately it is hard to improve this. Thanks to your files I have identified those 2 effects and they will at least map to something in .34.

**Comment by keithsw1111** [comment]
Closing due to no further updates from the reporter.
