### ISSUE TITLE
BAtch Rendering doesn't save sequence after model renaming

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#2179]
**Is your feature request related to a problem? Please describe.**
I have renamed a few models, when I do a Batch render I get a popup to rename the old model to the new model. I have to do that for every sequence in the batch render. The problem is that it doesn't save that renaming of the models after the batch Render.  

**Describe the solution you'd like**
I believe that the issue is, in batch render, it just opens the sequence and renders it, but doesn't save it with the new renamed models. So even though I renamed the model, the change is never saved. Option 1 if possible add a checkbox so save sequence after batch. Option 2 If you are doing a batch Render, remember the settings from the first one and apply them to the rest of the sequences in the batch. 

**Describe alternatives you've considered**
The alternative is to manually open each sequence once, go through the renaming dialog and then save the sequence.

**Additional context**

**Comment by keithsw1111** [comment]
So ... this is deliberate. The problem with saving changes like this during a process like batch rendering is it would be prone to error situations where users would accidentally do things and then have no easy way back from the situation. So we winstead adopted a do no damage strategy.

Could it be solved with some reworking of that code ... possibly but it is extemely brittle code based on the last time on worked on it and the behaviour is not well documented ... particularly some of the edge cases.

A better approach would likely be a total rethink on how we handle opening of sequences that dont match the underlying layout. The challenge is (and the reason it is so messy today) is there is a whole spectrum of approaches and some work well for one or 2 renamed models while others work well for large scale change and yet others work well when you stupidly opened a sequence which has nothing to do with your layout. The current solution tries to do all 3 and it is a bit of a mess.

**Comment by patdelaney** [comment]
Perhaps just table it for a separate utility, under tools to do mass remap/rename.  But yes, the edge cases are the ones that are sometimes hard to code for.  But breaking it out as a separate function under tools is definitely more deliberate so it can’t accidentally do the wrong thing when opening a sequence in batch Render.
