### ISSUE TITLE
System Path prompt when Starting only references Show Directory

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#218]
Using 4.0.25 OS X
I just installed 4.0.25 and I did not have my Disk NAS mounted when I started. I received the error prompt that /Volumes/share/xlights was not found, please configure the directories.

However; when I clicked past that, only the SHOW directory was empty and wanting to be updated, the media and sequence directory still reflected the mount point that was not available. Should they all reflect that they could not be found? 

It appears that only the show directory is being checked for availability and not the other two.

see the screen shot:
![screen shot 2015-04-28 at 3 35 57 pm](https://cloud.githubusercontent.com/assets/10136122/7381005/ba60db1e-edbc-11e4-958a-98867ad5bf44.png)

**Comment by AzGilrock** [comment]
I'm gonna put it back to single show directory if I hear one more thing about it.

**Comment by LightsOnHudson** [comment]
Sorry to hit a nerve?

**Comment by AzGilrock** [comment]
No problem enter all you want.  I'm unsubscribing from the issue list.  If anything actually important gets entered someone can email me that know how to contact me.  Otherwise I will work on things I notice that bother me while I'm sequencing and work on the already mile long list of enhancements we have in our heads.

**Comment by stevegiron** [comment]
Ben, now that the configurable directories are set to Show and Media are you still having this issue?

**Comment by LightsOnHudson** [comment]
Steve,
I'll have to check. And I saw that it is only down to two folders now. I'll test soon.

**Comment by LightsOnHudson** [comment]
This works fine. Just test in 4.0.31
