### ISSUE TITLE
Boscoyo 36" Spinner - wiring view not matching the node layout

### ISSUE THREAD

**Issue by Scott-Tex-Sedam** [smeighan/xLights#2180]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

Very simply the node numbering of the wiring view does not match the node layout view for pixels 9, 10, 33, 34, and 57. I have a screen shot of both that I can put in the drop box. I know this is a small thing compared to what you work on but I found it confusing at first. The node layout is correct. It is just the wiring view that is off.

link to dropbox folder with image of issue. 
https://www.dropbox.com/sh/3p3iqtimzrpd7no/AABFsqfp1YXeEfcLs1K1QsQoa?dl=0

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by priemd** [comment]
I am not able to replicate, just downloaded boscoyo 36" spinner from vendor model download dialog and looks fine here, tried in .32 and .33 with multiple resolutions, zoom in/zoom out, make font larger/small...everything lines up as expected...

![image](https://user-images.githubusercontent.com/2279532/91373226-d8da5080-e7e3-11ea-8963-fa22dc0cc776.png)

Need more info (layout/model file/os, version/etc) if you are still seeing this behavior.

**Comment by Scott-Tex-Sedam** [comment]
David,

                Thank you for getting back to me. I will supply what ever 
information I can to help.



                Current version of Version of Xlights is 2020.33 64bit but I 
pulled down the model in version  2020.28 64 bit using the “create new 
download button and selecting the Boscoyo Spinner 36in from the list.



                This is what I see when I zoom way more than I usually 
would.









This is what I see when I zoom in the max I normally would.









What other information can I supply for you. Please let me know what you 
need and how I can get it for you.





Regards,
Scott Sedam

CTS Networks, LLC.
(c) 508-838-9492
(o) 508-576-5200 xt.225
ssedam@ctsnetworks.com
www.ctsnetworks.com

**Comment by priemd** [comment]
In xLights if you could go to Tools >> Package Log Files and attach the zip, thanks.

**Comment by Scott-Tex-Sedam** [comment]
Please let me know if this is what you need.



Regards,
Scott Sedam

CTS Networks, LLC.
(c) 508-838-9492
(o) 508-576-5200 xt.225
ssedam@ctsnetworks.com
www.ctsnetworks.com

**Comment by priemd** [comment]
You didn't upload the zip...

**Comment by keithsw1111** [comment]
I really dont think this is a bug. There is always tradeoffs when rendering these things in terms of how close or far the number should be from the point. If we fine tuned it for this model it would be bad for another ... thats why we added the zoom in feature. So the question becomes is it really broken ... or just at this zoom it is confusing.

**Comment by Scott-Tex-Sedam** [comment]
Keith,          Thank you for looking at this. I understand your point. I only brought it to the teams attention because it caused me confusion when I was working on the prop and was using the wiring diagram as a guide.           I understand your point about this being a potential case of "wack a mole" and fixing it here could impact other models. You then fix those models and impact others.         I also understand that this could have something to do with my system/video card and how the image is rendered.         You guys have much bigger fish to fry and this could be a one off thing. Thank you very much for taking the time to look into it. I really appreciate the work you guys do.--ScottSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Keith Westley <notifications@github.com> Date: 8/29/20  6:14 AM  (GMT-05:00) To: smeighan/xLights <xLights@noreply.github.com> Cc: Scott-Tex-Sedam <ssedam@ctsnetworks.com>, Author <author@noreply.github.com> Subject: Re: [smeighan/xLights] Boscoyo 36" Spinner - wiring view not matching the node layout (#2180) 
I really dont think this is a bug. There is always tradeoffs when rendering these things in terms of how close or far the number should be from the point. If we fine tuned it for this model it would be bad for another ... thats why we added the zoom in feature. So the question becomes is it really broken ... or just at this zoom it is confusing.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/smeighan/xLights/issues/2180#issuecomment-683269464",
"url": "https://github.com/smeighan/xLights/issues/2180#issuecomment-683269464",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
