### ISSUE TITLE
corrupt settings. 

### ISSUE THREAD

**Issue by jdthomas24** [smeighan/xLights#2184]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by jdthomas24** [comment]
update settings to Controller F16V3 are corrupt.  2 ports are out of order. This is causing one port to not work. I am on newest update via APP Store- .33 

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/5120848/xLightsProblem.zip)

**Comment by jdthomas24** [comment]
<img width="1213" alt="Screen Shot 2020-08-24 at 8 02 35 PM" src="https://user-images.githubusercontent.com/27937586/91110923-caa1fe00-e644-11ea-9fc4-4af19ce5c073.png">

**Comment by keithsw1111** [comment]
Looking at the trace it is hard to tell. It looks like the controller is already corrupt and so xLights keeps that corruption. I am not saying xLights didnt cause it in the first place but that was likely some time ago and now it just keeps it. Consider selecting the Full xLights Control option in which case xLights will ignore anything on the controller and just write what looks like a valid configuration.

**Comment by jdthomas24** [comment]
The controller was running an older Firmware.   I updated the firmware and then flashed the setting from XLIGHTS and the issue corrected. Thank you for the email and getting back with me. 

Jason Thomas
