### ISSUE TITLE
Effect settings randomly enable/disable

### ISSUE THREAD

**Issue by jhoybs** [smeighan/xLights#2186]
**Describe the bug**
I noticed while using the VU Meter effect that the settings controls for it aren't being enabled or disabled properly.  At certain times the settings are disabled (for example saving the file) and are supposed to enabled (for example after a save) after an action is complete.  I'm finding that you can easily be left without access to the settings (ie: they are grayed out). 

**To Reproduce**
1. Load xLights and create a new animation sequence
2. Drop the VU Meter effect on a prop and select it
3. Open the Effect window - sometimes you will notice that the settings controls for the effect are disabled
4. If you perform a "render all" you'll notice that the settings controls will enable after the render
5. Deselect the effect by clicking in the sequencer window (black area)
6. Select the VU Meter again and you'll notice that some of the settings controls are now disabled

**Versions (please complete the following information):**
 - Windows 10 Pro w/latest updates
 - xLights v2020.31

**Comment by keithsw1111** [comment]
Without an example it is hard to tell if this is correct or incorrect ... but I have done a full review and cleanup of the panels and it may address this if it was incorrect. A video of the issue in .34 would help once its out.

**Comment by jhoybs** [comment]
I was able to capture a video of the problem.  It appears to be more than one effect that has a problem.  The
 video shows the problem with Snow Flakes but I'm able to recreate with other effects.

[EffectControls.zip](https://github.com/smeighan/xLights/files/5196709/EffectControls.zip)

I can also provide my zipped sequence file, but it was too big to post here.

**Comment by keithsw1111** [comment]
I am aware of the snowflake problem and it is fixed but if you cant name the others then i am not sure which ones i should be looking at.
