### ISSUE TITLE
xLights gets hung up and will not close

### ISSUE THREAD

**Issue by JMHaro** [smeighan/xLights#2187]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
After I have been editing a couple different sequences, when I started to load another sequence xLights just doesn't want to load the sequence and it will not even shut down.  I end up having to use the Task Manager to be able to close it.  This has happened to me 2 times so far.  The firs time was the very first time I was using it after updating to 33.  And then it just happened to me again.  It doesn't 'appear' to be locked up since it will still save the current sequence but will not close or load anything else.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
Video showing issue (sorry sound didn't record).  
https://www.dropbox.com/s/p5u5qt3qf235spk/2020-08-28_21-03-16.mp4?dl=0
Just in case the uploaded zip file doesn't work.  Here it is on my dropbox:  
https://www.dropbox.com/s/40rby01qj3x75pv/xLightsProblem20200828.zip?dl=0

**Expected behavior**
Expect to be able to load a sequence replacing the one currently loaded, and/or be able to close xLights.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.33

**Additional context**
In the attached xLights_l4cpp.log  It shows me restarting it at line 11106 (so I could get the log files.)
It looks like lines 11077 to 11089 shows where I was trying to close the sequence and trying to stop the program.
If you do need the sequence let me know and I can send it.  But since it's happened to me on two different sequences I didn't think it was them.

I did just realize that I did have the Effect Preset window open since I had been adding some saved effects to my sequence.  But I just now tried reopening the sequence and opened the Effect Preset window, but the xLights didn't have any problems in closing the sequence or exiting.  So I don't know if that did have anything to do with it.

**Attachments**
[xLightsProblem20200828.zip](https://github.com/smeighan/xLights/files/5144693/xLightsProblem20200828.zip)

**Comment by keithsw1111** [comment]
I think i have this fixed in .34 ... I think it relates to rendering jobs being terminated early but not looking finished so it waits indefinitely for them to abort.

**Comment by JMHaro** [comment]
Thank you.
