### ISSUE TITLE
Custom model text is visible when model is not 'custom'

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#219]
Using OS X 4.0.25
When viewing the model properties, the CUSTOM Menu header (icons..etc) is visible when the item is not in custom mode.

This should only be visible when in custom mode? yes?
![screen shot 2015-04-28 at 3 41 35 pm](https://cloud.githubusercontent.com/assets/10136122/7381050/32203780-edbd-11e4-8895-db9ccb1c462a.png)

See attachment.

**Comment by AzGilrock** [comment]
Doesn't bother me to see them there.

**Comment by AzGilrock** [comment]
This is no longer an issue since the layout was re-designed.  You only get the option to pop-up the custom dialog cell editor when you are in a custom model and not all models.
