### ISSUE TITLE
Latest ZIP source fails to compile

### ISSUE THREAD

**Issue by cybie257** [smeighan/xLights#2190]
I don't see any files changed since the ZIP file created for version 2020.34 (at the time of my git clone). On two machines, Mint Linux 19.3 and Ubuntu 20.04, I could not get 2020.33 and .34 to compile. I cannot confirm 2020.32, as I have not tried. 31 and 29 are good. 

I did a git clone and built without incident. I am curious if the zipped up files have some sort of corruption. It does seem to have the same file count when not including the .git vs. .github folders, so I am unsure where the problem is. 

This is more informational as I was able to get a successful build only by doing the manual git pull vs the zip file. I wanted to point this out as I know you don't have a lot of Linux users to report issues and thought you would like to be aware of this finding. 

I did notice that I got errors for undefined issues listed below on the failed ZIP versions:

ControllerSerial.cpp:(.text+0x3495): undefined reference to `GenericSerialOutput::GenericSerialOutput()'
/usr/bin/ld: .objs_lr/outputs/Output.o: in function `Output::Create(Controller*, wxXmlNode*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
Output.cpp:(.text+0x39c7): undefined reference to `GenericSerialOutput::GenericSerialOutput(wxXmlNode*)'
/usr/bin/ld: .objs_lr/controllers/BaseController.o: in function `BaseController::CreateBaseController(ControllerEthernet*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
BaseController.cpp:(.text+0x656): undefined reference to `Minleon::Minleon(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[1]: *** [xLights.cbp.mak:1350: out_linux_release] Error 1
make[1]: Leaving directory '/home/shawn/Downloads/xLights-2020.34/xLights'
make: *** [Makefile:28: xLights] Error 2

Thanks!

**Comment by keithsw1111** [comment]
I think Chris fixed this today. It used to be Windows and Linux shared the same build config but this has changed and sometimes we forget to update the Linux files. If you are going to build regularly you are going to need to learn how to deal with that.

**Comment by cjd** [comment]
Yep - fixed this today.  The codeblocks files were not updated to add the new files so I've added them in

**Comment by cybie257** [comment]
Ok, cool. It was just informational as I figured it was something simple. I like to build as I tend to have less issues when I build directly on the machine I am going to be using it on. :)
Thanks guys!
