### ISSUE TITLE
Clone Group Fails in 2020.34

### ISSUE THREAD

**Issue by kcobbva** [smeighan/xLights#2194]
In Version 2020.34 each time I clone a group Xlights crashes and I get an Xlights.exe has stopped working.  I've tested this on two separate show folders and also in Permanent and Temporary show folders.

**Comment by priemd** [comment]
Cannot recreate, please read through the issue report items that are asked for and at least attach your zipped up show folder and logs.  Please recreate the issue/crash you are experiencing then reopen xLights and go to Tools >> Package Log Files.  Also once you've done this is it a particular group or all groups you attempt to clone?  Have you tried to create a new show directory, add a few models, add them to a group and then attempt to clone that new group?

**Comment by keithsw1111** [comment]
I looked at this crash when i was going through the crash logs and I cant reproduce it ... maybe you can make a video of exactly what you are doing ... some times small things make a difference.

**Comment by kcobbva** [comment]
Hi,

I have reverted back to get a task done.    I will upgrade back to this version at some point today and will capture any issues on video if they occur.  If it works ill close the request.

Kevin

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kcobbva** [comment]
Please close this.    I have reinstalled and went through the same scenarios that were crashing and they are functional this time around.  I cannot recreate the issue so I believe it's a closed issue.
