### ISSUE TITLE
Single Strand - Erratic Display

### ISSUE THREAD

**Issue by byakymyk** [smeighan/xLights#2196]
MacBook Pro 16" 2019 - OS 10.15.6
xLights V34

Single Strand effect is showing erratic display jumping left and right in Model Preview - I have attached video and sample sequence.
[SampleVideo.zip](https://github.com/smeighan/xLights/files/5164711/SampleVideo.zip)
[TEST.zip](https://github.com/smeighan/xLights/files/5164715/TEST.zip)

**Comment by keithsw1111** [comment]
This is not a bug. Its like watching the spokes on a wheel ... at some speeds it will look like its going backwards when it is really going forwards ... just slow it down.
