### ISSUE TITLE
xLights Crashes for Singing Face

### ISSUE THREAD

**Issue by rpFalcon** [smeighan/xLights#2197]
[xLights_dbgrpt-5400-20200902T130432.zip](https://github.com/smeighan/xLights/files/5166145/xLights_dbgrpt-5400-20200902T130432.zip)

Just trying to update model

**Comment by rpFalcon** [comment]
Trying to insert Boscoyo  ChromaBulb 46" Hanging model

**Comment by rpFalcon** [comment]
This is my first issue, how can I get someone to look at the bugreport?

**Comment by keithsw1111** [comment]
Update your video drivers. This is an open GL crash.

**Comment by rpFalcon** [comment]
Can you give me a little more details other than "update video drivers"?

**Comment by AzGilrock** [comment]
Go to the website for your video card, get latest driver, install it.

**Comment by rpFalcon** [comment]
Looks like will have to get a new video card.

**Comment by dkulp** [comment]
In the Preferences panel, you can force xLights to use OpenGL 1.1, but performance will be lower and some things like the shader effect will likely not work.   Might be a temporary solution for now.

**Comment by rpFalcon** [comment]
Set it back to OpenGL 1.1 and it seems to be working. This will help me continue with sequencing. Next step is to get a video card installed.
