### ISSUE TITLE
AppImage missing since 2020.32 release

### ISSUE THREAD

**Issue by TechplexEngineer** [smeighan/xLights#2199]
**Describe the bug**
It seems app image builds are not part of the most recent releases :(

**To Reproduce**
On the releases page releases since 2020.31 are missing the AppImage

**Comment by TechplexEngineer** [comment]
Looks like there is an error in the travis build log:
https://travis-ci.org/github/smeighan/xLights/builds/722440328#L990

**Comment by dkulp** [comment]
This looks fixed with .35 as the appimage is there.
