### ISSUE TITLE
Enhancement request: Label sections of a song for effect repetition

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#220]
If we had the ability to mark sections of a song via highlighting beats as follows:
Intro,Verse, Pre-Chorus, Chorus, Bridge, Outro ,etc..
Each time a section named "Verse" was named it could copy all the effects from the previous section labeled "Verse"

Nutcracker 3.x made this possible via text annotations on the timing grid, and the grid/cell based sequencing with cut/past. This method made sequencing easier/quicker and we only needed to tweak colors and effect directions to make each verse a bit different. 

If the ability to copy/paste more than one model and effect were enabled this could be done manually as well in 4.x

Or perhaps this could be done by inserting a musical symbols (repeat sign) just as we now insert timing marks. 

A sequence could then look like this 

Intro, Verse 1, Chorus
Verse 2, Chorus
Verse 3, Bridge
Chorus, Outro

The time to sequence a song would then be cut down to Intro/Verse/Chorus/Bridge. 

Just thinking out loud here, maybe this is xLights 5.x stuff, who knows.
Thanks!
Steve

**Comment by AzGilrock** [comment]
The timing marks actually have a text field we just aren't displaying it.  If you import from Audacity those labels are saved in case we display them in the future.

You can already copy/paste more than one model and effect.  In my recent sequencing I have 2 models and I'm copying my entire chorus section across both models and pasting it further into the song.

**Comment by stevegiron** [comment]
4.1.13 addresses this. Thanks.
