### ISSUE TITLE
Pixelated Effects on Matrix

### ISSUE THREAD

**Issue by charbaugh1** [smeighan/xLights#2201]
PROBLEM:
I opened up xLigths 2020.34 this evening to find all effects on my matrix extremely pixelated.  If I add a new effect to the matrix in an existing sequence, it too is pixelated.  If I create a new sequence in the same show folder (Christmas), there are no problems and everything looks fine.  Also, the same pixelation exists when playing the sequence on the physical matrix, both in bridge mode or as a stand alone player in FPP.  I have tried opening up 3 or 4 backup folders, and all of the ones I've opened have the same issue.  This issue exists with all of my existing sequences in my Christmas folder.  I was working in a sequence earlier today, and everything was fine.  I changed the show folder to my Halloween folder, and all of those sequences appear normal.  The problem seems to be localized to existing sequence files in my Christmas folder.

No errors occurred

CONFIG:
Windows 10 Pro
xLights 2020.34

SCREENSHOTS:
I attached a screenshot of the Model preview with the Butterfly effect - one shot of an existing sequence and one shot of a new sequence.  

![Capture](https://user-images.githubusercontent.com/64978442/92294204-8db0f380-eeef-11ea-95c5-58ea4cc99807.PNG)
![Capture2](https://user-images.githubusercontent.com/64978442/92294206-90134d80-eeef-11ea-8661-11695646aaa2.PNG)

SEQUENCE
Attached is the packaged sequence file (O Come All Ye Faithful) that I'm working on currently that has the issue reported.  I've also attached a sequence from my Halloween folder (Ghostbusters) that shows how it looks normally.

[TSO -  O Come All Ye Faithful _ O Holy Night (Instrumental).zip](https://github.com/smeighan/xLights/files/5177425/TSO.-.O.Come.All.Ye.Faithful._.O.Holy.Night.Instrumental.zip)

[Ghostbusters.zip](https://github.com/smeighan/xLights/files/5177431/Ghostbusters.zip)

**Comment by keithsw1111** [comment]
This happens because you are not putting it on the matrix ... you are putting it on the group. While I can see an argument that says this should not generate such a pixelated buffer the problem that has it would break so many people's displays that the change is just not possible.
If you want the high res - just put the effect on the model.
