### ISSUE TITLE
Controllers --> visualizer

### ISSUE THREAD

**Issue by lewislawrence2** [smeighan/xLights#2202]
**Is your feature request related to a problem? Please describe.**
i am a new user... I am using the visualizer page to map pixels to controllers

**Describe the solution you'd like**
By right clicking on the visualizer page, there is an option to print.  I would like the print to be larger.  Instead of shrinking all to fit on one page, could it default to fit on 2 or 3 pages tall?  or be scalable?

**Describe alternatives you've considered**

**Additional context**

**Comment by Kosh42** [comment]
I get that. I have a Kulp 32 with half a dozen differential receivers, and I need a magnifying glass to read the print ;)

**Comment by sslupsky** [comment]
A common UI way to do so is the add a "scale" box and a "scale to fit" checkbox.

Similarly, add support for printing portrait and landscape.

**Comment by keithsw1111** [comment]
The problem is the amount of code that has to be written to support multi-page. While not a bad idea its going to take someone quite motivated to implement it all.

**Comment by lewislawrence2** [comment]
No worries, thanks for the comment.

Best,
Lewis

**Comment by computergeek1507** [comment]
This has been added
