### ISSUE TITLE
XLIGHTS .34 crashes every single time a model group is created

### ISSUE THREAD

**Issue by jblue502** [smeighan/xLights#2203]
.34 crashes every time I try to create a single model group. See the 4 crash report files.
[xLights_dbgrpt-9964-20191001T214555.zip](https://github.com/smeighan/xLights/files/5179876/xLights_dbgrpt-9964-20191001T214555.zip)
[xLights_dbgrpt-10264-20200906T112214.zip](https://github.com/smeighan/xLights/files/5179877/xLights_dbgrpt-10264-20200906T112214.zip)
[xLights_dbgrpt-18832-20200803T233544.zip](https://github.com/smeighan/xLights/files/5179878/xLights_dbgrpt-18832-20200803T233544.zip)
[xLights_dbgrpt-22924-20200906T111322.zip](https://github.com/smeighan/xLights/files/5179879/xLights_dbgrpt-22924-20200906T111322.zip)

**Comment by keithsw1111** [comment]
I believe i fixed this for .35 a few days ago.
