### ISSUE TITLE
Copy/Paste of lyric tracts intermittently working.

### ISSUE THREAD

**Issue by Poporacer** [smeighan/xLights#2205]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
You cannot cut and paste sections of a lyric tract. Sometimes (but rarely) it will work on first boot up but most of the time you cannot copy a lyric tract to a different lyric track. There is plenty of room on the timeline and I tried it with the timing tract active and not active. I tried it with several elements and just one element, none of them worked.

**To Reproduce**

See attached video at https://drive.google.com/file/d/1g0OIBLuTrTVR-C0bKr2i8xp9VBBc1b7d/view?usp=sharing

1. Select a portion of lyrics from one lyric tract
2. Right click, select copy
3. Left click on the lyric tract where you want to paste, right click and paste

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.34

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
I tried and it seems to work fine ... not sure how you got into that state from the video.

**Comment by Poporacer** [comment]
OK, so in researching this, I came across some strange behavior. The steps below were repeated several times (20-30 times) so that I could document the exact steps I took so that you could hopefully recreate it on your end. But then I tried to make a video to demonstrate it and I had to make several takes because I kept screwing it up and then I must have made some slight change that reset something because after about the 4th try at the video, it actually started working as intended?? So for the most part it is fixed. One issue still lingers as noted below. I included what I discovered when it wasn't working in case the issue comes up again. 

This is the original post before it somehow got fixed.....

A little more info and maybe I have found a pattern and a different issue possibly related? It looks like it has something to do with the Render?
** This is now not relevant** I attached the sequence I am working on so that you can try to duplicate it. (And another video in case you can't duplicate)

1. Open the sequence and copy a section of lyrics and paste, it works fine.
2. Play a portion of the timing line to play (by highlighting the timeline or the waveform) then the singing tree shows no output whatsoever, but it actually appears to be with the whole house group, the Singing tree is in the Whole House group.. Nothing was changed to the Whole House group so it shouldn't be affected by adding some lyrics? 
3. Render All and if I play a section again, the tree and other models on the house preview show up correctly,
4. Select the model and the model preview shows up and appears to be working, but then if a section of the timing track is played, the Tree on both the Model preview and House preview are blank.

And at this point Copy and pasting no longer work, It looks like the copy might not be copying the data correctly? 

So in evaluating the Copy/Paste in a little more detail I found some interesting results.

Open the sequence and copy a section of lyrics ("You Gave it away" starting at at 3:10.900) The copied data is:

CopyFormat1	15	0	8	1	-1	NO_PASTE_BY_CELL
Faces			207525	207775	4	-1000	TIMING_EFFECT
gave			207775	208050	4	-1000	TIMING_EFFECT
it			208050	208325	4	-1000	TIMING_EFFECT
away			208325	209400	4	-1000	TIMING_EFFECT
etc			207525	207575	5	-1000	TIMING_EFFECT
U			207575	207775	5	-1000	TIMING_EFFECT
etc			207775	207825	5	-1000	TIMING_EFFECT
E			207825	207975	5	-1000	TIMING_EFFECT
FV			207975	208050	5	-1000	TIMING_EFFECT
AI			208050	208275	5	-1000	TIMING_EFFECT
etc			208275	208325	5	-1000	TIMING_EFFECT
AI			208325	208550	5	-1000	TIMING_EFFECT
WQ			208550	208650	5	-1000	TIMING_EFFECT
AI			208650	209225	5	-1000	TIMING_EFFECT
E			209225	209400	5	-1000	TIMING_EFFECT
And it pastes just fine

********************This issue below still exists**********************
If I copy the section "Special" starting at 3:19.125 the copied data is:

CopyFormat1	7	0	8	1	-1	NO_PASTE_BY_CELL
special			199125	201175	4	-1000	TIMING_EFFECT
etc			199125	199175	5	-1000	TIMING_EFFECT
MBP			199175	199225	5	-1000	TIMING_EFFECT
E			199225	199625	5	-1000	TIMING_EFFECT
etc			199625	199750	5	-1000	TIMING_EFFECT
AI			199750	200550	5	-1000	TIMING_EFFECT
L			200550	201175	5	-1000	TIMING_EFFECT

And it will paste, but the word no longer shows as "Special" but now shows as "faces" this is consistent with selecting only one word.
*****************************end of existing problem****************************
Now for the strange part.

Start with fresh sequence
Copy and paste a section of lyrics ("You Gave it away" starting at at 3:27.525) The copied data is: 

CopyFormat1	15	0	8	1	-1	NO_PASTE_BY_CELL
Faces			207525	207775	4	-1000	TIMING_EFFECT
gave			207775	208050	4	-1000	TIMING_EFFECT
it			208050	208325	4	-1000	TIMING_EFFECT
away			208325	209400	4	-1000	TIMING_EFFECT
etc			207525	207575	5	-1000	TIMING_EFFECT
U			207575	207775	5	-1000	TIMING_EFFECT
etc			207775	207825	5	-1000	TIMING_EFFECT
E			207825	207975	5	-1000	TIMING_EFFECT
FV			207975	208050	5	-1000	TIMING_EFFECT
AI			208050	208275	5	-1000	TIMING_EFFECT
etc			208275	208325	5	-1000	TIMING_EFFECT
AI			208325	208550	5	-1000	TIMING_EFFECT
WQ			208550	208650	5	-1000	TIMING_EFFECT
AI			208650	209225	5	-1000	TIMING_EFFECT
E			209225	209400	5	-1000	TIMING_EFFECT

Then Render all.

Copy the lyrics that were just pasted and the copied data is:

CopyFormat1	15	0	8	1	-1	NO_PASTE_BY_CELL
Faces	E_CHOICE_Faces_Eyes=Auto,E_CHOICE_Faces_FaceDefinition=Default,E_CHOICE_Faces_Phoneme=AI	C_BUTTON_Palette1=#FFFFFF,C_BUTTON_Palette2=#FF0000,C_BUTTON_Palette3=#00FF00,C_BUTTON_Palette4=#0000FF,C_BUTTON_Palette5=#FFFF00,C_BUTTON_Palette6=#000000,C_BUTTON_Palette7=#00FFFF,C_BUTTON_Palette8=#FF00FF	215600	215850	4	-1000	TIMING_EFFECT
gave			215850	216125	4	-1000	TIMING_EFFECT
it			216125	216400	4	-1000	TIMING_EFFECT
away			216400	217475	4	-1000	TIMING_EFFECT
etc			215600	215650	5	-1000	TIMING_EFFECT
U			215650	215850	5	-1000	TIMING_EFFECT
etc			215850	215900	5	-1000	TIMING_EFFECT
E			215900	216050	5	-1000	TIMING_EFFECT
FV			216050	216125	5	-1000	TIMING_EFFECT
AI			216125	216350	5	-1000	TIMING_EFFECT
etc			216350	216400	5	-1000	TIMING_EFFECT
AI			216400	216625	5	-1000	TIMING_EFFECT
WQ			216625	216725	5	-1000	TIMING_EFFECT
AI			216725	217300	5	-1000	TIMING_EFFECT
E			217300	217475	5	-1000	TIMING_EFFECT

And this looks way different than the original and it won't paste probably because it is in the incorrect format?

**Comment by keithsw1111** [comment]
I may have this fixed for .36 ... at least the bottom issue.

**Comment by Poporacer** [comment]
Thanks, 
And the strange render issue came up again but then resolved before I could take a video :( 
But a common thread is that the group that is affected by this oddity has a shader effect on it.

**Comment by keithsw1111** [comment]
I believe this is fixed.
