### ISSUE TITLE
Upload Inputs/Outputs  to F16 V3 on 2020.35

### ISSUE THREAD

**Issue by xlights33** [smeighan/xLights#2207]
upgraded to 2020.35 and not able to upload inputs/outputs to a falcon F16V3   
down graded to 2020.34 and back to working  same config  works with or with out force local ip 

i can open connection from xlights to the falcon controller with the open button 

setup is 
pc  192.168.1.19     wireless
      192.168.2.1       ethernet (connected to a linksys switch that the controller is connect to ) 

falcon controller    192.168.2.11    gateway 192.168.2.1

tried to set  force local ip set  to 192.168.2.1 same thing not able to upload to controller 

Joe

**Comment by keithsw1111** [comment]
I would need sample files to see if we can reproduce it. Alternatively log files might help if you grab them immediately after trying to reproduce it.

Jumping into zoom is also likely to help. If its an error on your part they will find it and fix it.

**Comment by xlights33** [comment]
I was on the zoom meeting and they could not find anything wrong  as i changed no settings   on my network and just down graded to 20202.34 and worked    i will jump on the zoom tonight and see if they can help me with what logs to send 
 or if you can let me know what you need from where and i can attach it

**Comment by keithsw1111** [comment]
tools/package logs creates the files we need.i alse need to know which controller.

**Comment by xlights33** [comment]
Falcon f16 v3 with 3 exp boards running 2.55

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by xlights33** [comment]
i reloaded ver 2020 35 and tried it again and all good  not sure what happened
