### ISSUE TITLE
Mac Builds Not Building

### ISSUE THREAD

**Issue by jeffla** [smeighan/xLights#2208]
xLights seems to be working fine, but the latest Mac build is .31... or have they moved?

**To Reproduce**
1. Go to http://dankulp.com/xlights/
2. Scroll to the bottom
3. Observe latest build version

**Expected behavior**
A version closer to the Windows release.

**Comment by dkulp** [comment]
The https version of the link had the proper header but it wasn't appearing on the non-ssl version.  Just fixed that.

In any case, the primary way xLights is now distributed on the Mac is via the Mac App Store:
https://apps.apple.com/us/app/xlights/id1137297689?mt=12
