### ISSUE TITLE
Release 27 Models disappearing while sequencing   

### ISSUE THREAD

**Issue by RichardRennII** [smeighan/xLights#221]
I found an issue when working with the toggle strands and nodes as I would as I would toggle them to close them my models would close up and disappear leaving me no models in the sequence. I saved the work done closed it and reopened the sequence and the models where there

![image](https://cloud.githubusercontent.com/assets/11212370/7400882/f6ad8050-ee8d-11e4-84ae-6e34849bffb1.png)

**Comment by kppankratz** [comment]
I noticed that earlier too, but I found that I simply had to scroll up to the top using the scroll bar on the right.  Seems like when the strands are being collapsed that the model is being hidden behind the timing mark row.

**Comment by stevegiron** [comment]
Are seeing this with 4.0.31? Can we close this ticket?

**Comment by kppankratz** [comment]
This is still an issue that I can recreate in 4.0.31.  I have a MT with 16 strands of 85 nodes.  If I toggle the strands, then toggle the nodes of strand 1, scroll down to strand 2 and toggle the strands to collapse everything it appears as if the whole model just fell off the sequencing grid.  You have to scroll up in the grid to make it reappear.

**Comment by stevegiron** [comment]
I have seen this too as kppankratz has described. Marking as Bug-Minor.

**Comment by stevegiron** [comment]
Changing to trivial as it's just the need to scroll up after you close the strand view.  I'm thinking we close this altogether.

**Comment by kppankratz** [comment]
Personally, I wouldn't close the ticket until it's been resolved.  Yes, it's a trivial thing, but I panicked when it appeared that I had a model disappear off of the grid.

**Comment by dkulp** [comment]
Fix is coming in a couple hours
