### ISSUE TITLE
XSchedule - UI to allow bypass of password for certain plugin pages

### ISSUE THREAD

**Issue by Shane8johnson** [smeighan/xLights#2211]
**Is your feature request related to a problem? Please describe.**
Would like plugin pages such as "not so big buttons" to be excluded from password protection. 

**Describe the solution you'd like**
I would like a way to select plugin pages to **not** be protected with the password, in xschedule. All other pages would remain password protected. Preferably this would be via a UI on the xschedule options interface. 

**Describe alternatives you've considered**
NA

**Additional context**
I am not a developer by any means, but I do have a basic understanding of HTML,CSS,Javascript. If anyone has a suggestion for a code snippet that could be included in the plugin page I wish to exclude password protection, that would work as well. (I have created a child plugin based off the "not so big buttons" script, so that my changes will not be overridden when Xlights updates.)

It appears that the current setup is looking in the core.js file and determining if the user is logged in by calling to the xSchedule API. If a user is not logged in, then it redirects to the login.html page. Me editing the core files are not a feasible solution because this will be overridden when xlights updates.

**Comment by keithsw1111** [comment]
I have added a sample file called guestbuttons.html which is a self contained page which will work even if password is set ... as long as you set the right options ... you need to enable this behaviour.

**Comment by Shane8johnson** [comment]
Keith, Firstly, thank you for the great work on this! This is exactly what I'm looking for and it works wonderfully. 
Do you have any resources that would be helpful in learning how to use websockets with the Xlights API? 

I'm wanting the following to display on the guestbuttons.html page, but it doesn't display. ([Image here](https://imgur.com/mn9UpRx)) Presumably because the pageHome.js file is calling on the query for "getPlaylists" and it's returning a user not logged in error. (If i'm understanding everything correctly.)

How can I convert the following to work on websockets instead of the existing scrips in pageHome.js ?
** *As a note, I would not, and am not asking for you to invest your time writing code for my personal project.** You invest plenty already into our Xlights Enhancements and Bug fixes for us.  I'm hoping you can simply point me in the right direction on how to rewrite the dashboardLoadStatus and the populateTablePlaying functions (assuming those are the only two needed?) to work with websockets and your PASS variable. 


When I page a custom plugin page, I just used the following, and it works fine (again presumably because the user is logged in at that point)
`
            <div class="panel panel-default">
              <div class="panel-heading main-color-bg">
                <h3 class="panel-title">Currently Playing:
                  
                </h3>
              </div>
              <div class="panel-body">
                <div class="span6 text-center">
                  <div id="currentStep"></div>
                  <div id="stepStatusBarContainer" style="padding-left:12px; padding-right:16px;"></div>
                  
                </div>
              </div>
              </div>`

**Comment by keithsw1111** [comment]
Its actually trivial because xSchedule already sends you the status every second. I added a handleStatus function to the page which you can add code to to update playing playlist etc.

To see the API documentation check out the API document in the xSchedule folder on GitHub.
