### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by caniac97** [smeighan/xLights#2216]
Crash on visualize of controller with AC components
[xLights_dbgrpt-13280-20200910T072259.zip](https://github.com/smeighan/xLights/files/5201729/xLights_dbgrpt-13280-20200910T072259.zip)

**Comment by caniac97** [comment]
why is this closed?  what is the resolution?

**Comment by AzGilrock** [comment]
He probably either fixed it or it’s because this is a terrible bug report.  The template told you the info we need.  Can you reproduce the crash?  We already get that zip file don’t really need you posting it unless you add you add useful steps to reproduce the crash.

**Comment by caniac97** [comment]
yes it can be reproduced, every time I go into visualize on that one controller (the only one with AC components) it crashes and produces the zip file.
