### ISSUE TITLE
Moprh head color

### ISSUE THREAD

**Issue by Phrog30** [smeighan/xLights#222]
I'm having issues getting the head color correct.  I have a morph that sweeps right across 12 mini trees.  I have 3 colors, red, green, and black.  I use black to better fade.  On options, nothing is checked.  The effect is over 3 seconds in length.  I can have head duration turned all of the way up, and yet, the color red only shows very briefly.  

The main issue, what shows in the sequence is not representative of what plays.  To me, if it shows 2 seconds of red, it should be playing red.

**Comment by AzGilrock** [comment]
The morph head color should be working fine now.  Here's a couple screenshots that show how it maintains a solid color or transitions between two colors if setup that way:

![morphheadcolor](https://cloud.githubusercontent.com/assets/2024669/7664583/f0aa13e0-fb43-11e4-8498-2ddb90a3ba95.jpg)
![morphupdate](https://cloud.githubusercontent.com/assets/2024669/7664584/f2ad021a-fb43-11e4-87a8-b8381b6228e6.jpg)
