### ISSUE TITLE
app image doesnt run latest version

### ISSUE THREAD

**Issue by thedannymullen** [smeighan/xLights#2221]
I noticed the app image file size changed.  I am running ubuntu 20.04.  When I try to run the latest releases they give an error, I am wondering if there is something missing in the build.

```anny@Big-Gray-Linux:~/Downloads$ ./xLights-2020.36-x86_64.AppImage 
/tmp/.mount_xLightwhPfdD/AppRun.wrapped: error while loading shared libraries: libx265.so.146: cannot open shared object file: No such file or directory
danny@Big-Gray-Linux:~/Downloads$ 
```

**Comment by extremeskillz** [comment]
Same issue here. On 20.04LTS and can not open this appimage. I sent back to .23 for now.

**Comment by SonnyJim** [comment]
Same issue, Linux Mint.  I'm guessing they've forgotten to include several static libs, seeing as the filesize dropped 20mb or so.

Last working version I can use is 2020.31

**Comment by thedannymullen** [comment]
Glad it is not only me...

**Comment by lotusnopes** [comment]
I've got the same problem on Pop_OS! (basically Ubuntu 20.04:
`/tmp/.mount_xLightKQeekB/AppRun.wrapped: error while loading shared libraries: libx265.so.146: cannot open shared object file: No such file or directory`

Also tried adding the repo:
`/tmp/.mount_xLightKQeekB/AppRun.wrapped: error while loading shared libraries: libx265.so.146: cannot open shared object file: No such file or directory`

**Comment by CaffeinatedFunctionality** [comment]
Also same. Following

**Comment by tgodfrey73** [comment]
Chris D. manages the linux builds. Sent him a FB message about this for awareness.

**Comment by cjd** [comment]
It is now working when building locally via https://github.com/cjd/xlights-build-docker
I've pushed an updated docker image (which is used for the auto builds) so hopefully on next release this will fix up

**Comment by thedannymullen** [comment]
@cjd thanks!  Glad you found a problem, I will keep my eyes out to verify the fix!  Thanks for the builds also!

**Comment by tgodfrey73** [comment]
appImage 2020.40 appears to be working for me. Thanks!

**Comment by lotusnopes** [comment]
Yeah, it's working for me too, thanks!

**Comment by SonnyJim** [comment]
Working fine on Linux mint.  This issue can now be closed.
