### ISSUE TITLE
Faces Settings on Mac doesn't load timing tracks

### ISSUE THREAD

**Issue by wilsoc5** [smeighan/xLights#2222]
Running 2020.37 on Mac 10.14.6.

Timing track list for Faces effect is never updated. 
 

0. Start xLights
1. Loaded a singing faces model from download website (Boscoyo ChromaCharacter Tree)
2. Create new musical sequence
3. Add song in wizard
4. Select 20 fps
5. Quick start
6. Right click "New Timing" timing channel, add Lyrics
7. Continue following instructions under **Timing Tracks** section for singing face in Manual: https://manual.xlights.org/xlights/chapters/chapter-four-sequencer/singing-faces
8. Get down to text box saying "If the Timing track name (‘Lyrics1’) does not appear in the list of Timing Tracks, click on another effect and then return to the Face effect to force the list to be refreshed." in manual
9. Add new effect to be able to force the list to be refreshed. 
10. Reclick to Face effect and ensure "Timing Track" is selected
11. Drop down list is never refreshed. 
12. Restart xLights
13. Load sequence
14. Try 10 again. 
15. Still no luck. Try creating new timing track
16. Add lyrics to new timing track
17. click on other effect
18. Click back to face effect and toggle timing track to phoneme and back again.
19. List still not updated. 

**Expected behavior**
Expect to be able to specify the timing track for the faces to enable singing faces. 

**Screenshots**
<img width="1242" alt="Screen Shot 2020-09-13 at 01 08 38" src="https://user-images.githubusercontent.com/11683051/93011798-29c9a300-f55f-11ea-864d-3ccfa726a7b1.png">

**Versions (please complete the following information):**
 - OS: Mac 10.14.6
 - xLights version 2020.37

**Additional context**
Relatively new user (but experienced C++ developer) so I could just be screwing something up, but I followed the manual to the letter and cannot get the Timing Track list to reload. I'm filing this bug report while I peruse the code. It's been a while since I dealt with WxWidgets. 

**Attachments**
(see the screenshot above)

**Comment by dkulp** [comment]
You haven't broken the timing track down into phonemes yet.   It won't appear until it has all three layers.

**Comment by wilsoc5** [comment]
Yep. Newbie mistake. Thanks for the prompt reply. I might suggest adding that as part of the 
```
If the Timing track name (‘Lyrics1’) does not appear in the list of Timing Tracks, click on another effect and then return to the Face effect to force the list to be refreshed.
``` 
block in the manual.
