### ISSUE TITLE
Mac: House preview full screen for multiple desktops

### ISSUE THREAD

**Issue by bedawg10** [smeighan/xLights#2223]
**Is your feature request related to a problem? Please describe.** NO
Every time I'm working with xlights on my macbook without my second screen I have an issue with the house preview being visible enough. When I drag it out to its own window (like I would do with multiple monitors) it attaches its self back within xlights. This isn't a bug, it's just really finicky on where I can put the window. 

**Describe the solution you'd like**
It would be really great if the house preview screen could be expanded into full-screen mode (the green button for "enter full-screen mode"). this would put it on a second desktop and would allow you to gesture between the sequence and the house preview. Currently, if you expand the house preview to full screen it sits in front of the sequence screen and the sequence screen is inaccessible. 

https://www.dropbox.com/s/6l8ibsi4b76pgqp/Screen%20Recording%202020-09-13%20at%208.50.59%20PM.mov?dl=0

**Comment by dkulp** [comment]
If you hold CMD while dragging the window around, it won't re-dock.  This is as designed.

**Comment by bedawg10** [comment]
Awesome! Thanks for letting me know. 

Brandon Clark
386-864-0455
