### ISSUE TITLE
Interface broken, displays with wrong resolution to the actual interface 

### ISSUE THREAD

**Issue by fone626** [smeighan/xLights#2224]
[2020-09-13 20-47-44.zip](https://github.com/smeighan/xLights/files/5216058/2020-09-13.20-47-44.zip)
![xlights_interfave_bug-comments](https://user-images.githubusercontent.com/38029943/95063780-a7428800-06b3-11eb-9239-eaf6daa85ef0.jpg)

**Describe the bug**
On the options for the controllers, and the options for the models under the layout tab (there may be more) shows in a different resolution to the rest of the interface.  In other words the interface either looks too big or too small, but the real, usable and correct size interface is invisible until you've clicked on the position that that it's supposed to be in and it's selected.  This leaves you having to click up and down the visually wrong sized interface, often completely out of the visible interface, in order to select the option you want to edit. It's difficult to be sure what you've actually selected.  This makes editing those options extremely frustrating.
I've attached a video so you can see what I'm, badly, describing.  The options interface displays too small on the computer I recorded the video on, but too big on 3 other laptops I've tried it on.  This behavior started with version 2020.30.

**To Reproduce**
Open xLights and click on any controller or a model.  The options for it won't be the correct size. and when you click on something it doesn't necessarily select what you clicked on.

**Expected behavior**
The interface you see is the interface you get.

**Screenshots**
I've attached a zipped video showing the problem.

**Versions (please complete the following information):**
 - OS: Linux (Kubuntu 20.04 and KDE neon 20.04)
 - xLights versions 2020.30 thru 2020.56

**Comment by jacob-swenson** [comment]
I'm also seeing this issue on 2020.40. Pop!OS using GTK Theme Adwaita-dark (in-case that matters).

**Comment by mmcauley1** [comment]
I am also having this same issue on versions 2020.30 thru 2020.42.  Linux Mint 19.3 (Cinnamon).  The Properties windows on the Controllers and Layout tabs are affected.

**Comment by mghaff007** [comment]
I was able to fix my mouse being out of sync by changing my screen resolution than changing it back in ubuntu. fixed my issues!

**Comment by fone626** [comment]
Changing resolution made it go from too small to waaaaay too big for me.
![Screenshot_20201007_021444](https://user-images.githubusercontent.com/38029943/95313659-3af78e00-0845-11eb-9167-f1006b811853.jpg)

**Comment by mmcauley1** [comment]
I agree with fone626.  Changing the resolution did NOT help or fix anything.

**Comment by kalebr3** [comment]
Same issue here, seen on the screenshots of the controllers and layout screens.

**Machine Version Information**
![Screenshot from 2020-10-09 17-13-26](https://user-images.githubusercontent.com/31462347/95632064-d4e05600-0a52-11eb-8434-f63b0894b261.png)

**xLights Screenshots (Version 2020.42)**
![Screenshot from 2020-10-09 17-06-38](https://user-images.githubusercontent.com/31462347/95632107-ec1f4380-0a52-11eb-8805-b9a2d614f1fa.png)
![Screenshot from 2020-10-09 17-06-50](https://user-images.githubusercontent.com/31462347/95632113-ef1a3400-0a52-11eb-97f1-71dd9aa6a720.png)

**Comment by jacob-swenson** [comment]
As said by others, changing the resolution did not solve the problem. Neither did changing GTK Theme.

**Comment by jacob-swenson** [comment]
Still an issue in 2020.43

**Comment by ajpri** [comment]
Noticed that the issue is much worse when using a 4K resolution. Changing res down to 1080p makes it better but still bad. Probably something with the scaling.

**Comment by mghaff007** [comment]
Changing Te resolution only fixed one of my problem's but it came back after i reloaded xlights and now it will not go away. Sorry everyone i was trying to help. But now i got more issues and might just have to reinstall my os and start from scratch.

**Comment by ajpri** [comment]
Decided to test with Wayland the same results. Impacting both x11 and Wayland. Ubuntu 20.04.

**Comment by drasch** [comment]
Same issue with Ubuntu 20.04 and 4k screen

**Comment by reenx** [comment]
I did some investigating and discovered that the issue is the result of the update of wxWidgets to the version xlights_2020.30.
Further investigating pinpointed that the problem starts with the commit of wxwidgets 1422991 were the propgrid is modified to use GetDPIScaleFactor in stead of GetContentScaleFactor. 
I am not that familiar with xLights of wxWidgets  to further determine if this is a xLights or wxWidgets problem. But this information might help someone else fix this.

**Comment by mmcauley1** [comment]
Still an issue in AppImage 2020.51.   Last usable AppImage is 2020.29.

**Comment by MoulderUtes** [comment]
I also have this issue on gnome manjaro, app image 2020.56 and 57.

**Comment by fone626** [comment]
I've checked it on one of the laptops and my desktop computer and so far the bug appears to have been fixed in 2021.01.
Many thanks goes to whoever fixed it. This bug made doing my first show ever this last season extremely difficult.
