### ISSUE TITLE
Xschedule Add all Fseq below subdirectory

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#2226]
**Is your feature request related to a problem? Please describe.**
Moved my show folder, and doesnt seem to be an easy way to add all fseq's from a directory/subdirectories,

**Describe the solution you'd like**
Be able to select my sequences folder, and have it scan and show a list like the batch render xlights dialog to allow you to click on
the sequences you want to add to a playlist, rather then having to add 1 by 1,

My show folder structure is
/Home/Shows/SequenceName/Sequence.fseq

Your thoughts appreciated.

**Comment by keithsw1111** [comment]
You can already do this two ways:

1. Shift or ctrl click when adding and select multiple.
2. Drag and drop from your file explorer onto the tree in the playlist editor.
