### ISSUE TITLE
E1.31 Output Uploads to FPP

### ISSUE THREAD

**Issue by Kosh42** [smeighan/xLights#2227]
**Is your feature request related to a problem? Please describe.**
I have a few WLED controllers in my show. These work when I output from from xLights and my FPP instance goes into Bridge mode. But when I play from my BBB on a Kulp board (in master) the WLED controlled lights don't work by default. I have to manually add the E1.31 outputs to FPP.

**Describe the solution you'd like**
I'd like the FFP connect tool to upload E1.31 output to WLED in FPP as well as FPP remotes.

**Describe alternatives you've considered**
Manually adding each WLED as an E1.31 controller in FPP.

**Comment by computergeek1507** [comment]
If you have the wled controllers added in the Controller tab. If you set the UDP Out drop-down to All, in FPP connect, it will upload the E131 outputs to the FPP controller.

**Comment by Kosh42** [comment]
Many thanks, works a treat. I'll close this.
