### ISSUE TITLE
Renaming models crashes app

### ISSUE THREAD

**Issue by Phrog30** [smeighan/xLights#223]
I had several models I renamed.  These models were in the sequencer.  When I renamed, this didn't push to the sequencer.  On save the app crashed.  When I reopened, it asked if I wanted to delete or rename.

**Comment by stevegiron** [comment]
Hello, I'm helping sort the issues and determine which issues are still valid. 
As of May-14 we are version 4.0.31. Is this issue still occurring?

**Comment by Phrog30** [comment]
Yes, nothing has been done to fix this, so it is still occurring.

To test, add a model in the sequencer, then rename the model in the 
preview tab.  You will notice the name change did not push to the 
sequencer.  This will in turn cause a crash.

James

------ Original Message ------
