### ISSUE TITLE
HinksPix Pro controller unable to upload output

### ISSUE THREAD

**Issue by ChadOhman** [smeighan/xLights#2232]
**Describe the bug**
I consulted with the xLights Zoom room (thank you, gentlemen!) and are finding that I cannot upload output from xLights to the HinksPix Pro controller. The application hangs for some time and then an error appears that says "Unable to connect to HinksPix '/GetInfo.cgi'." and "Error connecting to HinksPix controller on 10.0.0.64."

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a HinksPix Pro controller
2. Select the controller on the Controllers tab, confirm a green light.
3. Click "Upload Output"

**Expected behaviour**
Expected to see the upload complete successfully and output settings change on the controller to what's in xLights.

**Screenshots**
![image](https://user-images.githubusercontent.com/2351/93689291-4e0b0f80-fa8a-11ea-8484-7de38ff61a14.png)
![image](https://user-images.githubusercontent.com/2351/93689371-3da76480-fa8b-11ea-8772-63f2c2935b36.png)
![image](https://user-images.githubusercontent.com/2351/93689389-56177f00-fa8b-11ea-897f-0ebd80227bc2.png)

**Versions (please complete the following information):**
 - OS: Windows 10 Pro 2004 (build 19041.508)
 - xLights version 2020.38 64bit

**Additional context**
This does not appear to be sequence related.

**Attachments**
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/5250636/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
@computergeek1507 it was suggested that maybe there is new firmware that breaks the upload.

**Comment by bkschuster** [comment]
I am experiencing the same issue with both the upload of inputs and outputs. 

On the inputs, it often does not ever come back with an error. While it is hung, you can't get to the controller web interface either. If you end task xlights (Windows10) then it frees us the web interface on the controller most of the times. Other times you need to unplug the controller and let it reboot before you can get back to the web interface. 

I did notice that the controller just had a new firmware update and also that Joe Hinkle is working on changes to the controllers configuration page per his latest video https://www.youtube.com/watch?v=0E3dzLrHl98&t=3s it is very possible that is the cause of the issue.

**Comment by computergeek1507** [comment]
I can reproduce it with my controllers, I will try to fix it soon.

**Comment by Joeh311** [comment]
I am having the same problem.  Has anyone found a solution?  Thanks

**Comment by computergeek1507** [comment]
Please try this test build and see if it fixes the issue. https://drive.google.com/file/d/1Er9ZaGF44G97GTjx0CgVGFlr-1koSnYg/view?usp=drivesdk

**Comment by ChadOhman** [comment]
Brilliant.

![image](https://user-images.githubusercontent.com/2351/94703286-ec556b80-02fb-11eb-83d1-cae3db9c469e.png)
![image](https://user-images.githubusercontent.com/2351/94703241-e069a980-02fb-11eb-878b-796197091497.png)

**Comment by bkschuster** [comment]
Sorry for the delay in my response but I have tested with the test build and it works for me as well. Thanks for fixing this.

**Comment by ChadOhman** [comment]
It looks like Joe is back at it again... he's changed something and now it doesn't upload anymore.

I wish he would stop messing with things.

**Comment by computergeek1507** [comment]
I have firmware 85 and it is working correctly for me.
![image](https://user-images.githubusercontent.com/2293065/95006073-0f1ea300-05ce-11eb-872a-efe6de7692ee.png)

**Comment by ChadOhman** [comment]
Interesting, I have 85 as well now and I'm back to the same errors I had before.

**Comment by computergeek1507** [comment]
Firmware 101 has specific xLights APIs, should be good now
