### ISSUE TITLE
New Versions Not To Change File Locations

### ISSUE THREAD

**Issue by Kosh42** [smeighan/xLights#2233]
**Is your feature request related to a problem? Please describe.**
Every time I upgrade to a new version, my Backup and Render Cache folders default back to using the show folder, not the folder I had previously defined.

**Describe the solution you'd like**
I'd like a new install to to overwrite my preferences on where to save backups and render cache.

**Describe alternatives you've considered**
Only way around it is to change it every time. If you forget, Google drive gets very full, very fast.

**Comment by keithsw1111** [comment]
Are you just installing the new version ... or uninstalling and reinstalling? What operating system?

**Comment by Kosh42** [comment]
Just installing the new version, not uninstalling first. And Windows 10 Home, but I've had it in Pro too.

Happens on both my laptop and desktop (hence the Google drive synced show folder).

**Comment by keithsw1111** [comment]
I dont think this is correct. Those settings are saved in the RGBEffects file and cannot be affected by an install.

Are you sure you are not pointing to a different show folder.

If you insist this is happening I need an rgb effects file after you have the settings right. The upgrade. Then another copy of the same file. Then start xLights ... then another copy of the file. 

Only if those files show changes being made can i take this further.
