### ISSUE TITLE
Every upgrade seems to recreate support folders in root of C

### ISSUE THREAD

**Issue by kevinsaucier** [smeighan/xLights#2234]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Installing a new version of the application creates empty colorcurves/palettes/valuecurves folders on the root of C.  If I delete these, they come back on the next install.  Just tried with .39 and the folders were created again.  If this is known behavior, please just close this problem but I've never seen data actually appear in these folders.  My show folders are on OneDrive (in a local OneDrive folder - C:\Users\kevin\OneDrive\Desktop\XMas Lights\xLights\Layouts\<showfoldername>).

**To Reproduce**
Install xLights.  Delete the above 3 folders from the root of C.  Install an updated copy of xLights.  Pretty sure this has been happening for a while as I've deleted these folders a few times and never really paid attention to when they were recreated until just now.

**Expected behavior**
These folders would be in the layout folder but not on the root of C.

**Screenshots**
Probably self explanatory but I'm happy to provide a screenshot, if needed.

**Versions (please complete the following information):**
 - Windows 10 v2004
 - xLights 2020.39

**Comment by keithsw1111** [comment]
They get created when you open a show folder there ... otherwise they dont. I would need to see a log file just after this happens to see why.

**Comment by kevinsaucier** [comment]
That's what I figured but I don't have a show folder there and, when opening after the upgrade, it goes directly to my normal show folder.  Happy to grab a log file.  Can you please tell me where that would be located?  Thanks!


Kevin

________________________________

**Comment by keithsw1111** [comment]
Tools menu ... view log

**Comment by kevinsaucier** [comment]
Here you go.  I've opened/closed xLights a couple of times since it was created but the first lines correspond with the time the folders were created (1:40p EDT).


[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/5252377/xLights_l4cpp.log)

**Comment by keithsw1111** [comment]
So actually this has nothing to do with the upgrade. xLights does this every time it is run.
