### ISSUE TITLE
Export models to HLS

### ISSUE THREAD

**Issue by jcmarksafb** [smeighan/xLights#224]
Just tried to export a model to an .hlsnc file and xl stopped working. It generated a bug report, but I couldn't read it as it was "grayed" out. I had to close xl. Any thoughts?
John

**Comment by stevegiron** [comment]
Hello, I'm helping sort the issues and determine which issues are still valid. 
As of May-14 we are on version 4.0.31. Is this issue still occurring?

**Comment by jcmarksafb** [comment]
No, you can close that ticket. The last time I tried, it did just fine. ThanksJohh
 


     On Monday, May 18, 2015 3:27 PM, stevegiron <notifications@github.com> wrote:
   

 Hello, I'm helping sort the issues and determine which issues are still valid. 
As of May-14 we are on version 4.0.31. Is this issue still occurring?—
