### ISSUE TITLE
Start channel for controller for first universe

### ISSUE THREAD

**Issue by CaffeinatedFunctionality** [smeighan/xLights#2240]
I'm using multicast and I'm told it's best to keep universes low so I know there is usually a channel offset for the first channel so for example controller A can be Universe 1 can be channels 1-315 and controller B can be channel 316-510. I know the software I use supports this and I though xlights did at some point. I also am adding a smoke machine and that's 1 channel and 511 channels unused in that universe. As I understand it currently one controller must be set for the entire universe even if you don't fill it up. I don't mean the channels per universe option. I want to share a universe between two controllers. Is this still possible?

**Comment by keithsw1111** [comment]
As long as you are multicasting you can do this today. Just define one universe and put all the props into it. That one universe represents two controllers.
Of course this is all based on a somewhat unnecessary premise that you need to use one universe when 2 would be simpler and easier.
I dont see what you are asking for use to enhance.

**Comment by CaffeinatedFunctionality** [comment]
ah ok I think I see the point I've been looking at this all wrong. On the controller screen I've been treating it as 1 controller per line. I still kinda feel it probably should represent that because it would make it easier if I ever want to move from multicast to unicast, however this is a good enough work around for me that I haven't thought of.
