### ISSUE TITLE
Render all does not render all.

### ISSUE THREAD

**Issue by Poporacer** [smeighan/xLights#2245]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I opened a sequence and "rendered all" but one of the groups did not render. If I click on the effect it will then render and show. 

**To Reproduce**
1. Open the sequence
2. Render all
3. Play the sequence and look at the tombstone group. The effects that start at 14.025, 14.550, 16.125, and 16.625 were individually selected so show properly. The rest of the effects do not. Select an effect and then it renders and will display properly. Sometimes selecting an effect does not fix it until you select a different effect and then select the original effect. Saving the sequence after selecting an effect doesn't always fix the problem, the effects will not show again once the sequence is reopened. (see attached video as well) 

https://drive.google.com/file/d/1YW3vT2GN061NT6CePtRBRhcJapVV5_K4/view?usp=sharing

**Expected behavior**

Render All should render all of the effects.
**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 
[Ghostbusters.zip](https://github.com/smeighan/xLights/files/5286963/Ghostbusters.zip)
2020.40

**Additional context**

**Attachments**
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publicly

 please say so and be ready to PM them to one of the developers when asked.

**Comment by kcobbva** [comment]
I am running into the exact same issue (2020.40) and also on my tombstones as of last night after adding a 5th and going back into some large sequences to re-render and save off for Halloween.  I plan to roll back a version or two tonight to see if the issue follows.  My specific issue is on "Enter Sandman" sequence by Tom BetGeorge, which I had 4 initial tombstones on until I added one last night and ran into this issue attempting to re-render.    I don't have access to my files here but do want to add on as I also seeing this.

**Comment by dkulp** [comment]
FYI:  I cannot reproduce. I grabbed the Ghostbuster.zip file above, loaded it in .40, hit Render All, hit play, an the tombstones blinked as appropriate through the On effects and every other effect.

**Comment by Poporacer** [comment]
I had a feeling that would happen! That is why I included the video…

Rick Harris

**Comment by Poporacer** [comment]
@kcobbva I found a hack to fix it. Click on one of your effects to select it, press "ctrl A" to select all. Then right click Canvas and select Bulk Edit and select Checked and then right click again and Bulk edit to unchecked and it seems to reset things? But you will have to go to back and manually add any canvas setting that you might need (not a common setting for most effects but is needed on the Shader effect so look through your effects before you try the hack.

**Comment by kcobbva** [comment]
@Poporacer   Thank you!  I will look at this this evening.

**Comment by kcobbva** [comment]
So I rolled back and still displayed the same issue but it was updated in 40 with the new tombstone and I was on 39 so I saw the same.  I ended up validating the sequence and then exporting.  Ran a Render and save and then created a new sequence and imported the exported and matched the models.   Working perfectly in 39.   I'm staying here until after Halloween.

**Comment by AzGilrock** [comment]
Well there are ways to create a sequence where clicking the effect changes the result from a render all but it’s a rendering order issue.

**Comment by Poporacer** [comment]
I believe this has been fixed or it was the after effect of a very old sequence that somehow along the line did not get update to current formats?
