### ISSUE TITLE
Protocol Naming

### ISSUE THREAD

**Issue by AleXthePunK** [smeighan/xLights#2246]
I didn't see an issue opened or closed.

This is for version 2020.40

In previous version, Bulk Edit Controller Connection, the protocols were all in lower case, so you couldn't choose one, because the Protocols in the actual Controller connection for each model was case sensitive. Example: dmx vs DMX, ws2811 vs WS2811

In version 40, the protocols in the models are all lower case, which match the bulk edit, but it won't let you choose or change one because they are still case sensitive somewhere in the backend. 

I wasn't sure if this was noticed or not.

**Comment by computergeek1507** [comment]
I fixed it yesterday with commit f493d36e3487b21aadebecb5856d472c78fbed73
