### ISSUE TITLE
Effect Timing to Timing Track

### ISSUE THREAD

**Issue by syracuse-lights** [smeighan/xLights#2247]
**Is your feature request related to a problem? Please describe.**
Not really a problem, more of a request.  I would like to convert my vixen sequences into xlights.  I have no problem with importing the effects, but I have several props that i have effects on that are timed for music events like piano or drums. I would like to convert them into timing tracks so that I can change the imported timed effect into new effects based on timing track. 

**Describe the solution you'd like**
To be able to convert a model effect (Row) to a Timing Track (Row)

**Describe alternatives you've considered**
I have created a timing track and clicked the "T" button at the start and end of the timing effect.

**Additional context**
![Screenshot 2020-09-27 200310](https://user-images.githubusercontent.com/69699152/94383174-85b62f00-00fc-11eb-94dd-d456b5802353.png)

**Comment by darylc** [comment]
This is already implemented to 2020.41
