### ISSUE TITLE
error in check sequence

### ISSUE THREAD

**Issue by jnealand** [smeighan/xLights#2248]
Minor problem and I can make it go away by thru notepad++

error being raised because ws2811 and WS2811 protocols being used on a single port

I got this error while doing check sequence with no sequence open as I tried to cleanup changes I made to my layout.  I notice that the model GUI only allows the lower case version while that model was created two years ago.

Also had an error on TM1811 as being invalid.  Even though the actual pixels are TM1809 I am aware that specifying them as ws2811 everything works.  I editted those protocols to ws2811 using notepad++ and the error went away.

![Check sequence error1](https://user-images.githubusercontent.com/2533387/94483844-85c03880-01a9-11eb-985e-9dbf59089899.jpg)

**Comment by jnealand** [comment]
TM1811 should have been TM18XX

**Comment by computergeek1507** [comment]
fixed with 2dad1deb07af32156f774adf214e23c9aa1db7a6
