### ISSUE TITLE
Data validation issue with lyric tracks

### ISSUE THREAD

**Issue by cmanucy** [smeighan/xLights#2249]
**Describe the bug**
I've been tracking down an issue with the Singing Faces group - we have an xtiming track that doesn't import properly.  Upon investigation I determined the issue is due to some extra quotation marks in the xml file.  In trying to figure out where that came from, I realized the original track had quotation marks in it, and these were being carried into the word breakdowns.  Once the track(s) are exported, the quotation marks mess with the xml parsing.

**To Reproduce**

If you "Import lyrics" on a track and it has a track with lyrics in it, such as:

"Here's Johnny!" she said, and smiled in her special way.

The quotes will be removed before the lyrics are placed on the track.

However, if you manually go into the track and add lyrics without using the import process, you can add quotes to the lyrics.  Then if you break them down, the quotation marks are carried down when you breakdown the phrases.

If you export the lyric track, the quotation marks are not removed and therefore mess with the XML formatting.

<timing name="New Timing" SourceVersion="2020.31">
   <EffectLayer>
      <Effect label="Here's Johnny!" starttime="0" endtime="15000" />
      <Effect label=""Here's Johnny", she said" starttime="15000" endtime="30000" />
   </EffectLayer>
   <EffectLayer>
      <Effect label="Here's" starttime="0" endtime="7500" />
      <Effect label="Johnny" starttime="7500" endtime="15000" />
      <Effect label=""Here's" starttime="15000" endtime="18750" />
      <Effect label="Johnny"" starttime="18750" endtime="22500" />
      <Effect label="she" starttime="22500" endtime="26250" />
      <Effect label="said" starttime="26250" endtime="30000" />
   </EffectLayer>
   <EffectLayer>
      <Effect label="etc" starttime="0" endtime="50" />
      <Effect label="AI" starttime="50" endtime="7450" />
      <Effect label="etc" starttime="7450" endtime="7500" />
      <Effect label="etc" starttime="7500" endtime="7550" />
      <Effect label="AI" starttime="7550" endtime="11250" />
      <Effect label="etc" starttime="11250" endtime="11300" />
      <Effect label="E" starttime="11300" endtime="15000" />
      <Effect label="etc" starttime="15000" endtime="15050" />
      <Effect label="AI" starttime="15050" endtime="18700" />
      <Effect label="etc" starttime="18700" endtime="18750" />
      <Effect label="etc" starttime="18750" endtime="18800" />
      <Effect label="AI" starttime="18800" endtime="20625" />
      <Effect label="etc" starttime="20625" endtime="20675" />
      <Effect label="E" starttime="20675" endtime="22500" />
      <Effect label="etc" starttime="22500" endtime="22550" />
      <Effect label="E" starttime="22550" endtime="26250" />
      <Effect label="etc" starttime="26250" endtime="26300" />
      <Effect label="E" starttime="26300" endtime="29950" />
      <Effect label="etc" starttime="29950" endtime="30000" />
   </EffectLayer>
</timing>

Steps to reproduce the proper behavior:

1. Create a new blank track
2. Right click on the track, "Import lyrics"
3. Type in some words, add some quotation marks
4. Quotes are removed (good behavior).

Steps to reproduce the unexpected behavior:

1.  Create a new blank track
2.  Right click on the track, "Import lyrics"
3.  Type in some words
4.  Modify the lyrics, add quotes around some words (simulates a user adding in lyrics manually)
5.  Right click on the track, 'break down phrases'
6.  Observe quotation marks on the words

**Versions (please complete the following information):**
 - OS: MacOS 10.15.6 (19G2021)
 - xLights version 2020.31

I'm happy to attach a sequence if desired, but this one is pretty easy to reproduce.

**Comment by computergeek1507** [comment]
it skips the symbols when you breakdown the phonemes
![image](https://user-images.githubusercontent.com/2293065/94500444-4efc1980-01cd-11eb-8f5d-5b930d840e24.png)

**Comment by cmanucy** [comment]
yes - but the problem is on export of the track as an .xtiming.  Once exported, you cannot re-import into a sequence without manually editing (fixing) the extra quotes.

So xLights is perfectly happy with quotes, but the export/import process is borked by them.

**Comment by AzGilrock** [comment]
Just type a message in the Singing Face group that says hey idiots quit typing the fucking quotes.

**Comment by cmanucy** [comment]
HAH!  That's actually the thing we're looking out for in the QC process now that we've identified it as an issue... 

Would it be possible to use the same input validation that's going on for the "import lyrics" function on modifying phrases as well?
