### ISSUE TITLE
Add Scale value for ruler

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#2252]
With the addition of the ruler in 3D, it would be beneficial to show the scale, which I would take to be the calculated length of the ruler line in xlights divided by the real length units entered.  For example, if the real life measurement was 25 feet and the ruler was drawn from point 0,0,0 to 200,200,200 in xlights (a total length of 346.41 xlights units), the scale would be 346.41 units/25 feet = 13.86 units per foot.

That can then be used to set the grid size for drawing objects.  So if I wanted a grid at 10' spacing, I would multiple the scale by 10' to get 138.6 units, which would be entered line spacing for the grid.  The size of the grid and location could also be easily adjusted that way.  

It would be nice if the real life dimensions for the grid could also be shown, but not absolutely needed.

Thanks.

**Comment by keithsw1111** [comment]
I am not sure I understand what this is saying. But if you really just mean can we display the grid spacing in real measurements if the ruler exists then sure why not.
