### ISSUE TITLE
Group Order does Not Follow Display Element Order

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#2254]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
In my Layout Tab my Mini Trees sort by 1 thru 10.
In the Display Elements Tab my Mini Trees sort by 1 thru 10.
When I put them in a Group (Mini Trees) and the Mini Trees Group ios expanded they are in sort 10 thru 9..with 10 before 1.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. In Layout have 10 mini Tree Named 1 thru 10
2. In Display Elements add them to a group named Mini Trees
3. In Sequence Tab expand Mini Tree Group..they are list as 10, 1, 2, 3, 4, 5, 6, 7, 8, 9

**Expected behavior**
Would expect them to Sort the same way as they do in Display Elements

**Screenshots**
Screen Shots attached.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.40

**Additional context**
N/A
![Sort Layout](https://user-images.githubusercontent.com/13740582/94767319-e645a600-0360-11eb-9b1d-aa429af3d703.jpg)

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
The model order in a Group is defined in the Group Panel on the layout tab
![image](https://user-images.githubusercontent.com/2293065/94770330-5a447600-0382-11eb-9999-74664dc92151.png)

**Comment by jimswinder** [comment]
I guess I don't understand...what's the difference between the two?

________________________________

**Comment by jimswinder** [comment]
never mind...I get it!!  thanks!!!

________________________________
