### ISSUE TITLE
3D model OBJ format does not support jpeg textures

### ISSUE THREAD

**Issue by sslupsky** [smeighan/xLights#2255]
When importing a 3D model, I have found that if there is a texture with the file extension "jpeg" listed in the materials file, the texture is not imported and appears "black" when rendered in the layout.

**Comment by sslupsky** [comment]
I will give that a try.  I am poking around in the Tiny OBJ Loader repo now to see if it is supported in the lib.

**Comment by AzGilrock** [comment]
OBJ files are just text so open it in Notepad++ and change the name.  Then change the file and try it.   Probably faster then digging in documents.

**Comment by sslupsky** [comment]
Yeah.  I changed the filename extensions from ".jpeg" to ".jpg" and updated the mtl file.  That doesn't appear to have fixed it.  Is there anything I need to do to the OBJ file?

**Comment by sslupsky** [comment]
There is one material in the list that is a .png file and that one is being loaded but for some reason the jpegs are not.

**Comment by sslupsky** [comment]
Here is a copy of the model.
[3dmodel_w_jpeg.zip](https://github.com/smeighan/xLights/files/5313453/3dmodel_w_jpeg.zip)

**Comment by sslupsky** [comment]
I had a different model where the textures are all PNG's and that appears to import fine.

**Comment by AzGilrock** [comment]
Yeah I mainly only tested OBJ files I exported from SketchUp so I never paid attention to the material file formats.

**Comment by sslupsky** [comment]
I'll tinker a bit more and see if I can narrow it down.

**Comment by sslupsky** [comment]
I was able to load a model with the jpeg textures so I think I have it working.  I think it might be a path problem.  I will close this for now and reopen if there is still a problem.
