### ISSUE TITLE
Model disappears when moving model along X axis

### ISSUE THREAD

**Issue by sslupsky** [smeighan/xLights#2256]
I have encountered an issue that causes the model to disappear when moving it along the X axis.  I think the issue is somehow related to how xLights is calculating the position of the model.  I have attached a screencast and screenshot below.  Note when the model is being moved left or right along the X axis, the coordinates for the model in the bottom left corner of the xLight window show an invalid coordinate denoted with "x=nan, y=nan, z=nan".  When this happens, the model disappears.  When moving the model along the Y or Z axis, this issue does not occur.

I am running xLights 2020.40 on macOS.

[xlight issue.mov.zip](https://github.com/smeighan/xLights/files/5314356/xlight.issue.mov.zip)

![Screen Shot 2020-10-01 at 1 32 45 PM](https://user-images.githubusercontent.com/16888734/94854941-f73af980-03ea-11eb-93a1-cded99c51c02.png)

**Comment by sslupsky** [comment]
There are no error messages or warnings in the log.

**Comment by AzGilrock** [comment]
Ok so if I get home and drop a Single Line and move it and it doesn't disappear we won't have enough info to make any progress on this.

**Comment by sslupsky** [comment]
Yeah, I understand.  I haven't been able to come up  with any idea why this is happening.  I have not done much with xLights yet so I essentially have an empty project.  I added a few music tracks to my assets folder and imported one into the timeline.  But beyond that, the only model is the 50 light single string which is configured to talk to a Kulp K8.

Is there anything else I can provide that would be helpful?  I have attached a copy of the show directory here (without the music files since they have a copyright notice on them).

[test.zip](https://github.com/smeighan/xLights/files/5314652/test.zip)

**Comment by sslupsky** [comment]
I removed the 3D model from the layout (only thing remaining in the layout was the grid).  That did not affect the issue with single string.

**Comment by sslupsky** [comment]
I added another model and deleted the existing one and I can move the new one around fine.  Must be some sort of corruption of the first model?

**Comment by sslupsky** [comment]
I will close this for now since I have found a way to correct the issue.

**Comment by keithsw1111** [comment]
I tried this on my windows machine and i dont seem to be able to reproduce the behaviour

**Comment by sslupsky** [comment]
Yeah, its kinda weird.  The issues appears to be confined to the one model.  I opened the show directory on a different computer running an earlier version of xLights (2020.31) and observed the same problem.  Maybe it is an issue only with the mac version. 

The easy work around was simply to delete the model.

Thank you @AzGilrock and @keithsw1111 for your help.  This software is amazing.

**Comment by dkulp** [comment]
I was able to reproduce it on OSX, but only in the release/optimized builds, not debug.    I'm digging into it.

**Comment by sslupsky** [comment]
If it helps, another way I found to make the model disappear is to manually change the coordinate of the model using the Size/Location settings.
