### ISSUE TITLE
Unable to Resize House Preview Window in Ubuntu

### ISSUE THREAD

**Issue by borth79** [smeighan/xLights#2257]
**Describe the bug**
The House Preview window has no option to resize in Ubuntu 20.04. There is no maximize button or the ability to increase the size of the window by dragging from the window borders. This also affects the Export House Preview Video option as it seems to be dependent on the House Preview Window size and zoom level.

**To Reproduce**
1. Open xLights
2. Open a Sequence
3. Undock House Preview window
4. Hover mouse over bottom left corner border, bottom right corner border or left/right side border

**Expected behavior**
I would expect that the House Preview window be re-sizable. 

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04
 - xLights version 2020.23 & 2020.4

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by dkulp** [comment]
This was fixed a few weeks ago.... make sure you are using the latest build.  (currently 2020.40)

**Comment by borth79** [comment]
Awesome! Thanks for all your hard work and help.
