### ISSUE TITLE
"Set Property" for multiple effects

### ISSUE THREAD

**Issue by charbaugh1** [smeighan/xLights#2258]
There are many times when I need to make a change to a single property value in multiple effects that may purposefully have differing values in other properties.  Using the current Update button would set them all exactly the same.

What would be nice is a "Set Property" option in the right click context menu.  When you choose Set Property, a dialog box will open that lists all of the common properties of the selected effects (color, value curves, in/out transitions, buffer, layering info, etc).  The user can select the individual property, or properties, they want to change, input the desired value, then click OK.  

One specific example:  I have a series of Fire effects on my mini trees; in total there are over 150 individual Fire effects to make the trees appear to dance to the music.  One set of trees is a blue color and another set is red.  To further complicate things, several had unique in/out transitions and Growth Cycles.  I needed to set a value curve for the height on all the effects to get the desired outcome (to make them drop, instead of just turn off).  Using the Update button would have set them all to exactly the same color, in/out transition, and growth cycle, when the only property I wanted to modify was the Height value curve.  In the end, I had to select them individually to make the needed change.

**Comment by keithsw1111** [comment]
Bulk edit already exists for individual properties and has done for a couple of years now.

https://youtu.be/jtPZEd5jecc

**Comment by computergeek1507** [comment]
https://manual.xlights.org/xlights/chapters/chapter-four-sequencer/changing-an-effect#bulk-edit

**Comment by charbaugh1** [comment]
Well, now I feel stupid.....

Thanks!

**Comment by keithsw1111** [comment]
You may want to validate issues with the community in the forums/facebook groups before adding tickets here.
