### ISSUE TITLE
Data Layer import of a conductor file crashes Nutcracker

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#226]
After opening an exsisting sequence and attempting to import a conductor formatted datalayer file Nutcracker crashes with the following report file.

https://dl.dropboxusercontent.com/u/28041968/Nutcracker%20Testing/xLights_dbgrpt-10576-20150512T192741.zip

**Comment by dkulp** [comment]
Any chance of getting the conductor file as well?  Not much info in the back trace. :(

**Comment by MrChristmas2000** [comment]
I believe this is the file I exported from LSP and attempted to load into NC.

https://dl.dropboxusercontent.com/u/28041968/Nutcracker%20Testing/WIW%20-%20MASTER%20FILE.25ms.working%20-%2005_10_2015.seq
