### ISSUE TITLE
 add the possibility of being able to move the strings of the megatree in the visualiser

### ISSUE THREAD

**Issue by thisim** [smeighan/xLights#2264]
**Is your feature request related to a problem? Please describe.**

would it be possible to add the possibility of being able to move the strings of the megatree in the visualizer.
Currently it is impossible to be able to put several strings on a single output. 
Only the first string of the megatree can be moved.

![megatree](https://user-images.githubusercontent.com/31959517/95085622-c37c0e80-071f-11eb-956a-12419303b871.JPG)

![visualiser](https://user-images.githubusercontent.com/31959517/95085650-ce36a380-071f-11eb-86db-03f12f5b9bf7.JPG)

**Comment by AzGilrock** [comment]
xLights has always treated the #Strings field to mean # of outputs.  If you have a long string on an output that zig-zags you define that with Strands Per String.
