### ISSUE TITLE
Star Model with 20 nodes node 11 missing from model

### ISSUE THREAD

**Issue by toddwright11** [smeighan/xLights#2266]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Make a star and put in 20 as the number of nodes.... node 11 or the top of the star is missing

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to input star model
2. Click on node/string set to 20
3. Scroll down to look at model layout.... node 11 (top of star is missing)
4. See error top of star model is missing

**Comment by keithsw1111** [comment]
This happens with some start locations but not with others. Fix will be in .43 on the weekend. Windows fix early can be obtained through Zoom.

**Comment by toddwright11** [comment]
Thank you... have a great day.... night....
