### ISSUE TITLE
Ruler issue

### ISSUE THREAD

**Issue by denniskuntz** [smeighan/xLights#2268]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Dimensions for models become incorrect.

**To Reproduce**
Uncheck the Active box for the Ruler and Save
Close Xlights
Restart Xlights. 
Width, Height, Depth values for models are now incorrect. Just one example is the Grid model should be 10.x by 10.x. It now shows 125.x by 125.x. If you leave the Active box checked the values remain correct when closing and restarting Xlights. Also changing the value back to Active fixes the values. 

**Expected behavior**
Making the ruler not active should not mess up the measurement of models

**Screenshots**

**Versions (please complete the following information):**
 - OS: [Windows 10 1909
 - xLights version [2020.42]

**Additional context**

**Attachments**
Not sure if this is triggered by something with my setup so I packaged a test sequence so you have my setup which should allow you to replicate.

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
[20 test.zip](https://github.com/smeighan/xLights/files/5337315/20.test.zip)

**Comment by keithsw1111** [comment]
Fixed for .43
