### ISSUE TITLE
Message when clicking on a effect

### ISSUE THREAD

**Issue by RichardRennII** [smeighan/xLights#227]
In the new release 4.0.31 I am getting this message when I click on an effect in the sequencing grid.

 
![image](https://cloud.githubusercontent.com/assets/11212370/7652819/6b38966a-fade-11e4-8993-4e0234c6f970.png)

**Comment by AzGilrock** [comment]
Yeah that's a by-product of being a beta tester.  The initial releases that included the new Fan and Shockwave effects I forgot to name the notebook tab to something meaningful so if you happened to use those effects during that time you got a bad name in your XML.  We didn't want to bog down the code doing renames for the all the stuff that changes during the beta phase.

I fixed my personal sequences by doing a global search and replace:
ID_NOTEBOOK3 becomes ID_NOTEBOOK_Shockwave
ID_NOTEBOOK2 becomes ID_NOTEBOOK_Fan

The other way to fix an effect is after you click it and close that dialog just hit Update and then make sure to Save the file at the end.

**Comment by dkulp** [comment]
This is a sideeffect of use still working on the Morph affect.  Once the effect is "per Gil's standards", users won't see this.   Workaround for now is to hit the "Update" button after this pops up.
