### ISSUE TITLE
Add power and data connection (PHY) metadata to models

### ISSUE THREAD

**Issue by sslupsky** [smeighan/xLights#2275]
When creating a layout it would be helpful if there was the ability to enter additional metadata that describes the physical electrical connection for the string data and the string power.  I think this would help the user plan power injection and aid the setup.

The additional metadata could be attached to the model or perhaps it might be attached "connecting lines" between the models shown the visualizer.

**Comment by keithsw1111** [comment]
This has been discussed several times and rejected.

**Comment by sslupsky** [comment]
Is it a difficult thing to implement?  Having the info in xLights saves having to create a separate spreadsheet to track this data when building the layout for your house.  At the end of the layout process, it would be helpful to be able to refer to the layout and generate a Bill of Materials which you could then send off to Ray Wu et al.

Alternatively, perhaps there could be a general "Notes" field attached to the model.  Then the user could put this type of data and other user specific data into the "notes".

**Comment by keithsw1111** [comment]
There already is a general description field.
