### ISSUE TITLE
Model export channel count for groups is incorrect.

### ISSUE THREAD

**Issue by sslupsky** [smeighan/xLights#2279]
It appears to me that the channel count reported in the model export csv is incorrect.  I have attached a sample here.  In the sample, you will note the channel count totals for the groups do not match the channel counts when you add them up individually.  It looks to me like the group total is also adding the models that are between the instances included in the group.

For example, if you refer to the "Roof - Garage" group, there are two models in that group, "Roof - Garage 1" and "Roof - Garage 2".  The total of the individual models is 900 + 90 = 990 channels.  The csv reports the group total as 1548.  The difference is 558 channels, which is the number of pixels of the "Door - Garage" model which is not included in the group.

[models.csv.zip](https://github.com/smeighan/xLights/files/5356434/models.csv.zip)

**Comment by keithsw1111** [comment]
True ... I have removed those properties.
