### ISSUE TITLE
Release 4.0.31 crashes

### ISSUE THREAD

**Issue by RichardRennII** [smeighan/xLights#228]
I am seeing a lot of crashes when saving. The effects are saved but Nutcracker crashes and I have to use task manager to close it out and re-open it to continue

**Comment by stevegiron** [comment]
Richard, please comment with more information to help the developers isolate the issue. Post your xlights_rgbeffects.xml and xlights_networks.xml. Is this for all sequences or just a given sequence. If it's more problematic on a given sequence, please post that xml as well. Thanks.

**Comment by thedementedelf** [comment]
I am getting a crash every time I go to preview.  The program freezes and I need to use task manager to shut the program down.

**Comment by dkulp** [comment]
Can we get your xlights_*.xml files from your show directory to see if we can reproduce it?

**Comment by RichardRennII** [comment]
Steve 
The crashes are at random times. while writing this I created a new sequence added models and when I save it it crashed  can you email me and I will send the files to who ever needs them.
rennslightsforcharity@gmail.com


![image](https://cloud.githubusercontent.com/assets/11212370/7693142/ef2bd2e8-fd9a-11e4-8c84-3dd2071649cc.png)

**Comment by stevegiron** [comment]
Richard, can you post those files to drop box or another file share? You can also post to the forum, reference this issue # and attach the file there on the Forum.

**Comment by RichardRennII** [comment]
I posted them in the forum Steve

**Comment by thedementedelf** [comment]
dkulp.....I emailed them to you

**Comment by dkulp** [comment]
Yea.. the problem is the crash is occurring in your video driver which is very strange.     From googling, it looks like you  have an ATI card?
Can you double check that you have the latest versions of you video drivers and see if that helps.   

Dan


> On May 19, 2015, at 10:44 AM, thedementedelf <notifications@github.com> wrote:
> 
> dkulp.....I emailed them to you
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Daniel Kulp
dan@kulp.com - http://dankulp.com/blog

**Comment by stevegiron** [comment]
Crash files here: http://nutcracker123.com/forum/index.php?topic=1192.msg6391;topicseen#msg6391

**Comment by thedementedelf** [comment]
Dan,

 

I checked the driver and there was an update available. I installed it and rand Nutcracker and got the same crash.  I’m attaching the new logs.

 

Thanks

 

Kevin J Dunn

Dementedelf Productions

 <http://www.thedementedelf.com/> www.thedementedelf.com

 <http://www.holidayamericaradio.com/> www.holidayamericaradio.com

**Comment by RichardRennII** [comment]
This issue seems to be gone for me in the new release 4.0.32
