### ISSUE TITLE
xSchedule with colorlight plugin crashes every time

### ISSUE THREAD

**Issue by mharnishfeger** [smeighan/xLights#2283]
I believe I was on 2020.37 initially  and I copied the DLLs from colorlight plugin v4 over to my c:\Programfiles\xlights folder.  When I launch xschedule I see the plugin is available but when I enable the plugin it pauses then goes (not responding) then I get the crash report I am attaching here.  I upgraded to 2020.42 and recopied the DLL's to see if that resolved anything but still get the same issue or crashing when I enable the plugin.  

I thought maybe not having the matrix configured under xschedule might be the issue so i went and created that as well with the same outcome.

Thanks for everything you guys do!!
[xSchedule_dbgrpt-10892-20201010T191058.zip](https://github.com/smeighan/xLights/files/5360407/xSchedule_dbgrpt-10892-20201010T191058.zip)
 

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
Install the redistributions on the bottom of this page. https://github.com/computergeek1507/ColorlightPlugin

**Comment by mharnishfeger** [comment]
Thanks, I’ll give it a try in the morning.

Thanks,
Mark Harnishfeger

On Oct 10, 2020, at 7:35 PM, Scott H. <notifications@github.com> wrote:

﻿

Install the redistributions on the bottom of this page. https://github.com/computergeek1507/ColorlightPlugin

**Comment by mharnishfeger** [comment]
Looks like that fixed it. I will play with it more tomorrow but it is loading now.

Thanks,
Mark Harnishfeger

On Oct 10, 2020, at 7:35 PM, Scott H. <notifications@github.com> wrote:

﻿

Install the redistributions on the bottom of this page. https://github.com/computergeek1507/ColorlightPlugin
