### ISSUE TITLE
Unable to export model for ESEQ

### ISSUE THREAD

**Issue by bigwavedave42** [smeighan/xLights#2284]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I had done it before, a few weeks ago, on an earlier version.  Attempting to export model to ESEQ to use as a background effect (Tune To Sign).  I am using a xsq file that worked for the initial export, a few weeks ago.  I opened it again, as I wanted to turn brightness down to 50%.  Doing the "Render and Export" does not even create a file when choosing ESEQ or Compressed ESEQ options.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

VIDEO in folder: https://drive.google.com/drive/folders/1Cd8uwpWC2UnWU4xQ1SSVzk8AAMXpsIH8?usp=sharing

1. Go to 'Sequencer Tab'
2. Click on desired model
3. Right Click -> Model -> Render and Export
4. Choose name for file, and choose ESEQ file or Compressed ESEQ
5. Says that it was written, but no new files found matching.  

**Expected behavior**
I would expect there to be a new ESEQ file as named in the prior dialog box.  

**Screenshots**

See Video : https://drive.google.com/drive/folders/1Cd8uwpWC2UnWU4xQ1SSVzk8AAMXpsIH8?usp=sharing

**Versions (please complete the following information):**
 - OS: Mac 10.15.6
 - xLights version 2020.42.2

**Additional context**
I tested GIF as an export, and it appeared to work.  It actually created a file anyways.  So, it shouldn't be an access restriction.  
I tested LOR export, but it crashed xLights with a complaint about timing.  

**Attachments**
XSQ File included in Drive link : 
https://drive.google.com/drive/folders/1Cd8uwpWC2UnWU4xQ1SSVzk8AAMXpsIH8?usp=sharing

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by bigwavedave42** [comment]
Just for kicks, I also tried Uncompressed AVI render/export, and that created a file.  

I also tried to do just Export (instead of Render and Export) and doesn't create a ESEQ file in that flow either.

**Comment by bigwavedave42** [comment]
I just uploaded a "Tools - Package Log Files" as well, to the Google Drive folder mentioned above.

**Comment by keithsw1111** [comment]
It works for me in .42.

**Comment by bigwavedave42** [comment]
This was seen on .42.2 is that unique to Mac?

Can you validate, from the video, that I'm following the right process?

**Comment by bigwavedave42** [comment]
Confirmed it is working on a Windows install of 2020.42.  It would seem to validate that I am following the proper steps.

So seems limited to Mac in my environment so far.
