### ISSUE TITLE
Star model 

### ISSUE THREAD

**Issue by ebuechner** [smeighan/xLights#2285]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
The strands don't match the layers of the star when set for a starting point on the inside of the star. The strands seem to want to start from the outside going in with the numbering resulting in a complete mismatch with the layers.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
Star model set with inside layer of 20, layer 2 30, outside layer 40, starting location bottom ctr-CW inside, outer to Inner ratio 2.62.
Drop a on effect onto any one of the strands and take note that it doesn't match up with a layer of the star.

**Expected behavior**
A clear and concise description of what you expected to happen and why.
I expect to see each strand match a layer in the star.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]
Running on a Windows 10 64-bit machine.

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
2020.43?

**Comment by ebuechner** [comment]
Yes

**Comment by keithsw1111** [comment]
I think scott has this fixed in .44. Please reopen if its not fixed.

**Comment by ebuechner** [comment]
Not Fixed

**Comment by keithsw1111** [comment]
Then we need a sample

**Comment by ebuechner** [comment]
[Twinkle Twinkle BROKEN Star.zip](https://github.com/smeighan/xLights/files/5417943/Twinkle.Twinkle.BROKEN.Star.zip)

**Comment by keithsw1111** [comment]
Ok ... I think I have a fix for this one now.
