### ISSUE TITLE
Star Render Style "Layer Star" produces different effect 2020.40 vs 2020.43

### ISSUE THREAD

**Issue by DonMc33** [smeighan/xLights#2286]
[xlights star.zip](https://github.com/smeighan/xLights/files/5374325/xlights.star.zip)

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
In 2020.40, a star that is setup in the layout tab wired "Bottom Ctr - CW", 6 layers Inside 20, 30,40,50,60, Outside 70 produces the desired effects in the sequencer when Render Style "Layer Star" is selected.  When this same sequence is opened in 2020.43, the effect is not reproduced the same on the star with all the same settings.

**To Reproduce**

Step 1) Go to xLights 2020.40, open the  sequence Mary's Little Boy Child (Purchased from PPD, please PM and I can send to you), go to the model "Star Storyline Tree" and select any of the effects that utilize the render style "Layer Star" and note the behavior of the effect in the Model Preview window. 
 Step 2) Close 2020.40 and install 2020.43, open the  sequence Mary's Little Boy Child (Purchased from PPD, please PM and I can send to you), go to the model "Star Storyline Tree" and select any of the effects that utilize the render style "Layer Star" and note the behavior of the effect in the Model Preview window.  

Step 3) Note the totally different effect that displays on 2020.40 vs 2020.43on the "Star Storyline Tree".

**Expected behavior**
Expected the "Star Storyline Tree" effects with Render Style " Layer Effect" to behave the same in 2020.43 as it did in 2020.40.

**Screenshots**
Two videos linked, one with model preview for 2020.40 showing the effects on the Star Storyline Tree as I would expect, and a second video showing this same model and effects on the model preview with how the effects are different with the same render style "layer Star".  In both of these cases, the star model in the layout tab was not changed, they were set "layout tab wired "Bottom Ctr - CW", 6 layers Inside 20, 30,40,50,60, Outside 70"

https://www.dropbox.com/s/jetfpolcqe69uak/xLights%202020_40%20-%20C__Users_donal_Documents_xLights_xLights%20Sequences%202020_03%20-%20Mary%27s%20Little%20Boy%20Child%20%28Glee%20Cast%20Version%29.xsq%202020-10-12%2013-04-29.mp4?dl=0

https://www.dropbox.com/s/4gs3tq4n8ouxajv/xLights%202020_43%20-%20C__Users_donal_Documents_xLights_xLights%20Sequences%202020_03%20-%20Mary%27s%20Little%20Boy%20Child%20%28Glee%20Cast%20Version%29.xsq%202020-10-12%2013-10-37.mp4?dl=0

**Versions (please complete the following information):**
 - OS: Windows 10 Pro
 - xLights version 2020.43

**Comment by Cboehm00** [comment]
Same thing for myself. I dont feel it's necessary to open another ticket for this issue.

**Comment by keithsw1111** [comment]
I believe scott has this fixed for .44 ... at least in my testing with your layout.
