### ISSUE TITLE
House Preview, Layer Blending, etc windows not opening

### ISSUE THREAD

**Issue by DBLights** [smeighan/xLights#2288]
When I click VIEW:WINDOWS:HOUSE PREVIEW, the House Preview window does not open.  Same issue with the Layer Blending Window.  All other windows open just fine.  I just updated to 2020.43 on Windows 10 x64.  I have closed xlights, rebooted and created both animation sequences and musical sequences, and still have the same issue.

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
Got to View->Windows->Reset To Default and see if they appear. https://manual.xlights.org/xlights/chapters/chapter-five-menus/view/windows#reset-to-default

**Comment by DBLights** [comment]
That didnt work when I tried it earlier, but after restarting my computer a third time, it has finally gone back to normal.  Must have been an issue on my end.  Thanks.
