### ISSUE TITLE
Feature Request: Projector Control for Optoma GT760A

### ISSUE THREAD

**Issue by thespica93** [smeighan/xLights#2289]
**Is your feature request related to a problem? Please describe.**
Not related to a specific problem. I purchased a few Optoma GT760A projectors that have RS-232 control on the, I would like to have On/Off control of them through Xschedule please

**Describe the solution you'd like**
I would like to Add a projector in advanced sequencing, and select this model projector to turn on and off at specific times

**Describe alternatives you've considered**
I would have to manually turn on and off the projectors each night

**Additional context**
I will attach the manual below with the RS-232 command strings. I can only find the GT760 projector manual. I believe they are the same. 
Thank you for all your work!
[GT760-M-en-GB.pdf](https://github.com/smeighan/xLights/files/5373764/GT760-M-en-GB.pdf)

**Comment by keithsw1111** [comment]
This projector is already supported by xSchedule ... There are some codes in the manual we didnt have but all the critical ones were already there.
