### ISSUE TITLE
Enhancement request:  import LOR timings

### ISSUE THREAD

**Issue by RobMetzger** [smeighan/xLights#229]
If possible, it would be nice if we could import our timing marking from LOR.  Example is I have a regular timing that I do in LOR, then I make 3 others, with the beat wizard(quarter notes, 8th notes, and 16th notes) and if I could import those as separate timings it would be great.  Excellent job so far guys!

**Comment by stevegiron** [comment]
LOR LMS and LAS timings are now importable.
