### ISSUE TITLE
while opening Display Elements the window opens on a monitor that is not present

### ISSUE THREAD

**Issue by CharlesSmothers** [smeighan/xLights#2290]
**Describe the bug**
I kept repeatedly trying to access the "Display Elements" window, but could not.
I tried the toolbar button and the View -> Windows -> Display Elements to try to bring up the window.
I even tried View -> Windows -> Reset to Defaults several times.
I closed and re-opened xlights.
I still could not access the "Display Elements" window.

This was all while using my laptop by itself - no second monitor.

At some point, I re-attached my extra monitor back at my office desk.
 
I tried again to open "Display Elements" and lo and behold, it appeared on my 2nd monitor.

**To Reproduce**
- using a system with more than one monitor currently connected
- open the "Display Elements" window.
- move the Display Elements window to the second monitor
- detach the monitor
- try to open the "Display Elements" window by using either the toolbar button or the View -> Windows -> Display Elements.
- try View -> Windows -> Reset to Defaults
If you cannot get to the Display Elements window then there is a problem.
If you can get to the Display Elements window, then the issue has been resolved.

**Expected behavior**
Would it be possible for xlights to do one of two things?
a. check whether a display is active before opening a window on to it. If it is not present then open the window on the primary display.
b. put the "Display Elements" window back to the primary display when View -> Windows -> Reset to Defaults

**Screenshots**
I don't have a screenshot that shows a window that is not there. :-) 

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.43

**Additional context**
I'm sure that I had been using xlights on my laptop while the second monitor was attached. I later detached the monitor and took my system with me somewhere. While away from my desk and away from my second monitor I was unable to access the Display Elements no matter what I did. Closing xlights, rebooting the computer, even upgrading xlights to the newest version did not bring back the missing Display Elements window. I'll bet that xlights was opening the window, but not anywhere that I could see it or interact with it. It wasn't until I was back at my desk with the second monitor that I was able to recover the missing window.

**Attachments**
- there were no crashes therefore no logs to include.

If you would prefer not to post your sequences publicly please say so and be ready to PM them to one of the developers when asked.

I posted this on nutcracker123 forums also.

**Comment by CharlesSmothers** [comment]
I found another issue that was related to windows on a secondary display.
Someone suggested starting xlights with the /w option.

I'll try to verify whether the /w option would reset the Display Elements back to the primary display.

If this is considered an edge case and won't be fixed - that would be understandable.
I just wished I knew about /w a few days ago.
But it would be good, I think, to have View -> Windows -> Reset to Default really reset the windows.

--
Charles

**Comment by AzGilrock** [comment]
I have always been able to restore the windows with a Reset to Defaults followed by a Dock All

**Comment by CharlesSmothers** [comment]
After using /w once, now I cannot easily reproduce the issue.
@AzGilrock  is Dock All a debugging feature?  The references to "dock all" that I could find had to do with debugging in windows.

**Comment by AzGilrock** [comment]
Well I thought if you found Reset to Defaults you couldn't miss it...lol.

![image](https://user-images.githubusercontent.com/2024669/96053475-6b868b80-0e34-11eb-8681-2c35f3d48fce.png)

**Comment by CharlesSmothers** [comment]
I'm going to close this.
--
Charles
