### ISSUE TITLE
Question about adding new wxWidget UI on Mac

### ISSUE THREAD

**Issue by this-username-is-taken** [smeighan/xLights#2292]
This is more of a question instead of a bug. I'm wondering how are `wxWidgets` are being added into xLights UI (for example, new windows and new dialogues).

I only see instructions on how to build the `wxWidgets` lib but not how to add new widgets in the UI. I see these UI is defined as .wxs in the `wxsmith` folder, but these files open up as text/xml in Xcode. I also looked up wxsmith but that seems like a plugin to CodeBlocks. I couldn't find any information about adding new wxWidgets in Xcode via a GUI editor. Obviously I can copy/paste the existing .wxs files and edit them manually, but I just wanted to know if there is a better option.

**Comment by computergeek1507** [comment]
you have to use codeblocks, I think Dan use a Windows VM and run Codeblocks on OSX

**Comment by dkulp** [comment]
Actually, I made a custom build of CodeBlocks for OSX so I don't need to use Windows.   You can grab it from:
https://dankulp.com/cb/

**Comment by this-username-is-taken** [comment]
Great! Thanks a bunch!

**Comment by keithsw1111** [comment]
For those in the future hitting this post please dont esit the wxsmith files manually or edit code generated by wxSmith as this is often if not invariably lost the next time someone tries to actually use wxSmith on the files.
