### ISSUE TITLE
Perspectives Bug - Effect Assist Window

### ISSUE THREAD

**Issue by tvengineer77** [smeighan/xLights#2299]
When changing from Sequencer to Layout or Controller tabs, the "Effect Assist" window pops back up even after closing it. It interferes with those tabs so I have to move it out of the way every time, only for it to re-appear when I go to a different tab. 

I have tried re-saving the perspective view to default without this window called up, I have also tried creating a completely new perspective without the effect assist window, and have also tried the "reset to defaults" under View>Windows and nothing keeps the Effect Assist window away.

**To Reproduce**
1. Open xLights.
2. Click on Sequencer tab - effect assist window shows up even though the perspective was saved without it.
3. Click "x" on effect assist.
4. Save perspective as default.
5. Click on Layout or Controller Tab.
6. Effect assist window re-appears once clicked - and depending on where it was last placed, can interfere with the model layout in the layout tab.

No other windows appear to function this way, so far as I can tell. Just the effect assist window.
 
![image](https://user-images.githubusercontent.com/73245348/96749167-742d1380-1398-11eb-8999-bde855007300.png)

![image](https://user-images.githubusercontent.com/73245348/96749389-bfdfbd00-1398-11eb-9656-e3edd65d2c6c.png)

![image](https://user-images.githubusercontent.com/73245348/96749433-d38b2380-1398-11eb-9fc3-51e5168a44b5.png)

 - OS: Windows 10 x64
 - xLights version 2020.43 and 44 (just upgraded to 44 this morning and still does it)

**Comment by computergeek1507** [comment]
Go to File->Preferences and verify the Effect Assist Window Setting is set to auto or off.

**Comment by AzGilrock** [comment]
Not sure everything at play here but the Effect Assist Window also has logic that display the window based on the selected effect.  Only a few effects are supported by the window so it can be set to be Alway On, Always Off, or Toggle mode which displays only when the selected effect is supported.  So go into settings and play with that mode setting.

**Comment by tvengineer77** [comment]
Ok that fixed it - it was set to Always On in the preferences. Whew! So glad to not have to deal with that little guy any more.

Thank you for your help! I'm closing this issue.
