### ISSUE TITLE
Picture effect\gif file not working all the time

### ISSUE THREAD

**Issue by broomy111** [smeighan/xLights#2301]
Hi Xlights team

I'm having a problem with trolls sequence from many years ago.  I'm bring it back for this year and I had moved all of my files from google drive to drobox,  and I've pointed all the picture effects to the new locations and I close the sequence, relaunch and several of the gif and png effects dont work and show just red.  The file path is correct.  I click browse, navigate to the file again, select it and then it shows up.  Close the sequence and it does it again and doesnt recognize the file.

These effects are on the mega tree and seem to effect the Branch character more.  

Thank you

Kevin

Windows 10 pro
Xlights 2020.44 64bit

![2020-10-21 20_39_14-xLights - C__Users_broom_Dropbox_Xlights_RGB_2020_Christmas_Sequences_Can't stop](https://user-images.githubusercontent.com/28641357/96822006-eaa03480-13dd-11eb-8890-116e1624e85e.png)

[Can't stop the feeling-KB.zip](https://github.com/smeighan/xLights/files/5419895/Can.t.stop.the.feeling-KB.zip)

**Comment by keithsw1111** [comment]
It is hard to verify your story just using the files as I cant be sure you do things the way I do things. I would need to see a video showing it broken (check sequence with error). Showing you fix it (check sequence no error). Saving it. Closing it. Opening it (check sequence error returns).

**Comment by broomy111** [comment]
Sounds good Keith, I will get the info this evening and update the github
report.

Thanks sir

**Comment by broomy111** [comment]
Hi Keith, I just noticed that even though I browse to the file location for the picture effect to point to the new location, I hit save and if I go to close the sequence out, Xlights asks me to save even though I haven't made any changes after the first one and I had already saved. So I save again.   When I open the sequence back up and look at the file path of the picture effect, its not correct.

Correct path - C:\Users\broom\Dropbox\Xlights\RGB\2020\Christmas\Sequences\Can't stop the feeling- #3\Eyeless trees and eyes\Toll eyes up.gif

Path that shows up after opening sequence- C:\Users\broom\Dropbox\Xlights\RGB\2020\Christmas\Sequences\Can&apos;t stop the feeling- #3\Eyeless trees and eyes\Toll eyes up.gif


I've attached the check sequence and the behavior seems to be happening mainly with the .gif files.

Let me know if you need additional info

Thanks sir

[xLi98D8.tmp.txt](https://github.com/smeighan/xLights/files/5434022/xLi98D8.tmp.txt)

**Comment by keithsw1111** [comment]
I need the video I asked for. Only with that can I validate what you are doing that we are not handling correctly.

**Comment by broomy111** [comment]
Sorry Keith, This is a quick capture.  Let me know if you if the video resolution isn't good enough.

https://vimeo.com/471835227

**Comment by keithsw1111** [comment]
The video does not really do what i asked ... the check sequence things were important because it would prove the correctness of the change. I also kind of need commentary otherwise I have to guess what i think you are showing me.
