### ISSUE TITLE
Add a single receiver

### ISSUE THREAD

**Issue by dszoka** [smeighan/xLights#2306]
Add an option to just add a single receiver to a F16 under options, so instead of just 1 or 2 expansions you can add a single receiver, to be used off Serial port 1 

So it would add just 4 ports to ur layout

**Comment by darylc** [comment]
When you add a single receiver off of Serial port 1, the f16v3 does not actually create any more outputs, you re-use 4 of your existing outputs for those receiver ports, and set the mapping of those outputs manually in the f16v3.

If you don't want to use any of the original 16 outputs, then you tell the f16v3 you have an expansion board (even though you don't).

I believe xlights mirrors the f16v3 behavior appropriately and am not convinced xlights changes are required.
