### ISSUE TITLE
Crashed whike saving sequence timing marks

### ISSUE THREAD

**Issue by oilyd** [smeighan/xLights#2308]
**Describe the bug**
After clicking save sequence the dialog window opens and xlights just crashed forcing a close and loosing everything.  Using 64 on windows 8.1.

**To Reproduce**
Steps to reproduce the behavior: set audio track in sequencer add timing marks then save it just crashes on me.
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
Save sequence so I can shut laptop and get some air.

**Screenshots**

**Versions (please complete the following information):**
 - OS: windows 8.1
 - xLights version latest version

**Additional context**

**Attachments**
No attachments available at present as have to hard shutdown xlights using task manager.

**Comment by keithsw1111** [comment]
There is not enough information here. At a minimum we need your show files and ideally your logs.

**Comment by oilyd** [comment]
Hi Keith so I managed to get it working for some reason the xlights download from the website worked and I re-installed it that way and everything seems to be fine bow. Forgive my ignorance in the lack of log files
/information.  If any further issues arise I will make sure they are included. As I said all good so far Thanks.


Sent from my Samsung Galaxy smartphone.



-------- Original message --------
