### ISSUE TITLE
Enhancement request: Add ability to save/recall display profile

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#231]
When creating a sequence it would be nice to load a profile that would contain a fixed/customizable set of display elements/layers.

**Comment by gerry4** [comment]
Within LSP, this is achieved when creating a new sequence , by optionally (tick / untick) specifying the default sequence  name (ie including fully qualified path name) to load the models (channels and layers in LSP terminology) from.

**Comment by stevegiron** [comment]
This is now a function of the Views feature.

**Comment by gerry4** [comment]
Yes , Great enhancement ....even better than having a single default !
 

Gerard
 
Date: Thu, 9 Jul 2015 13:57:57 -0700
