### ISSUE TITLE
Preferences -> Default Brightness

### ISSUE THREAD

**Issue by AleXthePunK** [smeighan/xLights#2310]
When you give a Falcon controller full Xlights Control it erases all of the ports, and starts fresh on the string output settings.
At the same time, it sets all of the brightness (by default) to 100%

The feature request is: Somewhere in the preferences dialog, a setting that lets you set the overall default brightness for full control.

For example: You set this preference to 30%, and when it clears all of the string ports on the Falcon controller, it sets all of the ports to 30%

**Comment by cathelest** [comment]
Do you not set your brightness in xlights?
If you setup each of your props brightness (Can also select all and bulk edit brightness).
And upload.
Does the upload not set the string output brightness based on what you set in xlights?

**Comment by AleXthePunK** [comment]
Yes, I'm aware you can set your brightness on the prop level. That is not what I put this "enhancement" in. If it wasn't setting the brightness, I would have put it as a bug.

Some people still do things manually. If you have empty ports on a Falcon controller, it will set the default to 100%. If you manually go in and change them to 30% because you have no prob there, the next time you upload it switches it back to 100%. This is just one example.,
