### ISSUE TITLE
xLights on pixelbook C0A - display/resolution issues

### ISSUE THREAD

**Issue by dekke046** [smeighan/xLights#2312]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
There is no bug in terms of xLights functionality.
I am trying to run the appimage (2020.45) version of xLights on a google Pixelbook, which results in unusable GUI, see the attached image and console output.

Console output after closing xLights:

```
./xLights-2020.45-x86_64.AppImage 
./src/common/stdpbase.cpp(62): assert ""traits"" failed in Get(): create wxApp before calling this
./src/common/stdpbase.cpp(62): assert ""traits"" failed in Get(): create wxApp before calling this

(AppRun.wrapped:14363): Gtk-WARNING **: 23:08:27.092: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


(AppRun.wrapped:14363): Gtk-CRITICAL **: 23:08:27.092: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:14363): Gtk-CRITICAL **: 23:08:27.092: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(AppRun.wrapped:14363): Gtk-WARNING **: 23:08:27.092: gtk_widget_size_allocate(): attempt to allocate widget with width 6 and height -19

(AppRun.wrapped:14363): Gtk-CRITICAL **: 23:08:27.092: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

Layout - glVer:  4.3 (Core Profile) Mesa 19.2.8  (virgl)(Red Hat)

```

If there are any suggestions how this can be improved I would like to hear this.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Download appimage
2. chmod +x xLights-2020.45-x86_64.AppImage
3. ./xLights-2020.45-x86_64.AppImage
4. See screenshots

**Expected behavior**
A usuable GUI

**Screenshots**
![image](https://user-images.githubusercontent.com/12866158/97500744-6d8e3580-1970-11eb-892c-7bf7b38525ef.png)
![image](https://user-images.githubusercontent.com/12866158/97500797-85fe5000-1970-11eb-96d2-fcbb03cf203f.png)
![image](https://user-images.githubusercontent.com/12866158/97501250-41bf7f80-1971-11eb-8c68-e333bbcbe931.png)

**Versions (please complete the following information):**
 - ChromeOS: Versie 86.0.4240.77 (Officiële build) (64-bits)
 - OS:
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
 - xLights version 2020.45

**Comment by reenx** [comment]
Is this the same problem as #2224?

**Comment by dekke046** [comment]
> Is this the same problem as #2224?

@reenx  you are correct, these are the same as #2224 and #2313 

Version 2020.26 seems to be just fine.

**Comment by dekke046** [comment]
Same problems as described in issue #2224 and #2323 closing this duplicate.
