### ISSUE TITLE
Vendor choice disables protocol options on controllers tab

### ISSUE THREAD

**Issue by HansonElectronics** [smeighan/xLights#2315]
When using Hanson Electronics vendor and model DMX2-18 in particular the option for the "open dmx" and other protocols are removed. When configuring an open dmx dongle the vendor and model probably shouldn't effect the choices.
I don't know what other models this effects as it was only during a zoom session that I saw this. My laptop is x32 and currently has 2020.12 and I can't see the issue myself.

**Comment by keithsw1111** [comment]
This is not a bug. As I understand it this is just a dumb dmx device with no upload characteristics and as such setting the protocol is irrelevant.
