### ISSUE TITLE
Upload input and upload output do not work with BBB and FPP Proxy

### ISSUE THREAD

**Issue by thisim** [smeighan/xLights#2316]
Upload input and upload output do not work with BBB and FPP Proxy.
As you can see from my screenshots, I am accessing my BBB's web page via Xlight and the FPP Proxy.
On the other hand, it is impossible to upload the configuration of inputs or outputs.
On the other hand, if I connect my computer to the network dedicated to my LEDS, the upload of inputs and outputs works but I no longer have access to the web page of my BBB when I click twice in the controller.
I think the upload input and upload output function does not go through the fpp proxy when the BBB card is selected as controller..
I have a friend who has the exact same problem.
With a falcon F16V3, no problem with the upload input and upload output via xlights and fpp proxy.

 - OS: Windows 10
 - xLights version 2020.46 64bit

![1](https://user-images.githubusercontent.com/31959517/97812372-23af9300-1c81-11eb-802f-3bf36b14a286.JPG)

![2](https://user-images.githubusercontent.com/31959517/97812375-2ca06480-1c81-11eb-88e3-f094c7b40c7d.JPG)

**Comment by thisim** [comment]
Have you managed to reproduce the problem? I have a friend who has the exact same problem.
With a falcon F16V3, no problem with the upload input and upload output via xlights and fpp proxy.

**Comment by keithsw1111** [comment]
Go to the zoom room. If the problem persists through their troubleshooting update this ticket with what you learn in the discussion and we will look at it. 99% of the time this is user error and there is not enough here to work out what that might be.

**Comment by thisim** [comment]
![3](https://user-images.githubusercontent.com/31959517/98039182-973ad700-1e1e-11eb-8f80-c5c9cdec3b2f.JPG)
I am French and it is not possible to use zoom because I do not speak English.
Here is another screenshot where we can clearly see in the log that xlight does not communicate through the fpp proxy. I also test the FPP connect function of xlights and same problem. For it to work, I have to connect directly to my LEDS network.
