### ISSUE TITLE
Version 2020.46 Single Line Output to F16v3

### ISSUE THREAD

**Issue by FormatHDA** [smeighan/xLights#2319]
OS: Windows 10 Build 1909
xLights: 2020.46
Falcon F16v3 firmware 2.56 with 1x expansion board

Summary
Update to Falcon F16v3 controller has the incorrect number of pixels for single line with two nodes per light.

Steps
1. Launch xLights 2020.46
2. Controllers Tab
3. Create connection to Falcon - Auto Layout=Enabled, Auto Size=Enabled, Full xLights Control=Enabled or Disabled, IP address
4. Layout Tab 
5. Create single line in layout tab
6. Single line properties - #Strings=1, Nodes=12, Lights/Nodes=2
7. Save Controller and Layout Tabs
8. Controllers Tab
9. Click Visualize and drop single line on port 1
10. Save Controller and Layout Tabs
11. Highlight F16v3 controller
12. Click upload inputs - Success from bottom left status bar
13. Click upload outputs - No errors appear
14. Click Open button to launch website of F16v3
15. Click Output Settings -> String Outputs
16. Port 1 has 12 pixel count

Expected behavior:
On the Visualizer the port should have 24 pixels listed, not 12.
On the Falcon website, Pixel count should be 24, not 12.  (1 string with 12 collection of 2 pixels each)

Temporary Fix 
Update the controller to match the number of pixels: 24

<img width="326" alt="Visualizer" src="https://user-images.githubusercontent.com/73865582/97946901-aa37a380-1d59-11eb-8a27-677cef75a249.png">
<img width="620" alt="Falcon Configuration" src="https://user-images.githubusercontent.com/73865582/97946902-aa37a380-1d59-11eb-8421-a8bbe340b8d7.png">
<img width="457" alt="Single Line" src="https://user-images.githubusercontent.com/73865582/97946903-aa37a380-1d59-11eb-9013-49166871c9a0.png">
<img width="581" alt="Falcon Website" src="https://user-images.githubusercontent.com/73865582/97947007-f7b41080-1d59-11eb-8e49-278d63ddd0bb.png">

**Comment by computergeek1507** [comment]
The Lights/Node property just changes the number of lights on the model preview. If you want two pixels group together in the controller, Set the group count to 2 in the controller connection settings.
![image](https://user-images.githubusercontent.com/2293065/97947595-b91f5580-1d5b-11eb-875b-698e06b566d1.png)

**Comment by FormatHDA** [comment]
Thank you CG1507 for showing me the area in the layout tab to control the grouping

I see the falcon has updated correctly to include the grouping.  Visualizer shows 12 pixels unfortunatally, super minor i know.

<img width="496" alt="Pixel Count" src="https://user-images.githubusercontent.com/73865582/97947920-d3a5fe80-1d5c-11eb-87d7-a151eaf5be4f.png">
<img width="457" alt="Layout tab" src="https://user-images.githubusercontent.com/73865582/97947975-05b76080-1d5d-11eb-8dc5-a2735ac06c0b.png">

**Comment by keithsw1111** [comment]
I actually dont think this is a bug at all. 2 lights per node does not change the number of nodes sent to the controller ... just how many lights are displayed in the preview. The grouping just tells the controller to repeat the same data to multiple nodes ... it does not change the number of nodes ... so 24 nodes with a grouping of 1 is the same as 12 nodes with a grouping of 2.

**Comment by FormatHDA** [comment]
While i disagree, and think the pixel count should show the number of lights being powered, I'll close the request.
Thank you for your time and dedication to the software.
Mark
