### ISSUE TITLE
Save as folder path set to current working folder path

### ISSUE THREAD

**Issue by FormatHDA** [smeighan/xLights#2320]
OS: Windows 10 1909
xLights: 2020.46

Request Summary:
When saving as a sequence, please default the current working folder path and not the show directory folder.

Steps:
1. Open sequence not currently saved in the root of the show directory.
(i.e. C:\users\bob\documents\xlights\sequences\Killer_Song\Killer_Song14.xsq
2. Click File - Save Sequence As
3. The default save path shown is the show directory path
4. Request is to default the save path to the current working folder path
(i.e. C:\users\bob\documents\xlights\sequences\Killer_Song\ )

**Comment by keithsw1111** [comment]
If i implement this I will have someone else ask for the reverse ... we just cant win with them.

**Comment by FormatHDA** [comment]
Fair, and understand the challenge of how design the UI.
Thank you,
Mark
