### ISSUE TITLE
Set group count not working as expected

### ISSUE THREAD

**Issue by corywagner** [smeighan/xLights#2321]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Background:
I created a custom model that contains 56 RGB pixels. To save channel space, and because the model really does not need anything but illumination, I want all Pixels to behave as 1 group; same effects applied to each pixel. 

I have done this in previous years by setting the group count directly in my Falcon controller.  However, this year, I decided to optimize and simplify my display network and let Xlights control the controllers (per you BKM on numerous videos).

First Issue:
When I try to set the groups count in my model to 56, it will not accept the number.  It seems to only accept up to 50; anything above 50, and it won't save the number.
Second Issue:
If I try to use any number great than 1 or less than fifty, then try to export to the controller (Upload Output). I get an error:
![Screen Shot 2020-11-04 at 11 46 07 AM](https://user-images.githubusercontent.com/73963738/98160825-9f812980-1e93-11eb-8362-1ac26fde1df9.png)
Model file attached
[Piggy.xmodel.zip](https://github.com/smeighan/xLights/files/5490192/Piggy.xmodel.zip)

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to 'layout"
2. Click on 'create new custom.'
3. edit model data to include 56 pixels
4. Strings=1
5. set group count to 56
6. save
7. Will not save
8. change group count to 40
9. Save will work; then
10. got to controllers
11. Click on proper controller
12 Click "upload output"
13. See error

**Expected behavior**
I expect that when strings=1 and Group count=56, then upload the configuration to the controller, that same data will reflect in the controller (output settings- string ports) as configured.  I expect that the model will behave as a single pixel and what ever I sequence to that model, all pixels will behave the same.

**Screenshots**
attached

**Versions (please complete the following information):**
I am using a Falcon F16 controller via ethernet. firmware version 2.54.
I am running xlights on a windows10 computer with i7 processor and 16 GB RAM - pro, latest build
Xlights version 2020.46

**Additional context**
Maybe I misunderstand how it works in xlights, nonetheless, it works as I expect if I configure the controller manually

**Attachments**
attached

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by kbostick88** [comment]
I can confirm i was able to reproduce issues with Group counts. When you set Group Count in Xlights it saves, but when you check the controller, the group count is not sent/set correctly. If you manually set the group count in the controller it will work as expected. This issue is not sequence related, it is also an issue in test mode in Xlights

**Comment by computergeek1507** [comment]
I increased the max group to fix the first issues, For your case you only want a single pixel model and then you would set the group gout to 56. The total pixel count including the groups must be under 1024 that why the error is popping up.

**Comment by corywagner** [comment]
Thank you!  Seems to work!
