### ISSUE TITLE
Slight enhancement to visualizer to assist differential receiver layout

### ISSUE THREAD

**Issue by TxBillbr** [smeighan/xLights#2324]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
I run 4 K40Ds, 2F8-Bs, etc.etc. It is tough picturing the differential breaks in the ports. I currently use a manual process to do my planning. I print the visualizations of all my controllers and then use colored thin sharpies to mark out receivers and other notes. Then I go back into visualizer and make the system align to 4-port boundaries. The colored boxes for smart differential receivers got me to thinking there might be a fairly simple way for the user to add coloration to help in the layout work.  I want to be able to visually identify the four ports on the end of a long wire.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
It would be excellent if at a minimum we could get a color assigning a port or group of ports to a "legacy differential receiver". This would allow the user to visually see the differential receiver boundaries. An over the top solution would be to allow the user to assign colors/names/notes to groups of ports. This would allow folks like me to use color or names to differentiate receivers, purpose, use_case, etc. by assigning arbitrary colors/names to ports.  Today I do this work as well as load balancing, PSU placement, and layout planning with the help of a huge spreadsheet. The meta-data helps me determine if I am overloading PSUs, need F-amps, or power injection.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
A potentially potent way to handle this is to allow users to have an arbitrary keyword list and notes field per controller and per port. That would allow adding metadata and choosing the line and fill color based on a keyword.  No keywords? no problem. It would default to today's colors. The idea would be to color the port boxes on the visualizer screen based on some mouse gesture? (right-click menu dropdown with keyword list and + - to add/remove? dialog box? whatever...).  The notes could be seen with a roll-over tool-tip kind of thing.  Even if the meta data is only visible via the csv export, it adds a central place to track an manage the complexity.

**Additional context**
_Add any other context or screenshots about the feature request here._
The visualizer has been an outstanding feature for XLights. I know it is not a simple beast.  Thank you for that work. It has saved me countless hours in my layout time. Even having a small number designating the differential receiver port on those ports would be helpful. There are certainly many ways to advance the function of the visualizer. Thanks for giving it some thought.

    .--------------------------.
    | Pixel Port 13 [1]         |
    | Pixels: 243               |
    `---------------------------'
    .-------------------- ------.
    | Pixel Port 14 [2]         |
    | Pixels: 24                |
    `---------------------------'
    etc...
Example markup for me...
![image](https://user-images.githubusercontent.com/44479016/98321473-c3835e80-1faa-11eb-8fe1-3a372326e3d3.png)

**Comment by darylc** [comment]
I wonder if a generic comments box per output would be a good solution here?  It's something I would like to see for other reasons and is probably useful for a lot of people.

**Comment by keithsw1111** [comment]
I agree there is a problem here to solve ... but a solution that is suitably controller independent needs to be found. While the FPP controllers and the Falcons are pretty similar (although not the same as the FPP controllers dont have the Bank limitations), the Hinkspix controllers are quite different (at least that is what i understand as i am not close to the details). Whatever we come up with I am keen represents all the controller configs but in a way that puts the specifics in the controller xml file ... and not in a bunch of vendor specific code in the visualiser.

**Comment by computergeek1507** [comment]
this was added in version 2020.49

**Comment by TxBillbr** [comment]
Thanks for the prompt add. Having the color bars helped me. Hopefully others as well.
