### ISSUE TITLE
Font size of model list in sequencer window doesn't auto-adjust correctly for pixel density of screen

### ISSUE THREAD

**Issue by zephyrr** [smeighan/xLights#2326]
**Describe the bug**
My laptop has a high pixel density screen.  Most windows software, including xLights, automatically adjusts to use a reasonable font size - EXCEPT the rows of the sequencer display, whose text is unreadably small.  So far, all the other windows in xLights are correct, so I suspect someone may have forgotten some kind of adjustment for that one window, and that this can be an easy fix (since all the other windows do it right).

**To Reproduce**
Open xLights, create models, click on Sequencer tab, create new sequence.
The list of models on the left side of the Sequencer window will be unreadably small; text everywhere else is appropriately sized.

**Expected behavior**

The Sequencer window would have fixed text sizes (for model/group names) similar to the other windows.
 - OR -
Add a vertical zoom function to the sequencer window, increasing/decreasing the row height with appropriately scaled fonts

**Screenshots**
![Screenshot 2020-11-06 111014](https://user-images.githubusercontent.com/4857690/98407298-472d6180-2024-11eb-905f-46b80c0db601.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: 2020.45 64bit

**Additional context**
Using Dell laptop with high pixel density screen

**Attachments**

**Comment by dkulp** [comment]
There is a setting in the Preferences panel for the size of these.  Some folks like it small (even on the hi res screens) to allow more models to be displayed and thus see more of their display.

**Comment by zephyrr** [comment]
Excellent, thank you.  (I did search the documentation with all the keywords I could think of, but it's a bit obscure without your hint).

The text for the model list being adjustable solves most of the issue in a good way.  However, the "timing" text just above the list is still tiny.  Is that deliberate or is there some way to adjust that as well?
