### ISSUE TITLE
XLights 2020.46 Crash after compiling Shader xLights Audio - fractal audio.fs

### ISSUE THREAD

**Issue by dennismccreery** [smeighan/xLights#2327]
1.  Downloaded the PPD sequence "Don't Stop the Santa Man"
2.  Opened XLights and rendered this sequence in place and saved.
3.   Opened a blank XLights instance and created a new musical sequence with the music saved from 1. above
4.  Imported from the PPD sequence rendered in 2. above
5.  Saved the resulting sequence
6.  Attempted rendering, crashed four times consistently
7.  Appears to crash just after compiling the xLights Audio - fractal audio.fs shader

Crash report attached

System configuration:
Computer:
      Computer Type                                     ACPI x64-based PC
      Operating System                                  Microsoft Windows 10 Pro
      Internet Explorer                                 11.572.19041.0 (IE 11.0.210)
      Edge                                              86.0.622.63
      DirectX                                           DirectX 12.0
      Date / Time                                       2020-11-07 / 07:38

    Motherboard:
      CPU Type                                          OctalCore Intel Core i7-9700, 4515 MHz (45 x 100)
      Motherboard Name                                  Asus ROG Strix Z390-E Gaming  (3 PCI-E x1, 3 PCI-E x16, 2 M.2, 4 DDR4 DIMM, Audio, Video, Gigabit LAN, WiFi)
      Motherboard Chipset                               Intel Cannon Point Z390, Intel Coffee Lake-S
      System Memory                                     65451 MB  (DDR4 SDRAM)
      BIOS Type                                         AMI (11/26/2019)

    Display:
      Video Adapter                                     GeForce RTX 2070 SUPER  (8 GB)
      3D Accelerator                                    nVIDIA GeForce RTX 2070 Super
      Monitor                                           LG UltraWide WQHD (DisplayPort 8-bit)  (2801348047)

    Multimedia:
      Audio Adapter                                     nVIDIA TU104 HDMI/DP @ nVIDIA TU104 - High Definition Audio Controller
      Audio Adapter                                     Realtek ALC1220P / ALC S1220A @ Intel Cannon Point PCH - cAVS (Audio, Voice, Speech) [B0]

    Storage:
      Storage Controller                                Intel(R) Chipset SATA/PCIe RST Premium Controller
      Storage Controller                                Microsoft Storage Spaces Controller
      Disk Drive                                        Intel Raid 1 Volume  (7452 GB)
      Disk Drive                                        Samsung SSD 860 EVO 4TB  (4000 GB, SATA-III)
      Optical Drive                                     ATAPI iHES212   3
      SMART Hard Disks Status                           OK

    Partitions:
      C: (NTFS)                                         3725.4 GB (2689.8 GB free)
      D: (NTFS)                                         7452.0 GB (7451.7 GB free)
      Total Size                                        11177.4 GB (10141.5 GB free)

[xLights_dbgrpt-23756-20201107T072941.zip](https://github.com/smeighan/xLights/files/5504988/xLights_dbgrpt-23756-20201107T072941.zip)

**Comment by dennismccreery** [comment]
Downgraded to 2020.45 and it rendered successfully using the same configuration.

**Comment by keithsw1111** [comment]
I just tried it using the audio I have for that song and that shader and it didnt crash. Maybe package it up and send it to us (but obviously not here).

**Comment by dennismccreery** [comment]
Here's a link to the sequence I was trying to import (including the music):

https://1drv.ms/u/s!Aj3J0O38KlwJhdtsjh28sWxecZVMPA?e=Qfn2ds

You should already have the XSQ that I was trying to import into.  Attached is the mapping file I was using for the import.

Hope that helps.
[Pro_PPDmapping.zip](https://github.com/smeighan/xLights/files/5506658/Pro_PPDmapping.zip)

Regards,

Dennis

**Comment by dennismccreery** [comment]
Upgraded to .47 and it seems to work now, so you can close this.
