### ISSUE TITLE
XLIGHT FREEZES WHEN CLCIKING ON SUBMODEL

### ISSUE THREAD

**Issue by Parkviewlights** [smeighan/xLights#2328]
Just downloaded .47 (Windows 10) and the following issue has occurred, Gone back to 46 and the issue has continued into previous releases now.

When in layout , select any prop and click on Sub Model . 
The screen locks up but doesn't come up with "NOT RESPONDING" CTRL, ALT & DEL 
Check CPU Percentage etc and everything is ok but it doesn't allow you to do anything in Xlights after clicking on the tab
You have to end task and restart the program 

I've included a screenshot of the dulled out browser bar in xlights and the Task manager CPU Levels ETC
 
![Submodel issue  47](https://user-images.githubusercontent.com/74182171/98529983-3e33ce80-2276-11eb-82dc-1e6e8d243f06.png)

Cheers

**Comment by computergeek1507** [comment]
The submodel dialog is probably opening off screen. Go to "View->Windows->Reset To Defaults" to reset the window positions before you try to open it.

![image](https://user-images.githubusercontent.com/2293065/98618661-a8c52880-22cf-11eb-8e8f-c172810e432b.png)

**Comment by AzGilrock** [comment]
And I usually follow that up with a Dock All

**Comment by Parkviewlights** [comment]
Many Thanks. 

I don’t know how this has happened but that has solved it . 

Much appreciated 👍




Kind regards 

Simon Jones 
Airetech
07807044207
Simon@airetech.co.uk
