### ISSUE TITLE
Hard crash - when typing a period before a number in the "In Transition" field

### ISSUE THREAD

**Issue by smtpboy** [smeighan/xLights#2329]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When trying to set a time for the In Transition, if you type a period before a number, such as ".5" - the program instantly crashes.  If you type a number first, such as "0.5" this does not happen.

**To Reproduce**
1. Select an effect.
2. Click in the "Time(s)" box under "In Transition" in the "Layer Blending" window.
3. Press the "." key before typing a numeral.
4. Program crashes every time.
5. Happens in both brand new clean sequences with nothing in them as well as established sequences and is fully reproducible.

**Expected behavior**
Program doesn't crash.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...] MacOS 10.15.7
 - xLights version [e.g. 2019.37] 2020.47

**Additional context**

**Attachments**
https://www.dropbox.com/s/nnrxglnp7zmp2np/xLightsProblem.zip?dl=0

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
Maybe its OSX specific. I put a .5 in transition in on a fade on an on effect and a .7 transition out and it didnt crash on windows.

**Comment by keithsw1111** [comment]
when you say hard crash do you mean it just closes, hangs or crashes with an error dialog. I assume not the last option.

**Comment by smtpboy** [comment]
@keithsw1111 Completely crashes/closes, generates an Apple core dump and opens up the Mac error reporting dialog.

**Comment by smtpboy** [comment]
@keithsw1111 I also tried it on Windows and couldn't replicate it there, it happens on Mac every time though.

**Comment by dkulp** [comment]
2020.47.1 is in review which fixes this.

**Comment by smtpboy** [comment]
Thanks gents.
