### ISSUE TITLE
Sequence crashes in 4.0.33

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#233]
I created a new sequence, defined one model 'Singing faces' and imported a purchased LOR sequence (using the Import effects tab) , which came through very well ! Saved the sequence.
Then opened it again and added all my models , then pressed save. It displayed a number of messages indicating that some models could not be found eg 'Could not find a model or Group named Lanterns ,' (repeated for Icicles and others) etc - which are old models , so not sure where it is getting these from , but it still saved the sequence. Noticed that I could not see the sequence information of the singing face in the sequencer ,(but it still played in preview ),  (I realise now that I have to toggle nodes )

Imported audacity timing marks and pressed save and it crashed.

So I tried this a few more times ie to import audacity timings and either save , or render first , then save , but it kept crashing. Have not yet added any effects. 

Can open and play the sequence no problem.

I cant upload the debug zip file as it says file type not supported , so I will post this on the forum in the bugs section (same heading , user Gerry)  and upload the zip files there   

Regards

**Comment by gerry4** [comment]
Gilrock has responded and I have provided additional data as well as further crash reports on the same post on the forum.

**Comment by stevegiron** [comment]
Closing per G
