### ISSUE TITLE
2020.47 (MAC) crashing immediately when I scroll in a sequence

### ISSUE THREAD

**Issue by bchiaino** [smeighan/xLights#2330]
I just grabbed .47 from the App Store, opened a sequence and went to scroll down and it immediately crashes every time I try and do this. 

video - https://youtu.be/3lUWyXKj0gU
Packaged sequence - https://drive.google.com/file/d/1VrM2IImQMjBgNUf-RQcZAplkq0fY6tGF/view?usp=sharing

Is there anyway to go back to .46? I can't do anything with this sequence now. Thank you

MacBook Pro  - 10.15.7
8gb ram
2.3 i5

**Comment by SOHARMON** [comment]
I am having the exact same problem with an opened sequence from Holiday Lights.  It has worked fine for a couple of weeks them xLights updated and now crashes upon scroll.  It also won't display house preview anymore.

**Comment by SOHARMON** [comment]
Hey bchiaino,

I went back on Time Machine and restored the app back to 2020.45
Works perfectly.   Until they get the problem fixed in 2020.47

**Comment by dkulp** [comment]
2020.47.1 is in review which fixes this.
