### ISSUE TITLE
photo not working on mega tree

### ISSUE THREAD

**Issue by Lenchuckd** [smeighan/xLights#2335]
Hi there, I'm not sure if i'm in the right place.  Wanted help for my mega tree.  The photo I have displays correctly on my screen but when played on the actual tree, instead of showing in the middle, it shows half on the top and half on the bottom.  I believe its because I am running 8-100 node strings folded instead of 16-50 node strings.  But every other thing works and I have my tree set up correctly I believe.  Is there anything I am missing?

**Comment by AzGilrock** [comment]
So what do other effects do?  You say "every other thing works" but I have no idea what that means.  Is that all other models or all other effects on the tree?

**Comment by Lenchuckd** [comment]
Hi there, sorry for not being more precise.

All effects render correctly and play correctly on my mega tree except for
pictures and moving pictures.  When I play a picture on my computer it
looks great.  When I move it to the actual mega tree it doesn't work. If
the picture shows on the middle of my mega tree model on the computer, it
then plays scrambled on the top and bottom of the tree.

I have the tree submodled into top middle and bottom.  The picture is
supposed to be on the middle sub model but alternates top/bottom on the
tree.

My tree is 8 100 pixel strands folded to 16 50 pixel strands and is set up
that way in my layout tab.

All other effects .. on, off lines text etc work great.

Thanks in advan for your help.

Dave.

**Comment by AzGilrock** [comment]
Ok now you're throwing another wrinkle in the equation.  You're putting it on a submodel.  So does the picture work ok if its just put on the model?  Create a new sequence, put a picture on the model, and package the sequence.  We don't trust that you set it up right all because you said so.

**Comment by Lenchuckd** [comment]
Hi, I already tried that... Same result unfortunately... I stopped the
picture on my whole tree model and same result....

**Comment by AzGilrock** [comment]
Try a different photo.  Make sure to re-save it in Paint so it doesn't have any extra formatting junk tied to it.

**Comment by Lenchuckd** [comment]
Can you advise the re-save part?  So open it with paint then save it as the
same file type?

And I have tried with other photos... Same result.  I can send screenshots
of my setup and node layout if that helps?

**Comment by keithsw1111** [comment]
My guess is you have not set zig zag correctly. You dont provide any details so i cant tell if it is right but ...

1. # strings should be set to the number of data cables going to your controllers.
2. # nodes per string is the number of nodes on each string
3. # strands per string is the number of times each string zig-zags up and down the tree.

So a 12 string, 50 nodes per string, 1 strand per string tree ... and
a 3 string 200 node per string, 4 strand per string tree
will look the same on the screen but display very differently on a physical tree if they dont match the actual wiring.

**Comment by Lenchuckd** [comment]
Hey Keith, thanks for the response.
I am running an 800 light mega tree.  I am running an 8  - 100 node strands
which start at the bottom, fold at the top and  run back down, so 50 up 50
down.  Below are my settings in xlights.  I believe they are correct?

I am running a round 180degree tree.

My settings are:
bottom/top ratio - 6
Perspective - 2
# Strings - 8
Nodes / String - 100
Strands / String 2
Starting location - Bottom left

If you could advise it would be greatly appreciated

Regards,

Dave Lenchuck.

**Comment by AzGilrock** [comment]
To be honest everything you've said doesn't not sound possible.  You say that the photo looks good on the preview in xlights but displays wrong on the actual tree.  So that sounds like a mismatch between the xLights setup and controller setup.  But then you say all other effects are fine.  Its not really possible for both things to be true.  So pretend you are in court and need to show us evidence.  PIctures/screenshots of controller setup and xlights setup and/or videos mean a lot more than just text you type here.

**Comment by Lenchuckd** [comment]
Will do!  I know... Im losing my mind over this!
I'm attaching my string layout in my controller,
my mega tree settings,
my sequencer settings
and other settings...
once again, it displays on the tree blank in the middle and puts the logo
scrambled on the top and bottom... I have just tested this with other
photos in other sequences  this morning and same thing.

I have a "domenic the donkey" routine where I have various donkeys in the
sequence, display on the computer, don't display on the tree... (top an
bottom scrambled again.)  I really hope this helps...
My physical strands are 100 nodes... starting bottom going up 50 then going
back down 50... so for output 17, 50 up 50 down etc....

**Comment by Lenchuckd** [comment]
I can't film the actual tree right now because its daytime! but I can send
what its doing after... here's some more evidence!

**Comment by Lenchuckd** [comment]
hey sorry here's the 2 photos for my node layout... they wouldnt fit on one
screen!

**Comment by AzGilrock** [comment]
Drop a Butterfly effect and see if it looks scrambled or not.  It should have a red diagonal going to the bottom left corner.

**Comment by AzGilrock** [comment]
BTW Im not seeing any photos.  You have to actually go to the github website to attach screenshots you can't just email them back.

**Comment by Lenchuckd** [comment]
ok i will do... the butterfly effect does have the diagano red line

**Comment by Lenchuckd** [comment]
![butterfly](https://user-images.githubusercontent.com/74312259/98976580-87d62080-24e5-11eb-8206-7501a238bffb.PNG)
![controller page](https://user-images.githubusercontent.com/74312259/98976581-886eb700-24e5-11eb-834c-7561fc875e77.PNG)
![domenic donkey sequencer](https://user-images.githubusercontent.com/74312259/98976582-886eb700-24e5-11eb-80b4-6cb250a5244f.PNG)
![domenic donkey settings](https://user-images.githubusercontent.com/74312259/98976583-886eb700-24e5-11eb-9c24-27fd632963c7.PNG)
![mega tree settings](https://user-images.githubusercontent.com/74312259/98976584-886eb700-24e5-11eb-84b1-69119277a3f0.PNG)
![Model Preview](https://user-images.githubusercontent.com/74312259/98976586-886eb700-24e5-11eb-903f-ac47d021dff6.PNG)
![node layout 2](https://user-images.githubusercontent.com/74312259/98976587-89074d80-24e5-11eb-8137-e1e89b722c6f.PNG)
![node layout](https://user-images.githubusercontent.com/74312259/98976590-89074d80-24e5-11eb-9813-879289f5179f.PNG)
![sequencer](https://user-images.githubusercontent.com/74312259/98976591-89074d80-24e5-11eb-8726-26a1f1963849.PNG)
![string layout](https://user-images.githubusercontent.com/74312259/98976592-89074d80-24e5-11eb-98c9-a91f8704fb0d.PNG)
![whole layout](https://user-images.githubusercontent.com/74312259/98976594-89074d80-24e5-11eb-9a56-dea70c6382e2.PNG)
![xlight settings](https://user-images.githubusercontent.com/74312259/98976596-899fe400-24e5-11eb-9f04-59cca1105c5b.PNG)

**Comment by Lenchuckd** [comment]
hope this helps!

**Comment by keithsw1111** [comment]
Controller settings? I would also like to see controller connection properties ... maybe you zig zagged on the controller as well as in xlights (which would undo the zig zag).

**Comment by Lenchuckd** [comment]
Ok I will send first thing tomorrow, Toronto Ontario Time.... I have to leave for work now :(.   but for the record I am using a Hinks Pix Pro with a standalone SD card.  I am outputting the controller settings from xlights with the upload input and upload output buttons.  Also the graphics don't work regardless of playing off sd card or computer.

Thanks for the help and I'll definitely be donating to xlights this year!

Dave.

**Comment by keithsw1111** [comment]
If you are still stuck i would strongly recommend dropping into zoom. The interactive troubleshooting there would solve this much faster.

**Comment by Lenchuckd** [comment]
ok I will send the controller settings and of course I will try the zoom
option... just a question, how does it work, are there times and days
specifically to join a session or just anytime?

Regards,

Dave.

**Comment by patdelaney** [comment]
Jump in any time of day for US times  after dinner it's fairly active, so
you may have to wait a bit.

**Comment by Lenchuckd** [comment]
here's my hinkspix config screens... can't see where I went wrong but hope you guys can pick out a flaw!  thanks again all!

![hinks3](https://user-images.githubusercontent.com/74312259/99081277-91689280-2590-11eb-9ce2-345d71b175c8.PNG)
![hinks2](https://user-images.githubusercontent.com/74312259/99081278-92012900-2590-11eb-9024-e389d54f23ae.PNG)
![hinks1](https://user-images.githubusercontent.com/74312259/99081280-92012900-2590-11eb-965b-0fea11f5f197.PNG)

**Comment by Lenchuckd** [comment]
update, even when I try and run snowflakes down the tree... the first line goes down, second line goes up etc.... so it's definitely an issue with the folding of the strands... just can't find the answer....

**Comment by AzGilrock** [comment]
Ok so that makes sense.  All effects are messed up so its a mismatch between xlights and the controller setup.  I don't see anything wrong but I also don't see how you would even setup strand folding in that controller.  Are there any pages that define zig-zag?  For a test set the model up in xLights as 16 strings, 50 nodes, 1 strand and see how it runs.  If it looks ok on the real tree then you definitely have a zig-zag defined in that controller.

**Comment by Lenchuckd** [comment]
OK! Well problem solved!  Thank you all for your help, The lighting community is amazing.  I'm not exactly sure what happened but I did a factory reset on my controller, reset all the inputs and outputs through xlights and voila!  It appears to be working!!!

I'll have to view it at night to make sure but it's looking good so far!  The learning curve is steep on this one... This is my first year and I've been working on this and learning from scratch since January so once again... thank you for all the help and cheers to the creators of xlights!  I'm looking forward to bringing cheer to Courtice Ontario Canada this season!
