### ISSUE TITLE
FPP Connect 'checking for mounted media drives' extremely slow

### ISSUE THREAD

**Issue by bshep** [smeighan/xLights#2337]
**Describe the bug**
On OSX when choosing FPP Connect, the step for 'checking mounted media drives' is extremely slow, taking 30-60secs without any mounted drives and several minutes if you mount the SMB shares for FPP, i currently have 4 FPP instances (1 master and 3remote )

**To Reproduce**
1. Click on FPP Connect inside xLights

**Expected behavior**
1. It should either be faster or there should be a setting to disable checking for mounted media drives to speed up the process.

**Screenshots**
Available on request

**Versions (please complete the following information):**
 - OS: Mac 10.15.7 (19H15)
 - xLights version  2020.47.2 ( issue also present on earlier version, but last year it worked better )

**Comment by neowolfwitch** [comment]
I've had this same issue. I was told it was looking through ALL mounted drives, including network shares, for a specific file, I believe. I wish this was configurable somehow.

**Comment by bshep** [comment]
I think the issue is with this line:

https://github.com/smeighan/xLights/blob/0d1740b92aab03743be54d3df1e05b997d3dfdcd/xLights/controllers/FPPConnectDialog.cpp#L944

My Boot drive ( which is usually the only drive mounted ) is called 'Macintosh NVME' and not 'Macintosh HD' so its trying to search through that drive for an FPP instance.

**Comment by patricknew78** [comment]
I'm having this issue as well, except that mine "Beach balls" and forces me to quit the program after a few minutes of waiting.   I've only successfully been able to connect to FPP 2-3 times randomly.   I've tried this on both my Late 2013 and again last night on my new M1 MBP 2020, both with the same issue.   Of note, my hard drive is named "Macintosh HD."
