### ISSUE TITLE
xSchedule Freezing/Lagging Issue

### ISSUE THREAD

**Issue by charbaugh1** [smeighan/xLights#2341]
Sequence freezes/lags on smart differential receiver when playing from xSchedule.  This happens on all sequences (more noticeable on fast moving effects).  This does not happen when outputting directly from xLights when testing; only from xSchedule.

I have included video clips of the behavior, and the sequence used in the video.  One video is when playing from xSchedule and the other is when playing from xLights directly.  I have also included the log file from xSchedule.

Setup Details: 
- xLights v2020.47
- Show computer:  i7, 16GB RAM Windows 10 Pro; GB ethernet
- Gig ethernet switch  
- I have an F4v3 with v2.55 firmware that has 2 differential receivers - 1 standard and 1 smart differential receiver configured in standard mode.  The issue being experienced is only with the smart differential receiver.    
- Show network is stand alone; no connectivity to the house or the internet
- All connections are hardwired; no wifi in use
- Distance from switch to F4v3 = 40 ft
- Distance from F4v3 to smart differential = 60 ft

Troubleshooting steps - 
1.  I have swapped all CAT6 cables for known good ones and bypassed the bulkheads in my controller boxes to eliminate the cabling
2.  Upgraded xLights from .34 to .47.  The problem occurred on both versions
3.  Verified nothing else is running on show computer; reduced startup items in Windows to bare minimum
4.  Verified the turtle is not displaying in xSchedule when freezing occurs
5.  Verified switch settings on receiver
6.  I have set my other controllers Active setting to xLights only in the controller tab.  The F4 is the only one in bridge mode; I have a PiCap and a P5 matrix on Colorlight card running in remote
7.  I have tried changing the FSEQ settings in preferences to all other options (V1, V2 Uncompressed, etc), rendering and saving after each change to see if there was any difference.   No noticeable difference seen
8.  I tried putting the smart differential into smart mode (and reconfigured in the controller string outputs to match), but no difference.
9.  Temporarily removed all but 2 arches to eliminate power injection concerns
10.  Swapped smart differential with a spare I had on hand

I have attempted to eliminate all of the possible hardware issues and have exhausted efforts on the forums and FB groups before posting here.  Let me know if I've missed any piece of info.

[xSchedule_l4cpp.log](https://github.com/smeighan/xLights/files/5537093/xSchedule_l4cpp.log)
[Ghostbusters.zip](https://github.com/smeighan/xLights/files/5537096/Ghostbusters.zip)
[Clips.zip](https://github.com/smeighan/xLights/files/5537150/Clips.zip)

**Comment by keithsw1111** [comment]
So it only lags on the smart receiver ... or everything lags? If xSchedule is going to lag generally everything would lag ... not just some ports. 

Looking through the logs I do see some slow frames ... they are not super frequent but they are there.

The fact you say you get no turtle suggests the problem is not xSchedule itself as it will display whenever a slow flame occurs (as long as you didnt disable UI updates). So that leaves network issues and controller issues.

I note you have pixel stricks ... I assume the network connection to the falcon is fully wired.

I would also check the smart receiver is correctly configured ... ie the termiations are turned on. I also assume you are not daisy chaining them. Of course I dont understand why this would make it work differently to xLights rather than xSchedule.

You may want to pop into zoom and get someone else to run their eyes over it.

**Comment by charbaugh1** [comment]
It is just the smart receiver.  I agree it would seem to be hardware/network related, but I've eliminated all of those items through change outs and testing.  The only thing I haven't swapped out is the network switch, but I highly doubt that is the issue since everything else on the F4 is fine.The Pixel Sticks are no longer part of the show and have been disabled in xLights.  The Falcon is indeed hardwired, and I've swapped the CAT6 with known good.Correct, I am not daisy chaining the receivers.  I have checked the config several times to be sure the switches are set right and match what is configured in the controller.The fact that it operates differently in xSchedule vs xLights is what keeps bringing me back to a software related issue.  If it were hardware or network based, then it should be giving me flaky results on both, right?I will jump on zoom this evening to let someone else look through all the setup and will let you know the results.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Keith Westley <notifications@github.com> Date: 11/14/20  6:47 AM  (GMT-06:00) To: smeighan/xLights <xLights@noreply.github.com> Cc: charbaugh1 <clark_harbaugh@sbcglobal.net>, Author <author@noreply.github.com> Subject: Re: [smeighan/xLights] xSchedule Freezing/Lagging Issue (#2341) 
So it only lags on the smart receiver ... or everything lags? If xSchedule is going to lag generally everything would lag ... not just some ports.
Looking through the logs I do see some slow frames ... they are not super frequent but they are there.
The fact you say you get no turtle suggests the problem is not xSchedule itself as it will display whenever a slow flame occurs (as long as you didnt disable UI updates). So that leaves network issues and controller issues.
I note you have pixel stricks ... I assume the network connection to the falcon is fully wired.
I would also check the smart receiver is correctly configured ... ie the termiations are turned on. I also assume you are not daisy chaining them. Of course I dont understand why this would make it work differently to xLights rather than xSchedule.
You may want to pop into zoom and get someone else to run their eyes over it.

**Comment by charbaugh1** [comment]
Jumped into Zoom this evening.  Admittedly I had a very poor internet connection from my show computer (not normally connected to the house wifi/internet), so I ended up getting dropped before we got too deep.  After I got dropped from Zoom, I continued to try different troubleshooting different things.  On my network setup, I have two small 5 port GB switches connected together.  I had all the controllers on one and my show computer and a wifi router on the other.  The wifi router is always off, unless I'm needing to sync files from OneDrive.  On a whim, I swapped the show computer with one of my controllers on the two switches, putting one controller on the secondary switch and the computer on the switch with the rest of the controllers.  It worked fine.  What doesn't make any sense whatsoever is that I can put my computer on the primary and my Falcon on the secondary switch, and it works fine.  Just not the other way around.  It also doesn't answer why I would get different results from xLights vs xSchedule, but at this point its irrelevant since I've found the right combination that works.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Keith Westley <notifications@github.com> Date: 11/14/20  6:47 AM  (GMT-06:00) To: smeighan/xLights <xLights@noreply.github.com> Cc: charbaugh1 <clark_harbaugh@sbcglobal.net>, Author <author@noreply.github.com> Subject: Re: [smeighan/xLights] xSchedule Freezing/Lagging Issue (#2341) 
So it only lags on the smart receiver ... or everything lags? If xSchedule is going to lag generally everything would lag ... not just some ports.
Looking through the logs I do see some slow frames ... they are not super frequent but they are there.
The fact you say you get no turtle suggests the problem is not xSchedule itself as it will display whenever a slow flame occurs (as long as you didnt disable UI updates). So that leaves network issues and controller issues.
I note you have pixel stricks ... I assume the network connection to the falcon is fully wired.
I would also check the smart receiver is correctly configured ... ie the termiations are turned on. I also assume you are not daisy chaining them. Of course I dont understand why this would make it work differently to xLights rather than xSchedule.
You may want to pop into zoom and get someone else to run their eyes over it.

**Comment by keithsw1111** [comment]
I have no idea why it would be different. The code that xSchedule uses to send out data is the same code as xLights. I am going to put this down to a network issue.
