### ISSUE TITLE
Mac: Unable to lasso-select effects and move them anymore.

### ISSUE THREAD

**Issue by neowolfwitch** [smeighan/xLights#2342]
I'm trying to fix a lot of effect timings after updating the media on a sequence. The only way to select multiple effects on a Mac right now is to command-click on each one, which is a problem when you are dealing with dozens of them at a time, or trying to select a large timespan. This was working fine until version .47.

Lassoing just highlights the effects in blocks, but doesn't actually select them for moving. You can delete them, but that's about it. If you try to cut-and-paste- it will cut them, but not paste them.

The odd thing is it doesn't seem to be every file. Just some, and I don't know why. I'm attaching two sequences. 
"Here Comes Santa Clause" won't let me lasso anything. "Christmas Vacation" will, for the time being. It seems like after I edit and save a few times- the behavior returns.

Side note: Is there a Mac version only GitHub for this? I would rather not clutter up the main xLights bug reports if they shoudl go somewhere else. Thanks! :)

[Mavis Staples 'Christmas Vacation'.xsq.zip](https://github.com/smeighan/xLights/files/5541167/Mavis.Staples.Christmas.Vacation.xsq.zip)

[Here Comes Santa Claus.xsq.zip](https://github.com/smeighan/xLights/files/5541163/Here.Comes.Santa.Claus.xsq.zip)

**Comment by keithsw1111** [comment]
Lasso only works when no timing tracks are selected.

**Comment by neowolfwitch** [comment]
Thank you for clarifying that Keith. Closing.
