### ISSUE TITLE
Import faces from sub-model

### ISSUE THREAD

**Issue by itsfja** [smeighan/xLights#2343]
Two of my most recent coro purchases have poor to disastrous models.

I note that faces can be imported from an existing model. I would wish to import from the current model's sub models. 

Example GE Singing Decorated Tree, the sub models are correct yay!, but the faces are not present, I opened the xmodel in Notepad++ and cut and pasted the sub-model  entries for the face parts. Could this be imported rather than use an editor?

**Comment by computergeek1507** [comment]
Create a new Face and if you right click on the grid and there is an import from submodels option

**Comment by itsfja** [comment]
Thanks. I searched and searched.
