### ISSUE TITLE
Tree Model Alternate Nodes

### ISSUE THREAD

**Issue by kevinsaucier** [smeighan/xLights#2345]
I've searched FaceBook but have come up blank and I don't see a way to search for it here.  It would be great if there were a way to implement a tree model with alternating nodes on each strand.  For instance, the Boscoyo Large Mini Tree requires 10 strands of 18 nodes each.  To go zig zag with standard 4" spacing requires putting a jumper in between each drop or to skip a few holes at the bottom of each (or using a custom string, of course).  Using alternating nodes would allow each drop to be wired down, then back up, and onto the next drop without having to use a custom model.

Thanks for your time!

**Comment by sslupsky** [comment]
@keithsw1111 Thank you for the time on Zoom today to discuss this.  @CamJN  and I successfully prototyped an alternating nodes option for the tree model this evening.  I think a PR that covers the bases you requested will be ready soon.
