### ISSUE TITLE
Brightness Issue

### ISSUE THREAD

**Issue by HonScottHMcCoy** [smeighan/xLights#2346]
xLights v2020.47 (64bit)
Falcon F16V3
Pixels-2-Things

I spent two days on an issue and finally found out what was happening. I don't know if this is a bug or not, but it certainly didn't act as I expected.

I set all models to 30% on a channel and pushed everything to Falcon. The pixel models trigger the Pixels-2-Things. However, the data wasn't tripping Pixel-2-Things.

I figured it was the brightness, so I unchecked the brightness in the models. I thought this would reset them to 100%. I pushed to Falcon. Since the brightness field was unchecked, I'm guessing it just doesn't push any new data for that field to Falcon? At least that's what happened.

Once I set the models manually to 100% and pushed to Falcon, it worked properly.

Is there a setting that makes fields go back to defaults if turned off or cleared?

Scott

**Comment by computergeek1507** [comment]
If the brightness options is uncheck, xLights does not change the value unless you enable "Full xLights Control" If brightness is unchecked xLights assumes you are going to set it manually in the Controller.

**Comment by keithsw1111** [comment]
This is by design.
