### ISSUE TITLE
Gilbert Engineering Wreaths "failed to download model file"

### ISSUE THREAD

**Issue by bhensley86** [smeighan/xLights#2348]
**Describe the bug**
Adding a Gilbert engineering wreath object such as the "MOAW" is followed by a "Failed to download model file". If I go to other manufactures wreaths, props or objects, they load with no problem. 

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to 'Select new download'
2. Draw an object 'square shape'
3. Go down to Gilbert Engineering --> wreaths --> double click on MOAW
4. see error dialog menu popup with red X pic saying "Failed to download model file"

**Expected behavior**
I expect the wreath to load. 

**Versions (please complete the following information):**
 - OS: Windows 10 Pro "20H2" "19042.630"
 - xLights version: 2020.47

**Additional context**
I've tried closing and re-loading xlights, every time I try and download the prop object it says it fails to download.

**Comment by keithsw1111** [comment]
This is not an xLights defect. GE included the model description but no downloadable xmodel file.
