### ISSUE TITLE
OSX shortcut enhancement

### ISSUE THREAD

**Issue by bacarudaguy** [smeighan/xLights#2349]
**Is your feature request related to a problem? Please describe.**
Enhancement request is related to universal OSX keyboard shortcuts

**Describe the solution you'd like**
I would love to see 'Command+W' implemented to 'Close Sequence'... OSX uses this shortcut to close windows, browser tabs, etc... editing the keybindings.xml file gives the option for 'Control+W', but the File menu has 'Command+N' for New Sequence, 'Command+O' for Open Sequence, etc.

**Describe alternatives you've considered**
Editing keybindings.xml, but would have to edit every file for every show folder.. doesn't actually implement an application wide shortcut.

**Additional context**
Editing keybindings file and adding the Close Sequence shortcut doesn't actually work - verified XLights was closed, made the edit, saved, reopened XL, opened a sequence and attempted to close with the new shortcut... 

<img width="742" alt="Screen Shot 2020-11-17 at 8 35 42 AM" src="https://user-images.githubusercontent.com/1183946/99396574-e87fa780-28af-11eb-98be-43a1fd2a558b.png">

**Comment by computergeek1507** [comment]
added with 5422684a2d28b0b17c5c11416f5065b32e80dcbe

**Comment by bacarudaguy** [comment]
Thanks Scott! Look forward to this update on the next release.
