### ISSUE TITLE
Enhancement request - Backup location

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#235]
Can the location of where files be backed up be configurable (similar to the show directory)
That way one could set it to a different location.

Having it as a sub directory of the show directory means that if you or someone else on your computer accidentally deletes the show directory , you also lose any backups there. 

(and I know that good practise would be to daily back it up off the computer ), but .....

**Comment by AzGilrock** [comment]
My vote is to not add another directory to track.  If the Backup we provide doesn't save enough then you can always backup the whole directory with OS utilities that specialize in that.  Like in Windows just right-click your show folder and send to compressed zip file.  Then drag that file wherever you want it.

**Comment by gerry4** [comment]
True, but given where it backs the data up to (and also see other request of what should be backed up) ,  the backup function as it stands is not very useful and could lead to a false sense of security.
I regularly eg every day or more often now with the crashes , backup the entire show directory to USB, and then to an alternate computer or use drop box , but having the backup directory within that directory simply make that outer (ie show) directory larger , so have now stopped using it.
Just my observation .. and I know I am new to xlights ... the effects and ease of use are simply great !

**Comment by AzGilrock** [comment]
Yep if your doing your own backups then you don't need to use ours.

**Comment by stevegiron** [comment]
The original purpose of the backup evolved from corrupted XML files. The backup gave a sense of security that if you deleted your models or overwrote a sequence with an empty file, the installer fumbled something, that you could revert to a saved copy.  The backup in Nutcracker is working as designed.

**Comment by gerry4** [comment]
Thank you,
 
No problem. 
 
Please close if you feel that this is not required.
 
 
regards

Gerard
 
Date: Thu, 28 May 2015 16:17:48 -0700

**Comment by AzGilrock** [comment]
It appears we decided not to do this one.

**Comment by gerry4** [comment]
Okay... 
 
I thought it had been closed already.
 

Gerard
 
Date: Thu, 2 Jul 2015 21:23:47 -0700
