### ISSUE TITLE
DMX Fixtures not mapping colors when in a group

### ISSUE THREAD

**Issue by forkineye** [smeighan/xLights#2350]
**Describe the bug**
When creating a DMX model (DMX Flood in this case) and assigning RGB channels, the channel definitions are not adhered to when the model is placed into a group.  In this instance, R/G/B are channels 2/3/4. The same bars effect was dropped on the model and the group.

**Screenshots**
![125235804_10159150451619703_241209731621316814_n](https://user-images.githubusercontent.com/4047923/99438496-e1718d00-28e1-11eb-87dc-2274514c8383.jpg)

![image](https://user-images.githubusercontent.com/4047923/99439564-55f8fb80-28e3-11eb-9624-89e9fe8ad118.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: 2020.46 and 2020.48

**Comment by AzGilrock** [comment]
For DMX models to work in a group the Default Layout for the group needs to be set to "Single Line" and use a "Per Model Default" render style.  See this video.
https://www.youtube.com/watch?v=9FiuwY65eZg

**Comment by forkineye** [comment]
> For DMX models to work in a group the Default Layout for the group needs to be set to "Single Line" and use a "Per Model Default" render style. See this video.
> https://www.youtube.com/watch?v=9FiuwY65eZg

That solved it, thanks!  Still related to DMX, what is the shutter open threshold?  Is there anyway I can map my brightness channel to always be 255 at the model level, or do I need to use an effect on the channel?

**Comment by AzGilrock** [comment]
The shutter open threshold is really just to teach the GUI when to show the beam.  Some devices have a special shutter channel so the beam is off until the channel goes above a certain value.  There's no way to automatically set a channel to be a certain value at the model level.  Yes you would need an effect to set it or use a feature in the player like I believe in xSchedule you could tell it to always drive a channel to a certain value.

**Comment by AzGilrock** [comment]
In fact pretty much all the model settings are for making the model look "pretty" in the GUI or as close to reality as possible.  Whatever value to drive the channel is what gets sent out.

**Comment by forkineye** [comment]
@AzGilrock Appreciate it, thanks much!

**Comment by forkineye** [comment]
@AzGilrock I can't for the life of me figure out how to get effects like Twinkle to treat the lights individually using the preview and render settings required.  I've tried many others as well, but no joy.  Is this possible with the DMX model? Example of what I do with my old RGB DIY floods that I'm trying to replace - https://youtu.be/Ux_irhMArRs?t=58.

**Comment by AzGilrock** [comment]
You can always create additional models that map to only the RGB channels and group those and treat them like normal lights
