### ISSUE TITLE
Crash when setting transition time

### ISSUE THREAD

**Issue by sslupsky** [smeighan/xLights#2352]
I encountered what looks like a reproducible crash when you enter a time for a transition.  The problem seems to be that if you click on the number box and first type a period to enter a fractional second, xlights crash.  If you prefix the period with "0", the crash does not occur.

I am running xLights v2020.47 on macOS Catalina.

**Comment by dkulp** [comment]
This was fixed in 2020.47.1, make sure you are up to date.  (2020.48 is current)
