### ISSUE TITLE
Candy Cane String single channel, single color intensity support

### ISSUE THREAD

**Issue by TechplexEngineer** [smeighan/xLights#2353]
**Is your feature request related to a problem? Please describe.**
Ideally when sequencing AC props such as a string of Candy Canes where there are 8 candy canes on a single plug [like theese](https://www.homedepot.com/p/Home-Accents-Holiday-10-in-Candy-Cane-Pathway-Lights-Set-of-8-TY166-1118/202534405?MERCH=REC-_-searchViewed-_-NA-_-202534405-_-N&) It would be great if the candy cane model supported configuring all the candy canes to be on the same channel.

Currently if one makes a string of candy canes and sets them to "Single Color Intensity" each candy cane is assigned its own channel.

**Describe the solution you'd like**
Ideally there would be a check box "All candy canes use same channel" or similar.

**Describe alternatives you've considered**
I've reduced my model to a single candy cane.
Another option is to create a bunch of candy canes and set them to the same start channel.

**Comment by keithsw1111** [comment]
I think you have the right answer here: "Another option is to create a bunch of candy canes and set them to the same start channel."
