### ISSUE TITLE
Disable Rendering for entire model

### ISSUE THREAD

**Issue by vult2000** [smeighan/xLights#2354]
Similar to the recent enhancement Keith added to be able to disable rendering for a specific effect, I would like the ability to right click on a model in the sequence and disable rendering there as well.   

My P5 panels are sometimes used in whole house or other group effects, so even though I am not applying effects to them directly on them in the timeline, they are still causing considerable render times because of group effects being applied to them.

**Comment by keithsw1111** [comment]
This was implemented a while back
