### ISSUE TITLE
Version 2020.48 does not have a linux version

### ISSUE THREAD

**Issue by TechplexEngineer** [smeighan/xLights#2359]
**Describe the bug**
It seems the automated build did not run for the 2020.48 release of xlights as there is no appimage release on the releases page: https://github.com/smeighan/xLights/releases

**Comment by keithsw1111** [comment]
This was because the tagged version build failed on Linux

**Comment by TechplexEngineer** [comment]
Bummer. It looks like there have been successful builds since, is the plan to just wait until the next release? Or is there work that needs doing?

**Comment by keithsw1111** [comment]
Unless Chris steps in ... yes.

**Comment by cjd** [comment]
There isn't currently a way to trigger a 'non-release' build so it would need to be marked as a new release (such as 2020.48.1) so in general I just leave it for the next release as they tend to be each week ;)
If there is a specific fix you need before the next release let me know and I can see about tagging a new build (or if you want you can build a local release using https://github.com/cjd/xlights-build-docker/  There is a script in there which will use docker to build the appimage of the current git build

**Comment by TechplexEngineer** [comment]
Thanks for the info, I'll give building xlights a try. Its been on my todo list for a while
