### ISSUE TITLE
Enhancement request - Import effects for LSP (seq) files

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#236]
Similar to the import effects functionality just added in xlights for LOR , HLS , Vixen etc , can the same be extended for LSP files (ie conductor seq files ).
There are a large number of LSP users out there and with the new LSP software not yet in BETA , there may be a number of people who would look to switch over to another sequencer this year.

**Comment by MrChristmas2000** [comment]
Hasn't this been addressed with the new LSP sequence import?

**Comment by gerry4** [comment]
Yes it has - the latest enhancements that enable LSP  MSQ files to be imported by strand are great !

**Comment by stevegiron** [comment]
If this is resolved, please close the issue! Thanks,
