### ISSUE TITLE
Sequence save not recorded

### ISSUE THREAD

**Issue by Cboehm00** [smeighan/xLights#2361]
When I edit a sequence, save it, then either close it or open a different sequence - xLights asks if I want to save or discard changes.  Upon saving a second time via the Save Changes button, I can then perform my action without being warned about saving.  

Using 2020.48

**Comment by keithsw1111** [comment]
This typically happens because something was updated on load. Is this a sequence you have previously opened and saved in .48

**Comment by Cboehm00** [comment]
Yes.  It happens on every sequence.  If I open it and render, then save it doesn't happen.  If I open any sequence, change something, save WITHOUT rendering, then open another sequence, close the sequence, or close the program I am prompted to save again.

**Comment by keithsw1111** [comment]
You may need to be more precise about how you did things as i just tried opening a sequence. making a change. saving it using toolbar or menu. then close sequence on the menu and I didnt get a prompt to save.

**Comment by Cboehm00** [comment]
I'm not sure how much more precise I can be, but I'll try:

I open any sequence, make a change, like just moving an effect, click file/save, then click file/close, or exit, or open sequence I'm prompted to save.
If I open a sequence, make a change, but click Render All, then file/save, then file/close, or exit, or open sequence I'm not prompted to save.

**Comment by keithsw1111** [comment]
Maybe it is your sequence. I have tried this all the ways you describe and i dont see it so maybe it is something in the sequence itself.

**Comment by Cboehm00** [comment]
I don't know what is going on but it happens on all of my sequences on one computer.  I moved my sequences to a different computer and the save prompting issue doesn't happen.  
Please close this issue.
