### ISSUE TITLE
Problem configuring models in DDP controller

### ISSUE THREAD

**Issue by MikeSoukup** [smeighan/xLights#2362]
**Describe the bug**
I'm having trouble configuring some of my models using DDP.  I set the controller up for DDP.  I assigned my 5 models to the controller using chaining - 3 models on the first port, 2 models on the second port.  Both in xLights and when I upload to the FPP I only see 2 of my models.  I've added & removed models from the chains and no matter what I do, I can only get Tree Ball 1 and one of the others to appear on the controller.

Additionally, when I open the visualize window, it's behaving strangely.  When I first opened it I saw Tree Balls 1 & 2 on port 1 and nothing on port 2. Then I clicked on Tree Ball 2 and it changed to Tree Ball 3. Then I clicked on Tree Ball 1 and it swapped places with Tree Ball 3. Then I clicked on Tree Ball 3 and it disappeared and Tree Ball 4 appeared on port 2. Then I went back to my Layout tab and the ports on all the models were not what I set them to before.

**To Reproduce**
I described the steps above.

**Expected behavior**
I expect all 5 of my models to appear on the controller.

**Screenshots**
![controller](https://user-images.githubusercontent.com/10994778/99914123-d0999080-2cc0-11eb-8f2a-889f51b96873.png)
![layout](https://user-images.githubusercontent.com/10994778/99914125-d3948100-2cc0-11eb-92a1-c033eaa98894.png)
![fpp](https://user-images.githubusercontent.com/10994778/99914127-d5f6db00-2cc0-11eb-8761-c9b357974c89.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.48

**Additional context**
I can provide my config files if needed.

**Comment by computergeek1507** [comment]
Need to get your files for more debugging

**Comment by MikeSoukup** [comment]
Here are the config files.

[show export.zip](https://github.com/smeighan/xLights/files/5581010/show.export.zip)

**Comment by computergeek1507** [comment]
Your DDP controller channel size is set to 510. The models you are trying to add are over 510 channels. You need to manually set the channel size larger or enable the auto size option (this is preferred)

![image](https://user-images.githubusercontent.com/2293065/99931515-cf00b480-2d22-11eb-8d4c-84d503daecda.png)

**Comment by MikeSoukup** [comment]
Thanks, that appears to fix things.
