### ISSUE TITLE
Custom model changes to order of lights requires clicking model in sequence before saving to take effect

### ISSUE THREAD

**Issue by ejordan107** [smeighan/xLights#2368]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by ejordan107** [comment]
2020.48 Windows 10
If not clear enough let me know, happens for every sequence not a certain one.  Any custom model just changing around sub-models or faces and clicking save for the model then saving sequence it does this.  I found if I click on the element (model) in the sequence I can watch it change from the old changes to the new changes and then hitting save for the sequence resolves the issue.  I can reproduce each time.

**Comment by computergeek1507** [comment]
If you change a model setting with a sequence loaded, you have to rerender for the sequence data to regenerate it for the new model settings.

**Comment by ejordan107** [comment]
I will check further but seems I still have to open each sequence then click on the element that I made changes to then wait for it to render then save the sequence.  If I just save the sequence with auto render on save it doesn't show the changes.  I'll check further asap more important is adding more shows right now!  Thanks to you and your team for all that you do.




On Wednesday, November 25, 2020, 8:24 PM, Scott H. <notifications@github.com> wrote:




If you change a model setting with a sequence loaded, you have to rerender for the sequence data to regenerate it for the new model settings.

**Comment by keithsw1111** [comment]
This behaviour is by design as Scott says and why we provide batch render ... in these circumstances where you make changes that require re-rendering you kick off batch render and let it do its thing.
