### ISSUE TITLE
Enhancement request: Media file missing, prompt for user input

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#237]
When sharing sequences, odds are the media file will not be found in the original author's location, prompting the media file missing/corrupt message. It would be  nice to have the app then ask if you'd like to locate the file OR say that it found the file in the configured audio folder.

**Comment by AzGilrock** [comment]
Or we could just automatically launch iTunes and purchase the song for you...lol.

**Comment by stevegiron** [comment]
No need to purchase, the files are already there. If you want to polish the app, great. If not, no worries.

**Comment by cjd** [comment]
This is implemented now - if the song is missing then it will prompt to select the media file or convert sequence to animation
