### ISSUE TITLE
Sequence crashes using 4.00.34

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#238]
Hi,
Installed 4.00.34 , Opened the previous sequence I was working on (last updated and saved a hour ago with 4.00.33) 
Clicked on the sequencer tab and it crashed
Repeated and the same thing occurred, so at this stage it would appear that I can't even work on the seq with this release. :(

Debug report and screen print has been attached to my post on the xlights forum  (user Gerry)

**Comment by dkulp** [comment]
WholeHouse models on sequence grid caused a crash.  Fixed.

**Comment by gerry4** [comment]
I am using Windows - so assume that I have to wait for Sean ?

**Comment by dkulp** [comment]
Yep.
