### ISSUE TITLE
Serial Port Channel differentiation in visualize

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#2381]
There are two different ways that the channel on a serial port (DMX, LOR) can be set, either by setting the channel or setting the channel and chaining other models to that.  Currently, there is no way to see which method was used other than to look at the channels or to change something.  If the visualizer could show which method was being used, it could be useful to help see where the channels may not be set as desired, such as if all 16 channels on an AC controller aren't being used.  Thinking something like using different bracket styles... ( ) { } or [ ] for the different types might work.

**Comment by keithsw1111** [comment]
This is a really unusual situation that can only arise if they are not doing auto layout models ... and even then i am not sure it is even possible with current versions. As discussed will close this.
