### ISSUE TITLE
xLights hangs for 1-2 minutes after any model parameter change

### ISSUE THREAD

**Issue by jeffc** [smeighan/xLights#2384]
**Describe the bug**
Whenever I make any change to a model, xLights hangs for anywhere from 45 seconds to 2 minutes before becoming responsive again.

**To Reproduce**
 1. Create an empty directory and extract attached files into it (`xlights_keybindings.xml`, `xlights_networks.xml`, `xlights_rgbeffects.xml`, and `xlights_rgbeffects.xbkp`)
 1. Start xLights and point set the new directory as the show directory
 1. Try to change anything in the models tab (number of nodes in a string, color order, create a group, add/remove to/from a group, etc. Creating a new model is also very slow)
 1. Wait patiently for xLights to respond

[debug.zip](https://github.com/smeighan/xLights/files/5638840/debug.zip)

**Expected behavior**
I would expect xLights to be as responsive as it was when starting in a fresh show directory, or at least close.

**Versions (please complete the following information):**
 - OS: Reproducible on Arch Linux and Windows 10. On Linux, with and without `taskset -c 0` (as suggested in `README.linux`)
 - xLights version 2020.51, also reproducible in a few randomly-chosen-and-downloaded 2020.4x releases

**Additional context**
I thought maybe I just had too many nodes in my layout, so I deleted the four matrices. This didn't make it any better, and was still slow. I haven't been able to pin this down to any specific model when I've tried recreating it from a fresh show dir in different orders. I did a "package logs" dump, attached

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/5638893/xLightsProblem.zip)

**Comment by jeffc** [comment]
Update: I've played with the settings a little more, and it looks like the problem only shows up when I have a few models whose start channel is set using the "Universe Number" option, with a controller and a universe offset. If I update references like `#Teensy:5:1` to `!Teensy:2560` (which should be equivalent; 512*5=2560), I don't see the problem anymore and xLights is snappy again :)

**Comment by keithsw1111** [comment]
Your problem is you have references like #teensy:1:1 ... this causes xlights to go looking up the ip address of the teensy (which if it isnt present will take a while before it times out). if you use # then you want it to be #1:1 or #192.168.0.1:1:1 ... which will both resolve quickly.
