### ISSUE TITLE
Information about where the debug report will be generated is incorrect

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#239]
Hi,
When the application crashes and the user is prompted to 'OK' the debug creation of reports, the screen indicates where the debug zip file will be created. This indication (in my case) is incorrect ie it does not create the debug report there , but instead creates it in the show directory.
I have attached screen prints of what it says in my post pertaining to the crashes .
Now that I know that this is the case , it is not an issue , but I had over 10 crashes at releases 4.00.29 to 4.00.32 that I did not submit , because I simply could not find the debug files and spent much time trying to look to see if these were hidden files or my windows directory (that was indicated) was hidden or had some special properties.
Only saw them when I went to backup the show directory - by which time it was too late to submit.
The same thing could occur for other 'newbee' users.

**Comment by dkulp** [comment]
There isn't a way to specify the path on that dialog. At that point, it's just figuring out what files and such to put in the zip and is using a temporary directory to do it.   That's all within wxWidgets and nothing we can do. 

However, I added a MessageBox after that will popup with the final location of the zip.
