### ISSUE TITLE
FPP Connect - FPP upload screen does not always populate my Pi

### ISSUE THREAD

**Issue by lewislawrence2** [smeighan/xLights#2390]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I am using xlights on a MAC. when running FPP connect, FPP instance does not always populate...

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. first time - Open Application, render all files, select FPP connect, FPP instance shows up as desired, load files to raspberry pi/ FPP (all works as expected)
2. work on a few new songs/ sequences, make some adjustments...
3. second time - render all files, select FPP connect, FPP instance does not show up.

**Expected behavior**
FPP instances should always populate when running FPP connect in the FPP upload menu

**Screenshots**

**Versions (please complete the following information):**
 - OS: Mac 10.15.7 - catalina
 - xLights version 2020.51

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
This should have been fixed in .52.

**Comment by lewislawrence2** [comment]
Awesome! I’ll see if it’s available yet for me on a Mac 

Best,
Lewis
