### ISSUE TITLE
Visualizer Enhancement

### ISSUE THREAD

**Issue by Bugga36** [smeighan/xLights#2393]
Would it be possible to add a "right click option" to the visualizer which allows the user to add a text note which is specific to that  specific prop on that port.  This would be very helpful in keeping track of specialized wiring or power requirements for individual props.  If and when the prop is moved, it would be up to the user to modify the prop's note as required.

**Comment by keithsw1111** [comment]
You can already add a comment on a prop ... not in the visualiser. Happy to add that description into the tooltip popup (where set) but i dont think editing the description in the visualiser adds enough value to further clutter the menus there.

**Comment by Bugga36** [comment]
Adding the information to the visualizer popup would be fantastic.  Thanks.
