### ISSUE TITLE
Twinkle effect seems to be missing Value Curves

### ISSUE THREAD

**Issue by MarkA75160** [smeighan/xLights#2395]
**Is your feature request related to a problem? Please describe.**
In most effects where a numeric value can be entered, there is the option to enter a Value Curve.  In the Twinkle Effect the values for "Number of Lights" and "Twinkle Steps" seem to be missing that option.

**Describe the solution you'd like**
Add the Value Curves option to the Twinkle Effect.  One simple use of this would be to have the Number of Lights slowly decrease over the duration of the effect.

**Describe alternatives you've considered**
no know alternatives exist.

**Additional context**
![image](https://user-images.githubusercontent.com/57245161/101262503-eff2dd80-3704-11eb-8335-a14127c1c7e9.png)
![image](https://user-images.githubusercontent.com/57245161/101262529-27fa2080-3705-11eb-8b0c-e0572c5ab92d.png)

**Comment by keithsw1111** [comment]
This is typically because the algorithm behind the effect does not make it easy (or sensible) to change the value of that setting during the effect. Adding a value curve would require an entirely new algorithm which would "break" current displays and make us exceptionally unpopular.

**Comment by MarkA75160** [comment]
Thanks Keith that makes sense.   No worries.  I first thought maybe it just got overlooked but I understand what you are saying.  Do know have any tips or tricks of another way to simulate Twinkle with a gradually reducing number of lights.  I know I can do a fade out transition but that's a different look than what I'm hoping to achieve (reducing the total points of light versus reducing the brightness)

**Comment by keithsw1111** [comment]
Have you tried sparkles on the color panel ... not the same effect but maybe good enough?

**Comment by Clyde-L** [comment]
> 
> 
> Thanks Keith that makes sense. No worries. I first thought maybe it just got overlooked but I understand what you are saying. Do know have any tips or tricks of another way to simulate Twinkle with a gradually reducing number of lights. I know I can do a fade out transition but that's a different look than what I'm hoping to achieve (reducing the total points of light versus reducing the brightness)

Mark, I address the issue by using multiple effects placed side-by-side, increasing the slider for each effect.  While yes it's is a "manual" way to do this, it will get the job done.  Same issue with the Strobe effect, there are no value curves so I try to use the same angle.  Since this is something I frequently want to do, I've created a preset effect I can quickly lay down.  Then I adjust the effects to match the timing of the song.

**Comment by AzGilrock** [comment]
I'm gonna look at doing this.  I just modified Twinkle with a new algorithm option which is more random and I think it makes it so I can use value curves.

**Comment by AzGilrock** [comment]
Ok I've got the value curves working.  They will look best with the New Render Method option.
