### ISSUE TITLE
Crash when editing model data for GE Spooky Trees

### ISSUE THREAD

**Issue by samjohnson4412** [smeighan/xLights#2396]
When clicking "edit" on the model data for the GE Spooky Tree (Version B - downloaded through Xlights) the software crashes. 

Running V2020.52 on Windows 10.

The check sequence file says the following about the model:
    WARN: Custom model 'L Spooky Tree' missing node 34.
    WARN: Custom model 'L Spooky Tree' missing node 63.
    WARN: Custom model 'L Spooky Tree' missing node 101.

When clicking on the wiring diagram for the model, those nodes are not missing. 

As such, the singing faces on these models do not show correctly in real life.

**Comment by keithsw1111** [comment]
I downloaded the model ... it is missing 34 and 63 and 101.

As for the crash ... I dont think it is ... i just think it i really slow due to a change which i have a fix for.
