### ISSUE TITLE
Crash in submodel dialog

### ISSUE THREAD

**Issue by TechplexEngineer** [smeighan/xLights#2397]
**Describe the bug**
When creating a submodel, after entering a name, if you click in the list of submodels xlights crashes

**To Reproduce**
1. Create window outline
2. open submodel editor
3. click add button
4. type submodel name
5. click in the list of submodels
6. crash occurs

**Expected behavior**
Expected to be able to create another empty submodel

**Versions (please complete the following information):**
 - OS: Linux Mint 20.04
 - xLights version 2020.52 64bit

**Additional context**
I am able to reproduce multiple times
My complete show folder is available in git here: https://github.com/TechplexEngineer/Lightshow/commit/d8140ead02329d9f4d8ad7af33cc827e118b804d

**Attachments**
[xLights_dbgrpt-82842-20201205T212758.zip](https://github.com/smeighan/xLights/files/5648180/xLights_dbgrpt-82842-20201205T212758.zip)
[xLights_dbgrpt-79384-20201205T212451.zip](https://github.com/smeighan/xLights/files/5648182/xLights_dbgrpt-79384-20201205T212451.zip)

**Comment by keithsw1111** [comment]
It doesnt crash on windows but i have added protection on the only reason why i can see it might crash ... so check out .53 when it comes out.
