### ISSUE TITLE
[UPDATED after .56 release]  Enhancement: Display Elements window - sort by model start channel no with groups on top

### ISSUE THREAD

**Issue by mararunr** [smeighan/xLights#2398]
In Display Elements window, add sort option to "sort by model start channel number with groups on top"

Using DDP on all my controllers and so use simple animation sequence to test left, down bars effect on all my models.  Since I'm trying to validate channel number mapping as well as orientation it would be nice to be able to sort in the display elements window by start channel number so the models are listed in channel order (pop groups to the top I guess or wherever since I don't really care about groups when doing this).  Right now, none of the other sort options allow this to be done easily - find myself scrolling up and down the list to find the next model in channel number order.

(I have 564 models across 4 houses so I realize I have more than the normal but this might also help the commercial folks)

Thank you for considering

![Display_Elements window](https://user-images.githubusercontent.com/11252070/101281003-3fcbb600-3792-11eb-8cc4-07ec492df39d.png)
![Layout](https://user-images.githubusercontent.com/11252070/101281009-45290080-3792-11eb-9d65-421fc1b9ba91.JPG)

**Comment by mararunr** [comment]
It's close after .56 but doesn't quite work.  Here is my networks, rgb_effects, and a simple animation seq where all I did was open and sort in display elements.  (Did notice that .56 said controller/port vs controller/channel no.)  Thanks for working on this request.
[xlights_networks.xml.txt](https://github.com/smeighan/xLights/files/5721609/xlights_networks.xml.txt)
[xlights_rgbeffects.xml.txt](https://github.com/smeighan/xLights/files/5721610/xlights_rgbeffects.xml.txt)
[sort by controller channel almost.xsq.txt](https://github.com/smeighan/xLights/files/5721611/sort.by.controller.channel.almost.xsq.txt)

**Comment by keithsw1111** [comment]
It wasnt meant to be close ... it was just a coincidence. The change was made for other reasons. I either didnt see or totally forgot about this request.

**Comment by mararunr** [comment]
@keithsw1111 thank you for the reply.  That makes sense.  I still appreciate it - and all you do Keith.
