### ISSUE TITLE
Xschedule remote falcon disabling

### ISSUE THREAD

**Issue by ebeckereb** [smeighan/xLights#2400]
**Describe the bug**
When xschedule enables and disables remote falcon￼ it is working on decoy since it uses playlist name to validate enable / disable and rf reports a voted sequence as a playlist it disables rf viewer page every time a voted song plays and re-enables it when it goes back to the main playlist. 

**To Reproduce**
Have xschedule play a selected playlist and enable the rf viewer page. When A voted song is chosen it will disable the viewer page. 

**Expected behavior**
Viewer page shouldn't be disabled when a voted song is chosen. As long as we are inside show hours with the Mai selected playlist the viewer page should stay enabled 

**Screenshots**
![image](https://user-images.githubusercontent.com/74929163/101294296-0750ca00-37dc-11eb-998f-d874e4ceedff.jpeg)

![image](https://user-images.githubusercontent.com/74929163/101294310-1afc3080-37dc-11eb-81ea-cb13a31c78c4.jpeg)

**Versions (please complete the following information):**
 2020.52

**Comment by keithsw1111** [comment]
I think i have this fixed.

**Comment by ebeckereb** [comment]
Just installed 2020.53 and having the same issue
