### ISSUE TITLE
xscheduler - Easier Stop and Start

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#2401]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Would it be possible to add a Stop and Play button that would Stop the current Playlist (at the end of its current song) and a Play button that would start a different Playlist regardless of Priority setting...I keep needing to stop my long playlist and start my short playlist when all of a sudden traffic increases....I guess a "Play On Demand" button...lol

**Describe alternatives you've considered**
I've tried using the Priority numbers but with no luck..

**Additional context**
None

**Comment by keithsw1111** [comment]
You can create any buttons you like ... all of those things can be supported by custom configured buttons ... see edit menu/options

**Comment by jimswinder** [comment]
Thanks...will give it a try!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
