### ISSUE TITLE
Feature lost in 2020.53

### ISSUE THREAD

**Issue by Padre653** [smeighan/xLights#2402]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
The ability to hover your mouse over a pixel in sub-model builder in 2020.53 no longer works

**To Reproduce**
1. Go to the layout and select a prop
2. Click on sub-models
3. hover over a pixel in the right window

**Expected behavior**
In version 2020.51 this feature still works, in 2020.53 it no longer does.
If I reinstall 2020.52, it works again.

**Versions (please complete the following information):**
 - OS: Windows 10 Pro OS version 19042.630
 - xLights version 2020.53

**Comment by computergeek1507** [comment]
I fixed this yesterday with c996a545d0f715ed802113d90b5c994005195c80
