### ISSUE TITLE
Circle Model does not export correctly to a Custom Model

### ISSUE THREAD

**Issue by Poporacer** [smeighan/xLights#2404]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
If you have a Circle model with 1 string, 20 layers, 50 nodes per layer, center 15% (common for the GE Grand Illusions) and you export it to a custom model, xLights will skip several nodes in the center ring and will end up with only 924 nodes.
In the wiring view of the Custom model, it shows the pixel from 1-924 but in the Node layout, it shows nodes 1-1000 but several of the pixels 
[CircleExportedModel.zip](https://github.com/smeighan/xLights/files/5656857/CircleExportedModel.zip)

It starts skipping around pixel 700

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Create Circle Model with attributes stated
2. Export to custom Model
3. Import Custom model 

**Expected behavior**
The Custom model should match as close as possible to the Model Exported.

A possible solution would be to add the option of Individual Start Nodes to standard models.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by priemd** [comment]
I believe this is a known issue but why would you want to export an OOB model like this as a custom model?  Just use 'Export xLights Model'.  Speaking in terms of the GE Grand Illusion you mentioned if you use the Vendor Download you are in fact importing the OOB Circle model, not a custom model.

**Comment by computergeek1507** [comment]
@priemd the circle model doesn't support multiple strings like the custom model. The default render style of the circle midel is also different than the default render style of the custom model.

**Comment by priemd** [comment]
@computergeek1507 so create a shadow model, if we're talking GE Grand Illusion then create a Matrix with 1000 pixels >> export as custom model >> import into layout >> set strings and indiv start nodes.  That was the advice given to me by Keith and has worked just fine.  I have 14 shadow models that I just cast off into another preview as they are only there so I can set Indiv Start nodes for the model they are shadowing.  Keith added the 'Shadow Model For' flag after some back and forth discussion regarding this topic.
![image](https://user-images.githubusercontent.com/2279532/104115237-1810c600-52db-11eb-8c61-9eda6d6898d7.png).  I don't sequence much so I can't speak for the render style issue you mention so can't speak regarding that.

**Comment by priemd** [comment]
Individual Start Nodes for every model type would be great, but where to do it right/appropriately?  To me this is a controller connection property for the model vs a model property, but there are also many that still don't use controller connection and use start channel so my opinion is biased per say

**Comment by computergeek1507** [comment]
This should be fixed with https://github.com/smeighan/xLights/commit/02954bcf6f27c7a914b26ab4db82a3ee988ad03f
