### ISSUE TITLE
Provide Group membership(s) somewhere in the model in the layout tab

### ISSUE THREAD

**Issue by tmblue** [smeighan/xLights#2407]
**Is your feature request related to a problem? Please describe.**
I was trying to track down an issue and it felt like I may have put a model in the wrong group. There was no central spot to see where that model may exist, so I had to open up each group.

**Describe the solution you'd like**
I'd think it would be helpful as part of the model data and settings there was a group affiliation row, showing all the groups this model belongs to.

**Describe alternatives you've considered**
None 

**Additional context**

**Comment by computergeek1507** [comment]
Keith added it last night, 
 74aa014d553714ed97defdf881be331612699f47
