### ISSUE TITLE
Create new timing marks from selected effects

### ISSUE THREAD

**Issue by pacmanfourtwenty** [smeighan/xLights#2408]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a might be nice to have

**Describe the solution you'd like**
It would be nice to select a range of effects and be able to create either timing marks to the existing timing track or create a new timing track with new marks based on the effects start and end time

**Describe alternatives you've considered**
simply copying and pasting the effects and then using the drop down to change effect types. 

**Additional context**
 it would be nice to be able to do this so you could lay down different effects on other models based on the effects of a different model that might not line up with the existing timing marks. 
Might be usefully for lets say multiple single strand effects you have laid down to select them all and create new timing and timing marks and be able to lay at VU meter on other models to fire based on the new timing.

**Comment by keithsw1111** [comment]
You can do this already from a row ... not multiple rows. Right click on row heading ... row ... create timing from effects.

**Comment by pacmanfourtwenty** [comment]
Thanks, that worked perfectly
