### ISSUE TITLE
Crashes in 4.00.35

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#241]
(using Windows 7 Enterprise on a 4GB i5 32 bit laptop )

Opened and saved a few times without doing anything. Okay.
Added an effect . Saved . Okay
Added an effect . Saved . Okay
Moved two models up the sequencer view . Saved . okay
Added a new effect (on the vertical group) . Saved . okay
Added a new effect (on the same vertical group) . Changed colours of the effect. Saved . Crash

In between somewhere , I closed the perspective window and the effects window

Added to the forums under bugs and included the debug report there.

----- 
Added another crash report to the same post.
Copied details here -

I opened an existing sequence , and pressed Save 3 or 4 times without doing anything at all, other than shift the same effect a bit.

Stopped when it crashed. Watched the messages . the last one is that the fseq file has been created successfully in nn.nn seconds. Then  a couple of secs later it gracefully crashed.

Most of the time that it crashes , is after a save . Having said that , I am saving it every 5 minutes ie after dropping every 2 -3 effects that I wish to keep.

Not sure if it has any bearing , but I normally close the Perspectives and Effects Windows and move the Model window partially over the sequencer window.

**Comment by gerry4** [comment]
I have added another post with two more debug reports today.
The last one is after I removed the 'empty' Whole House model and cleaned out the model groups that it belonged to (user Gerry).

**Comment by stevegiron** [comment]
We're at 4.01.01 now, are you still having the same exact crashes?

**Comment by gerry4** [comment]
Hi,
 
I only used it briefly (an hour) yesterday as have been travelling , but absolutely no crashes during the hour.
 
I saved a few times and it did not crash.
 
Please close those other issues. Should it occur again , then I will provide details and open a new issue
 
thanks
 

Gerard
 
Date: Wed, 3 Jun 2015 09:17:03 -0700

**Comment by stevegiron** [comment]
Closing per G
