### ISSUE TITLE
Singing face images not loading as expected

### ISSUE THREAD

**Issue by nmiller0113** [smeighan/xLights#2414]
This is a tough one to explain so I'm also [attaching a video](https://drive.google.com/file/d/1JaFMljz5lPwND7enhyPnW2TMuN4yzSFL/view?usp=sharing) to show it. I can reproduce this every time. Essentially, I downloaded someone else's sequence (attached), and when I play it after saving and rendering it's not recognizing the matrix images for the singing faces and just shows on the matrix.

**To Reproduce**
1. Open xLights
2. Change to show folder of the downloaded extracted sequence package
3. Open the sequence
4. Save and render the sequence
5. Hit play and none of the face images on the matrix do anything but show a full red fill
6. Go to the layout tab, select one of the matrix models with a singing face mapped to it in the sequence, select the faces section, click on the path to the image, then cancel out twice (CHANGED NOTHING...SAVED...APPLIED NOTHING)
7. Go back to the sequencer tab and hit play on the sequence or click on the singing face effect on the model you previously checked in the layout tab...AND NOW IT MAGICALLY WORKS! :)

**Expected behavior**
I shouldn't have had to perform the extra step to click in a field for the face images. Especially since I never changed anything, nor did I save or apply anything...I hit cancel every time as you can see in the video.

**Versions (please complete the following information):**
 - Mac 10.15.7
 - xLights version 2020.55

[Logans TreeIntro1.zip](https://github.com/smeighan/xLights/files/5692711/Logans.TreeIntro1.zip)

**Comment by nmiller0113** [comment]
Just bumping this again to see if it has been reviewed at all? I was curious what could be causing it.

**Comment by dkulp** [comment]
Not sure what you are showing, but only the Yellow tree images are actually in the zip you attached.  Thus, there is no way for it to find any of the other face images as they don't exist in the zip.

**Comment by nmiller0113** [comment]
That's interesting as this was built using the package sequence option so it obviously must not think it exists. Yellow is never actually even used in the sequence. If you watch the video you can see that selecting the path makes it start working, which also proves it is there. I'm wondering if it has anything to do with my folder structuring. Rather than using the package sequence option, which is obviously leaving out some files, I'll just attach the original I downloaded from [Sequence Armory](https://sequencearmory.com/)
[Logans TreeIntro1.zip](https://github.com/smeighan/xLights/files/5871928/Logans.TreeIntro1.zip)

**Comment by nmiller0113** [comment]
@dkulp, to add to what I stated above, I'm very confident that if you watch the video you can clearly see that something isn't right. I go all the way to where the correct path is under the faces set up on the model, but I've selected nothing and canceled out of every step I made, and yet it magically starts working.
