### ISSUE TITLE
xScanner

### ISSUE THREAD

**Issue by HonScottHMcCoy** [smeighan/xLights#2415]
Keith,

Excited about your new xScanner! Some of us in the Zoom room this morning were discussing it and wondered if it's possible to add a testing of wifi devices in xScanner for signal strength? We are assisting someone and thinking it's a signal issue between the router and Pi. 

Just a thought. Thank you.

**Comment by keithsw1111** [comment]
Unless I can find an FPP API that shows that I am not sure I can. I dont have WIFI on mine and the doco does not show a sample.

**Comment by ghormann** [comment]
@keithsw1111  It is only in FPP 4.6 and greater, but the rest API is /api/network/wifi_strength 
![image](https://user-images.githubusercontent.com/24968726/103000976-19c84480-44fa-11eb-99a5-7db8f2f6ca75.png)

If is possible (but rare) for an FPP box to have multiple wifi connections.   The field "level" is used for strength. 

The following is used for labeling the strength.
![image](https://user-images.githubusercontent.com/24968726/103001164-71ff4680-44fa-11eb-98c0-f9538fcb740c.png)
