### ISSUE TITLE
Clicking into layout model after changing detail value ignores changes

### ISSUE THREAD

**Issue by adobitar** [smeighan/xLights#2418]
When entering a value in a detail field (# Lights Top in Window Frame details, for example), if you make a change but click into the model (to select a different element, for example), the change you made is reverted instead of being saved.  To change a value, you need to first select a different detail field first (click into # Lights Bottom field, for example) to get the change to save.

As of 2020.55 64bit PC

**Comment by keithsw1111** [comment]
Tab or space also saves the value ... this is a defect in the underlying cross platform library we use and unfortunately there does not seem to be much we can do about it.

**Comment by AzGilrock** [comment]
You can also look at this another way.  If you accidentally change a value its easy to click away and restore it to the original value or you hit enter to latch the new value.  I'd consider it a good feature.
