### ISSUE TITLE
Export house preview fails

### ISSUE THREAD

**Issue by sslupsky** [smeighan/xLights#2419]
This is the exception reported in the log file:

2020-12-16 16:44:30,943 4797709760 log_base [DEBUG] Writing house-preview video to /Users/stevenslupsky/Desktop/River Flows In You.mp4.
2020-12-16 16:44:30,992 4797709760 log_base [ERROR] Exception caught in VideoExporter - 'VideoExporter - Error opening video codec context'
2020-12-16 16:44:31,034 4797709760 log_base [ERROR] DisplayError: Exporting house preview video failed.  

Sorry, there doesn't appear to be any more info than this.

I have attached the sequence below.  Let me know if you need anything else.

[Archive.zip](https://github.com/smeighan/xLights/files/5706104/Archive.zip)

**Comment by keithsw1111** [comment]
This is likely machine specific. Is this Linux per chance? Maybe if you installed something like VLC it would install the necessary codecs.

**Comment by sslupsky** [comment]
Apologies, I should have indicated my hardware.  I am running macOS Catalina on a Mac Pro.  I have xLights on my MBP.  I will try this there and post back.

**Comment by sslupsky** [comment]
Have not had a chance to try this on another computer yet but I did look further into the configuration of my Mac Pro.

From what I can gather, the VideoExporter uses FFmpeg?  Is that correct?  A quick search on this repo suggests to me that the necessary FFmpeg libraries are included with xLights?

I have confirmed that ffmpeg was installed when I set up Audacity (/Library/Application Support/audacity/libs).  Could the Audacity libs be conflicting with the libs that xLights uses in some way?

I also have FCPX installed which has an extensive list of professional video codecs available.  I also have Handbrake installed.  But I do not have VLC installed.  Is VLC a dependency?

@keithsw1111, you mentioned "necessary codecs" ... are those dependencies listed somewhere so I can check for them?

**Comment by sslupsky** [comment]
I installed VLC but that did not resolve the issue.

**Comment by AzGilrock** [comment]
I never use that feature why not just use a screen capture tool?  One of the best free ones out there is actually not well known but it’s called OBS studio.

**Comment by sslupsky** [comment]
@AzGilrock That is a good suggestion, I hadn't thought of doing it that way but it makes perfect sense.  I'll do that.  Thank you.
