### ISSUE TITLE
Hover tips may be incorrect 

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#242]
When on the sequencer or the preview tab , when I place my cursor on any of the labels at the top eg File .... Settings , Imports etc - it says 'Export only Channels associated with one model' 

This is a very trivial issue (if an issue at all) - just thought that you may wish to know.

I only noticed it , because I was doing a hover on the 'Replay Section' button to ask a question  and the cursor went to the wrong button. 

--Windows user

**Comment by AzGilrock** [comment]
I've seen that for a long time.  Just been too lazy to figure out how those tips are even being displayed.

**Comment by stevegiron** [comment]
Gil, see xlightsMain.cpp Line 599

**Comment by stevegiron** [comment]
Gerry, I don't see this with 4.1.8.  You you? If not ok to close!
