### ISSUE TITLE
Models unreadable

### ISSUE THREAD

**Issue by dhooper6430** [smeighan/xLights#2421]
Trying to import a sequence with 2020.56, current OS is WIndows 10. Models labels are unreadable.

Screenshot of how it looks
![xlights_models_unreadable](https://user-images.githubusercontent.com/8426764/102705643-bdc8aa80-42c4-11eb-91f3-fbd89c959809.JPG)
)

**Comment by computergeek1507** [comment]
Go to File->Preferences and under the color manager tab click the reset to default.

**Comment by dhooper6430** [comment]
Thanks .. that has fixed it!
