### ISSUE TITLE
xScanner

### ISSUE THREAD

**Issue by HonScottHMcCoy** [smeighan/xLights#2422]
Keith, I'm trying the xScanner included in today's v2020.56 build.

I'm still getting "Ping FAILED!" on my Pi and Falcon controller. However, it does find them. I can also connect to them just fine.

These are accessed via my wifi network. My PC connects to my wifi and also my network directly with ethernet. The wireless is the 10. network. The wired is 192. network.

Here is a screenshot. Let me know if I can test anything else for you.

Scott McCoy
![image](https://user-images.githubusercontent.com/33946864/102719798-d1204980-42b5-11eb-8608-5cf2c8ac4e24.png)

**Comment by HonScottHMcCoy** [comment]
![image](https://user-images.githubusercontent.com/33946864/102719843-075dc900-42b6-11eb-9378-dd74b3f13b2d.png)

**Comment by keithsw1111** [comment]
Assuming they are not down then the most likely reason is either the ping was lost, the reply was lost or the remote was too slow to respond and it gave up waiting. I am not sure I am that keen to change it.

**Comment by keithsw1111** [comment]
What i can do is mark ping successful if the web request is successful as clearly they can talk.
