### ISSUE TITLE
Unable to import any effects with new version

### ISSUE THREAD

**Issue by chrissystephens** [smeighan/xLights#2424]

**Comment by Terrevue** [comment]
Same issue I am having.  In addition, when clicking the "Layers" button on the Layers Blending window, the application stops responding.

**Comment by computergeek1507** [comment]
Without some additional details, we cannot help very much. When in the import process is this happening, what files are you importing, What OS and platform, and a gif/ video of the issue.

**Comment by Terrevue** [comment]
![Screen Recording 2020-12-21 at 4 28 01 PM](https://user-images.githubusercontent.com/45849973/102828818-3dc94000-43ab-11eb-82f3-bbaa589b1027.gif)
Not really much to it.  Try to import, and it just locks up and I have to kill the app.  I have used import literally dozens of time a day for the last few weeks so it was working great up until the last update.

**Comment by keithsw1111** [comment]
Could it be the dialog is just appearing off the screen? Maybe you used to have a monitor plugged in?

**Comment by dkulp** [comment]
This was fixed in .56.1 which is now in the app store.  Force an update or wait until it auto updates.
