### ISSUE TITLE
Batch Render causes Mac Spinner of Death

### ISSUE THREAD

**Issue by chatcat100** [smeighan/xLights#2425]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

Batch Render causes a Mac Spinning ball of death.

**To Reproduce**

Tools > Batch Render

The option to pick sequences does not even occur. The app stops responding and requires a Fore-Stop

**Expected behavior**
Be given an option to pick sequences

**Screenshots**

**Versions (please complete the following information):**
 - OS: 10.15.7
 - xLights version: 2020.56

**Additional context**
Seems to occured on 2020.56 upgrade

Can't seem to screen shot it.

**Comment by dkulp** [comment]
This was fixed in 2020.56.1, force an update in the App Store App

**Comment by chatcat100** [comment]
Confirmed.
