### ISSUE TITLE
Distinguish groups from single models when importing effects

### ISSUE THREAD

**Issue by Cassock** [smeighan/xLights#2428]
**Describe the solution you'd like**
When importing effects, it would be very nice to know which models are intended to be used as groups versus single models. Highlighting these groups in blue like the left side would be wonderful. Even better would be the ability to drill down into those groups to see which models are within.

**Additional context**
![image](https://user-images.githubusercontent.com/15901832/103091897-94a96200-45c3-11eb-8db9-33099975ac03.png)

**Comment by Cassock** [comment]
Here's an unbelievably bad mockup for mega bonus points showing model type as well:
![image](https://user-images.githubusercontent.com/15901832/103092669-02568d80-45c6-11eb-9556-192845c9ad20.png)

**Comment by Clyde-L** [comment]
I have inquired about this as well, spoken with Scott about it.  As I understand the challenge comes from loading an xsq/xms sequence file.  When you do an import, the sequence file you're importing does not contain information about groups.  The original layout file (xlights_rgbeffects.xml) contains that information, and it's not trasnfered over to the xsq.  So the models in the xsq/xml have no idea what they are, until they are combined with the rgbeffects.xml file.
