### ISSUE TITLE
Linux Import effects does not allow showing/importing on strands and submodels

### ISSUE THREAD

**Issue by fone626** [smeighan/xLights#2429]
When importing a sequence the little triangle that is next to the models that allows you to drill down to the strands, sub models, and nodes isn't there.  There is a space for it, it's just not there and clicking in the space where it should be doesn't do anything.

This was a feature I was going to request, but then watching Keith's most recent video I realized that it was already in there and just not working under Linux.  It would have saved me hours if it had been :(

**Expected behavior**
Be able to show sub models and stands so I can import models onto them.

**Versions:**
 - OS: Linux (Kubuntu 20.04 and KDE Neon 20.04)
 - xLights version 2021.06

**Comment by briggtr** [comment]
OS:  Ubuntu 22.04.05 LTS

I can confirm the same behaviour on xLights versions:
- xLights-2021.40-x86_64.AppImage
- xLights-2021.35-x86_64.AppImage
- xLights-2020.53-x86_64.AppImage

Unable to get to the Channel Mapping in 2022 versions (See issue #3348)

**Comment by fone626** [comment]
Dan just fixed a crash on import for Linux and as a side effect it seems to have also fixed this issue... YAY!!!!  Thanks Dan!
