### ISSUE TITLE
4.00.35 - Butterfly effect on wholehouse model has no effect ?

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#243]
Hello 

I added a butterfly effect to the whole house model which is at the top (see screen picture attached)
It had no effect ie no colour on any channel . Tried after saving as well.
Works if dropped to another model group.
 
![wholehousebutterfly](https://cloud.githubusercontent.com/assets/12591974/7830213/f4286334-048d-11e5-92bc-5a288b909bf4.jpg)

R 4.00.35 . Windows 7 user.

P.S - I apologise in advance if this is not an issue but a user understanding error.

**Comment by dkulp** [comment]
This looks like a problem in your model:
`
<model name="Wholehouse Model" DisplayAs="WholeHouse" StringType="RGB Nodes" parm1="400" parm2="257" WholeHouseData="" MyDisplay="1" offsetXpct="0.0000" offsetYpct="0.0000" PreviewScale="0.3330" PreviewRotation="0" versionNumber="1"/>
`
There isn't any "data" in there so there are no nodes or anything.   Recreate your whole house model OR delete it and create a "WholeHouse" group and use the group.

**Comment by gerry4** [comment]
Thank you.
I had generated it using the build whole house model function from preview.

Will recreate as a group

Date: Wed, 27 May 2015 06:41:55 -0700
