### ISSUE TITLE
Needs Clarity: "Model Blending Default Off"

### ISSUE THREAD

**Issue by jnovack** [smeighan/xLights#2430]
Under Preferences -> Sequences -> "Model Blending Default Off"

This sentence does not confirm to typical documentation standards and needs clarification.

Does it mean that Model Blending will be Default Off for imports? So clicking the box meaning that the default will be off?   This is counter intuitive. Is it only for importing? Or sequence creation?

Or is it asking me if I WANT model blending, and it's telling me the default is off (in which case, "Model Blending (Default Off)" is probably more appropriate.

**Expected behavior**
Dropdown box with the Default Model Blending with options On or Off.

**Screenshots**
![image](https://user-images.githubusercontent.com/387006/103155017-ec81cd80-4769-11eb-84e8-bafa3c814b82.png)

**Versions (please complete the following information):**
 - OS: All
 - xLights: 2020.56

**Additional context**
We had a question in the Zoom about it and everyone was confused.

**Comment by AzGilrock** [comment]
Its used to indicate whether this checkbox I circled defaults to checked or not for new sequences.  So we refer to that setting as the "Model Blending Default" and it's saying do you want that default to be On or Off when you create new sequences.  You really don't need to change anything it was mainly there to support old behavior.  Most people don't understand model blending.  It's purely how models are blended during render time it has nothing to do with importing sequences.  I'm not even sure I can give an accurate description of model blending right now without looking how we do it again.  I believe its when a model renders over top of a group effect it will blend if the box is checked or it will erase then render if the box is unchecked.  I've found over the years it doesn't matter what we do there will always be a certain number of folks confused but I'll let others decide if they want to change it.

![image](https://user-images.githubusercontent.com/2024669/103156267-48495800-4764-11eb-8298-5f03864e9509.png)

**Comment by kevinsaucier** [comment]
I would agree this is probably a pretty minor issue but simply changing the wording to 'Model Blending Defaults to Off' with the checkbox would probably cover it for the most part.  With Model Blending built into the import window now, you don't really even have to think about it anymore (though it would be ideal if the Model Blending checkbox in the import window was checked by default.  :)

**Comment by AzGilrock** [comment]
Yeah I've never seen that import option I had to lookup what it does.  I found it confusing if you look at the line I underlined does that mean the sequence I'm importing into has it enabled or the sequence I'm pulling the effects from has it enabled?  Truth is we can never make all the text perfect....we've tried...lol.
![image](https://user-images.githubusercontent.com/2024669/103306333-88aa0f80-49ca-11eb-8b8e-9e4dae205edf.png)

You wouldn't believe how many iterations we did on this dialog because people couldn't figure out what the buttons meant.
![image](https://user-images.githubusercontent.com/2024669/103306438-cd35ab00-49ca-11eb-8754-07a0f7636169.png)

**Comment by kevinsaucier** [comment]
Yup, I think Keith added that option a few versions ago, Octoberish, maybe.  Totally understand trying to get the text right.  I've done help files and UI design before.  As you said, you can't please everyone.  What I've found is that it's almost always beneficial to pass it by an end user or two who haven't really used it.  If they ask questions, you're not done.  :)  The Save dialog is perfect.  Verbose is always better, in my book.  Worst case, a ? icon with a tooltip.  

For the underlined above, simply changing to 'Blending between models is ENABLED in the source sequence' may work.  Or just removing that entirely, given that the checkbox is just asking if you want to import or not.  Doesn't really matter what the original is and just keeps us from having to read the sequence creators website to see what they intended.  Realistically, before that checkbox, I rarely checked or made the change anyway, unless a sequence was obviously weird looking.

**Comment by computergeek1507** [comment]
I switched it to a dropdown for you.


![Screen Shot 2020-12-29 at 5 13 37 PM](https://user-images.githubusercontent.com/2293065/103317513-62e82f00-49f9-11eb-8ae5-4f5d853e8380.png)


Changed with eb6a9597edabce634a1d8c9ecbf50b51210520e8

**Comment by jnovack** [comment]
Just for me??? 😍
