### ISSUE TITLE
Some effects (Single Strand/Curtain/etc.) do not respect model orientation in 3D

### ISSUE THREAD

**Issue by kevinsaucier** [smeighan/xLights#2436]
Not sure if this is a bug or an enhancement request, but I'm thinking enhancement.  When some effects are placed on a model group in 3D mode (honestly, I didn't check 2D) and not all models are oriented the same way, the effect doesn't respect the orientation setting of the model.

An example probably makes this easier to see.  I have 12 snowflakes on my roof.  Because I'm an idiot, I preset which way was 'up' (related to how I mount them) on the snowflakes prior to wiring them so, once I wired them in 5 different orientations (sigh....), I had to modify my models in the layout to reflect which way was actually up in reality.  Some have pixel 1 at the top, some to the side, some at the bottom, etc.

When applying whole house effects (bars, shockwaves, etc.), the effects process properly, i.e.:

![image](https://user-images.githubusercontent.com/25715814/103297982-6ebafd80-49c7-11eb-959f-2de5799a0d53.png)

However, when applying a single strand or curtain effect to the 'Flakes' group, the orientation starts at pixel 1 so the result is a bunch of mismatched effects, like below:

![image](https://user-images.githubusercontent.com/25715814/103298720-eb021080-49c8-11eb-9da1-ba6001721af4.png)

![image](https://user-images.githubusercontent.com/25715814/103298729-efc6c480-49c8-11eb-8e08-971e7244bad6.png)

My expectation would be that 'up' is 'up', regardless of the actual wiring, though I understand why it's not.  Not exactly sure the best way to attack the issue, maybe a checkbox on the Render Style to treat up as up?

I'm happy to take a video, get more screenshots, or test additional effects, if it would be helpful.  Thanks team!

**Comment by kevinsaucier** [comment]
Alright, I am 100% certain I tried different render styles before submitting but, when I go back now, it seems that 'Per Model Per Preview' may be addressing this issue.  Perhaps I didn't wait long enough for the rerender before.  I'm going to leave this issue here, just in case it sparks something on your end but, if the render style really is all it takes, please virtually slap me and close it out.  Thanks again for your time!

**Comment by AzGilrock** [comment]
Yep only render styles with "Per Preview" in the name will account for orientation in the layout.

**Comment by AzGilrock** [comment]
I've had the same thing where I wired one star different and I ended up pulling the pixels and fixing it because it comes back to bite you later.  You redo your layout and forget which ones are wired which way and you don't want to be stuck not being able to use default render buffers.

**Comment by kevinsaucier** [comment]
Yup, I may end up pulling them but that equates to something like 1800 pixels and the wiring diagram from GE for those snowflakes looks like a blindfolded monkey made it!  :)  So......we'll see.  

Thanks for the info!

**Comment by computergeek1507** [comment]
There is a rotation right click option in the custom model dialog that will rotation the nodes in the model. The shift nodes right click option will also do this if the wiring pattern is the same.
