### ISSUE TITLE
Alternate Backup Directory does not work

### ISSUE THREAD

**Issue by agent462** [smeighan/xLights#2437]
**Describe the bug**
When trying to use alternative Backup Directory it will always persist to using the Use Show Folder checkbox.

**To Reproduce**
Settings Enabled:
Backup on Launch
Backup Subfolders
Purge Backups Older than 90 days

1. Uncheck Use Show Folder
2. Select Alternative Backup Directory
3. Click OK
4. Click Save on Controller tab
5. Close Xlights
6. Reopen Xlights
7. "Use Show Folder" is enabled and backup is in show folder

(Alt Backup Directory is still filled out and correct but is ignored)

OR

1. Uncheck Use Show Folder
2. Directory text box next to show folder is enabled for editing. Select alt folder.
3. Click OK
4. Click Save on Controller tab
5. Close Xlights
6. Reopen Xlights
7. "Use Show Folder" is enabled and backup is in show folder

**Expected behavior**
Alternative backup folder should be used

**Versions (please complete the following information):**
Windows 10
Xlights 2020.57 (and at least 56)

**Comment by AzGilrock** [comment]
Confirmed.  I don't know how that ever worked looking at the code.  It attempts to read the backup folder from the rgbeffects XML file before it has even read in the settings node that contains that info.
