### ISSUE TITLE
Import Effects to channel blocks doesn't work for even (maybe all) source channels in "Stands and Channels" mode

### ISSUE THREAD

**Issue by arnolddeleon** [smeighan/xLights#2438]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Importing multi channel S5 sequences fails for the "even numbered" source channels

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Create a model and corresponding channel block
2. Create a new sequence
3. Import an LOR S5 sequence with bundles (superstrings)
4. Enable Stands and Channels importing
5. Map channels to channel block

The resulting sequence doesn't propagate the effects to the node for the channels that were sourced from the "even channels", the effect appears at the "higher" (don't know the right term) level but not the node for the broken ones.  For the good channels the effect appears on the nodes after the sequence is rendered.

**Expected behavior**
All channels should be mapped correctly to usable results

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.57

**Additional context**
See https://www.facebook.com/groups/xLights/permalink/3651576021544793/

**Attachments**

LOR Sequence:  https://www.dropbox.com/s/vq7q638clxb5ex3/12%20Days%20of%20Christmas%20-%20Muppets%20-%20Laura.loredit?dl=0

The imported to and models I was testing with are here:  https://1drv.ms/u/s!Aviu8TMuu2YvgYAKRBCnI4VBVhPljA?e=CQ8fnK

Sorry it is OneDrive link.  Dropbox is refusing to sync for me right now. If it needs to be Dropbox I will have to try again at some other time perhaps after I give it a kick in the head.

**Comment by arnolddeleon** [comment]
I showed Keith the bug during a zoom session and he had me left click one of the effects that was rendering and switched it to white and that caused it render down to the node

**Comment by arnolddeleon** [comment]
Unselecting the color from the strand is sufficient to make it render on the node level in case that is helpful.  Interestingly if I unselect the color on the working effects (red and white in my example) they also continue to work.

**Comment by arnolddeleon** [comment]
The same bug appears to happen none strand and channels imports.

**Comment by keithsw1111** [comment]
I am trying to look at this one but I just dont understand what you were mapping ... do you have an xmap file i can use that shows what you mapped.

**Comment by keithsw1111** [comment]
Actually ... I see the problem ... it is because the effects map to the 2nd layer as green when we likely should map them as white for channel block models.

**Comment by arnolddeleon** [comment]
ok, that's good to know.  Does that account for the odd/even behavior as
well?

I'm happy to provide any debugging information.
