### ISSUE TITLE
MacOS App Store version doesnt appear to include xSchedule

### ISSUE THREAD

**Issue by siclarkplugins** [smeighan/xLights#2439]
Apologies if I am missing something obvious, but as a new user to xLights, the xlights.org website directs MacOS to the App STore and the only application I get installed is xLights.  I cant see how to install xSchedule onto my Mac. 

Thanks

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by dkulp** [comment]
xSchedule is no longer available on the Mac.  Adjust plans accordingly.   The strong recommendation is to get a Raspberry Pi and run FPP, although xSchedule for Windows or Linux will run fine in a VMWare image (VMWare player is free) if in a pinch.

**Comment by chanson6680** [comment]
@dkulp I will PAY you to compile Xschedule for macOS. You've got me addicted to your M1 build. I have a very Large build with 6 kulp K32 controllers. I also use distributed audio systems which I need my PC/Mac for. it would be AMAZING if there was still a way to get xschedule for mac running.
