### ISSUE TITLE
Models do not get removed/renamed  from Model groups when deleted/renamed 

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#244]
Hello,

This is an observation based on two other issues that I posted that Dkulp and Gil assisted/advised on.

I believe that if you have a model defined and it is in a model group and you then either rename or delete the model , it does not remove it (or rename it) from/in  the model group (s) that it belongs to . You then end up with messages (eg Lanterns cannot be found--- which I had renamed to Lanterns Group), (eg 'Whole house model'  cannot be found - which I deleted today).

I now know to look in the model groups and delete them from there or remove and add back the correct one if required.

The same may occur if a model group is part of another model group (not sure if that is possible) 

Also - re the problem that I had re the 'Whole House Model' being empty , I generated this from the preview screen - I have today deleted it - and therefore saw the message described above come up as soon as I tried to save.

**Comment by AzGilrock** [comment]
Models that are deleted or renamed do now get updated in all the model groups and views.  Closing.

**Comment by stevegiron** [comment]
This is good news. Will have to update the UG.

**Comment by AzGilrock** [comment]
Well if this is news then maybe you need to double check it for me.  I thought this was fixed several versions ago.

**Comment by stevegiron** [comment]
Confirmed working.

**Comment by bigwavedave42** [comment]
I had this happen to me in 4.3.0.  It took me awhile to discover that it was still listed in the group.  Once I went into the model group and deleted the reference there, the error/warning pop-ups went away.

**Comment by AzGilrock** [comment]
I just confirmed that renaming a model updates it's name in model groups and the views.  Steve also confirmed this functionality works.  There are ways you can get that error message.  Like if you do the change and only save the sequence but forget to save the models/view file then this will happen.  I don't think there is still a problem so if you can prove it is then open a new issue with exact steps to replicate.
