### ISSUE TITLE
xFade universe least count is 1,but i need to set it to zero . x lights can do that it would be very helpfull.

### ISSUE THREAD

**Issue by johermohit** [smeighan/xLights#2440]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by keithsw1111** [comment]
You will need to be more specific ... what exactly are you looking to change?

**Comment by computergeek1507** [comment]
I think Universe id 0 needs to be supported for Artnet on xFade

**Comment by johermohit** [comment]
> 
> 
> I think Universe id 0 needs to be supported for Artnet on xFade

yeah, that's exactly what I want to say, pardon my bad English
