### ISSUE TITLE
layers rendering top down

### ISSUE THREAD

**Issue by robbaldwin12** [smeighan/xLights#2442]
on version 2020.57 

layers are rendering top down.

**Comment by computergeek1507** [comment]
Without your layout, some examples sequences, and screenshots/videos, I don't see how we can help. Was it correct in 2020.56? The code related to render order has not changed in a while.

**Comment by robbaldwin12** [comment]
looking into it... it appears that if there is more than 1 blank layer between effects this happens... ill post screens shortly

**Comment by keithsw1111** [comment]
Check the blend style ... there are blend styles that reverse the order of blending.

**Comment by robbaldwin12** [comment]
thanks keith... yes it was a blend style issue ...
