### ISSUE TITLE
Twinkle effect shows less lights over time.

### ISSUE THREAD

**Issue by kkatee** [smeighan/xLights#2445]
**Describe the bug**
When using the new renderer for the Twinkle effect, the number of active lights rapidly diminishes over the duration of the effect.

**To Reproduce**
Twinkle effect with 30 second duration
number lights 100
twinkle steps 80

**Expected behavior**
number of active lights should remain relatively consistant across the whole duration of the effect.

**Screenshots**
Video attached.

**Versions (please complete the following information):**
Windows 10, xlights 2020.57

![twinkle2](https://user-images.githubusercontent.com/34851555/103863349-cddde800-5114-11eb-904a-852f10fbca0a.JPG)
![twinkle4](https://user-images.githubusercontent.com/34851555/103863345-ccacbb00-5114-11eb-9267-b428e6df25f8.JPG)

https://user-images.githubusercontent.com/34851555/103863242-9a9b5900-5114-11eb-8ffc-f19380a20afb.mp4

[Test.zip](https://github.com/smeighan/xLights/files/5780110/Test.zip)

**Comment by AzGilrock** [comment]
Thanks.  The good news is Clyde already showed me the day last release came out so I fixed it 10 days ago.  Just waiting for a new release.
