### ISSUE TITLE
Fire Effect doesn't work with Single Line model

### ISSUE THREAD

**Issue by robjoyce1921** [smeighan/xLights#245]
When a fire effect is applied to a single line model (like a vertical pixel string on a house), the effect shows as repeating red and yellow dots, instead of one strip of vertical fire starting at yellow and proceeding up to red flame.

**Comment by stevegiron** [comment]
I found a workaround. Make your single line model a 2 line matrix instead. Physically it will be only one strand, and it works.   
![image](https://cloud.githubusercontent.com/assets/10568498/7924145/b1fe4a62-086d-11e5-9d01-17b2354a6612.png)

**Comment by robjoyce1921** [comment]
I tried the work around.   its ok if the only thing I want to do is fire.  Unfortunately, the strings are the verticals on my house and front columns.  Respectfully request this be reopened, even if it is too trivial to work right now.  That way if anyone opens up the fire effect for another purpose, they may put a little time into addressing the issue.
