### ISSUE TITLE
Help installing New Controllers

### ISSUE THREAD

**Issue by Lenchuckd** [smeighan/xLights#2452]
Hi there, I have run a HinksPix Pro 16 output received with an 8 SPI smart long range receiver this past year.  For 2021 I have purchased 2 16 SPI smart receivers (Still in Transit) for 32 more outputs.  

My question is how do I add the new receivers to xlights so I can add my new models to the layout tab and associate them to the new controllers.  Currently I don't have enough open ports on the "visualize" tab and can't figure how to add more.  When I try and add a new controller, it adds a completely new one and looks for another IP address, which isn't the case for the HinksPix Pro as they will all work together.

Any ideas? Or do I have to wait for them to physically arrive and then use the "discover option" in the Controllers tab?

**Comment by nmiller0113** [comment]
This question is best for the forums. Check out the [Do You Need Help](https://nutcracker123.com/forum/index.php?board=35.0) section of the xLights forum and post this there. Folks there will be able to assist. Github reporting is mainly for bugs or feature requests. Be sure to close this out after you've posted there. Thank you!
