### ISSUE TITLE
Export Models.csv incorrectly calculates "Light Count" for Arch model

### ISSUE THREAD

**Issue by ctrobbins** [smeighan/xLights#2454]
I created an arch model with 3 arches with 29 nodes per arch and 3 lights/node (prop uses RGB 30/10 strip). So in total there are 87 nodes/261 channels used and also a total of 261 lights. However when I export the models using Tools - Export Models, the resulting CSV file only shows 87 lights under the "Light Count" column for the model.

I checked with a polyline model that also used the same 30/10 strip and that one did calculate the Light Count correctly, so it seems not all model types have this problem.

**Comment by computergeek1507** [comment]
fixed with fdd84a9b2a466d3aaf8a18a8885a3f6d6bbbaff3
