### ISSUE TITLE
Driveway Arches using Mega Tree Model

### ISSUE THREAD

**Issue by PixelPowerUSA** [smeighan/xLights#2455]
It would be helpful if the Mega tree model could also be used as a horizontal matrix for driveway arches for example. Currently when adjusting the mega tree model for this purpose the pixels go top to bottom. The mega tree model is useful because it curves like driveway arches when moved to a horizontal position.

**Describe the solution you'd like**
Create a selection to use the mega tree model as a horizontal matrix for this purpose or allow curving of a matrix model.

**Comment by AzGilrock** [comment]
Why do you need it to be one model?  The Arches model was made for this.

**Comment by PixelPowerUSA** [comment]
Well I dont know. If I put the driveway arches in a group will it act as a
matrix? I conferred with a few sequencing experts and this was a potential
remedy. Btw welcome back Gil.

Brian Roberson / 772-519-1338

**Comment by dkulp** [comment]
If you set the default render style for the group to Vertical Stack, it should act as a matrix.

**Comment by AzGilrock** [comment]
Well I didn't participate on Facebook for about 8 months but I was here and on the forum the whole time.  Just didn't make code changes most of the year.  Trying to balance all the things I want to work on.  My Facebook future might be in question.  I stayed off so I didn't have to hear all the political and covid talk.  But now I've got several friends all quitting Facebook on Jan 20th so we'll see.  I do like helping people with issues on FB but the group doesn't have that many support topics anymore.

**Comment by PixelPowerUSA** [comment]
Thanks

Brian Roberson / 772-519-1338

**Comment by PixelPowerUSA** [comment]
Well nice hearing from you. Btw I'm Sam Robb on FB.

Brian Roberson / 772-519-1338

**Comment by PixelPowerUSA** [comment]
> If you set the default render style for the group to Vertical Stack, it should act as a matrix.

Vertical stack doesn't work.

**Comment by AzGilrock** [comment]
I setup a quick layout and it appears to work to me.  To verify I added a Matrix that shadows the same channels so I could see what the butterfly really looks like across the archway.
![image](https://user-images.githubusercontent.com/2024669/104535699-eac26180-55d3-11eb-92ec-52dad4589a16.png)

**Comment by AzGilrock** [comment]
By the way you can set Vertical Stack as the default layout for the group then you don't need to change the Layer Settings for each effect

**Comment by computergeek1507** [comment]
The models need to be in the order in the model group.

**Comment by PixelPowerUSA** [comment]
Thanks, got it working.

Brian Roberson / 772-519-1338

**Comment by PixelPowerUSA** [comment]
Thanks
