### ISSUE TITLE
xLights hangs when removing all models from controller

### ISSUE THREAD

**Issue by jstorms** [smeighan/xLights#2457]
Open Xlights Ver 2021.01 64bit on Windows 10
From "Controllers" tab select "FrontYard" controller.
Press "Visualize" button
Right click on back ground and select "remove all models from controllers"
I get a blank dialog saying 'Debug report "xLights"' with no text
After a while Windows gives me the option to close the unresponsive program.[](url)
[storms14Jan2021xlights2021.zip](https://github.com/smeighan/xLights/files/5816934/storms14Jan2021xlights2021.zip)

**Comment by jstorms** [comment]
Did not produce a trace/logfile :(

**Comment by TrekErs** [comment]
I was able to duplicate this crash using the packaged zip file.
