### ISSUE TITLE
'Display Element' up and down arrow not working in 2021.01

### ISSUE THREAD

**Issue by PixelPowerUSA** [smeighan/xLights#2458]
Was playing around with 2021.01. I cant move the order of a model or group up or down individually with the arrows in the 'display elements' window. The sort options work fine but I wanted to move one group below the other for rendering purposes and couldn't do it individually. Thanks, Sam Robb

**Comment by AzGilrock** [comment]
It's working for me and I did make some fixes to both the arrows and drag features for sorting recently so there's a possibility something isn't right but there were bugs I found that should have been fixed.  Anyways if you have a sample sequence package it and give me instructions like tell me a specific model to click on and which way it doesn't move.

**Comment by PixelPowerUSA** [comment]
**I tried attaching the packaged sequence but it says the file is too big.** 

Anyway, I am trying to move the 'All Driveway Arches GRP' below the 'All Lights GRP' using the arrows.  When I highlight and press the down arrow it does not move, but when I press the up arrow it moves down. 
![File too big](https://user-images.githubusercontent.com/49037022/104734094-b5ba2a00-570d-11eb-802c-d28af11ee61e.JPG)

**Comment by AzGilrock** [comment]
A packaged sequence should not be that big.  Are you using the Package Sequence feature under Tools?  And if you are then in your settings make sure its not set to include the audio.  Plus we really don't need a full sequence you could create a new empty sequence that contains just the models and no effects.

**Comment by jnovack** [comment]
Confirmed by members in the Zoom room.

**Comment by computergeek1507** [comment]
Works fine for me. Can you upload your layout?

![elements](https://user-images.githubusercontent.com/2293065/104768975-87077800-573c-11eb-912e-7f093f44e2ce.gif)

**Comment by AzGilrock** [comment]
Yeah doesn't matter if 100 people say yes happening to me also until someone provides a file with instructions I'm not going to work on it.

**Comment by PixelPowerUSA** [comment]
My packaged sequence is 238mb. I'll upload my layout. But really I can just
hit the up arrow to go down. I'm sure itll be fix soon.

Brian Roberson / 772-519-1338

**Comment by PixelPowerUSA** [comment]
Tried to upload the xLights_rgbeffects file and xLights_network file and it gives me an error. I've found a work around so feel free to close my case out. Thanks.
![Not supported](https://user-images.githubusercontent.com/49037022/104780207-6ba56880-574e-11eb-9622-ba8e79e112ed.JPG)

**Comment by PixelPowerUSA** [comment]
> Works fine for me. Can you upload your layout?
> 
> ![elements](https://user-images.githubusercontent.com/2293065/104768975-87077800-573c-11eb-912e-7f093f44e2ce.gif)

That's good but I wouldn't waste anyone's time if it work for me. Cheers

**Comment by PixelPowerUSA** [comment]
I've got a work around. Thanks

**Comment by AzGilrock** [comment]
If I package a blank sequence its 8MB.  You must have a ton of faces images attached to your models.

**Comment by PixelPowerUSA** [comment]
> Yeah doesn't matter if 100 people say yes happening to me also until someone provides a file with instructions I'm not going to work on it.

Nice..... I closed it so you don't have to work on it Gil. Cheers.

**Comment by PixelPowerUSA** [comment]
> If I package a blank sequence its 8MB. You must have a ton of faces images attached to your models.

Nope, Just a large display I guess. 900,000plus channels.

**Comment by AzGilrock** [comment]
I do believe its failing for you I just need to be able to create the failure or I would never know I've fixed it.  The bugs I did fix where there a few years.

**Comment by AzGilrock** [comment]
What about drag and drop?  Does that do the same thing?  You can drag an item up one to do a swap.

**Comment by AzGilrock** [comment]
Also XML files cannot be attached here.  A Package Log Files operation would zip up just the XMLs that define your layout.

**Comment by PixelPowerUSA** [comment]
> What about drag and drop? Does that do the same thing? You can drag an item up one to do a swap.

Drag and drop doesn't work either for me.

**Comment by PixelPowerUSA** [comment]
> Also XML files cannot be attached here. A Package Log Files operation would zip up just the XMLs that define your layout.

I pm'd it to Scott. I tried to pm you but it doesn't allow files.

**Comment by AzGilrock** [comment]
I have a mediafire account I think you can upload to this folder but haven't had anyone try this in a long time:
https://www.mediafire.com/folder/xawxug88g57d3/PixelPower

**Comment by PixelPowerUSA** [comment]
I sent you a pm. If you answer me I can send you the stuff.

Brian Roberson / 772-519-1338

**Comment by PixelPowerUSA** [comment]
Ok I'll give it a shot

Brian Roberson / 772-519-1338

**Comment by AzGilrock** [comment]
Ok I didn't see any emails.  I didn't know Github even had a PM capability.

**Comment by PixelPowerUSA** [comment]
Uploading niw

Brian Roberson / 772-519-1338

**Comment by PixelPowerUSA** [comment]
I pmd you in FB messenger. Anywho I just uploaded the file to your media
fire folder. Did you get it? Lol

Brian Roberson / 772-519-1338

**Comment by computergeek1507** [comment]
[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/5823176/xlights_rgbeffects.zip)

**Comment by PixelPowerUSA** [comment]
> [xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/5823176/xlights_rgbeffects.zip)

I guess this is a quiz. Dude i tried to drag this file and it wont accept it. Its good to know you can do it Scott. I sent the sequence to Gil.

**Comment by PixelPowerUSA** [comment]
[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/5823221/xlights_rgbeffects.zip)

**Comment by AzGilrock** [comment]
Not sure I had the media folder settings right.  It's now setup as a filedrop.
http://www.mediafire.com/filedrop/filedrop_hosted.php?drop=b8b49be6df9e4b8c21e8deae92295be0d90b0321df30bdcecdcd3fc807acda2b

But I did just grab the file Scott attached.  I haven't gotten it to fail yet.  I don't see an "All Driveway Arches" group so I tried using the "Arches Group".  Here's the groups I see.
![image](https://user-images.githubusercontent.com/2024669/104785066-e79bb280-5746-11eb-92b1-92ddce7b4df1.png)

**Comment by AzGilrock** [comment]
LOL...the zip file you posted won't open but Scott's did.

**Comment by PixelPowerUSA** [comment]
Its all arches Driveway GRP.
![Layout](https://user-images.githubusercontent.com/49037022/104785277-225a1680-5758-11eb-84d8-1e1a25cb9da7.JPG)

**Comment by AzGilrock** [comment]
Ok I thought Scott had posted your settings.  I guess it was his.

**Comment by PixelPowerUSA** [comment]
> LOL...the zip file you posted won't open but Scott's did.

Yeh thought he was giving me a hint to change the extension for tranferring

**Comment by AzGilrock** [comment]
Ah...ok I renamed it to xml and it works.  Scott actually zipped his.

**Comment by AzGilrock** [comment]
I'm trying but the buttons seem to work in both directions using your show folder.  Maybe make a video so we can spot if your doing something I'm not.

**Comment by PixelPowerUSA** [comment]
Cool. If you didnt get the packaged sequence I can change the extension and
send it in messenger.

Brian Roberson / 772-519-1338

**Comment by PixelPowerUSA** [comment]
Hmm it must be my PC then cus up goes down and down does nothing. It's not
a big deal if its just me because I can work around it.

Brian Roberson / 772-519-1338

**Comment by PixelPowerUSA** [comment]
I'm just highlighting the grp and clicking the up and down arrow. I'm good.
We can put this to bed.

Brian Roberson / 772-519-1338
