### ISSUE TITLE
Crash upon adding model

### ISSUE THREAD

**Issue by lorenyarbrough** [smeighan/xLights#246]
4.0.35 crashes upon adding a new model. I've saved, closed restarted, uninstalled etc and the same issue: crash upon adding a new model.

**Comment by stevegiron** [comment]
Mac or PC version?

**Comment by stevegiron** [comment]
Changing to Bug-Minor. Workaround is to add a timing track before clicking on the sequencer grid.

**Comment by AzGilrock** [comment]
Is this still a bug?  I think we fixed the crashing when clicking on the grid without a timing track.

**Comment by lorenyarbrough** [comment]
The issue went away with the very next release.

Sent from Yahoo Mail on Android
