### ISSUE TITLE
Select Effects doesn't work in Linux

### ISSUE THREAD

**Issue by fone626** [smeighan/xLights#2460]
Starting with 2020.2 Select Effects doesn't let you do anything at all.  Effect Type isn't being populated with any of the used effects.  When you click the little down arrow (or anywhere else for that matter) next to "Effect Type" nothing happens at all.  You don't get the selection of effects like you used to.  It does act like it's giving you a place that you could type if you click in the box next to "Effect Type:", but nothing appears/happens if you type anything.

 - OS: Linux, spacificalluy, Kubuntu Linux 20.04 and Kubuntu Linux 22.04
 - xLights versions: From 2020.2 to current
 - Versions 2020.1 and prior worked correctly

**Comment by keithsw1111** [comment]
Must be a Linux issue. Seems to work on windows.

**Comment by fone626** [comment]
Can I pay someone to fix this?  This problem has eaten so much of my time having to manually identify and select a bunch of effects within sequences, usually multiple times because I'll miss-click and lose all the selections half way though.

**Comment by fone626** [comment]
This was recently fixed by a workaround from @djulien . The search effect window also has the same problem under Linux.
