### ISSUE TITLE
Sequence saved with bad characters in file, and will not open

### ISSUE THREAD

**Issue by jlange6648** [smeighan/xLights#2465]
**Describe the bug**
I created the attached sequence, and had zero issues with it. When attempting to reopen the file, it would only open a blank sequence with no data in it. Upon further debugging of the xsq file, I found that one of the timing track names got saved with a 0x10 character somehow before the name of the track.

Manually editing this file, and removing that character, it then opened with no issues. I can't say how it got into this state, but xlights should have prevented any strange ASCII escape codes from making their way into the saved XML file, or at least given some sort of error message as to why it didn't open the file

**To Reproduce**
open the attached sequence

**Expected behavior**
Not save bad files

**Screenshots**

**Versions (please complete the following information):**
 - OS: Mac OS 10.15.7
 - xLights version 2021.01

**Attachments**
See attached sequence
[bug.xsq.zip](https://github.com/smeighan/xLights/files/5825215/bug.xsq.zip)

**Comment by keithsw1111** [comment]
There is nothing we can do to fix your file (other than edit it with a text editor). We can however endeavour to prevent such characters being entered.
