### ISSUE TITLE
Upload Input and upload Output for ESP32 Not sure how to handle Props on 2 Ports

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#2468]
**Describe the bug**
There are 2 issues:
When uploading the Output to an ESP32 based Pixel stick with 2 outputs. Group Size is Set to 0, it should be set to 1 by default. I'm not sure what xLights is sending for that field so we will start there, if not then we can get Pixelstick team involved.
![image](https://user-images.githubusercontent.com/8147459/105231104-f4941980-5b2b-11eb-9f7b-11f14330b6d0.png)

2nd issue could be related:
How to configure xLights to handle 4 props, 2 on each output. In the sample sequence I will upload, I have 4 8 node circles, 2 on each port of the ESP32. But when I upload it, I don't see a way to map the channels to the the data goes out the correct port on the pixel stick.

![image](https://user-images.githubusercontent.com/8147459/105231597-bea36500-5b2c-11eb-85e6-022635710c0b.png)
![image](https://user-images.githubusercontent.com/8147459/105231607-c3681900-5b2c-11eb-8888-df45f9323923.png)
![image](https://user-images.githubusercontent.com/8147459/105232073-7d5f8500-5b2d-11eb-82bd-5d5d3571b75c.png)

**To Reproduce**
Use the test project, upload inputs and upload outputs to Pixelstick

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version [2021.01]

**Additional context**

**Attachments**

[sample test.zip](https://github.com/smeighan/xLights/files/5845174/sample.test.zip)

**Comment by MartinMueller2003** [comment]
The group number is a very minor issue and the ESP corrects it on its own. 

The ESP expects the data for each port to be contiguous in the data stream. 150 channels on port 1 and 300 channels on port two == 450 contiguous channels sent to the ESP.

**Comment by patdelaney** [comment]
I'm not sure what this means .. " The ESP expects the data for each port to
be contiguous in the data stream. 150 channels on port 1 and 300 channels
on port two == 450 contiguous channels sent to the ESP."

Let do a skype later and troubleshoot it. I'm on a con call right now.

Pat
