### ISSUE TITLE
Is there lyrics support for other languages?

### ISSUE THREAD

**Issue by mase76** [smeighan/xLights#2469]
Hi!
Is there lyrics support for other languages than English? I added a phonetic user_dictionary for German, but when I break down  the Words, they are not recognized. I see all the words in the user lyric dictionary editor, the words are correct, but the phonemes are not the same as in the dict file.
Here is the dict I added:

[user_dictionary.zip](https://github.com/smeighan/xLights/files/5857527/user_dictionary.zip)

**Comment by mase76** [comment]
There is a continued project Papagayo-NG, which supports different languages. It works withoutr dictionaries. I made a pgo with it and imported it in xLights with good results.
https://github.com/morevnaproject-org/papagayo-ng

**Comment by keithsw1111** [comment]
xLights uses the Carnegie Mellon University open source pronunciation dictionary: https://en.wikipedia.org/wiki/CMU_Pronouncing_Dictionary
If you can source something similar for your language of interest then it could be added.
You may also want to check out https://github.com/cmusphinx/cmudict ... if this version contains words ours is currently missing that you are interested in we may be able to look at updating it.

**Comment by Fuchur-Flensburg** [comment]
I searched for a german dictionary too and found this: 

https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/German/

I think it is the same file, which was mentioned from mase76.

The phoentic codes are not really compatible with the english phoentic codes. But after following Search&Replace (in this order), it is usable in xlights:

AAAH	==>	AH
AAH	==>	AH
AA	==>	AH
AH	==>	AH1
AE	==>	AE1
AO	==>	OW1
AW	==>	AW1
AX	==>	AE1
AY	==>	AY1
CC	==>	SH
CH	==>	SH
EEH	==>	EH
EE	==>	EH
EHH	==>	EH
EH	==>	EH1
ERH	==>	AE1
ER	==>	AE1
EX	==>	AE1
HHH	==>	HH
IIH	==>	IH
IH	==>	IH1
IY	==>	IH1
NSPC	==>	N
OE	==>	ER1
OHH	==>	AO1
OOOH	==>	AO1
OOH	==>	AO1
OH	==>	AO1
OI	==>	OY1
OO	==>	AO1
OY	==>	OY1
PF	==>	F
Q	==>	(Q has to be deleted including the following blanc. Replace "blanc Q" with an empty string)
RR	==>	R
TS	==>	ZH
UE	==>	UW1
UUH	==>	UH
UU	==>	UH
UH	==>	UH1
VV	==>	V
X	==>	SH
YYH	==>	IH1
YY	==>	IH1
Y	==>	IH1

After this, you have to Uppercase the whole file and insert a second blanc direct behind every german word.
You can do this with notepad++ and a search and replace with regular expression: ^(.+?)[ ](.+) and replace with: $1  $2 

BTW: The following method from the documentation from xlights even does NOT work for english words:
https://manual.xlights.org/xlights/chapters/chapter-four-sequencer/singing-faces/adding-word-to-user-dictionary

The resulting phoenetic codes are not usable with xlights. It just results in "etc" "etc" "etc" for every word. You can also see this in the last screenshot in documentation,
