### ISSUE TITLE
Enhancement request - Prompt on exit to click Save

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#247]
If modifications have been done to the sequencer effects ie new effects have been dropped onto the sequencer , or existing ones changed and the user attempts to exit without having Saved the changes, provide the usual 'Exiting without saving will lose changes .. etc ' warning.

Currently , if the above occurs , the changes since the last save are lost.

**Comment by kppankratz** [comment]
Or if you try to open or create a new sequence while another sequence is open that hasn't been saved yet either.

**Comment by AzGilrock** [comment]
Duplicate of #151
