### ISSUE TITLE
Always build against your patched WxWidgets

### ISSUE THREAD

**Issue by mase76** [smeighan/xLights#2470]
Hi!
The application should always be build against your patched version of the WxWidgets library be default. When I have installed another upstream library on my system, Xlights is build against that version, and I will run in all the bugs caused by this wrong library.

**Comment by AzGilrock** [comment]
I'm not following what you want.  So you are doing your own builds and its not getting the right wxWidgets.  You don't even mention what operating system your talking about.  Most people don't build the code they use our installations.  If you build the code yourself your in charge.  Like on my Windows system I have to make sure my build environment is pointing to the correct wxWidgets library as specified in our build readme files.

**Comment by mase76** [comment]
Sorry, I am using Debian Gnu/Linux, which ships wx 3.0.5. I removed the dev packages to get a working build. I saw, there is a check in the Makefile. However this did not work as expected.

**Comment by cjd** [comment]
The check should be checking if 3.1.5 is installed (can't check for certain builds)
Debian buster (and sid) look to only come with 3.0.4 so shouldn't have passed the 'test "`wx-config --version`" != "3.1.5"' section of the makefile.
Do you still have the output from when you tested?

**Comment by mase76** [comment]
I reinstalled the wx dev packages, but now I cannot reproduce the issue any more. I don't know, what went wrong. On the other side, you patched wx for your purposes. So even when I have an upsteam version 3.1.5, I guess, I will not have a 100% correct view. Therefor I thought, you could always build against your patched version. If you don't agree with that, you can close this issue, and I will reopen it, when I can reproduce the version checking issue.
