### ISSUE TITLE
Out transition using Pinwheel - extend the time that actually renders

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#2473]
When using the out transition with the pinwheel type, it appears the transition will only start with sub 2 second times. You can set 4 seconds, but the transition will only calculate and take effect on 2 seconds or less.  The other transition types will render at any time value set.  Please extend the transition time for this type if possible.

Thanks,
Steve Giron

**Comment by keithsw1111** [comment]
Do you have an example?

**Comment by stevegiron** [comment]
Set a 4 second long ON effect and set the out transition to 4 seconds with sliders.  Do it again with Pinwheel as the out type as an example.

Or you can paste this:

CopyFormat1	0	1	2	0	60	PASTE_BY_CELL
On	T_CHOICE_Out_Transition_Type=Pinwheel,T_SLIDER_Out_Transition_Adjust=50,T_TEXTCTRL_Fadeout=4.0	C_BUTTON_Palette1=#FFFFFF,C_BUTTON_Palette2=#FF0000,C_BUTTON_Palette3=#00FF00,C_BUTTON_Palette4=#0000FF,C_BUTTON_Palette5=#FFFF00,C_BUTTON_Palette6=#000000,C_BUTTON_Palette7=#00FFFF,C_BUTTON_Palette8=#FF00FF,C_CHECKBOX_Palette1=1,C_CHECKBOX_Palette2=1,C_CHECKBOX_Palette3=1	99950	103650	2	-1000	60	61	0	100

**Comment by keithsw1111** [comment]
Yeah not sure how Kevin intended this to work.

**Comment by KMojek** [comment]
I'll take a look.

**Comment by KMojek** [comment]
Okay, it is actually a problem when used as either an in or out transition; it just doesn't seem as noticeable with "in". The adjustment setting is not working as I expected... it increases the number of "arms" which is what I intended but also affects how quickly the transition takes to go from start to end.

**Comment by KMojek** [comment]
I pushed up a fix; I'll close this out once that goes out in the .06 release.
