### ISSUE TITLE
Sequencer Protections

### ISSUE THREAD

**Issue by akareaper** [smeighan/xLights#2474]
Would like to see a feature in which those who create and sell sequences have the ability to "hide" the effects and such. This would protect their intellectual property so that others cannot buy a sequence, and just copy and paste someone else's work. I can understand people that sell effects packs, but whole sequences is different. Many have the idea they can copy effects, place them in their sequences, and then sell them.

**Comment by keithsw1111** [comment]
Yeah nah ... closing as this is not going to happen. You can achieve some of this using export model effects but people quite rightly dont like them because they are not as good.
