### ISSUE TITLE
Making a door with starting location on bottom right starts on bottom left

### ISSUE THREAD

**Issue by fone626** [smeighan/xLights#2477]
**Describe the bug**
Making a door with starting location on the bottom right still starts on the bottom left and then jumps to the bottom right

**To Reproduce**
Using the window model, make a door by setting the bottom with 0 lights and whatever you want for the top and sides.  Then set the Starting Location to Bottom Right and the wiring view will be light the attached image.

**Expected behavior**
The wiring will start at the right side without jumping across the threshold of the door.

**Screenshots**
![Door](https://user-images.githubusercontent.com/38029943/105928841-9079c580-6003-11eb-8dab-65bc9ddde0ce.png)

**Versions (please complete the following information):**
 - OS: Kubuntu Linux 20.04
 - xLights version 2021.02

**Comment by keithsw1111** [comment]
I am willing to bet you have it going around the door the wrong way ... in which case this is correct behaviour. I would need to see the model settings to be actually sure.

**Comment by fone626** [comment]
keith, you're absolutely right.  I can't believe I overlooked that and that I wasted you're time.  Sorry.
