### ISSUE TITLE
message boxes not going away

### ISSUE THREAD

**Issue by RichardRennII** [smeighan/xLights#248]
Not sure if this is a bug but when I make a change to a model name like "pixel tree" to "Pixel tree" or when importing data from LOR and Nutcracker can not find something, I get the message can not find pixel tree or what ever model, the message box gets stuck in a infinite loop and I have to restart the computer to get it to go away. I have tried closing out the program with task manager but the message will not close out.

**Comment by stevegiron** [comment]
Is this still happening Richard ?

**Comment by stevegiron** [comment]
Please reopen if this is still happening.
