### ISSUE TITLE
Twinkle render method setting for existing sequences causing a problem

### ISSUE THREAD

**Issue by Balders154** [smeighan/xLights#2482]
**Describe the bug**
there is a render method selection in twinkle that by default seems to be set to "old render method" for EXISTING sequences. This made any twinkle effect in my sequences invisible until I set it to "new render method". The default for new sequences is set to "new render method", it's just affecting existing sequences.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Load an existing sequence
2. Click on any twinkle effect in the timeline
3. No twinkle is shown until the render method in the twinkle setting is set to "new render method"

**Versions (please complete the following information):**
 - OS: Windows 10 
 - xLights version 2021.02

**Additional context**
The twinkle effect is near the beginning of this sequence

[Merry Xmas Everybody shortened.zip](https://github.com/smeighan/xLights/files/5894591/Merry.Xmas.Everybody.shortened.zip)

If you would prefer not to post your sequences publicly please say so and be ready to PM them to one of the developers when asked.

**Comment by AzGilrock** [comment]
Yep I fixed that 6 days ago when it was first reported.  Gotta wait till next release unless you build your own version.

**Comment by Balders154** [comment]
Thanks Gil
