### ISSUE TITLE
Dragging an effect from node leaves "ghost" of the effect

### ISSUE THREAD

**Issue by keukenrol** [smeighan/xLights#2485]
**Describe the bug**
In the sequencer, double click on a group, then strand to reach the individual nodes (pixels). When adding an effect to a single node, for example "ON", the effects get assigned correctly to that node. However, when dragging it to a new time position, sometimes a "ghost" of the original effect remains in place. This can be seen and is also shown on the actual light, but cannot be selected.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Open a new sequence with at least a single group with a few RGB pixels in it.
2.Open the group until you see the individual nodes.
3. Add an effect.
4. Now drag the effect down the line and release. Check if it leaves a "ghost". The "ghost" effect is not selectable, but it does output light on the pixel during that time. Also, when changeing the duration of the effect the same happens.

**Expected behavior**
When dragging the effect, NO ghost should appear.

**Screenshots**
![XlightsnodeBug](https://user-images.githubusercontent.com/56192644/106365601-f2556a80-6336-11eb-9154-50fb1dda41dc.png)

**Versions (please complete the following information):**
 - OS: [Windows 10.0.19041.746]
 - xLights version [2021.03]

**Additional context**
This happens to all sequences, also new. Pixels defined as ws2811.
Bug is already present since version 2020.42 an later (when I started using xLights).

**Attachments**
No crashes, screenshot for explanation of the bug.

I would like not to share the sequence in public.

**Comment by computergeek1507** [comment]
if you do a render all, it will go away. The old rendered data is not being removed because you did not rerender that portion of the timeline.

**Comment by keukenrol** [comment]
> if you do a render all, it will go away. The old rendered data is not being removed because you did not rerender that portion of the timeline.

Okay, but this means during programming and testing, you have to render the whole scene every time to precisely tune the effect. Its a useful tip for the moment, thanks!

**Comment by AzGilrock** [comment]
If we are not attempting to re-render the "from" location of moved effects it seems like a deficiency.  Ideally xLights would always be attempting to keep the rendering accurate and up-to-date in the background and then cancel/restart whenever editing affects an area.

**Comment by keukenrol** [comment]
> If we are not attempting to re-render the "from" location of moved effects it seems like a deficiency. Ideally xLights would always be attempting to keep the rendering accurate and up-to-date in the background and then cancel/restart whenever editing affects an area.

I think it is the case with the higher levels, the groups are rendered fine without the need to click render all. I would suppose indeed the rendering would take place between the previous start point and the new end point, (or reversed, depening on the direction you slide the effect in to).

**Comment by dkulp** [comment]
moving effects on submodels/strands/nodes was not keeping track of the dirty area properly.  Will be fixed in next release.
