### ISSUE TITLE
Effect presets dialog - preview effect images red.

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#2486]
May not be a bug, could be an issue with my setup,

On the effect presets dialog, the new preview effect image doesnt seem to show images used in effects but shows them red.
Has this been tested? If works for others must be my issue.
(Once the effect has been apply'd it shows them fine on the sequencer)

**Comment by computergeek1507** [comment]
Red normally means it cannot find the Image file on disk. When you apply'd it xLights searched for the image and found it. I think, the search method is only done on effect selection in the timeline not rendering. If you you so a package sequence of your files and upload the zip I can look into it.

**Comment by priemd** [comment]
Another thought....the preview for the preset is generated when you add it and never generated again.  Maybe you didn't copy the image into the correct folder when you first added the preset...... so when it first generated the image was not available.  Try deleting the preset gif from Show Folder\presets dir and then open the dialog and click on it to generate the preview.... still red?

**Comment by cathelest** [comment]
I deleted the images and when i clicked on the individual lines in the preset dialog it rerendered the gifs with red,

I have since fixed by applying the preset to a fresh timeline, and then highlighting the effects and updating the preset and is now working, 

Presuming i didnt do something properly, m,any thanks,
