### ISSUE TITLE
Warp Effect in version 2021.3

### ISSUE THREAD

**Issue by Wheaton117** [smeighan/xLights#2491]
Was working on a seqence using version 2020.57.   Updated to 2021.3   Now, when applying a ward effect to another effect, xlights freezes,  Just get the onnoying spinning sircle.   Went back to version 2020.57, and everything works fine.

Can't attach any files, as no error file is ever genereated.  Can't even get a screen shot as everything is frozen,  

I i was either the swirl or the disolve effect I was trying.

**Comment by AzGilrock** [comment]
I'm not familiar with Warp is it a transition or really an effect?  In any case specifying which effect it was applied to could help as well as is the effect on a model group or an individual model?

**Comment by dkulp** [comment]
Additionally, if you can create a simple sequence in 2020.57 that works, but then hangs in 2021.3, that would be awesome.   Possibly create a small screen recording or similar that shows the steps to reproduce.

**Comment by Wheaton117** [comment]
Warp distorts whatever effect is below it.  There are multiple choices,
from water drops, to dissolving in or out.  All attempts were at a prop
level, and just to make sure it wasn't just 1 effect that was the problem,
I experimented on multiple effects, with the same issue. I just created
a.new animated sequence.  put a color wash on my mega tree, put the warp
effect above the color wash, chose the "dissolve option and it froze.
attached is a picture I took from my phone.

**Comment by Cranzy-AU** [comment]
I was going to report the same issue and saw this was already reported.
I have created a video of me showing the problem.
I just made a layout with just 1 tree on it and put the warp effect.
Here is a video [https://youtu.be/Sfia6QmDmUk](url)
