### ISSUE TITLE
xLights Scheduler starts MIDI output before beginning a step

### ISSUE THREAD

**Issue by harshsjani** [smeighan/xLights#2494]
The xLights Scheduler application starts a MIDI output stream before the step actually starts playing when the "Play Selected" button is pressed. This causes any other application using the MIDI stream to begin its media play before xLights Scheduler's steps actually begin playing. The consequence of this is that there's about 0.5 to 1 second of lag between the two media files playing.
Additionally, the MIDI stream is not entirely smooth. It has a couple of jerks here and there over its course.

**To Reproduce**
1. Start xLights Scheduler
2. Configure an output MIDI stream for a step
3. Configure the step to also play some media file (video/audio)
4. In a separate application (we've tried nearly a dozen different applications), use the MIDI source as an input stream
5. Go to xLights Scheduler and hit the "Play Selected" button to play the steps
6. Observe that the external application starts playing its media immediately, but xLights Scheduler takes almost half a second more to play its own media causing a de-sync of about 0.5-1 seconds

**Expected behavior**
When the step is played, both media players/outputs should happen at the same time. In fact, the external player starts playing earlier as the MIDI stream has already started, but the xLights Scheduler step is not even highlighted green until that point. See the attached screenshots and video for more clarification.

**Screenshots**
![image](https://user-images.githubusercontent.com/17380942/106943111-da386f00-66d9-11eb-8548-72e749c6afb6.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.02

**Attachments**

https://user-images.githubusercontent.com/17380942/106943271-153aa280-66da-11eb-8611-1838e7b7c44f.mp4

https://user-images.githubusercontent.com/17380942/106943287-18359300-66da-11eb-932b-44bcb2a4c84b.mp4

**Comment by tanmayswami** [comment]
I need to solve this problem - because my whole show is running with the support of MIDI (MIDI library needs to be changed)

**Comment by keithsw1111** [comment]
Try enabling fast start audio ... it sounds like it is taking a while to open the audio file.

**Comment by tanmayswami** [comment]
Surely, I will try this option.  I will update you today. Would you be able to give a time when i can demonstrate the issue if it fails to work?

**Comment by tanmayswami** [comment]
No change in the result. Tomorrow i will be in zoom call to discuss the issue.

**Comment by keithsw1111** [comment]
You could launch vlc to play your video:

vlc.exe --no-video-title -f "video.mp4" vlc://quit

This will run the video full screen and exit when done. This would likely be the most performant way to run the video.

**Comment by tanmayswami** [comment]
Following I used for the application using Windows Media Player - 

C:\Program Files\Windows Media Player\wmplayer.exe "video.mp4" /play /fullscreen /close

I need one last help from you. I am trying to run the video on the second monitor screen. I tried using 

DisplaySwitch.exe /Switch 1 /Switch 2 but it failed to work as expected. 

Can you help me on this issue?

Again, appreciate your help. Thank you.

**Comment by tanmayswami** [comment]
Hi Keith,

Thank you for your reply. This is very useful. We used windows media player
to run the command and there is a major difference and it works as
expected. I will close the ticket now. Following I used for the application
using Windows Media Player -

C:\Program Files\Windows Media Player\wmplayer.exe "video.mp4" /play
/fullscreen /close

I need one last help from you. I am trying to run the video on the second
monitor screen. I tried using *DisplaySwitch.exe /Switch 1 /Switch 2 *but
it failed to work as expected. Can you help me on this issue?

Again, appreciate your help. Thank you.

regards,
Tanmay S

**Comment by keithsw1111** [comment]
I really dont know ... at this point you are really working with the features of the operating system.
A quick google search says open the program and move it to another monitor without making it full screen. Then try running our wmplayer command line. Beyond that I am not sure.
