### ISSUE TITLE
Wavy Effect Crashing xLights on 2021.3

### ISSUE THREAD

**Issue by barrylights** [smeighan/xLights#2495]
In the attached sequence, every time I added the Match image and then put the Warp effect over top of it. It worked fine until I switched the Warp type to Wavy. Every time, it would lock xLights up. I re-installed version 2021.2 and it worked fine. The attached sequence is from 2021.2 as I did not try and go back to .3. 
[Fight Song 2021.zip](https://github.com/smeighan/xLights/files/5937699/Fight.Song.2021.zip)

**Comment by Cranzy-AU** [comment]
Was reported and solved recently.
[https://github.com/smeighan/xLights/issues/2491](https://github.com/smeighan/xLights/issues/2491)

**Comment by barrylights** [comment]
Thank-you guys. You always respond quickly and I appreciate your dedication to xLights.
