### ISSUE TITLE
Presets Memory Issue

### ISSUE THREAD

**Issue by MCStoff** [smeighan/xLights#2496]
Large preset libraries cannot be previewed sequentially.  The more preset you preview, the more memory xLights uses until the system runs out of resources.  Also, it is impossible to import larger preset libraries.  The system eventually runs out of memory and locks up.  It appears that the memory allocated to display the preset is not being released.  xLights 2021.03

**Comment by priemd** [comment]
I am not able to replicate this in 21.03 or 21.04 where the preview render size was doubled.  I just imported 48 presets in bulk on both 21.03 and 21.04, mem usage started at ~275MB, peaked at 276.5 and dropped back down to 275 when it was done rendering them all.  Certainly not seeing any signs of a mem leak.  Maybe you can provide some more details... system?  platform?  maybe it's a particularly lengthy preset with lots of layers?

**Comment by MCStoff** [comment]
Let me send you the preset file that was causing the issue. Is this the best email to respond to?

I am using Windows 10 Professional and 2021.04. 

Try importing first and then perhaps you will be able to replicate the issue. 

Thanks!

**Comment by priemd** [comment]
Yeah you can reply here.

**Comment by MCStoff** [comment]
Here you go.
A little more background...when importing, the import process "locks up" for lack of a better word.  Task Manager shows all memory being utilized during the import.  I worked around it by editing the presets into the rgbeffects file.
The preview issue arose after I had previewed about 25-30 presets.

MichaelShowstopper Sequences
 

    On Wednesday, February 10, 2021, 8:31:57 PM CST, David Priem <notifications@github.com> wrote:  
 
 

Yeah you can reply here.
