### ISSUE TITLE
Enhancement - Allow Model physical real-world perspective when facing something near head on....

### ISSUE THREAD

**Issue by mararunr** [smeighan/xLights#250]
See photo.  In the physical world, both sets of arches are the same size (6 foot wide, 5 foot high for each arch, 24 feet long total).  The arches on the right of the driveway are at XL model size 10.0.  The arches on the left of the driveway are at XL model size 5.0 (trying to "fit" the arches on the driveway border as shown in the photo).

Is there a way to provide a little more realistic physical perspective when a model is rotated?  The ones on the left don't look anything like real life.

![image](https://cloud.githubusercontent.com/assets/11252070/7926947/cd21d0ee-089e-11e5-971d-f8b00fc7212e.png)

**Comment by stevegiron** [comment]
The app is 2 dimensional. All effects are 2 dimensional even thought the models have 3d shapes to them.  I would create a custom model to get the view I wanted.

**Comment by AzGilrock** [comment]
Yeah the problem is the rotation currently only applies a 2 dimensional rotation which is basically around the Z axis.  We would need to add 2 more rotation fields to allow rotation around X and Y to draw them in any orientation.

**Comment by mararunr** [comment]
Right - on same page with all responded.  Put this as enhancement request in title.  If we don't want to capture those here, I'm good with that.  Where would you like enhancements?  Thanks, mv

**Comment by stevegiron** [comment]
This issue has been tagged as an enhancement request. No further action needed.
