### ISSUE TITLE
DMX Fixture Profile

### ISSUE THREAD

**Issue by RJGivens** [smeighan/xLights#2500]
I need a profile for an ADJ 18P Hex IP in 8 channel mode

https://cdb.s3.amazonaws.com/ItemRelatedFiles/11452/18P%20Hex%20IP%20-%20User%20Manual.pdf

**Comment by AzGilrock** [comment]
You don't really need a profile the user can setup anything they need in a few seconds. Just create a DMX moving head (not sure if you want 2D or 3D) and type in 8 for number of channels.  Then type in 1, 2, 3, and 4 for the red, green, blue, and white channel numbers.  Type in 7 for the shutter channel.  Then define your start channel however you need it in your DMX chain.  Other channel for the device will need to be controller manually with the DMX Effect.

**Comment by RJGivens** [comment]
The fixtures I am using are a 8 channel wash light. 


1-Red
2-Green
3-Blue
4-Amber
5-White 
6-UV
7-Dimmer
8-strobe 


How can I make XLights control these?

**Comment by AzGilrock** [comment]
xLights will only automatically write to the red, green, blue, and white channels by dropping regular color effects.  Like I said only the DMX Effect can be used to control the other channels.  The DMX Effect contains a slider for every channel.  The only other trick you can do is you could setup a single channel model for any channel you like and drop On effects to control that channel.

**Comment by RJGivens** [comment]
Ah - I think I understand how it works now.
