### ISSUE TITLE
Upload inputs / upload outputs information for Pixelsticks V.4x does not appear to log correctly.

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#2502]
**Describe the bug**
upload input and outputs to ESP pixelstick 4.x is not logging correctly in xlights logs. See attached examples

**To Reproduce**
Connect ESP Pixels stick running latest 4.x unify branch
Configure xlights for a sting connected to the pixelstick
Click upload inputs
check the xlights log I don't see the complete json being logged but it you use web socket tool esp returns a complete string.

**Expected behavior**
I would expect to see the full json string logged

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, ]
 - xLights version [e.g. 2021.04

**Additional context**
[xlights_logging.txt](https://github.com/smeighan/xLights/files/5962982/xlights_logging.txt)
]

**Comment by dkulp** [comment]
Has been fixed.  Was a WebSocket bug
