### ISSUE TITLE
Select Effects dialog stays populated once sequence closed and can cause crash if selected.

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#2504]
I doubt this would stop anyone doing anything, and is more just something i noticed, so not really a issue.

**Describe the bug**
The select effects dialog will stay populated after a sequence is closed, and can cause a crash if an effect is selected.

**To Reproduce**
1. Open a sequence with images.
2. On select effects dialog select effects type pictures
3. On select effects dialog select a model that has pictures on it
4. On select effects dialog Effect by time will populate.
5. Close sequence.
6. See if the list stayed populated and click on one.

**Expected behavior**
Clear the list on close.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.04 (Latest)

**Comment by computergeek1507** [comment]
Fixed with 470a6318cce06e9737b02c337c9ea03e18ef0d0b
