### ISSUE TITLE
Sequencing

### ISSUE THREAD

**Issue by jcjahner** [smeighan/xLights#2506]
When I watch the tutorials on inserting text on a character line in the sequence, the tutorial says double click between lines and a little editor box comes up where you enter your text.  They show that you have to go to settings and go to timing D Click mode then click the edit mode.  I have the newest update on my Xlight program.  I have no settings header to show where to set the timing D mode to Edit.  can anyone tell me where I find it or what I have to do to get the edit box displayed. Thank You

**Comment by computergeek1507** [comment]
The settings were moved to a dialog in the File Menu under Preferences

https://manual.xlights.org/xlights/chapters/chapter-five-menus/file#preferences

![image](https://user-images.githubusercontent.com/2293065/107857942-6431b780-6dff-11eb-8d4f-f86283f6fe76.png)

**Comment by jcjahner** [comment]
Thank you
