### ISSUE TITLE
Deprecate PlayListItemFPPEvent.cpp

### ISSUE THREAD

**Issue by ghormann** [smeighan/xLights#2507]
With FPP 5.0, the FPP Events have been converted to Commands and the API currently used by xLights in PlayListItemFPPEvent.cpp removed.   I'm not sure if anybody using this feature in xLights, but it won't work as coded going forward.

**Comment by keithsw1111** [comment]
I have added support for the new command slots.

**Comment by ghormann** [comment]
Thanks @keithsw1111
