### ISSUE TITLE
Xlights crashes when trying to add a Polyphonic Transcription timing

### ISSUE THREAD

**Issue by Joemarthey** [smeighan/xLights#2509]
![Capture](https://user-images.githubusercontent.com/58240978/107885750-fdc59b80-6ec9-11eb-838a-596f1be96548.PNG)

**Comment by computergeek1507** [comment]
In xLights, go to Tools->Package Sequence and upload the zip file it creates. Based on your crashlog, the audio file is causing the issues and without the audio file, we can not debug it.

**Comment by Joemarthey** [comment]
[The Most Wonderful Time Of The Year.zip](https://github.com/smeighan/xLights/files/5978412/The.Most.Wonderful.Time.Of.The.Year.zip)

**Comment by keithsw1111** [comment]
There is nothing we can do about this. This is a bug in the vamp code which does not happen often but in some songs polyphonic transcription crashes.
