### ISSUE TITLE
I think I broke it 

### ISSUE THREAD

**Issue by RichardRennII** [smeighan/xLights#251]
I was testing the limits of 4.1, I created a sequence with 180 models added a bunch of timings and created random effects for each model. It played well and when I hit save NC crashed, when I reopened it I got this error message . and now all is gone I have no models and my perspectives are gone.I have attached a photo of the message. it did create a debug report if some one would like it.

![image](https://cloud.githubusercontent.com/assets/11212370/7939478/40014d5e-0919-11e5-9fbd-ca723ea17098.png)

**Comment by RichardRennII** [comment]
update I was able to restore what was gone and able to get it back to before the crash and the sequence was saved and plays perfect

**Comment by AzGilrock** [comment]
The debug report can be attached to a forum post.  It would make this easier to look at since I'm not going to create 180 models manually. :)

**Comment by RichardRennII** [comment]
I can not seem to get it attached I can email it to some one . I keep getting "Unfortunately, we do not support that file type"  when I try to attache it.

**Comment by AzGilrock** [comment]
That's why I said "The debug report can be attached to a forum post."  The xLights forum...not here.

**Comment by RichardRennII** [comment]
Sorry Gil have been working strange hours

**Comment by AzGilrock** [comment]
Is this still a problem?  I don't remember anything posted on the forum for us to look at.  If so then please point me to the post.

**Comment by RichardRennII** [comment]
Sorry for the delay in response no it is no longer an issue

**Comment by AzGilrock** [comment]
Ok I'll hit the close button for you.
