### ISSUE TITLE
Zip Importing Link with saved mapping.

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#2513]
The new mapping method seems great, can we take it a step further and have a metafile or something in the zip to have the vendor or author name, which can pass into the importing dialog for saving, then on next import from same vendor it will check for saved mapping and allow auto mapping,

**Comment by priemd** [comment]
You can already create a 'master mapping' for any layout you map from frequently, just create a simple sequence using the layout you map from frequently and add an On effect to the props/groups which are frequently used then back in your layout create the master mapping file which you can load for every real sequence you map from.  I hear you but the reality is even those layouts which we import from frequently change.  Then what?  Say I map a brand new sequence on the brand new layout from vendor X.  Then I map an older sequence from vendor X which has half the props/different props/names and/or groups changed/etc....this becomes a bit of a mess trying to track.

**Comment by cathelest** [comment]
True, never contemplated older sequences, 
Will close this, many thanks for the response,
