### ISSUE TITLE
Fails to load on MAC when importing a music file

### ISSUE THREAD

**Issue by JD2410** [smeighan/xLights#2514]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When I try to load a sequence with an audio file in it the application crashes on a mac. The same thing happens when I try to create a new sequence and select an audio file.

**To Reproduce**
Steps to reproduce the behaviour:
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. open Xlights
2. New Sequence
3. Select Music Sequence
4. Select Audio File
5. Crashes and requests error report sent to apple

**Screenshots**

**Versions (please complete the following information):**
 - OS: [Mac 10.11.6]
 - xLights version [e.g. 2021.05]

**Comment by priemd** [comment]
10.11 is 5 major versions behind in terms of OS. Upgrade your Mac to at least Catalina which is 10.15, see if your problem still exists.

**Comment by dkulp** [comment]
10.11 is no longer supported.  As of 2021.09, 10.12 is marked as the minimum version in the App Store.
