### ISSUE TITLE
Add support for SSL when using the xSchedule Web interface 

### ISSUE THREAD

**Issue by Shane8johnson** [smeighan/xLights#2517]
**Is your feature request related to a problem? Please describe.**
Ref: [Add support for WSS Websockets #2516](https://github.com/smeighan/xLights/issues/2516)
The modern web is moving more to the HTTPS protocol and displaying warnings for non-secure pages. While most users may not have their xSchedule public facing, those who are taking advantage of the addition of the GuestButton.html (no auth) feature are left with challenges to implement a SSL certificate or use the HTTPS web protocol. 

**Describe the solution you'd like**
Have a section on the xSchedule Options tab (above/below/around "port") to choose between HTTP and HTTPS as well as a button to import an SSL Certificate. If no certificate is imported AND using HTTPS, then a self signed certificate will be issued automatically (causing browser warnings…but still a certificate nonetheless.)

**Describe alternatives you've considered**
The current work around is to use a SSH/VPN tunnel (like portmap.io) running on HTTPS, and point to port running xScheduleWeb using HTTP (picture below) **AND** to convert all WebSockets from WS to WSS. (referenced in the link at the top)
![image](https://user-images.githubusercontent.com/36906111/108603594-75824300-736e-11eb-84dd-555ec47ff02c.png)

**Additional context**

**Comment by BryceDFisher** [comment]
If you're exposing this to the internet, it would probably make a lot of sense to use nginx (https://nginx.org/en/), apache (http://httpd.apache.org/), or similar technology to proxy the requests from the internet into xSchedule.  Ideally, these would be running on dedicated hardware.  Those technologies can do SSL termination, and provide a layered security approach to better protect your home network.
portmap.io is also not a bad solution :)

**Comment by keithsw1111** [comment]
This is not going to be implemented. If you want SSL use FPP.
