### ISSUE TITLE
Models tab under layout shrunk

### ISSUE THREAD

**Issue by ktrbmn** [smeighan/xLights#2518]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
After updating from 2020.41 after New Years to 2021.1the models tabs under the Layout tab shrunk and nothing seems to change it back to what was the normal size. see attached image

![Screenshot (4)](https://user-images.githubusercontent.com/79381322/108608791-02d58f80-738f-11eb-91a7-fcfc9b984ebb.png)

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
please update to 2021.5, I believe this has already been fixed.

**Comment by ktrbmn** [comment]
I just did today from 2021.3 to 2021.5. And still have the same issue with the model tabs being shrunk. 

Robert

**Comment by dkulp** [comment]
I believe this was mentioned as being fixed.
