### ISSUE TITLE
update 2021.05 installed, opened then crashed and now controllers and models gone

### ISSUE THREAD

**Issue by soundmankc** [smeighan/xLights#2521]
I installed the update 2021.05, I then opened Xlights and started editing a sequence. After a few minutes Xlights crashed. When I attempted to reopen Xlights all of my controllers, models and even my house picture are missing. It is now displaying a very old picture and a single set of arches that I did 2 years ago. Please advise what I should do? Win 10 x64 laptop with 12Gb ram and 1TB SSD hard drive.

**Comment by priemd** [comment]
Make sure under the Controllers tab that your show folder is pointing to the correct location.  Sounds like it is pointing to a completely different location.  If it is the correct folder, which I doubt as you said it is displaying a very old picture which makes me think your show folder isn't pointing to wherever you have been making changes then ping back....just don't start deleting folders as there is always a backup snapshot taken every time you open xlights where you can recover from.

**Comment by soundmankc** [comment]
That did it! Thank you so much for your help. Blessings
