### ISSUE TITLE
xLights 2021.5 - Visualize controller makes xlights freeze

### ISSUE THREAD

**Issue by Jaimy-D** [smeighan/xLights#2527]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

When adding additional "props" in a excisting layout, Id like to asssign the props via the visualize button in the controller tab. When clicking visialize (without having connection with the F16v3) the xLights 2021.5 freezes. 

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to '...' Add props, put them in a universe of liking - don't assign a port in the layout tab
2. Click on 'controller Tab - click the controller the new prop should be added on - visualize 
4. See error --> software freezes.

**Expected behavior**
It should open a screen showing the available ports & assigned props & the to be assigned ports

**Screenshots**
Well I could send a greyed out screen, but SW freeze as description would suffice

**Versions (please complete the following information):**
 - OS: [Windows 10
 - xLights version. 2021.5

**Additional context**
It did work in previous versions 2021.4 and 2020.57

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
Can you attach your rgbeffects and networks xml file

**Comment by Jaimy-D** [comment]
Hi Scott,


Sorry for the late reply, since the issue I've upgraded to 2021.19, but all
the in-between versions I've been working with had the same issue. --> And
as I frequently visit the ELF trainings no one else seems to have the issue.
I do have multiple show maps - as I do christmas/halloween/testing all from
a different showmap.

So the error reproduces in all maps so I send you the one that I'm working
the most in.

Best regards

JAimy Deelen

Op zo 20 jun. 2021 om 14:47 schreef Scott H. ***@***.***>:

**Comment by keithsw1111** [comment]
Can you attach the layouts that way anyone can look into it.

**Comment by Jaimy-D** [comment]
Keith,


I'm not really sure what you ask me to send over at this moment,
screenshots of the layout screens (of the maps I have?)

Regards

Jaimy

Op ma 28 jun. 2021 om 10:35 schreef Keith Westley ***@***.***

**Comment by keithsw1111** [comment]
Scott listed the files xlights_rgbeffects.xml and xlights_networks.xml.

Or just go to tools menu ... package logs ... and send us the zip file it creates.

**Comment by Jaimy-D** [comment]
Keith,

Thanks for the reply - will send the package then this evening - not behind
the right laptop at this moment. However the question was asked as I
already sent the requested files as a reply on Scott H. request (maybe by
not using the reply all that wasn;t visible?)

So those 2 files I can send right now actually (hooray for GMAIL)

Thanks,


Jaimy



Op ma 28 jun. 2021 om 21:28 schreef Keith Westley ***@***.***

**Comment by keithsw1111** [comment]
I dont think i ever received these files.

**Comment by Jaimy-D** [comment]
Hi Keith,


Could be me being NOOB to this kind of stuff - but I've added it twice to
the mail - and the first time I thought it was because I did not reply to
all - but as it is the third time asking, is it expected that I sent it by
mail - or do you expect me to add the files to the original "issue" report?

Because "assumption" is the mother of all fuckups - I rather ask :-)

They are added again to this mail as well


Thanks for at least keep asking - makes me at least feel that someone can
tell me in the end what I do terribly wrong. (As I hear on-one else
complaining about it)


Regards
Jaimy

Op di 13 jul. 2021 om 06:23 schreef Keith Westley ***@***.***

**Comment by Jaimy-D** [comment]
[xlights_networks.zip](https://github.com/smeighan/xLights/files/6806991/xlights_networks.zip)

Ok, took some effort - but I zipped them and added them to this thread - YAY

**Comment by keithsw1111** [comment]
So the F16V3 visualiser loads fine. I suspect your issue is that the visualiser is appearing on a screen you cant see. In an ideal world you would go to the view menu ... windows ... reset to defaults ... but in 2021.21 that wont work. It will work in 2021.22.

Your other option is to open the visualiser. Now press alt+space then release the keys and then the m key and release it. Now hit an arrow key and release it and then move the mouse ... it should magically reappear.

**Comment by keithsw1111** [comment]
If there is any other problem causing the hang then your best bet is to upgrade as I am not seeing a hang on the current version.

**Comment by Jaimy-D** [comment]
Keith,

Opening on another screen - would it really be that stupide - I was every
now and then working with an additional monitor - and as said before from
2021.5 onwards it never ever seems to have worked - and looks like xlights
freezes - however I concur that if there is a (invisible) other screen
open, that makes sense in one end.

But as an improvement proposal I would suggest that pop-up screens should
pre-check the "mode/amount" of the screens used before it opens & not open
on the screen I moved it last, because that is the only way this happened I
guess. I opened the visualizer, moved it for convenience to the additional
screen, and then closed it. And when opening it again on a single laptop
screen it is "gone" as it opens outside the actual screen frame?. As I'm
definitely not a SW programmer I have no clue if that is even possible. But
as I can imagine that there will be people using xlights with even lesser
knowledge of it as me?

For now many thanks for the suggestions/tricks - I will try that
immediatly when I arrive home this afternoon - and will close the thread if
that works.


Thanks for the effort!

Jaimy

Op di 13 jul. 2021 om 10:46 schreef Keith Westley ***@***.***

**Comment by keithsw1111** [comment]
We have a function that tries to detect exactly that ... but it is not super reliable and it is difficult to do this well when you are writing code that has to work across a number of different operating systems.

void EnsureWindowHeaderIsOnScreen(wxWindow* win)
{
    int headerHeight = wxSystemSettings::GetMetric(wxSystemMetric::wxSYS_CAPTION_Y, win);
    wxSize size = win->GetSize();
    wxPoint pos = win->GetPosition();

    if (wxDisplay::GetFromPoint(wxPoint(pos.x, pos.y)) < 0 &&
        wxDisplay::GetFromPoint(wxPoint(pos.x, pos.y + headerHeight)) < 0 &&
        wxDisplay::GetFromPoint(wxPoint(pos.x + size.x, pos.y)) < 0 &&
        wxDisplay::GetFromPoint(wxPoint(pos.x + size.x, pos.y + headerHeight)) < 0) {
        
        // window header is not on screen
        win->Move(0, 0);
    }
}

**Comment by Jaimy-D** [comment]
Keith,

Awesome trick - it was indeed not in the same window - who would have
guessed - I sincerely hope that the code for the "sensing" how many screens
there are becomes more stable.
For now this is one on the list of Ï need to remember that one"

Jaimy

Op di 13 jul. 2021 om 10:43 schreef Keith Westley ***@***.***
