### ISSUE TITLE
DeBug report on 4.1.0  

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#253]
When clicking on any tab I get a debug report and NC shuts down

DeBug report here:
https://www.dropbox.com/s/yahu32966n9b8di/xLights_dbgrpt-8164-20150602T153250.zip?dl=0

Video screen capture here:
https://www.dropbox.com/s/mvf9gwmkx5pckzy/XL%204.1%20crash.mp4?dl=0

Thanks,
Clyde

**Comment by stevegiron** [comment]
Clyde,
The app should not crash, that is a given. The workaround is NOT go to the sequencer tab until you have  a sequence open. All menu items are greyed out on the sequencer tab until you've got a sequence open anyhow.

**Comment by dkulp** [comment]
This crash is different.  If you edit the xlights_rgbeffects.xml and change the "matrix"  "parm3" value to something less than or equal to parm2, it will open.    We need to put a guard on that.   

Basically, your matrix is setup as 1 string, 9 lights per string, but 13 strands.   You cannot fold 9 lights into 13 strands which is causing the crash.

**Comment by Clyde-L** [comment]
Steve, it happened when I clicked on ANY tab.  I'm into 4.1 now using a different directory with all my models.  I made that directory and created the model for a video I shot.  It seemed to work fine but then crashed.

**Comment by Clyde-L** [comment]
Sadly it won't let me go into the model to fix the problem.  As soon as I open a sequence, it crashes again.

**Comment by stevegiron** [comment]
If the issue is with your models, then temporarily change the show directory so you get a new xlights_rgbeffects.xml file created. Or backup your existing rgbeffects.xml file and manually edit it per Dan's post.
