### ISSUE TITLE
Loss of shader specific Effect Settings with release of 2021.05

### ISSUE THREAD

**Issue by Old-Salt** [smeighan/xLights#2530]
**Describe the bug**
Loss of shader specific Effect Settings with release of 2021.05

**To Reproduce**
Compare shader Effect Settings for any effect with more than the two standard settings in previous versions to those on 2021.05.

**Expected behavior**
The same Effect Settings as displayed in previous versions should be available in 2021.05 and subsequent releases.

**Screenshots**
![Untitled-1](https://user-images.githubusercontent.com/44735832/109074554-49e4bd00-76ce-11eb-95ce-1c6e103a0e7d.jpg)

**Versions (please complete the following information):**
 - OS: Windows 7
 - xLights version 2021.05

**Additional context**
none

**Attachments**
Screen shot of shader Effect settings from versions 2020.57 through 2021.05. Galaxy.fs was loaded from file for all versions of xLights.  Note that versions 2020.57 through 2021.04 share the same Effect Settings for the shader, and are not repeated.

**Comment by computergeek1507** [comment]
Dan already pushed a fix for this, it will be fixed in the next release
