### ISSUE TITLE
Manual Addendum

### ISSUE THREAD

**Issue by Old-Salt** [smeighan/xLights#2532]
**Is your feature request related to a problem? Please describe.**
No, this is an addition to the manual.  It's available in .doc format as well, if this makes it easier to add to the manual.  This document contains simple instructions for adding shaders not distributed with xLights.  There are also images of all shaders currently distributed with xLights, including those for which xLights currently has no images.  This makes it easier to select a shader.

[Shaders.pdf](https://github.com/smeighan/xLights/files/6043098/Shaders.pdf)

**Comment by AzGilrock** [comment]
Developers don't typically read or write the manual its some group of users that created that effort.

**Comment by computergeek1507** [comment]
I'll work on adding it.

**Comment by Old-Salt** [comment]
There's no other method I know of to share this with the community, so I added it here.

**Comment by AzGilrock** [comment]
The xLights forum and Facebook group both reach much wider audiences.

**Comment by Old-Salt** [comment]
Satisfatory
