### ISSUE TITLE
Crashing after multiple copy then clicking on model grid

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#254]
I copied 3 effects and when clicking on the sequencing grid, NC freezes and closes.

Link to debug report:
https://www.dropbox.com/s/sdx29anj923q6lw/xLights_dbgrpt-7804-20150603T145247.zip?dl=0

**Comment by Clyde-L** [comment]
And now it crashes when I click on the sequence grid

**Comment by Clyde-L** [comment]
And again here is the latest debug report
Link:
https://www.dropbox.com/s/n43gj28c8cr0myo/xLights_dbgrpt-15956-20150603T145906.zip?dl=0

**Comment by AzGilrock** [comment]
Is this reproducible?  The dropbox links aren't valid for me to see the crash reports.

**Comment by stevegiron** [comment]
Is this still occurring with 4.1.7?

**Comment by AzGilrock** [comment]
Don't believe this to be an issue anymore.  You can re-open or create new ticket if it happens again.
