### ISSUE TITLE
Boscoyo xModel Problem

### ISSUE THREAD

**Issue by MacDaddyEug** [smeighan/xLights#2546]
![IMG_9868](https://user-images.githubusercontent.com/79928910/109680036-f7bdf480-7b30-11eb-9177-53e8598a549b.JPG)
![IMG_9869](https://user-images.githubusercontent.com/79928910/109680049-f8ef2180-7b30-11eb-8f00-f6759cf440bb.JPG)
![IMG_9870](https://user-images.githubusercontent.com/79928910/109680051-f987b800-7b30-11eb-8715-ddb1be9d47f9.JPG)
![IMG_9871](https://user-images.githubusercontent.com/79928910/109680057-fab8e500-7b30-11eb-8d4e-b99fb092b064.JPG)
I have a problem inputting props.  The Boscoyo download shows the proper prop but the prop on the screen is WAY different and NOT correct.  The pixel count is only 291 and the model is supposed to have 515.  Is this a Boscoyo problem? or xLights?

**Comment by computergeek1507** [comment]
Contact Boscoyo or ask if anyone in the Facebook group has the model. Models are controlled by the vender. xLights just pulls the data from the venders website.
