### ISSUE TITLE
[Xlights 2021.3] Crashed while zooming

### ISSUE THREAD

**Issue by jstorms** [smeighan/xLights#2549]
Xlights 2021.3 crashed when I was in the sequencer and zooming in. Previously I had added multiple layers to existing model, and was cutting/pasting models.
[xLights_dbgrpt-10748-20210306T094426.zip](https://github.com/smeighan/xLights/files/6095620/xLights_dbgrpt-10748-20210306T094426.zip)

**Comment by keithsw1111** [comment]
This bug was fixed a while back.
