### ISSUE TITLE
[2021.05-07]

### ISSUE THREAD

**Issue by wersvdru** [smeighan/xLights#2550]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
xLights crashes when changing show folder. Whenever I have 'backup on launch' selected in preferences and I change my show folder to my 3D show folder (temporarily) xlights crashes. I turn off "backup on launch" everything is fine.

I have only revisited my 3D layout on version 2021.05 and when I had the crash, I upgraded to 2021.07. The last successful usage of my 3D show folder was on January 16, 2021 and I always update when a new xlights comes out. (if this helps to detect when it happened to start).

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Enable "Backup on Launch" in preferences.
2. Change Show Folder

**Expected behavior**
I would expect not to have a crash.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [Windows 10]
 - xLights version [e.g. 2021.05-07]

**Additional context**
See added log file (xLights_l4cpp_After.log) and check out line # 1855, there you will see two \\ in my directory path and that is where I think the issue is. I don't have a \ in my directory name. This only happens when I have "Backup on Launch" and change show folders.

**Attachments**
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file

https://www.dropbox.com/s/i3cr0m43mh49gs1/xLightsProblem.zip?dl=0

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
Can you try this again in 2021.22 when it comes out. I have added some additional checks.
