### ISSUE TITLE
2021.07 -  Group with no name appearing in display elements in sequence view

### ISSUE THREAD

**Issue by OnlineDynamic** [smeighan/xLights#2554]
**Describe the bug**
On the display elements window on the sequencing view I see a group on the available models/groups with no name
This group does not appear in list of groups in the layout view

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to sequence tab and open display elements
2. Look on left side of screen at available groups
3. See error - a unnamed group

**Expected behavior**
Only display groups which I can see in the layout view

**Screenshots**
Attached

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.07

**Additional context**
Think this started before 2021.07

**Attachments**
zipped sequence

[xlights bug.zip](https://github.com/smeighan/xLights/files/6128541/xlights.bug.zip)

![bug screen shot](https://user-images.githubusercontent.com/68251154/110913026-86d6c380-830c-11eb-9e9f-9dd5b73b4e6e.PNG)

**Comment by tbistr69** [comment]
I too have been seeing this for quite some time, good catch!

**Comment by computergeek1507** [comment]
I added code to prevent adding/renaming groups with blank names but I have no added anything to remove them. I would just manually edit the xlights_rgbeffects.xml as Gil has mentioned.

**Comment by tbistr69** [comment]
> Problem is figuring out how you got into this situation. Inspecting your xlights_rgbeffects.xml file the group with no name is clearly there. You could edit the file with Notepad++ and give it a name. If you can figure out how it happened that should be fixed but I'd rather not see code added that wastes time looking for these things to fix.

Thanks, I was able to go through my rgbeffects file and locate the culprit(s). Not sure how they got there but they are gone now!

**Comment by dkulp** [comment]
Scott added code to prevent this.
