### ISSUE TITLE
Corrupt rgb effects after working with multiple copies of xlights 2021.07

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2556]
Not sure how it happened.. other then upgraded to 2021.07. Worked on a sequence, opened another copy of xlights (at the same time) to view another sequence. Next morning .. upon starting xlights it warns of corrupt rgbeffects and a default one is being created.
Went to backups to restore a prior copy to get around this.

**Comment by computergeek1507** [comment]
can you attach the corrupt rgb effects file so we can look for some clues.

**Comment by derwin12** [comment]
[GOOD.zip](https://github.com/smeighan/xLights/files/6137233/GOOD.zip)
[BAD.zip](https://github.com/smeighan/xLights/files/6137234/BAD.zip)
Including the "corrupt" files in the BAD.zip and the current  GOOD.zip ones that I reverted to to rollback and move forward..

**Comment by derwin12** [comment]
Hasnt happened again...
