### ISSUE TITLE
Windows version of queen mary vamp plugin points to an old version?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2559]
We found last night from zoom that if you downloaded the plugin from the website then you would get a 2020 version of the plugin.
 That updated plugin, for example, when adding Bar and Beat Tracker provides additional tuning parameters like Alpha, Tempo Hint and Constrain Tempo. We find that these extra parameters result in a better representation of the music being analyzed.
I *think* googling xlights we point to some locally hosted .exe version of the plugin?

Workaround is to remove plugin, install from the link below ... dont use the Download from within xlights.

https://code.soundsoftware.ac.uk/projects/qm-vamp-plugins/files
I think it is 1.8.1 vs 1.7.1  ?

**Comment by derwin12** [comment]
https://github.com/smeighan/xLights/blob/07be07752bef0f204051d2b77391da729cfcccd8/xLights/UtilFunctions.cpp#L694

**Comment by keithsw1111** [comment]
It sure does ... last I checked the current version was 1.7.1 and it was dreadfully unstable. I have not looked at 1.8.1

**Comment by keithsw1111** [comment]
Its actually 1.8.0 and it seems to work ok ... and even better I dont need to build it.
