### ISSUE TITLE
xLights Crash When Opening Sequence - 2021.07 + 2021.08

### ISSUE THREAD

**Issue by kevinsaucier** [smeighan/xLights#2566]
Edit:  Doh!  Don't know what year I'm in.  This should have been about the 2021.07 and 2021.08 versions.  🤦‍♂️

Created a new blank sequence using 2021.07 but xLights gave the 'you're about to crash message' just after clicking OK on the new sequence dialog.  It didn't actually close so I saved the blank sequence and then closed xLights.  Reopened xLights and tried to reopen the sequence and it just crashed immediately before ever opening the sequence.  I updated to 2021.08 and it does the same.  I deleted the old sequence file and created a new one in 2021.08 and it worked without a problem.

It may have just been an invalid sequence that got created after the partial crash, but I know there have been reports of xLights crashing more often so I figured I'd upload the packages so you could take a look, just in case it helps.  Thanks!

[xLights_dbgrpt-7944-20210322T144325.zip](https://github.com/smeighan/xLights/files/6184651/xLights_dbgrpt-7944-20210322T144325.zip)
[xLights_dbgrpt-11792-20210322T134200.zip](https://github.com/smeighan/xLights/files/6184652/xLights_dbgrpt-11792-20210322T134200.zip)
[xLights_dbgrpt-13432-20210322T143943.zip](https://github.com/smeighan/xLights/files/6184653/xLights_dbgrpt-13432-20210322T143943.zip)
[xLights_dbgrpt-18500-20210322T144456.zip](https://github.com/smeighan/xLights/files/6184654/xLights_dbgrpt-18500-20210322T144456.zip)

**Comment by dkulp** [comment]
These are all crashes while trying to read an apparently corrupt fseq file, but down in the decompression libraries.   They likely stem from trying to save the blank sequence after the about to crash warning had already corrupted everything.
