### ISSUE TITLE
Enhancement request: Add "Effect Settings" to right mouse click

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#257]
The first thing I do after dropping an effect on a cell is tweak the settings. Adding "effect settings" or "Properties" to the right click would be a great bonus to all.

**Comment by AzGilrock** [comment]
I'm not sure what you're acting for.  The effect settings panel is sitting wherever you put it and that's where you make the changes.  I like to leave the effect setting panel pulled out and sitting right on top of the grid so when I drop an effect the panel is right there.

**Comment by stevegiron** [comment]
Here's how I see it.  For me this would aid in the sequencing workflow. I dock the Effect settings panel to the left as it takes too much screen space on a single monitor setup.

![image](https://cloud.githubusercontent.com/assets/10568498/8049397/ab1cf0b2-0e13-11e5-8dcb-292c98771699.png)

**Comment by AzGilrock** [comment]
Yeah I meant what did you expect it to do when you click "Effect Settings" on the right click menu?  The way all the logic works all the effect setting changes need to go through that panel interface.

**Comment by stevegiron** [comment]
Right clicking on Effect Settings would merely open the effect settings panel front and center. It would be identical to how the Sequence Settings box comes to the foreground when you select Sequence Settings.

**Comment by keithsw1111** [comment]
I dont think this makes any sense any more,
