### ISSUE TITLE
2021.09: Bulk Edit  on Morph "Swap Start and End Points" Broken

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#2571]
After updating to 2021.09, the Morph Options Tab, the Bulk Edit for  "Swap Start and End Points", is no longer working.  The button does continue to work for individual Morph "swaps".  

Thank you for looking,

Clyde

![image](https://user-images.githubusercontent.com/12719816/113189395-28c14000-9229-11eb-8fe0-4968355bca16.png)

**Comment by computergeek1507** [comment]
fixed with c7e1d77dd4409fd24d2d94ad28d8582298ad0782
