### ISSUE TITLE
Layer Settings broke

### ISSUE THREAD

**Issue by Old-Salt** [smeighan/xLights#2574]
**Describe the bug**
Layer Settings broke = Multiple problems...

-  buffer goes to 1/2 vertical and horizontal when 1/2 horizontal is chosen (new in 2921,10)
- Transformation / flip horizontal when 2 shaders used, both must use same settings for the buffer when one is flipped and half horizontal buffer is selected.  (both must use either the left or right half) - goes back many versions

Noticed when using shaders

Will update after VCS 2021

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 7
 - xLights version 2021.10
 - 
**Additional context**

**Attachments**

**Comment by Old-Salt** [comment]
When reverting to a previous version, xLights complains about two unknown key bindings.  Get help in the zoom room to fix this problem.

**Comment by dkulp** [comment]
I cannot reproduce #1.

I have no idea what you are talking about with #2.   Without a packaged sequence and clear instructions on what is the issue, this issue will be closed.

**Comment by Old-Salt** [comment]
Hi Dan,

 

This was entered on GitHub as I was working on an eXessential presentation, so I was light on the details.

-          buffer goes to 1/2 vertical and horizontal when 1/2 horizontal is chosen (new in 2921,10) 

I’d ignore this until the next xLights release.  It may be related to other issues.  I’ll check it then.

 

-          Transformation / flip horizontal when 2 shaders used, both must use same settings for the buffer when one is flipped and half horizontal buffer is selected. (both must use either the left or right half) - goes back many versions

This one is that the transformation / flip horizontal is applied to the entire buffer, not the portion used by the effect.  From the presentation I’m preparing:

---------------------------------------------------------------------------------------

Demo 1:  Fuzzies Attack the render buffer

 

Load a new copy of the shader lab

Place ‘Fuzzies Attack’ on the timeline, and lock it

Configure color for Halloween (shader – use xlights color panel, xLights set color -Yellow)

Shader does not fill the screen – use shader controls to fix this (Center x: ~ -20, Center y: ~-40)

Fuzzies mainly run to right

-          Right click the buffer, select ‘right half’ 

-          Copy Fuzzies Attack’ to second layer

-          Second copy is invisible – buffer settings were also copied

-          Right click the buffer, select ‘left half’ - more Fuzzies, but going in the wrong direction

 

Sequence staged to this point

-          Transformation – Flip Horizontal – left side Fuzzies disappear

-          Right click the buffer, select ‘right half’ – they’re back, and headed in the right direction

-          Important – Tansformations affect the entire buffer, not just the part your effect is using

End of Problem area

 

Fuzzies run in pairs, not randomly

-          Default shader control / Lead in Frames – set to about 300

 

Fuzzies run pseudo randomly, good enough for this demo

-          Lock the second effect

 

 

I’ve staged the sequence to the point where the problem occurs.  It may not be a problem, but the intended result.  I’ll also update GitHub with this information.

 

PS: thanks for fixing #2574 – Layer settings broke.  It will make life much easier for us.  I hope my comment made it easier to locate and fix the issue.  It does pose a problem for my presentation, as I’ll need to omit the part where I described a work-around.

 

Tony

**Comment by Old-Salt** [comment]
This was entered on GitHub as I was working on an eXessential presentation, so I was light on the details.

-          buffer goes to 1/2 vertical and horizontal when 1/2 horizontal is chosen (new in 2921,10)

I’d ignore this until the next xLights release.  It may be related to other issues.  I’ll check it then.



-          Transformation / flip horizontal when 2 shaders used, both must use same settings for the buffer when one is flipped and half horizontal buffer is selected. (both must use either the left or right half) - goes back many versions

This one is that the transformation / flip horizontal is applied to the entire buffer, not the portion used by the effect.  From the presentation I’m preparing:
…

---------------------------------------------------------------------------------------

Demo 1:  Fuzzies Attack the render buffer



Load a new copy of the shader lab
Place ‘Fuzzies Attack’ on the timeline, and lock it
Configure color for Halloween (shader – use xlights color panel, xLights set color -Yellow)
Shader does not fill the screen – use shader controls to fix this (Center x: ~ -20, Center y: ~-40)
Fuzzies mainly run to right
-          Right click the buffer, select ‘right half’
-          Copy Fuzzies Attack’ to second layer
-          Second copy is invisible – buffer settings were also copied
-          Right click the buffer, select ‘left half’ - more Fuzzies, but going in the wrong direction

Sequence staged to this point
-          Transformation – Flip Horizontal – left side Fuzzies disappear
-          Right click the buffer, select ‘right half’ – they’re back, and headed in the right direction
-          Important – Tansformations affect the entire buffer, not just the part your effect is using
End of Problem area

Fuzzies run in pairs, not randomly
-          Default shader control / Lead in Frames – set to about 300
Fuzzies run pseudo randomly, good enough for this demo
-          Lock the second effect

I’ve staged the sequence to the point where the problem occurs.  It may not be a problem, but the intended result.  I’ll also update GitHub with this information.

PS: thanks for fixing #2574 – Layer settings broke.  It will make life much easier for us.  I hope my comment made it easier to locate and fix the issue.  It does pose a problem for my presentation, as I’ll need to omit the part where I described a work-around.

**Attachments**
[blank shader lab1.zip](https://github.com/smeighan/xLights/files/6252367/blank.shader.lab1.zip)

**Comment by dkulp** [comment]
Likely not going to be changed.    Currently, transformation are applied BEFORE the sub buffers are computed.   Changes to that to make the sub buffer get applied first would likely break a bunch of peoples sequences.     I'll leave this open if one of the other developers wants to chime in, but I'm not likely to look at this.

**Comment by Old-Salt** [comment]
Closed due to Dan's comments - this is designed behaviour.
