### ISSUE TITLE
Shaders visually adding value curves where they should not be

### ISSUE THREAD

**Issue by bravado67** [smeighan/xLights#2575]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

In the video, you will see three of the same shaders but each should do different things in the x Offset and y offset based on value curves. The issue is the value curves will be highlighted in the effects that should not have them. 

To reproduce add a shader effect to a model and make some modifications to it in the shader dialog box. Add the same shader and make changes to it. You will see they are inheriting each change you make visually. 

Here is the link to a video I did for you. 
https://vimeo.com/531929650
PW: xLights

[Shaders adding value curves.zip](https://github.com/smeighan/xLights/files/6245755/Shaders.adding.value.curves.zip)

**Comment by Old-Salt** [comment]
Shaders are strange...
The shader settings are not reset until a different shader effect is added to the timeline

you will find other challenges working with shaders...
The best way I've found until these are fixed is
- suspend rendering using the checkbox under the timeline
- add the shader, and position it on the timeline
- lock the shader effect
- re-enable rendering (remove the check)
- render the seqiunce
- adjust the settings for the shader

This will prevent xLights from stacking multiple render cycles and locking you out, sometimes for several minutes,  It won't fix the 'reset to defaults' problem you described, but will allow you to work with them.  I suggest reverting to 2021.09, as there are other problems with 2021.10, including a shrinking render buffer.

eXessentials on April 7 covers working with shaders,  Please bring this up during the Q&A.

**Comment by Old-Salt** [comment]
**Bug re-stated:**  If two of the same shaders are on the timeline, the value curves are not updated in the 'Effect Settings' panel when switching between them.  If a change to value settings is made, or a new value setting is added it is applied to both.  This does not occur when different shaders are involved.

Bug existed back to at least xLights version 2020.57

To reproduce:
In a new sequence:
- add a new shader(I used 'great balls of fire' as in the original report, and others)
- configure a value curve (I used a saw tooth -0.5 to 0.5 for offset x)
- add a second shader from the effects toolbar 

_* note this is a second copy of 'great balls of fire' with same settings as above_

- remove the value curve for offset x from the second shader

_* note both copies of 'great balls of fire' work correctly_

- click on the first shader added to the timeline

_* note the settings are intact_

- click on the second shader added to the timeline

_* note the value curve for the first shader has been carried over
  but the second shader still works as it was configured (no value curve applied)_

- add a value curve to the second shader (I used a saw tooth -0.5 to 0.5 for offset y)

_* note the second shader works correctly_

- click on the first shader added

_* note the value curve for the second shader has been carried back and
  the first shader now works with BOTH value curves applied_

- click on the second shader

_* note the value curves of the first have carried over, but this one works correctly_

- remove both value curves from the first shader

_* note both shaders work correctly_
