### ISSUE TITLE
Command + (period) not marking spot on sequence - Mac

### ISSUE THREAD

**Issue by dfg138** [smeighan/xLights#2576]
Command + (period) does not mark spot on sequencing grid.  I can change key binding to use another character and it works correctly.  Command+/ works appropriately for returning to marked spot.  It doesn't appear that Mac is utilizing Command + (period) anywhere else that would cause a conflict.  

Mac OS Big Sur 11.2.2 
xLights 2021.10 (issue existed on .09 as well)

**Comment by dkulp** [comment]
This doesn't seem to be possible to implement.   macOS maps cmd-. to a Cancel action internally someplace and xLights never even gets the key events.   What I'm going to implement, however, is support for the actual CTRL key.   Thus, the actual ctrl-. and ctrl-/ will work.    At this point, they will be the only two added to the default keybindings, but you will be able to add additional  bindings that use the real CTRL key.   They won't work on the other platforms if you load the same keybindings.xml file.

**Comment by dfg138** [comment]
Awesome! Thanks Dan!
