### ISSUE TITLE
crashes when I import LMS file

### ISSUE THREAD

**Issue by wdmilkie** [smeighan/xLights#258]
using win 8.1 on laptop
start new musical sequence
open audio file
set time to 50ms
set to LOR
click to import lms file
crashes
repeatible

**Comment by wdmilkie** [comment]
using new 4.1.2 XL

**Comment by wdmilkie** [comment]
I think this may be my fault, I didn't have any network defined under setup
I'll try it later

**Comment by stevegiron** [comment]
Let us know your change fixed this issue.

**Comment by wdmilkie** [comment]
haven't had time to even look at it but I will

william

**Comment by stevegiron** [comment]
Hi Will, is this working now?  We're on Version 4.2.13 now. http://nutcracker123.com/nutcracker/releases/

**Comment by wdmilkie** [comment]
yes, I think I forgot to set up the network properly, sorry, I should have
deleted it; forgot

thanks

william
