### ISSUE TITLE
New Error- "Unhandled exception"

### ISSUE THREAD

**Issue by Lenchuckd** [smeighan/xLights#2581]
Hey,

Getting a new error that crashes xlights, seems to be when i'm changing sub-models.

Unhandled exception

An unhandled exception occurred Press "Abort" to terminate the program,
"Retry" to exit the program and "Ignore" to try and continue.

Thanks in advance,

Dave.

![image](https://user-images.githubusercontent.com/74312259/113477882-2a6e4c00-9453-11eb-9091-892234671c07.png)

**Comment by Raketyboom** [comment]
I am getting the same error when trying to add models to an existing group. The only resolution is to terminate the program. none of the abort/retry/ignore options work.  It just rethrows the same error dialogue box back up.

**Comment by bjhiltbrand** [comment]
This issue was already reported in [2577](https://github.com/smeighan/xLights/issues/2577). It appears to have been fixed with the latest 2021.11 version. Please check and verify.

**Comment by Lenchuckd** [comment]
Just updated and appears to have worked! Thanks! Closing this request.
