### ISSUE TITLE
export model cad / export layout dxt

### ISSUE THREAD

**Issue by lesm2425** [smeighan/xLights#2583]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
hi when i download 2021.10 i got this strange message when i opened up x lights i went to the forum and i was told to remove the keybinding file.
i later went to back to 2021.9
since then i was getting little glitches in the program, effects wear off and music would glitch for a milli second.
it got worse as yesterday when i was rendering up and the screen would flash just like a flicker what was when the render would fail,
so your fscq files are corrupt and will not play on FPP.
also its running a little slow.

**To Reproduce**
it come on after you install 2021.10, i have installed 2021.11 and thats not helped.

**Expected behavior**
correct fscq files

**Screenshots**
![export model export layout](https://user-images.githubusercontent.com/65862734/113507014-ea38c780-953f-11eb-8f56-d45231e2c026.jpg)

**Versions (please complete the following information):**
 - OS:windows 10 20H2
 - xLights version [e.g. 2021.10

i anm having to run my easter show by output to lights and i cant run anything on FPP

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
Keybindings errors are harmless. Delete the keybindings file and it will get re-generated (assuming you have not customised it).

Any other errors you are having we would need a better explanation of and/or a sample. Until then I am going to close this one. You can reopen it if you attach more files.
