### ISSUE TITLE
Poly line doesn't support video or image effect

### ISSUE THREAD

**Issue by nielsotto** [smeighan/xLights#2584]
Hi
When doing the poly line, it's not able to put a video file on the pixels. When doing any other pre-made model, like the tree, the video runs immidiately.
<img width="1792" alt="Screenshot 2021-04-04 at 19 10 47" src="https://user-images.githubusercontent.com/40137522/113516370-2ee15480-957a-11eb-8ae6-d8b3a8233003.png">
<img width="1792" alt="Screenshot 2021-04-04 at 19 11 31" src="https://user-images.githubusercontent.com/40137522/113516372-3143ae80-957a-11eb-884f-4b40a78497ed.png">

**Comment by keithsw1111** [comment]
This is by design ... props with a 1 dimensional buffer are not suitable for video effects.
