### ISSUE TITLE
Crashing Moving Rosa Grande in 3D

### ISSUE THREAD

**Issue by Kosh42** [smeighan/xLights#2585]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Every time I try and move a Rosa Grande in 3D xLights crashes.

**To Reproduce**
See video. Moving in 2D is fine.

https://user-images.githubusercontent.com/58401509/113516751-ef176e80-9573-11eb-9867-751e915203b1.mp4

**Expected behavior**
Not to crash.

**Screenshots**
See video.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021:11

**Additional context**
Crash report attached.

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
[xLights_dbgrpt-24228-20210404T180612.zip](https://github.com/smeighan/xLights/files/6254998/xLights_dbgrpt-24228-20210404T180612.zip)

**Comment by keithsw1111** [comment]
I believe these problems are now fixed. Please reopen if you are still experiencing issues.
