### ISSUE TITLE
Ability to easily shape and animate the render buffer

### ISSUE THREAD

**Issue by qualar** [smeighan/xLights#2589]
**Is your feature request related to a problem? Please describe.**
1. Currently the render buffer only has 4 points so can only be rectangular. Add ability to add extra nodes to allow the render buffer to be any shape.
2.  Add a motion tab to provide the ability add multiple points that store position, size and rotation of the render buffer when sequence is playing the render buffer would transition from point 1 to point 2 etc etc.

This would enhance all of the current built-in effects and make complex motion path animations easy to implement.

I have included an image of how the interface may look
https://1drv.ms/u/s!ArKnPav27dHwkel8h32oJP-QI8cwXg?e=kcsV4l

**Comment by computergeek1507** [comment]
You can already do this with multiple layers and masking

**Comment by qualar** [comment]
> You can already do this with multiple layers and masking

The shape yes but not the motion path.  To do motion paths you need to set the value curves for Top, Bottom, Right and Left of the buffer which can be very cumbersome and involves writing down all the co-ordinates to ensure the buffer size remains consistent.

**Comment by Clyde-L** [comment]
Using the 2D Path editor  can accomplish this with your path and the shape.  Also, shapes has an Emoji feature where you can find simple images that you can change to any font you like.

https://www.youtube.com/watch?v=A2PkJkiPolU

**Comment by qualar** [comment]
Clyde.  I know that the animation can be achieved but would be much quicker and ekegznt if a motion path tool was integral to the render buffer.  This would allow position, scale and rotation to all be controlled in one window.  Also the 2D Path Generator tends to crash when you use a lot of points.

**Comment by AzGilrock** [comment]
I don’t see render buffers changing from rectangles.  All effects expect a rectangular render buffer

**Comment by AzGilrock** [comment]
And I don’t remember all the details but there was a good reason we never put the x/y motion into the buffers. We thought about it years ago.. it won’t work like you think
