### ISSUE TITLE
2021.11 Key Bindings not working

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#2590]
After installing 2021.11, I found that many of my keybindings (insert row above/below, open preset menu, open effects assist window) do not activate those functions.  The effects keybindings worked just fine, no problem.  It seemed like the "functions" within the sequencing grid were the only things affected.  
Currently reverted back to using 2021.10 and these shortcuts now work.  

Thank you for looking into it.

Clyde

**Comment by computergeek1507** [comment]
fixed with 0e671138a484b49a920746294e7d33b46af9a641
