### ISSUE TITLE
Single Strand Icon

### ISSUE THREAD

**Issue by justinmiller24** [smeighan/xLights#2595]
The icon for the 'single strand' effect has two strands on it. This was mentioned as a possibly feature enhancement (cosmetic only) at VCS and I wanted to pass along.

**Comment by AzGilrock** [comment]
So the feature enhancement is to remove the second strand from the icon?

**Comment by justinmiller24** [comment]
@AzGilrock Correct. It was suggested as a UI enhancement today during John Storms' session at the Virtual Christmas Summit, so I wanted to relay.

**Comment by AzGilrock** [comment]
I didn’t think it coUld be that stupid but had to check.

**Comment by derwin12** [comment]
I was sort of said in jest ;-)
