### ISSUE TITLE
xlights to limit 680 pixels per port

### ISSUE THREAD

**Issue by Strawberry1997** [smeighan/xLights#2596]
I want in the visualizer to indicate any controller port that has over 680 pixels per port to keep the controller in 40FPS.
possibly make the 680 number customizable for each user or controller.
This is mainly for the Falcon controllers which have banks that share ports 1+17+33

**Comment by keithsw1111** [comment]
I dont think this is necessary. This is intrinsically a property that varies by controller and even by pixel type.
