### ISSUE TITLE
Tapping the timings 4.1.3

### ISSUE THREAD

**Issue by RichardRennII** [smeighan/xLights#260]
Not sure if this has been brought up but I have noticed that tapping the timings in place, half way through the song it will just randomly stop playing have to start it up again and from that point on it will just stop playing from time to time more of a annoyance than anything.

**Comment by stevegiron** [comment]
I thought I had that issue too. It was me inadvertently hitting the spacebar when I was hitting the T for timing marks. Switched keyboards, no longer an issue.

**Comment by stevegiron** [comment]
Richard, can you verify that this is 100% the software and not a stray finger by the spacebar.

**Comment by RichardRennII** [comment]
I will play with it tonight to see if it happens again being very careful not to hit the space bar

**Comment by RichardRennII** [comment]
Steve  I watched very closely and I must have been touching the space bar
not realizing it have had no issues lately

**Comment by stevegiron** [comment]
#1. If your hands are shaped like any normal human being, you can't get to the T key without something hovering over the space bar unless you turn your keyboard 180. 

#2. I only know of your issue because it happened to me many times :)
