### ISSUE TITLE
Single Strand To/From Middle Location Error W/ Video

### ISSUE THREAD

**Issue by trevora91730** [smeighan/xLights#2603]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
The Single Strand Chase Type "To/From Middle" does not start at the middle.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Add Single  Strand to Arches
2. Change the type to "From Middle" or "To Middle"
3. Watch it not start/end in the middle of the arches

**Expected behavior**
Expect it to start to/from the middle

**Screenshots**
Video attached

**Versions (please complete the following information):**
 - OS: Windows 10 pro
 - xLights version [e.g. 2021.12] April 12, 2021

**Additional context**
N/A

**Attachments**
Video describing error and setup

https://user-images.githubusercontent.com/9464766/115129058-14f73700-9fa8-11eb-9d7d-506177c88ef4.mp4

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by trevora91730** [comment]
Does anyone else have this issue?

**Comment by keithsw1111** [comment]
You didnt attach a show folder so we cant reproduce it.

**Comment by trevora91730** [comment]
> You didnt attach a show folder so we cant reproduce it.

[Test.zip](https://github.com/smeighan/xLights/files/6587973/Test.zip)
