### ISSUE TITLE
Updating an Effect

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#2605]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When updating an Effect for multiple Elements (IE from "On" to "Twinkle") it also updates the color to whatever might be checked.
I would think the Update button in the effects settings would only update the effect...not other things (like color) also.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Highlight multiple elements
2. In Effect Settings change the effect from one to something else
3. If a color is checked in "color" those elements color also changes

**Expected behavior**
I would think the Update button in the effects settings would only update the effect...not other things (like color) also.

**Screenshots**
N/A

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.12

**Additional context**
N/A

**Attachments**
-N/A

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
This is expected behaviour. Have you tried using bulk edit instead. I think the update button should be removed.

**Comment by jimswinder** [comment]
No...have not tried using bulk edit...will look for that and give it a try.

Thanks!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Keith Westley ***@***.***>
Date: 4/27/21 2:05 AM (GMT-08:00)
To: smeighan/xLights ***@***.***>
Cc: jimswinder ***@***.***>, Author ***@***.***>
Subject: Re: [smeighan/xLights] Updating an Effect (#2605)


This is expected behaviour. Have you tried using bulk edit instead. I think the update button should be removed.
