### ISSUE TITLE
AC Toolbar - Twinkle Does Not Ramp up to 100%

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#2606]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When using the AC toolbar and using the Twinkle with a Ramp Up or Down it does not gegin/end at 100% even though the setting is 0and 100
**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Turn on AC Toolbar
2. Click "On"
3. Click "Ramp Up"
4. Setting 0 and 100
5. Use on Element

**Expected behavior**
Would expect Twinkle - Ramp Up to go from 0 to 100%

**Screenshots**
N/A

**Versions (please complete the following information):**
 - OS: Windows 10
 -  - xLights version 2021.12

**Additional context**
N/A

**Attachments**
N/A

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
It does ramp up to 100% ... remember the scale of brightness is 0-400% so it should only go up 1/4 of the maximum value.
