### ISSUE TITLE
Common Group or Model names

### ISSUE THREAD

**Issue by lewislawrence2** [smeighan/xLights#2608]
**Is your feature request related to a problem? Please describe.**
Hi, I am in my second year of using x lights, its a remarkable program!  As a new user, i mapped a number of songs from various places.  its much easier than trying to create too many of your own songs, the learning curve to this hobby is high.  I would like a chance to give back to the community!

**Describe the solution you'd like**
I would like to work with a group of people to develop a basic set of Group names.  My vision is that these could be a set of default groups people could use for initial mapping and sequencing.  It could also simplify the mapping process for new sequences.  I realize that the programers have set this up to allow infinite possibilities, and full customization.  I think this should continue, but new people will benefit from a baseline of folders, they want some guidance.

for example - wholehouse or housewhole, all house, house no yard.  People use each of these and it causes more time than it should with mapping, mapping templates help, but i think we can do better.  If we came up with an initial 20-25 groups, newbies would have a some good help with getting started.

**Describe alternatives you've considered**
the current strategy of everyone starting from scratch is cumbersome, a default list would help to overcome the learning hurdle.

**Additional context**
I don't think this should be led by a single person or sequencer, it should be a group effort, people are welcome to participate in developing the base list.  I will be glad to work with anyone you designate as key persons to develop the list.

I appreciate your consideration - and thank you for making xlights so awesome!

**Comment by keithsw1111** [comment]
While I see some pretty big challenges in making this happen I dont see how you need anything in the code to change to do it. Ask for volunteers on facebook ... do your work ... publish it ... get a bunch of support ... and then do your best to influence folks to align. There are lots of vested interests out there that will likely passively resist such an initiative but with enough support I guess you could make it happen ... you could even have standard xmap files for the recalcitrant vendors unwilling to align.

Of course there are some pretty significant limitations in what you can achieve in a handful of groups but who knows folks may find the idea interesting enough to support you.

So unless there is something you think you need in the xLights code which I cant see then we will close this ticket. Feel free to add more comments or reopen if there is a change to propose.

**Comment by lewislawrence2** [comment]
Perfect, I’ll give it a shot, thanks for the words of wisdom

Best,
Lewis
