### ISSUE TITLE
Light-O-Rama Model Types Missing

### ISSUE THREAD

**Issue by NDelo21** [smeighan/xLights#2610]
**Describe the bug**
When adding a Light-O-Rama Controller, the Models are out of date

**To Reproduce**
1. Go to the Controllers Tab
2. Add a USB Device
3. Select LOR for the Vendor
4. Model List is out of date

Additionally:
5. If you select LOR Optimised for the Protocol, the Controller details section appears
6. Under the Device Type, the same LOR devices are missing

**Expected behavior**
The following two "newer" LOR devices should be in the list
1. CCC-II/Pixie2
2. PixCon16

**Screenshots**
Controller List from the Light-O-Rama Software
![LOR_Controller_List](https://user-images.githubusercontent.com/82744997/115174368-20755b80-a097-11eb-9e29-de16aae5fe7c.png)

Available Controllers from xlights:
![XLights_Options_List](https://user-images.githubusercontent.com/82744997/115174427-371bb280-a097-11eb-9d16-c324c56afe6c.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.12

**Additional context**
I personally have the Pixie2 / CCC-II. I have tried selecting other options, but I am unable to control those lights through xlights without it.

**Comment by computergeek1507** [comment]
The PixCon16 is already available, add a ethernet type controller to select it.

**Comment by computergeek1507** [comment]
Added Pixie 2 with https://github.com/smeighan/xLights/commit/846c08a2969b81c4175a35a9e8acc7c620e54606

**Comment by NDelo21** [comment]
Perfect, thanks. I realized after I opened the issue that this wasn't the cause of my problems. I realized that this just sets up the number of outputs, so that you can setup your channel numbers. Thanks for responding.

**Comment by NDelo21** [comment]
I noticed in the newer versions of xlights that the Pixie 2 is now in the Model list. I am wondering if it's also possible to add it under the Device Type as well? I know that it's not a huge deal, but it just makes things a bit cleaner :)

**Comment by AzGilrock** [comment]
I wrote the original Lor Enhanced Protocol stuff but I'm not as familiar with the reorganization of everything.  It doesn't make sense to me that Model and Device Type could be 2 different controllers anyways.  So you're saying someone can select Pixie 4 for model and Pixie 2 for Device Type?

**Comment by NDelo21** [comment]
When it comes to adding in the LOR devices, you can only have 1 connection to the COM port. So you can't add each controller separately, they all have to be under one. So the Vendor / Model at the top is only useful if you have 1 device on the LOR network. In my case, I have two. So I update that there are 2 Devices. Then you need to specify each device separately. So in that situation, there is a Device Type drop down list, and the Pixie2 isn't there.

I posted a picture of my config, as well as what options are available from the device drop down.
![xlights_LOR_Config](https://user-images.githubusercontent.com/82744997/116607503-0e4db580-a900-11eb-82cc-ab9e0ca152af.png)

![xlights_LOR_Device_Options](https://user-images.githubusercontent.com/82744997/116607513-13126980-a900-11eb-9c59-25deb1594cc4.png)

**Comment by AzGilrock** [comment]
Well yeah I understand that part that's why I wrote it that way so you could define multiple LOR controllers for one COM 
port.  Without digging into the code I don't know if that "Model" field really does anything.  It should be pretty easy to add the Pixie2 to the Device Type because I'm pretty sure my code looks for the "Pixie" prefix and then strips off the number on the end to know how many channels to define.

**Comment by keithsw1111** [comment]
I have added a Pixie 2. The Pixcon is an ethernet controller and does not belong here.
