### ISSUE TITLE
Open a .xsq directly when the directory has a - in it, will cause an error on startup

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2611]
As reported on fb. If you double click on an .xseq file where the directory has a "-" it will throw and error/warning that xlights has invalid parameters..

Eg: c:\xlights\dec-2020\showfolder  .. as an example directory.

I gather that the double click sees -2020 as a parameter to xlights rather than part of the file name.

**Comment by keithsw1111** [comment]
I believe I have this fixed on windows ... I have not tried to address it on other platforms as it may have undesirable side effects. In my checkin I have described the right long term solution but I cant make that change ... at least not in a way that fixes it on all platforms.
