### ISSUE TITLE
Sequence Scaling

### ISSUE THREAD

**Issue by JD2410** [smeighan/xLights#2612]
**Describe the bug**
The scaling of the main sequence area is really small and hard to use
![image](https://user-images.githubusercontent.com/48348103/115596765-65d09d80-a2d0-11eb-9740-f503adbdcc3c.png)

**Versions (please complete the following information):**
Windows 10
Xlights Version Latest as of 21/04 (I can't see it 
![image](https://user-images.githubusercontent.com/48348103/115596617-3588ff00-a2d0-11eb-8e91-6b6b5747585d.png)

I don't know if there's a setting or something but really could do with making it to scale with the rest of the interface

**Comment by JD2410** [comment]
Compare the text in the screen shot in comparison to the rest of the interface text and you'll see what I mean.

**Comment by dkulp** [comment]
There is a setting for this in the "Effects Grid" tab of preferences.

**Comment by JD2410** [comment]
@dkulp you are actually my hero good sir! all sorted
