### ISSUE TITLE
Shader Effect: Drop-down selection is ignored if the label contains a comma

### ISSUE THREAD

**Issue by Old-Salt** [smeighan/xLights#2618]
**Describe the bug**
Shader Effect: Drop-down selection is ignored if the label contains a comma

**To Reproduce**
1.  Import the attached sequence
2.  Set the color option to "Convert to Black and White "
3. Note the conversion works
4. Open the shader in an editor, insert a comma in the label at line 38
5. Replace the shader effect with another shader 'Blue Streaks.fs' provided
6. Reload the shader 'Color Change or Make Mask_dev.fs'
7. Set the color option to "Convert to Black and White "
8.  Note the option does not work

Note: The shader must be replaced, then re-loaded for any changes in the JSON blob to take effect.  

**Expected behavior**
Shader drop-down lists should allow commas

**Screenshots**
n/a

**Versions:**
 - OS: Windows 7
 - xLights version [e.g. 2021.12]

**Additional context**
n/a

**Attachments**

[shader lab comma bug.zip](https://github.com/smeighan/xLights/files/6383485/shader.lab.comma.bug.zip)

**Comment by keithsw1111** [comment]
This is not going to change. the use of commas in field values is buried deep deep within the way effect settings are handled and would be a massive change just so a rarely used shader field could be supported. What i will do is remove the comma from the field values when we load it.
