### ISSUE TITLE
Xlights instantly crashes when creating a new 40fps musical sequence

### ISSUE THREAD

**Issue by qualar** [smeighan/xLights#2619]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When you create a new musical sequence then select 40fps xlights locks up and crashes.  It works fine if you select 20fps or create an animation sequence.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Create new sequence
2. Select Musical Sequence
3. Select 40FPS

**Expected behaviour**
Should create a new sequence

**Versions (please complete the following information):**
 - OS: Windows 10 [Version 10.0.19042.928]
 - xLights version 2021.13

**Comment by computergeek1507** [comment]
Can confirm it locks up for me as well. Seems like something in 11ddea268529d1f9db16c7d2fdf51b48aac131d0 and 515f60c953046824753025bf56dc735cd117e824 caused it. I reverted these two commits on my local build and it worked as expected.

**Comment by keithsw1111** [comment]
Yeah ... a race condition
