### ISSUE TITLE
Show Stopper While Playing

### ISSUE THREAD

**Issue by wbottomley** [smeighan/xLights#262]
If the correct mp3 file has been removed, moved, or in a different directory, the show simply stops.  Can it be coded to note the error in the log but continue on?  This is really helpful especially on two different machines where one is used to sequence and the other for playback.

**Comment by AzGilrock** [comment]
Ok I think I fixed this.  I modified it to jump to the DELAY_AFTER_PLAY state which will run any delay or post song action you have setup and then cycles to the next song.  I tested with two songs and then renamed the mp3 for the second sequence and it played sequence 1 and then displayed the error for sequence 2 and then started playing sequence 1 again.

**Comment by wbottomley** [comment]
Excellent!  Thank you!!!!!!!!!!!

On Wed, Jun 10, 2015 at 10:12 AM, Gil Jones <notifications@github.com>
wrote:

> Closed #262 <https://github.com/smeighan/xLights/issues/262> via 709b28c
> <https://github.com/smeighan/xLights/commit/709b28c98f7a76716ce869aa0b45b31da4b124b4>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smeighan/xLights/issues/262#event-327472375>.
>



-- 
William Bottomley
