### ISSUE TITLE
Some Value Curves for Shaders not working, others have random information displayed

### ISSUE THREAD

**Issue by MDickson00** [smeighan/xLights#2620]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

When using the shader effect, after choosing a shader and attempting to use value curves in the effects settings sindow, Offset X, Offset Y, and Zoom value curve buttons do not work. Also, the other values listed in the effects settings have random names such as j,k,c0,c1, etc... See picture attached.

1. Start a new sequence
2. Drop on a shader effect and choose a shader
3. In the effect settings window, click on the value curve buttons for Offset X, Offset Y, and Zoom
4. Notice that nothing happens
5. Also look at the names for the other valuse listed for that shader in the effects window.

It would be expected that clicking the value curves button will open a new window allowing you to change the value curves.

I am attaching the sequence I was working on, and an image of the effects window.

Using Windows 64 version 2021.14
![xlightsBug](https://user-images.githubusercontent.com/83371818/116465669-273c6500-a833-11eb-9ec4-7a5ea193c710.jpg)
[Old Time Medley.zip](https://github.com/smeighan/xLights/files/6394497/Old.Time.Medley.zip)

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by Old-Salt** [comment]
With Respect to point #5, I examined the shader 'Fly Through.fs' and found:

'Lead in Frames:', 'Time Speed:', 'Offset x', 'Offset y', and 'Zoom' are parameters added by xLights.

'j', 'k', 'c0', 'c1', and 'c2' are parameters added by the shader itself.  These are the names of uniforms (or variables) defined in the JSON blob.  They have no nice label telling us humans what they do, so xLights' display for these is correct.

**Comment by keithsw1111** [comment]
I fixed the value curves. The rest is as expected.
