### ISSUE TITLE
Addition of 'Multiply' method of 'Layer B;ending'

### ISSUE THREAD

**Issue by Old-Salt** [smeighan/xLights#2621]
**Is your feature request related to a problem? Please describe.**
Current blending methods result in on/off masking with harsh edges, or the visibility of the grayscale layer,

**Describe the solution you'd like**
Pixel by pixel multiplication of the individual rgb channels for two layers. This would result in changes in brightness of a layer when a grayscale layer is used as a multiplier.  Use of two colored channels could provide some interesting results.

**Describe alternatives you've considered**
Use of the alpha channel for grayscale masking.  This would involve conversion of a layer into alpha channel or opacity data prior to use for blending.  The alpha channel is apparently ignored during blending.

**Additional context**

**Comment by keithsw1111** [comment]
I dont think you have described it very well but i think you want to set the new pixel to

r(layer1) * r(layer2) / 255. green and blue similar

In which case done.

Alpha channel is not ignored in blending but i also dont know how i would determine the value unless i average the rgb values.
