### ISSUE TITLE
Bulk edit submodels

### ISSUE THREAD

**Issue by reelpilot** [smeighan/xLights#2622]
**Is your feature request related to a problem? Please describe.**
There is currently no easy way to add or update submodels to more than one model at a time. I currently have over 50 versions of the same model and need to update the submodels for these. Doing it one at a time will take a very long time as I must select a prop, click the submodels edit window, click import and select the model or file with the updated submodels. A way to bulk edit this process would be a huge timesaver for instances when multiple props need to be updated.

**Describe the solution you'd like**
When selecting multiple models, retain the submodel edit box in the left hand column so that the current process of updating the submodels can apply to all selected models.

**Describe alternatives you've considered**
Using the current process to individually update over 50 models.

**Comment by computergeek1507** [comment]
I added a "Export SubModels To Other Models" option to the submodel dialog to export one models submodels to other models in bulk, https://github.com/smeighan/xLights/commit/5905a8437a9ddaed6edbd4dfbfd20a21880a16e4
