### ISSUE TITLE
XLights crashes when loading a certain sequence

### ISSUE THREAD

**Issue by TomL8345** [smeighan/xLights#2624]
xLights (Ver 2021.14 64bit) crashes each time I try to open my sequence Skating.  I have used this same sequence in xLights for the last several years.  All other previously used sequences open properly

1. open xLights
2. click Open Sequence
3. choose Skating sequence file
4. press Open button
5. xLights then closes

[xLightsProblem04-30-21.zip](https://github.com/smeighan/xLights/files/6408763/xLightsProblem04-30-21.zip)

[Skating.zip](https://github.com/smeighan/xLights/files/6408768/Skating.zip)

**Comment by keithsw1111** [comment]
It opens for me which means the problem is either environmental or requires all the sequence components which this way of sharing may have missed some. Maybe go back to a prior version and package the sequence.

**Comment by dkulp** [comment]
The log contains a bunch of:

2021-04-30 16:14:43,387 15272 log_base [WARN] LoadResampledAudio: This shouldnt happen ... read [6490112] + nb_samples [2048] > _tracksize [6490112] .
2021-04-30 16:14:43,387 15272 log_base [DEBUG] DoLoadAudioData: Song data loaded in 120. Read: 6492160

which is the root cause of the crashes I fixed yesterday.   This is likely fixed on master now.

**Comment by TomL8345** [comment]
> The log contains a bunch of:
> 
> 2021-04-30 16:14:43,387 15272 log_base [WARN] LoadResampledAudio: This shouldnt happen ... read [6490112] + nb_samples [2048] > _tracksize [6490112] .
> 2021-04-30 16:14:43,387 15272 log_base [DEBUG] DoLoadAudioData: Song data loaded in 120. Read: 6492160
> 
> which is the root cause of the crashes I fixed yesterday. This is likely fixed on master now.

Dan, does this mean it should be fixed with the next update?  I am just trying to understand what you are saying.

Thanks,

**Comment by MrPaulAR** [comment]
@TomL8345 If this is fixed will you please close the issue.

**Comment by TomL8345** [comment]
Issue was fixed with update.  How do I close this issue?
