### ISSUE TITLE
Enhancement: Improve text on Import effects dialogue box

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#263]
Suggest changing left column "Model" to "Model Source"

and

Left column "Channel" to "Model Destination"  You can't map to a channel, only to a model, so Model is more appropriate here.

Also timing marks are listed as possible destinations to map to when importing. Can you filter out timing marks?

![image](https://cloud.githubusercontent.com/assets/10568498/8096274/2d6ff6dc-0f8a-11e5-96c0-b0ab409744bf.png)

**Comment by dkulp** [comment]
The 3 columns on the left are the target destinations.    You can import the effects onto the model, onto a strand of the model, or a node of the strand.      The "Channel" colum is the source and for LMS, HLS, and LSP, channel is likely the right name.  I suppose for xLights imports, renaming that to Source might work.
