### ISSUE TITLE
2021.15 crashing when saving layout image

### ISSUE THREAD

**Issue by bacarudaguy** [smeighan/xLights#2633]
Attached video shows saving the layout image, making a change, then re-saving the image and attempting to replace the file. XLights crashes and does NOT produce a crash report (app or system).

OSX 10.15.3

https://user-images.githubusercontent.com/1183946/117229647-634e6780-ade9-11eb-8b3e-eb35982805ec.mp4

**Comment by keithsw1111** [comment]
Maybe an OSX issue ... It seems to save ok on windows.

**Comment by dkulp** [comment]
Cannot reproduce on OSX either.

**Comment by bacarudaguy** [comment]
Just replicated it twice... seems to be an issue overwriting the Untitled.jpg default file name...

**Comment by keithsw1111** [comment]
If neither Dan or i can reproduce it then we either need more information or I will need to close this.
