### ISSUE TITLE
xschedule closes after sequence 2021.15

### ISSUE THREAD

**Issue by bcarriveau** [smeighan/xLights#2635]
**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to xschedule, put a fseq into a playlist, 
2. manually start fseq
3. watch time run down on sequence 
4. xschedule closes by itself.

**Expected behavior**
xschedule to stay open and not close

 - OS: windows 10
 - xLights version 2021.15

**Comment by keithsw1111** [comment]
I think this has been fixed by one of the other changes & will be in .16
