### ISSUE TITLE
Xlights crashes with layout submodel changes.

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2636]
Seems like quite a few steps .. but will crash every time. (Hoping you get the debug logs)
2021.15
Note: I have a second instance of xlights open pointing to a temp folder to view another layout and flip back and forth.

Editing a prop and the submodels .. 
1. Custom Model, Add new submodel (30+ submodels)
2. Add the various Node Ranges, click OK.
3. Add this new model to a group and Save (since it would crash in a bit)
4. Go to the sequence render and it crashes there or after playing the segment a couple of times.
5. I can package an empty sequence to add if that would help.

**Comment by derwin12** [comment]
[WIP - PC Spinner - Crash.zip](https://github.com/smeighan/xLights/files/6446883/WIP.-.PC.Spinner.-.Crash.zip)
Working with PC Spinner SubModels then adding to the various PC Spinner Groups.

**Comment by derwin12** [comment]
[xLights_l4cpp.zip](https://github.com/smeighan/xLights/files/6446884/xLights_l4cpp.zip)
No dump but there appears to be something in the dump log

**Comment by dkulp** [comment]
FYI:  I had tried to reproduce this on OSX and couldn't get it to crash.
