### ISSUE TITLE
Minor Screen Refresh Bug .. with Perspectives 2021.15

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2637]
Using a default perspective and switching to a more full screen perspective, it doesnt populate the list of models completely. Perhaps some sort of refresh is needed after switching perspectives? (work around is to switch Views and back to force the list to repopulate)

![2021-05-09 09_51_16-xLights - F__2020_ShowFolder3D_WIP - PC Spinner xsq](https://user-images.githubusercontent.com/4643499/117574777-b73ca300-b0ac-11eb-90b7-0777782f2636.jpg)

**Comment by keithsw1111** [comment]
I dont seem to be able to reproduce it. I created 2 perspectives. One with a small effects grid and one with a large one and kept switching between them and every time it repainted.

Either there is something particular about what you are doing or this problem has disappeared.

**Comment by dkulp** [comment]
Could not reproduce on OSX.   I think from the description is was more about hitting the maximize button or something to make the grid larger.  Not really sure as the description on how to reproduce is severely lacking.

**Comment by derwin12** [comment]
Cant duplicate it either ..
