### ISSUE TITLE
Errors doing xmodel import with groups included

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2638]
I have an xmodel exported from my layout that I would like to distribute to others for import. The xmodel includes the model plus a bunch of submodels. Also included are the various groups that included this model (only this model are in the groups). 
2015.15

When importing the model it shows an alert box saying the various models dont exists. When it completes, the model and submodel are there, the groups are there, but the submodels that should be part of these new groups, do not exists.

Should be easy to duplicate .. From the layout, import the attached xmodel.

It seems like when the groups get processed it doesnt know that there exists new model and or submodels (yet).
[PC Spinner.zip](https://github.com/smeighan/xLights/files/6447830/PC.Spinner.zip)

**Comment by derwin12** [comment]
user said it worked when done in some 2020.x version

**Comment by bacarudaguy** [comment]
I've got this same issue... took a moving head, exported, then tried to reimport into a different layout... getting an error stating it's an invalid model... failed on both 2021.16 & 17...

**Comment by keithsw1111** [comment]
Actually I think this is fine. The model file contains a model called PC Spinner Left but the groups refer to PC Spinner Right and quite rightly xLights is saying there is no PC Spinner Right.

So the question more correctly becomes why does the model file include a reference to a model not in the file but there is not enough information here for me to determine that. I would need the original layout and to know exactly how you exported it.

**Comment by derwin12** [comment]
So when exporting the model, dont select any groups in that pop up asking for groups. Will give that a try..
