### ISSUE TITLE
FFWD and REW hotkeys (for use with transcription foot pedals or macro keyboards)

### ISSUE THREAD

**Issue by DoctorWiz** [smeighan/xLights#2639]
I have some transcription foot pedals that I would like to use for sequencing:
https://www.amazon.com/Infinity-Digital-Control-Computer-USB2/dp/B002MY6I7G/
They are available used on eBay starting around $20 USD.
I also have an Elgato Stream Deck, and macro keys on my Corsair keyboard I've been assigning shortcut keys to (highly recommended!)
Typically, pressing the big center pedal with transcription software causes the audio to play, releasing it causes it to pause.  Pressing the left pedal rewinds, and pressing the right pedal fast-forwards.
The Ctrl-0 thru 9 and Ctrl-Shift 0-9 hotkeys are great, but what I'm looking for is something more akin to ffwd and rew regardless of where you are, so perhaps a key to jump to the next marker (whichever one that might happen to be, based on your current position) and likewise jump to the prior marker.  And/or hotkeys to jump forward or backwards by _x_ number of seconds.
You can also switch modes on the foot pedals by pressing the left and right pedals together, so the more unique ways to navigate, the better, and that brings me to speed...  Hotkeys to speed up or slow down playback would be useful, or alternatively, if the options on the Audio menu were rearranged in order 1/4, 1/2, 3/4, 1, 2, 3, 4 I could use an Alt-A, Arrow Up, or Alt-A, Arrow Down.
As for Play & Pause, I've already got it working by sending a Media-Play/Pause (toggle) keystroke when depressing the middle pedal, and again when releasing it.  What would be better tho is separate non-toggling hotkeys for play and for pause.

Thanks guys!  You rock!

**Comment by keithsw1111** [comment]
I added a prior and next tag hot key option. They will only jump to inserted tags ... not the 10% invisible points. The speed keys have also been added.
