### ISSUE TITLE
Crash during a LSP file import.

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#264]
I mapped my Nutcracker Mega Tree  to LSP megatree channels. I then attempted to do an import on a sequence of the Megatree effects with a resulting crash. A screen dump of the crash is here:
![screenhunter_235 jun 10 19 18](https://cloud.githubusercontent.com/assets/3072139/8096782/bacc23ca-0fa8-11e5-95be-15bc291ce131.jpg)
The crash file is located here.

https://dl.dropboxusercontent.com/u/28041968/Nutcracker%20Testing/xLights_dbgrpt-6180-20150610T191816.zip

I can provide any further files as needed.

**Comment by dkulp** [comment]
May need to see the MSQ file as well.

**Comment by MrChristmas2000** [comment]
This is a link to it.
https://dl.dropboxusercontent.com/u/28041968/Nutcracker%20Testing/Winter%20Wonderland%20techno%20-%20MASTER%20FILE%20-%2005_10_2015%20-%20Copy%20-28.200s.msq.zip
Started to test another set of NC models for import with the same file and it crashed.

**Comment by dkulp** [comment]
This Controllers/10da02e0-0be6-42b1-b45f-712a9fb51170 file in the msq is corrupt.   There are several thousand extra lines of stuff after the closing '</Controller>' which is causing the XML parser to bail.   I've updated the code to display a better error message (with the filename in it), and continue with the files that CAN be read.   It thus won't crash.   However, to get information out of that controller, you will need to fix the file.
