### ISSUE TITLE
[Optionally] Remove Empty "New Timing" Track on Imports

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#2640]
**Is your feature request related to a problem? Please describe.**
Feature

**Describe the solution you'd like**
Remove the "New Timing" track when importing sequences as I can only assume that 99% of the people importing sequences never use it and never remove it from their sequence view.  Maybe make this an option in the import screen that has a default that can be defined in the xLights preferences.

**Describe alternatives you've considered**
Right click and delete.

**Additional context**

**Comment by keithsw1111** [comment]
Adding it as an option will use more real-estate on the import dialog which i am not keen on doing for something so trivial.

That said removing it in the following circumstances does make sense.

1. The only timing track is New Timing
2. There are no timing marks on it
3. At least one timing track is being imported.

**Comment by MrPaulAR** [comment]
I'm good with that too.
