### ISSUE TITLE
Photo of model not updating in 'Download' model dialog

### ISSUE THREAD

**Issue by OnlineDynamic** [smeighan/xLights#2641]
**Describe the bug**
When selecting models from the tree view navigation - on the right side the info section at the bottom of the Item tab correctly reflects the selected model but the image (photo of the model) often stays on previously selected model

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to Download model
2. Click on any moddelin the left tree view
3. See error of image not upadting aas youu move between models

**Expected behavior**
Expect image to reflect selected model and show a placeholder if an image isn't available for  that model

**Screenshots**
Attached - showing 'POlice Shield'model slected but image of Maltese Cross

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.15

**Additional context**

**Attachments**
![Capture](https://user-images.githubusercontent.com/68251154/118378420-b7b4cc80-b5cb-11eb-82ab-3d26ec18c307.JPG)

**Comment by keithsw1111** [comment]
So the root cause is the vendor model image files are missing ... you can see this by going into the log file and looking for downloads like https://cdn.shopify.com/s/files/1/0165/4439/9424/products/monster-face-4-pack-22-inch-pixel-props-771_500x.jpg?v=1610317118 which when you click on it return a 404.

**Comment by keithsw1111** [comment]
In the next version it will remove the old image which is all we can do. Speak to your vendor about their missing images as they control them.
