### ISSUE TITLE
Default FSEQ Type for FPP connect

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#2643]
When uploading a sequence using FPP connect, the default type appears to be V2 Sparse.  I think this should be set to V2 for E131 controllers instead (Kulp or other Cap/Hat connected directly to the FPP would stay as V2 Sparse).

The reason for this is if a E131 controller or controllers are connected to the FPP, the V2 Spare file does not always seem to work correctly, and users have to know to change to V2 to make it work.  The reason that I think is the problem is that xlights doesn't know what is connected to the FPP to be able to make the sparse file.  For example, if I have a FPP with 2 E131 controllers connected to it, and another FPP with 3 E131 controllers connected to it, there is nothing in xlights to designate which controllers are connected to which FPP.  The exception to this is if proxies are being used.  But if a static route is set up, xlights doesn't know anything about the setup... and because of that, the sparse file is either the same as the V2 or does not seem to work correctly.  Defaulting it file type to V2, for E131 controllers will make it work better for everyone.  If they feel as if they can benefit from the sparse file, they can choose to change to that.

**Comment by darylc** [comment]
Given xLights has no idea what E1.31 controllers live behind any particular FPP, either all FPP's should receive V2 fseq files by default... or the v2 sparse files should always contain all channels that xLights can't accurately triangulate to a specific FPP instance (eg the ones known via capes/hats etc).

The current defaults break FPP in a lot of configurations.  Eg the simplest configuration 1 FPP with 1 E1.31 controller, both on the same LAN as the xLights computer)

**Comment by dkulp** [comment]
I completely disagree.   It should ALWAYS be V2 Sparse for all uploads to FPP.    When uploading, it will upload the channel ranges that that particular FPP instance is configured to output.   If that FPP instance is not configured to output a particular range, then it will not get that range of channels.   If a user goes and then reconfigures FPP to output additional ranges, then they need to re-upload the sequences to include the additional ranges.    This is working as designed.

**Comment by darylc** [comment]
@dkulp  Thanks for closing this without trying to understand what is broken.

We are both saying that we are OK with V2 sparse mode as default but _only_ if the sparse fseq contains the channels that the FPP needs to put out via the E1.31 controllers.  It does not do this today, but xLights has no idea that I have an E1.31 controller that my FPP needs to output to.  What are we missing here?

**Comment by darylc** [comment]
@dkulp Maybe there is a bug in sparse mode? When you select UDP outputs to be uploaded, surely the spares FSEQ should contain the channels that output (it doesn't)

**Comment by dkulp** [comment]
> @dkulp Thanks for closing this without trying to understand what is broken.
> 
> We are both saying that we are OK with V2 sparse mode as default but _only_ if the sparse fseq contains the channels that the FPP needs to put out via the E1.31 controllers. It does not do this today, but xLights has no idea that I have an E1.31 controller that my FPP needs to output to. What are we missing here?

As far as I can tell, it IS doing it today.   Any channel ranges that are configured on the e1.31 outputs page in FPP are included in the sparse ranges (providing the e1.31 output is enabled and fppd restarted) when the fseq file is uploaded.   But in any case, if there is a case where it's not, a bug should PROPERLY logged completely describing how to reproduce the issue including attaching sequences and/or configurations so that it can be reproduced and fixed.   This issue is logged not as a bug but as a feature request to change defaults, not fix a bug.   The defaults are correct as designed which is why the issue is closed.

**Comment by TrekErs** [comment]
This sounds like a chicken and the egg problem. Unless the user first manually configures the E1.31 outputs, fpp connect has no way of knowing how to accurately generate the sparse file. Most people rely upon FPP connect to configure the device, so now we are back to how do we tell xlights which controllers a specific instance of FPP should output UDP to when a proxy isn’t used.  Maybe the UDP drop down could also list all controllers that are configured as Active?  The user would then have the option to select one or more of the controllers in addition to the All or Proxied options.

I think this will become more of an issue as people grow their display and buy a mix of controllers, some using Master/Remote and some used  E1.31 or similar.
