### ISSUE TITLE
FPP V2 Sparse files with E131 controllers.

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#2645]
**Describe the bug**
This is a more detailed follow up to issue #2643 I submitted yesterday.  

When using a V2 Sparse file in FPP connect, the sparse file is based on the current FPP Channel Output settings.  If nothing is set up in FPP (in a new install for example), the Sparse file is set for no channels being output and does not play correctly.  The channel outputs need to first be configured for the sparse file to be made correctly.  This is commonly done by using the UDP out and setting to all on FPP connect.  However, if someone has multiple controllers connected to a single FPP, or are using multiple FPPs, there is no way for xlights to know which controller is connected to which FPP (at least if static routing is used).   So once the FPP connect is done with UDP set to all, the Channel Output for all FPPs will be set to output to all controllers.  This will work, but is not desired, since the FPPs are outputting to controllers not connected to them.  Furthermore, on future FPP connects, the V2 spare file will be identical to the V2 file, as all channels are being used, and thereby isn't reducing the file size as desired. 

**To Reproduce**
A PDF of some testing with the uploads is attached with screenshots.  The FSEQ files for each of the 3 tests show on there are attached as well.

**Expected behavior**
There seems to be 2 intertwined issues here.  

The first is that the FPP Connect V2 sparse file uses the Channel Output of the current state of the FPP.  It seems that the sparse file should be based on the configuration of the FPP after the FPP connect (with UDP set to all) makes any changes.  Otherwise it is sending a file that is not going to be valid for the setup it is configuring.

The second is that xlights does not have any way to know which controller is connected to which FPP is using static routes.  Without knowing this, it's not possible to fully configure a E131 device using FPP connect.

What this means is that in order to get a usable configuration on the FPP, a user has to do the following:

1. Do a FPP Connect with UDP set to All, but not upload a FSEQ file.
2. Manually uncheck any E131 devices not connected to each of the FPP device they are using, and save that configuration.
3. Do another FPP connect with UDP set to none, and then upload the FSEQ file. 

If any changes are done to the layout or channels, all 3 steps must be done again.  This is not intuitive, and is the reason for confusion with many users.  It seems that FPP connect should be able to know what the channel outputs should changing to and sending only files that have enough information to be able to play that in a single FPP connect.

A simple short term work around to this is to have the FSEQ file type be V2 rather than V2 sparse by default for E131 controllers connected to a FPP, or to only allow the V2 file type if UDP is set to all, so that all channel information is present.  If UDP is set to none, then the sparse file can be used as is.  
[Upload FSEQ.zip](https://github.com/smeighan/xLights/files/6490568/Upload.FSEQ.zip)
[FSEQ V2 Sparse Problem Doc.pdf](https://github.com/smeighan/xLights/files/6490572/FSEQ.V2.Sparse.Problem.Doc.pdf)

**Comment by darylc** [comment]
Thank you very much @dkulp
