### ISSUE TITLE
Channel mapping enhancement

### ISSUE THREAD

**Issue by Xenialights** [smeighan/xLights#265]
When importing a sequence and mapping channels, it would be nice if when a new channel is opened the pull down menu would either default to the last channel chosen or the last channel chosen plus one.  This would be much quicker than having the drop down channel menu reverting to channel 1 and then having to scroll down to the channel needed each selection.

**Comment by dkulp** [comment]
FYI and a quick note:  this is exactly how it works on the Mac.  Not sure on Windows.

**Comment by Xenialights** [comment]
In windows 7 & 8, the drop down menu always goes back to the first channel.

**Comment by MrChristmas2000** [comment]
That is correct that is how it works in windows, except if you have already selected an item like the wrong channel and you reselect it the list will  point back to where the current selection is.

**Comment by AzGilrock** [comment]
I believe with the new Import dialog this is no longer an issue.  You can now drag and drop items from another pane so there is no scrolling through items.
