### ISSUE TITLE
Default Port Brightness option on FPP controller type

### ISSUE THREAD

**Issue by OnlineDynamic** [smeighan/xLights#2654]
**Is your feature request related to a problem? Please describe.**
Not able to set default brightness for all ports on an FPP based controller (in my case a PI with ESPArtstick hat running FPP) in the same way I can for my F16v3

**Describe the solution you'd like**
Have an option to set "Default port brightness" on FPP controllers the same as currently exists for F16v3's so that the config is pushed to FPP when you "Upload Output" from xlights to FPP

**Describe alternatives you've considered**
Have to manually change port brightness on each out in FPP

**Additional context**

**Comment by computergeek1507** [comment]
You can set the brightness for each model in xLights and it will be uploaded to FPP. There is a bulk edit option in the layout tab to make this easier. The Upload code is a little different for FPP that the Falcon, but this could be added as well.

**Comment by computergeek1507** [comment]
added with https://github.com/smeighan/xLights/commit/13838de96ca390ee656cddca8b4c06292880759d
