### ISSUE TITLE
FPP Connect can sometimes hang

### ISSUE THREAD

**Issue by TrekErs** [smeighan/xLights#2656]
FPP Connect will hang when uploading if an offline FPP instance exists.

Perform an FPP Connect, check the upload option for an active FPP instance, uncheck upload for offline FPP instances that appear.  FPP Connect hangs and xLights must be force closed.

Program should not become un responsive and require a force close.

![xLights Controllers](https://user-images.githubusercontent.com/77506588/118754783-8d0d8280-b81c-11eb-8570-d693e1022acf.JPG)
![InkedFPP Connect_LI](https://user-images.githubusercontent.com/77506588/118754805-9565bd80-b81c-11eb-8977-7843605a7578.jpg)
![FPP Connect Not Responding](https://user-images.githubusercontent.com/77506588/118754810-9860ae00-b81c-11eb-9b44-cb42fc1ec280.JPG)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.16

Last lines of xLights_l4cpp.log
2021-05-18 21:00:02,843 25468 log_base [INFO] FPPConnect GET http://10.0.0.5/fppjson.php?command=getSysInfo&simple  - Return: 28 - RC: 0  - 
2021-05-18 21:00:12,845 25468 log_base [INFO] FPPConnect GET http://10.0.0.5/fppjson.php?command=getSysInfo&simple  - Return: 28 - RC: 0  - 

Log updates every 10 seconds, note time stamp

**Comment by derwin12** [comment]
Close this?
