### ISSUE TITLE
Shaders - Sliders for floats and point2Ds non functional

### ISSUE THREAD

**Issue by Old-Salt** [smeighan/xLights#2658]
**Describe the bug**
Any Sliders for floats and point2Ds defined within a shader are non functional
Sliders for floats and point2Ds defined by xLights are functional

**To Reproduce**
1. Load any shader that has a float or point2D input defined in its JSON
2. Move the slider - no change to effect
3. try swirl or hoop dreams I've never touched them

**Expected behavior**
Sliders should work as in previous versions of xLights

**Screenshots**
n/a

**Versions (please complete the following information):**
 - OS: Windows 7
 - xLights version 2021.17

**Additional context**
n/a

**Attachments**
n/a

**Comment by computergeek1507** [comment]
fixed with 5c06b6d9f4daba52c00c0e25e8302397b8ec2db7
