### ISSUE TITLE
SAVE AS

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#266]
Using the new version of OSX 4.1.13 I am in the process of building up sequences.

As I make changes I like things, I would like to SAVE AS the sequence and configuration as the current state so I may close Xlights, and open that sequence where I was if I make a huge mistake (beyond the level of UNDO's) :)

I could use this to make smaller shows, and if those are acceptable, save them as their own name, and they would play fine.

Later I come back to it, add more elements and save that sequence as a new name referencing the new elements. 

So on and so forth.

Possible?
Thx

Ben

**Comment by AzGilrock** [comment]
That's the purpose of the backup feature.

**Comment by smeighan** [comment]
i agree with gil, there is a way to achieve this now. When you press F10 every xml file is backed up.
xlights_rgbeffects.xml has your models
xlights_networks.xml has teh content of your SETUP
every xml file is store in the backup subdirectory under YYYY-MM-DD-HH-MM-SS
so you can have 86,400 copies per day.

Just press F10 as you go along, it only takes a few seconds.

we have no automated way to restore from teh backups. just go into the directory under Backup and compy your file (like wizards.xml) go back up two directories to your show directory and paste. This restores from the Backup.

**Comment by LightsOnHudson** [comment]
Thank you, I did not associate Backup with this request. However; thank you for adding it as an enhancement for the future so you can have control of the Sequence name much like a document as you are saving it as you are going along and can reference that point in time. I will use this alternative method to get started.

**Comment by AzGilrock** [comment]
There is no enhancement that will be done.  If you want to save to a new name then use Save As.  If you want to save it along with your model and channel setup then use Backup.

**Comment by LightsOnHudson** [comment]
Hi Gil, Help me locate the Save As that you mention? I do not have that in the latest OSX 4.1.4 File Menu. See attachment. Are you referring to saving the file, then going into the Folder structure and renaming it there? 

![screen shot 2015-06-12 at 8 51 36 am](https://cloud.githubusercontent.com/assets/10136122/8132642/5fa0aa28-10e0-11e5-846f-50379d1305ae.png)

**Comment by AzGilrock** [comment]
There is a Save As button on the toolbar beside the save button.  I'm used to using the toolbars.  We should probably add it to the File menu also.

**Comment by LightsOnHudson** [comment]
Thanks Gil.
