### ISSUE TITLE
"Invalid" characters in State definition

### ISSUE THREAD

**Issue by bacarudaguy** [smeighan/xLights#2660]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When creating states on a moving head model, a capital letter gives the attached error of an invalid character... unable to combine character cases in the state name (I get not having spaces, but capitalization shouldn't matter)

**To Reproduce**
Create moving head model, open state definition window, name a new state, check force custom colors, create a new state with a capital letter (ie: Lampon) and attached error happens. Also unable to mix cases (ie: LampOn)

**Expected behavior**
Should be able to name states with mixed letter case, or even begin a state with a capital letter... 

**Screenshots**
Attached... 

**Versions (please complete the following information):**
OSX 10.15.3 - XLights 2021.17
<img width="421" alt="Screen Shot 2021-05-24 at 9 02 15 PM" src="https://user-images.githubusercontent.com/1183946/119424680-e883b880-bcd3-11eb-8322-cf3c7287f43a.png">

**Comment by keithsw1111** [comment]
I dont think this is a bug. Forcing lower case allows the state effect to force the timing track also to lower reducing case mismatches resulting in states not working. I dont think the advantage of mixed case outweighs that.

**Comment by bacarudaguy** [comment]
Hey Keith - I definitely see the logic in preventing user created issues of mixed case and such... any thoughts on allowing a couple special characters such as dashes (-) to help break up words?

**Comment by keithsw1111** [comment]
From the code the valid characters are: abcdefghijklmnopqrstuvwxyz0123456789-_/\|#

That seems to me like a perfectly reasonable range of characters.

**Comment by bacarudaguy** [comment]
That seems like a fair list to me... thank you for the reply and the character info! :) I'll close this out...
