### ISSUE TITLE
Unable to assign model to controller:universe

### ISSUE THREAD

**Issue by cowboyjeeper** [smeighan/xLights#2661]
When I'm assigning models I can assign it by !controller:channel or by many other options but it would be very useful if it would allow me to assign by controller:universe

Much easier than me having to calculate my universe # 8 starts at channel 3571

ie instead of

!controller_a:3571

I could do something like

~controller_a:8

**Comment by computergeek1507** [comment]
This already exists if you select use start channel, you can select the IP address and universe. 

https://manual.xlights.org/xlights/chapters/chapter-four-tabs/models/model-attribute/changing-start-chanel#manually-changing-start-chanel
