### ISSUE TITLE
star layer render style on imported props

### ISSUE THREAD

**Issue by arnoldsq** [smeighan/xLights#2665]
I have Boscoyo ChromaStar 36 6 ring and 46 6 ring in my show.  I am attempting to import a show I purchased from inspire light shows.  He uses the layer star render effect on a lot of effects and That is not available on my stars.  Is it possible to to get this added to the imported stars?

**Comment by keithsw1111** [comment]
Layer star is available on the inbuilt star model only. If you are not using the inbuilt model for your star then you will either change the model or just do with out those effects.
