### ISSUE TITLE
Custom model with Node Single Color gives no output

### ISSUE THREAD

**Issue by myhrmans** [smeighan/xLights#2666]
Creating a custom model in xLights and then setting it to Node Single Color does not change the amount of channels it takes up, neither does it give any output in the model preview or to the connected lights on the specified port.

To reproduce simply create a sequence with a custom model of any sort with a few nodes. 
Set the **_String Type_** to **_Node Single Color_**. Apply any effect on the custom model. 
Nothing will be sent to the model. 
Neither in Model Preview, or to the real lights.

- OS: Windows 10.
 - xLights version 2021.15
 
Sequence + Layout:
https://www.dropbox.com/s/7284g6bcfq99kai/xlights_demo_bug.zip

**Comment by deplanche** [comment]
The "Node Single Color" is a very uncommon string type.  Are you sure that you don't want it to be "Single Color" instead?

**Comment by myhrmans** [comment]
@deplanche No. The reason for using Node Single Color is since I have custom led strips with 3 white LEDs connected to the ws2811.
