### ISSUE TITLE
Controller Connections Shows different options for Same Type of Controller

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#2667]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Controller Connections Shows different options for Same Type of Controller (San Device E6804) for different model using same controller

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to Layout Tab
2. Click on "Arch 1" 
3. Expand "Controller Connection"
4. Arch 1 has more options than if you repeat the above steps for any other Arch (and any other Model Controlled by a San Device...in particular Arch 1 has a "Set Brightness" option.

**Expected behavior**
Same Options for all models

**Screenshots**
See Attached Screenshots

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.18
 - 
**Additional context**

**Attachments**
No Crash log
![Arch 1](https://user-images.githubusercontent.com/13740582/120959362-72894380-c70e-11eb-8044-69dee2102c45.jpg)
![Arch 5](https://user-images.githubusercontent.com/13740582/120959373-774df780-c70e-11eb-9983-6db684403d26.jpg)

[Rudolph the Red-Nosed Reindeer - Gene Autry.zip](https://github.com/smeighan/xLights/files/6605861/Rudolph.the.Red-Nosed.Reindeer.-.Gene.Autry.zip)

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
Thanks for finding this, fixed with with 42df41a31634ac9eb7c699e9aa030d1bcb7b6919

**Comment by jimswinder** [comment]
Thanks for fixing it!!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: "Scott H." ***@***.***>
Date: 6/7/21 6:38 AM (GMT-08:00)
To: smeighan/xLights ***@***.***>
Cc: jimswinder ***@***.***>, Author ***@***.***>
Subject: Re: [smeighan/xLights] Controller Connections Shows different options for Same Type of Controller (#2667)


Thanks for finding this, fixed with 42df41a<https://github.com/smeighan/xLights/commit/42df41a31634ac9eb7c699e9aa030d1bcb7b6919>
