### ISSUE TITLE
WLED added twice to xScanner device type detection

### ISSUE THREAD

**Issue by BryceDFisher** [smeighan/xLights#2668]
WLED added twice to device type detection in xScanner.

https://github.com/smeighan/xLights/blob/42df41a31634ac9eb7c699e9aa030d1bcb7b6919/xScanner/Scanner.cpp#L728
https://github.com/smeighan/xLights/blob/42df41a31634ac9eb7c699e9aa030d1bcb7b6919/xScanner/Scanner.cpp#L733

**Comment by computergeek1507** [comment]
Fixed a84938bd8e8606448dd56654c6c29dd2a6279bd2
