### ISSUE TITLE
HLS Importing getting Handler exceptions then crashes

### ISSUE THREAD

**Issue by tucsonlights** [smeighan/xLights#267]
I am trying to import my sequences from HLS into a sequence in Xlights. I can import the small stuff like Dumb rgb strands and RGB floods. When I try to import 47 pixel window frames I get a Handler Exception and the option to ignore, abort, retry. I have tried all of them and then xlights hangs or crashes. I am running Win 8.1 64bit.

**Comment by tucsonlights** [comment]
I used effects imported from xlights 3 and dropped them on the pixel planes in HLS. I don't know if that is the problem.

**Comment by tucsonlights** [comment]
Log Name:      Application
Source:        Application Error
Date:          6/13/2015 3:58:56 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      SeanMSI
Description:
Faulting application name: xLights.exe, version: 0.0.0.0, time stamp: 0x5577cae7
Faulting module name: ntdll.dll, version: 6.3.9600.17736, time stamp: 0x550f42c2
Exception code: 0xc0000005
Fault offset: 0x0004102e
Faulting process id: 0x1cec
Faulting application start time: 0x01d0a62b3647a853
Faulting application path: C:\Program Files (x86)\xLights\xLights.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: c4a788e9-121f-11e5-826d-1008b160f90e
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-06-13T22:58:56.000000000Z" />
    <EventRecordID>3178</EventRecordID>
    <Channel>Application</Channel>
    <Computer>SeanMSI</Computer>
    <Security />
  </System>
  <EventData>
    <Data>xLights.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5577cae7</Data>
    <Data>ntdll.dll</Data>
    <Data>6.3.9600.17736</Data>
    <Data>550f42c2</Data>
    <Data>c0000005</Data>
    <Data>0004102e</Data>
    <Data>1cec</Data>
    <Data>01d0a62b3647a853</Data>
    <Data>C:\Program Files (x86)\xLights\xLights.exe</Data>
    <Data>C:\Windows\SYSTEM32\ntdll.dll</Data>
    <Data>c4a788e9-121f-11e5-826d-1008b160f90e</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by tucsonlights** [comment]
Here is the Dropbox links for my files.
https://www.dropbox.com/sh/lnueopt719kxznl/AACU4c9RmAZ0YPi8HoasXvsDa?dl=0
https://www.dropbox.com/s/sghz4rz1phbtd5z/CAROLOFTHEBELLS2015.fseq?dl=0
https://www.dropbox.com/s/rsylg27p94srvx0/CAROLOFTHEBELLS2015.xml?dl=0

**Comment by stevegiron** [comment]
Hi, is this still an open issue for you? If not can you please close the issue. Thanks.
