### ISSUE TITLE
Twinkle error / issue

### ISSUE THREAD

**Issue by greggvelez** [smeighan/xLights#2674]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When using the Twinkle effect with a .5 in transition and New Rendering Method option, sometimes there's a error that causes all of tthe lights to turn on during the transition time period before rendering the effect correctly.  It's difficult to reproduce, but I think if you exit out of xlights then open and reload the sequence, it's more likely to reproduce.

**To Reproduce**
See above.

**Expected behavior**
The Twinkle should work normally right away, regardless of transition in.

**Screenshots**
N/A

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.18

**Additional context**
N/A

**Attachments**
N/A

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
Can you attach a sample sequence with just that effect so we can see it?

**Comment by greggvelez** [comment]
Thanks for asking!  This sequence I've attached has three instances of it
at 4:32, 14:13 and 21:00.

Gregg

**Comment by keithsw1111** [comment]
Not much I can do with that. Can you use tools package sequence and post that zip file. This one is missing a whole bunch of stuff necessary to reproduce the problem.

**Comment by greggvelez** [comment]
Sorry about that.  Uploading what you need now and I'll DM the link when finished.  Thx

Gregg

**Comment by keithsw1111** [comment]
So the sequence you uploaded is unique to say the least. I dont know how you got it into that state but you have hundreds if not thousands of effects on nodes. If i were you I would create a new sequence and then import from this sequence but only map the key models. That way you can drop out a lot of the junk which is likely where your problem is.

**Comment by AzGilrock** [comment]
This should be fixed for next release

**Comment by greggvelez** [comment]
Niiiiice!  Thank you!  I kinda figured you would be working it after seeing
other people posting about similar problems.  So I haven't altered my
sequence yet.  You all are the best!  Time for a donation!

Gregg

**Comment by greggvelez** [comment]
Awesome job fixing the Twinkle bug in the 2021.25 release!  Works perfectly
for me now.  Thank you!  I donated!

Gregg
