### ISSUE TITLE
Display Element Additional Sort View

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#2676]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
In the display elements I'm asking for an additional sort option that would/could be applied to any non-master views that would allow the view to be sorted based on the master view.  

My example would be my snowflakes.  If I create a new view for them based on the alphabetical sorting it will put the "snowflakes" group below any groups with sub-models.  I understand that the render order is solely based upon the master view but it would be helpful if I could quickly sort any other views to match that of the master view when I'm looking at the sequencer window.

I would like a new menu under sort called "same as master".

**Describe alternatives you've considered**
Clone the master view and then remove items I don't plan on using.  I see some downsides.
* If I change the master view later I need to remember to go back and update this other view
* I'm lazy and I would need to remove 80% of my items to reduce the view to just, for example, snowflakes

**Additional context**

**Comment by keithsw1111** [comment]
You do understand that this would be a point in time match. Given master views are sequence specific as soon as you open another sequence they would be 'out of order' again.
