### ISSUE TITLE
Art-Net 4 Node's : Mismatch IP

### ISSUE THREAD

**Issue by vanvught** [smeighan/xLights#2678]
**Describe the bug**
It is not possible to work with multiple Art-Net 4 Node's with the factory settings.

**To Reproduce**
Use multiple Art-Net 4 Node's from the same vendor with factory settings.

**Expected behavior**
Show all Art-Net 4 Node's without error.

**Screenshots**
![Schermafbeelding 2021-06-18 om 19 36 19](https://user-images.githubusercontent.com/4319913/122598421-19ee6a80-d06d-11eb-987c-155a63a67e75.png)

**Versions (please complete the following information):**
 - OS: MacOS 11.4
 - xLights version 2021.19

**Additional context**
As reference DMX Workshop where both Art-Net 4 Node's are shown.
![Schermafbeelding 2021-06-18 om 19 42 21](https://user-images.githubusercontent.com/4319913/122598659-6a65c800-d06d-11eb-959d-dcdb2c5edfe3.png)

**Comment by keithsw1111** [comment]
This is expected behaviour ... if it is a new device you would click no and xLights would add the device. Doesnt it work that way?

**Comment by vanvught** [comment]
This defect seems related to the issue where xLights can only handle a single ArtPollReply -> https://github.com/smeighan/xLights/issues/2680#issuecomment-869497187

**Comment by keithsw1111** [comment]
Yep ... but if they return the same name then we cant be sure if the name is a duplicate or the ip address just changed. We dont want to add things if the ip changed ... we would prefer to change the ip so that is how it works. Ideally controllers would generate unique default names,

**Comment by vanvught** [comment]
> Yep ... but if they return the same name

They have different Art-Net Long Names. There are unique ArtPollReply's -> expected behavior is that both Art-Net 4 Node's are listed.

**Comment by keithsw1111** [comment]
Can you attach the contents of the artpollreplies

**Comment by keithsw1111** [comment]
Also shouldnt you be an input ... you receive data?

**Comment by keithsw1111** [comment]
Actually it is really confusing. On output line it says transmit but then source:artnet
But on input it says receiving data but dest in artnet.
I am sure there is a logic to it but i dont get it and the spec glossary does not help.

**Comment by vanvught** [comment]
> Also shouldnt you be an input ... you receive data?

No. See the Art-Net 4 specification -> https://artisticlicence.com/WebSiteMaster/User%20Guides/art-net.pdf

**Comment by keithsw1111** [comment]
With the last release all the artnet changes are in ... is this still a problem.

**Comment by vanvught** [comment]
Just dowloaded the latest version form the Apple App Store. Still the same issue.

![Schermafbeelding 2021-07-17 om 19 50 40](https://user-images.githubusercontent.com/4319913/126045842-2090c395-9f74-4eb1-97f0-691103b333e2.png)

```
2021-07-17 19:57:46,757 4697689600 log_base [INFO] ******* OnInit: XLights started.
2021-07-17 19:57:48,048 4697689600 log_base [INFO] Version: 2021.21 - App Store
2021-07-17 19:57:48,048 4697689600 log_base [INFO] Bits: 64bit
2021-07-17 19:57:48,048 4697689600 log_base [INFO] Build Date: July 11, 2021
2021-07-17 19:57:48,048 4697689600 log_base [INFO] WX Version: wxWidgets 3.1.6
```

As reference the DMX Workshop:

![Schermafbeelding 2021-07-17 om 19 54 25](https://user-images.githubusercontent.com/4319913/126045881-de0021c1-3fd8-4f58-8525-bf96f679fdd2.png)


And the sample configuration manager:

![Schermafbeelding 2021-07-17 om 19 52 56](https://user-images.githubusercontent.com/4319913/126045892-ec55dacc-0316-4eab-b248-cd2db252146a.png)

**Comment by keithsw1111** [comment]
So you have 2 controllers with the same name on different IP addresses ... this would be expected behaviour.

**Comment by vanvught** [comment]
> So you have 2 controllers with the same name on different IP addresses ...

There can be multiple Art-Net 4 controllers with the same long name or short name.

>  this would be expected behaviour.

A special implementation for xLights. And a limitation when using Art-Net 4 node's.

Will this issue be fixed?

**Comment by vanvught** [comment]
As reference the expected behaviour.

![Schermafbeelding 2021-07-18 om 08 21 14](https://user-images.githubusercontent.com/4319913/126057810-64e2c819-dab8-47b1-937f-0390b2e30964.png)

![Schermafbeelding 2021-07-18 om 08 19 42](https://user-images.githubusercontent.com/4319913/126057813-79182345-e692-4777-94ed-2f2a5e5e2bdf.png)

**Comment by dkulp** [comment]
No.  This will not be fixed as it's not a bug and working as designed.   If you have two nodes with the same name on different IP addresses, expect the message.   If the controller cannot have a proper name set, we don't recommend using that controller with xLights.

**Comment by vanvught** [comment]
>  it's not a bug and working as designed. 

Having multiple Node's with the same short name or long name is normal behavior.

This limitation of xLights should be mentioned in the documentation. And then it could be advised, in order to be xLights compatible; make sure the Art-Net 4 controller's have different long names or different short names. 

Otherwise xLights cannot work with Art-Net 4 Node's.

**Comment by dkulp** [comment]
xLights can work fine with them, just not discover them individually.
