### ISSUE TITLE
Art-Net 4 Node's : Not showing the vendor from ESTA code 

### ISSUE THREAD

**Issue by vanvught** [smeighan/xLights#2679]
**Describe the bug**
The Vendor field is empty.

**To Reproduce**
Use any Art-Net 4 Node from https://github.com/vanvught/rpidmx512
This can be the Orange Pi firmware or any Linux/MacOS test Art-Net 4 Node.

**Expected behavior**
When there is an ESTA code provided, then show the Vendor

**Screenshots**
![Schermafbeelding 2021-06-18 om 19 49 29](https://user-images.githubusercontent.com/4319913/122599293-67b7a280-d06e-11eb-8c44-fb6e38487198.png)

**Versions (please complete the following information):**
- OS: MacOS 11.4
- xLights version 2021.19

**Additional context**
Showing Wireshark which recognizes the ESTA code.
![Schermafbeelding 2021-06-18 om 19 51 13](https://user-images.githubusercontent.com/4319913/122599435-a9484d80-d06e-11eb-8662-4925cd006aec.png)

**Comment by computergeek1507** [comment]
The vender field is only populated if the controller discovered is one of the predefined controllers in xLights.

**Comment by keithsw1111** [comment]
This is not how the vendor field is meant to work.
