### ISSUE TITLE
Art-Net 4 Node's : Not showing all Universes

### ISSUE THREAD

**Issue by vanvught** [smeighan/xLights#2680]
**Describe the bug**
There is just a single with one Universe while the Art-Net 4 Node has 5 Universes

**To Reproduce**
Use an Art-Net 4 Node with more than 1 Universe

**Expected behavior**
Show all Universes from the Art-Net 4 Node

**Screenshots**
![Schermafbeelding 2021-06-18 om 19 55 19](https://user-images.githubusercontent.com/4319913/122600118-9da95680-d06f-11eb-8fe0-b650a9d8f43d.png)

**Log**

```
021-06-18 19:25:20,594 4448222720 log_base [DEBUG] Running controller discovery.
2021-06-18 19:25:20,596 4448222720 log_base [INFO] ZCPP sending discovery packet.
2021-06-18 19:25:20,606 4448222720 log_base [INFO] ArtNet Discovery strange packet received.
2021-06-18 19:25:20,612 4448222720 log_base [INFO] ArtNet Discovery strange packet received.
2021-06-18 19:25:20,627 4448222720 log_base [INFO] ArtNet Discovery strange packet received.
2021-06-18 19:25:20,636 4448222720 log_base [INFO] ArtNet Discovery strange packet received.

```
**Versions (please complete the following information):**
-OS: MacOS 11.4
- xLights version 2021.19

**Additional context**
Showing DMX Workshop where all 5 DMX Ports are listed with their Universe
![Schermafbeelding 2021-06-18 om 19 55 51](https://user-images.githubusercontent.com/4319913/122600256-cd585e80-d06f-11eb-8b01-dc6eb5f48e7c.png)

**Comment by computergeek1507** [comment]
Are you using The Discovery Button or manually adding the Artnet Controller Output in xLights?

**Comment by vanvught** [comment]
> Are you using The Discovery Button or manually adding the Artnet Controller Output in xLights?

I am using the Discovery button.

**Comment by keithsw1111** [comment]
I dont think you are supposed to return 5 discovery packets for one device. xLights expects only the one. Its up to the user then to change the number of universes. I dont say this confidently from a Artnet spec perspective but the only device I have ever seen that sends a response is the F16V3 and it returns one so that is all xLights currently handles. If you can point me to the part of the spec that shows what you are doing is right I would be happy to update the implementation.

**Comment by vanvught** [comment]
@keithsw1111 
>  If you can point me to the part of the spec that shows what you are doing is right I would be happy to update the implementation.

Per Art-Net 4 specification there is an ArtPollReply per 4 ports or even per Universe. So a 8 ports 4x Universe pixel controller can send 8 ArtPollReply's or 32 ArtPollReply's.

[https://art-net.org.uk/faq/nodes-with-4-ports/](https://art-net.org.uk/faq/nodes-with-4-ports/)

**Comment by vanvught** [comment]
@keithsw1111

>If you can point me to the part of the spec that shows what you are doing is right I would be happy to update the implementation.

It seems that xLight does not understand Art-Net 4 ArtPollReply's. The log is showing.
ArtNet Discovery strange packet received.

Per Art-Net 4 specification there is an ArtPollReply per 4 ports or even per Universe. So a 8 ports 4x Universe pixel controller can send 8 ArtPollReply's or 32 ArtPollReply's.

https://art-net.org.uk/faq/nodes-with-4-ports/

**Comment by vanvught** [comment]
> So a 8 ports 4x Universe pixel controller can send 8 ArtPollReply's or 32 ArtPollReply's.

In the above `8 ports` refers to the physical pixel controller output ports. Each such port has 4 Art-Net ports -> 8 ArtPollReply's or 32 ArtPollReply's.
