### ISSUE TITLE
Tools Test .. deselect all/Many doesnt really clear the choices

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2683]
Not sure if this was intended behavior or not...
On Models tab, select a number of nodes. Right click, Deselect All, then try and select a new one .. and the other selections get turned back on again. Cant seem to find a way to clear them..other then one at a time.

**Comment by computergeek1507** [comment]
It would be helpful if you included more information. Layout/Networks Files? A video of what you are doing. Please use the issues template in github and fill it out.

**Comment by derwin12** [comment]
https://user-images.githubusercontent.com/4643499/122824585-dd11b600-d2ae-11eb-8233-6806c662348b.mp4

Nothing fancy .. think this shows you what I am seeing .. Deselect ALL or Many, the next click and they all come back checked again.

PiCap In this case.
