### ISSUE TITLE
Crashes xLights when clicking effects assist window in morph

### ISSUE THREAD

**Issue by KevynChambers** [smeighan/xLights#2685]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When clicking on Effects Assist window in Morph Effect immediately shuts the program and exits

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to a sequence
2. Click on morph effect
3. Click on Effect Assist window grid
4. Shuts program and exits

**Expected behavior**
To be able to use the window to set X,Y co-ordinates

**Screenshots**

**Versions (please complete the following information):**
 - OS: Linux version only?
 - xLights version 2021.18

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
I cant reproduce it. I added a matrix. dropped a morph on it and then clicked on effect assist and i got no crash.

It may be layout specific. Can you attach a sequence with your layout and one morph effect on a model that demonstrates the problem.

**Comment by KevynChambers** [comment]
Hi, thanks for getting back to me, ok I will try and do that. I also found
this weekend that it also crashes when I try to adjust string numbers on
some new Spinarchys I've just added? It generated a report which I will try
and locate and send to you? PCs aren't my forte so bear with me!!

Regards Kevyn.

**Comment by KevynChambers** [comment]
Hi Keith,

So I've just made this crash report from trying to alter the string number
on a spinarchy, I hope this is the right thing? I will work on getting a
layout and sequence to you as soon as poss!!

Regards Kevyn

**Comment by keithsw1111** [comment]
Which crash report?

**Comment by keithsw1111** [comment]
I still dont see an attached crash report. Likely you tried to send it via email ... but that wont work.

**Comment by KevynChambers** [comment]
Hi Keith,

Firstly may I apologize for my slow replies, computers are not something I
really have a lot of dealings with so I can't navigate them easily! I think
the fault may have been model specific as I've altered my layout now and it
doesn't seem to do it now?

I don't know how any of this works but the Linux version of xLights is
still at 2021.18 and hasn't received any updates regarding the latest
version? Someone else has suggested letting you know in case an Automatic
image builder has failed? Otherwise this program is amazing! Thank you for
all your hard work!

Regards Kevyn.
