### ISSUE TITLE
Importing .zipped/compressed Sequence files appears broken

### ISSUE THREAD

**Issue by PixelPowerUSA** [smeighan/xLights#2694]
After upgrading to .20, when trying to import compressed sequences, it doesn't work. There was a similar issue early on that was fixed. It appears broken again.
![Capture](https://user-images.githubusercontent.com/49037022/123854728-1371b580-d8ed-11eb-8dba-cc9bb2e1a8d9.JPG)

**Comment by computergeek1507** [comment]
Please attach the sequence or specify which sequence you are trying.

**Comment by PixelPowerUSA** [comment]
Any of them, I tried several, old and new.

**Comment by computergeek1507** [comment]
Sam Rob told me it is working now for him. Closing
