### ISSUE TITLE
Long batch of Lyrics will not import

### ISSUE THREAD

**Issue by DoctorWiz** [smeighan/xLights#2697]
I'm trying to import a long batch of lyrics for "The Magical Kingdom of Claus" by Bob Rivers, and when I try to import them, I paste them in and click OK and-- nothing happens.
I tried splitting them into sections, and did successfully import the first 20 lines, but when I tried to do another 20 lines, or even less, again nothing imported.
I went thru the lyrics and removed any characters I thought might be interfering like apostrophes and question marks but that did not solve the problem (and the first 20 lines which did import already had said characters which imported fine)
Lyrics attached.
[Lyrics - TRIMMED The Magical Kingdom of Claus by Bob Rivers.txt](https://github.com/smeighan/xLights/files/6757678/Lyrics.-.TRIMMED.The.Magical.Kingdom.of.Claus.by.Bob.Rivers.txt)
.

**Comment by computergeek1507** [comment]
It worked fine for me. I am using the newest xLights code with Notepad++ on Windows 10. Please provide more information on your computer setup. Thanks.

![Lyric dialog](https://user-images.githubusercontent.com/2293065/124493505-b447f100-dd83-11eb-9535-92f5884d1e9c.gif)

**Comment by DoctorWiz** [comment]
Works for me too now.  Definitely was not a couple days ago (tried multiple times).  Dunno what changed between then and now tho-- nothing that I'm aware of.
Sorry to have wasted your time.  If I reproduce it I will do further troubleshooting and isolation.  Thanks!

**Comment by computergeek1507** [comment]
Issues normally arise when copying text from a website to xLights. Sometimes websites have unsupported characters. The Notepad software will remove these invalid characters. If you got the lyric from a website let me know the link and I will look into it.
