### ISSUE TITLE
Twinkle showing like single lines on my driveway lights

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2698]
Not clear if this is new or an old bug. I have attached the effect sequence. When effect is played on any of my everything type groups, the twinkle renders long lines (many pixels) on the driveway lights. I tried default/per preview/per model etc. Most are set at default so hoping that will just "work". (old and new render methods)
It works on the 2 driveway models fine.

[Bug - twinkle driveways.zip](https://github.com/smeighan/xLights/files/6757685/Bug.-.twinkle.driveways.zip)

**Comment by keithsw1111** [comment]
There is no bug here. Just set the render style to per model default.
