### ISSUE TITLE
Piano effect - piano tops not working for me

### ISSUE THREAD

**Issue by JonB256** [smeighan/xLights#27]
I'm playing on a 40x24 horizontal matrix. The piano tops looks good on screen & matrix (good proportions and shape), but the keys do not visibly change color when playing. 

The equalizer mode is working and looks good (and I'm using it), but the keytop mode is what I'm hoping for.   

Also, getting Red and Green for colors - doesn't seem to care about any color choices I pick. 

Jon

**Comment by smeighan** [comment]
closing all bugs over 6 months old. We will start tracking issues in Xlights 4.0.
