### ISSUE TITLE
Enhancement requests - Repeat section of Waveform

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#270]
If you highlight a section of the  waveform , you can press the space bar to repeat ie replay that section.
However if you click anywhere in the grid (with nodes toggled on , or maybe even otherwise), the highlighted section of the waveform disappears.
The request is to be able to highlight  a section and have it enabled until some specific action (ie with a start line and end line) and also be able to stretch the highlighted section in either direction. You can then keep on playing that section or move either the start or end line to focus on a particular section whilst adding / moving effects on the grid and then play that section again.

**Comment by stevegiron** [comment]
Gil has added this functionality.
