### ISSUE TITLE
Persistant is not cleared after the effect

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2701]
Not sure if this is intended or not. When two single strand effects are next to the other, the prior effect is not cleared.
Single strand, from middle and persistant and then repeat that again.

Note in the sequencer tab, if you just click on the 2nd effect you can see it still has the prior "ends" still visible. If you press play, the entire previous red arches are still visible.

[Bug - persistant.zip](https://github.com/smeighan/xLights/files/6773765/Bug.-.persistant.zip)

**Comment by AzGilrock** [comment]
See discussion in #977 and #518.  Keith said he wouldn't fix it.

**Comment by derwin12** [comment]
Okay so a bit of a bug and a feature. The workaround of moving the effect down a layer works just fine. Thanks for the heads up.

**Comment by AzGilrock** [comment]
Well you never know maybe he feels different now.  That's why I left it open.
