### ISSUE TITLE
Will not download prop without crashing

### ISSUE THREAD

**Issue by WolfeK77** [smeighan/xLights#2702]
[xLights_dbgrpt-18212-20210707T142016.zip](https://github.com/smeighan/xLights/files/6779642/xLights_dbgrpt-18212-20210707T142016.zip)

**Comment by derwin12** [comment]
Try Tools->Purge Download Cache

**Comment by WolfeK77** [comment]
That didn’t fix it


Sent from AT&T Yahoo Mail for iPhone


On Wednesday, July 7, 2021, 5:09 PM, Daryl ***@***.***> wrote:




Try Tools->Purge Download Cache

**Comment by keithsw1111** [comment]
While xLights should not crash there is also a problem with a lot of the GE links being broken. Unfortunately the crash is deep in the bowels of the CURL library we use which makes it really hard to work out why a request that when I test it returns a 404 crashes for some other people.

**Comment by keithsw1111** [comment]
Can you try again in 2021.21 ... I dont think I fixed it but there were some changes made so it may now work.

**Comment by WolfeK77** [comment]
Whatever you did seems to have fixed it. It worked perfectly. 
Thank you!


Sent from AT&T Yahoo Mail for iPhone


On Monday, July 12, 2021, 11:11 PM, Keith Westley ***@***.***> wrote:




Can you try again in 2021.21 ... I dont think I fixed it but there were some changes made so it may now work.
