### ISSUE TITLE
Enhancement request - Waveform scrubbing

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#271]
When scrubbing the waveform , play the sound of the music that corresponds to that section.

**Comment by stevegiron** [comment]
If your sound file is off a few seconds from the scrub line, use Audacity to re-save the file at 192bits with a Constant Bit Rate. The scrub line will match the audio this way.

**Comment by gerry4** [comment]
Hi,
 
What I meant was that if I move the cursor over a part of the waveform -(eg backwards and forwards about 5 cms)  , can it be made to play the sound that corresponds to that  waveform (eg in Papagayo , LSP  etc).
 
Not sure about the exact terminology - LSP calls it scrubbing..
 


Gerard
 
Date: Mon, 15 Jun 2015 08:35:37 -0700

**Comment by stevegiron** [comment]
How you describe it, is how it works for me when I highlight a section of the waveform. It plays when I hit spacebar and repeats when I hit spacebar again and the models play accordingly to the waveform section highlighted.

**Comment by gerry4** [comment]
This is without hitting the spacebar .
 
ie when you click on the waveform and press hard on the cursor and move it back and forward a bit (say one to two cms), the sound plays. 
 
Useful to get exactly the spot u need , to then insert a timing mark or to shift an effect a couple of millimetres etc.

Gerard
 
Date: Mon, 15 Jun 2015 16:35:54 -0700

**Comment by stevegiron** [comment]
Did you know you can zoom in on the waveform by double clicking on the waveform. Keep double clicking until you've got a zoom setting you can use. To zoom out, hold the shift key and double click on the waveform. You'll find a setting where you can SEE the spot you need and won't even have to hear it. You'll be able to see patterns and know exactly where to place a timing mark
