### ISSUE TITLE
Bulk edit of Controller names/ ports not working as expected

### ISSUE THREAD

**Issue by bcarriveau** [smeighan/xLights#2711]
**Describe the bug**
Bulk edit of Controller name/ ports not working as expected.

in addition but may be related, visualizer  is very buggy. at times when trying to drop props in specific spot they wont take, or go to end, then if you move again it will go back to the right by its self. Seems moves are not updating?

**To Reproduce**
Highlight all props in layout, right click, bulk edit, controller name. select different controller, hit ok. Controller change does not happen. This behavior is also with bulk editing controller port numbers

**Expected behavior**
Would move all selected items to controller or port specified under the bulk edit command.

**Versions (please complete the following information):**
 - OS: Windows 10     21H1
 - xLights version 2021.21(up tp date with master) but confirmed with others its an issues on there 2021.21 as well.

**Attachments**
Added image of what remains after trying to bulk everything to a *fake controller

![cont](https://user-images.githubusercontent.com/60801063/126048382-1c06b5af-f552-4cee-9c92-f383565035d7.jpg)

**Comment by bcarriveau** [comment]
While playing more if One bulk edits props to a Port first, and then bulk edits to a controller it seems to take update the controller name but in the visualizer all the props that were bulk edited to the port are not on the port, usually only 1 goes on the port. 

hope this helps any.

**Comment by keithsw1111** [comment]
The visualiser will not show 2 props that overlap ... so editing properties on the layout needs to be valid for it to show up in the visualiser correctly. Auto layout models makes this easy because it ensures there are no overlaps. I would need to see the log file just after you opened the visualiser to validate that there is an error here or not but I suspect not.

**Comment by bcarriveau** [comment]
i tried to grab all models from a junk test seq folder and move them all to a (*Fake) controller. This was the log result after opening visualizer. 

Not a big deal either way , was just trying a faster approach for helping someone earlier today is how i got a little confused by this.


[Log.txt](https://github.com/smeighan/xLights/files/6835573/Log.txt)

**Comment by keithsw1111** [comment]
From the log:

2021-07-17 21:29:13,880 8824 log_base [DEBUG] CUD add model removed model GE Grim Reaper 2019 as it totally overlaps with model GE Flying Bat Jr
2021-07-17 21:29:13,880 8824 log_base [DEBUG] CUD add model removed model Channel Block-2 as it totally overlaps with model Matrix-str-1
2021-07-17 21:29:13,883 8824 log_base [DEBUG] CUD add model removed model Matrix-str-1 as it totally overlaps with model Single Line
2021-07-17 21:29:13,883 8824 log_base [DEBUG] CUD add model removed model Single Line-7 as it totally overlaps with model Single Line

This is normal behaviour for the visualiser
