### ISSUE TITLE
Multiple Rendering Angles in 3D

### ISSUE THREAD

**Issue by technodisney** [smeighan/xLights#2716]
**Is your feature request related to a problem? Please describe.**
The building I am programming on is on a corner and I will be placing lights on two sides, each have their own spot which is excellent for viewing but on the corner where you can see the entirety of both faces it isn't safely accessible to pedestrians. Too program this layout in xlights at the moment I have too flatten it out into a panorama.

**Describe the solution you'd like**
The ability to render out multiple camera perspectives in 3d mode. So I can have a left side of building group and right side of the building group each I can put effects on that will render out from the camera perspective I have assigned for that group. 

It could also make for some new uses of effects if you could assign them too a camera facing down. 

As an addition to this, it would be cool if a 2d plane could be used in addition too a 3d plane, it will allow sweeping an effect around the corner.

**Describe alternatives you've considered**
My other option is too stitch together a panorama and just import that and treat it as a single surface. Which will work, but it will allow for much more creativity if I can have different perspectives in 3D.

**Additional context**
No

**Comment by computergeek1507** [comment]
This is already possible. In your 3D layout, create Viewpoints and then each effect can be rendered per different viewpoint. In xLights everything is rendered in a 2D plain even in 3D mode.

**Comment by technodisney** [comment]
Oh wow, AMAZING! Thank you!
