### ISSUE TITLE
Virtual Matrix generate and export video files

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#2717]
**Is your feature request related to a problem? Please describe.**
I have been playing with FPP and virtual matrix's, and they seem very data intensive, especially on higher resoloutions,
Video files play great however, 
If DEV's think this idea is not needed, happy to delete, 

**Describe the solution you'd like**
An idea I would think would be to have xlights have the ability to generate a video file of the entire sequence duration so you
can combine video files and general sequence effects, and have xlights export it as a video file,

This could either be done during rendering, or prompt at end to run seperate render process for them (and save in same location as fseq using model name),  (and when uploading to remote PI's through fpp connect, the file can be uploaded to them and renamed to the same filename as the fseq)

**Describe alternatives you've considered**
Tried using E131 for virtual matrix, but get tearing and freezing, havent had any luck using DDP which i beleive should be alot better, but though local video files may be even better??

**Additional context**
Not sure if this feature is really required, but thought a export model video for the matrix could work?

Thoughts?

**Comment by keithsw1111** [comment]
this already exists

**Comment by computergeek1507** [comment]
Right click on the Model Name in the Sequencer, Model->Render and Export. Select Video 

![image](https://user-images.githubusercontent.com/2293065/126565362-f495c04b-3408-44c2-be4d-6a961fcbd885.png)

![image](https://user-images.githubusercontent.com/2293065/126565530-5709a04a-b6f7-4cd2-a7a7-4b3457fcab39.png)

**Comment by cathelest** [comment]
Thanks heaps, sorry didnt know it existed,
