### ISSUE TITLE
Enhancement request - Papagayo convert into effects  

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#272]
Currently (4.1.5) the process I have gleaned to import a papagayo file or files is to create an Xlights xml (using the papgayo tab)  and then open the xml it in a new xlights seq.
The second step does a 3.x to 4.x convrersion
(I have done the coro face convrersion)
The results are a non editable 'effect' against the model (ie similar to a datalayer import). 
Could the results be changed to be editable effects (eg On effects ?). That way we can then use all the XL functionality of copy and paste / undo / move/ group move / replay / start from any point on waveform etc etc to manipulate the results.

**Comment by AzGilrock** [comment]
Papagayo files (.pgo) can now be imported into timing tracks and then you can use that to create your effects on the desired models.  I think we can close this one.

**Comment by gerry4** [comment]
thank you !



Gerard


________________________________
