### ISSUE TITLE
No update for LInux version since 2021.18

### ISSUE THREAD

**Issue by KevynChambers** [smeighan/xLights#2721]
Hi, There doen't appear to have been an update on Linux version since 2021.18? Someone suggested to me an autobuilder or complier may not be functioning correctly to cause this?

**Comment by computergeek1507** [comment]
I added a github action, so new releases should work in the future. Here is a link to a test build I created. Let me know if it works for you.

https://github.com/computergeek1507/xLights/releases/download/2021.25/xLights-2021.23-x86_64.AppImage

**Comment by KevynChambers** [comment]
Hi Scott,

Just to say that this did work, thank you very much for your help and the
work you put into xLights.

Regards Kevyn.
