### ISSUE TITLE
Upload Output to Hanson rPI-MFC Failed

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#2729]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I tried to upload output to a Hanson rPI-MFC and in the lower left I got Hanson Electronics Upload failed.
![image](https://user-images.githubusercontent.com/8147459/127755929-d041d88d-2753-4af7-8dfd-b51a961c6b17.png)

**To Reproduce**
Open xLights
add the Hanson Electronics rPI-MFC as a controller
Create a simple animation with 1 sting of 50 pixels
Save sequence
try to upload outputs.
![image](https://user-images.githubusercontent.com/8147459/127755967-45ee5836-de82-4852-b8b9-2820ef64bb22.png)

**Expected behavior**
It should not error out.

**Versions (please complete the following information):**
 - OS: windows 10
 - xLights version [2021.23]

**Attachments**
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/6912012/xLightsProblem.zip)

**Comment by patdelaney** [comment]
This still appears to be broken. I don't get an error message, but when I go to the Pi only the input is configured.
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/6939992/xLightsProblem.zip)

video  https://youtu.be/lAN6uBBq8f0

**Comment by keithsw1111** [comment]
Tell me more about this board ... this seems to be a matrix control hat? If not do you have the right board or do we have the properties wrong. Not having ever seen one we are in the dark here

**Comment by keithsw1111** [comment]
Basically because the code thinks this is a panel controller it wont try to upload strings. If it supports both then you have a problem as the FPP upload code only allows one or the other not both ... I am not sure if that can or even should be changed.

**Comment by patdelaney** [comment]
Here is more info on the board. http://www.hansonelectronics.com.au/product/rpi-mfc/   I'm not sure if he output types are mutually exclusive, meaning can I output to pixels, panels, and a DMX output.  I will research and test that.

**Comment by keithsw1111** [comment]
Yeah ... the upgrade assumes one or the other and the panel option rules. Is the board designed to be used with all at once or are you expected to choose? If that were the case then we could add different variants.

**Comment by patdelaney** [comment]
I'm checking to see if I can manually configure all of it at once. (Pixels,
panels, and dmx)

**Comment by patdelaney** [comment]
OK I have tests the rPI-MFC hat with Panels, Pixels and DMX all working at once. Alan Hanson confirmed that this is possible. I will include screenshots for each of the setups so you can adjust the variant. Please note for Pixels you must configure output 2 and not use output 1. The Pixels run off Output 2 and will not work on output 1.
![image](https://user-images.githubusercontent.com/8147459/128901552-23e26ee1-444a-490e-87fd-d12aba52dbb5.png)
For LED panels you need to check Use CPU PWM
![image](https://user-images.githubusercontent.com/8147459/128901679-3e3eaaaf-00af-4140-be7e-472bfa291802.png)
For DMX use port ttyAMA0 and DMX-Open
![image](https://user-images.githubusercontent.com/8147459/128901784-3aecbe09-b6f1-4692-a619-8d73ceccbb99.png)
