### ISSUE TITLE
Seen on Mac - Beam no longer lines up when the DMX model is flipped

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2731]
Sorry I dont have details .. but someone (Michael) on zoom .. asking to have the head flipped upside down .. but when he does that the beam no longer lines up.

Will try and upload the layout.. (3D ver)

**Comment by derwin12** [comment]
[DMX_Head_Model_Not_Matching_Beam_When_Upside_Down.zip](https://github.com/smeighan/xLights/files/6919844/DMX_Head_Model_Not_Matching_Beam_When_Upside_Down.zip)

**Comment by keithsw1111** [comment]
It seems to look ok on windows ... 
![image](https://user-images.githubusercontent.com/10283944/127948589-f16c6be2-8505-418f-9f95-3079a7e7e0b1.png)

**Comment by dkulp** [comment]
Looks the same on OSX.   Not sure what we're supposed to be seeing.

**Comment by derwin12** [comment]
Well hoping Michael chimes in here .. but that appears correct .. ie he was going to hang his mh from his eaves in an upside down config. He wasnt able to get the beam to act correctly or show correctly on his layout.

**Comment by AzGilrock** [comment]
I'm pretty sure that model will not work right if you use the Rotation parameters.  The orientation parameters were meant to be used to define the real world positioning but we didn't have one to flip it upside yet.  Even though it looks ok in Keiths screenshot I'm not sure it would have stayed aligned if he had caused it to move.  See my discussion in #2155
