### ISSUE TITLE
When reversing a model, can the submodels optionally be "reversed" as well?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2732]
On zoom a person came in with a GE Grand Illusion - which he wired from the outside in, rather then the desired inside to the out. It was simple enough to change the property but the submodels were all wrong. 

What we tried was:
output the spinner to a custom model, import this custom model back , then in model data, reversed the nodes. So now the node numbers were correct. We were just going to use this custom model for the submodel definitions (ie. import them afterwards). We were hoping the submodels would be "reversed" as well when we refersed the model nodes. 
Perhaps a prompt when you right click, reverse, that says "Cascade to submodels?" If the submodels would have been reversed, we would have imported them back into the xlights native spinner for the GE Grand Illusion.

**Comment by keithsw1111** [comment]
This is not trivial ...

When you open the model data it isnt saved until you press ok ... between opening the dialog and clicking ok you could make a lot of changes
Some of those changes might just be number shifting/flipping in which case creating a mapping is possible ... but the user could do so much more. Manually moving or even adding to numbers ... at some point remapping stops making any sense and there is no way to know when that is.
So do I always remap? If i dont how do i know when to stop ... and how does this just not look like random un-explainable behaviour to the user?

For example ... imagine a situation where you have a model containing just 3 nodes ... and you say reverse the nodes ... but then you undo the reverse by over typing nodes 1 and 3 with 3 and 1 respectively ... what do i do?

Also if you rotate the model ... do i remap ... for some submodels you need to restructure them. For others it does not matter.

**Comment by derwin12** [comment]
Perhaps a new option Reverse & Cascade (no undo) ? 
or perhaps something right on the submodel but I dont see that being feasible either - unles perhaps take max / min of main model and modulus the values found in the submodel.
I dont envy the folks who wire the big HD props differently than the PPD or vendor models.

**Comment by computergeek1507** [comment]
The Submodel dialog already has options to flip the nodes if desired

![image](https://user-images.githubusercontent.com/2293065/128363903-09f6bf1f-f304-4090-b99d-2a6c68f57558.png)

**Comment by derwin12** [comment]
We missed this ... that might just be what we were looking for all along.. Thanks for pointing it out..

**Comment by derwin12** [comment]
Tested this with the  GE Grand Illusion .. works perfectly..
