### ISSUE TITLE
2021.24

### ISSUE THREAD

**Issue by OceanViper** [smeighan/xLights#2733]
Opened Xlights 2021.23
It prompted me to update to 2021.24
Download the app image
Ran Xlights
Opened XLAW sequence
Use full render
Attempted to add lyric track (track radio was not selected)
Lyrics imported just fine (copied & paste)
Next I attempt to adjust track lyrics very slightly
**Xlights FROZE!**

I attempted this three times and it froze every time
Went back to Xlights 2021.23

Problem solved. 
I will be on the lookout for 2021.25

**Comment by keithsw1111** [comment]
Fascinating ... maybe you would like to share the sequence so we can try to reproduce it?

**Comment by darylc** [comment]
End user came into zoom, is running linux

**Comment by cjd** [comment]
If left when frozen - did it eventually recover?
Also - if you select 'suspend render' a tthe bottom of the screen - does it still hang?

**Comment by OceanViper** [comment]
Hell Chris that was last year's problem. After 2021.36 that problem got better. By better I mean Yes, if you wait 1/2 hr or more it eventually returns. Now with 2021.36-2021.40. The xscheduler takes even longer to open on Linux Mint 20.2. Sometimes it opens within 4 hours, but it usually just never opens at all. I don't attempt to open it during showtime. Also I don't have FPP and apparently there are none avail anyways. Before you ask, NO I never have xlights open at the same time. However since xlights & xshedualer are now married, the only way I find to open xscheduler is to open xlights, go to tools>xscheduler>Open. 100% of the time I get a message stating 

**"Port 80 is busy, you may have another process running in the back ground."**

Yes I agree with Linux, I do have another process running in the background, it's called xscheduler! I finally decided to open it on a windows laptop to set my New Year schedule. I set my Christmas show at #3 priority, and my New Year schedule at #7 priority. Low and behold, the Christmas show still took priority. I changed the priorities several times before coming to the conclusion the only was to stop the Christmas show was to just delete the entire show. 

Now Jan 4th my News Year's countdown sequence finally played along with my other New year sequences. My wife was getting scared, she said that if the Christmas schedule continues to play after it has been deleted, we are being haunted and will have to sell our house and move away to get away from it. LOL  It was indeed creepy, very spooky... The next thing I was going to try was shutting off the main circuit breaker to the whole house. Then if the Christmas show continues to play without electricity, then I must agree with the wife, Time to move away for sure!

**Comment by OceanViper** [comment]
FYI, All of Xlights is ran from an app image on a T7 Samsung 1TB SSD along with my show folder & all sequences. Yes, I plugged the T7 into a USB and deleted the Christmas show on a Windows Laptop. Then returned the T7 back to my Linux laptop that runs the shows. I'm going to let it run until Jan 10th to see what happens. I'll be back with a report soon...

**Comment by cjd** [comment]
Closing off old linux issues - reopen if still occurring
