### ISSUE TITLE
Shaders and Check Sequence not working.

### ISSUE THREAD

**Issue by OceanViper** [smeighan/xLights#2737]
Keith I am running Xlights V24 on Linux Mint 20. All software is updated including Linux. However my shaders and animated gifs are failing. My **Check Sequence** no longer works. I found this in my log file.  

2021-08-05 23:16:19,090 140306141570624 log_base [ERROR] Failed to compile shader program /media/ocean/T7/Xlights-Shows/Shaders/Bulge.fs
2021-08-05 23:16:19,379 140306141570624 log_opengl [ERROR] shader-compile failure: '0:87(2): error: `return' with **wrong type ivec2**, in function `IMG_SIZE' returning vec2

See the attached files... If you need anymore files, or a copy of Linux Mint 20, let me know.
[Xlights_Debug.zip](https://github.com/smeighan/xLights/files/6943670/Xlights_Debug.zip)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/6943672/xLightsProblem.zip)

Thanks -Ocean

**Comment by keithsw1111** [comment]
I dont really support Linux specific errors. A failure to compile shader code could be a problem with the shader or a problem with your driver. If it works on other platforms then it is a driver issue which only you can fix.

**Comment by dkulp** [comment]
Fixed the shader compile issue with IMG_SIZE.

**Comment by OceanViper** [comment]
IMG_size?  Can you be a little more specific? What do I need to do?

**Comment by dkulp** [comment]
Nothing... the shader will compile and run correctly with 2021.25 when that is released.

**Comment by AzGilrock** [comment]
You need to sit back drink a beer and wait for next release. :)

**Comment by OceanViper** [comment]
LOL-  Okay that I can do, actually that's the best advice I have had all week!  
Thanks Dan.  Seems there are not many Xlights users running Linux, and most Linux users don't know what Xlights is.

**Comment by keithsw1111** [comment]
I cant think of any reason why check sequence would not appear in the tools menu.

**Comment by OceanViper** [comment]
Sent from Yahoo Mail for iPhone


On Friday, August 6, 2021, 3:55 PM, Keith Westley ***@***.***> wrote:




I cant think of any reason why check sequence would not appear in the tools menu.




Perhaps Dan my know, I am grateful that he solved the shader issue fast. 

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by computergeek1507** [comment]
The Check sequence works when I build from source. It doesn't work for me with the appimage either. I think it has something to do with the sandbox appimages are run in.

**Comment by OceanViper** [comment]
Well then it's nice to know I am not the only one. I have ran the Appimage on several drives on my desktop. Today my software manager notified that there was a newer version of Linux Mint so I upgraded from 20.0 to 20.2 Cinnamon  I tried my .M2 drive because it is my fastest drive. Also ran it on a Samsung T7 SSD then proceeded to run it on my laptop that uses a Samsung Evo which is also running Linux. I think you might be right about the sandbox. Maybe Dan will look into it.

**Comment by OceanViper** [comment]
In Linux Mint (Cinnamon) V20.2   Xlights Check Sequence is now opening via **Libre Office Writer**. Apparently Linux is treating the Check Sequence file as a document as opposed to a text file. I am using the 2021.24 App Image. I Still have not tested it on my Linux laptop but I will report back when I do.
