### ISSUE TITLE
Should SingleStrand collapse at the end of each cycle w circle model?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2741]
Question from zoom .. using a circle model and single strand effect, the effect collapses down at the bottom for each cycle - should it continue on or is that even possible? We figure it has something to do with it going from right to left and reaching the end of the buffer and there is no wrapping taking place (as that isnt possible?)

Attached is the test effects along with the spiral that does the complete revolution but doesnt look the same.

Probably not a bug but we wondered if this was the intended effect.
[SS-Question.zip](https://github.com/smeighan/xLights/files/6951568/SS-Question.zip)

**Comment by keithsw1111** [comment]
The effects in the sample sequence are on a model that does not exist in that setup and the question is not clear enough for me to know exactly what you are asking.

**Comment by derwin12** [comment]
Shoot I forgot to save layout before packaging sequece.. It is just a circle model .. but I will create another one.

**Comment by derwin12** [comment]
![2021-08-10 08_17_40-xLights - F__2021_TestFolder_SS-Question xsq](https://user-images.githubusercontent.com/4643499/128865586-a1117aeb-f962-4288-98e8-f28e88edc96d.jpg)
![2021-08-10 08_17_31-xLights - F__2021_TestFolder_SS-Question xsq](https://user-images.githubusercontent.com/4643499/128865593-67268f25-af33-4aaf-a1a8-c20a6bc49388.jpg)

**Comment by derwin12** [comment]
[SS-QuestionReUpload.zip](https://github.com/smeighan/xLights/files/6961596/SS-QuestionReUpload.zip)

**Comment by derwin12** [comment]
So the SS effect basically collapses and disappears when it hits the bottom/end of the loop.

**Comment by AzGilrock** [comment]
I haven't looked at the file but the effect has no idea its a circle model.  It just renders onto the provided buffer.  The circle model is going to be represented in the buffer as a stacked straight lines so its like you take a matrix and then bend it around into a circle.  The point where you bend the two ends together is where the effect will end.

**Comment by keithsw1111** [comment]
This is 100% correct ... as Gil says the buffer ends there ... it does not magically loop around.
