### ISSUE TITLE
xLights closing down (no crash alert) when render all for a specific sequence

### ISSUE THREAD

**Issue by earft01** [smeighan/xLights#2745]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
xLights closing down (no crash alert) when render all for a specific sequence

**To Reproduce**
Open sequence (only one that I am having problems with at this time that I know of)
Click render all

**Expected behavior**
Expected render all to complete

**Screenshots**
n/a, closes down when hit render all

**Versions (please complete the following information):**
 - OS: Windows 10 20H2 Build 19042.1110
 - xLights version 2021.65 64bit

**Additional context**
n/a

**Attachments**
I do not have a dropbox account, I have generated the logs and have the sequence file ready so please PM me when ready for me to send via PM.

**Comment by keithsw1111** [comment]
Given we dont know who you are based on your id i am not sure how we are to PM you.

**Comment by earft01** [comment]
Sorry, https://www.facebook.com/earljordan28117

On Aug 13, 2021, at 3:42 AM, Keith Westley ***@***.***> wrote:

﻿
Given we dont know who you are based on your id i am not sure how we are to PM you.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by keithsw1111** [comment]
Was this fixed in .25?

**Comment by earft01** [comment]
Yes

On Aug 15, 2021, at 1:00 AM, Keith Westley ***@***.***> wrote:

﻿
Was this fixed in .25?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
