### ISSUE TITLE
K8-B does not have a drop down for Serial and DMX does not go through

### ISSUE THREAD

**Issue by SRipaldi** [smeighan/xLights#2746]
In the Controller tab, the Kulplights K8 does not have a serial drop down option.   If the K8 is configured as a K8 it will not send DMX data through the RJ-45 ports.   If the K8 is configured as an F8 with Serial, DMX data will be sent through the RJ-45 ports.

Current Xlights Version: 2021.24
Logs show no errors.

**Comment by computergeek1507** [comment]
The DMX ports on a K8 are the green screw terminals not the RJ45

**Comment by dkulp** [comment]
Actually, on the K8, they are pin headers to the right of the OLED, but yes, the RJ45's are ONLY for pixel data.   The 2 DMX outputs are configured on the "Other" tab.

**Comment by SRipaldi** [comment]
Fair, I will test with the ttys1 port on the board.  Interesting point I put a FPP 4.6 build onto the controller, called the K8 and F8  with serial and everything worked as before.
