### ISSUE TITLE
Boscoyo Models Not Properly Importing on Ubuntu

### ISSUE THREAD

**Issue by borth79** [smeighan/xLights#2748]
**Describe the bug**
Boscoyo model does not include all sub-models. I have viewed the .xmodel file for the Boscoyo Chatty Ghost, but the sub-models from the file are not importing.
http://hohenseefamily.com/xlights/Models/Boscoyo%20Chatty%20Ghost.xmodel
I can see all the sub-models are defined in this file, but only the outline imports. This also seems to be consistent with the other Boscoyo models, but not all.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to Layout tab
2. Click on the Download object option
3. Click on the layout preview
4. Click on Model of Ghost Left Chatty
5. Click on Sub-Models ... button to to open the sub-models
6. See that only the outline exists

**Expected behavior**
I expect all the sub-models to be properly imported and displayed

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04
 - xLights version xLights-2021.18x86_64

**Comment by dkulp** [comment]
That file only has a single "Outline" submodel.   The other things in that file are face definitions for the faces effect, but they are not submodels.

**Comment by borth79** [comment]
You are right. Just found them. User error. :)
