### ISSUE TITLE
Importing Effects

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#2749]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When trying to Import Effects, xlights closes down.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Open Sequence "Dueling Jingle Bells"...Get warning "Missing Models In This Sequence"
2. Do You Want to Continue To Open Click on "No"
3. Click on "Import Effects" Open Dueling Jingle Bells"
4. Click on "Auto Map" After it finishes mapping click on "OK"
5. xlights shuts down and closes.

**Expected behavior**
Would expect xlights to remain open and effects imported to sequence.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
Without the sequence there is nothing we can do with this.

Also given you are using automap we would need your layout as well.

**Comment by jimswinder** [comment]
> 
> 
> Without the sequence there is nothing we can do with this.
> 
> Also given you are using automap we would need your layout as well.

I know...hit the wrong button...trying to edit it but uit wont let me!!  lol
can you delete it and I will start over

**Comment by jimswinder** [comment]
how / where do I find the layout to attach?


________________________________
