### ISSUE TITLE
Effects do not get undone from sequencer player after Undo

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#275]
I created a new sequence .
I used the Create random effects to create random effects on 6 cells on my Megatree.
I played the sequence and changed my mind.
I then used the Undo effects function and the effects were visually removed from all 6 cells
I then added a new effect (drag and drop) , stretched it to fill 3 cells , then did the undo effects command 3 times (it did an undo move , undo move and undo added effects).  Great !!

So visually , there was no effect against the mega tree model at all

I then pressed play to listen to the sequence and decide my next step , when I noticed that the previous effects still played in the house preview window, even though they had been removed.
What played was the new effect for the first 3 cells and then the remained of the random effects for the next 3 cells.

Have not pressed render..
Had to save before exiting as the warning came up. After which it was back to normal ie no effects played.
This was done using the normal sequencer layout ie Toggle nodes was off.
I am not sure if in between I pressed save at any point , but I don't think so. Notwithstanding what can be seen (ie no effects) is not what is playing (previous effects).

**Comment by AzGilrock** [comment]
Well it sounds like you already knew the answer.  You gotta hit Save or Render All if you want to fix the rendering in a sequence.  Doing an Undo doesn't fire off rendering tasks.  Just be happy you have the Undo.

**Comment by gerry4** [comment]
Okay. I thought it was a bug. No problem . just need to get used to a different way .

And I am grateful to the Undo function - I use it extensively as you can tell. Without it many other effects such as copy and paste etc would not be used as often.
