### ISSUE TITLE
Selective Submodel Import

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#2754]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
When working in a submodel there is an import button.  However I would like ask for an enhancement so that during the import process there is an option to select which submodels to import.  Default would be all checked.

**Describe alternatives you've considered**
Depending on the number of layers in the submodel I typically just modify the xml directly or copy & paste into the new submodel dialog.

**Additional context**

**Comment by computergeek1507** [comment]
added with 44ca0b0b9e8a605732c1b9f3bd3c79a3064e88a3
