### ISSUE TITLE
Alternative backup folder does not work

### ISSUE THREAD

**Issue by tomhammond** [smeighan/xLights#2756]
There seem to be two issues related to backup:

1.
If I enable Backup Subfolders in Preferences, xLights backs up all of the subfolders inside the show folder, including the backup folder itself.  Therefore it is looping, backing up the contents of the backup folder into the same location, looping until xLights crashes.

2.
I tried to set an alternative backup folder by disabling the Use Show Folder and defining an Alternative Backup Directory in Preferences.  When I click OK, I am prompted to save the Controller Layout tab, which I do.  When I exit xLights, restart it, then go back into Preferences, the "Use Show Folder" is enabled again.  Also, backups are stored in the Backup folder inside the Show folder, not the alternative directory that I defined.  

I verified that the path entered into Alternative Backup Directory is valid by cutting & pasting it into an Explorer window.

I made a video for issue 2:
https://youtu.be/XQcJloSAHMo

Let me know if you need a video for issue 1.

Thanks,
Tom Hammond

**Versions (please complete the following information):**
Windows 10
xLights 2021.25

**Comment by keithsw1111** [comment]
I need the logs to see what was happening.

**Comment by tomhammond** [comment]
OK, I will provide the logs tomorrow (Sunday EDT).

**Comment by keithsw1111** [comment]
Your video looks correct. Alternative backup is only used when you press F11 or choose File/Alternative Backup.

Otherwise backups go to the backup folder.

As for #1 it will not backup the backup folder in your show folder ... likely you have something funky there where the backup folder is sitting in a folder under the show folder ... in which case it will be backed up.

Essentially I suspect your folders are a bit of a mess.

**Comment by tomhammond** [comment]
I can't reproduce this problem now.  A few days ago, xLights crashed on two successive startups with a crash message and everything.  I didn't have the presence of mind to backup the log at that time.

 

I did not have the backup folder inside a different folder underneath the show folder.  The defined backup folder was outside the show folder.

 

I can't recreate the problem now, sorry to waste your time.

**Comment by keithsw1111** [comment]
I will close. If you manage to reproduce please post logs and reopen the issue (or create a new one).
