### ISSUE TITLE
Import the automated Audacity Lyric track breakdown..

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2759]
Have you seen this vid from Phil about using https://autolyrixalign.hltnus.org/ to analyze lyrics and audio to determine the placement of words in a song? Wondered if xlights can say perhaps take in that raw .audacity file so we can eliminate the need to run the macro in notepad prior to loading in xlights.

**Comment by keithsw1111** [comment]
We already load audacity files.

**Comment by derwin12** [comment]
This is a special type of output .. it is not outputed by audacity but by this other software noted above .. so it needs a little tweak on xlights side to be able to handle it. (see the video ... from Phil)
https://www.youtube.com/watch?v=CGwlmtLDaTI&t=117s

**Comment by computergeek1507** [comment]
The file generated is space separated and xLights requires tab separation. I was going to update it.

**Comment by keithsw1111** [comment]
Can someone attach a file?

**Comment by derwin12** [comment]
Sorry didn't think to do that ... is here is Breakfast Burrito - not a great example of its work as it didn't recognize the word Burrito, but that should'nt matter.
Attached is what they consider an "Audacity File" .. with default .txt extension
[result_lyrix_269641713.txt](https://github.com/smeighan/xLights/files/7027526/result_lyrix_269641713.txt)
