### ISSUE TITLE
Mac - Output to Lights take a while to execute with unavailable controllers.

### ISSUE THREAD

**Issue by zackbcom** [smeighan/xLights#2760]
**Describe the bug**
Unable to confirm if is also an issue on windows.
When clicking _Output to Lights_ and there are Kulp controllers in the controllers tab that are offline (pixel hats in this case), xLights clocks excessively. With 4 controllers offline, it takes 4+ minutes to enable the output and give back control to xLights UI.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to Controllers tab
2. Add a new Kulp F32A-B controller (Auto layout mode, Auto Upload, Auto Size all selected. DDP Protocol)
3. Set an IP that goes nowhere.
4. Save
3. Load any sequence.
4. Output to lights is clocking for minutes.

**Expected behavior**
Xlights should know that the controllers are offline and skip over the code that makes calls to FPP to enable settings and only send the DPP data.

**Workaround**
De-Activate the controllers in the controllers tab.

**Screenshots**
mac_osx_mouse_spinner.gif

**Versions (please complete the following information):**
 - OS: Mac 11.4
 - xLights version 2021.25

**Additional context**
Haven't tried it on any other controller types.
Might be related to the code that calls to FPP that enables the Channel Input.

**Attachments**
N/A

**Comment by keithsw1111** [comment]
Turn off auto upload ... at least for now.

**Comment by bacarudaguy** [comment]
I was having this same issue with auto-upload turned off... we have a mix of Pi's, Kulps, Falcon's and SanDevices... my work around was to select the controllers that were offline and make them Inactive. This solved the problem at the time, but you have to remember to reactivate them.
