### ISSUE TITLE
2021.25 Crashes if serial controller is in xlights_networks.xml

### ISSUE THREAD

**Issue by Kintara** [smeighan/xLights#2762]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
If a serial controller is added everything is fine untill Xlights is next run. It then fails to run.
**To Reproduce**
Set a serial controller then save and close Xlights
Restart Xlights and after banner is shown it then dissappears.

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version [e.g. 2021.25]

**Additional context**
removing this line from xlights_networks.xml and Xlights will start as normal
```
 "<Controller Id="171" Name="Serial_" Description="" Type="Serial" Vendor="" Model="" Variant="" DefaultBrightnessUnderFullControl="100" ActiveState="Active" AutoLayout="0" AutoUpload="0" SuppressDuplicates="0" Port="COM3" Speed="57600" Protocol="Generic Serial" Prefix="+&gt;" Postfix="">
    <network ComPort="COM3" BaudRate="57600" NetworkType="Generic Serial" MaxChannels="8"/>
  </Controller>:"
```

**Attachments**
File extension changed to txt from xml
[xlights_networks.txt](https://github.com/smeighan/xLights/files/7027685/xlights_networks.txt)
https://photos.app.goo.gl/aMVrfrVKdDb8DWcR6

**Comment by keithsw1111** [comment]
I believe this if fixed in .26.
