### ISSUE TITLE
Highlight nodes from line above when building sub models 

### ISSUE THREAD

**Issue by bcarriveau** [smeighan/xLights#2768]
Uploaded is a quick and dirty image to represent what im thinking.

While building sub models , is it possible to have the nodes from the line above show in a color different then white? 

I would find this VERY helpful to the end user to help then remember what they just created , this would be much more helpful on all these new high dense props vers. just my example of a snow flake.

![submodel highlight](https://user-images.githubusercontent.com/60801063/130718591-8e6a751f-0f3d-4ee9-b592-63efdeebeb73.jpg)

**Comment by bcarriveau** [comment]
@computergeek1507 , i did update the picture to show more what i was thinking. Thank you for looking at this!

**Comment by computergeek1507** [comment]
added with e9c21df070232cc53122843b3c1ef751b4f4ee0c
