### ISSUE TITLE
Visualizer on Panel Matrices Not Working as Expected

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#2770]
**Describe the bug**
I currently have 2 P5 matrices on a single ethernet port of a FPP instance.  Since each matrix is the exact same size I just have FPP configured to have a single matrix that 2x as tall.  I tried the auto layout option but I think there may be a few bugs.

In visualizer when I drag just one of the P5 panels over another model that's on a different controller higher up (Tune To) is displayed where I dropped the single matrix.  The tune-to is also using full xlights control.  This cosmetic because the Tune-To channels are correct with the proper controller assignment.

I then went to the visualizer and I noticed that my matrices do have the proper controller & port assigned but all have the same channel numbers.  In the layout tab I set them to be port 1 and set the model chain to be Top Left at the begenning with Top Right set to follow top left.  This did not adjust the channels.

![image](https://user-images.githubusercontent.com/3765696/130802230-c2af0aee-1893-43b3-b095-252a7ecf9df5.png)

Another note is that on this controller, FPP Attic Windows, I have 540672 channels assigned but when I open xLights the previously working AutoSize option that was working is resetting the channels to zero.  I may revert to manual sizing for this controller.

**To Reproduce**
I think I've covered this above.

**Expected behavior**
Full control + auto layout + auto size to handle chained matrixes just as if this were chained models.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Win 10
 - xLights version 2021.26

**Additional context**

**Attachments**
networks & rgbeffects from 2021.25
Relevant controller is "FPP Attic Windows"
Relevant models are "Dormer - Top Left" and "Dormer - Top Right"
[xLights Configs.zip](https://github.com/smeighan/xLights/files/7047493/xLights.Configs.zip)

**Comment by keithsw1111** [comment]
Are you trying to put 2 panels on the one led panels output in the visualiser? I am not sure it was ever built for that ... likely you would need a shadow model. Of course maybe we could just chain the channels ... I am not sure there is a good reason why we dont. Is that what you are expecting?

**Comment by MrPaulAR** [comment]
This is likely enough of a corner case so that it's not worth the exercise.  As you mentioned there are at least two options available for this (shadow model and submodels).

My option was a 3rd which is to define FPP as a full matrix (14h x 2w) which is how colorlight is configured (2 colorlight cards).  Then in xLights I used the older "chain models" option to define 2 matrices at 7h x 2w and just have the 2nd matrix follow the first.

**Comment by MrPaulAR** [comment]
This may not have been the initial vision or within the scope of the
current vision.  I've got a workaround in place for my personal needs using
the old way of telling the 2nd model to follow the first.  I prefer this vs
sequencing to submodels.

My proposal was to account for the following.

   - Single colorlight matrix defined as 6 tall by 3 wide (dimensions
   aren't important but help with visualization)
   - In the real world this would be 2 separate matrix that are 3 tall by 3
   wide
   - In FPP this is defined as one matrix that is 6 tall by 3 wide
   - In xLights the most common option is to draw 1 matrix but sequence to
   2 submodels
      - Or draw 1 matrix and use shadow models as you mentioned to address
      layout issues.

Probably should just leave things as they are is this is very much a corner
case and there are already multiple workarounds.  Maybe FPP will add the
ability to chain matrixes and this could be reconsidered.
