### ISSUE TITLE
Check Sequence show errors and warnings as icons on main UI

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#2774]
Please close if this seems stupid or not possible etc. 
Just curious as to why we do it the way we do it, and if there may be a better way?

**Is your feature request related to a problem? Please describe.**
If you never run the check sequence, you may not realise you have errors and warnings

**Describe the solution you'd like**
Is it possible to have a option to enable running the check sequence before/during/after rendering, 
and then showing icons on the main UI with warning and error counts, 
and when you click either icon it can just open the checksequence text file,

**Describe alternatives you've considered**
Having errors and warnings show in a UI where clickable to select effect in question could be nice,

**Additional context**
Just curious as to why we use check sequence the way we do?
Is there a reason its a manually started process?
Is there a reason we just do the text log and not show it on the UI?

**Comment by keithsw1111** [comment]
A few of reasons I can immediately think of.

1. It started organically this way as a trouble shooting tool. (not a reason to leave it this way but definitely why it is this way)
2. The runtime ... as shows get larger some check sequence checks can get quite slow.
3. Check sequence is deliberately very thorough and picky. This means that warnings in particular would be annoying if they were always in your face ... particularly if it is a warning you are consciously ignoring.
4. They would clutter the UI and would not always have a good place to appear. xLights is already a complex UI ... further cluttering it with obscure UI check sequence hints would be hard to do cleanly.

That is not to say that you couldnt potentially change Check Sequence to make it easier to use.

For instance
- You could decide that check sequence should run automatically on sequence open (i would hate this but it could be done).
- You could give the user control over which checks run (at least to some level ... some checks are quite distributed).
- You could have a simpler error only check sequence ... focussing on the serious issues.

**Comment by computergeek1507** [comment]
I have thought about trying to add a "background" check sequence. I think the wxLogDialog could be used. In the taskbar have an Error, Warning or Ok icon and open the dialog when it is double clicked. Run it in a background thread at sequence load and maybe after idle for a set time.

**Comment by keithsw1111** [comment]
Only problem with that @computergeek1507  is you will need to get your locking sorted as otherwise it could just drive a bunch of crashes trying to access models/effects that have been suddenly deleted/recreated.

**Comment by bacarudaguy** [comment]
Just a thought here, but could it run when a sequence is (re)rendered? Seems like a good time for a process like that to work...

**Comment by keithsw1111** [comment]
Wont that just slow down the render?

**Comment by AzGilrock** [comment]
Folks shouldn't need to be running check sequence hardly ever.  We created it because we kept seeing the same mistakes over and over and most of them were simple enough for the average person to find without the tool.  And most issues it finds are global to all sequences so no need to run it on every sequence.  You run it when you have an issue you can't figure out.  You have the ability to run it no need to make it automatic.
