### ISSUE TITLE
Crashes when Opening New Musical Sequence on Mac

### ISSUE THREAD

**Issue by neumaa** [smeighan/xLights#2777]
xLights crashes when I try to open a new musical sequence on my Mac.  This happens when I select New Sequence > Musical Sequence > select an .mp3 file.  I get an error "xLights quit unexpectedly.  Click Report to see more detailed information and send a report to Apple."  Link to that report included below.

I'm on an older Macbook Air purchased in 2013 OS X Yosemite 10.10.5 (14F2511).  I used xLights last year on the same computer without issues.  I'm currently on xLight 2021.07 and would like to upgrade to see if that fixed the problem but I am having issue with that too.  In the app store, when I click "Update" it just spins.

I've tried to adjust my OpenGL settings and reset my windows/perspectives but it doesn't seem to fix the problem.  I'm happy to provide whatever information I can to assist with a fix so let me know if there's any information that would be helpful.  Thank you in advance.

xLights Packaged Logs - https://www.dropbox.com/s/s1d15hf0g1zyd1j/xLightsProblem.zip?dl=0
OSX Crash Report - https://www.dropbox.com/s/yhkeqq0gh7s0bwq/OSX_crash_report.txt?dl=0

**Comment by dkulp** [comment]
You can try deleting the xLights app (copy it to a safe location first) and re-install.   That will likely install 2020.50something.  We now require OSX 10.12 so your 10.10 will no longer work.   10.12 is the minimum.
