### ISSUE TITLE
Canvas Layer Settings Not Holding - Win and OSX

### ISSUE THREAD

**Issue by byakymyk** [smeighan/xLights#2788]
Mac V27
Noticed that when I opened one of my sequences the Warp Effect started interacting with a the last layer which I had turned off.  I went to Layers and turned off bottom two layers -> click off Warp Effect -> click back on Warp Effect -> go to Layers and layers clicked off are shown to be selected again.  I have attached video.

https://user-images.githubusercontent.com/2902828/131594011-9f38d63e-70b2-4220-ad01-1b6bf6bf3377.mp4

**Comment by byakymyk** [comment]
No change in V28

**Comment by fone626** [comment]
This is also not working on Linux.
This bug bit me yesterday and had me doubting my sanity until I realized that the setting were reverting once deselected.
I eventually found that if I press F5 immediately after clicking OK on the layer selection that my settings would stick, and sanity was restored.

**Comment by byakymyk** [comment]
Fone626 - You are correct that F5 will no hold the layer selection.  However, the layers below will not render for me now - only the ones selected.  In my example I only want layers 3, 4, 5 & 6 impacted by the warp effect.  Now after deselecting layers 7 & 8, these underlying layers won't render.  Still a major bug for a sequencer.

**Comment by fone626** [comment]
byakymyk - Just tried it myself with the same results as you.  The warp effect seems to be baking the black into the result. I had to add a chroma key to the warp effect to get it to show what was below it.

**Comment by computergeek1507** [comment]
I tried to reproduce this on windows and I could not.

**Comment by byakymyk** [comment]
I will take a screen cap showing I am having same issue on both Win and Mac.

**Comment by byakymyk** [comment]
https://user-images.githubusercontent.com/2902828/133096768-e933b7f6-cd9a-40fc-9033-d709cef2567a.mp4

**Comment by fone626** [comment]
In addition to the video above I found this youtube video from April where he's teaching you to click render after making the canvas setting to make them actually:
https://youtu.be/k9W_07pAO80?t=155

**Comment by byakymyk** [comment]
Just a reminder that after V23 it does not render properly even if I can trick the app to turn off the layers - all layers that are turned off do not render.

**Comment by byakymyk** [comment]
I recently update to Mac 29.2.
I am now able to turn on and off the appropriate layers when using Warp Effect - Canvas - Layers.
However, the layers below that are turned off (or deselected) will not render.
Example Shape Effect on Layer 1, Warp Effect on Layer 2 has Layers 3 to 6 selected and Solid Colour in Layer 7  - Layers 1 to 6 render but layer 7 will not

**Comment by byakymyk** [comment]
V37 has fixed the issue

**Comment by adamcoulombe** [comment]
I am running v2021.39, it is not remembering which canvas layers when I return to the canvas panel

**Comment by adamcoulombe** [comment]
https://user-images.githubusercontent.com/469038/145058236-28549ce9-d777-4792-bd40-9bf0c9a51010.mp4
