### ISSUE TITLE
Crash: Adding elements to a 4.1.4 sequence file with latest version 4.1.7

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#279]
Using OSX 4.1.7 version today.

I opened a sequence that I had created in 4.1.4.

I added another later below my Matrix and attempted to drag in an effect. In this case Twinkle. When I let go of the mouse I received the pinwheel of death and xlights completely crashed.

If I created a new sequence in 4.1.7 .. Saved the sequence.. Closed xLights. Re-opened Xlights, and added the same effect there was no crash.

I'm concerned that my file from 4.1.4 is no longer usable.

A dropbox link to the XML file is here: https://www.dropbox.com/s/l88znq6giedmoxm/Santa%202x2.xml?dl=0

**Comment by kppankratz** [comment]
This sounds almost exactly like the issue I'm having with the new release and reported on the forum.  All I have to do is simply click on an existing effect from a previously saved file and it crashes.  Not all effects though.  I feel your pain, but glad it's not isolated to just me.

**Comment by kppankratz** [comment]
Is this still a problem with the latest release?  My issues went away with 4.1.8 under OS X.

**Comment by LightsOnHudson** [comment]
This works as of 4.1.8 I just tried it this morning :)
