### ISSUE TITLE
Model Groups containing duplicate nodes - Can it Ignore Shadow Models?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2790]
Not a big deal .. it appears shadow models get flagged for duplicates. Attached is my show folder.

WARN: Model group '01 Everything' contains model 'Eaves - Lower - C9 Lights' and model 'Eaves - Icicles' which contain at least one overlapping node (ch 12495). This may not render as expected.
    WARN: Model group '01 Everything' contains model 'Icicles Single String' and model 'Eaves - Icicles' which contain at least one overlapping node (ch 12495). This may not render as expected.

This used to be 2 different physical models but decided not to use the top of the icicles to be the lower c9 lights - so made them a shadow model of the icicles.
[nothing.zip](https://github.com/smeighan/xLights/files/7108951/nothing.zip)

**Comment by derwin12** [comment]
Thinking about this .. perhaps it should be left as just a consequence of shadow model. If you include them both in a group the error would flag and catch this.  In my case I include both since at one time the models were indeed using different pixels/channels

**Comment by keithsw1111** [comment]
Why would you add in the shadow models ... it should be one or the other

**Comment by derwin12** [comment]
It was a real prop at one point .. so it was sequenced against (eaves line), then when I bought icicles I just submodel my icicles and use that and turned the eaves into a shadow model of the icicles top line. Probably should just bite the bullet and yank that old submodel out as I am unlikely to use it anymore anyways.

**Comment by derwin12** [comment]
Seems fine the way it is .. I will handle the model on my side.
