### ISSUE TITLE
My Mega Star Model hasn't worked correct since version 2020_40

### ISSUE THREAD

**Issue by fitz333** [smeighan/xLights#2791]
What the star is meant to look like (Version 2020_40):
![image](https://user-images.githubusercontent.com/74628494/132113761-0dc18691-2315-47f4-80cd-8dc63bcfded7.png)

What is looks like in any update since:
![image](https://user-images.githubusercontent.com/74628494/132113726-bb176208-efb7-464d-86a4-755a51842f11.png)

Any update from 2020_40 onwards is making my megastar look strange and I cannot fix it apart from going back to the 2020_40 version. I need to build my megastar in 3 different stars as each star connects to a different strand on the mega tree. Is there a fix for this?
Here is a link to the video of exactly what I am trying to do. https://www.youtube.com/watch?v=68_8NjkC3pc
Attached below are screenshots of how the star is made:
![image](https://user-images.githubusercontent.com/74628494/132113858-3a626dcc-67f3-4150-bbf1-b6be0c54287a.png)
![image](https://user-images.githubusercontent.com/74628494/132113865-6d45bdec-79d0-4727-b798-18e1d3987508.png)
![image](https://user-images.githubusercontent.com/74628494/132113873-658d843b-900d-4a03-b22b-27a226a5c9a8.png)

**Comment by AzGilrock** [comment]
You really need to do a Package Log Files and post that nobody wants to spend 10 minutes trying to reconstruct the model just give them the file with it already there.

**Comment by Old-Salt** [comment]
Did you update the xmodel since release 2040, or perhaps change the resolution of your whole house display in layout?

Most xmodels are mapped onto a rectangular grid.  The smaller the size of the grid, the more likely you'll encounter that type of distortion.  Without the packaged sequence(s) there's no way for us to investigate the problem.

**Comment by jefft0825** [comment]
There was an update to the star model in 2020 that reverses the pixel count from inside to outside.   Look through release notes for the star. 

My guess is you have to reverse the pixel count per layer to get it to look correct

**Comment by fitz333** [comment]
[Xlights Issue.zip](https://github.com/smeighan/xLights/files/7127693/Xlights.Issue.zip)
I have attached the files, hopefully that's the files needed? I'm only new to this so please let me know if its the wrong files.
I haven't changed anything or updated anything on the xmodel. Any update after 2020_40 changes that star. All I do to fix it is reinstall version 2020_40 or earlier and the star corrects itself.
On the latest versions I can create a 6 row star that looks correct though I need to build the star model the way I have so I can use the left over channels on the mega tree for each part of the star.

**Comment by AzGilrock** [comment]
There have been updates that changed the mega-star that required users to make adjustments.  I had to fix my megastars awhile back but I forget which release changed them.  Since you have that 3 star conglomerate you probably just need to adjust the percentages for the center gap.

**Comment by fitz333** [comment]
> There have been updates that changed the mega-star that required users to make adjustments. I had to fix my megastars awhile back but I forget which release changed them. Since you have that 3 star conglomerate you probably just need to adjust the percentages for the center gap.

Ok thank you for the info. Where do I adjust the percentages for the centre gap?

**Comment by keithsw1111** [comment]
So you have strings that are a different length so you cant merge it into a single star model.

The change you are seeing is not going to be reversed. It had to be made to support stars with multiple layers with the same number of nodes that could not be supported by the old star model.

There is one option. Create a single star with 6 layers of the appropriate sizes. Export it as a custom model. Import that model. Set individual start nodes and choose the appropriate nodes for your 3 strings. The custom model wont necessarily look as good but it should be ok.

**Comment by dkulp** [comment]
Pushed an enhancement to allow controlling the layer positioning a bit better (more like "Circle"model).

**Comment by fitz333** [comment]
Thank you everyone for the help. The inner % made it workable so I can now start using the new versions of xlights.
