### ISSUE TITLE
fpp connect - add to playlist - no duplication?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2793]
Using fpp connect and you enter the playlist to add it to. Can it be handled such that it doesnt duplicate the sequence in the playlist if it already exists?

**Comment by computergeek1507** [comment]
Which version of FPP are you using?

**Comment by derwin12** [comment]
4.6.1

**Comment by computergeek1507** [comment]
I tried 5.1 and it doesn't duplicate

**Comment by derwin12** [comment]
Let me try .. i was pretty sure id dupped -- but perhaps thats a new 5.1 feature

**Comment by derwin12** [comment]
Yea .. definitely does it in 4.6.1 :-(
Go ahead and close if its an fpp issue as I dont see them doing a 4.6.2

**Comment by computergeek1507** [comment]
We could add logic to xLights to prevent this but as it's fixed with FPP 5.0, I don't plan on it
