### ISSUE TITLE
Bulk Edit Text Controller Start Null Node should be Controller End Null Node

### ISSUE THREAD

**Issue by jaredkaczynski** [smeighan/xLights#2796]
https://github.com/smeighan/xLights/blob/b979fbd197e3c8a10d4d19490641e35d7d5c2aa1/xLights/LayoutPanel.cpp#L4292

Minor text issue, both the start and end node bulk edits display as Start. This should be End for the applicable end node bulk edit to avoid confusion. It functions properly otherwise.

![image](https://user-images.githubusercontent.com/11617892/132439820-f9330bb8-e971-43b6-a877-20cddc698f4a.png)

Version 2021.28

**Comment by computergeek1507** [comment]
fixed with efb9b9f4e52a29c82316acaa426840206fc91ec1
