### ISSUE TITLE
Version 3.2.14 and earlier - Fire will sometimes freeze up

### ISSUE THREAD

**Issue by JonB256** [smeighan/xLights#28]
There is an unexpected interaction between Effect 1 (with Fire) and Effect 2, even if the "Effect1" choice is made in the Combined Effect area. 

For example, if I pick Text for Effect 2, it works fine, but select Spirograph, Tree, Twinkle or Single Strand, and the Fire freezes. All Effect 2 choices "above" Spirograph have no similar effect of freezing the fire motion.

This is all in the Nutcracker Play window. Don't know about Preview after save.

Update - installed prior versions back to 3.2.10 - they do it also.

**Comment by smeighan** [comment]
closing all bugs over 6 months old. We will start tracking issues in Xlights 4.0.
