### ISSUE TITLE
Saving of a file looses some data and errors

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#280]
I load a sequence that was used last year and converted from NC 3.6 to NC 4.0. 
It loads I can see data in most of the channels.
I want to save the file for more editing without destroying the original sequence.
I perform the procedure shown in this video:
https://www.youtube.com/watch?v=Og16FBfnu5U
Error messages appear in the video.
I was using the files in this group here:
https://dl.dropboxusercontent.com/u/28041968/Nutcracker%20Testing/My%20test%20sequences.zip

**Comment by stevegiron** [comment]
It looks like it's trying to read from your F: drive. Do you have an F: volume/drive/disk mounted?
Also the audio at 2:20 loud and clear, nice microphone.

**Comment by MrChristmas2000** [comment]
I do have an F: drive but it is for the dell notebook diagnostics.

Sorry I was sitting on the dining room chair and it is leather, I was wearing shorts and my bare leg scooted across it and made the F... sound. Yea that headset picks up a pin drop. Sometimes those video get a little boring, so that should spice it up :)

**Comment by MrChristmas2000** [comment]
I edited the sequence and changed the file folder and still the same errors.

Note: these files were converted on a different machine as well which it's data drive was on F:

**Comment by AzGilrock** [comment]
You're XML file has a data layer so you had to have already converted this file and added the data layer to point to last years XSEQ file that it references.  Is that source and data path listed below still good?  If not then that's why you lost all that data.  If it can't find the file for the data layer it can't render it's data.

    <DataLayer lor_params="0" channel_offset="0" num_channels="32768" num_frames="2896" data="F:\Tom Data\My Documents\Nutcracker.Xlights media files beta\Carol of the Bells - MASTER FILE_12_09_2014.iseq" source="F:\Tom Data\My Documents\Nutcracker.Xlights media files beta\Carol of the Bells - MASTER FILE_12_09_2014.xseq" name="Carol of the Bells - MASTER FILE_12_09_2014"/>

**Comment by MrChristmas2000** [comment]
Ok, went back and I rechecked the folder path, I had copied the wrong path when updating it earlier. Now it is saving as I would have expected. Excellent. Now off to fix the timing mark thing.
