### ISSUE TITLE
Circle Model - Pinwheel does not render correct in a group - overlay Scaled

### ISSUE THREAD

**Issue by jefft0825** [smeighan/xLights#2801]
The circle model does not render correct when using pinwheel overlay scaled on a circle model.   If you use a custom model - it works fine

Attached a sample show folder - same model - one is using the circle - one is using a custom model that I made in Light Show Hub.   
[Test.zip](https://github.com/smeighan/xLights/files/7150347/Test.zip)

**Comment by computergeek1507** [comment]
The Default render style of Circle model is different that a Custom Model. The Default render style of a Custom Model is a grid layout that overlays the pixel locations. The Circle model's model's default render style is a 2D grid where each circle layer is stretched out into a line and then stacked onto eachother

**Comment by jefft0825** [comment]
Is there a way to fix this?    Or a reason to keep it the way it is?   I see more issues with circle models than any other model and once I make it a custom model, everything works as it should.

**Comment by AzGilrock** [comment]
It can't be changed without breaking all existing sequences.  The Circle model will work just like a Custom model if you select a "Per Preview" type of render buffer which maps the pixels as they appear in space instead of in a convenient line.  Having the render buffer in a line makes many effects work better like a SingleStrand, Marquee, Morph, etc.

**Comment by derwin12** [comment]
I dont know what "overlay scaled" is .. but would it make sense to have "overlay scaled per preview"? That sounds cool, but just bad..

**Comment by computergeek1507** [comment]
"overlay scaled per preview" doesn't make much sense as models are already scaled to the preview based on their size. "Per Model Per Preview" would probably render as desired.

**Comment by keithsw1111** [comment]
This is not a defect but by design.
