### ISSUE TITLE
Model doesn't chain to props spanning multiple ports.

### ISSUE THREAD

**Issue by gleaminx** [smeighan/xLights#2812]
If you add a model in the visualizer to chain after a model that spans multiple ports it keeps trying to set it as the first prop.  Please watch my video at the link provided.

https://youtu.be/ofdf7Ku-V1g

**Comment by derwin12** [comment]
Not the expert here but I *think* that you shouldn't be concerned about the "Beginning" tag - with the visualizer, it uses the absolute addressing. So check that start channel, is it right after the last channel of the prop on that 2nd string? And can you confirm on the controller web page, that the prop does indeed get added to the pixel count on the 2nd string? And the last channel in that second port, is indeed what the controller shows as the last channel for that second prop?

**Comment by keithsw1111** [comment]
Thats not a bug. Entirely expected behaviour and it wont cause a problem. It is the first model on the port ... the second icicle string is not a model on that port but a hangover from the prior port.
