### ISSUE TITLE
Only 2 Pixel Port mappings when adding WLED ESP8266 Controller instead of 3

### ISSUE THREAD

**Issue by bdtrocke** [smeighan/xLights#2814]
**Describe the bug**
When creating a new controller, selecting Generic ESP8266 under WLED only yields two Pixel Port mappings instead of three. When selecting ESP32 I can see all 8 ports. Is this correct behavior? It was my understanding that the ESP8266 should support 3 Pixel outputs. 

**To Reproduce**
Add new Controller set Vendor and Model to WLED and select Generic ESP8266 as the Variant then select Visualize.

**Expected behavior**
Expected behavior is to have 3 total Pixel Ports to map to instead of only 2

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.29

**Attachments**
![image](https://user-images.githubusercontent.com/8836850/134192359-7aa5596a-a3b4-45d0-aace-2a3470cefd2d.png)

**Comment by computergeek1507** [comment]
fixed with 267b2f8d10ed2c456f3775617a5384436f661873

**Comment by patdelaney** [comment]
What hardware board are you using to get the 3 outputs? (Or are you just breadboarding it?)
