### ISSUE TITLE
Xlights to F16v4 over E1.31 stops outputting to lights until reboot

### ISSUE THREAD

**Issue by jstorms** [smeighan/xLights#2817]
Was running the attached test.zip sequence from xlights over E1.31 for about 30 minutes when the F16v4 stopped updating the lights.
I had the bars selected with the mouse on the sequence tab. The controller ran bars for about 30 minutes then the lights froze. Lights are on, but no longer updating.

This happened last weekend and the zoom room guys had be load up a special version of the firmware. 
Falcon_16_V4_Firmware_5.fl3

I can connect via the web and look around and I dumped the log and the config.
While locked I see the Status->E131 Packets Received counts incrementing, but the lights aren't doing anything.
I goto Test and try to turn on a test pattern, but it still is showing bars where it locked up.

I goto Settings and Reboot, lights go off, and after controller reboots the controller resumes outputting to lights.

09/25/2021  02:09 PM           175,611 debug.log.txt
This is the log file downloaded from the f16v4

09/25/2021  02:10 PM             2,961 Falcon_F16V4_2127 (1).json
This is the saved configuation for the F16v4

09/25/2021  02:11 PM         1,732,380 test.zip
This is the test sequence and layout I was running when it locked.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.29 64 bit
 - Falcon_16_V4_Firmware_5.fl3

**Attachments**
attached zip file contains test sequence, layout, the f16v4 log file and config json fi
[test.zip](https://github.com/smeighan/xLights/files/7230254/test.zip)
le

**Comment by keithsw1111** [comment]
This is not an xLights issue. The zoom guys have a beta of build 7 that should address this issue.
