### ISSUE TITLE
Key Bindings has no close button

### ISSUE THREAD

**Issue by pkretche** [smeighan/xLights#2818]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
From File menu, Key Bindings window does not have a close button.  Must use Alt+F4.  Many GUI users won't know this.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to File
2. Click on Key Bindings
3. Window has no cluse button

**Expected behavior**
Expect to be able to close the window with red X button or Close button.

**Screenshots**
![image](https://user-images.githubusercontent.com/91396784/134788939-4dafe721-cbec-49f3-9072-21876cf86582.png)

**Versions (please complete the following information):**
 - OS: All Windows
 - xLights version 2021.29 and prior

**Comment by bcarriveau** [comment]
Its there, its just not shown, expand the window width and you will see it to the right, @keithsw1111 has addressed this small anomaly last night and will be repaired in 2021.30 

Code Commit is here https://github.com/smeighan/xLights/commit/0e38a9ba8e6a235af9b7023d1ff9f6cd7fa2cff0
