### ISSUE TITLE
Side effect of lighting first pixel cyan -- all floods now show cyan in layout :(

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2824]
Perhaps only light the first pixel cyan for a prop if the pixel count is something greater than 1?5? 10? whatever.
Or leave as is and call it a feature :-)

**Comment by AzGilrock** [comment]
Oh geez I haven't seen this change.  I'd say put it back to how it was which was fine.  Anyone that needs to know where pixels are can look at node layout.

**Comment by derwin12** [comment]
It does have a cool reason for it .. it makes it real obvious where your start node is on say matrix, windows etc.

**Comment by AzGilrock** [comment]
Its another piece of info you really don't need very often.  Once you get things setup you most likely never need to see that for years on that model.  I would have rather seen it highlighted only when a model is selected not see blue dots all over the screen all the time assuming that's what's been done from this description.
