### ISSUE TITLE
Automatically Handle Invalid Characters in FPP Connect Uploads

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#2829]
**Is your feature request related to a problem? Please describe.**
Common issue in the xlights zoom is people having invalid characters in the fseq/audio/video filenames resulting in all kinds of odd behavior in FPP from sequences just not playing to fppd restarting.

**Describe the solution you'd like**
Ideally the upload method in FPP connect would strip all invalid characters on upload.  

I think it would also be satisfactory to give a dialog box to the user and inform them that the selected items have invalid characters and prevent the upload.

I understand this will not fix all issues as users can still upload via other methods.  I'm just targeting FPP connect for this feature request.

**Comment by Clyde-L** [comment]
Learned this while using FPP and uploading one of my sequences.  This is a good one to have a popup notification saying the file name has character that FPP can not recognize.

**Comment by ghormann** [comment]
FPP 5.0 and above have code to sanitize the file name.  The files are "renamed" during upload to remove special characters.

Commit: https://github.com/FalconChristmas/fpp/commit/1142fc231a294587b2642c2152776d37515358e7

Sanitization function:  https://github.com/FalconChristmas/fpp/blob/bccb9d95702dd00fcb871f9e1b849c09320f34b8/www/common.php#L2020-L2027

**Comment by MrPaulAR** [comment]
Does that mean that when folks in the zoom room run into issues on 5.x we
should open issues on FPP with their specific example?

**Comment by ghormann** [comment]
@MrPaulAR Having a very specific example would help, especially if fpp is raising an exception or not moving the file out of upload dir
