### ISSUE TITLE
Ability to "move to top" / "move to bottom"

### ISSUE THREAD

**Issue by gothambeat** [smeighan/xLights#283]
When you are configuring the model layouts and adding them, there is currently the ability to move up and move down.  It would be nice to have two additional options.  Move to top and Move to End.

**Comment by AzGilrock** [comment]
I'm not sure we need this now that I look at what we have.  You do know you can select more than one item right?  So if you select the first item and then shift select the second to last item and then hit Move Down it's equivalent to moving the bottom item to the top.

**Comment by AzGilrock** [comment]
Also you can control click to add/remove items for the selection group so you can select item 4 and item 8 and move them both at the same time.

**Comment by AzGilrock** [comment]
With the new functionality checked in for next release you can drag and drop items in the window now so it should be easy to move up or down.
