### ISSUE TITLE
View Log in xLights and xSchedule do not work on Windows 11

### ISSUE THREAD

**Issue by craiz** [smeighan/xLights#2830]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
The Tools -> View Log menu option does nothing.

Possibly related issue is that Check Sequence creates a txt file in the user's temp folder but does not open it in notepad.

**To Reproduce**
1. Use a Windows 11 Insider build.  I don't know if it is a compatibility issue with Windows 11 or not that's just what I have on my machine when I noticed the view log doesn't work.

2. Open xLights or xSchedule

3. Press Tools -> View Log and nothing happens.  I checked my users temp folder thinking the log file may be there (where I see that check sequence files go) which may have been created but not opened and do not see any file that looks like xLights log file.

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2021.30 64bit

**Comment by keithsw1111** [comment]
Do you have a file association set for file types? Unless the OS has a bug I dont see why this would not work ... we just launch the file type and rely on the OS to use the file extension to open the file.

**Comment by craiz** [comment]
It seems it was indeed an OS issue.  I updated to a new Windows Insiders build and the issues no longer repro.

**Comment by AzGilrock** [comment]
I'm glad we have you folks to find all the problems before I ever upgrade.
