### ISSUE TITLE
Check sequence bug on "Model Groups containing duplicate nodes"

### ISSUE THREAD

**Issue by OnlineDynamic** [smeighan/xLights#2831]
**Describe the bug**
Check sequence showing a warning which doesn't seem to make sense (about a duplicate model in a group)

**To Reproduce**
Run a check sequence on the attached rgbeffects file
You will see warning saying:
Model Groups containing duplicate nodes
    WARN: Model group '-Grp All Verts' contains model 'Lounge Window Left/Verts' and model 'Lounge Window Left/Verts' which contain at least one overlapping node (ch 10827). This may not render as expected.

**Expected behavior**
No warning as the 'Lounge Window Left/Verts' sub-model is only in group once

**Screenshots**

**Versions (please complete the following information):**
 - OS:  Windows 10
 - xLights version: 2021.30

**Attachments**
- rgbeffect file
[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/7271212/xlights_rgbeffects.zip)

**Comment by cathelest** [comment]
Check and see if you have a model, and a submodel in the same group,

I had some of my sub models show up in groups that i dont remember adding them to, (eg submodels in an all group)

**Comment by keithsw1111** [comment]
To send us your layout please use tools menu package logs. The attached file is insufficient to reproduce the problem.

As you say the error looks odd but without all the necessary files I cant open your layout.

**Comment by OnlineDynamic** [comment]
Hi @keithsw1111 

Thanks for looking into this - file attached as request
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/7273380/xLightsProblem.zip)
ed

**Comment by keithsw1111** [comment]
So technically the error is correct but it would have been more helpful if we had pointed out in this case the problem is with the submodel ... it includes multiple instances of the same node. That also wont render as you may expect.

**Comment by OnlineDynamic** [comment]
@keithsw1111 interestingly you are right the sub-model definition looks like there is a duplicate node '1' but in the draw model dialog it looks correct - see images attached
![draw_model](https://user-images.githubusercontent.com/68251154/135810339-35cf5fc7-f953-4021-8c88-ec65cdf2d3c3.JPG)
![sub model definition](https://user-images.githubusercontent.com/68251154/135810342-d7edd2d3-0768-4c11-b1fd-904250e73a68.JPG)

**Comment by keithsw1111** [comment]
There are actually 13 duplicate nodes and clicking on that dialog does not fix it.
