### ISSUE TITLE
Single Line only show and work in Horizontial

### ISSUE THREAD

**Issue by Lors1896** [smeighan/xLights#2834]
Hello,

in the Model Preview all Single Lines are Horizontial and they only work Horizontial at the Efect.
![Fehler](https://user-images.githubusercontent.com/91914636/135914243-3c5f6066-5bec-4f36-9363-f126ce830a41.PNG)

I use the new Version Xlights
![Fehler2](https://user-images.githubusercontent.com/91914636/135914266-964c4b20-6c9b-44d8-9e29-3a8e80dfd826.PNG)

**Comment by computergeek1507** [comment]
Change the render style to "Per Preview"

**Comment by computergeek1507** [comment]
All Models have a default model buffer, this buffer is relative to the model not the model preview. Per Preview render style will render effects to the preview.
