### ISSUE TITLE
Scrolling with arrows on keyboard

### ISSUE THREAD

**Issue by tucsonlights** [smeighan/xLights#284]
I think the ability to scroll the effects grid left->right and up->down vice-versa with the keyboard arrows would be a fantastic addition.

**Comment by AzGilrock** [comment]
I added the ability to scroll the grid left/right using Shift + Mouse Wheel.  Mouse Wheel already will scroll it up/down.  We already use the arrow keys for other functions like moving the selected effects so I'd rather not try to make those keys dual purpose.
