### ISSUE TITLE
MAC - xlights Preferences Default View not populated with new views

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2841]
Was in display elements, created a duplicate of Master view, ordered it, called it My Master View.
Went to xlights->preferences->sequence tab and the 2nd drop down only ever showed a checkmark.
Tried going back to menu and saving layout to write that new view to the .xml and repeated the preferences and had the same results -- ie just a check mark it never let us select "My Master View"

**Comment by keithsw1111** [comment]
Is this still a problem?

**Comment by dkulp** [comment]
Yes.   I'm working with the wxWidgets folks on some updates to wxWidgets to fix it: 

https://github.com/wxWidgets/wxWidgets/pull/22169

when we update the build of wxWidgets we use for xLIghts, I'll make sure a fix is included.  I was hoping to update soon, but wxWidgets/master has a few big issues that make it not quite usable right now.

**Comment by derwin12** [comment]
Dan ..  is this okay to close? You think it was addressed with the wxWidgets recently completed?
