### ISSUE TITLE
Matrix not displaying correctly

### ISSUE THREAD

**Issue by ametsman** [smeighan/xLights#2844]
When I start xLights I get this message: Could not calculate start channels for models: Matrix:#100:1. I am running the Matrix from a BBB.When I  created a sequence and used the Matrix, the graphic looked fine in xLights but was not correct on my panel. It was like the panel was split in 2. Attached are some connections. Just did some more testing. Sequences made with 2019 xLights that I haven't edited play fine on my panels. Any new sequences I make, do not.
![Capture](https://user-images.githubusercontent.com/59275876/136610251-d84bf30e-f603-45c0-b67d-94e0046e1ee0.PNG)

**Comment by keithsw1111** [comment]
This is unlikely a bug .... most likely a setup issue. Suggest you pop into zoom and get the guys there to look at it. If after them helping you you still have issues feel free to reopen this with more details such as a copy of the show so it can be reproduced.
