### ISSUE TITLE
A "Your Prop Storeroom" feature

### ISSUE THREAD

**Issue by OnlineDynamic** [smeighan/xLights#2848]
**Is your feature request related to a problem? Please describe.**
Many of us have lots of physical props that we have built over the years, some custom models, some just props that have been wired a certain way (like in reverse by mistake, or with extra null nodes which we just couldn't be bothered to chop out etc...) and as budget and time allow, we gradually build on these collections hidden away in our garages and lofts most of the year.  Each year our layouts need to evolve with the toys we have created throughout the year - this feature would allow us keep track of what we physcially have or need to have on our shopping lists.

It would be cool if you were able to keep an inventory of these props (your own prop store room solution) which kept track of what you had, gave unique id's to the props (which we could label the physical props with) and save their properties so that they can be easily brought into new layouts in xlights alongside the generic and downloadable models that we have today

**Describe the solution you'd like**
Abillty to have an inventory dialog to mange your models. Be able to save models into this inventory from layout view and ability to import from inventory into layout in standard interface.

The inventory area could also hold controllers as well as models.

In the inventory it would be good to have:

- unique prop / controller id's
- physical characteristics of models e.g. voltage,physical dimensions,type of pixel (bullet or square)
- ability to see aggregate views on numbers of nodes across models (this would help with shopping lists when compiling orders)
- sure this list of features would grow with community input

**Describe alternatives you've considered**
currently just try to name props in xlights in a way to help remember special characteristics and import models from previous years

**Comment by keithsw1111** [comment]
There is always the description field and model export. I really dont think this belongs in xLights beyond that.

**Comment by extremeskillz** [comment]
I agree with Keith. I export my custom models to a safe place as they are mine or if I feel like it I will share it on the Xlights Google Drive.
