### ISSUE TITLE
Missing Part of Audio scrub selection v4.1.8

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#285]
I was doing a lot of scrubbing to build a timing track and kept noticing that when scrubbing a section of audio that the playing cursor never completely moved to the end of the selected section as I show in this video.

https://www.youtube.com/watch?v=nAcHak5_3Cg

It clips off the last 50 to 100ms of the audio scrub. This occurs whether you select the audio from the timeline or the audio envelope.

**Comment by MrChristmas2000** [comment]
???? This is more of a bug isn't it?

**Comment by stevegiron** [comment]
Tom, check this out.   http://tinyurl.com/q3nj9mo

**Comment by AzGilrock** [comment]
I really don't think this can be fixed.  We tell windows media play to start and then we tell it to stop.  In between we are servicing events that are firing throughout the windows controls telling things to refresh and causing window invalidates and redraws.  Sometimes mine stops early sometimes it stops a little late.  Sometimes the event to refresh the last draw might lag slightly and then right behind it comes the event telling it everything has stopped and to erase the play line.  You really can't work in a 200ms range and expect to get perfect starts and stops.

**Comment by stevegiron** [comment]
Closing because xLights calls a different library for this functionality.
