### ISSUE TITLE
Built-in Face definition 'Rendered' stoped working after 2021.28 update

### ISSUE THREAD

**Issue by MarkA75160** [smeighan/xLights#2851]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When selecting the built-in 'Rendered' face definition on a model that has other faces defined, it will cause the first defined face to be used instead of the selected 'Rendered' face.   Additionally, the "Show Outline" box must be checked in order to get the mouth movements to follow the phonemes in a timing track.  If "Show Outline" is un-checked then the 'Rendered' face is displayed, but the mouth does not change to match the phonemes in the timing track

If no faces are defined on the model, then selecting 'Rendered' works normally, with or without "Show Outline" checked. 

**To Reproduce**
1. Choose a model that already has faces defined, or add a new face to a model.
2. Create a timing track with lyrics and phonemes
3. Drop a Faces effect on the model and set it to use the phoneme timing track
4. Set the Faces effect to use the 'Rendered' face
5. If "Show Outline" is checked, the first defined face, not the 'Rendered' face will display with mouth movements
6. if "Show Outline is not checked, the 'Rendered' face will display, but no mouth movements.
7. Next, delete all face definition on the model or use another model with no face definitions
8. The Effect now has 'Default' in the Face Definition field and it can't be changed, but it all works as expected (with a 'Rendered' face) when there are no other face definition on the model

**Expected behavior**
The 'Rendered' face type should work with or without other faces defined on a model
AND it should work with or without an outline ("Show Outline box checked or unchecked)

**Screenshots**
![image](https://user-images.githubusercontent.com/57245161/136683538-74dd85b2-0e71-42d4-bb52-b77c729eca29.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: worked in 2021.27, broken in 2021.28 -through- 2021.32

**Additional context**
This worked in 2021.27 and broke in 2021.28 which added the following enhancement:
_**enh (keith) Have face effect use the first assigned face on a model if the effect is calling for a face that is not on the model**_

I believe what's happening is the new code is detecting that 'Rendered' is not an assigned face for the model and thus is forcing the effect to use the first assigned face when there are user-defined faces available.  The code needs to test and see if 'Rendered' is requested in the effect settings and not force the first user-defined face to be used.

I don't know what is going on with the "Show Outline" quirk, but its somehow related because it works properly when there are no other faces assigned.  

**Attachments**
In the attached sequence, model "Tree2" has Face effects set for a 'Rendered' face and Tree2 also has other faces defined on the model.  When the effect plays, the first user-defined face is used instead of the 'Rendered' face - unless you uncheck "Show Outline" then it shows a 'Rendered' face but no mouth movements to match the phonemes

Model "Wind-Dining" has no user-defined faces assigned to it.  However, the Faces Effect sets the Face definition to 'Default' and 'Rendered' does not appear to be an option when there are no user-defined faces.  But it it works as expected with the 'Rendered' (or 'Default' ) face

[Beep Beep Im A Sheep.zip](https://github.com/smeighan/xLights/files/7316926/Beep.Beep.Im.A.Sheep.zip)

**Comment by keithsw1111** [comment]
Some of these issues were new but some are actually as a result of some old xLights 3 compatibility code. I have decided to drop that code and just ensure the face effect works as you would expect on models with and without face effects.
