### ISSUE TITLE
Previewing a Effect Preset before applying to a model.  Enhancement request 

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#286]
I believe that all the code to do this enhancement probably exist.

It would be great to be able to right click on a model in a cell, select the 'effect presets' option, select any preset and see it preview in the Model Preview window before selecting 'Apply Preset'.

**Comment by AzGilrock** [comment]
Actually Presets are more complex than they used to be.  Before a preset only applied to a single model.  Now you can have a preset that contains effects for every model in your layout.  So what exactly do we preview...the whole house?  The way we render changed in XL4.  We used to render the effects on the fly.  Now we multi-thread render to the play buffer so the infrastructure to render a preset like this isn't really built-in anymore.

**Comment by stevegiron** [comment]
Closing this one. An entire sequence can be saved as a preset. That would be a long preview and on too many models.
