### ISSUE TITLE
Cannot edit in AC mode.

### ISSUE THREAD

**Issue by mchaos** [smeighan/xLights#2863]
Using AC mode, some times when I start a sequence, and add the song, I cannot edit in AC mode. I add a timing, and i still can't. I it's like the select arrow is stuck on, but I click to light on, or ramp and it will not ad marker anywhere in song.

It's like some sound files I cannot get it to edit. And some I can some times and others not. This last sequence I was working on, I had to add an MP3 that would let it edit in AC mode, then change the mp3 to what I wanted. It worked up until the end of the song, and all of a sudden, I cannot place markers. I can't do anything.

I can edit in normal mode. But I am using all AC.

Linux Ubuntu, 20.4.. latest xlights, and it happened on a few previous versions.

**Comment by mchaos** [comment]
Doesn't it figure, I post this and I figure it out.. I noticed the main timing track was shorter then the song. Dragging that to the end fixed the issue. I have to look and see if this is what happens on some songs and if I have to drag that for any that don't work. Still a strange bug.. But my issue is done.

**Comment by keithsw1111** [comment]
Because AC mode sequences in timing track cells having a timing track active and with cells in the area you are trying to sequence is mandatory.

**Comment by mchaos** [comment]
Yes, but the issue is that when I start a sequence, and add a timing track, it does not automatically apply the timing track correctly. I have to finagle it. It should just add the track... It's a pain in the but. The next sequence I do I will screen cast it so you can see the issue.

**Comment by keithsw1111** [comment]
Not a very precise description ... maybe you could make a video showing your concern
