### ISSUE TITLE
Small Render Buffer generated on model GROUP for wide layout display

### ISSUE THREAD

**Issue by DonMc33** [smeighan/xLights#2866]
**Describe the bug**
When rendering effects on the GE Priem Cubes set up in a group, some effects, such as the meteor effect, come across very pixelated on the cubes.  This issue was discussed in the Zoom room, the thought was that the way the group was being rendered was due to an unexpectedly small buffer size (66x15)

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Load the attached test sequence
2. Render the sequence
3. Look at the results of the meteor effect in the sequence, from approximately 56 seconds to 108 seconds (see attached "Cube sequence.png" for timing area illustrated)
4. See how the meteors are displayed as groups of pixels on the front of the cubes versus single pixels

**Expected behavior**
Meteor effects would be displayed as single pixels as the effects begin on the cubes, versus groups of pixels (maybe 4 pixels being grouped together where there should be only one).  See the packaged file "
[Test Sequence Small Render Buffer original sequence imported from.zip](https://github.com/smeighan/xLights/files/7360836/Test.Sequence.Small.Render.Buffer.original.sequence.imported.from.zip)
For the expected behavior, approximately 55 seconds to 108 seconds in the sequence on the meteors effect on the model "GE Priem Cube Grp".

**Screenshots**
File "Cube Grouping.png" from a models export shows a buffer size of 66x15 for the "GE Priem Cubes Grp", this issue was discussed in the Zoom room, the thought was that the way the group was being rendered was due to an unexpectedly small buffer size (66x15).  For comparison, when the sequence is opened up in the sequencers show folder, the buffer size for this group is 307x72, as evidenced by the export models group from the sequencers show folder.

"Cube sequence.png" file is to show where in the sequence the effect is located.

"Original Sequence Meteor" is a screenshot with the original sequence show folder opened up and the sequence playing, snipped at the time showing how it should be displayed.

"My meteor".jpg" is a screenshot with my sequence show folder opened up and the sequence playing, snipped at the time showing how it should be displayed.

**Versions (please complete the following information):**
 - OS: Windows 10 Pro
 - xLights version 2021.33

**Additional context**
Other effects, such as text and pinwheels, are also different from what is expected when compared to the original sequence from the sequencer.  The example sequence is only the "Cubes" portion of an imported sequence.

This issue emailed to developers earlier, following up with bug report.

[Test Sequence Small Render Buffer.zip](https://github.com/smeighan/xLights/files/7359969/Test.Sequence.Small.Render.Buffer.zip)
.
![Cube Group](https://user-images.githubusercontent.com/53984565/137631478-2594ba80-7947-4b4f-956c-44ec7015eb51.png)
![Cube sequence](https://user-images.githubusercontent.com/53984565/137631482-6cdc49b4-c74a-436c-a840-495143cd8213.png)
![Original Sequence Meteor](https://user-images.githubusercontent.com/53984565/137633003-8ce4b18d-2bd0-4c1b-b439-f7cf2be1ceac.jpg)
![My Meteor](https://user-images.githubusercontent.com/53984565/137633007-3c8a64ea-6be4-4b6b-ae46-9e734b77dde3.jpg)

**Comment by DonMc33** [comment]
Can I obtain a copy of xlights with this change enabled for use in my show this year since it is a known issue in my layout?  Appreciate the consideration.

**Comment by keithsw1111** [comment]
The problem with that is you get one point in time copy ... I am not going to keep updating it if i cut one. It is also way more likely to have other issues.
