### ISSUE TITLE
Crash to desktop on copy effect on timeline

### ISSUE THREAD

**Issue by samstreak** [smeighan/xLights#2867]
Win10; xLights version 2021.33
Copy via Ctrl-C or via right-click, copy
Spinner, fan effects both, haven't tried others yet
New sequence or opening old, with all models or just adding one to an empty sequence

**Comment by keithsw1111** [comment]
We need a crash log or at least a packaged logs files. Otherwise there is nothing we can do with this.

**Comment by keithsw1111** [comment]
Closing due to lack of response.
