### ISSUE TITLE
Hinks Pix Pro visualize output roll over show showing proper port. 

### ISSUE THREAD

**Issue by stk21** [smeighan/xLights#2869]
![image](https://user-images.githubusercontent.com/32824148/137830733-b6c779c7-5141-4f6b-8b11-eb7128a7aca8.png)

Hey Keith.  Had a user on zoom this evening that had a hinks pix pro, and the fourth channel in the smart receiver was not showing the proper receiver ID.

**Comment by bcarriveau** [comment]
#4256b3d fixed this, will be in next release.
