### ISSUE TITLE
Command Line Check Sequence Output Option to File

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#2872]
**Describe the solution you'd like**
When running the /cs flag it default opens a text editor with the results in a file within the OS tmp folder.  I'm asking for a different option that'll save this to a file in the same folder as the sequence being opened with a name that's the same as the sequence.

**Additional context**
I'm running this on a folder with > 100 sequences overnight.  The result is a bit unwieldy.

Also, if the txt files are in a common folder a user could quickly grep through files to find sequences that have a common problem and batch fix those issues.  Ex: wrong face names, missed timing track from import, etc.

**Comment by keithsw1111** [comment]
With the automation capabilities added i dont think this is required any longer.
