### ISSUE TITLE
Ver 33 lights up a pixel out of face/eyes range

### ISSUE THREAD

**Issue by Darzoom** [smeighan/xLights#2877]
The zip file from today s with version 33.  Using that sequence, it lights up pixel 298 on the Boscoyo ChromaCharacter as if it is part of the eyes in the face definition.  Yet, it is not included as part of the eyes.  The issues does not surface in xLights when running on the screen only.  When output to lights is ran and the sequence ran in xlights, the issue surfaces.  When running the sequence in the earlier dated zip, this is not an issue.  

I am on a Mac and can't go back to the previous version of xLights relative the September date of the zip file.  The same happens when running the sequence in FPP.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to 'xLights turn on output to lights.
2. There is nothing to look at on the xLights screen as it does not surface there. 
3. Check Sequence does not show a pixel issue or overlaps relative to the model in use. 
4. I have no error screen to post as it does not error in xLights or FPP.  It only happens on the actual prop.

**Expected behavior**
Pixel 298 should not light as part of the eyes as it is not defined as part of the eyes.  

[astronaut in the ocean.zip](https://github.com/smeighan/xLights/files/7401635/astronaut.in.the.ocean.zip)

**Screenshots**

**Versions (please complete the following information):**
 - OS: Mac 11.6
 - xLights version 2021.33

**Attachments**
- No crash log was produced

[astronaut in the ocean.zip](https://github.com/smeighan/xLights/files/7401638/astronaut.in.the.ocean.zip)

**Comment by keithsw1111** [comment]
Closing due to lack of followup. If the issue still exists you can reopen the issue.
