### ISSUE TITLE
Edit and/or view a Preset values. Enhancement request

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#288]
Be able to view a presets values and or edit them directly.

**Comment by AzGilrock** [comment]
Again a Preset may contain 4000 effects...it's no longer just 2 effects on a single model.  If you want to alter a preset you gotta lay it into the sequence...edit it....then reselect and hit Update Preset.  If you want to view or edit the values feel free to use a text editor to edit them in xlights_rgbeffects.xml.

**Comment by stevegiron** [comment]
Because a preset can literally be an entire sequence with multiple models and many layers there is no way to implement this. Closing the issue request.
