### ISSUE TITLE
Generating 3 Segment High Submodel for Triple arches doesnt include outer arch

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2892]
From Zoom - see attached.
Created BadArch wit h 3 equal layers of 50 pixels.
Created submodel and the Action to create Segments 3 High.
The Outer segment doesnt "catch" the last layer of pixels and is empty.

**Comment by derwin12** [comment]
[BadArch.zip](https://github.com/smeighan/xLights/files/7447368/BadArch.zip)

**Comment by computergeek1507** [comment]
I have a fix for it but I will probably wait until the new year as it is risky

**Comment by keithsw1111** [comment]
Scott can you check it in commented out or maybe #ifdef-ed out so we dont double make the change.

**Comment by derwin12** [comment]
I will close this ... assuming Scott or Keith will see this and verify / ignore if need be..
