### ISSUE TITLE
Submodel issue

### ISSUE THREAD

**Issue by MWLamers** [smeighan/xLights#2893]
Running Xlights 2021.34
I added a new model to my sequences foe 2021. The new model is made up of several matrix named "New Castle" as well as sub-models, "new outline" and "Windows". These are in groups with the same names.
This spring I started programing my sequences adding the model and sub-models. See video #1.
Recently I continued programming my sequences with the new model. 
I added effects to the programming lines for the sub-models, they worked well. I inserted an effect on the main model line, tested, the sub-models no longer visable. see video 2 & 3.
on a second pc running XLights 2021.34 I built a similar model with sub-models with the same results.
I have attached video and sequences and log files
[Issue 10-30-2021.zip](https://github.com/smeighan/xLights/files/7447725/Issue.10-30-2021.zip)
[Video 1.zip](https://github.com/smeighan/xLights/files/7447726/Video.1.zip)
[xlightsissue 10-30-2021a.zip](https://github.com/smeighan/xLights/files/7447728/xlightsissue.10-30-2021a.zip)
[xLightsProblem10-30-2021.zip](https://github.com/smeighan/xLights/files/7447729/xLightsProblem10-30-2021.zip)

Thank You

**Comment by extremeskillz** [comment]
Similar issue here. I can't even import the submodels from file. 

I'm on the Linux Version.

**Comment by extremeskillz** [comment]
Seems to be working on the latest release, 2021.35. I was able to test by exporting my model with submodels and import it again. Linux appimage of 2021.35 is ok as of right now.

**Comment by MWLamers** [comment]
Not working for me! 2021.35?

**Comment by extremeskillz** [comment]
@MWLamers Try exporting the whole model with sub models and reimporting it. This seemed to work better then importing the sub models independent of the model. It's still a weird behavior but its working for me.

**Comment by MWLamers** [comment]
Thanks!
