### ISSUE TITLE
Text Effect Broken

### ISSUE THREAD

**Issue by Old-Salt** [smeighan/xLights#2897]
_**Describe the bug:**_
The Text Effect was broken with the release of Version 2021.31.  Text Effect worked properly in previous releases.

_**To Reproduce:**_
**Last Working Version:**
1 - Install Version 2021.30
2 - Load Sequence  "Broke Text Effect"
3 - Render and run - note text displays properly
4 - Load Sequence "Christmas Animation"
5 - Render and run - note text displays properly at 00:23, 01:05, 1:49, and 2:27.

**Broken Version:**
6 - Install version 2021.31
7 - Load Sequence "Broke Text Effect"
8 - Render and run - note text is not displayed
9 - Load Sequence "Christmas Animation"
10 - Render and run - note text is not displayed properly at 00:23, 01:05, 1:49, and 2:27.

_**Expected behavior**_
Text Effect works properly for all releases.

_**Screenshots**_
n/a

_**Versions:**_
 - OS: [e.g. Windows 7]
 - xLights version 2021.31

_**Additional context**_
Found when re-rendering Christmas Animation in version 2021.35.  I re-installed previous versions to determine the release where this bug originated.  (2021.35 -> 2021.12, -> 2021.24 -> 2021.30 -> 2021.31)

_**Attachments**_
[Broke Text Effect.zip](https://github.com/smeighan/xLights/files/7468143/Broke.Text.Effect.zip)

[Christmas Animation.zip](https://github.com/smeighan/xLights/files/7468144/Christmas.Animation.zip)

**Comment by dkulp** [comment]
It's likely Windows 7 or the video drivers as we moved text rendering to using DirectX API's.   My suggestion is that we officially drop support for Windows 7.

**Comment by Old-Salt** [comment]
If this is the case:
1. Dropping support for an OS should not be done without notifying the users.
2. As many open issues should be closed as possible before dropping support for an OS.
3. Support for an OS should not be dropped as users enter the busy season.

I suggest that if support for Windows 7 is to cease that this be done between Jan 15, and Apr 30.

**Comment by jdm7999** [comment]
Agreed. Why would a change like that happen right before everyone goes live? Now I need to go back to pre .31 and re-render everything...

**Comment by AzGilrock** [comment]
Well you could also ask why would anyone upgrade xLights right before they are about to go live.  When developers make changes there is minimal testing and there is no regression testing and history shows the chances of new bugs are high with every release.  I would pick a release at least a couple months early and stick with it.

**Comment by monstrousmike** [comment]
I am running on Windows 10 with all of the latest updates and am seeing the same problem with the Text Effect. Going back to .30 did not resolve the issue for me. Fortunately it is one short sequence that I can live without.
