### ISSUE TITLE
Layered Arch Model Missing Layers

### ISSUE THREAD

**Issue by dennismccreery** [smeighan/xLights#2899]
![Layered_Arch_Model_Bug](https://user-images.githubusercontent.com/9154810/140387620-3338832b-aef3-44a0-9c97-16a41bef8251.jpg)
**Describe the bug**
When modeling a Layered Arch, there's no longer any way to insert the number of pixels in each layer.  Also, any existing layered arches don't render properly

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to Layout tab
2. Click on Arches model
3. Drag onto layout to create arch
4. Set Nodes in the Arch to 643
5. Check "Layered Arches"
6. Note that the "Layers" attribute remains a number.  

**Expected behavior**
In 6. above "Layers" attribute should have morphed to a list of layers with number of pixels in each layer.

See attached screenshot

 - OS: Windows 10 64-bit - Build 19043.1288
 - Xlights version: 2021.35

**Comment by keithsw1111** [comment]
Did you try changing the number to say 2 or 3 ... and then expanding the + sign that appears next to it?

**Comment by dennismccreery** [comment]
When you say "the number" I assume you're referring to the number of layers?  That's just it, I don't see a plus sign next to it, regardless of what number is there.

**Comment by keithsw1111** [comment]
Did you press enter or tab after changing the number? Your image shows a 1 and it looks exactly as i would expect it to.

**Comment by dennismccreery** [comment]
I tried pressing enter and tab, still no plus sign.  Attaching an image from a blank test layout.
![Layered_Arch_Model_Bug_Test](https://user-images.githubusercontent.com/9154810/140401167-aebd6f10-4786-4811-9eb8-d50ea5e02ce5.jpg)

**Comment by bcarriveau** [comment]
![Screenshot_20211104-140054_Chrome.jpg](https://user-images.githubusercontent.com/60801063/140403217-ae7403b8-9e6c-471d-bf54-44b3bc524c07.jpg)

**Comment by dennismccreery** [comment]
Ah, thanks I totally missed it since it's in the grey channel and is so small.  Not a bug then, sorry

**Comment by dennismccreery** [comment]
Not a bug, did not see UI element.
