### ISSUE TITLE
Create gh-pages branch

### ISSUE THREAD

**Issue by rawcreative** [smeighan/xLights#29]
To help consolidate things and make releases more accessible to all by having a single page for project info, updates and downloads rather than multiple sites for the various builds I've forked the repo and created a page using Github Pages. I plan on adding more info and sections to the page, and possibly documentation as well. 

It's currently set up to point to files within Github's releases section of the primary repo, while this can easily be changed, GH's releases feature is a great way to easily track everything in one place. I've written a preliminary Grunt task to update version numbers and will modify it to update filenames in the markup as well so as long as the release feature is used with consistent filenames and tags, updating the page to reflect to versions can simply be done with the command 'grunt bump' from the command line (assuming you have node/grunt installed on your system. I can include directions on installing this if needed)

Since PR's have to be on existing branches can someone with push access create a gh-pages branch so I can submit a pull request?

**Comment by AzGilrock** [comment]
Closing because we already have defined locations for our releases.
