### ISSUE TITLE
Layered Arch Rendering Seems Wonky

### ISSUE THREAD

**Issue by dennismccreery** [smeighan/xLights#2901]
1. Go to blank test layout
2. Click on Arch model and drag to layout
3. Check "Layered Arches"
4. Set number of Layers to 8
5. Click plus sign to the left of "Layers"
6. Set Inside to 1, layer 2 to 2, layer 3 to 3, etc through layer 7.  Set Outside to 8
7. Observe rendering on layout.  Looks like it's rendered "inside/out" in that the Inside layer is on the outside and the outside is on the inside, the whole arch is reversed.

I would expect the rendered layout to follow the model.

See attached image for test model.

 - OS: Windows 10 64-bit 19043.1288
 - xLights version: 2021.35

![Layered_Arch_Rendering_Wonkyjpg](https://user-images.githubusercontent.com/9154810/140408310-52e29b6a-ea6c-4585-87b7-ed3d63666ed8.jpg)

**Comment by bcarriveau** [comment]
Besides the layer pixel counts being a bit weird for an arch that has 8 arms, it appears to work correctly as you entered. 

Take a look at the Node layout, Xlights it drawing it  to represent what you entered for the values.

**Comment by dennismccreery** [comment]
Actually, it's being rendered "backwards" so the Outside layer is inside, layer 7 is next, etc. Here's another example, where you can readily see that the outside layer doesn't have 80 nodes.  BTW, this used to work as I would expect
![Layered_Arch_Rendering_Wonky_2](https://user-images.githubusercontent.com/9154810/140600958-615b0358-f896-42eb-94a3-75955bf7e468.jpg)
.

**Comment by dennismccreery** [comment]
BTW, this bug apparently first appeared on release 2021.18.  Prior releases render the layered arch correctly.  Hope this helps in tracking down what was broken.
