### ISSUE TITLE
HinksPix Long Range port ID does not work with cascade remotes

### ISSUE THREAD

**Issue by TrekErs** [smeighan/xLights#2907]
The pop up tool tip in the visualizer will show the port identifier of a 16 port long range and a 4 port long range.  However if a cascade dept of more than 1 is selected the tool tip always shows Port 1 for all ports.

The attached packaged log contains a 16 string mega tree cascaded down 4 smart receivers.  Hover over the various ports and see that Port 1 is always identified.

The ports should show the correct corresponding output port.

 - OS: Windows 11
 - xLights version 2021.35
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/7491737/xLightsProblem.zip)

**Comment by computergeek1507** [comment]
Fixed in 2021.38
