### ISSUE TITLE
Use the Enttex range of Controllers with xLights

### ISSUE THREAD

**Issue by SimonSparksUK** [smeighan/xLights#2909]
I would like to be able to use the Enttex range of Controllers with xLights, please can you look into adding support for them, specifically the Wired Ethernet versions.

https://www.enttec.co.uk/product/controls/addressable-led-pixel-control/din-rail-ethernet-pixel-converter/

**Comment by keithsw1111** [comment]
Without a sample device there is not much we can do to add upload support for them. We could possibly add a controller properties file but it would be purely based on the rather vague information they have on their web site and as such it may or may not work.

**Comment by SimonSparksUK** [comment]
Where in the world are you based ?

**Comment by keithsw1111** [comment]
Australia

**Comment by SimonSparksUK** [comment]
Have you seen this feature table for their products?

https://www.enttec.co.uk/support/supported-led-pixel-protocols/

It looks like the OCTO supports most of the features

https://www.enttec.co.uk/product/controls/addressable-led-pixel-control/octo-din-rail-led-pixel-controller/

I would be willing to donate one of these to you if you can add support for all of the Enttec Products to xLights.

**Comment by keithsw1111** [comment]
I have added a properties file for their controllers based on the spec sheets but they are pretty incomplete and inconsistent so I cant guarantee they are correct. By all means you can send me a device with a web interface for configuration but I cant guarantee building an upload for that product will support all their products ... it may if all their UIs are identical but I doubt that is the case. If they are similar then one product and a bunch of browser traces may make it possible to support all of them with a responsive user to answer questions and run tests.

**Comment by keithsw1111** [comment]
You can grab entec.xcontroller and put it in your xlights application folder and try it today.

**Comment by SimonSparksUK** [comment]
I went and had a route around in the store room and I found an:

Enttec Ethergate Mk3 and an Enttec Pixie Driver 12v

I connected it all up to the network and did a network discovery in xLights.

***@***.***

I connected a long pixel strip and ran it around the room with some extra 12v injectors along the way.

***@***.***

And voila it works, I am going to ask they guys in the office if anyone knows where the other demo kit it as and I will give it a try to.

**Comment by keithsw1111** [comment]
To be clear ... xLights has always been able to run these controllers. The only gap is xLights has no specific capabilities to automate the configuration for these controllers as it does with many others. To use it you just need to get the universes correct for the controller. While these are high end devices their feature set is quite limited compared to hobby controllers which can make them harder to setup.
