### ISSUE TITLE
Ability to right click on a timing track or model and move it up/down in the list  - Enhancement request

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#291]
It would be good to be able to click  on a model or timing track and drag it up or down the list.

This may be a semi repeat but I believe no one has asked for the dragging ability.

**Comment by AzGilrock** [comment]
This one might cost you a few beers. :)

**Comment by keithsw1111** [comment]
This drag and drop ability is in display elements. While I am sure people would like it in the sequencer itself the amount of work involved would be huge for not a lot of value.
