### ISSUE TITLE
Poly Line Dimensions, please show individual Segment dimensions

### ISSUE THREAD

**Issue by dbinit** [smeighan/xLights#2917]
This would really help when modeling my roof line as a single Poly Line.

Thanks!

**Comment by keithsw1111** [comment]
Where exactly would i display it?

**Comment by dbinit** [comment]
I was thinking in the Dimensions zippy, kind of like the Indiv Segments.
<img width="508" alt="Screen Shot 2021-11-12 at 10 09 18 AM" src="https://user-images.githubusercontent.com/77516/141498224-5f09e24b-33ff-4a47-94a8-c4788148c62e.png">

**Comment by keithsw1111** [comment]
This turned out to be simpler and easier to integrate into the UI than i remembered.
