### ISSUE TITLE
FPP Upload Hangs when media exists

### ISSUE THREAD

**Issue by schbrownie** [smeighan/xLights#2918]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When attempting to upload a .fseq files from the FPP Upload utility, XLIGHTS will become unresponsive (aka crash or hang) if the .wav file already exists on the controller.

**To Reproduce**
1.  Open FPP Upload utility
2.  Select controller  (F16v4 controller, latest firmware and V2 Uncompressed FSEQ type)
3.  Selected sequence(s)
4.  Click "upload"
5.  'Dialog' box pops up and displays progress... eventually it hangs at approx 99% complete.  Falcon controller shows file is present, but size is 0B.  

**Expected behavior**
I would expect an error message to appear or something other than a crash/hang with no explanation.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10, all updates complete
 - xLights version = latest (2021.35 and 2021.36... I thought that my last version might be an issue, so I updated and problem still exists)

**Additional context**
I was able to 'fix' the issue and get files to successfully upload.  I found that if there is a .wav file already on the Falcon controller (but no .fseq file), the upload will fail in this mode without warning.  

**Suggstion**:  Add a check during the upload procedure to check if .wav file exists with same name and prompt user to delete .wav file and start over... or promt user if they want to overwrite or skip.... not sure exactly what would work best with XLIGHTS.  

**Attachments**
- None

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
I think i have this fixed for .37 ... at least the part i can reproduce.
