### ISSUE TITLE
Ability to right click on a timing mark and delete that timing mark  - Enhancement request

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#292]
Just the simple ability to click select a timing mark and delete it without having to collapse two marks together.  Sometimes this does not seem to work properly.

**Comment by AzGilrock** [comment]
I don't get this one.  I can select a timing mark and delete it.  You do realize there really isn't such thing as a timing mark but more so a timing range.  We treat them like every other effect.  A timing effect has a start and a finish.  If you click in the middle it will delete the entire timing effect.  If you click a timing edge mark that is really the end of one timing effect and the start of the next timing effect.  So when you delete it removes the one it selected which is probably the one to the left based on the selection logic order.  I think what you're expecting is to click that edge and have it delete the timing effect on both sides of the edge and then join the remaining effects together.  I'll have to think about this now that I know what I think you mean.

**Comment by MrChristmas2000** [comment]
I right clicked on a timing mark, pressed delete and the white bar disappeared between the two remaining marks. I then could not select the effect area between them.

I made a quick video of what I am referring to. If what I am seeing is supposed to work that way, that's ok, I will adjust to the difference.

**Comment by AzGilrock** [comment]
Yeah I understand what you mean.  The timing marks are really the gaps between the tick marks and not the tick marks themselves so once you delete the timing mark there is no effect to select in the gap that remains.  I'm just explaining how it currently works...not saying we won't consider an improvement.  If you start with a blank sequence and then click in the waveform at the 1 second mark it creates a timing mark that begins at zero and ends at 1.0.  Then if you click at 2 seconds it creates a timing mark that begins at 1.0 and ends at 2.0.  So the tick mark you can select at position 1.0 is technically a member of two different timing effects.  The selection logic only selects one of these two when you click on it.  So when you select delete to remove it the effect from 0 to 1.0 disappears and the effect from 1.0 to 2.0 remains.  Now go up and drag a range from 3.0 to 4.0 and hit "t".  Now you will have a timing effect from 3.0 to 4.0 with a gap between 2.0 and 3.0 so you can't select in between them.  Now if you want to bridge that gap I agree there's not a nice way.  You need to create a mark in the middle and then drag it over to magnetically connect to the 3.0 mark.  Maybe if we created a hotkey that would do a fill which would be the opposite of what split does.  Or maybe I add a timing option to the right-click menu and then have a sub-menu under that with several things you could do.  I just need to get agreement from the others before changing any of this.

**Comment by stevegiron** [comment]
Please keep the right click menu short. With 3 of the 4 options related to timing, I agree those could be nested under Timing>Add,Delete, Import for example. The auto-fill between two timing ticks if one is deleted would be a nice add as well.

**Comment by AzGilrock** [comment]
Yeah I don't know.  You already right-click and Import timing from the row headings.  Delete is already there because deleting timing effects is the same logic as deleting any other effect.  In fact you can select timing and effects at the same time and the right-click delete menu deletes them all.  The only thing that might need to change for that part is the right-click menu currently doesn't work on the timing rows.

I'm not sure I like this trend of trying to allow everything to have a way to do things with the keyboard and mouse.  There are plenty of programs where the keyboard is the only way to do certain actions.

**Comment by AzGilrock** [comment]
Forgot I actually implemented this already.  After you select a timing mark you can right-click and select delete. Closing.
