### ISSUE TITLE
Crashes on new seq. multiple show folders when just adding dragging the picture effect to any model.

### ISSUE THREAD

**Issue by earft01** [smeighan/xLights#2920]
Not able to select path it crashes just when adding the default picture effect.  2021.36 (64-bit).  Debug attached.
[xLights_dbgrpt-728-20211109T212635.zip](https://github.com/smeighan/xLights/files/7509384/xLights_dbgrpt-728-20211109T212635.zip)

**Comment by jlange6648** [comment]
Also just had this crash

[xLights_dbgrpt-26028-20211109T212954.zip](https://github.com/smeighan/xLights/files/7509392/xLights_dbgrpt-26028-20211109T212954.zip)

**Comment by earft01** [comment]
Windows 10 - 1909 (64bit)  Render no issues.  Check seq. (new seq.) does mention some overlap and some unused channels that needs corrected but haven't had issues crashing when seen them before for the show folder.

**Comment by bcarriveau** [comment]
can confirm this happen to me ashwell, new seq, drop picture effect, cash.

[xLights_dbgrpt-21276-20211109T203520.zip](https://github.com/smeighan/xLights/files/7509404/xLights_dbgrpt-21276-20211109T203520.zip)



windows 10
2021.36

**Comment by jlange6648** [comment]
Note this only happens when dropping in a picture.. dropping in a "On" then changing the type to picture works fine

**Comment by bcarriveau** [comment]
here is the call stack at the point of crash

>	[Inline Frame] Xlights.exe!ShaderProgram::BindBuffer(int sz, void *) Line 232	C++
 	Xlights.exe!OpenGL33Cache::Draw(DrawGLUtils::xlVertexAccumulator & va, const xlColor & color, int type, int enableCapability) Line 860	C++
 	[Inline Frame] Xlights.exe!DrawGLUtils::Draw(DrawGLUtils::xlVertexAccumulator &) Line 742	C++
 	Xlights.exe!GLGraphicsContext::drawLineStrip(xlVertexAccumulator * vac, const xlColor & c) Line 769	C++
 	Xlights.exe!xlColorCanvas::DrawPalette(xlGraphicsContext * ctx) Line 361	C++
 	Xlights.exe!xlColorCanvas::render() Line 234	C++
 	Xlights.exe!xlColorCanvas::render(wxPaintEvent & event) Line 212	C++
 	Xlights.exe!wxAppConsoleBase::CallEventHandler(wxEvtHandler * handler, wxEventFunctor & functor, wxEvent & event) Line 666	C++
 	Xlights.exe!wxEvtHandler::ProcessEventIfMatchesId(const wxEventTableEntryBase & entry, wxEvtHandler * handler, wxEvent & event) Line 1432	C++
 	[Inline Frame] Xlights.exe!wxEventHashTable::HandleEvent(wxEvent &) Line 1039	C++
 	Xlights.exe!wxEvtHandler::TryHereOnly(wxEvent & event) Line 1628	C++
 	[Inline Frame] Xlights.exe!wxEvtHandler::TryBeforeAndHere(wxEvent &) Line 4007	C++
 	[Inline Frame] Xlights.exe!wxEvtHandler::ProcessEventLocally(wxEvent &) Line 1561	C++
 	Xlights.exe!wxEvtHandler::ProcessEvent(wxEvent & event) Line 1534	C++
 	Xlights.exe!wxEvtHandler::SafelyProcessEvent(wxEvent & event) Line 1650	C++
 	Xlights.exe!wxWindow::HandlePaint() Line 5319	C++
 	Xlights.exe!wxWindow::MSWHandleMessage(__int64 * result, unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 3097	C++
 	Xlights.exe!wxWindow::MSWWindowProc(unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 3883	C++
 	Xlights.exe!wxWndProc(HWND__ * hWnd, unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 2925	C++
 	[External Code]	
 	[Inline Frame] Xlights.exe!wxWindow::MSWSafeIsDialogMessage(tagMSG *) Line 2790	C++
 	Xlights.exe!wxWindow::MSWProcessMessage(tagMSG * pMsg) Line 2672	C++
 	Xlights.exe!wxGUIEventLoop::PreProcessMessage(tagMSG * msg) Line 142	C++
 	Xlights.exe!wxGUIEventLoop::ProcessMessage(tagMSG * msg) Line 160	C++
 	Xlights.exe!wxGUIEventLoop::Dispatch() Line 227	C++
 	[Inline Frame] Xlights.exe!wxEventLoopManual::ProcessEvents() Line 234	C++
 	Xlights.exe!wxEventLoopManual::DoRun() Line 288	C++
 	Xlights.exe!wxEventLoopBase::Run() Line 87	C++
 	Xlights.exe!wxAppConsoleBase::MainLoop() Line 377	C++
 	Xlights.exe!wxEntryReal(int & argc, wchar_t * * argv) Line 504	C++
 	Xlights.exe!wxEntry(int & argc, wchar_t * * argv) Line 175	C++
 	[External Code]

**Comment by keithsw1111** [comment]
Until .37 turn off the effect assistant.
