### ISSUE TITLE
LIFE Effect broken in newest releases, works in release 2021.33 but not in 35 or 36 (not sure about release 34)

### ISSUE THREAD

**Issue by wkhundley** [smeighan/xLights#2921]
Drop the LIFE effect in any sequence (new or existing) and nothing happens! This happens in both the 2021.35 and 36 release versions, I skipped 34 so I'm unsure if it's also present in that version. Reverted my xlights installation back to 2021.33 and the effect works just fine.  Windows 64 Bit installation

UPDATE: 34 works fine, issue exists in release 35 & 36

**Comment by cosborn71** [comment]
Same for me ... Tested in the following:
MacOS 11.6 - working up to 2021.35, broken in 2021.36
Win 10 Pro build 21H1 - working up to 2021.34, broken in 2021.35 and 2021.36 

I noticed that if you make the effect really short, it will flash on and off (still not doing what the effect should). If the effect is spread across a second or more it basically appears to do nothing.

**Comment by keithsw1111** [comment]
Dan fixed this i believe
