### ISSUE TITLE
chained cloned (copy and pasted) models to inherit future changes from parent model

### ISSUE THREAD

**Issue by oderbang** [smeighan/xLights#2923]
**Is your feature request related to a problem? Please describe.**
Problem is you have multiple custom models all the same and you want to add sub models...or make the same change to all those models you have to do it over and over.. 

**Describe the solution you'd like**
Chain copied models to their parent they where "cloned" from.. so you make a change to the parent model the changes cascade down to the child models.

**Describe alternatives you've considered**
You have to either edit one and copy past replace model with this... ok but still a pain as you have to re line everything up re do the controller affiliation etc

**Additional context**
none

**Comment by keithsw1111** [comment]
This does not work as a concept as it opens a whole can of worms related to inheritance sometimes and not others, breaking etc ... all just to save some one time work ... its not worth the user issues it would create.
