### ISSUE TITLE
Drag multiple models around in layout view

### ISSUE THREAD

**Issue by tbtgspence** [smeighan/xLights#2924]
When selecting multiple models in 2D view (holding CTRL), if you then try to click and drag the multiple selections, it deselects all but he model you tried to drag.  If you are clicking on a model that is already selected and attempt to drag, it should not deselect the other models, but should drag them all.

You can work around this by using the arrow keys to move the models once they are all selected, but dragging would be much easier as it takes time to get them positioned correctly using the arrows.

**Comment by AzGilrock** [comment]
Hold down shift to move the selected models

**Comment by tbtgspence** [comment]
Checked into this, it's actually CTRL.  Confirmed that if you continue holding CTRL when clicking multiple models, you can drag all of them.  Good to know, but the behavior isn't consistent with industry-standard apps that allow multiple object selection, like Adobe Illustrator.  Even in Windows Explorer, if you CTRL-Click multiple files and then let off the mouse, you can click-hold-drag on any of them to move all the files without it deselecting the rest.

Thank you for the info, this will certainly help.

**Comment by AzGilrock** [comment]
xLights is becoming the new industry standard.  Pretty soon you'll be complaining to Adobe that they don't work like xLights. :)

By the way it works different in 3D mode.  There you can select them all and move the group using the handles.  I guess in 2D shift is for group selection.  That's what I get for answering without being in front of my xLights PC.

**Comment by AzGilrock** [comment]
I think one of the main reasons it works that way is because its not always easy to click on a model so it was too easy to deselect everything which can be frustrating.  I know in 3D mode that was definitely the case.  Also in 3D mode we needed to be able to click and rotate the screen around while models were selected and again it was real easy to accidentally click on a model since some of them have huge selection zones.

**Comment by tbtgspence** [comment]
No problem, thanks for the reply.
