### ISSUE TITLE
Change double-click behavior of controller to open Visualizer

### ISSUE THREAD

**Issue by tbtgspence** [smeighan/xLights#2926]
Currently double-clicking a controller defaults to opening it in a browser.  Through my usage over the past year or two, since adding the visualization feature, I feel like defaulting to opening the Visualize interface would be a better choice for double-click.  Since you are moving towards doing most of the controller config from within xLights, there is less of a reason to go to the controller's web interface.  So this fits more in line with the additions of the visualizer and other "Full xLights Control" features.

**Comment by keithsw1111** [comment]
If i implement this i'll just get the other 50% of users complaining about it ... just like we did with double clicking on effects.

**Comment by tbtgspence** [comment]
I get that.  People resist change.  I think as long as you make the
decision that is best for the software going forward, you will always have
to deal with some of those people.

**Comment by keithsw1111** [comment]
Then you understand why i am not going to implement this.

**Comment by tbtgspence** [comment]
It seems you are moving to an xLights-centric configuration model where you
don't have to do config through the web interface.  As more and more people
use the visualizer, you will eventually come back to this and make the
change.  :)
