### ISSUE TITLE
V36 House Preview Playback - Very Choppy on MAC

### ISSUE THREAD

**Issue by byakymyk** [smeighan/xLights#2927]
After upgrading from V35 to V36 House Preview playback of sequence is very choppy.  Reverted back to V36 and everything fine.

OS: Mac 12.0.1 - MacBook Pro 16" 2019 (Intel)
xLights version V36

**Comment by byakymyk** [comment]
V37 House Preview playback continues to be choppy

**Comment by byakymyk** [comment]
Don't know if this has anything to do with the choppy playback but Preferences -> OpenGL Setting keeps resetting to V1.x/2.x when I change it to V3.x

**Comment by danjamescrosby** [comment]
Having the same issue here. It seems to be just animation (no music) sequences that are affected for me.

**Comment by byakymyk** [comment]
V38 fixed choppy playback
