### ISSUE TITLE
Adding Prop to end of another multiport prop flags for Gap in models when using remotes

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2928]
From Zoom..
Create a multiport Tree prop - 4 ports. Make it an A Remote.
Add a star to the last port following that Tree.
Now go an add something on the first port, Remote B and it will flag the start as a gap.
Now it is *just* a warning .. not clear if it stops the push or an error. Can this be confirmed?

![image](https://user-images.githubusercontent.com/4643499/141232096-c7ae14a7-10d2-48d3-a165-1e6df62c26f1.png)

**Comment by derwin12** [comment]
Ryan confirmed you get a warning on the upload but it DOES push to the controller as a virtual string. So is this okay then?

**Comment by derwin12** [comment]
Ryan's version to duplicate the issue..

![image](https://user-images.githubusercontent.com/4643499/141233422-c7a708dd-7a4a-4aca-872e-8554d139c225.png)

**Comment by derwin12** [comment]
Related to hanging Terry's V4. He has sent Keith his f48 hang on pixel port page file ctrlcfg.dat

**Comment by bcarriveau** [comment]
Try a Ctrl Shift R ;-)

**Comment by keithsw1111** [comment]
It is only a warning and it has to do with how xLights does its autolayout. The controller will still work.

As for your other problem when you update the firmware you must clear your cache (which ctrl-shift-R does) to ensure you are using the latest web assets.
