### ISSUE TITLE
Spinner Center Alternate Counter Clockwise Odd

### ISSUE THREAD

**Issue by pottenmak** [smeighan/xLights#2929]
**Is your feature request related to a problem? Please describe.**
A few years ago I created 3 spinners, i've wired them Center Alternate Counter Clockwise and created a custom model for them (25 Lights/Arm).
Now I see you can select "Starting Location" "Alternate Counter Clockwise", in wiring view the order is 1, 25, 2, 24, 3, 23, ...
But I used 25, 1, 24, 2, 23, 3, ... (first pixel on the second place), saved me some place

**Describe the solution you'd like**
Would it be a lot of work to add "Alternate Counter Clockwise Odd", where the first pixel is on the second place ?

**Describe alternatives you've considered**

**Additional context**
<img width="128" alt="Schermafbeelding 2021-11-11 om 17 46 22" src="https://user-images.githubusercontent.com/5180547/141336530-b56b0fc8-0b1d-4b37-bc58-0069139afe88.png">
.

**Comment by keithsw1111** [comment]
Not going to do this. If you want to use our alternate wire it that way ... if not export it as a custom model and renumber it your way.
