### ISSUE TITLE
XL Crash when importing a papagayo (PGO) effect - 4.1.18

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#293]
Attached (drop box link) is a debug report (three  instances) of an xl crash at 4.1.8 when attempting to import a papagayo created pgo file into xl.

https://www.dropbox.com/s/4qhcukhdx0gdk6t/xlCrashPgoInput.zip?dl=0

In addition to the content of the debug report , I have also included 
-	the input pgo file (Little Drummer Boy_v2part1.pgo) ,  
-	the xml being written to (Little Drummer Boy_papa2) 
-	a copy of the xml before it crashes (Little Drummer Boy_papa2_in)
-	a screen print of the  parameters during input.

Note that I have successfully imported other pgo files including Voice 1 of the same song, so not sure why this is crashing.

Process followed :
1.	Created and saved a  sequence  Little Drummer Boy_papa2 , with two models - Singing faces and Singing faces 2.
2.	Created a backup copy of this seq and called it  Little Drummer Boy_papa2_in.
3.	Shut down xl and opened it again.
4.	Clicked on papagayo tab
5.	Select papagayo file (Little Drummer Boy_v2part1.pgo)
6.	Select output seq file (Little Drummer Boy_papa2). Accepted warning message that seq will be overwritten.
7.	Chose output type – Coro faces
8.	Selected previous preset , amended details and saved as ‘CoroPGOPreset2. Saved that preset.
9.	Clicked on create new sequence. Xl crashed
10.	Note: I am not sure whether after saving the preset , if the saved preset actually represents what is on the screen – may be worth checking if that is the cause, as I think that it may contain both Voice 1 and 2

**Comment by stevegiron** [comment]
Hi, is this still an open issue for you? If not can you please close the issue. Thanks.

**Comment by gerry4** [comment]
I dont think it has been addressed , but am closing it . In case someone else tries to import and it fails , then can look at it again..
