### ISSUE TITLE
crash each time I try and add a photo

### ISSUE THREAD

**Issue by ScubaJ** [smeighan/xLights#2930]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
A clear and concise description of what the bug is .
I drag and drop "pictures" into my sequence, I stretch it out a bit and then in "effects settings" I click browse and pick my photo. and as soon as I try to move it left or right on the sequencer, I get the bug every time and its happened on a couple songs.
![BUG](https://user-images.githubusercontent.com/94133557/141368584-189c978a-b617-4ec9-83a3-9d24c5331c34.png)
 

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.
I expect to be able to add a picture and move it into the right timing spot without a crash

**Screenshots**
screenshot added

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]
 - version 2021.36

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked
[xLights_dbgrpt-16552-20211111T135118.zip](https://github.com/smeighan/xLights/files/7523236/xLights_dbgrpt-16552-20211111T135118.zip)
.
[xLights_dbgrpt-16552-20211111T135118.zip](https://github.com/smeighan/xLights/files/7523237/xLights_dbgrpt-16552-20211111T135118.zip)

[xLights_dbgrpt-16552-20211111T135118.zip](https://github.com/smeighan/xLights/files/7523239/xLights_dbgrpt-16552-20211111T135118.zip)
[xLights_dbgrpt-7924-20211111T102053.zip](https://github.com/smeighan/xLights/files/7523240/xLights_dbgrpt-7924-20211111T102053.zip)
[xLights_dbgrpt-4088-20211111T093352.zip](https://github.com/smeighan/xLights/files/7523241/xLights_dbgrpt-4088-20211111T093352.zip)
[xLights_dbgrpt-2008-20211110T082219.zip](https://github.com/smeighan/xLights/files/7523242/xLights_dbgrpt-2008-20211110T082219.zip)

**Comment by computergeek1507** [comment]
Will be fixed in the next release
