### ISSUE TITLE
Xlights 2021.36 Crashing

### ISSUE THREAD

**Issue by Lenchuckd** [smeighan/xLights#2933]
Just upgraded to latest version.  When I drag a photo onto my mega tree, xlights crashes... time and time again, can't get around it.  Error report has been sent.

**Comment by computergeek1507** [comment]
Already been fixed for the next release, hopefully someone will make a new release soon

**Comment by computergeek1507** [comment]
Workaround is to disable the effects assistant in File->Preferences
