### ISSUE TITLE
Crash when selecting existing picture effect on matrix to change location of picture file

### ISSUE THREAD

**Issue by swoolf1341** [smeighan/xLights#2934]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Crash when selecting existing picture effect on matrix to change location of picture file

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to Matrix
2. Click on First picture effect on row 2 (starts at 0:00.000)
 At this point I get a debug report

**Expected behavior**
Should let me change where to find the picture file

**Screenshots**
None

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version [e.g. 2021.36]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked
[xLights_dbgrpt-528-20211112T112037.zip](https://github.com/smeighan/xLights/files/7529911/xLights_dbgrpt-528-20211112T112037.zip)
[Away In A Manger.zip](https://github.com/smeighan/xLights/files/7529913/Away.In.A.Manger.zip)
.

**Comment by dkulp** [comment]
Fixed in 2021.37

**Comment by swoolf1341** [comment]
Thank you Daniel!
