### ISSUE TITLE
xLights freezes when Importing sequence

### ISSUE THREAD

**Issue by booshka207** [smeighan/xLights#2936]
This occurred in 2021.36 and 2021.37.  Though I went back to 2021.34 and it occurred.

I can successfully:  New Sequence > Musical Sequence > Choose audio file > Quick Start > Done.

However, when I go to Import sequence, the log at the bottom of the screen displays 'Effects Loaded: 100%', but xLight freezes.  There's no crash or error log.  The normal prop mapping doesn't appear.
I've let it sit over night incase it was taking (excessive) time, but it stays frozen.  If I click on any part of the screen, I get the 'bling' audio sound, but can't select anything.

I've attempted this on sequences that I have already successfully imported and saved, but the same issue occurs.

**Comment by keithsw1111** [comment]
Sounds to me like there is a popup window off screen somewhere ... hit alt+ space then m then down arrow key then move the mouse.

If that doesnt work view/windows/reset to defaults

If that doesnt work run xlights with the /w command line switch

**Comment by booshka207** [comment]
Thanks Keith, the alt/space/m method worked
