### ISSUE TITLE
2021.37 no vertical sequence grid lines

### ISSUE THREAD

**Issue by skipit79** [smeighan/xLights#2938]
**Describe the bug**
Upgraded to 2021.37 and the vertical sequence grid lines have gone away.

**To Reproduce**
Occurs in old sequences and newly created sequences. 

**Screenshots**
Screenshot attached.

**Versions (please complete the following information):**
 - OS: [Windows 10
 - xLights version [2021.37]
![Capture](https://user-images.githubusercontent.com/94211099/141605430-b5dcdeff-2ee6-45a4-ad0c-fcb50c25bc10.JPG)

**Comment by computergeek1507** [comment]
do you have a timing track with timing marks?

**Comment by dkulp** [comment]
Definitely there on OSX.   I'll take a look though.  They might be too thin for the the non retina type displays.  

<img width="446" alt="Screen Shot 2021-11-13 at 7 07 30 AM" src="https://user-images.githubusercontent.com/91569/141643337-a0a1f641-45b4-481c-aaa7-60526bec7899.png">

**Comment by skipit79** [comment]
I don't have a timing track yet in my sequence with marks, but I just added a test track and I can see the marks just fine.  I downgraded to 36, they appear in that version.  I'm using a 4K monitor 3840x2160.

**Comment by keithsw1111** [comment]
It is definitely broken on windows.
