### ISSUE TITLE
Font size in sequencer components view list

### ISSUE THREAD

**Issue by pcarff** [smeighan/xLights#2940]
**Is your feature request related to a problem? Please describe.**

The font size of the components in the view list is too small.
![fontsizexlights](https://user-images.githubusercontent.com/810652/141687081-159ca27d-d2f8-4a5d-a4f5-1a5d4c2c85c3.png)

**Describe the solution you'd like**

Be able to change the font size.

**Describe alternatives you've considered**

**Additional context**

**Comment by computergeek1507** [comment]
Go to Files->Preferences, under the Effects Grid Tab, the grid spacing drop-downs chances the size.
