### ISSUE TITLE
Repeatable consistent crash

### ISSUE THREAD

**Issue by chuckackerman** [smeighan/xLights#2942]
In this sequence (Fantasmic) when I click on the Picture effect on the Garage Matrix model around the 2:41 mark the program crashes and produces the attached zip file.   This happens every time. 

I'm running 2021.36.
[xLights_dbgrpt-18400-20211115T074520.zip](https://github.com/smeighan/xLights/files/7540350/xLights_dbgrpt-18400-20211115T074520.zip)

**Comment by computergeek1507** [comment]
Fixed in .37

**Comment by chuckackerman** [comment]
Thanks.
