### ISSUE TITLE
Feature request: support importing sequences from passworded zip files

### ISSUE THREAD

**Issue by scardus** [smeighan/xLights#2944]
Many of the sequence zip files on the xlights shared drive are encrypted with a password.  This results in an error when you try to import a sequence directly from the zip. 

Please add support to prompt for a password when a password protected zip file is detected.

**Comment by keithsw1111** [comment]
As long as the wxZipInputStream continues to not support passwords I doubt this is going to happen. I have little interest in implementing this from scratch. Reading their posts this seems exceptionally unlikely so the only other way this could get added is us moving to a new library and that would be such a large rewrite effort that again this would be well down the list but as you say desirable.
