### ISSUE TITLE
Navigation enhancements - cosmetic

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#295]
Hello,
Am adding these cosmetic enhancement items , in the event that any of them are simple to implement and/or the developers happen to be changing that functionality.

1. When creating a new sequence or opening an existing one , after the dialogue is complete (and the icons enabled) , default to the Sequencer tab (and show the sequencer details) , rather than the setup tab details. 
2. When adding models to the sequencer (or now at 4.19. to a View ), when the sequence elements windows is closed , the user is 'taken to outside xlights' rather than to the previous open xlights screen. It kind of gives an impression that xlights has ended abruptly. Happens most of the time , but not always (Windows user)
3. Add a 'Save as'  option to the Pop down list of the File Menu (same use as the 'Save as' icon). Noticed when I started doing the documentation that this was not there.

**Comment by cjd** [comment]
Item 1 is implemented in https://github.com/smeighan/xLights/commit/55f35abfd60ea34a7043b17aceece58e3bee8340
Item 3 was added a while ago - visible as "Save Sequence As" now rather than "Save As Sequence" to clarify its purpose.
Not sure how to fix up item 2 though

**Comment by gerry4** [comment]
Hi ,
Yes , One was fixed some time ago.  Than you. I updatee the manual , but must check the text used if it has changed.
For item 2 , is it that you cannot simulate the problem or can , but not sure how to fix it ?
If the former , then I can recreate as it often occurs and let u know which steps causes it.
If not sure how to fix it , then suggest that you leave it as it is not such an issue and it may cause more harm then good trying to fix - others have reported it as well , but on fb.
Regards

Gerard

Date: Sun, 20 Sep 2015 21:36:16 -0700

**Comment by cjd** [comment]
For item 2 - I assume you mean the dialog that is titled "Display Elements" - and this dialog is actually a panel (and so can be docked in with the other items such as "Effect Settings" and so it doesn't have the main window as it's parent.
Thereby the main window isn't always given focus when the panel closes

**Comment by gerry4** [comment]
Hi Chris, yes it is the window which opens when u right click and select 'Edit Display Elements' from the sequencer grid.
It says Sequence Elements on the top of the window (when it opens) and yes , i see that it is the same as one of the Display Element window from the View,Windows tab. It seems to be the only when that sometimes "loses xlights focus" is takes you to the Windows desktop. How does it normally know what to return focus to and if nothing else , is it possible to default to the sequencer tab (if 'the focus is null') - or is it not that simple. If complicated , am happy to close the issue as not worth spending tiome on when there are better things for you guys to work on. thanks for fixing the default to the sequencer tab when u open a sequence. I saw that today 4.1.13 !

**Comment by cjd** [comment]
There isn't much that could be done other than changing it to a stand-alone dialog - and that would break multiple other things.
The parent/focus is not set in the code itself but rather it is in how wxwidgets itself handles focus so I don't think there is anything specific that can be done.
If the big re-organisation of the interface happens (after christmas) it may be able to be fixed then

**Comment by gerry4** [comment]
Thanks Chris >
