### ISSUE TITLE
Horizontal matrix rendering discrepancies

### ISSUE THREAD

**Issue by reelpilot** [smeighan/xLights#2953]
**Describe the bug**
I'm using P5 panels to create a vertical pixel poles. The P5 panels are driven by a ColorLight card which only supports a horizontal matrix configuration. Despite creating the same buffer as a vertical pixel pole by having the poles set as horizontal and the # strings set to 384 and the nodes/string set to 64, the same effect renders completely different compared to a true vertical pole set as vertical and # strings 64 and nodes/string 384.

**To Reproduce**
Setup two different matrix poles. The only one that works with a ColorLight is set as "horizontal" with # strings 384 and strands/string 64. The second matrix is set as "vertical" with # strings 64 and strands/string 384. Put both in the same group and apply a single strand effect with chases 5, chase size 2 and render style of vertical per model. See video link below.

https://youtu.be/SVs8kekcvyE

**Expected behavior**
Previously I've used P10 panels for my pixel poles and they were controlled by a raspberry pi and a matrix hat. That allowed the poles to be configured as a vertical matrix and all my effects in countless sequences were based on this. Unfortunately ColorLight cards do not support a vertical matrix and the panels must be configured horizontally. (see link below) In xLights by setting the horizontal matrix as 384 strings and 64 strands/string it then creates the same vertical buffer as a true vertical matrix. Most effects render as expected with the exception of the single strand effect in this configuration.

https://youtu.be/ven9L1HYJsM

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.33 (issue is present on all versions that I have tried)

**Attachments**

[P5 Panel Demo.zip](https://github.com/smeighan/xLights/files/7577475/P5.Panel.Demo.zip)
.

**Comment by keithsw1111** [comment]
This is not a bug. That is the correct render buffer. When you change the model from horizontal to vertical it changes the way the strands run and this buffer follows the strands.

**Comment by dkulp** [comment]
If using FPP to drive the colorlights, you could keep the old vertical configuration in xLights and just have FPP map it to the colorlight horizontal setup.
