### ISSUE TITLE
Insert Playlist Immediately does not resume Virtual Matrix video 

### ISSUE THREAD

**Issue by MikelMD** [smeighan/xLights#2956]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I am running 3 FPP Pi’s on 4.6.x.  I have a Master and two slaves, one a virtual matrix (a TV) the other a Mailbox w/ a sensor.  When I play a sequence, say I have a sequenceName.fseq on the Master and a sequenceName.mp4 on the Virtual Matrix Pi.  When the mailbox sends a GPIO trigger to the Master, the master runs an event “Insert Playlist Immediately”.  This stops the current sequence, run a specified sequence, Santa.fseq and send the same command to the Virtual Matrix which pauses the current video and runs Santa.mp4.   Thus far, all works great.  The issue is, after Santa.fseq and Santa.mp4 runs and the sequenceName.fseq returns at the point of pause, the virtual Matrix is still paused at sequenceName.mp4.

This occurs w/ every one of my sequences - the video is at a paused state.

**To Reproduce**
Have a sequence with a virtual matrix video
run the "Insert Playlist Immediately"
this should pause the current sequence (and video) and insert a new sequence and video.
When the inserted sequence and video ends, BOTH the sequence and the video that was paused should continue.
Currently, only the sequence continues, the Virtual Matrix video is paused at the point of when the "Insert Playlist Immediately " command was issued.

**Expected behavior**
The expected behavior is after the "Insert Playlist Immediately" has concluded, and the original FSEQ sequence picks up where it was paused, that the Virtual matrix does the same.

**Screenshots**
Not applicable, since you need to see it on the Virtual Matrix

**Versions (please complete the following information):**
Windows 10
xLights version 2021.36

**Additional context**

**Attachments**
Attached fseq files and mp4 videos - https://www.dropbox.com/sh/khnlxa5nyvu98os/AAC7e5WjPUKl684RdhQ1OudFa?dl=0

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
Sounds like a FPP issue not xLights

**Comment by MikelMD** [comment]
Since I am running 4.6.x I will upgrade to 5.3 to test.

**Comment by dkulp** [comment]
This is an fpp issue, not xLights
