### ISSUE TITLE
Edit Display Elements Seems to be Broken

### ISSUE THREAD

**Issue by Cboehm00** [smeighan/xLights#2958]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When I Right Click on the elements list and click "Edit Display Elements" nothing happens

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to 'Any sequence'
2. Click on 'Right Click the Display Elements List'
3. Scroll down to 'Edit Display Elements'
4. See error - Doesn't do anything at all

**Expected behavior**
Should bring up list of display elements to add and remove from sequence,

**Screenshots**

**Versions (please complete the following information):**
 - OS: [Windows 10]
 - xLights version 2021.38

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
Odds are it is just appearing somewhere you cant see ... go to view - windows - and choose dock all ... if that does not work try reset to defaults and restart xlights if you still cant see it.
