### ISSUE TITLE
Rendered windows not loading properly

### ISSUE THREAD

**Issue by zachsteffens** [smeighan/xLights#2959]
Layout and Sequence tabs were working fine yesterday.

When I logged in today they were no longer rendering properly.
Large chunks of the UI just do not render. 
Nothing in the windows event logs and no application crashes.
Tried installing the update (ver 2021.38) tried to uninstall and reinstall.
Several machine reboots, no luck

Only thing that changed since yesterday was I received a microsoft update (kb5007186)

![xlightsSequence](https://user-images.githubusercontent.com/8375389/142964867-5337bc8c-3c33-483c-877e-35a97e9d6b05.png)
![xlightsLayout](https://user-images.githubusercontent.com/8375389/142964877-f0a36ba0-fc60-4597-89a4-03a9080f2c25.png)
.

**Comment by keithsw1111** [comment]
Update your video drivers ... the MS update has broken it.
