### ISSUE TITLE
DMX Control effect

### ISSUE THREAD

**Issue by tucsonlights** [smeighan/xLights#296]
Add an effect named DMX control with a slider bar from 0-255 than we can drop on to the timeline to control dmx fixtures like moving head lights,  foggers, and lasers.

**Comment by damon-atkins** [comment]
I suggest its completed as an object,  you can label the object e.g. "swinging light 1", and add as many DMX channels and label the channels.   e.g.  Horizontal, Vertical.

**Comment by AzGilrock** [comment]
Closing. Forgot we had this issue listed when I implemented the DMX effect.
