### ISSUE TITLE
Build error in Linux

### ISSUE THREAD

**Issue by mase76** [smeighan/xLights#2961]
Hi!
Since the last versions I have a build error in Debian Gnu/Linux Bookworm:
`xLightsMain.cpp: In lambda function:
xLightsMain.cpp:1794:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
 1794 |         std::this_thread::sleep_for(std::chrono::seconds(3));`

**Comment by computergeek1507** [comment]
What version of gcc are you using?

**Comment by mase76** [comment]
I use gcc-11.2.0.

**Comment by computergeek1507** [comment]
I assume the std library headers changed for c++20, I will have to look at it. The build server uses gcc9 and it is working.

**Comment by dkulp** [comment]
Can you see if adding "#include <thread>" to the top fixes it?

**Comment by mase76** [comment]
Yes, adding "#include <thread>" would fix it. I had also to add it to controllers/Falcon.cpp.
But where must I add the linker option -lzstd?

**Comment by mase76** [comment]
The linker option is still missing.
/usr/bin/ld: cannot find -lzstd

**Comment by computergeek1507** [comment]
Did you run apt-get install libzstd-dev

**Comment by mase76** [comment]
Oh! I thought, this is a part of libstdc++-dev. My fault.
