### ISSUE TITLE
Batch render - Sequence Element Mismatch

### ISSUE THREAD

**Issue by lewislawrence2** [smeighan/xLights#2965]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]. I am attempting a batch render of sequences before uploading to my controller.  In a few sequences, I receive a notice - Sequence Element Mismatch.  I select "Rename this element to," then pick a new element.

Each time I do another batch Render, I get the same error.

**Describe the solution you'd like**

I think that once i select rename this element, it should be permanent, and not ask me again the next time i do a batch render. 

**Describe alternatives you've considered**

i could remap the sequence, but seems like the renaming should be done when the error is found.

**Additional context**

**Comment by keithsw1111** [comment]
This is not going to change ... batch render is the worst time to be forced to make a permanent decision about a sequence.
