### ISSUE TITLE
Not saving settings during batch render prompts

### ISSUE THREAD

**Issue by OnlineDynamic** [smeighan/xLights#2967]
**Describe the bug**
If a sequenece references an mp3 file which has changed location - during the batch render process a prompt window comes up to select the new location.  This works as expected and the sequence then renders. However the new location selected isn't save to the sequence properties so next time the sequence is opened again the mp3 location is still missing

**To Reproduce**
move mp3 for sequence to new folder
try to batch render sequence
put new location of mp3 in popup window
allow sequence to render
close everything down and reopen the sequence

**Expected behavior**
to remember the newly selected location

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.38

**Comment by dkulp** [comment]
I'm at a point now where I think if Batch render cannot load a sequence without errors, it should skip that sequence and at the end, display a warning dialog that says "You need to fix these sequences".

**Comment by keithsw1111** [comment]
This is not going to change ... batch render is the worst time to be saving changes as the user is typically just trying to get through the render. If you cant keep your sequences in good repair ... batch render is not for you.

**Comment by OnlineDynamic** [comment]
@dkulp I agree.... just closing this bug saying if you hit this error condition tough luck because your a numpty user doesn't seem like a good response to those trying to contribute to the community.  If the sequence has errors and you are just trying to get through the queue it shouldn't prompt for user input at all
