### ISSUE TITLE
Build broken on Void Linux

### ISSUE THREAD

**Issue by the-maldridge** [smeighan/xLights#297]
I'm trying to build using the supplied makefile and I receive the following error:
```
g++ -DwxUSE_UNICODE -std=gnu++0x -O2 -std=c++0x -Wall `wx-config --version=3.0 --cflags` -Winvalid-pch -DWX_PRECOMP -DNDEBUG -Wno-reorder -Wno-sign-compare -Wno-unused-variable -Wno-switch -Wno-unused-but-set-variable -Wno-parentheses -Wno-return-type -Wno-uninitialized -Wno-unused-value -Wno-sequence-point -Wno-comment -Wno-unused-function  -Iinclude -Isequencer -I../xLights -c ChannelMapDialog.cpp -o .objs/ChannelMapDialog.o
g++: error: ChannelMapDialog.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
xLights.cbp.mak:604: recipe for target '.objs/ChannelMapDialog.o' failed
make[1]: *** [.objs/ChannelMapDialog.o] Error 1
make[1]: Leaving directory '/home/maldridge/Documents/xLights/xLights'
Makefile:23: recipe for target 'xLights' failed
make: *** [xLights] Error 2
```

I have also tried building using Code::Blocks, but this fails being unable to find portions of wx despite having installed version 3.0.2.  Any suggestions are appreciated.  Additionally if someone can tell me who I need to contact to get permission to package this, I'd be greatful.

**Comment by AzGilrock** [comment]
We have someone that usually keeps the Linux build up to date but not as often as the other platforms so the Linux release lags behind.  Usually we are adding a lot of new files so most of the time the Linux makefile just needs updating to include the new stuff.  Not sure what you mean by needing permission to package this.  I think the Linux builds are already being hosted somewhere but I'd have to check with the others.

**Comment by the-maldridge** [comment]
So I should in theory be able to check out an older version and package that, is that correct?  As far as permission I have always found it to be bad form to just package and send to a repo without the project's permission.  I can assure you that this is not packaged currently for Void linux.

**Comment by AzGilrock** [comment]
Ok now I know what mean by packaging it.  I'd need to see how the other developers feel about it.  The program is currently changing fairly rapidly with new features so they may want to wait for a more stable version.  Right now we are still in beta releases but I expect an official release soon since an Expo is upcoming.

**Comment by cjd** [comment]
The build issue should be fixed now.
When this occurs you can manually re-run the cbp2make (or just remove xLights/xLights.cbp.mak and it will automatically rebuild)

**Comment by the-maldridge** [comment]
Hm, I'm still running into an issue building, though it got much furthur this time.  The failure occurs during the linking phase:

```
.objs/TabPreview.o: In function `xLightsFrame::OnButtonPreviewOpenClick(wxCommandEvent&)':
TabPreview.cpp:(.text+0x1358): undefined reference to `SaveChangesDialog::SaveChangesDialog(wxWindow*)'
.objs/SeqFileUtilities.o: In function `xLightsFrame::CloseSequence()':
SeqFileUtilities.cpp:(.text+0x31bd): undefined reference to `SaveChangesDialog::SaveChangesDialog(wxWindow*)'
collect2: error: ld returned 1 exit status
```

A ways above that, it was hunting for 'gstreamer-interfaces' but I believe this to be unrelated.

**Comment by AzGilrock** [comment]
Undefined reference to SaveChangesDialog means the makefile is not updated to build the SaveChangesDialog.cpp file I added recently.

**Comment by the-maldridge** [comment]
Okay, I have gotten it to build by regenerating the makefile from the code::blocks one.  Should I PR the new makefile in, or leave that to your existing *nix contributor?

**Comment by cjd** [comment]
I'll commit the changes shortly - I just hadn't rebuilt since the save changes dialog was added

**Comment by cjd** [comment]
This should be fixed by commit https://github.com/smeighan/xLights/commit/f6aed3a210b7af1a11c8dc7fb23ec2755f956373
