### ISSUE TITLE
Bug in Layout "Controller: Use start channel"

### ISSUE THREAD

**Issue by blardyblar** [smeighan/xLights#2971]
This seems to be a bug (or I really don't understand how "Use Start Channel" for the controller setting is supposed to work.

Steps to Reproduce:
FPP PB16 controller on network
160 pixels attached to one port (happens to be a differential expansion port, but I don't think the bug is specific to that port type) of the PB16 - first 150 on one prop (say a tree), and next 10 on second prop (say the star on top of the tree).

New (empty) xLights show folder
Add PB16 controller to Xlights using DDP
  -leave default settings on controller:
  -Auto Layout Models: yes / checked
  -Auto Upload Configuration: yes / checked
  -Auto Size: yes / checked
  -Full xLights control: no / unchecked
Add a model to the layout, the tree:
  -Set controller to the above added controller
  -Set the pb16 output channel of the model
  -Set number of pixels: 150
  -This model works fine
Add a second model to the layout, the star on the above tree:
  -Set controller to "Use Start Channel"
  -Set start channel to the end of the tree model above
  -Set number of pixels: say 10
Enable light output (which also sets up the FPP player settings)

Actual outcome:
xLights sends all 160 pixels worth of data to the controller (FPP shows DDP receiving channels 1-480) but the second model wasn't setup in the controller, so only the pixels of the first model actually get data from the controller. In the channel outputs section, the tree has been added to the chosen port with 150 pixels, but the star on top is completely missing

Desired outcome:
xLights sets up both the models under that channel of the controller and sets the number of pixels in each accordingly

Workaround:
If instead of choosing "Use Start Channel" for the controller on the second model, if you explicitly choose the right controller and do everything else the same, it works correctly, and sets up both models in the controller with the correct number of pixels in each, so they actually work. The real issue is "Use Start Channel" for the controller option seems broken - at least with a DDP connected PB16 FPP controller.

**Comment by computergeek1507** [comment]
xLights has two start channel "modes", if you have auto Layout Models and Auto size enabled, xLights will determine channels by the Controller drop-downs and the controller port. When you select use start channel xLights uses the old start channel code and this will not trigger the auto size to increase. Either Use the visualizer and it does it all for you, or disable auto layout models and do it all manually.
