### ISSUE TITLE
Foreign characters are now not working in Singing Faces and Lyric tracks

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#2975]
From Zoom.
"Sweden Daniel" found that lyric tracks with foreign characters resulted in the singing face "not singing". Renamed the track and it worked.
Foreign characters in the file paths and/or the singing face in the layout also resulted in blank singing faces. Deleting these faces and re-adding using plain english worked fine.
These were sequences that worked prior (last year?). So perhaps some unexpected consequences to changes in the plumbing of xlights.

**Comment by keithsw1111** [comment]
Do we have the sequence?

**Comment by derwin12** [comment]
I will see if I can get it from him.. 
This was "red bulb" röd glödlampa
So perhaps as simple as Download red bulb from singing faces and use that name. I will see if I can duplicate as well.

**Comment by derwin12** [comment]
[SpecialChars.zip](https://github.com/smeighan/xLights/files/7642437/SpecialChars.zip)
I downloaded the red bulb to my mini matrix - gave it the sweedish name.
Created sequence and timing track . Works for other faces but nothing for röd glödlampa
