### ISSUE TITLE
Display elements are invisible when Pixel Style is set to "Smooth"

### ISSUE THREAD

**Issue by ceefit** [smeighan/xLights#2977]
When a new display element is added to the layout - the `Appearance -> Pixel Style` defaults to `Smooth`. In this mode, the pixels are not visible on the screen. Any other setting (`Square`, `Solid Circle`, `Blended Circle`) renders properly and yellow pixels are visible.

**To Reproduce**
1. Navigate to Layout Tab
2. Create any new display element (Arches, Single Line, etc)
3. It will not be visible.
4. Set the `Appearance -> Pixel Style` to another value.
5. The pixels are now visible

**Expected behavior**
The `Smooth` pixel style should render a visible element when the option is selected.

**Screenshots**
![Working](https://user-images.githubusercontent.com/40200212/144453495-db6be4d3-ac3b-4411-805c-8d5f6bb1f161.png)
![Not Working](https://user-images.githubusercontent.com/40200212/144453501-437f78a8-d260-4b53-9117-2576f41f0e7d.png)

**Versions (please complete the following information):**
 - OS: [Arch Linux / Gnome 41.1 / X11]
 - xLights version [2021.38]

**Comment by keithsw1111** [comment]
Update your video drivers. If this was a general bug as stated everyone would be experiencing it.

**Comment by ceefit** [comment]
The drivers appear to be the latest as of today.

```
❯ nvidia-smi
Thu Dec  2 14:23:38 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 495.44       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   52C    P8     1W /  N/A |      4MiB /  3914MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
```

**Comment by ceefit** [comment]
I was able to resolve this issue by invoking the xLights AppImage with `prime-run`.
