### ISSUE TITLE
Select All / Deselect All checkboxes on Batch Render Dialog

### ISSUE THREAD

**Issue by OnlineDynamic** [smeighan/xLights#2982]
**Is your feature request related to a problem? Please describe.**
Have 50-60 sequences to render from a directory - currently have to manually go and check the box next to each file name which is time consuming

**Describe the solution you'd like**
Add a 'select all' and 'deselect all' option on the batch render window

**Comment by jefft0825** [comment]
You can.   Right click them

**Comment by OnlineDynamic** [comment]
@jefft0825 thankyou! thats a well hidden little gem!
