### ISSUE TITLE
Select All / Deselect All checkboxes on FPP Upload dialog

### ISSUE THREAD

**Issue by OnlineDynamic** [smeighan/xLights#2983]
Is your feature request related to a problem? Please describe.
Have 50-60 sequences to render from a directory - currently have to manually go and check the box next to each sequence file name which is time consuming

Describe the solution you'd like
Add a 'select all' and 'deselect all' option on the fpp upload window for selecting sequences

**Comment by jefft0825** [comment]
This is also already in there.   Right click the boxes and click select all

**Comment by computergeek1507** [comment]
Already exists
