### ISSUE TITLE
Support null pixels at end of props

### ISSUE THREAD

**Issue by TechplexEngineer** [smeighan/xLights#2984]
**Is your feature request related to a problem? Please describe.**
I have the Boscoyo Chroma Cane Mini 48s, when I pushed the pixels in I left the extra two pixels at the end. This worked great until I wanted to daisy chain the two crhoma canes so I could plug them into the same controller port. It seems that xlights supports configuring start null pixels which partially solves the problem. However the frustration is when moving props around I have to remember to remove the start null pixels. It seems like the info about the ending null pixels should be attached to the model that the null pixels are part of.

**Describe the solution you'd like**
Ideally there would be an additional option added to models "Set End Null Pixels" just below "Set Start Null Pixels"

**Describe alternatives you've considered**
Change how the pixels are pushed into the prop.
Manually keep track of the null pixels when moving props around :(

**Comment by bcarriveau** [comment]
Fpp based and the new Falcon controllers can do it.  It is controller dependent.

**Comment by keithsw1111** [comment]
This is a controller issue ... not an xLights issue. xLights supports end nulls where the controller does.

**Comment by TechplexEngineer** [comment]
Sorry my bad, I would swear that option wasn't there yesterday, But it clearly is today. Thanks!
