### ISSUE TITLE
fickering  leds when uploading layouts on falcon controller

### ISSUE THREAD

**Issue by sanmas999** [smeighan/xLights#2986]

**Comment by keithsw1111** [comment]
This is not an adequate description of a problem and it almost certainly has nothing to do with xLights. Controller behavius during upload is undefined ... it could do anything. If your have problems after the upload describe the specific settings on the controller that are wrong including images of the controller configuration and a copy of your layout created using Package Logs on the tools menu.

If you are able to provide all that please attach it to this issue and reopen it.
