### ISSUE TITLE
xSchedule Ignoring Refire Frequency

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#2992]
**Describe the bug**
When creating a schedule, the refire frequency is ignored.
Instead of triggering every 10-15-30 minutes (as you set it), on application startup the schedule starts playing immediately as long as you are within the overall time window of the schedule.

**To Reproduce**
See attached ZIP. This contains three playlists & three schedules (no sequences, just 'set-color' steps for ease).

**Expected behavior**
Intermission (Priority 5) should start at 10:00 and run on loop till 22:00.
Show 1 (Priority 7 with an Every 30 min refire) should interrupt at 10 AM, 10:30 AM, etc.
Show 2 (Priority 7 with an Every 30 min refire) should interrupt at 10:15 AM, 10:45 AM, etc.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights V2021.37

[xLightsTestDir.zip](https://github.com/smeighan/xLights/files/7671251/xLightsTestDir.zip)

**Comment by merryoncherry** [comment]
I think this would get reopened.  I have seen it happen with the fix of #3474.
