### ISSUE TITLE
Crash on close

### ISSUE THREAD

**Issue by ptr727** [smeighan/xLights#2994]
**Describe the bug**
Crash on close.

**To Reproduce**
Lauch xLights, got new version notification, downlaod new version, close xLights, install new version, launch xLights.
Create a simple one icicle layout and sequence, upload to FPP on PiZero, close xLights, crash on close.

**Expected behavior**
No crash.

**Screenshots**
NA

**Versions (please complete the following information):**
 - OS: Win11
 - xLights: 2021.39

**Additional context**
NA

**Attachments**
Project folder with crash report attached.
[xLights.Test.Crash.zip](https://github.com/smeighan/xLights/files/7677262/xLights.Test.Crash.zip)

**Comment by ptr727** [comment]
I had a few more crashes with 39, normally when saving a sequence, the submit error dialog briefly shows then disappears, as if it is also crashing.
Upgraded to 40, save, crash, error dialog briefly shows and goes away.
Is there another way to collect crash dumps?

**Comment by keithsw1111** [comment]
Is this still an issue?

**Comment by ptr727** [comment]
I've not been using xLights recently.
I'll report again if it still happens with a current version.
