### ISSUE TITLE
MQTT events not working with Xscheduler

### ISSUE THREAD

**Issue by Zaxxore** [smeighan/xLights#2996]
I have created  2 MQTT events and they don't work. I tried with firewall disabled witn same result. I'm using version 2021.39. Here is the log when I start Xscheduler.

> 2021-12-09 06:49:17,830 5428 log_base [INFO] Listener thread for MQTT running.
> 2021-12-09 06:49:17,831 5428 log_base [DEBUG] ListenerMQTT connected to 192.168.0.156:1883
> 2021-12-09 06:49:17,832 13232 log_base [INFO] starting server on 0.0.0.0:80...
> 2021-12-09 06:49:17,832 18532 log_base [DEBUG] Pinging thread BonHomme started
> 2021-12-09 06:49:17,832 13232 log_base [INFO] server running on 0.0.0.0:80
> 2021-12-09 06:49:17,833 13232 log_base [DEBUG] Adding IPs to ping.
> 2021-12-09 06:49:17,833 13232 log_base [DEBUG] Update the playlist tree.
> 2021-12-09 06:49:17,833 13232 log_base [DEBUG] Creating buttons.
> 2021-12-09 06:49:17,837 5428 log_base [DEBUG] ListenerMQTT listening
> 2021-12-09 06:49:17,840 13232 log_base [DEBUG] Schedule loaded.
> 2021-12-09 06:49:17,844 5428 log_base [INFO] MQTT subscribing to topic xSchedule/PlayList.
> 2021-12-09 06:49:17,844 5428 log_base [INFO] MQTT subscribing to topic xSchedule/Toggle.
> 2021-12-09 06:49:17,844 5428 log_base [ERROR] MQTT client has disconnected.
> 

It looks like it connect to the broker, it works and it disconnect.

If I open the MQTT events I get that in the log:

> 2021-12-09 06:59:35,467 13232 log_frame [WARN] Timer: Frame event fire interval 8ms less than 1/4 frame time 12ms
> 2021-12-09 06:59:49,200 13232 log_base [WARN] MQTT trying to subscribe to topic xSchedule/PlayList but listener not in a good state.
> 2021-12-09 06:59:49,200 13232 log_base [WARN] MQTT trying to subscribe to topic xSchedule/Toggle but listener not in a good state.
> 

Here are the events details:

![image](https://user-images.githubusercontent.com/45795267/145393287-24a78218-efb5-45c1-9bbb-268d58836caf.png)

![image](https://user-images.githubusercontent.com/45795267/145393421-3bd9bf7c-4413-43e4-af0e-2d305ac27401.png)

Any idea ?

**Comment by keithsw1111** [comment]
As best I can tell this only happens if your MQTT broker closed the connection ... does its logs say why it did?

**Comment by Zaxxore** [comment]
Here is the info in the MQTT broker log:
1639189373: New connection from 192.168.0.113:49292 on port 1883.
1639189373: New client connected from 192.168.0.113:49292 as xScheduleEvent1 (p2, c0, k0, u'mqtt').
1639189373: No will message specified.
1639189373: Sending CONNACK to xScheduleEvent1 (1, 2)
1639189373: Bad socket read/write on client xScheduleEvent1: Invalid arguments provided.

**Comment by keithsw1111** [comment]
So there is something the server does not like and it closes it? Maybe there is a problem with the event? Does the other event work?

**Comment by Zaxxore** [comment]
I have deleted the event1 to keep only the event2 and got about the same result:
2021-12-13 20:06:33,391 74640 log_base [DEBUG] MQTT listener starting.
2021-12-13 20:06:33,391 74640 log_base [INFO] Listener thread for MQTT created.
2021-12-13 20:06:33,391 74640 log_base [WARN] MQTT trying to subscribe to topic xSchedule/Toggle but listener not in a good state.
2021-12-13 20:06:33,391 74640 log_base [WARN] MQTT trying to subscribe to topic xSchedule/Toggle but listener not in a good state.
2021-12-13 20:06:33,391 74640 log_base [WARN] MQTT trying to subscribe to topic xSchedule/Toggle but listener not in a good state.
2021-12-13 20:06:33,391 74640 log_base [INFO] Allocated frame buffer of 510 bytes
2021-12-13 20:06:33,391 32484 log_base [INFO] Listener thread for MQTT running.
2021-12-13 20:06:33,394 32484 log_base [DEBUG] ListenerMQTT connected to 192.168.0.156:1883
2021-12-13 20:06:33,394 74640 log_base [INFO] starting server on 0.0.0.0:80...
2021-12-13 20:06:33,394 74576 log_base [DEBUG] Pinging thread BonHomme started
2021-12-13 20:06:33,395 74640 log_base [INFO] server running on 0.0.0.0:80
2021-12-13 20:06:33,395 74640 log_base [DEBUG] Adding IPs to ping.
2021-12-13 20:06:33,396 74640 log_base [DEBUG] Update the playlist tree.
2021-12-13 20:06:33,396 74640 log_base [DEBUG] Creating buttons.
2021-12-13 20:06:33,403 74640 log_base [DEBUG] Schedule loaded.
2021-12-13 20:06:33,403 32484 log_base [DEBUG] ListenerMQTT listening
2021-12-13 20:06:33,404 32484 log_base [INFO] MQTT subscribing to topic xSchedule/Toggle.
2021-12-13 20:06:33,404 32484 log_base [ERROR] MQTT client has disconnected.

From MQTT broker:
1639443869: New connection from 192.168.0.113:61419 on port 1883.
1639443869: New client connected from 192.168.0.113:61419 as xScheduleEvent2 (p2, c0, k0, u'mqtt').
1639443869: No will message specified.
1639443869: Sending CONNACK to xScheduleEvent2 (1, 2)
1639443869: Bad socket read/write on client xScheduleEvent2: Invalid arguments provided.
1639443906: Received PINGREQ from 2OeQFP71cAHEht9MnTHj5i
1639443906: Sending PINGRESP to 2OeQFP71cAHEht9MnTHj5i
1639443966: Received PINGREQ from 2OeQFP71cAHEht9MnTHj5i
1639443966: Sending PINGRESP to 2OeQFP71cAHEht9MnTHj5i
1639443992: New connection from 192.168.0.113:61358 on port 1883.
1639443992: New client connected from 192.168.0.113:61358 as xScheduleEvent2 (p2, c0, k0, u'mqtt').
1639443992: No will message specified.
1639443992: Sending CONNACK to xScheduleEvent2 (1, 2)
1639443992: Bad socket read/write on client xScheduleEvent2: Invalid arguments provided.

**Comment by keithsw1111** [comment]
Do we know what "1639443992: Bad socket read/write on client xScheduleEvent2: Invalid arguments provided." from MQTT means?

**Comment by keithsw1111** [comment]
This article seems to suggest this is related to a mosquito change: https://forum.micropython.org/viewtopic.php?t=11076&p=60836. From the associated ticket https://github.com/micropython/micropython-lib/issues/445 it seems like maybe it is a keepalive problem but the error message is seriously unhelpful. If that is the problem it would sure help if their logs said it was. Maybe there is an increase in debug level you can turn on to work out exactly what your version of MQTT broker is complaining about. Making random changes in the hope of guessing what its issue is seems counter productive as it is likely to introduce as many issues as it resolves.

**Comment by keithsw1111** [comment]
I have added the code to set the timeout but I have left it disabled for now in the hope we will get some certainty about this.

**Comment by Zaxxore** [comment]
Here is the logging setting in Mosquitto. I can't have more.
log_type error
log_type warning
log_type notice
log_type information

**Comment by ingenthr** [comment]
I ran into seemingly the same behavior (based on looking at the logs) with @dustin 's mqttd.  He noticed the keepalive being 0 is okay by the spec, but wasn't a case that had been handled.  xSchedule is setting keepalive to 0.

He also noticed that the mosquitto_sub CLI doesn't allow this:
```
$ mosquitto_sub -k 0 -h mqtt -t '#'
Error: Invalid keepalive given, it must be between 5 and 65535 inclusive.
```

From the packet capture, all of my other clients are doing a keepalive of 30 or something along those lines.  I don't see a way to configure this in xSchedule's client at the moment.  I'm guessing that this is probably needed though unless TCP keepalive is being configured.

**Comment by dustin** [comment]
I do think this is a broker bug.  I've [fixed my broker](https://github.com/dustin/mqttd/commit/af3ae795d11e1d46a4d3a2a529ae5c85d8dbd1be) to support receiving zero.  I expect others might also run into this.

I'm glad I did, though.  I've not run into a bug in my broker in a long time. :)

**Comment by ingenthr** [comment]
The fix from @dustin made the logs happier and xSchedule mostly work.  There's a minor complaint in my logs…

```
2022-10-31 16:44:38,044 7512 log_base [DEBUG] Trying to read MQTT packet.
2022-10-31 16:44:38,044 7512 log_base [ERROR] Unexpected MQTT Packet: 9.
2022-10-31 16:44:38,059 3212 log_base [DEBUG] Checking the schedule ...
2022-10-31 16:44:38,059 3212 log_base [DEBUG]    Active scheduled playlists: 0
2022-10-31 16:45:00,061 3212 log_base [DEBUG] Checking the schedule ...
2022-10-31 16:45:00,061 3212 log_base [DEBUG]    Active scheduled playlists: 0
2022-10-31 16:45:20,212 3212 log_frame [WARN] Timer: Frame event fire interval 11ms less than 1/2 frame time 12ms. 1 events skipped.
2022-10-31 16:45:45,596 7512 log_base [DEBUG] Trying to read MQTT packet.
2022-10-31 16:45:45,637 7512 log_base [DEBUG] MQTT Topic: fld/xScheduleWinPC/Event.
2022-10-31 16:45:45,722 7512 log_base [DEBUG] Event fired MQTT:playlist -> Play specified playlist:halloween2022
```

**Comment by armorer1984** [comment]
I'm also getting this issue with my Xlights connection to my Mosquitto broker. It would be nice if Xlights would set a 30 sec keepalive and reconnect if the ping to the broker failed in the event of a half connection.

As it sits right now, I can't get my broker to accept a 0 keepalive.

**Comment by armorer1984** [comment]
> The fix from @dustin made the logs happier and xSchedule mostly work. There's a minor complaint in my logs…
> 
> ```
> 2022-10-31 16:44:38,044 7512 log_base [DEBUG] Trying to read MQTT packet.
> 2022-10-31 16:44:38,044 7512 log_base [ERROR] Unexpected MQTT Packet: 9.
> 2022-10-31 16:44:38,059 3212 log_base [DEBUG] Checking the schedule ...
> 2022-10-31 16:44:38,059 3212 log_base [DEBUG]    Active scheduled playlists: 0
> 2022-10-31 16:45:00,061 3212 log_base [DEBUG] Checking the schedule ...
> 2022-10-31 16:45:00,061 3212 log_base [DEBUG]    Active scheduled playlists: 0
> 2022-10-31 16:45:20,212 3212 log_frame [WARN] Timer: Frame event fire interval 11ms less than 1/2 frame time 12ms. 1 events skipped.
> 2022-10-31 16:45:45,596 7512 log_base [DEBUG] Trying to read MQTT packet.
> 2022-10-31 16:45:45,637 7512 log_base [DEBUG] MQTT Topic: fld/xScheduleWinPC/Event.
> 2022-10-31 16:45:45,722 7512 log_base [DEBUG] Event fired MQTT:playlist -> Play specified playlist:halloween2022
> ```

What did you do to Mosquitto to accept the 0 keepalive?

**Comment by dustin** [comment]
Your suggestion above is a workaround for a bug in mosquitto.  @ingenthr is using [my mqtt broker](https://github.com/dustin/mqttd) which also had this bug, but no longer does.

**Comment by armorer1984** [comment]
Ok, for Mosquitto, here is the fix:

Go into your mosquitto.conf file and add the following:

`max_keepalive 0`

Close the conf and systemctl restart mosquitto

As a side note, it would be nice if xScheduler would behave with a keepalive and ping the MQTT broker every 60 seconds or so.
