### ISSUE TITLE
Effects show up different in two different tree types with submodels

### ISSUE THREAD

**Issue by nmiller0113** [smeighan/xLights#2997]
**Describe the bug**
I noticed when using submodels on two different tree types, flat and round, that the impact/mixing of effects on submodels vs the main model was treated differently between the different tree types even though they have the exact same effects placed on them. I created a test sequence that shows this which is packaged and attached. I also attached a screenshot.

**Expected behavior**
Minus the shape of the tree, the impact of the effect should generally be the same, unless this is expected behavior between different tree types.

**Screenshots**
<img width="677" alt="Screen Shot 2021-12-09 at 7 48 51 AM" src="https://user-images.githubusercontent.com/1048868/145430031-8b9603e7-9072-431b-a144-ba4fa77ab12d.png">

**Versions (please complete the following information):**
 - OS: Mac 11.6.1
 - xLights version: 2021.39

**Attachments**
[bugtest.zip](https://github.com/smeighan/xLights/files/7686546/bugtest.zip)

**Comment by dkulp** [comment]
This is just the way the models are drawn on screen.   The 3d tree has blue nodes behind the red "front" nodes so OpenGL will blend them together on screen a bit.   If you flip to 3D view, you can see that the actual data is as expected. 
<img width="540" alt="Screen Shot 2021-12-09 at 11 03 58 AM" src="https://user-images.githubusercontent.com/91569/145432589-4fada5a5-15ec-4288-9aae-749fba05459e.png">

**Comment by nmiller0113** [comment]
Thanks @dkulp! Well crap, I feel bad even bothering you all with this. It was an illusion the whole time. I went back and checked the sequence you and I were discussing in email and that fully supports what you're saying. Sorry to bother!
