### ISSUE TITLE
Crash creating Horiz. Matrix

### ISSUE THREAD

**Issue by Materdaddy** [smeighan/xLights#30]
Using the latest revision (c04dfc1 at the time of this bug creation) I receive a crash in the linux build when trying to create a Horizontal Matrix.

I rolled back to the revision I had been using for a while and tried it, same crash.  It must have been around for a while: 6f1f581 was the old revision I also tried.

Steps to reproduce:
• Click Nutcracker tab
• Click "Models"
• Click "New"
• Name it and enter the following parameters:
  · Horiz Matrix
  · RGB Nodes
  · 1 String (default)
  · 50 Nodes (default)
  · 1 Strand (default)
  · Start Channel 1 (default)
  · Bottom Left (default)
• Click "OK" on the new model creation window
All appears to be well at this point, but the next step causes a crash:
• Click "OK" ok the models list window
• Kaboom!

Here's a stack trace from gdb, unfortunately I'm not a wx guy, so it means little to me:
#0  0x00000000004b783e in wxXmlNode::GetParent (this=0x0) at /usr/local/include/wx-2.9/wx/xml/xml.h:151
#1  0x0000000000495c56 in xLightsFrame::ShowModelsDialog (this=0x7fffed6fa010) at TabSequence.cpp:548
#2  0x0000000000495db4 in xLightsFrame::OnButton_ModelsClick (this=0x7fffed6fa010, event=...) at TabSequence.cpp:561
#3  0x00007ffff5f5cc9f in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/local/lib/libwx_baseu-2.9.so.5
#4  0x00007ffff60adf72 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/local/lib/libwx_baseu-2.9.so.5
#5  0x00007ffff60ae326 in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () from /usr/local/lib/libwx_baseu-2.9.so.5
#6  0x00007ffff60ae3c6 in wxEvtHandler::TryHereOnly(wxEvent&) () from /usr/local/lib/libwx_baseu-2.9.so.5
#7  0x00007ffff60ae483 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /usr/local/lib/libwx_baseu-2.9.so.5
#8  0x00007ffff60ae4e5 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/local/lib/libwx_baseu-2.9.so.5
#9  0x00007ffff6ba903d in wxWindowBase::TryAfter(wxEvent&) () from /usr/local/lib/libwx_gtk2u_core-2.9.so.5
#10 0x00007ffff6ba903d in wxWindowBase::TryAfter(wxEvent&) () from /usr/local/lib/libwx_gtk2u_core-2.9.so.5
#11 0x00007ffff6ba903d in wxWindowBase::TryAfter(wxEvent&) () from /usr/local/lib/libwx_gtk2u_core-2.9.so.5
#12 0x00007ffff6ba903d in wxWindowBase::TryAfter(wxEvent&) () from /usr/local/lib/libwx_gtk2u_core-2.9.so.5
#13 0x00007ffff6ba903d in wxWindowBase::TryAfter(wxEvent&) () from /usr/local/lib/libwx_gtk2u_core-2.9.so.5
#14 0x00007ffff6ba903d in wxWindowBase::TryAfter(wxEvent&) () from /usr/local/lib/libwx_gtk2u_core-2.9.so.5
#15 0x00007ffff60ae237 in wxEvtHandler::SafelyProcessEvent(wxEvent&) () from /usr/local/lib/libwx_baseu-2.9.so.5
#16 0x00007ffff6a92e98 in wxgtk_button_clicked_callback () from /usr/local/lib/libwx_gtk2u_core-2.9.so.5
#17 0x00007ffff30829a7 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff309b006 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff309b852 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff4bf5b45 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#21 0x00007ffff30829a7 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff309b006 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff309b852 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff4bf4949 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#25 0x00007ffff4c9d099 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#26 0x00007ffff30826e0 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff30934d0 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff309b2db in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff309b852 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00007ffff4db493e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#31 0x00007ffff4c9b434 in gtk_propagate_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#32 0x00007ffff4c9b78b in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#33 0x00007ffff49087ac in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#34 0x00007ffff29b9355 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff29b9688 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff29b9a82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff4c9a797 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#38 0x00007ffff6a40ac5 in wxGUIEventLoop::DoRun() () from /usr/local/lib/libwx_gtk2u_core-2.9.so.5
#39 0x00007ffff5f9ae50 in wxEventLoopBase::Run() () from /usr/local/lib/libwx_baseu-2.9.so.5
#40 0x00007ffff5f6128f in wxAppConsoleBase::MainLoop() () from /usr/local/lib/libwx_baseu-2.9.so.5
#41 0x00007ffff5fdf255 in wxEntry(int&, wchar_t**) () from /usr/local/lib/libwx_baseu-2.9.so.5
#42 0x00000000004d7812 in main (argc=1, argv=0x7fffffffdef8) at xLightsApp.cpp:17

Originally I had set "Single Color White" and the numbering seemed off (start and end channels were both 1, instead of the number of nodes, which I expected).  That wasn't the cause of the crash since "RGB Nodes" still causes a crash.

**Comment by smeighan** [comment]
closing all bugs over 6 months old. We will start tracking issues in Xlights 4.0.
