### ISSUE TITLE
Allow using Hostname's or FQDN's for controllers

### ISSUE THREAD

**Issue by ptr727** [smeighan/xLights#3000]
**Is your feature request related to a problem? Please describe.**
I'm using DHCP for controller network configuration.
I enter a FQDN for the controller in the IP address field in XLights, seems to work, but:
When I upload to FPP, I see two controllers, the FQDN as entered and the IP.
When I tools/Check Sequence, I get a warning that the IP of the controller is not valid.

**Describe the solution you'd like**
I'd like the IP filed to be able to be a Hostname or FQDN, without duplicates (compare discovered IP with resolved IP), and without complaints.

**Describe alternatives you've considered**
Using static IP's or DHCP reservations is more work and prone to error.

**Additional context**
NA

**Comment by kkatee** [comment]
Not sure why you think having your addresses change whenever they feel like it is less prone to error.

**Comment by dkulp** [comment]
This should be fixed in 2022.14 as the compares in FPP connect also consider the uuid.   This likely requires FPP 5 or 6 on the FPP side.
