### ISSUE TITLE
Support for more and forever repeating string effects (like WLED)

### ISSUE THREAD

**Issue by ptr727** [smeighan/xLights#3002]
**Is your feature request related to a problem? Please describe.**
I use WLED, and found xLights by chance, still a n00b but thousands of $ later I have a couple controllers and thousands of lights. But, I do wish xLights had the simplicity and string sequence selection offered by WLED.
I am switching between a QuinLED-Dig-Quad running WLED most days and a Kulp F4-PB / Falcon F16v4 for holidays, it would be fantastic if I only needed xLights to e.g. make my patio lights slowly animate every night, vs. having to switch controllers out.
What I find missing in xLights are forever repeating string [sequence animations](https://github.com/Aircoookie/WLED/wiki/List-of-effects-and-palettes).
Yes, I could use single line, and drag it out to a long time, and make the controller repeat the play.
But, a few issues:
- The sequence editing is really geared to small time periods, e.g. even for a running lights effect it is not possible to get fine grained control over number and colors of pixels chasing, it is a function of % of total length divided by counts, so very easy to get uneven numbers and gaps.
- Because of the time based animation, there is almost always a disruptive jerk in effects when repeating the sequence, due to the animation stitching not being continuous.
- The number of string animations is very limited compared to WLED, that is really all about string animation.

**Describe the solution you'd like**
The outcome I'd like is to be able to have a large selection of string animations, that do not require me to make render changes, or experiment to not get gaps, or not get a jerky repeat. 
There are probably several solutions:
- Add more string animations, maybe borrow  or share code or animations from WLED, specifically making it easy to control running lights.
- Introduce the concept of repeating an effect, i.e. instead of needing to drag an effect out over the time, just tag it to repeat until stopped. This is not necessary if all sequence controls are not span based, again e.g. the single line that calculates in % over time and line.
- Add support for seamless stitching of effects when repeating the sequence, e.g. repeating a rainbow effect should be smooth forever, not jerky.
- This may be a stretch, but today rendering is done in xLights and the players play the rendered content, in WLED the controller runs the sequence, maybe a new type of sequence that is executed on the controller, vs. xLights rendering. This is not to be like WLED, but to address the issues of seamless stitching and forever repeating sequences. Could also be done by having native sequence file support for repeating sections with perfect stitching.

**Describe alternatives you've considered**
I keep running two controllers, or the problems with xLights and repeating playlists already discussed, i.e. lack of control and jerky transitions.

**Additional context**
NA

**Comment by sslupsky** [comment]
I have not played around with this but can you do this in FPP with the Pixel Overlay feature?

**Comment by rhd** [comment]
Hi @keithsw1111 - How do you enable an effect to continue forever? I'm trying a `Single Strand` WLED effect under the `FX` tab. AFAICT, it always restarts and I don't see a way to tell xLights to render this effect forever. I see the effect loops forever - but it's causes a obvious transition most of the time.

Thanks!

**Comment by ptr727** [comment]
Just FYI, I did discover how to use WLED overlay effects in FPP, easy, but not as feature rich as xLights.
So this ask is still for native repeat until stopped style effects.

Primary problem is the abrupt / jagged animation changes on loop repeat when there is no sync or blending with the native effect timing.

I also notice that when making the effect time very long, some settings are difficult to control, as the options work well for short periods not long periods. I.e. deterministic vs. relative values, e.g. repeat 3 times in time period of effect vs. repeat 3 times per second, where the former's effect changes drastically as the effect period is changed, and requires some math to maintain the same effect. Would be nice to be able to control timing over the period or timing per fixed period overlayed on the effect time.

**Comment by keithsw1111** [comment]
xLights fundamentally does not do that. You can create long sequences but at the end of the day it ends and loops and unless the effect happens to be in the same state as the beginning it wont loop cleanly.

WLED can do this because it expects to run forever … it’s a controller not a sequencer.

Keith

**Comment by rhd** [comment]
@keithsw1111 thank you for the clarification. I'll investigate the overlay option in FPP.
