### ISSUE TITLE
xScheduler 2021.39 - Repeat Firing of Schedule not Working

### ISSUE THREAD

**Issue by robfallone** [smeighan/xLights#3004]
End Goal: The following bug is encountered when trying to set a playlist to run every X minutes.

Problem: When setting "Refire frequency:" to "Fire every 5 (or 15) minutes", I see the next fire time updated correctly but the playlist does not actually run.

I have attached a screenshot of my schedule and the "xlights.xschedule" file.

![image](https://user-images.githubusercontent.com/29558143/145701388-ec53e154-8b0a-4c01-ac98-c0b738c1afc7.png)
[xscheduler refire.zip](https://github.com/smeighan/xLights/files/7698150/xscheduler.refire.zip)

**Comment by keithsw1111** [comment]
I tried your xSchedule file and it worked fine on my machine.

Possible reasons:
- I may be running a newer version (although I did test with the latest release build)
- There may be issues with your FSEQs ... as you only sent the xschedule I had to add my own FSEQ and it worked fine.

If you are still having the issue we may need to exchange a more complete set of files. You should likely email me a dropbox (or similar link). I will need the audio, fseq, xschedule and networks files at a minimum. I could probably get away with just the first song in the schedule.

Also can you send the xschedule log file. Would like a chance to look at that again.

**Comment by emccarron** [comment]
2021.40 -- might be seeing the same thing.  Schedule set to fire every 30 min sometimes fires, sometimes doesn't. 

Win 10 Home -- brand new install.

Noticed "Active Scheduled Playlists" in log does not always drop to 0 after show is complete?

When it skips a fire event, it -does- update the next scheduled time, but log looks like nothing happened.

I can provide files if needed as well...  This is a new toy and it very well might be operator error on my end.

Awesome work!

Ed

**Comment by emccarron** [comment]
Think I found my problem -- failed to set correct network adapter in xscheduler.  Lost connection to remotes intermittently, which seemed to cause schedule to fail.

Still testing. :)

**Comment by robfallone** [comment]
Its now after the holidays and I've spent a significant amount of time trying to reproduce this issue. I am unable to reproduce the original failure. As such, I am closing this now.

**Comment by emccarron** [comment]
It's very possible a misunderstanding of the "fire every" setting is what
did me in. Setting up seven separate schedules, each "fire once," resolved
it for me.
Thanks!
