### ISSUE TITLE
Inactive Models that are inside groups show in model preview for the group,

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#3006]
Not really an issue for me, or probably most,
But thought i would point it out,

If you have an all group, and have some inactive models that are part of that group, 
They are hidden on Video/House preview correctly, but show on the model preview,

Not sure if that is intended or not,

**Comment by keithsw1111** [comment]
A similar thing occurs when you have a model from another preview. It kind of makes sense as it is part of a group and the group is visible.
