### ISSUE TITLE
Imported Faces changes to default face if the target face doesn't exist

### ISSUE THREAD

**Issue by kevinsaucier** [smeighan/xLights#3008]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I imported all of last years sequences into this years layout by creating new sequence files, then using the import feature to map from last years models to this years.  On models where a face was not already created with the same name as the model being mapped from (for instance, last years matrix had 'Red Bulb' and this years it was called 'Bulb - Red'), the import just changed the mapping to the first face in the list on the matrix (in this case, Abel from the Blinding Lights sequence).  This causes the sequence to look incorrect and the user to no longer know which face was supposed to be used in the sequence when fixing it.

**To Reproduce**
Listed above

**Expected behavior**
I would have expected it to act like missing images or shaders, leaving the original face name in the drop down but showing up as all red and appearing in the Sequence Check as an error.  Instead, all of my sequences just have Abel singing multiple parts.  This is very apparent in 'The Greatest Showman XLATW' sequence, where there are 4 Abels singing on my matrix at the same time.  :)

**Versions (please complete the following information):**
Windows 2021.39

**Attachments**
I can dig out the old sequence, if it would be helpful, but the steps above pretty well describe the issue.

**Comment by derwin12** [comment]
This was added as a feature - but perhaps it should only default it in the node models (ie chromabulbs) and not do this for matrix type faces?

**Comment by keithsw1111** [comment]
This is by design.

**Comment by kevinsaucier** [comment]
Just my opinion, I suppose, but this is a lousy design.  Instead of notifying that there are missing faces, it simply silently assigns a seemingly random face.  The time it takes to find and fix all of these faces (given that I now have no clue what face each effect was supposed to be) is huge.  At the very least, Daryl's suggestion makes sense.  Pick a default on node models and prompt or flag on matrix models.  🤷‍♂️

**Comment by keithsw1111** [comment]
Check sequence would have warned you if you had run it. That is why it is there ... to explain odd behaviour situations that a user can get into.

**Comment by kevinsaucier** [comment]
To be fair, that is correct, and I did run Check Sequence on the first few sequences that I imported but it wasn't finding any issues and it was adding significant time to the import/upgrade process so I stopped.  That said, I just redid the process with 'The Greatest Showman' sequence and, while Check Sequence does indeed point out that face effects are missing, by the time it does so, the effects themselves have already been updated to the 'default' face name in the sequence so the same problem remains.  At this point, all I can do is use the Check Sequence to get a list of faces that need to be created, then go back and create them, then reimport the effects.  It seems like there must be a better way.  Maybe a popup during the import to warn you that a face doesn't exist and ask if you'd like to create a new face or copy an existing one.  At least that way, it would maintain the correct name and, once the face was created, rendering would pick it up and the sequence would be good to go.

**Comment by AzGilrock** [comment]
I think it would be fine to "display" a default face if the image is missing but if I'm hearing that we are renaming the image field I don't like that option.  In that case we may as well rename missing images and video files as well to default ones.

**Comment by kevinsaucier** [comment]
I did test again and, during the initial import session (before saving/closing the sequence), I was able to add the necessary faces to my Mega Tree and it updated the effects to have the right one.  I didn't try with the matrix because the faces already existed there but I'm guessing it would be similar behavior.  So, while the Check Sequence option does give you the info necessary to fix the issue, it's still a bit daunting because of the vast amount of info provided by the Check Sequence tool.  When importing a single sequence, it might add just a few minutes to the process but, when importing 50 or 60 sequences at the beginning of season (when stress is high), those few minutes add up to hours and hours.  And, all that said, if you happen to save the sequence and close it before you notice the problem (as I did on a number of sequences), the data seems to be gone and you have various faces in your sequence with no easy way to fix them.

Just to be clear, please know that I'm not trying to be argumentative.  I'm able to figure out the issue and work around it, even though it's a bit of a pain and it's time consuming.  I'm just trying to make it easier for the vast number of users who are not particularly technically adept.  The current behavior is not particularly intuitive and, if you don't notice it first time out, fixing it takes some effort.
