### ISSUE TITLE
Papagayo - Image Faces

### ISSUE THREAD

**Issue by maffeirw** [smeighan/xLights#301]
I would like to request the following changes to the Papagayo Tab - Image Faces section for each of the Voices in the table. This is for the purpose of allowing development of images for background, mouths and eyes which could be used as layers on for matrices and pixel trees. See:
http://nutcracker123.com/forum/index.php?topic=1402.msg7941#msg7941

1) Add the ability to set the layer effect to '1 reveals 2"  in the Face Outline and Mouth fields (either in each field in the table or as two seperate groups for each voice)
2) Add the ability to generate the Face Outline, Mouths and Eyes on different layers.

**Comment by AzGilrock** [comment]
Papagayo tab is being deleted and all existing  .pgo files should be converted to use the new built-in xLights method of doing singing faces.
