### ISSUE TITLE
Unable to import lyric timings downloaded from xLights Singing Faces Project through xLights 2021.39

### ISSUE THREAD

**Issue by neowolfwitch** [smeighan/xLights#3011]
**Describe the bug**
Files downloaded through xLights from the Singing Faces Project are downloading as either .xtiming.txt or .xtiming.xml files.
The .xtiming.txt files cannot be imported. They just produce a blank timing track.
The .xtiming.xml files display and empty dialog to select a timing track.
Renaming either file time to just .xtiming results in an empty timing track.

This appears to be a file issue, and not an access issue. The same results happen regardless of where the file is imported from. (The same results occur if the file is copied to the Show Directory, for example.)

**To Reproduce**
Go to Tools -> Download Sequences/Lyrics.
Select a lyric timing track from the xLights Singing Faces Project.
xLights downloads the track via Safari. (?)
Depending on the track selected, it will either be downloaded as .xtiming.txt or .xtiming.xml.

In xLights- Right click on New Timing and select Import Timing Track.
Browse to the downloaded file and select.
If it is a .txt file- a blank timing track will be created with the file name.
If it is a .xml file- you will get a pop-up dialog prompting to select the timing track. It will be empty.

**Expected behavior**
Expected behavior is the track is downloaded as .xtiming, and can be imported into xLights using the established procedure.

**Screenshots***
<img width="450" alt="Screen Shot 2021-12-15 at 10 14 20 AM" src="https://user-images.githubusercontent.com/68392802/146223535-e31845c6-ca89-4fd6-a9a5-5ff5cfb28188.png">
<img width="304" alt="Screen Shot 2021-12-15 at 10 14 36 AM" src="https://user-images.githubusercontent.com/68392802/146223538-c9cd0837-0157-4e95-b5da-0aad053309f9.png">
<img width="292" alt="Screen Shot 2021-12-15 at 10 16 58 AM" src="https://user-images.githubusercontent.com/68392802/146223541-36c78518-8b10-4d5e-99b2-0c7ba4edb071.png">

**Versions (please complete the following information):**
MacOS 12.0.01 (Monterey)
xLights 2021.39

**Additional context**
At least one other person running the same version of xLights was able to reproduce this problem in the Zoom Room.

We were able to devise a workaround in the Zoom Room:
Create a blank timing track and export it.
Cut and paste the contents from one of the "bad" files into it.
Import it. It will work then!

**Attachments**

**Comment by AzGilrock** [comment]
Yep everything in the xLights code is looking for an extension of "xtiming".  I'm not confident the renaming you did worked.  Sometimes the OS can add hidden file extensions.  The fact that you can copy the contents to another file to get it to work says the filename is bad.  It doesn't do this on my PC.

**Comment by neowolfwitch** [comment]
As noted- in the Zoom Room we determined this was specifically xLights 2021.39 running on a Mac.
The problem does not occur with any other version/OS.

**Comment by AzGilrock** [comment]
So 2021.38 works fine?

**Comment by neowolfwitch** [comment]
According to the guys in the Zoom Room that tested it- yet.

**Comment by neowolfwitch** [comment]
I found a bitter workaround, since the problem really is the file extension...
(I believe part of the problem is how the files are being fed from the Singing Faces Project, with a .xml or .txt extension.)

In xLights 2021.39 on a Mac, if you download a lyrics timing track from the Singing Faces Project, it will download as either a .txt or .xml file.

The file will look something like:
Let_It_Go.xtiming.txt
-or-
Let_It_Go.xtiming.xml

xLights will NOT recognize this as a timing track, and will not import it properly, because it has the wrong extension. The extension MUST be .xtiming.

On a Mac, just removing the .txt or .xml for the file name, doesn't actually change the file's extension internally. In order to actually fix these files, you have to remove both .xtiming and .txt/.xml "extensions" first.

In the above example, you need to rename the file to just: Let_it_Go

Then rename it again and  .xtiming to it, like: Let_It_Go.xtiming

The Mac will then ask you to confirm that you want to change the file extension, from either .txt or .xml to .xtiming. 
Confirm this change, and now you can import your file.

**Comment by neowolfwitch** [comment]
I could be wrong (since I don't have an older version of xLights or another Mac to test it on right now) but in the Zoom Room I believe others testing it said the file extension didn't seem to matter in Windows, or .38 or older on a Mac.(?)
