### ISSUE TITLE
Feature Request:  Default Gamma

### ISSUE THREAD

**Issue by sslupsky** [smeighan/xLights#3018]
**Is your feature request related to a problem? Please describe.**
It would be helpful to be able to have a default setting for Gamma.

**Describe the solution you'd like**
Similar to the "Default Brightness" setting for controllers that support FPP, add a "Default Gamma" setting as well.

**Describe alternatives you've considered**
Manually change Gamma using FPP output settings or model dimming curves.

**Comment by tmblue** [comment]
+1
