### ISSUE TITLE
New render style:  Drill down to models when a group contains sub groups

### ISSUE THREAD

**Issue by sslupsky** [smeighan/xLights#3019]
**Is your feature request related to a problem? Please describe.**
When creating groups, it is useful to be able to have groups within the group.  This is useful when adding or modifying models that are used across multiple groups to avoid having to remember which groups need to be changed or updated.  You can make one change to a subgroup and that change is then automatically reflected in any groups that use the subgroup.

The side affect of doing this is that rendering is effected.  That is, "Per Model" rendering doesn't actually render on a model basis when there is a subgroup.  Rather, each subgroup within a group is treated as a model instead of a group.  Thus, rendering of a group that contains subgroups may not produce the expected result.

**Describe the solution you'd like**
It would be useful to have an additional render style that drills all the way down to the model for situations where this is preferred.

**Describe alternatives you've considered**
The alternative is to avoid creating groups with sub groups or when you intend to use the "Per Model" render style, apply the effects to the subgroups instead of the upper level group.

**Comment by keithsw1111** [comment]
The behaviour of groups within groups is intentional as it itself enables certain things to be achieved. If you want a group that will render per model create one with all the models in it.

**Comment by sslupsky** [comment]
@keithsw1111 I recognized that a group could be created with just the models.  However, that creates a great deal more "maintenance" when a change to a model can propagate across many groups.  You have to anticipate which groups are affected and manually go and change those groups.  I originally thought this is a bug since the "Per Model" render style is not what is actually occurring.  The render style is likely more properly described as "Per Group Member".  I fully recognize that "certain things can be achieved" using this "Per Group Member" method.  I am pointing out that there are useful benefits to having a true "Per Model" render style.

**Comment by keithsw1111** [comment]
A model group is a model just like any other model inside xLights ... so the name is technically right.
