### ISSUE TITLE
Xlights for Mac: butterfly effect not displaying

### ISSUE THREAD

**Issue by cjalmond** [smeighan/xLights#3020]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Adding a butterfly effect to any model does not display after a render.  I can get it to display in model preview after a render if I add/remove a color from the palette.

**To Reproduce**
(See video linked below)
1. Add a butterfly effect to a prop
2. Double click the butterfly effect
3. Notice the model preview window is blank.
4. Do a render all and save and double click the effect and it will be blank in the model preview.

To get the effect to show in the model preview:
1. Double click the effect
2. Remove or add a color from the palette and it will show up

If you render after add/removing colors, then the issue will be duplicate.  This issue also prevents the effect from showing on actual props when running my show.

**Expected behavior**
Butterfly effect show up in model preview.

**Versions (please complete the following information):**
 - OS: Mac OS 12.0.1 (new M1 Pro)
 - xLights version: 2021.39
 
 
 **Attachments**
Video of issue
https://www.dropbox.com/s/tnngpck2ssmcfy6/butterfly_effect_mac_issue.mov?dl=0

Sequence
https://www.dropbox.com/s/4pbuyu9oi3esccj/Sleigh%20Ride.xsq?dl=0

**Comment by neowolfwitch** [comment]
I had this problem on my M1 Mac. Be sure "Experimental GPU Rendering" is turned off in Preferences->Other. It's apparently VERY experimental. I don't remember turning the option on, but turning it off fixed Butterfly.

**Comment by cjalmond** [comment]
Superb! thanks...

**Comment by dkulp** [comment]
This will be fixed in the next release.   Workarounds are to either disable the GPU rendering or to disable the RenderCache.
