### ISSUE TITLE
Remove all Models - visualizer.   Prompt before it removed 

### ISSUE THREAD

**Issue by jefft0825** [smeighan/xLights#3026]
When changing smart remote modes in the visualizer, it’s right next to remove all models from controller.  I have hit this a few times on accident and had to redo the entire controller 

Can there be a prompt to confirm that the user wants to really remove the models from the controller in case someone accidentally clicks it

**Comment by computergeek1507** [comment]
added with 74553db076e2b1eeca9bf6f33566a4f1e7216edb
