### ISSUE TITLE
Renaming an Imported Timing Track Results in a Crash

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#3027]
**Describe the bug**
If I import a timing track and then immediately rename it xlights will immediately exit without a core dump.

I can get past this by doing the following steps.
- New Sequence with music
- Import timing track
- Save
- Attempt rename and let xlights crash or just open the saved xsq file
- Rename without issue

I've gotten this issue from xtiming files from the following sources
- autolyrixalign (audacity txt files)
- xtimings I've created by using AWS speach recognition
- xtimings downloaded from singing faces project

**Versions (please complete the following information):**
- Win 10 & Win 11
- xLights 2021.39 & 2021.40

**Comment by sslupsky** [comment]
I will add that you do not have to do an import to crash xLights.  Simply renaming the timing track can cause the crash too, though I haven't figured out the steps to reliably reproduce the issue.  Sounds like importing then renaming reproduces the issue reliably.

**Comment by computergeek1507** [comment]
fixed with 8f69eacdac1a971f133278852b85ff9763cd92d4
