### ISSUE TITLE
Support for Twinkly lights/controllers

### ISSUE THREAD

**Issue by BrandonLive** [smeighan/xLights#3033]
Hi there. I'm new to xLights, but last year I made my "easy mode" entry to setting up LED light shows using Twinkly brand WiFi RGB lights. If you're not familiar with these, they're sets you can buy at Best Buy or Home Depot which include a small WiFi + Bluetooth controller on each strand, designed to be used with the Twinkly mobile app. It allows you to use your phone camera to map the light positions, join multiple strands in different ways, to use pre-built effects, author custom effects (in the mobile app), produce playlists, etc.

Under the hood, each controller runs a lightweight web server, exposing a fairly straightforward REST API through which you can either upload a "movie" or send real-time commands. I began playing around with this a bit last year, and began creating a simple Node library [here](https://github.com/BrandonLive/Twinklier-API-Client). I haven't had a chance to get back to that, but I might use some of my remaining holiday vacation time to play around with this more.

My little library was based partly on hacking around and observing the communication between the mobile app and the devices, but later augmented by the surprisingly detailed documentation I discovered [here](https://xled-docs.readthedocs.io/en/latest/rest_api.html#overview), apparently produced by some others who took a similar reverse engineering approach sometime before me. In fact, just now looking at their [intro page](https://xled-docs.readthedocs.io/en/latest/readme.html), it looks like there are a number of clients and tools which have cropped up over the years. I'll have to look some more about at those soon.

Anyway, looking at xLights, I'm now intrigued at the prospect of adding at least some level of support for Twinkly lights to the project. This could take different forms, but since I see that multiple ethernet protocols seem to be supported today, it seems like it might be possible to integrate support for Twinkly's protocol more or less just like those? Failing that, perhaps I could write a converter from an export format, or something like that.

I'm curious if anyone else has looked into this or has been thinking about it, or if it would be worth exploring ways to add some level of support via new contributions. I don't have a strong sense of how much time and effort it may take, but I'm willing to take a stab at it.

**Comment by keithsw1111** [comment]
Without access to a set of lights/controller this is unlikely to happen.

**Comment by BrandonLive** [comment]
I have several sets.

**Comment by keithsw1111** [comment]
So are you going to raise a pull request with the change?

**Comment by BrandonLive** [comment]
Well yes, possibly, that’s what I was getting at. But I was following the documentation for feature contributions which said to file an Enhancement issue, and I wanted to see if anyone else had already explored this before going to deep into it. I don’t have anything ready at this point, just starting to play around, but it seems like it should be possible from what I’ve seen so far.

**Comment by sslupsky** [comment]
Have you been able to confirm anywhere if the pixels use ws2811 led drivers?

**Comment by robfallone** [comment]
Looks like someone is already trying to do this. https://github.com/smeighan/xLights/pull/3068 Can you take a look and see if you can help/improve it? It currently has some objections / areas for improvement.

**Comment by kkatee** [comment]
This was added in 2022.10
