### ISSUE TITLE
xSchedule: CURL call does not post json data

### ISSUE THREAD

**Issue by Holiday851** [smeighan/xLights#3035]
Version 2021.38

[xlights.xschedule.txt](https://github.com/smeighan/xLights/files/7777616/xlights.xschedule.txt)

Download the attached file and put it in your show directory. Rename it to xlights.xschedule.
Start xSchedule
Select and run the playlist.
Look at the log. It shows a GET.

2021-12-26 13:43:06,140 20096 log_base [INFO] Calling URL https://google.com.
2021-12-26 13:43:06,143 14764 log_base [DEBUG] Checking the schedule ...
2021-12-26 13:43:06,143 14764 log_base [DEBUG]    Active scheduled playlists: 0
2021-12-26 13:43:06,152 14764 log_base [DEBUG] Checking the schedule ...
2021-12-26 13:43:06,152 14764 log_base [DEBUG]    Active scheduled playlists: 0
2021-12-26 13:43:06,793 20096 log_base [INFO] CURL GET: <!doctype html
[cut response for brevity since it's not important]
2021-12-26 13:43:06,794 20096 log_base [DEBUG] PlayListCurl thread done.

Verified the GET by having it call into my web service.

**Comment by computergeek1507** [comment]
Please update to 2021.40, some CURL changes were added

**Comment by Holiday851** [comment]
OK, thanks. I'll give that a try next week. I don't want to upgrade
anything until after NYE.

**Comment by Holiday851** [comment]
Installed 2021.40.
Same results.

From xschedule file
<PLICURL URL="https://google.com" Type="POST" Body="{test:1}" ContentType="JSON" Delay="0" Name="test"/>

From log: 2022-01-01 08:11:43,141 20788 log_base [INFO] CURL GET

Also verified with my personal website that it is calling the GET version of the call instead of the POST version.

Attached the full log
[xSchedule_l4cpp.log](https://github.com/smeighan/xLights/files/7797904/xSchedule_l4cpp.log)
.

**Comment by Holiday851** [comment]
It still repros in 2021.40. I updated the bug with a new log.

It was super cool (quite literally - It was -5°F / -15°C - the house we're
building still doesn't have electricity or heat) last night having
xSchedule do my countdown and fire off my new New Year's sequence right on
time. Y'all are doing an awesome job!

**Comment by thomastech** [comment]
I'm having the same issue. All curl POST calls are using GET instead. Confirmed on client side as well as by reviewing xSchedule logs.

- Thomas

**Comment by thomastech** [comment]
Thank You for the PR. I'm not setup to compile xLights, so I'll have to wait until the next release to try it out.

- Thomas

**Comment by Holiday851** [comment]
Sorry for the spam, guys, but I don't know another way to contact a github
user.

Thomas,
I am really interested in your PixelRadio project - if you don't mind, can
you contact me at the email address in my profile (it's in the description
section of the profile)? (but I totally understand if you want to remain
private).

-- Debora (Holiday851)

**Comment by thomastech** [comment]
Today I found that 2022.07 had been released into the wild. Tried it out. Happy to report that CURL POST is working correctly for me. 

My tests involved the "Text" Content Type. The payload used xScheduler's %ALBUM%, %ARTIST% and %TITLE% variables. All worked without issue.

Thank you again for fixing this.

- Thomas
