### ISSUE TITLE
API request: /packageSequence

### ISSUE THREAD

**Issue by neowolfwitch** [smeighan/xLights#3036]
**Is your feature request related to a problem? Please describe.**
Hopefully I'm not the only one who does this...

Since my layout and models usually change every year, I've found it a lot easier to package all of the current year's sequences up, and then once I have everything finalized for the new year- I import them into my new layout.

So, right now I am going through the "usual" routine of:
Opening each sequence.
RenderAll (just in case I missed something since the last time it was opened).
Save
Tools -> Package Sequence
Save

For 60+ sequences... The carpel tunnels are killing me.

**Describe the solution you'd like**
The (in-development) REST API already has the functionality to open a sequence, render all, and save. The only thing missing is the ability to package the sequence.

It would be GREAT if something like /packageSequence was added to the API.

If this is added, it would be easy to either write a shell or PHP script to step through all the sequences in the show folder, render all and package them.

As an alternative- an option similar to Batch Render in Tools, called Batch Package, would also be great.

**Comment by AzGilrock** [comment]
Wow every time I hear you guys talk about 60 sequences I’m like they must not have traffic issues.  I have to keep song list short so people will see it repeat and leave.

**Comment by neowolfwitch** [comment]
Well, 10 of them are intros/messages and static displays, but I've got about 50 actual musical sequences that we just shuffle every day. Good idea though on keeping them short for traffic. Fortunately it hasn't been an issue in my small town.

**Comment by computergeek1507** [comment]
added with 71e2f959cad8b41586f40e92651e9970a80d5460
