### ISSUE TITLE
Crash when trying to draw new animation in Effects Assist

### ISSUE THREAD

**Issue by kjdunn** [smeighan/xLights#304]
When trying to draw something from scratch in the Effects Assist window it keeps freezing and crashing the entire program. It was freezing the program, but finally got a crash report.  But cannot attach here.

**Comment by RichardRennII** [comment]
I was able to duplicate this issue I could add pictures fine but when trying to draw from scratch the program would freeze and crash

**Comment by stevegiron** [comment]
Hi, is this still an open issue for you? If not can you please close the issue. Thanks.
