### ISSUE TITLE
Apply Brightness to Certain Controllers

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#3042]
**Is your feature request related to a problem? Please describe.**
In xScheduler, when adding a "Brightness Button" it would be nice to be able to apply only to certain controllers instead of your complete layout. I have 33 LOR A/C controllers that I would like to stay at 100% brightness while dimming my 12 San Devices that control my pixels.

**Describe the solution you'd like**
One of two solutions...
1)be able to "click" on the controllers you want to have dimmed
2) be able to click on the controllers you DON'T want to have dimmed

**Describe alternatives you've considered**
I cannot think of an alternative as my San Devices firmware do not have an option to set their brightness

**Additional context**

![Brightness](https://user-images.githubusercontent.com/13740582/147795771-e71c47f6-2041-49c3-8074-77d9889b6dac.jpg)

**Comment by computergeek1507** [comment]
add a Dim Output Processing to xSchedule


![image](https://user-images.githubusercontent.com/2293065/147795942-5da6d99d-33bc-47f7-9d5e-173c07710ddd.png)

**Comment by jimswinder** [comment]
can this be put on certain controllers...or dims the whole layout?
________________________________

**Comment by jimswinder** [comment]
where does one find this "Output Processing" tab?

________________________________

**Comment by jimswinder** [comment]
never mind...found it
________________________________

**Comment by jimswinder** [comment]
Thanks Scott...that solution worked great!!
________________________________

**Comment by keithsw1111** [comment]
I actuallu think you want exclude dim ... this protects a set of channels from being dimmed.

**Comment by jimswinder** [comment]
Dimming a range of channels worked for me...

thanks!
________________________________

**Comment by jimswinder** [comment]
If I use the Brightness control in the xscheduler, will Exclude Dim make those selected stay at normal brightness then?
________________________________

**Comment by keithsw1111** [comment]
Yes it will.
