### ISSUE TITLE
xlDo Automation - getMedia to return the media filename back to the calling script.

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3045]
Looking to retrieve the value of the media for a sequence. Thinking being, 
I can open a sequence, render it, export the model to avi file WITH the media.avi so that avi file can be used on a virtual matrix.
Alternative would be to grep the .xsq to extract that name prior to the xldo functions.

**Comment by keithsw1111** [comment]
Added to getOpenSequence ... i think ... to be honest your description is pretty confusing once you get past the first sentence.
