### ISSUE TITLE
Falcon F16V4 Data out of date

### ISSUE THREAD

**Issue by dgrant3830** [smeighan/xLights#3046]
I'm new to Xlights so if I've made a mistake, please pardon me. Trying to assign two Falcon F16V4 controllers to a first sequence, 1 Matrix and 1 Pixel tree. Per Falcon's data sheet, 96 universes for each controller and 1024 Pixels/output in E1.31 mode. Your latest version 2021.40 64Bi
![Error1](https://user-images.githubusercontent.com/96960183/147861587-02c7be5d-102a-41da-b985-98925504be14.jpg)
t

**Comment by computergeek1507** [comment]
To use the visualization, you need to Enable Auto Layout Models

**Comment by dgrant3830** [comment]
Ok, but when I turn that on, I lose the ability to have ws2815 pixel protocol. Sorry, but trying to do something via Xlights that I was mostly able to do via LOR but more licensing costs are getting in my way to make this work. Simply put, I'm going to upgrade a 16x50 pixel tree to 24x300 and a 24x50 matrix to 24x300. I'm hoping to use my existing sequences and import that information into Xlights but first things first, I need to get these new controllers to set up correctly and able to handle the larger pixel counts for the new pixels. Also understand, I've not purchased the Falcon F16V4 controllers nor the WS2815 strips yet, pending first to see if it'll even work.

**Comment by keithsw1111** [comment]
WS2815 is the same protocol as WS2811 ... the only differences are electrical within the pixel.

**Comment by dgrant3830** [comment]
Thank you Sir!
