### ISSUE TITLE
xSchedule - cloning a step makes it loop oddly until restart

### ISSUE THREAD

**Issue by Holiday851** [smeighan/xLights#3048]
This repros on 2021.38 and 2021.40. Windows 10

Cloning a step and then playing the playlist will get the playlist stuck on the step that was cloned (the original step).

Expected behavior: to continue through to the cloned step and on to the rest of the playlist.

Repro steps:
Download the attached file, put it in your show directory, and rename it to xLights.xSchedule
Start xSchedule
It will automatically play through all three steps (schedule is set to play most always - unless you're testing at exactly 11:59pm)
Click Stop All
Double click the Playlist to edit it
Select Delay 1
Right click Delay 1 and select Clone
Name it Delay 1a
Click OK
Click Reset All Schedules
It will play Delay 1 (green) and show Delay 1a as next (yellow), but it will only play Delay 1 over and over
Save it
Close xSchedule
Start xSchedule
Now it works again
[xlights.xschedule.txt](https://github.com/smeighan/xLights/files/7802740/xlights.xschedule.txt)

**Comment by robfallone** [comment]
I was easily able to reproduce this issue. I found the is during the "clone" process, we are copying the original ID to the newly cloned PlayListItem. I am working on a fix for this.

**Comment by robfallone** [comment]
I have opened a PR for this issue here: https://github.com/smeighan/xLights/pull/3061

**Comment by robfallone** [comment]
Issue has been resolved. Closing.

**Comment by robfallone** [comment]
I believe issue has been resolved. This issue can be closed.
