### ISSUE TITLE
Additional Outline Color Options for Faces

### ISSUE THREAD

**Issue by chart8015** [smeighan/xLights#3049]
Many of my singing props have more than 2 outline colors. The Face Outlines in the Face definition node are the quickest way to define these however they are currently limited to two outlines. 

I would like to see the option of 3 or more Face Outlines of which I'm able to force additional colors for. This seems like an easy enough fix to create efficiencies in this area. 

In the past, I created sub-models for each sequence and defined the colors in the sequencer. Time-consuming when you have a large number of songs and want to make changes to the colors. The capability is there with the face definitions. Would just like to expand on it. 

**Additional context**

**Comment by keithsw1111** [comment]
We added the ability to use a state for exactly this reason.

**Comment by chart8015** [comment]
Thank you. Apologies for not doing more research. Thanks for the quick response.

**Comment by computergeek1507** [comment]
Your can also use the eyes open two and three as two more colors

**Comment by chart8015** [comment]
Thank you!!
