### ISSUE TITLE
Audacity Timing Mark import failing (Mac version 4.1.11)

### ISSUE THREAD

**Issue by bajadahl** [smeighan/xLights#305]
Tested in 4.0.31 and importing timing marks worked.   4.1.10 and 4.1.11 both did not work

![audacity_timing_import_fail](https://cloud.githubusercontent.com/assets/2394009/8783471/9bc6197e-2ee1-11e5-9582-1550fbdc24f9.jpg)

**Comment by AzGilrock** [comment]
Is this still a problem?  It looks like I must have run into this on my own cause on Aug 8th I checked in a change that checks that the timing grid doesn't have 0 rows before calling the DeleteRows method which should have fixed this.

**Comment by AzGilrock** [comment]
Ok I'm declaring this fixed.  Reopen if you encounter it again.
