### ISSUE TITLE
Render Order Not Followed for Shaders

### ISSUE THREAD

**Issue by Old-Salt** [smeighan/xLights#3052]
**Describe the bug**
Groups containing subModels followed by an effect on the model itself are not rendered properly

**To Reproduce**
1. Place a white On effect on a Group containing a  subModel
2. Place a Shader effect on the model (this should be below the Group with the subModel)
3. View the nodes of the model which make up the subModel, note effect on the model is not correct.

**Expected behavior**
The Shader effect should overwrite the nodes of the entire model.

**Screenshots**

**Versions (please complete the following information):**
 - OS: checked on Windows 7 and 8
 - xLights versions verified on 2021.12, 2021.30, 2021.40  

**Additional context**
Note that the Butterfly effect works as expected on the Rosa Grande, but the Shader effect does not.
The Shader used for demonstration zeros out the Green channel.
A Test gif applied to the model, simulating the subModel is used from 00:00:05 to 00:00:09 to demonstrate the expected result.
See Strand 2 on the virtual matrix for the affected nodes

**Attachments**
Test sequence which demonstrates the problem.
[test.zip](https://github.com/smeighan/xLights/files/7808803/test.zip)

**Comment by AzGilrock** [comment]
So that shader effect just doesn't seem to be working at all.  Even in the middle where its on the top layer it did nothing for me.  I changed the effect to another shader I had already and the render order is working fine.  The way rendering works I don't believe its possible for it to work differently for a certain effect.

**Comment by Old-Salt** [comment]
matrix.jpg
![matrix](https://user-images.githubusercontent.com/44735832/148144171-b012859f-706e-43fe-84e3-e2d43f3ac07a.jpg)

note the the image paints the same nodes white on the model, as the On effect does at the subModel level.
only 16 nodes on strand 2 of the matrix are white for either effect
note the white pixels are changed to purple by the shader when applied after the image
note the white pixels are blanked out by the shader when applied after the On effect is applied to the subModels

rosa grande.jpg
![rosa grande](https://user-images.githubusercontent.com/44735832/148144175-5f84e726-0e78-4ec1-8d7b-eb986c398f33.jpg)
note when the butterfly effect is applied on the model when the On effect was previously applied to the subModel works as expected
note when the shader is applied on the model when the On effect was previously applied to the subModel does NOT work as

**Comment by AzGilrock** [comment]
But if I change that shader to this space one I have it does properly overwrite the On effect so it doesn't appear to be a render order problem its more of not understanding how that shader works.

**Comment by AzGilrock** [comment]
I have not been able to get your shader to actually draw anything even when placed by itself.  What's it supposed to do?  It says it requires Canvas mode which seems weird.

**Comment by dkulp** [comment]
It's definitely due to canvas mode.   Canvas mode only works with layers on the currently rendered model, then the merging would occur with data that was there from the previous group.

**Comment by Old-Salt** [comment]
This shader does not create a new design.  It is supposed to take the colors of the nodes and modify them.  Shaders like space and most of the others in the catalogue generate new patterns on the nodes.  This class of shader and modifies what's already there, 

It requires that the result of rendering groups and models above it be added to the canvas before this class of shader is rendered,

**Comment by AzGilrock** [comment]
From Dan's comment sounds like this isn't going to change.
