### ISSUE TITLE
xlights: unknown encoding only when batch render

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3056]
I have a sequence that flags this error only during batch render. It seems it doesnt have the same font path? doing the batch versus loading and rendering.

Rest of the message is
No font for display text in encoding 'Unicode 8 bit (UTF-8)' found. 
Would you like to select a font to be used for this encoding...

It is a purchased sequence. I will update with the font after the batch completes. I doubt it used Unicode 8 bit for the font.
I think it is pointing to Shape effects  Object to Draw: Emoji,  Character Arial Narrow, 10  127855

**Comment by keithsw1111** [comment]
If this is still an issue can you send me the sequence to see if i can reproduce

**Comment by derwin12** [comment]
Cant duplicate .. it was the Fairy Pixel Dust sequece Twelve Days of Christmas.
