### ISSUE TITLE
Increase Universes for ESPixelstick upload

### ISSUE THREAD

**Issue by TownshendLights** [smeighan/xLights#3058]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
ESPisxelstick 4.0 has a max universe of 6, if you try to upload the config to the controller it won't let you do more than 6.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. On Controller screen
2. once espixelstick vender and model 4.x are selected and the ESP32 variant.
3. If universe count is larger then 6 
4. This is when the error comes up.
5. 
**Expected behavior**
Except more than 6 universes

**Screenshots**
<img width="362" alt="image" src="https://user-images.githubusercontent.com/97005812/148626474-38119299-88b5-4f11-a29d-72b523d23af8.png">

<img width="388" alt="universes" src="https://user-images.githubusercontent.com/97005812/148626457-75be7952-cda1-4324-8ae1-1f6cf962268e.png">

**Versions (please complete the following information):**
 - OS: Windows 10.
 - xLights version 2022.01

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
Added in 2022.2
