### ISSUE TITLE
xl crashes when using the text effect with more than one line of text against a matrix

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#306]
Description and debug report attached in 2nd post of :  
http://nutcracker123.com/forum/index.php?topic=1341.0 

Also replicated today at 4.1.11 so can provide additional debug reports.
Adding a text effect with one line seems okay. Saved no problem.
Then text to the second line and tried to change the font, position and direction attributes , resulting in a crash
(the text is against a 64 8 64 matrix model)

**Comment by stevegiron** [comment]
Very strange there were a few P10 matrices at the Expo running multi lines of text, one as marquee signs giving class information with no issue.

**Comment by gerry4** [comment]
Hi,

Were they using xlights output or native scripts using the matrix  overlay function in FP ?

I'll see if I can do a video. 

Others have had this crash too ie auusiephil . I think Dan commented on it too

It's the gifts thing people with panels want to try.

Date: Tue, 21 Jul 2015 20:24:11 -0700

**Comment by AzGilrock** [comment]
Dan has already checked in changes that I think might help the text effect.  It used to be always thrown on the main thread and I think he figured out that's not needed anymore which should make it perform just as well as all other effects.

**Comment by gerry4** [comment]
Thanks Gil/ Dan,
 
Will try it out as soon as released. 
 
Scrolling (up/down) or stationery a few words of the song on the panels  from time to time is quite a nice effect , but u need more than one line of text working for it to be useful.
 

Gerard
 
Date: Fri, 24 Jul 2015 15:04:26 -0700

**Comment by AzGilrock** [comment]
I've done up to 4 lines of text but that was all with one Text effect.  You don't need multiple effects to have multiple text lines.

**Comment by gerry4** [comment]
Hi Gil,
 
The crash is on one effect only.
 
No problem if I use only one line , but if I put text on the second line and then try and change the variables of the second  line ie the font , x, y pos (so that it is below the first line), the direction of the scroll ,  and the color , it crashes.
 
I was trying to do something like
 
Merry Christmas   <--- first line
     To You   <--- second line
 
(both same color and moving upwards 
 
Let me see if I can get it to crash with a video recording (which I have never done before , but may as well learn how to  now)
 
Regards

Gerard/Gerry
 
Date: Fri, 24 Jul 2015 16:24:50 -0700

**Comment by AzGilrock** [comment]
I believe you I'm just saying its not as cut and dry as doing the same steps causes a crash because I've been doing exactly what you're saying with no crashes.  Now I will say I did started getting crashes on Text effects when I switched to a different computer that wasn't as powerful as my desktop so it has something to do with the threading and capabilities of each PC.  So no video needed lets just see how Dan's changes perform.

**Comment by gerry4** [comment]
Ah okay , thanks.
 
I use a standard simple laptop for the xl sequencing which BTW works absolutely great most of the time !!
 
(I thought it was one of the attributes being changed or a combination off , so spent some time trying to isolate which one , so as to advise  , but obviously a video would then not help based on the below)

Gerard
 
Date: Fri, 24 Jul 2015 16:34:54 -0700

**Comment by AzGilrock** [comment]
Yeah that what happened to me.  I took my laptop to the Expo and started seeing crashes on sequences I had rendered a 100 times on my desktop no problem.

**Comment by stevegiron** [comment]
Hi Gerry, I think this is working now. Please confirm.

**Comment by gerry4** [comment]
Hello Steve,
 
Yes it is , please close.
 
Regards


Gerard
 
Date: Sun, 6 Sep 2015 23:54:16 -0700

**Comment by AzGilrock** [comment]
Gerry I can't see what you see but doesn't it give you the option to close the issue also?  If you created it you're always free to close it.  I'll leave it open so you can look.

**Comment by gerry4** [comment]
Yep - I can close it and have closed it (first one I closed). I thought that I could only add comments, so maybe I have been looking at other ones previously.
Many Thanks
