### ISSUE TITLE
Single Strand From Middle does not include middle pixel for odd length Line

### ISSUE THREAD

**Issue by MikeSoukup** [smeighan/xLights#3060]
**Describe the bug**
If you add a Single Strand effect with Default render style and "From Middle" chase type to a Single Line model that has an odd number of pixels, the middle pixel doesn't get used.

**To Reproduce**
1. add a Single Line model that has an odd number of pixels
2. apply a Single Strand effect to the model with Default render style and From Middle chase type

**Expected behavior**
I expect the middle pixel to be used, but it is always black

**Screenshots**
![image](https://user-images.githubusercontent.com/10994778/148694788-ef4fbd9d-9bb4-41dd-a9fc-ac764ba09c8d.png)
the top line has 51 pixels, the bottom has 50 and I applied the same Single Strand effect to both

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights 2022.1

**Comment by MikeSoukup** [comment]
@keithsw1111 I have a possible fix for this, but this is the first time I've looked at xLights code so I don't know if I broke something else.  How do I get someone to look at it and approve it?  Is it as simple as forking & submitting a pull request?

**Comment by computergeek1507** [comment]
Make a pull request and someone will look at it for approval
