### ISSUE TITLE
Additional Key Bindings

### ISSUE THREAD

**Issue by cybercop23** [smeighan/xLights#3071]
**Is your feature request related to a problem? Please describe.**
It will be usefull to have additional key bidings for the Layout to support easier/faster access to SubModels, States and Faces, similar to how we have ones for Wiring View and Node Layout. 

**Describe the solution you'd like**
When a model is selected, you can already map a key to get to Wiring and Node views. Add the same ability to be able to use keybindings to open Faces, Stats and SubModels windows without the need to navigate, scroll and click.

Additioally, since there's no double click action on a prop, chose one of the above, most likely SubModels to open the SubModel window (or make it configurable)

**Describe alternatives you've considered**
None. Only other option is to scroll and click.

**Additional context**
None

**Comment by AzGilrock** [comment]
I don’t like mapping double click like that.  It’s supposed to deselect models when you double click open space so this could cause you to accidentally deselect or accidentally open a dialog you don’t want if you don’t have the mouse position perfect

**Comment by cybercop23** [comment]
Doesn't single click in an open space deselects one or more selected models? Double, doesn't seem to do anything since first click deselects them. But in any cause, if there's a default open dialog on double click, it could be made configurable and let the user "be aware".
