### ISSUE TITLE
Timing Event Random Bar - seems to group multiple props together when hitting an event

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3072]
Not clear if this is a bug or just not understanding the settings. Attached is the test sequence.

Flat Trees - found that I had to "Horizontal Distribute" the props for it to work. If I move any of them, they will likely pair up and show 2 perhaps 3 at a time.

Used the same effects on the spiral trees -- and again multiple spiral trees light at the same time. 
Is there a setting on the group perhaps that might fix this?

Another zoom user found same issue with peace stakes .. get doubles showing but if he horizontal distribute it fixed it
[RandomTree.zip](https://github.com/smeighan/xLights/files/7867636/RandomTree.zip)
.

**Comment by computergeek1507** [comment]
Groups by default use per preview as the render style. This  overlay a 2d grid over the current preview and put each models node in a cell of the grid. This grid size will max out at 400x400 and then xLights will start grouping pixels together. The "timing event bar" with then divide up this grid based on the number of bars. It doesn't know out model locations. If you want to only single props coming on, change the render style to "Per Model Single Line" and set the number of bars to the amount of models in the group.

**Comment by derwin12** [comment]
Thanks Scott!! We just discovered this too .. we had Default Model as a Pixel and that is where we got stuck.

This is indeed the fix/answer. Thanks!
