### ISSUE TITLE
Single Color Problem in Layout

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#3076]
**Describe the bug**
When playing back a sequence, effects on Single Color (DMX - AC Channel type models) do not appear to be lighting the entire model on the house preview, but instead are only lighting the first bulb on the line.  All of the other bulbs light white regardless of if there is an effect on them or not.  The Model preview looks correct, but the House preview is not.  I have attached a test sequence for this with my layout.  There is also an image showing the model preview, which is what it should look like, and the house preview, with only the 1st bulb lit (it is very hard to see because only 1 is lit for each so I circled it to show it a little better).   

**Expected behavior**
The house preview should match the model preview.  

**Screenshots**
See below

**Versions (please complete the following information):**
Having the problem on 2022.02 on Windows.  Was not a problem on 2021.38, which was the last one I was using to sequence on.  

[2022-02 Bug.zip](https://github.com/smeighan/xLights/files/7876155/2022-02.Bug.zip)
![2022-02-Bug Image](https://user-images.githubusercontent.com/17793531/149642555-f818c033-2f01-409a-9435-12f3f2b416d1.JPG)

**Comment by aggie81** [comment]
I am having the same problem with 2022.2, so didn't want to start a new issue. I have AC single color, single channel string lights in my show. On the string or poly line models (wrapped trees and yard outlines) , only the first light in the line responds in the house preview when playing a sequence, the rest are solid on all the time. This was working in 2022.1 and is broken in 2022.2. Attached is a sequence showing this. First open it in 2022.1, render and play to see what it should look like. Then do the same in 2022.2, the issue will be obvious. Running on Windows 10 Home 21H2. Thanks

[You Make It Feel Like Christmas.zip](https://github.com/smeighan/xLights/files/7876242/You.Make.It.Feel.Like.Christmas.zip)

**Comment by aggie81** [comment]
Just noticed this as well. Single pixel models (RGB floods on the house) are not working as before either. Models Flood-1 to Flood-8 in the above attached sequence.

**Comment by dkulp** [comment]
On a positive note: it's all working fine on a Mac.
