### ISSUE TITLE
Time sync with pre rendered file upload

### ISSUE THREAD

**Issue by ScobbyDoo** [smeighan/xLights#3078]
I'm thinking about option for store pre renderd data to some hardware & sync with time to reduce my lond distance wireless connection traffic & speed of network.

Is there any option available in FPP for time sync? Like artnet timecode or any other way?

Thanks

**Comment by kkatee** [comment]
Have you considered posting this in the FPP github, rather than the xlights one?

https://github.com/FalconChristmas/fpp/issues

**Comment by ScobbyDoo** [comment]
I'm finding an option in X-schedule also

**Comment by keithsw1111** [comment]
This already exists in both FPP and xSchedule
