### ISSUE TITLE
models disapeared again

### ISSUE THREAD

**Issue by santa25** [smeighan/xLights#308]
Well after I had to re draw all my models after they disapeared, I saved and backed up F10 yesterday, just opened xlights again and all models have gone again

**Comment by stevegiron** [comment]
Please give the exact process you did to have the model disappear. A video captured of what you're doing with the FREE Screencast-o-matic would really help.

**Comment by santa25** [comment]
Hi Steve, my problem was solved by Gil Jones, thanks for your reply
