### ISSUE TITLE
Group Center "plus" is gone or disappears when you attempt to move it

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3081]
From zoom... attached is the layout. For the bigger layout groups like "Entire Display .." etc, if you change the x and/or y the red centering plus disappears. Seems to be new in .02

[CenteringGroupBug.zip](https://github.com/smeighan/xLights/files/7877950/CenteringGroupBug.zip)

**Comment by derwin12** [comment]
Another zoomer - lost his 2d house image .. rolled back to .01 and it worked again. simple .jpg image. Attached is his layout.
[missing layout background.zip](https://github.com/smeighan/xLights/files/7878552/missing.layout.background.zip)
.

**Comment by AzGilrock** [comment]
We have a red centering plus?  I've never seen one in my layout.

**Comment by computergeek1507** [comment]
> We have a red centering plus? I've never seen one in my layout.

It use to only appear in 2D mode
