### ISSUE TITLE
3D Mesh textures do not appear in 2022.02

### ISSUE THREAD

**Issue by MTBehnke** [smeighan/xLights#3083]
My 3D house model, including textures, works fine in 2022.01.  Once I upgraded to 2022.02 the mesh still works but the textures no longer appear.

When I reinstall .01 the textures appear again.

**To Reproduce**
1. Started with 2022.01 and working mesh (3D house model)
2. Upgraded to 2022.02 and textures no longer appear
3. Downgraded to 2022.01 and textures reappear

**Expected behavior**
Textures should continue working in .02 as they do in .01.

**Screenshots**
Screenshots from 2022.01 and .02 are attached

**Versions (please complete the following information):**
- OS:  Windows 10
 - xLights version 2022.02

**Additional context**
Note, the .obj, .mtl and texture files do not contain any spaces, which I believe has caused other issues.  Model was created in Sketchup and exported as .obj file, which generated the files with random long filenames.  These files worked directly as downloaded until upgrading to .02.  As a test I simplified the longer names to 'xHouse3D', which continue to work as expected in .01 but not .02.

**Attachments**
Zip with .obj, mtl and texture files:
[xHouse3D.zip](https://github.com/smeighan/xLights/files/7878255/xHouse3D.zip)

Zip with xlights_networks, _rgbeffects, and _keybindings.xml:
[Christmas.zip](https://github.com/smeighan/xLights/files/7878282/Christmas.zip)

Screenshot using 2022.01:
![House 2022_01](https://user-images.githubusercontent.com/22116435/149684097-a1aaa1ee-dfaa-49ab-b1b7-ee1898d25f08.jpg)

Screenshot using 2022.02:
![House 2022_02](https://user-images.githubusercontent.com/22116435/149684099-085cf5ab-05ca-40e3-ac82-356e3b39884d.jpg)

**Comment by AzGilrock** [comment]
Thanks for providing the files.  I’m sure we will get this sorted out. There are going to be a few growing pains as we transition to using an abstraction layer for graphics to support OpenGL and Metal on Mac.  I’d stick with the older version if anything becomes a big issue.

**Comment by AzGilrock** [comment]
We usually do these more drastic changes at the beginning of the year

**Comment by MTBehnke** [comment]
No worries, completely understand!

As an FYI, I just got a new PC so tested the issue on my old PC (integrated graphics) and had the same issue - no textures with .02.   New PC with the issue has an RTX 3070.  Not sure if this is helpful info.

Be glad to provide any additional info that would be helpful and/or provide testing.

**Comment by dkulp** [comment]
2022.03 will fix this, but your obj really is poorly made causing a LOT more drawing calls than should be required.  First off, over half of the indexes are for the railing on the back porch which isn't even visible in your display.  They look nice though.  :).     Second, every single triangle that has a texture on it is actually rendered twice.  It is rendered once with the texture and then immediately rendered a second time with a solid color.   With 2022.02, the second rendering was "winning" whereas 2022.01 (and eventually 2022.03) the first render will win.   However, there is definitely a cost involved with setting up the drawing calls and sending data to the GPU and such for all the triangles that will not result in anything being displayed.

**Comment by MTBehnke** [comment]
Great info.  I re-exported my house model from Sketchup, this time with 'Export two-sided faces' unchecked, and now it works perfect in .02.  I also deleted all the railings in the xLights version of my full house model.  You guys are outstanding!
