### ISSUE TITLE
2022.02, blended circle not working in house preview - single line.

### ISSUE THREAD

**Issue by MovieDad** [smeighan/xLights#3085]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Using a single line 1, 1 light, 1 node to represent a flood, changing pixel size to 200, transparency 20, black trans to 50, then pixel style to blended circle. it is only showing a small line on the right-hand side. tested this on several sequences, just started happening since 2022.02

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
The screen cap shows that the color does not fill the entire blended circle, its just a small line from center to the edge of the right of the circle. Highlighted in the screen grab. All the flood lights should be green, using an on setting in sequence.

**Screenshots**

![image](https://user-images.githubusercontent.com/97895249/149782291-d78d31ef-8c21-44f3-a8ae-92af53bf73e2.png)
![image](https://user-images.githubusercontent.com/97895249/149783744-82f86002-b2b4-49ee-b5b9-9811ea87bf89.png)

**Versions (please complete the following information):**
 - OS: windows 11
 - xLights version 2022.02

**Comment by keithsw1111** [comment]
Is this still a problem ... i dont seem to be able to reproduce it.
