### ISSUE TITLE
2022.02.1 Effects pane does not scroll

### ISSUE THREAD

**Issue by sslupsky** [smeighan/xLights#3086]
**Describe the bug**
The effects pane does not scroll when a sequence is played to the end.

**To Reproduce**
1. Create an animated sequence 2 seconds in length
2. Add a random effect to a random model
3. Click "Play"
4. Wait for play to end (2 seconds later).  The play head will be near the end of the sequence.
5. Attempt to scroll the effects pane

**Expected behavior**
The effects pane should scroll

**Screenshots**
This screen shot shows the sequence before play.  Note effect is applied to "House - All" group.
![Screen Shot 2022-01-17 at 9 57 12 AM](https://user-images.githubusercontent.com/16888734/149811754-7b04cc9a-128b-4d96-938b-c2a2ea3f0668.png)

This screen shot shows that when attempting to scroll the effects pane, it does not scroll.  However, the view pane (that shows the models, groups and layers) does scroll.  Note effect appears to be applied to "Windows - Horizontal" group now but it is actually still applied to the "House - All" group as shown above.
![Screen Shot 2022-01-17 at 9 57 35 AM](https://user-images.githubusercontent.com/16888734/149811902-ff242db0-981b-478a-bf9d-0327adc65330.png)

If you close the sequence, the effects pane remains locked and continues to display the effects that were showing before attempting to close it.

You can work around the problem by pressing play and stopping the sequence before the play head reaches the end of the sequence.

**Versions (please complete the following information):**
macOS 11.6.1
xLights 2022.02.1

I can post a sequence if you require it but it is trivial to recreate this so I did not include it here.

**Comment by AzGilrock** [comment]
If you click in the effects area first will it scroll then?

**Comment by sslupsky** [comment]
> If you click in the effects area first will it scroll then?

No, it's stuck.  Almost seems like it looses all events sent to it or maybe the events never arrive.  XLights becomes somewhat unstable at this point as well.

**Comment by keithsw1111** [comment]
I have tried to reproduce this in the latest version and dont seem to be able to do it with your instructions ... could it be it has been fixed?

**Comment by keithsw1111** [comment]
Closing this for now ... if it is still a problem we can reopen.

**Comment by sslupsky** [comment]
@keithsw1111 I think I recall it was in the release notes for 2022.03:
— bug (dkulp) MacOS: Fix scrolling/displays on OSX after play finishes
