### ISSUE TITLE
DMX connections/not showing in layout in .02

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3087]
From zoom... Attached is the sequence and layout. Nothing appears for the dmx props anymore in the play of the sequence.
(rendered/saved etc) DMX props in the bottom front are not reacting.

**Comment by derwin12** [comment]
[MissingDMX no music.zip](https://github.com/smeighan/xLights/files/7884065/MissingDMX.no.music.zip)
I had to remove the .wav file for the music as it was too big

**Comment by keithsw1111** [comment]
This is too vague to do anything with ... which props are the dmx props ... what should they be doing? Is it still a problem in .5 ... the LOR small bushes I guess are DMX and they seem to be responding to me.

**Comment by derwin12** [comment]
Agreed .. it is working in the latest build..
