### ISSUE TITLE
Creating New Sequence Crash

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#309]
With a sequence open and morph effect previewing on a model, if I then select "new sequence" and go through the steps of setting up a sequence, xLights will crash before getting through all of the steps.

If I have a sequence open and no effect previewing, I can create a new sequence without an issue.  I can only recreate this crash when the morph effect is previewing, multiple sequences.

I posted the debug report on the forum at http://nutcracker123.com/forum/index.php?topic=1408.0

Dan replied "Looks like the Affects Assist panel isn't being cleared of it's state when a sequence is closed.   It's still trying to display elements from the closed sequence.   Definitely a bug."

Noticed this in 4.1.11 and it's still present in 4.1.12.

**Comment by AzGilrock** [comment]
Version 4.1.13 I added code to set the effect assigned to the assist window to NULL when closing a sequence so this should be fixed.  If you could verify and hit close if it's fixed that would be great.

**Comment by kppankratz** [comment]
This crash is now gone.  Thanks for the fix.
