### ISSUE TITLE
.02 crashes when launched in windows 10 pro

### ISSUE THREAD

**Issue by lightingfool** [smeighan/xLights#3093]
[xLights_dbgrpt-1588-20220118T120736.zip](https://github.com/smeighan/xLights/files/7892176/xLights_dbgrpt-1588-20220118T120736.zip)
attempted to load in sequence and xlights crashes

**Comment by TheOneCalledScott** [comment]
I may have experienced the same thing.  2022.02 launched after install into the Controllers tab but freezes/crashes when clicking on the Layout or Sequencer tabs.   Running Windows 10 Home (21H2) on a Surface Pro 7.  Rolled back to 2022.01 and the problem resolved.  Here is my debug report as well if it helps.  Thanks for all you do.

[xLights_dbgrpt-13496-20220119T202151.zip](https://github.com/smeighan/xLights/files/7902058/xLights_dbgrpt-13496-20220119T202151.zip)

**Comment by keithsw1111** [comment]
Unfortunately windows crash reports are broken right now so these crash reports dont really tell us all that much. We also know that xLights has been unstable and not fully functional on all platforms for the past few releases while some pretty fundamental changes are made. Given this I am going to close this for now. Within a release or two our crash reports will be fixed and hopefully the code will stabilise. If you are still seeing issues then please resubmit.
