### ISSUE TITLE
Weekly/Nightly Builds

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3096]
Does xlights have the "plumbing" that would make it possible to release/post nightly or weekly builds automatically to a server? Not to push out to users but to allow risk takers to try master branch releases?

**Comment by AzGilrock** [comment]
I think its already doing a Linux build.  Don't think you can make it do Windows or Mac builds its not setup with the tools.  But don't worry the folks who install our releases the first couple days they come out are already "risk takers".  :)

**Comment by computergeek1507** [comment]
I have already started working on this I will have it done soon

**Comment by AzGilrock** [comment]
Problem is most of the developers push to master and we don't always make sure things are pristine first.  We sometimes push in progress things and then communicate about whether we are ready for a release.  I wouldn't want to hear about any issues from people trying to run in-between builds.

**Comment by keithsw1111** [comment]
Yeah the risk here is we dont guarantee conversion or communicate backward compatibility issues until the release. If you were using nightly builds you would be responsible for backing things up and own dealing with corruption issues which can occur.

**Comment by derwin12** [comment]
Yes .. understood .. we would be flying without a parachute :-) but hopefully we catch stuff prior to going out to the 1000s of others when they get the update notice.

**Comment by AzGilrock** [comment]
If you find it before release you gotta fix it…lol

**Comment by derwin12** [comment]
Looks like Scott has this enabled .. we see it under Actions and Runs.. Thanks Scott.
