### ISSUE TITLE
Update on Effect window for Faces updated colors and layer blending

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3097]
Not sure if this is a bug or a feature :-)

I selected a number of faces effects. Changed the phoneme to E then pressed Update.
It updated to the E but it also updated all the colors along with the fade outs that were set on one of the effects.

Should it just update the values for the particular window pane (ie Effect values) and not all the window panes?

**Comment by computergeek1507** [comment]
I believe it updates everything, that is why Keith added bulk edit

**Comment by keithsw1111** [comment]
I didnt think it updated colour ... but everything else is original behaviour that has been there since 2014. I dont have super strong feelings about it so am inclined to leave it as is.

**Comment by derwin12** [comment]
K. Thanks for your responses...
