### ISSUE TITLE
2022.02.3 Crash when editing custom model

### ISSUE THREAD

**Issue by sslupsky** [smeighan/xLights#3098]
**Describe the bug**
xLights crashes when editing a custom model.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Edit custom model
2. Edit model data
3. Select an area of the grid
4. Click the "cut" button

xLights crashes at this point.

**Versions (please complete the following information):**
 - xLights 2022.02.3
 - macOS 11.6.1

**Comment by sslupsky** [comment]
Here is a copy of the model (it has sub  models and the crash may have something to do with that).

[Window Frame - 1 Vertical Mullion.xmodel.zip](https://github.com/smeighan/xLights/files/7916623/Window.Frame.-.1.Vertical.Mullion.xmodel.zip)

**Comment by sslupsky** [comment]
Yeah, that appears to be the problem.  If I remove the sub models before cutting the nodes, xLights does not crash.

**Comment by computergeek1507** [comment]
It is working fine for me, this may be already fixed in master.

![cut_custom](https://user-images.githubusercontent.com/2293065/150624113-ef950aed-07f3-40cd-8317-05d899da77ba.gif)

**Comment by sslupsky** [comment]
I did a bit further investigation and it sometimes the cut and paste is successful.  I have found one particular cut that reproduces the crash every time for me:  Select the top row->cut->click->crash.

https://user-images.githubusercontent.com/16888734/150654310-63fd8a4e-54e6-497c-8f82-4b1bbd9b1941.mov

**Comment by keithsw1111** [comment]
Yeah the problem here is details were left out of the original problem. The problem occurs when nodes are deleted which leads to a submodel referencing nodes that dont exist. This is why when reporting problems you need to be really specific. If you had said originally which nodes you were cutting the problems would have been fixed in a day.
