### ISSUE TITLE
Unable to install new version-  Help, I'm a newbe

### ISSUE THREAD

**Issue by PJShaver** [smeighan/xLights#310]
While install wizard is installing I get an error that says DeleteFile failed;code5  Access Denied.

I won't be surprised if this is user error, but any guidance you can give will be greatly appreciated.

Paulette

**Comment by stevegiron** [comment]
What happens if you hold the shift key done, then RIGHT CLICK on the Nutcracker setup  and choose RUN As Administrator?

**Comment by PJShaver** [comment]
Hi, Steve!  I got the same error message.

**Comment by stevegiron** [comment]
Try installing to a different folder.  I install to a different folder each time I install a release version. This allows me to switch versions for feature testing.
![image](https://cloud.githubusercontent.com/assets/10568498/8856484/0d63e7d8-3120-11e5-825d-9bd842defbbc.png)

**Comment by AzGilrock** [comment]
Sounds like you have some type of anti-virus software blocking the install to program files.

**Comment by smeighan** [comment]
if you have mcafee, you may need to disable it to do teh install. you can select the 15 minute temp disable.

**Comment by gerry4** [comment]
Most probably an access authority error ie need admin privileges or something similar
What version of Windows are you running , is it a standlone PC or a work PC etc.
Do you have admin rights when installing ?
Can I suggest that if you still have this problem , then post it on the forum (under I need help) as lots of people will suggest options  and comments - not many people come here (to github) every day.

**Comment by PJShaver** [comment]
Thanks for help. I moved off the laptop on to the desktop that I will be using exclusively for lights, uninstalled xlights and reinstalled.  Working as expected now.
