### ISSUE TITLE
"Sequence Video" window no longer working in 2022.x

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3108]
Attached is just a simple empty sequence using a mp4 as the audio. Going into View->Windows->Sequence Video shows "black" ie empty.
Went back to 2021.39 as it was handy and it shows the video without issue.

I was wanting to use this feature with another video/sequence but figure this empty one shows the same issue anyways.

Daryl
(Sorry me again :) )

PS. Also tried converting mp4 to and avi and same results (works in .39 not in .03)

**Comment by keithsw1111** [comment]
Works fine for me ... maybe turn off hardware video decoding.

**Comment by derwin12** [comment]
That is not set. Worked in 2202.01 .. stopped in 02 and didnt work in last nights build.
I will check my drivers..

![2022-01-28 09_03_12-Start](https://user-images.githubusercontent.com/4643499/151560259-aeb59128-cf92-4b81-bbcd-0b45bf74a970.jpg)

**Comment by dkulp** [comment]
Also make sure you are using OpenGL 3.3

**Comment by derwin12** [comment]
I will check that .. 2 others confirmed same results in zoom room. Updated nvidia driver made no difference.

**Comment by derwin12** [comment]
![2022-01-28 10_14_03-Start](https://user-images.githubusercontent.com/4643499/151572093-da12dc2d-0102-442d-8994-8745619f23d0.jpg)
4.6 ?

**Comment by AzGilrock** [comment]
I think he meant The OpenGL setting inside xLights

**Comment by bcarriveau** [comment]
Can also confirm this does not work on 2022.03, rolling back to 2022.01 allows it to work correctly. openGL set to auto, hardware decoding turned off. windows 10

**Comment by derwin12** [comment]
Changing from Auto to 3.x made no difference. Is there anything that could be added to say "check sequence" that might show pertinent dependencies. eg opengl, driver settings or whatever might be a possible cause (no idea what else might cause this)?

**Comment by bcarriveau** [comment]
looking at it a little bit more, there is a small difference in 01 vs 03 ver 01 doesn't show the selected windows that are active.
is there something i can look for with VS that would be helpful? the outputs seem to be the same between the two.

![Screenshot (295)](https://user-images.githubusercontent.com/60801063/151673180-cdff45db-059b-4ec6-976b-829bb24f792f.png)

and here is 03


![Screenshot (296)](https://user-images.githubusercontent.com/60801063/151673184-b065c41d-390e-4bcf-94ba-906abf96de0b.png)

**Comment by bcarriveau** [comment]
@derwin12 see if @dkulp fixed it for you also, here is the latest build ( https://drive.google.com/file/d/1-EFXYaooSk2FWyuURcWvP8huh7RmrKsq/view?usp=sharing )

**Comment by derwin12** [comment]
Fixed!
