### ISSUE TITLE
Timeline indicator position when you stop it

### ISSUE THREAD

**Issue by HuggiesHA** [smeighan/xLights#3109]
Hello

Thank you very much for this amazing product.

Just wondering if this could be an option that can be either turned on or off so it offers the best of both.

When you play a part of the sequence and want to stop it at a certain point, would it be possible for the timeline indicator to stay at the spot it was stopped? An example would be how the timeline indicator stops in Camtasia software when you stop it.

Not sure if this has been requested before but think it will be a great add-on feature. If this can be an option for on or off, then everyone get the method that suits them better.

Thank you again for the great work

**Comment by computergeek1507** [comment]
There is a Pause button

**Comment by HuggiesHA** [comment]
Does that have a keyboard key like the the space bar for stop

**Comment by derwin12** [comment]
Yes the Pause key 👍
