### ISSUE TITLE
Mac Sequencer UI Features not fully functional

### ISSUE THREAD

**Issue by MrRocketman** [smeighan/xLights#311]
I've seen videos of people using xLights on Windows, and when they drag timing marks, the current time marker (the one over top of the audio waveform) moves with it. This doesn't happen on my Mac and it makes it rather challenging to line up timing marks. I've also read about things like being able to select multiple timing marks at once then drag them and I can't seem to get that working either. This is all on the latest beta 4.1.12

![screen shot 2015-07-22 at 7 42 32 pm](https://cloud.githubusercontent.com/assets/1709766/8841391/20794b18-30aa-11e5-9376-c3c086bcb3d1.png)

Thanks!
James (MrRocketman)

**Comment by AzGilrock** [comment]
No that marker doesn't move in Windows.  You must be looking at old videos.  That is marking where play should start and it was considered an issue that you couldn't click in the grid without it moving.  Maybe we could add a second line of a different color to mark where you are clicking in the grid.

**Comment by kppankratz** [comment]
I could see a subtle indicator in the wave form to indicate the cursor position.  There is a similar feature in another program I use a lot and it comes in very hand when you are trying do precise alignment.  I've included a snap shot of what I'm talking about.  Look to the right of the 8" ruler mark and you can see a dotted line indicating where the cursor is located beneath it.

![cursor location](https://cloud.githubusercontent.com/assets/12144876/8890255/b8351962-32be-11e5-860f-c4562be4baf8.png)

**Comment by SLSettles** [comment]
Agree that an indicator line to show where your cursor is in the timelines would be very helpful, especially when you have a lot of timings and models between the waveform and where you are working. I have another UI feature that is not working on Mac. Ctrl-Scroll does not zoom in and out as (the manual says) it does on the PC.

**Comment by MrRocketman** [comment]
This is all I am really wanting to happen: https://youtu.be/r-DPC9VWw64?t=45s 

You can see the line on top of the audio waveform moves when the left edge of the effect is dragged.

I can't for the life of me get it to function on my mac. Maybe I'm missing something.

**Comment by kppankratz** [comment]
Looking at the video, I see what you are talking about.  That version of xLights is 4.0.35 from back in May.  A lot has changed since then, and this is one example that I cannot duplicate any longer in the most recent version of the Mac.  Not sure if it still works on the PC side of things.  I did roll back to 4.0.35 and it worked per the video.
