### ISSUE TITLE
Consider adding Palette Editor - basic functions

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3112]
The palette drop down (Load), could a couple of features be added there via right-click? One to delete a palette and another to rename one. Realizing of course, this can be done via the file browser, it would be nice to have that built in for ease of use.

**Comment by keithsw1111** [comment]
Delete a palette already exists. Rename doesn't ... but I also cant think of a decent way to implement it from a user experience perspective that would work. Unless you can come up with something I plan on closing this one.

I guess I could add a name button ... or prompt for a name when you click save ... but that does not solve the rename problem unless you then delete and resave.

**Comment by derwin12** [comment]
I never noticed the little x there for delete -- was always looking for a right click on it..  With the delete there, this should be fine as is.
