### ISSUE TITLE
background image wont load, only white/gray box with newest version release, windows 10

### ISSUE THREAD

**Issue by stickymits** [smeighan/xLights#3119]
version 2022.03 on windows 10, intel graphic driver. Background image displays as solid white/grey. Was able to go back to version 2021.40 and stepped up to 2022.01 and still loaded image properly. Again still no image load with 2022.03
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/8007314/xLightsProblem.zip)
.

**Comment by TrekErs** [comment]
Another user in zoom on a HP with intel built in graphics had this same issue.  Unfortunately I wasn’t able to get more information.

**Comment by derwin12** [comment]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/8045184/xLightsProblem.zip)

**Comment by dkulp** [comment]
"Layout - glVer:  1.1.0  (GDI Generic)(Microsoft Corporation)"

Install real video drivers.
