### ISSUE TITLE
Enhancement Request - test tab

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#312]
For the test function , could we please have an enhancement that enables you to locate and test  channels or a range more easily. For example (any of the following or similar)
1. A find/locate channel so that if u enter a number eg 11800 it takes you there (as the scroll window is very sensitive) (or a locate model or select model or anything similar)
2. After saving a range of channels (eg say Singing face 81-89), when I next load that saved item , position to the first channel that is loaded and ticked  ie 81 rather then having to scroll and try and locate the channel number eg 81)
3. When you start a test (eg Chase) , on the status row at the bottom it says "Testing Channel 1" , "Testing Channel 2"  ,"Testing Channel 3" (or something similar) as it loops through each channel. Could it instead call out the channel number eg "Testing Channel 81", "Testing Channel 82", "Testing Channel 83" 
4. Have an 'On' function ie I simply want to turn the channel (or selected range) On and leave it On whilst I check how something has been configured. (Is this the same as the Background option and increasing the Background value to max ?)

**Comment by AzGilrock** [comment]
See if the test tab update can close this also.

**Comment by gerry4** [comment]
Thanks very much for this !
