### ISSUE TITLE
DMX issue

### ISSUE THREAD

**Issue by lenhard2007** [smeighan/xLights#3121]
2022.04 DMX head sequences are backwards and the visual DMX head while playing a sequence is bigger and the beam is very small.  I have 2022.02 with no issues. All my sequences are backwards on 2022.04

**Comment by dkulp** [comment]
This was somewhat mentioned in the 2022.03 release notes.  Pretty much all the DMX objects will need adjustments with 2022.03+ as they were changed from using world coordinates/sizes to model coordinates.

**Comment by lenhard2007** [comment]
Any idea when it will get fixed? I like the new fx in single strand but would have to go back too .02 for the dmx heads to work. ThanksJustin Lenhard Sent from my T-Mobile 5G Device
-------- Original message --------From: Daniel Kulp ***@***.***> Date: 2/6/22  11:52 AM  (GMT-06:00) To: smeighan/xLights ***@***.***> Cc: lenhard2007 ***@***.***>, Author ***@***.***> Subject: Re: [smeighan/xLights] DMX issue (Issue #3121) 
This was somewhat mentioned in the 2022.03 release notes.  Pretty much all the DMX objects will need adjustments with 2022.03+ as they were changed from using world coordinates/sizes to model coordinates.

**Comment by dkulp** [comment]
It won't get fixed as it's not broken.    As the release notes say, you MUST adjust the DMX objects for the new rendering.

**Comment by AzGilrock** [comment]
These are all just visual differences in the preview your actual sequences would have still played the same.  You just need to change the sign on a parameter to get it to not go "backwards".  Like if its the Pan direction that is backward change the sign on "Pan Deg of Rot".  Like if its 540 make it -540.

**Comment by lenhard2007** [comment]
Thanks. I will test the physical dmx head on Tuesday. Make corrections per instructionsSent from my T-Mobile 5G Device
-------- Original message --------From: Gil Jones ***@***.***> Date: 2/6/22  7:20 PM  (GMT-06:00) To: smeighan/xLights ***@***.***> Cc: lenhard2007 ***@***.***>, Author ***@***.***> Subject: Re: [smeighan/xLights] DMX issue (Issue #3121) 
These are all just visual differences in the preview your actual sequences would have still played the same.  You just need to change the sign on a parameter to get it to not go "backwards".  Like if its the Pan direction that is backward change the sign on "Pan Deg of Rot".  Like if its 540 make it -540.
