### ISSUE TITLE
Bottom part of the window is cut off

### ISSUE THREAD

**Issue by chuckackerman** [smeighan/xLights#3122]
The bottom part of the screen is cut off as can be seen in the attached screen shot.  It makes it difficult to read the text on the bottom.

xLights v 2022.04 (Windows 10)

This occurs in 1080p and 4k resolutions on my monitor.  It also doesn't matter what I set the display text size to.

It occurs in full screen mode and restored mode. 

https://drive.google.com/file/d/1ntGoXuIlCM-DUZkOD1I74zhiDSou7wIq/view?usp=sharing

**Comment by bcarriveau** [comment]
Link goes to a request page, not sure anyone wants to request to see your issue, you can drag images right into this box for direct viewing/upload.

**Comment by chuckackerman** [comment]
Thanks for the info.  Here's the screenshot.

![Screenshot 2022-02-06 123819](https://user-images.githubusercontent.com/39970914/152701727-b2116de6-93cf-4553-a9e6-a3267ef171a4.jpg)

**Comment by bcarriveau** [comment]
Does it also not display fully if maximized?  Not often xlights would be ised not maximized, assuming you are talking about the lower left status info text and render bar?  I cannot recreate this on .04 windows 10(non4k). Usually it's a 4k/graphics card issue. 

Do you have a Non4k display you can open xlights on and see if it corrects itself?

There is a few people that cannot load xlights at all on a 4k, but after it opens on another screen they can drag it over without issues.

**Comment by computergeek1507** [comment]
It's probably because you have a multiplier(125% or 200%) set in your display settings

**Comment by chuckackerman** [comment]
We can close this issue.  Rebooting my PC cleared up the problem.  I should have done that before submitting the problem.
