### ISSUE TITLE
Selecting Effects Assist window to be viewed - changes preferences to Always On.

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3127]
Normally I would like it off, so preference is set to Always Off - but selecting to view E.A once, changes that preference going forward. Is that a bug /  "feature"?

2022.04 and prior

Daryl.

**Comment by derwin12** [comment]
Just the usual window view item from the menu. Sorry not on xlights to give
exact menu choice.

**Comment by derwin12** [comment]
Are lines 3071 + 3074 of tabSequencer.cpp required? Seems like whenever the window is shown it will set the preference. 
Can the preference just be set when it is done via the preference window? (no coder expert here).

**Comment by AzGilrock** [comment]
Well when you ask for the window to be shown we show it permanently until you ask for it to not be shown.  How else do we know when to quit showing it?

**Comment by derwin12** [comment]
If you dont change the preference, either stop xlights, its gone again .. or you click the x on the window, like any other window. Not sure why this would be treated differently here.

**Comment by AzGilrock** [comment]
It has to be different than the other windows because when you select an effect it checks that setting to see whether to show the window if its an effect that has EA support.  So when you decide to close that window or show that window that setting needs to be changed or the behavior when you select effects won't be right.

**Comment by derwin12** [comment]
Well you know the code obviously better than I. Thanks for looking..

**Comment by AzGilrock** [comment]
Well if you see me comment but not close it that's because I'm waiting for other developers to weigh in.  I'm just one person someone else might have more insight or desire to make a change.
