### ISSUE TITLE
Serparate Size and Location locks

### ISSUE THREAD

**Issue by OnlineDynamic** [smeighan/xLights#3129]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to lock the size of a model seperately to locking its location

**Describe the solution you'd like**
Split Size and Location to 2 seperate lock check boxes.

Now that we can use the ruler to set real world dimensiions on the house, it be great to set the real world dimensions on the models and then lock those.... but still be able to reposition them in space on the house

**Comment by AzGilrock** [comment]
I don't like this suggestion at all.  Just imagine a Single Line Model that has two endpoints and center handle.  We would have to allow the middle handle to work but not the endpoint handles as well as having to allow the movement and rotation tools but not the scale tool.  This just ends up making the code a freakin mess and actually will slow down the program having to make all these extra decisions.
