### ISSUE TITLE
Pixel counts wrong w/ HinksPix_4 following a HinksPix_16 Smart Receivers

### ISSUE THREAD

**Issue by JohnCreed** [smeighan/xLights#3131]
**Describe the bug**
HinksPix Smart 4-Channel receiver daisy chained after a Smart 16-Channel receiver creates incorrect Pixel count and sometimes errors if the counts go over 680 (HinksPix limit).

**To Reproduce**
Steps to reproduce the behavior - see video: [https://youtu.be/F4SUER89czc](https://youtu.be/F4SUER89czc)

NOTE: Mega-tree shown is 8 x 100 pixel physical strings folded in half (2 strands per string) making a 16 string x 50 pixel tree. No power injection, just 8 physical ports (800 pixels total) off the 16-channel Smart Receiver.

**Expected behavior**
I would expect the pixel count on the visualize screen to be 450 for Ports 9 & 10 in my example (see video and screenshot).  It looks like there is trouble with xLights calculating the total pixels when a 4-channel smart receiver daisy chains after a 16-channel smart receiver.  The data streams over twisted pairs inside the CAT5 to run "data streams" and the 4-channel receiver would need to share the data stream of Ports 1, 2, 3, 4 with the 16-channel receiver, but when I configure xLights this way the Pixel counts are wrong.

**Screenshots**
![image](https://user-images.githubusercontent.com/99777857/154233382-2e08c7c1-c324-4427-a882-df8956eca389.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2022.04 (Feb 6, 2022)

**Additional context**
Worked in the Zoom room on Feb 15 with Ryan and gang for several hours, but realized later after reading all documentation and watching videos there is a bug here.

**Comment by computergeek1507** [comment]
This is a side effect of how xLights does channel allocation with multiple string models. The way around this issue is to enable "Universe per String" I saw your other issue and will look into it soon.

**Comment by derwin12** [comment]
Thanks Scott ..  Ryan suggested that too but he ran into max universes (as per the other issue ticket). He was able to move things around to get a valid config but was asked to post the issue here. Thanks for taking a look!

**Comment by JohnCreed** [comment]
It would be nice to have this fixed because after I add 7,200 pixels to my garage doors I'll exceed the 144 universe count on my controller just from that.  It would be great to be able to uncheck "Universe per String" and have xLights work with remote receivers and multiple string models together properly.

**Comment by JohnCreed** [comment]
With other bug fixes made in xLights and my understanding of how this works improving I am no longer having this issue as of 2022.9.
