### ISSUE TITLE
Total number of pixles used

### ISSUE THREAD

**Issue by Jaa1i** [smeighan/xLights#3133]
**Is your feature request related to a problem? Please describe.**
I would love to have a menu feature that lists the total number of pixels used within a layout.

**Describe the solution you'd like**
A menu option that simply provides a total number of pixels used in a Layout. It could be a totals pop up that lists the total number of props, pixels, strands etc.

**Describe alternatives you've considered**
You can 'Export Models' and look at the totals that way, but a quick glance would be really handy.

**Comment by computergeek1507** [comment]
As you described this is already in the Export models. I don't see why it would be needed "all the time". When I sequence, I have never needed to know what the total count of my display is. I would like to know a real world use case where total pixel count is needed?

**Comment by Jaa1i** [comment]
> As you described this is already in the Export models. I don't see why it would be needed "all the time". When I sequence, I have never needed to know what the total count of my display is. I would like to know a real world use case where total pixel count is needed?

Just because it is not a feature that would be of benefit to you, doesn't mean it's not beneficial to others. I'm currently building a layout from scratch and am checking fairly regularly how many pixels I've used.

**Comment by computergeek1507** [comment]
As a developer of xLights, we must weight if added something will benefit our many users and where/how to implement it. Putting the total pixel count at a random location in the GUI doesn't seem very helpful to many people. You can criticize my judgement, but I doubt another xLights developers will implement this either.

**Comment by AzGilrock** [comment]
All you really need to know is how many pixels can you afford....triple that number...then calculate the credit card debt you will be in after a few years.
