### ISSUE TITLE
Feature request - Status screen when playing seq directly from Xlights - DDP source

### ISSUE THREAD

**Issue by brmeadows2841** [smeighan/xLights#3134]
**Is your feature request related to a problem? Please describe.**

It would be nice if when playing a seq directly from Xlights or Xschedule,  if on the home/status page of the device receiving data, the name of the seq or some indication of what and from where the source is being displayed.

**Describe the solution you'd like**

Would it be possible to pass the seq name or source info from Xlights in the data stream, this would allow for IDing the source of DDP data.  As it stands from FPP you only know if data is being received by the sync packets numbers but you don't know the source or name of data source.

**Describe alternatives you've considered**

**Additional context**

![154551502-c757109d-32d8-49c0-98a8-4f8508ba1f92](https://user-images.githubusercontent.com/81775646/155324339-e2fef3cd-ee05-418f-a916-7049642a58b0.png)
)

**Comment by keithsw1111** [comment]
In DDP it is not possible … there is no place in the protocol to include it. E131 does have a spot to say where data is coming from (64 chars from memory) but right now we just send xLights. We don’t send the sequence name.

**Comment by nmiller0113** [comment]
I'm guessing you'd be better off requesting the feature on the receiving end (controllers) to provide identification based on source IP...probably the best you'd get.
