### ISSUE TITLE
Nightly build is failing on xscheduler.

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3137]
Just posting this for visibility - perhaps Scott is aware..
In the Actions, the nightly build to compile has failed the past couple of nights on this library error. Thanks for taking a look.

       "D:\a\xLights\xLights\xSchedule\xSchedule.sln" (default target) (1) ->
       "D:\a\xLights\xLights\xSchedule\Xschedule.vcxproj" (default target) (2) ->
       (Link target) -> 
         LINK : fatal error C1047: The object or library file '..\lib\windows64\libltc.lib' was created by a different version of the compiler than other objects like 'x64\Release\AudioManager.obj'; rebuild all objects and libraries with the same compiler [D:\a\xLights\xLights\xSchedule\Xschedule.vcxproj]
         LINK : fatal error LNK1257: code generation failed [D:\a\xLights\xLights\xSchedule\Xschedule.vcxproj]

**Comment by computergeek1507** [comment]
I am aware, it emails me everyday. The libltc library needs to be recompiled for a newer version of Visual Studio. Keith is the only one with a working VS project to do this currently. I tried making it myself with no luck so far. I am hoping Keith will give it to me or recompile it soon.
