### ISSUE TITLE
xLights set-up when using  SanDevice 682 

### ISSUE THREAD

**Issue by PJShaver** [smeighan/xLights#314]
After setting up the xLights setup, I am now trying to so a small test using 2 models and sending the output straight from the program to 2 different 682s.  But the 682 controllers are not letting me enter the universe and channel numbers used in xLights.  I'm stuck.  

xLights set up Network type E131,  Port: Multicast Universes: 510 channels.  Thanks as always for the great advice.

**Comment by PJShaver** [comment]
Each 682 will only let me enter up to 12 universes, and does not allow a start value with more that 3 digit channels.  But the xLights setup that I did at the Christmas Expo I have 24 universe and Channel number in the 12, 000s.  Do we need to go to unicast mode?

**Comment by stevegiron** [comment]
Each universe can have up to 512 channels. You should configure the E682 with a max of 510 channels.  Don't be confused about the 682 mapping to xLights. Universe #2 Channel #1 will be xLights channel 511. (If Universe#1 had 510 channels configured and the controller was first in the controller order)  Get one controller working, then add the other.

**Comment by PJShaver** [comment]
Thanks!
