### ISSUE TITLE
xLights Crashes when saving Effect Preset with Per Model Default Deep

### ISSUE THREAD

**Issue by monstrousmike** [smeighan/xLights#3140]
**Describe the bug**
xLights crashes every time I try to save a new preset that has the Render Style set to Per Model Default Deep. Other render styles save fine. The example is in my Miscelaneous presets, Spooky Eyes Fan. I had to save it with the Render Style set to Default. For now I apply the preset, then change the render style to Per Model Default Deep. 

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Edit an effect to use Render Style = Per Model Default Deep
2. Right click in the timeline and select Effects Presets
3. Click new preset
4. xLights will crash

**Expected behavior**
xLights should not crash when saving any effect as a preset, using any render style.

**Screenshots**
![image](https://user-images.githubusercontent.com/46628259/155848013-6aeec16e-82f0-4f71-95be-4f4f1d965eef.png)

**Versions (please complete the following information):**
 - OS: Windows 10 64 bit, up to date on all Windows Updates
 - xLights version 2022.05 64 bit

**Additional context**
NA

**Attachments**
Packaged Sequence with presets:
https://www.dropbox.com/s/zlox2e36lahx8mk/Ladies%20and%20Gentlemen.zip?dl=0

Packaged log file:
https://www.dropbox.com/s/ls02q7g2ifvew6m/xLightsProblem-SavingEffectsPresets.zip?dl=0

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

[xLightsProblem-SavingEffectsPresets.zip](https://github.com/smeighan/xLights/files/8146869/xLightsProblem-SavingEffectsPresets.zip)

**Comment by AzGilrock** [comment]
For the developers:  Yes this is happening due to the creation of the preset preview window.  It uses a Matrix model and then tries to render the effect but the "Deep" render buffer is assumed to be applied to a group so it crashes because of a NULL pointer when trying to get the ModelGroup pointer from the model.  I didn't have time to fix at the moment but it seems like we need to either convert the render buffer to the non-deep version when rendering a preset or we add protection where its actually crashing so that any model passed in that is not a group reverts to the non-deep processing.

**Comment by monstrousmike** [comment]
Gil,
I'm glad to hear it wasn't something silly that I was doing. I have an easy work around, so no rush on this from my perspective. Thank you for the quick response!
- MonstrousMike

facebook.com/monstrousmikewww.monstrousmike.com
 

    On Saturday, February 26, 2022, 02:56:23 PM EST, Gil Jones ***@***.***> wrote:  
 
 


For the developers: Yes this is happening due to the creation of the preset preview window. It uses a Matrix model and then tries to render the effect but the "Deep" render buffer is assumed to be applied to a group so it crashes because of a NULL pointer when trying to get the ModelGroup pointer from the model. I didn't have time to fix at the moment but it seems like we need to either convert the render buffer to the non-deep version when rendering a preset or we add protection where its actually crashing so that any model passed in that is not a group reverts to the non-deep processing.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
