### ISSUE TITLE
Some GIF's do not render

### ISSUE THREAD

**Issue by sslupsky** [smeighan/xLights#3142]
**Describe the bug**
Some GIF's do not render.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Create sequence
2. Add pictures effect
3. Select attached GIF
4. Model/House preview is black (blank)

**Expected behavior**
GIF should render model and house preview.

![ukraine-heart](https://user-images.githubusercontent.com/16888734/155898982-80d0ea8b-f342-4242-ba55-6e02a16086a9.gif)

There is a YouTube video documenting this issue here as well:
https://www.youtube.com/watch?v=-WnnL361It4

Unfortunately, I do not have Photoshop so I am unable to take advantage of the workaround in the video.  I loaded the GIF into Apple Motion and then exported to a new GIF using compressor but the result was a static image in xLights.  I have attached that GIF here as well.

![ukraine heart (Small)](https://user-images.githubusercontent.com/16888734/155899072-02cc22d0-b77a-42f2-a326-6374763dc184.gif)

**Comment by AzGilrock** [comment]
This problem has existed for years so not sure anyone cares to spend time on it.  Also not sure if it’s even in our code or a library we use

**Comment by bcarriveau** [comment]
add the gif to the video effect instead, its how alot of us work around it.

**Comment by sslupsky** [comment]
I tried to use it in the video effect but there is a significant visual discontinuity when looping the gif when you do that.

**Comment by keithsw1111** [comment]
This gif wont animate because the gif header says it is a gif87a file and the gif reading code included in wxWidgets will only animate gif89a.
The best fix is to go to https://www.piskelapp.com/p/create/sprite and load and export the file like this one.
It animates perfectly.

![155899072-02cc22d0-b77a-42f2-a326-6374763dc184 (1)](https://user-images.githubusercontent.com/10283944/155939034-4c42a6f2-f1b1-4964-811a-246ca3588654.gif)

**Comment by keithsw1111** [comment]
Sorry I did the compressed one ... here is the uncompressed one: https://piskel-imgstore-b.appspot.com/img/31942068-9865-11ec-a293-53c318b8bdd5.gif

**Comment by sslupsky** [comment]
@keithsw1111  I believe the first file has a gif89a header.  I think the one used was the second attachment that I generated with Apple Compressor.  The output of Compressor looks like it used the wrong gif87a header.

**Comment by keithsw1111** [comment]
I went back to the file you indicated. As you say the header is fine but the parser sees the file as corrupt. I am not going to be changing the parser so the fix remains as previously stated ... run it through piskel.
