### ISSUE TITLE
xLights: Sub-Model Select Nodes window loses Node Range text box on large models

### ISSUE THREAD

**Issue by Holiday851** [smeighan/xLights#3146]
Large Model (no text box):
![SubModelTextBox](https://user-images.githubusercontent.com/95460274/156031165-62692cc9-b429-444f-9f95-3a28c2e104ab.png)
Large Model Zoomed Out (still no text box):
![SubModelTextBoxZoomOut](https://user-images.githubusercontent.com/95460274/156032054-1b14d94f-ffa6-49ec-8256-a766df032242.png)
Small Model (has text box):
![SubModelTextBoxSmall](https://user-images.githubusercontent.com/95460274/156031847-fc45081d-0e03-48ee-a26a-0b971b1f7a4a.png)

Repro:
Select/create a large (ie., a lot of rows and columns defined - doesn't need to have many actual nodes) custom model in Layout
Click in the sub-model text box ("Click to edit")
Click the "..." button to edit
Click "Add" to create a new sub-model
Double click on "Bottom" to open up "Select Nodes"
The text box with the node ranges is not visible (the matrix takes up the whole rest of the window) even if you zoom

Note:
I just realized that technically, the model doesn't have to be large or small to repro this - but I'm not going to redo the images to show it repro-ing with the same model. 

Alternate Repro:
Select/create a model with at least one node (see next bug I will log) - repros even with a 1x1 matrix
Click in the sub-model text box ("Click to edit")
Click the "..." button to edit
Click "Add" to create a new sub-model
Double click on "Bottom" to open up "Select Nodes"
The text box with the node ranges is visible
Zoom in so that the matrix requires vertical scrolling.
Close the window.
Double click on "Bottom" to open up "Select Nodes"
The text box with the node ranges is now not visible

**Comment by Holiday851** [comment]
Version 2022.05 64-bit Windows 10

**Comment by computergeek1507** [comment]
fixed with 93573e3d0038d186555733377ae1cd084e1b154c
