### ISSUE TITLE
xLights: Sub-model window crashes if no nodes defined in custom model

### ISSUE THREAD

**Issue by Holiday851** [smeighan/xLights#3147]
I don't think this is hugely important since I doubt anyone would _want_ to create a sub-model if they haven't created the model yet, but I found it when creating repro steps for the previous bugs I logged, so I figured I'd report it and you can close it if it doesn't meet the fix threshold.

Repro:
In Layout, select the "Custom Model" tool
Create one by clicking in the Layout window
Click on the Sub-Model text box (Click to edit).
Click on the "..." button to open the Sub Model window.
Click "Add" to add a sub-model.
Double click "Bottom" to select nodes.
Crash

Expected:
Either don't crash, don't allow sub-model edit when no nodes defined in the model, or don't allow select nodes when no nodes defined in the model.

**Comment by Holiday851** [comment]
Version 2022.05 64-bit Windows 10

**Comment by computergeek1507** [comment]
fixed with 93573e3d0038d186555733377ae1cd084e1b154c
