### ISSUE TITLE
Layout creation problem

### ISSUE THREAD

**Issue by kopierreko** [smeighan/xLights#3150]
Since some months, on Mac, when we create / copy items in the layout page, the start address of the element is not automatically routed on the end of the previous model, and it's REALLY BORING !

For each item, we have to go to the properties menu and set "individual address", then click on "..." and define to the end of the previous model.

Go Controllers
Create an ethernet controller with 2 universes for example
Go to Layout
Put one arche for example, you will see that the start address is the end of the 2 universes, automatically (which is a bug, it should be 1) : 1021 (2x510+1)
Go to Arches > Controller > Use Start Address > put 1 of the controller.
Now normally, the next model created should follow the first Arche.
Make a new Arche, same problem : 1021.
Make another without setting the start address : 1171
Try copy/past and all you want, there is no other way than setting ALL the model address manually...

<img width="687" alt="Capture d’écran 2022-03-02 à 23 22 26" src="https://user-images.githubusercontent.com/17888657/156460450-ef9ff85f-32bf-4bd9-b6e6-3ffa2d771100.png">

 - OS: Mac OS 10.14, 10.15
 - xLights version 2022.15, on Fedora too if I renember (but not very sure)

[layoutbug.zip](https://github.com/smeighan/xLights/files/8173351/layoutbug.zip)

**Comment by derwin12** [comment]
I believe those are not the desired settings anyways. Go to the controllers tab and open visualizer - drag n drop there. This will set the port and the absolute address correctly. The way it is now it puts it outside the controller range in a save non-controller address space. It makes no assumptions of what controller/port you might put it on.

**Comment by kopierreko** [comment]
I don't understand what you say... Which visualizer do you want me to open in the controller tab ? And what do you want to drag & drop ?

I make exactly the same think I made since many years and I can assure that I never had this kind of problem before

**Comment by derwin12** [comment]
This was added mid last year with the no controller numbering added this year. Visualize is the button on the bottom center of the controller tab. If you have used xlights in the past you may not be aware of this "new" functionality. Perhaps google up the video or hop into xlightszoom.com for a quick tutorial. Once you see/use it, it will all make sense and make things much easier going forward.

**Comment by keithsw1111** [comment]
This is intentional ... we dont optimise for this older way of working any longer. We still make it possible to do things that way but we now optimise for the visualiser.

**Comment by kopierreko** [comment]
OK, I saw it in a tutorial, but the problem is I use my own controller and so if I don't specify the vendor/model, the Visualize button is never enabled...

Do you have a solution for that ? Or can I create a custom controller ?

**Comment by keithsw1111** [comment]
Then you just need to do it manually. You still have the ability to do that ... you have just lost some of the optimised workflow for that way of doing things.

**Comment by keithsw1111** [comment]
You can create your own xcontroller file ... but that assumes you support the necessary features. It is just an xml file.

**Comment by kopierreko** [comment]
Don't worry, I'm a software engineer, it's not a problem ^^ 
At this time, I didn't searched in the bowels of the software because I thought it was a bug, but if there is a explanation somewhere about how to make it, no problem for me.

The only thing is I can choose the size of each output in the webpage of my controller so I will have to find a solution to make it "variable" in xLights. 

But first thing, making the Controller ^^
