### ISSUE TITLE
Crash with the new Find Possible Source Effects (Keith's 2022.05 special build)

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3152]
(For Keith) 
Using Keith's very latest build, xlights still crashed. I cant repeat it every time but the attached video shows one such crash.

Some combination of Edit Display Elements, Deleting the model and Find Possible Source Effects.

https://user-images.githubusercontent.com/4643499/156904991-367ef823-e40e-4291-a038-00fab47e8118.mp4

[xLights_dbgrpt-4004-20220305T195649.zip](https://github.com/smeighan/xLights/files/8191767/xLights_dbgrpt-4004-20220305T195649.zip)

**Comment by keithsw1111** [comment]
This is actually nothing to do with the change ... the bug has been there for a long time. Essentially by removing the model the effects grid pointer to the selected effect is no longer valid so it crashes when you right click.
