### ISSUE TITLE
Wave Effect no longer animating as of 2022.06 on Mac

### ISSUE THREAD

**Issue by neowolfwitch** [smeighan/xLights#3156]
**Describe the bug**
Wave won't animate.

**To Reproduce**
Add a Wave effect to any prop. It just sits there.

**Expected behavior**
Wave is an animated effect that should actually be moving.

**Screenshots**
Screenshot attached. Of course you can't tell from it- but the wave is not moving, at all.

**Versions (please complete the following information):**
Mac OS v. 2022.06 (M1 Pro MacBook Pro 14")

**Additional context**
All other animated effects seem to work fine. This one was until this .06 update.

**Attachments**
<img width="1938" alt="Screen Shot 2022-03-07 at 11 09 13 AM" src="https://user-images.githubusercontent.com/68392802/157083476-580e38e9-9423-49b3-be85-ce3994a2cc59.png">
[Wave Test.xsq.zip](https://github.com/smeighan/xLights/files/8199546/Wave.Test.xsq.zip)

**Comment by AzGilrock** [comment]
Looks like Keith has checked in a fix for this.
