### ISSUE TITLE
2022.06 Wave effect does not have movement

### ISSUE THREAD

**Issue by sidelights** [smeighan/xLights#3161]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
either having an existing sequence with a wave effect with movement or creating a new one with movement.  No movement occurs on the wave effect.  Worked in 2022.01 does not work after upgrade to .06. 

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. create a new sequence, or existing sequence created prior to .06
2. added wave effect with speed > 0 to a group (used "all models" group).   left to right, right to left does not matter.
3. rendered all
4. no movement is seen in .06. 

**Expected behavior**
movement on wave effect 
![wave_no_movement](https://user-images.githubusercontent.com/101691917/158523074-28d77674-4a67-4b1d-afda-b9118fd6d718.png)

**Screenshots**

**Versions (please complete the following information):**
 - OS: [windows 8.1 or later (noted on 8.1 but others in zoom room mentioned other versions as well ]
 - xLights version [e.g. 2022.06]

**Additional context**
none 

**Attachments**
no crash

PM if seq needed.  Very easy to reproduce.  Sorry do not have a drop box account.

**Comment by computergeek1507** [comment]
This has already been fixed for the next version
