### ISSUE TITLE
Mac Check Sequence Failure 

### ISSUE THREAD

**Issue by Darzoom** [smeighan/xLights#3162]
When running Check Sequence without a sequence open it aborts and exits xlights.  Mac Version 6.2
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/8268843/xLights_l4cpp.log)

**Comment by Darzoom** [comment]
John has also seen it in Windows Nightly Build 3638

**Comment by dkulp** [comment]
I cannot reproduce with my layout.

**Comment by Darzoom** [comment]
Here is the layout if that helps.

**Comment by Darzoom** [comment]
[check sequence failuer.zip](https://github.com/smeighan/xLights/files/8274166/check.sequence.failuer.zip)

Maybe you need this.

**Comment by Darzoom** [comment]
BTW, Check Sequence works in a different Show Folder.  Just not the Christmas folder.

**Comment by Darzoom** [comment]
I found the issue.  There was an imbedded OBJ file with a "-" and a space in it.  I removed the OBJ and it works.

**Comment by derwin12** [comment]
Dan - the obj file was invalid - wasnt that corrected or is this another edge case? "tomb stone.obj"

**Comment by dkulp** [comment]
The obj file can have a space in it, but the MTL file that it refers to cannot.
