### ISSUE TITLE
Background image selector does not have validation.

### ISSUE THREAD

**Issue by Mark79864** [smeighan/xLights#3163]
Following from Zoom room:

User wanted to add OBJ file. I found that they tried to add the OBJ file where an image file would be selected for 2D preview.
Nothing seemed to happen and that is what had confused them.

Attached is a recreation in Windows v2022.5 . User on Zoom had MacOS.
![image](https://user-images.githubusercontent.com/72605347/158953813-be23f401-8f4f-4b6e-8068-f4242d05df9e.png)

Enhancement:
Something for 'background image' selection to validate the file type with warning on non-image type. 
Possibly it informs the user to go to '3D objects' for adding an OBJ if they try to load an OBJ in the 'background image' selector.

**Comment by AzGilrock** [comment]
Fire that user they don’t meet our minimum qualifications…lol
