### ISSUE TITLE
Export House video is all Green (both mac and latest nightly build)

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3164]
Just doing the usual export house video preview option. The resulting mp4 is a dark St Patricks video :-)

**Comment by dkulp** [comment]
I cannot reproduce.   Exporting the house preview video seems to work fine.

<img width="2073" alt="Screen Shot 2022-03-18 at 2 41 55 PM" src="https://user-images.githubusercontent.com/91569/159064539-5feae713-f7da-416a-a238-b444cf9ff6ac.png">

**Comment by derwin12** [comment]
I'll upload David R from mac then mine from windows. Perhaps there is something you can see in the mp4 itself.

https://user-images.githubusercontent.com/4643499/159095300-41d01f91-7c26-4e4d-aba3-32cad14a6151.mp4


https://user-images.githubusercontent.com/4643499/159095314-b0d6b28e-6f55-44f1-9610-a684f5ea15c0.mp4

**Comment by derwin12** [comment]
Ok .. I will check with David R on Mac .. the fix for me was to go into  the layout, reset, render then export. Ie. it wasnt showing even during playback so hence it wouldnt capture on the export. Not sure if there is a way to warn to user that a render is required or not.
