### ISSUE TITLE
Moving Head Spotlight Sequencing Change in 2022.?

### ISSUE THREAD

**Issue by Joemarthey** [smeighan/xLights#3166]
After updating to 2022.6, the moving head spotlight pan orientation has to be adjusted 180 degrees from the original orientation.  While this fixes the orientation in Xlights, it also causes the movements to be reversed from their original direction.  An example would be a DMX effect that would pan the spotlight from straight forward to straight left from the viewers perspective on one particular set of movers was 170 to 128. This has now changed from 170 to 212, which used to be the way to get it to move from center to right.  So all movements and sub-movements to go those directions are now the opposite of what they used to be and it takes a very lengthy amount of time to correct all of these movements.

**Comment by AzGilrock** [comment]
Pan orientation has zero effect on real world motion

**Comment by Joemarthey** [comment]
But in the video preview it does.  So it's difficult to create a sequence when the movers are pointing in the incorrect direction in the preview from how they would appear in real world motion.

**Comment by AzGilrock** [comment]
So no changes in 2022.6 affected moving heads so the title is misleading.  It might have changed in 2022.2.  Most likely you just need to reverse the sign on the range of motion parameter.  You didn’t attach a sample sequence so nothing else we can do.

**Comment by AzGilrock** [comment]
It would help to have the setup before you changed anything

**Comment by Joemarthey** [comment]
What all files do you need?  I have several that are set up prior to the change and then one that I'm working on right now that I am using after the change.  You are correct it may have been an earlier update that caused it.  I believe this is my first update since late last year.  I thought I did one when 2022.1 or .2 came out but may be mistaken.

**Comment by AzGilrock** [comment]
You know we provide tools to package what we need in the Tools menu.  Package sequence if it’s a sequence and Package Log Files for just the setup

**Comment by AzGilrock** [comment]
And I’m assuming you tried reversing the sign?

**Comment by AzGilrock** [comment]
Joe...we talked at the FMM.  I want to fix this for you.  If you could create a simple sequence that does at least a couple moving head motions that would help.  Just do a Tools -> Package Sequence and attach that zip file here.  It would be best if its from the earlier version of xLights before 2022.02 where it worked the way you wanted with the old settings.  Then I can figure out how to make things work the same in the new version.

**Comment by Joemarthey** [comment]
Thanks so much Gil. I’ll work on putting something together tonight or tomorrow night. I’m assuming I can just send you one of my packaged sequences from 2021 that I haven’t opened since upgrading to 2022.xx and that should work?

It was great meeting you and I wish I had more time to spend getting to know you better. Hopefully next year at the FMM.

Sincerely,

Joe Marthey

On Apr 6, 2022, at 9:27 AM, Gil Jones ***@***.***> wrote:

﻿

Joe...we talked at the FMM. I want to fix this for you. If you could create a simple sequence that does at least a couple moving head motions that would help. Just do a Tools -> Package Sequence and attach that zip file here. It would be best if its from the earlier version of xLights before 2022.02 where it worked the way you wanted with the old settings. Then I can figure out how to make things work the same in the new version.

**Comment by AzGilrock** [comment]
And point me to a timestamp for one of the effects that works now and had to be changed in newer releases.

**Comment by Joemarthey** [comment]
[2021.37 Version MH Test.zip](https://github.com/smeighan/xLights/files/8435639/2021.37.Version.MH.Test.zip)
[2022.6 Version MH Test.zip](https://github.com/smeighan/xLights/files/8435641/2022.6.Version.MH.Test.zip)

Both versions have the Pan Orientation set to 90.  As you can see, the 2022.6 version has the moving heads pointed towards the rear of the house, even though they have the Pan Orientation set the same in the Layout tab as the 2021.37 version, which has them pointed towards the front of the house.  The only way to correct this is to add 180 to the Pan Orientation and have it set to 270, but that causes the pan movements left and right to be the opposite of what they originally were in previous sequences I have created.  So if I originally had the movers fanning outward, they now fan inward instead.  
I'm more than happy to supply any additional information you need and thank you kindly again for taking a look at this.

**Comment by AzGilrock** [comment]
Ok so it appears to be what I said.  The Pan is 180 degrees changed in orientation and the motion direction reversed when Dan did the changes.  So if you change Pan Orientation from 90 to 270 that rotates it back around.  And you change Pan Deg of Rot from 540 to -540 it will spin the opposite direction.  That should match on screen what you started with.
