### ISSUE TITLE
Ability expire a sequence after being played more than x times - PPP feature

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3174]
PlayPerPay
I would like to be able to disttibute a sequence, but I dont want to them to be able to play it over and over again.. So sort of locking mechanism.
Perhaps a method of payment as well .. so they have to pay in bitcoin to my account.
Xlights could take a piece of each transaction.

Thoughts? Seems like a win win strategy to me...

**Comment by AzGilrock** [comment]
https://wptavern.com/project-owners-can-now-block-abusive-users-on-github

**Comment by keithsw1111** [comment]
I do believe Gil this was an attempt at April fools day humour.

**Comment by AzGilrock** [comment]
Yep I know mine was a belated April fools day reply.  I actually heard about this at the FMM...lol.
