### ISSUE TITLE
Increased Buffer Font Size

### ISSUE THREAD

**Issue by Indigogyre** [smeighan/xLights#3177]
It's really hard to read the buffer fonts when I am trying to adjust them. I'm having to fight with just being able to decipher the settings and it is very annoying.

It would be wonderful if you would put in either a means to adjust the size of the buffer or put in a panel that the settings could entered on. Either would be appreciated to make adjusting buffers easier.

![Buffer Font Size](https://user-images.githubusercontent.com/45136194/161388646-23313fea-ab46-4e63-a4d4-30d9f506c720.JPG)

Thank You

**Comment by derwin12** [comment]
..dont forget you can use the edit option in there to type in the exact numbers you are looking for.

**Comment by keithsw1111** [comment]
As Daryl says this already exists ... right click and select edit.
