### ISSUE TITLE
Long render times .. and weird "threads"?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3179]
(feel free to close this .. but wanted to flag something might be up with the later nightly builds).

Seems like getting some random long render times (windows). Here is a screen shot .. it is like it cant start threads or something?

![image](https://user-images.githubusercontent.com/4643499/161407188-7915868d-0367-4495-9185-9e32e5317a21.png)

**Comment by fone626** [comment]
I'm also seeing this on my Linux install.  The random slow renders are only using a single CPU core.

**Comment by keithsw1111** [comment]
This is entirely normal behaviour ... it is because your everything group is a render dependency for all the other props and likely something on it is rendering slowly holding up all the other render threads. This is one of the downsides of sequencing groups that people dont seem to understand.
