### ISSUE TITLE
Models in model groups do not reflect changes made to node order

### ISSUE THREAD

**Issue by dgirard96789** [smeighan/xLights#318]
If a model is created, then added to a model group, any changes to that model do not take effect when the model is selected in a sequence within the model group.  For example, a grid model created as 1 string, 99 nodes and 3 strands per string--this creates a zig-zag node layout.   If this model is added to a model group, but then changed to be 3 strings, 33 nodes, and 1 strand per string (creating a bottom-up node layout)...when the model group is used in a sequence (even a brand new sequence), the individual model maps it's nodes as if they were still in the original configuration.   This is clearly demonstrated if a "bar" effect moving up is played on these models.

**Comment by stevegiron** [comment]
This is true. Just remove the model from the group and add it back.

**Comment by dkulp** [comment]
I believe this is fixed with the new layout code.   Can someone verify?

Models now have a change count and any modification to the model should be incrementing it.   The group code tracks the change count and if different, re-calculates the group.

**Comment by keithsw1111** [comment]
Given Dan says this was fixed 3 months ago and no one has provided any feedback to the contrary ... closing.
