### ISSUE TITLE
Adding Group In Layout Doesn't Appear In Sequence List

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#3183]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
On the Layout Tab, when adding a Group (House Pixels) to another Group (RGB Elements) it used to show up right away in your Sequence View (ie RGB Elements).,,now it's not.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to Layout Tab
2. Click on Group "RGB Elements)
3. Under "Add To Group" move "House Pixels" to Models In Group.
4. House Pixels does not show up in Sequence View of "RGB Elements"
**Expected behavior**
When adding a model or group to a Sequence View it used to show up right away.
**Screenshots**
See Attached Video

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2022.7
 - 
**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

https://user-images.githubusercontent.com/13740582/161668802-75854e5c-3741-4f6b-91c4-2c623f2f9b0a.mp4

**Comment by jimswinder** [comment]
[Mary Did You Know RGB - Clay Aiken.zip](https://github.com/smeighan/xLights/files/8414439/Mary.Did.You.Know.RGB.-.Clay.Aiken.zip)

**Comment by computergeek1507** [comment]
This is by design. Models are not automatically added to existing/open sequences. You must open the display elements and add them manually.

**Comment by jimswinder** [comment]
Thanks...mut be losing my mind...thought for sure it had worked that way before...lol
________________________________
