### ISSUE TITLE
Additional eye states within Face Definition

### ISSUE THREAD

**Issue by Frowndon** [smeighan/xLights#3184]
Hello,

To make my singing props wink for example I turn the eyes off within the faces effect and apply the "on" effect to a sub model to make the prop wink.
I've used states also but find the sub model easier. 
Is it possible to add additional eye states to a face definition eg wink, sad and happy or even add custom eye states and then select these new states from the Eyes menu in the Faces Effect Settings?

Regards,
Brendan.

**Comment by keithsw1111** [comment]
That is exactly what states are for. Adding a second way to do it doesn't seem to add a lot of value.

**Comment by Frowndon** [comment]
Hi Keith,

States don't integrate well with auto eyes.
Take the example of a wink: you still have to turn off the eyes in the effect settings for the duration of the wink to allow the state effect to work, otherwise you just get a blend of eyes open and wink. 
Having extra eye states integrated into Faces Effect Settings would be nice to have but not critical.
You probably have loads of more important stuff to do.

Thanks for adding in the fine control on the wave effect, I know it was broken for 22.06 but I can now get the wave effect perfectly in time with the music with 22.07.

Regards,
Brendan.

**Comment by AzGilrock** [comment]
So have you tried the State effect with other blend modes so it will do an overwrite instead of a blend?

**Comment by Frowndon** [comment]
@AzGilrock 

Hi, yeh, tried them and all sorts of funny things start to happen, the mouth disappears or changes colour.
Bottom-Top kind of works but the mouth on my new model runs up the side of the face so that doesn't work either. 
As I said above it would be nice to have, that's all but I'm sure there are more pressing issues.

**Comment by AzGilrock** [comment]
I'm sure there is a way to accomplish this without changes but you need to provide a sample sequence or otherwise we end up creating a test that does not match your scenario and then it just frustrates everyone.

**Comment by Frowndon** [comment]
[Face eye test.zip](https://github.com/smeighan/xLights/files/8425005/Face.eye.test.zip)

I've attached a packaged test sequence (hope it works)

- The first wink is how I've being getting the prop to wink: sub model and turn off the eyes.(works)
- The second wink is just using states not turning off the eyes.(eyes open blended with wink)
- The third one (smiley face) is using states and turning off the eyes.(works)

I taught it would be handy to just select wink from the Faces effects settings instead of turning off the eyes to allow the sub model/state work.

There's probably a tick box somewhere that will allow the state to over ride the auto eyes but I just can't find anything.

**Comment by AzGilrock** [comment]
Thanks.  I'll try to remember to look at this tonight after work.

**Comment by AzGilrock** [comment]
Sorry forgot to look at this till now.  The problem is you are inserting the State effects below the Faces effects.  Effects on a model render bottom to top like stacking layers of paint so you need to swap the Faces layer and the State effects layer.  Also for the State effects you need to change the blend mode from Normal to Effect 1 so that you get a hard overwrite instead of a merged blend.

**Comment by Frowndon** [comment]
Thanks very much for looking at this for me but the mouth disappears when you you set it up the way you explained. I tried all the combinations of layers and blend modes before putting up the original post. I'm happy to just keep doing what I've been doing, I just taught it would be handy to select the other eye states(wink happy etc) from the Faces effect settings and not have to deal with layers and states/sub-models
![mock up](https://user-images.githubusercontent.com/88113304/162905891-40173830-d859-4f81-9222-583c2badbff2.jpg)
.

**Comment by Frowndon** [comment]
Thanks very much for your time and advice but messing around with channels and shadow models is too messy. I'll just continue on the way I've being doing it.
