### ISSUE TITLE
Crashes when trying to save

### ISSUE THREAD

**Issue by jerryszewc** [smeighan/xLights#319]
I am running 4.1.12. I have deleted 2 elements in the sequencer. I also deleted it on the layout and in the models. When I try to save it crashes.

**Comment by stevegiron** [comment]
Have you tried the latest release of 4.1.13?

**Comment by jerryszewc** [comment]
Yes I have but that is where it started so I came down one in hopes to fix the problem. this is what it stays like.
![capture](https://cloud.githubusercontent.com/assets/13650588/9075242/489cdb54-3ad8-11e5-86c6-0fe3d170c3a5.PNG)

**Comment by AzGilrock** [comment]
The best way to fix this is create a thread on the forum and attach a sequence plus the xlights_rgbeffect.xml file *BEFORE* you've done any of the deletions.  Then give the steps of what I need to delete and do to recreate the problem.

**Comment by stevegiron** [comment]
Is this still an issue?

**Comment by stevegiron** [comment]
No feedback for 28 days. Closing issue. Please reopen if need be.
