### ISSUE TITLE
Add remove model from group to the right click menu

### ISSUE THREAD

**Issue by MDickson00** [smeighan/xLights#3191]
In the layout tab when right clicking on a model within a group it would be useful to add the ability to remove that model from that group as opposed to using the groups menu below.

**Comment by MDickson00** [comment]
I replied to the email Gil, but in case it didn't go through. I meant right click in the list not on the model itself in layout.

**Comment by MDickson00** [comment]
After more discussion in Zoom about this, I understand that I was quite vague about the idea. When you expand a group in the group/model list, it would be intuitive to be able to right click on a model in that particular group list and choose remove from group, meaning that particular group. Please see attached image for reference, sorry for the confusion Gil, but at lease it's not DarylE making the request.
![right click menu](https://user-images.githubusercontent.com/83371818/162541814-caa08c3f-7f64-4e08-ae1c-72be7ff3ba16.png)

**Comment by dkulp** [comment]
This is already done. That's one of the enhancements I did at the Florida Mega Mini while listening to folks with similar struggles during the beginner class.

**Comment by MDickson00** [comment]
Thanks for the response Dan, I will look for it in the next release. I will quit spamming now.

**Comment by keithsw1111** [comment]
@dkulp ... did you check it in/push it? I dont see it in the commit log?

**Comment by dkulp** [comment]
Commit 62d51ce69a45261c5fd56a81cb16166fc2e40d0d

**Comment by keithsw1111** [comment]
Yeah ok ... was just looking at where your icon was and forgot the rows under were also you.

**Comment by MDickson00** [comment]
Apologies Gil, yes I meant from the list on the left side
