### ISSUE TITLE
Export House Preview - Not Working - Mac Version. 2022.07 and 2022.08

### ISSUE THREAD

**Issue by Darzoom** [smeighan/xLights#3199]
**Describe the bug**
Export House Previews produces green screen video.

**To Reproduce**

1. Open a sequence (Junk1.zip attached)
2. Render and save
3. Open File/Export Whole House Video/select save location
4. File produced is green screen (Junk1.MP4 attached)

https://user-images.githubusercontent.com/81765092/162626452-8ff0dff4-63bf-433c-aee8-3b45e37e8387.mp4

**Expected behavior**
Expect a video of the house affects running.

[Junk1.zip](https://github.com/smeighan/xLights/files/8459290/Junk1.zip)

**Screenshots**

None attached

**Versions (please complete the following information):**
 - OS: Mac Monterey 12.2.1
 - 2.6 GHZ Quad Core I7
 - 16gb 2133Mhz LPDDR3
 - Radeon Pro 450 2gb
 - Intel HD Graphics 530 1536 MB
 - xLights version 2020.07]

**Comment by bcarriveau** [comment]
It's a feature,  go to lor if you don't like it Dave🤣🙈 

Jk 😊

**Comment by whirlywhopter** [comment]
I am also running into what may be the same or a related issue with the whole house preview rendering.  My configuration is macOS 12.3.1 an M1 Max MacBook Pro running the current 2022.08 version of xLights.  I have also encountered similar rendering issues in previous 2022.x versions.  The setup I used for this testing was with two external monitors connected and the internal display disabled.  The primary monitor is a 4K display and the secondary monitor is a 1920x1280 monitor in portrait orientation.  Using the same process as the original post in this report and with the house preview window open full-screen, I am getting various different results:

With the preview window open full-screen on my 4K primary monitor, I am getting a video file that appears to have a resolution of approximately 3K by 1.5K and only shows the upper left-hand corner of the actual layout shown in the preview window.

With the preview window open full-screen on my portrait orientation 1920x1280 monitor, I get a video file with a resolution of approximately 2.4Kx3.8K, this time with the upper left-hand corner of the video now showing the same contents as the preview window and the rest of the video window filled with a green background.

**Comment by ponddude85** [comment]
No changes on .09. Still getting the same results.

**Comment by whirlywhopter** [comment]
I have not had a chance to check on all the scenarios above but .09 does seem to be rendering a 4K preview if I have the house preview window open full-screen on a 4K display.  I will try to do further testing when I get a chance.

**Comment by AzGilrock** [comment]
Closing since you opened a duplicate issue
