### ISSUE TITLE
Default port brightness missing on f16v4

### ISSUE THREAD

**Issue by computerdave200** [smeighan/xLights#3211]
In controller settings the default port brightness and gamma settings on the f16v4 is missing in 2022.08. I jumped on zoom room and verified with those online this evening. 

_
Version .07
<img width="687" alt="2022 07 brightness control visible" src="https://user-images.githubusercontent.com/51300984/164131123-a67bf9b0-fac7-4e9c-ba51-6cb15aa0c668.png">

version .08
<img width="698" alt="2022 08 default port brightness missing" src="https://user-images.githubusercontent.com/51300984/164131124-05142a50-2109-4a7c-8d7a-eea570c01622.png">

**Comment by computergeek1507** [comment]
fixed with 548c02cb02e68307d82e152c4a1e2fc5f8fe4b60
