### ISSUE TITLE
Sketch effect not allowing selection of an image file on Mac

### ISSUE THREAD

**Issue by whirlywhopter** [smeighan/xLights#3219]
When creating a sketch effect in 2022.08 on the Mac, the effect assist dialog does not appear to allow selecting any files for the background image.

1. Create a new Sketch effect on any sequence and select this effect on the Mac.
2. Open the Effect Assist window.
3. Click the "Browse" button beside the "Background:" entry and browse to a location with image files.

All files appear greyed out and cannot be selected in the effects assist window as a background image.  It does not appear to be possible to select any background images to use when tracing outlines on macOS.

This behavior was seen on both an M1-based Mac (MacBook Pro with M1 Max) and an intel-based Mac by another person in the Zoom room.  Other effects that use file selection such as the picture effect seem to be working as expected.

**Comment by KMojek** [comment]
Pretty sure this was fixed for 2022.09 here: https://github.com/smeighan/xLights/commit/efe00a66a6babc3b4ec19a391e2aef21b79f12ad Thanks Dan!

**Comment by whirlywhopter** [comment]
Fantastic!  I just checked and it does appear to be resolved on my installation.  I will do some more testing later with different file types.
