### ISSUE TITLE
Vertical line does not continue sometimes after pause and resume 

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#322]
A few releases ago , Gill added the 'vertical line' that moves along from the top across all cells of the grid when you play / pause etc :+1: 

I have noticed , however , that it you press Pause , then add an effect to the grid or even click on an empty cell in the grid , when you resume the sequence (by pressing the pause button again),  that vertical line does not then move along ie it remains where it was (and the time counter  and everything else is also 'frozen). The music does continue from where you left off.

So , what I then do is Pause again , click on the waveform from where I had paused and press the 'Start' button instead.

Is this as expected ? Or should I be doing something different after the first pause to resume?

Windows and 4.1.12

**Comment by AzGilrock** [comment]
Sounds like something needs to be looked at.  Technically there is a problem with what you are doing and I'll have to decide how to handle it.  You are trying to pause what we call Model Play mode and then drop an effect which initiates Effect Play mode and then trying to resume Model Play mode.  It's not really possible to flow those modes like that.  It's been real tricky trying to deal with all the possibilities of how these modes interact.  You can't be in both.

**Comment by gerry4** [comment]
Hi Gil,
 
Thanks for your reply.
 
Then don't worry about it if it is not easy to change behaviour.
 
I can quite easily click on the waveform (where I paused) to reset the pointer and continue from there.  Just have to teach myself to do that consistently, because if you forget to do that (before dropping or going to adjust the effect) , then you lose the point of where you were.
 
Particularly when you are trying to 'hear' the point to slightly move the effect to.
 
Regards
 
Gerard
 
Date: Mon, 10 Aug 2015 06:54:50 -0700

**Comment by gerry4** [comment]
Thank you !!
 
regards

Gerard
 
Date: Sun, 6 Sep 2015 20:54:24 -0700
