### ISSUE TITLE
Add New State Definition "stuck" in single node Mac ONLY

### ISSUE THREAD

**Issue by cybercop23** [smeighan/xLights#3229]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
After adding a new State Definition on a Mac and going back to edit it, it always reverts to Single Node

**To Reproduce**
1. Pick any model and add a new Node Ranges State Definition
2. Add 2 states with any node ranges and press OK
3. Go back to edit that same State Definition
4. You will see it saved it as Single Nodes vs Node Ranges

This works okay on Windows. Both Mac and Windows running the latest version.

**Expected behavior**
Expect the have the new SD as Node Ranges. Without that State Efffects will not work.

**Screenshots**
![image](https://user-images.githubusercontent.com/23619433/167049091-6b89a801-3595-4ee4-a429-3826e5ed6a44.png)

![image](https://user-images.githubusercontent.com/23619433/167049073-6e9abe4d-f2c0-42eb-90b9-6f41b0d34b2c.png)

**Versions (please complete the following information):**
 - OS: Mac 12.3.1 
 - xLights version 2022.09
**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by dkulp** [comment]
I cannot reproduce this.    I can create new states, set to Node ranges, add ranges, save, come back in and everything is still set to Node ranges.

**Comment by cybercop23** [comment]
@dkulp assuming you are doing this on a Mac? I had another regular Zoomer (is that a thing) try it on his Mac 22.9 and he had the same issue.

**Comment by merryoncherry** [comment]
I had all kinds of trouble in my first experiences with the model state dialog, including an issue that seems a lot like this one.  I took a pass over it and tried to fix as many as I could.  (Didn't get them all, but it's a bit better.)  PR inbound.

**Comment by cybercop23** [comment]
Seems to be working now. Closing
