### ISSUE TITLE
Universes and Channels Associated with Them

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#323]
This probably is not an issue, but me not understanding the process...

Why when setting up your networks (adding an E1.31), the channels are continuous?
In LOR I have my networks set up as :
Universe 1 Channel 1 - 483
Universe 2 Channel 1 - 512
Universe 3 Channel 1 - 512 
Universe 9 Channel 1-375 (not all of my Universes use all 512 channels) and so on until I get to Universe 12 thru 20. I want each of these Universes to have Channels 1-300 as each one will only control 100 nodes.

Is there no way to accomplish this? Or will it even matter when I export something to LOR?

**Comment by stevegiron** [comment]
You just need to add universes to the NC setup tab and define the last channel for each. You can add multiple universes at once with the last channel set to 300.

**Comment by jimswinder** [comment]
Steve.....I guess that is the issue then. I set the "Last Channel" to 300 but it just adds all the channels of each universe sequentially. See attached pic.
![nutcracker](https://cloud.githubusercontent.com/assets/13740582/9216496/e96f52c8-406e-11e5-84e5-eb2a127dc3e2.jpg)

**Comment by stevegiron** [comment]
Negative. Each universe still starts at 1 and ends at 300. The sequential
channels are the Nutcracker channels.

**Comment by jimswinder** [comment]
Well....that certainly is confusing...

**Comment by stevegiron** [comment]
If you had ten 1 dollar bills in your pocket they'd all start with 1.  But when you count them, you say one, two, three, four, five, six.....   If you had 20 dollar bills, you'd count 20,40,60, 80.  How can the 4th 20 dollar bill be 80????  Same as the 4th universe with only 20 channels in it. The last channel in NC would be channel 80. Hope that analogy makes sense.

**Comment by jimswinder** [comment]
Analogy makes sense...but don't see how it relates to this....I assign certain channels to universes but that is not what is shown. ..

**Comment by stevegiron** [comment]
On the E131 setup window you posted, where the last channel is 300, what is not shown is that the first channel is #1.  Each universe you have there (12,13,14,15) all have channels 1-300. They are unique because they are in different universes. If you know your model is plugged into the controller with universe #13, then you would define that model as starting on Nutcracker channel #301 on the model definition page.

**Comment by jimswinder** [comment]
Like I said at the start...it's probably me not understanding the process...which I still dont...lol
