### ISSUE TITLE
xLights 2022.09 crashes when changing Render Style

### ISSUE THREAD

**Issue by jstorms** [smeighan/xLights#3236]
**Describe the bug**
xLights 2022.09 crashes when changing Render Style

**To Reproduce**
Previously was running xLights 2022.4. 
Fresh install. Installed xLights 2022.9 on Windows 10
Start xLights 2022.09 64-bit
File -> Open Sequence -> Feliz Navidad - Jose Feliciano.xsq
Select Vu Meter on first model "_EVERYTHING-NotStrobes"
I've also seen this happen with other effects
Goto "Layer Settings" -> "Render Style" -> "Default Model as Pixel"
About a second later xLights crashes with a Debug Report
I've had issues with crashing on everything after xLights 2022.4

**Expected behavior**
Expecting xLights not crash ;)

**Versions (please complete the following information):**
xLights 2022.09

Device name	GRISWOLD-XPS
Processor	Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz   2.60 GHz
Installed RAM	32.0 GB (31.9 GB usable)
Device ID	0FC3B32D-6860-4C8C-B8FC-B08FA81BF8B1
Product ID	00325-95968-24966-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points

Edition	Windows 10 Home
Version	21H1
Installed on	‎10/‎1/‎2020
OS build	19043.1645
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was 
https://www.dropbox.com/s/55qy7e5bs081abg/xLights_dbgrpt-3228-20220510T165442.zip?dl=0
[xLights_dbgrpt-3228-20220510T165442.zip](https://github.com/smeighan/xLights/files/8665272/xLights_dbgrpt-3228-20220510T165442.zip)

**Comment by cybercop23** [comment]
I also get non-stop crashed on Mac/2022.9 I have several crash reports if needed. They should also (hoping) go to Dan via the App Store.

**Comment by keithsw1111** [comment]
I think this is already fixed.

**Comment by jstorms** [comment]
Verified fixed in nightly build: xLights64_2022_9_nightly-e4fb2db.exe
