### ISSUE TITLE
Details not shown in Test tab until Setup is edited and saved

### ISSUE THREAD

**Issue by rudybrian** [smeighan/xLights#324]
This was observed in xLights 4.2.0 on Mac:

If you create a new model and associate the channels with an existing channel defined in the Setup tab, the details (with the associated model and color) do not appear in the Test tab for the associated channels until one selects Change in the Setup tab, and then OK (no changes need to be made).

**Comment by stevegiron** [comment]
I marked this as a trivial but. I've always just accepted it as that's the way it works. Not sure if this is a bug or the application is not working the way you expect it to, or it's working exactly how the programmer designed it.

**Comment by rudybrian** [comment]
I would agree that this is trivial, but from a user standpoint the behavior isn't quite what I was expecting. I seem to recall having seen this in an earlier 4.x release, but it was probably masked by restarting xLights after adding my models.

**Comment by AzGilrock** [comment]
Keith isn't this fixed with your latest code?

**Comment by stevegiron** [comment]
The classification of Trivial, Minor, Major, Critical is by definition.

If it doesn't crash, or there's a work-around it gets marked as Trivial.  I
know 'trivial' can sound derogatory, however it allows the team to
prioritize the volunteer hours in their coding efforts.

-Steve

**Comment by keithsw1111** [comment]
I believe this is fixed with the new test dialog.
