### ISSUE TITLE
2022.10 Hang when applying singing face to model

### ISSUE THREAD

**Issue by jstorms** [smeighan/xLights#3243]
**Describe the bug**
xLights hang when placing Singing Face effect on model
my xlights config attached

**To Reproduce**
Start xLights v2022.10
Switch to Sequence Tab
Start new animation sequence, 40fps
Drag "Singing Face" effect to "Singing-Tree-01" model
Hourglass - hangs. I let it sit for 10 minutes. 
Killed xLights with task manager, xLights task listed as non-responsive
CPU usage 18-19.5% CPU, 297.2 MB, 5.3-5.6% GPU

**Versions (please complete the following information):**
xLights version 2022.10

**Attachments**
https://www.dropbox.com/s/qlrih3z9be7x55g/xLights2022v10_Hang_on_SingingFace_effect_placement.zip?dl=0
[xLights2022v10_Hang_on_SingingFace_effect_placement.zip](https://github.com/smeighan/xLights/files/8695613/xLights2022v10_Hang_on_SingingFace_effect_placement.zip)

**Comment by jstorms** [comment]
I need to get a different repro for attachment

**Comment by dkulp** [comment]
Duplicate of #3242 which is already fixed anyway.
