### ISSUE TITLE
Using Alt+drag to create a chase only works when dragging right

### ISSUE THREAD

**Issue by rudybrian** [smeighan/xLights#325]
This was observed in xLights 4.2.0 on Mac:

The feature @AzGilrock introduced in 4.1.0 that allows you to select a set of effects on multiple models and then hold down Alt while dragging the lower-right corner of the selected effects to create a chase appears to only work when the mouse is moved to the right. If you attempt to move the mouse to the left while the set of models are still selected, nothing happens. Per Gil's video associated with the 4.1.0 release (https://www.youtube.com/watch?v=5M9X2xKWSr0) this restriction should not exist, but may be Mac-specific.

**Comment by stevegiron** [comment]
You must have enough space/timing grid divisions available to drag to the left. I tested with 4.02.00 and it's working on Windows.  Confirm you have enough space to drag to the left.

**Comment by rudybrian** [comment]
Thanks Steve,

I added a second timing mark before the chase effects and it works as expected. This only seems to happen if you have effects starting at the first timing mark.

**Comment by AzGilrock** [comment]
The alt drag doesn't even look at timing marks it's using the sequence timing divisions.  So if you have a sequence with 50ms intervals and you want to drag 10 rows you need 500ms worth of space to accomplish that drag.  Currently I only allow drags that give perfect spacing between effects.  If I allowed anything less then some of the effects would get rounded to the nearest timing interval and wouldn't be even if you grabbed it to move it back to center.  I think this is working as designed.
