### ISSUE TITLE
Enhancement: Edit State Effect Created from DMX Effect

### ISSUE THREAD

**Issue by davidLCL** [smeighan/xLights#3250]
I'm always frustrated when programming DMX lights when I need to update positions, colors, or other attributes that I've saved into the State Effect.  This would allow for greater interoperability between different models of DMX lights.

I spoke with Keith Westley at Transworld about this and he recommended the enhancement of "Edit State Effect Create from DMX Effect".  This would allow you to re-load states created from the DMX effect back into the DMX effect, then allow them to be overwritten with the existing "Save as State" button.

**Comment by computergeek1507** [comment]
added

**Comment by davidLCL** [comment]
Awesome!  That was super fast!  One more quick tweak - the ideal workflow would be to then re-save the state under the same name to overwrite it.  

This would enable you to re-save the state and have all of the references to the state in the sequencer automatically update to the new values on the next render.  Is this possible?
