### ISSUE TITLE
issue with face effects locking up - crashes

### ISSUE THREAD

**Issue by dougiek1** [smeighan/xLights#3252]
to start, i am very new to this. 60 year old mechanical engineer is ADHD. not great at computers.  

I have sequenced 6 Halloween that all are ok with me and everything works.  I have tried to sequence this one three times and am having the same issue. 

To check the mouth movement I drag the face effects onto one of the singing characters and when I try to select the sound track or anything else it freezes my computer up. I have placed other effects on a singing character and the work fine.  then when i pull the face on the same thing happens.

**To Reproduce** drag face effect on to a singing character and try to assign the track it is to be associated with.
See round symbol showing the computer is working.  I waited over several hours on the third try. 
I expected the option to pick the vocals track
**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]  windows 11
 - xLights version [e.g. 2019.37] 2022.10 64 bit may 15 2022
 - 

**Additional context**
Add any other context about the problem he

I do not know how to do the drop box.  If needed, I can do this later.  just not sure, but I can learn
**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced **_**Please do not open, i do not know how to do the drop box**_**
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file
[Oogie Boogie's Song.zip](https://github.com/smeighan/xLights/files/8747924/Oogie.Boogie.s.Song.zip)

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
[Oogie Boogie's Song.zip](https://github.com/smeighan/xLights/files/8747925/Oogie.Boogie.s.Song.zip)

**Comment by computergeek1507** [comment]
It has already been fixed

**Comment by dougiek1** [comment]
Thanks, I searched for it before posting. what do i need to do

**Comment by computergeek1507** [comment]
Wait for the next release or download the nightly

**Comment by dougiek1** [comment]
thanks again
