### ISSUE TITLE
4.2 Papagayo removed "Auto" Papagayo faces for trees, matrices, etc.

### ISSUE THREAD

**Issue by mararunr** [smeighan/xLights#326]
Before, there was a default or auto face that could be used for trees, matrices, etc.  With 4.2 we lost that functionality.  Once you select the Faces effect with something other than "Default" you lose the ability to go back and use "Default" faces.

Example, in my papagayo song I have two singing coro faces (smart rgb), a matrix, and 2 mega trees (5 voices).  When I broke down words and added the Faces effect for the very first time to the matrix, the "Default" option was available from the dropdown to use the "default" as face definition with my matrix (no pictures just the standard default singing face).  This was available in 3.x as well to do easy singing faces for matrices and trees.  Then I went to one to my coro face models and selected "node range" for face definition.  When I went back to the matrix model the next time, the face definition was now "node range" and "default" is no longer an option (in fact there are no options because when you click on face definition drop down, it is only populated with node range, no other choices).

Please correct to always have "default" face option always available.

Thanks, mv

**Comment by dkulp** [comment]
Can you double check your model definition to make sure matrix was saved?   If NodeRange is in the drop down, then the Rendered won't be available.   After updating the model, you may need to click on an effect on a different model and then click back to force the list to update.

**Comment by mararunr** [comment]
Double-checked, matrix is vert matrix and both trees are Tree360....now, that being said, it seems to work fine now.  Not sure what's different but since I was sequencing in the middle of the night because of insomnia I'm going to remove/rescind.  Sorry Dan & crew, mv
