### ISSUE TITLE
Default Gamma Not Being Saved

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#3261]
**Describe the bug**
The default controller brightness is not being saved in the xlights_networks.xml file (I looked and no attr for that field).

**To Reproduce**
Selected a controller (tried both F40 & PB16 with full control) and set the gamma to 2.2.  Clicked save.  Closed xlights.  Opened xlights.  Observed the gamma is still 1.   

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2022.11

**Comment by computergeek1507** [comment]
fixed with f06cb540b0b2b0fca6cfd12e5637ccf3015a8e81
