### ISSUE TITLE
Link to forum doesn't work

### ISSUE THREAD

**Issue by Poporacer** [smeighan/xLights#3265]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

If you go to the help section in xLights and click the Forum button, it takes you to "https://nutcracker123.com/forum" which is a dead link. I think the link used to point to the Falcon Christmas Forum which has changed hosting?

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by tirebytr51** [comment]
At least for Firefox, the forum doesn't launch from the website either. Just get a blank page with no text or images.

**Comment by AzGilrock** [comment]
I don't think its hosting because the base .com address still works.  I don't think anyone but Sean can fix this and he probably won't be reading these issues.  He emailed about it a couple months ago so I thought he was going to fix it.

**Comment by keithsw1111** [comment]
I have removed the link until Sean decides to fix it.

**Comment by Poporacer** [comment]
No, no other way, there is another forum that is quite active than might help, https://falconchristmas.com/forum/
