### ISSUE TITLE
Custom Model Generator - xlights crash on exit (nightly build from 2 nights ago)

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3269]
Attached is a vid .. basically started the process, skipped ahead to process, pulled in some random video. It says cant find start, clicked next again then exited the dialog. Now closed xlights. No crash dump reported.

https://user-images.githubusercontent.com/4643499/171013915-cb6216b2-fdea-47c5-babd-7bab4d912b69.mp4

[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/8799157/xLights_l4cpp.log)
.

**Comment by keithsw1111** [comment]
I think I already fixed this but the daily build was likely not the one you used.

**Comment by keithsw1111** [comment]
I made a tweak ... but it will only help if you cancelled the scan pressing escape. I dont seem to be able to reproduce if i dont cancel

**Comment by derwin12** [comment]
In latest build, when X to close is pressed, it appears to close the dialog but then it prompts that no start channel was found. Closing xlights is now clean. Seems like this is fixed.
