### ISSUE TITLE
Creating model groups causes last created model to loose shape dimensons

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#327]
Version 4.02.00 on Windows
I created 6 models and sized them to 4/12 on the width/ht.
I placed the models in their layout areas, created a group and placed all 6 models in the group. I updated the group and the last model created lost it's 4/12 size. 

This is easily repeatable.

**Comment by AzGilrock** [comment]
Yeah there's a lot more bad things going on than that.  There were apparently a bunch of places that weren't updating the internal XML object and instead were saving to the XML file so when we quit saving that file every time you sneeze there are things that aren't being updated in the XML so if you do any operation that calls the UpdateModelsList() function then it reverts to the settings stored in the internal XML object.  So you lose any size, position, and rotation changes you've done.  Not sure if you lose anything else.

You can also easily recreate this by just moving a model and then right-click and select model properties and then OK and it will snap back to the original position.

The best bet for now is to hit the Save button after you make position changes.
