### ISSUE TITLE
Have to reset both model and house preview each time xlights is started.

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3272]
This started happening earlier in the year with the updates. Not sure if it is a common issue with others or something local to my environment. Might there be a "reset" that can be added to the code on startup that mimics be right clicking and resetting each of the windows?
2022-05-31 11:49:01,250 53484 log_opengl [INFO] ModelPreview - glVer:  3.3.0 NVIDIA 512.77  (NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2)(NVIDIA Corporation)

**Comment by keithsw1111** [comment]
Have you tried "Restore Default Viewpoint". It sounds like you set a default and now it is using it.

**Comment by derwin12** [comment]
Okay .. It does appear that my default is messed up .. so playing around in layout should be able to figure this out.. Thanks.
