### ISSUE TITLE
Model Groups Not Showing Up In Layout

### ISSUE THREAD

**Issue by tlindz** [smeighan/xLights#3274]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Model groups that I have created are not showing up in the Layout tab - Models.  They show up under my display elements but not under the Layout tab.   If I try to create new groups with the same name it tells me I can't

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
I have attached images to this case along with a zip file of my project show folder.  This is not a sequencing issue but a layout issue.

**Expected behavior**
Would expect the groups to show up in the Layout tab.

**Screenshots**
I have attached screen shots to this case

**Versions (please complete the following information):**
 - OS: Windows 10 Home Build 19044.1706
 - xLights version 2022.11

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
![xLightsGroupIssue](https://user-images.githubusercontent.com/69407437/171936040-211ab78b-ec9c-4cab-9f8e-e57a50430131.PNG)
![xLightsGroupIssue2](https://user-images.githubusercontent.com/69407437/171936811-cc782d38-8784-4a81-a437-8eadf04e9a61.PNG)
[xLightsIssue.zip](https://github.com/smeighan/xLights/files/8835296/xLightsIssue.zip)

**Comment by computergeek1507** [comment]
Try changing your Layout Preview to "All Models" and see if you accidently moved them to another preview

![image](https://user-images.githubusercontent.com/2293065/171942189-99a1cc87-2832-4d4d-866f-edf1bef35adf.png)

![image](https://user-images.githubusercontent.com/2293065/171942564-fba8ad6f-ee79-43ff-9519-86b87344c8d8.png)

**Comment by tlindz** [comment]
Scott,

You are the man and are 100% correct.  I knew it had to be something I was doing wrong.

Thank you very much for the quick reply.

Tim

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
