### ISSUE TITLE
Sub-buffer top/bottom by ramp value curve

### ISSUE THREAD

**Issue by cuneoxcuneo** [smeighan/xLights#3277]
**Describe the bug**
The sub-buffer size isn't growing/shrinking as set by the value curve for the top/bottom parameter values (Ramp).

**To Reproduce**
sequence attached

**Expected behavior**
sequence effects appear to work as expected in ver. 2022.10.
sequence effects do not work in 2022.11 or 2022.12.  Effects are present, but do not fill the expected sub-buffer.

**Versions 
 - OS: Windows 10 - 64bit (up to date as of 6/8/22 1:43pm pacific, per settings/Windows update screen)
 - xLights version 2022.12 64bit 

**Additional context**
I have checked each effect to verify there are no roto-zoom parameters being applied.

Mega tree is split into upper and lower effects (both Spiral). lower = bottom 0, top 43;  upper = bottom value curve ramp 45 -> 99, upper = top 100.
This works as expected - upper effect gradually "shrinks" as the bottom draws up toward the top of the tree.

As the upper spiral effect is drawing up, the meteors effect is supposed to fill in the space being vacated. This effect also uses value curves to ramp up the count and speed parameters.
Meteors = bottom 45, top value curve ramp 45 -> 100. (45->200 has same result)
Very little of the effect is visible at the very bottom of the sub-buffer area.  It doesn't expand upward to the top of the tree as the top parameter value increases.

At approx 20 sec into the sequence, the bottom spiral effect draws downward.  sub-buffer - bottom 0, top vc ramp 44 ->1.
This works as expected.

A separate meteors effect is supposed to fill the area vacated by the lower spiral effect.  No value curves for count or speed used.
Lower meteors effect sub-buffer : bottom vc ramp 44 -> 1, top 100.
The bottom of the meteors effect does move down as expected, however, the top (set to 100) also moves down.

**Attachments**

[test_Fails.zip](https://github.com/smeighan/xLights/files/8864907/test_Fails.zip)

**Comment by dkulp** [comment]
Will be fixed in .14
