### ISSUE TITLE
Questions on effect settings

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#328]
Hello Dan , Gil,
For the following effects , do you know / can you easily ascertain what the following attributes are meant to do:
Thanks

1. Circles:
--- Radial 3D

2. Pictures
-- Frame Rate Adj
-- Start position – wrap x

3. Single Strand
 --Chase : 3D Fade

4. Spirals
-- 3D
-- Grow
-- Shrink

**Comment by stevegiron** [comment]
I use most of these in my sequences. I'll input the data in the user manual.

**Comment by gerry4** [comment]
Thanks Steve,
 
I could not see any difference to the effect when I tried it , but then I am using a laptop , so it could be that my models and density etc made it such that the change was not visible or that it was the wrong model type.
 
Gerard
 
Date: Thu, 13 Aug 2015 08:40:10 -0700
