### ISSUE TITLE
Export House Preview Video quality dropped dramatically between 2021.40 and 2022.12 (Windows 10 OS)

### ISSUE THREAD

**Issue by tmeyermn** [smeighan/xLights#3282]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

Issue is independent of sequence

**Describe the bug**
When I compare the export house preview video between version 2021.40 and 2022.12 the video quality is much worse in 2022.12.  The filesize for the one exported from 2022.12 is smaller as well.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Export the house preview video from a sequence in 2021.40
2. Export the house preview video from the same sequence in 2022.12

**Expected behavior**
Exported video quality from version 2022.12 should be at least the same if not better than 2021.40.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2022.12

**Additional context**
Observed by Diana Stoffregen as well.

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
I do not wish to publish sequences publicly. If a sequence is required please PM me, thank you.

**Comment by derwin12** [comment]
asking the obvious .. you did maximize your house preview? (realize you are no rookie)

**Comment by tmeyermn** [comment]
Yessir, I understand having to ask lol  Let me know if  you need anything else.  It’s really the only thing keeping me from switching to the 2022 versions.   From: DarylSent: Friday, June 10, 2022 2:21 PMTo: smeighan/xLightsCc: Tim Meyer; AuthorSubject: Re: [smeighan/xLights] Export House Preview Video quality dropped dramatically between 2021.40 and 2022.12 (Windows 10 OS) (Issue #3282) asking the obvious .. you did maximize your house preview? (realize you are no rookie)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by computergeek1507** [comment]
when I do it the frame width and height is right but the data rate is 44kbps

**Comment by tmeyermn** [comment]
[image: image.png]

**Comment by tmeyermn** [comment]
oddly the audio bit rate is 129kbps vs 128kbps

**Comment by tmeyermn** [comment]
![Capture](https://user-images.githubusercontent.com/43391347/173168137-1ee8d32a-b78f-42b2-8eae-552fded4422a.JPG)

**Comment by derwin12** [comment]
Scott's change in the nightly build doubles up the values from the previous exports. Similar to what you were seeing in the 2021 exports.

**Comment by dkulp** [comment]
We're still talking about it.   It drops from h264 to mpeg4 encoding which is does not allow use of the hardware decoder on most SBCs (including Pi4).   Thus, we're still investigating if we can keep h264, but handle the bitrate better.  Stay tuned.  :)

**Comment by tmeyermn** [comment]
Thank you guys!
