### ISSUE TITLE
Select Effects .. show values in Min and Seconds to make it easier to find in the time line.

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3283]
Currently it shows the value in seconds .. but that makes it a bit tough (but not impossible lol) to find in the timeline.

![image](https://user-images.githubusercontent.com/4643499/173151410-de37eca9-667b-4fc7-a1c9-516fa50c5fc0.png)

**Comment by computergeek1507** [comment]
What would you suggest as a better solution then?

**Comment by derwin12** [comment]
Instead of 179s
Perhaps  2m 59s or whatever the format is on the timeline.

**Comment by derwin12** [comment]
Just grabbed a screenshot
So in the timeline its 1:35.000 whereas select effects would show 95.0s
Simple thing .. if its easy to implement.

![image](https://user-images.githubusercontent.com/4643499/173190504-4f83da33-f471-4745-8389-c875f272000e.png)
