### ISSUE TITLE
Countdown option for Text effect crashes 

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#329]
Select Countdown =  !to date !%tofmt
 
Enter the following date without quotes (ie exactly as follows) in the text field
/Fri, 25 Dec 2015 00:00:00 +0100/ %D

It should display a correct value eg 133d
(copy the previous string to the clipboard)
now try and enter - 

/Fri, 25 Dec 2015 00:00:00 +0100/ %c
it will crash. 
Restart xlights and paste the proper value back. Should be okay
Now try and change anything after the second / delimiter (whilst the countdown attribute has !fmt selected !!!!) . It will crash
Or try and change the delimiter to say '-' (whilst the countdown attribute has !fmt selected). It will crash

or even if you try one of the valid format values eg %H
I think the problem is that as you are changing stuff in the Line 1 attribute , it attempts to parse the text and so crashes (if the countdown attribute has !fmt selected at that point).
if you do not have the delimiters ie / / , then it wont crash or if you first add the text string with the Count down value to any of the other options , then after that change to the !fmt value. the issue is if you already  have the !fmt value specified first and then specify a text string that kind of passes the initial parser.

Back trace1:
x6a0a9f21 ZNK10wxTimeSpan6FormatERK8wxString
0x005bfd80              _fu3169___ZTV8wxBitmap
0x008352e6              _fu7689___ZN8wxString4nposE
0x004f6632              JobPoolWorker::Entry()
0x75f81328 endthreadex
0x7608ee6c BaseThreadInitThunk
0x77ac34c0 RtlInitializeExceptionChain
0x77ac3493 RtlInitializeExceptionChain

Crashed thread id: 62F8

Thread: 5900
    <idle>

Thread: 62F8
    Rendering layer effect for frame 2015 of P10 Matrix, layer 0.
    BUTTON_Palette1=#FF0000,BUTTON_Palette2=#00FF00,BUTTON_Palette3=#0000FF,BUTTON_Palette4=#FFFF00,BUTTON_Palette5=#FFFFFF,BUTTON_Palette6=#000000,CHECKBOX_LayerMorph=0,CHECKBOX_OverlayBkg=0,CHECKBOX_Palette1=1,CHECKBOX_Palette2=1,CHECKBOX_Palette3=1,CHECKBOX_Palette4=1,CHECKBOX_Palette5=0,CHECKBOX_Palette6=0,CHECKBOX_TextToCenter1=0,CHECKBOX_TextToCenter2=0,CHECKBOX_TextToCenter3=0,CHECKBOX_TextToCenter4=0,CHOICE_LayerMethod=Normal,CHOICE_Text_Count1=!to date!%fmt,CHOICE_Text_Count2=none,CHOICE_Text_Count3=none,CHOICE_Text_Count4=none,CHOICE_Text_Dir1=left,CHOICE_Text_Dir2=left,CHOICE_Text_Dir3=left,CHOICE_Text_Dir4=left,CHOICE_Text_Effect1=normal,CHOICE_Text_Effect2=normal,CHOICE_Text_Effect3=normal,CHOICE_Text_Effect4=normal,Effect=Text,FONTPICKER_Text_Font1='times new roman' 14 windows-1252,FONTPICKER_Text_Font2='segoe ui',FONTPICKER_Text_Font3='segoe ui',FONTPICKER_Text_Font4='segoe ui',SLIDER_Brightness=100,SLIDER_Contrast=0,SLIDER_EffectLayerMix=0,SLIDER_SparkleFrequency=0,SLIDER_Text_Position1=50,SLIDER_Text_Position2=50,SLIDER_Text_Position3=50,SLIDER_Text_Position4=50,TEXTCTRL_Fadein=0.00,TEXTCTRL_Fadeout=0.00,TEXTCTRL_Text_Line1=-Fri&comma; 25 Dec 2015 00:00:00 +0100- %,TEXTCTRL_Text_Line2=,TEXTCTRL_Text_Line3=,TEXTCTRL_Text_Line4=,TEXTCTRL_Text_Speed1=10,TEXTCTRL_Text_Speed2=10,TEXTCTRL_Text_Speed3=10,TEXTCTRL_Text_Speed4=10

Back trace 2
0x6a0a9f21 ZNK10wxTimeSpan6FormatERK8wxString
0x005bfd80              _fu3169___ZTV8wxBitmap
0x008352e6              _fu7689___ZN8wxString4nposE
0x004f6632              JobPoolWorker::Entry()
0x75f81328 endthreadex
0x7608ee6c BaseThreadInitThunk
0x77ac34c0 RtlInitializeExceptionChain
0x77ac3493 RtlInitializeExceptionChain

Crashed thread id: 65A8

Thread: 5F4
    Initializing rendering thread for P10 Matrix

**Comment by stevegiron** [comment]
I submit that this drop down option be removed from xLights. Nobody will miss it.. really.

**Comment by gerry4** [comment]
Hi Steve,
 
That's fine by me. Perhaps  just remove the format from the drop down box in case anyone ever wants those formats back ?


Gerard
 
Date: Thu, 13 Aug 2015 23:17:57 -0700

**Comment by stevegiron** [comment]
Gerry is this still an issue for you?

**Comment by gerry4** [comment]
Hi Steve, let me check after I install 4.2.15 . Only the last item would cause a crash and I did not see a fix mentioned in any release notes. (Not that people would use it really)
