### ISSUE TITLE
xLights crashes during a render all.

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#3291]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Shortly after clicking the 'render' button, xLights just closes with no error report.

**To Reproduce**
Load sequence
click the render button
Crash

**Expected behavior**
I would have expected a render to be completed, even the render progress never shows after clicking the rendering bar.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2022.12

**Additional context**
This has halted work on this sequence.

**Attachments**
No log produced.

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked. The sequence is a commercial sequence and can be provided upon request.

**Comment by keithsw1111** [comment]
Closing as no sequence is provided to reproduce the problem.
