### ISSUE TITLE
Todays Nightly build is not installable - it hard closes because of virus infection.

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3293]
Likely a false alarm but prior nightly builds can be installed. Something funky with the latest?

**Comment by bcarriveau** [comment]
**Same**
![2022-06-23 17_22_59-Windows Security](https://user-images.githubusercontent.com/60801063/175425041-69503aa3-3e2f-4286-8fa1-ca1c6a315930.png)

**Comment by derwin12** [comment]
Last nights is fine again..
