### ISSUE TITLE
Color Dropper Limits?

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#3296]
Is there a limit to the number of color that the color Dropper can display or read?  I have 117 color palettes saved in my folder.  I'd say that only the first 25-27 pallets are being displayed.  Can the color dropper be expanded to read all the color or is there a limit?

Thank you,
Clyde

![image](https://user-images.githubusercontent.com/12719816/175784462-2269fe5f-e1c5-40c4-a0c4-817df6778ffd.png)

**Comment by keithsw1111** [comment]
Max colours is currently set a 200. This was an arbitrary limit ... I am not sure how high it could go before performance issues arise.
