### ISSUE TITLE
Questions on functuonality

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#330]
Hello,

A few questions on functionality for the manual documentation

1. On the sequencer, if you right click there is an option to 'Export Model' . This brings up an 'Export Sequence' window where you can specify the type of file ie LCB etc. 
What exactly does this do ie does it copy all the effects in the song for that model so that you can then import into the respective sequencer ?

2. On the model list window, you can highlight one or more models and then click export csv . This creates a csv file , with one row per model etc. So what is the purpose of this ie what do you do with that afterwards ?

3. What is the purpose of the Play Model function (right click against the model name or Model group) - is it just to play it in the model window or is it used for something else / as well ?

4. In the Info/Media screen  (under sequence settings) , there is a tick box attribute ' Overwrite Media Tags'   . What does it do if ticked ie what are media tags ?

5. All the information on the meta data screen (eg author, song , artist , album etc) - what is the purpose of adding / updating anything here. Is it used anywhere ie either in xL or when an fseq is created ?  

regards

**Comment by AzGilrock** [comment]
1)  That's what its supposed to do.  Currently I believe there is a problem when trying to execute the Export Model for a model group.
2)  I've never seen it so if I knew what data it provides I could guess.  If it shows channel assignments then its probably just for folks that want to look at all their start channels and have a chart.
3)  When you play a sequence on the grid the Model Preview window only shows one model so if you choose this option then you are setting the focus of the preview window to that model and starting play.  It's really no different than hitting play and then clicking that model row.  I forget if it always starts at the beginning of the song or not but that's easy to test.
4)  When you choose a song we parse the meta data info.  That checkbox determines whether you want us to overwrite the metadata on the other tab.  Sometimes you've manually updated it and don't want it to be overwritten.
5)  That serves no purpose other than users wanted a place to store info like that and when sharing files it helps identify who created the sequence if filled out.

**Comment by gerry4** [comment]
Many thanks Gil,

Will update the manual today with this.

Date: Fri, 14 Aug 2015 05:58:07 -0700
