### ISSUE TITLE
Xlights not uploading outputs to Pihat

### ISSUE THREAD

**Issue by MDickson00** [smeighan/xLights#3301]
In xlights contoller tab choose FPP for vendor, choose Pihat for model, choose 2 output RPIWS281x, verfiy there are models assigned to ports in the visualizer and upload outputs, the outputs will not be uploaded. Rolled back to 2022.10 and this issue goes away. Seems to be specific to 2022.13

**Comment by computergeek1507** [comment]
Does a error popup appear or does it silently fail?

**Comment by MDickson00** [comment]
There is no error, the channels just do not get uploaded. Log files show nothing out of the ordinary.

**Comment by MDickson00** [comment]
Unfortunately the guy we were helping in zoom had to leave after we got him going. He was using a falcon pihat if that helps, the upload would say completed but nothing woul actually upload to the controller. We tried through the controllers tab and though FPP connect.

**Comment by derwin12** [comment]
Didnt see a pi-strings.json .. this appears to be a file that isnt uploading/showing on fpp
(json but uploaded as .txt)
[co-pixelStrings.txt](https://github.com/smeighan/xLights/files/9004504/co-pixelStrings.txt)

**Comment by computergeek1507** [comment]
fixed with 4cc19c72f323b17eb018999787e4a8590d31f49e
