### ISSUE TITLE
Release an arm64 version for Windows

### ISSUE THREAD

**Issue by craiz** [smeighan/xLights#3305]
**Is your feature request related to a problem? Please describe.**
Unable to run xLights on arm64 device running Windows.

**Describe the solution you'd like**
Install and run xLights on arm64 device running Windows.

**Comment by nking77750** [comment]
unable to install xlights to galaxy book go 5G    with arm64 CPU.  any ideas ?

**Comment by keithsw1111** [comment]
This is not a platform we specifically build for right now. If the windows or Linux builds work then this would be more good fortune right now than planned support. Maybe sometime in the future one of the current developers or a new developer will have such a platform and build for it but until then this is unsupported.

I am closing the ticket though as I dont see someone specifically going out and buying hardware just to address this ... it is more likely they will get the hardware and then decide to get it working on it and the existence or non existence of a ticket is not going to make a difference.
