### ISSUE TITLE
Export House Preview Video Quality

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#3309]
In late May, 2022 I began to notice the export preview videos were much lower in quality and definition.  I video the quality appeared grainy and with low definition.  I hadn't changed how I output my video, but soon realized if I extended the house preview box to a size slightly larger than my monitor (1920x1080), that this solved the problem.  Great, I had a work-around!    (FYI - I was able to increase the size of the preview window because I had multiple monitors (3wide x 2tall set.)  

Yesterday, I exported a preview video using the most recent release, 2022.12.  Using my work-around, the quality came out very poor.  Looking at the file sizes of the created MP4 videos, I noticed they are much smaller than they used to be.  MP4 files used to be 300mb - 500mb.  Now they are exporting as 35mb - 66mb.  I again tried my "fix", increasing the size of the house preview window even larger than the monitor, but that too did not work.  The quality issues seems to have started with the March release of 2022.05.  I didn't notice at the time and continued through using them in March and April.  

I have attached a screenshot of the video files and sizes I've created to-date.  You'll noticed the videos created in January and February are much larger file sizes using 2022.01 - 2022.04.  Some of the newer (May/June) videos with larger file sizes were created using my work-around.  It looks like the issue started in March with 2022.05, continuing to 2022.12.  The March/April videos show the smaller file size.  I was hoping the video export could be restored to it's former quality?

Thank you for looking into this.

Clyde

![image](https://user-images.githubusercontent.com/12719816/177005488-adfc7c57-5688-42e9-9fd2-0839515af056.png)

**Comment by dkulp** [comment]
The latest is 2022.13 and includes a bunch of fixes for video export.   In the preferences, there are also some settings for bit-rates and such to use.

**Comment by Clyde-L** [comment]
> The latest is 2022.13 and includes a bunch of fixes for video export. In the preferences, there are also some settings for bit-rates and such to use.
I'll have a look now and reinstall 2022.13.   Pardon me, I meant to say I was using 2022.13 yesterday when attempting this.... not 2022.12.  my fix for .12 still worked and is what I reverted to.

I'm reinstalling now and looking it over.

Thanks!

**Comment by Clyde-L** [comment]
Thank you.  I think I have the settings corrected for better output.  I didn't see the settings in the .12 version or notice anything in the .13 release notes.  After testing a number of output types, I've settled on MPEG4 @36000KB.  It seems to be the closest to original quality.

![image](https://user-images.githubusercontent.com/12719816/177009868-9ebf563c-9e22-4bc7-9310-1d87a1140084.png)

**Comment by computergeek1507** [comment]
I used H.264 with a bitrate of 9000 and got pretty good looking videos
