### ISSUE TITLE
More Models Please

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#331]
e.g.
Christmas Cane, Star Burst (e.g. like a + and x merged), Grid (off set matrix the lights on the second row are between the lights above and below, i.e. not a square grid).  Icicles,  e.g. 5 pixels down, then 4 pixels down then 3 pixels, down pattern repeats, each string down is a certain distance apart.
e.g. http://www.aliexpress.com/store/product/individually-LED-full-color-Icicles-string-DC12V-WS2811-controlled-all-white-wire-IP68-60nodes-set/701799_32310871722.html

Some basic shapes, e.g. Triangle,  Individual pixels,

**Comment by stevegiron** [comment]
These shapes are very customizable with the pixel orientation and layout. These are best modeled as custom models. 
Example on my pixicles 
![image](https://cloud.githubusercontent.com/assets/10568498/9280747/45e220d2-4275-11e5-8efb-765a130c43f1.png)
![image](https://cloud.githubusercontent.com/assets/10568498/9280764/5c12d414-4275-11e5-836f-512151f88180.png)

The Holiday Coro and Boscoyo standard shapes may be added later.

**Comment by damon-atkins** [comment]
![image](https://cloud.githubusercontent.com/assets/9368124/9977776/5daac9d2-5f56-11e5-9d00-4d991493ae2c.png)

The only problem i with this is when the items is rotated it will no longer fall with gravity.

**Comment by damon-atkins** [comment]
It would be nice to see complex models @smeighan

**Comment by damon-atkins** [comment]
I suppose you have rotate, you could add https://www.google.com/search?q=shear+transform

**Comment by damon-atkins** [comment]
Thanks for the, I need to down load the latest version now.
2016.15  Mar 30, 2016
   -- enh(@dkulp)  Add "Icicles" model

I think being able to shear would be still usefully for the custom designs.

**Comment by keithsw1111** [comment]
I think this is done.
