### ISSUE TITLE
Picture effect fails to load picture

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#3310]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
After pointing the effect to a png or .gif file the effect fails to show up in the effect.

**To Reproduce**
Browse to where the folder containing the pciture and select file.
Click update just to be sure
Render
Picture does not show up in Model preview window or house view when playing.

**Expected behavior**
Would have expected the pciture to show up in the preview window.

**Screenshots**
Not applicable

**Versions (please complete the following information):**
Windows 10
xLights version 2022.13

**Additional context**

**Attachments**
Attached is a sample sequence demonstrating the bug.
[Picture effect fail.zip](https://github.com/smeighan/xLights/files/9033352/Picture.effect.fail.zip)

**Comment by MrChristmas2000** [comment]
Further Information.
The problem may come from the fact that I use an external data drive and xLights may not be able to properly handle longer folder names.

**Comment by keithsw1111** [comment]
There is a special character in your folder name which xLights is not handling correctly. I suggest you remove it.

![image](https://user-images.githubusercontent.com/10283944/177018386-0a6320c2-1085-430b-9ad3-bfe2f88c1682.png)

**Comment by MrChristmas2000** [comment]
That was it, the " caused a lot of pain.
