### ISSUE TITLE
xscanner crashes as it processes thru the ips

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3312]
Some one on fb reported this, so I thought I would try as well. Mine is the nightly build from a couple nights back.

Here is the crash report - nothing really to note as it ran - it showed the various ips on my machine. Listed a couple OFFLINE then this came up.

[xScanner_dbgrpt-11248-20220703T170927.zip](https://github.com/smeighan/xLights/files/9035503/xScanner_dbgrpt-11248-20220703T170927.zip)

**Comment by keithsw1111** [comment]
I have added some logging if you try it again. I am pretty sure it is failing in the code that extracts the web page title but i cant see why. This may help isolate it.

**Comment by patdelaney** [comment]
I raised the question in the FB group and thank you for filing. I pull the latest nightly down. (xLights64_2022_13_nightly-60c2ed9) and reran, but not sure if the last nightly build has your logging.  I'll attach the xscanner_l4cpp.log
[xScanner_l4cpp.zip](https://github.com/smeighan/xLights/files/9039578/xScanner_l4cpp.zip)
.

**Comment by keithsw1111** [comment]
There is nothing in that log and based on time of day I doubt it was in the daily you used.

**Comment by derwin12** [comment]
After the nightly build with logging..
[xScanner_dbgrpt-50228-20220705T094537.zip](https://github.com/smeighan/xLights/files/9046832/xScanner_dbgrpt-50228-20220705T094537.zip)

Not sure I see much difference in the logs.

**Comment by derwin12** [comment]
Boring crash video..

https://user-images.githubusercontent.com/4643499/177344190-251721e4-18c3-4918-8540-a007db4e40b2.mp4

**Comment by keithsw1111** [comment]
Actually the log does have a message ... filtering to the crashed thread ...

2022-07-05 09:45:37,306 57144 log_base [DEBUG]     HTTP Connected.
2022-07-05 09:45:37,306 57144 log_base [DEBUG]     Getting the web page. <= this is the new log entry
2022-07-05 09:45:37,383 57144 log_base [CRIT] Crashed: Fatal exception occurred.

This tells me it is crashing in the CURL request which is earlier than i was expecting. I will come up with further logging to see if we can work out why.

**Comment by keithsw1111** [comment]
Can you add to xscanner.windows.properties in your xLights folder as an inserted line at line 9

log4cpp.category.log_curl=DEBUG, A1

Then grab the next daily build.

**Comment by derwin12** [comment]
Lots of new log entries in there..

[xScanner_dbgrpt-35380-20220709T084849.zip](https://github.com/smeighan/xLights/files/9076545/xScanner_dbgrpt-35380-20220709T084849.zip)

**Comment by patdelaney** [comment]
here's the log
[xScanner_l4cpp.zip](https://github.com/smeighan/xLights/files/9076590/xScanner_l4cpp.zip)

**Comment by keithsw1111** [comment]
I have checked in a possible fix. Pat's log didn't have a crash in it but Daryl's did.

**Comment by derwin12** [comment]
I couldnt use the nightly as it is flagged as a virus (again).. but here is the crash with the new .14 release.
[xScanner_dbgrpt-59676-20220710T092554.zip](https://github.com/smeighan/xLights/files/9079149/xScanner_dbgrpt-59676-20220710T092554.zip)

**Comment by derwin12** [comment]
Is it a particular IP that it fails on? Perhaps I can look into what that device is on my network?

**Comment by merryoncherry** [comment]
Last one mentioned in xScanner_l4cpp.log is:
 2022-07-10 09:25:54,553 42376 log_base [DEBUG] == Info:   Trying 192.168.0.74:80...

It seems to crash while dumping out the response.

I think it is coming from a line of Curl.h code like:
                logger_curl.debug(buffer.c_str());
Or
                logger_curl.debug(res.substr(0, 4096).c_str());

Both of these lines of code are big no-nos.  If there is a '%' anywhere in that response string who knows what'll happen, if it's a '%s' or similar it'll likely crash.

The correct code ought to be:
   logger_curl.debug("%s", buffer.c_str());
Or similar.

 I could make a patch for you to try but it won't be of use until someone commits it, or if you want I could give you an xScanner .exe to try.

**Comment by computergeek1507** [comment]
Here is a exe to try with the above fix
[XScanner.zip](https://github.com/smeighan/xLights/files/9079395/XScanner.zip)

**Comment by merryoncherry** [comment]
Thanks for that.
I think it may crash in another place - the original one - once debug log is fixed.
I'm curious what device was at that IP; if I have one I'll try scanning it.  (I'd scan my show network, but it isn't plugged in because... July :-D )

**Comment by keithsw1111** [comment]
I think @merryoncherry is right ... I have made that fix

**Comment by derwin12** [comment]
Scott -- I cant get that file .. VIrus again ..I will see if there is something I turn off windows to let me grab these things..

**Comment by derwin12** [comment]
Turned off virus protection. .. dropped in xlights folder, ran but it crashed with no debug. Grabbed a few IPs then spun and died.
