### ISSUE TITLE
Remove Auto Upload Configuration

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3319]
Show of hands to have it removed? Seems like it is never a good thing to enable ..

**Comment by dkulp** [comment]
Ummmm.... why?   It's a good way to make sure the controller has the proper configuration before data is sent to it.  IMO it should always be enabled.

**Comment by keithsw1111** [comment]
It would be nice if it was asynchronous to the output and somehow not interrupt output if the config was ok which it should be most of the time and not so problematic when the controller is offline. I also generally recommend people turn it off as it can make turning on output to lights really slow and people don't intuitively get the connection between this setting and that experience. As Dan says the outcome is desirable just the side effects don't always make it worthwhile.

**Comment by derwin12** [comment]
I guess its the unexpected-ness of it. For most people, then would be unaware of when it uploads and we are just getting them used to save, upload outputs, fpp connect. Having this auto upload has the potential to send an incomplete picture of their controllers. 
.. Just trying to simplify things in the zoom room when we say check this, this , not  this, this , this etc...
