### ISSUE TITLE
Network output delayed when xLights is in the background

### ISSUE THREAD

**Issue by rudybrian** [smeighan/xLights#332]
This was observed with xLights 4.2.0 on OSX Yosemite (10.10.4):

I was burning in some new pixels using an A-B-C-All cycle in the Test tab of xLights and my lovely new F16V2 and switched another app into the foreground with the xLights window just behind my active window. I noticed that the RGB transitions on my pixels slowed and occasionally stopped. If I then bring the xLights window back into the foreground the pixels would flash very quickly through the RGBW cycle (as though it was catching up) and then resume transitioning at the selected cycle speed.

I'm not sure if this is just OSX deprioritizing apps that aren't in the foreground, but thought I should mention it.

**Comment by dkulp** [comment]
This is OSX's App Nap feature.    I started looking at trying to figure out how to disable it when output to lights is turned on, but didn't get too far as it required objective C code which I didn't have a chance to figure out.

**Comment by stevegiron** [comment]
To disable App Nap on a Mac on a global basis, simply open the Terminal app and enter  the following command:
defaults write NSGlobalDomain NSAppSleepDisabled -bool YES

to reenable:

defaults write NSGlobalDomain NSAppSleepDisabled -bool NO

Not sure if xLights supports application NAP suspension as not all do.

Command + I  In the Get Info window, check the option to "Prevent App Nap".

**Comment by rudybrian** [comment]
It doesn't look like xLights has the "Prevent App Nap" option in the Get Info window. I am unable to disable it globally as this will have battery life consequences...
