### ISSUE TITLE
Last nights build - once again flagged with a virus (cant test xscanner Keith)

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3324]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
Works fine for me. Maybe include some more information on your setup.


![image](https://user-images.githubusercontent.com/2293065/177820241-5671592e-88cf-4887-843d-5d06542130b3.png)

**Comment by derwin12** [comment]
3 others in zoom had the same results. Seems windows 10 defender traps it.
During the unzip and run stage..

![image](https://user-images.githubusercontent.com/4643499/177837722-c3098c25-7109-4b18-994a-24e154f1ca53.png)
![image](https://user-images.githubusercontent.com/4643499/177837784-daa4780b-7cd8-4af7-b0a2-3c1d9234b9d9.png)

Likely just a fluke with the compile. Seems a common thing to have false positives with this particular virus.

**Comment by derwin12** [comment]
Same thing happens if I just try and zip unzip it. Windows defender says no way will this pass thru its guarded watch ..lol

**Comment by derwin12** [comment]
Last nights is fine .. weird ..
