### ISSUE TITLE
Moving Heads - remap channels - add offset, factor and zeroing

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3325]
Still working on a good way to map others MH sequences to a different MH.

When mapping channels (using the remap channels in dmx). What if there were 3 new columns added to the mapping dialogue.
..all optional

Offset. This value would be added to each value (for the particular channel) and mod 255.
[So if their pan was 80 for example, an offset of 30 would mean the mapped value would be code 110]

Factor. This value is multiplied to each value (for the particular channel)
[Say they have a 540 spin, I have a 360 spin. The factor would be 540/360 ie 1.5) - hoping you get the idea here]

Zero. This will zero out the from channel once the remap has been done. So if you remap channel 1 to 3, 3 gets the value, 1 gets a zero.
[what happens now is I map channel 14 to pan but channel 14 is left at the original sequenced value and messes up channel 14 since the original sequencer didnt need that channel)

Does this make any sense to be perhaps included?

![image](https://user-images.githubusercontent.com/4643499/177826489-4bcf120b-92bf-491d-b511-6cce214c74d2.png)

Perhaps a branch were we can test out this idea??

**Comment by keithsw1111** [comment]
Right now that dialog is a point in time process ... it has no ongoing impact on effect values which this idea would require.

For me a general solution for these sorts of things would be to make DMX models more conceptually virtual than they are today allowing the specification of a profile which could then be developed between the virtual model and the physical device. This virtual model would be able to as you say remap channels, realign value ranges etc.

This would be a breaking change although for existing sequences you could have a raw profile which just passes the values through in some unchanged way. Sequencers who would want to sell would need to redo their sequences to the virtual DMX props properties so they would eaily map to their clients devices.

This is an idea only ... there is so much about this that could prove impossibly complex to actually implement and even if it can be implemented providing a simple UI that doesnt confuse everyone could also be really challenging.

**Comment by derwin12** [comment]
I was thinking it would be a one time thing .. when the channels are mapped to the new channels, the non-zero effect values would be altered.

At this point the vendors are pushing out more and more MH sequences .. hoping to make use of their offerings..

**Comment by AzGilrock** [comment]
The best solution would be to scrap the current way of sequencing moving heads.  That’s why I wanted to create a Moving Head effect that would control using actual degrees of rotation which is universal.   We should never be trying to reverse engineer what a particular DMX value on one head maps to another.

**Comment by merryoncherry** [comment]
Makes sense @AzGilrock ... is it being planned / worked on?

**Comment by computergeek1507** [comment]
I started a branch with a "DMX Path" effect that I hope to do something similar to what Gil suggested. I want to create DMX "paths" based on degrees of motion and add 16bit support

**Comment by AzGilrock** [comment]
Yeah I was planning on having that ability already and pretty sure I talked about it.

**Comment by derwin12** [comment]
Just a followup .. mapping some MH stuff , the "zero" column I suggested might be better served as a empty value that one could enter 0 or any other numeric value. For example channel 6 for me, needs to be set to 16 to set the full on gobo. 
Currently being done via a bulk edit after the channel maps (along with the zeroing out of channels as mentioned above).

**Comment by danielrenwick** [comment]
This would be great to see

**Comment by danielrenwick** [comment]
Hi @AzGilrock  I was just wondering if this enhancement is in works. I am currently working on a presentation for MHs and one of the points of discussion is the home/rest position, so if there are any updates in progress I will gladly let them know. Thanks for all your hard work guys.

**Comment by computergeek1507** [comment]
I'm not Gil but I started working on this and got it working with non-values curve values. Scaling Value curves is more difficult to implement. ![image](https://user-images.githubusercontent.com/2293065/188758354-545776c4-2467-4a05-b705-800997b8de14.png)

**Comment by danielrenwick** [comment]
Thanks for that, yeah I'd imagine values curves will be challenging

**Comment by computergeek1507** [comment]
I added this, I didn't add the "zero" or "fixed valve" column, if you need to do this, you can set the scale to zero and it will zero the import value. Then the offset will be the "fixed valve".
