### ISSUE TITLE
Import Effects - Automap - find the strand name matches..

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3328]
Pressing the automap button it doesnt find the exact matches for strand names.
for example

Moving Head-1->Strand1->Dimmer

If finds and matches Moving Head-1 model.

Not a big deal if not implemented.

**Comment by computergeek1507** [comment]
Do you have some example files for this? I would like to see if I can fix it

**Comment by derwin12** [comment]
Here are some fake on effects stuff .. saw this for mh mapping but imagine it could be used in other places..
[MatchStrands.zip](https://github.com/smeighan/xLights/files/9181421/MatchStrands.zip)
![image](https://user-images.githubusercontent.com/4643499/180785366-c956c4ee-4d8e-4eb0-b550-ff57ea8c8c05.png)

**Comment by computergeek1507** [comment]
Fixed with a2bd130a94b94ea038afee67ec031ca5c818b963
