### ISSUE TITLE
Remove all overlays with a single request

### ISSUE THREAD

**Issue by ruskin0611** [smeighan/xLights#3332]
I use the 'Set pixels' and 'Set pixel range' APIs quite a bit to dynamically set the colors of various pixels when games are being played.

At the end of the game, I need to clear all the overlays so that when my general lights are brought back up, the pixels aren't still colorised from the previous actions.

To do this, I use the 'GetRangesSet' query and then iterate all of the overlay channels which it returns, and then call 'Set pixels' with the channel number and zero to clear that overlay.

In the instances where I have a memory game and display either 8 images (9 pixels wide by 11 high) or 12 images (9 pixels wide by 7 high), I can have between 756 and 792 overlays to clear.

Which means one call to get the ranges (GetRangesSet) and then up to 792 webservice calls for each of the overlays which need to be cleared.

Would really love an API command like 'Clear all overlays' which allows me to make a single webservice call and have xSchedule remove all the overlays.

**Comment by merryoncherry** [comment]
Ruskin and I are going to play with an implementation of this, unless the primary devs think that's the wrong idea.  Also #3329 (a small bug) and maybe #3330 (or something simple that would help cut the number of calls down).  Would certainly be interested in the thoughts, "gotchas", etc., to look out for.

**Comment by keithsw1111** [comment]
Have at it ... it shouldnt be that hard to implement.

**Comment by ruskin0611** [comment]
Released in version 2022.16
