### ISSUE TITLE
Allow adjustment of dynamic range of pixel brightness in the sequencer's preview panes

### ISSUE THREAD

**Issue by artwait** [smeighan/xLights#3338]
**Is your feature request related to a problem? Please describe.**
My display runs at 20% (set on the controller), but even with that, I find I sometimes need to reduce the brightness of an effect in xLights to <10%. When I do that, however, I find that I can no longer see the effect in the xLights Model Preview or House Preview panes, making sequencing difficult.

**Describe the solution you'd like**
It would be helpful to have a way to, say, compress the dynamic range of the rendered brightness in the preview panes, especially on the dark end of the brightness spectrum. Perhaps a slider (or two: one for the darkest end and one for the brightest end of the spectrum) in the View preferences or Sequences preferences. This would allow the user to intentionally boost the brightness of pixels in the panes without affecting the rendered output to the controller.

**Describe alternatives you've considered**
I've increased the pixel size in the Appearance of my models, and this does help a bit, but not enough without making the pixel sizes comically large.

**Comment by keithsw1111** [comment]
Why dont you just make the pixels bigger in the preview.
