### ISSUE TITLE
Missing matrix face images Network Shared Folder

### ISSUE THREAD

**Issue by jgvary** [smeighan/xLights#3342]
If you use Add Face Definitions to a Matrix, Then Download Images, Select a image, Select a Face, Insert Face.  The folder slashes flip from back slashes to forward slashes after the show directory folder.    they should be backward slashes for the download images location. This causes errors if you use a shared folder in windows.

![image](https://user-images.githubusercontent.com/67112140/179544419-b34e8f87-651f-4023-b5e9-582cc9887953.png)

This shows as an error in the Check Sequence log.  

    WARN: Faces effect image file 'X:\2022 Shows Folder 2/DownloadedFaces/Snowman03_AI_eo.png' not under show directory. Model 'Samsung Virtual Matrix', Start 0:00.000
    WARN: Faces effect image file 'X:\2022 Shows Folder 2/DownloadedFaces/Snowman03_E_eo.png' not under show directory. Model 'Samsung Virtual Matrix', Start 0:00.000
    WARN: Faces effect image file 'X:\2022 Shows Folder 2/DownloadedFaces/Snowman03_FV_eo.png' not under show directory. Model 'Samsung Virtual Matrix', Start 0:00.000
    WARN: Faces effect image file 'X:\2022 Shows Folder 2/DownloadedFaces/Snowman03_L_eo.png' not under show directory. Model 'Samsung Virtual Matrix', Start 0:00.000
    WARN: Faces effect image file 'X:\2022 Shows Folder 2/DownloadedFaces/Snowman03_MBP_eo.png' not under show directory. Model 'Samsung Virtual Matrix', Start 0:00.000
    WARN: Faces effect image file 'X:\2022 Shows Folder 2/DownloadedFaces/Snowman03_O_eo.png' not under show directory. Model 'Samsung Virtual Matrix', Start 0:00.000
    WARN: Faces effect image file 'X:\2022 Shows Folder 2/DownloadedFaces/Snowman03_U_eo.png' not under show directory. Model 'Samsung Virtual Matrix', Start 0:00.000
    WARN: Faces effect image file 'X:\2022 Shows Folder 2/DownloadedFaces/Snowman03_WQ_eo.png' not under show directory. Model 'Samsung Virtual Matrix', Start 0:00.000
    WARN: Faces effect image file 'X:\2022 Shows Folder 2/DownloadedFaces/Snowman03_etc_eo.png' not under show directory. Model 'Samsung Virtual Matrix', Start 0:00.000
    WARN: Faces effect image file 'X:\2022 Shows Folder 2/DownloadedFaces/Snowman03_rest_eo.png' not under show directory. Model 'Samsung Virtual Matrix', Start 0:00.000

It was suggested that I map a drive instead of using shared network names and that resolved the error message in the check sequence, but still flips the slashes from back slashes to forward slashes after the show directory folder.

![image](https://user-images.githubusercontent.com/67112140/179543880-1b3b19ff-b528-46e4-a0a0-454193542243.png)

Versions
 - OS: Windows 10
 - xLights version 2022.14 64Bit
[example.zip](https://github.com/smeighan/xLights/files/9133171/example.zip)

**Comment by keithsw1111** [comment]
The forward slashes are harmless. xLights handles them behind the scenes. Your problem was you were not using a drive.
