### ISSUE TITLE
Add gravity direction value curve to liquid effect

### ISSUE THREAD

**Issue by leelindquist** [smeighan/xLights#3343]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to see the liquid effect configurable with an adjustable gravity direction, ideally a value curve. Currently gravity always pulls the particles straight down. Since the particles have inertia and will bounce / flow off the bottom and sides, and they can be set to persist for an adjustable amount of time, it would be fun to be able to change the gravity vector while the effect is running / rendering to simulate a container that is rocking or tipping. 

**Describe alternatives you've considered**
I've considered using roto-zoom on the buffer to adjust the look of the effect, but that doesn't change the physics of the particles themselves. I'd like to be able to put a sinusoidal value curve on the gravity vector such that it looked like the "container" the liquid was in was rocking back and forth.

I've also considered using a shader, but haven't found one that acts like the liquid effect.

**Additional context**
Ultimately I'd love something that could produce an effect like this:
https://www.youtube.com/watch?v=k75IJKScU7s

**Comment by keithsw1111** [comment]
The particle simulator does not support a vector for gravity so this is not really possible.

**Comment by leelindquist** [comment]
I'm reading through the documentation on the Box2D engine, and it looks like gravity is defined in 2 dimensions, but is currently only implemented in the y dimension for this effect.

https://github.com/smeighan/xLights/blob/0fdd242af1da68e29a9cf492649a9d5cbc1663ae/xLights/effects/LiquidEffect.cpp#L590

What is unclear so far in my reading is whether gravity can be manipulated after the world is initialized. An answer on StackExchange related to this questions suggests yes, but I don't know how to go about testing that within the xlights effects rendering engine.

**Comment by keithsw1111** [comment]
Ah ... i missed that it was a vector.

**Comment by leelindquist** [comment]
Thanks! I'm excited to try it out.

**Comment by leelindquist** [comment]
I tried this in the windows nightly build 0edcbcc, and while the gravity direction slider does work (and does exactly what I expected!) clicking the value curve button for the gravity direction doesn't bring up the value curve dialog box. The value curve button for the gravity value (the one above) does bring up the dialog box as expected.
