### ISSUE TITLE
Build process documentation

### ISSUE THREAD

**Issue by ScobbyDoo** [smeighan/xLights#3347]
Previously i tried to build xlights in code blocks but no luck.
Any how i managed to work with install win10 sdk however its not mentioned in documentation for build in windows 

After that i also faced fome linking errors for libraries.

Is there any docker image like solution available?

I've some good suggestions to improve functionality & features in xLights( like web app cross platform input,remotehandling)

I will do that by pull requests 

Thanks

**Comment by keithsw1111** [comment]
We do not use Codeblocks actively for building xLights on windows. While it is not broken deliberately it is also not tested. All devs on windows these days use visual studio.

As for your changes for the bigger ones I suggest you pre-discuss them with any one of the core developers before investing too much time in them.  This can help you identify potential pitfalls or complexities you need to consider. This will help manage the risk that your change is rejected or even worse rewritten which can be a very frustrating experience. This can be done by posting a suggestion in a new ticket and ask for input or you can try messaging one of us directly. It really does not matter who you approach all are generally willing to help. As long as you are clear when you post an idea that you plan to implement it we will generally leave it to you to do so within a reasonable period of time (ie months).

**Comment by ScobbyDoo** [comment]
Initial i dont want to put effort to inject some critical changes from system side in xLights code base,all I'm trying to handle is raw byte configuration over the web app & cross platforms.

Apart from that virtual channel watcher,manual fader (runtime), bit rate,model building from web to direct xLights ,catch and loop data frames, midi cue player.

SDL2 in python will help to view virtual output to reduce configuration.

These are some features i want to test and contribute.

Except code blocks (as i read in documentation and follow that steps) i can also try in Visual Studio if their is any steps available to setups environment & build process.

Thanks.

**Comment by computergeek1507** [comment]
https://github.com/smeighan/xLights/blob/master/README.windows

**Comment by AzGilrock** [comment]
Figuring out how to build is your initiation to xlights developement.
