### ISSUE TITLE
CFBundleShortVersionString still set to 4.1.0 for 4.2.1

### ISSUE THREAD

**Issue by rudybrian** [smeighan/xLights#335]
I noticed that the "Version" string (a.k.a. CFBundleShortVersionString) given on xLights 4.2.1 on OSX is still showing 4.1.0.

The error can be corrected (manually) in line 18 of xLights/xLights-Info.plist.

**Comment by keithsw1111** [comment]
Given we are at 2016.37 I can safely assume we are not going to hop into a time machine and fix this one.

**Comment by rudybrian** [comment]
Hmm, it has been updated since I opened the issue, but master as of today (latest  commit b52c280be3b71da5d9f817c5082f4d258b1cd8f5) is lagging behind the current version:

```	<key>CFBundleShortVersionString</key>
	<string>2016</string>
	<key>CFBundleVersion</key>
	<string>21</string>
```

**Comment by AzGilrock** [comment]
What purpose does this serve?  Obviously our Mac developer who creates the OSX installations isn't bothered by it enough to keep it updated.

**Comment by rudybrian** [comment]
These fields are used by both iOS and OSX/macOS apps to identify the version details of the application (primarily used for version management in the respective platform's app stores). I found a good writeup on this here: http://stackoverflow.com/a/31921249:

"**CFBundleShortVersionString** gives you the version of your app. Typically, its incremented each time you publish your app to the AppStore. This is the version, that is visible on the "Version" section for the AppStore page of the application.

**CFBundleVersion** gives you the build number; which is used for development and testing, namely "technical" purposes. That means, the end user is rarely interested in the build number, but during the development you may need to know is being developed and fixed on each build. Typically, its incremented on each iteration of alpha testing. Continuous integration tools (like Jenkins) can auto-increment the build number's last digit on each build."

**Comment by AzGilrock** [comment]
Doesn't sound like it really matters for xLights.  We will never be in the AppStore.  That's the problem with having fields that someone has the manually update every build.  We already have the main version info that is manually updated and that is what is used to display the version in the title bar.  Since you care about this maybe you can volunteer to keep it updated.

**Comment by dkulp** [comment]
Exactly.  I couldn't find any purpose for this information from an xLights perspective.  It's not displayed anywhere, it's not used for anything within xlights, etc....   Not worth bothering to update all the time.

**Comment by rudybrian** [comment]
Thanks for the feedback guys. Ya, if there are no plans to publish to the appstore, and an auto-updater aren't on the roadmap this probably isn't needed.
