### ISSUE TITLE
xSchedule video flash on startup of video 

### ISSUE THREAD

**Issue by jimhays** [smeighan/xLights#3350]
I spoke to the xlights zoom room tonight and they suggested I post to this issues list , they though it may be an issue with how the graphics card is opened.  They suggested not to use the hardware acceleration, but as the issue also happens (much less frequently) in s/w only mode to post here in case it is a bug that could be addressed.

Background: 
I have moved my 36 song synchronized light show from LOR S4 to xLights over the past 5 months 

My problem is with the video that goes with each sequence / song.  The videos are pretty basic.   There is one video per sequence.

I am running on an HP laptop and the secondary monitor or video projector are connected through an extra hdmi port, 

Issue:
When I play my sequences with xSchedule and add video to each sequence using the Video option under xSchedule the system all works but I get a brief white flash at the start of the videos. Not all of the time (depending on how I have configured  - see below ) and not predictably.   I have done quite a bit of experimentation.  Other then the white flash at the start of the video it otherwise works fine. 

I have tried shortening my videos to slightly shorter than the FSEQ length, lengthening my videos to be slightly longer, and of course the default was to be the same length as the original song because in LOR you add the video to your song to play and they are one and the same.   Therefore the flashing when it occurs seems to be irrespective of the video length.  

I have broken out and added a 0, 1, 2, or 10  second delay as a separate step (not using the integrated delay within the FSEQ + video step), and I can see that the flash seems to occur at the start of the video, not at the end of the previous.  After that I went back to adding a 2 second delay within the FSEQ plus Video step. I have also tried no delay without any benefit, but my default is 2 seconds. 

I am speculating that under certain circumstances when the video player is opened there may be some form of initialization that occurs that generates the flash under certain circumstances.  That is just my speculation.  Note that in LOR I believe the video  player stays open between sequences/songs (or there was an option), I mention that as perhaps that is why I do not see a problem there. 

I thought perhaps it was my Graphics driver, but my drivers are up to date ( I did uninstall and reinstall to no effect).  So I thought maybe it was my hardware config, so I moved everything to a newer PC (both are running the latest windows 10).  The two PCs are roughly 2 years apart, and have different generation I7 processors, different internal intel GPU and different NVIDIA chip sets.  The same issues occurs on both systems.

I have turned off windows updates, turned off anti-virus (except for firewall protection), and I always start from a clean boot and wait for the system to settle down from all the stuff that occurs on start up. The only thing I use the PC for is to run xlights and xschedule, there is plenty of memory and disk storge is upgraded to solid state vs spinning media.  All of the controllers are attached and running on a hardwired network (they all show up as green in xschedule, although the LED rgb lights are not connected to them ).   

I have tried using both hardware acceleration and software only video options, and using the xSchedule video player with and without fast start audio, with and without cache video, and also tried using the “use media player option” which used the default windows media player.

For hardware acceleration I have forced the system to use the NVIDIA chip set and then alternatively the internal Intel graphics GPU without success.   I have also tried inserting longer or shorter delays between sequences (0 1,2,10 seconds).

I create my mp4 video files with adobe elements video editor, however I also tried other random mp4 files without success (they still flash).  I also tried downgrading and creating mpeg vs mp4 video files without success (to try different CODECs but still get the flash).

In each case I have create a 1920 x 1080 window (the same size as I render to in my video editor so no conversion in resolution) and the video window is positioned totally within my second monitor (with nothing else displayed on it) which is also my projector.  I get the same problem (flash) with the second monitor or if I replace with my projector.

What I have found is the following:

•	When using xSchedule with the windows media player (with hardware acceleration) I always 100% of the time get the flash at the start of the video.  This is unacceptable as the videos are set up as holographic style images back projecting on to a grey transparent screen and the white flash is very distracting.

•	When using the xScheduler video player with hardware acceleration, if the Windows focus is on the xSchedule window (meaning the xSchedule window is highlighted on the main screen) and nothing is displayed on the second monitor except for when the video is running then I very often get a white flash on the secondary monitor/projector but not always. 

•	When using the xScheduler video player with hardware acceleration, if the windows focus is not on the xSchedule window (meaning the xSchedule window is not highlighted on the main screen, but I have some another window on the main screen selected), then in a sequence of 36 songs I may see 5-6 flashes.  It seems like there are less flashes if the xSchedule window does not have focus, it may be unrelated but in multiple runs it is what I observe. 

•	If I turn off xSchedule h/w acceleration (so software only) and use the video cache setting and fast audio start (these two option may not be required but that is how I tested, I did try with and without but landed on that combination for other reasons)  and if the windows focus is not on the xSchedule window there are approximately  0  - 3  flashes across 36 songs, again when they occur they are at the start.  On average I would say 2 flashes occur out of 36 sequences.  If I have the focus on the xSchedule window then number of flashes increases even with this configuration, so I always  leave the focus on a different window.  Perhaps it is coincidence, but it is what I observed across several runs.

The net of all of this is I can probably run the show without hardware acceleration for video (given the small number of flashes)  , where the focus is on a separate window then xSchedule. However, without h/w acceleration xSchedule gives warnings about it taking too long for the video player to decode frames. As my images do not typically have a lot of movement that is probably ok.   I may just live with this or look at using the command interface and try using vcl open-source media player but would rather not add that complexity and I don’t know it would help.

Again, it seems like depending on the configuration the graphics driver may think it needs to do a reset or other such operation before starting the video which causes the flash?  Has anyone seen this?  Is there some other setting I could use to avoid?   Would it help to keep the video player open between sequences (like LOR) for each video in case it is an issue on open?   

The zoom folks ask me if the flash always occurs on the same sequence/video. Its does not. It does not appear to be deterministic except in the case of windows media player which occurs 100%.  The white flash is only visible on the screen for less then a second, but as the screen is set up for holographic video images where the background is otherwise black, it is very noticeable.

**Comment by keithsw1111** [comment]
I would need to see your xSchedule file to ensure I understand how it is set up.

**Comment by jimhays** [comment]
Hi Keith,
I have multiple versions of the schedule for testing different options,  Different resolution, delay, windows media player, etc
But the one that works the best with a small number of flashes is Christmans2022_1920x1080_FastStart_2sec,  I cloned it to Christmas2022_1920x1080_FastStart_2sec_ForKeith just to be clearer.  Thanks Jim
[xlights.zip](https://github.com/smeighan/xLights/files/9276846/xlights.zip)

**Comment by keithsw1111** [comment]
I have pushed a possible fix. You can grab it from tomorrows nightly build and try it.

**Comment by jimhays** [comment]
Hi Keith, I downloaded the build and have been testing all afternoon.  So far the fix is holding up.  I will keep testing but it appears that the flash is gone at the start of the video.  I have made it thru 50 or so sequences with video without a flash.  I am also able to turn on the hw accelerator option (with built in player) and it is also doing well no flashes at video start.   Thanks
