### ISSUE TITLE
Music does not start where you place the cursor in the audio track

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#3352]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When you place the cursor in the audio track where you want to start playing the playing cursor starts several milliseconds past where you want the music to start playing.

**Expected behavior**
I would expect the music to start playing where I placed my cursor or at the beginning of a highlighted area of the audio track

**Screenshots**
Video of such behavior is attached.

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10
 - xLights version [e.g. 2022.14]

**Additional context**

https://user-images.githubusercontent.com/3072139/181253432-a0935c5c-2e1b-4d00-890e-8c7a9a01f29a.mp4

None

**Attachments**
Music Wrong Starting Point.mp4

**Comment by derwin12** [comment]
I cant duplicate this .. how are you starting the music after clicking the wave form? I dont see the pointer going back to click the play icon.

**Comment by MrChristmas2000** [comment]
Well It has stopped doing that so I'll close it for now. Thanks for checking
