### ISSUE TITLE
On 2022.14 When running a colour blend in palette, a lot of effects such as galaxy, wave and even on effect are not allowing the clock to be changed to an arrow to tailor the colour switch.

### ISSUE THREAD

**Issue by Cattbeanie** [smeighan/xLights#3355]
To reproduce:

1. Go to palette in effect such as galaxy and chose a colour blend (ie red to yellow) it doesn't matter which colours
2. Click on the clock
3. It does not change to arrow on click

I was expecting to be able to change this from clock to arrows (up, left, down, right). This has previously been the case around this and other effects eg butterfly.

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
It is not meant to. Only some effects have spatial colour curves. Each has to be added individually and some are much harder if not impossible/irrelevant to add. This would be an enhancement at best and to be honest I dont think we need to hold it open unless there is a very specific behaviour you can describe that you are looking for that is not otherwise achievable.

**Comment by Cattbeanie** [comment]
OK - I was trying to use it on the galaxy setting - I will layer blend instead.  Thanks for getting back to me.
