### ISSUE TITLE
Adding Text Effect To Submodel of Matrix Crashing xLights

### ISSUE THREAD

**Issue by TripleJ3EB** [smeighan/xLights#3356]
New sequence in 2022.14, add a text effect to a submodel of a led matrix  (I have it setup to have a left half and right half).  effect will add to the timeline, but as soon as you change the text of the effect, it crashes.

It appears if you put it directly on the model and not a submodel it works fine.

**Comment by TripleJ3EB** [comment]
extra info:  animation sequence, windows 10.

**Comment by dkulp** [comment]
I cannot reproduce this on the Mac.  I can add test to various submodels of various matrices (Bottom half of tune to, middle section of mega tree, various parts of my bushes matrix, etc...)

**Comment by merryoncherry** [comment]
Can't repro on Windows either, with a regular matrix with 2 subbuffers generated, or node ranges.  Can you explain how your matrix is set up in more detail?  Horizontal/vertical? Alternate nodes? Submodel is node ranges / subbuffer, and what is the buffer style?   (Better yet if you can provide the layout files).  And similarly, any additional detail about the text effect, or a sequence file saved just before you make the change that will crash it... maybe a packaged export with the layout too.

**Comment by TripleJ3EB** [comment]
Thank you both for trying.  I had the problem on three different computers.  Setting up a separate show folder just now to send to you for testing to show the problem, it was doing it, but now I cant get it to do it anymore on any of them.  

I'm not sure what I changed to make it stop crashing, but seems i've done it.
