### ISSUE TITLE
Enhancement: File Save As menu

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#336]
Request a standard Save As menu dialogue window. 

![image](https://cloud.githubusercontent.com/assets/10568498/9297478/ef9b0bb2-4454-11e5-96ee-7af363b8cc93.png)

**Comment by AzGilrock** [comment]
Are you going to handle all the support emails when people get errors opening up the sequences because they didn't copy the rgb_effects over where they put the files?

**Comment by stevegiron** [comment]
I have sequence xml files in many different folders, all of them open and play fine. I have many different xlights_rgbeffects.xml files on my system as well. No errors happen because the show directory feature takes care of that.

**Comment by AzGilrock** [comment]
Yeah as long as you remember which show directory goes with which sequences.

**Comment by stevegiron** [comment]
This request came from not only what folder am I saving to, but what are the files named already in this folder, so I can keep a constant format.
