### ISSUE TITLE
Everything becomes extremely slow/laggy while sequencer is playing sequence

### ISSUE THREAD

**Issue by fone626** [smeighan/xLights#3363]
**To Reproduce**
Load a sequence and press space to get it playing.  Then while it playing do anything in the interface, it will be slow to respond.  After using the interface while playing getting the sequence to stop playing can take several seconds to respond.

**Expected behavior**
The interface should respond immediately and the sequence should stop playing when requested to do so.

**Versions:**
- xLights 2022.15 (previous version worked fine)
- Windows version (via wine)
- Linux version, both appimage and compiled

**Comment by david6101** [comment]
Exact same probs here...performance has markedly degraded after upgrading to .15, prev version worked fine...as an aside, I also performed an Nvidia driver upgrade yesterday, fwiw...

**Comment by derwin12** [comment]
Test case for me was a simple face effect for a singing bulb. Tag the 5 colours, change one colour, count to 3 and the colour changes then 1 second later the prop changes in the display. So like 4 full seconds to update the colour on a singing bulb face effect.

**Comment by david6101** [comment]
Yep-same behavior for me

**Comment by keithsw1111** [comment]
When playing what does the FPS look like? Can you try the nightly build. I am wondering if there is a bug or a build problem. I am not seeing similar obvious issues but maybe there is something about layout etc that might be causing it.

**Comment by derwin12** [comment]
Here is a simple vid of me changing the colors on a face effect. Takes a couple of seconds for it to update the UI and the model. I tried turning render off and the palette still took 4 seconds to refresh (7s to 11s). This is the nightly build - had to turn off MS virus detection and it flags this with a trojan

https://user-images.githubusercontent.com/4643499/183444373-57d12ed5-42c7-42f4-8986-dc44f9479701.mp4

.

**Comment by fone626** [comment]
> When playing what does the FPS look like? Can you try the nightly build. I am wondering if there is a bug or a build problem. I am not seeing similar obvious issues but maybe there is something about layout etc that might be causing it.

I'm getting 26 FPS, which is actually typical for this computer.  I've noticed that the FPS slows down on very high resolution screens, and speeds up as I lower the resolution of the monitor.  This computer has an AMD 3950x and 64 gigs of ram with an Nvidia 2080super on a 50inch 4K monitor.  I actually get better FPS on my 12 year old laptop because of the lower resolution.   Anyway, that's a separate issue.
I just installed a ton of nightlies trying to track down the bug and found the last "good" version was Nightly #187 29c297a the very next Nightly #188 0edcbcc has the sluggish behavior.

**Comment by keithsw1111** [comment]
I am not sure that is right ... they are pretty innocent changes.

Can someone add an actual layout/sequence that shows the problem because i am struggling to reproduce it.

**Comment by computergeek1507** [comment]
I reverted efc63dabf9f0305fab0bb40d401c0d7baf99ec14 and ac43d3038ffec41f95847c9baa12c71b8ab0364e, then it started working normal again for me.

![lag](https://user-images.githubusercontent.com/2293065/183649076-b775ed65-12b4-4f61-beac-f4f5cc24419a.gif)

[Keha Take It Off2.zip](https://github.com/smeighan/xLights/files/9290438/Keha.Take.It.Off2.zip)
.

**Comment by computergeek1507** [comment]
I made a test build with the old timer code if anyone want to test and see if it fixes there issues.
https://github.com/computergeek1507/xLights/actions/runs/2822840698

**Comment by derwin12** [comment]
Scott .. that build fixed my simple test case with the singing bulb colour changes.

**Comment by keithsw1111** [comment]
Tomorrows nightly build may have a fix for this

**Comment by fone626** [comment]
I built a copy with Keith's latest timer fix and it seems to have done the trick.  The interface is now responding quickly for me.
