### ISSUE TITLE
"Never Dock" popouts preferences checkbox. [ UI Enhancement ] 

### ISSUE THREAD

**Issue by stevelawrence66** [smeighan/xLights#3364]
Hi Devs,

I find that I'm constantly irritated when moving my preview model / house windows around my (super wide) screen - they constantly 'dock' in places that are hot-spots, when I just intended to move them off to a corner. 

I understand that I can ctrl-click-move to not have them dock on drop, but I also find this irritating ( we're getting into the realms of Blender level of 'remembering keys').

I'd like for a preferences checkbox to 'never dock' a popout window if that's possible? That way, you could treat a window move as 'always ctrl-clicked'  and I can swipe them around without my screen reconfiguring itself every time I it.

Thanks as always! Appreciate all the work!
Steve.

**Comment by keithsw1111** [comment]
I dont see an easy user experience here that would be any less frustrating. Most people either already have everything where they want it and dont move things around or are actively moving things around in which case sometimes wanting things to dock and not dock.

When you combine that with what the wxAUIManager can and cannot do I just dont see an obvious alternative better experience that is not just as obscure as holding down the control key.

Maybe we could add a sub menu allowing you to say never dock on a few of the panes ... but which panes. Likely house preview but which others. I dont want them all as the visual clutter would be too much.

**Comment by stevelawrence66** [comment]
I see your point - yeah. Effects windows, layer windows or colour windows all have their docked place. 

And yes - my main issue is with House preview and Model preview. 
But right now. I can pull out an effects window and ctrl-move it around and leave it undocked. I can have my layer settings sitting o'top of my Effects settings - just floating. 

So, maybe a toggle for docking? I almost *never* move anything *except* the preview windows, once I've got my layout all set up. The only things which *do* move are the preview windows. But for those I have to hold ctrl-move down every time it happens - which is fairly often. I'd rather ctrl-move to tell it to DOCK, than ctrl-move to tell it to not dock. 

So... Perhaps a setting which toggles the need to CTRL- to dock. If it's on? You have to ctrl-move to to dock a window, if it's off? It moves freely? ( And vice versa: If you have it on, then you NEED to ctrl-move to dock a window. 

You could leave it unset to preserve users learned behaviour and give people the choice if they want an 'alternative'. It trips me up all the time  - I don't *expect* a window to auto-dock in the Windows world if I 'just move it'

**Comment by keithsw1111** [comment]
flipping the ctrl behaviour is both tricky to do but also equally confusing as we have seen from the double clicking of effects.
