### ISSUE TITLE
Perspective windows not retaining their positions and they move on their own

### ISSUE THREAD

**Issue by JMHaro** [smeighan/xLights#3365]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I use dual monitors and my perspective windows are setup on the second monitor.  Every time I open 'any' sequence the perspective windows open about a header height lower than where they were last saved.  And then when I move each window back to the proper location, the rest of the windows drop down another header height.  I can supply a sequence but it occurs on any sequence I open up.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Save perspectives displayed on second monitor
2. Close out of xLights
3. Open xLights and open any sequence
4. The perspectives are not where they were and they will jump down when trying to realign them.

**Expected behavior**
The perspectives should remain where they were last saved and they should not move as you are moving other windows.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2022.14

**Additional context**
This never did this before and I've always had my perspectives on my second window for many years in the past.  It's definitely been occurring since .14, but I can't remember when it first started doing this, but it did start some time this year.

**Attachments**
[xLightsProblem20220806.zip](https://github.com/smeighan/xLights/files/9275597/xLightsProblem20220806.zip)

Video showing the issue (let me know if you can't get to the video):  https://www.dropbox.com/s/f12r8twvtefmnwr/Perspectives%20Moving%2020220806.mp4?dl=0

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.  
I can supply a sequence if one is needed, but it occurs on any sequence I open.

**Comment by tmeyermn** [comment]
I see the same thing, 2022.16.  All the undocked windows move when you move one of them.

**Comment by keithsw1111** [comment]
I have tried your layout and I dont seem to be able to reproduce the problem. Looking at your config I think your description above is missing a whole bunch of detail which may or may not be important. For instance you dont seem to be using auto save or default ... but a named perspective. You dont talk about how you created that ... maybe that is significant.

Unless we can get it to a point where we can reproduce it we are not going to be able to fix it.

**Comment by JMHaro** [comment]
What kind of more details do you need that might help?  I had created the perspective a long time ago.  I have two named perspectives, one for single monitor (which basically is close to the default) and then one for dual monitor so all the perspective windows (as shown in the video) are on my second monitor.

Like tmeyermn, I was still able to reproduce it in (2022.16 64bit).
I have my second monitor setup as in the attached image The top windows are at the very top of the screen.  I've named this perspective view as "2-Monitor View"
Then switch back to the "Default Perspective"
Then switch back to the "2-Monitor View"
    Everything jumps down about the height of a windows top border
They try to move each window back up to where it should be starting with the first top left window.  Once it's moved and dropped, then the rest jump down about another top border and this repeats with moving each one back up.
![2nd Montior Display](https://user-images.githubusercontent.com/3945942/188522045-fe5c5d9c-065d-4ecf-b95f-7a585639b5ca.jpg)

**Comment by tmeyermn** [comment]
Same behavior for me.  I have 4 monitors but use 3 of them for xlights.  The middle (main) screen is xlights, left screen is the house preview and right screen is menus (colors, effects settings etc).  When I start xlights and go into my sequence the house preview is lower (down and to the right about 50 pixels or so).  When I move it to the top and expand to full screen the menus on the right screen drop down and to the right 50 pixels or so.

**Comment by keithsw1111** [comment]
What are the properties of these monitors ... the display settings ... particularly those below. If you change it to 100% does the problem still occur. Not everyone is having this issue so we need to know what is unique about your setups. How does it vary between monitors. What is your main display vs non main screens?

![image](https://user-images.githubusercontent.com/10283944/189109073-4cbf8adf-351c-45df-8aa9-c2b841be75f7.png)

**Comment by dkulp** [comment]
Can someone check to see if it's still an issue with the nightly builds.   

It's likely part of https://github.com/wxWidgets/wxWidgets/issues/22533 or https://github.com/wxWidgets/wxWidgets/pull/22651 which the latest nightlies should be picking up.

**Comment by tmeyermn** [comment]
I just checked with a nightly build and also 2022.17 and it appears to be fixed.
