### ISSUE TITLE
xlight64 won't open on windows 11.

### ISSUE THREAD

**Issue by RodMachBR** [smeighan/xLights#3366]
Hello I need help.
I've been using xLights on my iMac, now I bought a new Windows 11 PC and I can't get xLights to open.
Opens xScanner64, xSchedule64 but not xLight64.
No error message nothing just doesn't run. I've tried to disable windows firewall, antivirus firewall but it's still not running.

**Comment by keithsw1111** [comment]
try running it from the command line with

xlights.exe /w

This will reset it to its newly installed state.

**Comment by RodMachBR** [comment]
Thanks, now at least I can run it, but still not 100%, it only runs through cmd.  (xlights /w)

Rodrigo

Send from my iPhone

On Aug 8, 2022, at 5:15 AM, Keith Westley ***@***.***> wrote:

﻿

try running it from the command line with

xlights.exe /w

This will reset it to its newly installed state.

**Comment by keithsw1111** [comment]
Could it be a problem with your show folder. Create a new one. Then save and close xlights and open again. If it works then most likely it is a problem with your show folder.

If so attach your networks and rgbeffects files ... maybe we can reproduce it.

**Comment by RodMachBR** [comment]
Now I able to open if double clic directly from my project, but still not working from icon on desktop.

**Comment by keithsw1111** [comment]
Again I believe it relates to your show folder ... without a copy of your networks/rgbeffects there really is nothing more we can do.

**Comment by RodMachBR** [comment]
Tks, everything works fine now.
