### ISSUE TITLE
Xlights .15 Freezing on Win 10 Pro

### ISSUE THREAD

**Issue by bobreese** [smeighan/xLights#3367]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
While building a sequence and testing it with the play / stop buttons, xlights freezes.
Task manager shows CPU continues to use 60+% of the CPU's and continues to use the network.

**Versions (please complete the following information):**
Windows 10 Pro Version 21H1
 - xLights version 2022.15 64bit

Xlights Freeze at 022-08-09 10:21:20,102 11716
This line in log was from me using the task manager to End Task
2022-08-09 10:45:56,407 11716 log_base [INFO] xLights Closing

[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/9292735/xLights_l4cpp.log)

**Comment by keithsw1111** [comment]
Tomorrows nightly build may have the fix for this.

**Comment by bobreese** [comment]
Thank you!
    On Wednesday, August 10, 2022 at 05:43:03 AM CDT, Keith Westley ***@***.***> wrote:  
 
 


Tomorrows nightly build may have the fix for this.
