### ISSUE TITLE
Diacritics in filenames causes sequence data to be lost

### ISSUE THREAD

**Issue by plbeaudoin** [smeighan/xLights#3368]
**Describe the bug**
I observed that if there are accented letters in the sequence's filename, then when I reopen it, all data will appear to be lost (no media, no effects in sequence).

**To Reproduce**
Create a new media sequence 
Select an audio file
Click on Quickstart (that part does not matter)
Add some data to timing tracks, place some effects on a few models.
Save the sequence, name it "Noël"
Reopen the sequence (File / Open / Noël.xsq)

**Current behavior**
The app shows an empty waveform area and no effects. Even the sequence settings don't show the media association.

**Expected behavior**
File is save/opened as if there was no diacritics in the filename.

**Workaround**
Avoid using accented letters in your filenames.  Alternatively, if you have already worked on a project and it seems all lost, rename the files to remove the diacritics and reopen it in xLights.

**Versions (please complete the following information):**
 - OS: macOS 12.1
 - xLights version 2022.14

**Additional context**
This is probably a generic issue with who unicode filenames are handled. This issue could be unique to Mac but I suspect it could also happen on other platforms.

**Comment by hsiboy** [comment]
I came here to see if anyone else was having a similar issue to this.
I'm running version 2022.16 and I have a sequence that won't load a video file because of an ö in the filename. Even after I changed the filename on the computer, I don't seem to be able to update the filename in xlights because it chokes as soon as it tries to read the nonexistent path.

Where are paths cached?

**Comment by dkulp** [comment]
This will be fixed in the next builds (on Mac).   That said, use of characters like that is STRONGLY discouraged.   There is definitely a good chance that uploading to FPP will not work properly with non-ascii characters in the file names.
