### ISSUE TITLE
xlights /w giving an error and not wiping?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3369]
Using .15 ran xlights /w as both normal and admin and the following is being displayed.

![image](https://user-images.githubusercontent.com/4643499/183748696-bc7660c6-9525-40dd-917a-2c5308c174ec.png)

The show folder does not reset - it should, shouldnt it?  So I assume the wipe didnt happen.
Is this just local to me  - or can others duplicate this?

**Comment by keithsw1111** [comment]
I suggest you run it as administrator ... failing that run regedit and delete it manually. As long as that is failing the wipe wont work.

**Comment by derwin12** [comment]
Some sort of corruption ..will google for an answer..
![image](https://user-images.githubusercontent.com/4643499/183903808-beb58f9e-fb37-4f07-9dc6-1eabf34ba33a.png)

![image](https://user-images.githubusercontent.com/4643499/183903741-19af2396-91b3-4713-839e-8bfe0fad3ba5.png)

**Comment by derwin12** [comment]
Found this utility that did the trick from MS.
https://answers.microsoft.com/en-us/windows/forum/all/removing-a-rogue-registry-key/cd841d75-c5dd-47e8-a515-6eb4c886a1c9
