### ISSUE TITLE
State Effect - copy and paste doesnt retain set values

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3370]
Create a state effect, change the timing track and/or the Mode and/or color.
Copy n paste the effect to a new prop - it will lose the values copied from the original effect.

Ver .14 and .15.

Tested with a timing track set, the pasted buffer is shown here.. (Appears that the timing track IS there)
CopyFormat1	0	1	1	0	0	PASTE_BY_CELL
State	E_CHOICE_State_Color=Graduate,E_CHOICE_State_Mode=Default,E_CHOICE_State_StateDefinition=,E_CHOICE_State_TimingTrack=New Timing	C_BUTTON_Palette1=#FFFFFF,C_BUTTON_Palette2=#FF0000,C_BUTTON_Palette3=#00FF00,C_BUTTON_Palette4=#0000FF,C_BUTTON_Palette5=#FFFF00,C_BUTTON_Palette6=#000000,C_BUTTON_Palette7=#00FFFF,C_BUTTON_Palette8=#FF00FF,C_CHECKBOX_Palette1=1,C_CHECKBOX_Palette2=1	7150	21150	8	-1000	0	2	66	39

**Comment by keithsw1111** [comment]
I think the bug is worse than that. If you set up 2 state effects and set them to timing track and then just highlight both by dragging a box around them ... I think it corrupts the settings of one of them ... the main selected one.
