### ISSUE TITLE
xschedule released version 15 generates enormous number of warnings and then hangs, version 14 worked fine with same xschedule file

### ISSUE THREAD

**Issue by jimhays** [smeighan/xLights#3371]
I moved from released version 13 to a nightly build of version 15 of xschedule to test a possible bug fix for bug #3350,  

The fix for bug #3350 worked, but I then ran into a separate problem where my log file grew without bound for several hours and then xschedule would hang. At the time of the hang the log file was too large to open with notepad. I tried several time and each time after a few hours into the play it would hang, that is when I noticed the log file being so large. 

I thought maybe it was related to the bug fix so tried the released version of xschedule 15 (without the nightly build fix for bug 3350) and the same behavior of the log file growing very large occurred. I rolled back to version 14 and had no issues with the log file.  Could the xschedule fix added in the "released" august 4th version (2022.15) of xschedule have introduced a side effect? 

What I see is an endless stream of  Log_frame [WARN] Timer: Frame event fire interval x ms less then 1/2 frame time...  These warnings come at a very fast clip.  These warning did not occur with this frequency in release 14 or prior with the exact same xschedule playlist.  I am using the same xsequence file that was attached to bug #3350.

I am attaching the log files from release 14 and release 15 (both the standard release, not the nightly build). for comparison.  Both log files were stopped at the start of the 4th song in the sequence approximately 5 minutes from the start.  The size of the release 14 log file is 709K, the size of the release 15 log file is 22.8M 

[xSchedule_l4cpp_rel14.zip](https://github.com/smeighan/xLights/files/9310493/xSchedule_l4cpp_rel14.zip)

**Comment by keithsw1111** [comment]
What frame rate is the song. Is it music or just animation or something else?

**Comment by jimhays** [comment]
HI Keith,  

 

They are all music sequences brought in at 20fps (50ms).  All of the music are mp3 files that I had used under LOR S4, for the sequences I either imported the LMS sequence, or imported from SS, and in others I just rebuilt from scratch natively.  It’s the same audio files I used with LOR S4.

 

I did not see this issue with xschedule version 13, version 14, or earlier versions (I have been working on this conversion from LOR since March so have been working across multiple versions without problem). I only saw this stream of warnings  when I went to release xschedule V15. 

 

Everything seems to work its just the log file grows so big and eventually the xschedule just stops playing (hangs) mid song somewhere into the second loop.  I have around 36 songs so it runs just under 2 hours before it loops. 

 

I downgraded to V14 and it worked, went back to v15 and it did not, went back to V14 and it worked and then went back to v15 and it did not.   The songs and playlist I tested with all are identical between runs on each version, I am not changing anything else.

 

For the last two runs one each on V14 and V15 I let them both play for 5 minutes so you could see the difference in the logs for the same exact set of songs at the start of my playlist.

 

Of course, I am running video in xscheduler alongside each sequence in case that is related.  I did not reattach the xschedule file to this bug report as it is the same as I had sent with the other bug you fixed around the white flash when video starts.

 

That fix for white flash worked great, but that is when I noticed the warnings and hang, but as I said I reverted to the standard V15 release (without the fix) and still saw the same WARNING issue which is why O wondered if it could be related to the xschedule fix in the published version of V15?

 

Let me know if there is any data I can provide to help. 

 

 

Jim

**Comment by jimhays** [comment]
I am trying to look up a tool that would let me tell you the frame rate of the songs, its not something I usually look at but will goggle and see what tool I can use and get back to you on that

 

From: Jim Hays ***@***.***> 
Sent: Friday, August 12, 2022 3:44 PM
To: 'smeighan/xLights' ***@***.***>; 'smeighan/xLights' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [smeighan/xLights] xschedule released version 15 generates enormous number of warnings and then hangs, version 14 worked fine with same xschedule file (Issue #3371)

 

HI Keith,  

 

They are all music sequences brought in at 20fps (50ms).  All of the music are mp3 files that I had used under LOR S4, for the sequences I either imported the LMS sequence, or imported from SS, and in others I just rebuilt from scratch natively.  It’s the same audio files I used with LOR S4.

 

I did not see this issue with xschedule version 13, version 14, or earlier versions (I have been working on this conversion from LOR since March so have been working across multiple versions without problem). I only saw this stream of warnings  when I went to release xschedule V15. 

 

Everything seems to work its just the log file grows so big and eventually the xschedule just stops playing (hangs) mid song somewhere into the second loop.  I have around 36 songs so it runs just under 2 hours before it loops. 

 

I downgraded to V14 and it worked, went back to v15 and it did not, went back to V14 and it worked and then went back to v15 and it did not.   The songs and playlist I tested with all are identical between runs on each version, I am not changing anything else.

 

For the last two runs one each on V14 and V15 I let them both play for 5 minutes so you could see the difference in the logs for the same exact set of songs at the start of my playlist.

 

Of course, I am running video in xscheduler alongside each sequence in case that is related.  I did not reattach the xschedule file to this bug report as it is the same as I had sent with the other bug you fixed around the white flash when video starts.

 

That fix for white flash worked great, but that is when I noticed the warnings and hang, but as I said I reverted to the standard V15 release (without the fix) and still saw the same WARNING issue which is why O wondered if it could be related to the xschedule fix in the published version of V15?

 

Let me know if there is any data I can provide to help. 

 

 

Jim

**Comment by jimhays** [comment]
I don’t know if this is helpful or what you wanted but windows properties detail show different bit rates:

 

For the first Intro in my playlist was recorded on my iphone and probably converted to mp3 :  176kbps

The first song is an older recording of Burles Ives Holly Jolly Christmas : 128kbps

The next song is Christmas vacation : 128kbp

The next song is We need alittle Christmas: 128kbps

 

I see others at 192kbps, or 256kbps, most seem to be 128kbps

 

There is one at 160kbps

 

Jim

 

 

From: Jim Hays ***@***.***> 
Sent: Friday, August 12, 2022 3:50 PM
To: 'smeighan/xLights' ***@***.***>; 'smeighan/xLights' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [smeighan/xLights] xschedule released version 15 generates enormous number of warnings and then hangs, version 14 worked fine with same xschedule file (Issue #3371)

 

I am trying to look up a tool that would let me tell you the frame rate of the songs, its not something I usually look at but will goggle and see what tool I can use and get back to you on that

 

From: Jim Hays ***@***.*** ***@***.***> > 
Sent: Friday, August 12, 2022 3:44 PM
To: 'smeighan/xLights' ***@***.*** ***@***.***> >; 'smeighan/xLights' ***@***.*** ***@***.***> >
Cc: 'Author' ***@***.*** ***@***.***> >
Subject: RE: [smeighan/xLights] xschedule released version 15 generates enormous number of warnings and then hangs, version 14 worked fine with same xschedule file (Issue #3371)

 

HI Keith,  

 

They are all music sequences brought in at 20fps (50ms).  All of the music are mp3 files that I had used under LOR S4, for the sequences I either imported the LMS sequence, or imported from SS, and in others I just rebuilt from scratch natively.  It’s the same audio files I used with LOR S4.

 

I did not see this issue with xschedule version 13, version 14, or earlier versions (I have been working on this conversion from LOR since March so have been working across multiple versions without problem). I only saw this stream of warnings  when I went to release xschedule V15. 

 

Everything seems to work its just the log file grows so big and eventually the xschedule just stops playing (hangs) mid song somewhere into the second loop.  I have around 36 songs so it runs just under 2 hours before it loops. 

 

I downgraded to V14 and it worked, went back to v15 and it did not, went back to V14 and it worked and then went back to v15 and it did not.   The songs and playlist I tested with all are identical between runs on each version, I am not changing anything else.

 

For the last two runs one each on V14 and V15 I let them both play for 5 minutes so you could see the difference in the logs for the same exact set of songs at the start of my playlist.

 

Of course, I am running video in xscheduler alongside each sequence in case that is related.  I did not reattach the xschedule file to this bug report as it is the same as I had sent with the other bug you fixed around the white flash when video starts.

 

That fix for white flash worked great, but that is when I noticed the warnings and hang, but as I said I reverted to the standard V15 release (without the fix) and still saw the same WARNING issue which is why O wondered if it could be related to the xschedule fix in the published version of V15?

 

Let me know if there is any data I can provide to help. 

 

 

Jim

**Comment by keithsw1111** [comment]
Tomorrows nightly build has a fix for this.
