### ISSUE TITLE
Changing effects grid spacing reduces the visible size of the model list in sequencer.

### ISSUE THREAD

**Issue by MDickson00** [smeighan/xLights#3372]
By default the effects grid sizing is set to "small", if you change it to "extra small" it does shrink the grid, but it also shrinks the visible area for your list of props. See attached photos.

Image 1 shows the effects grid set to "small" image 2 shows the effects grid set to "extra small", notice the empty space at the bottom of the prop list, this should be populated with more props in the list, it does still let you scroll down to view the rest of your props as seen in image 3.
![xlights1](https://user-images.githubusercontent.com/83371818/184241674-a83d8899-bacc-4de7-9bbd-1efdb94e0bef.png)
![xlights2](https://user-images.githubusercontent.com/83371818/184241696-b4ccf6ff-737f-477f-87db-022d21df0e39.png)
![xlights3](https://user-images.githubusercontent.com/83371818/184241716-3bedb552-a889-4617-b9be-ab77d704da78.png)

**Comment by derwin12** [comment]
I think I posted this before as wel.. Mark change from Master View to something else and back .. is it just a refresh issue?

**Comment by MDickson00** [comment]
Refreshing by changing the view, does in fact fix the issue.
