### ISSUE TITLE
Add ability to use xmaphint to map to a sub-model

### ISSUE THREAD

**Issue by cybercop23** [smeighan/xLights#3373]
I'm using the new xmaphint feature to create a "master" auto mapping file to use across all of the vendors that I have sequences for. This is an awesome feature and works great on groups and individual models.

However, I need to map a group (or even a model) to a submodel, and that doesn't seem to work currently.

I tried different ways to indicate a sub-model, \\ \\/ \t \ but nothings seems to work.

Here's an example:
  <Map ToRegex="ST Snowflake\Shuttles" FromModel="Door Star Wreath"/>

**Comment by keithsw1111** [comment]
Example did not come through

**Comment by cybercop23** [comment]
Arggg.... fogot to include it.
Tried all these combinations.

  <Map ToRegex="ST Snowflake\Shuttles" FromModel="Door Star Wreath"/>
  <Map ToRegex="ST Snowflake\\Shuttles" FromModel="Door Star Wreath"/>
  <Map ToRegex="ST Snowflake\\/Shuttles" FromModel="Door Star Wreath"/>
  <Map ToRegex="ST Snowflake\tShuttles" FromModel="Door Star Wreath"/>
  <Map ToRegex="ST Snowflake\\tShuttles" FromModel="Door Star Wreath"/>

**Comment by cybercop23** [comment]
Ahhhh... maybe I didn't forgot. Looks like it gets truncated..... Removed XML marker

 Map ToRegex="ST Snowflake\Shuttles" FromModel="Door Star Wreath"
 Map ToRegex="ST Snowflake\\Shuttles" FromModel="Door Star Wreath"
 Map ToRegex="ST Snowflake\\/Shuttles" FromModel="Door Star Wreath"
 Map ToRegex="ST Snowflake\tShuttles" FromModel="Door Star Wreath"

**Comment by computergeek1507** [comment]
added with ac684420d077c8a672c728c35f26980c418016da
