### ISSUE TITLE
Sequencing of Native Star at Layer level seems broken (again?)

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3375]
Seems like this was broken before and fixed? (Noticed from a zoom roomer - confirmed in v15 nightly)

6 Layer Star - native model. Throw and ON effect on strand 1 and it lights up something like the first x pixels from the start point and not the inner star.

I have my renamed - but here is what I am seeing.
![image](https://user-images.githubusercontent.com/4643499/184553572-53c5bccf-d1eb-4c0c-a372-5533b0f00bc1.png)
![image](https://user-images.githubusercontent.com/4643499/184553558-4cd09e56-e00f-440e-bd6e-57e75431c592.png)
![image](https://user-images.githubusercontent.com/4643499/184553587-38de69c9-ce46-48be-b889-067d3a5d1550.png)

**Comment by derwin12** [comment]
NOTE: May be working in v14.

![image](https://user-images.githubusercontent.com/4643499/184553612-809bc45e-0bf4-4064-abcd-caec22088e2a.png)

**Comment by computergeek1507** [comment]
fixed with 5f2d5a3b57e98942d751ec71baff71decd630c95 and 3fdab8f6ebeb6f91593e79fdc714f26f256d75ba
