### ISSUE TITLE
Enhancements for Shape effect

### ISSUE THREAD

**Issue by kkatee** [smeighan/xLights#3376]
There is two enhancements I would like to see for the Shape effect if possible.

1. Some method for having custom shapes.

2. Being able to have multiple characters when using emoji/text.

I have been able to work around this by creating a custom font that contains the things I need, but its not the most straightforward workaround :D

**Comment by keithsw1111** [comment]
I have added SVG files. Not going to do #2 ... just add 2 effects on different layers. If you want the 2 characters together then you need something other than the shape effect.

**Comment by kkatee** [comment]
Thanks Keith, I can always just make the 2 characters into an SVG :D
