### ISSUE TITLE
Keep Remote Falcon from restarting already playing sequence if set to overlay

### ISSUE THREAD

**Issue by Randomaker** [smeighan/xLights#3378]
The "play as an overlay effect" option in Remote Falcon works great for my use, so thanks for adding it! But there's one problem with it that could be quite useful to fix.

xLights reports the currently playing main sequence back to Remote Falcon, which means that it doesn't know whether an overlay is playing or not. Thus, it allows it to be selected again, starting it over.

The ideal fix for this would be to talk to the owner of Remote Flacon and add overlays as a global feature, but I'm sure that would take a lot of work on both sides.

For now, I think the best option would be to report back the overlay sequence instead of the main sequence, but ONLY if it was started by Remote Falcon. This isn't ideal as "Currently Playing" on Remote Falcon wouldn't work if using the overlay feature, but its not super important for this use case.

Thanks again!

**Comment by keithsw1111** [comment]
I have added an option to RF which allows you to tell the client to send the first playing effect as the current song instead of the playlist song. This is difficult to setup and test so if you could download the daily build from github and try it i would appreciate it. Give it about 16 hours from now to update.

**Comment by keithsw1111** [comment]
So the nightly build looks broken ... try this version: https://www.dropbox.com/s/9gaf000cdvoky5y/xLights64_2022_16.exe?dl=0

**Comment by Randomaker** [comment]
It doesn't seem to be enabling viewer control. But I went back to the last released version (2022.16) and it isnt working correctly either.

Here is the log-

Fetching current playing mode ...
{"viewerControlMode":"jukebox","remoteSubdomain":"joyorama","interruptSchedule":false}
MODE: jukebox
SUBDOMAIN: joyorama
Asking remote falcon to enable viewer control.
Uploading playlist to Remote Falcon.
    {"message":null,"currentPlaylist":null,"nextScheduledSequence":null,"viewerControlMode":null,"viewerControlEnabled":true}
Started.
    {"message":"Success","currentPlaylist":null,"nextScheduledSequence":null,"viewerControlMode":null,"viewerControlEnabled":null}
Clearing remote falcon list of songs.
    {"message":"Queue Empty","currentPlaylist":null,"nextScheduledSequence":null,"viewerControlMode":null,"viewerControlEnabled":null}
Asking remote falcon to disable viewer control.
    {"message":null,"currentPlaylist":null,"nextScheduledSequence":null,"viewerControlMode":null,"viewerControlEnabled":false}



When remotefalcon starts, it enables and then disables again, and then when I start a playlist it doesn't re-enable it.
And yes, I did make sure "Enable and Disable Remote Falcon Website" was checked.
On 2022.16,  it does the same thing, only it does update the songs, just not enable viewer control.

**Comment by Randomaker** [comment]
Maybe its something I am doing wrong, I went the whole way back to 2022.10 and its still not enabling

**Comment by keithsw1111** [comment]
Do you have a schedule playing. From memory RF is only enabled when a schedule is active.

**Comment by Randomaker** [comment]
Yes, you are correct, it's working perfectly now! No bugs or anything that I found.

Thanks so much for adding this and the previous feature, it will improve my show greatly!
