### ISSUE TITLE
DMX issues

### ISSUE THREAD

**Issue by lenhard2007** [smeighan/xLights#3379]
https://youtu.be/jkGi5EauY9M
Since 2022.13 DMX has had issues with displaying what  really happens. Curve values are overriding slew values and making them completely unrealistic to sequence. Second they do not move the same way when you ask it to repeat the sequence, very erratic.

I have to go back to 2022.12 to sequence DMX heads.
Im on Windows 11 
computer is Alienware 17 with latest hardware.

Please fix

Thanks

**Comment by danielrenwick** [comment]
I raised this same issue as well (#3314). I wasn't really able to explain it so it just put it down to perhaps something I stuffed up but hopefully your video helps now. There is definitely an issue when .13 came out with change to frame timestamp for the pan/tilt.

**Comment by AzGilrock** [comment]
Fixed for next release
