### ISSUE TITLE
Request: add links to the Help menu to find useful info

### ISSUE THREAD

**Issue by SteveGase** [smeighan/xLights#338]
Suggest the Help pull-down menu be augmented...

Help / IssueTracker ==> open browser to https://github.com/smeighan/xLights/issues
Help / Release Notes ==> open notepad to  (installDir)/README.txt
Help / Forum ==> open browser to http://nutcracker123.com/forum/
Help / Download Area ==> open browser to  http://nutcracker123.com/nutcracker/releases/

**Comment by keithsw1111** [comment]
Implemented.
