### ISSUE TITLE
Twinkle Effect Causing Slow Render & Different Results (PC vs MAC)

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#3381]
**Describe the bug**
This was duplicated based on a vendor sequence that we were helping a user with in the Zoom room.  The attached is just the 2 effects, the vendor's layout, and a video showing the different results on a M1 Mac with default and per preview render buffer.  The vendors vision is Per Preview.

The PC users are able to get it to render properly but it is very laggy.
**Versions (please complete the following information):**
 - OS: M1 MacBook Pro 2022.15
 - PC: 2022.15 & 2022.15 nightly

https://youtu.be/0BcC_1qifSA

[Bug.zip](https://github.com/smeighan/xLights/files/9390271/Bug.zip)

**Comment by derwin12** [comment]
Vendor video: First 0-20secs. The bug just flashes solid colors
https://youtu.be/wmyNeEpF90g?list=TLGG2gAP6k_1lxQyMjA4MjAyMg
Vendor:
![image](https://user-images.githubusercontent.com/4643499/185819095-ff3b7051-94db-4be1-9f4d-d86e18913364.png)
Mac:
![image](https://user-images.githubusercontent.com/4643499/185819132-19a28fae-a8a6-4e66-8a9d-23c10a2ef14c.png)

**Comment by keithsw1111** [comment]
I put in a change that may address this. It renders slowly but not too slowly.

**Comment by AzGilrock** [comment]
Well that's going to depend on what setting you have the Whole House model set to.  Default means its going to go by what you set as the default in the model settings.  Also I assume you are using the "New Method"?  You could switch to the older method which is faster just not as nice of a random distribution.

**Comment by derwin12** [comment]
So in our test case Default would point to Minimal Grid & 400 Size. Per Preview on the sequence would use some other grid size perhaps? Can we determine that value - is it displayed anywhere?
(3d display)
Keith's update cut the render time almost in half. We did try the old render method as well. It didnt fix the mac bug(?) and we pay attention to any noticeable change in render times.

**Comment by MrPaulAR** [comment]
I'll test the mac build once it's pushed to the app store.

**Comment by AzGilrock** [comment]
Can't remember if there's another way but if you drop a Morph effect on a model with the Effect Assist window it should show you the model buffer size.

Only thing I can find that Keith did was initialize a rotation quarternion.  I'm surprised if that was able to reduce the render time.  That variable was most likely intended to be calculated before its ever used and that's why it wouldn't have an initial value.  I hate these band aid fixes what really needed to happen is find out why its used before calculated.

**Comment by dkulp** [comment]
On the mac, the uninitialized variable was resulting in a 1x1 render buffer (which renders very quickly, but doesn't work very well for twinkle).  It's possible that on windows, the uninitialized variable was resulting in a much much larger render buffer that rendered slower.

**Comment by MrPaulAR** [comment]
Just tested this on 2022.16 on the M1 Mac and all seems well.

**Comment by keithsw1111** [comment]
> On the mac, the uninitialized variable was resulting in a 1x1 render buffer (which renders very quickly, but doesn't work very well for twinkle). It's possible that on windows, the uninitialized variable was resulting in a much much larger render buffer that rendered slower.

It was resulting in a buffer almost 2000x2000.

**Comment by keithsw1111** [comment]
> Can't remember if there's another way but if you drop a Morph effect on a model with the Effect Assist window it should show you the model buffer size.
> 
> Only thing I can find that Keith did was initialize a rotation quarternion. I'm surprised if that was able to reduce the render time. That variable was most likely intended to be calculated before its ever used and that's why it wouldn't have an initial value. I hate these band aid fixes what really needed to happen is find out why its used before calculated.

Thats fair. The uninitialised value was causing a large buffer which is why render time was impacted.

**Comment by AzGilrock** [comment]
Probably better to initialize it.  If that fixed it awesome.

**Comment by AzGilrock** [comment]
I’m in the middle of trying to get AC guys out here to fix a drain problem on a fairly new unit so I’m a little mad today.  They’ve been here 4 times and the bozos can’t fix it
