### ISSUE TITLE
Cannot load xScheduler in Linux

### ISSUE THREAD

**Issue by coolricky8** [smeighan/xLights#3383]
**Describe the bug**
I am trying to load xSchedule in Linux. I am running on Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-46-generic x86_64)

**To Reproduce**
I run the following in the terminal:
~/Desktop$ /opt/xLights-2022.15-x86_64.AppImage -x
./src/common/stdpbase.cpp(59): assert ""traits"" failed in Get(): create wxApp before calling this
./src/common/stdpbase.cpp(59): assert ""traits"" failed in Get(): create wxApp before calling this
Gtk-Message: 11:45:35.237: Failed to load module "xapp-gtk3-module"
execvp(/tmp/.mount_xLightCHyuSp/usr/bin/xSMSDaemon) failed with error 2!

Note if I tried to launch xLights in terminal, I get the also some error messages but the application loads up:
~/Desktop$ /opt/xLights-2022.15-x86_64.AppImage
./src/common/stdpbase.cpp(59): assert ""traits"" failed in Get(): create wxApp before calling this
./src/common/stdpbase.cpp(59): assert ""traits"" failed in Get(): create wxApp before calling this
Gtk-Message: 11:47:31.980: Failed to load module "xapp-gtk3-module"

(AppRun.wrapped:13108): Gtk-WARNING **: 11:47:36.300: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:13108): Gtk-CRITICAL **: 11:47:36.300: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:13108): Gtk-CRITICAL **: 11:47:36.300: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(AppRun.wrapped:13108): Gtk-WARNING **: 11:47:36.300: gtk_widget_size_allocate(): attempt to allocate widget with width 13 and height -7

(AppRun.wrapped:13108): Gtk-CRITICAL **: 11:47:36.300: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

**Expected behavior**
No errors, xScheduler opens.

**Versions (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-46-generic x86_64)
 - xLights version: 2022-15 ( I also tried 2022-14 and it's the same).

**Comment by xxv** [comment]
It looks like the command line arguments aren't being processed correctly. In the error log above it says:

```
execvp(/tmp/.mount_xLightCHyuSp/usr/bin/xSMSDaemon) failed with error 2!
```

which looks like it's trying to load up the xSMSDaemon instead of the scheduler.

**Comment by tbnobody** [comment]
Can confirm this issue. Still occurs in 2023.07

**Comment by Martin-HTQ** [comment]
Still occurs in 2023.07, quite confusing

**Comment by merryoncherry** [comment]
I believe this is a problem with the command line argument handling for AppImage / xSchedule.   The "-x" is triggering it to try to load SMS daemon for some reason.  I will try to get to the bottom of it, but in the meantime please consider the workaround of using "--xschedule" instad of "-x".  I tried it on 2023.07, the "-x" gives the error you are reporting but "--xschedule" is fine, it seems like it would probably affect a lot of versions similarly.

**Comment by merryoncherry** [comment]
^^^ Never mind, that doesn't always work.  But there is an easy fix.

**Comment by computergeek1507** [comment]
I think the short option should only be one character not two. Check sequences "cs" probably causes xcapture to not work either

**Comment by merryoncherry** [comment]
There's a long option - that silently doesn't do anything.
The issue is that there's a strncmp on line 511 of xLightsApp.cpp with a "2" that should be a "3"... should I submit a patch or can you just fix it?

**Comment by computergeek1507** [comment]
Sorry to steal your credit, I fixed it. Thought it was easier for me to do it then you make a branch and pull request for one character. We should add compares for the full names as well.

**Comment by merryoncherry** [comment]
Thanks!
