### ISSUE TITLE
Set the "Default" Camera on a Per Group Basis for Per Preview Render Style

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#3384]
**Is your feature request related to a problem? Please describe.**
Some of my groups are exactly perpendicular from the street.  When I import I make it a habit to go through and any effects that are per preview on these groups I go through and change to something other than "2D".  For each of the groups I do this on I never want 2D to be used.

**Describe the solution you'd like**
I'm asking for an option that will allow a default viewpoint to be set at the group level.  If this is set the following actions will happen.
* When importing it will parse all effects that are "Per Preview > 2d" and change to "Per Preview > CAMERA_NAME".
* When applying an effect to a group and changing the render style to Per Preview from any other render style it will default to the CAMERA_NAME defined in the group.
* 
**Describe alternatives you've considered**
Bulk changes work fine for this.  I just need to identify an effect that's got per preview.  Select that effect.  Select all effects on the group.  Then change it.  Anything that isn't "Per Preview" isn't impacted even though those effects are selected.

**Comment by tgrinnall** [comment]
this would be and great enhancement for people that have garages at a 90 degree angle from there house.

**Comment by koolsb** [comment]
+1. I have this same issue, many 90 degree angles in my home and it is a pain to go through and adjust off the 2d camera angle all the time.

**Comment by merryoncherry** [comment]
I don't know if this is planned.  In the meantime, I have devised a delightfully convoluted workaround.  (You're welcome.)
https://merryoncherry.org/2022/11/12/utility-for-getting-more-out-of-3d-and-handling-multiple-holidays-on-one-layout/
