### ISSUE TITLE
Nightly Build - the layout icons are gone..

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3388]
Perhaps the wxwidget update but I am guessing..
![image](https://user-images.githubusercontent.com/4643499/187006766-8c0fdede-290e-415b-82f9-d46978af8507.png)

**Comment by computergeek1507** [comment]
fixed

**Comment by derwin12** [comment]
Nightly build (after the fix) still has the missing icons. Keith wonders if your build/pull was correct. (He is in zoom atm)

**Comment by keithsw1111** [comment]
My release build also has the issue ... debug does not ... not sure why yet.
