### ISSUE TITLE
Request: Add a Banner-Creation tool

### ISSUE THREAD

**Issue by SteveGase** [smeighan/xLights#339]
The nutcracker forum has a banner creation tool...  specify the number of channels, and it customizes it for your channel count...   in forums, you can refer to the generated banner by a URL.

Suggest similar be done for nutcracker...

[i m g ]http :// sig.falconchristmas.com/90000[/i m g]

It might be even better if XLv4 calculated your channel count and gave you the prepared url:

Pull-down menu "Info" and the option  "Info / Banner"  creates the url

http :// sig.nutcracker123.com/90000  and opens a browser to display it!

**Comment by keithsw1111** [comment]
The nutcracker 123 banner tool does not seem to be working making this change moot.
