### ISSUE TITLE
Nightly Build - render hung on what appears to be the Shape Effect

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3393]
I post this because I seen that there was some code changes recently. (Not being used in this sequence)
![image](https://user-images.githubusercontent.com/4643499/187087792-644fdf02-e1d1-4144-9e0a-602bac2689c3.png)

Hung for 60s plus .. waiting to see if it does indeed finish.

**Comment by keithsw1111** [comment]
Not much we can do without a copy of the sequence. Email it to me if necessary.

**Comment by derwin12** [comment]
Not much help .. it stuck for 5mins. Couldn't ESC stop it. Had to hard stop it. Restarted xlights and it rendered just fine. I will see if I can duplicate it.

**Comment by derwin12** [comment]
Rendered fine numerous times afterwards. I will keep an eye out for it.

**Comment by derwin12** [comment]
Just after I closed this .. it hung again. I will send you the sequence via email. It is the group Mini Tree Left (or Right) the shape effects.
![image](https://user-images.githubusercontent.com/4643499/187089252-fd0638fc-ea5b-49cb-8eb7-3607e2ebe559.png)

**Comment by derwin12** [comment]
Repeatedly crashing now .. Using nightly build. I can resend the packaged sequence to Keith unless you have some debugging ideas for me.
I start xlights, open recent sequence, open the britney sequence, hit render. It gets abtt 90% then throws up the xlights has stopped and closes. No xlights debug dump.
Here is the view log from the next xlights open.
[Crashes.log](https://github.com/smeighan/xLights/files/9448481/Crashes.log)

**Comment by derwin12** [comment]
Narrowed down to one model group. Attached for others to give a try. Takes about 4 or 5 renders on my 16gb machine.
Open sequence, render, render, render .. etc then above hard crash.
[BUGMy Only Wish - Britney Spears8.zip](https://github.com/smeighan/xLights/files/9453392/BUGMy.Only.Wish.-.Britney.Spears8.zip)

**Comment by derwin12** [comment]
Narrowed down to just 1 layer and the shape effect. Note when bulk edited to "Default" the problem is gone.
[BUG - Shapes - 7.zip](https://github.com/smeighan/xLights/files/9483167/BUG.-.Shapes.-.7.zip)

**Comment by dkulp** [comment]
I've been hitting the render all button with this in a memory-debug build.  I've must of hit it 100 times now and I haven't seen a hang/crash yet and no errors.    That's on a Mac though.

**Comment by derwin12** [comment]
Must be .. still crashing for me after 1 or 2. Keith had it crash - not as often but hopefully he can catch this one. 
![image](https://user-images.githubusercontent.com/4643499/188319296-2f92f723-e1e7-47a1-a8ca-ac180d6620d6.png)

**Comment by dkulp** [comment]
I think I figured this out now.   It's likely not just the ShapeEffect as I think other effects that use a per model render style may also be affected.   Any effects that use the non-const methods on the SettingsMap might cause a mutation, which with per-model may be run on parallel threads and the mutations might corrupt things.   I'm going to make the SettingsMaps "const" going into the effect rendering which should fix this.

**Comment by derwin12** [comment]
Fixed! with the latest nightly build, I was able to run an xldo render all many many many times without a crash...
Feel free to  close if you guys are happy with the change.
