### ISSUE TITLE
Export to xMapHint Doesn't Escape Parantheses

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#3394]
**Describe the bug**
When using the "save as" dialog to save a xmaphint file some regex patters are not being escaped.  I've observed the **(** and **)** but may be others.

What is exported.
`    <Map ToRegex="^GRP Spiders (Legs)$" FromModel="Boscoyo BW Spiders Legs" ApplyTo="B" />
`
What is expected
`    <Map ToRegex="^GRP Spiders \(Legs\)$" FromModel="Boscoyo BW Spiders Legs" ApplyTo="B" />
`

**Versions (please complete the following information):**
 - OS: Win 11
 - xLights version: 2022.16

**Comment by computergeek1507** [comment]
Parentheses are not excaped in XML

**Comment by MrPaulAR** [comment]
If I don't escape them the regex fails though.
