### ISSUE TITLE
Warp effect does not render correctly in Per Model styles 

### ISSUE THREAD

**Issue by whirlywhopter** [smeighan/xLights#3395]
**Describe the bug**
Previously resolved bug #3286 or something similar seems to have returned.

The warp effect does not appear to render correctly when using "Per Model" render styles.

To Reproduce
(and/or link to a short video showing the problem with audio track describing what you are doing)

- Open or create a sequence and select a group which contains multiple models
- Create at least 2 layers and add an effect to the bottom layer and then the warp effect above it.
- Under "Layer Settings" for the render effect, select one of the "Per Model" options such as "Per Model default" or "Per Model Per Preview". It does not seem to matter what the render style is for the underlying effect.

The rendered effect on the props will not include the Warp effect. If you select one of the per-group render styles such as Default or Per Preview for the Warp effect, it will render as expected across all models in the group but if any of the per-model styles are selected, it does not appear that the Warp effect is rendered at all.

Expected behavior
When a per-model render style is selected, the Warp effect would render per model.

Screenshots

Versions (please complete the following information):

OS: MacOS Monterey 12.5.1
xLights version: 2022.16.1
**Additional context**

**Comment by dkulp** [comment]
You'll need to attache a small sequence.  It seems to be working properly for me.   A bars effect on a bottom layer and a circular swirl warp effect above it both set to "per-model default" is rendering exactly as I'd expect.  
<img width="461" alt="Screen Shot 2022-08-30 at 2 12 22 PM" src="https://user-images.githubusercontent.com/91569/187512250-bc78b0d9-ecdf-4cfe-b467-cb9ddcb3de77.png">

**Comment by whirlywhopter** [comment]
Well, when I went back to test the same simple sequence I created to document the issue, I do not seem to be able to duplicate the behavior I was seeing earlier.  I have also  created some new effects in existing sequences and tested a few old ones that use this type of effect and rendering and I do not seem to be able to replicate the behavior I was seeing previously across any of these test scenarios.  

I am wondering if I had some sort of temporary issue that was creating this problem during my previous testing that is no longer occurring now.   Please feel free to close this issue since it does not seem to be possible to replicate the issue in the same tests or other similar scenarios.
