### ISSUE TITLE
Ripple effect with X/Y value curves not rendering correctly

### ISSUE THREAD

**Issue by whirlywhopter** [smeighan/xLights#3396]
**Describe the bug**
In earlier xLights versions, the ripple effect would render as a circular effect even when value curves were applied to move the effect across a prop.  In recent xLights versions, the use of value curves no longer appears to shift the entire effect resulting in very different rendering behavior than in the earlier xLights versions.

This issue was discovered recently when working with a few sequences from last year so I am not sure at what version this xLights behavior changed.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

1.  Select a prop or group such as a matrix where the ripple effect can be seen clearly.
2.  Add the ripple effect to the prop and then select a value curve for "X" or "Y" Center such as a ramp. 
3.  As a control, create a "Shockwave" effect and apply the same "X" or "Y" value curve to use as a comparison.

**Expected behavior**
In previous versions, the ripple effect would render as an expanding ring that moved across the prop/buffer retaining its shape.  The Shockwave effect still renders with this behavior but in recent versions, the ripple effect now expands in a strange fashion, apparently turning into an oval or elongating the shape instead of translating across the prop or buffer.

**Screenshots**
Please let me know if you need additional information or examples.

**Versions (please complete the following information):**
 - OS: MacOS 12.5.1
 - xLights version: 2022.16.1

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by whirlywhopter** [comment]
I have attached a sample file that replicates the change in behavior I am seeing.   It has the same matrix configuration that I use in my full show layout and is exhibiting the same behavior with these matrices as I see in my full layout.  The attached sequence contains 3 effects applied to this prop.  The first is a ripple effect with a linear 0-100 value curve applied to the "Y Center".   Previous versions would render this effect in a similar way to the second effect which is a shockwave effect with the same type of value curve applied to the "Y Center" value.  The 3rd effect is a direct copy of the sliding ripple effect from the YouTube video below to hopefully show the difference in how this effect is being rendered in the current xLights versions compared to the earlier versions.

In my sequences from last year, the ripple effect would translate across a prop and retain its overall proportions in the same way that the shockwave effect does in the attached sequence.  When I render these sequences in the current xLights versions, the ripple effect is getting distorted instead of moving across the prop.

This [YouTube video link](https://youtu.be/leZO9o3_t_Q?t=152) shows an example of how these effects were being rendered in earlier xLights versions.  The diagonally sliding ripple effect is the one included in the sample file to illustrate the difference

Packaged sequence:
[Ripple Bug.zip](https://github.com/smeighan/xLights/files/9508099/Ripple.Bug.zip)

**Comment by AzGilrock** [comment]
I think what confused me is when I read the original post the first sentence made it sound like Shockwave was the problem.  I think you meant to type Ripple there.

**Comment by whirlywhopter** [comment]
Apologies!  I did not catch that in the original report.  The issue is with the ripple effect, not shockwave.  I will go back and edit it to correct that.

**Comment by keithsw1111** [comment]
But the shockwave effect has no value curve on X whereas the ripple does. If I take it off I think it looks exactly like the shockwave apart from blowing up a lot faster.
I am not convinced there is an issue here.

**Comment by whirlywhopter** [comment]
Is it possible that there was a change to the rendering behavior of the ripple effect itself or the buffer that would affect how it responds to value curves or how these curves are applied?  I wish I knew exactly what version introduced this but I had not opened these sequences until recently to get them ready for the 2022 show so I am not sure specifically when the behavior might have changed.

For a direct comparison of the difference I am trying to describe, the 3rd effect in the sample sequence I provided is an exact copy of the ripple effect from the sequence in the [YouTube video](https://youtu.be/leZO9o3_t_Q?t=152) linked above (the blue 'Ripple' with value curves on both x and y center).  The effect is used on several of the vertical matrix pixel poles where the ripple moves diagonally down and across the prop. 

In the 2021-era versions which were used to render the show in the video, the entire ripple effect was moved across the prop, expanding smoothly and retaining its proportions as it did so.  In the current versions, it seems that the overall effect is now being stretched or distorted more than moving across the prop.

When going back to copy the effect settings to create the sample file, I used an old show folder that I had not used with xLights since last year.  When I set this as my show directory and opened last year's sequence file from that location, this effect initially appeared in the preview like it does in the video above until the current xLights version re-rendered these ripple effects.  As soon as this happened, the appearance of these effects in the preview changed to the new behavior where the effect is stretched more than moved.

**Comment by keithsw1111** [comment]
That does not really help. Unless I have something I can specifically see the problem in I am going to need to close this. When I look at the behaviour of the effect it looks exactly as I would expect it to with those settings. Unless you can give me a show folder and sequence where it looks one way and a show folder and identical sequence where it looks another there is just nothing we can do.
99% likely is the underlying buffer is different so without that show folder we just wont know.

**Comment by whirlywhopter** [comment]
I am happy to try to provide additional information if I can.  Since the issue is the difference between the behavior in different xLights versions and it does not seem to be possible to reproduce the previous effect behavior in the current xLights versions, is there a location where I could find a mid-2021 version of xLights for Mac that I could use to try to generate a direct comparison with the same effect settings?
 
If so, what files should I collect  and send from the tests with the earlier version and with the current version?

**Comment by derwin12** [comment]
You can find some older mac versions here...
https://dankulp.com/xlights/archive/

**Comment by whirlywhopter** [comment]
Hi Dan, thanks for the link to the earlier versions and pointing out the changes to the ripple effect that were made late last year.  The description and timing of these sound like they might explain the difference in the rendering that I am seeing with these sequences from last year to the current versions. 

I am tied up until early next week but will test as soon as possible and provide an update to confirm.  If the current behavior is what is now expected for the ripple effect, I would love to see an enhancement to add a "Ripple Size" value that could allow effects like the ones I was able to create in the versions last year.

**Comment by whirlywhopter** [comment]
Sorry for the terribly long delay, after testing several versions, I have been able to verify that this behavior did change with the updates mentioned by Dan and what I am seeing is the difference between the new and older behaviors.
