### ISSUE TITLE
Nightly build .. missing icon images for shape effect perhaps others?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3397]
The layout icons are back .. but still missing some icons.
These are all shape effects.. (not off effects)

![image](https://user-images.githubusercontent.com/4643499/187293963-62d5cec8-d806-45f0-9840-964e121369a3.png)

![image](https://user-images.githubusercontent.com/4643499/187294133-ed6bcd08-19af-46ba-b3c8-e545ed5fe969.png)

**Comment by derwin12** [comment]
Some more .. I will keep and eye out on the nightlies to see if it is fixed.
![image](https://user-images.githubusercontent.com/4643499/187558068-71ad990a-4099-474b-8b88-23e37de32293.png)

**Comment by dkulp** [comment]
I've logged a bug with wxWidgets.... There seems to be an optimizer bug with Visual Studio 2022 (everything is OK with every other compiler).  They are able to reproduce it with a very small sample program and are investigating various work arounds.

**Comment by dkulp** [comment]
The wxwidgets folks changed the code enough so that whatever bug in the VS optimizer is causing this isn't hit anymore.  I've updated our fork with the latest changes and updated the build files.  Hopefully the next nightly build fixes this.

**Comment by derwin12** [comment]
Latest nightly build is working just fine...
