### ISSUE TITLE
Request: add an "Info / Statistics" page that reports interesting statistics...

### ISSUE THREAD

**Issue by SteveGase** [smeighan/xLights#340]
Under a new "Info" pull-down menu, create a page the reports interesting statistics:

First Channel Number:  #####    (first channel number specified in any defined model)
Last Channel Number:  #####    (last channel number specified in any defined model)
Total Channel Count:  #####    (the total number of channels specified in the models....  overlap/duplicates are not counted twice, gaps are not counted, ...)
Total Light Count:    ######   (number of RGB pixels defined, PLUS the number of lights defined in the single-color models)

**Comment by stevegiron** [comment]
Coming soon

**Comment by keithsw1111** [comment]
I think I can add this to the models export.
