### ISSUE TITLE
Identical fan effects different sizes when applied to similar groups

### ISSUE THREAD

**Issue by tmeyermn** [smeighan/xLights#3405]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I have 16 Pixel poles. 8 of them are in a group called All Pixel Poles Left the other 8 are in a group called All Pixel Poles Right.  When I put a fan effect on the left group and copy/paste to the right group the effect on the right is much smaller.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Place fan effect on left group with a radius2 of 100.
2. Copy and paste the fan effect from the left group to the right group.
3. See error

**Expected behavior**
The groups contain the same models and are the same size the effects should be the same size.

**Screenshots**
![image](https://user-images.githubusercontent.com/43391347/188065169-5834a0a4-4618-4884-bed9-80b0232da0d6.png)
![image](https://user-images.githubusercontent.com/43391347/188065237-4c4a0ebc-5e8e-4018-bd57-65c34c975864.png)
![image](https://user-images.githubusercontent.com/43391347/188065319-c1a8fc54-df19-4146-8e48-ef281929b13f.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - 2022.16

**Additional context**

**Attachments**
This is a link to a onedrive folder that contains the packaged sequences and also an mp4 of the issue.
https://1drv.ms/u/s!AijFdLMLE13wj4koBuEULsMOmLdk2w?e=v47ND8

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by tmeyermn** [comment]
https://user-images.githubusercontent.com/43391347/188067711-0a07458b-7fb3-4fef-af60-ae55f96cccc9.mp4

[gridsize.zip](https://github.com/smeighan/xLights/files/9475174/gridsize.zip)

**Comment by derwin12** [comment]
Cant say I know why it affects it but one group is outside the bounding box and the other is inside.
Even though both are set to Default render, the one is actually showing the results of a per preview render style.
Place them both inside the 2d bounding box and you get the same results for both groups.
Crank up the radius 2 and it covers the poles equally.
![image](https://user-images.githubusercontent.com/4643499/188160849-59afa0f9-007f-40ce-b913-23db74a22dda.png)

**Comment by tmeyermn** [comment]
This was an example layout just for the bug however I don't think that it's the bounding box but I do know that moving them will affect them as you noticed.  Here is a photo of my actual layout and everything inside is inside the bounding box.  When I move the right group to above the left group then they are the same size. Really weird....
![image](https://user-images.githubusercontent.com/43391347/188165402-f59e8697-4eaf-4255-9983-0294ddd5d85b.png)

**Comment by keithsw1111** [comment]
This is to be expected ..;. default throws a grid over the models and manipulates the size to try to get all pixels in their own cell. This makes it very sensitive to how the models are placed on the screen. This is the buffers the 2 groups generate as drawn:

Group Name	Default Buffer W x H
All Pixel Poles Left	172 x 58
All Pixel Poles Right	347 x 118
