### ISSUE TITLE
2200.16 (or Prior) Now Crashes via Debug

### ISSUE THREAD

**Issue by tgfink11** [smeighan/xLights#3407]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Something happened after downloading and viewing sequence from ListentoOurLights here (https://xlightsseq.com/sequences/holidays-are-coming-always-coca-cola.297/).

Was able to view and run sequence. After shutdown and next day open of Xlights, any model or sequence build/open...causes Debug Report to open and then Xlights closes completely. This happened regardless of show directories I tried.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to ]https://xlightsseq.com/sequences/holidays-are-coming-always-coca-cola.297/ and download installer
2. Open show directory and view as normally done in Xlights (ver 2200.16)
3. After running sequence, close Xlights, restart computer.

**Expected behavior**
Not to fail/quit if possible.

**Screenshots**

**Versions (please complete the following information):**
 - Windows 11
 - xLights version (2200.16, 2200.13, 2200.14)
 - Audacity 3.1.3 and 3.2.0

**Additional context**
Using Revo Unistaller Pro, removed all program/Registry info for Xlights and Audacity.
Clean install Xlights to new directory (no prior Xlights work, Audicity also.
Debug Report message on model or sequence build.

Clean install Xlights only to empty folder, no controller entry, same Debug Report on model or sequence.

At this point I have no Xlights use other than controller setup

Attachment is from one of the failures

[xLights_dbgrpt-25924-20220902T144923.zip](https://github.com/smeighan/xLights/files/9481495/xLights_dbgrpt-25924-20220902T144923.zip)

Thanks.
terry

**Comment by tgfink11** [comment]
SOLVED: Installed prior graphics driver release for AMD  RX 5500 XT and back to working.

**Comment by keithsw1111** [comment]
Sounds like a bug in the new driver.
