### ISSUE TITLE
K16-AB with 16port expansion- add ability to assign 32 port megatree to local ports not 16 local and 16 differential receivers

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#3408]
**Is your feature request related to a problem? Please describe.**
With a Kulp16-AB and a 16 port local expansion board the visualizer will not let you drop a 32 port megatree and use the local ports and skip the differential ports.

**Describe the solution you'd like**
Add the ability in visualizer to span the tree across the 16 onboard ports and the 16 local ports on the expansion board, skipping differential ports.

**Describe alternatives you've considered**
The user can manually edit the output page on FPP, but if they update from xlights it will overwrite the change.

**Additional context**
There are probably other use cases that I am missing.

This was a request from the Zoom room.

**Comment by computergeek1507** [comment]
You can do this with Shadow Models

**Comment by patdelaney** [comment]
Perhaps, but would a shadow model allow you to assign other other props to the differential ports?  It seems to me that it would be beneficial to have a constant user experience.

I'm not sure if there are other boards that would have the same issue, but perhaps with the K16 with expansion checked we offer the option to put the differential ports at the end of the chain.

**Comment by keithsw1111** [comment]
Shadow models are the right solution for this as any other solution opens up a large can of worms.
