### ISSUE TITLE
Add Advatek Long Range MK3 to Controller List

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#3409]
I saw in 2022.16 that Advatek MK3 boards are selectable (Yay) but I noticed the MK3 Long Range models are missing.
Here is the web link for those controllers: https://www.advateklights.com/products/pixel-control/long-range

**Comment by keithsw1111** [comment]
I looked at the link and there is no MK3 long range on that page ... just the MKII which we already support.

**Comment by jholmes09** [comment]
Hi Keith; The T-8S and the associated R2F/R4D devices are the MK3 long range series.
