### ISSUE TITLE
Cancelling xldo render scripts caused xlights to dump an error log

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3410]
Created a script (from Keith) called renderall.cmd

@set xlightsfolder=f:\xlights

:loop
"%xlightsfolder%\xlDo.exe" -v -c "{\"cmd\":\"renderAll\", \"highdef\":\"true\"}"
goto loop

=================

Open a sequence in xlights (nightly build was used).
Using file explorer, double click on the .cmd file
It renders and renders no problem
Hit ctrl C to stop the batch file and say Y to terminate the batch file.
in xlights get a quick blue circle then the debug dump dialog.
Attach is one of those logs.

[not a big deal - just noting the issue if its something easy/obvious]
[xLights_dbgrpt-8696-20220904T204331.zip](https://github.com/smeighan/xLights/files/9485808/xLights_dbgrpt-8696-20220904T204331.zip)

**Comment by merryoncherry** [comment]
I have been getting the same backtrace under a lot of other circumstances and can't make much of it.

**Comment by keithsw1111** [comment]
I think I have pushed a fix that will stop most crashes. There is still a small window in which it could crash but eliminating that would require a wholesale rewrite of third party code and to be honest if i was to do that I would look for an entire replacement as the code we are using is pretty limited in terms of features.
