### ISSUE TITLE
Export to DXF Color Coding

### ISSUE THREAD

**Issue by Fonzi03** [smeighan/xLights#3411]
It would be nice if the DXF export could include color coding which matches that of the visualizer (see second suggestion on this below). All LEDs associated with that output bank should be the corresponding color. The first prop from the controller or receiver should have some sort of identifier stating that it is the beginning of the chain, an end of chain identifier would be nice as well. 

The colors in the visualizer currently repeat (r,g,b,y,f) In order to make the above work properly these would need to be unique. This could be done one of two ways: Hard coded colors but enough to support the max outputs (could include striping), user select-able colors (would probably require a secondary color for striping as well). 

A bigger uplift but nice to have would also be to include 3d in the DXF export. Having this be a secondary request to the above is totally fine. 

This would help with show documentation, and annual setup/confirmation. I personally already do something similar where I screenshot the layout and add colors and text so I can reference.

**Comment by computergeek1507** [comment]
My initial thought is, I could use the model tag color to export the models as different colors

**Comment by computergeek1507** [comment]
the DXF file standard only support 255 predefined color, so any color would have to match the standard colors
http://gohtx.com/acadcolors.php

**Comment by Fonzi03** [comment]
Are you able to apply two color indexes per model? If only a single color is selected the second color auto matches the first. Realistically 255 should be plenty for most people but if you could have two color attributes per then you'd never run into not having enough or shades being hard to discern.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tarikjabiri** [comment]
Hi,

> the DXF file standard only support 255 predefined color, so any color would have to match the standard colors

The DXF is not limited to 255 colors actually you can define true colors directly for entities or the layers using the group code 420

*"32-bit integer value. When used with True Color; a 32-bit integer representing a 24-bit color value. The high-order byte (8 bits) is 0, the low-order byte an unsigned char holding the Blue value (0-255), then the Green value, and the next-to-high order byte is the Red Value. Converting this integer value to hexadecimal yields the following bit mask: 0x00RRGGBB. For example, a true color with Red==200, Green==100 and Blue==50 is 0x00C86432, and in DXF, in decimal, 13132850"*

Regards
