### ISSUE TITLE
Flood Model

### ISSUE THREAD

**Issue by Jaa1i** [smeighan/xLights#3412]
Is it possible to create a new stand alone model for Floods that can be conical in shape (or rectangular?), rather than the current solution of a single large gradient pixel that is flat? This would enable a more accurate render of the show for those who use floods.

<img width="525" alt="Screen Shot 2022-09-07 at 09 09 57" src="https://user-images.githubusercontent.com/50488459/188755792-1fd3f064-55e7-4546-a355-577d28c1c184.png">

**Comment by keithsw1111** [comment]
This already exists under the DMX model group.
