### ISSUE TITLE
Batch Packager? - Using a ui similar to batch render, batch package each sequence

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3419]
This could be used to backup complete sequences .. for moves to new machines, for your archives, to be sure you have a complete sequence, to share, etc.. 

Seems like a good idea?

**Comment by computergeek1507** [comment]
I wrote a lua script to do this in the script runner

**Comment by derwin12** [comment]
Thanks ..I see it now .. Looks like it will work nicely. Going to play with it and perhaps demo on zoom .. lol..

**Comment by derwin12** [comment]
Scott .. can you take a quick look at the script. The UI says the zip is going to F:\2022\Showfolder3D\blahblah.zip
in reality it is being dropped into by f:\xlights   program location folder.
![image](https://user-images.githubusercontent.com/4643499/189706554-1b31c28e-f298-4d74-9348-8e2f6fec22c8.png)

**Comment by computergeek1507** [comment]
I think I see the issue...

**Comment by darylc** [comment]
I came here to report a bug BatchPackageSequence.lua - I'm trying to run it on 2022.17, also tried .16 and someone on zoom tried 2022.13, we are both seeing xlights crashes.  The crash report should have uploaded.

**Comment by derwin12** [comment]
Scott - the change works fine.. DarylC - can I close this ticket? its not crashing for me, do you want to continue this ticket with perhaps additional comments/logs
