### ISSUE TITLE
Request: change the link button image and hover text in the Setup screen

### ISSUE THREAD

**Issue by SteveGase** [smeighan/xLights#342]
The existing image is confusing... 2 links connected, or 2 connected and one in red.
The hover text shows "Link Directories" regardless of state.

![image](https://cloud.githubusercontent.com/assets/2208257/9415858/b96324e2-4807-11e5-855b-98e679568083.png)

I'm still not sure if I'm linked or not.

Here are some suggestions.
When unlinked show a graphic with two links that are not connected... just 2 segments with space between them. 

(just noticed that the Media directory is greyed-out... that was my second suggestion. :) )

the 3rd suggestion is to change the hover text based on state/context.   "Unlink directories"... and "Link directories"

**Comment by AzGilrock** [comment]
I created it like that and I like it as is.  Now that you aren't confused anymore you can help tell anyone else that can't figure it out.  We don't have anything that changes hover text dynamically.
