### ISSUE TITLE
Managed controller is no longer available for WLED if not multicast

### ISSUE THREAD

**Issue by edwinhartman** [smeighan/xLights#3420]
As of version 2022.17, the "managed" option is only available for a multicast WLED setup, if not multicast, the controller is "unmanaged". Previously the managed option was available for both multicast and not multicast.

Thanks.

<img width="674" alt="Screen Shot 2022-09-12 at 12 20 26 PM" src="https://user-images.githubusercontent.com/38260044/189716916-56bff4e9-7c0e-4095-b844-d8f8c367a052.png">

**Comment by computergeek1507** [comment]
Do you have two controllers setup with the same IP address?

**Comment by edwinhartman** [comment]
Dang, y’all are smart! I switched to a different show folder and didn’t realize I had not updated one of the controller’s IP address, so yes, there was a duplicate! Updating the other controller to the correct IP address switched both the controllers to managed! Thank you so much!! Sorry for the oversight on my end!
