### ISSUE TITLE
Animated GIFs not recognized 

### ISSUE THREAD

**Issue by Darzoom** [smeighan/xLights#3421]
Effect problems
    ERR: Picture effect '/Users/johndoe/Documents/XL Shows/Christmas/Images/turkey-walk.gif' contains no images. Image invalid. Model 'Matrix', Start 0:32.750
    ERR: Picture effect '/Users/johndoe/Documents/XL Shows/Christmas/Images/turkey-walk.gif' contains no images. Image invalid. Model 'Matrix', Start 1:25.275
    ERR: Picture effect '/Users/johndoe/Documents/XL Shows/Christmas/Images/turkey-walk.gif' contains no images. Image invalid. Model 'Matrix', Start 2:06.825

![taxes-happy](https://user-images.githubusercontent.com/81765092/189752305-34cde1fc-d82c-4c86-8f3a-8b18e34e7733.gif)

Mac running 22.16.1

Similar issues for Windows machines.

**Comment by darylc** [comment]
Usually this is caused by an incompatible animated GIF, try another file.

**Comment by Darzoom** [comment]
Worked as a movie.

**Comment by keithsw1111** [comment]
The wxwidgets gif code has issues with some gifs. Loading and saving them with a gif editor is normally the fix. The video effect as you found does work but you lose some options.

Sent from my iPhone

On 13 Sep 2022, at 7:31 am, Darzoom ***@***.***> wrote:

﻿

Worked as a movie.

**Comment by Darzoom** [comment]
Thanks Keith.  I’ll give the edit a go.

**Comment by dkulp** [comment]
I've logged an issue at wxWidgets:
https://github.com/wxWidgets/wxWidgets/issues/22799

probably should have done that years ago.

**Comment by Darzoom** [comment]
I’m having an issue since .4 on a Mac.  When opening a sequence I had previously created, the models are not recognized and the timing tracks tick marks are gone.  




David Robinson
404-735-1377

**Comment by darylc** [comment]
@Darzoom Maybe open a new github issue if you have a new problem, this issue was closed a long time ago

**Comment by Darzoom** [comment]
Opened a new issue as requested.
