### ISSUE TITLE
export of groups to .bin not possible

### ISSUE THREAD

**Issue by gsta75** [smeighan/xLights#3424]
Hi

I am trying to export a sequence to SD Card (Minleon .bin file) but export of groups is greyed out.
No matter is simplest groups with 1 or 2 elements are created, export via right mouse button on sequence timeline is not possible.

How can it be done?
Thanks for your help

**Comment by keithsw1111** [comment]
It can’t be done. Export is from models only. If your group contains contiguous channels then use a shadow model and export that

Sent from my iPhone

On 13 Sep 2022, at 6:43 am, gsta75 ***@***.***> wrote:

﻿

Hi

I am trying to export a sequence to SD Card (Minleon .bin file) but export of groups is greyed out.
No matter is simplest groups with 1 or 2 elements are created, export via right mouse button on sequence timeline is not possible.

How can it be done?
Thanks for your help

**Comment by gsta75** [comment]
Understood. Thanks. Yes I have continuous channels (a couple of rings and lines). How can I make a shadow model? Could you point me where to get more info? The manual doesn't show it. THANKS for your help!!

**Comment by AzGilrock** [comment]
Just create a simple model like a Single Line Model and make it big enough to cover all the channels.  There is no rule saying you can't have multiple models that overlay the same channel range.  "Shadow Model" is just a name made up for the technique.  I always called them "Proxy Models".

**Comment by gsta75** [comment]
Thanks! That's a clever trick! Perfect.

**Comment by gsta75** [comment]
I did exactly that but now I see that the export possibilities are limited. Minleon (.bin) is not available. Would you know why and how to overcome that? https://freeimage.host/i/PS37Qp

**Comment by keithsw1111** [comment]
Use a matrix rather than single line.

Sent from my iPhone

On 13 Sep 2022, at 10:39 am, gsta75 ***@***.***> wrote:

﻿

I did exactly that but now I see that the export possibilities are limited. Minleon (.bin) is not available. Would you know why and how to overcome that? https://freeimage.host/i/PS37Qp

**Comment by gsta75** [comment]
Works. Thank you!!

**Comment by AzGilrock** [comment]
Doesn't make sense for Matrix to have different export options

**Comment by keithsw1111** [comment]
From memory when I wrote the minleon export it was generally for a collection of ports and the matrix and tree models made sense. I don’t remember if there was a reason why single line would not have worked.

Sent from my iPhone

On 14 Sep 2022, at 11:07 am, Gil Jones ***@***.***> wrote:

﻿

Doesn't make sense for Matrix to have different export options
