### ISSUE TITLE
FR:  Ability to use variables to insert meta-data from songs.

### ISSUE THREAD

**Issue by RiFF4711** [smeighan/xLights#3426]
First, thank you for everything you all do.  This is a feature request that could either be implemented in Xlights, FPP, or both to varying degrees.

Ultimately, many people have Tune To signs, either based on a P5 Matrix or pixel matrix, and use this to convey information about their show such as FM Station, Turn off headlights, etc.  As part of this, many people mention the name of the song currently playing.  It would be nice to be able to create a standardized Tune To sequence that could be copied to every sequence prior to rendering that could auto-fill some information about the show.  

My primary use-case would be something like "Now Playing - %SongName% by %Artist%", where the data is parsed from the information xlights contains in the Sequence Settings -> Meta Data area.   However, if this is something to be implemented, it would also be beneficial to have a global settings area in xLights where you can fill out information about your show.  This could expand the possibilities further to add variables such as ShowName, ShowURL, Hours, Dates, Station, etc, which would allow for a much faster batch re-render each year as things change or update.

As several of you devs are on both the xLights and FPP dev teams, I'll also include that it would be nice to have a similar feature in FPP using Overlay Models.  In that instance, the ability to use variables such as NextSong and NextArtist would be valuable.  

Thank you all for your time, both for your consideration of this request, and simply the large amount of time you all dedicate to this community.

**Comment by computergeek1507** [comment]
You can already do this.

https://manual.xlights.org/xlights/effects/off/text#text-replace

**Comment by computergeek1507** [comment]
The text effect can load data from a file as well, so you can put show info in a text file and the text effect will read it in.

**Comment by RiFF4711** [comment]
Thank you!  I don’t know how I missed that, and even reached out to Dan about it as an FPP feature.  I’ll mark this as closed.
