### ISSUE TITLE
Lua script RenderExportModel errors on Run

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3427]
I just click the script and press Run..

![image](https://user-images.githubusercontent.com/4643499/190530291-f02aa60d-582a-45db-822c-05ea62093e35.png)

**Comment by computergeek1507** [comment]
I must have forgotten to update it when I changed the lua api

**Comment by derwin12** [comment]
That works Scott! I will see if I can expand this into a BatchRenderExportModel.lua and perhaps a BatchCheckSequence.lua :-)
