### ISSUE TITLE
_.xbkp is not usable - autosave from a sequence prior to saving it to a filename cant be loaded back as .xbkp

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3430]
I created an animation, dropped a couple effects in the sequence. Waited a couple mins to get the __.xbkp file (attached)
Closed the sequence, not saving.
Open sequence, changing to the *.xbkp filter.
No effects are found/displayed but if you view the file they are in there. Something amiss?

renamed to .txt to upload here.
[__.xbkp.txt](https://github.com/smeighan/xLights/files/9586721/__.xbkp.txt)

It might be just the loading of  the .xbkp that is the issue, as it seems I CAN load it if I rename the .xbkp to _.xsq

**Comment by keithsw1111** [comment]
Without the layout that goes with this file there is not much to test.

**Comment by derwin12** [comment]
Oops ... should be easy to duplicate but here is a package logs to grab my xml files. (ignore the log parts)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/9590739/xLightsProblem.zip)
