### ISSUE TITLE
On effect enhancement

### ISSUE THREAD

**Issue by ebuechner** [smeighan/xLights#3432]
**Is your feature request related to a problem? Please describe.
*more functionality for the on effect*

A clear and concise description of what the problem is. 
Be able to use sine, music, Sawtooth, parabotic up and down, and other functions of value curve with the on effect allowing it to ramp up and down using less effects on a timeline.

**Describe the solution you'd like**
Add a checkbox and an a single intensity slider with value curves. The checkbox would switch the function over to the single slider so that existing on effects in sequences would not be broken. The slider would cover the full-time duration across the effect but it would have all the functions of value curves. 

**Describe alternatives you've considered**

**Additional context**

**Comment by computergeek1507** [comment]
VU Meter already does this.
![image](https://user-images.githubusercontent.com/2293065/190922412-208e54d8-ddef-46f5-b0c1-39e47fe00a9e.png)

**Comment by ebuechner** [comment]
Music effect was just one of the examples available in the value curve. This was just an idea that was expanding upon something that Gil had mentioned a while ago allowing for all the functionality that the value curve brings without breaking the on effect going forward.

**Comment by keithsw1111** [comment]
Why can't you just use the value curve on the brightness or use the VU meter. This does not seem anything that cannot already be done easily with a single effect.

**Comment by keithsw1111** [comment]
Closed due to no response. If you have a response please reopen it.
