### ISSUE TITLE
Tip of the day shows over show selection on fresh install on linux

### ISSUE THREAD

**Issue by freman** [smeighan/xLights#3433]
**Describe the bug**
When launching a fresh install of xLights on a fresh install of Linux (in this instance in a docker container - dorowu/ubuntu-desktop-lxde-vnc:focal) the show selector dialog shows up, then the top of the day window shows up.

You cannot do anything in the tip of the day window while the show selector dialog is visible, you have to figure that out, find the show selector dialog, and select a show before you can go back and close the tip of the day.

**To Reproduce**
Video demonstrating behaviour (clicks are highlighted): https://youtu.be/wCJlD6dCJCE
Steps to reproduce the behavior (on linux with docker installed):
1. docker run --rm -ti   -v /dev/shm:/dev/shm -p 6080:80 dorowu/ubuntu-desktop-lxde-vnc:focal
2. visit http://localhost:6080
3. launch the browser in the VNC interface and download xlights
5. click the application button and launch a terminal
6. in the terminal type `chmod +x xLights*; ./xLights-2022.17-x86_64.AppImage --appimage-extract`
7. launched the file manager and navigated to squashfs-root
8. launch AppRun

**Expected behavior**
Anything better than that, eg

- Don't show TOD until after show selector is done in initial setup.
- Show TOD below the show selector
- Don't show show selector until TOD is closed

**Versions (please complete the following information):**
 - OS: gentoo-docker-ubuntu-focal-lxde
 - xLights version: xLights-2022.17-x86_64

**Additional context**
No sequences relevant.

**Comment by AzGilrock** [comment]
So there's a workaround...we should add this to the Tips of the Day. :)

**Comment by freman** [comment]
I suppose that would be an ideal 4th alternative - make the first tip of the day for a fresh install "look behind this window"
