### ISSUE TITLE
Crash after changing layout

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3435]
Attached is the log dump - if this is not helpful feel free to close.  (Nightly build)

Opened the included sample sequence,
went to the layout, 
clicked on the group - spinner
added the efl radio 5x5 spinner submodel to the group
click back on the sequence, click on effect and it crashed.
Seems to be a common source of crashing - open sequence, change layout, back to sequence and crash.
[xLights_dbgrpt-22116-20220921T115951.zip](https://github.com/smeighan/xLights/files/9618384/xLights_dbgrpt-22116-20220921T115951.zip)

Another -- edit display elements, added group Spinner arms small then moved it down the order. 
Back to sequence and crash

[xLights_dbgrpt-7744-20220921T123410.zip](https://github.com/smeighan/xLights/files/9618663/xLights_dbgrpt-7744-20220921T123410.zip)
Create submodel, add to group, back to sequencer..
[xLights_dbgrpt-16960-20220921T134215.zip](https://github.com/smeighan/xLights/files/9619111/xLights_dbgrpt-16960-20220921T134215.zip)

**Comment by dkulp** [comment]
Unable to reproduce using the instructions on Linux or Mac.

**Comment by derwin12** [comment]
Just to add house preview needs to be open .. apparently crashing on the refresh of the house preview.

**Comment by derwin12** [comment]
![image](https://user-images.githubusercontent.com/4643499/192121969-9b5f43ce-8e79-42de-b8de-e7cd6141368f.png)

**Comment by derwin12** [comment]
Still crashing with 18.1
Open House Preview
Open Sequence
Click on Single Strand effect on Group - Spinner Rings
Go to Layout
Group - Spinner Rings
Add submodel like PC Spinner Left/Ring 3
Save
Back to Sequence and click off and on the Single Strand.
(if you didnt have house preview on, then turn it on, and crash)

[xLights_dbgrpt-3260-20220929T161119.zip](https://github.com/smeighan/xLights/files/9678949/xLights_dbgrpt-3260-20220929T161119.zip)
[xLights_dbgrpt-17168-20220929T111616.zip](https://github.com/smeighan/xLights/files/9678950/xLights_dbgrpt-17168-20220929T111616.zip)

**Comment by derwin12** [comment]
v19. Just an update that it continues to crash with this simple adding a model to a group during the house/model render.

[xLights_dbgrpt-38824-20221004T125421.zip](https://github.com/smeighan/xLights/files/9709061/xLights_dbgrpt-38824-20221004T125421.zip)

**Comment by derwin12** [comment]
fyi .. still duplicate this on .20 .. update a group, remove a submodel with a sequence open and house preview. Once you come back to the sequencer the crash dump comes up.

**Comment by keithsw1111** [comment]
With a simple layout I still cannot reproduce this. I added 2 46" flakes. created group and added the backlight pixels. Created a sequence. Added effects to groups and non-groups. then went to layout and clicked on submodel group and removed one of the submodels ... no crash.

So there is something more going on to cause the crash.

**Comment by derwin12** [comment]
I will try and strip it down to find the trigger..

**Comment by derwin12** [comment]
One model, one group. Last nights nightly - going to get some zoom roomers to try with this zip as well.
Open sequence, open house preview. Render and save sequence.
Go to layout .. add more submodel rings OR take a few away from the group.
Save
Go back to sequencer and click on one of the effects (to force the render)
[TestSequence.zip](https://github.com/smeighan/xLights/files/9854418/TestSequence.zip)

**Comment by keithsw1111** [comment]
Can you try this with the next nightly build. It may stop the crash

**Comment by derwin12** [comment]
Fixed in the latest commits -- pulled in and compiled .. Unable to duplicate crash now.
