### ISSUE TITLE
Inserting a GE icicles prop causes "failed to download model file" dialogue box

### ISSUE THREAD

**Issue by amiga-600** [smeighan/xLights#3436]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Using the "Create New Download" button, and selecting "Gilbert Engineering USA -> Christmas -> Icicles" then "Insert Model", xLights shows an Error Dialogue Box with the text "Failed to download model file." No prop is inserted.

**To Reproduce**
1.  Click "Create New Download" 
2. Click and drag on layout
3. Model download dialogue box appears
4. Click "Gilbert Engineering USA"
5. Click "Christmas"
6. Click "Icicles"
7. Click "Insert Model"
8. xLights shows an Error Dialogue Box with the text "Failed to download model file."
9. No prop is inserted.

**Expected behavior**
I was expecting to see the icicles prop to be inserted into the layout.

**Screenshots**
![2022-09-20 20_22_21-Window](https://user-images.githubusercontent.com/114023659/191578721-ac35e6f5-8a37-412e-a38b-4dbdbd4469b7.png)
![2022-09-20 20_23_37-Window](https://user-images.githubusercontent.com/114023659/191578753-7c0412b8-6ac8-4c34-b0f7-7445adc516a3.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: Version 2202.17

**Additional context**
None

**Attachments**

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
this is an issue with GE model repository. They have a link to a file that doesn't exist. Please contact GE.

![image](https://user-images.githubusercontent.com/2293065/191616873-68898538-c1bc-40b7-bc46-c90725210b6a.png)
