### ISSUE TITLE
Layout screen error when selecting models

### ISSUE THREAD

**Issue by nmiller0113** [smeighan/xLights#344]
I have an error that I get when I select one of my models in the preview area of the layout tab.  As an example, I tried to move the placement of my megatree and it gave the error.  I've restarted the program and it does it for all models and does it every time.  UNLESS.  In the layout tab on the left under Preview Models...if I select it there first I do not get any error for that model, or any model I select after that...no matter if I switch tabs and come back or whatever.  So the workaround is to select it in the left box first and then work in the preview window..otherwise I get the error below every time:

Xlights Error
21:20:16: Couldn't retrieve information about list control item 3.
21:20:16: Couldn't retrieve information about list control item 3.
21:20:16: Couldn't retrieve information about list control item 0.
21:20:16: Couldn't retrieve information about list control item 0.
21:20:16: Couldn't retrieve information about list control item 0.

I'm running the latest version of xL4 4.2.2 on a Windows 7 64bit machine

**Comment by nmiller0113** [comment]
I just noticed that even after the workaround, if I modify one of the models and come back and select a model in the preview area again it gives me the error until I select a model, any model, from the left side.  I can reproduce this every time.

**Comment by cjd** [comment]
I've just pushed a change to git that may help with this.
I'll test a bit more and if it works it should be in the next release
