### ISSUE TITLE
Upload to Advatek Mk2 or Mk3-Type Controllers Has Issues Effecting Controller Config

### ISSUE THREAD

**Issue by msimmons78** [smeighan/xLights#3442]
**Describe the bug**
1. The Name provided in xLights Controllers Config has random special characters added to it the end of the Advatek Controller's Nickname when uploaded.
2. When xLights does an upload, it should automatically set the Controller's "Advanced" checkbox as CHECKED, as shown in the Advatek's Assistant - Control Tab for the Controller, under all circumstances this should be hard coded.
3. Found that whenever xLights does an upload, it automatically sets every Port Configuration on the Advatek Controller to Zig Zag 1, when default should be Zig Zag 0 (for no Zig Zag).  Further found, that xLights Layout's Controller Connection is missing "Set Zig Zag" for Advatek Controllers.  This functionality is missing from the advatek.controller file and from code.

PLEASE NOTE... This is an urgent issue as this is effecting a large 300+ Advatek controller deployment that's coming up soon!!!

**To Reproduce**
Setup an Advatek Mk2 or Mk3 Controller and add a Model and then set Model to that Controller through Visualizer. And then do a Upload Output for that Controller.

**Expected behavior**
1. Controller's Nickname should match exactly Controller's Name within xLights.
2. Whenever an Upload is done to an Advatek Mk2 or Mk3 Controller, the Advanced checkbox should be CHECKED always for the Control config.
3. Whenever an Upload is done to an Advatek Mk2 or Mk3 Controller, the Zig Zag setting for every Port should be set to default 0, unless Zig Zag is checked in Layout's Controller Connection.    Also, such Zig Zag setting should be added as an available option under the Layout's Controller Connection settings.

**Screenshots**
See attachments...

**Versions (please complete the following information):**
 - OS: Windows 11 Pro 64-bit version 22H2 (22621.521)
 - xLights version 2022.17 64-bit
 - Advatek Firmware version 2.0.31 (latest public version)
 - Advatek Assistant version 2.3.24 (latest public version)

**Additional context**
N/A

**Attachments**
See Dropbox Link as:
https://www.dropbox.com/sh/sjgcclq727y2rr6/AAB6CqgDpaUZKZhv3XD-E1DZa?dl=0

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

Regards,
Michael

**Comment by keithsw1111** [comment]
#1 was a bug and is fixed.
#2 was a documentation bug ... it says I need to send a 1 but 0 seems to provide the desired behaviour
#3 advatek zig zag has never existed (it was only added to Falcon and FPP) and thus would have uploaded zeroes. It looks like you set it when using some other or undefined controller and it was holding it. Either way I have added the ability to set it.

I have made no changes for MK3 controllers as I have none to test on but the fixes may also work there.
