### ISSUE TITLE
Xlights on Mac causing E.131 data to always be transmitted on FPP v6.1 when upload output or FPP connect is used

### ISSUE THREAD

**Issue by meckman** [smeighan/xLights#3443]
So I upgraded my Raspberry Pi 4 to FPP v6.1, loaded up the FPP backup (v5.5) of settings and everything seemed fine until all my Atom bulbs running WLED all turned off.  Went to their WLED page and it said that the RPi was sending E1.31 data even though the player is idle.  

Re-etched FPP v6.1 and this time I did not use a backup.  Instead I manual configured the network settings, and loaded up 1 sequence/audio for testing, then finally I configured 1 of the Athom Bulbs in the channel outputs as it is in my show. Saved everything and started the sequence that I uploaded and the bulb reacted as it should to the E1.31 being sent.  I stopped the sequence and the bulb went back to the WLED default effect.

This is where it gets wierd.  I went to xlights (on Mac M1 mini running 2022.17) and pressed upload output on the controller tab for the RPi and it starts sending out the E1.31 data and the bulb turns off waiting for data that is not coming since the RPi is idle. The same happens when I hit FPP connect and upload the models and UDP data.

Verified the "Always transmit channel data" is unchecked.  Basically, it's all default settings except the network settings.

I have FPP v5.5 running on a separate RPi and I have no problems uploading to that RPi.  So this could also be a FPP issue, but figured I'd start here since FPP v6.1 seems work as long as it's manually entered and not sent from xlights.

**Comment by derwin12** [comment]
Think we saw something like this on zoom room last night. Had a VM defined in fpp but not used or sequenced. Output to lights flooded the pi with channels it shouldn't have. We had to disable the output on the pi to make it stop.

**Comment by meckman** [comment]
> Think we saw something like this on zoom room last night. Had a VM defined in fpp but not used or sequenced. Output to lights flooded the pi with channels it shouldn't have. We had to disable the output on the pi to make it stop.

This RPi is my Master player/controller. It is configured for a VM (it is configured and is used) that goes out to a projector. This board also handles the audio via soundblaster and obviously it handles the E1.31 data for the Athom light bulbs and large wreath all running WLED. I don’t believe I can disable the the output since I need the E1.31 data to be transmitted when the player is actively playing a sequence.

**Comment by meckman** [comment]
Upgraded to FPP 6.3 on my master controller and no longer exhibiting this issue. Seems to be fixed
