### ISSUE TITLE
Submodel selection process issues

### ISSUE THREAD

**Issue by Arcxk** [smeighan/xLights#3444]
**Describe the bug**
When trying to select submodels using the "Select Nodes" modal popup, using the "OK" button to confirm the current selection results in all nodes being selected for the submodel. Additionally, submodel selection is not working at all. I am only able to deselect nodes that have already been selected.

**To Reproduce**
1. Open submodel modal for any model
2. Click "add" button to create a new submodel
3. click "draw model" button to open "Select Nodes" modal view
 -  At this point I am unable to select any of the nodes via double-clicking a number, nor drag-and-drop mass select. I am, however, able to use the "select all" button to highlight all nodes, and then double-click or drag-and-drop to deselect some nodes.
4. Clicking ok results in all nodes being selected in the current submodel when back in the "Submodel" modal screen. 
5. Selecting a specific row, clicking "Draw submodels" to open the "Select nodes" modal view, then clicking "Select None" and then "OK" results in all nodes being selected in that specific submodel row.

**Expected behavior**
It should be possible to select or deselect specific nodes via double click or drag-and-drop, and have that selection honored when the "ok" button is clicked in the "Select Nodes" modal view.

**Screenshots**
Attached MHT file (MIME HTML file) from Windows Steps Recorder displaying the steps and highlighting mouse inputs.

**Versions:**
 - OS: Windows 10
 - xLights: 2022.17 (first noticed this year around v2022.08 )

**Additional Context** 
Works exactly as expected on MacOS. No issues there.

[steps.zip](https://github.com/smeighan/xLights/files/9648252/steps.zip)

**Comment by keithsw1111** [comment]
I am pretty sure this is fixed in the next version.

**Comment by Arcxk** [comment]
Not fixed as of 2022.21

Submodel Modal: Add > Draw Model > Select None > Ok

Results in all nodes being selected

**Comment by computergeek1507** [comment]
The next version will likely be 2022.22
