### ISSUE TITLE
Mapping/Translation table for Auto Map and possibly Bulk Render to help with year-to-year changes.

### ISSUE THREAD

**Issue by neowolfwitch** [smeighan/xLights#3447]
Often as shows evolve, props are renamed or retired and replaced. Often props from last year's sequence (for example) can be mapped one-to-one with a new prop for this year. Perhaps "Office Matrix" is now just called "Matrix", or "Mini Tree 1" is now "Mini Tree Left".

It is very tedious re-mapping dozens of sequences when the only things that have really changed may be the names of a props, or there is otherwise a one-to-one relationship between an old prop name and a new one. Auto-Map is great if there have been no changes, but there is no way to persistently tell it to map something to something else.

If there was a way to set up a mapping or translation table- this would be a lot less tedious and would save possibly hours of time in some cases. It can sort-of be done with saved mappings, but that isn't very intuitive and only works if every sequence has the exact same layouts and mappings to begin with.

It could have dozens of translations, which would also help significantly for importing purchased sequences. The table could look something like:

Mega Tree A -> Mega Tree
Mega Tree B -> Mega Tree
Mega Tree Left -> Mega Tree
Mega Tree Right -> Mega Tree
Mega Tree Sphere -> Mega Tree Starburst
P10 -> Matrix
P5 -> Matrix
GRP-Yard -> Yard
Office Matrix -> Matrix
Garage Matrix -> Matrix
Big Vendor Super Mega Awesome Wreath -> Wreath Left
Big Vendor Super Mega Awesome Wreath -> Wreath Right
...etc.

Those last two are an example of a single prop translated to two different props.

If there is duplication, for example using the above if there actually is an "Office Matrix" and a "Garage Matrix" in the imported layout, only the first match would be used. Perhaps some indicator like a special color flag could be used to indicate the duplicate entry in the Import Effects screen.

In the import Effects screen, it could possibly be built-in as an extension to Auto Map. It could also work for Bulk Render when a change in models is found- if it is referenced in the mapping/translation table- it would just be re-mapped instead of reporting an error (which won't be fixed anyway). This would allow someone to just copy last year's sequences to this year's show folder, and batch render them. Obviously if props changed there is a lot more to do, but this would eliminate a lot of time-consuming prop mapping  tedium, freeing up more time to actually tweak the sequences.

It may be possible to do something like this with the API, but I haven't dug into that again this year.

**Comment by cybercop23** [comment]
Hi @computergeek1507. I was going to put in a request for your Bulk Render remap and master view enhancement. Sounds like that would address this need as well as being able to update Master View to a new one when BR.

**Comment by sheisler314** [comment]
I agree that this would be so helpful as I have to re-map every sequence after making a prop name-change.  It would be great if we could apply an "updated map" or choose a "default map" that would include this one-to-one conversion/change.
