### ISSUE TITLE
Test tab not updating model names until restart of XL

### ISSUE THREAD

**Issue by nmiller0113** [smeighan/xLights#345]
The test tab model names are not updating until after a restart of XL.  I noticed this when I made some model name changes in the layout tab and saw that my test tab channel names had not updated.  I hadn't seen this previously so I restarted XL to see if that would fix it and it did.  Obviously something super minor and non-critical to the functionality of XL.  Just thought you'd like to know it.

**Comment by stevegiron** [comment]
That's just the way it works. The xLights configuration file is read when the application starts and the test tab code currently does not dynamically keep looking for updates.  I'm going to close this issue request as there is at least one other with the same observation. - Steve
