### ISSUE TITLE
2022.18 Crash on render

### ISSUE THREAD

**Issue by Nickatnite27** [smeighan/xLights#3450]
Xlights 2022.18 crashes on all renders. Does not matter which sequence. All do it. I’m using a MacBook Pro running Monterey 12.6

**Comment by AzGilrock** [comment]
Well you need to at least provide something.  After a crash open xLights and do a Package Log Files and attach it.

**Comment by dkulp** [comment]
Latest app store build (2022.18.1) should fix this.
