### ISSUE TITLE
FPP Proxy IP Missing for Twinkly Controller

### ISSUE THREAD

**Issue by koolsb** [smeighan/xLights#3452]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
The FPP Proxy IP is not configurable for a twinkly controller

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Controllers
2. Click on Add Ethernet
3. Change Protocol to Twinkly
4. FPP Proxy field disappears

**Expected behavior**
I expect the field to be configurable.

**Screenshots**
<img width="656" alt="image" src="https://user-images.githubusercontent.com/14332595/193357498-4eca7a2c-64ed-478d-80ef-b2f8eb932f48.png">

**Versions (please complete the following information):**
 - OS: Mac 12.2.1
 - xLights version 2022.18.1

**Additional context**
I have a use case where my twinkly lights are not on my main show network. I am using a FPP to proxy to the network the twinkly lights live on.

**Comment by keithsw1111** [comment]
@dkulp will tell me if i am wrong but I dont think FPP can proxy Twinkly traffic.

**Comment by computergeek1507** [comment]
FPP has a Twinkly output

**Comment by keithsw1111** [comment]
I know ... but can it proxy the protocol.

**Comment by dkulp** [comment]
It doesn't need to.   If you set an FPP proxy on an e1.31 based controller in xLights, the data is sent to FPP via DDP.  FPP than turns that into whatever protocol is needed.

**Comment by keithsw1111** [comment]
Yeah but twinkly isnt set as E131 ... so I think we need code changes like in e131 to switch it.

**Comment by koolsb** [comment]
I don't know if I need it to proxy per say... FPP will not be receiving any data. My use case is an FPP running in remote mode with the twinkly lights behind it. I need xlights to generate the V2 Sparse FSEQ file for the remote that includes the channels for the twinkly controller while configuring twinkly as a UDP output on the FPP remote also. Let me know if that doesn't make sense. 

![Screen Shot 2022-09-30 at 8 13 20 PM](https://user-images.githubusercontent.com/14332595/193377435-bca99e3a-6869-4c55-b878-93449d30fc2e.png)

**Comment by koolsb** [comment]
Thanks for jumping on this so quickly Keith!
