### ISSUE TITLE
iseq Error

### ISSUE THREAD

**Issue by wbottomley** [smeighan/xLights#346]
When transferring files to another pc without the same directory structure... an iseq error box pops up.  The suggested work around would be to manually edit the xml file with the correct directory path.
![screenshot 2015-08-23 09 32 52](https://cloud.githubusercontent.com/assets/12785363/9454688/023b14fe-4a92-11e5-95ea-39215fec122c.png)
![screenshot 2015-08-23 09 33 13](https://cloud.githubusercontent.com/assets/12785363/9454689/042470b2-4a92-11e5-9a8b-5ec0ab42732d.png)

**Comment by stevegiron** [comment]
This is not an application issue. Editing the xml file manually is an acceptable way to point to the new file location if need be. Keeping the same folder structure between PCs will also prevent this message from coming up.
