### ISSUE TITLE
xLights interface unresponsive

### ISSUE THREAD

**Issue by Stoshx** [smeighan/xLights#3460]
**Info**
Windows 10 version 21H1
RAM - 16GB
Processor - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz   4.00 GHz
Graphics - NVidia GeForce GTX 1060 6GB
xLights version - xLights64_2022_19

**Describe the bug**
xLights becomes unresponsive after performing any task on the sequencer tab..  The Controller and Layout tabs don't have any issue, only the sequencer tab.

**To Reproduce**
1. Launch xLights
2. click on Sequencer tab
3. start a new sequence
4. hit play on empty sequence and all controlls stop working.  Can't stop or pause the sequence.  I have to wait until it plays out 30seconds before any controls work.

I have one very simple basic sequence on a single string of 170 pixels, just loading the sequence locks the program and I can't do anything.  I can't even ALT+TAB to xLights, the entire program becomes unresponsive.  I can see the model and house preview both showing an effect moving, but I can't do anything in the proram.  The only way I can close it out is by killing the process from windows.  Nothing else on my computer is affected when xLights becomes unresponsive.

[Test.zip](https://github.com/smeighan/xLights/files/9720900/Test.zip)

**Comment by derwin12** [comment]
Works here ... with your upload. Perhaps go to Tools->Package log files and upload that?

**Comment by Stoshx** [comment]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/9730361/xLightsProblem.zip)

xLights is somewhat useable if I close out the House Preview window.  But if I play a sequence, any sequence, even a blank one I can't do anything until it finishes playing.  Pause button doesn't work, stop button doesn't work, no button works while playing a sequence.

I've notices that if I try to click on things or do things while the sequence is playing it's like it stores up those actions and once the sequence stops playing it tries to catch up from all my button presses that occured while the sequence was playing.

Attached is the requested file.
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/9730379/xLightsProblem.zip)

**Comment by derwin12** [comment]
Note .. we saw another case of this in Zoom last night. The render of a sequence just went Not Responding. Went back to .17 and it was fine. (.19 has issues buried in there somewhere)

**Comment by keithsw1111** [comment]
I tried the file and it renders and plays fine.
