### ISSUE TITLE
xlights import -> load mapping is not working.

### ISSUE THREAD

**Issue by jlebaugh** [smeighan/xLights#3461]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
xlights does not load a saved mapped file

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to 'Import -> import effects'
2. select .xsq file to import
3. Select some items to map from/to
4. Click on 'save mapping'
5. save file to <some file>
6. Click on 'cancel' 
7. Go to 'Import -> import effects'
8. click on 'load mapping'
9. no mappings are loaded

**Expected behavior**
Previously mappings would be preserved and loaded.

**Screenshots**
![Screen Shot 2022-10-06 at 12 37 58 AM](https://user-images.githubusercontent.com/24513756/194222896-da949a79-1c01-4a89-96d5-cc8792e1b786.png)
![Screen Shot 2022-10-06 at 12 38 50 AM](https://user-images.githubusercontent.com/24513756/194223012-16ce2cbb-ec78-4eb1-b7fb-785c65db01ad.png)
![Screen Shot 2022-10-06 at 12 39 31 AM](https://user-images.githubusercontent.com/24513756/194223108-87572655-1a78-4906-945f-5bfcd088ccd2.png)

**Versions (please complete the following information):**
 - OS: macOS 12.6
 - xLights version: 2022.19

**Additional context**
This worked for me last year, doesn't seem to work today.   Zoom room proposed filing a bug.

**Comment by onewithhammer** [comment]
Same issue.  Easy to reproduce.  I tried many times with different sequences but doesn't load mapping. 

OS: macOS 11.6.5 Big Sur
xLights Version: 2022.19

**Comment by computergeek1507** [comment]
Fixed with ecfafee839ad16e0586fd04c136b75fe879631c3 and 51ceb81b32d027252c531b9492221a1924710f5e
