### ISSUE TITLE
Metronome millisecond issues

### ISSUE THREAD

**Issue by TheHodge** [smeighan/xLights#3462]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When adding a metronome timing, I am unable to start the timing with 1 (e.g. to type 1000) I can type 2-9, (obviously cannot type zero) but one gives me an error sound.

(when producing a video of this issue, I found that 2-4 could also not be pressed)

In addition, the element is limited to 4 characters however if I type 9999 and click the Up arrow, I am able to create a timing with 5 decimal places.

**To Reproduce**
 I have produced a video showing this issue [https://share.cleanshot.com/kPHMUy](https://share.cleanshot.com/kPHMUy), when the dialog opens I am pressing 1,2,3,4,5,6,7,8,9

But to reproduce yourself

* Click Add Timing Track
* Select Metronome Interval
*Create a new timing track with the metronome 
* Select the milliseconds and type any number from 1-4 you will hear an error sound

**Expected behavior**
The box should fill with 1-4
**Screenshots**

See linked video above.

**Versions (please complete the following information):**
 - OS: OSX 12.4 (21F79)
 - xLights version 2022.18

**Additional context**
I can attach a sequence to this although I don't believe it's needed as this isn't a sequence issue?

**Comment by TheHodge** [comment]
Yep we tested this last night on Zoom and found that it seems to be an OSX only bug!

**Comment by sslupsky** [comment]
I submitted PR #3029 to fix this issue but it has not been merged.

@dkulp What is the status of #3029 ?  I recall you were hoping the issue would be resolved with a wxWidgets update but the problem still exists.

**Comment by cybercop23** [comment]
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/8d8b60a0-03b6-4664-a21a-353a39fc12ee)

Seems to work now. @TheHodge please confirm and close issue.

**Comment by sslupsky** [comment]
I see that wxWidgets has been upgraded to 3.3.0.  The bug was fixed in wxWidgets 3.2.0 so it should be fixed in xLights now.
