### ISSUE TITLE
Butterfly Effect Not Playing

### ISSUE THREAD

**Issue by kentstroker** [smeighan/xLights#3464]
All of my sequences that use a Butterfly effect are broken. The butterfly effect no longer appears in the Model Preview or House Previews. When I click on the butterfly effect in the timeline it does not display. Re-rendering does not change the situation. I am on 2022.19 on a Mac. I noticed this problem manifesting in 2022.18. My current workaround has been to replace the butterfly with plasma. I tried making a new sequence and importing from the "broken" ones, that does not alter the outcome. When I create a New Sequence then Butterfly seems to behave as expected.

If I create a New Sequence then Butterfly seems to behave as expected, I tried testing if groups might impact behavior but have not found a correlation. 

Thanks for all you do and I hope this is enough to help you find the root cause. Contact me for more details if you need them.

**Comment by keithsw1111** [comment]
A while back I thought Dan was playing with a mac only rendering of the butterfly effect to make it run better there but i dont see it in the code so maybe i was imagining things or he has since removed it.

Assuming I am not missing something then it is possible there is something going on with your specific sequence.

A few things to try.

1. Create a new animation and try it ... is it still a problem?
2. If it is still a problem run check sequence ... there are some checks in there than can spot these issues.
3. Share the sequences with us that has the problem ... ideally this test sequence with just one effect.

**Comment by kentstroker** [comment]
Creating a new animation with just a single effect does appear to work. This problem is impacting all of my sequences, not just one. Check Sequence revealed nothing beyond few overlapping channels. It is worth noting that there appears to be no correlation between the type of model and this problem. I have found out that if I drag a replacement Butterfly effect onto the existing, then Butterfly works. But, as soon as focus is placed on a different effect, returning to the Butterfly effect causes it to break again. I do have a Windows desktop that I could press back into service and see if this is truly a Mac-centric issue. Will share my findings shortly. I have attached the sequence in question. Thanks for checking into this, my current work around is to replace Butterfly with Plasma and increase the speed.

**Comment by kentstroker** [comment]
[Canvas Wonderland Intermission.xsq.zip](https://github.com/smeighan/xLights/files/9739977/Canvas.Wonderland.Intermission.xsq.zip)

**Comment by kentstroker** [comment]
This is a purchased sequence, Addams Family Theme Song. The Butterfly on the House Outlines and Verticals notoriously display this issue.
[AFT v1.xsq.zip](https://github.com/smeighan/xLights/files/9739986/AFT.v1.xsq.zip)

**Comment by keithsw1111** [comment]
Is there a layout that goes with that file?

**Comment by dkulp** [comment]
This is fixed in the next release.  Workaround is to disable the RenderCache or disable the GPU rendering.
