### ISSUE TITLE
Pinwheel with Value curve on Speed is jerky..

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3465]
From zoom room - is this supposed to be smooth as we value curve "speed" up from 0 to say 10.
If you watch the white blade, it jumps around rather then simply speeding up.
(found on mac but seems to be duplicated on windows)

v.19 and v .17
[fanbug.zip](https://github.com/smeighan/xLights/files/9742620/fanbug.zip)

**Comment by computergeek1507** [comment]
I believe this has been reported before. The pinwheel effect algorithms were written before value curves existed. It would need to be rewritten to support them better.

**Comment by derwin12** [comment]
Can this be tagged as enhancement request .. for when you are bored :-) or when I learn c++ ..

**Comment by AzGilrock** [comment]
It’s how value curves work.  The effect is calculated as if the input from the curve was at the current value the entire time.

**Comment by AzGilrock** [comment]
It works that way in tons of effects it’s just not so obvious on all of them.

**Comment by derwin12** [comment]
I seem to recall you mentioned this before .. thanks Gil.

**Comment by AzGilrock** [comment]
You could do it but the math would need to change so it could keep track of the previous position.  That would affect existing sequences so then you gotta provide an old vs new render method
