### ISSUE TITLE
Resize capability of "Preferences" Window on Windows Xlights

### ISSUE THREAD

**Issue by sheisler314** [smeighan/xLights#3470]
Problem:
Some screens do not allow the whole "preferences window" to fit in the screen.  Sometimes the toolbar at the bottom has to be moved or I have to go to other computers to change the settings and then allow my Google-Drive to sync up before re-opening on the computer where it doesn't fit.

**Describe the solution you'd like**
I'd like the Preferences window to be able to be resized so it can fit on the screen.  Either a "full screen" version or resizable corners.

**Comment by sheisler314** [comment]
The visualizer and keybindings windows both provide the ability to re-size

**Comment by computergeek1507** [comment]
In the future please fill out the whole issue template, don't delete parts like Operating System, Version, they are helpful.

**Comment by AzGilrock** [comment]
I personally can't stand it when people leave the entire template when they only fill out a few sections.  Things not filled out should be deleted and the sections that are filled out need the instructions removed I don't want to sift through it.

**Comment by keithsw1111** [comment]
Closed due to lack of response
