### ISSUE TITLE
Upload output to fpp 6.1 problem

### ISSUE THREAD

**Issue by thisim** [smeighan/xLights#3476]
- xLights version 2022.19
 - FPP version 6.1 with valid license for 48 output

There is a problem when I upload the output.
start channel an number of pixels assigned to outputs are not uploaded to fpp. In addition, the type of card selected in xlights is RGB48 and it is an RGB24 type that is uploaded to FPP.
I have attached screenshots and xlights log for you.

![1](https://user-images.githubusercontent.com/31959517/195940180-2268748e-f65d-41c5-a32b-b19e050bf06c.jpg)
![2](https://user-images.githubusercontent.com/31959517/195940307-129ea72e-aa8a-40ce-8091-b9ba8aa155db.jpg)
![3](https://user-images.githubusercontent.com/31959517/195940384-5a74bbea-36f7-4b3b-beab-7a75c5532278.jpg)
![4](https://user-images.githubusercontent.com/31959517/195940433-bfa73a2b-475f-479d-b3a5-ed47a38b2ed5.jpg)
![5](https://user-images.githubusercontent.com/31959517/195944972-33d16c49-b5ad-4f3b-a981-b2ac6ebe94ec.jpg)

[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/9790071/xLights_l4cpp.log)

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/9795561/xLightsProblem.zip)

**Comment by derwin12** [comment]
In xlights do a tools -> package logs files and attach it to the tickets

**Comment by thisim** [comment]
> In xlights do a tools -> package logs files and attach it to the tickets

It's good, I did the necessary to add the file.

**Comment by thisim** [comment]
Problem solved in new versions of xlights.
