### ISSUE TITLE
New "all" group created, layers underneath not rendering anymore

### ISSUE THREAD

**Issue by Erik-JanWind** [smeighan/xLights#3478]
**Describe the bug**
I created a new "all" group with which include my 2 new matrices. ( want an all group, that I had, without matrices and an all group with matrices. When I open a sequence, I copy all lines from my "all" group and paste them in "all with matrices" and delete the "all" lines. After that everything beneath it will not show anymore. I tried new saving, rendering, playing an effect on all separate layers. At the moment, no joy.

**To Reproduce**
Create a new "all" layer with a matrix included. Open a sequence and copy effects from old "all" layer to the newly created one. 

**Expected behavior**
That everything underneath would just render as "normal" on top of the new  "all" layer

**Versions (please complete the following information):**
 - Windows 11
 - xLights version [e.g. 2022.17 64bit]

**Attachments**
Attached the file with the (in my eyes) error in the "all with matrix" layer. If copied to the "All" layer above and delete the "all with matrix" everything is back to "normal"

[Walking in a winter wonderland Matrix layer all.zip](https://github.com/smeighan/xLights/files/9793139/Walking.in.a.winter.wonderland.Matrix.layer.all.zip)

**Comment by computergeek1507** [comment]
This was fixed in 2022.19

**Comment by computergeek1507** [comment]
If you restart xLights it will probably work on your version

**Comment by Erik-JanWind** [comment]
Goodday, I dl the newest version, started it, still same results, no underlying layers

**Comment by computergeek1507** [comment]
The render order is based on your master view put the new group at the top of the master view in the display elements

**Comment by Erik-JanWind** [comment]
YEAH!!! Nice one! I created a new master view a couple of days ago, because of the, no longer nice order. (I did not "Make it master") Now I did, and it works perfectly. Thanks a milion!
