### ISSUE TITLE
Enhancement Request - Resizing Whole House Preview Window

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#348]
You can resize the model preview window and the model with be enlarged or reduced in proportion.  The whole house preview does not work the same way, as it does not maintain the same proportions when you change the window size.  Anyway to make the resizing consistent between the two, with the model preview window being the ideal way?

**Comment by AzGilrock** [comment]
I think this is working as requested now.  Please hit close if you agree.

**Comment by kppankratz** [comment]
Still no change on my end as I can still distort the whole house image and models by stretching or squishing the window.  Not a big deal or high priority as once the window is set, I tend not to touch it again.  This is just one of those cosmetic items that does not affect how the program functions.  I will close this request and it could be reopened again if needed.
