### ISSUE TITLE
z Rotation making the picture have "holes" in it.

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3483]
ver 19 - Paul from Zoom (different Paul btw)

Using a picture as a mask or just placing on top of an ON effect will leave pixels showing thru if there is a rotozoom z rotation set.

![image](https://user-images.githubusercontent.com/4643499/196316359-6f8b0e13-2358-4493-9d02-dd775776f3c7.png)
![image](https://user-images.githubusercontent.com/4643499/196316389-c2325ecb-af9c-4cc1-966b-b4c213476721.png)

In this example a heart png, that was rotated 17deg,  was used, but other choices were spiders etc..

[Paul - icequeen.zip](https://github.com/smeighan/xLights/files/9805714/Paul.-.icequeen.zip)

**Comment by keithsw1111** [comment]
Did you change the zoom quality?

**Comment by derwin12** [comment]
Workaround seems to address the need.. thanks for pointing it out.
