### ISSUE TITLE
Crash on paste

### ISSUE THREAD

**Issue by ptr727** [smeighan/xLights#3486]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Pasted an effect on a newly created group.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Copy effect.
2. Go to layout and create a new group.
3. Come back to sequence and add group to view.
4. Paste effect on newly added group
5. Crash

**Expected behavior**
No crash

**Screenshots**

**Versions (please complete the following information):**
 - OS: Win11
 - xLights version 2022.20

**Additional context**

**Attachments**
Crash
[xLights_dbgrpt-14936-20221019T215328.zip](https://github.com/smeighan/xLights/files/9826439/xLights_dbgrpt-14936-20221019T215328.zip)

**Comment by derwin12** [comment]
Sounds similar to .. https://github.com/smeighan/xLights/issues/3435

**Comment by ptr727** [comment]
Could be, I notice that whenever I change the layout grouping while a sequence is open, and then interact with the sequence, it will crash.  
Have to close sequence, edit layout group, open sequence.
