### ISSUE TITLE
F16V4 (F48) in bridge mode, can they be excluded from fpp connect UI?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3487]
Would it make sense to not include them in the fpp connect UI if they are found to be running in bridge mode. A bit of confusion on the users in zoom room. (F48 etc)

**Comment by keithsw1111** [comment]
They should be ... unless the user specifically added them. From memory the V4 does not respond to discovery unless setup as a player.

**Comment by derwin12** [comment]
Definitely showing up .. not always .. one can go in and it shows, repeat the fpp connect and it is gone.

**Comment by derwin12** [comment]
Here is one from a zoom roomer ..
![image](https://user-images.githubusercontent.com/4643499/198339585-63fff5e6-d740-4535-96d9-0d70679e5979.png)

**Comment by derwin12** [comment]
Believe this has just been addressed.
