### ISSUE TITLE
Enhancement: Fire effect height range

### ISSUE THREAD

**Issue by rudybrian** [smeighan/xLights#349]
The current Fire effect in xLights 4.2.3 doesn't give you control of the height of the effect on single strand or single pixel models. If you attempt to apply the effect to a single horizontal line of pixels (that is effectively one pixel high) and set the Location parameter to "Bottom", all the pixels are illuminated, but the Height setting has no effect. If you use a model that is >=10 pixels high, the Height setting works to give you control of the amount of flicker at the top of the model where the active pixel(s) is configured.

My enhancement ask is that the Height parameter be adjustable into the negative range (effectively lowering the base of the fire below the origin on the y-axis) so that it could be used for the standard single strand models (one pixel high) w/o needing to create custom models. This enhancement should be backward compatible with previously saved sequences as only the permitted range of the setting will have changed.

**Comment by stevegiron** [comment]
I am not sure there will be a fire adjustment for single pixel wide models as that is not what fire was intended for.

You can make a fake model that is several pixels wide, with fake channels added to the real channels. The end result is a normal looking fire on a single pixel wide model.

**Comment by rudybrian** [comment]
Thanks Steve,

This would be applicable for larger models (like matrices) as well if you wanted to initially have the fire completely off-screen (model) and grow into view.

**Comment by stevegiron** [comment]
You can have come into view with a layer mask. Use the curtain effect as a mask to reveal the fire.

**Comment by AzGilrock** [comment]
I'm gonna say this can now be accomplished using the buffer options since it can be oversized and moved with value curves.
