### ISSUE TITLE
Default controller power output to low percentage vs. 100%

### ISSUE THREAD

**Issue by ptr727** [smeighan/xLights#3491]
**Is your feature request related to a problem? Please describe.**
It has happened a few times that I add or change a controller, plug in, test, and blow all the fuses, because I forgot to change the default power from 100% to e.g. 20%.   

**Describe the solution you'd like**
I think it would be good to default to "safe" values for power output, and let the user increase power, vs. decreasing power.
In reading the xLights Facebook group posts it seems like a great many users run at reduced output, vs. a minority if any running at 100%.
Maybe you have usage telemetry that can tell you?

**Describe alternatives you've considered**
Try to remember to change the default, and replace fuses when you forget.

**Additional context**
NA

**Comment by darylc** [comment]
That would break everyones shows who uses 100% (there are such people, I am one of them)

**Comment by ptr727** [comment]
Not so, if a show already exists the output is already assigned and changing the "default" for a new controller instance does not break anything already in existence.

**Comment by keithsw1111** [comment]
The problem is then we get hundreds of support queries because their lights arent very bright.

**Comment by ptr727** [comment]
@keithsw1111 I think that is opinion.
If xLights has usage telemetry showing that is so, or you can say with certainty that the complaints you receive covers 100% of all users, then yes.
If not it opinion, then "I can claim without data to back up my claim" that 99% of configurations run at 20%.

The problem of blowing fuses, and needing physical access to repair, due to a default value that is higher than current capacity remains unaddressed.
Other than changing the static default value, there are other options, e.g.:
- Expose general and configurable default values to use for new instances, including default brightness, shimmer frequency (epilepsy avoidance), etc.
- Calculate the port current, fuses are always 5A, set the default to say 80% of calculated port current. (always = speculation but I've never seen a port not fused at 5A, and assuming regular pixels 60mA not floods)

**Comment by computergeek1507** [comment]
I agree with Keith, leave it as is. If people are blowing fuses because of 100% brightness, I don't think xLights should control it. It would only prevent the issue initially, they could change it manually and blow it later.

**Comment by merryoncherry** [comment]
@ptr727  It would be great if xLights knew the port current, but it doesn't really.  5A fuses are pretty common but people power inject, there are diff boards and smart receivers to complicate it, and the typical* pixel uses less than 30 mA even though the default in the calculation is 60mA.
*another likely controversial statement backed only my my own data.

**Comment by ptr727** [comment]
@computergeek1507 there is a distinct difference between a default value that causes a blown fuse vs. a user that explicitly changes a value to 100% and then blows a fuse.

@merryoncherry yes people power inject, and then there is even less reason to use 100% as default on data ports, vs. power injection that is at least level 2 in complexity vs. lets power this thing on and see what happens level 1.

As more users start using xLights (like myself last year), the founders / experts should at least be considered of new users and patterns that sometimes occur in niche software growing more popular over time where there is survivor bias or lack of empathy for re-experiencing first time setups of new users that have a lower bar of entry.
