### ISSUE TITLE
Linux 2022 Builds Failing - Two issues to note

### ISSUE THREAD

**Issue by cybie257** [smeighan/xLights#3492]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

Issue #1 - 
Checking wxwidgets
Checking log4cpp
Linking libliquid
Linking libxlsxwriter
make[1]: *** No targets specified and no makefile found.  Stop.
make: *** [Makefile:57: libxlsxwriter] Error 2

Issue #2 - 
sudo apt-get install g++ gcc build-essential libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev freeglut3-dev libavcodec-dev libavformat-dev libswscale-dev libsdl2-dev libavutil-dev libavresample-dev libportmidi-dev libzstd-dev libcurl4-openssl-dev libltc-dev liblua5.3-dev wget git cbp2make
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libavresample-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libavresample-dev' has no installation candidate

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Fresh Install Ubuntu 22.04 LTS (Issue seen on Latest Mint Linux, Verified on Fresh Install of Ubuntu 22.04 downloaded and updated on Fri October 21, 2022)
2. For Issue # 2 - Run the command as shown in readme.linux file to get build environment setup. 
3. For Issue # 1 - Build and get error

**Expected behavior**
Done this many times before in the past per readme without these issues. 

**Screenshots**

**Versions (please complete the following information):**
 - OS: [Ubuntu 22.04 - Latest Build]
 - xLights version [2022.XX]

**Additional context**

1) I have found a fix for libxlsxwriter error, which allows it to proceed and work/compile into executable binaries.
The fix for this was to go to https://github.com/jmcnamara/libxlsxwriter found in the dependancies.txt file, download and run make. Then I copied all the files (the entire folder, whether needed or not) to the xlights-2022-xx dependencies folder for libxlswriter. The make/build provides the files that the makefile is seeking in the dependencies/libxlsxwriter/lib/ folder
Once these files are there on a fresh build, everything seems to move along fine without any other exit errors. 

2) I have not been able to fix Issue # 2, though it seems to compile after fixing Issue #1
This Issue seems unsolvable potentially due to outdated 7:4.2.7 libavresample-dev no longer available???
Here is the output from Synaptics under the 

libavresample-dev:

Package libavresample-dev has no available version, but exists in the database.
This typically means that the package was mentioned in a dependency and never uploaded, has been obsoleted or is not available with the contents of sources.list

NOTE: Although it compiles, I am unsure of any potential crashes/issues that may arise due to this not being installed as shown.

My guess is, if this is compiling for you just fine on a Linux box, it is possible that you have the older files for libavresample-dev, so it may be necessary to do a fresh install and run through to reproduce. This is the only thought I have as far as this not being found as I have tried other releases of source from all of 2022-xx as 2021 didn't have the libxslwriter coded in. 

Please feel free to reach out if you need any additional information, or to call me dumb for something I missed :P lol. 

Thanks for all you do! -Tim

**Comment by computergeek1507** [comment]
For the first issue you need to clone with submodules, "git clone --recurse-submodules https://github.com/smeighan/xLights.git" for the second issue the avsample package was combined in another package in newer ffmpeg used by Ubuntu 22.04 and Fedora 36

**Comment by threedotsonedash** [comment]
This may or not be related, however I am unable to run any of the Linux App Image files beyond xLights-2022.05-x86_64.AppImage, for every subsequent App Image release after then, they complain of the following missing library files :

- /lib/x86_64-linux-gnu/libm.so.6
- /usr/lib/x86_64-linux-gnu/libp11-kit.so.0
- /usr/lib/x86_64-linux-gnu/libstdc++.so.6.

I've attached the terminal output from attempting to run xLights-2022.06-x86_64.AppImage, I've tried each release since then with similar output for the same missing libs.

[xLights_terminal_2022-10-24.log](https://github.com/smeighan/xLights/files/9857061/xLights_terminal_2022-10-24.log)

**Comment by cybie257** [comment]
> For the first issue you need to clone with submodules, "git clone --recurse-submodules https://github.com/smeighan/xLights.git" for the second issue the avresample package was combined in another package in newer ffmpeg used by Ubuntu 22.04 and Fedora 36

In the past, I have only had to compile from source (Zip Files provided as a single download). Chris Debenham had directed me to use that method vs any git/clone commands due to the fact that one of the issues I had in the past was due to code in progress causing an error. Ever since, and up to the end of 2021, this always worked without make failures. 
I guess I would ask, is this the solution, or just a heads up on why I get these failures? I would think we would need a readme update on the readme.linux for compiling from source. The reason I compile from source is it allows me to have a good built binary made specifically for my system that doesn't crash. I'm not to keen on the appimage as it feels like there's a lot missing and lack of control, even if that doesn't make sense, lol. Thanks!

**Comment by computergeek1507** [comment]
I added some external libraries that require git clone with submodules. The readme.linux already states this. If you don't want to build master because its broken, you can always clone a tag with -b "tagName". I remove the libavresample library requirement from the readme. I am also not a fan of the AppImage, I have started working on generating a FlatPak but I haven't got it working.

**Comment by cybie257** [comment]
> I added some external libraries that require git clone with submodules. The readme.linux already states this. If you don't want to build master because its broken, you can always clone a tag with -b "tagName". I remove the libavresample library requirement from the readme. I am also not a fan of the AppImage, I have started working on generating a FlatPak but I haven't got it working.

Ok, I will give it a go and see how it works out. Thanks for the feedback!

**Comment by cybie257** [comment]
I can confirm that using a build line such as:
git clone --recurse-submodules -b "2022.19" https://github.com/smeighan/xLights.git xLights
does work by linking the modules that the zip source code fails with.
Luckily I have a 12th Gen intel i9 with 24 (make -j24) threads that compiles in 2mins 43secs :) because I have found another issue, that seems related to an issue about freezing during render starting with 2022.20 :( 

Please close this issue if you wish. I would only ask if there is any way to compile from the ZIP File source code to get the same results. As I see it right now, the only way to really compile to work is with the git clone option. And thanks for mentioning the tag option as I wasn't aware of that. 

Thanks! -Tim
