### ISSUE TITLE
Xlights seq looks better in xlights but wen in Xscheduler it looks like its not rendered 

### ISSUE THREAD

**Issue by Sam3287** [smeighan/xLights#3496]
Wen ever i look at my show on xlights it looks good but wen i put on Xscheduler and go outside it doesn't look like its rendered  

https://user-images.githubusercontent.com/105610765/197359488-0982101f-f63e-4dc9-b072-a732a9da7a43.mp4

**Comment by bcarriveau** [comment]
*edit... 
Your controllers are Red, meaning off line or unreachable. Probably a network configuration issue.


Close xschedual open seq, render and SAVE it. Conteollers tab and be sure to upload inputs first than outputs if not lo inked, Open xschedual, verify your show folder is infact xLights current show folder, hard to see on phone screen. Try it. Sounds like controller is not provisioned or a step listed here has been missed. Xschedual only reads the fseqs apon opening.

Maybe more info is needed if others have ideas. You posted very little info.
