### ISSUE TITLE
"Tip of the day" window is broken with multiple monitors

### ISSUE THREAD

**Issue by ErrorGamer2000** [smeighan/xLights#3497]
**Describe the bug**
When opening xLights 2022.20 on Windows 10 with two monitors (Main monitor 2560x1440 with secondary 1920x1080 on the right) The tip of the day window will fill both screens

**To Reproduce**
Simply open xLights with the tip of the day enabled on two monitors.

**Expected behavior**
The tip of the day window should be contained within a single window, and should not cover the second.

**Screenshots**
![image](https://user-images.githubusercontent.com/70162741/197405281-b04a27a7-7dcb-4371-9b19-355248fa8533.png)
(See where the titlebar is cut off, that is where the monitor changes)

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version 2022.20

**Comment by keithsw1111** [comment]
Tip of the day remembers the last size set. To fix this resize it to what you want and close xLights,

**Comment by ErrorGamer2000** [comment]
I did change the size, yet it still does it.

**Comment by keithsw1111** [comment]
Then your best bet is to select view/windows/reset to defaults which should clear the settings.
