### ISSUE TITLE
Enable All Render Confirmation 

### ISSUE THREAD

**Issue by AgingBeaver** [smeighan/xLights#3498]
**Is your feature request related to a problem? Please describe.**
I was "Disable Render" on individual Models. Had done quite a few and then accidentally hit the "Enable Render on All Models".  It reversed all my work and I had to start over.   

**Describe the solution you'd like**
Either add a confirmation box with a default of "NO" to require a mouse movement and not allow the Enable All to respond to just a "enter". 
Or change the position of Disable and Enable so they are not next to each other in the Menu. 

**Describe alternatives you've considered**

**Additional context**

**Comment by keithsw1111** [comment]
I am not generally keen on prompts to check intended actions unless the action is really damaging. This isnt.
