### ISSUE TITLE
Connect "Output" button so lights can be driven from XL4

### ISSUE THREAD

**Issue by smeighan** [smeighan/xLights#35]
Currently checking the the "Output" checkbox does not enable output to the controllers. This is a blocker for a XL 4.0 release

**Comment by dkulp** [comment]
Sean, I'm seeing output when they Output box is checked.   For the Test tab, the Preview tab, and on the new Sequencer tab.   Where are you not seeing it?

**Comment by smeighan** [comment]
Hi Dan;
i dont have any hardware connected. a few weeks ago you had said you that you would connect the output button. I missed the note that said it has been done. I will close it now.

thanks!
