### ISSUE TITLE
Adding a Slider Bar to the information windows in Model Group tab.

### ISSUE THREAD

**Issue by David-65** [smeighan/xLights#350]
What I would like to see added in xLights under "Layout", is on the Model Group tab/page. 
It would be nice to have the ability to see full name of your model listed in the "Add To Group" and the "Models In Group" then the limited space shown. Either by making those two windows wider to read more information, or adding a Slide Bar under the windows to be able to read the full name of the models.
You give almost unlimited space to type in a description name for a Model/prop in the Model tab, but when it comes to viewing those models in the Model Groups you are Limited to what you can now read.

Thank you,

![0010](https://cloud.githubusercontent.com/assets/14012763/9542357/ff75f1ea-4d3d-11e5-9946-d3d8784a4f66.jpg)

**Comment by AzGilrock** [comment]
Nice drawing...I think you just volunteered to help with the user manual. :)

So even if we make these boxes scrollable realize that if this wasn't enough room to distinguish one model from another you're probably not going to be able to distinguish them on the sequencer grid because it has a similar amount of space for the row headings.

**Comment by David-65** [comment]
Thanks AzGilrock, I understand the reasoning. 
I was just hoping with the allowed spacing available when entering a Model's description, the same would be possible when viewing from another page. I always try to put as much info in what little space I have, so I know what I'm looking at later on.

Thanks again,
   David


(  I'll leave the drawing to the professionals!  ;)  )

**Comment by AzGilrock** [comment]
I wouldn't mark this WontFix.  I think adding the scrollbar isn't a bad idea but just pointing out we aren't going to want to add scrolling to the row headers on the grid.

**Comment by AzGilrock** [comment]
Turned out this one was as easy as clicking a couple checkboxes in the dialog designer.

**Comment by David-65** [comment]
Thanks, keep up the great work!!!
