### ISSUE TITLE
Video Effect - Add preview to aid setting start time

### ISSUE THREAD

**Issue by OnlineDynamic** [smeighan/xLights#3500]
**Is your feature request related to a problem? Please describe.**
When trying to set the start time for a video effect it would be useful to be able to see a frame preview whilst selecting the start time to aid finding the correct part of the video to display from

**Describe the solution you'd like**
A small preview window below the Start time slider

**Comment by keithsw1111** [comment]
This is a lot of work when you can just watch the video in any video software and note the start time there.

**Comment by OnlineDynamic** [comment]
Perhaps change the start time format to be consistent with the time format for duration instead then to make it easier to match time from external video player
