### ISSUE TITLE
Mac Version 2022.20.2 - Suddenly model overlaps when auto manage is turned on

### ISSUE THREAD

**Issue by edwinhartman** [smeighan/xLights#3501]
I have added several new models to my layout today and suddenly there are overlaps between models. I do not manually maintain start channels, it's maintained automatically, and now there are suddenly overlaps between models.

Version: Mac 2022.20.2
Model type: Custom (not sure if it happens with built-in models)

I used the same custom model in my layout and the first one was fine, but the second one has the overlaps with the previous and next model (on the controller). As soon as I past the custom model, it will highlight the previous model in red.

Not sure how to work around this issue, but it seems like a bug, as I have not seen this problem before.

**Comment by computergeek1507** [comment]
Set the controller to "No Controller" under the model settings

**Comment by edwinhartman** [comment]
Tried that, then it will show an overlap with another model. So far I have not found a way to correct it. I tried switching the sequence of the 2 custom models on the same port and then the one that was number one, now number two, shows that problem and the model that was number two and now number one does not show an overlap….

**Comment by computergeek1507** [comment]
Sounds like a configuration issue, not a bug. Without a layout it's impossible to tell you the issue.

**Comment by edwinhartman** [comment]
Something must have been wrong with the custom model. I made it again from scratch and now the problem is not there any more.

Thanks.

Edwin

**Comment by computergeek1507** [comment]
If you skip nodes in a custom model it can cause channel overlap issues

**Comment by edwinhartman** [comment]
Looks like that might have happened, as the new custom model has one more node than the old one. Thanks again. I will keep that in mind if I run into this issue again.
