### ISSUE TITLE
Import effects not properly sorted when starting the import process

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3502]
Perhaps related to:
https://github.com/smeighan/xLights/commit/3fa70d11c68ee8e65c262118e2540b65192b027c
   -- bug (dkulp)  Fix crash on Effect Import dialog on Linux

When doing an import effects v19 and prior would just show models/groups from the master view, now it is showing all props and groups.

Use case would be to have a master view set to PPD and then the import effects would just show the groups created just for that type of import.

**Comment by dkulp** [comment]
I'm not seeing this.  If I set my master view to just a few models, that's all that's appearing in the imports dialog.

<img width="891" alt="Screenshot 2022-10-26 at 2 52 49 PM" src="https://user-images.githubusercontent.com/91569/198111975-53fca9aa-465a-4e73-b214-525b69437925.png">

**Comment by derwin12** [comment]
Weird .. it was reported on fb .. I duplicated .. now I cant .. so going to close unless I can trigger it repeatedly. Thanks for looking.

**Comment by derwin12** [comment]
Talking with the FB poster in zoom room we concluded that it DOES show the right view and props - what happened was the props are not initially sorted alphabetically - giving him the impression that they were not correct.  ie It changed from v.19
Is that a bug worth fixing?
Here is the list when you first go into the import dialog. Note the ^ in the Model column - making you think it is sorted.
![image](https://user-images.githubusercontent.com/4643499/198334925-1902b51b-155b-4d7f-9077-3c6e9bb99aff.png)
Here is the list after clicking the sort twice to get to sort.
![image](https://user-images.githubusercontent.com/4643499/198335114-f1bf69fb-503d-440a-9a12-9a2c94671722.png)

Is that a new bug or just something he just happened to notice when he updated to v20?
