### ISSUE TITLE
Select nodes for sub models

### ISSUE THREAD

**Issue by ebuechner** [smeighan/xLights#3505]
**Describe the bug**
When attempting to build a submodel by using the select node window you can no longer double click and get a gray window on the Node you're trying to select and when you click ok you end up with all the nodes in the model being selected.

**To Reproduce**
Selecting any model and select sub models click on ADD then draw model, then attempt to select any node in the window. Click ok even without a node being selected and you will find that the submodel you built will have all the nodes in the model being selected.

**Expected behavior**
Double click in select nodes should give you a gray point on the Node you select and when you click ok only the node selected should be populated under node ranges.

**Screenshots**

**Versions (please complete the following information):**
 Windows 10 machine running a Verizon 9 processor x lights version 2022.10 and up

**Additional context**
After doing some testing I found that this problem came up in 2022.10.

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by ebuechner** [comment]
I spoke to Scott and he said this isn't happening on everyone's computers. Can somebody tell me what outside sources that Xlights uses during this process so I can check the settings of my computer to see what might be causing it. For instance does it call on default settings in Windows or a certain file that I may not have updated.

**Comment by keithsw1111** [comment]
This happens on windows machines where Dark Mode has been selected. Fix will be in next release.
