### ISSUE TITLE
Freezes on render 2022.20 and .21(plus nightly fix)

### ISSUE THREAD

**Issue by Griffs68** [smeighan/xLights#3507]
This is a vender sequence

set as show directory open sequence( I don't have the correct music) then attempt to render all. On my machine it renders well until 1.03 when it starts to render a video effect on a few groups(6) then it hangs up and freezes with no further rendering, requires task manager ending of task.  with the help of the zoom room, found you can suspend render and delete the effect and the sequence will render out no issue.   Here is the google link to the packaged sequence https://drive.google.com/file/d/1F_H8pv72UhSLkKd8zg12HTjT0JxhG7S4/view?usp=share_link

running windows 10  21H2

**Comment by derwin12** [comment]
The video rendered fine on other props earlier on in his sequence. It was something in one of  the effects at the 1min3s time frame.
Other renders were stuck "waiting on frame" etc. He left it running over night and it never budged on that video.

**Comment by keithsw1111** [comment]
I downloaded it and it rendered fine. Maybe try tomorrows nightly build.

**Comment by ebuechner** [comment]
I found a problem in my logs that was causing an issue on this version. Try deleting all of your render cash and then do a render all and see if the problem persists.

**Comment by extremeskillz** [comment]
Even with render cache deleted it still crashing. Also importing effects cause xlights to shutdown.

**Comment by keithsw1111** [comment]
Is this still happening?

**Comment by ebuechner** [comment]
I haven't had a problem with this for a while. I don't know about anyone else.
