### ISSUE TITLE
Throw warning when opengl is "99" -- ie less than 1 or 2 or 3?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3508]
We had a user in zoom where his shaders were not working. View log correctly showed the driver was old/uninstalled. It was showing 99.
Is that something that could/should be flagged when one starts xlights?

**Comment by keithsw1111** [comment]
I dont think so. If you dont use shaders it does not matter and the warning would just be annoying. We render the shaders as solid colours when there are errors. The 99 from memory just means use default.

**Comment by derwin12** [comment]
Perhaps add to check sequence then?

**Comment by keithsw1111** [comment]
It is already there.
