### ISSUE TITLE
2022.21 Release Crashing

### ISSUE THREAD

**Issue by bobreese** [smeighan/xLights#3510]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
New release has crashed 3 times.

**To Reproduce**
I do not know what is causing it

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2022.21

Attaching last 2 crash dump files.

[xLights_dbgrpt-1252-20221029T193830.zip](https://github.com/smeighan/xLights/files/9895591/xLights_dbgrpt-1252-20221029T193830.zip)
[xLights_dbgrpt-12256-20221030T051532.zip](https://github.com/smeighan/xLights/files/9895592/xLights_dbgrpt-12256-20221030T051532.zip)

**Comment by keithsw1111** [comment]
This is I believe already fixed in the nightly builds.
