### ISSUE TITLE
Polyline Model Not Honoring Individual Segments Setting

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#3511]
I was having issues launching 2022.21.1 from the Mac App Store.  Initial launch would run, but subsequent attempts would just hang at the splash screen.  Version 22.2 from Dan seems to have fixed the launch problem.

On my layout the Polyline model has drastically changed now, and I'm assuming this has to deal with recent code check ins.  The appearance and individual segment settings don't seem to be honored any longer from pervious versions.  Including my rgbeffects file if needed to dig into the issue.

<img width="1658" alt="Screenshot 2022-10-30 at 10 35 16 AM" src="https://user-images.githubusercontent.com/12144876/198887444-22c9271a-20d9-4925-9bf9-71f80ff53187.png">

 - OS: macOS Ventura 13.0, M1 Max w/32 GB of RAM
 - xLights version 2022.21.2 (From Dan)

[xlights_rgbeffects.xml.zip](https://github.com/smeighan/xLights/files/9896221/xlights_rgbeffects.xml.zip)

**Comment by AzGilrock** [comment]
Do you see how many blue dots there are at the beginning of the model?  That's drawing your first node.  I've fixed an issue where we were not honoring the Lights/Node setting.  You have yours set to 8 so now its actually drawing the 8 lights you told it to.

**Comment by kppankratz** [comment]
Okay, I got it all straightened out once again.
