### ISSUE TITLE
Unable to save RGB or Network file

### ISSUE THREAD

**Issue by Dubbs2022** [smeighan/xLights#3512]
I am having some file structure issues I think and I really want to clean everything up.

**What keeps happening:**
- I created a house outline with 4 different strands (4 different sections of my roofline)
- I created a group called "house outline"
- Every strand works correctly when I run individually. Example, when I run a chase from left to right on each strand I have no problems
- I build a sequence that runs "bars" from left to right for the all group and no problem 
- However, I am building a new sequence and now all of a sudden when I build a "bars" to go left to right not all of the colors are aligned.

I have tried reloading the default layout I used for the sequence when it was working correctly, but getting the "unable to save RGB effects file" or similar message for the network portion.

How can I start fresh with a proper show folder and correct sequence. I think I could be having 2 issues going on here.

FYI- I can't see how to attach photos to this note, but if you email me I am happy to add some pictures to show the bars sequence not working consistently.

**Comment by keithsw1111** [comment]
This is better handled in the xlights zoom room which you can access from the help menu in xlights or from the xlights.org site using the blue button.
