### ISSUE TITLE
Crashes on 2022.20 & 2022.21

### ISSUE THREAD

**Issue by OnlineDynamic** [smeighan/xLights#3513]
On windows with 2022.20 and 2022.21 and experiencing lots of crashes during general use and rendering (more issues on 21)

Here is a link to google drive with some debug zip files:

https://drive.google.com/drive/folders/1cvHBX-wb27c-BKjPdVJxFRvuA4Go5WdJ?usp=share_link

Request access and I will grant

**Comment by bcarriveau** [comment]
Download a nightly build, it's most likley already been sorted out.

**Comment by extremeskillz** [comment]
Same issues on those releases with Linux Appimages. Seems to be crashing on rendering and importing effects from other sequences as well.  
I'm actually stuck as I can't import or render causing crashing. I may go back to .01 for now.

**Comment by extremeskillz** [comment]
Yes, on the Linux Version its still crashing with .22. I reverted back to .5 to get around this for now.

**Comment by cjd** [comment]
Closing off old linux issues - reopen if still occurring
