### ISSUE TITLE
Cant install 

### ISSUE THREAD

**Issue by DannyA34** [smeighan/xLights#3514]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
trying to download the news version but i get this, in the image its ofc on danish but i geuss the codes are enough? it says something like i should try install it again.  or if that doesnt help i should contact you. and it didnt. 

![fejl1](https://user-images.githubusercontent.com/52051272/199018594-54d38034-efc9-4ec2-8093-2f4d9d75fd8a.png)
![fejl2](https://user-images.githubusercontent.com/52051272/199018602-582b2f43-5111-4e03-9d02-033dcd3ff17e.png)

**Comment by AzGilrock** [comment]
Looks like the Visual C++ runtime is not being installed.  Maybe try to install it first manually with this link:
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by DannyA34** [comment]
that worked thanks man!
