### ISSUE TITLE
Mac version scroll wheel operation while hovering over field

### ISSUE THREAD

**Issue by reelpilot** [smeighan/xLights#3518]
**Describe the bug**
On the Mac version of xLights the user cannot hover over a drop down menu or a slider and use the scroll wheel to change the value or selection. This feature does work on the Windows version. 

**To Reproduce**
Hover the mouse over any available drop down menu or slider selection and attempt to move the scroll wheel, the value or selection does not change. One must click the mouse and select the option or drag the slider to the desired position. This is not necessary on the Windows version as the scroll wheel works. See video for how it works on the Windows version. 
https://youtu.be/pGFpeGOlPEc

**Expected behavior**
Have Mac version work the same as the Windows version with respect to the hover over scroll wheel functionality.

**Versions (please complete the following information):**
 - OS: Windows 10 & Mac 12.6
 - xLights version 2022.21

**Comment by dkulp** [comment]
The current behavior is the proper behavior for a Mac application.   Drop down lists and such on the Mac to not respond to scroll wheel events.   I don't believe this is something that could be changed.    The scroll wheel is only to be used for scrolling content, not changing selections.

**Comment by reelpilot** [comment]
Thanks for the quick feedback. I used that feature all the time when I used my Windows computer and I found it to be a time saver. I guess I better get used to lots of clicking since the Mac version is overall much better.
