### ISSUE TITLE
Model Selection for Output

### ISSUE THREAD

**Issue by mick1988** [smeighan/xLights#3519]
I'd like to be able to turn on the output for certain models while testing. In my specific case right now, as I'm working on singing faces, I would like to only output to the singing faces to see how they look on the actual props and then tweak from there. 

One solution to my current use case would be to start a new sequence with only the singing props, get them looking just right with the output turned on so I can see it on the prop, then I could export or copy/paste the effects to the main sequence.

But it would be nice to have a selector similar to the testing output selector that would apply to the output toggle as well. Then you could output just certain universes or select just certain props.

**Comment by computergeek1507** [comment]
I started working on this for singing faces last week but I haven't finished it yet.

**Comment by mick1988** [comment]
Well that's good news! I'll patiently wait until it gets implemented. Thanks!

**Comment by keithsw1111** [comment]
Done for states and faces ... I still need to do submodels but the code will be quite similar.
