### ISSUE TITLE
Advatek MKII+ - cant upload to controller - perhaps a new controller?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3520]
From the Zoom room. Cant upload to the advatek.
DarylC was going to see if he can hack the controllers file in the mean time.
Attached log file shows a unable to connect to http://x.x.x.x/ver message.

![image](https://user-images.githubusercontent.com/4643499/199627140-e6cbe2d1-7596-4806-83ca-59b2ab820efc.png)
[xLightsProblem Advatek MKII Plus.zip](https://github.com/smeighan/xLights/files/9924951/xLightsProblem.Advatek.MKII.Plus.zip)

**Comment by keithsw1111** [comment]
I need a log after you try to upload with the controller configured as a MK II ... the MK3 is a very different controller.

**Comment by derwin12** [comment]
I believe Travis and or darylc know this person and perhaps can reach out to him.

**Comment by Jasonaustralia** [comment]
not sure what you need keith

**Comment by keithsw1111** [comment]
Email you how? I dont think I know your email address.

**Comment by Jasonaustralia** [comment]
It’s ***@***.*** 
0409865301

**Comment by keithsw1111** [comment]
Is this still happening?

**Comment by Jasonaustralia** [comment]
Hey mate , no seems to have fixed it self, i installed xlights on my wife’s comp , and hers worked, so I uninstalled mine and re installed , fixed it all up 
    	Get Outlook for iOS
    
  

 From: Keith Westley ***@***.***>Sent: Sunday, May 7, 2023 2:36 pmTo: smeighan/xLights ***@***.***>Cc: Jasonaustralia ***@***.***>; Comment ***@***.***>Subject: Re: [smeighan/xLights] Advatek MKII+ - cant upload to controller - perhaps a new controller? (Issue #3520) 
Is this still happening?
