### ISSUE TITLE
Compling xLights Master under Windows Debug .. failing .. am I missing something?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3523]
I can get it to compile in release mode but not in debug mode.

![image](https://user-images.githubusercontent.com/4643499/199798052-df9c6409-7b1b-4583-99ec-4df0c6b70e90.png)

**Comment by keithsw1111** [comment]
Would need to see the ControllerEthernet::Ping stack frame to see where it is crashing. Or package logs.

**Comment by bcarriveau** [comment]
@derwin12 i tried as well and failed somewhere else but it appears call stack for vsc2022 pro on windows 10 is now gone and i have no idea to get it back, I ran the script to clone and build for WXwidgets and the build finishes now.

**Comment by derwin12** [comment]
Could this be the 0 channel FPP Player Only controller? I have removed it .. then was able to do the debug.
I added it back and get the above. It never gets to a full running state.
[twofiles.zip](https://github.com/smeighan/xLights/files/9932519/twofiles.zip)

**Comment by derwin12** [comment]
Here is the package logs *from* my normal xlights not via the VS debugger etc..
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/9932547/xLightsProblem.zip)

**Comment by AzGilrock** [comment]
Yeah that error its hitting is marked as a debug only error so it just skips it during Release mode.

**Comment by derwin12** [comment]
Thanks .. GIl .. I just realized that in Release mode, it does start up (bypassing this code check) but once I hit that Show Player in controller page it freezes. So this is looking like the new code for the show player. Passing back to Keith to take a peek.

**Comment by bcarriveau** [comment]
i added a show player, and it builds in debug mode for me

**Comment by derwin12** [comment]
Git user error .. I didnt pull in the latest master that I thought I was doing. Thanks Keith.
