### ISSUE TITLE
Lines top and bottom of a picture effect

### ISSUE THREAD

**Issue by ebuechner** [smeighan/xLights#3524]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I have a face effect that I overlay with a picture effect with the picture effect set to scale to fit to get eye movement.
This method worked fine until recent builds I'm currently on the latest nightly build.
If I use a gif file I get a pink line top and bottom if I use a png file I get lines.

**To Reproduce**
See attached sequence to reproduce

**Expected behavior**
See the eye movement and not be able to see the lines on the top and bottom where the picture effect lays over the top of the face effect.

**Screenshots**

**Versions (please complete the following information):**
 Windows 10 running the latest updates on Ryzen 9 processor and AMD video card.

**Additional context**

**Attachments**
https://drive.google.com/file/d/1jvGpnLbEDan71WLrxH6dVA8kB8EekfAV/view?usp=drivesdk

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
This is down to a bug in image scaling in the windows version of wxWidgets.

**Comment by ebuechner** [comment]
Is there a workaround? If WXwidgets is the problem and not Xlights I'm assuming going back in versions of Xlights won't help.

**Comment by dkulp** [comment]
It's technically a bug in visual studio 22. Older VS versions and debug builds are fine.  We may want to try turning down the optimizer level for the release wxwidgets build.

**Comment by ebuechner** [comment]
So I tried .22 and I'm still seeing the same issue.
I also noticed that images aren't as sharp on the newer versions of Xlights. For instance a face effect on .5 versus .22 . If this was simply an issue on house preview and model preview I wouldn't be that concerned but this is affecting the fsaq file.

**Comment by ebuechner** [comment]
I'm running the latest nightly build and the picture effect seems to be working after Keith's ci#1390 Commit.
