### ISSUE TITLE
Xlights 2022 21 show overlapping in layout while xlights 2022 20 didn't

### ISSUE THREAD

**Issue by NIcozozo57** [smeighan/xLights#3526]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to layout, tick "overlap check enabled"
2. Click on each models one by one, and some of them show overlapping
3. close xlights
4. install xlights 2022 20
5. go to layout, tick "overlap check enabled"
6. click on each models, no overlapping detected

**Expected behavior**
why is 2022 21 showing overlaping without any changes

**Screenshots**

**Versions (please complete the following information):**
 - OS: windows 10
 - xLights version 2022 20 / 2022 21

as you can see on the  screenshot, 
xlights 2022 20 show the start channels as expected
#31:1
#60:1

xlights 2022 21 show incorrect start channels
#31:169
#60:7

**Additional context**
![bad](https://user-images.githubusercontent.com/78501931/200133404-e3a9f644-c759-42dc-ab82-e596213ea440.png)

![good](https://user-images.githubusercontent.com/78501931/200133194-6f50796e-8d0d-4dbb-ad78-1eb24ccfe801.png)

**Comment by bcarriveau** [comment]
should share your layout, tools package logs.

**Comment by computergeek1507** [comment]
I believe Gil already fixed this, it is related to lights per node in the poly line model. You can download the nightly for the fix or in your polylines set the lights to node to 1.

**Comment by AzGilrock** [comment]
Yep it’s fixed and ready for next release.  You can just set lights per node back to 1 to fix the channels in 2022.21  set it back to 3 if you want when next release comes out.
