### ISSUE TITLE
Crash with Twinkly Lights

### ISSUE THREAD

**Issue by RiverRaid** [smeighan/xLights#3528]
Xlights immediately crahses on this issue, so I am not able to add a logfile, sorry

I tried to integrate my twinkly 750 WRGB-LED in Xlights.  As soon as i try to add an effect on the Twinkly Prop (Custom Model, created via Model Data => Import from Controller) Xlight crashes without warning. I guess, it has to to something with the calculation of the start channels? 

![Prop](https://user-images.githubusercontent.com/4259790/200197381-15104a53-bfe4-4109-bbc9-2d53f47fe105.png)
![Controller](https://user-images.githubusercontent.com/4259790/200197382-673bb2c5-9196-4a24-835f-95990850098b.png)

**Comment by keithsw1111** [comment]
There is a fix that may help in the next version.

**Comment by RiverRaid** [comment]
@keithsw1111 
Thank you, works like a charm :)
