### ISSUE TITLE
Xlights not finishing a render all on a sequence

### ISSUE THREAD

**Issue by broomy111** [smeighan/xLights#3529]
**Describe the bug**
When rendering all on a specific sequence, the lower left corner it stops at Done Rendering "Group- Roof Group" and wont ever finish.  I can render other sequences and don't seem to have the issue.  I upgraded to 2022-21 and same issue for this sequence.

**To Reproduce**
The sequence was from last year and this was the first launch of it, the message in the left lower corner was in red and said I needed to do a render all.  I clicked render all and it stops and never finishes.  I have to end task to get out of Xlights.

**Expected behavior**
Testing other sequences and they finish rendering fine, appears to be this one sequence.

**Versions (please complete the following information):**
 - OS: Windows 11 Pro 22H2- 22621.674
 - xLights version 2022-21

I will send the link with the sequence and logs, on  request.

Thank you

Kevin

**Comment by derwin12** [comment]
After the proglem..go to package logs and upload that zip here for review.

**Comment by broomy111** [comment]
Hi Daryl,

Here are the logs and the sequence.  Looks like this is happening with two
sequences from last year.   Other old sequences render fine.  Let me know
if you need additional info.  Thank you

https://www.dropbox.com/sh/owhdqnlvhgu59wv/AADprvXQrDfg_z1nxNB0lLnPa?dl=0

**Comment by derwin12** [comment]
I am not a developer .. but I see this in your log:
```
2022-11-06 17:32:39,163 18708 log_base [DEBUG] ShaderEffect::programIdForShaderCode() - fragment shader C:\Users\Broomy111\Dropbox\Xlights\RGB\2020\Christmas\Shaders\Creation by Silexars.fs compiled successfully
2022-11-06 17:32:39,181 18708 log_opengl [ERROR] shader-compile failure: '0(85) : error C0000: syntax error, unexpected $undefined at token "<undefined>"
```
Can you find another source for that shader? Or try removing that effect from your sequence?

**Comment by broomy111** [comment]
Thank you Dan!  So do I need to delete that shader file and download it
again?

Thanks again for all you and the other developers help
