### ISSUE TITLE
Select Effects Window -- can cursor keys be enabled in that window to scroll up n down?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3532]
Mouse click into the window, can the up n down cursor keys be enabled so one can scroll thru the choices and validate values?

![image](https://user-images.githubusercontent.com/4643499/200341587-eeabd4bb-b38a-40c9-9e30-ffb7ddbb0791.png)

**Comment by computergeek1507** [comment]
I am unsure what you mean by "validate values"? I am assuming you want the arrow keys to move the selection and highlight the effort on the timeline?

**Comment by derwin12** [comment]
In my case I have bad file names in shaders .. if I could just arrow down I can quickly find them in red :-)
(rather then back n forth with check sequence)
