### ISSUE TITLE
One pixel lighting only on ver. 22

### ISSUE THREAD

**Issue by AG1967** [smeighan/xLights#3536]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When sequencing my Tune To sign has the first pixel on the top left light up whenever my "Bedroom Window" lights up.  As best as I can tell, this is the only time it does this.  I was not able to run ver. 21 so I downgraded back to ver. 20 after ver. 21 was released.  I downloaded and ran ver. 22 today and noticed this when I opened up the sequence.  So I decided to go back to 20 to see if it was doing it that I hadn't noticed and it was not.  Then I upgraded to 22 again and it is lighting up this pixel.  I have attached the packaged sequence and screenshots as well.

![image](https://user-images.githubusercontent.com/117701682/200465764-14f5fbda-d5a4-4582-b966-bd46efe8978b.png)
![image](https://user-images.githubusercontent.com/117701682/200466024-0248de40-9d2f-4150-b450-b8f9f7fe8b50.png)

[Carol of the Bells (Dubstep).zip](https://github.com/smeighan/xLights/files/9957300/Carol.of.the.Bells.Dubstep.zip)

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by AzGilrock** [comment]
Can you check whether you have any PolyLine models set with Lights/Node as 3?  If so there was another bug I missed.  Set it back to 1 for now till we fix it.

**Comment by AG1967** [comment]
That worked.  Will this just be fixed on the next update?

**Comment by AzGilrock** [comment]
We try to close the issue when we check in code we think has fixed it.  I'd like to fix it before next release.  I don't usually know when the releases are coming out and last night I lost the ability to debug on the Mac.  First bad experience on the Mac every time I tried to step over a line of code the debugger is crashing.

**Comment by AzGilrock** [comment]
I checked in the fix for this bug.  One of the main reasons I missed seeing this issue is because the channel start and end number in the model list does not get updated when you change the Lights/Node because that parameter was not supposed to affect the channel numbers

**Comment by AG1967** [comment]
Thank you very much.

Thanks,

Aaron Guidry

504-606-9051 (cell)

 
“For I know the plans I have for you, says the Lord, plans for welfare and not for evil, to give you a future and a hope.”-Jeremiah 29:11 

    On Thursday, November 10, 2022 at 09:55:02 AM CST, Gil Jones ***@***.***> wrote:  
 
 


Closed #3536 as completed.
