### ISSUE TITLE
2022.22 Hanging on macOS

### ISSUE THREAD

**Issue by kentstroker** [smeighan/xLights#3537]
The macOS version has been hanging during routine operations requiring a force quit to recover. Most typically when opening a new sequence. This behavior has been observed since 2022.21. I am running on a new Apple MacBook M1 Max and the Ventura operating system. Since this is not crashing, just presenting the spinning beach ball of death, I am unsure what I can provide to assist with the investigation; please advise.

**Comment by kentstroker** [comment]
On some advice from Zoom Room, I turned off the render cache and emptied the directory holding the renderings. Seems to have corrected the issue. Will report back if I get a hang state event.

**Comment by thekev** [comment]
Try a nightly build? https://github.com/smeighan/xLights/commit/d1401f9b3a983cb894576a8ea1ebfc6908a0bb9c

**Comment by carldanley** [comment]
> On some advice from Zoom Room, I turned off the render cache and emptied the directory holding the renderings.

This also fixed my issue as well.
