### ISSUE TITLE
Crash in 4.2.6

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#354]
While having the preview screen open, having highlighted 11 effects on the grid, holding shift, and dragging the effects to the proper location, XL 4.2.6 crashed.  I was not able to duplicate it, but do have the crash report.

**Comment by AzGilrock** [comment]
If you can get me the crash report I'll look but usually I will need to reproduce the issue to figure out how to fix it.

**Comment by Clyde-L** [comment]
Gil  Sorry I didn't reply sooner.  Been working this whole weekend.  For the life of me, I can't figure out how to upload the file to github???  But here is a link to it in my dropbox

https://www.dropbox.com/s/b5rhlqq63yiwr9c/xLights_dbgrpt-2656-20150901T190658.zip?dl=0

**Comment by Clyde-L** [comment]
And how do you upload the bug reports to github?

**Comment by AzGilrock** [comment]
I don't think you can.  They can be attached on Facebook or the xLights forum posts.  I forgot to look at this yet.  If nothing is obvious in the backtrace we might have to wait till its reproducible.

**Comment by Clyde-L** [comment]
Ok, sounds good.  Thanks for looking into it.  Crashing is not so much of a problem for me.  But, when it happens, it's usually because I'm trying to do like 10 things at once.

**Comment by stevegiron** [comment]
Does this still happen with 4.2.9 ?

**Comment by Clyde-L** [comment]
Updating now to 4.2.9

**Comment by stevegiron** [comment]
Is this a duplicate of #365 ?

**Comment by Clyde-L** [comment]
This has not happened again in 4.2.9... Moved on to 4.2.10
