### ISSUE TITLE
XLATW - Import from Zip misses .svg files used in the new shape effect change

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3545]
Seen with the XLATW sequence from Mark Butcher he has shape effects with the new svg file feature. When importing from the zip it doesn't remap them like it does for avi/jpg/png etc.

The files are flagged (of course) on a reopen of the sequence as a missing asset.

    ERR: Shape effect cant find SVG file '/Users/jordennash/Desktop/xLights/2212 XAtW/xLights/Downloads/Light of Christmas/Mark Butcher - Vivid Sequences/Media/Light Of Christmas/Images/AngelRed.svg'. Model 'Matrix - 1L', Start 2:21.400

    ERR: Shape effect cant find SVG file '/Users/jordennash/Desktop/xLights/2212 XAtW/xLights/Downloads/Light of Christmas/Mark Butcher - Vivid Sequences/Media/Light Of Christmas/Images/AngelRed.svg'. Model 'Matrix - 1L', Start 2:36.850
    ERR: Shape effect cant find SVG file '/Users/jordennash/Desktop/xLights/2212 XAtW/xLights/Downloads/Light of Christmas/Mark Butcher - Vivid Sequences/Media/Light Of Christmas/Images/AngelRed.svg'. Model 'Matrix - 2R', Start 2:21.400

    ERR: Shape effect cant find SVG file '/Users/jordennash/Desktop/xLights/2212 XAtW/xLights/Downloads/Light of Christmas/Mark Butcher - Vivid Sequences/Media/Light Of Christmas/Images/AngelRed.svg'. Model 'Matrix - 2R', Start 2:36.850

[Light Of Christmas 3-Mark Butcher.zip](https://github.com/smeighan/xLights/files/9975139/Light.Of.Christmas.3-Mark.Butcher.zip)

**Comment by computergeek1507** [comment]
Does it copy the files to the "Picture Directory" set in the Import Dialog?

**Comment by computergeek1507** [comment]
fixed with fd7add3fade4926968b065f80b64b90b26b77121
