### ISSUE TITLE
Ability to set pixel direction per string

### ISSUE THREAD

**Issue by lorajoslyn** [smeighan/xLights#3547]
I currently have several of my larger elements that have both 1-chip and 2-chip bulbs (not ideal but that's the reality). 

With the visualization option, I currently have to upload the controller information from xlights and then manually re-enter the pixel direction on the controller screens for the few ports that do not match. 

It would be great if I could do this in xlights instead so it would retain that information.

**Comment by keithsw1111** [comment]
These scenarios are not meant to be dealt with by the visualiser. They need to be manually set up.
