### ISSUE TITLE
Ability to re-arrange ports for multi-strand elements in visualizer

### ISSUE THREAD

**Issue by lorajoslyn** [smeighan/xLights#3548]
My current mega tree is 18 strands.  I currently have them evenly spaced out on the board to help with loads (I don't use power injection).  When I pull the mega tree into the visualization, it pulls in all 18 strands together.  

Right now, I have to leave that in Xlights as-is, then after uploading I need to manually move the ports to the correct location on the controller screens. 

I also have some boards with ports that are non-functional.  This feature would also help if I needed to skip a port.  

I would assume elements would come in like they are right now, but have some manual method in visualization to split.

**Comment by bcarriveau** [comment]
Just set it up manually and keep the controller at the top of your controllers tab to avoid channel issues with other controllers using auto layout. That is not a normal scenario in my option. The visualizer with auto laypit is to make things easy for auto channel assignment not butcher a mega tree config lol.

(Deposited $0.02)

**Comment by keithsw1111** [comment]
We support this by allowing you to manually configure the controller and the models. Adding all sorts of weird and wonderful options (especially uncommon ones) overly complicates an already very complex section of the code and creates ongoing maintenance issues.

**Comment by AzGilrock** [comment]
Actually I find it quite normal to not just pack all the outputs in order on a controller.  For instance I have controller boxes I've built where I don't even have the even numbered outputs wired up and I also do load balancing between the 2 power supplies in some of my boxes.  As long as you don't check the Full Auto button everything seems to work find you just drag the models around to whatever port you have them on.

**Comment by AzGilrock** [comment]
Yeah I wasn’t really talking about your exact scenario.  I realized it was your strands not being separated after I posted..  I’ve had ports go bad as well and had to fix it in the controller
