### ISSUE TITLE
Crashes when rendering video files

### ISSUE THREAD

**Issue by Docbrew** [smeighan/xLights#3554]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When rendering a sequence with video files (.mov, and some .mp4) xlights crashes.

**To Reproduce**
Render any sequence with a .mov file in it.

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2022.18, 19, 21, 22

**Additional context**
I've also tried rendering the same sequences on my Dell laptop and it reproduces the same crash with the same error.

Snip it from crash report:  2022-11-12 10:02:25,900 16428 log_base [DEBUG] Job pool new size 39.
2022-11-12 10:02:27,633 18376 log_base [ERROR] ---------- WHVD: Failed to set media type : 0xc00d5212 : MF_E_TOPO_CODEC_NOT_FOUND
2022-11-12 10:02:27,633 18376 log_base [CRIT] Crashed: Fatal exception occurred.
2022-11-12 10:02:28,554 18376 log_base [DEBUG] Loading map file C:\Program Files\xLights 2022_22\xLights.map
2022-11-12 10:02:28,554 18376 log_base [DEBUG] Base module handle: 0x00007ff724840000
2022-11-12 10:02:28,554 18376 log_base [DEBUG]     File open.
2022-11-12 10:02:29,743 18376 log_base [DEBUG]     Map file loaded.
2022-11-12 10:02:30,255 18376 log_base [CRIT] xLights version 2022.22 64bit

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
[xLights_dbgrpt-5692-20221112T100227.zip](https://github.com/smeighan/xLights/files/9995375/xLights_dbgrpt-5692-20221112T100227.zip)

**Comment by derwin12** [comment]
Perhaps attach the video that is crashing it? Can you tell which one it is?
And be sure hardware decoding is NOT checked in the preferences section.

**Comment by Docbrew** [comment]
Turning off hardware decoding seems to have helped this a lot.
