### ISSUE TITLE
Sketch Effect - background image not in a packaged zip.

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3559]
Not clear if this is a bug or a feature request.. but if you use a background image to build a sketch effect, that image is not included in the zip package nor is it obviously remapped on an import. Now perhaps it is not required - since the pixel points are already defined. Including this file makes it easier to ensure you have a complete picture of the sequence's assets.

![image](https://user-images.githubusercontent.com/4643499/201571530-9f58f8f6-4228-4c5c-a8e1-816a595eab26.png)

[SketchEffect.zip](https://github.com/smeighan/xLights/files/9999329/SketchEffect.zip)

![image](https://user-images.githubusercontent.com/4643499/201571787-f8a52fc0-936d-4172-891a-de5db6e36cff.png)

**Comment by KMojek** [comment]
I should probably fix this since I added the sketch effect. The image is just for reference though. It's not needed at all for rendering the effect so not having it isn't breaking anything with sharing sequences. I agree it should be in the zip though.
