### ISSUE TITLE
Custom model submodels not getting added to groups if substrings match

### ISSUE THREAD

**Issue by merryoncherry** [smeighan/xLights#3560]
**Describe the bug**
When importing a custom model, submodels do not get merged into target groups properly if the target groups already contained models with names that are substrings of the newly-imported model names.

**To Reproduce**
Import this model first:
https://raw.githubusercontent.com/merryoncherry/merryoncherry/main/PixelTrim/Tree.xmodel

Then import this one:
https://raw.githubusercontent.com/merryoncherry/merryoncherry/main/PixelTrim/XmasArchTopPixelTrim.xmodel

When prompted, choose to merge into existing groups.

The submodels of the second model don't get added to groups properly.

**Expected behavior**
The submodels should be put in the same groups that they would if you were to import into new groups, or empty groups.

**Screenshots**
N/A

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: 2022.22 from source

**Additional context**
This appears to be an issue in ModelManager.cpp around line 426, where it uses a substring search on a comma-delimited list, and manages to match a substring.  PR inbound that fixes this, but perhaps there is a better utility for doing the match than the one I threw together real quick.

**Attachments**

**Comment by keithsw1111** [comment]
So was this fixed by your pull request?
