### ISSUE TITLE
Color Display Element Names

### ISSUE THREAD

**Issue by PeteTeller** [smeighan/xLights#3562]
My display elements list has gotten so long it's difficult to quickly identify categories of elements (HD Props or a particular prop and all its submodel groups, for example)

**Describe the solution you'd like**
I'd like to be able to assign colors to the text, background, or both of the display elements in the sequencer so I can quickly identify where similar elements are listed

**Describe alternatives you've considered**
I use groups of groups to approximate a collapsible list tree, but the groups still get lost in the clutter

**Additional context**
NA
![Sample](https://user-images.githubusercontent.com/76636447/201730236-ef1e42b2-faa7-4034-aaee-94878ed0a586.jpg)

**Comment by derwin12** [comment]
That is done with the tag color property
Set it here:
![image](https://user-images.githubusercontent.com/4643499/201802424-4ed2f35b-9fff-45ba-b14b-66e673f69f9a.png)
See it here:
![image](https://user-images.githubusercontent.com/4643499/201802399-e4948ae2-04d9-4e3c-9ebc-ad91f4568071.png)

**Comment by PeteTeller** [comment]
Thanks!

**Comment by PeteTeller** [comment]
That works for individual models...any chance we can get a similar tag for
groups?

**Comment by PeteTeller** [comment]
Disregard, I see it now..
