### ISSUE TITLE
Extend the fan radius values...

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3564]
As seen in zoom .. having the fan effect and wished to have it to the far right (or left) the max value of 500 for the radius2 wasnt large enough to cover the entire roof model. Tried oversize buffer but it didnt seem to make a difference. Is there another workaround or can the max value be increased?
![image](https://user-images.githubusercontent.com/4643499/201801732-6fa52e7c-6815-4ad5-a3db-6eccb7ddaf02.png)

**Comment by AzGilrock** [comment]
We've increased it a couple times.  The sad thing is now that its so big its rendered the slider fairly useless for dialing in smaller numbers...might as well just be a text box.  We normally would have done things in percentages in xLights but I was trying to match SuperStar functionality.
