### ISSUE TITLE
Twin Rays.fs Shader Rendering Issue on latest AMD Radeon Vega 8 Drivers Win10 64bit

### ISSUE THREAD

**Issue by cmichaelhansen** [smeighan/xLights#3566]
**Description**
Noticed that Twin Rays.fs shader file renders the swapped color palette, black is blue, purple is yellow, etc. Issue just started appearing on sequences that previously worked without any issue. After trying older versions of XLights, and then finally downgrading my video card drivers to a previous release, that finally fixed the issue.

**To Reproduce**
With the latest versions of XLights + AMD Radeon drivers (and appropriate hardware), just create a shader effect with Twin Rays.fs.

System Requirements *Known Good State*
![image](https://user-images.githubusercontent.com/1878012/201830548-5349205d-abda-4187-83da-da4b339ac6b6.png)

Driver that causes the issue: 22.10.3

**Expected behavior**
Twin Rays, should render correctly as it does from the website. Note: While using the latest AMD drivers, I had no issue seeing the proper colors. The issue only presented itself in XLights, and only with this particular shader. Lazy Rays which is basically the same shader, worked without problem.

**Additional context**
As this is sort of a particular case to my hardware/video card drivers, I'd be happy to help debug the issue.

**Comment by keithsw1111** [comment]
Sounds like a bug in your video card drivers. You should likely contact AMD.

**Comment by AzGilrock** [comment]
Yeah it doesn't sound like you ever tested the latest version of xLights with the older video driver that works.  Don't change 2 things.

**Comment by cmichaelhansen** [comment]
Currently I'm using the latest build of XLights 2022.22, while I had previously reverted back to an older version and then the older AMD drivers, I did then update to the latest XLights to make sure only one thing had been modified.

I agree that the culprit seems like the drivers, especially since that is what changed. However, there are a couple of things that should be noted.

1.) https://editor.isf.video/shaders/5e7a80297c113618206debee
 Renders with the proper colors using new or old AMD Drivers.

2.) While I didn't have a chance to test all of the other possible shaders, I have many used in my sequences and out of the 20 or so that are widely used, Twin Rays was the only one affected. 

3.) I went into the settings in XLights and changed the OpenGL from Auto to 3.x and restarted. However, after every restart, it only showed 1.x/2.x, even after agreeing to sending logs dialog box that was prompted for the OpenGL setting change.
![image](https://user-images.githubusercontent.com/1878012/202088144-b0c99d19-aba7-42ad-971a-dc9bf4f59122.png)


4.) Running Check Sequence, while the OpenGL was stuck on1.x/2.x, gave me a single ERR regarding a shader requiring OpenGL 3.0. 
"ERR: Sequence has one or more shader effects but open GL version is lower than version 3 (1). These effects will not render."
This didn't actually prevent anything from rendering in the sequence.

The last issue leads me to believe that maybe there is a weird issue determining how best to render that particular shader. This would explain why one is affected while the others are not. It doesn't explain why older AMD drivers would work in one case and not the other. Could be a red herring but thought I would mention it.

I know this is a bit of an outside issue and probably extremely hard to nail down unless you have a system to try it on with the same drivers. I'd be happy help run a build and report the results. Thanks for all the hard work on the program!

**Comment by AzGilrock** [comment]
If the old driver works why fight it.  What do you need from the new driver?  I once had an nVidia driver that completely broke 3DArcade and neither side was interested in fixing it so what do I do.  I run the older driver that works.

**Comment by dkulp** [comment]
This is a likely bug in the shader.   It doesn't render anything at all on the Mac.   The problem is that the color vec3 is not initialized which can result in a random "starting color".   If you change line 110 to read:

```
vec3 color = vec3(0, 0, 0);
```

then it may work better.   No idea if there is a way to log a bug against the shaders.

**Comment by cmichaelhansen** [comment]
> This is a likely bug in the shader. It doesn't render anything at all on the Mac. The problem is that the color vec3 is not initialized which can result in a random "starting color". If you change line 110 to read:

That is interesting behavior. Originally I brought this up to Tom of Magical Light Shows as he uses this shader quite a bit and I believe he's on a Mac. He'd not run across it the issue.

> 
> ```
> vec3 color = vec3(0, 0, 0);
> ```
> 
> then it may work better. No idea if there is a way to log a bug against the shaders.

That's a good thing to try. I'll create a second version of the shader with the update to line 110, then run some tests on AMD drivers + a simple sequence with both shaders to see when it breaks and if there are any other clues. I'll have some time this weekend to give it a go.

**Comment by AzGilrock** [comment]
Any idea if Tom is using an Intel based Mac or a new M1 chip Mac?

**Comment by cmichaelhansen** [comment]
> Any idea if Tom is using an Intel based Mac or a new M1 chip Mac?

I asked Tom and he mentioned that he using both Intel based Macs and i7 laptops.

**Comment by cmichaelhansen** [comment]
After reverting and trying all of the update packages in line, there seems to be no longer an issue with the shader rendering on the incorrect color palette. If it crops up again, I'll give try modifying the declaration line of that vec3 for color to be initialized properly. Otherwise probably safe to close this out. Thanks for the help!
