### ISSUE TITLE
.23 - change string count custom models - changes size of model - very small

### ISSUE THREAD

**Issue by jefft0825** [smeighan/xLights#3573]
If you change the string count in .23 on a custom model - it will resize the model to something that is impossible to see - it shrinks it down to just the 4 blue square corners.     

You can drag and make it bigger but if you try and resize to the same size as another prop, it reverts back to being very small

**Comment by bcarriveau** [comment]
I was having that issue on any model in .22 but thought it was something that got fixed.

**Comment by AzGilrock** [comment]
I just tested and cannot reproduce this

**Comment by AzGilrock** [comment]
I thought maybe it could be Windows only but I cannot download the Windows version 23.  The link doesn't work when I select to download the new version.

**Comment by jefft0825** [comment]
I was able to download .23 for windows from the download page on xlights.org  

Attached a sample layout - it was fine in 22 for me - if you change the string count to anything other than what it is, it shrinks it

[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/10042297/xlights_rgbeffects.zip)

**Comment by AzGilrock** [comment]
I went to the download page also.
<img width="1030" alt="Screenshot 2022-11-18 at 12 49 40 PM" src="https://user-images.githubusercontent.com/2024669/202790131-34e583ca-53bc-4da3-a8cf-cd16552c8c9a.png">

**Comment by keithsw1111** [comment]
I have reposted 23 with a recompile of wxWidgets which I believe fixes these issues. You will need to restore a backup of the rgbeffects file.
