### ISSUE TITLE
Latest Release 2022.23 - Invalid characters in Height box

### ISSUE THREAD

**Issue by deanathpc** [smeighan/xLights#3576]
Installed the latest release.  Under the layout tab I was attempting to get my channels laid out correctly.  With PolyLine elements the Height box has invalid characters in it which makes the entire layout tiny.  Too tiny to recreate.  Restored from a backup and the layout showed again.  Until I go to change the PolyLine elements.  Same thing happens.

Restored to v2022.22 and all is well.  No garbled characters in the Height box.

**Comment by bcarriveau** [comment]
Did you install the .23 scott put up last night under the releases here on github? I just installed that .23 and i do not see this problem. I think the early .23 in the day yesterday was broken.

**Comment by keithsw1111** [comment]
I have reposted 23 which should fix this but you will need to restore the rgb effects file from a backup.

**Comment by deanathpc** [comment]
I run on windows at this time.  I don't build from source code but installed the the exe packages.  I'll wait for the next release I guess.

**Comment by AzGilrock** [comment]
Keith said he posted the release an hour before you said you would wait for it.
