### ISSUE TITLE
Update (F5) does not work

### ISSUE THREAD

**Issue by ikke1981** [smeighan/xLights#358]
Hi,
I guess i found a bug. The update (F5) button in the effect settings tab does not work.
Since 4.2.7 i have to update all my Marquee effects in my sequences. 
When i click on the effect in the timeline, and i hit F5, it doesn't do anything. I have to manually hit the Update button.
I did a clean install. Win8.1
I hope it was helpfull.
Dennis.

**Comment by AzGilrock** [comment]
Yeah I don't think the F5 key was ever connected for version 4 and I'm not sure we want to add it now.  The goal is to get rid of the Update button.  I'm not sure it's needed anymore.  You should be able to accomplish the same thing by making any tweak at all to the effect and that would cause it to update the settings same as that button does.

**Comment by ikke1981** [comment]
Ok, i never used it before in v4. But I thought it would be easy to "update" an effect after an addition in the settings tab of that effect. Because if you make a change to an effect you like, you have to undo that same change.

**Comment by AzGilrock** [comment]
Well we really want to eliminate the need for the button.  I think the easiest way would be to just remove the button and then you all will let us know whats not working without it.

**Comment by ikke1981** [comment]
Thanks for all the effort you all put in to Xlights/Nutcracker. 
Keep up the good work.

**Comment by gerry4** [comment]
Damn ! I went and hit F5 for all the marquee effects too. Was quite pleased that I remembered to do so. Did not realise that it did nothing :)
I am sure I heard Gill say update your Marquee effects after the install. Guess I misunderstood.

**Comment by AzGilrock** [comment]
I guess I should remove the "F5" from the button...lol.  I did say that and meant press the button like I do. ;)

**Comment by stevegiron** [comment]
Is this really a bug? Is it an issue that needs to be open? Can it be closed?

**Comment by gerry4** [comment]
Hi Steve, I dont know . In the early days of 4.nn , I used to use the F5 (more in hope than anything else) . Did not use it again till Gil said to use it as above for the marquee release change, so not sure if it does anything or not (or is meant to do or not ) . The manual is suitably silent on this point :)

**Comment by ikke1981** [comment]
Hi all,
For me it can be closed. Now I know it can't be used, and the F5 is doomed to disappear, it's not really a bug anymore...
