### ISSUE TITLE
Visualizer Glitch 2022.23

### ISSUE THREAD

**Issue by MovieDad** [smeighan/xLights#3580]
When moving props in visualizer, all prop positions reset to a single point in the 3D layout window overlapping each other, switching to 2D still same issue, also noticing chinese/wingding characters showing in gama setting on all props after the issue occurs. eg gamma set to 2.3 shows 2.3%!@ 3 random characters added. Rolling back to 2022.22 resolves issues, I am able to use visualizer and move props to different ports. using 2 kulp contollers and 1 rasp pi for matrix.

**Comment by AzGilrock** [comment]
Have you redownloaded the release?  You’re describing the bug that everyone already reported which caused the release file to get pulled and reposted later
