### ISSUE TITLE
2022-22  Anytime I try to use File Close Sequence xlights hangs

### ISSUE THREAD

**Issue by jnealand** [smeighan/xLights#3581]
I have had this happen with multiple sequences so I do not believe it is sequence related.  I have been tweaking a bunch of sequences to add a new prop.  After the update, render all, and save I play to my computer screen, then do a File export to video.  After completion I do a File sequence close and xlight hangs (stays in an hourglass condition) forever.  I have waited over 10 minutes and just end up killing and restarting to do the new sequence.  Has happened on every sequence so far.    Render on save is definitely turned off (unchecked).

I have tried not using the file close and just open another sequence and that seems to work ok.

**Comment by dkulp** [comment]
It's render cache related and would go away if you disable the Render Cache.   However, it's also fixed in .23.

**Comment by jnealand** [comment]
Thanks for the quick response.
