### ISSUE TITLE
Poly Line Drop Pattern

### ISSUE THREAD

**Issue by athompson485** [smeighan/xLights#3586]
**Describe the bug**
When using a poly line for a pixel forest I have always zig zagged a the poly line and used a negative offset to have pole wiring start at the bottom instead of the top. Entering a negative offset now gives an error.

**To Reproduce**
Example, draw a single straight poly line with 50 nodes. Enter an offset of -5. This should result in a sting of pixel poles that are 5 tall and 10 of them. The negative offset should have the first node starting at the bottom. (a positive 5 would have it starting at the top as if it were icicles) However by using the -5 when you open the node layout window under "Node numbers starting with 1 followed by string number:" it says "Error - invalid height" instead of providing you with correct node layout.

**Expected behavior**
Node layout starts at the bottom of each drop instead of the top.

**Screenshots**

![image](https://user-images.githubusercontent.com/53411513/203185630-ad605da2-7749-4737-a6b4-16c230085314.png)
![image](https://user-images.githubusercontent.com/53411513/203185315-6b8134fd-fd7f-46e3-ba1c-6bfefaf95c30.png)
![image](https://user-images.githubusercontent.com/53411513/203185264-b90f4e47-c8a3-4bc5-8fa6-e3aea1bed16c.png)

**Versions (please complete the following information):**
 - OS: Windows 10 Pro
 - xLights version: 2022.23

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by AzGilrock** [comment]
Yeah that was my fault.  I was fixing a bug I found where if a user types "0" for the drop pattern the program would freeze and go nuts.  I completely forgot about negative drop sizes.
