### ISSUE TITLE
Sketch Effect background image reported as a missing asset

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3587]
The recent enhancement has introduced a bug in .23 / nightly. If the background effect is missing, it is flagged as a missing asset upon opening the sequence. You cant change the field to update or remove the file name. In this case I would likely just remove the filename (and did so via editing the xml).

**Comment by keithsw1111** [comment]
I think the bug is you cant remove the background image. You can't have the need to package the file but then say it isnt important in check sequence. So I made it possible to clear the background image file in the UI.
