### ISSUE TITLE
xSchedule Dosent Want to play any sequence  

### ISSUE THREAD

**Issue by Sam3287** [smeighan/xLights#3589]
Issue with xSchedule not wanting to play any sequence it goes three seconds in and stop

https://user-images.githubusercontent.com/105610765/203659951-84c27108-222b-43f6-a7d1-16ffbb2f1a0d.mp4

**Comment by bcarriveau** [comment]
I just tried on windows 10, 2022.23( 2nd version of .23) and it all plays fine for me, maybe try downloading .23 from github if you think possibly you got the broke .23 or even a nightly build?

**Comment by b1ackb3ar** [comment]
Getting the same issue here w/ 2022.23 on Windows 10, but won't even show any time lapsed (0 sec). Attempted the re-download/reinstall from Github.

**Comment by keithsw1111** [comment]
Time not advancing is an audio issue. Check settings and ensure you have the right audio device selected.

**Comment by keithsw1111** [comment]
What do the logs say re your 3 second issue. Would also need to see the schedule definition to see if there is a reason for that.

**Comment by b1ackb3ar** [comment]
> Time not advancing is an audio issue. Check settings and ensure you have the right audio device selected.

Huh, interesting. When the Audio Device is set to "Default" no output, but if I select a specific device from the list, works normally.
