### ISSUE TITLE
Matrix Start Location does Nothing

### ISSUE THREAD

**Issue by mattwells** [smeighan/xLights#3591]
I really do hope that I am doing something dumb here but:

**Describe the bug**
For power reasons I had to mount my pixel matrix upsides down to the default xLights settings. This means I need the start position top right rather than bottom left but changing the setting in xLights does nothing to the phisical matrix.

**To Reproduce**
Create a Pixel Matrix in xLights with the `Starting Location` set to `Top Right`. (mine is 24 tall 48 wide)
Generate a sequence that it is obvious which orientation it is in (mine has text saying `^ Up ^`)
Export the sequence to a player and play it. (I'm using Flacon F16v4 and I used FPP Connect to upload it)

**Expected behavior**
I expect the picture on the pixel matrix to be the correct way around.

**Screenshots**
![image](https://user-images.githubusercontent.com/507858/204062299-6a61a98b-0368-49d6-8db9-8f386603edbe.png)
![IMG_20221125_233832](https://user-images.githubusercontent.com/507858/204063440-724c493b-3da1-45cc-b85a-c88082817bd1.jpg)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2022.23 64bit

**Additional context**
Pixel Output settings on the Flacon F16

![image](https://user-images.githubusercontent.com/507858/204063768-1436536a-221c-4907-9919-a093fd12a949.png)

**Attachments**
Package Sequence: https://drive.google.com/file/d/1xXNth0dhMLPxe_x7TSdLyu58QRUNXhbx/view?usp=share_link

**Comment by merryoncherry** [comment]
I use this feature all the time and it works.
Are you sure you didn't start it at the bottom right?  And did you re-render your sequence after changing the layout?

**Comment by mattwells** [comment]
I believe I have done it correct, I created this Up sequence having discovered this behavour and I am fairly sure that I had the setting in the way it was wired (Top Right). Just to be sure.

* Launch xLights
* Confirmed that `Start Location` is `Top Right` in the layout tab
* Load the `Up` sequence
* Press the `Render All` button and `Save` to ensure.
* Deleted the FSEQ from Flacon (ensure it is definetly being over written)
* Upload the newly rendered FSEQ using FPP Connect

Result is the same.

**Comment by mattwells** [comment]
Confirmed: I am a dumbass thanks for the help merryoncherry, you were quite right about the wiring it bottom right.

What I did is I rendered the sequence multiple times change the setting each time Top Left/Top Right/Bottom Left/Bottom Right and uploaded each one and re-naming it and ran them all back to back. I think I need more beer before I debug hardware problems >.<
