### ISSUE TITLE
2022.23 Gif bug - Renders as silhouette

### ISSUE THREAD

**Issue by BlindsideZero** [smeighan/xLights#3592]
**Describe the bug**
When rendering some GIFs, they are showing as a silhouette now, vs previous builds.

**To Reproduce**
1. Open the attached sequence in 2022.23 and compare to 2022.22, or earlier, for the picture effects between them.

**Expected behavior**
The GIF image should be visible with the layered color behind it.

**Screenshots**
![image](https://user-images.githubusercontent.com/119126301/204100204-5d03b0f9-0dd9-421c-9de3-574707db2d95.png)

![image](https://user-images.githubusercontent.com/119126301/204100165-cad2d493-05c6-4d1f-9679-d62002f4191e.png)

**Versions (please complete the following information):**
 - OS: Windows 10 Home (build 19045.2251)
 - xLights version: 2022.23 64-bit

**Additional context**
No crashes

**Attachments**
[Candy Cane Lane_LONG.zip](https://github.com/smeighan/xLights/files/10096669/Candy.Cane.Lane_LONG.zip)

**Comment by keithsw1111** [comment]
I dont have a fix ... but it is a scaling issue. At scaling 5 it is black.
If i reduce it to 3 it is back in colour. 7 is also colour.

Not sure why.

**Comment by BlindsideZero** [comment]
Thanks.  I'll try playing around more with the adjustments.  I have been only editing this sequence in 2022.22, while reverting back to 2022.23 for all my other sequences due to some of them crashing when closing in the previous version.  

Thank you for the great work you have done with xLights!

**Comment by BlindsideZero** [comment]
I've found a good compromise to the scale to make it work.  It looks like the bug is effecting certain multiples of 5 in the scaling effect of pictures.  If an effect passes through one of those points it will temporarily drop the color, which can be seen on the nutcracker effect in this sequence too.  I basically have to avoid passing through those points.
