### ISSUE TITLE
  Cannot immediately select a model/group in the preview window

### ISSUE THREAD

**Issue by RogueLighting** [smeighan/xLights#3594]
Product version 2022-23.  

When I try to select a string of lights in the preview window, I have to click in the preview window
multiple times before the model is finally highlighted/selected.   How many time I have to click 
depends on how far down the "Models" list the object resides.  Never had this type of issue in 
older versions of the product.

1. Click on Layout tab
2.  In the "Preview" window..   Try to select a segment, string/model etc.
3.  Continue to left click in the preview window until the model/group/segment is selected.

EXAMPLE : 
If there are 5 models (A - E) in the model/group list  
You have model/group B selected in the model/group list,
and you try select model "E" in the preview window, you have
to click anywhere in the preview window 3 times before the model
is finally highlighted in the preview window.

Current work-around is to select the model directly from the "Model/Group" list window.

Thanks

**Comment by RogueLighting** [comment]
Duplicate to which bug guys?

**Comment by AzGilrock** [comment]
It looked like you posted the same issue twice…see #3593

**Comment by RogueLighting** [comment]
Ya.   The first one for some reason contained zero nfo though I put the
same data in that is in the other bug.  And the first one was (in my
opinion) closed prematurely

So I am assuming 3593 and 3954 are the same  now?     Sorry about that
