### ISSUE TITLE
Improper Render with Large Group Mac 2022.23

### ISSUE THREAD

**Issue by TylerNodine93** [smeighan/xLights#3599]
**Describe the bug**
During a Marquee Effect with speed set to zero (what i use for a static look before the show starts) if you use it on a large grouping "whole display" it glitches and flickers on some props. 

**To Reproduce**
1. Apply a marquee effect to a animation sequence on a whole display group
2. Set Band size to 1
3. Skip size 0
4. Thickness 1
5. Stagger 0
6. Speed 0
7. Start Position 0
8. Render and watch the preview it will have some lights flickering and others on solid as expected. 
9. Under layer settings set that to Per Model Single Line

Steps to workaround the behavior: 
1. However if you copy/paste the exact same effect to a smaller group or directly to the effected prop it solved the issue and no longer flickers. 

**Expected behavior**
Would expect a solid on effect with alternating colors based on selected colors to give a classic static look to the display. Would expect it to be solid with no flickering since speed is set to zero and since it works as intended on smaller groupings. 

**Screenshots**
See attached sequences for issue.  There are 2 uploaded one called "Flickering" and one called "Not Flickering" only difference between the 2 is the effect on the Outlines group to overcome the flicker for the time being (aka my work around) 

**Versions (please complete the following information):**
 - OS: macOS Monterey Version 12.5 (21G72)
 - Mac mini (M1, 2020)
 - Chip Apple M1
 - Memory 16 GB
 - xLights version 2022.23

**Additional context**
- Its a simple work around, just figured I'd share maybe it is an easy fix. 
- I did not have this issue a week ago, noticed it after batch rendering my 43 sequences before kicking off the season. But I don't think it's related to batch rendering since i can manually go in and make it do it on any new sequence that has never been run through batch sequencing and being that the Mac app store keeps stuff up to date automatically I'm not sure if it a new issue with .23 and wasn't there on .22 or if you would have to go back to .21 to get back to when it wasn't doing this. (Simple terms it does it in .23 but not sure if it started in .23 or a previous version) 

**Attachments**
Attached Folder Includes everything to see the issue set up as a temporary show folder.
https://drive.google.com/drive/folders/1qLZwWZfmzcNoEq0urFxIoKYs6-Car4E1?usp=sharing

There are 2 sequences included one showing the issue and one showing the work around. If you open the "Flickering" sequence zoom in on the outlines of the roof, specifically the left front eves and you'll see the issue.

**Comment by keithsw1111** [comment]
Check sequence answers this:

Model Groups containing duplicate nodes
    WARN: Model group 'Whole Display (No Matrix or CCR)' contains model 'Horizontal Lines' and model 'Outlines' which contain at least one overlapping node (ch 5010). This may not render as expected.
    WARN: Model group 'Whole Display (No Matrix or CCR)' contains model 'Left Third' and model 'Outlines' which contain at least one overlapping node (ch 35109). This may not render as expected.
