### ISSUE TITLE
Enhancement request - Warning if image is not found

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#360]
For a picture effect (and I guess for the matrix face effect) , if an image that was used previously can no longer be found , no error message is displayed.
The result is that effectively that 'effect' disappears from the sequence if the fseq is recreated.
is it possible at any point e.g. when the sequence is saved (or any other suitable time) , to provide some sort of warning to indicate that this has occurred e.g. 'missing images detected, images have been skipped' ?
This will then prompt the user to either go and correct the picture effects or move the images back to where they were previously depending on the scale of the change.

As a example, I started off with all images in the show directory  (cause I did not know better). Then when it got cluttered , I moved them to an images sub directory. The new sequences after that worked fine. But when I recreated the old sequences, the picture effects had no pictures . Took quite a while to figure out why some would work on the BBB panels and others would not. Still in the process of cleaning up the older sequences. Bound to happen to others closer to show time , especially if folks start using movies and don't set them up ' correctly' at the start.

**Comment by AzGilrock** [comment]
Didn't this all work easier last year when we required you to keep all files in one directory? :)

**Comment by gerry4** [comment]
I don't know. First year using xlights this year !
 
But it is nice being able to have images separately , especially with the P10s and many more images to use, playing movies as picture effects (because ffmpeg will then create many images to be used (even if each movie is only for a chorus) , so that floods the show directory , which is what caused me to move them all out in the first place.
 
I now realise that I should have created the image directory outside the show directory cause next year when I have a 2016 directory, the images will be in the 2015 sub directory, but will cross that bridge next year.
 

Gerard
 
Date: Mon, 7 Sep 2015 06:09:17 -0700

**Comment by keithsw1111** [comment]
Now that check sequence will check and detect this issue can I close it?

**Comment by gerry4** [comment]
Yes pleas and thank you !

Gerard
________________________________
