### ISSUE TITLE
XLights Not Condensing Nodes into Strands

### ISSUE THREAD

**Issue by jataylorSF** [smeighan/xLights#3606]
Hi! When i imported the Holiday Coro Singing Lightbulb face, the strand names did not condense down into 8 strands for me to rename. Instead it is showing all 560 for me to rename which would take forever to do on a 4 face project.

How do I get xlights to recognize this is an 8 strand project?

![image](https://user-images.githubusercontent.com/119538147/204901976-685ae7df-41c8-4462-9776-664aa4d6a931.png)
![image](https://user-images.githubusercontent.com/119538147/204902043-d92362ec-ba0d-478c-9f31-fa121a0db9f9.png)

**Comment by computergeek1507** [comment]
Are you using RGB "smart" pixels, "dumb" pixels or AC lights? If you are using smart pixels the model is correct. If you are using dumb pixels or AC lights you need to edit the custom model to be 8 nodes, then you would use the 8 nodes as your "stands" or channels of the singing face.

**Comment by jataylorSF** [comment]
I'm using regular LED strand lighting. How do i convert it to 8 nodes? When i built the show on Sunday, it condensed the nodes into 8 strands automatically. Now it wants me to name and assign all 560 nodes
