### ISSUE TITLE
Xscheduler Looking for old Contoller IP Address

### ISSUE THREAD

**Issue by nantwichvanny** [smeighan/xLights#3609]
I had cause to change the IP address of my main xlights controller  to neaten up the allocated IP ranges for various devices around the house.
Opening an existing sequence I changed my Falcon F48 IP  address from 192.168.1.250 to 192.168.1.200 within my xLights controller tab and saved it, this was picked up by other sequences when they were opened.

Running xSheduler for the first time it was apparent that the references to the old controller where still there, and that the controller was marked green and 'OK', yet was inaccessible to xSheduler.

It was somewhat confusing since there apparently was no way to change the IP address within xSheduler itself. Ultimately I ran Xlights standalone, that is not initiated from a sequence file, and within the controller tab the IP address was indeed 192.168.1.250. Changing it there and saving solved the problem. Perhaps my misunderstanding of the program but worth mentioning?

**Comment by darylc** [comment]
sounds like your xschedule is point to a different show folder than xlights?

**Comment by nantwichvanny** [comment]
Hi Daryl,
thanks for getting back to me but they are both pointing to the same folder.
Thinking about it, this might be a quirk particular to my own setup and a chance occurrence.
The old address of 192.168.1.250 now belongs to a 24 port switch.
It might be that xScheduler can find a route to the controller through that switch, thereby mistakenly 'thinking' that the controller is at 250 rather than 200 where it is being routed to and shows the controller as being Green and good to go but can't communicate with it..

**Comment by AzGilrock** [comment]
For the record sequences have no knowledge of controllers or IP addresses.  Everything is mapped to models.  The common xlights_rgbeffects.xml and xlights_network.xml contain all the controller info that map models to controllers.
