### ISSUE TITLE
Enhancement: Bring back the color palette functionality

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#361]
![image](https://cloud.githubusercontent.com/assets/10568498/9747532/f87d42be-5632-11e5-8af2-ec90708c2cf0.png)

**Comment by jnealand** [comment]
I vote for this.  Particularly when we are working on a non Christmas Holiday like Halloween

**Comment by keithsw1111** [comment]
Its not the same but you can now select from a set of saved palettes using a simple drop down.
