### ISSUE TITLE
Maximum height and width allowed for background image in layout, please increase

### ISSUE THREAD

**Issue by TripleJ3EB** [smeighan/xLights#3610]
Would appreciate if the maximum allowed setting for height and width was more than 4096.  I am trying to put a 1 mile long drive thru map across a fairgrounds, and I have a large satellite image of the 100 acres it meanders through.

Another related issue I am running into, I have the 800+ custom models already in the system, all with a scale factor of like 3.0, with the 4096 maximum size for the image, i need a scale factor of 0.15.

**Comment by keithsw1111** [comment]
I dont understand your second point.
