### ISSUE TITLE
hidpi scaling bug on Linux

### ISSUE THREAD

**Issue by xxv** [smeighan/xLights#3611]
**Describe the bug**
There's a rendering bug in the sequence view, house preview, and model view widgets on Linux on high-DPI (hidpi) screens. All the other UI elements work fine, but the these widgets show up ½-size in both X and Y (taking up the bottom left ¼ of the available area). The cursor changes according to the correct scaling factor (taking up the whole viewing area), which renders the sequence view unusable as the displayed contents don't match the interactive parts. See the screenshots below:

Sequencer and house preview:
![image](https://user-images.githubusercontent.com/124381/205450245-8ee065e9-4843-41fb-85ea-43f084d9134c.png)

Model view:
![image](https://user-images.githubusercontent.com/124381/205450714-92e97d0d-e19c-42d3-b367-99f7c2437624.png)

**To Reproduce**
Run Linux on a device that has a high-DPI (>96DPI) screen using Gnome. Look at the sequence view or the house preview widgets.

**Expected behavior**
The sequence and house views fill the rendering area.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Debian bookworm/sid (Linux) running Gnome
 - xLights version 2022.24 64 bit / wxWidgets 3.3.0 / using the app image distribution

**Additional context**

This is on a Thinkpad X1 Carbon 6th generation with a 14" 209DPI screen running at 2560x1440px. This is a 200% scaling factor.

This occurs with either Wayland or Xorg. I'd be happy to provide any debugging info, but I'm not sure what's applicable for this. 

I'd be happy to build from source if that would be useful.

Not attaching any sequences here as the rendering issue occurs even without a sequence loaded.

**Comment by dkulp** [comment]
Should be fixed now.   Will be in 2023.08.
