### ISSUE TITLE
House Preview In The Sequencer Tab Is Just A Big Square 

### ISSUE THREAD

**Issue by Sam3287** [smeighan/xLights#3614]
House Preview Wen Sequencing Is A Big Square But In The Layout Tab It Look's Fine 

https://user-images.githubusercontent.com/105610765/205555146-d93a2c6b-55b6-440e-ba7f-b6d5312898de.mp4

**Comment by darylc** [comment]
Maybe update your video drivers or perhaps changing your opengl version setting in xlights?
