### ISSUE TITLE
2022.24 Crash when clicking Layout or Sequencer tab Linux AppImage

### ISSUE THREAD

**Issue by no1unorightnow** [smeighan/xLights#3616]
**Describe the bug**
The entire program crashes when clicking on the Layout tab

**To Reproduce**
1. Double-click on AppImage to launch
2. Click the "Layout" or "Sequencer" tab
3. notice the window disappears due to crash

**Expected behavior**
1. Double-click on AppImage to launch
2. Click the "Layout" or "Sequencer" tab
3. the GUI changes to the Layout or Sequencer tab

**Screenshots**

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04
 - xLights version 2022.24

**Additional context**
I haven't had acceptable stability with any xLights release since 2022.14 across any of my Ubuntu machines (various OS versions)

**Attachments**
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/10161791/xLightsProblem.zip)
[drumboy.txt](https://github.com/smeighan/xLights/files/10161798/drumboy.txt)

**Comment by fone626** [comment]
I've found when this happens that the video drivers have been upgraded in the background and you simply need reboot so the running drives match whats installed.

**Comment by no1unorightnow** [comment]
Fascinating! That seems to be plausible. I'm unable to replicate at the moment. I had a recent reboot but likely did run another batch of updates after the reboot so it's entirely possible that's all it was (and I've rebooted since and it appears to be working again now).
I'm not sure if this should be closed as it's fixed, or left open as it shouldn't just crash.
