### ISSUE TITLE
Xlights crashes   

### ISSUE THREAD

**Issue by friskybri** [smeighan/xLights#362]
When I try to  turn off nodes inside of a string the program crashes every time.

**Comment by friskybri** [comment]
I am on windows 10, 3.5GH AMD processor with 16GB memory.   Nvidia 460 Graphics card.  With using xlights 4.27 and 4.28

**Comment by stevegiron** [comment]
Hi, is this still an open issue for you? If not can you please close the issue. Thanks.

**Comment by AzGilrock** [comment]
Closing.  Open new ticket if it happens again and include more info and your sequence files.
