### ISSUE TITLE
Older entries on xlights.org downloads doesn't goto older entries. 

### ISSUE THREAD

**Issue by stevelawrence66** [smeighan/xLights#3622]
On the Home page of xlights.org is listed the current release with the changelog for that release.

Beneath is is an 'Older Entries..." which one assumes would take you to the previous release ( plus changelog) but it doesn't. 
It goes to : https://xlights.org/page/2/ --> which ends up being the same page. So one cannot 'scroll back' through 'Older Entries...' to view the change logs of previous versions...

**Comment by darylc** [comment]
@wcfrostick
