### ISSUE TITLE
Spiral tree not working with some effecs

### ISSUE THREAD

**Issue by Woutch** [smeighan/xLights#3626]
**Describe the bug**
Some effects do not have the desired outcome on spiral trees, normal string trees work.

**To Reproduce**
Create 2 layouts, 1 tree with 12 strands. 1 tree with 1 strand and 20 spiral wraps

**Expected behavior**
Some effects do not work correctly.

**Screenshots**
![2022-12-07 16 14 31](https://user-images.githubusercontent.com/3136903/206217777-7082b25e-7707-42ac-b2a4-d01d2ec6ee9c.png)
![Animation](https://user-images.githubusercontent.com/3136903/206217791-61f3c82c-dac6-48ca-9108-ec650993505b.gif)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version [e.g. 2022.24]

Maybe this is some configuration issue, but I would expect both trees to show the same outcome.
Like the bars animation from bottom to top seems to work normally.
![Animation1](https://user-images.githubusercontent.com/3136903/206218872-86fccb93-a417-42f6-b234-f257cb49b065.gif)
But from right to left does not work on the spiral one.
![Animation2](https://user-images.githubusercontent.com/3136903/206218984-c5faea16-2946-40f5-ac66-b92fce8d88f9.gif)
(Default bars sequence, only changed direction to Left)

Many thanks,
Wouter

**Comment by AzGilrock** [comment]
Those models are going to have a different render buffer layout

**Comment by Woutch** [comment]
> If you want the tree with one strand and 20 wraps to act the same as the other tree, you will need to change your render style on the effect. Per preview may give you the results you want. This is not a bug or issue within xlights.

Thanks for the tip. I see that if I put it on per preview. This now works with with the bars effect horizontally. But others like Fan or Fire don't.

I guess this works not for all effects then.

Thanks for helping.
Wouter
