### ISSUE TITLE
Edit Display Elements Window not opening

### ISSUE THREAD

**Issue by algea100** [smeighan/xLights#3632]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Right click on sequence models and click on Edit Display Elements, Window does not open. Tried all options window still not opening!
**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.
Edit Display Window to open
**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2022.24

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by derwin12** [comment]
Usually hiding on another screen.. Try view->Windows->reset to defaults.  or perhaps ->dock all.

**Comment by algea100** [comment]
Thanks, tried most solves already, no luck, will keep messing around and see.
Thanks again.

**Comment by derwin12** [comment]
From command window, cd to the xlights folder (perhaps c:\program files\xlights) then xlights /w
This will wipe the preferences and settings and start a new. You simply repoint to your show folder on startup.

**Comment by AzGilrock** [comment]
I've never seen a "Reset to Defaults" followed by a "Dock All" not bring the window back if the window is actually active.
