### ISSUE TITLE
Import of Timing track failed - appears the label may be too big?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3633]
From Zoom. The attached file was created with the auto lyric align. Can xlights be changed to handle this long lyric label or should it go to the folks at autolyric align? I had the guy just remove the big long label and it worked fine. I did some testing and it seems to be just the size of the line, not something in the line that caused the issue.
[output (6).zip](https://github.com/smeighan/xLights/files/10220766/output.6.zip)

**Comment by keithsw1111** [comment]
This is a defect in the tool that created the xml file. The long text is not a problem. What is a problem is the inclusion of the & character. This character is illegal in an xml file unless represented as &amp;.
