### ISSUE TITLE
Crash - FPP Video Player Only after you switch from it.

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3635]
Using nightly..
Add Ethernet controller. Select FPP Video Player Only
Enter an IP or whatever.
Now change from Video Player Only to LED Panels.
..crash

I think the same crash happens if you choose ShowPlayer Only.

https://user-images.githubusercontent.com/4643499/207621818-109eb92b-d2f6-41e0-9466-18f6a504d3a3.mp4

[xLights_dbgrpt-17000-20221214T092456.zip](https://github.com/smeighan/xLights/files/10228642/xLights_dbgrpt-17000-20221214T092456.zip)

**Comment by computergeek1507** [comment]
fixed with e10b1eac4139ba5ce48b90a95997cd0b412a0a8e
