### ISSUE TITLE
Crash with first save-as for imported sequence

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#364]
I had just completed mapping out my LOR channels with my NC 4 models.  I had already saved the map.  I then clicked "save-as" in NC to save the converted LOR sequence as a new NC sequence.  I labeled the new file, then the program froze.  Here is a link to my dropbox where you can find the debug report.

https://www.dropbox.com/sh/1xtdo2c2es5o6vb/AABbJk6X_wUyhguY9YWRRD_za?dl=0

Thank you
Clyde

**Comment by stevegiron** [comment]
Is this still an issue Clyde?

**Comment by Clyde-L** [comment]
I have not tested with the latest release.  Go ahead and close it
