### ISSUE TITLE
Tree Rotation...Doesn't Seem to Render as Rotated...

### ISSUE THREAD

**Issue by bmasella** [smeighan/xLights#3640]
**Describe the bug**
Rather than starting in the center back of a 360 degree tree I had to start on the counter clockwise side 90 degrees from what should be center.   The effect of doing this is that all sequences that display an image or text on the tree have that text uncentered on the front of the tree.   Rewiring with position 1 as it is supposed to be is problematic due to controller placement and public access but certainly not undoable.   It was suggested that I try to use the Rotation option on the tree model.   I have done this and tried values that are plus and minus and can actually see in the visual representation the veins of the tree moving one direction or the other (depending on positive or negative).  When I get it positioned as I believe it should be, render the sequence, output to lights and play it seems to have no effect at all on the images and text on the tree.

**Expected behavior**
It was expected that the Rotation Option would allow for the entire tree to be rotated in the sequencing to have a different area facing forward

**Versions (please complete the following information):**
 - xLights version:  2022.24

**Comment by derwin12** [comment]
Rotation is only a visual change ... to rotate the look in your yard. Strand 1 will always be strand 1. Sounds like you might need to shadow model that configuration.

**Comment by AzGilrock** [comment]
Yeah the main thing is the default render buffer is always going to be like a flat sheet of paper that gets bent into a cone.  Where that sheet of paper meets is defined by where you locate string 1.  For a Picture effect you can fix it by adding X offset and checking the Wrap X checkbox.  The other option is to switch the render buffer to a "Per Preview" buffer but the side effect of that is the pixels in the back will mirror the pixels in the front.  Its been this way for 8 years don't think we are going to change anything.

**Comment by computergeek1507** [comment]
Change the render style to per Preview for the effect

**Comment by bmasella** [comment]
Thanks all... zoom room guys were awesome in trying to help.   Now we know!
