### ISSUE TITLE
Feature request:  Import timing from MIDI file

### ISSUE THREAD

**Issue by sslupsky** [smeighan/xLights#3641]
**Is your feature request related to a problem? Please describe.**
Import timing marks from MIDI file.

**Describe the solution you'd like**
MIDI files contain tempo information.  It would be useful if xLights supported importing the tempo information and created a timing track.

An example workflow is load audio track into Logic Pro.  Use Smart Tempo to analyze track and determine track Tempo.  Tempo can be constant or variable.  Export Tempo from Logic Pro to MIDI File.  Import MIDI tempo into xLights timing track.

**Comment by keithsw1111** [comment]
You can do this using "Import Notes"

![image](https://github.com/smeighan/xLights/assets/10283944/dbd4e014-524f-420b-9646-7e67ec32f87d)

**Comment by sslupsky** [comment]
Please reopen.  I was referring to a timing track, not notes.  In the example I gave, there are no notes in the MIDI file, it just contains tempo information.  I understand you can import notes from a MIDI file.  The MIDI file also includes the tempo and it would be useful to create a beat track from the tempo of the MIDI file.
