### ISSUE TITLE
Unable to add multiple smart receivers to port

### ISSUE THREAD

**Issue by northrup** [smeighan/xLights#3646]
**Describe the bug**
I have a Kulp 128D-B and I am trying to use Smart v2 Differential Receivers. I have port one cascaded to two differential receivers. One set to position A and one set to position B. This _SHOULD_ give me ports 1A, 2A, 3A, 4A, 1B, 2B, 3B, 4B. When I configured this in FPP Channel Outputs manually, all my lights work. HOWEVER, when in xLights I cannot EVER seem to assign models to anything other than port 1A.

How do I use daisy-chained differential receivers in xLights when it does not seem to understand such things. 

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**
When configured in FPP I can achieve the following:
![image-2](https://user-images.githubusercontent.com/11050/208368859-402b634a-6c9f-4758-a195-584e080a2a28.png)

However, when configured in xLights and uploaded to FPP, this is what gets configured into controllers outputs:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/11050/208369332-220d7519-d0a2-4456-8493-611a2770c3f8.png">

I should be able to assign models to port 2A from xLights, but it does not seem possible. 

**Versions (please complete the following information):**
 - OS: MacOS 13.1
 - xLights version: 2022.25

**Comment by AzGilrock** [comment]
I've never had a smart receiver so I've never played with that feature.  Sometimes its easier to just use the layout page and select the model and modify the controller properties there instead of trying to figure out how to set thing using the visualizer.  I know with my DMX serial outputs for a Falcon I find it easier to set it in the model properties and then things will show up correctly in the visualizer.
But there is probably a way to do what you want in the visualizer....someone should chime in soon.

**Comment by merryoncherry** [comment]
If in doubt, right-click.
Right-click in the visualizer.  You have to right-click the first strand if it is a multi-strand prop.
xLights doesn't know you have smart receivers and doesn't make special ports, you have to pick the smart receiver type, letter, and cascade on port if relevant.

Caveat - I haven't used that exact controller or receiver, but hopefully the same for you.

**Comment by computergeek1507** [comment]
It looks correct to me, it has 1A and 1B in FPP. xLights is uploading virtual strings for each model.

**Comment by computergeek1507** [comment]
Maybe attach your layout or screenshot of your visualizer to see your setup.

**Comment by derwin12** [comment]
Hop into xlightszoom.com and see if we can figure this out for you..

**Comment by northrup** [comment]
> It looks correct to me, it has 1A and 1B in FPP. xLights is uploading virtual strings for each model.

Correct - I can get the visualizer to land pixels on 1A and 1B in FPP when it uploads the configuration, however I cannot get xLights visualizer to land pixels on 2A, 2A, or 4A no matter what combinations I try in xLights. I'll hop on the Zoom here in a moment and see if I can find some help. I'll report back here whatever the Zoom yields.

**Comment by northrup** [comment]
![giphy](https://user-images.githubusercontent.com/11050/208498634-2d62e33f-35d7-4590-9867-12ea04c3192a.gif)

It turns out this was **entirely** of my own misunderstanding about how xLights translated the ports when using differential receivers. Some time in the Zoom Support room got me lined out.

@computergeek1507 (or anyone else), do you know where the source for the xLights Manual is at so that I could contribute some documentation to make this clearer for future users?

**Comment by northrup** [comment]
For future folks searching the XLights issue tracker for clues on this issue.

In xLights when you're using a differential receiver, the "Ports" map onto the FPP labeling for the receiver. So for example, if you had TWO v2 smart differential receivers cascaded off of "Port 1-4" on a Kulp board, with a receiver "A" and a receiver "B" FPP would show your ports available as 1A, 2A, 3A, 4A and 1B, 2B, 3B, 4B for the first "Port 1-4" output. How do we model that in xLights? In xLights the grouping of Pixel Port 1, Pixel Port 2, Pixel Port 3, Pixel Port 4 map directly onto our 1A, 2A, 3A, 4A ports when you select "Smart Remote -> A" on your model. If you wanted to place ports on the first port of your second differential receiver, Port B1, you would place those models on "Pixel Port 1" and select "Smart Remote -> B" to have them show up on 1B in FPP when uploaded.

**Comment by bcarriveau** [comment]
> It turns out this was **entirely** of my own misunderstanding about how xLights translated the ports when using differential receivers. Some time in the Zoom Support room got me lined out.
> 
> @computergeek1507 (or anyone else), do you know where the source for the xLights Manual is at so that I could contribute some documentation to make this clearer for future users?

https://manual.xlights.org/xlights/chapters/chapter-four-set-up/lighting-networks/controller-visualizer#smart-remotes
