### ISSUE TITLE
Lose ability to Edit Sub-models v24 (untested on v25) Mac M1 Studio

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3649]
From Zoom..
Tested on my v22 PC and it worked.
After going to the submodels (sometimes) immediately cannot change stuff - its all greyed out.
Other times, just clicking thru the various submodels, it will all go grey and cant he change values etc.
Note in this pic the Node Ranges/Bottom Name etc are all greyed out.
![image](https://user-images.githubusercontent.com/4643499/208727392-a0698cc7-0f44-44b3-9748-e9a6236a0572.png)

vs this from my PC
![image](https://user-images.githubusercontent.com/4643499/208727694-ac27ea0d-a940-47c1-83ba-56f4b00efccf.png)

I have asked PhillipCook to try v25 on his mac.
Attached is his package logs.
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/10270721/xLightsProblem.zip)

It as "My_Custom_Model" .. I had him place it on a port .. no difference.

**Comment by AzGilrock** [comment]
Weird cause that submodel dialog file has not been touched since 2022.22

**Comment by derwin12** [comment]
Phillip confirmed it still not working in v25 (mac)

**Comment by computergeek1507** [comment]
Can you have him record a video of him trying to select and edit a submodels, maybe I can reproduce it on my Mac

**Comment by pck66253** [comment]
This is Phillip. derwin12 thanks for your help. I'll record a video and send it here.

**Comment by pck66253** [comment]
Here is quick video. I discovered that I can close, then re-open Xlights and it lets me add new submodel items until I hit "OK", then when I re-open submodes to make changes or additions it grays out after a click or two.


https://user-images.githubusercontent.com/42684466/208752195-44922748-56ac-400a-8f05-e41aad6287d7.mov

**Comment by AzGilrock** [comment]
I think Dan already fixed it

**Comment by derwin12** [comment]
> I think Dan already fixed it

Dan's most recent commit has something todo about deleting a model - unless there was another update I missed?

**Comment by AzGilrock** [comment]
I just saw he made a change in the submodels dialog so I thought it could have been due to this issue being posted

**Comment by AzGilrock** [comment]
Ok I tried to reproduce on my Mac and I couldn't get it to fail.  I'm running 2022.25.1.  I have an M1 Max laptop running Ventura.

**Comment by pck66253** [comment]
Phillip here. I am running a Mac Studio with M1 Max 32Gb Ventura 13.1. Xlights version 2022.25.1.

I exported and imported the model and still have same issue. I imported to my 2015 Macbook Pro  running Mojave 10.14.6 with Xlights 2021.30 and have no problem.

**Comment by cybercop23** [comment]
I have the same issue on M2/Ventura.. Keep loosing the ability to edit when I make changes to existing or add new ones. If I press okay and go right back in.. it works fine.. .annoying but not a big issuse. 
Maybe I'll upgrade to the Pro version to get all the fixes.

**Comment by computergeek1507** [comment]
Pretty sure Dan fixed this with bcf61aa539c79457b22a636b9361a41b3420aa59

**Comment by pck66253** [comment]
just a quick update. I still have this problem. I don't know what bcf61aa means.
