### ISSUE TITLE
Select Effect tool

### ISSUE THREAD

**Issue by jefft0825** [smeighan/xLights#3652]
If you use the select effect tool (tools - windows - select effect) and try and highlight all of a certain effect in a sequence and bulk edit something, it doesn't work anymore.  

This is on the most recent version of xlights and hasn't worked in a few versions

Open up a sequence, use the select effect tool.   Pick and effect, pick a group, then select them all

Try and bulk edit a transition in and xlights will start glitching and won't do any of the bulk changes

**Comment by AzGilrock** [comment]
It's working fine for me.  Provide more details like what is your OS.  Might as well Package up a sequence for us.

**Comment by atticusm** [comment]
I've already submitted a bug report for this https://github.com/smeighan/xLights/issues/3644
