### ISSUE TITLE
House Preview only shows models included in the Selected View

### ISSUE THREAD

**Issue by devinhedge** [smeighan/xLights#3656]
**Is your feature request related to a problem? Please describe.**
Currently, the House Preview only displays the final rendering.
As I start to layer on layer upon layer of effects, it makes it difficult to see what an individual effect is doing before I layer on the next effect.

**Describe the solution you'd like**
As an xLights Sequence Junkie, I would like the House Preview window to only display models that are listed in the currently selected View so that I isolate a subset of models in a specific view and then view just that subset in the House Preview window.

I know this will be done when:
* GIVEN I have a specific view open in the sequencer (e.g. All Horizontals), 
* WHEN I open, and then when I have that view open in the sequencer, and press play on the sequence 
* THEN what is shown in the House Preview window contains only a rendering of THAT view's models.

**Describe alternatives you've considered**
As an alternative, I thought about having multiple sequence files where I am only working on specific sets of models within the sequence, then once I have that set of models working the way I want, I re-import only the model layers back to the primary sequence file.

**Additional context**
I think ideally, I'd like to have something akin to the way a network diagram in a higher-end compositor works where I can work on a given set of effects applied to a given set of models and only see the net effect of that isolated set of models. This isn't the same a the Model Preview which is just one composited view of a single Model.

The more I mull it over, really what I asking for is the render to only work on the current view, instead of rendering the entire sequence. I don't mind having multiple renders sitting on my desktop and "temporary renders" that are cleaned-up (deleted) when I go to close the xLights app, or close the current sequence. I think this could be done by just appending the View to the preview rendered filename. (I didn't completely explore what the code is doing because I wanted to get the frustration and idea out of my head.

**Comment by keithsw1111** [comment]
This is not possible given the way effects are rendered without introducing masses of complexity. If you want to do this ... open another copy of xLights and copy the effects into a new sequence.
