### ISSUE TITLE
San Device E6804 DMX Bridge

### ISSUE THREAD

**Issue by zNightman** [smeighan/xLights#3657]
I can no longer set an output on a San Device E6804 as DMX output allowing the E6804 to be used as a DMX bridge.  I also have several spiral models that are RGB dumb strings that are in a spiral tree shape that I use the DMX to control these strings.  I can also no longer set these models to a DMX protocol.

**Comment by computergeek1507** [comment]
If you don't use auto layout and don't set the controller type, you can manually configure it. Due to Sandevice using the Pixel ports as serial, I couldn't easily add code to the Visualizer to upload both
