### ISSUE TITLE
REQUEST: Move/Copy Faces Effects to Other Models

### ISSUE THREAD

**Issue by SLSettles** [smeighan/xLights#366]
I would love to see an option to drag Faces effects from one model to another. For instance, highlight a phrase, drag to another model and the phrase, word, and phoneme breakdown would all be moved to the target. Hold a modifier key (Option on the Mac) and the effect would be copied instead of moved. If a word is highlighted and dragged, only the word and phoneme would be moved/copied to the destination model (creating a new Phrase with that one word). I would think it would be best to constrain the drag so that it only moves model to model, not forward or backward in time, to avoid inadvertent sync problems. But, for repetitive lyrics it would be nice to be able to highlight a phrase and drag copy it to a later time in the same track, also.

**Comment by stevegiron** [comment]
Does copy/paste not work for that just like any other effect ?

**Comment by SLSettles** [comment]
No, it doesn't. I think I was talking to Gil about it and there was some problem with targeting the destination for the paste. That's why I thought the drag-copy might be a good solution.
