### ISSUE TITLE
Single selected effect Window

### ISSUE THREAD

**Issue by Strawberry1997** [smeighan/xLights#3660]
I want to see what 1 effect  does by itself. It is challenging when working with a prop that has multiple layered effects. to know which effect you are manipulating.  

I would like another window like the model preview window but separate. This window will only show effects that are selected. I would like the ability to select multiple effects using the ctrl key, these effects can be anywhere in the timeline and be played back in accordance to the timeline in this window. there are some effects that will  do nothing due to layer blending, which is understandable.

**Comment by devinhedge** [comment]
This is similar, or a derivative to #3656

**Comment by keithsw1111** [comment]
Then open another copy of xLights and paste them there or move them to a section of the sequence without other effects. This is not possible to implement in the rendering engine.
