### ISSUE TITLE
Overlapping submodels not fully rendering in a sub model group

### ISSUE THREAD

**Issue by Frowndon** [smeighan/xLights#3665]
This is probably a know issue but just want to confirm. I have a custom xlights model with 12 intersecting spirals which intertwine with each other. When I add the 12 submodels to a group and apply the single strand effect (per model single line) only the dominant sub model lights the intersecting pixels. When I apply the effect to all 12 sub models individually it works fine.

https://user-images.githubusercontent.com/88113304/210521247-20b6fcef-ac72-4364-84b8-da291e6ce1d4.mp4

https://user-images.githubusercontent.com/88113304/210521253-bbc0030a-56b3-4792-9953-2cd3ae52b141.mp4

![Capture](https://user-images.githubusercontent.com/88113304/210521255-a3b56658-2e69-41e2-8c1c-9da50bfc221c.JPG)

**Comment by keithsw1111** [comment]
This is expected behaviour and in fact check sequence warns you when you do this. A group can only have a node present once.

**Comment by Frowndon** [comment]
Hi Keith,

"A group can only have a node present once" that's all I need to see, the
warning on check sequence is ambiguous.
I'll stop trying to get it to work. Thanks for your reply.

Regards,
Brendan.
