### ISSUE TITLE
Enhancement: Add .out file type to Glediator file search

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#367]
Jinx! is a Glediator type effect generator and saves output files in Glediator format however it saves them with the .out extension as default.  Allowing the Glediator effect to also open .out files would save one step in creating effects with Jinx!

**Comment by cjd** [comment]
I added the option to open *.out files from the glediator file selection dialog - just choose the *.out option from the bottom right of the file dialog.
Not overly obvious - but simple to use once you know it's there

**Comment by stevegiron** [comment]
Tested and it works. Thanks Chris!
