### ISSUE TITLE
editable range for value curves

### ISSUE THREAD

**Issue by illusionmanager** [smeighan/xLights#3670]
I wanted a pinwheel to come in from the bottom and leave at the top. I used a value curve to animate its location. The value is however limited. The lowest value for example is 0, but when at zero, the pinwheel is already for 50% visible. I would like it to go below zero. It would be nice if we could adjust the min and max values of a curve. The default could be the same, but being able to change it would be nice.

**Comment by AzGilrock** [comment]
You should be able to accomplish the same thing by oversizing the render buffer.  You can make it larger than 100% then the effect can come in from off screen.

**Comment by AzGilrock** [comment]
The effects are written to draw across the render buffer its passed so we can't allow negative values because that puts things into positions that do not exist in the render buffer.

**Comment by illusionmanager** [comment]
You mean like this? that doesn't seem to work. (at least not in the preview area)
![Untitled-2](https://user-images.githubusercontent.com/79637793/210783344-b2fc37ee-de28-42b4-83a5-c9aed6cc5d4f.png)

**Comment by illusionmanager** [comment]
o wait I should have made it larger, not smaller. That does work!
