### ISSUE TITLE
twinkly driver buffering

### ISSUE THREAD

**Issue by illusionmanager** [smeighan/xLights#3671]
I've two 600 RGBW twinkly sets for which I used the support that is build into xlights. However, even though the wifi is relatively ok, often one of the controllers gets out of sync. It stills plays all the content just fine, but up to 10 second later. It seems to me that somewhere, the driver is just buffering all the data that it wanted to send out, instead of skipping a frame when it gets behind.

**Comment by keithsw1111** [comment]
Because of how twinkly work starting to send data requires a web call which needs to be respond before data can be sent. I suggest you need to fix your network so that open call works quickly. Without the open call the controller will not accept the data.
