### ISSUE TITLE
Ability to import sequences with viewpoints

### ISSUE THREAD

**Issue by snow56border** [smeighan/xLights#3672]
Currently, Xlights warns, during check sequence, that view points do not get imported.

![image](https://user-images.githubusercontent.com/91710580/210898530-b229a652-8adc-4d2c-9524-8af3baa8e79f.png)

When switching layouts, it can be infeasible to manually check every effect and what its viewpoint is set to for updates.

Original sequence:
![image](https://user-images.githubusercontent.com/91710580/210898744-18a5f5c4-c405-4b4d-a23b-259255827a04.png)

Updated layout sequence:
![image](https://user-images.githubusercontent.com/91710580/210898791-697a1c27-2a18-4aa0-a443-88ab6b754b3d.png)

Both layouts define the View Point top the same way, and the same coordinates. It would be helpful if Xlights could set the **Camera** field in **Layer Settings** to the value it was in the original sequence. Perhaps it could have the same prompt as missing models. If you did not have a View Point with the same name, it could ask the user which View Point it should use, or revert to the default 2D

**Comment by snow56border** [comment]
It would be cool to be able to have importing views work between sequences.

**Comment by keithsw1111** [comment]
If the layout includes the view then it should import ok and match the view you have in the target layout. 

An alternate approach would be to create groups with a default view set and then import onto that. That will work pretty much automatically.

It is not possible to actually import the view as every layout is different.

**Comment by snow56border** [comment]
The example I indicated above was two layouts with the same views defined (I copied the xlights folder so I could be sure they were identical layouts). I have been unable to get an imported sequence to match the exported sequence Buffer Camera value.

The buffer camera value seems to always revert to default, regardless of what the effect in the sequence has. I had a feeling that this property is just not carried in the sequence.

setting a group to default to a view isn’t a great workaround as the intent is to use this buffer camera option at the effect level. If I was assigning the entire group, I could just bulk edit the timeline. An example is when I sequence pixel poles. Creating a ripple that starts in the center and moves outward looks quite a bit different rendered from a typical front of house view vs a top down view. To get some of these effects, people have used shadow models and sequence on those (which is equivalent to setting a default view for a group )… but replicating every model for each view seems to waste a cool thing 3D layouts give you.

Other options like render type get set correctly, it would be a big help if the camera option could be set to the value it was in the original sequence. For a workaround, I could go back to shadow models, but it feels a shame since it feels like the sequence could contain this information on export and simplify a layout directly.

**Comment by keithsw1111** [comment]
So I just did this and it worked fine.

I created 2 show folders. One model in each ... different names and types. I also added a group and set its default camera to "Top" which i created in both layouts.

In 1 layout I created a sequence with one effect on the model and one on the group using the "Top" camera ... then I imported this into the second layout. The effects came in and the camera was correctly mapped for both effects.

Clearly you are doing something slightly different ... but i am not sure what ... and until we can identify this we wont be able to resolve it.

**Comment by snow56border** [comment]
I was able to test this out. I started from:
- New Show Directory
- One model created called 'Star'
- One Group with the above model in it called 'Star Group'
- One view saved as 'Top'
- One View Saved as 'Side'
- A new animation with the default 'All models' selected
- Added 3 layers to the group, 3 layers to the model
- On layer 1 of both group and model, I put an effect with Render style default
- On Layer 2 of both group and model, I put an effect with Render Style 'Per Preview' and Camera 'Top'
- On Layer 3 of both group and model, I put an effect with Render Style 'Per Preview' and Camera 'Side'
- Saved and packaged sequence as a .zip

I then created a new sequence
- A new animation with the default 'All models' selected
- Import -> Import Effects
- Mapped Star model to Star model
- Mapped Star Group to Star Group

The Results
- All imports to the model had the correct view and render style and worked how I would want
- All imports to the group correct Render style. All imports to the group had Camera set to 2D (group default)

Is it a limitation that groups can not have the camera property updated on an effect level? I see the group window in the layout does have the 'Default Camera'. I was hoping I could have something like the following:
- Group named 'Pixel Stakes'
- Composed of 200 individual line models
- I have views for top, side, front
- I sequence at the group level of 'Pixel Stakes'. assigning the camera any way I want for individual effects I put on the group

I could make a group called 'Pixel Stakes - Top', 'Pixel Stakes - Side', 'Pixel Stakes - Front' and set their default views to be the correct view. But that means I need to do that for every group. I currently have 32 groups, which would mean I would potentially need 96 groups. It seems very cumbersome, and I was hoping that I could apply effects at group levels and have them retain the effect camera setting. Then, if the layout its being imported into doesnt have that view name defined... then it could use the group default.

**Comment by merryoncherry** [comment]
I believe the reason here is a piece of code in SeqFileUtilities around line 1129, which says:
            // if we are mapping the effect onto a group and it is a per preview render buffer then use the goups default camera

I think this is not always necessary to do, and it could be changed so that if it is set to a non-default camera in the import sequence and the camera exists in the target layout that the camera is left alone.

I could probably make and test this change next week, if the dev team (Keith, as he wrote the code for per-group cameras?) thinks it is a reasonable approach.

**Comment by AzGilrock** [comment]
I created the Viewpoint feature and the ability to render from different Viewpoints but others may have touched it after.  But I probably didn’t do the import part….I’d say just try it and test it.   I’ve been busy on other stuff so haven’t tried to reproduce it

**Comment by snow56border** [comment]
Glad it could be found in the code. Would be great to see this feature updated! But also, patiently waiting on Gil’s moving head work :D

**Comment by snow56border** [comment]
@keithsw1111 , did you think what @merryoncherry mentioned is reasonable? I'd love to see this update!

**Comment by merryoncherry** [comment]
Will try it soon.

**Comment by merryoncherry** [comment]
See #3893.

@snow56border if you would please read the comment there to understand the limitation... and I can give you a binary to try if you like.  I did try it myself and it works the way I expect using top, side, and nonexistent camera in the imported sequence.

**Comment by snow56border** [comment]
@merryoncherry just tried the nightly build and it worked exactly as expected. Thanks! This is a huge help.
