### ISSUE TITLE
CMY Colorwheel option on Moving Heads

### ISSUE THREAD

**Issue by chrkov** [smeighan/xLights#3673]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support for CMY colorwheels on Moving Heads

**Describe alternatives you've considered**
Individual channel control.   But using CMY colorwheels I could just use colors in xlights instead of having to code DMX channels

**Additional context**
Attached is the manual for the Aqua Beams which use the CMY color wheels.
[Aquabeam-Manual.pdf](https://github.com/smeighan/xLights/files/10356956/Aquabeam-Manual.pdf)

**Comment by derwin12** [comment]
Isnt this already implemented?
![image](https://user-images.githubusercontent.com/4643499/211041834-5c0763fd-21c1-4cb1-bb44-d67646524a32.png)

**Comment by chrkov** [comment]
ColorWheel is implemented for fixed colors.   But CMY ColorWheels are not.   There are 3 seperate wheels.  Cyan, Magenta and Yellow.   Like RGB except CMY to make any color.

**Comment by chrkov** [comment]
I found the conversion equations to convert RGB to CMY.

C = (1-(Red/255))255
M = (1-(Green/255))255
Y = (1-(Blue/255))255

I tested this manually in xlights and the custom colors turn out perfect on the colorwheels   So you can take the RGB colorcode and convert to CMY on the moving heads and use the above conversion, it will set the CMY colorwheels to the correct color.

**Comment by merryoncherry** [comment]
These simplify to C = 255-Red and so forth.

**Comment by computergeek1507** [comment]
added by Kieth

**Comment by chrkov** [comment]
This is great to see it added.  Cant wait to play with it!
