### ISSUE TITLE
missing OK/Cancel on Schedule Playlist

### ISSUE THREAD

**Issue by blehke** [smeighan/xLights#368]
Sorry if this is already logged - I don't see it...  
When trying to schedule a playlist, if there are more than 5 days in the Show Dates, the OK and Cancel buttons start disappearing from the dialog.  At 8 days, they're gone.  Attached image has 6 days and they're mostly gone.  

![image](https://cloud.githubusercontent.com/assets/12703779/9859042/e5dcdcd0-5ae9-11e5-9292-6779763597ce.png)

**Comment by stevegiron** [comment]
I'm sure someone might take a look at this, however most if not all of the developers don't even use the built in scheduler. They use the Falcon Pi Player. Yet I do see this as an issue with the GUI.

**Comment by wbottomley** [comment]
A big issue as I'm one of those who use the scheduler/player.

**Comment by wbottomley** [comment]
Can we get this corrected in the next release?  I can't get the schedule saved without "OK".

**Comment by cjd** [comment]
I just committed a fix which should ensure the buttons are always visible (and allows you to resize the dialog while at it)

**Comment by wbottomley** [comment]
When will this update be pushed out?  It's needed very soon.

On Mon, Sep 28, 2015 at 9:53 PM, Chris Debenham <notifications@github.com>
wrote:

> Closed #368 <https://github.com/smeighan/xLights/issues/368>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smeighan/xLights/issues/368#event-421411159>.
>



-- 
William Bottomley

**Comment by cjd** [comment]
Hopefully in the next day or so
