### ISSUE TITLE
Sketch Effect Crashes Xlights in 2023.01

### ISSUE THREAD

**Issue by adamcoulombe** [smeighan/xLights#3684]
Putting a sketch effect on the timeline crashes xlights in 2023.01

**Steps to reproduce the behavior:**
1. Drag a sketch effect on the timeline in xlights 2023.01

**Expected behavior**
Earlier versions of xlights (eg 2022.22) didn't crash

**Screenshot**
![crash](https://user-images.githubusercontent.com/469038/212332476-91dc981c-3e97-4c98-8a06-b06f1f714252.gif)

**Versions:**
 - OS: Windows 10
 - xLights version 2023.01

**Attachments**
- Attaching crash report
[xLights_dbgrpt-4888-20230113T083100.zip](https://github.com/smeighan/xLights/files/10411989/xLights_dbgrpt-4888-20230113T083100.zip)

**Comment by KinzuaKid** [comment]
Same issue. Same steps to recreate as OP. Additional DBGRPT attached. Attempted dragging the sketch effect to several different models to see if the model type affects behavior. It does not. xLights crashes on any model the Sketch effect is dragged to.

**Attachments**
[xLights_dbgrpt-8904-20230117T191929.zip](https://github.com/smeighan/xLights/files/10441824/xLights_dbgrpt-8904-20230117T191929.zip)

**Versions:**
- OS: Windows 11 22H2 build 22621.1105
- xLights: v2023.01

**Comment by keithsw1111** [comment]
It crashes a lot ... 2nd most common crash in 2023.01
