### ISSUE TITLE
5x5 font

### ISSUE THREAD

**Issue by Mat-Moo** [smeighan/xLights#3686]
> could we get a new fixed 5x5 font in? I've been looking at the files, not sure on the format but happy to help with anything I can? Got some arches and columns that are 5 deep/5 wide, but I think it would be well received:)

**Comment by keithsw1111** [comment]
Font files are found here: https://github.com/smeighan/xLights/tree/master/images/Fonts

If you want to provide a 5x5 png then sure we can include it.

**Comment by Mat-Moo** [comment]
Ah fab, thought I'd need to do code - I will get that started!

**Comment by Mat-Moo** [comment]
Any easy way to test it? I've kept it as fixed width, so then works running in both directions (old skool!)
![5x5](https://user-images.githubusercontent.com/908888/215984010-7f4e757b-6e53-4fa4-ba79-ed1f2252c1bc.png)

**Comment by merryoncherry** [comment]
@Mat-Moo  There are about 2 lines of code to change too.  I can give you a patch so you can work on the font iteratively, or a binary with it in for you to try it out if you'd rather.  Just let me know which approach you want to take and where to put it.

**Comment by Mat-Moo** [comment]
Binary would be easier for me, would save me setting everything up (I'm a developer but my stack is Delphi / PHP etc.) - Thanks

**Comment by merryoncherry** [comment]
https://drive.google.com/file/d/1DLKJ5ZLVWtsVB5HkEOgSqxPcSN3vCxZz/view?usp=sharing

**Comment by Mat-Moo** [comment]
Brill, couple of tiny tweaks to make, also can I add another line to the bottom of the grid so I can add a UK £ symbol? = 0x83 character and the map only goes to 0x79, otherwise I may swap something like tilde (not often used) for us in the UK

**Comment by merryoncherry** [comment]
That's a definite maybe on the £.  The effect code would appear to be capable of going beyond 128, but I'm not sure what happens as far as 8-bit extended ASCII vs UTF-8 or something on the input text.  Would have to try it.

For other tweaks to the font, I'm not sure if you want to put the image here or if you want to put it in github?

**Comment by merryoncherry** [comment]
The existing font manager code doesn't want to go above 128.  That could be changed, but for just one symbol in one font it seems a bit much ("New feature - if you want a ££* in 5x5 font you can have it, any other symbol any other size too bad!).  If you have a lot of free time and want to add useful symbols / accent characters to all the other fonts too, then the code change is probably worth it.

*it is not 0x83, but 0xA3

**Comment by Mat-Moo** [comment]
yep, 0xA3 my bad - dec 163 (I have character map open as well, no clue why I put 0x83!)
Looking at the extended character map, and the fact that the first 0-31 characters in the images are empty - could it be as simple as if the asci value > 160 then map to to value-160? then £ and € (Although euro not in really) would map down to the current blank characters? Example added...

![5x5](https://user-images.githubusercontent.com/908888/217083790-1cbed2ac-fb39-494c-afe0-8ac642fb1174.png)

**Comment by merryoncherry** [comment]
It'd be just as easy and more explicable to allow the grid to be over 16 rows.
I see some value to doing this for really small fonts like x5 or x6, but for the bigger sizes (x12, x15) I assume people would use the OS fonts and it isn't worth adding.

**Comment by Mat-Moo** [comment]
I'm happy with any solution, (Extended ASCII support sounds more logical) to be honest the £ was a hope more than anything not sure how much it would be used, but does open the possibility of lots of European characters as well éóú etc. will be almost impossible to add them into x5 maybe with x6 - BTW I did a 5 layer arch and I think it looks wonderful (I'm being biased, and need to see it for real rather than virtual)

**Comment by AzGilrock** [comment]
The only thing I’ll chime in with is this whole non OS font feature was added to support the SuperStar imports so just make sure any changes don’t alter existing behavior for those imports.

**Comment by Mat-Moo** [comment]
Sorry, been a bit under the weather :( I don't know anything about SuperStar or even how much anyone uses non OS fonts, but personally I like the clarity and predictability of them :) I tried downloading a 5x5 os font  but couldn't get it to render well at all, at least not as I was expecting. I'm happy to leave it as is, learnt something new ASCII only has 127 characters haaha :)

**Comment by keithsw1111** [comment]
@merryoncherry ... am I expecting a pull request for this or do i need to look at incorporating it?

**Comment by merryoncherry** [comment]
I was going to add the extended font grid before making the PR... should be able to do it by the end of the weekend here.  If you want it split into 2 PRs, one for the initial 5x5 fonts and one for the extended characters, I can do that, just let me know.

**Comment by keithsw1111** [comment]
I would do the base case first as I am also concerned that the extended character one does not break the superstar import.

**Comment by merryoncherry** [comment]
Looking for guidance on the superstar import.

If we add more characters to the set, taking care to calculate the number of rows in the grid in a new way, the effect on behavior would be that characters over 127 would appear in the result, rather than being swallowed.  If that's going to break something, could we add the chars in a new font with a new name that didn't get used for superstar?

**Comment by keithsw1111** [comment]
I honestly dont know ... I would just test it and see what it does.
