### ISSUE TITLE
Morph: Effect Assist window missing Grid and Points 2023.01

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#3689]
Messing around with Morph effect today.  Found the Effects Assist window is missing the start and end points for the Morphs.  Was working fine in 2022.22 when I used it last.  Not sure when it happened.    The Morphs still work fine, just missing the grid and start/end points.

Thank you for checking it out!
Clyde

![image](https://user-images.githubusercontent.com/12719816/212755023-c1b4bcfc-e95e-4092-adf1-0b5d92096b1b.png)

**Comment by bcarriveau** [comment]
Try a nightly build clyde

**Comment by bcarriveau** [comment]
@Clyde-L Confirmed that it does work in the nightly builds, but its appears to be Missing the Center Icon for the effect as well? Has it always been missing?
