### ISSUE TITLE
Using cursor keys does not change the focus for effect placement

### ISSUE THREAD

**Issue by SLSettles** [smeighan/xLights#369]
If you click in the grid, the cell you click on become the focus for effect placement, i.e. if you hit the "o" key the cell will turn on. You can then move the highlight to an adjacent cell using the cursor keys, but the focus remains on the originally clicked cell.

**Comment by stevegiron** [comment]
What do you mean by "the focus remains on the original cell" ?

**Comment by SLSettles** [comment]
An example would be easier. Click in the grid on an empty cell, then use the cursor keys to move the highlight a few cells over and then hit "o". The cell you originally clicked will turn on, not the one you have highlighted. At least that's what it does on Mac.

**Comment by stevegiron** [comment]
I see what you mean. Confirmed.

**Comment by AzGilrock** [comment]
Sounds like I never tested the Paste feature after moving the selected cell with the keyboard.  As a note to myself the fix is that the drag start and drag end variables need to be updated whenever the cell is moved.

**Comment by AzGilrock** [comment]
This was fixed today.  The same bug was reported in #432 just stated a little differently.
