### ISSUE TITLE
Natively support non-serpentine matrices

### ISSUE THREAD

**Issue by jolcese** [smeighan/xLights#3691]
**Is your feature request related to a problem? Please describe.**
Matrices assume that the each line is connected to the next one using a snake/serpentine model.
For instance, a 4x4 matrix with `Top-Left` starting location and `Horizontal` Direction is addressed like this: 
``` 
[ 1,  2,  3,  4,
  8,  7,  6,  5,
  9, 10, 11, 12, 
 16, 15, 14, 13 ]
```

But there are cases where the matrix is not serpentine and in order to fix it, it requires to create a sub-model and modify every other row.

``` 
[ 1,  2,  3,  4,
  5,  6,  7,  8,
  9, 10, 11, 12, 
 13, 14, 15, 16 ]
```

This generates the desired result on the LED panel but the Preview on the Sequencer is now garbled as every other row is reverted.

**Describe the solution you'd like**
Provide ability to select Serpentine/Non-Serpentine configuration on matrices

**Describe alternatives you've considered**
As mentioned, a sub-model with every other row inverted works but breaks the Preview.

**Comment by derwin12** [comment]
Curious what physical prop is done this way..

**Comment by AzGilrock** [comment]
The default Matrix when you create it is non-serpentine.  It doesn’t become serpentine unless you change the strands per string to be greater than 1.   If you did something nuts like run a wire all the way across the matrix then you can still model it you just will need to manually configure the matrix in the controller.  So it can be done.  I’d rather not support a wiring scheme that should be discouraged.

**Comment by jolcese** [comment]
They physical arrangement is 4 (2x2) serpentine panels of 16x16 Leds each connected to WLED. WLED presents that as a 32x32 non-serpentine panel.
@AzGilrock You're absolutely right! I changed config to 32 Strings, 32 Nodes/String and 1 Strands/String and it works perfect not. Thank you!
