### ISSUE TITLE
Layout Tab - Group Models/Submodels - Add Filter

### ISSUE THREAD

**Issue by jefft0825** [smeighan/xLights#3693]
Click on a group - At the bottom you can filter your models that you want to add to your group.    Some of these models are getting bigger with alot more submodels and you cannot filter the right hand side (models in group) if you are trying to find something or make sure something is in there easily.  

Picture attached of my ask
![Filter - Models in Group](https://user-images.githubusercontent.com/39816390/214585163-d8b590e7-ea4e-4e05-bca0-c7eeb166407f.png)

**Comment by AzGilrock** [comment]
Issue I see with a Filter is how do you know what order you are placing a group if you move one over while its filtered.  BTW not sure if it you know but items only show up on one side or the other so if you see a model on the left you know its not on the right.

**Comment by jefft0825** [comment]
If you move a model or submodel over using the arrow keys - it always adds it to the bottom anyway and would have to rearrange - I just spent 5 minutes trying to find a submodel in a large group to see what was missing and thought a  filter would be nice.     

I see your point though - i would say most people just click the arrows and it lands at the bottom but I could be completely wrong?

**Comment by AzGilrock** [comment]
Well someone might take this one.  I'm pretty sure there is another bug or annoyance with this dialog I was running into.  After moving an item over and trying to goto another model I kept ending up with 2 models selected on the left so I was constantly having to click away on another model and back on the model I wanted to get the pair deselected.

**Comment by keithsw1111** [comment]
as Gil says filtering the right would cause issues with ordering so we are not going to do this.

90% of the time this way of creating submodels is actually the root cause of your usability difficulties. While not invalid it is a very messy and often unnecessary way to do things.
