### ISSUE TITLE
Custom Cube Model Wrong Pixel Count in Visulizer

### ISSUE THREAD

**Issue by bobreese** [smeighan/xLights#3694]
xLights: 2023.01 nightly-c93007
Windows 10

I created a Cube model of 9x9x5
Pixel count of Cube in visulizer: 405, Pixel count of Custom model in visulizer: 554

Exported as 3D Custom xLights Model, saved as Cube.xmodel
Did an Import of the Cube.xmodel
Model Data gave me 5 tabs
Renumbered some of the pannels to match my custom model.
Saved as package 1 (Package 1.xmodel)

Also did an export of models under tools menu. Excel spreadsheet shows both model as 405 pixel.
Renamed xmodel uploads with added .txt as xmodel file type was rejected as an upload
[Cube.xmodel.txt](https://github.com/smeighan/xLights/files/10522239/Cube.xmodel.txt)
[Package 1.xmodel.txt](https://github.com/smeighan/xLights/files/10522248/Package.1.xmodel.txt)
![Custom Model](https://user-images.githubusercontent.com/461610/215172456-c909e2de-b534-4aa2-92b1-4d790b47779e.jpg)
![Visulizer](https://user-images.githubusercontent.com/461610/215172468-eb8db7d2-643d-4fa7-988e-208f48bac713.jpg)
[Export Models.xlsx](https://github.com/smeighan/xLights/files/10522252/Export.Models.xlsx)

**Comment by computergeek1507** [comment]
when you "renumbered" nodes you mistyped "254", Check Sequence is your friend.

![image](https://user-images.githubusercontent.com/2293065/215278106-d9f1e4c4-4b41-4f42-9b06-7a9bd12cdd04.png)


![image](https://user-images.githubusercontent.com/2293065/215278089-37cbb3b2-1e26-4e2a-8433-b0e477093bc6.png)

**Comment by bobreese** [comment]
Thank you...
I missed that along with a few in the zoom room...
Sorry for wasting your time....

**Comment by bobreese** [comment]
How did you find the "Models with issues"?

**Comment by computergeek1507** [comment]
It is in the check sequence report
