### ISSUE TITLE
Missing preferences in 2023.1

### ISSUE THREAD

**Issue by monstrousmike** [smeighan/xLights#3695]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
The Preferences Colors tab is blank. There are no colors and no ability to set any colors Timing Tracks, Effect Grid, or Layout Tab. Additionally, the Exclude Presets and Exclude Audio options are missing from the Preferences Other tab.

**To Reproduce**
The preferences are there when I revert back to 2022.17, which was the last version I used in 2022. The preferences referenced above are missing every time I try to update to 2023.1. This was the case on two separate desktops and one laptop.

**Expected behavior**
The color selection option should be available to edit on the Preferences Colors tab.
The Exclude Presets and Exclude Audio options should be available to set on the Preferences Other tab.

**Screenshots**
Attached are screen shots of the referenced Preferences tabs from 2022.17 and 2023.1.
![2022 17 Colors](https://user-images.githubusercontent.com/46628259/215219397-951eb11c-16d3-40c0-8da3-d272c0d57b26.png)
![2022 17 Other](https://user-images.githubusercontent.com/46628259/215219401-9a92f0e0-4138-4332-86cc-4b63ff9990c3.png)
![2023 1 Colors](https://user-images.githubusercontent.com/46628259/215219407-49667a3c-de6d-49b8-9c49-64c96fc31b11.png)
![2023 1 Other](https://user-images.githubusercontent.com/46628259/215219415-9c830566-999d-40b3-a952-13c4897b2476.png)

**Versions (please complete the following information):**
 - Windows 11 Home 64 bit; Intel Core i9-13900k; 64GB DDR5 RAM; Gigabyte RTX 3060 Ti 8GB GDDR6 video card
 - xLights 2023.1

**Additional context**

**Attachments**
Attached is a packaged sequence. I am not having any issues with the sequence, but this should let you see my preferences. The sequences was packaged using 2023.1. I do not mind the sequence being posted publicly.

[A StoryBots Halloween.zip](https://github.com/smeighan/xLights/files/10523616/A.StoryBots.Halloween.zip)

- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by derwin12** [comment]
Just an FYI that this is still broken in the nightly build. Thought perhaps it might have been addressed with the prior commits.

**Comment by computergeek1507** [comment]
reported to WX https://github.com/wxWidgets/wxWidgets/issues/23182

**Comment by keithsw1111** [comment]
I am not seeing this in my builds ... is this still an issue

**Comment by bcarriveau** [comment]
@keithsw1111 , scott put in a work around for this a few days ago . Can probably be closed!

**Comment by bcarriveau** [comment]
It was fixed with a685308
