### ISSUE TITLE
xLights Background Image causes crash

### ISSUE THREAD

**Issue by blargh2947** [smeighan/xLights#3697]
1) Have an existing show folder with a JPG file as the background
2) Make a copy of the show folder XML data (but don't copy the JPG)
3) Temporary change the show folder to the new location
4) Attempt to change the background image

Causes xLights to crash
2023.01 64 bit

[xLights_dbgrpt-11184-20230129T165327.zip](https://github.com/smeighan/xLights/files/10530966/xLights_dbgrpt-11184-20230129T165327.zip)
[xLights_dbgrpt-11184-20230129T165327.zip](https://github.com/smeighan/xLights/files/10530968/xLights_dbgrpt-11184-20230129T165327.zip)

**Comment by blargh2947** [comment]
Any attempt to change the background image appears to crash 2023.1

**Comment by MDickson00** [comment]
Can confirm that this is happening in the latest nightly build as well.

**Comment by computergeek1507** [comment]
fixed with 2b15de76dd6d95bb43045b38089fecd3f58cab87
