### ISSUE TITLE
Add Ease of Access Accelerator Keys

### ISSUE THREAD

**Issue by DoctorWiz** [smeighan/xLights#3698]
**Is your feature request related to a problem? Please describe.**
The keyboard shortcuts and key bindings are great, but...  Ease of Access Accelerator Keys would be super useful to extend and enhance that functionality, make using the program faster and easier (without moving your hand between keyboard and mouse), useful for setting up macros in things like AutoKey or a Macro Pad (like StreamDeck), and last but not least, provide Ease of Access to users with disabilities including those of us with shaky hands.  Some things will certainly require a mouse or other pointing device but in theory you should be able to do [almost] everything with the keyboard alone.  Not every control or menu item needs an accelerator, you can use the key for something just before it on a dialog and then use the tab or arrow keys to reach the desired control.  Not sure about Linux/Mac but with C++ in Windows this is really easy to add, they have a tool specifically for it.

Places I'd like to see it first are dialogs where macros & automation would be most useful, this includes the Import Effects dialog, Perspectives, Search & Find, Display Elements, and Effect Settings (in roughly that order).

**Describe the solution you'd like**
Add Ease of Access Accelerator Keys.

**Additional context**
Microsoft article on the subject: https://learn.microsoft.com/en-us/windows/apps/design/input/keyboard-accelerators
![AcceleratorKeys1](https://user-images.githubusercontent.com/20911920/215362570-58c8811f-c2f8-4a64-b4c6-773ae226dbf6.png)
![AcceleratorKeys2](https://user-images.githubusercontent.com/20911920/215362574-d5b1005c-ab93-4bd5-ae0b-0fba8b2326e0.png)

**Comment by keithsw1111** [comment]
Because of the cross platform UI framework we use it is not as simple as these articles suggest. While I am happy to add specific accelerators where a case can be made there is not going to be a wholesale adding of them as they require lots of code and clutter up the code base and create dual maintenance issues.

**Comment by DoctorWiz** [comment]
Just one accelerator on most dialogs is enough.  You can then use the arrows and/or tab key to get to the other controls.  On big complicated dialogs, maybe two, one at or near the top or first control, another around halfish way down, possibly on a control likely to get altered.  Most useful on the most important controls that get changed often and/or things that may be scripted with keyboard macros.
First place I'd like to see them is on the import effects dialog.  Trying to script that dialog to automatically import and re-import/update AC channels from LOR.
(Thanks Keith!)

**Comment by computergeek1507** [comment]
I wrote an xldo/lua command that will import sequences with a xmap mapping file or a newer JSON file with more options. It only works with xLights sequences but I could add more file support if you share your use case.
