### ISSUE TITLE
DDP data type field not correct set

### ISSUE THREAD

**Issue by BlueAndi** [smeighan/xLights#3704]
**Describe the bug**
Using DDP as protocol, data frames are sent with a fixed data type field of 0x01:
https://github.com/smeighan/xLights/blob/d232c52777251cc0bb9d52221a33b38ecb809fa2/xLights/outputs/DDPOutput.cpp#L419

According to DDP specification http://www.3waylabs.com/ddp/
the 0x01 is interpreted as:
* Standard types
* Data type undefined
* Bits per pixel: 1

**To Reproduce**
N/A

**Expected behavior**
It is expected that the correct data type and bits per pixel are considered.
E.g. for 24-bit RGB (8-bit per base color) will be a 0x0D:
* 0x08: RGB
* 0x05: 24-bit per pixel

**Screenshots**
N/A

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: 202301

**Additional context**
N/A

**Attachments**
N/A

**Comment by dkulp** [comment]
If anything, this would be changed to just "0" for pretty much undefined as xLights would not make any attempt to interpret the channel data at send.  However,  I have no idea if the choice of 1 was due to a compatibility issue with hardware.

**Comment by BlueAndi** [comment]
0 is an option too, thats true. In this case the display device needs a own configuration to be able to interpret the incoming data.
Is there no chance at all in the future to provide the data type and bits per pixel? It may need a internal API change that its known at send.

**Comment by dkulp** [comment]
Very little chance of that.   In general, neither FPP or xSchedule would have that data at all.  It's just a block of channels.   The way DPP is generally used with xLights and controllers wouldn't even allow it to be set properly without breaking the packet into multiple smaller packets which defeats the purpose.   The DDP packets can hold a complete mix of things where some channels in the packet are RGB pixel data, some RGBW data, some are single channel control channels, some are DMX channels for things like moving heads, etc...   

I'll switch it to 0 and see if we get any reports of it breaking anything.   If so, we'd think about changing it to 3 (8 bits per element).
