### ISSUE TITLE
Visual Studio 2022 dll's not found

### ISSUE THREAD

**Issue by SS4077ss** [smeighan/xLights#3708]
Trying to build and use xLights in a clean VM.
I have completed all of the steps outlined in the README.Windows file and have gotten clean builds.
When I try to start the application I get a message boxes saying
 HIDAPI.DLL, 
 LIBCURL-x64.dll,
 AVCODEC-59.dll, 
AVFORMAT-59.dll can not be found.

the dll files are in the Bin64 folder.
Should they be in a different folder?

Thanks for you help.

 Visual Studion 2022 community in NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
They are in the bin64 folder for the installation creation script to work correctly. It is possible to create a post build step to copy them to the build directly but it slows down compilation. You have to manually copy them over to the output build directory for debug.

**Comment by SS4077ss** [comment]
Scott
Thanks for getting back to me.
After I copied them into the Xlights/X64/Debug directory I also had to copy
the
avutil-57, swresample-4, sdl2, and swscale-6 dll's as well.
Once those files were copied I was able to get Visual Studio to debug
xlights.
Thanks for your help.
Steve
