### ISSUE TITLE
Morph Icon missing in timeline. 

### ISSUE THREAD

**Issue by bcarriveau** [smeighan/xLights#3709]
Also shown in #3689 The Morph Effix once dropped in to the sequencer does not draw the .xmp icon. It is selectable , just not drawn. 

![2023-02-01 15_56_49-xLights (Ver 2023 01 64bit) Jan 29 2023](https://user-images.githubusercontent.com/60801063/216184121-e060cbf4-b922-47eb-83b5-a436b057c1e2.png)

**Comment by AzGilrock** [comment]
That was actually done on purpose.  If you turn off effect backgrounds you get the icon.  I like the look of it without an icon for that effect.  We did add the small icons to the Galaxy, Shockwave, and Fan effects to distinguish them from Morph.

**Comment by bcarriveau** [comment]
Closing as no icon for Morph is actual function of xL

**Comment by AzGilrock** [comment]
If the other dev's really think we should have the icon its as simple as changing the return value from 0 to 2 for the DrawEffectBackground function inside MorphEffect.cpp
