### ISSUE TITLE
Tree Model Interleave Nodes

### ISSUE THREAD

**Issue by MichaelWOlson** [smeighan/xLights#3715]
**Is your feature request related to a problem? Please describe.**
I want to build a giant vertical megatree that needs 2-3 power injections on each String and I want keep all of the power injection at the bottom. I also want to keep each String on a single controller port.

**Describe the solution you'd like**
I'd like the 'Alternate Nodes' mode to be implemented as an integer rather than a bool, the value of which would indicate how many times the node layout went up and down the String. e.g.
|Interleave setting|String Node Layout|
| ------------------ | ------------- |
|1|n1, n2, n3, n4,  n5,  n6,  n7,    n8,  n9,  n10|
|2|n1, n10, n2, n9, n3,  n8,  n4,    n7,  n5,  n6|
|3|n1, n7, n8, n2, n6,  n9,  n3,  n5,  n10,  n4|
|4|n1, n5, n6, n10, n2,  n4,  n7,   n9,  n3,  n8|

I'd recommend the number of nodes was power balanced on each pass, as you can see with the interleave==4 example of 3 up, 2 down, 3 up, 2 down, as opposed to 3 up, 3 down, 2 up, 2 down. (But that's not particularly important to me, though it is important that the gap between nodes never be greater than the interleave, otherwise the strand may not fit.)

Models with 'Alternate Nodes` == False would be imported with Interleave set to 1 and True as 2. Or index from 0 if preferred, I thought 1 might be clearer to people.

I'm not that particular about the names, indexing, or power balancing, anything that lets me inject at the bottom and doesn't eat up a bunch of channels unnecessarily would do.

**Describe alternatives you've considered**
1. I could use two tree models on top of each other with a slight offset, but this requires double the controllers (and probably manually controller configuration so I don't have to pair controllers at each location).
2. Manually configure a tree using a set of overlapping lines. I've been unable to find any 3d model export/import (dxf is 2d), but if that exists or was added I could generate the model externally and import it. (I find the idea of doing this by hand somewhat daunting.)
3. Allow manual customization of the node layout. Not supported, seems more involved to add but would open up a lot of customization.
4. Process the FSEQ between export from xlights and the FPP controller, but that makes it likely some one will muck up the show by accident.
5. Output Process the FSEQ on the tree FPP controller to rearrange the node layout. Currently no such output processor.

**Additional context**
This should be usable for horizontal and spiral trees too.

**Comment by keithsw1111** [comment]
In all my years this is the first time I have seen someone want this. We can of course support it but only with a custom model.

I am not inclined to introduce lots of complexity (and even the current interleave code is painful) to support one scenario in more than 10 years.

I am afraid you will need to use a custom model.

**Comment by MichaelWOlson** [comment]
Understandable. Thanks for the response!

It sounds like you wouldn't be interested in it as a contribution, so I'll focus on adding an FPP output processor, probably a more generically usable place to implement it anyway.
