### ISSUE TITLE
2023.02 Fails to upload outputs to F16V4

### ISSUE THREAD

**Issue by bobreese** [smeighan/xLights#3717]
After upgrading to 2023.02, xLights fails to upload outputs to F16V4
Verified with John Larson on xLights Zoom room.

[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/10611583/xLights_l4cpp.log)

**Comment by computergeek1507** [comment]
down this new file to C:\Program Files\xLights\controllers and see if it works.

https://raw.githubusercontent.com/smeighan/xLights/f6bc65f5c9c02c63441d4fe2d621f34aca64944c/controllers/falcon.xcontroller

**Comment by bobreese** [comment]
That worked.
Thank you
