### ISSUE TITLE
2023.2 crashes when trying to change house photo

### ISSUE THREAD

**Issue by iancooper65** [smeighan/xLights#3719]
[xLights_dbgrpt-9992-20230206T190610.zip](https://github.com/smeighan/xLights/files/10668522/xLights_dbgrpt-9992-20230206T190610.zip)

Every time I try to change the house photo in the layout tab, xlights crashes

**Comment by keithsw1111** [comment]
Maybe share a dropbox link to the photo (please dont embed it). I have tried in the latest version of xLights and it does not crash for me so there is something about the image or your environment. The crash dump did not really help isolate the problem.

**Comment by derwin12** [comment]
Is this the same as https://github.com/smeighan/xLights/issues/3697 ?

**Comment by iancooper65** [comment]
Yes, sorry Ian Cooper On 11 Feb 2023, at 16:21, Daryl ***@***.***> wrote:﻿
Is this the same as #3697 ?

**Comment by computergeek1507** [comment]
fixed with 2b15de76dd6d95bb43045b38089fecd3f58cab87
