### ISSUE TITLE
Inconsistency between "Model/Group" and "Models in Group"

### ISSUE THREAD

**Issue by sslupsky** [smeighan/xLights#3721]
**Describe the bug**
There is a visual inconsistency in the manner in which the elements of a group are displayed.  At the top of the layout tab where "Model/Group" items are listed, the order of the elements of a group that appears here is not the same as the order of the elements displayed in the "Models in Group" box at the bottom of the window.

**To Reproduce**
I have attached a screen shot below.  The "Star 120 GRP" is shown at the beginning of the list of the "Models/Group" and appears near the end of the list in "Models in Group".

**Expected behavior**
Order should be the same in both views.

**Screenshots**
![Screen Shot 2023-02-07 at 10 35 40 AM](https://user-images.githubusercontent.com/16888734/217322438-451ca3cd-3b6f-4e59-8333-6b1315a58466.png)

**Versions (please complete the following information):**
xLights 2023.2

**Comment by AzGilrock** [comment]
Top is sorted alphabetically and the bottom determines render order.  I see no need to change since you get both ways it makes it easier to find if a model is in the group.

**Comment by sslupsky** [comment]
@AzGilrock The top is not sorted alphabetically, the groups float to the top.  My guess is the top was envisioned to mimic a file system list. Since order of the models can affect the render, I suggest there should be consistency between the two lists or perhaps add a checkbox at the top to allow them to be sorted according to the group order.  Or, add a column that shows the sequence number of the model in the group and allow that column to be chosen for sorting.

**Comment by dkulp** [comment]
The top is always sorted based on whatever column is clicked (and sorting up/down depending on the arrow), but with the groups at the top.   If you click on the start channel column for example, the models in the group will all sort based on their start channel.   This is working as designed.

**Comment by sslupsky** [comment]
@dkulp Agreed, it is working as it was originally designed.  What I am pointing out is the inconsistency between the two lists and the importance of the model order.  In my view, the model order is quite important and easily overlooked when looking at the contents of that window.

**Comment by AzGilrock** [comment]
In the screenshot it is sorted alphabetically because of the column that is selected but of course we put groups first.  It’s been tweaked by everyone but I did create the initial version of that tree view so I don’t need an explanation of how it works.  I’m starting to get in the habit of not even replying because no one has ever argued me into wanting to do a change.  You have a couple other devs so cross your fingers.

**Comment by sslupsky** [comment]
@AzGilrock Sorry, I don't mean to come across as criticizing anyone about the way it is.  It is what it is and it works quite well.  The conversation helps my understanding of why it was done the way it is.  I am attempting to inject some ideas to help improve things.  I could probably do this change myself and submit a PR.  Though, I do not really understand the criteria used for getting things get merged so I tend to avoid making contributions.

**Comment by AzGilrock** [comment]
The issue I see is the drawing of that model tree can be very slow especially now that people's shows are larger and there are tons of submodels.  I'm pretty sure trying to redraw the upper window every time something changes in the lower window is going to be really sluggish.  I also don't feel like seeing the render order in that top model tree is that important.  You have other ways to see that information.

**Comment by dkulp** [comment]
The bigger thing to me is the current behavior is CORRECT.   If you click on the first column title, it is supposed to sort by name.   Any other sorting behavior is wrong.  That is how similar controls work in pretty much every application.   Thus, you would need to find a way to retain the current behavior while trying to introduce some sort of new "not really sorted, but kind of" ordering.  You'd likely need to dig through the list control in wxWidgets to figure out what could be done, but even then it might not be doable if you are dealing with native controls on the three platforms.

**Comment by sslupsky** [comment]
I see your point about the performance issue.  I am not very familiar with wxWidgets and so not familiar if it uses different threads for each of those controls.

I agree that the current behaviour is correct.  I am not suggesting it is incorrect.  The sorting issue could be trivially resolved by adding another column.  Importantly, I am asking if it worth considering if this view is the best way to present this information to the user given that model order is important during render.  There are situations where the render order is not obvious.  For instance, you cannot drill down into the groups or models of the master view in display elements to see the order of the  models of a group or the order of the submodels of a model.  So you cannot be certain that the master view in display elements presents all you need to know to evaluate render order.   Thus, when using the sequencer it becomes necessary to drill down on each group because model groups are being used to reorder models and submodels which leads to layout dependency in the sequencer and an incredibly complicated view.  The order of groups/models/submodels influences more than this particular issue so in that regard making this change is a bandaid and doesn't do enough to abstract the underlying complexity.
