### ISSUE TITLE
Heap corruption crash due to realloc race condition in rendering text effect's fetching song info for substitution

### ISSUE THREAD

**Issue by merryoncherry** [smeighan/xLights#3728]
**Describe the bug**
Sorry for lobbing in a contender for worst issue title ever.

This manifests itself in a highly intermittent way, only crashing / getting the debugger's attention every now and then.  I can't provide the commercial sequence; stripping out everything but text effects doesn't crash as often as it's timing dependent.

The cause of the issue, however, is somewhat clear from the code, and from the debugger screenshots below.
Text effect is rendering on a background thread.  (See either screenshot for stack trace at time of fault.)
TextEffect goes about the work to ReplaceVariables.
In computation of potential replacement values, a global wxString from xLightsFrame::CurrentSeqXmlFile->GetHeaderInfo is converted
This conversion appears to take a const object and return a const value, however the const is casted away so that an internal ConvertedBuffer can be Extend()ed (See screenshot 1)
Extend is calling realloc. (See screenshot 2)
If two threads call realloc essentially simultaneously, one is making a bad request and it could crash.  Sometimes the library catches it, other times I'm seeing a fault a little later in a log call.

**To Reproduce**
Render the sequence repeatedly in the debugger until something bad happens.  Seems it would need the media information to be a certain length; not clear if it also needs to have rendered a different sequence or something first.

**Expected behavior**
Beautiful, crash-free renders

**Screenshots**
Debugger Backtrace - interesting frame 1 where const is neglected:
![StackConstCast](https://user-images.githubusercontent.com/102841136/218291740-a5a0ac8d-ad08-4db7-a4d9-df1d2860dcc3.png)

Debugger Backtrace - interesting frame 2 where a realloc happens in a way that can be a race condition:
![StackLowLevelReallocFailure](https://user-images.githubusercontent.com/102841136/218291760-12725aa1-55b2-4fbe-9dba-57418f02e24c.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: 2023.02

**Additional context**
I would be happy to try to do something about this, but would need guidance from devs on the best solution.  It seems the issue would be hit less often if the replacement only got calculated when the substitution needs to be made, but this could also be done under lock, or the information could be cached in a way that reading it didn't modify anything.

**Attachments**

**Comment by computergeek1507** [comment]
I would add locks around the code to get sequence media info from the XML object. The replace code has limited use and I would not want to affect the render time of people who don't use it.

**Comment by dkulp** [comment]
Another option that might work would be to change xLightsXmlFile::GetHeaderInfo to 
```
    return UnXmlSafe(header_info[static_cast<int>(node_type)].Clone());
```
If the Clone is thread safe (I'll assume it is), then XmlUnSafe can manipulate the string all it wants.   Alternatively, change XmlUnSafe's param from a const reference to a copy to force the copy going in.

**Comment by merryoncherry** [comment]
Thanks for those ideas.

I'm also looking into a similar but slightly more involved case, inside the Shape effect on the Emoji setting.  The call "SetNativeFontInfoUserDesc" is being run on the background thread.  That is eventually rifling through the registry using instance variables, so can't be shared across threads.  Similar conundrum:
1) Render the Shape w/ Emoji effect on the main thread (again, this seems already to be the case on Linux for shape effect in its entirety)
2) Put a lock around it - I have used the FONT_MAP_LOCK from TextEffect as an experimental fix because it is already protecting the call there, and it did work.  (On a sequence I have that otherwise crashed 30% of the time, got 10 runs without crash).
3) Run just the font part using CallAfter et al

Option 2 is appealing from a performance perspective, but it's hard to say how to maintain it, and if the foreground thread makes a similar call simultaneously then there'd still be problems.

![ShapeEffectCrash2](https://user-images.githubusercontent.com/102841136/222745749-7caa350b-e0cb-4a56-ada7-b739d821467f.png)

**Comment by dkulp** [comment]
The TextEffects SetFont method should likely be updated to use a common "static" GetFont method (likely on RenderBuffer?)  that could be re-used in both places.   The LOCK it has would protect things 99% and since the result is cached and reused, the chances of registry issues become much smaller.   We COULD then use CallAfter for JUST the font creation which would occur only once per font.  It would be cached and remain on the bg threads after that.   

That said, in this particular case, we could further optimize things by pre-populating the cache with the native Emoji font at startup on the main thread, and bypass the SetNativeFontInfoUserDesc case entirely for most things (assuming Emoji font is mostly used).   I don't believe the _font.Encoding is needed for the Emoji font use as they are unicode.

**Comment by merryoncherry** [comment]
Thanks.  I think the clone string approach will be fine for text effect.  I will learn a bit more about the font code's behavior and requirements, brush up the test suite coverage a bit in this area, then propose something for shape effect.
