### ISSUE TITLE
Crash in single strand FX when a lot of color boxes are checked

### ISSUE THREAD

**Issue by merryoncherry** [smeighan/xLights#3729]
**Describe the bug**
Single strand effect, under "FX" tab, if you choose an effect (like "Wipe" but also many others), set palette to "* Color Gradient", and check a bunch of boxes, xLights will vanish after the 5th or 6th box is checked.

**To Reproduce**
Using the attached package .zip, click the one effect there and start checking more color boxes.
![FXCrashRepro](https://user-images.githubusercontent.com/102841136/218335670-7bcb7b01-88a8-4ed6-8fd3-8dfb2d7def09.png)

Or just put a single strand effect on a strand, switch to FX tab, choose "Wipe", choose "*Color Gradient", and then start checking color boxes until something bad happens.

**Expected behavior**
Not sure if the palette entries were supposed to get used (they don't), but shouldn't crash.

**Screenshots**
![SingleStrandCrash](https://user-images.githubusercontent.com/102841136/218335496-54db0f18-4e26-4695-b456-ca787ef2f39e.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: 2022.05 - 2023.02

**Additional context**
In release build, the debugger reports a stack corruption after handle_palette()

**Attachments**
[WipeCrash.zip](https://github.com/smeighan/xLights/files/10717199/WipeCrash.zip)

**Comment by bcarriveau** [comment]
I can also reproduce this.

**Comment by keithsw1111** [comment]
This does not seem to be still happening.
