### ISSUE TITLE
Enhancement request - Export xl setup in FP format

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#373]
Would be nice if the there was an option to be able to export the Setup information into a format that could then be used directly on the FP , without having to reenter the setup again there , particularly as channel counts and universes increase.

I only use E131 and am therefore not sure how many different other setup options there are and if it is feasible to cover them.

If this request is not feasible , please close :)

**Comment by stevegiron** [comment]
There is already talk about a universal format for this. Imagine if you could not only take the setup configuration from your controller as config.cfg file, but then import that to xLights, FPP,BBB and whatever other controller company that decides to use the future industry standard CFG file.

**Comment by keithsw1111** [comment]
This exists. Along with your networks file is a file named universes. This is the FPP universes file.

**Comment by gerry4** [comment]
Thank you very much !


Regards


Gerard


________________________________
