### ISSUE TITLE
FPP Pi 3 is not supporting serial ports in version 2203.02

### ISSUE THREAD

**Issue by jlarsonomaha** [smeighan/xLights#3730]
When setting up the Pi 3 I chose to add 3 LOR controllers to the serial port.    In the box at the bottom of the screen it shows a error saying that FPP does not support serial ports on the Pi.     

You can see a screenshot of the visualizer with the error and controller page here. 

https://1drv.ms/u/s!ArG3VWxxCDzkgmgPhV_NQizfe85E?e=vjhE8a 

I have used this setup in the past and it did work last year for my display.

**Comment by bcarriveau** [comment]
Did you try just the pi hat varient instead of virtual matrix?

**Comment by jlarsonomaha** [comment]
It does work with that option. Just not the vutural matrix.

**Comment by derwin12** [comment]
Bill .. can u update the fpp.controllers file, test and push? That is likely the issue.

**Comment by computergeek1507** [comment]
Can you try this FPP controller file and see if it works. [fpp.zip](https://github.com/smeighan/xLights/files/10736574/fpp.zip)

**Comment by computergeek1507** [comment]
You have to copy the xcontroller file in the zip to "C:\Program Files\xLights\controllers" and restart xLights

**Comment by jlarsonomaha** [comment]
Hello Scott,

 

 

This now works.

 

 

Thank You,

 

John Larson

**Comment by computergeek1507** [comment]
fixed with 1851904dc52d5b357cf73cd777bf985e4f93ea22
