### ISSUE TITLE
Crash on render

### ISSUE THREAD

**Issue by Stoshx** [smeighan/xLights#3735]
[xLights_dbgrpt-19692-20230225T132633.zip](https://github.com/smeighan/xLights/files/10832106/xLights_dbgrpt-19692-20230225T132633.zip)

Windows 10 version 22H2
RAM - 16GB
Processor - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz 4.00 GHz
Graphics - NVidia GeForce GTX 1060 6GB
xLights version - xLights64_2023_03

Describe the bug
I imported a sequence from xLights Around the World (Into the Unknown), when attempting first render after import xlights almost immediately crashes.  I open the saved sequence and try to run the tool check sequence and it also crashes.  Crash report attached.  All video files are pointing to the correct file locations.

[Sequence.zip](https://github.com/smeighan/xLights/files/10832129/Sequence.zip)

**Comment by merryoncherry** [comment]
I'm wondering if you have hardware video decoding enabled.  (File->Preferences.../Other/Hardware Video Decoding)
The code crashed in the vicinity of this with a missing codec, so could be a possible workaround.

2023-02-25 13:26:33,165 3604 log_base [DEBUG] CheckSequence: 
2023-02-25 13:26:33,165 3604 log_base [DEBUG] CheckSequence: Effect problems
2023-02-25 13:26:33,456 3604 log_base [ERROR] ---------- WHVD: Failed to set media type : 0xc00d5212 : MF_E_TOPO_CODEC_NOT_FOUND
2023-02-25 13:26:33,468 3604 log_base [CRIT] Crashed: Fatal exception occurred.

**Comment by Stoshx** [comment]
Yes, my Hardware Video Decoding box was checked.  Unchecking it resulted in a sucessfull render.  This is also the first sequence that used .MOV video files.  All my other sequences with video used .MP4, maybe an issue with rendering .MOV files?

**Comment by merryoncherry** [comment]
I think it didn't find the codec for your particular .MOV file and maybe didn't handle the error "gracefully".  (I am not an expert in this area, just thought maybe I could get you a quick workaround.)

**Comment by computergeek1507** [comment]
Can you attach the mov file?

**Comment by Stoshx** [comment]
There are six of them, two are over 400Mb, two are over 290Mb, and the other two are just over 10Mb.

http://xlightsaroundtheworld.com/previous-years.html
https://drive.google.com/drive/folders/1KaC7D6VCXfIxt6oVCi7j3qkfqXkqUh8c?usp=sharing
