### ISSUE TITLE
mapping preview

### ISSUE THREAD

**Issue by tgrinnall** [smeighan/xLights#3738]
When in the mapping dialog is there a way to have a preview screen of the model (like the wiring diagram) that your hovering over of their display and if your hovering over on a model of your display. This would help to see what each prop is what the vendor has named their props. Also would help with submodels also. when it comes to hd props. Thanks

**Comment by keithsw1111** [comment]
Right now the solution to this is open another copy of xlights. This has been asked for many times and thus this is a duplicate.
