### ISSUE TITLE
Xligh Crashes when trying to change house image in layout tab

### ISSUE THREAD

**Issue by drakkar20d** [smeighan/xLights#3742]
2023.3 crashes when trying to change the house image in the layout tab , this has happened on my computer and my mate's computer
both windows pc's, crash occurs as soon as you click to change the image , even before you can select an image
[xLights_dbgrpt-6536-20230303T210151.zip](https://github.com/smeighan/xLights/files/10881230/xLights_dbgrpt-6536-20230303T210151.zip)
![crash](https://user-images.githubusercontent.com/51933835/222704634-8a4b7e20-a36e-4a26-b56e-0ba995dc45d5.jpg)

**Comment by keithsw1111** [comment]
Can you create and package an empty sequence and we can try to reproduce

**Comment by computergeek1507** [comment]
Probably already fixed with 2b15de7

**Comment by drakkar20d** [comment]
> 

sure here it is  , although you don't need to have a sequence loaded for it to crash
[Christmas Mix.zip](https://github.com/smeighan/xLights/files/10885048/Christmas.Mix.zip)

**Comment by AzGilrock** [comment]
That’s why he said empty sequence.  Packaging a sequence also gives us your layout
