### ISSUE TITLE
Arches not working when creating multiple layers.

### ISSUE THREAD

**Issue by jlarsonomaha** [smeighan/xLights#3745]
![Arch layers](https://user-images.githubusercontent.com/61497602/223161145-42570247-b1dd-4d7f-b825-42b81646e747.jpg)

When making a arch multiple layers each layer after the first layer just adds one pixel as shown in the node layout.
![Arch layers](https://user-images.githubusercontent.com/61497602/223162440-fd2db2ac-f755-4b96-a550-a221ad876fc2.jpg)

**Comment by derwin12** [comment]
It is up to you to expand the layers and fill in how many pixels are in each layer. (That > symbol)

**Comment by Poporacer** [comment]
Just a little more clarification on what derwin12 stated, YOU define how many pixels are in each layer, xLights starts with 1 until you tell it how many by clicking on the < symbol next to the Layers, enter the correct numbers for each layer
![image](https://user-images.githubusercontent.com/46263877/227752088-41d6f7ad-588d-4e39-9024-c9e1c08fe7fa.png)

**Comment by jlarsonomaha** [comment]
Thank You,

**Comment by Poporacer** [comment]
@jlarsonomaha Can you close the issue, since it has been resolved?
