### ISSUE TITLE
Exporting model effects to .mp4 not working,

### ISSUE THREAD

**Issue by MDickson00** [smeighan/xLights#3755]
Trying to export effects on a model to .mp4 file results in an empty file.

1. Open any sequence or create a new sequence
2. Choose a model that has effects sequenced on that model
3. Right click on that model and from the sequencer list and highlight "model" from the menu and choose export
4. In the export dialog box, choose either compress or uncompressed .mp4 and choose a file path to save to,
5. Try and open the resulting .mp4 file or view the properties of the .mp4 file.

****Using the above steeps to create a .avi file works fine****

**Expected behavior**
I would expect the export to create a valid .mp4 file.

**Screenshots**

**Versions (please complete the following information):**
Windows 10 Xlights 2023.04

**Comment by computergeek1507** [comment]
What is your video export settings in the other settings tab?

**Comment by MDickson00** [comment]
![2023-03-17 16_38_17-Window](https://user-images.githubusercontent.com/83371818/226058132-a24154db-c1e3-4b4e-99f7-6a189d03a81c.png)

I should also note that this same behavior was observed on a MAC as well.

**Comment by derwin12** [comment]
Asking the obvious here ... did you render first?

**Comment by MDickson00** [comment]
Of course. Keith was looking at this yesterday, don't think he found the issue yet.

**Comment by keithsw1111** [comment]
The problem here was the matrix size. At only 12 pixels in one dimension it is under the MP4 minimum of 16 pixels. This fix scales the video so both dimensions are at least 16 pixels.

**Comment by MDickson00** [comment]
This isnatnce was recreated on my layout, the original layout that brought
this to my attention was using a different layout than mine but was
repeatable on my layout. I will try the nightly and report back.
