### ISSUE TITLE
Easier submodel creation for models with rotational symmetry

### ISSUE THREAD

**Issue by merryoncherry** [smeighan/xLights#3756]
**Is your feature request related to a problem? Please describe.**
For stars, wreaths/circles, and custom models with rotational symmetry, it would be nice to draw one submodel and have xLights make the rest.  It would also be nice to get rid of nodes that appear in the resulting submodel more than once.

**Describe the solution you'd like**
There is a description here:
https://merryoncherry.org/2023/02/28/new-utilities-for-adding-submodels-to-spinner-props/

**Describe alternatives you've considered**
This can all be done manually, it is very time-consuming however.

**Additional context**
Preliminary PR available.  It has undergone some testing.

**Comment by computergeek1507** [comment]
Your WordPress link requires a login...

**Comment by merryoncherry** [comment]
It is not supposed to need that any more but if it asks it is 'spinner'.
