### ISSUE TITLE
Faces Definition Not Working

### ISSUE THREAD

**Issue by PittFan** [smeighan/xLights#3758]
It does not appear the Faces Definition of a custom model is working correctly. The Node selection doesn't match the labeled nodes in the  Prop Preview.  Seems to be off by one node (e.g. select node 2 and node 1 is highligted).
Also, can no longer, right click and select a sub model.

Xlights version 2023.03 and 2023.04.  Windows.

**Comment by keithsw1111** [comment]
You need to attach a sequence which demonstrates the problem.

**Comment by computergeek1507** [comment]
This normally happens when the model is missing nodes or has duplicate nodes. Run check sequence and look for model errors.

**Comment by PittFan** [comment]
Ok, the off by on node issue was my fault!  Sorry.
But I sure do miss being able to select a submodel to define face nodes.  
I haven't created a sequence.  I'm in Layout tab defining my prop.  Something else that I can upoad?

**Comment by merryoncherry** [comment]
Please describe the issue with the submodel to define face.
I just tried it 
  - make new face
  - set to node ranges
  -  right click the face part to be populated from submodel
  - **check the box** next to the submodel(s) to include

Then it works.  It is quite easy to highlight the submodel without checking it and think that will work, and of course it doesn't.

**Comment by PittFan** [comment]
Great!  That worked.  Did the default "node" selection box change?  I don't recall making that selection in the past.
I do feel a bit embarassed currently.
