### ISSUE TITLE
OpenDMX output makes controllers flicker when using test tab.

### ISSUE THREAD

**Issue by dpitts** [smeighan/xLights#376]
Open DMX output makes controllers flicker when using test tab.
Open DMX works fine in sequencer though.

**Comment by dpitts** [comment]
Open DMX output makes controllers flicker when using test tab. Open DMX works fine in sequencer though.

**Comment by keithsw1111** [comment]
Dave is this still a problem now i have reworked the test tab into a dialog.

**Comment by keithsw1111** [comment]
I am closing this as I have not heard anything since March. If the problem does still exist please raise a new ticket.
