### ISSUE TITLE
Crash on saving Sequence

### ISSUE THREAD

**Issue by csmithten** [smeighan/xLights#3762]
[xLights_dbgrpt-5262-20230325T014324.zip](https://github.com/smeighan/xLights/files/11068129/xLights_dbgrpt-5262-20230325T014324.zip)
[xLights_dbgrpt-834-20230325T012213.zip](https://github.com/smeighan/xLights/files/11068130/xLights_dbgrpt-834-20230325T012213.zip)
[xLights_dbgrpt-8917-20230325T005156.zip](https://github.com/smeighan/xLights/files/11068131/xLights_dbgrpt-8917-20230325T005156.zip)
[xLights_dbgrpt-7921-20230325T003543.zip](https://github.com/smeighan/xLights/files/11068132/xLights_dbgrpt-7921-20230325T003543.zip)
[xLights_dbgrpt-6703-20230325T001757.zip](https://github.com/smeighan/xLights/files/11068133/xLights_dbgrpt-6703-20230325T001757.zip)

**Comment by keithsw1111** [comment]
Can you try the next release 2023.07 and see if it still crashes and if so attach the crash log. I have added some checks in that function. That said my attempts to reproduce are unsuccessful. You may want to send us the packaged sequence to see if we can reproduce it with the full sequence.
