### ISSUE TITLE
Layouts Missing after Installing 2023.05

### ISSUE THREAD

**Issue by cfudala** [smeighan/xLights#3765]
All of my layouts have disappeared after I downloaded and installed 2023.05.

Steps I used:
Started xLights 2023.04
Said yes to new version exists
Closed xLights while new version was downloading
Double clicked xLights64_2023_05.exe from the common download directory
Said yes to defaults
Said yes to read release notes and start application
I loaded a sequence and noticed when I expanded the house preview that only one model was showing.
The sequence played fine
Loaded another sequence and was expecting the default layout to be showing and still only one model
Went to the Layout tab and noticed all my layout only have one model
All the layouts are missing.

Attached are:
Screen shots of a sequence with the house previews showing only one model
a test sequence using my default layout and the most recent log file
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/11092791/xLightsProblem.zip)

[Error_2023.5.pptx](https://github.com/smeighan/xLights/files/11092769/Error_20
![Slide1](https://user-images.githubusercontent.com/105090364/228326908-80e0b2b4-063e-4d89-8b11-600cafb92737.JPG)
![Slide2](https://user-images.githubusercontent.com/105090364/228326910-179b475b-e5a0-4229-92b3-21c6cd8b9163.JPG)
[testingeffects.zip](https://github.com/smeighan/xLights/files/11092786/testingeffects.zip)
23.5.pptx)

**Comment by dkulp** [comment]
I see what's happening.   2D has everything on the same Z plane so the sort breaks it.  :(

**Comment by cfudala** [comment]
> I see what's happening. 2D has everything on the same Z plane so the sort breaks it. :(

Being  programmer at heart I am having a very difficult time just being a user  :)   However, I am going to act like a dumb user and ask.  
Is it safe to continue sequencing, given that at this stage I will not be messing with any of my layouts?   Will any subsequent saves  mess up the order of the models in the view?

**Comment by computergeek1507** [comment]
Fixed in 2023.06
