### ISSUE TITLE
Sequence renders when exiting "Sequence Settings"

### ISSUE THREAD

**Issue by Darzoom** [smeighan/xLights#3768]
**Describe the bug**
When exiting the "Sequence Settings" window on any sequence the sequence renders

**To Reproduce**
(This happens of both Animations and Musical Sequences) 

1. Open or create a new sequence
2. Click on FIle and sequence settings
3. Exit Sequence settings
4. Render begins......

**Expected behavior**
Not to render after exiting sequence settings.

**Versions (please complete the following information):**
 - OS: Confirmed on Both Win 10 and Mac Monterey 12.6.4
 - xLights version 2023.4 (Mac and Win) and 2023.5.1 (Mac only)

**Comment by Darzoom** [comment]
Even if nothing changes?

**Comment by keithsw1111** [comment]
Keeping track that nothing changes is not done because of the number of settings and a re-render is generally not that costly. It is not just the items Scott mentioned that could drive the need to re-render so we always re-render.

**Comment by Darzoom** [comment]
Thanks!
