### ISSUE TITLE
FPP Connect upload does not recognize .fseq or .mp3 files - MacOS 2023.05.1

### ISSUE THREAD

**Issue by twlare** [smeighan/xLights#3770]
Upload media files from FPP Connect to FPP v6.3. The files show in File Manager | Uploads, but not in Sequences or Audio.

1. Render a sequence
2. Use Tools | FPP Connect to upload the files to FPP. Media=checked, Models=All, UDP Out=All
3. Open FPP File Manager
4. Files show in Uploads, but not Sequences or Audio

xLights version 2023.01 correctly uploads the same files to Sequences and Audio.

 - macOS Ventura 13.3
 - xLights version 2023.05.1
 - FPP version 6.3 on Raspberry Pi 3B

Attached is one of many .xsq files that have the problem.
[Levitating - Spinner.xsq.zip](https://github.com/smeighan/xLights/files/11132757/Levitating.-.Spinner.xsq.zip)

**Comment by derwin12** [comment]
FYI if they are in upload (and not the others) then the file type extension is not recognized. Got a screen shot of the uploads screen/directory?

**Comment by dkulp** [comment]
This is technically bugs in FPP 6.3.   I'll try and work around it for the next version of xLights, but I pushed a fix to FPP v6.3 branch.   Thus, if you update to the latest FPP 6.3, the uploads from xLights should work again.

**Comment by twlare** [comment]
The updates to FPP v6.3 solved the problem. My system shows the working version as "6.3-4-g5f0be713".

**Comment by cybercop23** [comment]
This is fixed with today's 6.3 change...
https://github.com/FalconChristmas/fpp/commit/15823ca646f3007ccf1f603fd62b4151e3c2940f
