### ISSUE TITLE
FPP Connect not uploading new sequence but updating controller information 

### ISSUE THREAD

**Issue by TomDawes1** [smeighan/xLights#3772]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Sending a new sequence to FPP its updating the channel controller information but not uploading the sequence correctly, I have just tried adding new models, updated an existing sequence 

This had updated my controller output settings and they test ok using FPP test,
 
but the sequence is not playing the new version. 

I created a simple new sequence with basic animation but it has not uploaded to FPP although goes through the motions of uploading 

This has happened multiple times over a few days. 

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

Expected the new sequence to upload to controllers and play. But it's not. Has been working fine prior to MAC OS update. 

**Screenshots**

https://user-images.githubusercontent.com/129790663/229608138-ad2df1af-068d-4541-be34-2c319f9df58b.mov

**Versions (please complete the following information):**
 - OS:MAC Ventura 13.3
 - xLights version 2023.05.1
 - FPP 6.3

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by dkulp** [comment]
There is a 2023.05.2 version in the app store now that SHOULD fix this.   Can you please test and verify?   In addition there is an update to FPP 6.3 that also provides additional fixes for the uploads.

**Comment by TomDawes1** [comment]
Ahaaaaa, thanks that version appeared in UK APP store 2 hours ago so it had not picked up the update yet, forced it to update and that has sorted it, thanks!
