### ISSUE TITLE
Singing faces - old phoneme positions at end  do not get deleted when regenerating 

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#378]
I completed the 'Breakdown phrase' and 'breakdown words' components of the process for the song.

Then , when fining tuning , I adjusted and shortened the words of each phrase ie among other things, pulled back the end of the last word of each phrase.  I then selected all the words of each phrase , right clicked and selected 'Breakdown selected words'. The new set of phonemes get generated ,  however , the old phonemes are retained at the end ie they do not get cleared out (see attached images as examples). Am I doing something incorrect ? 
As a work around , I then zoomed out and  manually deleted each of the extra left over phonemes. 
![faceshorten](https://cloud.githubusercontent.com/assets/12591974/10213864/a2613fea-6855-11e5-9d7e-45a641c51f5e.png)
![faceshorten2](https://cloud.githubusercontent.com/assets/12591974/10213867/a7d3e3b0-6855-11e5-9495-29e17d199b4d.png)

**Comment by AzGilrock** [comment]
Phrases, words, and phonemes are not associated with each other so the word you are breaking down has no idea what phonemes it created the last time you did a breakdown.  So all it can do it delete anything underneath itself.  Initially I was thinking of trying to tie everything together but you run into a lot of situations where its not clear whether the user would want everything underneath it to change when they make a tweak to an endpoint.  I could have everything underneath try to move when something above it is moved.  The problem I had was what if you drag one of the word or phoneme endpoints that aligned with a phrase or word above it you would need to move items above and below it.  It got so messy trying to figure it out I just decided to let the breakdown do a one time creation and then all movement is independent of anything that created the items.

**Comment by gerry4** [comment]
Thanks Gil, I somehow thought that when you select all the words between two timing marks (which u can with one click ) and then selected 'breakdown selected words' it cleared out everything below that between the marks. I thought that the phonemes from before the first word got cleared , but not the ones after the last word (in the range of the timing marks) . Actually , I have not been paying attention to this as I think in most of my songs the words all 'touch' each other . I just right click and generate. But for this song , because of the long pause gaps I decided to tinker with it.  The functionality  is very good as is.  Thanks
