### ISSUE TITLE
zLights 2022-4  Will Not Accept a Manual Lyric Track

### ISSUE THREAD

**Issue by Bugga36** [smeighan/xLights#3782]
The GUI input box appears and allow the new lyric to be typed but there is no provision (such as an "OK" button) to click to allow that lyric to be accepted into the sequence.

**Comment by keithsw1111** [comment]
Please reproduce on the latest version and include a screen shot so we can be sure exactly where you are trying to do this. Otherwise we will have to close this.

**Comment by Bugga36** [comment]
Per your request.  The attached shows my Lyric input screen.

 

As mentioned, there is no method provided to submit the screen contents to the Xlights program.

The screen as displayed cannot be resized.

 

H Campbell

**Comment by keithsw1111** [comment]
Images sent through email are not visible.

**Comment by Bugga36** [comment]
I hope the image makes it this time.  I am totally unfamiliar with github communication.  See attached
![Lyrics Import Tool](https://user-images.githubusercontent.com/45780527/235282786-cb0f4706-60ac-4535-9a9c-eaf93372d0dc.jpg)

**Comment by keithsw1111** [comment]
Can you move the dialog up so we can see the bottom?
