### ISSUE TITLE
FPP (2023.06)connect fails Upload fseq files to pi devices using FPP 7.x.master

### ISSUE THREAD

**Issue by jeffc930** [smeighan/xLights#3786]
**Describe the bug**
FPP connect fails Upload fseq files to **pi** devices using FPP 7.x.master, this is using xlights Ver 2023.06.  
FPP Connect Uploads fseq files to **BBB** with the extension .patch.0 when using FPP ver 6.3-5 (xlights 2023.06)
**To Reproduce**
This happens after every instance of using FPP connect.

When Connecting to the 2  Pocket scrollers when they were ver 7, they would never connect to FPP at all, I had to disconnect the wireless dongle and reconnect it to access these pocket beagles. Once I reimaged the scandisks to 6.3-5 they would connect no problem.

The devices and versions are all identified on the screen shot

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 11
 - xLights version [2023.06]

**Attachments**

![Screenshot 2023-04-17 205003](https://user-images.githubusercontent.com/81841941/232666511-d640dbe4-e8dc-4b7d-9eb1-2f10a4e7728f.jpg)
![Screenshot 2023-04-17 205309](https://user-images.githubusercontent.com/81841941/232666972-df441d34-837e-4e7b-8b19-1cb50645f24a.jpg)

**Comment by Bthomas1326** [comment]
Have the same issue with FPP Connect on Windows 11, Beaglebone black.  xLights version 2023.6 and FPP version 6.3.5.

**Comment by digitydogs** [comment]
Issue also exists uploading to FPP 6.3.5 running on a Pi 4B using  Xlights 2023.06, Win 11

**Comment by JonD24** [comment]
In my case, the files I uploaded manually through the FPP browser were larger than the patch.0 files of the same sequence.  You might manually upload a sequence file to make sure they are the same file size before renaming the patch.0 files.

**Comment by Bthomas1326** [comment]
When manually uploading the files through the FPP manager the file size will always be larger.  That is why it is important for the FPP Connect to be working.

I have downloaded and installed FPP 7 and the issue with FPP connect goes away.

Bryan
________________________________

**Comment by Bthomas1326** [comment]
@***@***.***> be careful with xLights 2023.5 as there is a known issue with layout not showing properly in 2D.   you might need to roll back to 2023.4

**Comment by cybercop23** [comment]
This is fixed with today's V6.3 update

https://github.com/FalconChristmas/fpp/commit/15823ca646f3007ccf1f603fd62b4151e3c2940f
