### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by nickferlaino** [smeighan/xLights#3787]
**Describe the bug**
xLights 2023.06 crashes on start. I was using it regularly for the last month and suddenly can't open it. I guess issue started after last update. Already tried deleting app and reinstalled. Problem continues.

**To Reproduce**
1. Start app
2. Coloured pinwheel appears
3. Force quit

**Expected behavior**
I expected to open app, but only start up presentation screen appears

**Screenshots**
N/A

**Versions (please complete the following information):**
 - MacOS Ventura 13.2. MacBook Air M2 2022 24GB
 - xLights version 2023.06

**Comment by keithsw1111** [comment]
There is not enough here for us to troubleshoot anything. Unless you attach your networks and rgbeffects files we will just have to close it.

**Comment by nickferlaino** [comment]
I'm uploading both files, thanks for any help.

[Archive.zip](https://github.com/smeighan/xLights/files/11326219/Archive.zip)

**Comment by keithsw1111** [comment]
So it loads just fine for me.

This is likely a settings or profile issue.

This is a bit extreme but if you could run xlights from a terminal using the -w switch it will reset the profile on the machine like new clearing out whatever is likely causing the issue. 

The only problem with this is when you restart xlights you will need to repoint to the show folder. You will also need to resetup any preferences as these will be erased by this process.

**Comment by nickferlaino** [comment]
OK, I'll try. Thank you
