### ISSUE TITLE
Ripple Effect Duplicating Value Curves On Multiple Effects When Only One Effect Is Selected

### ISSUE THREAD

**Issue by dragonzpneuma** [smeighan/xLights#3789]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Value Curves on the Ripple effect carry over to other Ripple effects as shown in video.

https://user-images.githubusercontent.com/25988001/233207253-036edce4-a1ce-4e23-9e6c-b260afab86f3.mp4

**Comment by AzGilrock** [comment]
Calling @merryoncherry

**Comment by merryoncherry** [comment]
That particular effect is fixed in 2023.06, whereas the video is from 2023.04.

**Comment by merryoncherry** [comment]
See also #3775

**Comment by AzGilrock** [comment]
Thanks for following up
