### ISSUE TITLE
Unable to Upload to Advatek pixlite 4

### ISSUE THREAD

**Issue by James7063** [smeighan/xLights#3790]
In version 2022-25 I had no issues uploading output to my advatek pix light 4 controllers. however in versions 2023-4 & 6 i get an error Advatek output upload failed. I downgraded back to ver 2022-25 to retest and and was again able to upload to controller. (Eliminating any connection Issues)

However I again get the error after updating to newest version.

Thanks.

**Comment by keithsw1111** [comment]
Can you use tools package logs and attach them so we can reproduce. What firmware is your controller running.

**Comment by James7063** [comment]
Keith : Thanks for the Quick response. I had to recreate this error myself as I had just finished cleaning my main pc so I could do a clean downgrade to 2022-25. However I now have it loaded on a sandbox pc if you need further information. 

 

Todays test was run on 2022-25 successfully, then 2023-6 Fail! 

 

Regards James Todkill

**Comment by AzGilrock** [comment]
Don’t need to downgrade xlights.  I have like 75 versions of xlights installed on my pc

**Comment by keithsw1111** [comment]
If you tried to email the config as an attachment ... it failed

**Comment by James7063** [comment]
[Xlights error report.zip](https://github.com/smeighan/xLights/files/11299793/Xlights.error.report.zip)
 Ken zip files attached Thanks
