### ISSUE TITLE
Moving Heads - Tilt and Pan limiting

### ISSUE THREAD

**Issue by bmasella** [smeighan/xLights#3794]
Would like to be able to configure the high and low limits for tilt and pan on moving heads.  Purpose would be to keep the heads aligned in a way that restricts their ability to perhaps shine into neighboring propeties.   The limits become the minimum and maximum DMX values for these attributes so when sequencing if you attempt to use a value outise the limits xLights would force the appropriate value.

**Comment by AzGilrock** [comment]
This can kinda be done by using a Servo model to control the head.  I had been working on a new moving head which would be accomplished with the Servo model behind the scenes

**Comment by cabrower** [comment]
Adding onto this request, could there be maybe a safeguard feature that can be set that when the moving head is programmed to go through X/Y sets of coordinates that it calls for the dimmer/shutter to be lowered so that the light does not shine in that area? I have the same concerns as bmasella that if during programming or if using a premade sequence the moving head shines into my neighbor's properties it will be an issue.

**Comment by keithsw1111** [comment]
Pan is not practical as pans generally move through > 360 degrees but i have implemented this for tilt. This is a hard floor/ceiling on the tilt channel and it only works with DMX effect on the model or the on effect on the channel.

**Comment by AzGilrock** [comment]
@keithsw1111 I’ve got a problem with this.  I’m using the PanTiltAbility for my new Moving Head work and I use a different method to do position limiting.  This will probably force me to create whole new classes to copy all that functionality and rip it out.

**Comment by AzGilrock** [comment]
I also already have Pan limiting because I will flip the head over to reach the positions in back

**Comment by AzGilrock** [comment]
Anyways it’s early and I only took a quick glance so not sure if it would be easy to just ignore the new parameters I just would have liked to be consulted before new moving head changes were done.

**Comment by keithsw1111** [comment]
I will remove it then.
