### ISSUE TITLE
Unable to create timing marks with T (only creates 1 at  the end)

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3795]
Using 2023.7 - create an animation (30s)
Press T - it drops a timing mark at 30s. You cant create any more.

If you slide the 30s one back, and press T you get a 2nd one now it is placed at 30s.

![image](https://user-images.githubusercontent.com/4643499/234736621-cbd31a35-4089-4fca-9914-991c45304210.png)

**Comment by AzGilrock** [comment]
Where do you expect tot create them?  You can’t create marks on top of existing ones.  You can do a timing split

**Comment by sluther1130** [comment]
I see the same thing.

**Comment by derwin12** [comment]
> Where do you expect tot create them? You can’t create marks on top of existing ones. You can do a timing split

Seriously? How about where the cursor is or the black line in the timeline.

**Comment by AzGilrock** [comment]
Daryl ...sorry I can see I misunderstood the steps you described.  I see Keith fixed it but it really makes me curious how long that's been that way and if it was only animations that were a problem.

**Comment by AzGilrock** [comment]
No need to jump on me I make mistakes.

**Comment by AzGilrock** [comment]
When I saw the image I thought you were expecting it to create a timing mark where the black mark was when the existing mark was already there.  I just didn't read what you said correctly.

**Comment by derwin12** [comment]
btw it worked in the good version I used for last season -- 2022.22

**Comment by keithsw1111** [comment]
It had nothing to do with the QM change. It was the displaying time change when clicked that broke it. It surfaced other bugs which were latent in the code such that it looked like it was working but it was in fact wrong and when i corrected it other bugs surfaced.
