### ISSUE TITLE
effects are too small to be distinguished on linux 

### ISSUE THREAD

**Issue by cp16net** [smeighan/xLights#380]
Attached is a screenshot of the issue i see.

![xlights-effects-too-small](https://cloud.githubusercontent.com/assets/533503/10261878/3f34bd0a-6974-11e5-951d-259211ab86e2.png)

I've checked out the latest code as of tonight and built it. I have not been able to figure out why these icons are extremely small. I'm running on debian jessie and i just updated the readme.linux file with a few updates on what i needed to install to get it to build for me.

**Comment by cp16net** [comment]
Heres a screen shot of the top menu bar as well that are to small to read as well.

![effects-in-menu-bar-small](https://cloud.githubusercontent.com/assets/533503/10273299/e700dea8-6af3-11e5-9165-490b21a708e1.png)

I'd try to fix this but i dont know enough about wxBitmapButton. I recall the other buttons on the top being super small like this as well in 3.x when i build it for linux before. Seems like the wxAuiToolBarItem type fixed this issue, but i dont know if that was the reason or not. If someone suggests what the reason for this is i might be able help out. 

I'm a software engineer but dont focus much on gui or c++. I've been working on openstack in python.

Thanks.

**Comment by cjd** [comment]
There is a difference in behaviour on linux for those icons - but moving to wxAuiToolBarItem is a bit large a change this close to christmas (rather invasive all over the place)
You can go to "Tool Icon Size" under the settings menu and tell xLights to use larger icons.
That works as a workaround at the moment

**Comment by cjd** [comment]
I've just committed a small change that forces the pixmap size to use the next larger one - working around this issue for now

**Comment by cp16net** [comment]
@cjd yeah i didnt think it was a good idea either to make that type of change but its just what i noticed as i looked over the code. Btw i just pulled the latest code as of a few minutes ago before posting this and saw the commit but didnt see a change. screenshot posted.

![still-small-buttons-nutcracker](https://cloud.githubusercontent.com/assets/533503/10475588/bd389d2c-720a-11e5-9185-711833216360.png)

After pulling the code i built with `make clean; make` :crying_cat_face:

**Comment by cp16net** [comment]
So i just found the settings menu you were talking about and got the icons a reasonable size to see them. I _thought_ on boot of xlights the change would happen but that wasnt the case until i changed the icon size once.

![xlights-icons-much-better](https://cloud.githubusercontent.com/assets/533503/10490226/81e0f944-7265-11e5-83c7-13c5d5cfa82f.png)

Thanks for the work around!
:+1:

**Comment by cjd** [comment]
Fixed in recent releases
