### ISSUE TITLE
Can not "FPP Connect" after upgrading to 2023.7

### ISSUE THREAD

**Issue by JonD24** [smeighan/xLights#3802]
After upgrading to 2023.7 can no longer "FPP Connect" sequences and audio files to FPP 6.3 device.  Either the upload fails on all files, or occasionally it will upload everything, but the file extensions end with ".patch.0" and the file size on the FPP device is not correct.

I reverted back to xlights version 2022.25 and the "FPP connect" feature works fine.

**Comment by cybercop23** [comment]
https://github.com/smeighan/xLights/issues/3786

**Comment by JonD24** [comment]
Another person could not replicate the issue on fresh image of 6.3 no updates, but once they updated to the latest version 6.3-6 the problem appeared right away.  Apparently you need to be on a fully updated version of 6.3 for this to be an issue.  Was using Pi4.

**Comment by derwin12** [comment]
#3770

**Comment by Poporacer** [comment]
This should be fixed now, Please verify

**Comment by JonD24** [comment]
At first after updating FPP, after hitting the "upload" button it would display and small pop-up window named "xlights.exe" for a second or two, and then it would glitch out back to the main screen.  I could go back to xlights 2023-5 and it would work properly, and then back to 2023-7 and it would glitch out again.  Since then I have re-imaged the FPP and I am no longer having the issue.  I can upload running FPP 6.3-7-g15823ca6 and xlights 2023-7 fine now.  Thanks!
