### ISSUE TITLE
Roto-Zoom Z Rotation Value Curve

### ISSUE THREAD

**Issue by adobitar** [smeighan/xLights#3805]
It seems like when you set a value curve on the Z Rotation slider of Roto-Zoom, the animation is not being applied.

An easy way to see this is to put an effect on a prop or prop group and see that when you move the Z Rotation slider, you get some intended effect.  If you then open the value curve dialog and set a value curve like sawtooth with values and apply that, you would expect to see the same animation.  Currently, the effect remains static (no animation as expected).  Interestingly, if you also set a value on Z Rotations (other than flat value curve, it appears), the animation takes place (two curves must be set).  It does not appear that the value curve on just Z Rotation is respected.

**Comment by Clyde-L** [comment]
When using a value curve on the Z Rotation... you need to give the "number" of times you wish for that to occur.  The Z RotationS slider (second slider from the top of the roto zoom tab) needs to have a number in the box in order for the value curve to operate.  

The reason the top Z Rotation slider works is that you are manually setting the exact set-point for the effect.  Therefor there is no need to tell the Z Rotations the number of times to "do" the act.  The value curve on the first line requires a number on the second line.  See image below, hope that helps.
Clyde

![image](https://github.com/smeighan/xLights/assets/12719816/ebb1bf1a-0a25-451c-9e18-6ed5a5af8f21)
