### ISSUE TITLE
Enhancement request - reset perspectives

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#381]
From fb posts - 
When moving from a multiple monitor setup to a single monitor on another computer etc ... users cant find windows,
Gil: Yep there's no reset perspectives yet. Delete all the perspectives and it will come back. I've been meaning to fix this because it happens to me more than most people since I'm always loading other peoples setups.

**Comment by AzGilrock** [comment]
Keith checked in a change that provides View->Windows->Dock All which should satisfy this issue.
