### ISSUE TITLE
Add Single Strand Effect Chase Offset for custom movement

### ISSUE THREAD

**Issue by merryoncherry** [smeighan/xLights#3810]
**Is your feature request related to a problem? Please describe.**
As with the custom movement on the Bars effect, it would be nice to have a custom offset for the single strand chase.  This would allow it to move in much more interesting patterns than just left / right / inward / outward.

I have a patch that attempts this, which I will submit after it has gone through beta test.

**Describe the solution you'd like**
There are two parts:
 1. An offset slider/value curve, with a range of +/-5 cycles of movement.
 2. New chase types, that start with "Static", that don't have intrinsic movement.
   If you ramp the offset value curve from 0-100, it should do the same thing as the non-static effect with similar name.
    Static Left-Right - moves left to right as offset value increases
    Static Right-Left - moves right to left as offset value increases, also flips the color gradient so first color is on the left
    Static Dual - combination of Static Left-Right + Static Right-Left
    Static From Middle / Static To Middle - A mirror of chases headed away from middle, or toward middle, as offset increases
    Static Double Ended - This is like Static Left-Right, except it draws the chase both to the left and right of the center point; this can make it a bit more predictable for motion that alternates back and forth.

**Describe alternatives you've considered**
I suppose you could use other effects like bars/spirals, but the chase effect is a little bit nicer in some ways for 1D strings.

**Additional context**
I have a patch that attempts this, which I will submit after it has gone through beta test.

![ArchSettings](https://github.com/smeighan/xLights/assets/102841136/6d49000e-b852-4d37-ada8-26e6f15bd80a)
![Matrix](https://github.com/smeighan/xLights/assets/102841136/bba3b04f-e379-4e4b-9dce-cc56cdd90492)

**Comment by Clyde-L** [comment]
Looks good to me! :)

**Comment by bravado67** [comment]
This will be fun to play with. Nicely done!
