### ISSUE TITLE
PNG Transparency not working on House Preview

### ISSUE THREAD

**Issue by MichRX7** [smeighan/xLights#3814]
In even the most recent version the transparency of a 2d servo model is not being recognized in the House Preview, nor when outputting a video (which my guess is related to the House Preview issue). So, when you have multiple servo models in front of each other the further back models from your viewing angle are non-viewable.

1. Open a sequence
2. Put a 2d servo model on your 3d layout
3. Put a second 2d servo model right behind it on your layout
4. Start a new animation
5. Open the House Preview
6. Change your 3d view so you are staring at a slight angle from the models

At this point you will notice the transparency is actually black and blocking the model you should be able to see behind it.

The transparency is working in the Layout screen, so this is only on the House Preview. I am currently in 2023.08 on a Windows 11 PC, but I did have it confirmed on a Mac as well by Ron Howard.

Screenshots:
When the House Preview is not playing the transparency is working:
![image](https://github.com/smeighan/xLights/assets/71061371/3ae39185-bb7b-40ec-8007-3f03b68a0895)

Here you can see the transparency not working:
![image](https://github.com/smeighan/xLights/assets/71061371/5c2366f8-8395-4445-b9d9-14cd9a910045)

If I drastically angle it I am almost able to see the full images, but still not quite due to the transparency issue:
![image](https://github.com/smeighan/xLights/assets/71061371/b947d598-5dbb-4b99-b442-7fcaee787b44)

**Comment by DoctorWiz** [comment]
I have noticed that the transparency cuts off when viewing the png image directly or near directly head on, but when you incline your view, it turns transparent (in the correct spots) again.

**Comment by dkulp** [comment]
Fixed
