### ISSUE TITLE
Support for WLED 14B2 2D matrix

### ISSUE THREAD

**Issue by keukenrol** [smeighan/xLights#3816]
**Is your feature request related to a problem? Please describe.**
Tried out running my old matrix animations on the new 14B2 WLED build but the animations are messed up.

**Describe the solution you'd like**
Support for the 2D matrix configuration in wled.

**Describe alternatives you've considered**
Downgrading WLED binary.

**Additional context**

**Comment by computergeek1507** [comment]
Lack of communication
