### ISSUE TITLE
Request: Do for Piano what you've done for Papagayo

### ISSUE THREAD

**Issue by SLSettles** [smeighan/xLights#382]
It would be great if we could use the Vamp Polyphonic Transcription plugin to map notes to a predefined range of keys, like the Faces definition dialog maps phonemes to mouth shapes. In my idea, you would specify a range of keys that will be mapped (say a 28 key keyboard) similar to defining the size of a custom model, and then you specify a node (or range) that each key will control. When you click ok, the Polyphonic Transcription plug returns timing labeled with MIDI pitch numbers, which are converted to notes, and the ones that are within the defined range receive "on" effects for the timing indicated. To further enhance the effect, there could be a slight emphasis on the onset of the note, say a 1/4 second at 100% and then the rest of the note shines at 90%. Of course, these channels don't have to be mapped to piano key shaped models, they could be arches or mini-trees, or anything.

**Comment by jcmarksafb** [comment]
I second this effect.I use piano notes extensively and that would help me out a bunch. I don't know what it would take to do this, but it would be a lot of fun.John
 


     On Monday, October 5, 2015 6:56 AM, SLSettles <notifications@github.com> wrote:
   

 It would be great if we could use the Vamp Polyphonic Transcription plugin to map notes to a predefined range of keys, like the Faces definition dialog maps phonemes to mouth shapes. In my idea, you would specify a range of keys that will be mapped (say a 28 key keyboard) similar to defining the size of a custom model, and then you specify a node (or range) that each key will control. When you click ok, the Polyphonic Transcription plug returns timing labeled with MIDI pitch numbers, which are converted to notes, and the ones that are within the defined range receive "on" effects for the timing indicated. To further enhance the effect, there could be a slight emphasis on the onset of the note, say a 1/4 second at 100% and then the rest of the note shines at 90%. Of course, these channels don't have to be mapped to piano key shaped models, they could be arches or mini-trees, or anything. —

**Comment by keithsw1111** [comment]
With the new piano effect are we ok to close this one.
