### ISSUE TITLE
Superstring For Regular LEDs

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#3824]
**Is your feature request related to a problem? Please describe.**
Yes...can't see/play more than one color at a time in the House Preview for regular LED's when using the Superstring "String Type"

Would like to be able to see any color combination in the House Preview (actually works on the lights correctly but not in the preview) such as, if you have a four color Superstring, to see Red and Blue...or Blue and Green...or any combination of the 4 colors in my Superstring.

**Describe the solution you'd like**
I don't see why, if you chose for example four colors (IE: Red, Green, Blue, Pink) that in the House Preview, a Single Line of bulbs with a String Type of "Superstring" that bulb 1,5,9,13,17, etc could not be RED...2,6,10,14,18, etc could not be GREEN, 3,7,11,15,19 could not be BLUE and 4,8,12,16 and 20  and so on, could not be PINK. Then when you set the "ON" effect to that Superstring and chose any combination of colors (IE Red, Blue, Pink) those bulbs would light up in the House Preview.

**Describe alternatives you've considered**
Creating four separate models, one for each color.

**Additional context**
See attached video.

https://github.com/smeighan/xLights/assets/13740582/3d4b26c7-efd0-4297-a7e1-cd53150eb320

**Comment by jimswinder** [comment]
Another Option, instead of selecting multiple colors, might be to be able to double click on the Superstring within the Sequence Tab and therefore "exposing" the different Strands within the Superstring so you could then drop effects on the different "Colored Strands".  (See Attached Pic)

![Superstring Drill Down](https://github.com/smeighan/xLights/assets/13740582/ea638a60-e82d-4d6f-9a86-7deddbb4728c)

**Comment by cbennett6008** [comment]
It seems like you can do most of what you are looking to do with a group, (the second part for sure, if you doubler click a group, you can sequence onto the individual elements). You could also order the strands in the group in the order you want them to render so that when you change the render style to single line that they would all function as the same line.

**Comment by jimswinder** [comment]
Don't think you are completely understanding all the problems.



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: cbennett6008 ***@***.***>
Date: 9/21/23 4:29 AM (GMT-08:00)
To: smeighan/xLights ***@***.***>
Cc: jimswinder ***@***.***>, Author ***@***.***>
Subject: Re: [smeighan/xLights] Superstring For Regular LEDs (Issue #3824)


It seems like you can do most of what you are looking to do with a group, (the second part for sure, if you doubler click a group, you can sequence onto the individual elements). You could also order the strands in the group in the order you want them to render so that when you change the render style to single line that they would all function as the same line.

**Comment by keithsw1111** [comment]
Doing something specific for superstrings is not really practical ... especially for something so rarely used. If you want to see the channels the best option is to add a shadow channel block model and from that you can see what you are looking for ... and you get the added benefit of being able to sequence at the channel level as well. Use views to hide the extra models when you dont want to see them.

![image](https://github.com/smeighan/xLights/assets/10283944/535d9467-3dd8-4462-bac7-c4681668e2a2)

**Comment by jimswinder** [comment]
It's rarely used because it doesn't work!!  lol

xlights is starting to have too many "workarounds"...

Thanks anyway..
________________________________
