### ISSUE TITLE
Adding Duo2Go support in the wled.xcontroller file

### ISSUE THREAD

**Issue by jasonsomers** [smeighan/xLights#3828]
We  at RGB2Go would like to request that our Duo2Go controller be added to the wled.xcontroller file 

```
    <Controller Name="RGB2Go-Duo2Go">
        <Variant Name="ESP8266 v1.x" Base="WLED:BaseWLEDSettings">
            <MaxPixelPort>2</MaxPixelPort>
            <MaxSerialPort>0</MaxSerialPort>
            <Port1>2</Port1>
            <Port2>1</Port2>
        </Variant>
    </Controller>
```
Thank  you for your consideration!
-Jason

**Comment by computergeek1507** [comment]
the pin configuration is the same as WLED ESP8266 controller

**Comment by jasonsomers** [comment]
Scott,
That controller is listed with three outputs. The Duo2Go only has two.
It has caused a little confusion with my customers, so I figured I would
ask.
Thanks,
Jason

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by computergeek1507** [comment]
added
