### ISSUE TITLE
Text or  "Tune to Sign" as a model

### ISSUE THREAD

**Issue by Beldwain** [smeighan/xLights#383]
I have several "Merry Christmas" signs that light up on a single or duel channel.  Others may have static Tune to Sign" and want a model. To make these in a representative way with text for the preview is not easy and very time consuming.  

Is there an easier way or could something like this be added into xLights?

**Comment by stevegiron** [comment]
You could make the sign part of your background image. You will need to create a model for your items that you want to view in the sequencer preview.

**Comment by Beldwain** [comment]
Yes, I understand, it's the words that light up on the sign that I'm trying to make more simple, not really drawing the sign.

**Comment by stevegiron** [comment]
You just need a big custom model and resize to fit your preview.

**Comment by Beldwain** [comment]
Yes, I did that, I was just trying to find out if there is an easier way to do words that light up on a single channel.  Rather than drawing letter by letter or copying from my font application to excel, could it just be an option that I want to make the model text.  Just like you can choose a type of tree or window frame or arches.

**Comment by stevegiron** [comment]
There is no option to do that now. I suggest you change your request to add "Tune to Sign" as a model. It may or may not be implemented. It's developer's choice.

**Comment by Beldwain** [comment]
Sound advice, thanks, I have updated this.

**Comment by AzGilrock** [comment]
I could see this turning into a big mess trying to provide all the different fonts and whether you want the same channel for every letter or a different channel for every letter.  It's probably best left as a custom model since everyone might want to draw the letters differently for the way they've constructed their display element.  What would be good is for us to create a better method for users to share models so that they could be imported/exported from the GUI without requiring xml file editing.

**Comment by dkulp** [comment]
I kind of wonder if a PNG image could somehow be used for a single channel sign.   Basically On/Off to display the image.     Probably could even do something crazy with the PNG alpha channel to support RGB types (take the color/intensity for the alpha to mimic a back light or something).

**Comment by damon-atkins** [comment]
Use an image to represent the on or off state with a transparent background, which would break other things..... Or better maybe allow an image background to be shown behind the definition of a customer model.

**Comment by AzGilrock** [comment]
I think the best way to implement this would be the PNG image already suggested so I opened a new issue to cover that idea and will close this one.  Issue #687.
