### ISSUE TITLE
FPP Connect is failing in .09 as it tries to upload to F16V4 in bridge mode

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3833]
It would seem that in .09 it is not showing the bridge mode falcons which is okay, but it still seems to silently try to upload to them causing things to just die. Attach is a log from Jeff in the zoom room. You can see at the end that it is trying to upload to the falcon and gettting a gateway timeout. If he rolls back to .08 it shows in the fpp connect, it is unchecked and hence it works fine uploading to his 1 fpp instance and skipping over the various bridge moded falcons.

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/11658786/xLightsProblem.zip)

**Comment by jsander10** [comment]
Do you have any Questions let me know.
