### ISSUE TITLE
When using command-line render option, empty fseq is created on some layouts

### ISSUE THREAD

**Issue by merryoncherry** [smeighan/xLights#3836]
**Describe the bug**
When using the --show and --render command line arguments to xLights, sometimes the .fseq is full of black only.  The log shows that the renderer jobs were aborted.  This affects some layouts, but not simple ones.

**To Reproduce**
Use the --show= and --render options to render a sequence on certain layouts.  Simple layouts don't show the problem, the one that I know shows it belongs to a vendor, Magical Light Shows. Saving the layout right before render has no effect.  It doesn't seem to depend on the sequence.  I can package up a simple sequence on the layout but maybe should not attach here.

**Expected behavior**
Produced .fseq rendered with fidelity to what you'd get if you manually opened the sequence, rendered, and saved the .fseq.

**Versions (please complete the following information):**
 - OS: Windows 10
 - 2023.09; master as of 6/10/23

**Additional context**
Last year I automated the render using the HTTP API.  This year I have some inclination to also sometimes render using the --show= and --render xLights command line arguments.  Those options are not working for some show folders.  

As near as I can tell, the xLights frame is created, and then a chain of callAfter is initiated that will open, render, and save the sequence .fseq, and do callAfter to handle the next sequence, and so on.  The problem I have is that something is aborting the render job, so the .fseq produced is a save of empty data, and there is no failure notice.

The "something" aborting the render job is WORK_MODELS_REWORK_STARTCHANNELS, on or about TabSetup line 1103 where it says "abort any render as it will crash if the model changes" and calls AbortRender().  So the start channel rework is aborting the render started by the app when it starts.  (This layout does refer to universe+channel start channels; not what I usually work with, not sure if it is related.)

I have a working patch that does something slightly more convoluted than the original callAfter chain:
1. Detects if any renderer jobs were aborted after issue and passes that info to the render callback
2. If aborted, callback repeats the rendering callAfter (at most once), otherwise saves and calls the next callAfter

The question is whether this is a reasonable approach for this issue, or if there is a simple way to reorder things to prevent the abort, or whether there is a better, less fragile way to launch render from the command line, or something else I haven't considered?

**Attachments**

**Comment by computergeek1507** [comment]
There is a bug that everytime xlights load the rgb effects file it call the "WORK_MODELS_REWORK_STARTCHANNELS" command. It also regenerates the channel buffer. It started happening a while ago(2020ish) It related to the Layout code that has a queue to process the event to prevent duplicates. It hard to debug and I havent been able to fix it.
