### ISSUE TITLE
OpenDMX stopbits is not always set to 2

### ISSUE THREAD

**Issue by t2lights** [smeighan/xLights#3837]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When using OpenDMX the stopbits get set to 1 when Output To Lights is turned on for the first time after starting Xlights.  Every subsequent time the Output To Lights gets toggled on the stopbits will get set to 2.  If I close Xlights and reopen again the same thing happens.

**To Reproduce**
- I used a serial port monitor to see how many stopbits are set when the serial port is opened.  The program I used was AccessPort 1.37 from SUDT.com.
- Add an OpenDMX controller.  I have attached a screenshot of how I have the controller setup.  I did not choose a vendor because I am using a USB to RS-485 dongle from FTDI and that was not an option.  The part number is USB-RS485-WE-1800-BT.
- The first enable of Output To Lights sets the stopbits to 1.
- All subsequent enables sets the stopbits to 2.
- I have attached a screeenshot from the AccessPort software showing this behaviour.

**Expected behavior**
I would expect that the stopbits gets set to 2 everytime Output To Lights is toggled on when using OpenDMX.

**Screenshots**
I have attached two screenshots.  One for the OpenDMX controller setup and another of the serial port monitor.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: 2023.08 but I have seen this behaviour also with 2021.01

**Additional context**
I noticed the problem because I have a pair of LOR CTB16PC V1 controllers running firmware version 4.32 that will not become active when the stopbits are set to 1 but will always become active when the stopbits are set to 2.

**Attachments**
- Just the two screenshots.

Please let me know if more information is required or if this is expected behaviour.

thank you,

tom.
![OpenDMX setup](https://github.com/smeighan/xLights/assets/136258184/0c52b049-a590-45f9-b83f-990063203952)
![OpenDMX Stopbits](https://github.com/smeighan/xLights/assets/136258184/a79c76b7-16fa-48a0-9cd7-57f66d57b9ad)

**Comment by computergeek1507** [comment]
thanks for finding this, fixed with b16f14b27e1d75bb34e00e22a68a82812b43d657
