### ISSUE TITLE
2023.09.2 issue, moving head beams not showing correctly and DMX floods are showing up as weird shapes.

### ISSUE THREAD

**Issue by JBanbor** [smeighan/xLights#3839]
**Describe the bug**
When using moving heads in a sequence you can not see the beam like they are off but if you select the effect you can see in the model preview the beam shows up. I have a preview in 3d when I move around the 3d space certain beams show up while other disappear. 
Also when I updated to v9 my dmx flood lights became very weird shapes. 

**To Reproduce**

Drag around 3d space in visualizer with dmx floods and shapes will appear. 

Move around 3d space with moving heads and you will see that random points will trigger some to show the beam and some do not. It does the same thing with a sequence.. 

 
**Expected behavior**
On vision 2023.08 the beams showed up in the preview normal where I could have my view from the front of my house and see all 4 and not have to move all over the 3d space for them to show up. 
As for the flood lights they showed up as a triangle or circle depending on how I had my X,Y,Z set up. 

**Versions (please complete the following information):**
 - OS: MAC M1, (Monterey)
 - xLights version 2023.09.2 

**Youtube link to video** 
https://youtu.be/5UICo5xEfS8
Video of showing what's happening in layout when you go drag around 3d space with moving head beams and DMX flood lights. 

This layout was created for this test but my person layout does the same thing..

**Comment by dkulp** [comment]
Fixed on master, will be in the next release.
