### ISSUE TITLE
Xlights crashes when adding effects to timing track on Mac.

### ISSUE THREAD

**Issue by Finnagan** [smeighan/xLights#3845]
Hoping for some assistance with xLights crashing. New install of about 2200 pixels on my house and all working great with WLED but I’m looking for some better effects. I'm running v 2023.09.2 on a mac running 11.7.1.

I watched the video tutorials by Keith up to part 4 but any time I try to drop an effect onto the timing track of a poly line the program crashes but I have no issues with a single line. Tried Facebook and was directed here with the problem.

Log file can be found at 
https://www.dropbox.com/s/74sbb22mjszvt19/xLightsProblem.zip?dl=0

Thanks for any help.

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
I dont seem to be able to reproduce it on windows. with .09 or the latest build.

**Comment by STucker001** [comment]
Thanks for looking at it, i gave up on the mac and picked up an old pc to get going on it for now.

**Comment by dkulp** [comment]
Cannot reproduce on M1 or M2 Mac either....

**Comment by dkulp** [comment]
I cannot reproduce on either of my two Intel based Mac's either.  :(

**Comment by Finnagan** [comment]
Its up and running pn the PC but i since went back and reset the mac to factory settings, no restoration of old files/settings and no issues with it. Must have been something in my system settings. Thanks for the help.

**Comment by maddiane180** [comment]
Where you able to resolve this?  I am having the same issue.  When I try to add an effect to the timeline, it crashes on Macbook air.

**Comment by pbezant** [comment]
I too am having the same issue. 
<img width="452" alt="Screen Shot 2024-11-21 at 6 00 14 PM" src="https://github.com/user-attachments/assets/4a90d38f-bcb0-477f-8860-0feefb651969">

**Comment by Lugante** [comment]
I have the same issue on Mac Monterey (intel) even with factory settings. Indeed, I erased my disk and reinstalled the system completely, and the (almost) first thing I did was trying to run the xlights sequencer, but it crashed in the exact same way as before (ie when I drag an drop an effect on the time line of a sequence - even a single line, wether if it's an "animation" or a "musical sequence", wether in 20fps or 40fps...).
