### ISSUE TITLE
Frames Per Second Options include standard Video FPS

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#385]
e.g. Pal Video is 25 Frames Per Second.  NTSC 29.97

https://en.wikipedia.org/wiki/Frame_rate

**Comment by AzGilrock** [comment]
You can make it anything you want.  Just delete the FSEQ file, edit the XML file and change the sequence timing to whatever you want.

**Comment by keithsw1111** [comment]
I notice that changing the timing is not possible in the settings ... even to one of the standard timing amounts. Is this because it breaks stuff to change timing while the sequence is loaded?

**Comment by AzGilrock** [comment]
It wasn't possible before but it is now.  We now can resize the FSEQ and buffer size like we do when the duration is changed.  But some extra work would need to be done if you go from a smaller to a larger duration because then effect/timing edges might not be on a boundary.

**Comment by damon-atkins** [comment]
Any chance of getting stand FPS added to the GUI. i.e. 25 FPS...   It would make working with video sources simpler.

**Comment by keithsw1111** [comment]
Why would it make it simpler? XLights automatically adjusts the framerate to match the audio regardless of the framerates chosen. For 20fps it will drop frames when required. For 40fps it will duplicate video frames as necessary to match the frame rate. Consequently the maximum any image/audio sync is likely to be out is 25ms or 12.5ms.

**Comment by damon-atkins** [comment]
20fps creates more still images than required, for a 25fps video., enough images are created as it is.

**Comment by AzGilrock** [comment]
What "still images" are you talking about?  We don't create any images for video anymore.

**Comment by AzGilrock** [comment]
By the way when I implement this I wasn't planning on adding anymore fixed rates.  It was going to just allow you to type in the rate in an edit box.

**Comment by keithsw1111** [comment]
Damon it sounds to me like you are doing video the old ffmpeg way creating a folder full of frame images and using the picture effect to show them. We dont do it that way any more. If you use the new in 2016 video effect all the frame rate adjustments are done for you.

**Comment by AzGilrock** [comment]
We've added the ability to enter a custom frame rate.  You are limited to 1ms resolution so you can't get exactly 29.97 you can enter 34ms / 29.41fps or 33ms / 30.3fps.

**Comment by damon-atkins** [comment]
Notice that today when someone open the latest version at the Melb Mini.

**Comment by damon-atkins** [comment]
Many Thanks
