### ISSUE TITLE
Select Effect Window not selecting correct effects.

### ISSUE THREAD

**Issue by MrPierreB** [smeighan/xLights#3851]
**Describe the bug**
When you have use the Select Effect window to select multiple effects, not all selects are actually selected, and it also select a different effect than the one you clicked on.

**To Reproduce**
Add multiple single line effects to different props
Using the Select Effect Window, choose Single Strand type, select all props and then select a couple of effects.
If you select all effects, you will notice not all of them gets selected on the right, (so if you do a bulk edit, only selected ones gets updated).

**Expected behavior**
Whatever is selected in the select effect window -> actually gets selected.

**Screenshots**

Here you can see I selected the effect on the Feather Long Odd,  but on the right it actually selected Short Even.
![SelectEffectsIssue](https://github.com/smeighan/xLights/assets/25444831/b4190bd1-5e28-4a79-bb32-ecb0778c917c)

Here I select All
![SelectEffectsIssue1](https://github.com/smeighan/xLights/assets/25444831/0ca46d3b-8a4e-4160-bb1e-f1dae67cdeeb)

 - OS: Windows 11
 - xLights version 2023.09

I have also attached a zip file whic you can use.
When selecting Feather long Odd from the list, it seledct the Torch Short.

I have stepped through the code on the SelectPanel.cpp file, nothing obvious is sticking out that coudl be causing this.
After the items are added to the ListCtrl_Select_Effects and pointer data set,  i confirm each item has valid pointer,  then i tried to loop through all items right after all is added and it isn't valid for all. 

[SelectEffectIssue.zip](https://github.com/smeighan/xLights/files/11829082/SelectEffectIssue.zip)

**Comment by merryoncherry** [comment]
Good find, PR submitted.  By inspection, I think you could have problems with both the search effects panel and select effects panel, so adjusted both.

**Comment by MrPierreB** [comment]
@merryoncherry  Thanks for the fix.
I had a play with the code and tried to
ListCtrl_Results->GetItemCount() put that into int  and then use that for both inserting the item and setting the ptr ref, as it looked like i needed the index of the item to set the pointer.
