### ISSUE TITLE
xlights not displaying properly on Mac laptop.

### ISSUE THREAD

**Issue by ChazD1** [smeighan/xLights#3854]
I normally use my Mac desktop for running my show and sequencing. On occasion I'll use my Mac laptop to sequence while on the road. Recently I signed into xlights on my  laptop and it doesn't display correctly. I'm unable to see bottom of xlights application. Before this there was an issue with crashing when I tried to save a sequence, and a message was asking me to send in the report. 

OS version Bigsur 11.7.8
Xlights version 2023.3 

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

https://github.com/smeighan/xLights/assets/137739815/524886b7-3674-4ceb-9336-aeef39e01243

<img width="1440" alt="Screen Shot 2023-06-25 at 12 19 32 PM" src="https://github.com/smeighan/xLights/assets/137739815/bbef0fb3-2e3a-47
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/11862558/xLights_l4cpp.log)
07-a96b-7e21c6e3c004">

**Comment by ChazD1** [comment]
crash report 

[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/11862578/xLights_l4cpp.log)
for above

**Comment by dkulp** [comment]
Hover over one of the top corners and the resize cursor should appear and resize the window smaller. Alternatively, hit the Window -> Zoom menu option and it will resize to fill the screen and you can then resize it to what you need.
