### ISSUE TITLE
Smart T's not working with Menleon controllers

### ISSUE THREAD

**Issue by jlarsonomaha** [smeighan/xLights#3856]
When adding a matrix or tree to a Menleon controller using smart T's xlights will not add the second port to the first port to support the Smart T's under the controller tab.

**Comment by keithsw1111** [comment]
Can you post a sample layout?

**Comment by jlarsonomaha** [comment]
I packaged up a sequence that can be downloaded from here. https://1drv.ms/u/s!ArG3VWxxCDzkizdflyGj8SxFMeuM?e=tda61V  If you look at the Matrix Tow it has 32 strings that would be going to a 16 port controller. With the smart T's that would take 2 ports and put it to one port going back to the controller so that only 16 ports would be needed. Here is some info on the smart T's https://minleonusa.com/product/smart-t-2/  Let me know if you need anything else and Thank You.

**Comment by keithsw1111** [comment]
I downloaded that file and Matrix Tow does not have smart-Ts set.

**Comment by jlarsonomaha** [comment]
In 2023-09 and 2023-10 it will now allow us to check that box. When we check it as soon as we release the mouse click it goes back off.

**Comment by keithsw1111** [comment]
So it has to do with RGB+ pixel types which i can fix but do you know what chip are in these pixels?

**Comment by keithsw1111** [comment]
Wont that also be 1600 pixels per port ... an NDB cant do that many.

**Comment by keithsw1111** [comment]
Tonights build will have a workaround which will get it working ... but its not a permanent fix until we know the actual protocol.
