### ISSUE TITLE
Minor: In xSchedule viewing the menu freezes or skips playback.

### ISSUE THREAD

**Issue by dartunder** [smeighan/xLights#3859]
**Describe the bug**
Minor Issue: In xSchedule while playing a sequence viewing the menu freezes or skips playback.

**To Reproduce**
1. Start a sequence.
2. Make xSchedule the active window
3. Press Alt ( the file menu will appear and the skipping will begin )
   or click on File
   don't proceed to activate a command just let it sit like that with the file menu open.

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xSchedule version 2023.09

Note this happened by someone accidentally pressed the alt key on my show computer.  There was no obvious reason for it to not be working correctly.

**Comment by keithsw1111** [comment]
I am not sure if i consider this a problem or not. Obviously it would be ideal if it didnt but I am not sure it is even something we can fix as it is likely inherent in the windows messaging system.

**Comment by dartunder** [comment]
I agree it is not likely worth the time, but as a developer, I assume you would rather know about oddities and make that call than not and be surprised.

I ended up switching to FPP due to a new large P5 matrix.

Thank you for all you have done.

**Comment by CBenghi** [comment]
Hello @dartunder,

I might have found one issue that could cause this behaviour when you have an attached serial port. Was this your case?

Best,
Claudio

**Comment by dartunder** [comment]
No, I was not using DMX or anything serial at the time.  I'm using FPP now.
