### ISSUE TITLE
xSchedule not "working" on OS Xlights ver. 2023.09.3

### ISSUE THREAD

**Issue by drianpop** [smeighan/xLights#3861]
Hi i'm having a small proble while tryin to run show at xschedule, the main things is i know that xschedule is no more compatible with xlights since ver 2020, but the thing is, when i open .fseq the lights do random things, but when i try the same while opening .iseq runs the show BUT, making work 2 of the 4 LED equipment run as same, while each 4 has diferent stuff on it.

So my question is, is there something that is wrong on the config or i should reopen it on an older version of xlight to run xschedule (wich im afraid to do cause i dont know if the Fx gonna be the same)

Idk if i explained well, hope someone can help me :)

**Comment by derwin12** [comment]
I believe the fseq format was changed/enhanced in the past few xlights releases - this is likely to have broken the old xschedule on mac.

**Comment by drianpop** [comment]
and what can i do?

**Comment by computergeek1507** [comment]
You could save the FSEQs as V1

**Comment by dkulp** [comment]
Your best long term solution is to get a Raspberry Pi and get FPP installed.  Parallax has the Pi4 2G model in stock right now.

**Comment by drianpop** [comment]
> Your best long term solution is to get a Raspberry Pi and get FPP installed. Parallax has the Pi4 2G model in stock right now.

im gonna investigate aboout it, i just upgraded from arduino to ESP32 i think i will have to stay like this for a long time, but there's a place where i can know more about it?
