### ISSUE TITLE
additional FSEQ VIDEO for a second projector / tv rather then a virtual matrix

### ISSUE THREAD

**Issue by jamesssydney** [smeighan/xLights#3864]
Dear Xlights Developers.

Firstly thank you for this amazing software!!!

I'm using XScheduler to run my show and currently  have 1 data projector, which is running the video file via the FSEQ VIDEO option. I'm wanting to add a second projector, which will be running a different video, but don't want to loose the quality of the video by using the Virtual Matrix. Would it be possible to add an additional FSEQ video so I could run two separate videos plus the Xlights sequence. Hopefully I've articulated what I'm after.

Kind regards

James - Sydney Australia.

![FSEQ VIDEO](https://github.com/smeighan/xLights/assets/138438869/c57f9fc7-6c18-46e1-b69e-c9e8e6ca3d23)

**Comment by keithsw1111** [comment]
You can do this by editing the playlist as an advanced playlist and adding additional concurrent video playbacks.

**Comment by jamesssydney** [comment]
Thank you worked a treat. I watched you video very helpful!
________________________________
