### ISSUE TITLE
FPP V7 Master and .10 of xlights is failing on fpp connect with RC 400

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3865]
User came into zoom room. His fpp connects are only sending a few kb files to his master and remotes. He is using v2 sparse. The fpp connect process goes thru creating the fseq file (for v2 sparse) then closes and quits the fpp upload process.

It appears the handshake with GET is RC 400. Notice this was the case for both the mp3 and the fseq file.

The fseq on the file system is close to 1Gb. Prior years this would have pushed a 200+MB file to each remote (panels).

![image](https://github.com/smeighan/xLights/assets/4643499/5423ae8d-689a-49c5-ae6d-05fbc255420e)

(For Don McCrosky)

**Comment by derwin12** [comment]
![image](https://github.com/smeighan/xLights/assets/4643499/27527505-43be-4894-bf64-7d5498a36e0a)

**Comment by DonMc33** [comment]
Noticed there is another user that reported FPP connect file upload issues, see Falcon Christmas/FPP issue #1513

**Comment by dkulp** [comment]
I'd likely need to see the json from the "http://192.168.0.48/api/system/info" call.   In particular the ranges.   It's generating the sequences with only 8 channels which is the default if there are no outputs configured and enabled on the system.

**Comment by derwin12** [comment]
Hoping Don can provide this. I can add that we checked controller tab it
had panels defined for the remote and outputs configured for 200000?
Channels on the panels tab.

**Comment by DonMc33** [comment]
Info from requested link in Dan's note.... please advise if additional info is needed.
{"HostName":"ShowController","HostDescription":"Raspberry Pi (Pi 4)","Platform":"Raspberry Pi","Variant":"Pi 4","SubPlatform":"Raspberry Pi 4 Model B Rev 1.1","backgroundColor":"","Mode":"player","Logo":"Raspberry_Pi_4.png","Version":"7.x-master-151-ge937b018","Branch":"master","multisync":true,"OSVersion":"v2023-04","OSRelease":"Raspbian GNU\/Linux 11 (bullseye)","channelRanges":"0-7","majorVersion":7,"minorVersion":1000,"typeId":13,"uuid":"M1-100000000f7bed88","Utilization":{"CPU":28.301886792452834,"Memory":7.013431395561119,"Uptime":"1 min","Disk":{"Media":{"Free":49316171776,"Total":62578692096},"Root":{"Free":49316171776,"Total":62578692096}}},"Kernel":"6.1.21-v8+","LocalGitVersion":"e937b01","RemoteGitVersion":"Unknown","UpgradeSource":"github.com","IPs":["192.168.0.48","192.168.1.48"]}

**Comment by DonMc33** [comment]
JSON file from 192.168.0.48
[ShowController_all-backup_v7_20220912210301.zip](https://github.com/smeighan/xLights/files/11943823/ShowController_all-backup_v7_20220912210301.zip)

**Comment by derwin12** [comment]
Don, am I correct you didn't have anything defined on the master..so
channel count was essentially 0.

**Comment by DonMc33** [comment]
On the Channel Outputs tab the E1.31/Arcnet/DDP/Kinet has the "Enable Output" selected as well as "Multi Threaded".  None of the other output tabs are enabled or have outputs defined.
[Master Channel Ouputs.pdf](https://github.com/smeighan/xLights/files/11943966/Master.Channel.Ouputs.pdf)

**Comment by DonMc33** [comment]
Correct. Also added JSON file to case and screen snip of the only Channel Outputs tab with anything selected to the case. Sent from my iPhoneOn Jul 3, 2023, at 10:01 PM, Daryl ***@***.***> wrote:﻿
Don, am I correct you didn't have anything defined on the master..so

channel count was essentially 0.

**Comment by dkulp** [comment]
According to the json and your screen shots, you have NO outputs defined at all.   The e1.31/DDP output is enabled, but there are no targets defined so nothing would be output there.   The pixel strings page is empty.   There are no LED panels settings.   There are no outputs defined on the "Other" page.    Thus, according to your configuration, the .48 instance is NOT outputting anything and thus doesn't need any channel data (and thus gets the default of just the first 8 channels).

**Comment by derwin12** [comment]
The .48 is the player .. and has nothing .. its the remotes not getting channels. .82 in the pic above was the one that he was testing although there are numerous very similar other remotes. Do you need .info from .82 remote?

**Comment by DonMc33** [comment]
Attached is the json file for 192.168.0.82 remote.

[MatrixPole3_all-backup_v7_20230704112435.zip](https://github.com/smeighan/xLights/files/11951133/MatrixPole3_all-backup_v7_20230704112435.zip)

**Comment by DonMc33** [comment]
Issue resolved, FPP connect now uploading sparced sequences.  There are 9 3b+ Rpi's that connect to Colorlight cards in the display, all 9 of these had the following error stated on the status screen of FPP "Colorlight: Error getting indiex of interface, could not initialize ouput type Colorlight5a75, check logs for detail."  Each of these rpi were updated from FPP6.3 in place to FPP7 master.  

Found  the interface names was not selected (blank) on the LED Panels page.  Set up persistant names for network settings and then selected appropriate interface on LED Panels page, saved, rebooted and errors were no longer displayed on rpi status page. 

Via FPP connect, uploaded a sequence to master and remote FPP devices successfully.  Appears by not having these Pi's FPP Panels interface selected properly impacted successful FPP connect sequence uploads.

**Comment by derwin12** [comment]
Ron R in zoom is facing the same situation. Latest Master with latest xLights. Tried uploading V2 and V2 sparse. Similar log file. RC400 after the /meta 
Turns out Ron had a bad file named .fseq. We went in the terminal and removed all the .fseq and repushed.
Had a special character in pokemon.fseq  (some weird e character)
