### ISSUE TITLE
Tree model - No zigzag option

### ISSUE THREAD

**Issue by Mark79864** [smeighan/xLights#3866]
Would like the option for the tree model not have have 'zig zag' node layout.

Bunnings and Walmart mini trees tend to have position saving start pixels for each strand.
This means the model in xLights needs to have the start of each pixel strand at the top of the mega tree model.
https://auschristmaslighting.com/threads/pixels-in-parallel-yet-still-addressable.13976/
Wiring exactly like this:
![image](https://github.com/smeighan/xLights/assets/72605347/00c738fb-e7ab-4745-b414-5fde5a8948bc)
![image](https://github.com/smeighan/xLights/assets/72605347/240cc9ab-119f-484f-ab92-df39529a8d27)

Images above is using the icicles model. Using a mega tree model as a shadow model on the icicles is a solution at the moment.

I would like to ask if there is a way to change the 'tree' model to have a wiring option for 'no zig-zag'.

**Comment by dartunder** [comment]
------------ Hint for a developer - ---------
Code like below seems to work, but I don't know how to change the UI to support this.
----------

in MatrixModel.h

add protected variable:
   bool _ZigZagNodes = true;   // Daniel Hacquebord ZigZagNodes 2023-08-06
            
change this function:

        virtual bool StrandsZigZagOnString() const override
        {
            return _ZigZagNodes; // Daniel Hacquebord ZigZagNodes 2023-08-06
        }                    
----------------------------

 MatrixModel.h  4 places in InitVMatrix / InitHMatrix  ........

 if (_alternateNodes) {
                        if (isBotToTop) {
                            if (y + 1 <= (PixelsPerStrand + 1) / 2) {
                                Nodes[idx]->Coords[0].bufY = y * 2;
                            } else {
                                Nodes[idx]->Coords[0].bufY = ((PixelsPerStrand - (y + 1)) * 2 + 1);
                            }
                        } else {
                            if (y + 1 <= (PixelsPerStrand + 1) / 2) {
                                Nodes[idx]->Coords[0].bufY = (PixelsPerStrand - 1) - (y * 2);
                            } else {
                                Nodes[idx]->Coords[0].bufY = (PixelsPerStrand - 1) - ((PixelsPerStrand - (y + 1)) * 2 + 1);
                            }
                        }
                    } else {
                        Nodes[idx]->Coords[0].bufY = isBotToTop == (segmentnum % 2 == 0 || !_ZigZagNodes) ? y : PixelsPerStrand - y - 1; // Daniel Hacquebord ZigZagNodes 2023-08-06
                    }
                    
 ------------------------------        
 
 Then implement this property in the tree model, which inherits from the matrix model.

**Comment by bradywassam** [comment]
I'm having the same issue. Everything starts at the top.

**Comment by Pikokosan** [comment]
Same issue here. I'm not finding a good full solution to this.

**Comment by AzGilrock** [comment]
This is a case where configuring manually like we did in the old days works.  What you want is the same layout as a 16 string tree of 23 pixels per string with a top start location.  Oh but everyone wants to automatically configure their controllers which leaves you stuck with converting that to a Custom model.
