### ISSUE TITLE
Saving Sequence settings triggers render?

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#3872]
Using current xlights 2023.10 on Win11

Quick question, when hitting done in the sequence settings dialog, it triggers render,
Is this intended??

Dont believe iv noticed it doing this before, but thought best to check.

**Comment by AzGilrock** [comment]
Looking at the code there are conditions that can trigger render but it should only be if you mess with the data_layers in that dialog which I wouldn't think anyone uses anymore.

**Comment by AzGilrock** [comment]
After looking into again due to #3898 I see why this is happening and we will look into a fix.  I'll close this issue and we can track it in the other one.
