### ISSUE TITLE
Can't Select "Auto Layout" for certain WLED controllers since 2023.10

### ISSUE THREAD

**Issue by jasonsomers** [smeighan/xLights#3881]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When adding the WLED/RGB2Go-Duo2Go controller, to Xlights the "Auto Layout Models" option is not shown properly, so it cannot be checked. That prevents visualizing and uploading.

**To Reproduce**
1) Add a new controller
2) Select WLED as the Vendor and RGB2Go - Duo2Go as the Model

**Expected behavior**
The "Auto Layout Models" line does not appear

**Screenshots**
(https://drive.google.com/file/d/1otghPp2_Fxj3J717Ep4KNk-c6jnR1Ibt/view?usp=sharing)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2023.10

**Additional context**
Problem disappears after uninstalling and re-installing 2023.09

Thanks!
Jason Somers

**Comment by computergeek1507** [comment]
I noticed this too, The workaround at the moment is to deselect the controller and reselect it.

**Comment by computergeek1507** [comment]
broke with e5b9b80ce50ef2ba71cbaf5d237f22ee800c95e3

**Comment by computergeek1507** [comment]
Left is after selecting vender/model/variant. Right is after reselecting the controller. Lots of fields are missing or showing incorrect data.


![image](https://github.com/smeighan/xLights/assets/2293065/7ca3f58f-b176-404d-96ba-bd0b9913be46)

**Comment by jasonsomers** [comment]
Scott,
I see that it works not when I install my Dig-Uno....
[image: image.png]

However - when I install my RGB2Go-Duo2Go, it does not - it is still
missing the "Auto Layout Models" field
[image: image.png]
-Jason

**Comment by jasonsomers** [comment]
Can this issue be re-opened or should I open a new one?

**Comment by computergeek1507** [comment]
I look at it soon

**Comment by computergeek1507** [comment]
fixed with 5a85d6c8251fb91f40a225c513446ed2ef09cfe0
