### ISSUE TITLE
Shapes lose pixel data as they get larger

### ISSUE THREAD

**Issue by KinzuaKid** [smeighan/xLights#3883]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When the shape effect is used to create large in-filled shapes, past a certain size, those shapes have black pixel data inserted by xLights that appear to emulate a primitive shadow effect, but only serve to make those shapes "wrong" or only partially filled.

**To Reproduce**
1. Setup a matrix model 96H*192W
2. To a sequence and that model, add the "Shape" effect: object circle, thickness 100, count 1, start size 45, 55, and 65 (for comparison), no movement or random options selected, lifetime 100.
3. Observe that at size 45, the circle looks pretty good. No "holes". Now observe that as you increase the size to 55 and then 65, the number of "holes" (black pixels) increases in a pattern that starts to resemble faux shadows or curvature lines. You can substitute an SVG file and observe the same behavior.
4. Other shapes exhibit the same symptoms, but at different values for shape size than for the circle.

**Expected behavior**
I expect it to draw a filled circle, not a partially filled circle. When using the shape effect to build a mask/unmask, having those dead pixels makes the mask/unmask function incorrectly. Bonus: if I want to draw a "wheel of Swiss Cheese" I don't need to draw the holes! That said, I want a circle, not a Swiss Cheese wheel.

**Screenshots**
One available.

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2023.11

**Additional context**
None. Pretty straightforward on its own. Shapes drop pixel data as they get bigger.

**Attachments**
Image and a packaged sequence are located at the Dropbox link, [here](https://www.dropbox.com/sh/8j6ikyvub8fz5fu/AADgCuihKuFQjmOFBYgLv3Z5a?dl=0):

In long form, just in case:
https://www.dropbox.com/sh/8j6ikyvub8fz5fu/AADgCuihKuFQjmOFBYgLv3Z5a?dl=0

**Comment by merryoncherry** [comment]
What's really happening is that the circle is made out of points, and with a big enough radius those aren't touching so there are moire holes.

Someone may fix that, but if you are in a hurry and need a workaround that only covers a single circle like that, I'd suggest that Ripple (with "Solid Inward", enough ripples/spacing, movement none) can produce your filled round mask or masks with SVG shapes.  If only a circle is needed, shockwave is a little simpler to use, just turn off "blend edges", but it does work in pixels instead of percent so be aware if you are sharing the sequence with others.  Images - always a fallback option.

There are probably others.

**Comment by KinzuaKid** [comment]
> 
> There are probably others.

Indeed. If you introduce "blur" those spots will at first get worse, then, at about 5 or 6 blur, they will disappear. The downside is that the outer edge of the shape is now fuzzy instead of sharp. I hadn't thought about using images, however. That might be the best option, since I'm just using a shape that large as a mask. Black and white only.

A workaround is a workaround. I'll take it. I'll update my request from a bugfix to a user's manual update. If someone would just note in the manual the explanation in your comment and that it applies to ALL shapes, (so be careful using huge sizes on pixel dense models, and so forth), I think these workarounds then make a fix unnecessary.

That picture idea is simple, elegant, scales to anything up to your image canvas size, and the mask can be any shape. Perfect.
