### ISSUE TITLE
Arches Perpendicular to House don't render correctly

### ISSUE THREAD

**Issue by fernandop78** [smeighan/xLights#3884]
[Testing.zip](https://github.com/smeighan/xLights/files/12141987/Testing.zip)
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I have arches over my sidewalk and I noticed this past season the effects were off.  I traced it back to anything after version XLights64_
2022_01.  Several folks in the Zoom room were able to recreate the issue but no luck figuring out how to fix it.  I've attached my presentation but from what I can tell it stopped treating each arch as a line in 2D and now sees it as a single dot.  So an effect like pinwheel or meteors turns on the entire arch instead of just the portion needed.

**To Reproduce**
Please reach out and I can send a packaged sequence as an example.  To produce the effects I was used to you will need to download XLights64_2022_01 or earlier.  To see the bug you will need to download anything after that version, re-render the sequence and play it.  I've added more info/screenshots in the presentation.

**Versions (please complete the following information):**
 - Windows 10

**Attachments**
- Presentation
- Packaged Sequence upon request
[Arch Seq Issue.pptx](https://github.com/smeighan/xLights/files/12140840/Arch.Seq.Issue.pptx)

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by AzGilrock** [comment]
If its perpendicular that's the way its going to render if your render buffer is Per Preview.  You can change how it renders by changing the render buffer style for that model

**Comment by fernandop78** [comment]
I've tried changing the render buffer style but it still doesn't produce the effect correctly (it used to work before the version above).  I guess the bug I'm trying to report is how the 2D view of my layout looks.  My layout is done in 3D but when I look at how the 2D of my arches looks it doesn't represent what I have.  A 2D view of my arches used to look like a vertical line for each arch but after the version above it looks like a dot for each arch.  I put some screenshots of what I mean in the attached presentation.

**Comment by AzGilrock** [comment]
So post a sequence with a couple effects that show the problem.

**Comment by fernandop78** [comment]
> So post a sequence with a couple effects that show the problem.

Attached, called Testing.zip

**Comment by computergeek1507** [comment]
Have you tried 2023.11 I think Dan attempted to fix this.

**Comment by dkulp** [comment]
Seems to be a bug/issue in the. ThreePointScreenLocation for models that handle the height themselves. (thus, candy canes are likely also affected).   The "height" is only using the difference between Y locations.   If you adjust the arch so it's slight diagonal, you'll see it start creating and tiny arch on the 2D.   

Anyway, I'm kind of looking into it, but not sure how much time I can do so right now.

**Comment by fernandop78** [comment]
> Seems to be a bug/issue in the. ThreePointScreenLocation for models that handle the height themselves. (thus, candy canes are likely also affected). The "height" is only using the difference between Y locations. If you adjust the arch so it's slight diagonal, you'll see it start creating and tiny arch on the 2D.
> 
> Anyway, I'm kind of looking into it, but not sure how much time I can do so right now.

Thank You!!!  For now I'll continue to use the older version of XLights.  So happy this will get looked at and hopefully fixed in the future.  Again, thank you for everything yall do!

**Comment by AzGilrock** [comment]
I think this can be fixed by just removing all the "is_3d" decisions in PrepareToDraw for the ThreePointScreenLocation.   The formula for calculating the line length isn't working in 2D because the Z axis is the only one that has any length to it and its currently setting Z to 0 in 2D.  I've gotta run right now but I can checkin what I think fixes it later and tell me if I've missed something.

**Comment by AzGilrock** [comment]
Seems to render fine with the change I'm about to checkin

<img width="426" alt="Screenshot 2023-07-25 at 7 25 25 PM" src="https://github.com/smeighan/xLights/assets/2024669/26bd1e08-24ee-411e-a0e4-cb14338877ad">
