### ISSUE TITLE
Purge Backups issue

### ISSUE THREAD

**Issue by Poporacer** [smeighan/xLights#3885]
**Is your feature request related to a problem? Please describe.**
We have had a lot of people come in this year that are just getting started for the new year and have munged up their layout and/or Controllers and have the Purge Backups older than 90 days configured, so they have no backup to restore. (I think there is a Sequence vendor that recommends this setting?)

**Describe the solution you'd like**
In the Purge Backup routine, keep the most current backup that falls within the Purge date threshold and delete the others. That way there should always a backup to restore from (In theory anyway)

**Describe alternatives you've considered**

**Additional context**

**Comment by derwin12** [comment]
@computergeek1507 I think you can close this one ..

**Comment by Poporacer** [comment]
Fixed
