### ISSUE TITLE
Render hangs in 2023.10/11 on MacOS

### ISSUE THREAD

**Issue by smtpboy** [smeighan/xLights#3886]
**Describe the bug**
When rendering the sequence "Gloria" from Inspire Light Shows, the render will hang with a couple of groups sitting at "Waiting to start frame 3621" - this number will change slightly from render to render.  Once it hits this point, it pegs 6 cores at 100% each, and never finishes.  The only solution is to force quit xLights.  This didn't occur previous to 2023.10 as far as I can tell - this sequence ran/rendered fine previously and this hang only happens on Mac, it renders just fine on Windows in both .10 and .11.  This happens on both Intel and M2 Macs.   

**To Reproduce**
Load sequence.
Hit render.
Watch all groups/props render except for "Windows, Verticals and Yard Outline."

**Expected behavior**
Rendering should complete.

**Screenshots**
Attached.
<img width="2019" alt="Screenshot 2023-07-25 at 12 05 11 PM" src="https://github.com/smeighan/xLights/assets/71394162/7f929f6b-b72c-4f0d-8af1-a431b1510bea">
<img width="2028" alt="Screenshot 2023-07-25 at 12 06 04 PM" src="https://github.com/smeighan/xLights/assets/71394162/d9755d2a-1990-4d3a-8033-aeb631b79171">

**Versions (please complete the following information):**
 - OS: MacOS X 13.4.1 (happend on both Intel and M2)
 - xLights version2023.10/11

**Additional context**
Seems unique to this sequence.  Renders fine on Windows.

**Attachments**
[Sample of xLights.txt](https://github.com/smeighan/xLights/files/12163337/Sample.of.xLights.txt)

This is a commercial sequence, so i'm happy to provide it packaged up via PM.  I also attached a process sample from Activity Monitor.

**Comment by smtpboy** [comment]
Additional note: Render fails in the same manner if a clean xLights directory with only the sequence components is used.

**Comment by smtpboy** [comment]
I was able to work on the sequence more and more and finally narrowed down the issue.  It seems to be localized to a collection of Single Strand effects... I copied the effects out of the sequence into their own standalone animation sequence, and the problem is repeatable.  I've attached that sequence here... take a look at the Windows, Verticals and Yard Outline groups as the problem.  Make sure you suspend render if you make any changes that could trigger a render or it will hang xLights.
[Render Fail Example.zip](https://github.com/smeighan/xLights/files/12246167/Render.Fail.Example.zip)

**Comment by AzGilrock** [comment]
Well this is interesting.  I was about to say I did a render all and it worked just fine in 0.2 seconds.  Then I realized I was running in Debug mode in xCode.  So I ran the official xlights and sure enough its hanging.

**Comment by AzGilrock** [comment]
Makes it a little tough to debug when it renders fine in debug mode.

**Comment by AzGilrock** [comment]
Well I was able to get around the hang.  If you goto xLights Preferences, click the Other tab, and uncheck "GPU Rendering" that got it to render without hanging for me.

**Comment by smtpboy** [comment]
@AzGilrock  That was actually my first thought as well.  I tried toggling both the GPU and Hardware accelerator settings before I ever opened the issue... and it would hang with every combo of either setting on or off.  I just retried it to make certain.  It still hangs on the render with the GPU setting off, at least on the Intel iMac i'm on at the moment, I can check on my M2 MBP in a bit, but I tested the same thing there originally.

**Comment by dkulp** [comment]
There is a divide by 0 issue in the SingleStrandEffect if the effect is a single period long.  Testing a fix.

**Comment by smtpboy** [comment]
Thanks @dkulp --- you rock.

**Comment by AzGilrock** [comment]
Hmm...I wonder why it seemed to go away when I turned off GPU rendering.  I'd also like to figure out how Dan detected the divide by zero cause I didn't notice anything when running in the debugger.

**Comment by smtpboy** [comment]
Thanks @dkulp I can confirm things render properly and that is fixed in 2023.12 release.
