### ISSUE TITLE
Model Selection Issue in 2D with Y Rotation

### ISSUE THREAD

**Issue by jazakrzewski** [smeighan/xLights#3887]
**Describe the bug**
When working in the 2d layout and a model has a 90 degree rotation, clicking anywhere in the vertical plane it is in will select the model even if the area you are clicking is empty or has another prop

**To Reproduce**
https://youtu.be/Yl0yc5b5TPs

**Expected behavior**
Only click on the model selects it

**Screenshots**
Video linked above

**Versions (please complete the following information):**
 - OS: Windows 20
 - xLights version: 2023.10

**Comment by ravenridgelights-turtle** [comment]
I was able to reproduce this on mine in 2d as well but 3d works as expected

**Comment by AzGilrock** [comment]
Well that's pretty cool what's happening its actually rotating the selection area.  Its a one line code fix just need to remove the rotation matrix from the matrix being used for 2D intersection.  I'll have to check the other models but so far I only saw this issue in models that use the BoxedScreenLocation.

**Comment by AzGilrock** [comment]
Thanks for finding this but I did want to point out that for a tree model I don’t think you want to do the rotation like that.   There is a rotation parameter up in the models main settings.  I’d need to do some testing but I seem to remember rotating with one of those lower rotation parameters is not going to rotate the render buffer whereas that upper rotation parameter will affect the render buffer.  Test with some per preview effects

**Comment by jazakrzewski** [comment]
> Thanks for finding this but I did want to point out that for a tree model I don’t think you want to do the rotation like that. There is a rotation parameter up in the models main settings. I’d need to do some testing but I seem to remember rotating with one of those lower rotation parameters is not going to rotate the render buffer whereas that upper rotation parameter will affect the render buffer. Test with some per preview effects

Not sure what other parameter you are referring to? I only see this one in Size/Location

**Comment by jazakrzewski** [comment]
Didn't realize the other one was there, I'll have to test and see if one works different than the other for rendering
