### ISSUE TITLE
Hinkspix upload problem

### ISSUE THREAD

**Issue by Lenchuckd** [smeighan/xLights#3895]
Hi, I will attach screen shots, but this year adding a large mega tree which is going to be on a 16 port spi long range hinkspix receiver. I am cascading the ports, so that port 13 is actually spi 1-4, and 14 spi 5-8 etc.. at 300 per spi. But xlights is reading port 13 as only one spi and saying only 680 per port when in fact I should have 680 x 4 since i'm cascading the port..... please help
![Capture](https://github.com/smeighan/xLights/assets/74312259/c49ecf1d-4962-4b92-b3cd-38086cfe8eb3)
![Capture2JPG](https://github.com/smeighan/xLights/assets/74312259/ed26f294-b2e5-4fc4-b4de-85cd6e69bf35)

**Comment by computergeek1507** [comment]
You didn't file out the issue information, we cannot do anything to help you

**Comment by Lenchuckd** [comment]
Hi, I will attach screen shots, but this year adding a large mega tree which is going to be on a 16 port spi long range hinkspix receiver.  I am cascading the ports, so that port 13 is actually spi 1-4, and 14 spi 5-8 etc.. at 300 per spi.   But xlights is reading port 13 as only one spi and saying only 680 per port when in fact I should have 680 x 4 since i'm cascading the port..... please help 
![Capture](https://github.com/smeighan/xLights/assets/74312259/6b297381-9a1b-4179-be03-f8211ea46997)
![Capture2JPG](https://github.com/smeighan/xLights/assets/74312259/86ccfdc0-32e6-4bd1-af41-a8c65c28a0b9)

**Comment by computergeek1507** [comment]
How the data streams work with a 16 smart remote, you will not be able to drive that many pixels per port. The total pixel count added together on ports 1-4 must be under 680
