### ISSUE TITLE
Sketch Effect - add the "reset panel when changing effects"

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3896]
For consistency and to ensure things are reset prior to starting the effect again, can that feature be added to the effect.

![image](https://github.com/smeighan/xLights/assets/4643499/7b65d4ef-ae92-4f03-a94e-a81b31a8a1e8)

**Comment by AzGilrock** [comment]
I’ll look at that later.  I thought all effects have a function we call to set defaults so didn’t think it was a special case thing.  For the Sketch effect I think the default is to draw a tree

**Comment by computergeek1507** [comment]
Pretty sure effect assistant panels are reset when a different effect is selected

**Comment by derwin12** [comment]
Dropping the effect copies the previous effect each time.
![image](https://github.com/smeighan/xLights/assets/4643499/7ea5270f-0ca1-46f0-9e7c-80381ba27804)

**Comment by AzGilrock** [comment]
But did you change effects in between like the checkbox says?

**Comment by AzGilrock** [comment]
Whenever you click on any effect and then drop that effect your supposed to get a copy of it

**Comment by AzGilrock** [comment]
That setting means if you drop a different effect and then drop that effect you get a default version

**Comment by AzGilrock** [comment]
I still haven’t had time to try it though

**Comment by derwin12** [comment]
No I guess I did not .. what I did was close the prior sequence, started a new one and dropped the effect on. Should that have reset it? Maybe not?

**Comment by derwin12** [comment]
Thanks for clearing that up. Seems to be user error. Need to change effects not simply drop another in its place.

**Comment by AzGilrock** [comment]
Yeah I’m trying to remember many years ago this topic came up because someone changed it so every new drop took on the default values and I was used to getting a copy so we came up with the technique of getting a copy as long as it was the same as the last effect dropped
