### ISSUE TITLE
Option to not show strands and nodes when importing xml

### ISSUE THREAD

**Issue by jnealand** [smeighan/xLights#390]
When using import for bringing in a shared or old xml file the models for import show all the strands and nodes. I  suspect that when doing xml import most folks will be doing a model to model so having all the strands and nodes is causing us to have to scroll thru lots of unneeded lines in the mapping window.  See attached.  I have multiple arches using 300 nodes putting 300 lines in the window when I only need 1 line.
![mapping window](https://cloud.githubusercontent.com/assets/2533387/10553673/c4234138-742a-11e5-9148-9bcf7559b1aa.JPG)

**Comment by keithsw1111** [comment]
Included in 2016.33
