### ISSUE TITLE
Always on top window showing (including non xlights windows) for FPP Upload Progress Dialog

### ISSUE THREAD

**Issue by dartunder** [smeighan/xLights#3906]
in FPPUploadProgressDialog.cpp, regarding:

 Create(parent, id, _("Upload Progress"), wxDefaultPosition, wxDefaultSize, wxSTAY_ON_TOP | wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER, _T("id"));

Should this be  wxTOPLEVEL_EX_DIALOG or something other than wxSTAY_ON_TOP?

The progress dialog stays on top of other windows, even windows that are not xlights.

Tested on commit: 4d45d02

update: simply removing wxSTAY_ON_TOP results in the desired behavior ( tested on windows 11 )

**Comment by dkulp** [comment]
Just a note:  whatever is changed should likely also be update in the RenderProgressDialog.   These settings were copied directly from there.

**Comment by dartunder** [comment]
Likely, but in that case, you can close the window without canceling rendering.
