### ISSUE TITLE
Show folder is truncated in the controller tab

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3916]
When selecting a temporary show folder (and perhaps a permanent one?) if there are multiple spaces then it truncates after the 2nd space.
Directory "One Two Three" will be displayed as "One Two"

![image](https://github.com/smeighan/xLights/assets/4643499/8e0be1ae-ff1e-4c35-abf2-1ba5e3dd5806)

![image](https://github.com/smeighan/xLights/assets/4643499/271bd846-fd3f-4331-9dc4-eab2c1a5aa6d)

**Comment by derwin12** [comment]
Confirmed on the Permanent as well..
![image](https://github.com/smeighan/xLights/assets/4643499/b232414a-25ce-447d-8b34-914fa1740e51)

**Comment by AzGilrock** [comment]
That’s why programmers never use spaces in filenames

**Comment by computergeek1507** [comment]
Works for me...
![image](https://github.com/smeighan/xLights/assets/2293065/fc7856a0-9645-4880-9acc-e593f8e7c1f3)

**Comment by computergeek1507** [comment]
![image](https://github.com/smeighan/xLights/assets/2293065/d0bf6862-718e-4cdc-a499-64fc5b8f03d4)

**Comment by derwin12** [comment]
I was using the latest nightly build - the other guy was using .11 in zoom.

**Comment by derwin12** [comment]
I think its a ui drawing slowness.. it takes a bit but eventually shows for me. So not clear what other zoomer's were facing.
Lets close this and see if anyone else can duplicate it.
It is truncated UNTIL the "change temporarily again" button fills in..

![image](https://github.com/smeighan/xLights/assets/4643499/f4fb58c9-e22c-43a9-88f8-64dea94c2340)

**Comment by computergeek1507** [comment]
What are your windows scale factor?

**Comment by dartunder** [comment]
@derwin12 I'm not able to duplicate this issue any longer... can you?

**Comment by derwin12** [comment]
It seems like is just lag .. in the ui refresh. It does get there.. So I will close this.
![image](https://github.com/smeighan/xLights/assets/4643499/ec1d8cea-93d8-453a-a66e-585971e050f2)
![image](https://github.com/smeighan/xLights/assets/4643499/106f826f-d04a-4040-88fa-ffc8576c8bc7)

**Comment by derwin12** [comment]
Dart - if you have a test build .. I can try that.
