### ISSUE TITLE
v12, Windows and Dark Mode - Controllers Tab is not shown (blank)

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3921]
Couple of folks reporting this on zoom. New on 12 and Windows Dark Mode.
The controller tab is blank. If you use preferences to disable dark mode and do the restart it shows up fine.

**Comment by keithsw1111** [comment]
Is this still a problem. I have not seen anything more on it and i would expect to do so if it was still happening.

**Comment by derwin12** [comment]
No new reports of it..
