### ISSUE TITLE
keep location and size when replacing a model 

### ISSUE THREAD

**Issue by sidelights** [smeighan/xLights#3924]
**Is your feature request related to a problem? Please describe.**
It would be nice if when importing the same model to update it, and replacing a model with this model that the new model would not only keep the name of the old model but would also match the size and location.  Seems like a logical thing to do. 

**Describe the solution you'd like**
replace a model with this model, matches size and location of model it is replacing. 

**Describe alternatives you've considered**
match size prior to replacing, but you still have to put it back the the same spot. 

**Additional context**
Has been mentioned multiple times by "customers" and helpers of the main zoom room as a nice to have.

**Comment by Clyde-L** [comment]
I think this is a great feature!  When replacing a model with a model. Generally you want the model to fit where the other one did and you want it to be the same size. Good idea!

**Comment by dartunder** [comment]
This is the crude concept wanted... with so many types of models.. I'm not sure in which cases this would fail and or should not be offered.

in LayoutPanel.cpp:


            if (wxMessageBox("Merge The Submodels", "Merge The Submodels", wxYES_NO) == wxYES) {
                for (int i = 0; i < replaceModel->GetNumSubModels(); ++i) {
                    auto name{ replaceModel->GetSubModel(i)->Name() };
                    if (modelToReplaceItWith->GetSubModel(name) != nullptr) {
                        continue;
                    }
                    modelToReplaceItWith->AddSubmodel(replaceModel->GetSubModel(i)->GetModelXml());
                }
            }
        }

// add something like this...
        if (wxMessageBox("Use original size and position", "Use original and position", wxYES_NO) == wxYES) {
            modelToReplaceItWith->SetHcenterPos(replaceModel->GetHcenterPos());
            modelToReplaceItWith->SetVcenterPos(replaceModel->GetVcenterPos());
            modelToReplaceItWith->SetDcenterPos(replaceModel->GetDcenterPos());       
            modelToReplaceItWith->SetHeight(replaceModel->GetHeight());       
            modelToReplaceItWith->SetWidth(replaceModel->GetWidth());    
            modelToReplaceItWith->SetDepth(replaceModel->GetDepth());    
        }

        auto rmn = replaceModel->GetName();
        auto riw = modelToReplaceItWith->GetName();

**Comment by dartunder** [comment]
Completed by https://github.com/smeighan/xLights/commit/710c851baba6a5cac3b329a2aee5856490a2a560

**Comment by AzGilrock** [comment]
> Please close this

Curious do you not have access to close an issue or you just don't want to make that call?

**Comment by dartunder** [comment]
I do not have access to close it.   I did, however fix the issue with a PR.
