### ISSUE TITLE
Support for SK6812RGBW pixels for WLED Controllers

### ISSUE THREAD

**Issue by aadu** [smeighan/xLights#3934]
WLED has no problem with SK6812RGBW pixels internally, but xlights currently restricts support for wled controllers to just the following protocols: ws2811, tm18xx, ws2801, ldp8806, and apa102. I would love to see support for SK6812RGBW pixels as these are becoming much more popular.

**Comment by computergeek1507** [comment]
Controller support added with 7c17161
