### ISSUE TITLE
Fade Out Option For Piano Effect

### ISSUE THREAD

**Issue by dragonzpneuma** [smeighan/xLights#3935]
Would like to see a fade out option added to the piano effect.  Not to fade out the entire effect, but just to fade out each note.  Using multiple piano effects to fade out each note fades out the entire effect.  Simply turning the note on and off is impactful for a song with a strong beat but too harsh for a slow, mellow song.  Each note fading out would be more pleasant.  Could even be just for notes that are held for a specific amount of time.  Thank you for your consideration.

**Comment by sidelights** [comment]
like a timing track proportional fade on the key press ?

**Comment by dragonzpneuma** [comment]
Correct.  To simplify it, when the pink bar lights on each note, have it fade before the next note.Would probably have to be just for notes that are held for a specified amount of time, such asover 200ms.  Anything under that, the note would be too fast for the fade to be effective.  Turningthe fade option on and off could be just a tick box on the effect setting.
    On Tuesday, August 29, 2023 at 02:30:41 PM EDT, sidelights ***@***.***> wrote:  
 
 


like a timing track proportional fade on the key press ?

**Comment by sidelights** [comment]
I would also think this would be a nice thing to have.  You can 'sort-of' make that happen now if you make use of layering.  By selecting specific colors for the piano (I'm guessing you know you can choose 4), and then with an on effect above it with a layer blending style of shadow 1 on 2 and also on this same on effect set the brightness to a timing track proportional fade pointing to the timing track you can adjust the color of the key over time, in relation to the timing track itself. 

I could not get it to fade directly from color to white and black at the same time using this method.  

[pianoFade_attempt.zip](https://github.com/smeighan/xLights/files/12470119/pianoFade_attempt.zip)
