### ISSUE TITLE
Tag name on colors - colored blindness 

### ISSUE THREAD

**Issue by ducebigalow** [smeighan/xLights#3936]
I think it would be helpful for people that are coloured blind to be able to enter a tag name on a standard or custom colour along with the RGB code.  Just having the RGB code means nothing other than confirming a code, but having a name to the colour/code I think would help.  
Thank you
Shawn

**Comment by AzGilrock** [comment]
Go to the zoom room and ask them what the color is

**Comment by AzGilrock** [comment]
That was an inside joke. Everyone’s default support response is got it he zoom room now.  I haven’t even seen the RGB code I’ll need to see what we show. If it’s hex you can learn it. Like #FF0000 will be full red.  #00FF00 is full green and #0000FF is full blue.  So by how far between 0and FF the value is you can know how much of each color is set.  Not sure there is a name mapping for 16 million colors

**Comment by ducebigalow** [comment]
:) yah that might take some time.
I believe the code was in rgb.  Don't need to map all colours just an
option (for people like me) to map the ones that are the standard, but more
importantly the custom ones.  Just a thought.
Thanks for reaching out.

**Comment by derwin12** [comment]
Perhaps something like this library might help - (python version)
https://medium.com/codex/rgb-to-color-names-in-python-the-robust-way-ec4a9d97a01f
