### ISSUE TITLE
Incorrect channel order assigned in Visualise when using Cascaded smart receivers

### ISSUE THREAD

**Issue by tlabus** [smeighan/xLights#3939]
**Describe the bug**
When using Visualise with a cascaded model such as an 8-string mega tree on 2 4-port smart receivers, it incorrectly assigns channels for an item that is chained directly after the end of the last string. It will be correct until adding an item on a subsequent smart receiver that is not part of the cascade. When adding an item to the next smart receiver it is assign the channels directly after the last string of the mega tree, even though there is another model directly attached to that string.

**Expected behavior**
The item directly chained to the last string of the cascaded model should have the very next channel

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2023.11

**Additional context**
I will try to add a link to a video of this behavior soon. I have worked with some great people in the zoom room and they agreed that this is unexpected behavior.

**Comment by computergeek1507** [comment]
What type of controller, need more information about your setup.

**Comment by tlabus** [comment]
F8-P, but this happens in visualise before even uploading with and controller. Here is the video...

https://www.youtube.com/watch?v=suMdKHuZ_98

**Comment by tlabus** [comment]
In the example video, the mega tree is channels 1-7200.  When I add the star, it correctly get 7201-7350. But when I then add the Window frame, the window frame gets 7201-7596, and the star gets moved to 7597-7746. Since the star is directly attached to the end of the mega tree string 8, it should start on channel 7201.

**Comment by dkulp** [comment]
Not sure why you think it matters.   The strings on a port don't have to be continuous, particularly on an FPP based controllers.

**Comment by tlabus** [comment]
So when the is a single strand of 350 lights connected to an individual port, the 301st pixel does not have to be the next channel after the 300th?

**Comment by dkulp** [comment]
No.   xLights creates virtual strings for each prop.   FPP then combines the virtual strings together as part of the work it does.   When you upload it from xLights, you'll see separate lines for the last tree string and the star.

**Comment by tlabus** [comment]
Interesting. So in this case the 4th port on the smart receiver B would be channels 6300-7201 and 7597-7746. But with the virtual ports, that does not matter then? I learned something new. I was just concerned as I was getting the Warning of the gap at the bottom.

**Comment by tlabus** [comment]
Thank you so much guys! I appreciate the super fast responses. I was expecting to hear back in days or more, and it was just minutes. The xlights/fpp community is the best!
