### ISSUE TITLE
Perspective correction

### ISSUE THREAD

**Issue by illusionmanager** [smeighan/xLights#3940]
In the Layer Settings/Buffer menu I would like to be able to use arbitrary (non-rectangular) shaped buffers (still using 4 corners). This would allow for perspective correction of animations on for example trees. You are doing bilinear interpolation anyway, so this wouldn't slow down the code much (if at all)

I faked it on my tree with a movie by changing the content of the movie. (but you can't fake that using the supplied animations or normal movies. Here you can [see the effect](In the Layer Settings/Buffer I would like to be able to use arbitrary (non-rectangular) shaped buffers (still using 4 corners). This would allow for perspective correction of animations on for example trees. 
I faked it on my tree with a movie by changing the content of the movie. (but you can't fake that using the supplied animations or normal movies. Here you can see the effect: The first Santa has a way to big belly, the second one look much more like intended) https://www.youtube.com/shorts/pwrBqfhDCbE)
 The first Santa has a way to big belly, the second one look much more like intended) 
 
 For the user interface I would suggest clicking on an edge of the existing rectangle to move the edge, horizontally or vertically, and click on a corner to move it arbitrarily.

**Comment by computergeek1507** [comment]
I assume you were using the per preview render style? If you use per model default, horizontal stacked, etc you would not have this problem

**Comment by illusionmanager** [comment]
I'm using the default, 2D camera, not per preview render style.

**Comment by computergeek1507** [comment]
If you are using default on a group it uses per preview

**Comment by illusionmanager** [comment]
I'm confused as I have only two option to choose in Layer Setting/Buffer/Render Style. I can pick Default or Per Preview.
My model is a Custom model, a rectangular grid with a few leds missing near the top.

**Comment by AzGilrock** [comment]
Default means it’s whatever the setting is over in the Layout tab.   Bottom line is effects must be given a rectangular buffer so this is never going to be done from this render buffer settings.  It would need to be something that warps the result of an effect after it’s been rendered onto the rectangular buffer

**Comment by illusionmanager** [comment]
> Bottom line is effects must be given a rectangular buffer

of course is needs to be rectangular. But this interface tells you how to sample that rectangle. Currently you can only create smaller rectangles and move them around. But supposed the interface allows you to move the corners, the top line could be slanted. What it would mean is that this topline is the line where the top of the rectangle is sampled. It's just a matter of mapping. (in my case I would only the sides to be slanted, but the general case is to have arbitrary corners.)

**Comment by AzGilrock** [comment]
I feel like you already have options to change the perspective.  Here's a Picture dropped on a flat megatree with a Default buffer on the left and Per Preview on the right.  You can see how Per Preview maintains the original perspective and doesn't smoosh it at the top.

<img width="420" alt="Screenshot 2023-08-26 at 7 25 32 AM" src="https://github.com/smeighan/xLights/assets/2024669/f3c9ce16-b0f9-4bff-a78f-f9ceda9dbd8b">

**Comment by illusionmanager** [comment]
Wow that would be exactly what i would like to have. But how? What are the steps to do this?

**Comment by computergeek1507** [comment]
I think the problem is you probably had a mega tree that you exported to a custom model. The exported custom model will have a rounded layout which will not work well for your situation. You need to either use the default tree model or make a new custom model with the desired buffer look. Make each column each strand of your mega tree. It won't look right in the preview but it should work. The preferred way is to use the tree model but I assume you switched to a custom model due to uneven strings or some other wiring issue with the tree. You could also make a shadow model.

**Comment by illusionmanager** [comment]
O hang on, my tree doesn't look like that. My custom model looks rectangular. That might complicate things. I cannot use the default megatree, because mine has less density near the top
![snap](https://github.com/smeighan/xLights/assets/79637793/adb966dd-24c0-44c9-97b4-335e2f57e88a)

**Comment by illusionmanager** [comment]
> or make a new custom model with the desired buffer look.

This is how I defined my custom model, but how do I give that the correct buffer look?
![snap2](https://github.com/smeighan/xLights/assets/79637793/52e81d52-d616-4f00-bd0b-48c0bddd99f1)

**Comment by computergeek1507** [comment]
That should render correct if you are putting the pictures in the model. Depends on the scaling mode of the effects

**Comment by illusionmanager** [comment]
> That should render correct if you are putting the pictures in the model

I just loaded an image of a square, and the sides appear horizontally and vertically. Some where I have to tell it that it isn't a square curtain with leds, but a flat tree like thing. But where??

**Comment by AzGilrock** [comment]
You need to zip up a sample.  If your model is already rectangular there should be no squishing at the top.  We've always discouraged folks who wanted to make a tree like this.  Its not worth it.

**Comment by illusionmanager** [comment]
> You need to zip up a sample. If your model is already rectangular there should be no squishing at the top. We've always discouraged folks who wanted to make a tree like this. Its not worth it.

What files would you like me to zip? My custom model is defined rectangular, but I'm looking for the option to tell the software that the pixels in reality are closer to the top and make a mapping like in the right hand version of the picture you posted. I made the tree like this because I really didn't like all those trees with the top cut off.

**Comment by AzGilrock** [comment]
Only option I see is creating a Flat Tree like in my screenshot, exporting as Custom Model.  Re-import it and edit out all the missing stuff at the top and then renumber all the channels.  Then you have a Physical representation that matches the real world model.  It can be defined as a shadow model so that you can sequence onto your current model or the shadow version.  Other than this use case I don't much value in adding features to support the few folks that build these non-standard trees.  You build that you gotta deal with the consequences.

<img width="488" alt="Screenshot 2023-08-26 at 11 01 32 AM" src="https://github.com/smeighan/xLights/assets/2024669/e6562b1f-c51d-4ad6-9a68-ba89fe5e3105">

**Comment by AzGilrock** [comment]
Sequence that shadow model as Per Preview to prevent the squishing at the top but be aware using Per Preview you might need to scale your pictures/videos like 500%.

**Comment by illusionmanager** [comment]
> Other than this use case I don't much value in adding features to support the few folks that build these non-standard trees

i agree. I don't mind if the workaround is complicated. My suggestion is basically the way normal video mapping software works. So it is a pretty general way and could for example be useful for more than just my tree. But for only my tree there is no need to add this feature, since you found a way to work around it. I'll try your method and see how far I get.

**Comment by illusionmanager** [comment]
I'm closing this issue. Thanks for all the suggestions @AzGilrock @computergeek1507, without your help I wouldn't have been able to work around this request.
