### ISSUE TITLE
FPP Connect showing duplicates because of case?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3942]
![image](https://github.com/smeighan/xLights/assets/4643499/829fe0a1-23a6-43b2-85a7-fa27574895e4)

Not sure where it would get all the variations .. but can it be coded not to occur?

.LOCAL
.Local
.local

**Comment by dartunder** [comment]
W have a related issue where both the hostname and the IP can appear.
Can all the identified items be resolved to their IP address and used to look for duplicates and to determine proxy settings for udp out?
