### ISSUE TITLE
FPP Connect flagging an invalid IP -- perhaps because of case?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3943]
![image](https://github.com/smeighan/xLights/assets/4643499/a4e44d7c-795a-4bab-8987-6fc554c2f8cb)

If Paul-AZ re-entered this as fpp-p5.local the red goes away.
(changed to all lower case and stopped and restarted xlights - once again it is shown in red)
ver .13

**Comment by derwin12** [comment]
Fpp-projector.local fpp-projector.local also get flagged in red.

**Comment by derwin12** [comment]
Dan thinks this might be the "-"

**Comment by computergeek1507** [comment]
the regex didnt support "-"
