### ISSUE TITLE
Importing sequence from a vendor which has the same group name as your model breaks render sytle

### ISSUE THREAD

**Issue by sidelights** [smeighan/xLights#3945]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
If you have a model with the name 'Arches' for example (default name for the standard 'arch' model), and your importing a sequence from a vendor who has a GROUP called Arches.  The effects when imported will NOT have any 'per model X' render style.   This also breaks for Candy Canes, Icicles, or any model with a name the same as a vendor who has a group of the same name (I believe). 

**To Reproduce**
Create an arch model (with the default name) in a 'customer' layout, create a group name it something other than arches.   Create another layout (vendor) with a 'Arch' model with a name other than arches, and a group named Arches.   Under the vendor layout create effects on group level for the 'ARCHES' group with per model something or other.    Package the sequence and import from the vendors layout to the customer layout.  Mapping Group to group.   The resulting effects will all be default or per preview  for example but no per model anything. 

Import 

**Expected behavior**
Group effects should map to group effects regardless of group or model name.   

**Screenshots**
No screenshots provided but two different layouts provided. Vendor (source), and Customer (Target).  Including the saved mapping on how it was created. 

**Versions (please complete the following information):**
 - OS: [Win 11]
 - xLights version [e.g. 2023.13]

**Additional context**
This is NOT a new problem.  Occurred at least 1+ years ago

**Attachments**
Vendor packaged seq and customer (post import) packaged sequences. 

Customer:
[After_import_from_vendor.zip](https://github.com/smeighan/xLights/files/12459466/After_import_from_vendor.zip)

Vendor:
[VendorProvidedSeq_WhichHasTheSameGroupNameAsSingleProps.zip](https://github.com/smeighan/xLights/files/12459468/VendorProvidedSeq_WhichHasTheSameGroupNameAsSingleProps.zip)

**Comment by AzGilrock** [comment]
I don't think it has anything to do with what the names of those other single models are its probably just not importing the render style correctly.  I changed all the names and it does the same thing.

**Comment by AzGilrock** [comment]
Actually I do see the problem not sure why it didn't go away the first time I tried changing names.  I believe I see how to fix it.  We need to skip the normal "FixBuffer" call when we are creating an effect for the purpose of importing.
