### ISSUE TITLE
xLights 2023.13 crashes almost immediately on render

### ISSUE THREAD

**Issue by chuckackerman** [smeighan/xLights#3946]
When trying to render this sequence, xLights crashes almost immediately.  I wish I knew how to diagnose the log file but I can't.  I'd appreciate any help in where to turn within the sequence to correct the issue.

Here's the log file: https://drive.google.com/file/d/1MOsd7GmOaaY3Hcl5KLFBITbw2Qv5yGLg/view?usp=drive_link

**Comment by derwin12** [comment]
Under preferences, Other? 
make sure hardware video decoding is NOT enabled. Log showing crash on that - from what I can tell.

**Comment by chuckackerman** [comment]
> Under preferences, Other? make sure hardware video decoding is NOT enabled. Log showing crash on that - from what I can tell.

That solved it.  Thanks for your help.  This issue can be closed.
