### ISSUE TITLE
Clicking a model in layout sometimes selects a random inactive model.

### ISSUE THREAD

**Issue by dartunder** [smeighan/xLights#3947]
Clicking a model sometimes selects a random inactive models.

Example to reproduce: 
Take a layout and make all but one item inactive.  Click the active model, and an inactive model is sometimes selected.

Programmer Notes:

int LayoutPanel::FindModelsClicked(int x, int y, std::vector<int>& found)
This function returns multiple models when one is expected.
It should only return multiple models if the models overlap.

This must be returning true when it shouldn't for inactive models.
bool Model::HitTest(ModelPreview* preview, glm::vec3& ray_origin, glm::vec3& ray_direction)

Maybe look at commit:  [562790b] or [5e7592d]

**Comment by dartunder** [comment]
I duplicated this issue as presented by a zoom room user.

**Comment by dartunder** [comment]
I confirmed [562790b] introduced this issue.

Changing "TranslateMatrix" back to "ModelMatrix" fixes this problem but likely breaks the original issue. https://github.com/smeighan/xLights/issues/3887

**Comment by AzGilrock** [comment]
Does the inactive model overlap the one that was clicked?

**Comment by AzGilrock** [comment]
Also the description doesn’t say if it’s happening in 2D and 3D or 2D only

**Comment by dartunder** [comment]
2D
The inactive models do not overlap in any way.

**Comment by AzGilrock** [comment]
Ok I'm at a loss.  How exactly do you make a model "Inactive"?

**Comment by AzGilrock** [comment]
Ok found it under Appearance.  Didn't even know that was there.

**Comment by AzGilrock** [comment]
Ok I'm never seeing it select an inactive model when selecting a model.  What I do see is when you **deselect** a model it can cause an inactive model to be selected.

**Comment by AzGilrock** [comment]
I'm deleting that last statement because I'm finding its all over the map.  I keep getting into a state where I can't cause the problem at all.

**Comment by AzGilrock** [comment]
This is a fun one.  I have confirmed it was not my change to the BoxedScreenLocation that introduced this cause I can cause the bug without any BoxedScreenLocation models present.  Also the Active property has absolutely nothing to do with model hit testing.

So what I think is happening is when a model is Inactive the Display routine immediately exits for that model so it does not call the screenLocation->PrepareToDraw() function which is what updates the position of the model and its Matrix properties.  So then the Find routine is using a Matrix that is stale for those models.  The solution is most likely to just have the Find function skip the Inactive models.
