### ISSUE TITLE
Option to Import Effects as Locked

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#3950]
**Is your feature request related to a problem? Please describe.**
I imagine that like myself, most people that import effects don't do much with them as far as the timing is concerned.  Various effect settings are likely the only thing that is modified.

**Describe the solution you'd like**
I'm proposing another option on the import effects dialog that will import all the effects as locked.  When the effects aren't locked then it's very easy to accidentally move an effect when clicking on it (intentionally or accidentally).  If someone does this and doesn't realize the have moved the effect then that likely has unintended consequences that can't easily be fixed with a CTRL-Z since they aren't aware they did it.

**Describe alternatives you've considered**
I do this manually as the first thing after I import
* View all effects
* CTRL A
* Right click > lock

**Comment by derwin12** [comment]
Can this be set to unchecked by default to maintain prior results.

**Comment by MrPaulAR** [comment]
Or a user preference.

I like locked by default though.  Seems folks wanting to move effects from an import are the exception.

**Comment by computergeek1507** [comment]
Probably should be saved in the mapping file

**Comment by keithsw1111** [comment]
I really think locked by default is the better option.
