### ISSUE TITLE
Display background image in Submodel edit window

### ISSUE THREAD

**Issue by djulien** [smeighan/xLights#3953]
**Is your feature request related to a problem? Please describe.**
It is difficult to accurately select nodes manually when trying to set up a submodel if you are basing it on another image.

**Describe the solution you'd like**
It would be very useful to see a background image in the Submodel editing window (like it is in the Model Data node editing window).  This would allow easier selecting/tracing of nodes from various image sources.  It would also be a work-around for issue# 3110 - just use a white background image for that use case.

**Describe alternatives you've considered**
Create a new model and use the Model Data node editing window with a background image, then somehow transfer those nodes to a submodel (but this only works if none of the node#s change in the process)

**Additional context**
Ideally, allow a different background image on the Submodel than on the Model Data node editing window, but at least showing the Model's background image on the Submodel editing window would be quite helpful - you could then just change the Model's background image a few times while setting up the Submodels, then change it back to the permanent background image after the Submodels are all set up.

**Comment by computergeek1507** [comment]
If you doubleclick the row header, the node select dialog allows you to overlay an image.

**Comment by djulien** [comment]
Oh, I see there is already a background image setting on the Draw Model window.  Great!
