### ISSUE TITLE
Value Curves not showing meaningful value?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3956]
![image](https://github.com/smeighan/xLights/assets/4643499/ab169854-fe10-468c-9936-448afdbc659b)
While working on a value curve the tool tip doesn't appear to show values that are relative to the scale.
Note the example 100 to -100. The tooltip is showing decimal numbers.

**Comment by dartunder** [comment]
@derwin12 
If I understand correctly, 0.47 is the X value of the value curve from 0-1 or 47% of 100.
The -4.7 is the Y value scaled. 
How should it look?

Related Code:

        if (_vc->IsSetPoint(vcSortablePoint::Normalise(x))) {
            SetToolTip(wxString::Format(wxT("%s%.2f,%.1f -> %.1f"), time, x, _vc->GetScaledValue(y), ToReal(_vc->GetPointAt(vcSortablePoint::Normalise(x)))));
        } else {
            SetToolTip(wxString::Format(wxT("%s%.2f,%.1f"), time, x, _vc->GetScaledValue(y)));
        }

**Comment by derwin12** [comment]
According to the axis .. I would think it should be some value between -100 and 100, not .47 nor 47% 
You know .. maybe it IS right ... 0.47 might be the value between -100 and 100??

Gosh darn .. it is right!

**Comment by AzGilrock** [comment]
The .47 is the x axis.  It goes from 0 to 100%.  Basically represents the effect length.  So it’s shown the way we represent it internally as a value between 0 to 1 like dart under was saying
