### ISSUE TITLE
RGB2Go Duo2Go (and other WLED controllers) missing SK6812 protocol

### ISSUE THREAD

**Issue by jasonsomers** [smeighan/xLights#3957]
**Describe the bug**
Using RBG2Go Duo2Go:
When setting up a model, under the layout tab, SK6812 is missing from the options under the "Protocol"

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Set up Duo2Go controller
2. Add string to it in Visualizer
3. Click on Layout tab
4. Under Controller Properties, note the missing SK6812 option

**Screenshots**

**Versions (please complete the following information):**
 - OS:  Windows 11
 - xLights version 2023.13

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
![missing_sk6812](https://github.com/smeighan/xLights/assets/121630262/3e74f561-770d-474b-a197-0ece54d73ce8)

**Comment by computergeek1507** [comment]
Already added with 7c171611f52ee76b1bcdb019de9f129caf7bc368

**Comment by dartunder** [comment]
I believe they added that recently... would you like to try the nightly build and see if that fixes your issue?
https://github.com/smeighan/xLights/releases/tag/nightly 

Maybe fixed in https://github.com/smeighan/xLights/commit/7c171611f52ee76b1bcdb019de9f129caf7bc368
