### ISSUE TITLE
Buffer Stagger option working but not working.

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#3958]
Using 2023.13
The Buffer Stagger option seems to have an issue.  When sequencing and setting my Render Style to the horizontal or vertical stacked buffer style, I'm unable to unlock or activate the Buffer Stagger option.  While a few times I've gotten the Buffer Stagger option to work, most of the time I'm not able to reliably make it work.  

You can see how the options is grayed-out and non-operable in the screen shot below while selecting the Vertical Stacked buffer.  I was able to use it in a prior sequence and copy/pasted the effect with a selected Buffer Stagger time into a demo sequence to show it working. That is shown below in the video link I've posted to YouTube.

Hoping someone might have a look and see if it's working or not working on their end.  Thank you for looking into it.

Clyde

![image](https://github.com/smeighan/xLights/assets/12719816/f9afb7bd-9d01-4fdc-85c9-8388fa2f134a)

https://youtu.be/tzFWy2l6rWs?si=5bllUT0ZJGupUELk&t=381

**Comment by AzGilrock** [comment]
Couple things.  I didn't have audio but I didn't see in the video where "Vertical Stack" was actually selected.  Looked like you just kept hovering over that option and talking.  Also the screenshot above why is the "Stars on Trees" group the highlighted row but it looks like the selected effect is on the "Mini Trees" row.  Could you have had more than one effect selected?

**Comment by Clyde-L** [comment]
> 

Gil I've just attempted to change a number of the options on the effect in hopes it would unlock or open up the Buffer Stagger option. On my work computer, it doesn't seem to be doing anything different and is still unable to be changed.

**Comment by keithsw1111** [comment]
Going to need a sequence ... I tested it and it seems to work fine. Enables and disables as i change the render style.
