### ISSUE TITLE
Visualizer no longer showing virtual strings on a new line (change in brightness)

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3959]
Prior version (2022.22 and perhaps as recently as 2023.21) would should models on separate lines if something was changed from the prior model, for example  brightness. This doesnt seem to be the case anymore.
![image](https://github.com/smeighan/xLights/assets/4643499/7c63356f-c726-4ec0-b66e-aeeec6fcb439)

Port 15 is made up of various brightness'
![image](https://github.com/smeighan/xLights/assets/4643499/c14657ec-35f3-4a63-a29d-fa33b0912364)

**Comment by computergeek1507** [comment]
I think it was intentionally removed, it only did this falcons not FPP

**Comment by keithsw1111** [comment]
It was intentionally changed. To change it back you can change the following value in the falcon.xcontroller file ... but you will need to redo it after each release.

For V4
Line 170:         
change it to         <MergeConsecutiveVirtualStrings/>

For V2/V3
same change but on line 23.
