### ISSUE TITLE
Collapsed multi-layer paste ignores collapsed layers

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#396]
I copied a multi layer effect from model A and pasted it to model B with no issue.
To save screen real-estate, I collapsed the layer view on the sequencer on model B and did another paste. The end result was that the the multi-layer effect only pasted to the top layer.

I then expanded the layer view on the model and pasted again with no issue.
Not sure if it should work that way, I found it odd that it would work that way.

**Comment by AzGilrock** [comment]
The copy/paste is really supposed to be based on visible rows.  There should be no difference between copying effects from 4 layers on the same model, 4 rows of 4 different models, or 4 rows of strands, or 4 rows of nodes, or 3 rows of strands and 1 node row, etc.  Its just effects on a row being copied.  If you had Model B collapsed the extra effects would have attempted to paste onto the rows of Model C.

**Comment by stevegiron** [comment]
Ok, closing this one as it was educational and not an issue.
