### ISSUE TITLE
Window Model Does not Render On Right Side

### ISSUE THREAD

**Issue by neumaa** [smeighan/xLights#3960]
**Describe the bug**
I'm using xlights 2023.13 on a Mac and I'm having an issue where the window model is not rendering on the right side of the model.  I'm attaching screen shots and my package sequence to show what is going on.

This windows model is configured with 27 lights on top, 46 lights left/right, and 0 lights bottom.  When the model is renderend, there the lights on the right do not show but the lights on the top and left do show.  If I change the # of lights on top to 26 or 28, it works fine. But when set to 27, it doesn't work.

I joined the xlights Zoom today and shared my screen.  We tried multiple changes but ultimately they felt it was a bug possibly due to a rounding error and asked me to submit this report.  They did help me with a few possible workarounds by either using a poly line or a "Per Preview" render style.

On the Zoom, others tried my same setup without issue on the same version on Windows.  It appears to be a Mac only issue.

**To Reproduce**
1. On a Mac, load this [sequence package](https://github.com/smeighan/xLights/files/12566513/window-bug-sequence-package.zip) in xlights
2. Look at how the window model is rendering without lights on the right
3. The Poly line model renders fine but not the window model.

**Expected behavior**
I expected the right side of the window model to render and not be blank.

**Screenshots**
Screen shots attached and packaged sequence too.

**Versions**
 - OS: Mac Ventura 13.3.1 (a)
 - xLights version 2023.13

**Attachments**
![Screenshot 2023-09-09 at 12 57 10 PM](https://github.com/smeighan/xLights/assets/15722800/04b28c53-7bf6-4a2a-8c0d-98c279e61cfc)
![Screenshot 2023-09-09 at 1 05 29 PM](https://github.com/smeighan/xLights/assets/15722800/3a72a440-d037-474d-b0d8-e538690cea0a)
[window-bug-sequence-package.zip](https://github.com/smeighan/xLights/files/12566513/window-bug-sequence-package.zip)

**Comment by keithsw1111** [comment]
I tried and it works fine for me

![image](https://github.com/smeighan/xLights/assets/10283944/9915ced4-7478-4ffc-8f04-554a666de9e7)

**Comment by derwin12** [comment]
Release Mode? Mac? It was duplicated in zoom room.

**Comment by AzGilrock** [comment]
I'm not home to inspect this but the Marquee operates on the buffer its given so I'd be curious to see what that buffer looks like.  In any case a stop gap fix is just change the render buffer to single line that's how I usually run all my Marquee effects on any model that is really a single line.  I assume that buffer window it at 100% but you can double-click inside to make sure.

**Comment by AzGilrock** [comment]
If its really a size issue you should be able to see the exact same problem on a normal Matrix with the same dimensions.

**Comment by derwin12** [comment]
Matrix works .. something about the buffer for a window and odd pixel counts on the top (bottom can be zero or match the top).

**Comment by dkulp** [comment]
Seems to be a release mode issue.   Debug build works fine.   Digging in.

**Comment by sslupsky** [comment]
This problem still exists in 2023.19.  If I change the Thickness to 2 the right side and bottom segments appear.

![Screen Shot 2023-11-14 at 9 00 19 AM](https://github.com/smeighan/xLights/assets/16888734/21db434c-f91a-4ac7-bd68-ae4ec0aa8f81)

**Comment by AzGilrock** [comment]
I guess the Window models default buffer is not a single line.  I would just change the render buffer to single line and be done with it.  We should just delete the Window model and make people use PolyLine. :)

**Comment by sslupsky** [comment]
Yeah, if I use a single line buffer it works fine.  The "bug" might be related to the line thickness causing some pixels to be filtered out.  There are a couple artifacts in the screenshot.  The lower right pixel appears and two of the vertical pixels in the upper right corner appear.

**Comment by sslupsky** [comment]
Good catch.  Also, the bottom right pixel in the earlier screenshot is not quite all the way to the right.

![Screen Shot 2023-11-15 at 8 17 31 AM](https://github.com/smeighan/xLights/assets/16888734/277119ed-2f79-4d63-a5d9-d9ed99ede333)

**Comment by AzGilrock** [comment]
Yep I already saw that if you look a couple comments back.
