### ISSUE TITLE
Please add the ability to add/remove display elements to Master view from the Import dialog

### ISSUE THREAD

**Issue by cbennett6008** [smeighan/xLights#3965]
**Is your feature request related to a problem? Please describe.**
When importing a sequence, I often find myself having to cancel out, add models/groups, and go back. (or spend a while reordering things to suit a particular render order)

**Describe the solution you'd like**
From the import view, expose the button to add/remove display elements.
It would be ideal if we could also, from the import view see our display elements ordered as they are in our master view, and the imported sequence's display elements ordered by theirs, so that we could compare the display elements order side by side.
Perhaps even the ability to create an empty group while you map effects.

**Describe alternatives you've considered**
Today we are able to click cancel, add the appropriate elements to the mater view, and re-open the import tool.
We can also unzip open new instance, open the show folder, open the sequence, and then compare master view to master view.

**Additional context**
N/A

**Comment by dartunder** [comment]
Couple thoughts...
Adding a model, especially adding it to a group, can impact all previous sequences, so IMO, this should not be possible in the import dialog.

Adding an empty group could be useful, but you can save your import map, add the group, and resume work.

Sorting this list by the master view would be very helpful.

**Comment by cbennett6008** [comment]
Yea, I totally agree with what you said, I was only thinking in so far as being able to add/remove/reorder display elements that already exist to this sequences master view.

**Comment by keithsw1111** [comment]
Importing a sequence should not change your layout as you are importing a sequence ... not a layout.

**Comment by cbennett6008** [comment]
Thanks Keith,  I'm not sure I understand, isn't 'Add/Remove Elements'  on the Master view specific to the sequence, and not the layout?

**Comment by AzGilrock** [comment]
Seems strange to me to worry about render order while your importing.  It can always be changed later.  Why not just create a view that has Everything in your display.  Create a blank sequence using that View and then use that to import.  You shouldn't be messing around with having to add/remove model while importing.

**Comment by cbennett6008** [comment]
> Seems strange to me to worry about render order while your importing. It can always be changed later. Why not just create a view that has Everything in your display. Create a blank sequence using that View and then use that to import. You shouldn't be messing around with having to add/remove models while importing.

Creating a view that has everything in my display (or creating the sequence with the option for everything in my display) makes for a list of stuff in the import window that's significantly longer than my usual view, and in leaves me prone to error and a lot more scrolling as I import.  aside from my usual list of stuff, I usually only have to add a model/group or two that I already have, and frankly rather than scroll thru everything I have created, I'd just assume continue doing it that way, with a couple of iterations thru the import dialog if necessary.

**Comment by keithsw1111** [comment]
There is a lot of complexity in implementing this. I would prefer to just make it easier to find your model in the list. Dealing with this during the import process introduces a massive amount of complexity into a process that is already enormously complex.

**Comment by cbennett6008** [comment]
Well I certianly appreciate you guys taking the time to read my ramblings, You know what they say, unless you ask, the answer is always no. :)

**Comment by hoodlumj3** [comment]
I've imported a few sequences myself and yes have come up against this exact issue with having to cancel out etc... 
I understand the dialogue for matching and reassignment of models / groups during import but...
Now here me out...
What if there was a "Create groups for missing props/models/groups" checkbox option on the import matching dialogue?
That would allow any non found  p/m/g to get created in the sequence and the effects imported onto those empties. 
Then it would be up to the importer to sort out which models they assign in the empty groups by moving them around. 
This wouldn't nessesarily keep the render order but that gets lost if you actually assign evey source model into your view anyway during import. And then maybe there could be a notification that the layering is now compromised so don't expect stellar results.

**Comment by cbennett6008** [comment]
I feel like using that feature would make a disaster out of one’s layout by the second import.  Creating  a load of groups for submodels on props one will never own seems messy,  like we’re back to being better off opening both and copy/paste.

**Comment by hoodlumj3** [comment]
Hence the choice.
And also clean up
The empties, which are actually full of effects, you can delete when you've moved the effects to your own Props or vice versa move your Props into the imported groups which are full of effects. 
The second import would only be a mess if you didn't clean up from the first. 
People will learn quickly to remove empty groups if they import several sequences or not I guess. 

Flexibility is important, if someone finds importing a difficult journey because they get prompted to choose an equiv model they don't have then get prompted again for a model but have already assigned the better fitting mode earlier or have run out of models would get frustrated and cancel out and start again but create empty Props or groups before the import.  I mean you said it yourself. 
I've been there many a time so these are just my thoughts on the import process.

**Comment by dartunder** [comment]
Maybe an auto save of your current mapping ( file name automatic per sequence). So you can cancel, add what you need, and resume mapping easier?  While I could see adding one empty group upon button press it's only a convenience and you would have to go to layout anyway to fix the group so , I agree this adds complications that maybe shouldn't be done.

**Comment by cybercop23** [comment]
Allow typeahead would be great so you can jump to a model as you map. Also have a global ability to expand and collapse sub-models especially for those HD with 80+ submodels. 
Additionally, it will be good to not sort the sub-models (or have an option) since ShowStoppers has them organized  and the auto-sort messes with that.
