### ISSUE TITLE
FPP Connect to do a version check for supported versions

### ISSUE THREAD

**Issue by SRipaldi** [smeighan/xLights#3966]
**Is your feature request related to a problem? Please describe.**
Yes,  multiple people continue to be caught up by FPP connect not supporting anything greater than N-1.  This has cause hours of frustration for users and is being seen in all FB groups as well as Zoom help calls.

**Describe the solution you'd like**
During the FPP Connect scan of the network for instances, if it finds instances not on supported version it notifies the users of this case.  Either a pop up or a grayed out IP address in the UI. Basically anything except not showing the IP address.

**Comment by EricLangness** [comment]
Additionally, it would be beneficial to have notification of a non-conforming instance of FPP generated at the point of a controller configuration upload.

**Comment by computergeek1507** [comment]
It gave a warning last year

**Comment by derwin12** [comment]
Now it silently doesnt show the fpp instances .. (sometimes?)

**Comment by derwin12** [comment]
Confirmed in the .14 release. Should be able to close this.
