### ISSUE TITLE
3D Handles clip inside 3D Objects

### ISSUE THREAD

**Issue by degracode** [smeighan/xLights#3968]
**Describe the bug**
3D handles seem to clip inside 3D objects in the scene, meaning that it's quite difficult to use the handles to move an object.

![image](https://github.com/smeighan/xLights/assets/7349637/062f8bb2-bbc4-49c0-8f59-0e821be8fb22)

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Add an obj to the scene
2. Move another object (eg a model) inside the obj
3. Notice the grab handles disappear as the model moves inside it

**Expected behavior**
Grab handles should always render on top of the scene.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights 2023.13

**Comment by AzGilrock** [comment]
I provided a way for you to deal with this.  In the model properties there is a checkbox that will hide all the textures of the model and you will only see the mesh lines which allows you to grab the handles
