### ISSUE TITLE
Add the ability to add number sequence to timing tracks

### ISSUE THREAD

**Issue by Poporacer** [smeighan/xLights#3969]
**Is your feature request related to a problem? Please describe.**
If you have models that you want to animate via the State Effect but want to match the animation to an existing timing track, you have to manually align the timing marks to align with the "main" timing track.

**Describe the solution you'd like**
**Better solution below**  Say you have a timing track that follows the drum beats and you have a 4 count animation, you could set the Drums timing track as active and create 4 timing marks, 1-4, to align with the drum beats. Then you can copy and paste by cell (like you can do with effects) the subsequent timing marks so that they will align with the drum beats.

**After thinking about it, it would be better to have the ability to add a number sequence to an existing timing track.**

**Describe alternatives you've considered**
create a metronome with tags, but the timing will never match

**Additional context**

**Comment by AzGilrock** [comment]
One of the first issues is we don’t have the concept of selecting “cells” in the timing area.

**Comment by Poporacer** [comment]
I had a feeling that this quite possibly could be a major code change since timing tracks are very different than the effects grid. An entirely different animal to conquer and likely not implemented but thought I would ask in the slight chance that it wasn't that difficult.. 
    On Thursday, September 14, 2023 at 04:39:47 PM MDT, Gil Jones ***@***.***> wrote:  
 
 


One of the first issues is we don’t have the concept of selecting “cells” in the timing area.

**Comment by Poporacer** [comment]
I thought of another possible solution. Since the timing track is already there, what about a Right-Click option to add labels. Give the ability to set a sequence limit and then it will iterate through the numbers up to the sequence limit? But this might still be a bit too complex?
    On Thursday, September 14, 2023 at 05:08:44 PM MDT, Rick Harris ***@***.***> wrote:  
 
  I had a feeling that this quite possibly could be a major code change since timing tracks are very different than the effects grid. An entirely different animal to conquer and likely not implemented but thought I would ask in the slight chance that it wasn't that difficult.. 
    On Thursday, September 14, 2023 at 04:39:47 PM MDT, Gil Jones ***@***.***> wrote:  
 
 


One of the first issues is we don’t have the concept of selecting “cells” in the timing area.

**Comment by AzGilrock** [comment]
It’s a good request I’ll certainly keep it in mind when I’ve finished some other things

**Comment by Poporacer** [comment]
Thanks
    On Thursday, September 14, 2023 at 06:21:09 PM MDT, Gil Jones ***@***.***> wrote:  
 
 


It’s a good request I’ll certainly keep it in mind when I’ve finished some other things

**Comment by derwin12** [comment]
Am I missing something, why not create the states to match beats ie 1,2,3 or 4  1 is a state, 2 is another state, etc.
What states would you want to see? Or are you just looking to cut and paste to be more free-form/flexible?

**Comment by derwin12** [comment]
I can cut and paste at will in the New Timing .. i cut 4-1-2 and pasted it above...
![image](https://github.com/smeighan/xLights/assets/4643499/74699bd4-3fc2-4874-9d8e-ee51e7823f47)

**Comment by Poporacer** [comment]
I have several models that I use states, like bat flaps and Spider legs "walking" and I like to have them animated to a specific instrument, typically a drum or bass (sometimes piano) thus I would like the paste function to act the same as the Paste by Cell capability so that the pasted timing will conform to the timing cell sizes. I think adding the ability to add the number sequence to an existing timing track would be easier and actually better so that you don't have essentially 2 versions of the same timing marks.
    On Thursday, September 14, 2023 at 06:40:01 PM MDT, Daryl ***@***.***> wrote:  
 
 


Am I missing something, why not create the states to match beats ie 1,2,3 or 4 1 is a state, 2 is another state, etc.
What states would you want to see? Or are you just looking to cut and paste to be more free-form/flexible?

**Comment by Poporacer** [comment]
I think having the ability to just add a numerical sequence to an existing timing track would be a much easier solution. Maybe this video will make it a little clearer? 

https://github.com/smeighan/xLights/assets/46263877/3eeb961f-79f8-49e2-ac02-bc218a2cf7b0
