### ISSUE TITLE
FPP connect freezing 

### ISSUE THREAD

**Issue by TomDawes1** [smeighan/xLights#3970]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

FPP Connect freezes on "Probing information from FPP" popup screen 
**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

Normally jumps to next screen and select sequence to upload
**Screenshots**

**Versions (please complete the following information):**
 - OS: Mac OS Ventura 13.4
 - xLights version 2023.13
 - FPP 7.1

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/12620848/xLightsProblem.zip)

**Comment by morrydavis** [comment]
xlights seems to hang when uploading a sequencs using fpp connect I can close the windows except main xlights window only way is through task manager. files appear to be uploaded but progress window seems to stay up thats where it hangs. doesn't seem to be sequence related it has happened on more than one sequence

**Comment by derwin12** [comment]
Is this reproduceable in the later version? .16

**Comment by TomDawes1** [comment]
This has been working ok since the updates Sent from my iPhoneOn 15 Oct 2023, at 04:16, Daryl ***@***.***> wrote:﻿
Is this reproduceable in the later version? .16
