### ISSUE TITLE
Allow .aup file to be used for audio track

### ISSUE THREAD

**Issue by djulien** [smeighan/xLights#3971]
**Is your feature request related to a problem? Please describe.**
It is not uncommon to shorten an .mp3 file for use with a sequence, or to splice together a bunch of .mp3 files for a medley-style sequence.  This complicates the sequence sharing process and makes it more error-prone - it's often handled by providing instructions for the user to manually edit an off-the-shelf .mp3 file, or to provide declaration/proof that the user owns a legal copy of the .mp3 and then the sequence sharer/vendor will send an edited version of the .mp3 back to the user.

**Describe the solution you'd like**
It would be very helpful to allow an .aup (Audacity project) file to be able to be selected as the audio track for a sequence in xLights.  The .aup file can be freely included with the shared sequence files, and the user will end up with a correct sound track as long as the constituent .mp3 files are available on the user's computer, without the back-and-forth .mp3 handshaking.  (xLights would need to prompt for all the .mp3 files referenced by the .aup, as there could be multiple in the case of a medley)

**Describe alternatives you've considered**
I considered hacking up the xLights source code to accept an .aup file, but prompting for possibly multiple .mp3 files changes the UI slightly, and so the edits are best done in a manner consistent with the overall UI design policies of xLights.

**Additional context**
This could either be a change to the New Sequence window (to accept an .aup file and prompt for referenced .mp3 files), or maybe a Tools menu item that prompts for the .aup file and .mp3 files and generates a new .mp3, which can then be entered into the New Sequence window as-is.  I see there is a Tools menu item for a Reaper file, but Audacity seems to be a more popular tool for editing .mp3 files for usage in xLights.

**Comment by keithsw1111** [comment]
There is already 2 ways to do this in xlights ... not based on audacity. One is an xlights specific xml file describing the edits and one it another software product whose name is not top of mind ... I would need to look it up. Edits are limited to cuts and fades and can include merging multiple audio files.

**Comment by dkulp** [comment]
If done, this should be an addition to the "Prepare Audio"  menu item to recognize different file types (currently just reaper files).   That said, there are a bunch of concerns:

1) Audacity doesn't even use AUP files anymore.   For the last two years, the aup3 files that Audacity 3.x creates are binary sqlite databases that are not easily read/processed.  

2) aup files can describe all kind of various audio transformations and there is no way we'd support them all.

**Comment by djulien** [comment]
> 1. Audacity doesn't even use AUP files anymore.   For the last two years, the aup3 files that Audacity 3.x creates are binary sqlite databases that are not easily read/processed.

Whoops, looks like I'm using an older version of Audacity.

> 2. aup files can describe all kind of various audio transformations and there is no way we'd support them all.

I assumed it would just use the Audacity scripting API without xLights needing to understand all the transforms.

> There is already 2 ways to do this in xlights ... not based on audacity. One is an xlights specific xml file describing the edits and one it another software product whose name is not top of mind ... I would need to look it up. Edits are limited to cuts and fades and can include merging multiple audio files.

It sounds like I should just switch over to using Reaper then.  thanks!
