### ISSUE TITLE
Single Strand effects on Custom model don't follow the wiring

### ISSUE THREAD

**Issue by degracode** [smeighan/xLights#3972]
**Describe the bug**
I've imported Twinkly model data into a Custom model object. If I play a Single Strand Chase effect (with the default settings), it plays a spatial effect across the model that looks more like Bars, rather than chasing through the nodes in wiring order. Doing the exact same thing, but with a Single Line produces the expected effect

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Create a Custom Model
2. On the Model Data property, click Click to Edit
3. Click Import from Controller
4. Create a new sequence
5. Add the Custom Model to the sequence
6. Add a Single Strand effect to the Custom Model
7. Click Play

**Expected behavior**
The Single Strand effect should follow the wiring order, rather than produce a spatial effect.
My expectations are based on the effect's documentation here https://manual.xlights.org/xlights/effects/off/single-strand

**Screenshots**
This gif is showing a Window Frame-style Twinkly layout - a simple rectangle - playing a Single Strand Chase effect.
![BrokenSingleStrand](https://github.com/smeighan/xLights/assets/7349637/bdf6c958-eaca-4dc4-985b-9bee7438ff8f)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2023.14

**Additional context**

**Attachments**
https://www.dropbox.com/scl/fi/t3muaxa43ak7deyyona92/BrokenSingleStrand.zip?rlkey=2th5kk92w5ctqt8ct99k2znxy&dl=0

**Comment by computergeek1507** [comment]
It's working as expected, it's following the render buffer. Like you said if you want it to follow the node order change to single line render style

**Comment by degracode** [comment]
That would mean I need two models that represent the same physical device, so that I can use both single strand and spatial effects on it, which I believe would also prohibit layering the two types of effect together.

The line-based object also wouldn't look correct in the preview window as it won't spiral up the object it's physically wrapped around.

If this is by-design, is there another effect type that could be implemented that does run through in the single strand wiring order?

**Comment by keithsw1111** [comment]
Not true ... just change the buffer style to single line.

**Comment by computergeek1507** [comment]
You can layer two effects with different render styles, single line, and default

**Comment by AzGilrock** [comment]
Learn how to change the render buffer for the effect.   Maybe watch some videos since you sound new

**Comment by degracode** [comment]
Thanks, I'll have a look. Though a quick explanation for (an apparently obvious) newbie would have been nicer than this frosty reception!

**Comment by degracode** [comment]
> Learn how to change the render buffer for the effect. Maybe watch some videos since you sound new

Yep, that's done it thanks. Layer Settings -> Single Line for any future travellers.
