### ISSUE TITLE
"Locked" objects have confusing UX if you try to delete them 

### ISSUE THREAD

**Issue by degracode** [smeighan/xLights#3973]
**Is your feature request related to a problem? Please describe.**
I've just had a confusing case where I was trying to delete a mesh object via the 3D Objects list (right-click -> Delete), but it wasn't doing anything. Later, I noticed that the object had its "Locked" property ticked. Unticking this allowed the Delete to work as expected.

**Describe the solution you'd like**
The UX for trying to Delete something that's Locked could be improved in a couple of ways to inform the user why they cannot perform this action.
1) with a dialog "Object5 is locked and cannot be deleted", "Object5 cannot be deleted while locked. Would you like to unlock it first?"
2) the menu item could be disabled so the user can't click it. This could be enhanced with a tooltip explaining why the menu item is disabled, or change the text to something like "Delete [Object Locked]".

**Describe alternatives you've considered**
The alternative is allowing users to be frustrated and not understand why the action appears broken.

**Additional context**
Seen in xLights 2023.14.

**Comment by AzGilrock** [comment]
I’m not understanding that comment.   It looks like the code change was supposed to grey out options that weren’t available as well as display a message to let the user know a model couldn’t be deleted because it was locked

**Comment by derwin12** [comment]
Oops .. I commented on the wrong commit..
