### ISSUE TITLE
Feature Suggestion - Heirachal Layouts

### ISSUE THREAD

**Issue by kkatee** [smeighan/xLights#3975]
Dunno how feasible this idea is, but here we go.

Lots of people do shows for multiple holidays. Halloween and Christmas probably the most common.

Many people achieve this by having multiple show folders with their different layouts. The problem comes when updating things like house outlines that are common to all the layouts.

What im proposing is a system where you can have a Base layout with all the items that are consistent across layouts, then your Christmas and Halloween layouts just include the parts that are specific to that holiday. Then you can update your house outlines in the Base layout and its propagated to all your different setups.

**Comment by djulien** [comment]
How do you use multiple previews with 3D models/previews?

**Comment by kkatee** [comment]
If using previews, how do you assign a christmas prop and a halloween prop to the same port on a controller?

**Comment by AzGilrock** [comment]
Your right.  I've actually been wanting to delete that whole preview thing its just slowing down the code for like 2 people that use it.  I'd rather just see folks use multiple show folders its not worth the hassle to try to have all features of the program capable of supporting multiple shows.

**Comment by kkatee** [comment]
Sorry for trying to understand how it works.

**Comment by AzGilrock** [comment]
You can’t assign multiple items to a controller.   You just made me realize the can of worms this would open up.    We didn’t even have the Visualizer when I created that multiple preview feature so it wasn’t an issue back then

**Comment by bcarriveau** [comment]
Multiple show folders is the cleanest way to go. I would never want my halloween songs /images near my Christmas stuff. The visualizer, auto sizing and ability to simply click a button to update controls makes it all beyond simple to re sync devices between the holidays

**Comment by computergeek1507** [comment]
I have looked at adding the ability to connect controller configurations to previews, but it would be confusing and we would probably have the same issue we have now when people accidentally change models to a preview and don't know it

**Comment by dkulp** [comment]
Hierarchical layouts is something that's been on my todo list forever, but not something I want to tackle until the entire "use XML for internal storage" issue is resolved first.  My thought would be that you could assign a parent show directory and anything loaded from there would be treated as "read only".  That's likely doable, but not easily with the current method of having to pretty much reload the entire XML for basic changes.

**Comment by kkatee** [comment]
thats basically what I had been thinking Dan

**Comment by AzGilrock** [comment]
Hopefully we could delete the multiple previews stuff at the same time.  I’d also like to eliminate the master view concept.   Let whatever “Derived View” is current be what defines all the models that end up in a new sequence

**Comment by computergeek1507** [comment]
"Multiple Previews" is used by many large shows and drive throughs to separate sections of their shows. If you remove it you will effect lots of large shows.

**Comment by keithsw1111** [comment]
There is no reason why in the interim we couldnt offer a way to import from another show folder ... bring in all the models replacing like named models in the current layout. You could run this over and over again (possibly each time you open the show folder).
There is a downside to this though: The controller mapping would need to be constant. At a minimum the same controller and same port and same chaining on that port.
Using this you could maintain the common elements in one show folder then regularly bring in updates to one or more other show folders.
Usage will not be for the beginner though as if you dont have a good grasp of what is going on it would be very easy to make a mistake and screw things up.

**Comment by keithsw1111** [comment]
I have controllers working ... just need to add models and model groups.

**Comment by AzGilrock** [comment]
> "Multiple Previews" is used by many large shows and drive throughs to separate sections of their shows. If you remove it you will effect lots of large shows.

Yeah well we already set the precedent of pissing people off like removing xSchedule from Mac or FPP 5 and under support.

**Comment by AzGilrock** [comment]
There just so many messed up things with how Multiple Previews is implemented.  The positioning for one.  Every preview is technically overlaid on top of each other with regards to where xLights thinks the models are sitting in physical space.  And it only works in 2D.  People were supposed to use 3D to draw the larger shows and they could easily navigate around using Viewpoints.  Kinda tired of leaving things a mess all because it started being used.

**Comment by computergeek1507** [comment]
How everything is overlayed helps with render in a lot of cases. You can't render on multiple viewpoints with a whole display group. Maybe if groups supported a default Viewpoint for render then groups in groups might fix this.

**Comment by AzGilrock** [comment]
Yeah we are probably stuck keeping it.  I wish I could remember why we had to disable multiple previews for 3D.  I'd have to dig into the logic to remember.

**Comment by computergeek1507** [comment]
I wish all of us could get together and discuss "xLights 5" and make a wish list of things to change, code design, refactor, old stuff to remove, and work on a plan for a rewrite to fix this kind of stuff.

**Comment by keithsw1111** [comment]
I have implemented this for controllers and models. I have not done objects but I suspect that will also be wanted but it can be added later once we know this approach works in practice.

**Comment by kkatee** [comment]
Thanks Keith.

**Comment by djulien** [comment]
> Yeah we are probably stuck keeping it. I wish I could remember why we had to disable multiple previews for 3D. I'd have to dig into the logic to remember.

I turned on multiple previews in 3D and it worked quite well.  I only had some crashes when dragging/repositioning models that overlapped or were near each other.  I didn't track it down further since it worked well enough for me (and due to time constraints).

**Comment by AzGilrock** [comment]
I just remember telling Keith about a problem with it and he said well I’ll just turn it off for 3D.  Does it even handle the 3 D objects?

**Comment by keithsw1111** [comment]
> I just remember telling Keith about a problem with it and he said well I’ll just turn it off for 3D. Does it even handle the 3 D objects?

From memory (and that is all it is) it had something to do with getting 3d to work reliably in all the sequence preview windows for each of the views.

**Comment by djulien** [comment]
> I just remember telling Keith about a problem with it and he said well I’ll just turn it off for 3D. Does it even handle the 3 D objects?

seems to display fine is the Preview window. (wan't an exhaustive test, though)

**Comment by steveratcliffe** [comment]
Sorry to drag this one up again - stumbled across this thread on a hunt for decent info about "correct" implementation of multiple previews functionality (and not finding too much else at all).  Reading between the lines in this thread, I'm guessing previews doesn't get much much press if general consensus is that the features is a thorn in the side of the software?

My interest in multiple previews is for a whole village centre show I'm working on, which will have several feature buildings surrounding a central viewing position.  My current thinking was to use a different preview for each feature building, such that traditional "whole show" effects can be rendered "per preview" so the background/whole show effects would be replicated across each feature building/preview.

If there is a chance this functionality is going to disappear, I'll not go any further down that rabbit hole?  Equally if there is a better way of doing a large distributed show with multiple "centres" or "main views" that to some extent will involve some replication of common sequencing, I'd welcome any advice/suggestions.

Thanks, Steve.
