### ISSUE TITLE
Visual indicator for models/groups that have effects on submodels/nested groups

### ISSUE THREAD

**Issue by djulien** [smeighan/xLights#3976]
**Is your feature request related to a problem? Please describe.**
When effects are present on submodels, they are not visible unless the submodels are expanded within the view at the left of the sequencer grid.  This uses significant vertical screen real estate within the sequencer grid so the user often needs to collapse the models to conserve vertical space, but then it's hard to remember where the effects were.

**Describe the solution you'd like**
It would be extremely helpful to have a visual indicator on models when there are effects on any of its submodels.  This would make it easier to keep track of which models have effects on them when the model is collapsed and effects are present at the submodel level and not on the model itself.

**Describe alternatives you've considered**
The indicator could be a *, italic or colored font, etc, even the number of effects in parentheses.

**Additional context**
Similar for groups - it would be very helpful to have a visual indicator on groups that contain models or subgroups which have effects on them.

**Comment by AzGilrock** [comment]
This is already in the request list at least twice.

**Comment by djulien** [comment]
closed as duplicate

**Comment by derwin12** [comment]
Perhaps close..
https://github.com/smeighan/xLights/issues/566
https://github.com/smeighan/xLights/issues/2099

**Comment by djulien** [comment]
fantastic!  This will be very helpful!
