### ISSUE TITLE
Allow background image to be an HTML page

### ISSUE THREAD

**Issue by djulien** [smeighan/xLights#3977]
**Is your feature request related to a problem? Please describe.**
There are often YouTube videos, Amazon Music links, or other web-based info associated with a sequence.  Currently the user has to use external tools to manually open those external items.

**Describe the solution you'd like**
It would be very useful to be able to use an HTML page as a layout background image.  This would allow links to YouTube videos, Amazom MP3 files, other vendor files, etc, to be stored with the sequence and easily accessible from within xLights.

**Describe alternatives you've considered**
Text can be embedded into an image used as a background, but it's just static text and not clickable.

**Comment by dartunder** [comment]
Is it sufficient to include a readme in the zip file (PDF, HTML, whatever) with all the reference info?
Then we could maybe consider making that file more accessible during the import process.  Perhaps look for a readme.* file?
The background image would not be visible anyway unless the sequence zip is opened directly and viewed as a temporary layout.

**Comment by djulien** [comment]
A README file would contain all the info okay but is a separate place for users to remember to go look at.

Having a place within xLights for info about the sequence or models/layout would be useful - could there be a Notes tab that automatically displays a README file if found in the Sequence folder?

HTML or at least Markdown support would also be useful within the README.

**Comment by computergeek1507** [comment]
You can put a link in the sequence settings

**Comment by keithsw1111** [comment]
We are not going to have a html background but i did add some buttons to open the URLs and even lauch your mail client using the fields Scott pointed out in the sequence settings metadata.
