### ISSUE TITLE
Generate custom model fails with hardware decoding enabled

### ISSUE THREAD

**Issue by DnG-Crafts** [smeighan/xLights#3983]
**Describe the bug**
when using a video to generate custom models the tool will fail to detect nodes if you have hardware video decoding enabled.

**To Reproduce**
go into **Preferences** > **Other** and enable "**Hardware Video Decoding**" then attempt to generate a custom model using a video generated by the tool selecting "**Nodes- Automatic**"

**Expected behavior**
the custom model tool should analyse the video and report how many nodes found after the video is processed on the "**Bulb Identify**" tab

**Versions:**
 - OS: Windows 10
 - xLights version: 2023.08 64bit 
 - Hardware: intel i7 13700, nvidia rtx 3070

**Additional context**
i initially thought it may have just been something in my own pc causing the issue but another user reported the same issue in the support group and i suggested disabling hardware video decoding and they reported it solved their issue with detection.

**Comment by keithsw1111** [comment]
This varies by installation based on your hardware. Just turn it off if it causes you issues.
