### ISSUE TITLE
Heirachal Layouts

### ISSUE THREAD

**Issue by dartunder** [smeighan/xLights#3984]
@keithsw1111 
I like where you are headed... These are just some early observations...

I think it's important to know if an object is "FromBase" so you know where to do editing, as changing something from the base on a sub-show folder, like a description, will immediately get overwritten on the update.

We need to be clear about where this object is maintained and potentially prevent changes without first breaking the inheritance.  Also, there has yet to be an obvious way to push an object down to the base.

If it's not already a base Folder, it seems like it should be per a per-show folder setting rather than a global one.
Importing from the wrong base could cause all kinds of issues.

Feel free to close this immediately or leave it for discussion.

**Comment by keithsw1111** [comment]
I have considered locking the model and maybe locking all the properties in the derived show folders ... but not sure I want to do that. I also considered making it possible to disconnect it from base ... (not sure i will let you reconnect it ... maybe force you to delete it - but that has its own challenges).

Changing base show folders once set is not a great idea. I dont prevent it but I can see little reason for doing it.

**Comment by keithsw1111** [comment]
I do track that it came from base so all options are on the table right now.

**Comment by dartunder** [comment]
I'm not suggesting changing the base folder as a standard practice, but each show folder should be able to specify its base folder.  We may need to open a new folder for a different location, especially if the user is helping others.  (I don't need this feature yet, but I thought I would experiment)

 Yes, you track where it came from, but that needs to be at least shown ( a property or color change ) or not editable / locked, as you said.

**Comment by keithsw1111** [comment]
But each show folder does specify its base.

**Comment by dartunder** [comment]
ok great... ... when I switched temporarily to the "base" it still showed the base folder I guess I thought it was global like the permanent folder.

**Comment by keithsw1111** [comment]
Nah ... thats a bug

**Comment by AzGilrock** [comment]
I can't figure out how to use this.  When I check the Enable Base Show Folder Settings checkbox it won't stay checked and I don't see anything new appear anywhere.

**Comment by dartunder** [comment]
enable then restart xlights

**Comment by keithsw1111** [comment]
That could be OSX ... it does weird things with the preferences ... I may have missed something to make it work there,

**Comment by keithsw1111** [comment]
Yeah ... the wxwidgets code is broken ... it created the event but didnt hook it up

**Comment by keithsw1111** [comment]
Windows does not care ... but OSX does

**Comment by keithsw1111** [comment]
Fixed ... I find that with wxSmith ... some events need to be hooked up multiple times. Normally i notice but as i say preferences work on windows without it.

**Comment by AzGilrock** [comment]
Yep I’ve been running into that.   The first selection seems to open the file but not write the event then you gotta do it again.

**Comment by kkatee** [comment]
been checking it out tonight and im having trouble with groups. any props coming over from the base layout aren't keeping their groups. I have my outlines in an Outlines group, a Whole House group and my Everything group, in both the base layout and the xmas layout. whenever there is an update from base they are taken out of all groups.

**Comment by keithsw1111** [comment]
Not sure which version you tested with but i may have fixed that.

**Comment by kkatee** [comment]
Should have mentioned that, I'm testing with Nightly 0e2c662

**Comment by kkatee** [comment]
> Not sure which version you tested with but i may have fixed that.

its working for me in todays build, thanks Keith.
