### ISSUE TITLE
Deleting a Duplicate Timing Track Hides ALL Timing Tracks EDIT: Trying to select a Timing Track Hides them all also

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#3988]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I have duplicate Timing tracks...when deleting one of them it hides all the timing tracks.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. "Edit Display Elements"
2. Right Clik on a Timing Track - "Show All"
3. Right Click on Timing Track in Sequence - "Delete Timing Track"
4. All Remaining Timing Tracks get "Hidden"

**Expected behavior**
Would expect the selected Timing Track to Be Deleted and all other Timing Tracks do not get hidden.

**Screenshots**

**Versions *
 - OS: [Windows 10
 - xLights version 2023.14

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publicly
(https://github.com/smeighan/xLights/files/12710851/2023.Stretchy.Pants.-.Carrie.Underwood.-.40fps.zip)
 please say so and be ready to PM them to one of the developers when asked.
 
 [2023 Stretchy Pants - Carrie Underwood - 40fps.zip]

**Comment by keithsw1111** [comment]
I folled the instructions and did not see the issue. Not sure why you did step 1 but i did it and it made no difference.

**Comment by derwin12** [comment]
I duplicated it..
Keith - grab the sequence attached above .. 
In the display elements window - they are initially hidden (eyeball off).
Right Click to enable them.
Now hop over to the sequence, and delete a timing track.
They all flip back to hidden again. 
It is like the change in the display element window is not "saved" and reverted back with the sequence change being made.
![image](https://github.com/smeighan/xLights/assets/4643499/7486772c-2881-4379-99e1-d074d2408c2d)
...
![image](https://github.com/smeighan/xLights/assets/4643499/7e26e481-9b4a-4fbf-8256-80c81bab6db6)
![image](https://github.com/smeighan/xLights/assets/4643499/5a2b4434-5d51-4358-b476-9fe8dc47e63f)

**Comment by jimswinder** [comment]
thanks Daryl...I did a screen capture but github says it is too big to send
________________________________

**Comment by keithsw1111** [comment]
For larger screen captures upload them to youtube and paste the youtube link.

**Comment by keithsw1111** [comment]
The only possible bug I can see is the display elements when open dont update when you hide/unhide all timing tracks. Otherwise the behaviour is exactly as i would expect. If you close and reopen display elements it is correct.
