### ISSUE TITLE
Timeline zooming centered on mouse marker (QoxL)

### ISSUE THREAD

**Issue by hoodlumj3** [smeighan/xLights#3989]
Have the ability to use the waveform timeline mouse marker position ( vertical blue line on waveform ) to be the center of the timeline zoom in / out.

I'm offering to build this, wait, I have built this already [Branch:timeline-zooming](https://github.com/hoodlumj3/xLights/tree/timeline-zooming)

**Is your feature request related to a problem? Please describe.**
No, but yes - timeline editing efficiency problem.

**Describe the solution you'd like**
Ability to change timeline zoom level centered target (CTRL + Mouse Scroll Wheel) based on the mouse marker position (currently its the start play marker)
Preference option to select if you want timeline zooming to zoom in/out using Mouse Marker or Play Marker 
(naming to be considered / discussed)

**Describe alternatives you've considered**
No alternatives as there is only one way this can be workflow'd.
The current zoom in on play marker can get you disorientated and lost in the timeline in an instant (as its a hard zoom in / out) if you crazy zoom in or scroll the timeline window left or right (SHIFT +  Mouse Scroll Wheel) away from the play start marker.
Only way to recover / find where you were is to zoom all the way out, quickly scan the timeline and attempt to recognize were you think you were editing (as its not always on the play start position because scroll bars), click on timeline and zoom in again.

**Additional context**
I class this as Quality of xLights (Life) Enhancement ;)
Current zoom feature is not an effective use of time and as 95% of software that i've used does this OOTB already.
I believe this feature will increase the qualilty of xlights and life in general.

please discuss and feedback welcomed ;)

**Comment by keithsw1111** [comment]
Raise a pull request. Is this controlled by an option or are you changing the behaviour for all users.

**Comment by hoodlumj3** [comment]
Pull request incoming.

awww you ask such hard questions... ;D 

The zoom setting, on windows at least, is stored in the HKCU registery by xLights so its a local setting per user.
The default setting is set to use current behaviour - zooming on the start play marker.
Zooming setting is in preferences under the View tab.
I tracked down the colour setting i added to the xlights_rgbeffects.xml file so its show (folder) based, part of the layout.

**Comment by hoodlumj3** [comment]
PR #3991
