### ISSUE TITLE
Opening xL3.x sequence causes xL4.x to crash

### ISSUE THREAD

**Issue by ef9** [smeighan/xLights#399]
Hello,
I am trying to open a xLights 3.x sequence in xLights 4.x software, and it immediately crashes and generates a bug report.  So far, I have successfully opened 2 other xL 3.x sequences successfully.  

https://www.dropbox.com/s/ua4vym4znoy1zlw/xLights_dbgrpt-5620-20151023T195142.zip?dl=0

https://www.dropbox.com/s/ua4vym4znoy1zlw/xLights_dbgrpt-5620-20151023T195142.zip?dl=0

https://www.dropbox.com/s/i7exhw5yyfgvqv2/xlights_rgbeffects.xml?dl=0

**Comment by AzGilrock** [comment]
This was 1.5 years ago so I'm assuming you got past the problem.  Otherwise try with latest software and open new issue if you still have problems.
