### ISSUE TITLE
Compare layers

### ISSUE THREAD

**Issue by djulien** [smeighan/xLights#3993]
**Is your feature request related to a problem? Please describe.**
It seems fairly common to copy and paste effects from one model or group to another, in localized areas and even across the entire sequence.  This makes the sequence more difficult to maintain or enhance - you don't know if the multiple copies of the effects are exactly the same, or maybe there is a setting that is different between them but several panels must be visually reviewed in order to decide that.

**Describe the solution you'd like**
It would be very useful to have a Compare function in the right-click menu to compare the clicked-upon row or effect to a previously selected row or effect.  This would give guidance for the user to know whether the effects could be consolidated by moving them onto a parent group, which would make the sequence less bulky or make it simpler to apply changes when there are duplicates.

**Describe alternatives you've considered**
It's awkward to open the xsq file in a text editor, find the effects of interest, and then compare the text.  A context menu within the xLights sequencer grid would be a lot more convenient.

**Additional context**
A simple yes/no they are the same would be handy, or the ability to selectively merge or apply changes would be more powerful.

**Comment by keithsw1111** [comment]
Really not a fan of this. It seems such a niche case. Instead I added a duplicate effect which will duplicate all the effects on a specifed model/layer.

**Comment by keithsw1111** [comment]
I fear you misunderstand what duplicate effect does. It is a new effect that placed on a model explicitly does the same thing as another model layer. No need to guess if it is a duplicate ... it explicitly is.

**Comment by djulien** [comment]
Sorry, I misinterpreted what you meant by "duplicate".  That sounds like a useful new effect type!  Hopefully authors of shared sequences will use it.
How to make use of this on a pre-existing sequence?  (my original use case)  I see a lot of duplicated (ie, replicated) effects in shared sequences and it's difficult to know whether they can all be updated at one time, or there are subtle differences between them and they need individual edits.

**Comment by djulien** [comment]
I found another way to do the compare that seems to work, so I can use that approach:
1. select effects to compare from first layer, Control+C, paste into external text editor and save
2. select effects to compare from second layer, Control+C, paste into external text editor and save separately
3. diff the 2 saved text files (either ignore start/end times or align them first before copy+paste so they drop out of the compare results)
4. if the effects are the same, then I can move them from 1 layer to a parent folder and delete them from the second layer.  This will give me a DRY-er sequence with fewer WET effects.
