### ISSUE TITLE
FPP Connect

### ISSUE THREAD

**Issue by striker72** [smeighan/xLights#3994]
I upgraded to the latest version of your software and i am no longer able to use the FPP connect to upload my sequences to my FPP player.  I am able to manually copy them via the web interface so i knew they are not corrupt.  I thought i would try an older version i had downloaded on my machine so i first tried 2023_13 version and i Had the same issue.  SO then the version i had before that downloaded was 2023_09 and that version works fine to upload with FPP Connect.  I'll stick with that version until i can figure out what is wrong with the newer versions not uploading my sequences.

It just starts to upload the first song and the bar goes until 100 percent and freezes.  The entire app freezes and i have to exit it from task manager to try again.

On the newer version it happens whether i pick 1 song or multiple.

I am using Windows 11 Enterprise
Version 10.0.22621 Build 22621
It's an Acer Aspire TC-885 PC
16 GB RAM.

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
[Xlights FPPConnect Issue.pdf](https://github.com/smeighan/xLights/files/12731687/Xlights.FPPConnect.Issue.pdf)

**Comment by AzGilrock** [comment]
So what version of FPP is it?   Since FPP 7 came out I don’t believe the FPP connect supports version 5 anymore

**Comment by striker72** [comment]
6.3.1.1Regards,CraigOn Sep 26, 2023, at 9:53 PM, Gil Jones ***@***.***> wrote:﻿
So what version of FPP is it?   Since FPP 7 came out I don’t believe the FPP connect supports version 5 anymore

**Comment by striker72** [comment]
I will try to upgrade to FPP7 and see if that solves the problem. Regards,CraigOn Sep 26, 2023, at 9:53 PM, Gil Jones ***@***.***> wrote:﻿
So what version of FPP is it?   Since FPP 7 came out I don’t believe the FPP connect supports version 5 anymore

**Comment by striker72** [comment]
It looks like upgrading the FPP to Version 7 resolved the issue.  Thank you for the help.

Regards,

Craig.
