### ISSUE TITLE
No Issue : Request for info RE:KeyBindings

### ISSUE THREAD

**Issue by hoodlumj3** [smeighan/xLights#3995]
First off, not sure this is the best place ask these sorts of questions... didn't really want to clog up the issues list
but here goes.

Q:
What's the right way to add keybinds into xLights and their connection to code ? 
Am I ok to just copy paste existing KeyBindingTypes, KeyBindingTips and optionally KeyBinding DefaultBindings in xLights/KeyBindings.cpp, altering for uniqueness and then add the corresponding unique keybindindtype in the  MainSequencer::HandleSequencerKeyBinding (i.e manually edit code)
or is there an approved / ideal / better way ? 

Q:
Are we free to choose DefaultBindings for new KeyBinds or does this need to be vetted / discussed / bribery ?

TY

**Comment by keithsw1111** [comment]
Adding a binding that is useful is not a problem. Associating a default key should be discussed. By default we generally add them with no key unless we think everyone is likely to use it as it may clash with keys users have already set up.
