### ISSUE TITLE
Manual update regarding terms used in fpp connect section

### ISSUE THREAD

**Issue by bloojoop** [smeighan/xLights#3999]
I would like to suggest updating the verbiage in the xlights manual in the menu - tools - fpp connect section.  in the udp output section it currently states 
"'All' should be selected on Standalone/Master FPP Devices and 'Proxied' should be used for Remote FPP Devices that act as a tunnel to other controllers like a F16v3."

Since Standalone and Master are no longer modes that are used and since any fpp device can function as a proxy I propose the following verbiage change 
"'All' should be selected on Player FPP Devices that will send E1.31, DDP, or Artnet data to another controller and 'Proxied' should be used for any FPP Devices that act as a proxy tunnel to other controllers like a F16v3."

Just had a discussion with a user that believed that the udp out setting was supposed to be use for master/remote configurations, which of course now is considered Player/remote configurations.

**Comment by AzGilrock** [comment]
My FPP show player is my Master so I'm so confused now....lol.

Regarding the manual its not maintained here.  I'm not sure who owns it or how it ever gets updated.

**Comment by computergeek1507** [comment]
I'll update it

**Comment by bloojoop** [comment]
> My FPP show player is my Master so I'm so confused now....lol.
> 
> Regarding the manual its not maintained here. I'm not sure who owns it or how it ever gets updated.

Master is no longer an actual mode of operation... It is now called Player w/ multisync.. since 5.x ..  I absolutely still think of it as Master functionality, but that is not how the new versions of FPP refer to it so it can leave newer users confused.

**Comment by bloojoop** [comment]
> I'll update it

Thanks Scott, and Gil !!  I wasn't sure this was the right place but I was confident someone here would know the right place.

**Comment by AzGilrock** [comment]
Yeah I wasn't really confused I just refused to give up the old names all because FPP went woke and thought master/slave in electronics was racist.

**Comment by kppankratz** [comment]
I'm technically the "owner" of the as I set up the Gitbooks account to host the manual.  There's about 8 or 9 people out there who have access to make changes to the manual and push it out.
