### ISSUE TITLE
Crash. Open two sequences, on second you get a crash

### ISSUE THREAD

**Issue by smeighan** [smeighan/xLights#40]
I open test_for_crash.xml, adjust one timing mark and then open carol of the bells. i get a crash.
If i dont touch a timing mark, it doesnt crash. It may be that the animation for the preview started.

Remember the sequences i am using can be found at http://nutcracker123.com/nutcracker/xl4_crashes/
video of crash is http://nutcracker123.com/nutcracker/xl4_crashes/crash_issue_40.mp4

**Comment by dkulp** [comment]
I think I may have fixed this earlier as part of the rendering updates.   Can you verify?   I cannot reproduce now.

**Comment by smeighan** [comment]
i have verified that it does mot crash. i am closing ticket.
