### ISSUE TITLE
Wave and Twinkle Missing from Effect Bar and Effect Window

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#400]
They are still available if you add a dummy effect, then go to Effect Settings, and use the pull down.
Noticed this with .15 and up. Not sure when it happened.

![image](https://cloud.githubusercontent.com/assets/10568498/10721368/fe49b9be-7b5f-11e5-96c2-e3843c1cc06d.png)

**Comment by AzGilrock** [comment]
Closed by release 4.2.18
