### ISSUE TITLE
Falcon V4 and End Null Channels

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#4003]
We saw this in zoom .. not sure if a bug or just the way it is. Doesnt appear to harm the actual display.
A prop with 2 strings (ports) with individual strings. The zoomer wanted to note the null pixels at the end of the 2nd string.
They put in 4 for end nulls.
The falcon shows these 4 end nulls for *both* ports. Looking at the channels - it doesnt appear to affect anything but I questioned if it should show 0 for the first port just for correctness.

![image](https://github.com/smeighan/xLights/assets/4643499/6fe8034b-13a7-4916-9367-1740a967b420)

**Comment by computergeek1507** [comment]
It's not a bug it adds nulls to all strings
