### ISSUE TITLE
xLights Crashes when trying to upload output to a ESPixelStick

### ISSUE THREAD

**Issue by JMHaro** [smeighan/xLights#4005]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
xLights shows the ESPixelStick in green status and clicking the Open button opens the web page, but the Upload Output does this crash every time.

**To Reproduce**
1. Select the ESPixelStick controller.
2. Click Upload Output
3. Crashes

**Expected behavior**
Expect the Output be sent to the ESPixelStick

**Versions (please complete the following information):**
 - OS:  Windows 10
 - xLights version 2023.14
 - ESPixelStick:  FW Version 3.2, Build Date Nov 3 2020, 

**Additional context**
This is trying to do an Upload Output to an ESPixelStick.  It has worked in the past but I've attempted this 3 times and it's done the same error every time.
The ESPixelStick also for some reason quit responding to the Master FPP (all running 7.1).  It's responding with it's web site, but the Master FPP does not see it.  That's why I was going to try to resend the output to it
xLights shows it in green status and clicking the Open button opens the web page, but the Upload Output does this crash every time.

**Attachments**
[xLights_dbgrpt-23232-20230928T211846.zip](https://github.com/smeighan/xLights/files/12755527/xLights_dbgrpt-23232-20230928T211846.zip)

[xLights_dbgrpt-21996-20230928T204647.zip](https://github.com/smeighan/xLights/files/12755528/xLights_dbgrpt-21996-20230928T204647.zip)

[xLights_dbgrpt-34076-20230928T204958.zip](https://github.com/smeighan/xLights/files/12755530/xLights_dbgrpt-34076-20230928T204958.zip)

**Comment by Dubbs2022** [comment]
I have this same issue, caused my ESPixelStick to stop working entirely. To fix the pixel stick I had to completely reflash it, then go through the online GUI to reset it as well. After that it came back online and started working. I haven't uploaded my sequence out of xLights to it yet because it works fine now.

**Comment by computergeek1507** [comment]
If you update to the latest nightly it should be fixed
