### ISSUE TITLE
Menu zooms

### ISSUE THREAD

**Issue by Dubbs2022** [smeighan/xLights#4006]
I would like to be able to zoom into the "view" table. I run a 4k monitor and seeing all the layers can be tough when I have a lot of them. If I can zoom into this panel that would be great!

<img width="258" alt="2023-09-29_153302" src="https://github.com/smeighan/xLights/assets/116459396/a27dc256-bb81-4a69-87b0-857fb7ec5aa2">

**Comment by computergeek1507** [comment]
In the Preferences -> Sequence Settings, change the Grid Size
