### ISSUE TITLE
Add 40fps Oversubscription Color to Visualizer

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#4007]
**Describe the solution you'd like**
The visualizer today color codes things in a pass/fail mode (white/red).  I'm suggesting adding another color (yellow) so that if a user goes beyond 40fps support on that string the port will turn yellow with appropriate wording indicting why on either the tooltip or the error page at the bottom of the visualizer.  

No changes are needed to controllers.xml as these are ws2811 protocol limitations and not related to any controller specifically.

Maybe some logic as follows.
* Physical port or dumb receiver
  * FPS Warning at 800 pixels on a port
  * Error at whatever the controller limit is if it exists
* Smart receiver v1 as configured by the user by right clicking the pixel port and setting as such
  * FPS warning at 760 pixels on a port (the 760 number may not be accurate but it is the same on all v1 receiver)
  * Error at whatever the controller limit is if it exists
* Smart receiver v2 as configured by the user by right clicking the pixel port and setting as such
  * FPS warning at 720 pixels on a port (the 720 number may not be accurate but it is the same on all v2 receiver)
  * Error at whatever the controller limit is if it exists
* HinksPix smart receiver will be a little more complicated due to v2 & v3 controllers having different pixel count outputs
  * Today xLights doesn't account for the v3 controller so output maxes out at 680 pixels on a port.  No change.
  * If logic is added for v3 then the same logic as above if known how many channels are sacrificed for receiver identification (A, B, C, ...).  If not know then skip this check or inherit from the smart v2.

**Why are these numbers useful**
How many times have you seen/heard people asking how many pixels can be supported on a port at a frame rate?  What about the other option of users not even knowing that the controller will change the frame rate if the protocol doesn't support it?  This will address both of those issues.

**Comment by keithsw1111** [comment]
I have mostly implemented this. There are two new xml elements which document max pixels at 40FPS with and without SR ... it wont separate different SR versions. I have not filled in most controllers ... people can do pull requests for that.
