### ISSUE TITLE
LMS import does not handle DMX Intensity properly

### ISSUE THREAD

**Issue by AzGilrock** [smeighan/xLights#401]
The LMS import needs to look at the type attribute and if its DMX Intensity instead of Intensity it needs to treat the values on a 0-255 scale instead of 0-100.  Or maybe it's vice versa but I wanted to log this before I forget.  Currently it looks like we are treating any string other than Intensity as if its a Shimmer.

**Comment by neilsunw** [comment]
I also need effect type="DMX intensity" handled properly for a custom LED sign that can take commands via DMX.  As the code stands these effects are getting dropped.

An effect of type "DMX intensity" will already be in 0-255 scale.

**Comment by neilsunw** [comment]
I also need this for a custom LED sign where I can command changes based on "DMX intensity" values. It looks like LMS import drops all <effect type="DMX intensity" ... /> items (set to "0") in xLights FSEQ.

Here is a short example to send command "#2" (decimal 35, decimal 2) on two DMX channels, which will select Time/Temperature display on a custom LED sign:

`<channel name="Door Sign DMX_MODE" color="12615744" centiseconds="5767" deviceType="DMX Universe" circuit="91" network="4" savedIndex="2782">`
`	<effect type="DMX intensity" startCentisecond="160" endCentisecond="180" intensity="35"/>`
`</channel>`
`<channel name="Door Sign DMX_DIGIT" color="12615744" centiseconds="5767" deviceType="DMX Universe" circuit="92" network="4" savedIndex="2783">`
`	<effect type="DMX intensity" startCentisecond="155" endCentisecond="185" intensity="2"/>`
`</channel>`

Can we get a rebuild of LMS import to handle and keep "DMX intensity" effect values?

Are there any workarounds to directly input the needed DMX values into xLights on the sequencer?

thank you, Neil

**Comment by neilsunw** [comment]
Here is a proposed code fix for **xLights/Convertdialog.cpp**
function `void ConvertDialog::ReadLorFile(const wxString& filename, int LORImportInterval)`
(see _pass 2, convert the data section_)
**lines 1778 - 1782:**
`                        intensity = intensity * 255 / MaxIntensity;`
`                        startIntensity = startIntensity * 255 / MaxIntensity;`
`                        endIntensity = endIntensity * 255 / MaxIntensity;`
`                        EffectType = getAttributeValueSafe(stagEvent, "type");`
`                        if (EffectType == "intensity")`
**change to:**
`                        EffectType = getAttributeValueSafe(stagEvent, "type");`
`                        if (EffectType != "DMX intensity")`
`                        {`
`                                intensity = intensity * 255 / MaxIntensity;`
`                                intensity = intensity * 255 / MaxIntensity;`
`                                startIntensity = startIntensity * 255 / MaxIntensity;`
`                                endIntensity = endIntensity * 255 / MaxIntensity;`
`                        }`
`                        if (EffectType == "intensity" || EffectType == "DMX intensity")`

The "shimmer" and "twinkle" code is fine.

**Comment by neilsunw** [comment]
Here is a sample LMS file (renamed to TXT for attaching) to verify conversion, see FSEQ output on channels 1037 - 1046.
[NBP-FirstNoel-2015-DigitTest.txt](https://github.com/smeighan/xLights/files/710203/NBP-FirstNoel-2015-DigitTest.txt)

**Comment by AzGilrock** [comment]
We already know about the issue that's why I logged the ticket.  And that is not the only work that needs to be done to fix this.  Why are you working in LOR for sign effects anyways?  You need to just dump that use xLights natively.

**Comment by neilsunw** [comment]
I'm just trying to complete my migration to xLights/FPP and the "DMX intensity" effects (exact 0..255 values) not coming through are more like trigger commands to a DMX device. 

Everything else imported nicely and I like xLights -- great work!

-Neil

**Comment by AzGilrock** [comment]
I seem to remember this is code that needs to be fixed in SeqFileUtilities.  The only reason I wrote this issue is because I thought it was a quick fix and it turned out to be more difficult so I couldn't get it figured out in short order so I wrote this issue to come back to it later.  You only found the spot where a conversion is done but that doesn't fix the Import Effects method of bringing in LOR data and possible not the data layer method.

**Comment by neilsunw** [comment]
The second half of the fix is to put the same code changes in **xLights/FileConverter.cpp**

function **void FileConverter::ReadLorFile(ConvertParameters& params)**
(see pass 2, convert the data section)
lines 653 - 657:
`intensity = intensity * 255 / MaxIntensity;`
`startIntensity = startIntensity * 255 / MaxIntensity;`
`endIntensity = endIntensity * 255 / MaxIntensity;`
`EffectType = getAttributeValueSafe(stagEvent, "type");`
`if (EffectType == "intensity")`
change to:
`EffectType = getAttributeValueSafe(stagEvent, "type");`
`if (EffectType != "DMX intensity")`
`{`
`        intensity = intensity * 255 / MaxIntensity;`
`        intensity = intensity * 255 / MaxIntensity;`
`        startIntensity = startIntensity * 255 / MaxIntensity;`
`        endIntensity = endIntensity * 255 / MaxIntensity;`
`}`
`if (EffectType == "intensity" || EffectType == "DMX intensity")`

The "shimmer" and "twinkle" code is fine.

The tested the changes in **ConvertDialog.cpp** and **FileConverter.cpp** and it solves the problem of XML parsing dropping the EffectType == "DMX intensity" data.

Now my LOR imports have all the channel data!

**Comment by AzGilrock** [comment]
I'm not convinced any of these changes accomplish the original reason I wrote this issue.  I don't see anything that would alter the results of the "ImportLMS" function that is in SeqFileUtilities.cpp which is the function that is called if you do an "Import Effects" from the "Import" menu and choose an LMS file.  I think what you've done is for the Convert tab or a Data Layer Import button.

**Comment by AzGilrock** [comment]
So what I mean is I believe you change fixes a small piece of what I was planning to fix and probably the easy part of what needed to be done.  So even if we pull in your code I don't think it closes this issue.

**Comment by neilsunw** [comment]
The scope of my fix is for LMS XML data that was getting dropped on the XML parsing. I keyed in on "DMX intensity" as a named effect type in the LMS files. 

I'm sure there could be more work to render intensity values for xLights effects in the sequencer, and that could have a different issue description. All intensity data is converted to 0..255 scale for the xLights data layer. 

At least now all the intensity data will be there in the FSEQ file (data layer) -- all four LMS types: intensity, shimmer, twinkle & DMX intensity -- the first three are 0..100 scale and DMX intensity is 0..255 scale.

Thank you for the review. 

-Neil

**Comment by AzGilrock** [comment]
Did you test importing the LMS file as effects?

**Comment by AzGilrock** [comment]
Never mind I got home and like I thought you did not fix the code for importing an LMS file as effects you only fixed importing as a Data Layer.

**Comment by AzGilrock** [comment]
For my own reference when I look at this later the problem is in SeqFileUtilities...search for "intensity" string to find cases.  The issue which makes a fix difficult is we currently convert to On effects which use a 0 to 100 scale.  If I convert a DMX value into an On effect it will lose resolution and may not end up with the exact same value.  Such as the DMX value 136 cannot be represented with an On effect because 53% of 255 is 135 and 54% of 255 is 137.  It would be better to use DMX effect to represent these on Import but the issue there is the DMX effect will not work at the strand or node level only the model level.

**Comment by keithsw1111** [comment]
I think i fixed this.
