### ISSUE TITLE
Duplicate Effect does not work as expected for UV effect

### ISSUE THREAD

**Issue by dartunder** [smeighan/xLights#4010]
@keithsw1111 
Musical sequence with a timing track
Bars 30
Timing Event Jump 100
Timing Track {something}

The primary model turns on and then decays into the center. 
The duplicated model pulses on very briefly ( does not decay like the primary)

Compiled 2a0c176132e43856d21d9eec8ae969d622e716df (from 9/30/2023)

**Comment by keithsw1111** [comment]
Do you have a sample sequence so I can see exactly how you are using it.

**Comment by dartunder** [comment]
Thanks, that fixed the issues as expected.
