### ISSUE TITLE
FPP Connect - Unable to upload to F16V2 (not red) - F0:V0 unable to determine model/version

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#4017]
From zoom.. 
Using latest xlights but an old F16V2 running old 1.01 firmware.

Log shows..
Parsed firmware version 1.1
Connected to falcon - p=0 Model: '' Firmware Version '1.01' F0:V0
Error connecting to falcon controller on 192.168.1.248. Unable to determine model/version.

Can there be some handler added to upload in this case.
We left the user to update to1.03(?) think that was the latest version we could find.

**Comment by derwin12** [comment]
Adding to help others in the future.. updating to the latest firmware corrected this issue.

**Comment by keithsw1111** [comment]
I recommend v1.11 b006

**Comment by derwin12** [comment]
I believe all we found was v1.03?
