### ISSUE TITLE
MAC 2023.15 - hard crash in mac on startup..

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#4019]
Dan - others - can you verify that the mac version is okay for release? User came into zoom .. cant start the app since moving to .15

**Comment by derwin12** [comment]
![image](https://github.com/smeighan/xLights/assets/4643499/7eba8335-8e3e-476c-9ed7-42e6aa9d5144)

**Comment by derwin12** [comment]
![image](https://github.com/smeighan/xLights/assets/4643499/8baf6269-d386-4819-8b1a-bb79e6adeacd)

**Comment by dkulp** [comment]
It's definitely working on Sonoma (m2) and Ventura(intel) and I also see someone else has it working with Monterey (intel).  Thus, it seems to be working on the newer machines.

**Comment by derwin12** [comment]
Can you make .14 available on your website? He went back to the .01 as it was the only one available.

**Comment by derwin12** [comment]
Another report this morning..
![image](https://github.com/smeighan/xLights/assets/4643499/2d78791c-d105-4e03-b74b-c4fb86d9b241)

**Comment by derwin12** [comment]
Another
https://www.facebook.com/photo.php?fbid=10232186813121451&set=p.10232186813121451&type=3
![image](https://github.com/smeighan/xLights/assets/4643499/d1890657-0491-461c-9acd-044a7d306535)

**Comment by dkulp** [comment]
It's almost certainly due to Xcode 15.   Looking at the 15.1 beta, I see:

<img width="908" alt="Screenshot 2023-10-04 at 10 09 20 AM" src="https://github.com/smeighan/xLights/assets/91569/ad141ad5-a632-46fa-ad7a-5a4b3b47e2ac">

which is likely the problem.   Unfortunately, beta builds cannot be used to release to the app store so kind of stuck waiting for the 15.1 release.

**Comment by computergeek1507** [comment]
Can you downgrade to XCode 14?

**Comment by dkulp** [comment]
Not on Sonoma.   It requires a complete downgrade of the entire OS as well.

**Comment by bflat66-gmail** [comment]
Xlights is launching in OS 11.6.6 for me, but won't launch in 11.7.10 today.  Was working yesterday.

**Comment by AzGilrock** [comment]
That screenshot shows a work around by adding the linker symbol

**Comment by AzGilrock** [comment]
Unless they mean the update adds the new symbol option

**Comment by robfallone** [comment]
As a datapoint, I was able to load 2023.13 just fine but now experiencing this issue on 2023.15.

**Comment by dkulp** [comment]
I uploaded a 15.1 build to https://dankulp.com/xlights/archive/ which is built with the Beta Xcode and uses the additional flags.   I'm hoping that allows it to work on the older macOS, but it's not submittable to the Apple app store.

**Comment by robfallone** [comment]
@dkulp Thanks for the special build (2023.15.1). It works great on my older mac machine. Is it something we can fix going forward? Or are we saying older mac are no longer gonna be supported in Apple's app store?

**Comment by dkulp** [comment]
Once the next release of Xcode is released, we can submit them to the App Store again.  Until then, I'll need to do special builds and upload them outside the App Store.   Unfortunately, I have no idea when the next release of Xcode may be.   Kind of sucks as I'll need to do two builds, one using the release Xcode to submit for newer Macs and another with the beta to upload separately for older Macs.   Hopefully the new Xcode will come soon.

**Comment by dkulp** [comment]
I uploaded a 15.2 to https://dankulp.com/xlights/archive/  which is built with the released Xcode but with the extra flags.   Can someone test to see if that works?   If so, I'll push it through the app store.

**Comment by dkulp** [comment]
Stuck a second attempt at 15.2 up at that location.   Can you try again?

**Comment by robfallone** [comment]
@dkulp  Second 15.2 works! Ship it.

**Comment by robfallone** [comment]
We just had a success with someone in the Zoom room with the second 15.2. It worked for him as well.

**Comment by robfallone** [comment]
@dkulp The newly release 15.3 through the App Store works great on my older mac. Thanks again
