### ISSUE TITLE
FX Color Palette

### ISSUE THREAD

**Issue by Dubbs2022** [smeighan/xLights#4020]
I've used the "FX" modes a handful of times over the past 2 years, but sometimes I cannot figure out the color to match them. I'd like to see it where the color palette adjusts to what is selected in this menu. 

For example, when I choose Halloween it has a very good orange. But no matter how many times I mess with custom colors I can never match this orange. I've looked everywhere in online files to see if I can find the palette and can't seem to.

Do these colors go into the color dropper by chance?

<img width="179" alt="2023-10-04_193945" src="https://github.com/smeighan/xLights/assets/116459396/14d67e5f-ca77-45ee-8015-08acb0661064">

<img width="946" alt="2023-10-04_194439" src="https://github.com/smeighan/xLights/assets/116459396/0247c481-3234-435b-9529-745ca86f6d65">

**Comment by derwin12** [comment]
I think it is somewhere around here ..
https://github.com/smeighan/xLights/blob/a3a675f91890a1c060d0a6aff9cebea2cb2824d4/xLights/effects/FX.h#L606

**Comment by keithsw1111** [comment]
FX has inbuilt colour palettes which is why you can't see them:

#define PURPLE     (uint32_t)0x400080
   red 64, green 0, blue 128
#define ORANGE     (uint32_t)0xFF3000
   red 255, green 48, blue 0

**Comment by Dubbs2022** [comment]
Thank you Keith, greatly appreciated!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
