### ISSUE TITLE
2023.15 - FPS Warning in Visualizer doesnt seem correct for smart receivers.

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#4021]
![image](https://github.com/smeighan/xLights/assets/4643499/0822b5d2-c837-4634-a6bf-48a192005f05)
Soon as you make it a smart receiver the warning tag is shown.

**Comment by dartunder** [comment]
did you try it with the nightly?  I saw a commit that might affect this.

**Comment by derwin12** [comment]
I did not .. but I see the commit .. That is likely it.
