### ISSUE TITLE
Timeout during string output upload to FalconF16V3

### ISSUE THREAD

**Issue by wratej** [smeighan/xLights#4022]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When attempting to upload string output to FalconF16V3 via FPP proxy, xLights declares upload success. However, upon investigating Falcon controller outputs, they stay the same. Falcon UI is accesible and inputs upload just fine.
**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Configure FalconF16V3 in xLights to be full manged by xLights
2. Configure so that it is networked with FPP device as proxy
3. Configure desired models/ports in Visualizer.
4. Upload inputs and see completed message
5. Upload outputs and see completed message
6. Check inputs on Falcon UI and observe that they uploaded successfully
7. Check String outputs on Falcon UI and observe no change.
8. Click "View Log" in xlights and observe error "2023-10-04 21:35:30,193 139756853846400 log_base [ERROR] Failure to access /StringPorts.htm: Timeout was reached."

**Expected behavior**
Expect an error message in xLights if output upload did not truly succeed without having to check logs
Also expect output upload to function
**Versions (please complete the following information):**
 - OS: Linux Mint 21
 - xLights version 2023.14 app image

Latest log from this problem is attached.
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/12823001/xLights_l4cpp.log)

**Comment by derwin12** [comment]
Did you use a hostname or an ip for your proxy?  If hostname, then replace with the ip.

**Comment by wratej** [comment]
> Did you use a hostname or an ip for your proxy? If hostname, then replace with the ip.

I used an IP

**Comment by keithsw1111** [comment]
First of all I would try the zoom room.

If you want us to help we are going to need your networks & rgb effects files and the ip address of the controller to see if we can do the upload. If we cant reproduce the problem then zoom room is really your only option.

**Comment by keithsw1111** [comment]
BTW ... this is the error:

2023-10-05 14:04:07,540 140453027828096 log_base [DEBUG] Curl POST: http://192.168.1.120/proxy/192.168.100.3/StringPorts.htm
2023-10-05 14:04:37,541 140453027828096 log_base [ERROR] Failure to access /StringPorts.htm: Timeout was reached.

Again though I need to files above to try to reproduce.

**Comment by keithsw1111** [comment]
Ok ... so I need to see your files ... but if we cant reproduce then I would again suggest back to zoom room and try again. The room has different people at different times with different skills.

**Comment by wratej** [comment]
[xlights_networks.xml.txt](https://github.com/smeighan/xLights/files/12839694/xlights_networks.xml.txt)
[xlights_rgbeffects.xml.txt](https://github.com/smeighan/xLights/files/12839695/xlights_rgbeffects.xml.txt)
Attached files with .txt at the end to get around lack of xml upload support

**Comment by derwin12** [comment]
Best if you would repeat the issue then  go into xlights and under tools is
package logs. Run that and upload the zip file it creates.

**Comment by MDickson00** [comment]
Keith, I just dealt with a very similar issue on an F48v3 (White) running 2.55 firmware.

Using FPP as a proxy to his F48 when we hit upload outputs it imediately fails, when we separate the inputs/outputs buttons in xlights it shows a progress bar for about a minute, once it says complete we check the F48 and see no change to the string ports. We zeroed out all ports in the F48 interface and tried the same steps with the same results.

Running xlights 2023.15.3 on MAC OS 10.15.7 see attached packaged sequence.

[F16-Upload-Bug.zip](https://github.com/smeighan/xLights/files/12841908/F16-Upload-Bug.zip)

**Comment by MDickson00** [comment]
Additional log information:

2023-10-08 17:13:29,826 4617338304 log_base [DEBUG] Curl POST: http://192.168.4.62/proxy/192.168.5.200/StringPorts.htm
2023-10-08 17:13:59,828 4617338304 log_base [ERROR] Failure to access /StringPorts.htm: Timeout was reached.
2023-10-08 17:13:59,831 4617338304 log_base [DEBUG] Autosaving backup of sequence.
2023-10-08 17:13:59,831 4617338304 log_base [DEBUG]     Autosave skipped ... no changes detected since last save.
2023-10-08 17:13:59,831 4617338304 log_base [DEBUG]     AutoSave took 0 ms.
2023-10-08 17:13:59,840 4617338304 log_base [INFO] Serial Port 1 Protocol dmx Start Channel 1.
2023-10-08 17:13:59,840 4617338304 log_base [DEBUG] Making request to Controller '/SerialOutputs.htm'.
2023-10-08 17:13:59,840 4617338304 log_base [DEBUG]     With data 'a=0&btnSave=Save&t0=0&s0=1'.
2023-10-08 17:13:59,840 4617338304 log_base [DEBUG] Curl POST: http://192.168.4.62/proxy/192.168.5.200/SerialOutputs.htm
2023-10-08 17:14:29,841 4617338304 log_base [ERROR] Failure to access /SerialOutputs.htm: Timeout was reached.

**Comment by MDickson00** [comment]
He came back in the zoom room and reported that he rolled back to 2023.14.2 and the issue went away, issue appears to be in 2023.15.2.

**Comment by derwin12** [comment]
Another occurrence of this -- Mac duplicated on .16 and .14
fpp via proxy 6.3 latest. Traceroute just shows the one hop to the pi.
![image](https://github.com/smeighan/xLights/assets/4643499/b3a0014f-e6c5-4337-9ed5-e07897b685c5)

**Comment by MDickson00** [comment]
The latest occurance above was on an F48 (v3).

**Comment by cybercop23** [comment]
what we observed on zoom was that the laptop was extremly slowwww even browing the web (to get an archived ver of mac xlights...).. that may be the issue....

**Comment by derwin12** [comment]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/12975430/xLightsProblem.zip)
Another case tonight..
(worked around the issue by creating a static route on the mac so that he could hit the controller directly)

**Comment by wratej** [comment]
Tried again today with the patch @dkulp referenced here https://github.com/smeighan/xLights/issues/4061#issuecomment-1767844468 (Issue #4061 )
Still seeing problem
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/13046633/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
Yeah every instance of these I see involves a FPP Proxy. Can you reproduce the problem without the proxy?

**Comment by wratej** [comment]
I am able to upload to the controller if it's not an fpp proxy setup

**Comment by MDickson00** [comment]
Every instance that we have seen in zoom involves a proxy and Mac OS.

**Comment by wratej** [comment]
In my case I am on a Linux based OS (Mint)

**Comment by wratej** [comment]
This issue appears to have been fixed in 2023.18. Closing as completed. Thanks everyone!
