### ISSUE TITLE
Cape pinout verification issues.

### ISSUE THREAD

**Issue by Strawberry1997** [smeighan/xLights#4026]
When uploading controller configuration from Xlights to my F32-b I get a confirmation box that says: "Could not detect a pinout for F32-B-48 for controller type F32-B.  Configuration will not work.  Verify controller type/model/variant.  Continue?"
Checked all my xlights backup versions. 
these releases have this message:
2023.15
2023.14.2
2023.13
2023.12
2023.10 has no issues.

I think this enh is causing the issue
2023.12 Aug 9, 2023
-- enh (dkulp) Use FPP7 Cape API's to verify cape pinout is usable prior to upload

<img width="566" alt="Screenshot 2023-10-04 at 8 20 37 PM" src="https://github.com/smeighan/xLights/assets/78796480/e0472d8a-e51f-40f9-b65d-d7df1468973b">
 Using:
 Mac Air M2 sonoma 14.0
 
 About Cape/Hat
Name: F32-B
Version: 2.0
Serial Number: W191026183919
Designer: Daniel Kulp
Licensed Outputs: Unlimited ('ww' key)
Output Driver: BBB48String
F32-B is a cape for the BeagleBone Black that provides 32 direct, fused output pixel strings and another 16 strings on 4 differential ports.

I did the  EEPROM Upgrade from the controller with no joy. 
After the EEPROM Upgrade the Licensed  Outputs changed to  | Unlimited ('dk' key).
The controller runs as expected but this confirmation box on upload is showing every time.

**Comment by dkulp** [comment]
Since you are on a Mac, can you check with 15.3  from the App Store?

**Comment by Strawberry1997** [comment]
2023.15.3 has resolved the issue.
Thanks
