### ISSUE TITLE
Xlights output to lights, and test feature don't work with F16v4 as FPP without pi

### ISSUE THREAD

**Issue by ARL120384** [smeighan/xLights#4028]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

I' new to the game here and I've been running F16v4 without a pi. I've has success running my sequence, and finally due to a recent bug fix, FPP connect also works. However, "output to lights" and the xlights "test" feature don't work for me. 

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

1. In xlights, click the output to lights bulb, and play the sequence. There is no output to lights using my F16v4. 

2. Also, try the tools then test function. Ensure all channels are selected, then ensure output to lights checkbox is checked. 

**Expected behavior**
A clear and concise description of what you expected to happen and why.

I am expecting the lights to test, or the sequence to be previewed, because thats what the program is suposed to do.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...] MacOS Ventura, 13.6
 - xLights version [e.g. 2019.37] Xlights 2023.15
 

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publicly please say so and be ready to PM them to one of the developers when asked.
Tried to upload sequence, but file type not supported.

**Comment by derwin12** [comment]
Suggest you go to xlightszoom.com and get some help from the folks to verify if it is a bug.

**Comment by derwin12** [comment]
Found out this is not a capability. If in player mode, it can not accept inputs from xlights. F16v4 doesnt have the resources to do both.

**Comment by ARL120384** [comment]
Ahh ok. I'm in master, but they're essentially the same, correct? 

Thanks for your quick reply!

**Comment by derwin12** [comment]
Yes. I might have the name wrong.

**Comment by ARL120384** [comment]
Theres both master and player mode, but they essentially do the same thing according to the manual. Thanks for your help!
