### ISSUE TITLE
Closing a sequence does not purge it from the layout tab

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#403]
If you close a sequence, the sequence path and name are still displayed on the lower right of the app. Also, once you close a sequence, it does purge the Sequencer tab, but not the layout tab. The play, stop and slider still works.

**Comment by AzGilrock** [comment]
Yeah I'm not sure technically the Layout tab is its own player.  You don't even need an open sequence to play an FSEQ file on that tab.  That was the original use for that tab was to be able to do a conversion and then play the converted file without ever creating an xlights sequence.
