### ISSUE TITLE
Divide timings missing in menu on lyric tracks

### ISSUE THREAD

**Issue by o0charlie0o** [smeighan/xLights#4036]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
After version 2023.14 divide timings is no longer an option when you right click in a lyric track

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Create a lyric track
2. Breakdown phrase / word
3. Right click on phoneme
4. See Divide Timings is missing

**Expected behavior**
Divide Timings is usually the first option

**Screenshots**
Missing in version 2023.15 and 2023.15.3
<img width="278" alt="Screenshot 2023-10-09 at 3 25 48 PM" src="https://github.com/smeighan/xLights/assets/1259226/28a3a27f-0dc9-42aa-8b06-a0af691ffdf3">

Works in version 2023.14:
<img width="421" alt="Screenshot 2023-10-09 at 3 49 38 PM" src="https://github.com/smeighan/xLights/assets/1259226/7e30c62e-4fec-4736-b36b-ec871ac77361">

**Versions (please complete the following information):**
 - OS: Mac 13.4.1
 - xLights version 2023.15 and 2023.15.3

**Comment by derwin12** [comment]
Maybe this commit..  The Divide timings should be enabled regardless of the layerindex value..

![image](https://github.com/smeighan/xLights/assets/4643499/f93bd299-7569-4ae0-9180-e79d619893de)

**Comment by keithsw1111** [comment]
While I don’t mind adding this back I am not sure I get the use case for dividing timings on these layers hence why I disabled it. Can you help me understand why someone would need to do so.

Sent from my iPhone

On 10 Oct 2023, at 8:08 am, Daryl ***@***.***> wrote:

﻿

Maybe this commit.. The Divide timings should be enabled regardless of the layerindex value..

[image]<https://user-images.githubusercontent.com/4643499/273697584-f93bd299-7569-4ae0-9180-e79d619893de.png>

**Comment by o0charlie0o** [comment]
@keithsw1111 I use this extremely often for generating more detailed singing faces. Often for example I'll want to split an AI into 2 so I have AI and E when it's either a longer spread out note being sung or a more powerful beginning to a note that then looks better immediately switching to E as part of the same word. I also often split at the first word in a sentence to add an etc if it doesn't already exist. I even have automations in place on my stream deck to split at 2, 3, 4, 6, and 8. 8 might be used to create a vibrato effect.

**Comment by AzGilrock** [comment]
You can always split a timing the old school way

**Comment by derwin12** [comment]
> You can always split a timing the old school way

What's the old school way? edit the .xsq ?

**Comment by AzGilrock** [comment]
I used to do it all the time….just drag one edge of the effect to shorten it then ctrl-c, click, ctrl-v.   You can get pretty quick at it.   I didn’t even know you could split them so I’ve always done the paste method

**Comment by o0charlie0o** [comment]
@AzGilrock I figured there might be another way and although that does appear to work still it wouldn't be easy to automate from what I can tell. The shortening part is the main issue. Possible with something like keyboard maestro but a lot of room for error when the menu option was right there and consistent. Also wouldn't easily support adding multiple divisions at once.

**Comment by AzGilrock** [comment]
Ok just donate $100 and Keith will put it back in 😂

**Comment by o0charlie0o** [comment]
@keithsw1111 Thanks!
