### ISSUE TITLE
Make the option to lock imported effects a setting that can be defaulted to on or off.

### ISSUE THREAD

**Issue by tmeyermn** [smeighan/xLights#4037]
**Is your feature request related to a problem? Please describe.**
I never want the effects locked when imported so I always have to uncheck the option.

**Describe the solution you'd like**
Make the default to lock imported effects configurable in preference settings.

**Describe alternatives you've considered**
none

**Additional context**
It can be a problem if you re-import with erase existing and you didn't realize the effects are locked so nothing changes.

**Comment by dkulp** [comment]
2023.16 (submitted to apple, will be available for Windows shortly) will save the state of the checkbox and restore to the same state next time the dialog is used.

**Comment by tmeyermn** [comment]
Thank you!
