### ISSUE TITLE
XL4 Optimization Causing Dropped Packets In Some Setups

### ISSUE THREAD

**Issue by dave62350** [smeighan/xLights#404]
Here's my setup:
xLights on Computer ==>  Etherdongle ==> F16V1 ==> Megatree with TM1804 bullet nodes
After converting my sequences from 3.6.x to 4.x, I am seeing jerkiness in the effects on my megatree.   
I described the issue here:
http://nutcracker123.com/forum/index.php?topic=1930.0
I got help analyzing the issue from David Pitts who followed up with Dan Kulp so they understand the issue better than myself, but I am opening this issue for visibility and tracking.  As I understand it, a change was made in XL4 to "optimize" the sending of data packets.  This optimization is causing problems for setups like mine.  I think dropped packets is an appropriate way to describe it.

**Comment by stevegiron** [comment]
I see a code checkin that may address this. Stay tuned.

**Comment by AzGilrock** [comment]
Yes this should have been closed last year.  We always send the data even if it doesn't change.
