### ISSUE TITLE
After Apply Preset -Can we Have a Control Z to Delete it

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#4044]
**Is your feature request related to a problem? Please describe.**
When Applying a Preset and you see it was in the wrong position there is no Ctrl Z to delete what you just applied

**Describe the solution you'd like**
Would like to be able to use a Ctrl Z to delete a wrong positioning of an Applied Preset

**Describe alternatives you've considered**
Have to Highlight the entire Applied Preset and hit delete

**Additional context**

**Comment by keithsw1111** [comment]
That is what ctrl-z is for ... undo.

**Comment by jimswinder** [comment]
But it dosen't work on the Preset Apply...
________________________________

**Comment by keithsw1111** [comment]
I did ... and yes it worked. You do need to focus on the effects grid to undo though as that is where the undo is.
