### ISSUE TITLE
DMX sequence effect on WS2811 protocol prop causes jitter

### ISSUE THREAD

**Issue by GHgeoffrey** [smeighan/xLights#4045]
**Describe the bug**
Seeing an issue in the sequencer and then on the physical fixture (Windows 2023.16) with DMX effects in the sequencer where the DMX effect is controlling a device that is connected using WS2811 as the protocol.  

The issue goes away when the fixture is placed on a serial port in the visualizer and connected up using DMX natively from the controller and the protocol is set to DMX in the Layout.

In my case, I'm using an Experience Lights Pixel2DMX device which works very well but the sequencer is inserting random jitter and I can't figure it out.  

It repros every time when setting the fixture to WS2811 and goes away when setting the fixture to DMX.

In this case, it's a moving head - the issue doesn't occur when the moving head is set up to connect with DMX but when the protocol is set to WS2811, the DMX effect generates erroneous ramp up and down in the visualizer as seen here (- even though the DMX channel settings are set to static values.  Image shows static DMX values circled in blue and the erroneous jitter circled in red.

Issue occurs in sequencer house preview as well as on physical device using a Kulp K8 and an Experience Lights Pixel2DMX when fixture configured using WS2811 protocol.

Issue does not occur in sequencer nor physical device when using DMX protocol and assigned to a serial port on a Falcon F48V4.

**To Reproduce**
Create new Moving Head; assign to a pixel port in visualizer; ensure protocol is set to WS2811 in Layout.  Set a static value to any DMX attribute such as Tilt/Pan/etc.

Expand out the Moving head in sequencer - see the random ramp to full on effects causing jitter in movement of device.

**Expected behavior**
Random movements would not occur.

**Screenshots**

![Capture](https://github.com/smeighan/xLights/assets/147647401/aa2779cc-7520-4a33-b62b-b81db274c40a)
![ws2811](https://github.com/smeighan/xLights/assets/147647401/28f79503-f077-4de0-87a8-9e5ef6914a87)

**Versions (please complete the following information):**
Windows 10
xlights Version 2023.16 64bit

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
You didnt attach a packaged sequence which shows the problem? That makes it a lot less likely that someone will be able to reproduce and thus fix your issue.

**Comment by keithsw1111** [comment]
You do know you have sparkles set to 4 on all effects. That will cause glitching.

**Comment by GHgeoffrey** [comment]
> [TEST MH.zip](https://github.com/smeighan/xLights/files/12872800/TEST.MH.zip)



> You do know you have sparkles set to 4 on all effects. That will cause glitching.

Sometimes another set of eyes is what is needed.  Thank you.

**Comment by GHgeoffrey** [comment]
User error.  Closing.
