### ISSUE TITLE
Selecting locked effects does not show the purple Selected color - they stay red.

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#4046]
If you have locked effects - likely after an import of a sequence and lasso some effects or do a model select effects, the UI still shows the red locked effects and you don't know if they are indeed selected. The selected color should be shown rather then the red locked color.

**Comment by AzGilrock** [comment]
Hmm....then if that change is made you won't be able to tell if the lock/unlock operation is doing anything.  Need a different way to show locked.

**Comment by derwin12** [comment]
Tough to see .. but when you unselect it .. it should be able to go back to the locked red.  Correct though, while selected you cant tell that it was/is red and locked. Catch 22
Locked & Unlocked - not selected
![image](https://github.com/smeighan/xLights/assets/4643499/2ff5c9b4-1144-471d-a007-15991182db85)
Locked & Unlocked - selected
![image](https://github.com/smeighan/xLights/assets/4643499/acf3833a-9bf2-4a1f-9816-aa24b8b878fc)

Do we need to know it is locked while selected? I guess if you try to move it .. which you might want to move the non-locked effects, we would need some way to indicate locked. hmmm...

**Comment by AzGilrock** [comment]
Might be cool to draw a little lock icon beside the effect icon

**Comment by keithsw1111** [comment]
So it turns out you are in control ... there are options for which colour it turns when selected or the reference effect

**Comment by derwin12** [comment]
Is it worth changing the default "Selected Locked effects" color preference from that darker red (which pretty much matches locked red) to something lighter? Like a light red/rose? Going forward new xlights installed would pickup that new default.

**Comment by dartunder** [comment]
How about (200,128,152)?

In [xLights\xLights\ColorManager.h:](url)
            { ColorManager::ColorNames::COLOR_EFFECT_SELECTED_LOCKED, "EffectSelectedLocked", "Selected Locked Effects", xlColor(200, 128, 152), ColorManager::ColorCategory::COLOR_CAT_EFFECT_GRID },
            
![Colors](https://github.com/smeighan/xLights/assets/135712229/17ddc3cf-47c5-4e44-a951-825005b9ac52)

**Comment by derwin12** [comment]
That's essentially what I used..
