### ISSUE TITLE
Adding all display elements, sequencer tab not displaying everything

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#405]
Using OSX: 4.2.20:

I have 105 models in my layout window. When I click on the Sequencer tab and select Edit Display elements, and add everything to the Main View window and then go back to the Sequencer tab, I only see the first 25(ish) on the screen. I cannot scroll to the others that have been added.

I have had to right click on the sequencer tab elements, to edit the display elements again, go back in and make an adjustment to something . move something up or down. then close that window and then I can scroll to the other elements.

**Comment by AzGilrock** [comment]
I've seen this also in other ways like opening a sequence or creating a new sequence.  Haven't tried to track it down but I think a quicker workaround is you can double-click a row heading to expand it into nodes than then double-click again to collapse it and it fixes the scrollbar.
