### ISSUE TITLE
Node Count of Selected Models on Layout Tab

### ISSUE THREAD

**Issue by kylegrymonprez** [smeighan/xLights#4050]
**Is your feature request related to a problem? Please describe.**
Getting an easy to see total pixel count of a set of models without doing an export

**Describe the solution you'd like**
Was thinking of having the node count pop up in the lower right corner of the frame of the selected models. Digging around the code base isn't VERY intuitive yet, but after a few hours of poking around the event system is alluding me.

**Describe alternatives you've considered**
I could generate the XLS report and get the results that way, but I would love to see this at a glance in the editor without doing a report generation

**Additional context**
Looking to implement this is the code base to get familiar with the code, so if there's some pointers as to the methods which would be best to hook into, would love that. Found "FileNameText" as an example of the string to work from, and hook into "StatusBarSizer", but the detection of selection is not computing in my head.

**Comment by dartunder** [comment]
There is a tool tip displayed for individual models.
There is a different tip displayed when multiple items are selected.

Look in LayoutPanel.cpp search for... (around line 8501)
Selected Items:\n -Groups: %d\n -Models: %d\n -SubModels: %d\n 

However, calculating this is not simple,  If it was only models then maybe.  Dealing with groups gets more complex, the code to expand groups and prevent duplicates would be non-trivial.  

Note visualizer shows the total per port if that helps.

**Comment by kylegrymonprez** [comment]
Thanks @dartunder - I'll take a look. 

I found some node calculation elsewhere in the codebase - I can see submodel selctions getting tricky, but perhaps I can figure something out. Thanks for pointing me at that tooltip - maybe I can just add the calculation there and call it a day. 

I'll work on something and if I get close, I'll issue a PR
