### ISSUE TITLE
401 FPP connect response code

### ISSUE THREAD

**Issue by psantia01** [smeighan/xLights#4055]
I used to be able to use FPP connect to upload sequences, now I'm getting a response code 401 error.

I can connect to FPP via my browsers, and it finds it in Xlights (FPP connect), and it starts to upload it only to error off.  I upgraded my Mac to Sonoma yesterday (not sure this matters).
 
<img width="1032" alt="Screenshot 2023-10-15 at 7 27 05 PM" src="https://github.com/smeighan/xLights/assets/117611428/d8216995-bc46-484e-8dae-3573827e4467">

**Comment by dartunder** [comment]
Have you requested help in the zoom room?

**Comment by psantia01** [comment]
I have not, and embarrassingly, I'm not aware of this option.

**Comment by dartunder** [comment]
https://xlights.org/resources/

click on blue zoom meeting button

**Comment by dartunder** [comment]
@psantia01, please close or confirm if you still have this issue.

**Comment by psantia01** [comment]
So taking the password requirement out of FPP fixed the issue.  Thanks!!!
