### ISSUE TITLE
Enhancement request - single color models

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#406]
Currently , the top question/issue that people have pertains to single color models where the default color selected does not match the model and as a result 'nothing appears to work'

is it possible to either default the color palette to white (or none which uses white as a default) when one of these models are selected ?

If that is not possible due to the workflow, then perhaps a warning message for single color models if the colors selected do not match  after the effect is dropped ? (If using this approach , then need a way to turn off the warning i.e. do not show me this warning again)

Or any other implementation....

**Comment by keithsw1111** [comment]
I have added a colour prompt to the sequencer model heading showing the single colour. It doesnt solve this but does serve as a reminder that this is a single colour model.

**Comment by AzGilrock** [comment]
Keith...does the sequence checker spit out a warning for this situation now?  If so I'd say we can close this.

**Comment by keithsw1111** [comment]
No it doesn't.

Could it? Maybe. While we could spot some obvious errors it would be very difficult to be comprehensive. For example what if a bars effect was dropped and one of 3 colours had no red channel in it ... should that be a warning as the other 2 do? As long as the user is happy with the look then i guess it is ok.

I am a little concerned if we generate too many warnings (and we already generate a lot) that users stop engaging in the check sequence and we get back to answering simple error complaints in the forums which have dropped significantly over the past year or so.

**Comment by AzGilrock** [comment]
We changed it so single color models display the actual rendered color but that is only for effects that draw backgrounds like the On effect I believe.  Anyways I don't believe we are going to do anything additional here so closing.
