### ISSUE TITLE
Falcon F16 V4 Port Brightness reset on settings upload

### ISSUE THREAD

**Issue by santiagohl** [smeighan/xLights#4069]
I have encounter an issue with uploading configuration to the Falcon F16 Version 4 that when I upload the settings it will reset the brightness on the falcon to 100% for all ports.

When I upload to my Falcon F16 Version 3 this does not happens and the brightness for each port remains at what ever percentage I have set it.

Please fix the upload from xlight to Falcon F16 Version 4 so that it will not reset the brightness levels on the ports.

Controller info
Falcon_F16V4_948D

Let me know if there is anything else you need from me to help in correcting this issue.

Thank you in advance

**Comment by computergeek1507** [comment]
Disable full xLights control

**Comment by santiagohl** [comment]
Full xlights control is not enabled

![2023-10-20 22_00_38-xLights - E__Documents_xlights_Holloween_Halloween_static xsq](https://github.com/smeighan/xLights/assets/18582362/c76a2593-760b-4044-9061-29fa2e7dd3eb)

**Comment by dartunder** [comment]
Upgrade xLights.

The controller tab should have a default brightness option.

![image](https://github.com/smeighan/xLights/assets/135712229/e96a45e9-2b0f-47ad-837c-88bb52605ba9)

**Comment by computergeek1507** [comment]
@dartunder he is saying with that disabled default port brightness xLights is overriding the brightness set in the webui of the falcon. Most of the controller upload code is written so it will get the settings from the controller and only override the settings it needs to change. If Full xLights Control is enabled then xLights will overload all the settings.

**Comment by dartunder** [comment]
I see that the default brightness disappears when full xlight control is disabled. So I was mistaken regarding needing to update.  Without a falcon to test, I can't debug the remaining code. 

But the quick fix is to enable full control and set the default brightness in xlights, and or set the brightness per prop on the layout tab.

**Comment by santiagohl** [comment]
Correct, with Full xlight control **disable** when uploading to the F16 V4 it will override all brightness control and will make them all 100% on the V4. Same settings for the F16 V3 it **does not** override the brightness settings which is what prompted me to come here and report a bug. I need to add a note here, Only the Ports that have been configured or being used in xlight that are being updated are the ones to get reset.

Not a huge deal but I was trying to setup was trying to setup a few new props and had to upload setting either 5 or 6 times while troubleshooting and you know it got annoying to have to and reset brightness manually for all port configured each time I uploaded.

Here is a quick video for you to see the issue

https://github.com/smeighan/xLights/assets/18582362/a6b54594-5a4c-4bf1-8841-869db0d42403
