### ISSUE TITLE
Copy works offscreen left to right but not top to bottom

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#407]
I can copy effects left to right when the effects don't fit on the screen. I can then paste them to a different model and they will fill in as expected.  The same is not true when copying top to bottom on a model with many layers. While it appears the paste will only paste to the screen, it's the copy that only copies the visible rows. Verified by pasting back to a text editor.

**Comment by AzGilrock** [comment]
I can make the copy fail and I was able to do off screen copy and paste in both directions.  The only thing I see is there might be a selection problem.  I bet if you look again the effects you are trying to copy aren't actually highlighted pink.

**Comment by stevegiron** [comment]
No longer an issue.
