### ISSUE TITLE
Ability to save Batch Render List and FPP Connect Upload List

### ISSUE THREAD

**Issue by sheisler314** [smeighan/xLights#4074]
**Is your feature request related to a problem? Please describe.**
I think it would be very helpful to be able to save the list of checked sequences in "batch Render" and in "FPP Connect Upload" so that you could have a bulk batch render list, which is required after making changes to layout or ports.   Then, when only one sequence changes, it doesn't wipe out the list of checked sequences when you just want to render 1 or 2 or 3 sequences and upload those.  With 30 or 40 sequences, it can get very long to check and uncheck batch/upload items.  My work around for this is to have different computers do single or small # of batch renders and uploads and the master computer does them all (current/in-use sequences).  A "save list" option would resolve this.

**Describe the solution you'd like**
As indicated in my feature request description, the solution would be the ability to save the list, like we can save mappings and other areas of xlights

**Describe alternatives you've considered**
The only alternative I have is to use different computers with xlights installed and sharing the same data set, and use those computers to upload 1 or 3 sequences (and for small-batch rendering).  This is obviously not effecient.

**Additional context**

**Comment by dartunder** [comment]
Can you put the items you normally want to be rendered in your show folder and the others in a sub folder?  Then the standard filter logic can be applied.

FPP connect mostly skips files already uploaded, so having extra ones checked is not as bad as one might think.  Again if the sequences are organized then the automatic could allow you to easily select all and get the ones you want.

**Comment by computergeek1507** [comment]
You could make a lua script to do this

**Comment by keithsw1111** [comment]
With scripting I think you have everything you need to achieve this.
