### ISSUE TITLE
Model start channels greater than 99,999

### ISSUE THREAD

**Issue by darylc** [smeighan/xLights#408]
Is it possible to get the 99,999 limit raised?  I am having trouble compressing my controllers to make it all fit.

**Comment by darylc** [comment]
Looks to be just these 2 places to change it:

xLights/ChannelMapDialog.cpp:    SpinCtrlBaseChannel = new wxSpinCtrl(this, ID_SPINCTRL_BASE_CHANNEL, _T("1"), wxDefaultPosition, wxDefaultSize, 0, 1, 99999, 1, _T("ID_SPINCTRL_BASE_CHANNEL"));
xLights/ModelDialog.cpp:    SpinCtrl_StartChannel = new wxSpinCtrl(this, ID_SPINCTRL4, _T("1"), wxDefaultPosition, wxSize(90,21), 0, 1, 99999, 1, _T("ID_SPINCTRL4"));

**Comment by AzGilrock** [comment]
Since the limit is in the spin control only you could probably just type in the start channel you want in the XML file to get you going.
