### ISSUE TITLE
Servo Model & Value Curves Bug

### ISSUE THREAD

**Issue by McCoyCOREUSA** [smeighan/xLights#4084]
I'm using the Servo effect.
xLights v2023.18
Windows
Files attached.

When using value curves with the Servo effect, the start level and end level randomly change. I've played with this for several hours and it appears to be a bug where the values of another servo effect (the last I edited) are displayed/used in the next servo effect I edit. It's not every time. But it's definitely easily duplicatable. 

This is causing random servo values to be sent to my prop, physically breaking it in some cases.  

I had the guys in the Zoom Room review this with me and confirmed it must be a bug. Video link is below.

I'm happy to help with any troubleshooting I can do on my end. Unfortunately, the animatronics I built won't be able to run until this issue is resolved, so I'm anxious for a solution. 

VIDEO: The following link is for the screen capture video I took during the Zoom Room. I think I had the room audio off, but you can hear me and I demonstrate the issue.

VIDEO LINK: https://mccoycloud.com/index.php/s/T9AycFBoBWSyiSx

SUGGESTION: Is it possible to display the value curve data in the Effect Panel when it's set? Even the basic data? There is no way to view it without opening the value curves panel, which seems to be the point it's breaking in this situation.

Thank you,
Scott McCoy

[SANTA MOVEMENTS v2023-01.zip](https://github.com/smeighan/xLights/files/13196825/SANTA.MOVEMENTS.v2023-01.zip)

**Comment by AzGilrock** [comment]
I doubt this behavior is specific to the Servo effect and I wrote it.   xLights is designed to carry over the settings when the same effect is being used.   This sounds like a problem that happens because you are hooked up live while editing so isn’t the solution to prevent damage to not have output to lights on while editing?   This shouldn’t prevent you from running a show.  Also haven’t you set the limits for the model so that it wouldn’t send commands that move it past a good range?  I didn’t have time to watch the video.  This is a busy time of year for me also

**Comment by McCoyCOREUSA** [comment]
Gil, I don't edit live. I edit, then turn on and test. The problem is random. I can open the edit value curves on a selection, close the window (not cancel or save), then go to another and the value curves carry over. I know the previous values carry over when a new effect is created, but this happens on existing effects. Both are existing and have been set and saved. But at random, those numbers change without saving or actual editing. All I do is open the value curves to check my settings. 

Here is another example. I create sections for multiple servo movements. I get them set and working perfectly. Then, I create a new section of effects. I needed to check an effect on the first section, so I open it to view, then I close the window without saving. Somehow, that has changed the values on that working section, which makes it no longer work properly. 

It's like the carry-over of values that works for adding a new same effect is also (sometimes) doing that behavior to existing effects.

**Comment by AzGilrock** [comment]
Ok I’ll look into it when I can if no one else gets to it first.   I’m doing 100 mile bike ride in the morning so I won’t be in any condition to get on the computer rest of the day

**Comment by McCoyCOREUSA** [comment]
Thank you! And I'd be in the hospital after that ride! Haha Have fun.

**Comment by AzGilrock** [comment]
But just knowing how the effect code works if there is an issue it should be common…If someone could try doing similar steps with a different effect that uses value curves it might reveal that

**Comment by McCoyCOREUSA** [comment]
I've played with this for a long time. Definitely something wrong as shown in the video where I duplicated it. I set value curves and some just don't stick, or they change upon saving or something. This is really easy to see since I'm using a servo prop, so when a movement is wrong, it's very wrong and visible. I go back and check value curves and they are not how I originally set them. It takes several edits in some cases to get the values I need to stay.

**Comment by AzGilrock** [comment]
So its nothing to do with the Servo effect.  What you are seeing is how all Value Curves work.  Its the way you are closing the Value Curve window.  Take note that if you hit the red X or hit Cancel you deactivate the Value Curve.  You have to hit Ok for it to stay active.  So once you set it to in-active and then click on a different effect and then move back to that effect and click on the value curve its going to now inherit the settings from the one you just opened on the other effect.  So yeah its kinda quirky the way things work but its that way for all value curves not just Servo.  I tested on Morph and it does the same thing.

**Comment by McCoyCOREUSA** [comment]
Thank you. I actually caught Keith in the Zoom Room today and we walked through this and came to the same conclusion. I think if I was clicking the cancel button, I was expecting no changes to be applied. Now that I understand 'cancel' means reset to no value curves, I'll rework my stuff.
