### ISSUE TITLE
2023.18 - Can't delete imported effects

### ISSUE THREAD

**Issue by jdrews417** [smeighan/xLights#4088]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
A sequence that has imported effects, if you want to remove some (didn't like import, changing, whatever), the effect refuses to be removed.

**To Reproduce**
-Start a new musical sequence
-import effects from an xlights export (say, xlights around the world starter sequence)
-Now try to clear/remove a couple of the imported effects. They refuse to clear.
-Add a new effect to a track (not from an import)
-delete the new effect - the effect does delete

**Expected behavior**
Being able to delete an effect after importing it.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2023.18

**Additional context**
Used to work, not sure which verion since 2022.x it broke in.

**Comment by AzGilrock** [comment]
The effects are being imported as locked.   And I think they added a new option for you to choose but I believe it’s currently defaulting to locked.  So select all the effects and unlock them first
