### ISSUE TITLE
Lua Script - Select Sequences and deselect highlighted does nothing?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#4092]
lua:

seqs = PromptSequences()

Can others confirm - is it just my script?
Using above script line to select sequences, have a couple of items and right click - select Highlighted. That works. 
Right Click and Deselect Highlighted and it does nothing??

If you "Select Highlighted" again, it actually unselects them :-)

![image](https://github.com/smeighan/xLights/assets/4643499/9dd430da-dcbd-4682-b67e-445a41b75b9c)

**Comment by computergeek1507** [comment]
It's the same dialog at batch render, does it work in batch render?

**Comment by derwin12** [comment]
Interesting .. no it doesnt work there either.

**Comment by derwin12** [comment]
Is it this?
BatchRenderDialog.cpp .. should it be ID_MNU_DESELECTHIGH ?
![image](https://github.com/smeighan/xLights/assets/4643499/344ff4ab-9979-4b15-8f66-5aeaf2857df0)
