### ISSUE TITLE
when rendering effects on linux xlights slows down responding to mouse

### ISSUE THREAD

**Issue by cp16net** [smeighan/xLights#410]
I created a model and a sequence and then when i go to add an effect on the grid everything tends to slow down with xlights. 

i watched the process with top and never saw the memory or cpu spike.

I'm running this on a big machine (120gb ram, 16 core) and confused why this would occur. Running on my mac i dont see any issues. 

I might try on another machine i have to see if it happens there as well later. Posting this just to see if others have seen similar issues.

**Comment by AzGilrock** [comment]
With that much ram and cores it sounds like some kind of rack server.  We run OpenGL how is the video hardware in that thing?

**Comment by cp16net** [comment]
The video card is decent.

02:00.0 VGA compatible controller: NVIDIA Corporation GM107GL [Quadro K2200] (rev a2) (prog-if 00 [VGA controller])
        Subsystem: Hewlett-Packard Company Device 1097
        Physical Slot: 2
        Flags: bus master, fast devsel, latency 0, IRQ 74
        Memory at f2000000 (32-bit, non-prefetchable) [size=16M]
        Memory at e0000000 (64-bit, prefetchable) [size=256M]
        Memory at f0000000 (64-bit, prefetchable) [size=32M]
        I/O ports at 1000 [size=128]
        [virtual] Expansion ROM at f3080000 [disabled] [size=512K]
        Capabilities: [60] Power Management version 3
        Capabilities: [68] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [78] Express Legacy Endpoint, MSI 00
        Capabilities: [100] Virtual Channel
        Capabilities: [250] Latency Tolerance Reporting
        Capabilities: [258] L1 PM Substates
        Capabilities: [128] Power Budgeting <?>
        Capabilities: [600] Vendor Specific Information: ID=0001 Rev=1 Len=024 <?>
        Kernel driver in use: nvidia

freeglut3-dev:
  Installed: 2.8.1-2

Running debian jessie.

**Comment by AzGilrock** [comment]
I'd just use a more normal computer.  No one will be able to debug this but you.

**Comment by cp16net** [comment]
I noticed if i close the house preview and just use the model preview everything seems to work much better. I tested on another linux machine i have and saw the same slow down. Not sure why the house model would cause such a slow down.

**Comment by cjd** [comment]
It is most likely caused by the threading of wxwidgets on linux.  It seems to have a number of performance issues when talking between worker threads and the GL/gui thread.
Running xlights with 'taskset -c 0 xLights' to force xLights onto a single cpu helps a bit (and reduces crashes) but rendering will still be a slower than if more cpus were usable

**Comment by cp16net** [comment]
@cjd I saw this on another bug that was mentioned to help crashes but it didnt seem to help the slow down. Its very likely that the reason is wxwidgets on linux.

Is there a hard requirement to use version 3.0.1 of wxwidgets? I havnt tried the latest version 3.0.2 to see if there are any build errors. Thinking maybe there would be improvements using the latest version.

**Comment by AzGilrock** [comment]
We use 3.0.2 on Windows.

**Comment by cjd** [comment]
I'm using 3.0.2 on linux as well

**Comment by dkulp** [comment]
On OSX, we use what ever was the latest on the 3.0.x branch in git when I last built it.  :-)   3.0.2 doesn't work well on El Capitan and I need some of the fixes that have not yet been released.

**Comment by cjd** [comment]
Is this still occurring?
We have moved to wxWidgets 3.1 on linux now and I haven't seen this failure since then

**Comment by cp16net** [comment]
I have not had a chance to verify this with life occupying my time. We can close this issue for now.
