### ISSUE TITLE
Crash on Check Sequence

### ISSUE THREAD

**Issue by TrekErs** [smeighan/xLights#4106]
**Describe the bug**
xLights crashes on check sequence with this sequence.

**To Reproduce**
Load Underneath the Tree sequence....Tools....Check Sequence

**Expected behavior**
Program should not crash

**Versions (please complete the following information):**
 - OS:  Windows 11 22H2
 - xLights version 2023.19

**Additional context**
Other sequences checked fine, this sequence checked fine prior to import of effects from PPD.

**Attachments**
Crash log zip can be emailed

**Comment by derwin12** [comment]
If it crashes without the sequence -then upload that dump zip here .. otherwise if you could upload the tools->view.log
Dont post the crash zip here - wait for a developer to acknowledge and request it.

**Comment by TrekErs** [comment]
It only crashes with the sequences, I've emailed it to Keith.


On Mon, 06 Nov 2023 16:52:10 -0800, Daryl ***@***.***> wrote:
 
 

If it crashes without the sequence -then upload that dump zip here .. otherwise if you could upload the tools->view.log
Dont post the crash zip here - wait for a developer to acknowledge and request it.
