### ISSUE TITLE
Bounce effect on single strand broken

### ISSUE THREAD

**Issue by gothambeat** [smeighan/xLights#411]
When you select a bounce effect on a single strand the first element doesn't seem to turn on.  Example: I have 8 channel all white arches.  When I bounce them, they start on channel 2.   2,3,4,5,6,7,8,7,6,5,4,3,2,3,4,5,.....

**Comment by stevegiron** [comment]
There is no bounce effect in Nutcracker.

**Comment by gothambeat** [comment]
Steve,  it is the bounce option in the single strand effect.

**Comment by PhilHilton** [comment]
I'm not sure if this is related, but I also noticed that at the end of a bounce, the start of the next can be seen. I've added a screenshot that highlights this and the reported issue. In the bounce shown it is set to 3 cycles, but you can see it includes part of a 4th at the very end, and it starts with the first few pixels already fading out, having missed their queue. It's like the whole effect is offset.

![chase-startandendissues](https://cloud.githubusercontent.com/assets/10479191/11322302/900e0bc6-90b3-11e5-8e36-d7b9870d8f77.png)
![chase-startandendissues-settings](https://cloud.githubusercontent.com/assets/10479191/11322303/9010c1a4-90b3-11e5-9430-3894a04ec240.png)

**Comment by AzGilrock** [comment]
We had a user update the SingleStrand effect on Feb 28th.  From the description it may have fixed this if someone could verify.

**Comment by PhilHilton** [comment]
My apologies. I got a notification for the issue being closed but not for the comment on May 10th. I'll take a look when I get my light software setup again and re-open if it's still an issue. Thanks.
