### ISSUE TITLE
Windows Dark Mode Color Issue on Layout Tab

### ISSUE THREAD

**Issue by TripleJ3EB** [smeighan/xLights#4114]
Windows 2023.19

On the controllers tab, when you select a controller in the list, the highlighted color of the line is a bright gray, very easy to see.  If you click over to change a property, the highlighted controller changes to a darker gray color, but still very visible to see.

However, on the Layout tab, when selecting a model in the list, it uses the system standard color I believe, in my case a blue, still very visible, but the problem is when the list loses focus, the color of the selected model changes to a black that is barely distinguishable from the rest of the items in the list.  

It would be great if Layout tab highlight colors worked the same as the Controllers tab as I am spending a ton of time trying to make sure I am on the right model.

Thanks!

**Comment by TripleJ3EB** [comment]
Also, on the property pane below the model list on the layout tab, the group headers are not a different color than the sub properties. so the groupings become almost useless as its impossible to quickly jump to the section you are looking for.

**Comment by keithsw1111** [comment]
There is not much we can do here without customisation of wxWidgets.
