### ISSUE TITLE
Toggle to lock/unlock all effects.

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#4121]
Seems alot of people are getting confused importing sequences and having all the effects locked,

Perhaps a toolbar option to lock/unlock all may help?
Or checkbox near suspend render checkbox,

Thoughts?

**Comment by cybercop23** [comment]
I use key bindings even before this change to help with not moving things around... Ctrl A L or Ctrl A U

**Comment by darylc** [comment]
Certainly easier ways to unlock effects would be welcome now we are all faced with huge numbers of unexpected locked effects. Eg I was expecting to find unlock effects when right clicking on a model in the sequencer.

**Comment by AzGilrock** [comment]
Seems pretty easy to me.  If you want to unlock a single model right-click the model and do Select Effects then right-click in the grid an Lock/Unlock.  For all effect right click a model and select "Show All Effects", Ctrl-A, right-click Lock/Unlock.  Its literally a few seconds and shouldn't be an operation that's done that often.
