### ISSUE TITLE
Color errors when performing Z-rotation effects

### ISSUE THREAD

**Issue by szaske** [smeighan/xLights#4124]
I'm trying to create an effect where a prop rotates 90 degrees. To accomplish this I was using the Z-rotation effect. However when I do this (in version 2023.19) my colors get all messed up.  Transparent pixels appear in what should be a red section of the effect. I've attached a sequence that demos this issue.

But in case this sequence does not work, here's how to reproduce the issue.

1. Drop a matrix in your scene. Make is 50 pixels by 50 pixels
2. Create a sequence and add a On effect to the matrix. Make the color red.
3. Select the effect and click on the Roto-Zoom tab.
4. Set Z Rotations to 1
5. Set Z Rotation to a value curve. Use the Ramp setting and ramp from 0 to 100

What you'll see is the red color rotation 360 degrees, but at the same time this pattern of transparent holes will appear inside of your shape

I assume what's happening is that rounding error are causing the code that attempts to rotate the effect is unable to determine what color a pixel should be...and if it cannot determine a color it makes it transparent.  Instead the code should, when it's unable assign a pixel a color, it should instead check the pixels to it's left and right top and bottom and pick whatever of those colors is the most prevalent...or something similar.  As it is now the z rotation effect is not usable, because with these transparent pixels the whole prop blinks wildly while the rotation is happening.  Interestingly this blinking only occurs with a Z rotation.  X and Y rotations work without the flashing.

[z-rotation-error.zip](https://github.com/smeighan/xLights/files/13330676/z-rotation-error.zip)

**Comment by derwin12** [comment]
I asked this previously -- the answer was to bump up the Zoom Quality. That fixes you scenario above as well.

**Comment by szaske** [comment]
That's a great work around, though I'm not sure anyone would know to look for it. Perhaps we can leave this issue active so other people can find the discussion
