### ISSUE TITLE
FPP Connect Issue with F16V5

### ISSUE THREAD

**Issue by dsw-solutions** [smeighan/xLights#4128]
**Describe the bug**
xLights 2023.19 FPP Connect will not detect or add a Falcon F16V5 set in player or remote mode. 

**To Reproduce**
1. Go to FPP Connect
2. Click on 'Add FPP'
3. Enter IP of F16V5 controller
4. Controller is not added

**Expected behavior**
Controller is shown in list and can upload files to it via FPP Connect.

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2023.19

**Comment by BurtdeErnie** [comment]
Same issue here. Following

**Comment by keithsw1111** [comment]
I dont seem to be able to reproduce this. I can both discover my controller in player mode and add it manually if i bring up fpp connect first then power it on. I tried in remote mode and it worked fine.

**Comment by dsw-solutions** [comment]
The FPP MultiSync page detects it in FPP but FPP Connect in xLights does not for me. I even upgraded to 2023.20 and same thing.
![image](https://github.com/smeighan/xLights/assets/67870268/6e69a989-a93e-499d-9a35-d4298615849f)
![image](https://github.com/smeighan/xLights/assets/67870268/b6c9342c-fc59-4f9e-9655-3ba25670acda)

**Comment by computergeek1507** [comment]
I added support two days ago, but I don't have a V5 to test with. If you download the nightly you can test and see if it works.
8e20c535331197c63330f0a61b0ad23512cc2253

**Comment by aadu** [comment]
Has anyone tested and can confirm this works? I've experienced the same issue. Interestingly for me, there are also issues detecting espixelstick instances in remote mode. Not sure if it is related.

**Comment by keithsw1111** [comment]
I believe this works with 2023.21
