### ISSUE TITLE
Batch Render - Progress / Suppress issues and notify at end.

### ISSUE THREAD

**Issue by cathelest** [smeighan/xLights#4129]
**Progreess**
Is it possible to add a overall progress,

Either by a Count Rendering Sequence ?? of ?? etc,
Or possibly a progress bar, 
I realize some sequences are longer or shorter and have more effects, so not a perfect indicator, 

**Suppress Issues**

With batch render, is it possible to suppress all the issue prompts, but have it notify issues with sequences at the end,

At present I have 40+ sequences, and cant take over a hour for them to batch render,
If 1 has a issue it will prompt, and stop batch render until corrected,

Is it possible to have them warning suppressed, and have it simply prompt that there are issues with the following sequences,
Please reopen and check manually etc.

**Comment by keithsw1111** [comment]
With the latest changes I think we have done all we will do for now. I do tell you what sequence is being rendered and how many are left in the list. We have also implemented changes which auto solve some model rename issues with new model alias functionlity. Along with the suppress functionlity Daryl mentioned I think that is it for now.
