### ISSUE TITLE
ENHANCEMENT - Pseudo-Timing Grids

### ISSUE THREAD

**Issue by ghost** [smeighan/xLights#413]
It would save a lot of time (at least it would save _me_ a lot of time given the way I sequence) if there were virtual timing grids which were sub-divides of a grid already made. They would not be selectable or movable because they wouldn't be be part of the timing grid, but rather generated on the fly based on the real timing marks. Perhaps they would be a different color or just lighter.

For example, I go ahead and tap out every 4 beats (1 music measure) of a 4/4 song. Easy.. Quick..  I would then, as needed, right click on the timing grid and find a sub-menu of the context menu labeled Pseudo-Grid or Virtual Timings or similar. In that sub menu would be options for 1/2, 1/4, 1/8, 1/16 (maybe more.. 1/12 for triplet notes?). Choosing one of these would show timings which were subdivisions of the parent timing grid. 

So I've got those full measure timings (down beats, essentially), but i want to change effects on every beat. I would select pseudo-timing of 1/4 and have instant access to those beat timings without having to create them.  If I was working on an intricate guitar solo I may need 1/8 or 1/16. When I'm done with that section, I just turn off the pseudo-grid and it's no longer cluttering up the view.

Creating detailed and precise timing grids like those are tedious (especially since the split tool isn't working for me), but with pseudo timings not only would they be easy, but I wouldn't even have to make them. All of the precise and detailed timing markers would be extrapolated from the simpler, easier to make parent grid.

**Comment by keithsw1111** [comment]
We made it possible to divide grids ... not virtual but good enough.
