### ISSUE TITLE
The appimage hasn't been built since 2023.18

### ISSUE THREAD

**Issue by fone626** [smeighan/xLights#4131]
The linux appimage hasn't been built since 2023.18

**Comment by twardnw** [comment]
Also missing from the nightly builds too :(

**Comment by ChrisHammond** [comment]
Well that explains why I wasn't finding it..

**Comment by cjd** [comment]
Updated docker image created/uploaded now - next release should auto-build appimage again.

**Comment by cjd** [comment]
Confirmed working with 2023.21 release

**Comment by twardnw** [comment]
Thanks @cjd !

**Comment by computergeek1507** [comment]
@cjd can we automate the docker hub image creation by adding a GitHub action to the repo that does the generation?

**Comment by dkulp** [comment]
@cjd I think I have that figured out.   Can you check?

**Comment by cjd** [comment]
Yep - looks to have worked.
Testing now and will update travis (assuming it works)

**Comment by computergeek1507** [comment]
The app image builds with a git action in the main repo. I hope to figure out how to create a flatpak as well someday

**Comment by cjd** [comment]
I gave a test build via 'linux docker manual' workflow - and looks like we are good from now on :)

**Comment by twardnw** [comment]
And now the appimage for 2023.22.1 is missing :(

**Comment by dkulp** [comment]
22.1 was Mac only.  There wouldn't be an app image for it.

**Comment by twardnw** [comment]
well, no appimage for 2023.22 either ;)
