### ISSUE TITLE
Automatically update start channels when using a shadow model

### ISSUE THREAD

**Issue by smtpboy** [smeighan/xLights#4132]
**Is your feature request related to a problem? Please describe.**
When you use start channel based shadow models (as in Keith's youtube video), even a slight change to your layout can cause you to have to go in and potentially re-align all the start channels on your shadow models, creating a lot of repetitive layout editing.

**Describe the solution you'd like**
When "Shadow Model for..." is checked, automatically apply or update the start channel from that model to the primary model it is shadowing any time it updates or changes, possibly with an "automatically update channel numbers" checkbox to ensure this only happens if the user wants it to happen.  This would save a lot of time and frustration if you use a lot of shadow models.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by derwin12** [comment]
Can you post some screen shots of how it gets out of sync - I cant see why it would do that. Your shadow should be pointing to the start of the shadowed model and move to whatever port(s) you place the shadow on.

**Comment by smtpboy** [comment]
@derwin12 I think I fell victim to the age old problem of "enhancement overlook" in xLights again.  I was using older instructions that have you copy the start channels manually instead of using the "Start of Model" approach, which I just found in a later video.  So this feature already exists, I just wasn't aware of it.  The joy of videos that never get updated or taken down to indicate there are newer/better ways of doing things I guess. :)  Thanks for the insight.
