### ISSUE TITLE
Remove Preference to Save FSEQ File On Save

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#4138]
When would someone want to have this not checked?
![image](https://github.com/smeighan/xLights/assets/4643499/0777f361-f1b9-4ffc-a785-37dfdac5523d)

**Comment by dkulp** [comment]
When running on a machine with spinning disks, saving the FSEQ file can take quite a bit of time, particularly if you are forced to use uncompressed sequences.  For people that tend to hit "save" often while doing work, it can severely slow them down.  Also, for xSchedule folks, it would prevent updates to the running show while working on the sequences until it's "ready".

**Comment by derwin12** [comment]
How do they create the fseq files in those cases?

**Comment by dkulp** [comment]
When they eventually need it, they turn the option back on.   Either that or use batch render.

**Comment by derwin12** [comment]
Will close this .. had a user get this warning about it not saving.. thru me for a loop - why that would be a preference, he saw some video saying oh just ignore that warning. He wondered why his sequences were not working on fpp.
