### ISSUE TITLE
xlights.org download not working... per user report.

### ISSUE THREAD

**Issue by dartunder** [smeighan/xLights#4139]
Zoom user said and I confirmed...
Hey guys!  Is there something going on with the xlights.org website?  I try to download the latest version and it sends me in a vicious loop to the download page....

They were sent to GitHub to download directly as a workaround.

**Comment by dartunder** [comment]
Also, the zoom link is broken,
@keithsw1111

**Comment by Jaredag159** [comment]
Also confirmed, tried to update from xlights and the downloads page and neither option works.

**Comment by EvilForge** [comment]
No issues downloading from the popup in xlights or via web downloads page for me just now (tried it twice, xlights64_2023_20.exe, successful ran installation too..) I'm based in USA, Texas, if it helps any.

**Comment by typasch** [comment]
+1. I'm getting a 404 when I visit https://xlights.org/faq/how-to-install-xlights-on-osx/ 

Clicking the "[Click here to see list of MAC versions of xlights](https://xlights.org/download/3006/)" link just redirects to the homepage: https://xlights.org

**Comment by EvilForge** [comment]
Confirmed, I see the same. (but I only use windows x64) - on a whim i checked and https://xlights.org/faq/how-to-install-xlights-on-windows/ throws a 404 also.
(console error in Brave Browser: how-to-install-xlights-on-windows/:1   GET https://xlights.org/faq/how-to-install-xlights-on-windows/ 404 (Not Found))

**Comment by dartunder** [comment]
This appears to be fixed.

**Comment by typasch** [comment]
Still unable to view the Mac downloads page. Still getting a 404 for the "how to install" page.

**Comment by dartunder** [comment]
so some things are fixes and may are not.

**Comment by arretx** [comment]
Same issue.  Unable to find any download links for OSX.

**Comment by cjd** [comment]
I just had a quick look and all the wordpress plugins were disabled (don't know why)
Re-enabled the nessecary plugins and the site looks to be working properly again now

**Comment by cjd** [comment]
hmm - that may have fixed the site - but has messed up the admin pages.
Investigating now

**Comment by arretx** [comment]
One plug-in at a time. ;)

**Comment by cjd** [comment]
Hmm - now I can't even disable each as it looks like a plugin requires confirmation to disable :(
@keithsw1111 do you have access to the backend (ftp or ssh) so we can force disable them for now?
I used to have access but looks like things have long since changed :)

**Comment by keithsw1111** [comment]
I dont but @wcfrostick does. He is currently in the last couple of days of setting up a big show and may be able to help on the weekend.
