### ISSUE TITLE
HinkxPix won't allow assignment to smart receiver 3-9

### ISSUE THREAD

**Issue by dartunder** [smeighan/xLights#4148]
Selecting 3 is being processed as if the user selected 3 cascaded remotes.

I attempted to fix but then it doesn't handle cascaded remotes correctly.

https://github.com/smeighan/xLights/pull/4147

The original issue stems from:
       } else if (label >= "0" && label <= "25") {
which doesn't match "3"

Fixing this like this:
      } else if ((label >= "0" && label <= "9") || (label >= "10" && label <= "25")) {
      
This solved the original issue but it became clear that now selecting the number of cascades would be interpreted as selecting the corresponding smart receiver.

I thought about changing the menu to show SR 1, SR 2, ... SR 25.
If someone can tell me how to know which submenu the selected id is from then that could be used to alter the logic.

**Comment by dartunder** [comment]
The workaround is to set the smart remote in the layout tab. It is time-consuming but at least possible.

**Comment by computergeek1507** [comment]
I made a super hacky fix for this

**Comment by dartunder** [comment]
Thanks Scott! Clever way to tag the menu to know what type it is.
