### ISSUE TITLE
LOR Style Tap to Time

### ISSUE THREAD

**Issue by technoj** [smeighan/xLights#415]
I'm sure someone has already suggested this, so if this already exists, feel free to correct me.  Is there any way you can add a feature similar to the LOR timing where you tap (to the music) every time you want to add a timing?  This would simplify A LOT!!!!

**Comment by stevegiron** [comment]
Page 125 of the user guide will sort you out with that. 
http://nutcracker123.com/nutcracker/releases/XL4UserManual_v1.2.pdf
