### ISSUE TITLE
Blink does not work as expected  as of 2023.20 with new blink rate control.

### ISSUE THREAD

**Issue by dartunder** [smeighan/xLights#4152]
This commit has broken the blink effect under some conditions.  The behavior is not consistent.

Adding ability to adjust the frequency of the "Auto" eye bl… …ink
https://github.com/smeighan/xLights/commit/45e34cae999eadd7b2e5d09e7b9395059cd0486d

https://github.com/smeighan/xLights/pull/4089

Add a singing tree (ChromaCharacters--Christmas Tree) to the layout, create  new animation, add face effect for full 30 duration.
Set the Phoneme to "rest".    Run it, render it, click on and off the effect, render again play again, and again and again, etc. sometimes it will not blink at all.  This behavior is different than before.

I verified that the behavior is as expected prior to this commit.

@kylegrymonprez, So please take a look and see if you can reproduce this issue.  Good luck.  

Work around use version 2023.19 to render the sequence.

**Comment by dartunder** [comment]
FacesRenderCache* cache = (FacesRenderCache*)buffer.infoCache[id];
    if (cache == nullptr) {
        cache = new FacesRenderCache();
        buffer.infoCache[id] = cache;
    }
    
not sure if related...     
This new FacesRenderCache()  is different than the other one... 
The other one sets a value for nextBlinkTime, this one leaves that not set...

**Comment by dartunder** [comment]
Will be fixed by https://github.com/smeighan/xLights/pull/4153

**Comment by kylegrymonprez** [comment]
Thanks @dartunder - good catch
