### ISSUE TITLE
Music Not Aligned with Output

### ISSUE THREAD

**Issue by jtf107** [smeighan/xLights#416]
When playing from the middle of the song in the sequencer and layout tab the waveform, output, and play head match up, but the music does not. 

Playing from the beginning after hitting stop behaves normal.

If I want to preview a section I'm working on I have to play the entire song up the that point.

**Comment by stevegiron** [comment]
This is a VERY common issue that people bring up. Use Audacity to export the MP3 file with CONSTANT BIT RATE (CBR) and you'll be set.  128/192K does not matter.
