### ISSUE TITLE
App for schedule 

### ISSUE THREAD

**Issue by DannyA34** [smeighan/xLights#4162]
Hello, not sure if it's here to ask. Have you ever thought about making an app so those who is watching our ligheshows can use an app to pick numbers / vote for a number?

**Comment by keithsw1111** [comment]
So Remote Falcon does not do what you want?

**Comment by DannyA34** [comment]
Wow, didn't know it was there, my bad 😳 but thanks for your work here 👌👍

man. 27. nov. 2023 09.54 skrev Keith Westley ***@***.***>:
