### ISSUE TITLE
? Does xlights support Export to SD for Hinkspix 80?

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#4165]
User came in with 2 hinks .. old and new. He exports the sequence to the sd card - it works on his original hinks but is somewhat scattered on his Hinks80. Has Scott had a chance to view/code/verify the code for the newer Hinks?

**Comment by computergeek1507** [comment]
Looking at the code, I don't see anything that would be different between the Pro and Pro80.

**Comment by derwin12** [comment]
The guy was saying the lights would play fine on the Hinks (as the remote) but the 80 the lights were scrambled. I dont know if it was the master/remote stuff or just the 80. I realized this cant really be triaged without the hw .. so I will close the ticket but wanted to ask..

**Comment by computergeek1507** [comment]
I have the hardware, I need a package sequence with his files to test with.

**Comment by derwin12** [comment]
Okay .. if he comes back I will ask. It was essentially 2 mega trees - 1 on each controller. Basic sequence / twinkle.
He render, saved and use the Hinkspix Export to SD and tried playing it on the HP 80 as a master. I didnt even know xlights (you) supported the master remote for HP hardware.

**Comment by computergeek1507** [comment]
Was it on a spi boards or Smart Receivers and was "Universe Per String" enabled ?

**Comment by derwin12** [comment]
Matt - was back.. 
How do you create and SD card - 1 for each controller? JoeH says they should each get their own.

**Comment by derwin12** [comment]
He was back tonight .. we realized that the export does 2 separate sd card exports. He put them on different cards and it worked fine. He was a bit confused about making a more complicated schedule. I told him that the files were templates that he could use to create a more complicated playlist. Ie song 1,2 on M-W-F, 3,4 on T-R-S-S. He seemed fine with that.
