### ISSUE TITLE
Bulk Edit option missing for Lead In/Out frames and Fade

### ISSUE THREAD

**Issue by kevinsaucier** [smeighan/xLights#4172]
The Faces effect doesn't seem to support bulk editing the Lead In/Lead out Frames or the Fade During lead in/out checkbox (unless I'm just an idiot).  Not sure if this is by design because it can't be done or just an oversight, but it sure would be nice to have.  😁

**Comment by computergeek1507** [comment]
fixed 2f6bcfd70d8bb65f9fce4f262172f13af1bffe9d
