### ISSUE TITLE
Show effect description in tool tip as you hover over an effect

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#4179]
There is the ability to add a description to an effect with a right click. Can you show this when one hovers over the effect?
![image](https://github.com/smeighan/xLights/assets/4643499/6ba3b53e-ef81-437c-ac0c-8a95a2680bb6)

**Comment by keithsw1111** [comment]
It already appears at the bottom of the screen along with start stop and duration.

**Comment by derwin12** [comment]
missed that .. k.
