### ISSUE TITLE
Wrong count of total pixels per port with setup-ing the controller and props

### ISSUE THREAD

**Issue by kenaddams42** [smeighan/xLights#4193]
**Describe the bug**
The bug is not linked to a sequence but to the setup of the controller and the props.

I've got a megatree (2 strands of 500 pixels) + a top star (60 pixels) + two candy canes (50 pixels each). My controler is a Dig Quad Uno.

Each strand of the megatree is on a specific port (recomendation of 500 to 600 pixels per ESP32 port max).

- Megatree strand 1 is on Dig Quad port 1. Strand 2 on Dig Quad port 2. 
- Top star is on Port 1. Candy canes on Port 2.

On Port 1, with megatree strand 1 then the star, Xlights shows a total of 1060 pixels on port 1 instead of 560. And 660 pixels on port 2 instead of 600.

With the star then the megatree strand 1 on port 1, it shows the correct value on both ports 1 and 2.

**Expected behavior**
I expect the right total of pixels to be shown in Xlights - 560 on Port 1, whether the megatree strand 1 or the star is in first position.

**Screenshots**
With megatree strand 1 then the star:
![image](https://github.com/smeighan/xLights/assets/7167034/dc455b5d-5915-4152-864c-cdc7053c009e)

With the star then megatree strand 1:
![image](https://github.com/smeighan/xLights/assets/7167034/b77395e6-10b2-43d0-9f3b-1ded251cd173)

**Versions (please complete the following information):**
Windows 10 
xLights 2023.18 64 bits

Attachment: backup of the setup.
[2023-12-05-105238.zip](https://github.com/smeighan/xLights/files/13558243/2023-12-05-105238.zip)

**Comment by keithsw1111** [comment]
This is normal. You will get a warning but as long as your controller supports virtual strings it will work. If it doesnt then you cant use visualiser with this configuration but can manually configure your props and controllers to your liking.

Visualiser is not meant to handle every possible configuration and this one falls outside the bounds of what is supported.

**Comment by AzGilrock** [comment]
Bottom line is don't try to wire props in the middle of other props if you want automatic xLights configuration.

**Comment by kenaddams42** [comment]
That makes sense indeed. Even if it's not wired in the middle, virtually it
is.
Thanks for your help !
