### ISSUE TITLE
Enhancement Request: Effect Assist Window

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#420]
Is it possible, with the window set to be always off, to have a double click on a morph or picture effect trigger the assist window to appear versus using the view windows menu options?

**Comment by AzGilrock** [comment]
Double-click already has another purpose in that window.

**Comment by kppankratz** [comment]
I'm assuming the model names and sequencer grid are all considered part of the same window then?  If so, is there some other solution that would allow quick access to the assist window instead of having it toggle open every time you simply click on the effect?

**Comment by stevegiron** [comment]
You could make it part of one of your perspectives then it's just one click
away.

**Comment by AzGilrock** [comment]
I'm just not feeling the idea.  You have 3 options right now.  It's always on, always off, or it toggles on when you select an effect that applies to it.  Maybe someone else will be interested in adding this but probably not me.
