### ISSUE TITLE
Execute FPPConnect in command line

### ISSUE THREAD

**Issue by thekameleon** [smeighan/xLights#4204]
**Is your feature request related to a problem? Please describe.**
I'd like to compile and automate pushes of sequences to my controllers form a separate computer than my main computer. Id like to use events from github to kick those processes off.

**Describe the solution you'd like**
Utilize FPPConnect via command line. Specify controllers, which compiled sequences by maybe say date range or all in a specific folder. In all honesty just the FPP Connect upload utilizing the last settings of FPPConnect would be great as FPPConnect handles "changed" sequences vs. not changed.

**Describe alternatives you've considered**
Using the UI, but the goal here is continuous build automation.

**Additional context**
switch could be /fsu for fseq upload

**Comment by computergeek1507** [comment]
Using xldo or the http/script API this is already possible

**Comment by thekameleon** [comment]
I need to use XFade and be logged in to the desktop correct?
