### ISSUE TITLE
Layout tab - Groups

### ISSUE THREAD

**Issue by Kenneumann** [smeighan/xLights#4207]
Current version .22

On layout tab. When editing groups, the last prop name down the list is hidden and cannot be selected. Example group (bulbs) I have red, blue, green and orange. If I select the group it will only show the first 3 prop names in the add/remove box, but all 4 will highlight in yellow. 

If you need more details or possible screenshots. Let me know. I'm sure when people start editing groups they will come across the issue.

**Comment by dartunder** [comment]
If you are using dark mode, disable it and try again.

**Comment by derwin12** [comment]
https://github.com/smeighan/xLights/issues/4188

**Comment by keithsw1111** [comment]
Duplicate
