### ISSUE TITLE
Temporary files are not always deleted and their location is dependent wxWidgets temp file location.

### ISSUE THREAD

**Issue by dartunder** [smeighan/xLights#4213]
Temporary files are not always deleted; their location depends on wxWidgets temp file location.

A user was running out of space due to incorrectly selecting V1.  These temp files built up and filled his drive.

For example, FPP Connects a batch of sequences, including updating outputs. Some temp files were not deleted.

It looked like it was also creating temp files for the tip of the day, which were not deleted.

Files from Xlights are staying in this folder.   Should we have our temp folder and clear it on startup?
C:\Users\{username}\AppData\Local\Temp

**Comment by dkulp** [comment]
The tip of the day stuff should have been managed and cleaned up with the cached file downloader.  It wasn't.  That's now fixed.

**Comment by keithsw1111** [comment]
I think this is now fixed unless there is something more specific
