### ISSUE TITLE
Notification when Rendering is Complete

### ISSUE THREAD

**Issue by AJR214** [smeighan/xLights#4216]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. 

**Describe the solution you'd like**

A selectable on/off option in setting for a ding/bell/alert when a render is finished. This would be only when you press the render button, not for background rendering.

I have many sequences take 3, 5, even 10 minutes to render. During that time I work on other screens or do other things rather than watch paint dry. Golf is more interesting to watch than the render bars over and over! 

**Describe alternatives you've considered**

-render the first time to get approximate time to render, then next time I press render I set an alarm on my phone. 
- Watch the screen and all the pretty bars go from left to right while twiddling my thumbs for 6 minutes. 
- go do something else and forget about the rendering and realize 15 min later the render was done 8 minutes ago. 

**Additional context**

I put this in the Official xLights Group and there was additional interest in adding the feature as others have long render times as well.

**Comment by computergeek1507** [comment]
It shows the render progress in the system tray

**Comment by AJR214** [comment]
> It shows the render progress in the system tray
Yes, but this is not an AUDIBLE notification. If i walk away, i want to know when it’s done!

**Comment by AzGilrock** [comment]
Nope we usually just buy a Mac and wait 30 seconds

**Comment by AJR214** [comment]
> Nope we usually just buy a Mac and wait 30 seconds

Awesome! So $20k into this hobby and have to spend another $2k on an M1/M2 Mac just for sequencing - which as any PC guy will say - NO THANKS!

And either way, I'd still like the option of a "ding" when the sequence is rendered. I still wouldn't sit there for 30 seconds and watch the bars render each prop! Can the request just move forward to the dev team to decide if it's a worthy enhancement or not? Others seem to think it is.

**Comment by AzGilrock** [comment]
Yeah I am part of the dev team since 2015 and also have always been a PC guy but for xLights the MAC really is that much nicer that I used xLights donation money to buy one.

Your request is in....it may sit there for years like 100's of other requests.  I'll be working on moving head features cause this doesn't seem important.

**Comment by cybercop23** [comment]
> And either way, I'd still like the option of a "ding" when the sequence is rendered. I still wouldn't sit there for 30 seconds and watch the bars render each prop! Can the request just move forward to the dev team to decide if it's a worthy enhancement or not? Others seem to think it is.

There's always the option for you to develop it and create a PR to be incorporated.

**Comment by derwin12** [comment]
AJR -- no fear .. there are many new folks, who have committed changes this year that could/would like to take on such a challenge.
