### ISSUE TITLE
Batch Render Enhancement

### ISSUE THREAD

**Issue by jlwright325** [smeighan/xLights#4218]
When batch rendering, if you have made any changes in your layout and you are unaware that it will impact an older sequence, there is no way to cancel the batch render.

When prompted with the information that groups, props, etc. are missing. Allow the capability to cancel the batch render.

**Comment by dartunder** [comment]
It is not what you are asking for but holding escape will abort a batch render when the song is complete.

**Comment by jnealand** [comment]
I second this request twice this christmas season I initiated a batch render but both times realized after the first sequence stopped I had an erro in my config that would stop each sequence request a decision.  the first time I had 8 sequences, the second time I had 13 sequences to do.  In both cases I had to use task manager to kill xlights.

**Comment by keithsw1111** [comment]
Pres and hold ESC.
