### ISSUE TITLE
Enhancement Request: add a description field for each network defined in the Setup tab.

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#422]
I would like to be able to add notes to each universe that is defined in the setup tab. Some controllers can be multipurpose, maybe the first 8 outputs are for Twig trees and the other 8 may be user for different yard elements. (arches, stars, firesticks). I would like a description field next to each line so I can say what that universe/output is being used for.

**Comment by stevegiron** [comment]
You can do that natively with Windows. http://windows.microsoft.com/en-us/windows/create-keyboard-shortcuts-open-programs#1TC=windows-7

**Comment by PhilHilton** [comment]
Steve are you talking about the same thing?

I was about to ask for this so I'm glad Pat did. I'd much rather just look at my setup list and see "Mega tree Star/LOR DMX" rather than remember I have an e6804 is at 192.168.0.248 or that the star is on universe 50.

**Comment by patdelaney** [comment]
I added 2 requests, I think he was referring to the other request.

Pat

**Comment by keithsw1111** [comment]
This will be in 2016.8 c9142ff5ae1e5db912d87c6b635f48fa4d4ee673

**Comment by patdelaney** [comment]
Thanks
