### ISSUE TITLE
3d model export starts on the wrong index

### ISSUE THREAD

**Issue by JLOrwell** [smeighan/xLights#4220]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When I clicked on my mega tree to export the tree model as a 3d custom model, it looked correct but all of the bulb indexes were internally off one, starting at 0 and ending at 1499.  
**To Reproduce**
create a mega tree model then export it as a custom model.  Now inspect the model data in a text editor.
**Expected behavior**
The model data should start and index 1 and end with an index equal to the bulb count.

**Screenshots**
Here's a photo of index 1.
![image](https://github.com/smeighan/xLights/assets/12838841/13da9068-1589-45d1-bdb7-8debf061566a)

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - Windows 11
 - xLights version [e.g. 2019.37]
2023.20
**Additional context**

**Attachments**
Attached is the incorrectly generated model from a 180 degree tree that starts in the bottom left corner, has 1500 nodes, and is set up as a single string of 1500 nodes with 15 strands.
[Ladder Tree 3.zip](https://github.com/smeighan/xLights/files/13681160/Ladder.Tree.3.zip)

**Comment by AzGilrock** [comment]
Probably is wrong but then again computers do use 0 as the starting index.  We could easily have made it so the export and import match up and work with 0 instead of 1 as the start.  If you import it back is it wrong?

**Comment by JLOrwell** [comment]
yes it is wrong.  Looks correct on a re-import but it is starting at zero.
 This is offsetting the channels by one.
Note:  I noticed this error when I was importing the exported model into a
drag-drop custom model editor built into artnet 2 twinkly.  I'm going to
have to put in special code to increase all the indexes by one.
Note:  When I said "looks correct" that's not actually true.  the importer
skews large models on import in the preview and you have to go in the
custom model data and hit save to fix it, but that's a different error.

**Comment by AzGilrock** [comment]
By "skews" do you mean the scale of the model?  The import feature has you draw a boundary and then it imports inside that boundary.  But I do seem to remember another dev changing the behavior so I'm not sure exactly how its working currently.  I have a new model type that works well for Twinkly but its not ready to release.

**Comment by derwin12** [comment]
Something weird going on here .. a looked at a couple .xmodels and they start at 1. Can you do a package logs so that your showfolder layout is included?

**Comment by AzGilrock** [comment]
> Something weird going on here .. a looked at a couple .xmodels and they start at 1. Can you do a package logs so that your showfolder layout is included?

Based on Scott's commit it was just 2 specific model types with the issue.

**Comment by computergeek1507** [comment]
It was only if you export as a 3D custom model not regular old 2d custom models most people use

**Comment by JLOrwell** [comment]
by skews I mean it literally shifts over the pixels in the upper half of the model to the right in the initial display of it.  Going into the custom model and simply saving corrects it.  I care quite a bit less about that problem but it's been there at least a year.

**Comment by JLOrwell** [comment]
i know the 2d model export works.  I use Twinkly devices and I have a
program that allows me to fix their layouts and re-upload them as xmodels.
That's how I discovered this bug.  My validation caught it.  I would also
suspect most people use the 2d export because they don't know about the 3d
one since it's relatively new.

**Comment by AzGilrock** [comment]
Scott fixed it…no input need3d
