### ISSUE TITLE
Megatree output

### ISSUE THREAD

**Issue by gabi68** [smeighan/xLights#4234]
I have a megatree which use 3 connection to a quin ae+. 
The setup has 10 strands divided in 
2 (72leds each)  
4 (72 leds each)
4 (72 leds each)
How do I do this on xlights?

TIA
Gabi

**Comment by computergeek1507** [comment]
You have to use a custom model for unbalanced string counts

**Comment by gabi68** [comment]
What is the best way to do that? Any tutorials? Thank you.

**Comment by computergeek1507** [comment]
"Best way" is to not have uneven strings. 2 connections of 5 stands or have 12 stands with 4 per port. It better to model it in xLights first to verify your configuration then build/wire the prop in your yard.

**Comment by gabi68** [comment]
I agree with you about number of strands. I manage to make it work with a help from "shadow model" in xlights,

Thank you
