### ISSUE TITLE
FPP Connect - Add ability to Select All and Deselect All

### ISSUE THREAD

**Issue by chrkov** [smeighan/xLights#4236]
**Is your feature request related to a problem? Please describe.**
Not Really a problem - More of an inconvenience.   Using FPP connect, If I upload all my sequences and then later go to update a single sequence, I have to manually go and unselect every sequence that was selected before.

**Describe the solution you'd like**
Have a button (or a everything checkbox) to be able to select every file or unselect every file.

**Describe alternatives you've considered**
No real options

**Additional context**
None.

**Comment by derwin12** [comment]
Right Click -- it is there.

**Comment by chrkov** [comment]
Wow.   Three years and I had no clue.   I don't believe this is documented anywhere or I missed it.

Might want to just put a note or something on the page saying something like (Right click for Bulk Selections) or something to make it more obvious.


Thanks!

**Comment by computergeek1507** [comment]
In the manual in the FPP Connect  Section 

![image](https://github.com/smeighan/xLights/assets/2293065/cacf2d5b-f3c4-4ce2-8eeb-98b114e12aaf)
