### ISSUE TITLE
Persistance not resetting between effects

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#4237]
Jack from Zoom..
Persistent effect doesn't reset after the effect is done. Is this the norm?

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. On the ring submodels are a number of single strand effects. If you click on each one you see it "circles" around the prop just fine.
2. If you render it and play it just does the one circle effect and the persistent remains on, so it doesn't show the circling motion, back n forth.

**Expected behavior**
The effect should show a back n forth wiping of the wreath model.

**Screenshots**
![image](https://github.com/smeighan/xLights/assets/4643499/051e2aac-d384-47a0-ab56-936315e76f02)

**Versions (please complete the following information):**
verified in .17, .22 and .23 PC
[Dreams Of Fireflies (On A Christmas Night).zip](https://github.com/smeighan/xLights/files/13760194/Dreams.Of.Fireflies.On.A.Christmas.Night.zip)

**Comment by AzGilrock** [comment]
I remember this being talked about in #518

**Comment by derwin12** [comment]
Got it .. understood where Keith is coming from.  The workaround seems feasible - move them to different layers.
