### ISSUE TITLE
Bug: effects duplicating by pressing up/down arrow keys

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#424]
The effect has to span across timing marks (timing track active).  Click into a cell that the effect is on (not the center of the effect) and press the up or down arrow to move between layers of the model and the effect get duplicated.

**Comment by kppankratz** [comment]
From what I can gather with messing around with this find, it only happens when the effect is at least 3 cells wide.  Selecting either end cell or the exact middle of the effect won't duplicate upon pressing the up/down arrow.

**Comment by stevegiron** [comment]
Can't reproduce this with 4.2.23.  What version are you running.

**Comment by kppankratz** [comment]
I'm running 4.2.24 (latest version).  I've attached pictures showing what is happening.  First picture I simply select a cell that the effect is passing through.  Second picture shows what happens when you press the arrow down or up, depending on where the second layer is.

![duplicate effect bug 1](https://cloud.githubusercontent.com/assets/12144876/11487637/3f1b9b32-9786-11e5-95e0-29febe2b7931.png)
![duplicate effect bug 2](https://cloud.githubusercontent.com/assets/12144876/11487638/3f6702d4-9786-11e5-9819-af18dd77f5b1.png)

**Comment by AzGilrock** [comment]
People have been saying xLights is too confusing so this is all part of the new mind-reading logic.  We read your mind and automagically figure out what you want sequenced.  Obviously you must have been thinking you wanted a copy of that effect there.
