### ISSUE TITLE
Error opening .xseq files

### ISSUE THREAD

**Issue by technoj** [smeighan/xLights#425]
Hello
I am still new to xlights so I apologize if this isn't supposed to work.  I am trying to open a .xseq file on my Mac, but when I try to open it, it just grays it out.  I also tried dubble clicking it, and nothing happened.  I'm running version 4.2.24.

![screen shot 2015-12-05 at 9 25 19 pm](https://cloud.githubusercontent.com/assets/6800123/11611502/bec93a2e-9b96-11e5-8f60-e45f2a790b7c.png)

**Comment by stevegiron** [comment]
xseq, fseq files are binary files that are output to the lights. You should
open the XML file for editing purposes.

**Comment by technoj** [comment]
Is there any way to convert a .xseq to an .xml?

**Comment by stevegiron** [comment]
No. That's like trying to convert a cake back to sugar, flour eggs.

**Comment by technoj** [comment]
I thought so.  Thanks!  You can close me.
