### ISSUE TITLE
Enhancement: Reverse Color Pallette Button

### ISSUE THREAD

**Issue by PhilHilton** [smeighan/xLights#427]
Button to quickly reverse the order of colors in the color pallette. If I fade from red to blue, it's easy. The default color palette has them in the right order for a color wash to do it. If I want to fade back later I end up needing to choose a custom color and use another slot and get them in the right order.  Much quicker to just reverse the pallette.

**Comment by AzGilrock** [comment]
I vote No for this suggestion.  We will implement the saved palette functionality again and that should be sufficient.  This is too much of a special case and it's just trying to save a couple keystrokes.

**Comment by stevegiron** [comment]
I vote no because I think that's something another sequencer does.

**Comment by keithsw1111** [comment]
Implemented.
