### ISSUE TITLE
Enhancement: Setup Tab, Intuitive UI Improvements

### ISSUE THREAD

**Issue by PhilHilton** [smeighan/xLights#429]
Instinctual behavior of double clicking on a UI element is to work with or open it, not to toggle its active state. If you expect this and double click on a row, you may not notice the Yes/No label change in the Enabled column. I propose on the setup tab:

1. Replace Enabled column contents with checkboxes rather than the current Yes/No values.
2. Double clicking on a row (outside of a checkbox) to open the Change dialogue.
3. Possibly lighten the text of rows which are disabled to be even more obvious than the checkbox. Or some color visual indication (thin red line on left side? light red background?)
4. Add sorting by column so I can find all the universes at a given unicast IP address, or a given universe regardless of when it was added.
5. Add a general order column, far left, to easily restore natural channel ordering after other sorting.
6. "Change" button name to be normalized with other buttons across the application. xLights is inconsistent regarding "Change" and "Modify" 
7. For unicast networks, right click context menu for a network in the list to have option for "Open in Browser" which will hand off the IP with http:// prefix to the system default browser. 
See also, #422. I would have included that in this issue if it hadn't already been submitted.

**Comment by AzGilrock** [comment]
It was instinctual to me to not double-click on those items...lol.  I didn't even know we had that capability to disable them for most of this year until I read someone talking about it.  I think you are placing too much importance on the setup page.  Most people just setup their outputs in 5 minutes and never look at the page again.  I don't plan on wasting a lot of development time on making this pretty for a program we don't even sell.
