### ISSUE TITLE
Add ability to add new display elements to a new sequence

### ISSUE THREAD

**Issue by smeighan** [smeighan/xLights#43]
Currently if you do
1) New Sequence, create a musical sequence.
2) Go to Sequencer tab. 

There is no way to open the "Add Display Elements" window if you just created a sequence.
The display element window is available when you right click an existing model. 
The Display Element window will allow adding/deleting models from a sequence

**Comment by dkulp** [comment]
Note that you CAN do this via the View->Windows->Sequence Elements option.   Need to add that to the popups.
