### ISSUE TITLE
Enhancement: Auto-save

### ISSUE THREAD

**Issue by PhilHilton** [smeighan/xLights#430]
either or both of 2 options:

1) Option to automatically save your current sequence (without render, obviously) every x minutes. This would be the less preferred option as you would have to remember to turn it off if you were just experimenting lest you overwrite your important sequence data with doodles.

2) Option to automagically save your current sequence to /path/to/show/directory/autobackup/sequence.xml or /path/to/sequence/dir/sequence-name_autosave.xml every x minutes (5?). In the event of a crash you'll have something to help reduce the risk of punching a hole in the wall because you were too focused on sequencing to remember to click save...  I mean, I have a friend with that problem.. yeah... a friend.....

**Comment by stevegiron** [comment]
This is already on the to-do-list.

**Comment by PhilHilton** [comment]
Is this list published that I might avoid duplicate requests?

**Comment by AzGilrock** [comment]
Yep right here on GitHub.  This is the list...

**Comment by PhilHilton** [comment]
Searching for save and autosave before I submitted the issue did not turn up any requests for an autosave feature. Got an issue # for me?

**Comment by AzGilrock** [comment]
I don't know I was just answering the question about the list.  The problem is the issue list has gotten so big nothing gets fixed because no one has time to sort through which ones we want to do or not.

**Comment by PhilHilton** [comment]
I hear ya. I'd help if I had the time.
