### ISSUE TITLE
2016 Enhancement  Render to media file

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#431]
Render to media file like avi, mov, mp4.

This would save a step in screen recording the house preview or layout screens.

**Comment by cp16net** [comment]
+1

**Comment by AzGilrock** [comment]
There is a big difference between the data we render and what OpenGL is displaying on the monitor.  This would be basically writing our own screen capture tool.

**Comment by dkulp** [comment]
Well, if we flip the MP3 reading from using libmpg123 to libavcodec, this COULD be a possibility as we'd have the codecs in place.   This is something I'd like to do sometime next year as libavcodec hopefully would fix our issues with VBR mp3s, but could also make the pictures effect work with things like mp4's natively without having to deal with ffmpeg.

**Comment by AzGilrock** [comment]
I believe Keith already implemented this now.

**Comment by AzGilrock** [comment]
I just tested and Export Model to an uncompressed AVI works.  It's doesn't look as pretty as the OpenGL rendering so not sure how much it will be used but I think it satisfies this request.

**Comment by keithsw1111** [comment]
It is not meant to generate videos for watching ... it is generating videos for playback on models in other sequencers. This means they are extremely low resolution and when played in video players which try to scale up they look truly awful ... but if you were to drop the same video on an effect with the same resolution they would look pixel perfect.
