### ISSUE TITLE
arrow keys on sequence timings not working as expected

### ISSUE THREAD

**Issue by cp16net** [smeighan/xLights#432]
When using shortcuts like 'u' for fade up and 'd' for fade down i'd expect to be able to move on the timing grid in the sequencing and be able to just arrow to the block i want to do a fade up in and press 'u' and then arrow right for the next block and press 'd' for fade down. This doesn't work because you are required to click the box then press the shortcut key.

This would be a nice enhancement.

**Comment by AzGilrock** [comment]
If the grid has focus the shortcut should work.  I wonder where the focus is going when you hit the arrow keys because the grid must be losing focus when that happens for it to not work.

**Comment by cp16net** [comment]
@AzGilrock Does not look like the grid looses focus because the selection block moves, but pressing the 'u' for a fade up or shortcut keybinding does not appear to do anything. I've been running on my mac with the latest version 4.2.25.

Upon further investigation of this issue i found that using the arrow keys moves the selection block but not the "focus". I can tell by clicking a timing block to select one and pressing 'u' then 'delete' that mark. Then using the arrow keys to move a few blocks down and then pressing 'd' and it will update the original block. Not the one that is currently selected.

While seeing this i just saw something else that is probably related to this bug. Once clicking a block using the arrow keys to move around on the grid, for example move right 2 blocks and then move down 2 blocks and then pressing 'd' and the block that will be updated is the block on the same column as the block you initially selected but on the same row where the selection block is.

Looks like the row is changing the focus but the column is not when using the arrow keys.

Let me know if you need more info.
/me sorta wishes this project was not all c++ otherwise i might be able to help more. :coffee:

**Comment by AzGilrock** [comment]
Now that sounds like a bug that's been reported but I would have bet and lost money that we had already fixed it.

**Comment by cp16net** [comment]
Sounds like something that others would have caught i'm sure. I'm reading up on wxWidgets and maybe i can help out a little eventually... :)
