### ISSUE TITLE
fseq renders wrong when shortening the sequence to fseq file

### ISSUE THREAD

**Issue by cp16net** [smeighan/xLights#433]
I created a 30 second long sequence without music and then decided to shorten it to 10 seconds. When i save, the fseq file is generated but it still plays for 30 seconds. The sequence looks like 10 seconds in xlights and plays as 10 seconds.

I found the work around for this:
1. close xlights
2. delete the fseq file
3. open xlights
4. open the sequence
5. save the file

This generated the shorten file to play in the fpp. The bug must be that xlights reads both the xml and fseq file if it exists and persists some of the settings instead of regenerating all of the fseq file.

**Comment by AzGilrock** [comment]
Yep I identified this in Issue #196.

**Comment by AzGilrock** [comment]
Fixed by same checkin that fixed #196.
