### ISSUE TITLE
Render icon on Mac is not consistent with Windows version.

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#436]

**Comment by AzGilrock** [comment]
I believe that was on purpose because Dan didn't it since it didn't fit the typical Mac look.

**Comment by dkulp** [comment]
That and a "Gear" on OSX is generally reserved (per guidelines) for settings and preferences.  Being Red/Green color blind, I also find it problematic due to the color choice.

**Comment by stevegiron** [comment]
I don't mind what the icon is, I would just prefer it to be the same across
platforms. I was helping someone over the phone telling them to press the
green gear icon, and they could not find it. Later, I found out the icon
was not a gear.
