### ISSUE TITLE
Module Groups Render In Correctly?  i.e Module View <> House View

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#440]
![minitreegroup](https://cloud.githubusercontent.com/assets/9368124/11931071/5810585e-a83d-11e5-92f7-757520f792b0.png)
Hi Guys,
 Selecting Horizontal or Vertical layout for a group, does not give the expected results.

I assume it would internal build a matrix with all the other matrix join together.  It seems to be treating each object as one long string .  I assume it would determine the largest X and Y values of all the objects e.g.   5hx10w, 6hx8w, 3hx9w and when joined horizontally create 6hx20w matrix to fit them in to allow the effects.  or if it was vertical create 14hx10w matrix to fit them in.

How else could you get a bar effect to flow across.  Currently it moves one node at a time instead of a column at a time, because its converted into one long string of nodes.

Cheers

The rest of the features are fantastic.

**Comment by stevegiron** [comment]
Ensure that the the model group layout mode selected is "Minimal Grid", otherwise the grid size will be the size of your entire display.

**Comment by AzGilrock** [comment]
The way you're asking it to work is how it works.  If you can post your models on the forums someone can look into it.  It snapshots them how they appear on the Layout screen and creates a matrix.

**Comment by damon-atkins** [comment]
[Example.pdf](https://github.com/smeighan/xLights/files/69810/Example.pdf)
Here are some examples

**Comment by AzGilrock** [comment]
I think horizontal and vertical are supposed to be one long string of nodes as you are seeing.  It orders the nodes going in a horizontal or vertical direction.  If you want them to be rendered as an area then you use the other options.  There is no option that is going to group a bunch of individual nodes into a column.

**Comment by AzGilrock** [comment]
I believe the new buffer types feature Dan has added will satisfy what was asked for in this request.  The code is checked in and will be part of release 2016.9.

**Comment by damon-atkins** [comment]
@dkulp for fixing the Horizontal or Vertical layout for a group
