### ISSUE TITLE
xLights Crashes while trying to make a Window Frame object?

### ISSUE THREAD

**Issue by m00dawg** [smeighan/xLights#441]
Having a bit of trouble with xLights crashing while trying to make a Window Frame. I only have one other object currently in place (a 180 PixelTree). I configured a Window Frame in a 10/20/10 configuration. When I hit Ok to close the Model view I get the crash dialog.

I'm on Linux Mint 17.2 and installed xLights using the "make ; make install" method.

I had previous issues with adding in a Pixel Tree on a previous test setup but haven't quite figured out what is causing it to say much more. The error I get at console is just:

(xLights:10078): Gtk-CRITICAL **: IA__gtk_window_resize: assertion 'width > 0' failed

[xLights_dbgrpt-10043-20151222T133824.zip](https://github.com/smeighan/xLights/files/70114/xLights_dbgrpt-10043-20151222T133824.zip)

**Comment by dkulp** [comment]
Can you try again after doing a "make debug install" instead?   Hopefully that will get the debug symbols in there so we can see the stack traces through the xLights code.

**Comment by m00dawg** [comment]
Doh, sorry should've looked if it had a debug build option. Here is the error (this time adding a Pixel Tree) from the debug box that popped up:

########################################################################

ASSERT INFO:
/usr/include/wx-3.0/wx/strvararg.h(451): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type

BACKTRACE:
[1] wxArgNormalizer<unsigned long>::wxArgNormalizer(unsigned long, wxFormatString const*, unsigned int) /usr/include/wx-3.0/wx/strvararg.h:451
[2] wxArgNormalizerWchar<unsigned long>::wxArgNormalizerWchar(unsigned long, wxFormatString const*, unsigned int) /usr/include/wx-3.0/wx/strvararg.h:471
[3] wxString wxString::Format<unsigned long>(wxFormatString const&, unsigned long) /usr/include/wx-3.0/wx/string.h:2322
[4] handleCrash(void*) /nfs/home/tim/git/xLights/xLights/xLightsApp.cpp:150
[5] xLightsApp::OnFatalException() /nfs/home/tim/git/xLights/xLights/xLightsApp.cpp:276
[6] wxXmlNode::GetParent() const /usr/include/wx-3.0/wx/xml/xml.h:150
[7] xLightsFrame::ShowModelsDialog() /nfs/home/tim/git/xLights/xLights/TabSequence.cpp:285
[8] xLightsFrame::OnButtonModelsPreviewClick(wxCommandEvent&) /nfs/home/tim/git/xLights/xLights/TabPreview.cpp:790
[9] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
[10] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[11] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
[12] wxEvtHandler::TryHereOnly(wxEvent&)
[13] wxEvtHandler::DoTryChain(wxEvent&)
[14] wxEvtHandler::ProcessEvent(wxEvent&)
[15] wxWindowBase::TryAfter(wxEvent&)
[16] wxWindowBase::TryAfter(wxEvent&)
[17] wxWindowBase::TryAfter(wxEvent&)
[18] wxWindowBase::TryAfter(wxEvent&)
[19] wxWindowBase::TryAfter(wxEvent&)
[20] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[21] g_signal_emit_valist
[22] g_signal_emit
[23] g_signal_emit_valist
[24] g_signal_emit
[25] g_closure_invoke
[26] g_signal_emit_valist
[27] g_signal_emit
[28] gtk_propagate_event
[29] gtk_main_do_event
[30] g_main_context_dispatch
[31] g_main_loop_run
[32] gtk_main
[33] wxGUIEventLoop::DoRun()
[34] wxEventLoopBase::Run()
[35] wxAppConsoleBase::MainLoop()
[36] wxEntry(int&, wchar_t**)
[37] main /nfs/home/tim/git/xLights/xLights/xLightsApp.cpp:116
[38] __libc_start_main
[39] _start

########################################################################

Attached is the latest crash report and also here's some more info about my particular Linux install:

########################################################################

tim@lindawg ~/git/xLights $ dpkg --get-selections *wx*
libwxbase2.8-0:amd64				install
libwxbase3.0-0:amd64				install
libwxbase3.0-dev				install
libwxgtk-media3.0-0:amd64			install
libwxgtk-media3.0-dev				install
libwxgtk2.8-0:amd64				install
libwxgtk3.0-0:amd64				install
libwxgtk3.0-dev					install
wx-common					install
wx3.0-headers					install
tim@lindawg ~/git/xLights $ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 17.2 Rafaela
Release:	17.2
Codename:	rafaela
tim@lindawg ~/git/xLights $ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 

########################################################################

My suspicion is the version of wxWidgets that comes with Linux Mint might not be the latest so I may try a custom compile or try updating Linux Mint (I'm now a version behind the latest which just came out a few weeks ago).

[xLights_dbgrpt-21200-20151222T153808.zip](https://github.com/smeighan/xLights/files/70243/xLights_dbgrpt-21200-20151222T153808.zip)

**Comment by dkulp** [comment]
Can you do a pull and rebuild and try?  Added a null pointer check at that area of the code which should prevent the crash, but I don't really know why it's ending up as null at that point which is certainly bothering me.

**Comment by m00dawg** [comment]
Used latest pull (760407f9910f4ff3f706715f88618277b0174634) and still had a crash but a slightly different behavior this time.

I went to go add a new Pixel Tree and when I clicked Ok on the model box I got the attached error. It still created the tree as a model though showed a blank box on the layout. When I went into the models list and clicked on it, then it crashed. I did go ahead and upgrade to Linux Mint 17.3 before I re-ran a 'make clean; make ; make debug install' just in case though it didn't appear to upgrade wxWidgets or g++.

[xLights_dbgrpt-14010-20151222T163549.zip](https://github.com/smeighan/xLights/files/70284/xLights_dbgrpt-14010-20151222T163549.zip)
![screenshot from 2015-12-22 16 35 41](https://cloud.githubusercontent.com/assets/226504/11967665/4f91516e-a8ca-11e5-9d16-62b0ec8f9cf2.png)

**Comment by dkulp** [comment]
Can you pull and try again?   It looks like the place we were storing the XML for the new model isn't working correctly on Linux.   I've just used a standard map so hopefully that will help.

**Comment by m00dawg** [comment]
That seems to have resolved things! I did some basic tests of adding and removing multiple items with no issues. I'll put in some more time into it here over the next few days while I build out my actual 2016 show but it looks to be good to go! Thanks for fixing this so crazy fast!

**Comment by dkulp** [comment]
As an FYI:  the we use the same method of storing the XML pointer for a few other dialogs.     They might also need updating.

**Comment by m00dawg** [comment]
I've been keeping an eye out but so far no more crashing as I've been adding lots of models to the layout. I haven't re-tested it yet but xLights gets /real/ mad if you try to load a sequence that has models that do not exist. That previously caused xLights to freeze in a forever pop-up death spiral. I need to retest that but I've otherwise just been trying to avoid that.

**Comment by cjd** [comment]
Is this still occurring?
We have moved to wxWidgets 3.1 on linux now and I haven't seen this failure since then

**Comment by cjd** [comment]
Closing as issue unseen in months
