### ISSUE TITLE
Don't allow commas in model names

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#442]
I notice that groups are a comma separated list of model names. Might be a good idea not to allow , in model names.

**Comment by damon-atkins** [comment]
This should be consider a large bug, as it could need to people closing work.

**Comment by stevegiron** [comment]
Is this still an issue with 2016.20 ? A lot has changed since this issue was logged.

**Comment by damon-atkins** [comment]
Is this still an issue are , used in the xml file still, or are they allowed in the names.

**Comment by AzGilrock** [comment]
Most people are smart enough to not use commas in names so this is low priority.

**Comment by keithsw1111** [comment]
I dont think it is still an issue. I am pretty sure I put in a change recently that prevents commas in model and model group names.

**Comment by AzGilrock** [comment]
Yeah I assigned it to myself the other day to remind myself to investigate.

**Comment by keithsw1111** [comment]
I think I disallowed a bunch of characters but was worried that the way I did it would break some existing layouts ... no one has complained ... but that may be because they have not hit the code yet.
