### ISSUE TITLE
Setup Tab Needs Update Labels Button

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#443]
To have the labels updated with the model names, you need to click on change for each entry and click ok without changing anything and then save.

**Comment by AzGilrock** [comment]
Setup tab only updates when you open the program.  So just save and reopen xlights and they will be updated.

**Comment by damon-atkins** [comment]
It just adds to the confusion that they are not updated, or do not represents the current configuration of the modules.   Thanks for adding it to the enhancement list.

**Comment by AzGilrock** [comment]
LOL he adds everything as an enhancement.  Doesn't mean anything will be done.

**Comment by damon-atkins** [comment]
Can this be closed given, the recent changes in xlights
