### ISSUE TITLE
[Feature Request] Multiple Layouts/Previews?

### ISSUE THREAD

**Issue by m00dawg** [smeighan/xLights#444]
As my own lighting display gets more intricate, having the ability to have multiple previews which show different models would be hugely helpful. For instance, I might want a whole house layout but also want a layout that focuses on a part of my house (such as my front porch). This would allow me to got the overall view of a show while making sure the parts that might be harder to see on a whole house layout can be looked at. Object groups can help to a degree but are still a bit abstract.

Likewise, if my neighbors ever wanted to do lights to music and we all wanted to coordinate, it would be useful to have layouts for each house as well as a wide-angle view of all the houses.

Just a thought! My C++ is real rusty but I had planned on digging through things to see if I can determine how hard this would be to do, but thought I'd toss this out there just the same.

**Comment by stevegiron** [comment]
You can do that with the model groups feature. I have helped a few users that have a same basic house layout and use model groups for Christmas/Halloween separation.

**Comment by m00dawg** [comment]
I played around with that feature, but I couldn't find a way to associate a particular model group with a different image/layout? If I enable a model group then try and change the image, it changes it for all groups. I haven't figured out how to, say, create a model group for my 2nd floor windows using a close up of that section of the house for the image while having an 'all' group using an image that is of the entire house.

**Comment by idleup** [comment]
This is a feature that is very important to me as well for this year. I need multiple preview windows to represent different areas of a show that spans multiple geographical areas.

**Comment by m00dawg** [comment]
Looks like Gil has busted it out in the latest trunk, woohoo! It looks glorious!

I'm on commit 0dcab20020021e618e2a6db1a6a404f2a7ea4924 (master branch) and am having a rendering problem though where the Model Group and Element boxes on the Layout tab do not get redrawn when I selecting a new view. The items do not seem to be clickable either. The old view shows them though. The prevent being able to add models to the new previews.

I might be jumping the gun here on logging a bug since this feature just got introduced into master but just in case this proves helpful, I thought I would add it.

Here's what I'm seeing. This is on Linux Mint 17.2 by the way (using wxWidgets 3.1.0):

http://moocowproductions.org/tmp/xLights/blank-boxes-on-new-view.png
