### ISSUE TITLE
Brightness knob does not work on image in Layout on Linux

### ISSUE THREAD

**Issue by m00dawg** [smeighan/xLights#445]
It looks like the Linux version of xLights uses a different GUI element to adjust the brightness (a knob instead of a slider) which does not appear to work. I tried clicking and dragging, mouse wheeling, double-clicking but nothing seems to change the brightness of the image on the layout.

Only a minor issue since there are easy work-arounds (adjusting the brightness in an image editor like GIMP).
![screenshot from 2015-12-25 20 01 10](https://cloud.githubusercontent.com/assets/226504/12004854/d4cf2746-ab42-11e5-8b64-820b030a6fb3.png)

**Comment by cjd** [comment]
It was using a slider same as other platforms - but as no width was set it defaulted to 0.
I've forced it to 100dp for now
