### ISSUE TITLE
Animated GIF seems to not be 100% in xlights (MAC)

### ISSUE THREAD

**Issue by tmblue** [smeighan/xLights#446]
I've been playing with animated gifs and I've got a few that don't want to play correctly. In my preview this little ewok jumps straight up, then lands in a cloud of dust, but in xlights, it jumps up to the right and lands up there, then once the dust clears, it positions the ewok back at the base of my matrix and again moves it up and to the right.. I may have to post a vid, if you can't take this file toss it in xlights and see the same thing. (we are talking 2-3 positions up, not like it starts at the bottom of the matrix and jumps up to the top.

![output_cvbo0o](https://cloud.githubusercontent.com/assets/16458601/12014238/d430614c-acdc-11e5-875d-5a9c4d915877.gif)

and another one that seems to move up then down, this is Groot, should be him dancing and the planter all the time, in xlights, it jerks from showing the planter to just baby groot dancing

![groot](https://cloud.githubusercontent.com/assets/16458601/12014658/4e910b78-ace5-11e5-86db-9e16d4c4f3f7.gif)

If you preview the file or open it in a browser, you can see the correct behavior.

I have to have the Rate adjustment all the way up to get some movement.

**Comment by tmblue** [comment]
Note. on rate adjustment. If I have the effect on for a short time like 10-15 seconds i get good speed, once I push out the effect to a minute things slow down quite a bit.. (at least in preview, no idea how it looks on the matrix). Not sure why the effect length has such a dramatic affect on the gif movement speed

**Comment by AzGilrock** [comment]
I can answer the speed part.  Its designed so that a 1.0 frame rate will iterate though all the frames exactly once for the duration of the effect.  So increasing duration slows down the frame flipping.  If you need it to go longer than you can get with the frame adjustment then you just need to put multiple copies of the effect back to back.

**Comment by tmblue** [comment]
Awesome thanks, that makes sense, but does seem to mean adding more and
more effects and thus making the sequence larger right? Vs loading it once
and playing through it for the next minute or so?

Tory

**Comment by AzGilrock** [comment]
yep

**Comment by AzGilrock** [comment]
I believe this is fixed now after Keith's GIF handling updates.  I tested the jumping bear GIF above and it looked correct now.
