### ISSUE TITLE
Missing New Timing Options

### ISSUE THREAD

**Issue by robin1373** [smeighan/xLights#447]
I have noticed in v4.3.0 that when you try and add a new timing the only options are 50ms, 100ms or empty. in version 4.2.25 There was a drop down of several options . for example a beat detector. I am going under settings, sequence settings, timings and new. Where these options deleted for some reason?

**Comment by kppankratz** [comment]
It's working on my computer.  Did you install 4.3 on a new computer that does not have Audacity or the Queen Mary VAMP plugins installed?

**Comment by robin1373** [comment]
Yes... Just bought a new laptop and forgot about that. Thank you so much for the help...


Robin Moulton



On Tue, Dec 29, 2015 at 5:32 PM -0800, "Kevin" <notifications@github.com<mailto:notifications@github.com>> wrote:


It's working on my computer. Did you install 4.3 on a new computer that does not have Audacity or the Queen Mary VAMP plugins installed?

-
