### ISSUE TITLE
path includes multiple xlights entries

### ISSUE THREAD

**Issue by majkrebs** [smeighan/xLights#448]
The windows installer appears to be adding the xlights directory to the PATH each time it is installed. I had five instances in my PATH.

Windows XP and Vista.

**Comment by stevegiron** [comment]
I usually have about 10 versions of xLights installed at any one time. Here is the current list and only one path statement on my system.
![image](https://cloud.githubusercontent.com/assets/10568498/12094372/11322a36-b2bd-11e5-8bd9-9a85cf1ec1c3.png)

**Comment by majkrebs** [comment]
If XLights was installed in ten different directories, shouldn't there be 10 directories in your path statement? Did you look in the installer to see if there might be a problem?

This is definitely a low priority issue. Having the same directory in the path only slows down that part of the search that uses the path and should not cause an operational issue. But, if someone was building the installer someday and wondered if there was something to fix, I thought they might have a gander. If there is nothing wrong with the installer that is fine. If there is something wrong, maybe it can be fixed by ticking a checkbox.

**Comment by AzGilrock** [comment]
Anyone know if this is still an issue?

**Comment by stevegiron** [comment]
PC#1 Has one path. PC#2 has 2 paths, one each to the 32bit and 64 bit installs.

**Comment by AzGilrock** [comment]
Its not clear to me why xLights needs to be added to the path at all.
