### ISSUE TITLE
TEXT does not use the X axis. Can't position text right or left of center

### ISSUE THREAD

**Issue by tmblue** [smeighan/xLights#449]
using the X axis slider. Y axis slider works fine to position text up or down

Matrix

MAC 4.3.0.0 and previous versions

**Comment by AzGilrock** [comment]
Actually you can but I agree it's not perfect.  Select the Vector option and the X slider works.  Just make the start and end the same if you don't want the text to move.  If you need a different movement option you can move text in the X direction by inserting leading or trailing spaces.

The text effect is going to be redone this year anyways.  We will get rid of the multi-line part of it so if you need multiple lines you will use multiple effects on different layers.  The scaling should be moved out of the movement options and made a textbox.  And after moving to single line I'm hoping we can make the colors allow each letter to be a different color.

**Comment by tmblue** [comment]
Awesome, the redesign sounds great, as ya, layers are da bomb baby! :)

Thanks!
Tory
