### ISSUE TITLE
Bug: Error opening sequence after 2016.0x upgrade

### ISSUE THREAD

**Issue by CJHacker** [smeighan/xLights#453]
I've got a sequence I've been working on it 4.3.02 and saw there was a new update the last couple of days.  When I update to 2016.02 (tried on 2016.01 as well), every time I try to open this one particular sequence, it crashes right away.

I've created a post at [xlights forum](http://nutcracker123.com/forum/index.php?topic=2546.0) for this as well and attached the debug zip.

**Comment by AzGilrock** [comment]
Pretty sure we fixed this in 2016.3.  Reopen if its still a problem next time you get to run a newer version.
