### ISSUE TITLE
2016.3 Beta

### ISSUE THREAD

**Issue by kjdunn** [smeighan/xLights#455]
Did a fresh install.  The program will not launch. I am running Windows 10

**Comment by AzGilrock** [comment]
It works fine on Windows 10 for me so with the info you gave I can't help out.  Let us know if you have anything more meaningful like an error message or something.

**Comment by kjdunn** [comment]
No crash report because the program will not open.  The little blue wheel spins for about a second and disappears. The program never launches.

**Comment by AzGilrock** [comment]
Well it sounds like you can't be a beta tester for this version then.

**Comment by kjdunn** [comment]
That response helps a lot Gil. I just thought someone might like to know it didn't launch.

**Comment by kjdunn** [comment]
Sean here is the crash report I mentioned on FB

[xLights_dbgrpt-7912-20160202T000141.zip](https://github.com/smeighan/xLights/files/113428/xLights_dbgrpt-7912-20160202T000141.zip)

**Comment by dkulp** [comment]
Fixed on master...  You can work around it by editing your xlights_rgbeffects.xml and removing the two model groups that look like:

`<modelGroup name="New Model Group" models="" selected="0"/>`

the empty modelGroup is what is causing the crash.
