### ISSUE TITLE
Arbitory mapping of individual colour elements to channels.

### ISSUE THREAD

**Issue by mrpackethead** [smeighan/xLights#456]
want to be able to map the RGB channels of a particular pixel to arbitrary channels, rather than have to follow a RGB triplets.     Taking a 16x32 p10 panel, gives us 512 channels of R,G and B each.  It would be helpful to be able to send data out as three universes, one that was just red, one that is just green and  one that is just blue.   the channel need to get mapped into E1.31.

Do not be concerned with the remote end, thats sorted. I just want to use Xlights as a media server to drive them, This one comes with a bounty if you want to take it on.

**Comment by AzGilrock** [comment]
I'd like to know what hardware requires the data to be sent this way so we can know if you're the only person in the world that needs this feature or if it will ever benefit others.

**Comment by stevegiron** [comment]
You might be able to do this with the FPP remap function.

**Comment by dkulp** [comment]
I really don't see this as happening.    At BEST, this would be implemented as a special output that was 1536 channels long but internally wrapped 3 universes and mapped it at output time.   However, that would then be very specific to xLights and the resulting fseq would still be triplets so if you used FPP to run the show, you'd have to write an output there as well.  

In general, I suggest getting hardware that is more "standard" for Christmas light displays.

**Comment by AzGilrock** [comment]
I'm closing this since it will not be implemented.  If you have control of the receiving hardware it should be capable of reordering the data however you like it.
