### ISSUE TITLE
2016.3 with windows 10

### ISSUE THREAD

**Issue by jerrymacvaldosta** [smeighan/xLights#457]
After install (no errors) launching the program results in no errors and will not open the program. Performed upgrade. uninstalled previous version and clean install. same result  No errors and no splash screen (short wait after launch then returned to prompt).

**Comment by AzGilrock** [comment]
Where did you say the files are to troubleshoot this?

**Comment by AzGilrock** [comment]
Without seeing your files I would guess you have the same issue as issue #455.  If you follow the last post there you can delete the proper lines to get past the error or you can wait to see if the next release fixes it.

**Comment by stevegiron** [comment]
Does the task manager show xlights.exe as a running process?

**Comment by jerrymacvaldosta** [comment]
resolved with 2016.4

**Comment by jerrymacvaldosta** [comment]
No.  issue resolved with 2016.4
