### ISSUE TITLE
Add code to detect VBR files when audio files are opened.

### ISSUE THREAD

**Issue by smeighan** [smeighan/xLights#461]
With a few people still having the issue of not knowing if their files are CBR or VBR, i came across this project.

http://www.codeproject.com/Articles/8295/MPEG-Audio-Frame-Header

It says that it is suggested that VBR files put the string 'Xing' in the header of VBR files, but not everyone does so. I tried a half dozen amazon mp3 files, all VBR files had 'Xing'. I looked at same files after conversion to CBR using audacity, 'Xing' is missing.

It may not be 100% but it would at least catch all audio files from Amazon.

Maybe pop up a warning message that file is VBR and should be converted before use.

**Comment by keithsw1111** [comment]
I will look into including this.

Sent from my iPhone

On 4 Feb 2016, at 10:00 am, sean meighan <notifications@github.com<mailto:notifications@github.com>> wrote:


With a few people still having the issue of not knowing if their files are CBR or VBR, i came across this project

http://wwwcodeprojectcom/Articles/8295/MPEG-Audio-Frame-Header

It says that it is suggested that VBR files put the string 'Xing' in the header of VBR files, but not everyone does so I tried a half dozen amazon mp3 files, all VBR files had 'Xing' I looked at same files after conversion to CBR using audacity, 'Xing' is missing

It may not be 100% but it would at least catch all audio files from Amazon

Maybe pop up a warning message that file is VBR and should be converted before use

—
Reply to this email directly or view it on GitHub<https://github.com/smeighan/xLights/issues/461>.

************** IMPORTANT MESSAGE *****************************       
This e-mail message is intended only for the addressee(s) and contains information which may be
confidential. 
If you are not the intended recipient please advise the sender by return email, do not use or
disclose the contents, and delete the message and any attachments from your system. Unless
specifically indicated, this email does not constitute formal advice or commitment by the sender
or the Commonwealth Bank of Australia (ABN 48 123 123 124) or its subsidiaries. 
We can be contacted through our web site: commbank.com.au. 
If you no longer wish to receive commercial electronic messages from us, please reply to this
e-mail by typing Unsubscribe in the subject line. 
**************************************************************

**Comment by keithsw1111** [comment]
Closed
