### ISSUE TITLE
Ver 2016_5 Custom Model issue

### ISSUE THREAD

**Issue by bpducman** [smeighan/xLights#463]
After opening an existing sequence that has a custom model.
The model did not display correctly running in the layout tap.

I happen to have the model hanging on the wall and it was running the lights correctly.
After  I saved the sequence it no longer looked correctly in the layout nor did it run the lights correctly.

Thanks

**Comment by AzGilrock** [comment]
So you're not on Facebook I guess cause we've been talking about this for 2 days and its already been fixed.

**Comment by bpducman** [comment]
Yep, not real big on facebook.
Sorry to inconvenience you

**Comment by bpducman** [comment]
Thanks for fixing it
