### ISSUE TITLE
Crash when adding a custom color

### ISSUE THREAD

**Issue by kjdunn** [smeighan/xLights#464]
Noticed this in .5 and ,6.  When adding a custom color to a model the program crashes. Not making a custom model.  I am using flat tree and trying to make the color yellow.  Crash report attached
[xLights_dbgrpt-41636-20160207T133520.zip](https://github.com/smeighan/xLights/files/120851/xLights_dbgrpt-41636-20160207T133520.zip)
.

**Comment by dkulp** [comment]
I'm able to create models with custom colors just fine, no crashes.   Can you take a screen shot or something of the dialog before you hit OK so I can see all the settings you are using?

**Comment by kjdunn** [comment]
![custom color](https://cloud.githubusercontent.com/assets/13409733/12875746/ce3898f6-cdbe-11e5-80ae-c02d7e9652fb.GIF)
![custom color](https://cloud.githubusercontent.com/assets/13409733/12875750/e02ef96a-cdbe-11e5-95bd-b7a4dc76bcdc.GIF)

Here's a shot of the screen up to picking the custom color yellow. Once I click on the color it crashes.

**Comment by dkulp** [comment]
Just a note for tracking:   this works fine on the Mac and on Windows in debug.   Only seems to crash with the release build of wxWidgets.   It's crashing down inside the wxColourPicker control.   This suggests a gcc bug, but still need to investigate more.

**Comment by AzGilrock** [comment]
Makes me wonder what's different between that color picker and the one used for the Color panel.

**Comment by dkulp** [comment]
We don't use the wxColorPicker on the ColorPanel (although we likely should).   They are straight wxBitmapButton's that we then manage the "color" by creating images and responding to the button push and stuff ourselves.   More work than using a normal wxColorPicker.

**Comment by AzGilrock** [comment]
Can this be closed Dan?  I think you checked in code to fix it.

**Comment by dkulp** [comment]
Yep.   Fixed.
