### ISSUE TITLE
Model List Dialog / Model Dialog when in Full Screen Mode on MAC

### ISSUE THREAD

**Issue by jcochran** [smeighan/xLights#467]
When running 2016.7 in full screen mode on a Mac, the Model Dialog opens behind the Model List Dialog and you cannot interact with the Model Dialog, you can only close the Model Dialog. You must exit from full screen mode in order to properly interact with the Model Dialog.

<img width="1173" alt="screen shot 2016-02-10 at 9 02 40 pm" src="https://cloud.githubusercontent.com/assets/17170723/12968032/aa97ae68-d03a-11e5-810d-41325a9aac1b.png">

**Comment by keithsw1111** [comment]
Model dialog is gone as per the 2016.15 ... so closing.
