### ISSUE TITLE
Crash when attempting to add custom color to custom model

### ISSUE THREAD

**Issue by rcolving** [smeighan/xLights#468]
When attempting to add a custom color to a model the Software crashes  after selecting the custom color.
Trying to creat a model I name the model Tombstone 1, select Display as custom, Type of string-Single Color Custom, I click on the color square, select orange and then when it goes back get crash report and software closes.
[backtrace.txt](https://github.com/smeighan/xLights/files/129000/backtrace.txt)

[xLights_dbgrpt-13808-20160212T234440.zip](https://github.com/smeighan/xLights/files/129001/xLights_dbgrpt-13808-20160212T234440.zip)

**Comment by AzGilrock** [comment]
So not a bad bug report except that you didn't tell us which version you were using.  Sometimes these bugs hang around a while and when we look back we don't know what the current version was when you entered the issue.

This issue was reported 6 days ago in issue #464.  We close the issue when we checkin the change that fixes the problem but that doesn't mean a new release has been put out that includes the fix.

**Comment by rcolving** [comment]
Ver 2016.7


Sent from my Verizon Wireless 4G LTE smartphone-------- Original message --------From: Gil Jones <notifications@github.com> Date: 2/13/2016  8:14 AM  (GMT-06:00) To: smeighan/xLights <xLights@noreply.github.com> Cc: rcolving <rcolving@fmctc.com> Subject: Re: [xLights] Crash when attempting to add custom color to custom
  model (#468) 
So not a bad bug report except that you didn't tell us which version you were using.  Sometimes these bugs hang around a while and when we look back we don't know what the current version was when you entered the issue.

This issue was reported 6 days ago in issue #464.  We close the issue when we checkin the change that fixes the problem but that doesn't mean a new release has been put out that includes the fix.

**Comment by stevegiron** [comment]
Is this a dupe/cross bug report before the fix was released?

**Comment by AzGilrock** [comment]
I thought so also but I had trouble figuring out which checkin might have fixed it.  I was going to ask him to check again after next release.

**Comment by dkulp** [comment]
Should have been fixed in 95e61aa700967d99e6c2ff5a03654cc46ebb2a11

**Comment by AzGilrock** [comment]
So yeah we haven't done a release with the fix but it should be fixed.

**Comment by rcolving** [comment]
This happened for  me with ver.2016.7


Sent from my Verizon Wireless 4G LTE smartphone-------- Original message --------From: stevegiron <notifications@github.com> Date: 2/15/2016  9:27 PM  (GMT-06:00) To: smeighan/xLights <xLights@noreply.github.com> Cc: rcolving <rcolving@fmctc.com> Subject: Re: [xLights] Crash when attempting to add custom color to custom
  model (#468) 
Is this a dupe/cross bug report before the fix was released?

**Comment by AzGilrock** [comment]
Please check again with 2016.8.

**Comment by rcolving** [comment]
Yep!  Works now!!!
