### ISSUE TITLE
Waveform not cleared when switching to animation.

### ISSUE THREAD

**Issue by AzGilrock** [smeighan/xLights#469]
If a media sequence is converted to an animation sequence the audio waveform is not removed from the Timeline area.

**Comment by keithsw1111** [comment]
Gil I have not fixed this yet but I have cleaned up the passing of pointers to AudioManager so the RenderBuffer class now asks for it from the xml file class when it needs it. Should avoid issues with pointers being deleted and then referenced because a class still has the old one.

**Comment by AzGilrock** [comment]
Ok.  I think you had a flag to indicate whether the audio needed to be analyzed for the VUMeter effect.  That would probably need to be set to false somehow when the audio is swapped out or removed.

**Comment by keithsw1111** [comment]
Not really. This flag sits in the AudioManager class. My thought was the xml_file would delete and set to null its AudioManager pointer. When you change audio you delete and recreate the audio manager object. If you remove the audio and make it an animation then you leave the pointer as null.
I could make the audiomanager long lived ... ie allow you to change the audio file without destroying and recreating it ... that would work and possibly eliminate potential cross thread issues where the object was deleted from under them.
It would mean possibly changing effects so that they dont just check that the media is null or not ... ie they would need to check a property.
I may have a go at this tonight.

**Comment by AzGilrock** [comment]
Ok I've added code that delete the audio pointer and sets it to NULL if the sequence type is set to Animation and that seems to clear the waveform.  About to check this in.

**Comment by keithsw1111** [comment]
Can I suggest you save the pointer. Set the original to Null. Sleep for 1ms or maybe 10 … and then delete the object.

It sounds odd but there is a potential race condition such that a render routine is accessing the audio manager. Doing this will let the render routine finish the current frame and when it next comes around to the next frame it will get the null and exit correctly.

Keith

**Comment by AzGilrock** [comment]
I'd rather do something that makes sure no rendering is occurring when someone is opening the settings dialog and changing sequence types or creating a new animation sequence.

**Comment by keithsw1111** [comment]
Ok … different way to solve the problem … and to be honest better than the kludge I proposed which doesn’t actually guarantee anything.

**Comment by AzGilrock** [comment]
I'm not sure when you would run into it anyways.  To change the sequence type you have already opened up a dialog and then made a selection.  You can't open the dialog when you are doing a Save or Render All so it would need to be a render from adjusting an effect that takes a really long time.

**Comment by keithsw1111** [comment]
Agreed. When I am debugging render is quite slow so I do see it

Sent from my iPhone

On 19 Feb 2016, at 2:00 pm, Gil Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure when you would run into it anyways. To change the sequence type you have already opened up a dialog and then made a selection. You can't open the dialog when you are doing a Save or Render All so it would need to be a render from adjusting an effect that takes a really long time.

—
Reply to this email directly or view it on GitHub<https://github.com/smeighan/xLights/issues/469#issuecomment-186024258>.

************** IMPORTANT MESSAGE *****************************       
This e-mail message is intended only for the addressee(s) and contains information which may be
confidential. 
If you are not the intended recipient please advise the sender by return email, do not use or
disclose the contents, and delete the message and any attachments from your system. Unless
specifically indicated, this email does not constitute formal advice or commitment by the sender
or the Commonwealth Bank of Australia (ABN 48 123 123 124) or its subsidiaries. 
We can be contacted through our web site: commbank.com.au. 
If you no longer wish to receive commercial electronic messages from us, please reply to this
e-mail by typing Unsubscribe in the subject line. 
**************************************************************
