### ISSUE TITLE
Bug: Model Layout is not Consistent Between Versions

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#471]
Opening xLights under 4.3.02 shows my model layout correctly.  Opening xLights under 2016.xx produces a different model layout using the same showfolder xml files.  4.3.02 has a complete list of models, 2016.xx omits the two matrices.  I have to check models groups under 2016.xx for the matrix models to show up, and then they aren't even the correct size or location as 4.3.02.  Not sure why it only affects the matrix models.  Running Mac version of xLights.

4.3.02
![4_3_02](https://cloud.githubusercontent.com/assets/12144876/13088020/2d78cc58-d4b0-11e5-80ea-ed55e7025412.png)

2016.xx
![2016_8-1](https://cloud.githubusercontent.com/assets/12144876/13088082/724260f6-d4b0-11e5-83ec-f4afd24326d1.png)
![2016_8-2](https://cloud.githubusercontent.com/assets/12144876/13088091/7dc35a70-d4b0-11e5-925d-eb91467dd96e.png)

XML files
[Archive.zip](https://github.com/smeighan/xLights/files/133158/Archive.zip)

**Comment by AzGilrock** [comment]
So every version with 2016 acts like this?  You know there was a problem in one or two of the 2016 versions with how model groups display.  Are these screenshots from 2016.8 or not?

**Comment by kppankratz** [comment]
2016.1 appears correct.  2016.2 and up is like the screen shots above.  The images are from 2016.8.

**Comment by dkulp** [comment]
You have models and model groups named the same.  (A "Matrix" model and a "Matrix" group).    That's the root of the problem.  Remove the groups of those names.   We do need to block the creation of  groups/models of the same name.

**Comment by kppankratz** [comment]
That fixed it.  Thanks.  I agree that some sort of error checking would be useful.  Just curious, why does it show correctly in 4.3.02?

**Comment by dkulp** [comment]
In 4.3, groups and models were stored separately and Models always took precedent as that map was looked in first.   In 2016.2+, groups are a special kind (subclass in C++ speak) of Model and are part of the same map.  We just happen to load the groups second so they over write the existing models.

**Comment by AzGilrock** [comment]
We are now blocking the creation of duplicate model/group names so I believe this can be closed.
