### ISSUE TITLE
Blur value persisting in the Layer Blending Panel

### ISSUE THREAD

**Issue by rickcowan** [smeighan/xLights#477]
xLights BETA 2016.9

When selecting between effects the Blur value is not correctly updating its value. This seems to only happen when the second effect clicked has the default value for Blur. If the second effect has a value other than the default then it updates as expected. The slider correctly gets updated but the text box retains the previous effects value. This is also happening for the top slider/text box that is next to the drop down for the layer style.

Please see the attached video for a demonstration.

https://vimeo.com/157062796

**Comment by keithsw1111** [comment]
I would bet #476 and #477 have a common cause.

************** IMPORTANT MESSAGE *****************************       
This e-mail message is intended only for the addressee(s) and contains information which may be
confidential. 
If you are not the intended recipient please advise the sender by return email, do not use or
disclose the contents, and delete the message and any attachments from your system. Unless
specifically indicated, this email does not constitute formal advice or commitment by the sender
or the Commonwealth Bank of Australia (ABN 48 123 123 124) or its subsidiaries. 
We can be contacted through our web site: commbank.com.au. 
If you no longer wish to receive commercial electronic messages from us, please reply to this
e-mail by typing Unsubscribe in the subject line. 
**************************************************************

**Comment by AzGilrock** [comment]
I've never dug into this but I'm pretty sure this same thing has been happening all the time.  Any time we add something new that didn't exist before in a pre-existing effect or setting there is this same phenomena where thing don't appear exactly right until an effect has been updated which allows it to store the new setting names.

**Comment by rickcowan** [comment]
That's possible. I've never changed any of the color panel values before other than the actual colors and blur is of course new.
