### ISSUE TITLE
Bug: Blend option causing crash

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#478]
Playing around with the new unreleased transition options and I keep getting a crash whenever I select the blend option in the drop down and I have a time other than zero entered into the in or out transition fields.

No crash report with this particular crash.

Running OS X 10.11.3

**Comment by keithsw1111** [comment]
What type of model and what dimensions?

**Comment by kppankratz** [comment]
Matrix, 128 x 64 (width x height).
