### ISSUE TITLE
Enhancement: Scrolling effects bar

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#480]
With all of the new effects added, and any future ones, is it possible to make the effects bar able to scroll left and right if the effect icons extend beyond the screen?

I increased the size to the largest possible and I was unable to see or select any effects that were off of the screen to the right.

I know the icons were increased to help with the visually impaired at one point.

![effects](https://cloud.githubusercontent.com/assets/12144876/13480211/ed54f98c-e0a1-11e5-9aca-75156dda64f9.png)

**Comment by AzGilrock** [comment]
There is also an effect panel you can use.  I guess this all depends on your monitor cause if you look at that video effect preview I posted yesterday I have a lot of room for more effect icons.  I don't know if toolbars can contain scrollbars but it would grow vertically and take up space.  I think maybe allowing the user to customize the toolbar with their favorite effects might be better and then let the effect panel be used when you need one of the others.  You can also always drop and effect and use the effect settings panel to change the effect type in the drop down.

**Comment by keithsw1111** [comment]
The effect panel is the solution for this requirement ... or reducing the icon size which can be done via the settings menu.
