### ISSUE TITLE
Layout tab stop and pause not working

### ISSUE THREAD

**Issue by ccsuhr** [smeighan/xLights#481]
in version 2016_10 
in the layout tab: Once you start a sequence by pressing the play button on layout tab the sequence will start then there appears to be no control of till it finishes. The pause, stop button and the slider have no effect on sequence.  If you start the sequence in the sequencer tab  the menu bar play and stop ... all work fine. You can see the button being pressed in the layout tab but no results . Can be reproduced on existing and new sequences.

**Comment by kppankratz** [comment]
There's a separate play and stop button for the layout tab.  It's under the open button and right above the select model groups button.

**Comment by ccsuhr** [comment]
Uninstalled 2016_10 and installed 2016_9 and play and pause button on layout work correct.  uninstalled 2016_9 and reinstalled 2010_10 and play and pause and slider on layout tab have no effect after initial play.

**Comment by JonB256** [comment]
Also having this problem. Can't stop playback in Layout.

**Comment by dkulp** [comment]
FYI: These controls will likely just be remove as we get rid of the various tabs.

**Comment by ccsuhr** [comment]
Thanks don't usually use them but today did and found this.  Keep up the awesome work.
