### ISSUE TITLE
Bug: Switching tabs looses window positions under sequencer tab.

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#482]
After loading my perspectives under the sequencer tab, if I switch to another tab and then come back to the sequencer, all of my window positions have changed.  Some are even docked in the main window again.

2016.10 Mac Edition

**Comment by dkulp** [comment]
Can you resave your perspective and see if it continues?   We added a new panel (Layer Settings) so the old perspectives are invalid.

**Comment by kppankratz** [comment]
That worked, sort of.  Saving under the old perspective name did not correct the issue.  I had to create a completely new perspective name and save the positions under that.

Should I close this or leave it open to have it updated within the code to correct this?
