### ISSUE TITLE
Enhancement: Smart Screen Error on download Windows 10

### ISSUE THREAD

**Issue by ccsuhr** [smeighan/xLights#485]
![smartscreen](https://cloud.githubusercontent.com/assets/17096632/13530421/f1a6ca10-e1e6-11e5-8612-a34efa2a5561.PNG)
![smartscreen2](https://cloud.githubusercontent.com/assets/17096632/13530426/f51100b2-e1e6-11e5-9426-bfc5fd0f02b9.PNG)

**Comment by AzGilrock** [comment]
So what?  Tons of applications do that upon install on Windows 10.  Just hit Run anyway and install it.

**Comment by ccsuhr** [comment]
Thought it would make it look more professional and save questions from
noobs. Not sure what it took to fix this

**Comment by AzGilrock** [comment]
I would bet it involves paying Microsoft if its anything like the driver certification I've had to do for a WinQual.

**Comment by ccsuhr** [comment]
I'll close when I get home thanks for the information
