### ISSUE TITLE
Multiple video pointing to same video in same sequence are not independent of each other.

### ISSUE THREAD

**Issue by ccsuhr** [smeighan/xLights#486]
In trying to set start time to sync video note that with 4 elements pointed to same video they appear to be identical even with different start time one they start they are at same point in video.

![video1](https://cloud.githubusercontent.com/assets/17096632/13538451/3ec18474-e210-11e5-9bbd-02e621a6028d.PNG)
 note the point in time screen shot.

**Comment by AzGilrock** [comment]
Looks like this already got fixed yesterday.  Release 2016.11 should correct it.  I just verified it's not a problem in the latest Pull.

**Comment by ccsuhr** [comment]
Thanks for update.
