### ISSUE TITLE
Timing tracks don't work for dropping effects

### ISSUE THREAD

**Issue by smeighan** [smeighan/xLights#49]
Started with a v 3.6 xml
1) open xml file, it is auto converted. finds mp3 file 
2) Go to timing tab and import in two audacity label files.
3) go to Sequencer tab, 3 timing tracks shown
the "Imported Timing" track i can drop effects on and the timing marks seem to work. hovering over a model with "Import Timing" highlights block that is active,.

two additional imported timing tracks never highlight a region, unable to drop effects on them.

Here is a two minute video showing the issue, https://vimeo.com/120764177

**Comment by smeighan** [comment]
Dave explained the issue is the timing tracks have start and end times the same.

I looked at the timing produced from audacity

0.882358	0.882358	1
2.461315	2.461315	2
4.051882	4.051882	3
5.665669	5.665669	4
7.256236	7.256236	5
8.858413	8.858413	6
10.460590	10.460590	7
12.062766	12.062766	8

When i wrote a converter i ignored the econd timing and set the end timing as the start of the next row. this worked for all except the last row.

138.576689	138.576689	67
140.712925	140.712925	68
142.756281	142.756281	69
144.799637	144.799637	70

so for label 70 i would probably add one frame timing to it (eitehr 25ms or 50ms) to the start timing of label 70.

**Comment by AzGilrock** [comment]
Yeah this actually worked fine for my Audacity files I used for testing.  I had different start and end times since I like to drag out the timing end mark in Audacity and type in a label name which would import into xLights v3.  I've maintained importing the label but we don't display it yet.

**Comment by smeighan** [comment]
Hi Gil;

still see a problem. I see some timings changed, others have start and end the same.
when they are the same i cannot drop effects on them.


```xml
<ElementEffects>
    <Element type="timing" name="01 - Carol of the Bells">
      <EffectLayer>
        <Effect label="1" startTime="0.875000" endTime="2.450000"></Effect>
        <Effect label="2" startTime="2.450000" endTime="2.450000"></Effect>
        <Effect label="3" startTime="4.050000" endTime="4.050000"></Effect>
        <Effect label="4" startTime="5.675000" endTime="5.675000"></Effect>
        <Effect label="5" startTime="7.250000" endTime="8.850000"></Effect>
        <Effect label="6" startTime="8.850000" endTime="8.850000"></Effect>
        <Effect label="7" startTime="10.450000" endTime="10.450000"></Effect>
        <Effect label="8" startTime="12.075000" endTime="12.075000"></Effect>
        <Effect label="9" startTime="13.650000" endTime="13.650000"></Effect>
        <Effect label="10" startTime="15.275000" endTime="15.275000"></Effect>
        <Effect label="11" startTime="16.900000" endTime="16.900000"></Effect>
        <Effect label="12" startTime="18.475000" endTime="18.475000"></Effect>
```

**Comment by AzGilrock** [comment]
Can I see the first few lines of your text file?  I'm suspecting it's because is we round all timings to the frequency of the sequence so it's possible after rounding that when I grab the next start time it was rounded to the same as the end time of the previous.

**Comment by AzGilrock** [comment]
Just to record the history.  I've duplicated the problem.  It only happens in the Release build and works fine in the Debug build.  Still investigating a solution.
