### ISSUE TITLE
House Preview Displays in Long Skinny Window

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#491]
2016-11
If you open an existing sequence and then press the House Preview at the top of the screen with release 2016-11 it now opens a window the size of the X that you would press to close a window and it goes from the top of the screen to the bottom.  It is located to the left of the standard windows such as "model preview", "effects", "effect settings", etc.  When you undock the house preview window you get a windows about the size of two of the close x's stacked on top of each other.  The "dock all" returns it back to a long skinny window.
You can resize the window after you undock it but it returns to the long skinny window when you dock it.

**Comment by AzGilrock** [comment]
I had that happen last release.  The easiest fix is just delete your perspectives section in the xml and let it regenerate when you reopen the program.  There is some kind of problem with the old perspectives not changing to the new format properly or something.  I don't really understand the perspectives that well.

**Comment by dcwehw99** [comment]
Deleting the perspectives section took care of it.

Thanks
