### ISSUE TITLE
Space Bar not Function Until.......

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#492]
After initially opening a sequence the space bar is not functional to start and stop the playing of the sequence.  If you press the play key in the toolbar at the top, the sequence starts playing but pressing the space bar doesn't stop it.  Likewise if you stop the sequence that is playing with the stop button in the toolbar at the top, the space bar will not start playing the sequence again **UNTIL** you click anywhere within the grid of models in your sequence.  After doing that the space bar is fully functional.

Denny

**Comment by AzGilrock** [comment]
Yep that's how it works.  The grid needs focus or it doesn't receive the keyboard input.

**Comment by AzGilrock** [comment]
This was discussed long time ago here in #194.

**Comment by dcwehw99** [comment]
Gil,

Please don’t take what I’m trying to say as criticism because I’m only trying to help improve Xlights.  I feel the team does a great job on the product and I’m very thankful for what the team does.  I’m new to Xlights 4 but I have used Xlights 3 in the past so pardon me for questions/problems. 

 

Having been in the IT field for 38+ years I’m just trying to offer suggestions based on my experience.  One of the things I think is necessary is to have not only consistency within the Xlights application but consistency across Windows applications.  Can you imagine the user confusion if something as simple as the copy/paste keyboard combinations were one keyboard combination in one application and a different keyboard combination in another application?  Back in the early days of Windows, even before it was called Windows, that was how the software vendors wrote their applications because there was no standard.  What about if you made the F10 function key one thing in one window and something completely different in another window within the application.  That’s not something you want to do.  Also creating exceptions or special conditions should not be something you “design” into the application unless there’s a technical reason to do so.  I think in this case there’s no technical reason to do so either.

 

I know what we talking about here is trivial, i.e. the space bar starting/stopping the sequence without having to first click in the sequence grid.  If you look at other applications such as “Audacity”, “LSP”, “Power Director”, and “Pinnacle Studio” that have grids or even other MP3 players, they have all implemented the “space bar” to start and stop without having to first click anywhere.  The “space bar” function works immediately after opening a file without putting any conditions on being able to use it.   I did read problem # 194 and the conversation between “LightsOnHudson” and “Stevegiron”.   One of the first things I do when I come into Xlights is use the F10 key to create a backup, which by the way you can do without having to click in the Xlights grid.   I can’t imagine “designing” the application such that you would first have to click in the grid before pressing the F10 key to do a backup.  What’s the point of creating a condition on using the F10 key or the space bar?

 

I understand that you only have a limited amount of time and resources and this isn’t your full time job.  I was just offering food for thought so I’m ready to move on.

 

Thanks for your time.

 

Denny

**Comment by AzGilrock** [comment]
That story is kinda long...I'll have to wait for the movie.

**Comment by AzGilrock** [comment]
Actually I don't see this behavior.  I can click Play and then the spacebar still works.  You just need to press Alt+F4 after you start the program.

**Comment by dcwehw99** [comment]
That’s my point you have to click play or click on the grid before the space bar works.  All the other applications I mentioned, Audacity, LSP, Power Director, Pinnacle Studio, and MP3 players, the space bar works immediately without having to click on the play button or in the grid first.

**Comment by AzGilrock** [comment]
I don't need to read your long stories or explanations.  I thought I was clear in my first replies.  We already know.  We've already discussed it.  You aren't going to be able to find much I don't already know.  It's just wasting my time having to come back and look at these responses.

**Comment by stevegiron** [comment]
Question has been answered.
