### ISSUE TITLE
xLights crashes when trying to delete an effect preset group

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#495]
www.stevesimages.com/xl4/presets.mp4

This issue is at the 2:10 mark.

**Comment by AzGilrock** [comment]
Actually you can delete a preset group.  I had trouble reproducing this but finally got it to crash.  It appears to have something to do with the speed at which you are clicking the Delete button.  If you aren't clicking it fast it seems to delete just fine.  I'll have to see if there's something I need to lockout until the previous delete has completed.
