### ISSUE TITLE
Backwards compatibility improvement needed for existing effects

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#496]
When using presets, or effects in existing sequences, some tags are not recognized.
www.stevesimages.com/xl4/presets.mp4

Note in the video where after the 3rd pop-up message displays, the effect become sticky to the mouse.

![slider-direction](https://cloud.githubusercontent.com/assets/10568498/13731612/bc3f72c8-e92a-11e5-8db8-a9c721e40985.JPG)
![slider-speed](https://cloud.githubusercontent.com/assets/10568498/13731614/bf2122c0-e92a-11e5-8557-439b4fe599c1.JPG)
![fit-to-time](https://cloud.githubusercontent.com/assets/10568498/13731615/c1a8cb38-e92a-11e5-895d-c6d3158de277.JPG)
![slider-spirals](https://cloud.githubusercontent.com/assets/10568498/13731616/c835896e-e92a-11e5-8868-3ee5b5718954.JPG)

**Comment by AzGilrock** [comment]
I don't believe this is an issue now that we have upgrade code that is run when effects go through the paste logic which is how presets are applied.
