### ISSUE TITLE
Vixen Import Effects Mapping

### ISSUE THREAD

**Issue by Phrog30** [smeighan/xLights#499]
When trying to import effects from a Vixen 2.1 file, the mapping dialog is not allowing a node to node map.  Instead of being able to map a node (which includes all 3 colors), it only allows each individual color/channel to be mapped.
![vix](https://cloud.githubusercontent.com/assets/12203743/13819743/8e2feb70-eb68-11e5-85c4-7b1238133e30.png)

**Comment by AzGilrock** [comment]
I looked into this a few weeks ago and yours is getting further than mine.  I couldn't get it to show any channels.  I thought I had worked on troubleshooting a .vix file before but the only one I have doesn't seem to work.
