### ISSUE TITLE
Enhancement: use an image file as a background when defining pixel location in custom model editor

### ISSUE THREAD

**Issue by SteveGase** [smeighan/xLights#5]
I created a custom model for my 50-pixel coroflake, and due to the size of the grid and the irregular placement of pixels it was pretty awkward.

I found that if I opened a picture of the coroflake in MSPAINT and hovered over each pixel location, I could identify the coordinates.  I then created a spreadsheet with a bunch of conversion formulas to stretch/shrink the points to the 50x50 grid that I created in nutcracker.  My spreadsheet converted each point to the coordinates used in the custom editor.  It was awkward, and maybe something that others might not attempt.

A couple suggestions:

#1 (EASY):  allow the user to upload a picture into the custom model editor, and show that picture as a background for the grid.  The user should crop the image first for best success, but seeing the location of the lights will make it much easier to find the grid locations.

#2 (MODERATE): allow the user to upload a similar picture as the background, but as the user clicks on a point, a mark is made on the screen (maybe the channel number?) and the number of channels is incremented in model, along with the coordinates inside the grid.    Example: the user uploads picture of a texas star, and then proceeds to click on each of the five points.  With each click a number is written to that point... #1, #2, #3, #4, and finally #5.  As each point is clicked the count of pixels is increased.  On the previous page, the user can update the channel numbers for each pixel.

**Comment by stevegiron** [comment]
This issue is over 2 years old. Ok to close for now?
