### ISSUE TITLE
Xlights crashes after pressing Test Tab

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#502]
Opened a sequenced then dropped an effect onto the grid then pressed the "Test" tab and Xlights crashes.

**Comment by ccsuhr** [comment]
I crashed also but after closing the test tab and selecting between tabs crash reports attached.
[xLights_dbgrpt-3348-20160317T060201.zip](https://github.com/smeighan/xLights/files/177708/xLights_dbgrpt-3348-20160317T060201.zip)
[xLights_dbgrpt-11764-20160317T060340.zip](https://github.com/smeighan/xLights/files/177709/xLights_dbgrpt-11764-20160317T060340.zip)

**Comment by dcwehw99** [comment]
If you do the reverse, i.e. open a sequence, open/close the "Test" tab, and then drop an effect on the grid, Xlights goes into an infinite "Debug Report" loop.  To get out of the repeated "Debug Report" windows you have to cancel Xlights via the Windows "Task Manager".

**Comment by keithsw1111** [comment]
Odd ... I will need to look into this. The backtrace does not look like the test tab but it also doesnt look like anything else either. I will need to try to reproduce it.

**Comment by AzGilrock** [comment]
I thought we deleted the test tab and made it a popup dialog from a menu.

**Comment by dcwehw99** [comment]
Xlights 2016-13
By "Test" tab I mean press the "Tools" option at the top of the screen and then press the "Test" option.
