### ISSUE TITLE
Tools-Test: Single Output will only test first universe

### ISSUE THREAD

**Issue by mararunr** [smeighan/xLights#503]
Define multiple universes as one output (in my case 37 universes @ 192.168.1.123 for my BBB that has 3x4 P10 matrix).
Create a model larger than one universe (Horizontal matrix with 64 strands of 96 pixels for my 3x4 P10 matrix).
Go to Tools -> Test
Select controller and attempt test option (I used the last tab with R-G-B-All) - only first universe lights up
Select your model that spans multiple universes (I used the last tab with R-G-B-All) - only first universe lights up

Was able to create sequence and live update various effects across whole model with no problem (BBB in bridge mode whole time).

**Comment by keithsw1111** [comment]
Can you please post your xlights_networks.xml and xlights_rgbeffects.xml files so I can reproduce this.

**Comment by mararunr** [comment]
[LivingRoomP10s.zip](https://github.com/smeighan/xLights/files/180614/LivingRoomP10s.zip)

**Comment by keithsw1111** [comment]
Fixed in 9f4350f
