### ISSUE TITLE
Making app window span monitors causes timing mark to stretch

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#504]
www.stevesimages.com/xl4/screen-drag.mp4

No audio, I first show there are evenly spaced timing marks to the right and then drag the right edge of the application window to the right monitor.

This will also happen if you place the application on the right monitor and expand the window to the left.

**Comment by AzGilrock** [comment]
I got it to do this on one monitor.  Hitting the + then - buttons fixes the display.

**Comment by AzGilrock** [comment]
Yeah it looks like whenever the window was resized it wasn't recalculating the end time for the Timeline object so when it made the call to see if timings were on screen or not it calculated based on the last time the end time got updated like when you do a zoom.
