### ISSUE TITLE
2016.14 Crash in Sequencer

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#506]
If you immediately press the "Sequencer" tab after starting Xlights it crashes (debut report attached).
It will let you open a sequence and work with it OK; it's only if you press the tab immediately after starting Xlights.  I also found that if you wait 5-10 seconds before pressing the "Sequencer" tab it doesn't crash.

[xLights_dbgrpt-10072-20160325T103756.zip](https://github.com/smeighan/xLights/files/189685/xLights_dbgrpt-10072-20160325T103756.zip)

**Comment by keithsw1111** [comment]
Not seeing this one either. Can you check again in 2016.15 when it comes out.

**Comment by dcwehw99** [comment]
I just installed 2016-15 and I'm no longer having the problem.
