### ISSUE TITLE
2016-14 random crashes

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#508]
![image](https://cloud.githubusercontent.com/assets/10568498/14067800/676a5648-f422-11e5-98fb-46af7be171a8.png)

Video at www.stevesimages.com/xl4/14-crash.mp4

**Comment by keithsw1111** [comment]
Steve ... I cannot reproduce this ... maybe try again in the next release.

**Comment by stevegiron** [comment]
Will do. I installed a fresh copy of Win7 last night. I installed 2016.14 and had the same thing happen.  Can't wait to try the next release.

**Comment by stevegiron** [comment]
Unable to reproduce with .17. Closing.
