### ISSUE TITLE
Add Copy/Cut/Paste 

### ISSUE THREAD

**Issue by smeighan** [smeighan/xLights#51]
Be able to highlight a group of effects in the Sequencer grid and be able to
ctl-x: cut. Add thsi in addition to teh current DEL key
ctl-c: copy
ctl-x: paste

**Comment by AzGilrock** [comment]
I think there are a lot of questions to answer when considering how to implement this.  A few are:
Should paste delete all effects underneath the paste area?
Do we get crazy and have paste as foreground and paste as background and automatically create new layers whenever pasting where a current effect exists?
Do we get crazier and have paste by time as well as paste by timing mark divisions?

**Comment by stevegiron** [comment]
I would suggest that version one pastes on top of whatever is there.
Version 2 would allow for paste as new effect layer(s).
Version 3 would then allow the layers to be dragged higher/lower as needed.

I'd be happy with version one.

**Comment by stevegiron** [comment]
Is this one closeable now that we have copy/paste?

**Comment by stevegiron** [comment]
We now have Copy, Paste, Delete.
