### ISSUE TITLE
"Convert to Effect" Deleting Data

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#510]
Here's the issue I experienced with the "Convert to Effect" process:
1.  I created a new musical sequence at 20 FPS.
2.  I added an "Arches" model group which is made up of four (4) arch models of 8 nodes each.
3.  Then using the "Import" button under the "Data Layers" tab in "Sequence Settings", I imported the data for the arches from an existing sequence (*.xseq).  After the import the data for each of the eight (8) nodes looks OK if you expand the view of the models.
4.  If you then right click on any one of the eight nodes in one of the "arch" models and select the "Convert to Effect" option in the drop down box, it converts the data for that node into a Xlights effect.
5.  If you then select any of the converted effects in that node using a left click, it will delete all the data for the other seven (7) nodes within that model.  Only the data for the node you just converted remains.

It looks like when you do the "Convert to Effect" on the node it's either not displaying the effects correctly or it's not converting them correctly, i.e. the converted effect is appearing where there is no data and where there is data there is no effect.  I've only seen this problem for the "Arches" model; other models I have work correctly;

Thanks
Denny

**Comment by AzGilrock** [comment]
Yes I confirmed this is how it works.  When you click on an effect for the model its going to render for that entire model so it will blank out the other nodes.  We don't add back in data layer data until you do a full render all or save with render.  I'll leave this open for now while I ask the others if we would ever try to do more work in the quick render.
