### ISSUE TITLE
Effect Request: Audio

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#511]
Add a Audio effect that would allow sound clips to be dropped into sequences.  I could see triggering these clips during playback of a sequence without the need for a full audio track.

Is this idea even possible within wxWidgets and the current sequencer?  Throwing it out there for possible inclusion within xLights.  If not, then I can close the ticket.

**Comment by keithsw1111** [comment]
I dont think this is a good idea. Even if we could do it it would only work if you play your sequence in xlights ... there would be no way to reuse this in FPP for instance.

A better approach would be to use audacity to create an audio track with silence punctuated by the audio you want at the appropriate times and use this as the audio track ... you could then use it on FPP as well.

I suggest we close this one.
