### ISSUE TITLE
2016.16 crashes after a few seconds

### ISSUE THREAD

**Issue by joclaesbe** [smeighan/xLights#512]
xLights_dbgrpt-5544-20160401T201633.zip
.
.
Sorry to border you but since I installed the latest version of Xlights the program keeps crashing, so I'v posted the crash report in Xlights group Greetings
Jo

 The program crashes after I try to change an effect on a megatree model.

**Comment by stevegiron** [comment]
The latest releases seem to be very stable. Are you still having this issue?

**Comment by joclaesbe** [comment]
Hello,

Thank you very much for the interest and the following up, I really appreciate this.

At this moment I’m using the 2016.19 version, and it seems to be very stable indeed.

 

Very best regards and greetings from Belgium

Jo

 

Van: stevegiron [mailto:notifications@github.com] 
Verzonden: vrijdag 15 april 2016 22:35
Aan: smeighan/xLights <xLights@noreply.github.com>
CC: joclaesbe <jo@dedijk.be>
Onderwerp: Re: [smeighan/xLights] 2016.16 crashes after a few seconds (#512)

 

The latest releases seem to be very stable. Are you still having this issue?

**Comment by AzGilrock** [comment]
Sounds like we can close this.  You can always open a new one if you have another problem.
