### ISSUE TITLE
Future Enhancement Custom Colors to Custom Models

### ISSUE THREAD

**Issue by buckstopper2** [smeighan/xLights#513]
Wondering if the ability to add custom colors to an individual channel in custom models could be added. This would be for AC controllers for ex. I have an 8 channel talking tree with different colors lights on each channel 1-8. As it stands now the entire tree is one solid color.

**Comment by stevegiron** [comment]
You could create separate custom models for each channel.  Then create a model group that contained those parts to make up the tree.
