### ISSUE TITLE
Have ability to hide strands and nodes in "Import, Import Effects"

### ISSUE THREAD

**Issue by smeighan** [smeighan/xLights#514]
In the "Import, Import Effects" screen is there a way to hide the strands and nodes? I have 12,000 nodes. I have to scroll through 12,000 lines when i am only looking for the first line. This is especially true for importing in xLights xml files. A nice enhancement is if it could be a tree display, click to collapse nodes and strands.

**Comment by keithsw1111** [comment]
Done ... at least for xlights xml files.
