### ISSUE TITLE
Window to "edit display elements" in sequence tab will not launch

### ISSUE THREAD

**Issue by robjoyce1921** [smeighan/xLights#516]
When trying to add display elements in the sequence tabs, the window does not launch.  Deleting xlights_rgbeffects.xml allows normal functionality.

A quick video of the error condtion can be seen here:
http://screencast-o-matic.com/watch/cDfecm1wdY

Problem file:  
[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/201130/xlights_rgbeffects.zip)

Deleting the perspectives section of the xml solves the problem.  Not sure what is corrupt or how it forces the error, but deleting that section and relaunching the problem remedy's the issue.  Low priority but assume someone will want to track down the root cause and protect against the problem in the future.

**Comment by AzGilrock** [comment]
I opened your xlights_rgbeffects.xml file and I could see your Display elements window just fine.  It was below the normal window but I have a high resolution screen.  Maybe you don't.  Did you used to have things on two monitors and then went to one?  We really can't put code in there to try to analyze all your window locations and move them around.  We've already had this issue posted 2 or 3 times and the fix we installed was the "View / Windows / Dock All" feature.  I used that command and it docked your panel just fine.

**Comment by robjoyce1921** [comment]
I use a dual monitor setup.  Left monitor is 1760 x 1050, Right Monitor is 1920x1080.
To make the recording someone asked about I put the rgbeffexts file on my laptop and recorded the issue.  It did the same thing on both machines.  

Back on the xlights forum, someone suggested "dock all" as a cure.  I can tell you that dock all didn't correct the problem.  Understand if this is an edge case that you don't want to chase.  If there is something generic to reset any issues, I'm happy to try beta versions on my machine.  If you want to just close the issue, I don't mind.  Just wanted to ensure it was reported.   thanks,

Rob

**Comment by AzGilrock** [comment]
Here's a video of me using your xlights_rgbeffects.xml file in a show directory and where the display elements windows shows up and I execute a successful Dock All.  Note that the Display Elements window actually has the title "Sequence Elements" so maybe that's why you thought it wasn't there.
https://youtu.be/3zi0S3PnCyI

**Comment by robjoyce1921** [comment]
Gil - thank you for taking the time to check again and make the video.  It dock all does solve my problem.  I appreciate the personal investigation and reply.  So sorry for taking you away from real problems!
