### ISSUE TITLE
Future Enhancement: Undo feature when opening a seqence and remapping models

### ISSUE THREAD

**Issue by robjoyce1921** [smeighan/xLights#517]
When opening a sequence from another author, models need to be remapped into the new display.  Users get an alert "Model 'xxx' does not exist in your list of models" and user is prompted to delete the data for the missing model, or renaming the element.  Moving through the remap, pulling down the list of models to chose a remapping.  This should automatically click the radio button indicating you intend to remap, not delete the item.  I often forget to push the radio button and and wind up deleting.  Auto-selecting the radio button to rename would solve the problem.

![auto set rename button](https://cloud.githubusercontent.com/assets/6397578/14230304/2bff14ac-f91f-11e5-82ba-8b2445667de2.png)

Ideally, we could have an option to go back through past decisions with an "undo" function, but setting the radio button would solve 85% of my issues that require an undo/back button.

It would also be nice to add a "cancel open" button.  Today, you must walk through all remapping before you can quit.  If you make a mistake, you mush walk through all model remaps before trying again.

**Comment by AzGilrock** [comment]
Sean already beat you to the cancel button idea.  He emailed the developers yesterday and the fix was checked in before you posted.  I'm not sure anyone is going to do the rest of the requests but we'll see.

**Comment by robjoyce1921** [comment]
Thanks for the cancel button.  That will help when I mess up.  auto setting the undo selection whenever the pulldown menu of valid models for remapping would catch my stupid mistakes most of the time.

**Comment by AzGilrock** [comment]
We now have the ability to create a mapping file when you want to import an XML sequence from another author.   I tend to want the Delete option to be the default for this dialog.  So I think users need to use the new mapping feature or use this dialog as is.
