### ISSUE TITLE
Effect buffer doesn't clear between effects

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#518]
How to recreate:
New sequence with 2 timing marks.
Butterfly on timing mark 1
Strobe on timing mark 2
Set timing mark 2 Layer Settings for Persistent
When timing mark 2 starts, the last frame from timing mark 1 persists into timing mark 2.

Today's workaround is to put minimum sequence spacing gap between effects instead of effects touching in the sequencer.
![image](https://cloud.githubusercontent.com/assets/10568498/14257849/7d5c08f6-fa54-11e5-968f-ffcfc67113bd.png)

**Comment by AzGilrock** [comment]
Confirmed.  Not sure I know how to fix it but I'll look.

**Comment by keithsw1111** [comment]
I really dont want this changed. If you dont want the persistence to carry over from the prior effect then place the effect on a different layer.

Having it work this way enables other really desirable behaviour.
