### ISSUE TITLE
Pop up menus are not consistent

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#520]
This video shows the issue.
www.stevesimages.com/xl4/windows.mp4

**Comment by AzGilrock** [comment]
I don't have audio so I was wondering is it just a difference between how a docked vs un-docked panel works?  Did you try undocking something like the colors panel that was working and see if that breaks it?

**Comment by stevegiron** [comment]
The model preview appeared to behave when docked. The house preview did not. I tried again to verify and the model preview did not re-appear after closing the docked window. The results are inconsistent.

**Comment by keithsw1111** [comment]
Did you try dock all to see if it comes back ... while you may not have multiple monitors maybe the location when it is undocked is off the screen ... although I am not sure why that would be.

**Comment by stevegiron** [comment]
I do have multiple monitors but in this case I was only using one monitor. I did look on the 2nd monitor for the box but it never showed up there. Clicking enough times eventually will make the box reappear on the first monitor.

**Comment by keithsw1111** [comment]
Ok … but the question remains … did you try dock all and did it bring them back.

Not saying there isn’t a problem here but this would help understand what is going on.



************** IMPORTANT MESSAGE *****************************       
This e-mail message is intended only for the addressee(s) and contains information which may be
confidential. 
If you are not the intended recipient please advise the sender by return email, do not use or
disclose the contents, and delete the message and any attachments from your system. Unless
specifically indicated, this email does not constitute formal advice or commitment by the sender
or the Commonwealth Bank of Australia (ABN 48 123 123 124) or its subsidiaries. 
We can be contacted through our web site: commbank.com.au. 
If you no longer wish to receive commercial electronic messages from us, please reply to this
e-mail by typing Unsubscribe in the subject line. 
**************************************************************

**Comment by stevegiron** [comment]
I just clicked around until I saw the issue re-appaer. I then did a dock all and that did not fix it.

**Comment by AzGilrock** [comment]
I did some testing and it seems like this was working fine in 2016.13.  I think the new wxWidgets 3.1 fixed a bunch of old problems and caused a bunch of new ones.

**Comment by AzGilrock** [comment]
Found another quirk with this.  If you close a floating pane then the Toolbar button doesn't seem to work to bring it back.  But if you click over to another window in a different application like Internet Explorer and then click back on the xLights app then hit the toolbar button it works.  I discovered this trying to debug because the button wasn't firing the event code but after I switched over to make sure I had the breakpoint set it worked after I switched back.  But then doing the same steps again and it would not fire the event until I changed focus to another app and then come back.

**Comment by AzGilrock** [comment]
Well I was going to show this in a video but as soon as I run Camtasia the problem disappears.  It must somehow affect the event handling of the window since the screen capture is running.  Closed Camtasia problem returned.

**Comment by stevegiron** [comment]
Yes I tried to dock and that did not fix it. However randomly clicking on
the different tabs and other menu items will then bring the windows back.
I actually always run 2 monitors, but for this recording it was all running
on one monitor but I did peek on the other monitor to see if the windows
popped up over there. No luck.

**Comment by stevegiron** [comment]
Issue still exists with .18

**Comment by AzGilrock** [comment]
Closing since above referenced commit should have fixed this.
