### ISSUE TITLE
Crash after trying to update model group.

### ISSUE THREAD

**Issue by lightsonlinden** [smeighan/xLights#523]
I am trying to add a model group which I was able to add.  However, when I try to place the models into the group and then when I click OK after the edit to add the models - xlights crashes.

using version 2016.17

Screencast of the steps to the crash:  http://screencast-o-matic.com/watch/cDfifD145x

**Comment by lightsonlinden** [comment]
[xLights_dbgrpt-9052-20160406T230606.zip](https://github.com/smeighan/xLights/files/207722/xLights_dbgrpt-9052-20160406T230606.zip)

**Comment by AzGilrock** [comment]
I tried to reproduce this issue but couldn't.  First make sure it still occurs in version 2016.18.  Second I notice the model group in the video is not in the xlights_rgbeffects.xml file that is attached to the debug report so after you create that model group can you hit the Save button before you edit and add the models to the group.  That way we will have the same model group name in the zip file.  Not sure if this was something name specific. I notice the models/groups having problems all seem to use dashes in the names.

**Comment by dkulp** [comment]
This was fixed in 2016.18
