### ISSUE TITLE
Node Layout Icycles

### ISSUE THREAD

**Issue by ikke1981** [smeighan/xLights#526]
Hi, 
I guess i found a problem with the node layout of the Icyles. 
The last drop seems to come at the beginning of the strand, And nodes 1, 2, 3 and 77 are gone.
This is the standard iclycle from the version 2016.18.
Best regards, and thanks for this amazing program... 
Greetings from Belgium.
Dennis Pluy
![image](https://cloud.githubusercontent.com/assets/14152254/14404015/c10860ce-fe6c-11e5-9138-1ec09bb60755.png)

**Comment by stevegiron** [comment]
Verified. If you do a 3,4,5 defined icicle, the nodes show properly. Once you add that 4th drop the last drop appears at the start again.

**Comment by dkulp** [comment]
This was resolved in 2016.19
