### ISSUE TITLE
Importing SUP to Models

### ISSUE THREAD

**Issue by BigTrafficman** [smeighan/xLights#528]
I have updated to the newest xlights and when I import the sup file to a model (pixel tree) its not turning out as well as it did in the past versions. I tried to go back but I get an error now of .dll missing.  The sup is a 12x50 and I am converting it to a 16x84 like I have done in the past. Thanks again for such a great software.

Jeff Messer

**Comment by AzGilrock** [comment]
I tried it and it turned out well.

**Comment by AzGilrock** [comment]
I guess you didn't get the hint.  Unless you provide a better description of what didn't go well there is no way for me to know where to start looking.
