### ISSUE TITLE
Windows Packaging [Setup]

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#531]
Here are some suggested changes to the Windows installer

[setup]
;We set the UninstallDisplayName so it does not contain a verion number, thats what AppVersion is for
;which InnoSetup adds by default this makes it hard to automate if the UninstallDisplayName changes all the time.
UninstallDisplayName=xLights
AppName=xLights
; AppID determines the registry tree i.e. <AppID>_is1\
AppID=xLights
AppPublisherURL=http://nutcracker123.com/nutcracker/releases/
AppSupportURL=https://github.com/smeighan/xLights/issues
AppReadmeFile=http://nutcracker123.com/nutcracker/releases/README.txt
AppPublisher=The xLights Team
VersionInfoVersion=2016.20

If you wish to support moving to xlights 5 one day. And so having xlights4 and xlights5 installed at the same time
You need to set AppID=xlights4 and you may wish also to set AppName=xLights4 UninstallDisplayName=xLights4
Or you do instead of xlights do xlightsBeta

As it stands you could not install xlights4 and xlights5 at the same time

**Comment by AzGilrock** [comment]
For one we don't have an xlights4 anymore our versions are numbered based on year like 2016.22.  Also I have 8 versions installed on my machine currently so you're last statement that you can't install 2 versions at the same time isn't true.  I'm not sure where this comes from so I don't know which part of your post is actually changed from what we currently have.

**Comment by damon-atkins** [comment]
In Powershell you can do
gp -Path HKLM:SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\<AppID>
e.g.
gp -Path HKLM:SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\xLights_is1

When you installed the product it creates a registry entries i.e. AppID  as you do not change AppID you will only ever have one listing under. "Uninstall Programs" or 
"Control Panel\All Control Panel Items\Programs and Features"

If you uninstall xlights from "Control Panel\All Control Panel Items\Programs and Features" currently it will just uninstall the last version installed.

If you want multiple installed you need to change AppID   However DisplayName should just be "xLights" not 'xLights version 2016.22'    You can tell the different versions apart with DisplayVersion which is currently being set.    Putting version numbers in DisplayName which it difficult to automate.

However if someone installs over the top of a previous version it should be uninstalled first so its registry entries are removed if using a different AppID for each install.

You can also use wildcards,   Wow6432 indicates the installer was a 32 bit app
gp -Path HKLM:SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\xLights*

64bit installers installing a 64bit program are located here
gp -Path HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\xLights*

**Comment by AzGilrock** [comment]
I don't really need an uninstaller to delete my other versions....I just delete the directories.  Anyways I'm not the one doing the installer.  There are other things that could get broken.  We use common registry entries and don't really want a new clean registry area for each version.

**Comment by damon-atkins** [comment]
It means users have installs left around, which they can only be removed deleting the directory which is not the windows approach.

Easy fix is have AppID=xLights2016.X.X  and if  a directory already exists, ask them to remove the old version first. The current install detects the existing directory it just needs to refuse to install

**Comment by damon-atkins** [comment]
Of default the install directory to have a version in its name

**Comment by AzGilrock** [comment]
Only advanced users end up with xLights installed in multiple locations anyways.   I really don't want to have the program show up with 8 uninstallers on my system.

**Comment by damon-atkins** [comment]
If its install 8 times it needs to, otherwise uses can not remove it..   I would think a lot of people would have a few version installed.   As you all ways say you want testers, or still finding bugs esp. leading up to Christmas.  People would have one stable version installed and one bleeding edge version.

**Comment by AzGilrock** [comment]
It hasn't been a problem for anyone else.  Like I said I'm not the one that would do the work anyways so you're wasting your breath arguing with me.

**Comment by damon-atkins** [comment]
Just trying to help

**Comment by AzGilrock** [comment]
Closing old issues I don't believe will be implemented.  Keith is doing the setup installs and would have implemented this already if it was going to happen.

**Comment by AzGilrock** [comment]
All the developers see every comment to all the issues here but keep hoping maybe you will wear one down.
