### ISSUE TITLE
[Crash] Setting up Models during Webinar

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#533]
I was testing the feature where we double-click to create multiple models when the program crashed.
Attached is the .zip. 
[xLights_dbgrpt-502-20160416T100653.zip](https://github.com/smeighan/xLights/files/222304/xLights_dbgrpt-502-20160416T100653.zip)

**Comment by keithsw1111** [comment]
Do you know exactly what you were doing ... it looks like you were doing a delete not drawing models.

**Comment by jholmes09** [comment]
Yes this is correct.
I was drawing multiple models using the quick-draw feature (double-click) when it crashed.
It happened really fast so I may have gone to delete one of them when the actual crash happened.

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by AzGilrock** [comment]
Can you still cause this with the latest release?

**Comment by jholmes09** [comment]
I'll try and get back to you if I run into an issue. If you don't hear from me, it's all good!

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by jholmes09** [comment]
Hello,

Yes this is still an issue. Here is the report. 


Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by AzGilrock** [comment]
Sorry but you need to better describe how you are causing the crash.  There is no "double-click" action to create models so what are you doing?

**Comment by jholmes09** [comment]
Hello,

If you double-click the icon for the type of model you want, it allows you to create multiple of that item. However, if I create multiple in fairly quick succession, then hit the delete key, it crash of the program. 

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by AzGilrock** [comment]
Ok that's what I thought it's not a double-click it's two single clicks.  We don't have an event handler for the mouse double-click event.

**Comment by AzGilrock** [comment]
Well that was even more simple than you described.  Assuming the screen had focus if you hit the Delete key any time a model was not selected it would crash.
