### ISSUE TITLE
[Crash] Undo Timings and Editing Timing Names

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#534]
[xLights_dbgrpt-1066-20160416T143632.zip](https://github.com/smeighan/xLights/files/222419/xLights_dbgrpt-1066-20160416T143632.zip)

**Comment by keithsw1111** [comment]
Can you describe what you were doing exactly. I can see it was an attempt at an undo but I have no idea what the exact context was.

**Comment by jholmes09** [comment]
Hello,

I thought I wrote it in the description but let me see if I remember…
I believe I was deleting time signatures in bulk. Then I tried to undo?

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by AzGilrock** [comment]
This was part of the crashes-a-lot thread.  We agreed to close these and open new issues when problems arise.
