### ISSUE TITLE
Importing Horizontal Matrix (.SUP) files

### ISSUE THREAD

**Issue by bluzervic** [smeighan/xLights#537]
There is a problem importing (.sup) files from superstar with Horizontal matrixes.

I have attached a (.sup) file for curse of the Ice queen for example. The 1st part of this SUP file should be music notes displayed on the matrix.

I can do a teamview anytime for debugging as well.
Rename the file back to a (.sup) file from (.txt) as I could not upload it here with the (.sup) extension.

[curse-of-the-ice-queen-v2.txt](https://github.com/smeighan/xLights/files/222788/curse-of-the-ice-queen-v2.txt)

Just make a 12 string by 50 LED horizontal matrix and import it to that model.
Lower left is the 1st LED

**Comment by stevegiron** [comment]
Worked fine for me.  The notes are image files with movement.
![image](https://cloud.githubusercontent.com/assets/10568498/14617209/3e4f413c-0562-11e6-8c7b-a7c1f20d7df4.png)

**Comment by stevegiron** [comment]
Do you have a link to what this sequence should look like?

**Comment by AzGilrock** [comment]
You said "just make a 12 string by 50 LED horizontal matrix".  That makes me question whether you set this model up correctly.  A typical 12x50 ribbon tree is a vertical matrix not horizontal.  You should define it as a vertical matrix and then number of strings=12 number of nodes per string=50.  If you wanted a similar horizontal matrix then the number of string would be 50 and nodes per string would be 12 but I don't think that will import correctly because superstar defined that tree as vertical strands not horizontal.  Pretty sure there is no bug here.

**Comment by bluzervic** [comment]
Thought I would try to clarify what I have.

1. the initial matrix is a horizontal matrix 12 strings x 50 LED (600 nodes) starting bottom left. If I import a SUP file from LOR into that matrix It does not import correctly. This model is called Matrix

My work-around is I created a vertical matrix 12 strings x 50 LED (600 nodes) starting top left. If I import a SUP file from LOR into that matrix, it imports correctly. This model is called matrix-2

The SUP file is for a horizontal matrix 12 strings x 50 LED(600 nodes) and starting bottom left.
I uploaded my XML files and the current FSEQ file and SUP file

[curse.zip](https://github.com/smeighan/xLights/files/232529/curse.zip)

**Comment by bluzervic** [comment]
Also after I import it, Sometimes, I have to tweak the offset of the notes, so they are within the boundaries of the matrix.

I do have some songs in youtube... search for bluzervic, I do not think I have this particular song

**Comment by AzGilrock** [comment]
Did you mean to close the issue?  Also have tried checking the Swap X/Y checkbox during the import.  I tried to provide several options to deal with the various ways SUP files might be organized.

**Comment by bluzervic** [comment]
No did not mean to close it
I think I tried various ways to import it but had no luck

I can try again just to be sure

Vic

**Comment by AzGilrock** [comment]
Yeah I looked and the checkbox only flips the Y axis so it probably won't help.  I'll try to look at the file today to see what can be done.  Like usual we write the code to work with the files we have as examples and all my sequences were vertical ribbon trees.
