### ISSUE TITLE
Enhancement Request: Effect Settings for DMX  enable the ability to set the Ramp Value in real time.

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#538]
I have just started testing the DMX Effects setup tab for testing a moving head light. Based on the what I heard during the Vegas classes, I created three props for the light. 

Prop 1 to set the dmx channel 6 to 255. I will place that in sequence to keep intensity of the light full (255).

Prop 2 is set to DMX channel 10. The head will be treated a s single RGB node. 10 is R, 11 is G, 12 is B.

Prop 3 is set to DMX channel 1. The horizontal movement is Ch 1, the Vertical is Ch3

So my thought for making the light move is to use the DMX effect to set the start point of the head and then use the ramp to set the end point. I can set the start point by clicking on the CH 1-9 tab. I can set the Endpoint but clicking on the endpoint tab and setting the value.  The problem is if you don't click use ramp you will not get a "Live" view of the end point. If you click use ramp the effect keeps looping so it makes it hard to fine tune the end point.

Option 1: When you click on the Ramp tab and enter values, adjust the head in real time like you do on the channels 1-9 tab.

Option 2: add a pause or no loop preview checkbox next to the "use Ramp" this would stop the effect from looping, you would see the movement once. then you can fine tune the end point.

I can create a video demo, But gill I think you have one of these heads that you can test with.

**Comment by AzGilrock** [comment]
I just use the start point tab to get my live view of the endpoint value then I set the start value back to where I want it and set the end.  It shouldn't take you very long to figure out what numbers you want to use for the various positions you will send it to.

**Comment by AzGilrock** [comment]
I think this request is satisfied with the elimination of the start and end ramp tabs and the new ability to use the value curves.  The only limitation now is you don't get real time feedback when adjusting a value curve but that should be more of a global request to the value curve operation.
