### ISSUE TITLE
End Channel refresh issue in Layout

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#539]
If I create a single line effect that is 10 nodes, the last channel is not calculated automatically when you leave the node count cell. The work around is to change the start dmx channel to something else and then change it back again.  See youtube video:
https://youtu.be/s2XIqRh1Sgo

Pat Delaney

**Comment by AzGilrock** [comment]
Yeah we knew about this one but I guess it wasn't recorded in an issue yet.  I believe it's happening with all model types.  We had several people run into this at the seminar.  Everything still operates correctly its just a display refresh issue.

**Comment by AzGilrock** [comment]
This should have been closed.  The commit that fixed this called out the duplicate which was already closed.
