### ISSUE TITLE
2016.20 Setting - Grid Spacing Issue

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#541]
2016.20   There are two issues with "Grid Spacing" but I'm guessing they are really the same issue.

I have the "Grid Spacing" for my sequences setup for "Small" which allows me to display all my models on one screen.   If I change the "Grid Spacing" to something wider, e.g. "Large", Xlights will only display the models it can fit on one page; there is no way to scroll to the second and subsequent pages.  You have to save your work, exit the application and restart it to be able to see all the models again with the "Large" setting.

The second issue is just the reverse of the above scenario.  If you have the "Grid Spacing" setup for say "Large" and it takes three (3) screens to be able to scroll through all the models and you change it to "Small", it will still take three (3) screens to scroll through all the models even though they would fit on one screen.  It only uses approximately 1/3 of the grid after switching back to "Small".  If it only displayed 10 models per screen in "Large" grid spacing it still only display 10 models per screen in "Small" even though they will all fit on one screen.

Thanks
Denny

**Comment by AzGilrock** [comment]
Your right there is a refresh issue but you don't need to exit the application to fix it.  You just need to give xLights a foot massage and it will show all the rows properly.  Just open up the Display Elements window and then close it and the rows will refresh.

**Comment by dcwehw99** [comment]
Thanks!  That took care of the refreshing of the models in the grid but revealed another issue.  

After closing the "Display Elements" window none of the menu options and their corresponding drop-down menus work unless you first click in the grid.  I'm guessing this is "focus" issue I've seen and experienced previously.

Thanks for you time and help.
Denny

**Comment by AzGilrock** [comment]
The focus thing is already logged elsewhere.  The temporary workaround for that is you need to click on another application and then back to xLights or click around the tabs in xLights.

**Comment by AzGilrock** [comment]
This is fixed for next release.  Now if I can find all the bugs submitted for the 27 ways you could cause the same bug.
