### ISSUE TITLE
Enhancement Request: Insert multiple layers option

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#542]
Just a thought.  Is there a way to add and option to insert multiple layers.  I find I add at least 10 layers to the mega tree.  Would be great to add a popup box to define how many layers to add.

**Comment by stevegiron** [comment]
+1 Finally a decent request comes in!

**Comment by stevegiron** [comment]
A different perspective would be to define number of layers within the model. Whenever you add the model to a sequence, X # of layers would be added as well for that model.

**Comment by Clyde-L** [comment]
Yes, being prompted how many layers to create would be a nice add to the model setup.

**Comment by Clyde-L** [comment]
Keith gonna have a look at this ?
 :) 
thank you !

**Comment by keithsw1111** [comment]
I'm looking ... not necessarily doing it.

**Comment by Clyde-L** [comment]
I understand :)  I just added 29 layers to a pixel tree last night.  Took a while and came to see if anyone commented on it since.  You just happened to self-assign it hehe.

**Comment by AzGilrock** [comment]
Just don't make it where I gotta deal with a dialog box to add 1 layer.

**Comment by Clyde-L** [comment]
Ok, soooo right click
shows:
Add layer
Add Multiple layers

**Comment by AzGilrock** [comment]
Yeah and if we listened to every suggestion the right-click menu wouldn't even fit on the screen...lol.

**Comment by Clyde-L** [comment]
I understand when you are talking about the sequencing screen that a smaller right-click menu makes for easy navigation.  But, we are talking about a menu that is usually only activated a few times during the sequencing process.  

I was working within LOR (gasp....) the other day and am reminded how there are waaaaaay too many options in the right-click menu.   The reality is that many of us add 15 layers to the mega tree every time we open a new sequence.  Remember I'm not the expert.  Simple is best.  And if it can be done, then I would be a happy camper.   

I'm not a noob Gil.  I know you guys put a lot of time into this.  Sometimes it is more trouble than it's worth.  I also know we frustrate the hell out of you all sometimes.  As always, I appreciate what the developers have done.  You guys rock 💃

**Comment by AzGilrock** [comment]
I never said we wouldn't do this one but I do try to keep the right-click menu as minimal as possible.

**Comment by stevegiron** [comment]
Make it intuitive like the layers tab when moving multiple models.  Shift+Right Mouse click for the win.  Keeps the right mouse click menu clean since once you add 19 layers to a model, you probably won't add another 19 to the same model.

**Comment by Clyde-L** [comment]
That is not a bad suggestion Steve.  I appreciate the minimal right-click menu now that I'm used to it.

**Comment by keithsw1111** [comment]
Agreed Gil ... adding one layer should not require a dialog box. I am also conscious of the number of right click menu items.

What about this as an idea ... in excel if you want to insert multiple columns you first select several columns then you click insert and that many are created ... so what if you selected cells across several rows and I used that as a hint as to how many rows to create?

**Comment by AzGilrock** [comment]
I'd just add the Insert Multiple Layers option to the menu.

**Comment by Clyde-L** [comment]
I kind of Like Keith's idea.  I am very used to selecting multiple rows  when inserting additional rows in MS Excel.  That truly is the simple way to do it.  But, I realize that is not intuitive to those users who don't use Excel.  I believe that Gil is right, an addition to the right-click menu is best.  Would be nice to have both options.  

Heck, even a shortcut key would do nicely! :) it doesn't have to be a mouse click that does it.  Perhaps this:
Ctrl + i  

That could work for me.  This could auto insert 1 layer
Ctrl + m 
Could serve to bring up a dialog box, then type a number of layers for the model.  
Keeps that menu exactly the way it is 🎯

**Comment by stevegiron** [comment]
Clyde, you don't have a sequence template with all your desired models each with X layers in it?

**Comment by keithsw1111** [comment]
I ended up adding an insert multiple layers below option to the right click menu. If you want to insert them above then you need to insert 1 above and then insert multiple below that ... this means I can add only one item to the menu.

**Comment by Clyde-L** [comment]
Steve I do not.  Was not aware a template could be saved?  :)

Keith thank you for looking into this.  Just one option is all I needed, it sounds intuitive.  I look forward to the addition, it is an enhancement that many are looking for.
