### ISSUE TITLE
Enhancement Request: Effects assist update

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#543]
Is there a way to use the effects assist screen with other effects such as On, "Single Strand, or Curtain?  Would be nice to layer different effects into smaller areas on my mega tree.

Thanks for reading
Clyde

**Comment by AzGilrock** [comment]
I was going to use it for some of my other effects but hadn't planned the ones you mention.  It's only able to modify parameters that already exist in the effect and you sound like your talking about new features that don't exist.

**Comment by Clyde-L** [comment]
Is this something that could be added to the other effects Gil?

**Comment by AzGilrock** [comment]
I think what you want is to be able to scale and offset an effect.  Kinda like what you will find in the controls for my Marquee effect.  We wouldn't necessarily use the Effect Assist to accomplish that.  There's been discussion about a global X/Y positioner and scaling but I find downsides to that also.

**Comment by AzGilrock** [comment]
This is actually implemented now but not with Effect Assist.  Dan added the new sub-buffer capability where you can limit an effect to a smaller part of the model using a drawing area he added to the Layer Settings dialog.  So I'm closing this one out.

**Comment by Clyde-L** [comment]
Cool  Thanks! :+1:
