### ISSUE TITLE
2016.21 Picture Effect Not Working

### ISSUE THREAD

**Issue by Phrog30** [smeighan/xLights#546]
Working picture effects no longer work in 2016.21 until something in the effect is changed, possibly acting like a refresh.  I went back to 2016.20 and the picture effects work correctly.  I didn't see any other effects that didn't work.  My image files are stored in MyDocuments within a xlights folder I created, they aren't in the show directory.

I tried 3 different sequences, all worked prior to 2016.21 and all had issues.  The effects don't even work in the model preview.  I would toggle scale to fit, then they would start working.

James

**Comment by AzGilrock** [comment]
Fixed by my last commit.  Didn't know this issue was here at the time.
