### ISSUE TITLE
Write a new papagayo font end to replace papagayo

### ISSUE THREAD

**Issue by smeighan** [smeighan/xLights#55]
write a replacement for papagayo

**Comment by djulien** [comment]
Does this refer to replacing the XML handling front end (Papagayo tab) from xLights 3.x, or is the intention to also include the core Papagayo functionality so that Papagayo itself is no longer needed?

**Comment by dpitts** [comment]
The ultimate would be eliminate the need for Papagayo by having a complete editor. Make it better in the rewrite to remove Papagayo's shortcomings.

**Comment by gerry4** [comment]
I heard on one of the recordings (if i heard correct) Sean say that he would be working on the Papagayo tab/functionality in Aug this year . Is that still on the cards and if so what is being planned to be done ? 
If not on the cards , no problem , I'll work with what is there now which is a tad time consuming, but depending on what is being planned , I could wait and save lots of time and effort. for example if for coro faces , the conversion /import made it editable On effects , one could then move , copy and paste and do tons of stuff quickly in xl after doing the basics in pg for voice 1.

**Comment by stevegiron** [comment]
Yes, that is what he said at the Expo.

**Comment by gerry4** [comment]
And I just went on fb after that and saw Gil indicate that he was doing something that sounded that it was in this area ! 
xLights absolutely rocks !


Gerard
 
Date: Fri, 24 Jul 2015 21:00:29 -0700

**Comment by stevegiron** [comment]
Can this be closed?

**Comment by gerry4** [comment]
Yes - definitely  

Gerard
 
Date: Thu, 13 Aug 2015 23:19:56 -0700
