### ISSUE TITLE
2016.22 Grid/Waveform re-position Issue on Restart/Replay

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#550]
2016.22
1. Play a sequence and let it scroll beyond the first screen and press the stop button or space bar. 
2. If you press the "Play" or "Replay Section" buttons or press the space bar to restart the playing of the sequence, the grid and waveform are not refreshed to the corresponding start location for the replay.  The grid and wave form stay on that ending screen. You must manually re-position to the start of the sequence.

Thanks
Denny

**Comment by stevegiron** [comment]
That only happens to me when my system is low on memory.

**Comment by dcwehw99** [comment]
Both my desktop (16 GB) and laptop (6 GB) do the same thing.  I went back to 2016.14 and it did it back then too.

Denny

**Comment by stevegiron** [comment]
xLights is a 32 bit app and can only address 2GB of memory.

**Comment by dcwehw99** [comment]
Always happens even immediately after opening a sequence without any changes.  I just tried creating a new sequence with only one model and one effect and it happens so for me size or number of changes doesn't matter.

What release are you running?

Denny

**Comment by stevegiron** [comment]
I install each release to a different folder so I can troubleshoot if need be.
![image](https://cloud.githubusercontent.com/assets/10568498/14872034/02436578-0c9d-11e6-8063-bfd20a5f1018.png)

**Comment by AzGilrock** [comment]
Not sure what Steve is seeing because I don't think we have it coded to jump backwards on repeat or if you hit play and the start marker is off screen backwards.

**Comment by AzGilrock** [comment]
Just click in the waveform to set the start marker.  Then scroll forward to put the play marker off screen on the left and then hit play.  It doesn't adjust the scroll to show where the play marker is playing you have to wait till it rolls on screen.  Might be something we should fix.
