### ISSUE TITLE
"Single Color" Model Group Issue with White

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#551]
2016.22
I have a four (4) color mega-tree that is made up of 12 (50 node) strings each of red, green , blue and white, i.e.they are single color AC strings.  I have defined four(4) 12 string "Single Color" models; one for each of the four colors.  I have defined a "mega-tree" model group made up of those four (4) models.

Here's the problem I'm having.  If I drop a red "On" effect onto the "mega-tree" model group, the tree shows as red.  If I drop a green "On" effect onto the "mega-tree" model group, the tree shows as green.  If I drop a blue "On" effect onto the "mega-tree" model group, the tree shows as blue.  But when I drop a white "On" effect onto the "mega-tree" model group, the tree shows as red, green blue and white; i.e. all four (4) models are turned on not just white.  It's the same as though no color has been checked in the "Color" window and you drop the "On" effect onto the "mega-tree" model group.  If  I drop a white "On" effect onto the White mega-tree model itself, the tree shows as white.  It's only when you drop it on the model group that you get all the colors.

Thanks
Denny

**Comment by stevegiron** [comment]
What is white?  It is the equal combination of 255 RED, 255 Green and 255 Blue. This is why white will turn on RGB defined strings.  What happens when you change the order of the model group vs the model in the sequencer?

**Comment by dcwehw99** [comment]
The model is defined as a "Single Color" model with the string color of white versus a RGB string in its properties.  But that brings up a good point, white is a combination of red, green and blue.  I hadn't thought of that.  I only have the model group for the mega-tree defined in the sequence with none of the four (4) model so there's no changing the order.  I'm trying to stay at the model group level and drop effects on the model group versus the models if at all possible.  

So I did a little more experimenting with more than one color selected for the "On" effect and see that's what's happening isn't what I was expecting.  I thought that since each of the four models was defined as a "Single Color" that whenever you turned on one of the colors the string matching that color would be turned on.  Not so!

If for example you check red and green for the colors, only the red string is turned on.  Turns out only one color is turned on at a time for the colors red, green and blue in that order if you use a model group.  White happens to turn them all on.

Looks like using a model group for "Single Color" string may not make any sense.

Denny

**Comment by stevegiron** [comment]
Here's a video I did for that minus the white. https://www.youtube.com/watch?v=5wUCA_gqrCs

**Comment by dcwehw99** [comment]
Aha!  I see you did a custom model where I used the "Tree" model with a string type of "Single Color".  I was trying to get a view of my tree similar to what it really looks like.

Denny

**Comment by AzGilrock** [comment]
Nothing to fix here this is just how a model group is going to work when a color is dropped.  In fact if you dropped Orange on the group it will fire the red and the green at partial brightness.  I believe a string defined as white will only fire when all 3 components are equal R=G=B.  So you really can't combine a White with an RGB in a group and expect white colors to not affect the RGB.

**Comment by dcwehw99** [comment]
Agree!
