### ISSUE TITLE
Copy Row doesn't select correct row

### ISSUE THREAD

**Issue by uzelessknowledge** [smeighan/xLights#553]
I'm trying to copy an entire row from one model to another. When I right click on the model I want and select copy row the row that I'm on isn't selected. You can see it selects some other row. 
Mac OSX 10.11.4
XL 2016.22-OpenGL3.
Video here: https://www.dropbox.com/s/1fc33a14hjxg07x/Copy%20Row%20issue.mov?dl=0

**Comment by stevegiron** [comment]
What happens when you paste that row to another row? Do you get the desired output?

**Comment by uzelessknowledge** [comment]
No, I get the row that was highlighted in purple.

**Comment by AzGilrock** [comment]
The vertical scrolling is messing it up.  I know I fixed that same bug once before.

**Comment by AzGilrock** [comment]
Hmm well I can't find any evidence of a checkin fixing this before but I know I've seen it and though it had been corrected but I guess not.
