### ISSUE TITLE
Prompt to save mapping file 

### ISSUE THREAD

**Issue by smeighan** [smeighan/xLights#554]
If I have a mapping file, save 20 models. Come back in add 40 more models and forget to press save mapping file , if i press OK i lose all the 40 mappings. Please have the program prompt to save the mapping file before executing the OK prompt.

**Comment by AzGilrock** [comment]
Aren't you supposed to be in a webinar? :)

**Comment by keithsw1111** [comment]
Will be fixed in 2016.33
