### ISSUE TITLE
CTRL+Z Question?

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#556]
I don't know if this is by design or not but the way the CTRL+Z works today it updates the grid view each time you press the CTRL+Z but the "Model Preview" and "House Preview" are not updated until you press the "Render All" button. 

It would be nice not to have to do a "Render All" after each CTRL+Z to get the previews refreshed.

Thanks
Denny

**Comment by AzGilrock** [comment]
Yes it's so the program doesn't run slow.  You probably don't realize we would have to render every model for each timespan affected.  We don't have anything that links which models and groups are affected by changes to other models considering that a model's channels can exist in any number of other models and groups and their is the render heirarchy to consider.  The preview is really never guaranteed to be up to date unless you do a Save or Render All.  Just click on an effect for a model group and then click an effect for a single model within that group.  The first click will erase the effect in the single model until to click on that effect assuming you have the group higher in the render order.

**Comment by dcwehw99** [comment]
Thanks for the information and feedback.

Denny

**Comment by AzGilrock** [comment]
I'm going to close this one.  It can't be fixed unless we do a major overhaul of the engine where we always keep the entire render buffer up to date.  If we do an engine upgrade like that it will automatically fix this so I don't think we need an open issue hanging around for this.  If we did it should be an issue titled something like.  "Automatically keep the render buffers up to date" and would need to be accomplished with background threads kinda always doing some work to keep them up to date without interfering with the user so it wouldn't be immediate feedback.
