### ISSUE TITLE
2016.22 Text Effect Setting Position

### ISSUE THREAD

**Issue by Phrog30** [smeighan/xLights#557]
When entering the start and end positions in the numeric entry box, it will only allow 3 characters.  This is a problem when entering a negative value as the sign counts as a character.  So, a value of -100 is not possible.  The slider does work correctly.  This is a very minor issue.  This may be a global issue across other effects with similar settings, I noticed the picture effect is the same.

Thanks,
James

**Comment by stevegiron** [comment]
James
The text effect is on the radar to get modified. The 4 layers of text was originally introduced with xLights 3.x to effectively get around the 2 effect limit per timing mark. Now that we have layers, 4 lines of text in a single effect is not needed.

**Comment by Phrog30** [comment]
Not sure what you are referring to... effect limit per timing mark.  I 
was simply stating about position setting.

------ Original Message ------

**Comment by AzGilrock** [comment]
Ok I'm fixing this for the Text effect. Its probably only an issue for parameters that can go negative but it's on a case by case basis.  The developer who created each effect types in the size for the text box so I believe this was considered in some places and maybe not others.  Point being I not going to look through every setting on every panel. It will be easier to just let the users report it when they run into one.

**Comment by Phrog30** [comment]
I understand, thank you sir.
