### ISSUE TITLE
xLights running idle dies

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#558]
I have to say it's always been like this with version 4.x, I have finally captured what it looks like.
New PC with xLights, Notepad++ and Google Chrome as the only installed apps. When leaving xLights idle for a couple of days, (sometimes just for a day) it will render useless and have to be terminated via task manager. 

![image](https://cloud.githubusercontent.com/assets/10568498/14986619/8c24427c-1101-11e6-9bb7-d7003eb8e9d0.png)

**Comment by AzGilrock** [comment]
Not sure what I'm seeing in the photo.  Was there a sequence open?  Have you ever watched memory usage to see if it continues to go up?

**Comment by stevegiron** [comment]
Will reopen when I gather more info.
