### ISSUE TITLE
2016.23 Starting/Ending Point of Effect Missing in Grid

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#560]
2016.23
The starting and ending point of an effect is no longer visible in the grid.

**Comment by AzGilrock** [comment]
The program was modified to start using newer OpenGL 3 features.  We've been talking about and working through all these display issues all day yesterday.  There is already a probable fix completed.  No real need to log every little display thing you are going to see in these beta versions.  This isn't the kind of problem that goes unnoticed and forgotten about.
