### ISSUE TITLE
[Bug] start channel to be specified in #:# notation and multicast

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#568]
4.0.33  May 23, 2015
   -- enh(dkulp) Allow start channel to be specified in #:# notation where first part is the output and the second is the offset from the start of that output.  So 3:1 is the first channel of the third output.

It appears this does not work in multicast.
e.g. in setup define 200 multicast universe for output and then use 3:1 format.

Swap to unicast and it works.

Thanks

**Comment by AzGilrock** [comment]
And how do you know it's just not multicast that's not working for you?  It would have been better to leave it on multicast and switch to absolute channel numbering.  Data transmissions don't have anything to do with how the start channel is defined.

**Comment by damon-atkins** [comment]
Any progress on this. Or is it a MultiCast "The User" issue?

**Comment by AzGilrock** [comment]
The problems that need hardware to be hooked up don't get looked at quite as fast.  Also you didn't say what type of playback method isn't working.  Are you just clicking on an effect to preview it?  Are you playing the sequence while on the grid?  Are you running it in the scheduler?  Are you downloading the file to FPP?

**Comment by damon-atkins** [comment]
It was a new seq, with one item a matrix. Not starting at universe 0 and using multicast.  It happen during the Christmas Mini several months ago.  The matrix did not display correctly on the P10s.   Changed to uni-cast and it worked fine.

**Comment by AzGilrock** [comment]
That doesn't tell me which of the 4 playback methods you were using but nevermind.

**Comment by damon-atkins** [comment]
Direct from X-Lights to Ethernet

**Comment by AzGilrock** [comment]
It probably doesn't matter but there are 3 different ways to play an effect from xLights.  You can click on the effect in the grid.  You can play the sequence on the grid.  And you can save and play the sequence from the scheduler.  That's what I was getting at but when I look into it I'd just pick one and see what it does.

**Comment by damon-atkins** [comment]
The definition for the multicast was one large one of several universe.    If you did unicast you would have several definitions one for each IP target.    Is the maths done differently.  Unfortunately everything is packed away.

**Comment by keithsw1111** [comment]
Can I close this issue?

**Comment by damon-atkins** [comment]
I will re-open if still an issue

**Comment by damon-atkins** [comment]
Thanks
