### ISSUE TITLE
Enhancement request: Add rotation movement on picture effect

### ISSUE THREAD

**Issue by Phrog30** [smeighan/xLights#569]
Is it possible to add an option movement for rotation around a specific point on the photo?  For example, to have the photo rotate around the center point, kind of like vector, but rotate instead.  Thanks for listening.

James

**Comment by kppankratz** [comment]
Wasn't Sean working on RotoZoom at one point this year?  I was under the impression that could do something like this (based on reading up on the subject).

**Comment by Phrog30** [comment]
I remember hearing about it, but that's it. Not sure. I thought it would be
cool to still use the picture effect, but just have another motion movement
option.

James

**Comment by stevegiron** [comment]
You have it, it's called Glediator. Use Glediator (it has the rotozoom function) to do it and import that output with the Glediator effect.

**Comment by Phrog30** [comment]
My enhancement request was for something native to xlights. Of course,
Steve, we can import from 3rd party apps. This is a request. Feel free to
act on it or not, I'll be fine either way. But Steve, your response is in
no way helpful.

I've read some of your previous requests over the years, so not sure what
you are trying to do.

James
On May 15, 2016 5:40 PM, "stevegiron" <notifications@github.com> wrote:

You have it, it's called Glediator. Use Glediator (it has the rotozoom
function) to do it and import that output with the Glediator effect.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/smeighan/xLights/issues/569#issuecomment-219315491>

**Comment by stevegiron** [comment]
Just trying to help. If you really want to have an image rotate in a sequence, there's a way to do it now before this new feature is implemented.

**Comment by Phrog30** [comment]
My goal is to help make this software better. Since my high level coding
skills are poor, my only valid contribution is to make suggestions and help
others. I submitted this request because I thought it would be useful. Then
if someone asks, how do I rotate a picture, the effect is already there,
instead of saying, use glediator.

I'm well aware of glediator and other 3rd party apps. Thanks for the
reminder.

James

**Comment by AzGilrock** [comment]
Adding the code is pretty easy.  The heartburn is figuring out where to provide all the settings on the effect panel since it's kinda clutter already.  Especially if we let you define the rotation center point as well as rotation direction in addition to the start and end angles.

**Comment by Phrog30** [comment]
I understand. It was a thought. If you guys think it would just clutter
things then I completely understand.

**Comment by keithsw1111** [comment]
Roto-zoom will be in 2016.34.

**Comment by kppankratz** [comment]
Compiled and played with this feature.  Nice enhancement.  One issue I noticed is that if you manually type in a value into the properties window and click OK, they do not get saved.  Open the properties window up again and the values are back to where they were.  Adjusting the values with the sliders do work as expected.

**Comment by Phrog30** [comment]
Awesome, I look forward to playing with it. I'm not familiar with the
rotozoom effect, can it rotate an image without the image being tiled?

Thanks Kevin for your work.

James

**Comment by keithsw1111** [comment]
Kevin. Fixed I think. I have also made values more sensible for what they do.

**Comment by kppankratz** [comment]
Thanks Keith.  I tried to compile but it failed, so I will have to wait for Dan to fix the Mac build before I can test again.

**Comment by AzGilrock** [comment]
Probably best to wait anyways.  We had some news ideas so it's going to change a little.
