### ISSUE TITLE
Enhancement Request: option to duplicate effects on model groups

### ISSUE THREAD

**Issue by BoonDogs** [smeighan/xLights#570]
When placing an effect on a model group, is it possible to have an option appear, to either:
1) To have the effect duplicated on every model in that group
2) Render the effect across all the models

Example: drop the butterfly effect on a model group, and all the colours either flow across all the models, or each model has the same colours on it.

Thank you

**Comment by AzGilrock** [comment]
This is a duplicate of #392. Closing.
