### ISSUE TITLE
Bug...Adding a model to sequence

### ISSUE THREAD

**Issue by Lightaholic** [smeighan/xLights#571]
Basically, have 1 model, started new musical sequence, added timing, select add model...debug report.
I've tried all 3 Open GL's with no luck. 
May have to do with my display driver..just didn't know for sure.
Driver is Intel(R) HD Graphics 3000

[xLights_dbgrpt-8432-20160514T215509.zip](https://github.com/smeighan/xLights/files/264803/xLights_dbgrpt-8432-20160514T215509.zip)

**Comment by AzGilrock** [comment]
I can't think of anywhere that we have a button or option called "add model" so I don't know if you mean you are on the layout page adding a model or you are in the Display Elements screen hitting the Add button.  If it happened when you clicked a button its probably not an OpenGL issue.

**Comment by Lightaholic** [comment]
Sorry for the confusion, It was on the Display Elements screen when I hit the Add button. I was at LUO this weekend when it was happening. New install of 28 at the time. A few guys there told me to try the OpenGL because of the display issues with others. I myself don't know anything about it at all. They just said to post it here. I have since loaded several different versions including the Production Release with the same results.
Thanks

**Comment by AzGilrock** [comment]
I tried your setup and I can't get it to crash.  I do notice you have a model called "Tree" and a model group called "TREE" that contains no models.  I would first delete that "TREE" model group because you don't need it and that will make sure you don't get confused and accidentally try to use it.

**Comment by Lightaholic** [comment]
Even being new to xLights, I sequence just fine on my desktop. That's why I figured it may be with the display card. I took this computer to LUO and Renn & Clyde both saw this happen time and time again. That's also why I just had 1 model and a simple timing. Sometimes I can add the model before it crashes...sometimes it crashes once I click Edit Display Elements. I'm at a loss, just wanted a secondary computer to sequence on when out of town. Thanks for any help. 

Btw, I completely uninstalled xLights and reinstalled again...new release .32 with the same results multiple times before I added the file below. Sorry to be a pain...

[xLights_dbgrpt-3476-20160519T221818.zip](https://github.com/smeighan/xLights/files/273779/xLights_dbgrpt-3476-20160519T221818.zip)

**Comment by AzGilrock** [comment]
Any chance you could capture a session with screen capture so we can see all your steps that cause the crash?  Sometimes there is just one little thing you are doing that's different than how we do it that can cause it.  I've seen this several times where I go back and forth with someone and then I see a picture or video and I notice something clear as day that's causing it....but not always.

**Comment by Lightaholic** [comment]
I did get it to add a model the other night by quickly saving the sequence before it crashed, but as I reopened it and added another model...crashed again. 

So, I uninstalled xLights and deleted all files and started from scratch with a fresh install of 2016.32 I hope I did this right...it's my first screen recording.

[xLights model add.zip](https://github.com/smeighan/xLights/files/278589/xLights.model.add.zip)

[xLights_dbgrpt-8800-20160523T211438.zip](https://github.com/smeighan/xLights/files/278580/xLights_dbgrpt-8800-20160523T211438.zip)

Thanks for any and all help.

**Comment by AzGilrock** [comment]
So in that video it crashed when you hit the red X.  Is that always when it crashes?  When that panel is closed it calls the SetFocus() function which is supposed to make sure the focus is set back to the application because it used to jump to other applications.

**Comment by Lightaholic** [comment]
Like I mention in the video, sometimes I don't even get to click the add button. Sometimes it's just as I click the model itself...it varies each time. But everything works fine until I right click and hit the Display Elements...it can happen anytime once that screen opens till just after I add the model.

**Comment by AzGilrock** [comment]
Well unfortunately it doesn't sound like anything I can easily fix.  If it keeps happening at different times it doesn't sound like any of the code related to that window.  It looks like its crashing with just normal windows message routing occurring.  It could be video/opengl related.  Our whole program has gone south since those changes.  You might try docking the window instead of leaving it floating and see if that makes a difference.

**Comment by Lightaholic** [comment]
I use my desktop most of the time anyway. Thanks for looking into the issue...I'll try again with each update of the software and see if it helps.
