### ISSUE TITLE
Slight "tear" in the model preview for my matrix (since 2016.28)

### ISSUE THREAD

**Issue by JonB256** [smeighan/xLights#573]
First noticed in 2016.28 but still in 2016.31.

For an animated GIF and for Video, I'm seeing a horizontal tear (perhaps 2 or 3 pixel shift) across what appears to be the exact middle of the image in Model Preview. Changing the size of the Model Preview does not make it go away. The House Preview is fine. Just the model preview.

I have a Radeon HD 4200 card, AMD processor.

**Comment by AzGilrock** [comment]
I'm not seeing any tearing when I try a GIF.  Can you attach a picture?  Maybe it's part of the recent video card issues.

**Comment by JonB256** [comment]
Just upgraded to 2016.32 and I'm not seeing it now. It may have been refresh speed related??

**Comment by AzGilrock** [comment]
No once a frame starts drawing it doesn't get interrupted.  The refresh rate thing was just to try to make the frame rate more consistent with the target goal of the sequence.

**Comment by JonB256** [comment]
I'm seeing it again, even when I enlarge the Model Preview (which made it go away before)
Version 2016.32, Auto Select on OpenGL
![middle of model preview](https://cloud.githubusercontent.com/assets/5251235/15451492/18cecbde-1f8a-11e6-841f-46a2ddcac015.JPG)

**Comment by AzGilrock** [comment]
Well try it in version 2016.22 because that is the version before OpenGL changes.  If it happens there also we will know its not the new changes.

**Comment by JonB256** [comment]
Ok, it is still there in 2016.22

But just in a relatively small Model View window.
If I enlarge it past a certain point, it is perfect.
![large window](https://cloud.githubusercontent.com/assets/5251235/15451735/d4870608-1f98-11e6-8ada-2c48c933771c.JPG)
![small windown](https://cloud.githubusercontent.com/assets/5251235/15451736/d4872160-1f98-11e6-8853-ef11c4ed73a0.JPG)

**Comment by JonB256** [comment]
If I change the Model Appearance to a single pixel, square, instead of 3 pixels, round, it doesn't do it.

It is some kind of rendering problem, but the Full Preview never does it, just the Model. You have it labeled as a Trivial Bug and I agree. It does not affect final output.

**Comment by patdelaney** [comment]
I see this issue as well.

 

Pat Delaney
