### ISSUE TITLE
Backup feature doesn't backup the current work

### ISSUE THREAD

**Issue by tomhammond** [smeighan/xLights#578]
Hello,

I (and others) have noticed that the Backup feature only backs up the most recent save of the xLights data.  But, people assume that Backup will backup their current work (changes that occur after the most recent save).  

It would make more sense to have the Backup feature automatically perform a Save command, then make the backup.  Then the backup will have the most recent changes as well.  That's what people assume will happen, but does not.

Thanks for listening!
Tom Hammond

**Comment by stevegiron** [comment]
This topic comes up often in the training videos and is covered in the user manual. Welcome to xLights.

**Comment by tomhammond** [comment]
Hi Steve,

Thanks for the response.  I realize how the Backup feature works.  What I am trying to say is that the Backup feature could be improved by automatically saving the current layout/sequence data, then performing a backup.  That way the backup contains the absolute latest version of the show.

People use the Backup feature to create a history of changes.  That way if they make a major mistake in their show, they can restore an older backup.  But Backup does not backup any current changes to the show (before a Save is performed).  It would be nice if Backup could perform a Save, then run the Backup.

Thanks for listening,
Tom

**Comment by dkulp** [comment]
On the flip side, if I'm doing some experimental work in my sequence and I think "something isn't quite right, I better do a backup of what was there before I lose it", then the current behavior is much much better.

**Comment by tomhammond** [comment]
OK, no problem.  :)

**Comment by stevegiron** [comment]
Dan, how about implementing F9 for a quick save. This is to re-program the mentality that F10 is actually saving something when someone is sequencing. Then F10 will have more purpose of actually saving new files.  We all preach to use F10, but the fallacy is that F10 only backs up saved files.

**Comment by keithsw1111** [comment]
what if on pressing F10 rather than overwriting your saved sequence (say aaa.xml) it was to create an aaa.workingcopy.xml version and back both up? Best of both worlds ... no extra function key. Slightly harder to recover from but not much harder ... just have to open a file with a slightly different name.

**Comment by stevegiron** [comment]
F10 currently just copies all existing files with xml extension to the backup folder with current date-time as the folder name. 987 xml files and you're working on a single sequence. You get 987 files copied each time you press F10.
