### ISSUE TITLE
Waveform showing as black window

### ISSUE THREAD

**Issue by AzGilrock** [smeighan/xLights#58]
Currently there is an issue where the waveform on the sequencer grid shows as black.  We've been using a workaround where you modify your shortcut to disable desktop composition (Aero).  Apparently that's great for Windows7 but Windows8 does not have a convenient way for the user to disable desktop composition so several items do not display correctly on a Windows8 machine.  This is based on feedback from users and reading up on Aero in Windows8.

**Comment by mararunr** [comment]
Thank you for posting Gil.

**Comment by AzGilrock** [comment]
This is fixed by recent checkins.
