### ISSUE TITLE
Add ability to right click a model and break it into new models

### ISSUE THREAD

**Issue by smeighan** [smeighan/xLights#580]
Add to the right click menu in LAYOUT. "Break this model into xx Virtual models', xx would be thumb wheel choice..
New models would have same display as but would eveny divide the channels (or strings,nodes) into new models

**Comment by AzGilrock** [comment]
Does Keith new feature to break a model into sub-models satisfy this one?

**Comment by keithsw1111** [comment]
I believe it does.
