### ISSUE TITLE
Add ability to Align effects

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#581]
Add ability to match duration between X number of effects with the last effect selected being the one that all others selected align to. Once selected, create options to align start times, end times, or both start and end times. This is necessary for copying, pasting, and changing effects across multiple rows in the sequencer grid

**Comment by idleup** [comment]
The lack of ability to align effects is really starting to cause me problems in my workflow. Here is a screenshot of how I have always done it in Vixen 3. The way it works is that the last effect you select when doing a multiple select OR the effect you right click on to get the context dialog menu, is the effect that is used as the "Target" for all other effects in the selection. So if I select "Match Duration" or instance it matches all selected effects to the duration of the one I had right clicked on to bring up the context menu. 

The ones that are most important to me are:

1. Align Start Times
2. Align End Times
3. Align Both Times
4. Align Start to End
5. Align End to Start

Once you have had these alignment tools, it is very hard to sequence without them. It is great that you can currently snap to a timing mark when you first add the effect to the timeline but 90% of my effects are copied and pasted from other places in the sequence or other sequences (and timing marks are not magnetic to pasted or dragged effects) and matching duration/starts/stops is very important to keep everything synced across models.

Here is a screenshot of what I would like to see:
 
![align](https://cloud.githubusercontent.com/assets/1878658/17311177/ef560566-580e-11e6-80e3-62e7c9ea2560.png)

**Comment by AzGilrock** [comment]
It may seem simple but I've got to figure out how to handle situation like this where everything you see circled in red is part of a multiple effect selection.  How should it handle all those options in this situation?

![effects](https://cloud.githubusercontent.com/assets/2024669/17312114/5637f4b0-5805-11e6-8a43-9f53c1132a9a.png)

**Comment by idleup** [comment]
Well in Vixen 3 it would overlap the effect if one already exists in the destination location on that row. For xLights that only supports one effect per row, the equivalent action would be it would drop to a new automatically created row.

**Comment by AzGilrock** [comment]
I expect you to step up and take the blame if the Vixen guys complain we are copying them. :)

**Comment by idleup** [comment]
Actually I asked Jeff to add that functionality to Vixen last year so it would be me copying myself. One other thing that I he did that was really nice is allowing hot keys to be assigned to the align functions, it really sped up workflow. If it is not too much trouble can you do that as well?

**Comment by AzGilrock** [comment]
I got the first 4 alignment modes done last night and it works pretty cool.  I think it also accomplishes the bottom 3 alignment modes talking about "marks" because I've got it designed where you can select a timing mark as the reference effect and all the alignments will be done with respect to the timing mark.  So you can align all edges to either side of a timing effect or make the effects match the duration of the timing effect.

What does Align Start to End do if you have more than 2 effects selected?  Also not sure what the difference is between Distribute Equally and Distribute Effects.

**Comment by idleup** [comment]
Gil what you did is amazing. I have not found any bugs in testing it so far.

As for Align Start and Align End it will align all effects in the multi-selection group to the start or end of the selected target effect. I do not know the difference between Distribute Equally and Distribute Effects, those are not options I asked for or use.

**Comment by AzGilrock** [comment]
I think I've implemented all the options we need at this time for alignment.
