### ISSUE TITLE
Editing Element - Jumps to Background Image Window Clicking in Start Channel Window

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#583]
When I am editing an Element, like changing the name and then going down to Start Channel, every other time when I am editing an element and I click in the Start Channel window, it jumps to the Background Image window.

In my case I made 12 Single Line strings and was editing them to name them all the same, (IE Bay Window 1, Bay Window 2, etc)

**Comment by AzGilrock** [comment]
Looks like it was specifically code to work that way when you rename a model it unselects all models so it can fully reorganize the list and when no model is selected the background image and window properties are the defaults that display in the property grid.

**Comment by jimswinder** [comment]
but why does it do it every other time...not every time

**Comment by AzGilrock** [comment]
If you change the name and hit enter it works the same way every time.

**Comment by jimswinder** [comment]
so an extra step to have to hit enter....and even then, i don't want it to go to the Background Image...
Just seems strange to have it do that...

**Comment by jimswinder** [comment]
And now xlights is locking up after I have changed 5 Element names in a row...has done it 3 times...

**Comment by keithsw1111** [comment]
This was fixed in .22
