### ISSUE TITLE
Window Frame - No Option to Add # of Strings

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#587]
Want to make a Window Frame that has 4 Strings...One Each of Red, Green, Blue and White, but no # of Strings option in Create Window Frame like in Create New Single Line

**Comment by keithsw1111** [comment]
I am closing this. Window frame model is inherently a single string. If you want multiple strings then drop multiple single lines. Adding multiple strings to window frame would unnecessarily complicate the model.
