### ISSUE TITLE
Crash after saving layout and copy/paste

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#589]
Open xLights
Open a sequence.
Go to the 'Layout tab'.
Do a copy (ctrl+C) of a model.
Do a paste (ctrl+P) of that model
Do a 'Save'
Repeat a model copy
Repeat a paste and xLights crashes.
I was able to repeat this multiple times.
[xLights_dbgrpt-7516-20160606T184833.zip](https://github.com/smeighan/xLights/files/301511/xLights_dbgrpt-7516-20160606T184833.zip)

**Comment by AzGilrock** [comment]
Hmm.. Not sure this should have been closed based on that checkin.  If the nullptr is really what was happening then the checkin is going to stop the crash but the user is still left with the Paste not working because it will be ignored and then we will be back here with another issue posted.

**Comment by MrChristmas2000** [comment]
I'll test it with the next release, if it does not paste then I'll post another bug.

**Comment by AzGilrock** [comment]
No need.  Sean just forwarded a problem to me this morning and guess what?  It's this bug...lol.
