### ISSUE TITLE
Dragging Timing Marks

### ISSUE THREAD

**Issue by AzGilrock** [smeighan/xLights#59]
I've noticed when dragging timing marks you gotta keep your mouse pointer within the bounds of the row or it quits moving.  This makes it hard to adjust if you can't move the mouse in a perfect line.  We need to alter the code to capture the row when the mouse is pressed and then not require it to stay within the row.  Of couse we would need to be able to handle the mouse moving outside the entire grid window.

**Comment by smeighan** [comment]
this will be nice, not a blocker so i am tagging it for 4.1 release.
