### ISSUE TITLE
Enhancement to allow us to click on a node in the model preview or hose preview which then selects the line in the sequencer

### ISSUE THREAD

**Issue by EagleFIre26** [smeighan/xLights#593]
Hi I just wanted to request a feature that would allow to click on a node in the model or house preview that would then select the corresponding row in the sequencer

**Comment by AzGilrock** [comment]
I don't think we want to do this idea but I'll leave it open for a bit to let others chime in.  The problem is models can be members of several groups some of which may not be visible and I don't want to have the screen jumping around and unhiding things from a mouse click in the preview window.

**Comment by EagleFIre26** [comment]
What if it was instead a right click option with wording "Select Node
Sequence in Model" which would then open another cascading menu with the
models the node is grouped in for the user to select so only one group
opens. 

 

  _____

**Comment by AzGilrock** [comment]
And what do I do if that model isn't even in the particular View you have selected?  I don't want to automatically try to scroll your view around when the model isn't visible.

**Comment by EagleFIre26** [comment]
Not sure what language other than xml the code is written in, but if
properties are an option you may be able to create a array list for each
view built and then the list values can be the model names.  

You could then save the active view name reference it to corresponding list
and value.  This would allow you to check to see if the current active view
has the model you are trying to reach.  If not 

either a notification returns letting the user know the model isn't in the
current model or the action highlights the corresponding node in the model.
I am not a strong coder, so I am just shooting out 

ideas. 

 

  _____

**Comment by AzGilrock** [comment]
If I liked the idea I could figure out how to do it.

**Comment by AzGilrock** [comment]
I don't think we want to implement this one.

**Comment by EagleFIre26** [comment]
thank you forgot I asked.  Thought it might be a popular feature
