### ISSUE TITLE
Allow us the option pause the song in sequencer and restart without starting from the initial starting line.

### ISSUE THREAD

**Issue by EagleFIre26** [smeighan/xLights#594]
Allow us the option pause the song in sequencer and restart without starting from the initial starting line.

example
Initial starting line - 43 seconds
play 10 seconds
pause pause time is at 53 seconds 
Unpause song starts from 53 seconds not 43 seconds. 

Also It would be nice if when paused the red line would still be visible at the position the song is paused

**Comment by AzGilrock** [comment]
The playback is designed to work exactly like Audacity and everything you're asking for already works fine.  If you want to pause hit the pause button.  Then hit the pause button again to unpause from the paused position.  I see the the red line and green play marker just fine when it's paused.  Please ask for help on a forum or Facebook to confirm you have a real problem before posting an issue here.

**Comment by EagleFIre26** [comment]
Hmmm for me it dissappears when hitting pause.  And then restarts at the
initial starting line.

**Comment by AzGilrock** [comment]
Are you only hitting the Pause button to stop and restart?  Are you on Windows, Mac, or Linux?

**Comment by EagleFIre26** [comment]
Windows 7 ultimate using the space bar hot key

**Comment by AzGilrock** [comment]
Ok so did you hear me mention anything about using the spacebar?  No.  The spacebar does exactly what it does in Audacity.  1) Hitting the spacebar when play is stopped starts play.  2)  Hitting the spacebar during play stops playback (it does not perform a pause).   Trust me I've spent hours on how all that playback stuff works and it's fine tuned how we want it and it's not changing.

**Comment by EagleFIre26** [comment]
Just tried it with the space hot key vs the button.  The button shows it
staying but the hot key doesnt.  Both restart it from beginning when
unpaused if you higlight a section of the wav view

**Comment by AzGilrock** [comment]
Spacebar is not a hotkey for pause.  It works the way I just said it works.

**Comment by EagleFIre26** [comment]
Ok i guess I thought it was suppose to behave the same from a facebook
discussion earlier in the year.  Just like having a simple key to press
more easily then trying to quickly go over to button.  Since you can also
get more exact timing when you are trying to make sure your initial timing
tracks are correct.  Didnt mean to flood the issue queue I'm a software qa
analyst so it kind of comes naturally to me to record something so I dont
forget and to try and separate out requests so they can be tracked
individually.
