### ISSUE TITLE
Enhance to export the color template for each node for a custom model that can then be used for a new sequence 

### ISSUE THREAD

**Issue by EagleFIre26** [smeighan/xLights#595]
export the color template for each node for a custom model that can then be used for a new sequence 

So in this case all we have to do is mess with the eyes and mouth movements instead of restating the outline colors each time.

**Comment by stevegiron** [comment]
If you create a preset effect it will save the color palette along with that effect. Just recall the preset and you'll have unlimited color palette's to use.
