### ISSUE TITLE
Custom Hot key request

### ISSUE THREAD

**Issue by EagleFIre26** [smeighan/xLights#596]
Is it possible to create a feature that would allow us to assign our own hot keys to different parts of the program?

**Comment by stevegiron** [comment]
Yes, please read the user manual.

**Comment by stevegiron** [comment]
There are couple of hotkeys built in to the application. There are are many hotkeys by default set to the effects. You can change all of those. The user manual goes over it.  The Official xLights Facebook forum, the nutcracker123.com forums have a lot more users that can help. Github is primarily used by the developers and does not have a huge user base like the forums do.

**Comment by AzGilrock** [comment]
We aren't adding hotkeys for everything.  There are too many functions in this program to try to please the folks that don't want to touch their mouse.  Read up on the key_bindings.xml file.  The capabilities you can do with that is what you get.
