### ISSUE TITLE
Bug - Ver 35 - When an affect is assigned you are using ctrl+left click to select multiple cells that already have effects and don't click on the white square the other whole selection disappears

### ISSUE THREAD

**Issue by EagleFIre26** [smeighan/xLights#597]
Bug - Ver 35 - When an affect is assigned, and you are using ctrl+left click to select multiple cells that already have effects and don't click on the white square but instead accident click on the area in the cell outside of the white box the other whole selection disappears and you have to start all over. 

the Shift left click feature feature also appears to not work when click on the white box in order to select the affects in the cells and not the cells themselves.  I was thinking this might be useful if for instance you wanted to select the white box (affect) in a range of cells right click then choose the option to say change the color or change the affect for that range in order to make it faster, instead of having to change the color of an on affect for example for each cell.

**Comment by stevegiron** [comment]
You should create a video of this issue and narrate as you go along.  You should read the manual to understand the 5 zones inside of an effect.  Clicking each of the zones does something different. You mentioned the white box (middle) there are 2 more zones either side of the middle.

**Comment by AzGilrock** [comment]
You can already do what you're asking.  You just need to learn the program better.
