### ISSUE TITLE
Bug Ver 35 - When dragging the timing mark of a second timing track the affect timing in that timing mark do not move with it.

### ISSUE THREAD

**Issue by EagleFIre26** [smeighan/xLights#598]
Bug Ver 35 - When dragging the timing mark of a second timing track the affect timing in that timing of of the affect in the cell does not move with it.

**Comment by AzGilrock** [comment]
Ok you've hit your issue limit.  I have no idea what that description means by the way.  There are no bugs with how the timing mark movement works.  There may be a misconception in what you expected.  How long have you used the program?  It's best to get to know it awhile before you show up here posting a boatload of issues.  When I get this many issue emails from one person in one day I just start ignoring them.

**Comment by EagleFIre26** [comment]
Sorry if the wording was confusing I have included a couple photos of the
sequencer before and after the timing move showing the timing marker has
moved but the affect timing has not moved with it.  For instance when you
want to adjust the timing of a mouth movement and have already added the
affect of on,

 

I've been using it since around Feb. now.  and played around with it a
little for a couple months before starting first sequence.

 

Tim

 

  _____

**Comment by AzGilrock** [comment]
Once effects are dropped they are not connected to the timings.  Timings are only an aid to drop the effects but then the effects can be moved and resized independently of the timings.  If you watch this video you will see how to move the timings with the effects at the 1:05 mark.

https://www.youtube.com/watch?v=BBuInkYuuqc

**Comment by EagleFIre26** [comment]
Ok, thank you. I guess its more of an enhancement request then to make it
faster to move the cells over to the new timing. Using the shift + Left
click to highlight the effects in that timing column and then drag the start
or stop position for the selected range of cells.  

 

  _____

**Comment by drlucas** [comment]
Greetings, 

We've just visited a great  place  with cozy atmosphere insight, just take a look <http://tino.christianityclub.org/e7dor/3>

drlucas
