### ISSUE TITLE
Roto-Zoom preset

### ISSUE THREAD

**Issue by Phrog30** [smeighan/xLights#600]
When selecting a preset, the selected preset name doesn't show in the drop down list.  So, we don't know which one is currently selected.

**Comment by AzGilrock** [comment]
I think it's working the way we wanted it to.  You just use it as a helper to set the sliders for people that can't figure out how to set the sliders.  The name in that combo is not saved anywhere.  It works the same way as my Morph Quickset combo.  I don't leave the combo to the name you select.

**Comment by Phrog30** [comment]
Ok.

**Comment by AzGilrock** [comment]
I'll let Keith decide but the only thing I could see happening is you set the selected value but you'd need to blank out the field if anything was touched that made it no longer equal to the preset.

**Comment by Phrog30** [comment]
I agree. It would have to reset if something was changed. I wasn't
thinking, you can delete the issue if you want.

**Comment by keithsw1111** [comment]
This was deliberate. It is a shortcut to help people get the settings right ... It is not a permanent state.
