### ISSUE TITLE
Crash when changing sequence time

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#603]
[xLights_dbgrpt-849-20160620T182852.zip](https://github.com/smeighan/xLights/files/324425/xLights_dbgrpt-849-20160620T182852.zip)

**Comment by AzGilrock** [comment]
So it crashed because you changed the sequence length while it was rendering.  So you need to figure out how you got into that state because the Sequence settings should have been greyed out to not allow you to change it while rendering.  Are you using any new autosave features?

**Comment by jholmes09** [comment]
Hello,

If I am, I'm not aware of it. 
I downloaded the latest version and did not change any of the default settings. 

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by AzGilrock** [comment]
You didn't know you were rendering?  Its all in the xlights_l4cpp.log file.  We can see a lot of what you do and when you did it.  You opened a sequence and then started rendering it 21 seconds later.  Then the sequence length was changed in the middle of the render.  That it bad because its unallocating memory that is being written to by the rendering.

**Comment by jholmes09** [comment]
Sorry, what I meant was I did not know if I was using any auto save features. 

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by AzGilrock** [comment]
Well I don't think the new autosave that will render is released yet.  I can see in the log it did a quick autosave while it was rendering.  That should probably be locked out although not sure why it would be a problem.  Looks like we lockout the autosave if you hit the Save button but not if you hit the Render All button.  Still not sure how you were able to bring up the settings.  Almost like an event got lost that messed up the program state.

**Comment by jholmes09** [comment]
Yeah, my whole system has been acting very strange. I'm running 5,440 pixels on a custom map and the effects are slow to update both in the preview and live. The system is taking forever to save a simple 30 second sequence. It's all very odd. 

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents
