### ISSUE TITLE
Enhancement Request: Add ability for matrix models to maintain aspect ratio

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#606]
When in Layout and creating matrix models I would like the ability for the model to "snap" if that is the right term, to the correct aspect ratio. But we should allow the user the ability to resize with out maintaining the correct aspect ratio.

For example if I have a matrix that is 400 x 300 pixels, when I draw it I want it to be 4x3 ratio. If I choose to squish it to 3x3 that's fine, but I would like a way to snap it back to 4x3.

If this is in there I apologize for not knowing.

Pat

**Comment by kppankratz** [comment]
There is a check box to maintain the aspect ratio on the Video Effects Settings window.  The Pictures effect (if you want to use the ffmpeg option for video) has a scale to fit option.

**Comment by patdelaney** [comment]
I’m not talking about the maintaining the aspect ratio of the video in the matrix. I was referring to actually drawing the matrix model on the layout screen in xLights. I want the model to maintain the correct proportions when placing it on the layout.

**Comment by AzGilrock** [comment]
So Pat I was looking at this since I had assigned it to myself.  How do I determine the "correct" aspect ratio?  What if I have a 32x42 matrix like I do?  Or a 12x50?  Is "correct" assuming equal horizontal and vertical spacing?

**Comment by AzGilrock** [comment]
I implemented this by adding a right-click option to fix the ratio of a matrix.  It will take the smaller distance between pixels and make it equal for both height and width.
