### ISSUE TITLE
Spiral Tree/Node Spacing

### ISSUE THREAD

**Issue by bwinter1** [smeighan/xLights#608]
I've created a Round (Spiral) Tree: 360 Deg, 1 String, 150 Lights/String, 4 Spiral Wraps.

It appears that the LEDs are spaced differently at the top versus the bottom (LEDs are spaced further apart at the bottom, but are much closer at the top of the spiral).

I think this is also a noticeable factor when I run basic chaser-sequence.  The chase appears to run faster through the broader-spaced LEDs, and runs slower through the close/dense-spaced LEDs.  I would assume that this spacing is important for other effects as well.

**Comment by keithsw1111** [comment]
Dan has fixed this.
