### ISSUE TITLE
Importing (.lms) to xlights causes runtime errors and exceptions (v2016.38)

### ISSUE THREAD

**Issue by bluzervic** [smeighan/xLights#610]
error: This application has requested the Runtime to terminate it in an unusual way (for example)
Xlights then terminates no crashfile

unfortunately the lms file is too big to attach here

**Comment by AzGilrock** [comment]
I created a folder for you to upload the files:
https://www.mediafire.com/folder/ach7q4deiiax9/Bluzervic

I'll need the xlights show directory files also unless they are the same as the last ones I got from you for the superstar import issues I debugged.

**Comment by bluzervic** [comment]
tried to add zip file and it does not work or I am doing something wrong

Instructions ?

**Comment by AzGilrock** [comment]
I don't know what it looks like for you.  For me I just get a page where I drag and drop the file.  All I know is I created another folder like this last year and ShellZ unloaded her stuff to it.  Just saying "it does not work" doesn't give me much insight to help.

**Comment by AzGilrock** [comment]
Ok going back through older issues now.  If we can't get this file somehow then I'll have to close this.  I provided a drop box area as one option.  If you can't figure out how to put something there trying using Google for advice.

**Comment by keithsw1111** [comment]
Can I close this issue

**Comment by keithsw1111** [comment]
Closing due to no followup.
