### ISSUE TITLE
Bug: Perspective crash

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#613]
If you select a perspective to load without having a sequence open, xLights will crash.

**Comment by cjd** [comment]
Which platform is this on? (ie: windows/linux/osx)
I gave it a test on linux and was able to load various perspectives with no sequence loaded

**Comment by kppankratz** [comment]
OSX 10.11.5

I always have to load a perspective when I open xLights too, even though the perspective is properly saved within the xml file.

**Comment by keithsw1111** [comment]
Can you please post your crash dump so we can see what is going on.

**Comment by kppankratz** [comment]
No crash report is generated, but I do get the debug alert window.  Not sure if the package files will help, but I've included them here too.

![untitled](https://cloud.githubusercontent.com/assets/12144876/16601277/3ae7fc62-42d1-11e6-930f-3a07f51b01f8.png)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/348712/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
Lots of different crashes here. Need to look into the code and try out your files to see if I can reproduce or at least protect ourselves from crashing.

**Comment by keithsw1111** [comment]
I have added some checks in v40 that may log some additional info to help us understand why this fails. Please retest when v40 is released and post us your logs again.

**Comment by kppankratz** [comment]
Once Dan is back and has a chance to fix the Mac build, I will compile a new version and check this out.

**Comment by kppankratz** [comment]
I compiled the updated code now thanks to Dan.  Same thing, but I can shed a little more light on this.  Selecting a perspective under setup, layout or schedule on a fresh launch of xLights will cause the crash.  Once I switch to the sequencer tab, then a perspective can be selected while on any of the other tabs without issues.  Bottom line, I can't try loading my saved perspective until I switch to the sequencer tab at least once.  Although I'd like to know why I always have to load my perspective on each launch, even though it is saved correctly in the xml file?

I can leave this open for a eventual fix, or close the ticket since it's mostly operator error.

**Comment by AzGilrock** [comment]
How do we know the perspective is saved correctly?  There have been plenty of bugs along the way that can mess them up.  Have you totally deleted and recreated/saved it?

**Comment by kppankratz** [comment]
Yes, the perspective is saved properly and I recreated it after deleting that section of the xml to verify that my problem still exists.  I really think this is a Mac only issue, very possibly only my Mac since I haven't seen any other comments on the forum.  I don't experience this when using a duel monitor set up under Windows.
