### ISSUE TITLE
Butterfly effect lower left pixel always red but now a diagonal line stays red too.

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#616]
I have seen this before that the lower left pixel in butterfly remains red. But now with ribbon matrix there is a red diagonal line on the left side.  The matrix is 16 high x 256 wide. I will have it at the expo. See the Youtube demo. This may be know already.
https://www.youtube.com/watch?v=I5c08JLkc9U

Pat

**Comment by AzGilrock** [comment]
That's just the way Butterfly was designed to work.

**Comment by AzGilrock** [comment]
Technically its not always red.  See attached image.  You can change the palette.  But the diagonal alone the line I circled in yellow will always be the same color unless you pick one of the other styles.  The question is why do people think the pattern needs to move?  That's the algorithm that Sean created and it's been that way all along.
![butterfly](https://cloud.githubusercontent.com/assets/2024669/16718268/548f6528-46d3-11e6-8509-094a9140db8e.png)

**Comment by stevegiron** [comment]
I reported this to Sean a couple of years ago when I had only a few strings
of lights and the first pixel was always red. I thought I had a bad pixel
until it worked fine with other effects.  Sean sent me the math source for
the butterfly and indeed the same color is always used for the bottom left
corner.

**Comment by AzGilrock** [comment]
You can always zoom and rotate it if you want to see more variety.

**Comment by patdelaney** [comment]
I’m ok with it knowing the explanation, I just never really noticed it before.
