### ISSUE TITLE
Initial undocking of a window defaults to a minimized size

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#617]
Here's the first undocking of the effect assist window.

![image](https://cloud.githubusercontent.com/assets/10568498/16711797/0e7ec976-4623-11e6-8e29-80ad31e6076c.png)

It does this on each version for only the first undocking.  Windows version for the reporting.

**Comment by AzGilrock** [comment]
Yep I see that all the time.  Never took the time to dig into how to fix it because its not inside our code its a 3rd party library that handle those windows.
