### ISSUE TITLE
Enh: Ability to expand Display Element / Model space in sequencer tab

### ISSUE THREAD

**Issue by nmiller0113** [smeighan/xLights#618]
In the sequencer tab to the left of the sequencer space where the models/display elements are laid out, I noticed that the names of some of my models are getting cut off.  Some of them have longer names, not super long, but I can no longer read the end of them as it is cut off.  I have a few models with similar beginnings and are differentiated at the end so this is a bit of a nuisance as I've got to go into the Edit Display Elements screen to see what is actually selected.  I understand that I can shorten the names but I do enjoy having the detail if possible.  So my enhancement request, if the effort is worth the return to the development team, is that you could make it possible to grab and stretch that space to accommodate longer names so they aren't cut off...just as you would be able to do in a spreadsheet to expand a column or cell.  I hope that request makes sense.

**Comment by keithsw1111** [comment]
The names now pop up in a tooltip if they are too long.
