### ISSUE TITLE
Layer transition modes square and circle explode - implode

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#622]
Square explode and circle explode actually implode unless you chose the reverse option. 
We consider an outward growing shape to be considered an explosion.

**Comment by keithsw1111** [comment]
This seems to have only been wrong on the transition out. Existing sequences from 50 onwards should be auto corrected without changing how they look. Anyone using v50 before releases will have problems as the auto convert logic wont kick in until the version number is updated.
