### ISSUE TITLE
Enhancement request - Define required channels on Setup section only

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#624]
If possible , can the channel definition on the setup page be enhanced so that only the required channels are defined - ie something similar to the FPP or F16v2 where (say) you define the universe , start channel and number of channels on each row. (xlights calculates and displays the end channel)

However:
The next start channel does not have to  be contiguous to the end of the previous start channel , so if you have gaps in between , you don't have to define a filler to fill that up.

Example:
Universe.. Start... #of channels
1.................1............512
2.................2000....1000
10..............5000.....nnn
200...........10000...512 etc

Currently , inserting or shifting ranges is quite tricky due to the recalculation of everything when u change an item and inadvertently you can shift channels from universes that you did not intend to , unless you keep before and after images of the screen that you can use to compare.

A warning / highlight of any overlapping channels would be useful in this case.

**Comment by keithsw1111** [comment]
I say no. With the enhancement to allow you to specify model start number as universe/channel this should not be necessary. Models should automatically remap if you insert a controller or add/remove channels on setup. That combined with the existing start channel modes means you should never be sensitive to setup changes. The worst thing you should have to do is render all.

**Comment by gerry4** [comment]
Hello Keith,


Currently all my models are defined as specific channel numbers (which I understood was the most common way to do so). I have attached a screen print of my setup -- all the lines with a dot in them are unused.  Am I doing something that is not necessary if I want to use the Output to lights  function in xLights to test ?


Without changing everything to {Universe, channel} is there a way of simplifying the setup ?


If not, no problem , I just have to be careful on the setup changes.



Gerard


________________________________

**Comment by AzGilrock** [comment]
You can daisy chain models now and tell one to start where the last one ended.  That way you change the first model and they all move.  It's so easy to remap universes why do you need big gaps?

**Comment by gerry4** [comment]
Unfortunately , that was how I defined them in my first year when I used LSP (which was only 2 Christmas's ago). With mostly P2s with two outputs each,  and not knowing much , I started each new prop at a nice round number with large gaps in between in case I had to move stuff due to voltage drop , null pixels and all that stuff.



Then  last year ,, when I switched to xLights , I imported the LSP sequences as data layers (the import worked perfectly) and then added everything new in xLights.  , but I have assumed that the channel numbers must match i.e. I cant change them now ?


I thought that with the recent changes where the setup definition is no longer mandatory, it would now be possible to do this .. hence the request . But not an issue . What I will do is bite the bullet after Christmas (before taking it down) and redo everything without the gaps and get rid of the LSP imported data layers.


I do daisy chain the latest models , but still start the first model of a group on a nice round number (and stop when the channel count of that 'group' reaches 450).. because am not sure how the 510 v/s 512 channels of different controllers (I now have a mix bag of F16v2, pixlite and the P2) ) work.

So if I had 6 trees of 50 pixels each , I would daisy chain two groups , with the first and 4th anchored on absolute numbers.



Gerard


________________________________

**Comment by AzGilrock** [comment]
Yeah but I do the same thing.  I have gaps in the middle of my setup and it should be pain free.  I can create the setup for my show in 3 seconds.  I delete all universes, tell it I want 61 universes with 512 channels each....done.  I don't even use all the universes.  I daisy chain back to back on each controller but I like to start each new controller on a new universe and I've left some gaps.  So my question is what's the problem with just defining them all but then just don't use the ones you don't use?

**Comment by gerry4** [comment]
Thank you  Gil,


I guess that I have stumbled through to a somewhat partial understanding of how channels on universes physically work on controllers and therefore on setups such as the xlights , FPP and the actual controller.

I don't have a grasp of what occurs or should occur when you cross the 510/512 boundary (example1- 500 pixels all end to end on a P2 on different props) , (example 2 - 500 pixels on different outputs of a F16 or Pixlite16). How the "start port" on controllers is meant to be used when not set to 1 etc.



Therefore I have broken the channel ranges into chunks that do not ever exceed 510 so as to avoid the problem. (except for the P10 definitions).


Accordingly, getting the setup correctly aligned on xlights , the controllers and FP takes me quite a long time (am embarrassed to say how long). Off which getting it correct in xlights is the longest, particularly when after testing , I find that you are a few pixels off etc. I then have to 'insert', 'remove' a few channels here and there in the definition and test again.


I don't think that there are any videos out there which explain the right/easy way on setting up definitions.


Gerard


________________________________

**Comment by AzGilrock** [comment]
I still don't see how any of that makes the setup page difficult.  Just delete everything and then add how ever many universes you want all with a size of 510.  If you only use 300 channels of the first universe then who cares....just start the next prop at channel 511.  I literally never touch the setup page.  Using F16v2's makes it even easier.  You just start each output 1 channel after the end of the previous one.  It internally will copy the data where it needs to go. In xLights you just define all those models back to back.  Its so simple to me I guess I don't know what else to say.  I really don't even think about it until I'm setting up in my yard.  I connect the item to the controller then I open up xLights and change the start channel to whatever the F16v2 had for that output.  Then I re-render and I'm done.
