### ISSUE TITLE
Enhance the presets functionality

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#625]
If possible, please indicate how many layers a preset needs.  Here is the result of a preset applied to a model with not enough layers. The effects spill over into the subsequent models.
![image](https://cloud.githubusercontent.com/assets/10568498/16957769/a05b404c-4d92-11e6-9511-49dc6a4665db.png)

Alternatively, when applying a preset, a warning can come up.
![image](https://cloud.githubusercontent.com/assets/10568498/16958055/c8ce2552-4d93-11e6-80a0-e17ed432b6ef.png)

This will improve end result of sharing of preset effects.

**Comment by AzGilrock** [comment]
Yes it would be nice to show the number of layers beside the preset.  I don't like the warning because presets are not meant to be exclusive to one model.  Technically a preset can contain effect for every model in the sequence.  You could create a preset for the Chorus of a song.

**Comment by stevegiron** [comment]
True, you can save an entire sequence as a preset too.  Ok, just the number of layers without the warning would be great. I save my presets in groups for Tree or Matrix because the tweaks are based on the model shape/size. Some presets look great on tree and not so much on a matrix only because of the shape difference.

**Comment by stevegiron** [comment]
With the ability to see the number of layers on a preset, it would be nice to see the number of layers on a model in a sequence too without having to count them manually.

**Comment by AzGilrock** [comment]
Yeah we already have #397.

**Comment by keithsw1111** [comment]
I have added a count of the layers in the preset after the preset name.
