### ISSUE TITLE
Bug:  Effect Assist window - cannot undock without disappearing.

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#627]
Any time I try to select the Effect Assist window and undock it to move into a new location, it simply disappears.  I then have to reload a perspective to get it to show up again.

The House Preview and Model Preview windows will undock, but appear very very small on screen too.

Running the latest and greatest, release 40, under Mac OS X.

**Comment by AzGilrock** [comment]
Sounds like you keep reloading a bad perspective.  Just try deleting the entire section from the rgbeffects file and start over.

**Comment by kppankratz** [comment]
That worked.  Thanks.
