### ISSUE TITLE
Preset checkin needs another look at

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#628]
![image](https://cloud.githubusercontent.com/assets/10568498/17075862/5409c710-5056-11e6-8e7a-c5c4dc437d4e.png)

http://www.stevesimages.com/xl4/preset-layers.mp4

**Comment by keithsw1111** [comment]
Steve can you send me your rgbeffects file.

**Comment by stevegiron** [comment]
Sure what's your email address?
