### ISSUE TITLE
Create Start Channel Option based on Controller

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#631]
It would be nice if their was an option when selecting a start channel for a model that was based on the controller. For instance, I have 30 controllers in Unicast so each uses Universe 1-12. Assigning channels per universe would be great if it was done on a per IP basis for Unicast configurations. The best option would be to have an 'Offset From' option that could be the IP address for the controller so that additional additions or changes for new models added to the controller would not affect channels numbers on anything outside of that controller.

**Comment by keithsw1111** [comment]
You already have the output:channel option. Outputs are numbered from the top down on the setup tab starting at number 1.
The problem with your suggestion is we would need ip (or some portion of it) + universe + channel offset ... at what point does it just become easier to put the output number?
Mind you ... it would not be a hard add.

**Comment by idleup** [comment]
Yes, I know about the output offset that uses the row number on the setup tab. The problem is that with 30 controllers with 12 universes that is 360 rows and they are not even numbered! Imagine looking at a model and seeing that it is output offset number 242, it is not easy or intuitive to try and figure that out hence my request.

**Comment by idleup** [comment]
On the flip side, it is very intuitive to look at a model, click the channel start, and see that it is set to controller 10.10.10.15 universe 3 channel 36.

**Comment by keithsw1111** [comment]
So a format like #10.10.10.15:3:26 would work? And i look at the number after the # to work out if it is an IP address or not.

**Comment by idleup** [comment]
Sure that will work just fine. I do not really care about the syntax as long as I understand it do whatever is easiest for you.

**Comment by dkulp** [comment]
Keith, I think instead of a  text field where the user has to enter the output number, maybe change it to a drop down list of the controllers.   Internally, it would still be the same "output:offset" notation, but the output number is selected via a drop down.

**Comment by keithsw1111** [comment]
Sure but you still have the problem that the outputs arent numbered on the setup screen and if you have lots of them you can get lost ... also the dialog is modal (from memory) so you cant go and look. We could add the extra details in the drop down i guess but not store them the in the start channel string.

The other problem with output number is it is not resilient to change in the setup. If I add a universe 13 to controller 1 and move it into "order" then everything below it is moved one place. While there is no need to move it people who like "order" do want to do that. Absolute references are better because we are independent of the controller order ... we just need to look it up.

Gils argument (because he has made it before) is just add them all ... while that works not everyone works that way.

**Comment by idleup** [comment]
Keith, I agree with both your points above.

**Comment by dkulp** [comment]
And what happens when I go to setup and change the controllers IP address?  Or change it from universe 3 to universe 4?  It's the same issue.   All the absolute references are now wrong/invalid.

**Comment by idleup** [comment]
If you are using multicast and change a universe assignment than it is reasonable to expect you will mess up all your channel assignments affected by your changes (which could be your entire show). In the same way if you are using Unicast and make changes like you mentioned than it is reasonable that you may have to modify the channel assignments for that controller. The difference is the scope of what you can mess up is limited to the controller in which you made the changes.

**Comment by keithsw1111** [comment]
Implemented

**Comment by AzGilrock** [comment]
LOL.  All this was discussed and implemented while I was asleep.

**Comment by idleup** [comment]
Keith, thank you for getting on this so quickly! I am thoroughly impressed.

**Comment by AzGilrock** [comment]
That's why no other sequencer can keep up.  We have round the clock coding.  While the US guys are sleeping Keith is awake coding. :)

**Comment by idleup** [comment]
Yeah its great, and with my impending deadline I will likely be submitting
round the clock requests :-)
