### ISSUE TITLE
Add Channel -> Model Reference Map

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#632]
Desired Functionality is for user to see what model a given channel is associated with and what channel a given model node is associated with. Unless I am doing something wrong and this already can be done, this is what I proposed doing:

Modify the **Tools -> Test** dialog so that when expanding a row under Controllers you see this:
Channel {R} [1] (1) - (MODEL NAME) Node (1)
Channel {G} [2] (2) - (MODEL NAME) Node (1)
Channel {B} [3] (3) - (MODEL NAME) Node (1)

**Instead of this**:
Channel {R} [1] (1)
Channel {G} [2] (2)
Channel {B} [3] (3)

Furthermore when expanding the model below that section you would see the inverse, this:
Channel {R} [1] (1) - E1.31 10.10.15.2 {UNIVERSE} [ROW_CHANNEL] (GLOBAL_CHANNEL)
Channel {G} [2] (2) - E1.31 10.10.15.2 {UNIVERSE} [ROW_CHANNEL] (GLOBAL_CHANNEL)
Channel {B} [3] (3) - E1.31 10.10.15.2 {UNIVERSE} [ROW_CHANNEL] (GLOBAL_CHANNEL)

**Instead of this**:
Channel {R} [1] (1)
Channel {G} [2] (2)
Channel {B} [3] (3)

Some other features that would nice but not important to accomplish the core purpose would be an option to filter unassigned channels or show only mapped channels and an option to export to CSV for further filtering and searching in Excel.

**Comment by stevegiron** [comment]
Matt, in every version of xLights, you've had a modelxls.bat file included. Copy your xlights_rgbeffects.xml file to the bat file location.  Run the bat file and you'll have output very close that.

**Comment by keithsw1111** [comment]
There is also the model export on the tools menu which gives you a model and controller export. I suspect that is what you really need.

**Comment by dkulp** [comment]
Also note that a channel can map to more than one model.   That makes the first part way more complex.  Do we list ALL the models that the channel belongs to?

**Comment by idleup** [comment]
I moved the xlights_rgbeffects.xml to the /bin folder and ran the modelxls.bat. The resulting csv file had column headers but no data... 

The models export looks good and is definitely useable for some of what I need because all the information is on one screen BUT by keeping it a single row per model it still does not allow me to quickly visualize channel gaps or see the relative ending channel if it is in a subsequent row (e.g., Models that span more than one universe). Seeing the absolute ending channel is not very useful when your channel starts are based on relative positioning (like output number, universe number, etc.). The format tree like you see on the test dialog is the best way to quickly visualize both channel gaps as well see both the absolute ending channels and relative ending channels for models spanning multiple rows. I hope this makes sense... So I think this issue is still valid for what I am wanting to do. It does not need to be modifications to the test dialog, it can be a CSV export, I just thought the test dialog would be the quickest way to implement because it already breaks out the information into one row per channel. If further explanation is necessary let me know. I may not be explaining why I need this type of view in the most comprehensive way.

**Comment by keithsw1111** [comment]
I contemplated (and even built the code) to show as a tool tip which model a channel was connected to but abandoned it as the UI would not work the way I wanted it to due to limitations in the UI framework. 

As Dan points out the big challenge with this is many people map the same channel into multiple models which complicates the UI. For your use case it may make sense but for others it is just clutter. 

When Gil gets his nested models working this is going to be even worse as I run into circular references in groups.

I am happy for this to be a suggestion but in this case I dont think I will be rushing to implement it until at least Gils change is done. There is just too much risk of rework.

**Comment by idleup** [comment]
Okay that's fine. I can still get the channel mappings the old fashion way using excel. Having 100k+ channels to keep track of is a pain and a real time channel mapping at a high level view would be nice eventually. The way it is done in Vixen 3 is that channels are shown with a green icon if there is a node associated to them, the node can be present in many groups (models). It is easy to see in the tree view what channels are yet to be mapped and which are already mapped. You can cross reference both ways. Something similar would be helpful in xLights. As for Dan's comment about multiple models per channel the best way to implement that if it were in the test dialog is how the nodes are represented where they can be expected if their are multiple channels per node. In the same way, if you have multiple models per channel each model can be represented as child elements.

**Comment by keithsw1111** [comment]
You can do that today on test ... go to the models section. Select the top level node ... go back to the controller section. All controllers with all channels used will now be ticked. Those with gaps will be filled in. You can drill down to see which channels are and are not in use. Those in use will be ticked. The only thing you cant immediately see is which model is using it ... but you have that info in your export.

**Comment by keithsw1111** [comment]
Gil found a way to get tooltips working on the tree control on windows ... so in v46 on windows in the test dialog you can click on a channel and a tool tip will appear listing all the models and groups that contain the selected channel or are on the selected controller.
I dont believe it will work on the Mac due to a defect Dan mentioned.

**Comment by AzGilrock** [comment]
Just browsed you're checkin and I think for Mac you just remove the "GetView()" part of the call so you should be able to make it work without skipping it on Mac.  Just #ifdef around those few calls.  Also I think you have a comment saying the tooltip doesn't work that you can remove now.

**Comment by keithsw1111** [comment]
I will make the change tonight.
