### ISSUE TITLE
Change Lights/String to Nodes/String on Matrix Model

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#633]
Okay, this is a very minor issue but as I am learning the XL terminology it did confuse me a little bit. In order to stay consistent with the terminology used on other models (like the single strand) it may be more accurate to change the "Lights/String" property label to "Nodes/String" on the Matrix Model. 

If people were to use 60/20 strips on a matrix (which I don't know why they would but I have received emails from people who do) than I guess there could be a property added for "Lights/Node" on the matrix model like their is on the single strands/polylines models, but in order to maintain consistency with terminology, Lights should probably always be considered "LED Clusters" (or the thingy that emits light) and Nodes should be the WS2811/2801/Whatever (or the chip thingy that controls a light).

Just my $0.02 as a new user to the program...

**Comment by stevegiron** [comment]
I believe there was a request to include a 3Led/node string type for this.  You should also note, that we don't have "Props or fixtures"  They are "models"  You do not add models to a sequence,  you add "Elements" Elements are models, model groups and timing tracks. It goes on and on but you'll figure it out as you go.
