### ISSUE TITLE
Changing default perspective causes uncaptured crash on exit

### ISSUE THREAD

**Issue by mararunr** [smeighan/xLights#64]
Modified perspective and saved as default.  Every time on exit, below crash message (not a normal debug crash).  Testing on my Windows 7 desktop with this scenario (multiple occurrences before reporting).

Modified display perspective screen capture and crash message (in 2 parts) below.

![image](https://cloud.githubusercontent.com/assets/11252070/6519844/b22f28c2-c37f-11e4-97ff-ae725dd105fb.png)

![image](https://cloud.githubusercontent.com/assets/11252070/6519808/345a9742-c37f-11e4-812c-46be15abd49b.png)

![image](https://cloud.githubusercontent.com/assets/11252070/6519810/412e0968-c37f-11e4-8d1b-d7a606c07737.png)

**Comment by smeighan** [comment]
i am having a problem duplicating this crash.
i modified default perspective and click to exit afterwards and i do not get a crash. i am on windows 7.

Maybe you could use the free software from screen-cast-o-matic to record your key strokes so i can duplicate them exactly?

**Comment by mararunr** [comment]
Ok.  I'll try to get it done tonight.

**Comment by mararunr** [comment]
Recording #1
|   |
|   |  |   |   |   |   |   |
| Recording #1 |
|  |
| View on youtu.be | Preview by Yahoo |
|  |
|   |

**Comment by mararunr** [comment]
http://youtu.be/lWH4P2Hyh54?hd=1

**Comment by mararunr** [comment]
I also showed some of the redrawing/resizing opportunities (ghost bars/images).  You can skip to about 1:50 as the first 1:50 is just me trying to figure out a clean install to redo it from complete scratch.  Hope this helps, mv

**Comment by smeighan** [comment]
mark can you send your xlights_rgbeffects.xml and the sequence xml file to xlights@meighan.net so i can try and duplicate?

**Comment by mararunr** [comment]
Sean, it does the same thing with no files in the show directory.  Will get you those files and screencast of crash with no starting xlights*.xml (and no sequences) as well shortly...

**Comment by mararunr** [comment]
Attached...
or here...Public  and screencast (better quality - upgraded to Pro) of starting with empty show directory (and fresh install).  I didn't even save the perspective - I just closed a couple frames, moved the display frame and closed XL4 = crash.
https://www.youtube.com/watch?v=Bw6DMRuu90s&feature=youtu.be&hd=1

Sorry Sean (et al.).  Let me know if you need anything else.  Happy to help any way I can.

**Comment by mararunr** [comment]
https://onedrive.live.com/redir?resid=D05FBDC1B79CF3A9%21105

**Comment by mararunr** [comment]
This appears to be fixed with 9 Mar build.  I tried several different ways and did not get a crash (uncaptured or graceful with bug report). Thank you!

**Comment by mararunr** [comment]
Resolved.

**Comment by mararunr** [comment]
Re-tested with 4.0.9 - no issue
