### ISSUE TITLE
rotating arches doesnt update select area

### ISSUE THREAD

**Issue by cp16net** [smeighan/xLights#645]
What i did:
Create a new arch and flip it around so that the arch start channel is on the right instead of left and make the arch go up instead of down.

Expected behavior:
select it by clicking on the arch

Actual behavior:
clicking on the arch does nothing.
clicking below arch selects arch.

**Comment by AzGilrock** [comment]
Doesn't the arch model have a field to specify controller location?

**Comment by cp16net** [comment]
i guess thats what "Starting Location" means with values of Right and Left. But update this field doesnt update the display colors for the green and blue dots representing the start/end of the model.

**Comment by AzGilrock** [comment]
Well that's an assumption thinking it should.
