### ISSUE TITLE
Cancel custom model import causes errors

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#647]
Custom model import, cancel then you get this
![image](https://cloud.githubusercontent.com/assets/10568498/17633744/c6d58f6c-6083-11e6-8cfd-39306167c758.png)

Then this:
![image](https://cloud.githubusercontent.com/assets/10568498/17633756/d35af4b6-6083-11e6-8e1b-b793ce300eb9.png)
 and the Xlights Error should read "xLights Error"

**Comment by AzGilrock** [comment]
That second error windows isn't from xLights but I'm gonna fix it so it never comes up.
