### ISSUE TITLE
Exporting a model in LCB format places unmapped channels after the used channels

### ISSUE THREAD

**Issue by PKingRoch** [smeighan/xLights#648]
xLights 2016.41 is exporting unused channels when exporting a model that has gaps in the node assignments.  xLights 4.2.8 didn't export these unused channels and things were much nicer.  Please contact me by email if you need any evidence of what I am doing.  I have a pixel tree (16x50) that uses one universe for each strand (150 channels).  I only want to export 2400 channels in the LCB file, but instead 7830 channels are being exported.

**Comment by AzGilrock** [comment]
For the other developers.  I verified in 4.2.8 the export file size is the same even when using individual start channels with gaps.  So far I didn't see what changed to alter this behavior.

**Comment by keithsw1111** [comment]
The last change was probably when I removed the convert tab.

**Comment by PKingRoch** [comment]
Here are the two lcb files for comparison where I discovered this. 
[test 4.2.8.zip](https://github.com/smeighan/xLights/files/416553/test.4.2.8.zip)
[grandma left 2016.41.zip](https://github.com/smeighan/xLights/files/416554/grandma.left.2016.41.zip)

**Comment by keithsw1111** [comment]
I beleive I have this fixed for v2016.46. Please check on release and close if ok.

**Comment by keithsw1111** [comment]
This should be fixed now that v46 is out
