### ISSUE TITLE
256 Color Picker

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#649]
Hi I would like to seem something like this as a colour picker, or an alternative to the customer colour picker. It would allow a more consistent set of colours. Realistic 256 colours is heaps from a selection point of view.

https://en.wikipedia.org/wiki/List_of_software_palettes#8-8-4_levels_RGB

PS what the reason behind the 6 colour limit?

**Comment by keithsw1111** [comment]
6 colour limit ... we support 8 and if you click on the colour you can make it any colour you like. If you right click you can make it a gradient.

**Comment by AzGilrock** [comment]
Those color pickers look terrible in my opinion.  I've wanted to add more option but it's not going to look like those.  I like the Mac ones better.
![colorpickers](https://cloud.githubusercontent.com/assets/2024669/17644381/fc8acfd0-6139-11e6-88a4-ee1c3107efd9.PNG)

**Comment by damon-atkins** [comment]
http://img.uninhabitant.com/colourcube.html   this is an interesting page

**Comment by stevegiron** [comment]
![image](https://cloud.githubusercontent.com/assets/10568498/17672424/2203aae6-62d1-11e6-9c14-c6515f7d5595.png)

**Comment by leevigraham** [comment]
The colour picker is part of the OS you use which is fine.

I would like to see RGB / HSL sliders as an option for quick colour updates. Something similar to this post: http://nutcracker123.com/forum/index.php?topic=3388.0

**Comment by keithsw1111** [comment]
Yeah no. This very very unlikely to ever happen. That post asked for saved palettes and that exists so we consider this closed.
