### ISSUE TITLE
Playback from scrubber line gets off

### ISSUE THREAD

**Issue by smeighan** [smeighan/xLights#65]
If you click into a song and start to play, the music is not aligned/

**Comment by AzGilrock** [comment]
I worked on this for a couple hours.  It appears this is only a problem for mp3's with certain bitrates.  The file that fails was 250k and I resampled it to 160k and it plays just fine.  At 250k there is about a 1.5 second offset where the music is playing behind where it should unless you start at the beginning of the file in which case it works.

I've confirmed we are requesting the proper time in milliseconds in the wxMediaCtrl::Seek() call so the problem appears to be outside of our source code and in the wxWidgets code.  I've used the wxMediaCtrl::Tell() call to confirm it has the right spot we told it to seek and its still not playing it correctly.

**Comment by smeighan** [comment]
resampling the wave files is an acceptable workaround. people will have only 5-10 sound files, only some need to be resampled. the process takes < 1 minute and it is a one time operation.
