### ISSUE TITLE
Enhancement Request: Ability to select the effect or effect use on the insert random function

### ISSUE THREAD

**Issue by jediknight2** [smeighan/xLights#651]
I'd like to see the ability to choose which effect or effects are used in the random effect function.  In addition, the ability to select a saved preset to use as that random effect.  In addition, a way to select the area on the timeline and insert that effect X% in the selected area.  For example, I create a preset that is an ON effect that is 9 seconds.  2 seconds fade in, on for 7 seconds and 2 second fade out.  I select an area on the time line for a model.  Say I select the area from 5 seconds to 45 seconds.  I select random, select my preset and can choose a percentage to fill with that effect.  So if I choose 20% it takes my preset effect and fills that area randomly to cover 20% of the selected area.

**Comment by keithsw1111** [comment]
Given some of the oldest still open requests here are enhancements/changes to random effects I really dont like the chances of this being done. Outside of testing I believe there is very little use of the random generation function.

**Comment by AzGilrock** [comment]
I think you created videos to show how you do this in HLS.  You should link them here.

**Comment by computergeek1507** [comment]
I added this as an option to the preference panel
