### ISSUE TITLE
State definition error - I think Keith did it!

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#654]
![image](https://cloud.githubusercontent.com/assets/10568498/17751220/f08ddc38-647a-11e6-82cd-c2028f977532.png)

**Comment by AzGilrock** [comment]
LOL...yeah I searched for his name in the code.

StaticBitmap1 = new wxStaticBitmap(this, ID_STATICBITMAP1, wxBitmap(wxImage(_T("C:\\Users\\keith\\Documents\\xLights\\include\\sevensegment.xpm"))), wxDefaultPosition, wxDefaultSize, wxSIMPLE_BORDER, _T("ID_STATICBITMAP1"));

**Comment by AzGilrock** [comment]
Obviously this shows none of the rest of the developers tested it.

**Comment by keithsw1111** [comment]
hmmm ... thats not good. I think i thought it would embed it as a resource somehow.

**Comment by stevegiron** [comment]
Let's call him "Brittney Spears"

**Comment by AzGilrock** [comment]
Not sure what size or type of image you're trying to display but I know I have some PNG files I use in the code and I have a special utility I found that I run and it converts the PNG image files into .h header files that can be used to create the images.  Look at PaintToolIcons.h for example.   I really need to get that tool checked in along with a lot of the graphic resources I've created for things like the Media, Animation, and FPS button images I've created using that tool.

**Comment by keithsw1111** [comment]
The image is checked in ... I think i just set the staticbitmap property instead of #including the xpm file and loading it from the resource.

**Comment by AzGilrock** [comment]
Ok yeah I saw that file get checked in cause I remember checking to see if it was an icon.  Just in case you need it the tool I use is called wxInclude and is talked about here.  I like it cause you can package a whole set of images into a single .h file.
https://wiki.wxwidgets.org/Embedding_PNG_Images
