### ISSUE TITLE
Add ability to save Value Curves

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#655]
I have created custom value curves and would like to save them for future use. In the value curves dialog box create a button to save and name it and it will then show up in the drop down list.

**Comment by keithsw1111** [comment]
Not quite as described ... it shows up as an icon like the colour curve does (which means you can see the shape).

**Comment by idleup** [comment]
I am confused about your comment Keith and why this was closed? Is it not a valid request to want to use custom value curves since most of the attributes now support them?

**Comment by AzGilrock** [comment]
He closed it because he checked in a change that allows you to save and load custom value curves.  I think he was trying to describe that his implementation of how he's doing it didn't exactly match your request.

**Comment by idleup** [comment]
Oh okay, I will pull the changes and check it out. Thanks.

**Comment by keithsw1111** [comment]
Yeah Gilmore right. Not quite as requested but I functionally equivalent.

**Comment by keithsw1111** [comment]
Bloody autocorrect.

**Comment by stevegiron** [comment]
"Gilmore Wright" is his secret pen name. shhhh

**Comment by AzGilrock** [comment]
I was thinking I truly don't understand the Austrailian dialect... :)
