### ISSUE TITLE
Sharing User Effects

### ISSUE THREAD

**Issue by RyanKasperCook** [smeighan/xLights#656]
It would be great if we could create a place for users to share their unique effect combinations. For starters it could just be a simple screen shots of our Effect Settings, Color, Blending, Layer Settings etc... along with possibly a video of the model and how that effect looks.  This would more specifically apply to effects users have built in multiple layers to create unique one of a kind effects.

I personally have a hard time with layers and blending modes, and think this would really help other users have a better understanding of layers/blending options and what can be done.  To take it a step further, if this takes off, you could incorporate an "automated" sharing option that xlights would render and post effect parameters and model preview to this area if user so chooses to share it.  Just a thought, thanks!

**Comment by stevegiron** [comment]
You can save an effect as a preset and share the preset. The presets will indicate how many layers the effect has so it can be properly used.

**Comment by RyanKasperCook** [comment]
Okay, so maybe this isn't the place to suggest it, but I was thinking more along the lines of an online directory or ongoing table of effects users have shared.  Every now and then someone will share something on FB page, but then eventually gets lost in list of posts.... so thats what I was thinking would be great to have a place people could go to for inspiration on web that is just dedicated to effects/presets users have shared

**Comment by AzGilrock** [comment]
Well most people don't know that things on Facebook are not as "lost" as they seem.  In the xLights group you can type in a search phrase to find stuff or for anything that was ever attached to a post you can just click the Files tab and there are all the attachments in a list.

**Comment by RyanKasperCook** [comment]
Yes, you can search in FB groups and upload files I realize, but this is not what I was trying to convey.  It sounds like this is something you are not interested in or just not grasping what I am saying.... but thanks anyways.

**Comment by keithsw1111** [comment]
I have this repository https://bitbucket.org/keithsw1111/sequencing-assets/downloads ... happy to accept contributions

**Comment by stevegiron** [comment]
I've added an effect preset forum to the xLights forums.
http://nutcracker123.com/forum/index.php?board=46.0
