### ISSUE TITLE
Enh: Add ability to remove sub-model layer from sequence.

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#658]
I'm liking the sub model feature and ran into an issue.
I created a sequence PC1 and loaded it on PC2. The second PC had the same models, but ever so slightly differently named sub models. The sequence opened, and now it has 2 submodel layers for each regular model.   The submodel effects don't play now because of layering order, etc.

I need a way to delete a submodel layer from a sequence, especially when the submodel doesn't exist.
Yes, I know.. use the same rgbeffects file on both systems and this won't happen.

**Comment by keithsw1111** [comment]
Is this still a problem. Think everything needed to handle this situation has been added.

**Comment by AzGilrock** [comment]
Reopen if needed.
