### ISSUE TITLE
Crash upon collapsing model group tree 

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#659]
If I expand a model group tree and select one of the models, then try to collapse the group, xLight will crash.  Only does this if a group model is selected.  I can expand a group and collapse it without issues as long as a model isn't selected.

Running Mac OS X 10.11.6, xLights v46 + (compiled as of 4:30 pm 8/18).

[xLights_dbgrpt-5840-20160807T194758.zip](https://github.com/smeighan/xLights/files/425944/xLights_dbgrpt-5840-20160807T194758.zip)

**Comment by AzGilrock** [comment]
This should be fixed by the 2016.47 release.
