### ISSUE TITLE
Crash when creating groups in the Layout Tab 2014.46

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#660]
I have been building this layout.  While trying to add models to the new group, Xlights creates a crash report.  I'll post a video to the Xlights FB group and link it here:
https://www.facebook.com/relxerd/videos/10153779410384212/?permPage=1

[xLights_dbgrpt-9824-20160819T174210.zip](https://github.com/smeighan/xLights/files/427947/xLights_dbgrpt-9824-20160819T174210.zip)

**Comment by AzGilrock** [comment]
This should be fixed by the 2016.47 release.

**Comment by Clyde-L** [comment]
Thank you Gil
