### ISSUE TITLE
Adding Models to Group

### ISSUE THREAD

**Issue by kmacmaster** [smeighan/xLights#662]
When I add new models to new groups, I can only add one at a time without the program crashing.  I add one, press save, add another, press save, add another, crash.

To reproduce, create a model group (I use spaces and Caps in my models / groups) and add something to it.

Xlights 2016.46

Ken MacMaster

[XLights.zip](https://github.com/smeighan/xLights/files/428639/XLights.zip)

**Comment by AzGilrock** [comment]
This should be fixed by the 2016.47 release.
