### ISSUE TITLE
Enhancement Paste

### ISSUE THREAD

**Issue by jediknight2** [smeighan/xLights#664]
A keyboard button that can be used with the Paste function.  So when a timing grid is in view you can press the button, paste and the copied effect will fill the area between the timing marks.  In addition, if you select an area, the highlighted area will fill with the effect.

https://drive.google.com/file/d/0B71_WLJUoWJKbDJ4M0NoSE5Ud0k/view?usp=sharing

**Comment by AzGilrock** [comment]
It's already there Ctrl-v

**Comment by jediknight2** [comment]
What version?  I'm on 2016.42.  If I copy an effect out of an area between 2 timing marks and go to paste between 2 timing marks of a different size, the effect retains the length of the original effect, it doesn't resize itself.

**Comment by stevegiron** [comment]
In the user manual, these two buttons on the toolbar are documented. 
![image](https://cloud.githubusercontent.com/assets/10568498/17862271/5db5d1d6-6849-11e6-8592-e0dd32d7296e.png)

**Comment by AzGilrock** [comment]
Yes when you have Paste by Time selected that's what you get.  Paste by Cell will do it proportional as long as the copy has the proper info.

**Comment by jediknight2** [comment]
Got it....I guess I need to peruse the manual again.  Never noticed those icons.  Sorry to bother you guys.
