### ISSUE TITLE
Add Keybinding TYPE for Pause

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#665]
Something like this:

`<keybinding key="p" type="PAUSE"/>`

**Comment by stevegiron** [comment]
Spacebar works today for pause.

**Comment by idleup** [comment]
No spacebar does a STOP operation

**Comment by kmacmaster** [comment]
I would love to see the keybindings expand.  I'd like to be able to open previews, play, pause, skip back, skip forward, render, and etc.  Keyboard shortcuts for everything.
