### ISSUE TITLE
Add Intensity Curve to Layer Blending

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#666]
I love the in and out transitions but would love to apply a fade at a non-uniform rate. For instance, I want a "flash-fade" on a curtain effect for instance (it could be any effect). I would want to set the intensity curve the same way as the other attribute value curves so it goes from 80% to 100% in .2 seconds and then from 100% to 0% in 3 seconds.

**Comment by AzGilrock** [comment]
I think you can already do this because we provide multiple ways to control intensity.  Doesn't one of the panels have a brightness slider that has a value curve?  That should work to do this.

**Comment by idleup** [comment]
Thanks Gil that worked. I was thinking of it more as a transformation and didn't even think to look for the functionality in the color panel :-)
