### ISSUE TITLE
Renaming Model Group Removed Row from Sequence

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#671]
After renaming a model group the group name in the sequencer remains the same. After closing and when reopening it does recognize the old group is gone and allows you to re-specify a new group name by selecting from the list of model groups in the drop down. This is fine. However, once the sequencer opens, that group row is missing from the sequencer and must be re-added. Perhaps at the time the new group is specified in the drop down list when opening the sequenced it should also re-add the selected group to the sequencer.

**Comment by AzGilrock** [comment]
I think you mean model group.  "LayoutGroup" happens to be the internal name I use for the extra preview window objects so it could cause confusion.  Sounds like the model rename is broke again for at least the 3rd time.  I didn't think we were due to break it again till next month.

**Comment by idleup** [comment]
Yes, I'm sorry you are correct, it is a Model Group

**Comment by keithsw1111** [comment]
Fixed
