### ISSUE TITLE
Typo in DMX model

### ISSUE THREAD

**Issue by gmartens** [smeighan/xLights#674]
This is a very easy one. It seems that moving head is spelled wrong in the DMX effect. Under the dropdown "DMX Style." Here's a screenshot: 
![example](https://cloud.githubusercontent.com/assets/22039302/18293508/ccdb796a-7458-11e6-84b2-bbe99432fd7e.png)
It's spelled "moving" not "moding" :)

**Comment by AzGilrock** [comment]
The ones I use are spelled right...lol.
