### ISSUE TITLE
Modify default value curve thumbnail

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#675]
When you click the value curve and change it the thumbnail next to that parameter representing the value curve changes to whatever curve you selected or created. This is great to see a quick visual indicator of all your parameters value curves. However, when you have no curve selected it shows a "Ramp Up" icon as the default icon. This should be changed to something that does not confuse and make you think you have a ramp up curve defined. Perhaps a straight line through the middle of the box would be best as it implies that without a defined value curve your values are linear. (Same thumbnail you see if you defined a flat value curve with level set to 50)

**Comment by keithsw1111** [comment]
I dont know that a straight line would be an improvement. Seems much of a muchness. If we were to change it it would need to not look like any possible curve but still hint at the buttons function. Icons are not my thing ... ask Gil ... he has to keep replacing my shoddy efforts. Maybe you could knock up and submit some icons we could consider for inclusion.

**Comment by AzGilrock** [comment]
I haven't looked so it's actually a drawn icon for the default?  I assumed it was inheriting the internal values and drawing the curve you were going to get if you activated it and accepted defaults.  Like if you select it you were going to get a ramp by default or wherever you had last left it when you deactivated it.

**Comment by keithsw1111** [comment]
Yeah it is a drawn icon. Feel free to change it. While you are at it the import xmodel icon needs work on the layout tab :)
