### ISSUE TITLE
Enhancement Request: add the ability to record key presses for triggering  pneumatic props.

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#678]
I want to build a sequence in xLights that I can use for a Monster in a Box. (MIB)  the sequence would be triggered by a pressure mat or motion sensor. The sequence would likely have an audio track with screams and various "monster noises" i would be sequencing lighting effects too.  Ideally I would like to assign a track(s) called relays, or anything that makes sense.  But the way I see it working is that I build my sequence. Then I rewind it to the beginning. I play the sequence and I start to tap a key on the keyboard, almost like adding a timing mark, but I want it to record key down and key up events. I want the relay engaged as long as the key is down and then when I release the key the relay is off. 

I guess a future enhancement would be to map multiple keys to timing tracks, and use the keyboard like a midi-keypad to sequence, 

Thoughts?

**Comment by keithsw1111** [comment]
I think this is unlikely to be implemented any time soon. These functions seem more appropriate to a show player such as FPP which is already capable of much of this.

The xLights show player has not been materially changed in several seasons as all the developers generally use FPP for the playing of their shows.

**Comment by patdelaney** [comment]
I’m not looking for the change in the show player, I’m looking for the change for when you are building a sequence. I’d like it to work like when you t to add a timing mark, but instead of just marking the timeline. I want to trigger and On event and stay on until I let go of the key.

 

Think of it like hitting the “o” key. That places the on event on the time line. I want to be able to highlight a track, hit play, and then when I want the on event I hit “o” and it stays on until I lift up on the key and it stops placing the on event?

 

Or maybe a better option, we just add a new feature to the timing function. Currently it I hit t it will add a mark to the timing track. How about the same but if I hold the t down while the track is playing it marks and in and then an out on the timing track

When you lift up on the key?

 

Does that explain it better?

**Comment by keithsw1111** [comment]
So I have to use up another key, somehow tell it which model to place the on effect onto ... it all seems like a lot of extra code complexity for a very specific use case. It would at best be one of those hidden features which attract bugs because we dont test them very often.

Why not tap out your timing marks using the t key then drag and drop some on effects onto the appropriate models.

**Comment by stevegiron** [comment]
Just add another timing track to your sequence. Use that new timing track
as your guide for your ON /  OFF events. Use the t key as normal to place
timing marks. When done go back and add the ON effect at those timing mark
locations. Two step, yes.
