### ISSUE TITLE
XML Parsing Error importing Effect Presets

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#679]
If I create effect presets and then export them, if I try to import them I get:

`XML parsing error: not well-formed (invalid token) at line XXX`

**Comment by idleup** [comment]
Okay, this was due to an illegal character in the XML (the amperstand). I would say to prevent this either escape the amperstands that are in the preset group names or dis-allow them.

**Comment by keithsw1111** [comment]
Disallowed.
