### ISSUE TITLE
Closing out the program

### ISSUE THREAD

**Issue by RichardRennII** [smeighan/xLights#68]
Every time I close the program I get a Xlights.exe has stopped working message

**Comment by AzGilrock** [comment]
I checked it a fix 20 minutes before you posted that fixes a lot of these.  We can't usually find these very easy unless they are happening to us or you have a debug report with the backtrace.txt file.

**Comment by AzGilrock** [comment]
Also it helps if we know the date for the build you are running.  Cause I know I checked in something that cause exit crashes 2 or 3 days ago so if you had a build with that it would explain it.  So this really needs to be checked after the next build.

**Comment by RichardRennII** [comment]
Sorry about that. It is not creating a debug report I just get the message and since I am the only one that knows I download every release as soon as it comes out it would help if I started letting you guys know what release date I am using. this is 3\4\2015 release

**Comment by RichardRennII** [comment]
New release dated 3\9\2015 have not had this issue

**Comment by AzGilrock** [comment]
I'm gonna close this since it appears to be fixed.  We can easily open a new one if it comes back.
