### ISSUE TITLE
HLS sequences not Importing

### ISSUE THREAD

**Issue by jediknight2** [smeighan/xLights#680]
If you use Import > Import Effects with an HLS file, no effects are imported.  I can choose the HLS data file, map the channels to nodes, but when I press OK, nothing is imported.  That same file works OK when using the Data Layer import. Data Layers come in fine, with the exception of Animated models.

**Comment by AzGilrock** [comment]
You forgot to provide a link for where someone can download the files.  I don't have any HLS files.

**Comment by jediknight2** [comment]
Sorry about that. https://drive.google.com/file/d/0B71_WLJUoWJKblROdERfUk10NUE/view?usp=sharing  You can also see what I'm talking about at the end of this video.  https://drive.google.com/file/d/0B71_WLJUoWJKbDI2OHFZOWFaR2s/view?usp=sharing
