### ISSUE TITLE
Animated Models will not convert effects

### ISSUE THREAD

**Issue by jediknight2** [smeighan/xLights#681]
I brought in an HLS data file via the Data Layer Import.  I could expand all of my models and convert all my nodes to effects.  However, none of the 8 channels associated with an Animated model will convert.

**Comment by AzGilrock** [comment]
What the heck is an "Animated model"?

**Comment by jediknight2** [comment]
A singing model.  Here is a video showing my issue https://drive.google.com/file/d/0B71_WLJUoWJKbDI2OHFZOWFaR2s/view?usp=sharing  The file you can use is here, https://drive.google.com/file/d/0B71_WLJUoWJKblROdERfUk10NUE/view?usp=sharing

**Comment by jediknight2** [comment]
A work around is to create 8 strands of icans separate from the animated model.  Set them as the channels, in my case 1-8.  Bring back in the data layer and you can use the newly created models not attached directly to the animated model to convert to effects.
