### ISSUE TITLE
View dropdown becomes unselectable

### ISSUE THREAD

**Issue by k8r4** [smeighan/xLights#682]
When I change the View dropdown from the 'master' to another view AND open the house or model preview, the View dropdown is no longer selectable. I have to close the house or model preview and resize one of the windows and the dropdown menu becomes selectable again.

Steps to Reproduce
1. Change View from Master to another View
2. Open a house or model preview window
3. View dropdown is unselectable
4. Close house or model preview window
5. Resize one of the windows
6. View dropdown is now selectable

**Comment by AzGilrock** [comment]
I can't reproduce.  I tried those steps several different ways and it always worked fine.  You should list your operation system and the version you are using.

**Comment by k8r4** [comment]
Version: 2016.48
OS: Windows 10

It appears to be happening with any dropdowns. For example: Effect Settings dropdowns are unselectable when the house or model preview is open.

**Comment by AzGilrock** [comment]
Same OS as me so I'm at a loss on this one.

**Comment by k8r4** [comment]
I completely uninstalled and reinstalled 2016.48 and I am no longer having the issue.
