### ISSUE TITLE
Initial display of Layout tab kinda funky on Linux

### ISSUE THREAD

**Issue by m00dawg** [smeighan/xLights#686]
When first firing up xLights, the Layout tab doesn't quite draw correctly wherein all the table elements are squished to the left. If I grab the model/group row divider it will then redraw and it sort of pops back but it doesn't seem to save that orientation.

Not a big deal for me but it might be confusing for someone new to xLights that also happens to be on Linux (though I recognize us strange folk are a minority).

![screenshot from 2016-09-14 20 22 31](https://cloud.githubusercontent.com/assets/226504/18535498/55ab875a-7aba-11e6-9611-4830c4810ef1.png)

**Comment by cjd** [comment]
The problem is in LayoutPanel.cpp - the width of the first column is not being autosized properly (as gtk doesn't do the redraw in time before the width is checked)
I'm looking at a clean fix for it currently
