### ISSUE TITLE
Add ability to place an Image model in Layout

### ISSUE THREAD

**Issue by AzGilrock** [smeighan/xLights#687]
I'd like to be able to place a PNG image type model in Layout.  Initially just ability to place a static image and adjust the transparency would be great.  Maybe it could get fancier and be able to have an On and an Off image and be a model that would react to effects.

**Comment by stevegiron** [comment]
I'd like to see this expand to the Boscoyo Spooky eyes type of use where you can draw a shape or highlight an area of an image to respond to effects via 3 channel RGB response.

**Comment by keithsw1111** [comment]
stevegiron ... I dont understand the enhanced functionality you are talking about ... I was contemplating closing this request.

**Comment by stevegiron** [comment]
I think this request preceeded the current ability for a custom model with a single node and a shape.
We can now do something like this for the Boscoyo spooky eyes and thus my portion of this request has been fulfilled. 
![image](https://user-images.githubusercontent.com/10568498/34958466-ecc63c5a-f9e6-11e7-947c-6fb2fe18d9f4.png)
