### ISSUE TITLE
dragging the main window larger

### ISSUE THREAD

**Issue by jnealand** [smeighan/xLights#69]
When I grab the right side of the main window to make it larger I am getting continual images of the right hand side.  Same thing happens when I make the window smaller.  I do not see this issue with any other program that I do this with.
![results of dragging the right edge of main window](https://cloud.githubusercontent.com/assets/2533387/6546740/c98a81a2-c595-11e4-8f0a-3778348bde38.JPG)

**Comment by AzGilrock** [comment]
What's the date of your build?  I'm pretty sure my checkin on March 6th fixed this.

**Comment by jnealand** [comment]
I have the Mar 4 version that Sean packaged up.

**Comment by AzGilrock** [comment]
Ok then lets double check this next build you get and hopefully its already fixed.

**Comment by jnealand** [comment]
problem appears to be fixed in the Mar 9 release.  You can close the ticket.
