### ISSUE TITLE
Enhancement Request: Add a [SAVE] button to Effects Preset box

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#690]
Since the Effects Presets are saved to the XLights_RGBeffects.xml, you have to change screens to save it.  I don't know how easily a save button for the xml could be added.  Would be nice to have.  Thanks!

**Comment by keithsw1111** [comment]
It prompts when you close if you have not saved. It also auto saves periodically so you are unlikely to lose anything.

**Comment by Clyde-L** [comment]
Thanks Keith.  I was not sure that it was saving the rgb effects file.  I guess my concern was that I use the beta releases.  I've experienced a crash before saving the work.  Changing to the layout tab it what I'll have to do.
