### ISSUE TITLE
Preview Windows Brightness Setting Not Applied on Application Open

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#691]
When opening the application and going to View -> Previews -> My Preview the preview window opens up without the brightness setting applied. If I open the preview on the layout tap and change the brightness value then change it back again the preview window now applies the brightness setting correctly when switching back to the sequence tab.

**Comment by AzGilrock** [comment]
When I open mine with View -> Previews -> Show All they all open up with the proper brightness.  There might be an issue with changing the setting not taking effect till you force an update to the preview window like a resize or something but you could easily just uncheck the Show All make all the adjustments and then do a Show All and they will all have the correct brightness.  Brightness is usually a one time setting.
