### ISSUE TITLE
Preview windows not opening and returning to position on application start

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#692]
I have created a Perspective and opened several preview windows placing them on my screen how I want them sized and tiled. I then 'Save Current' and close the application. When I open it again the preview windows do not open.

**Comment by AzGilrock** [comment]
Like I said before the extra previews I created are not managed by the wxAuiManager so they are not part of the perspective.  I added their own logic to remember where they were but I don't automatically open them.  I made it one simple step to open them back up View -> Previews -> Show All.

**Comment by idleup** [comment]
Oh okay. They are not remembering where they were when re-opened. They do remember their size though. Also, I am not wanting them all open, just the 4 I use most (several previews are meant to be hidden because they have proxy models). I guess the issue can then be why they are not remembering their location when re-opened. And if their is another issue for adding them to the perspective this can be linked to that issue.

**Comment by AzGilrock** [comment]
Hmm...they should remember the size and position.  I added that feature because my test case had 13 windows and I didn't want to place them every time.  Try hitting the "Save" button on the Layout tab after you move positions.

**Comment by AzGilrock** [comment]
Well I do see some of them that seem to keep jumping back to my 1st monitor.  Not sure what changed.  You can see the positions stored for the previews in the rgbeffects file under the LayoutGroups section.

**Comment by AzGilrock** [comment]
There seems to be a problem if you only move one window it updates that window and forgets the others.  So the temporary workaround I believe is make sure you move them all and hit Save.

**Comment by AzGilrock** [comment]
Ok pull the code and try again.  The event handler for size changes was looking at the x and y values of the event and I thought they were the positions but they turned out to be the width and height.

**Comment by idleup** [comment]
Yep, works now :-)
