### ISSUE TITLE
Trouble copy/pasting Morph effect

### ISSUE THREAD

**Issue by m00dawg** [smeighan/xLights#693]
I'm having a heck of a time trying to grab and then cut and past the Morph effect. I presume part of it is because you have to grab it on the left? I've tried a few ways (such as highlighting that section of the track) and it seems to be stubborn occasionally crashing (see attach). This is on Linux Mint using trunk (up to commit e11b0142dff7d312154a808d67c8c8ea44ff6c53). Replacing an existing effect by dragging the Morph icon on top of an existing effect seems to work, it's just the cut/paste that seems to be fickle.

[xLights_dbgrpt-18828-20160919T171249.zip](https://github.com/smeighan/xLights/files/481246/xLights_dbgrpt-18828-20160919T171249.zip)
[xLights_dbgrpt-18623-20160919T170520.zip](https://github.com/smeighan/xLights/files/481247/xLights_dbgrpt-18623-20160919T170520.zip)

**Comment by AzGilrock** [comment]
I've never been able to read anything useful from a Linux backtrace file.  But as far as grabbing/selecting any effect you don't have to grab it on the left.  You can click it on either edge, or in the middle when the cursor turns to a hand.  You can also select an effect by clicking in a cell if you have an active timing track and timing marks that create cells.  Without a timing track active you can drag a yellow dashed box around the effect to select it.  Seems like you only found 1 of the many ways to select an effect.  Have you reviewed the user manual to know the 7 hotspots on an effect?

**Comment by m00dawg** [comment]
Ah copying from the middle seems to work as long as the effect is large enough. If it's too small I can only grab it from either end, which is kinda awkward to do (could be a Linux specific issue, I haven't tried it on other platforms yet) because it's one of the few effects that doesn't show the icon, so I sort of have to guess at clicking. Clicking on the cell (using an active timing track) seems to be working now but it requires that the effect is large enough (if it's within a single cell, it's a bit hard to select).

I have been running into the crashing bug pretty reliably though. I looked at the terminal output and it didn't really show much of anything. :/

**Comment by AzGilrock** [comment]
We provide several easy ways to zoom in.

**Comment by AzGilrock** [comment]
Ok someone else just reported a paste crash that helped me pinpoint it.  It happens if you try to paste bad data.  I accidentally moved a variable initialization up too far before the paste data length was validated.  So if you select an empty cell and copy/paste it you get a crash so I think that's your crash.

**Comment by m00dawg** [comment]
Yep that bug sounds similar, although I applied the latest git (3ad3d81bd707de7c14013ab15ba6e11912991161) and it's still occuring for me. The sequence seems to be:

1. Create a new morph effect on a string model
2. Delete original effect from destination string model channel
3. Copy morph to gap left by previous effect

Grabbing the morph icon from the effect palette and on top of an existing effect (thus replacing it) works reliably, however.

**Comment by AzGilrock** [comment]
Please show it in a video.  We can talk all day without me being able to repeat it.  Sometimes people spend hours telling me about a problem then they show me a picture and it's solved in 20 seconds.

**Comment by m00dawg** [comment]
Yep, very valid point. Here's a video showing how to reproduce the crash on Linux:

https://www.youtube.com/watch?v=KWu8ceFGi60

I tried to grab some info by running xLights in debug mode (xLights -d) but the output on the terminal didn't really show any errors when it crashed. I used my Game of Thrones sequence in the video because that is where I discovered it, but I also tried it on a clean animation sequence (I can provide a video of that as well if need be).

Let me know if there is anything else I can do to help!

**Comment by AzGilrock** [comment]
I'm having trouble seeing it from the video but is the effect actually selected (edge lines turn purple) when you do the copy?  I was working without a timing track active so if you didn't have it selected when you did the copy and tried to do a paste then its pasting garbage and probably in a different part of that function I fixed.  Try the paste that's failing without a timing track active and see what happens.  Maybe that's the clue.

**Comment by AzGilrock** [comment]
Ok I think I see where it can crash.  In EffectsGrid.cpp line 2030 it's accessing the 7th member of the data in the copy string so if you didn't have an actual effect selected when you copied it can crash there.  I will have to add similar protection like I did at line 2167.  I can't fix this till later.

**Comment by m00dawg** [comment]
Womp, sorry, I tried to find the first working capture tool I could to get it out to you and the one I used doesn't have zoom or anything fancy to make it easier to see. But yes I did select it (lines turned purple). It bombs without a timing track as well so if you like I can bust out a video without one (and/or put a morph in between two timings) if you need to verify. You can't see it visually from the video, but I did a CTRL-C to copy and CTRL-V to paste. Also, if it helps, I can show a working example using, say, the chase effect using the same steps.

**Comment by AzGilrock** [comment]
So are you saying it only crashes with a Morph effect?

**Comment by m00dawg** [comment]
Correct, here's an update video showing both (and on a clean Animation sequence so it's easier to see hopefully):

https://www.youtube.com/watch?v=ZqyT_gbGpic

**Comment by AzGilrock** [comment]
Too bad it doesn't seem like the crashes on Linux are providing a log4cpp file.  There should be no difference in a paste based on the type of effect so something weird is going on there.

**Comment by m00dawg** [comment]
I can test it on Windows and OS X as well but don't have any build tools setup for either so don't have an easy route to test from the master git branch. OS X shouldn't be too hard to compile and test though. I have zero build tools on Windows unfortunately. May take me a bit to test OS X but I can certainly give it a go if need be.

**Comment by AzGilrock** [comment]
For the problem you're showing it should be happening in the latest release...you shouldn't need to build code.  If you don't see it then it's probably a Linux only issue.

**Comment by m00dawg** [comment]
:+1: I'll try to knock that out later today then.

**Comment by AzGilrock** [comment]
I notice you keep pasting on the exact same row when it crashes.  Its best to try to do things differently to isolate a pattern.

**Comment by m00dawg** [comment]
Also valid point. Tried it on a few other channels, including some "dumb AC" (Renard) channels. Same result. I also tried using the right click menu and doing a Copy / Paste that way. Same results across all those tests.

**Comment by AzGilrock** [comment]
Since we aren't getting a log can you open an empty text file and do the Paste into the document and post it here?

**Comment by m00dawg** [comment]
Hah I didn't know I could do that! Well that's neat! Here's the results:

#################################
Single Strand:
CopyFormat1	0	1	1	0	-1	NO_PASTE_BY_CELL
SingleStrand	E_CHECKBOX_Chase_3dFade1=0,E_CHECKBOX_Chase_Group_All=0,E_CHOICE_Chase_Type1=Left-Right,E_CHOICE_SingleStrand_Colors=Palette,E_CHOICE_Skips_Direction=Left,E_NOTEBOOK_SSEFFECT_TYPE=Chase,E_SLIDER_Color_Mix1=10,E_SLIDER_Number_Chases=1,E_SLIDER_Skips_Advance=0,E_SLIDER_Skips_BandSize=1,E_SLIDER_Skips_SkipSize=1,E_SLIDER_Skips_StartPos=1,E_TEXTCTRL_Chase_Rotations=1.0,E_VALUECURVE_Chase_Rotations=Active=FALSE|,E_VALUECURVE_Color_Mix1=Active=FALSE|,E_VALUECURVE_Number_Chases=Active=FALSE|	C_BUTTON_Palette1=#FFFFFF,C_BUTTON_Palette2=#FF0000,C_BUTTON_Palette3=#00FF00,C_BUTTON_Palette4=#0000FF,C_BUTTON_Palette5=#FFFF00,C_BUTTON_Palette6=#000000,C_BUTTON_Palette7=#00FFFF,C_BUTTON_Palette8=#FF00FF,C_CHECKBOX_Palette1=1,C_CHECKBOX_Palette2=1	600	6150	13	-1000	NO_PASTE_BY_CELL

Morph:
CopyFormat1	0	1	1	0	-1	NO_PASTE_BY_CELL
Morph	E_CHECKBOX_Morph_End_Link=0,E_CHECKBOX_Morph_Start_Link=0,E_CHECKBOX_ShowHeadAtStart=0,E_NOTEBOOK_Morph=Start,E_SLIDER_MorphAccel=0,E_SLIDER_MorphDuration=20,E_SLIDER_MorphEndLength=1,E_SLIDER_MorphStartLength=1,E_SLIDER_Morph_End_X1=0,E_SLIDER_Morph_End_X2=100,E_SLIDER_Morph_End_Y1=100,E_SLIDER_Morph_End_Y2=100,E_SLIDER_Morph_Repeat_Count=0,E_SLIDER_Morph_Repeat_Skip=1,E_SLIDER_Morph_Stagger=0,E_SLIDER_Morph_Start_X1=0,E_SLIDER_Morph_Start_X2=100,E_SLIDER_Morph_Start_Y1=0,E_SLIDER_Morph_Start_Y2=0,E_VALUECURVE_MorphAccel=Active=FALSE|,E_VALUECURVE_MorphDuration=Active=FALSE|,E_VALUECURVE_MorphEndLength=Active=FALSE|,E_VALUECURVE_MorphStartLength=Active=FALSE|,E_VALUECURVE_Morph_End_X1=Active=FALSE|,E_VALUECURVE_Morph_End_X2=Active=FALSE|,E_VALUECURVE_Morph_End_Y1=Active=FALSE|,E_VALUECURVE_Morph_End_Y2=Active=FALSE|,E_VALUECURVE_Morph_Repeat_Count=Active=FALSE|,E_VALUECURVE_Morph_Repeat_Skip=Active=FALSE|,E_VALUECURVE_Morph_Stagger=Active=FALSE|,E_VALUECURVE_Morph_Start_X1=Active=FALSE|,E_VALUECURVE_Morph_Start_X2=Active=FALSE|,E_VALUECURVE_Morph_Start_Y1=Active=FALSE|,E_VALUECURVE_Morph_Start_Y2=Active=FALSE|	C_BUTTON_Palette1=#FFFFFF,C_BUTTON_Palette2=#FF0000,C_BUTTON_Palette3=#00FF00,C_BUTTON_Palette4=#0000FF,C_BUTTON_Palette5=#FFFF00,C_BUTTON_Palette6=#000000,C_BUTTON_Palette7=#00FFFF,C_BUTTON_Palette8=#FF00FF,C_CHECKBOX_Palette1=1,C_CHECKBOX_Palette2=1	2500	7500	8	-1000	NO_PASTE_BY_CELL
#################################

I provided a single strand for a working comparison. This was on an Animation sequence where I put both a morph and single strand on some channels then did a Copy and paste into a text file of each effect.

**Comment by m00dawg** [comment]
Just tested latest build available from xlights.org on Windows and I am able to copy/paste and reproducing the above steps does not cause a crash.

**Comment by AzGilrock** [comment]
That's what I was afraid of.  I won't be able to troubleshoot if it won't crash for me.

**Comment by m00dawg** [comment]
Hehe me too :) I can't think of what more to do on the Linux side, but if I come up with something I'll share it. In the meantime, I know how to work around it, and can use Windows if I really need to be cutting and pasting lots of Morph effects. It'll work for the Holidays :) Thanks for looking into this Gil!

**Comment by m00dawg** [comment]
Since it looks like xLights outputs more debugging info, I thought I'd provide an update to this issue. As before, placing a Morph on one track then doing a copy paste of that effect to another track causes xLights on Linux to crash for me (as of commit 2ca4df85d2f19ad577f9cda8964be6a934a01a49). As noted previously, I still have the work-around of booting up Windows when I have to do a lot of Morph work but thought I would provide the latest crash report anyway in case it proved helpful.

[xLights_dbgrpt-29422-20161014T215701.zip](https://github.com/smeighan/xLights/files/530726/xLights_dbgrpt-29422-20161014T215701.zip)

**Comment by AzGilrock** [comment]
So every other effect type will copy/paste just fine?  There really shouldn't be any difference between doing a copy/paste between any of the effects.  The only thing that can change is the length of the data being pasted.  So a lot of value curves were added to the Morph effect so maybe its character length is longer than the others and Linux has a problem with that.

**Comment by m00dawg** [comment]
Actually it does look like a few others crash too. So far:

DMX
Fan
Morph

But, weirdly, after I ended up going through every effect and copy/pasting as well as copying their contents to a textfile (attached), but when I went back to re-test the above 3, they ALL worked without crashing across multiple channels. If I restart xLights and paste a morph from my textfile that would previously crash it would work - multiple times. In fact, once I copy/pasted from the textfile onto a channel, I wasn't able to make the morph effect reliably crash by copy/pasting other morphs in the sequence.

But it looks like I can reliably get it to crash if I update the palette of an existing morph and try to copy/paste that directly from xLights. If, however, I copy the contents to a textfile first, then copy it back over into xLights that does NOT crash.

Seeing if I can distill this down a bit:

- Starting xLights, creating a new morph and copy/pasting that in xLights directly = CRASH
- Copying a Morph effect to a textfile first and then back to xLights = WORKS
- Copying a Morph effect to a textfile first then back to xLights and then re-selecting and copy/pasting that effect in xLights = WORKS
- Updating an existing morph from a previous copy/paste test by changing the palette and copy/pasting that in xLights directly = CRASH
- Updating an existing morph from a previous copy/paste test by changing the palette and copying that to a textfile first then back to xLights = WORKS

To be clear, when I say "copying to a textfile and back" I mean copying the text of the copy then re-selecting said text and recopying it. Also I tried some of these tests with DMX and Fan with the same results.

I'm not sure if that makes a lot of sense or not but hopefully it helps!

[xlights-copypaste.txt](https://github.com/smeighan/xLights/files/531351/xlights-copypaste.txt)

**Comment by cjd** [comment]
Does this still occur?
There were a number of fixed to the debugging code that should have fixed this up a while ago

**Comment by m00dawg** [comment]
Appears to be yup! I created a much of morphs in one of my shows just now using the latest git pull and works like a champ!

**Comment by cjd** [comment]
Excellent - I'll close this off then
