### ISSUE TITLE
import effects selection process

### ISSUE THREAD

**Issue by jnealand** [smeighan/xLights#696]
When selecting a model to import, a dropdown box opens that allows one to scroll the models that can be imported.  Once you select a model the dropdown closes, but the selection still scrolls if you move the mouse wheel.  This is a problem since once a selection is made we scroll to the next model where we want to pick a model to import and if you are using the mouse wheel to do that scrolling you are changing your previous selection and may not notice that this is or has happened.  Would like to have the selection process end once a model is selected and no scrolling allowed for that window anymore without another click in that window.

**Comment by keithsw1111** [comment]
Just like the annoying tripple click to drop the dropdown box this is built in behaviour that I dont think we can easily change.

**Comment by AzGilrock** [comment]
Just remove the word "easily" from your reply....it give them hope it can be changed...lol.

**Comment by jnealand** [comment]
From back in my old MS Access days.  I remember that there were combo boxes and list boxes.  I just tried a list box in Access and while the focus remains the mouse wheel does not scroll the entries after selection.  But I don't know if that is true in this software.  Just a thought

**Comment by AzGilrock** [comment]
Closing since the import dialog/process has been completely reworked.
