### ISSUE TITLE
dragging the main window larger (repeat of closed #69)

### ISSUE THREAD

**Issue by mararunr** [smeighan/xLights#70]
Sorry but I'm still getting the same result with the 9 Mar build on my windows 7 machine.

![image](https://cloud.githubusercontent.com/assets/11252070/6588241/e2b19c2e-c75c-11e4-9103-bcbdac5c74e9.png)

**Comment by AzGilrock** [comment]
You sure Aero is turned off?  I'm having trouble figuring out a way to cause this.

**Comment by mararunr** [comment]
My apologies, didn't update the new shortcut when I installed the new build....that being said, though it's still a bug, right?  I mean, I don't have to change the shortcut for other programs to get them to work correctly.  Or do you feel this is all wrapped up in bug #58?  I'm good either way.  By the way, hopefully you saw that I believe #64 is fixed with latest build.

**Comment by AzGilrock** [comment]
Yep the other issue is the same thing.  It's an issue when Aero is on so it applies to both Win 7 & 8.  Actually there are programs that force you out of Aero mode like try running Teamviewer but it is something we want to fix.  I'm closing this one because #58 covers the problem we need to fix.

**Comment by mararunr** [comment]
Re-tested with 4.0.9 - no issue
