### ISSUE TITLE
Converson from .fseq to .lms not working .49

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#702]
Was trying to show how to convert a .fseq file to a .lms file and have had some trouble.  It worked fine the other day.  Today I have 3 or 4 files that will not open in LOR

See this video post for specifics.
https://www.facebook.com/relxerd/videos/10153877722754212/?permPage=1

Thank you
Clyde

**Comment by keithsw1111** [comment]
Clyde ... did you get to the bottom of this?

**Comment by Clyde-L** [comment]
Seems I can make conversions alright again.  I'm in .50 now.  Still not sure what the problems were or if there were issues with the computer at the time.  I will go ahead and close out this issue.  Thank you for looking into it for me.
