### ISSUE TITLE
Enhancement Request: Export all model info including Size/location and Appearance.

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#704]
It would be good to be able to export the size/location and appearance info for a model in the event something gets moved and data saved before an undo.

**Comment by keithsw1111** [comment]
We already back everything up ... many many times.

**Comment by MrChristmas2000** [comment]
I am refering to the 'Export Model' as described in the xLights 2016.45 manual page 131

**Comment by keithsw1111** [comment]
Details like location only have meaning to xlights internally and this is already liberally backed up. Adding it to the model export would not add any value to the user.
