### ISSUE TITLE
Mac - coming out of sleep mode 

### ISSUE THREAD

**Issue by drlucas** [smeighan/xLights#705]
When I am working on a sequence, and put my mac book pro to sleep and wake back up, the play control under the sequencer tab no longer functions.

**Comment by drlucas** [comment]
I found more details on this problem...what is happening is when the audio device changes the play control no longer works. for example if i'm using bluetooth headset and switch to normal speakers the bug occurs.

**Comment by AzGilrock** [comment]
There was a fix for Mac audio in the last release.  Reopen if it did not fix this issue.
