### ISSUE TITLE
Enhancement Request: Add a single channel matrix option

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#708]
<edit>
Could we add a single channel matrix option that works as fluidly as the current RGB matrix option?  I understand this would take some time to work on.  

<original>
I have tried several times to build a single channel matrix using a 6 X 8 (6 polls X 8 channels).  The matrix model will only recognized 3 channel RGB and not single channel,  I have to create a custom model to work around this.  I tried 3 different models and no luck.

![screenshot 2016-10-02 21 42 16](https://cloud.githubusercontent.com/assets/12719816/19025603/1723dd9c-88e9-11e6-85f5-a4a044c8b011.png)

**Comment by AzGilrock** [comment]
I can't find anything wrong.  I created a vertical matrix with 6 strings 8 nodes per and single color white and it responds to effects.  Are you using the right color effects to trigger it?

**Comment by Clyde-L** [comment]
Yes, it is a white matrix... and using white to render the effects.

**Comment by AzGilrock** [comment]
Well it worked when I tried it.  You'll need to show a video and maybe provide files that aren't working.

**Comment by Clyde-L** [comment]
Here is a node preview.  This does not look correct. Or maybe I'm building it wrong?

![screenshot 2016-10-05 22 08 57](https://cloud.githubusercontent.com/assets/12719816/19138231/55b65c40-8b48-11e6-8fad-2bdbe7de601d.png)

**Comment by AzGilrock** [comment]
Ok if you want to change the issue description to be the node layout isn't drawing correctly I'll agree but it's not having any effect on the operation of the model.

**Comment by Clyde-L** [comment]
Gil can you screen print how you build the matrix please?

**Comment by AzGilrock** [comment]
Same as yours but I used vertical.  What exactly isn't working right?

**Comment by Clyde-L** [comment]
not able to run a chase up and down or left and right.

**Comment by Clyde-L** [comment]
See the problem is that the model shows only 6 channels are used, and not 48 like it should.  There is no configuration I can come up with where I'm getting my 48 channels and the model is correct.  

If I change this to a standard RGB model, the model works perfectly with the settings.  But, it now has 48 pixels x 3 channels.

**Comment by Clyde-L** [comment]
Video posted here in the FB group
https://www.facebook.com/relxerd/videos/10153901808464212/?permPage=1

**Comment by AzGilrock** [comment]
I believe Single Color was always designed so that a string is one channel.  The number of strings is always the number of channels.

**Comment by keithsw1111** [comment]
Closing because this is behaving as expected.
