### ISSUE TITLE
Fire effect height textbox entry

### ISSUE THREAD

**Issue by Phrog30** [smeighan/xLights#709]
Using 2016.50, the fire effect height textbox won't allow manual entry.  The slider works fine.

Example, current value is 40, backspace and the code will automatically enter a value of 10.  Example, highlight the current value and no matter what is entered it automatically generates a 10 or 100 (one character is 10, two characters is 100).

**Comment by cjd** [comment]
It was failing because it had to be between 10 and 100. So as any change to text field temporarily put the size one or three digits (and so outside the range) it forced it to 10 or 100.
This is fixed up now by allowing the field to go < 10
