### ISSUE TITLE
Some models don't display correctly on the model preview window

### ISSUE THREAD

**Issue by AzGilrock** [smeighan/xLights#71]
I noticed a matrix I created not displaying the correct number of row and columns on the model preview tab.  The screenshot shows it's correct on the preview tab but not the preview window.
![xlightsissue](https://cloud.githubusercontent.com/assets/2024669/6588851/10f22886-c755-11e4-9285-a37401a5e8ec.png)

**Comment by dkulp** [comment]
What's the config for the matrix...   I've been testing with a 70x70 matrix and it looks ok in both.

**Comment by AzGilrock** [comment]
I had it set as Vert Matrix, RGB Nodes, 85 strings, 64 nodes per string, 1 strand per, start channel 1, Bottom left.  I think it did this with Horz and Vert.

**Comment by dkulp** [comment]
I still cannot reproduce this.   Can you hit the "Render All" button and see if it fixes itself?

The only way I see this is if I change my grid model from the 70x70 to the 85x64 you have and then forget to rerender.

**Comment by AzGilrock** [comment]
I don't get home till late tonight but I'm sure that's probably it.  I've only been thinking about hitting the render when I need to refresh imported data.  I didn't think about needing to hit it when models are added or modified.  Now it makes sense why initially I was seeing a tree shape showing up on a rectangle.   This all happened while I was trying to create a demo video so it totally screwed up what I was trying to do.  I was like delete that video I can't show that disaster....lol.

**Comment by stevegiron** [comment]
From within the sequencer tab, I can create a new sequence, and add 2 models. Effects will render to the model display for a tree shape but not a H or V matrix.

**Comment by AzGilrock** [comment]
I've confirmed there really is an issue even if you hit save or render.  Maybe it's a Windows only issue since Dan doesn't see it.  In this screenshot the morph should have had a perfect hourglass shape.  There are 11 columns missing.
![modelpreview](https://cloud.githubusercontent.com/assets/2024669/6652511/6d600e18-ca2e-11e4-89f9-63c7afd1f68c.png)

**Comment by dkulp** [comment]
Can you attach the xlights_* and the xml?  I can take a look if I can reproduce here. 

Also, what happens if you make the window smaller?  Could it be the same aero cut-off thing you are seeing on the grid?

**Comment by AzGilrock** [comment]
This turned out to be me not having enough channels setup in the setup page.  The only warning we currently have is if you try to play it in the preview it gives the message about not enough channels.  Maybe we should add a warning when the user creates the model.

**Comment by dkulp** [comment]
I just added a warning that will notify you when a model exceeds the number of output channels.   This should occur when opening a show folder as well as creating a new model.   Haven't completely tested this though.

**Comment by smeighan** [comment]
This sounds like the warning Dan added closes this issue.
