### ISSUE TITLE
Curtain effect doesn't scale

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#711]
On a 64 strand megatree, the curtain effect appears to only use about 50 strands wide on the tree. I thought it would extend the full width of the tree.

**Comment by AzGilrock** [comment]
Here's a 64 strand tree with a Curtain effect:
http://giphy.com/gifs/26hiryJ7LrVIhPVL2

**Comment by stevegiron** [comment]
Deleted tree, recreated tree, works now.
