### ISSUE TITLE
Enhancement New Spinner Module Type

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#714]
Hi Guys,
Have an idea for a spinner layout.  I suspect this year I will need to use a custom module for this.

![image](https://cloud.githubusercontent.com/assets/9368124/19212451/2faca64c-8d9d-11e6-92f4-fc17c05c1b32.png)

Basically its feed in cable, then fix length of lights, then a feed to the next set of lights and so on.

`----====.====-----====.====-----====.====-----====.====`
The `.` represents the centre of the strip of lights.  i.e. the point at which each strip will cross another strip in the centre of the spinner.

Each strip cross the centre of the spinner.  So if the strips were 1 meter long. The Diameter would be 1m, and the radius 0.5m

This method makes it easy to manufacture a spinner.  The wire lengths between the arms is dependant on the number of arms and the diameter of the circle.  Current xlights assumes the data wire runs up and back each arm.   In the above example it does not.

**Comment by jwylie01** [comment]
What about the poly line model? You could insert 0 length strings between the arms to make the pixels go the direction you need

**Comment by damon-atkins** [comment]
That's a good idea.

**Comment by Clyde-L** [comment]
I typically build a matrix and create my effects on it... then the custom model is what shows in the house preview.

**Comment by damon-atkins** [comment]
Orginal Spinner Code https://github.com/smeighan/xLights/commit/08e9090cb7e6594302bf5e42c49a62215b48d81b

**Comment by damon-atkins** [comment]
Orginal Spinner Code https://github.com/smeighan/xLights/commit/08e9090cb7e6594302bf5e42c49a62215b48d81b by @keithsw1111

**Comment by keithsw1111** [comment]
Given this can be easily done with polyline and it is not the normal way people tend to set up spinners I dont think we should be adding this.

**Comment by damon-atkins** [comment]
@keithsw1111 It's easy to order it from china this way. It saves a person who can not solder from doing it themselves.      As you can order one meter strips join by cable and then cross them over to form the spindle, all without soldering.

**Comment by Clyde-L** [comment]
@damon-atkins  If you need a hand, let me know.  I can help you with this.  email me

Clyde at
leechburglights@gmail.com

**Comment by damon-atkins** [comment]
Thanks Clyde.   I already have the items made from China.   The other benefit is that the centre of the spinal is condense. i.e. no large electrical round connection box in the centre.  From the centre the lights start a 1.5 cm from the centre.

**Comment by keithsw1111** [comment]
@damon-atkins I am not saying dont build it that way ... just saying use the polyline model rather than build extra complexity into the spinner model.

**Comment by AzGilrock** [comment]
This can be done with PolyLine or a Custom model so closing.
