### ISSUE TITLE
PolyLine - trouble grabbing corners for square shape

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#715]
The Poly Line is nice.
Trying to use it to create a square. A good thing is, that unlike windows it does not place light spots on the corners.  

I am having trouble lining it up into square, and also moving it around.   I suspect once its a square, the marks for moving are hidden under the marks for the segments.  When trying to move the whole thing, I end up reshaping it.
Cheers

**Comment by AzGilrock** [comment]
I realized this before it was ever released.  I just grab one corner and move it out of the way if I need to expose one of the side handles.  And you don't use the side boundary corners to move the whole thing....you can just click in the middle of your square and drag it to move it around the screen.  The side handles are only for scaling it and like I suggested just move a corner, scale it, then move it back.

**Comment by AzGilrock** [comment]
This is fixed in the 3D beta branch so I'm closing since it will eventually become mainline code.
