### ISSUE TITLE
Submodel bug issue

### ISSUE THREAD

**Issue by ncosper** [smeighan/xLights#716]
Super small issue I ran into, but if you have a submodel in .49 and you attempt to apply a vertical (middle, top, bottom) curtain effect only one node seems to blink. Other effect seem to work fine on the submodel including horizontal curtain effects.

**Comment by AzGilrock** [comment]
Probably not a bug.  A horizontal single line model would have reacted the same way.  Not all models are suited for every effect setting.

**Comment by ncosper** [comment]
It was actually just being applied to a horizontal matrix which I would have guessed would be appropriate. As I mentioned very small issue but figured I'd put it in since I noticed.

**Comment by AzGilrock** [comment]
So now its a horizontal matrix model and not a sub-model?  I'm sure a curtain will work on a matrix.  But none of our effects that are vertical will work on a horizontal straight line.

**Comment by ncosper** [comment]
No its a portion of a custom horizontal matrix. The parent model is a custom model but is laid out like a horizontal matrix. Its done this way due to the pixel order. In reality the parent model of these sub models is only there for programming purposes, nothing looks like this on my display. The parent model is a duplicate of another custom model that has a different pixel layout. 
Attached a screen of the model with a curtain payout applied to it. Each color basically has one node that blinks. Either black or the other color in the palette. You’ll see those on the top left of each color. 

Nick Cosper | Realty Executives| Associate Broker 
Web: www.NickCosper.com <https://u2405593.ct.sendgrid.net/wf/click?upn=jO8QHYGGCoEsRwCk0a2TAoFLlP0wb7znCYMV7RxWsNNxm80tzdlM-2BzI6U1jccH48_s5UH8bhnBaopYjthcNSRcdiBRgsA7pXMT2Fjo-2F-2FYuK-2Fjp7tVuoWEDvTz4pk2HJWduuO-2FA16KWsPuKce1MjMq30ne-2FXR4-2BR5udYW4qqYxPQCEIP604c0Q6Dzq1iKKA4y3-2B6Zqa9IhwmkNVlv5c0SUQaFwot7ZkaIh0SYSMH4TDPmf90Hh2F-2B8wTsngVocluS-2B3q0nPXMw-2FKG6XaN1hUFRafZ-2FjeY6vc6JMemmvOpVU51NIifdce4jzVnOHiViMSkUmgUiU7l8pQc1AGeRyU1tpbAMvjlEiO2-2B-2FS8o-2BIbe4B-2BUIHBgTtvNhkYGGFCdXyxdTSdyss4jb7vM1efpO9u1Dg-3D-3D> | Mobile: 928-225-9333 | Office: 928-773-9300 | Email: reply@nickcosper.com <mailto:reply@nickcosper.com>
Mailing Address: 15 E Cherry Ave | Flagstaff AZ 86001 | Toll Free Fax: (928) 774-1102


CONFIDENTIALITY NOTICE 
The information contained in this email, including any attachments/information, is for the sole use and reference of the intended recipient and may be legally privileged. It is intended solely for the addressee. Any unauthorized review, use, disclosure or distribution of this email is prohibited. If you received this email in error, please contact the Sender and discard the email.

**Comment by AzGilrock** [comment]
The sub-model is like a horizontal single line model so a vertical curtain isn't going to look like its opening only a horizontal curtain will do that.

**Comment by keithsw1111** [comment]
Is this still an issue?

**Comment by keithsw1111** [comment]
Closed due to no follow up
