### ISSUE TITLE
.50 Crash Musical Sequence 20 FPS 

### ISSUE THREAD

**Issue by ChaseWoofer** [smeighan/xLights#719]
When creating a new musical sequence when set to 20 FPS after the initial setup, play the music and within 3 sec it crashes with the attached reports.  If you set the sequence to 50 or 100 FPS on setup there is no issue.

[xLights_dbgrpt-28412-20161012T174126.zip](https://github.com/smeighan/xLights/files/525714/xLights_dbgrpt-28412-20161012T174126.zip)

**Comment by keithsw1111** [comment]
Is this still an issue? My intuition says this was a memory issue which the 64 bit version should have fixed.

**Comment by keithsw1111** [comment]
Closing due to no follow up.
