### ISSUE TITLE
After clicking the save button lost all ability to open, close, etc

### ISSUE THREAD

**Issue by jnealand** [smeighan/xLights#72]
Mar 10th release, 1st file I tested.  Opened and converted the file,  hit save and the area with the file icons went all black and also covered up the word portion of the menu in that area.  All that was left was the word help.

**Comment by jnealand** [comment]
Also could not exit the program using the upper right hand exit button.  And the blue line that says sequence setting extended across both of my monitors (only the blue line.  Also could not close the program by right clicking on the icon in the task bar and using the close window option.  Had to go to task manager and end task.

**Comment by jnealand** [comment]
Tried for a second xml file and it converted correctly,  Told me there was not media file, but it was in the folder.  Selected the media file, filled in some of the meta data, closed the sequence settings windiow, hit play and could hear the music, but could not see anything in the model preview for any of the models.  clicked over to the preview window and the file was not there.  Clicked the save button and while I did not get the big black window, the file buttons and the menu line all became greyed out.  Clicking the exit button did close the program.

**Comment by jnealand** [comment]
3rd try -After restarting the program opened a 3rd xml file, slected the media file the program crashed.  I quit testing for now.

**Comment by AzGilrock** [comment]
If you want to email me the xlights_networks.xml, xlights_rgbeffects.xml, and the xml for the sequence I can try it out and see if I get any crashes.  Sometimes we developers have everything working great in our one of two test sequences and don't hit all the boundary conditions.

When it searches for the media file it actually looks in several places.  I should create a flowchart cause it's kinda complex.  But if it can't find the media file listed inside the file it opened currently I think I have it using the filename to search for an mp3.  So if you're like Sean and have a file called TestForCrash.xml with an audio file named Carol of the Bells and it doesn't find it at the path listed ist starts searching for TestForCrash.mp3.  Maybe we need to switch that to use the actual name that was listed but drop the path off of it.  I think I originally just did what Sean came up with.

**Comment by dkulp** [comment]
As an FYI:  this is something I've been struggling with a bit and did commit a few changes.  For me, my big issue has been "windows" paths in the XML  For example, if the XML has "C:\Users\dkulp\foo.mp3", when I load that in the Mac version of xlights, it doesn't recognize ANY of that as "path" so it looks for a file of that whole name.  I've done a few things to try and strip off the file name "foo.mp3" and then start applying some of the search logic.

**Comment by jnealand** [comment]
I have not seen this problem for a long time, I think we could close it.
