### ISSUE TITLE
Idea: Move Tool, Rotate Tool, Resize Tool etc.

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#724]
Instead of having to click items a certain way with shift key or Alt Key  etc.  
How amount Icon's which represent different operations in the layout screen, so when you click and press hold the mouse, the expect operation happens.
e.g.
Move
Rotate 
Resize Keep Aspect Ratio.
Resize No Aspect Ratio.
Edit (.e.g Poly Module)
Clone
etc
Also may help reduce the size of the Context Menu (left click), so in move mode only alignment options appear.

Anyway its just a thought.

**Comment by AzGilrock** [comment]
I'm going to close this because I've added Move, Scaling, and Rotate tools in the 3D branch of the code.
