### ISSUE TITLE
Enhancement: Layers Setting Transformation

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#727]
I would like to have the option added to the Transformation menu.  I would like to be  able to render effects at a 45º angle.  Spiral works great but would love to add a morph to go diagonally across the mega tree or whole house model.  The option of 45º  Clockwise or Counter Clock wise would be really nice.  I'm just not getting the look I want with the Spiral effect.

Thanks!

Clyde

**Comment by AzGilrock** [comment]
A morph can already be set to go any angle with the rotation stuff.

**Comment by AzGilrock** [comment]
I mean "without"

**Comment by Clyde-L** [comment]
I'm having trouble doing this with a custom model.  The effects assist does not show up for it

**Comment by AzGilrock** [comment]
You gotta make the window bigger.

**Comment by Clyde-L** [comment]
Ok got it, but still can get the full prop to render from the very bottom left corner to the top right corner without skipping pixels.  Pixels on the top left and bottom right are not being activated.

**Comment by AzGilrock** [comment]
It can be done....might take 2 morphs.  Gotta get creative....hint...use the Repeat option.

**Comment by Clyde-L** [comment]
Yeah, still not having luck trying to use it with the repeat.

**Comment by AzGilrock** [comment]
So if you rotate a Morph its still not going to fill the corners unless you can upscale it.

**Comment by keithsw1111** [comment]
I thought there was a wipe transition which could do something like this. There is a parameter which controls the angle of the wipe.

**Comment by keithsw1111** [comment]
Can I close this issue?

**Comment by Clyde-L** [comment]
yes

On Sun, Aug 13, 2017 at 5:16 PM, Keith Westley <notifications@github.com<mailto:notifications@github.com>> wrote:

Can I close this issue?
