### ISSUE TITLE
Implement Background Render

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#728]
When a user hits the play button they want to see what their sequence will look like on the preview. Currently that is not guaranteed. Instead you may see a modified render based on the order of effects clicked and in what order they were clicked since the last render all occurred. 

The simple answer to prevent this is to always hit 'Render All' before hitting play but this is not intuitive and if it does not address the problem that if you click the effect rather than the play button you may still see a modified render based on stacking the clicked effect on top of the existing buffer.

I believe that a user should always see in the preview what they will see at their lights, whether they click the effect in the timeline or hit the play button, this means that all effects for the duration of the clicked effect must also be re-rendered.

Proposed Solution
Implement a background render that is always updating the buffer. It would only update the changed model/effects and those occurring during the the same time slice that is overlapping the changed effect (rather than constantly doing a Render All which would be huge performance hit)

**Comment by keithsw1111** [comment]
With the enhancements earlier this year by Dan on the background renderer ... can I close this one?

**Comment by idleup** [comment]
So this was a really big deal last year but I have not done any extensive sequencing to see what the effects are of Dan's enhancements? What did he do that would have addressed this? Lets keep this open for a little longer because I am just about to get started sequencing my 2017 show and I want to see if it is still a problem.

**Comment by keithsw1111** [comment]
Dan improved the smarts which determine what needs to be re-rendered ... its still not perfect but it is better than it was. Down side is there are more situations where you can get crashes which we are slowly whittling down.

**Comment by AzGilrock** [comment]
I think most of the background rendering is sorted out.  Only time something may not be up to date could be some type of copy/paste situation.

**Comment by keithsw1111** [comment]
I am closing this issue ... not because it is invalid but because it is obvious we need to continue to work on this and we are unlikely to ever be 100% happy with it. There is nothing in the ticket which is a new suggestion or not already implemented.
