### ISSUE TITLE
Enhancement request - expand/collapse models in sequencer grid

### ISSUE THREAD

**Issue by Phrog30** [smeighan/xLights#733]
If we add layers we currently can expand or collapse into these layers, one at a time.  Would it be possible to add a collapse and expand all button?  

Thanks for considering.

James

**Comment by keithsw1111** [comment]
I added a collapse all recently ... does it do what you were thinking of? It doesnt work on layers ... it works on strands/nodes. There is already a close button for layers. Can I close this?

**Comment by Phrog30** [comment]
Yes sir, you can close. Thank you for your hard work.

James Landwerlen
