### ISSUE TITLE
Enhancement: Add minute : second option to count down on text effect

### ISSUE THREAD

**Issue by jwylie01** [smeighan/xLights#734]
Add minute second count down on text effect that does not require a specific date.

**Comment by jwylie01** [comment]
I have done the coding and testing the changes now. Just need to find out how to upload the changes

**Comment by stevegiron** [comment]
Contact Sean to be added to the approved developers.

**Comment by keithsw1111** [comment]
Or create a pull request and one of the existing developers may merge it in ... or better yet both and see which gets done first. You are better getting added as a developer if you plan on submitting more stuff.

**Comment by jwylie01** [comment]
Well I think I figured out how to create a pull request. Ended up with 2 requests since I made changes to 2 files so I'm hoping I did it correctly.

**Comment by jwylie01** [comment]
I sent Sean a message to get added as a developer because I will be adding more stuff as time goes on. This addition was something easy I was able to knockout quickly.

**Comment by keithsw1111** [comment]
You should have a change to the panel .cpp file as well to add the combo box entry.

**Comment by jwylie01** [comment]
I changed TextEffect.cpp and TextPanel.wxs. I'm not seeing a panel.cpp.

**Comment by keithsw1111** [comment]
TextPanel.cpp

**Comment by keithsw1111** [comment]
It changes when you change TextPanel.wxs ... or it should

**Comment by jwylie01** [comment]
Okay. Looking at that now.

**Comment by AzGilrock** [comment]
What OS are you using?  I know on Windows I use Git for Windows and you can easily do a "Check for Modifications" to find all the files you've modified.

**Comment by jwylie01** [comment]
found it and added the pull request for that.

**Comment by keithsw1111** [comment]
I have merged it. The only suggestion I would make in future is if every developer tagged every change with a vanity comment the code is going to get really cluttered really quickly. I would only add such tags where you need to explain something odd in the code for future developers. In all other cases we can see in Github who made the change.

**Comment by AzGilrock** [comment]
I think there should have been a way you can do a Pull request for all the files in one request.

**Comment by AzGilrock** [comment]
Yeah I use Git Blame if I need to figure out who modified a line. :)  Sometime I'm the culprit.

**Comment by keithsw1111** [comment]
More often its me :)

**Comment by jwylie01** [comment]
Habit to add the comments. I'll remember to not add them in the future. 

I know how nasty those blocks of code can get thanks to working on software that is 20+ years old.

**Comment by AzGilrock** [comment]
Yeah we had a guy at work that would put comments in the code with other people's names.  I found one that said something like "Add this function due to conversation in the hall with Gil on XX-XX-XXXX."  I was like dude don't be putting my name in the code.
