### ISSUE TITLE
Mask doesn't work with Rotozoom explode

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#735]
Text on layer 1, rotozoom set to Explode 
Color Wash or ON effect on layer 2

Layer 1 blending mode set to 1 is unmask.

The desired result is the text take on the color set on the color chosen for layer 2. This works for about 1/2 of the effect duration, and then the text shows as white.

**Comment by stevegiron** [comment]
![image](https://cloud.githubusercontent.com/assets/10568498/19898349/f3c022ce-a018-11e6-91dc-aa8bb27e4bf5.png)

**Comment by keithsw1111** [comment]
Can you post a sequence that demonstrates this.

**Comment by stevegiron** [comment]
It's working properly w -53. Closing this out.
