### ISSUE TITLE
Using ON effect does not apply properly

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#740]
Using any version above .40 in OSX or PC, using the ON effect does not place the ON effect as default full On.

We have a lot of AC channels defined to DMX channels - LOR/Lynx Express channels. So we define colors for the elements that are plugged in. Blue stuff is ON with blue, White, etc. For the whole house model when we want things all one color or fading up or down on that color selection.

If you use any of the default preset keys, U for UP, D for Down, O for ON. When you start using U that works, and D for down that works. But when you want to use O for ON, it just keeps the last D or U setting. This should default to ON with that keystroke. We had to backrev to .40 in order for this to remain steady.

---If it is not related, I will open another ticket.
What we also saw. If you have a sequence. and you save it, and it has some ON effects that were properly placed using .40. (We were using / openging some sequences from the summer we started using), and if you place more On effects in timings down the sequence, it would replace all the effects in that row with a Ramp effect, either UP or Down. Again, sticking with the O button keeping the latest D or U effect setting.

**Comment by AzGilrock** [comment]
You can alter the result of the "O" key yourself.  Just set an On effect how you want it and then copy it and paste it into Notepad.  Then you will see the format of a couple additional fields that you can paste into your xlights_keybindings.xml file to change the On hotkey.  That's exactly how we will fix it by setting the default for the hotkey but it will require folks to delete their existing keybinding file for it to get the new defaults.

For the second part I have no idea without seeing it in a video and/or having a copy of the old sequence to experiment with.  Sounds unrelated.

**Comment by LightsOnHudson** [comment]
I'll try to get the video created and show it. It is really bizarre.

**Comment by LightsOnHudson** [comment]
My license for my screen record is not working - here is the ZIP file of the sequence.

If you open it in V51 or V52 using PC - and just go to one of the timings area right of any that are already there - and hit the D or UP key for those key effect, and it will change EVERYthING to the left in that model to that same effect. Example: There are snowflakes that have ON channels throughout, placing a D or U key in a timing block will change all that sknowflake model timing areas to that effect. 

V40 does not do this.

**Comment by LightsOnHudson** [comment]
[Archive.zip](https://github.com/smeighan/xLights/files/584334/Archive.zip)

**Comment by LightsOnHudson** [comment]
[EffectChange.zip](https://github.com/smeighan/xLights/files/584627/EffectChange.zip)

**Comment by LightsOnHudson** [comment]
I've attached a video - using Quicktime player record screen - opening the sequence, then moving to the end of the sequence area, and pressing the 'd' key for a down fade and you can see that everything to the left on the same model line changes as well.
This is not happening in v40. So it's the same in both mac and pc. I had V47 on the mac that i created this video and on the pc i have 51 and 52 both exhibiting this

**Comment by AzGilrock** [comment]
If you open the sequence and just hit Render All you'll see it turns them into ramps as well.  But according to your file that is what they are supposed to be.  It's just not displaying the effect background initially until you do something to cause a render.  If you look at the effect database in the file it has this for the second effect so every On effect with a reference of 1 is going to ramp to 0.  Default values are automatically removed so that's why you only see this one non-default value.

    <Effect>E_TEXTCTRL_Eff_On_End=0</Effect>

**Comment by LightsOnHudson** [comment]
I understand, however the UI presents them as ON. How do I fix it to use the benefits of V51 or V52? So is this more than one issue that I need to open? The UI says it is on, the XML says that is is a ramp. I understand now that it rendered immediately when I put a new effect on the line. That I get, but how do I fix the ones that are in there?

**Comment by dkulp** [comment]
After opening the file, hit Render.  Then the UI is correct.   Many of the effects don't know how to completely display themselves until they've been rendered once.  (Single Strand Skips is another big one)   That said, .53 will fix this for the simple On effects.

**Comment by AzGilrock** [comment]
Actually if you expand down to the node level I think you will see that it really is a ramp.  I'm not sure why the top level effect background is not updating till later.  I'd have to check into that.  One question is have you completely saved and rendered and created a .fseq file and then reopened the sequence?  I'm wondering if it needs to pull the data from render buffer and if you open with no .fseq then it has no render data yet.  I'm not at home to try right now or I'd check myself.

**Comment by AzGilrock** [comment]
Ok Dan answered while I was typing.

**Comment by LightsOnHudson** [comment]
Gil:
In V40 it is fine. I can open the XML file do the save, render and all that and re-open it in V40 everything is normal. If I take the original XML or the Rendered Saved XML and open it in V51 or V52 (PC) or V47 Mac, I get the ramping behaviour as we have been discussing. 
We use a lot of AC and appreciate the enhancements of speed saving, and the presentation of the color of the string on the model line. Helps remember what color to set it to to turn on that channel.
Thanks for including it in V53.

**Comment by dkulp** [comment]
v40 does almost the exact same thing.   If you open it in v40 and hit the Render button, the exact same thing happens.   The only difference with v50ish is that the first time we add an effect, instead of just rendering the area of that one effect, we render the model for the entire length of the sequence which is why you see it.

**Comment by AzGilrock** [comment]
I believe the improvement Dan implemented for next release satisfies this issue so closing it.

**Comment by LightsOnHudson** [comment]
Ok, yes, it will be nice to see it as the proper effect when you open the sequence. i clicked on each model line in the sequence and it rendered out. I saved the sequence. close Xlights, and open again and the old effect settings were still visible. Click on the model and they render again. I have Render on save enabled as well. I'll wait for the next release and trust the effects are there properly but not visible properly. thanks guys!

**Comment by dkulp** [comment]
The effects displayed on the grid are just an approximation.   When you open a sequence, SOME effects can display a very rough approximation.   On, Color Wash,  etc... Most cannot display any sort of approximation at all.   After rendering, a better approximation can be used.   Color Wash will be better, on, etc... has more data to be able to do a better job.   Some effects like Single Strand Skips cannot display any sort of approximation until after the first render.  

Thus, even with the next builds, if you want things to use the "best approximations", hit Render immediately after opening it.
