### ISSUE TITLE
Allow user to see numerical value of points on a custom value curve

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#741]
This is important to custom value curves can be created with precision. For instance, if I have a position value set as "20" on a fill effect and want to create a custom curve for the Offset I need to ensure my custom values along the curve never goes past "80" or the effect will wrap to the start of the strand. Likewise if I want the effect to go exactly to the end I need to make sure my custom curve points go to exactly "80" so I need a way to see that.

Two potential options that I see would make sense:

1. When holding the mouse down on a point on the value curve a popup shows the value of that point (however the popup may get in your way to see what you are doing as you drag the point around.

2. Have a box down below the curve graph that shows the value of the currently selected point (probably better option). Currently when you select to use a custom curve all the boxes and values below the graph gray out. There should be a box labeled "Point Value" and the box shows the currently selected points value.

**Comment by keithsw1111** [comment]
This has been implemented
