### ISSUE TITLE
Show effect description on effect mouse over if description is not null

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#745]
Rather than right clicking or exporting effects it would be nice to just mouse over the effect to see the effect description.

**Comment by keithsw1111** [comment]
If we were to do this it would have to be an optional setting as I am not sure I would want popup text turning up every time i clicked on an effect getting in the way of timing marks etc.

**Comment by idleup** [comment]
Maybe add it to the properties panel so it does not popup but at least shows up with a single click.

**Comment by AzGilrock** [comment]
This is similar to #414 where the user wanted start/end time information for the selected effect to be displayed.   However we do this it should probably show all this info.  The LOR hover info feature is kinda nice.  It doesn't pop up right away and it's not activated with a click/selection of an effect.

**Comment by idleup** [comment]
Ah! I actually was thinking about asking for start times, end times, and duration as well, especially important when you have DMX movement and are trying to gauge whether you have enough time during the duration of an effect to complete the movement (e.g., cannot do a spin with my moving head if duration is less than 2.5 seconds). It would be great if you could put duration, description, start time and end time somewhere easy to see quickly.

**Comment by keithsw1111** [comment]
Maybe rather than a popup which might get in the way we could display the details in the status bar.

**Comment by idleup** [comment]
I don't care where it is :-)

**Comment by keithsw1111** [comment]
Implemented

**Comment by idleup** [comment]
Awesome thanks Keith!
