### ISSUE TITLE
Add scroll bars to preview window

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#746]
When out at show location if tweaks need to be made on laptop the preview windows are off the screen and cannot be resized on the laptop (much lower resolution screen than development machine at home). Since it sounds like it would be a big deal to allow resizing the preview windows can scroll bars at least be added? This would need to be both on the preview screen under layout tab and the preview Modals that show up to view the sequence playing.

**Comment by dkulp** [comment]
This only applies to the Layout tab... all the other previews are resizable and scale to whatever size you make their window.

The reason it's not resizable on the Layout tab is due to mouse hit testing.

**Comment by idleup** [comment]
This reminds me, the reason I cannot even see the preview windows when they are open on the laptop monitor is that they are off the screen. My desktop is a 4K monitor so they are likely positioned way out of the laptops viewable desktop. How do I get them back to where I can see them? I am stuck.

**Comment by AzGilrock** [comment]
Did you try the options we give for resetting windows to default or the dock all?  I can't remember which but I know I programmed it to pull all those windows to the first monitor for one of those operations.

**Comment by idleup** [comment]
I thought I tried all those options but will try again to confirm

**Comment by AzGilrock** [comment]
I looked at the code.  Its the one that resets windows to default positions.  What I do is I grab the position of the Model Preview window and then I move all the other previews to x+100, y+100 so position your model preview close to where the others should be pulled to.

**Comment by keithsw1111** [comment]
It would be nice if it was not only scrollable but zoomable as well. Hit testing alone should not be a reason not to do this it is just more complicated as you need to keep adjusting mouse coordinates to the offset and zoom level ... not much different to zoom in the sequencer. Something for 2017.

**Comment by AzGilrock** [comment]
Layout zoom is already in issue #200.  We'll be able to zoom in and fly through the 3D previews.

**Comment by idleup** [comment]
Guys, can you revise the priority of this issue? The zoom is not as important as the scrolling but both would be nice. I was reminded yesterday how I am completely stuck to make changes "in the field" when I was at a customers location and needed to update a model but I could not because the layout preview was created on my 4K monitor with a size of 2000 x 1250 and on my laptop the resolution of the screen is so much lower.

**Comment by AzGilrock** [comment]
I tried to do it last year and had it partially working but I ran into a lot of problems.  Everything is drawn percentage based so if you change the values for the background it should pull the drawing into the size of a smaller monitor.

**Comment by idleup** [comment]
What about scroll bars and not resizing?

**Comment by AzGilrock** [comment]
Just adding scrollbars sometimes is a problem in CodeBlocks.  We don't really have priorities for these issues.  Everyone just works on whatever they want.  After how thing went for me last year I'm probably only going to work on things I want for myself now.

**Comment by idleup** [comment]
Okay I understand, is anyone else willing to add scrollbars so I am not paralyzed to make model changes from my laptop while out in the field?

**Comment by AzGilrock** [comment]
I still don't see why you think you are paralyzed in the field.  You should be able to make your layout fit on the laptop by typing in smaller numbers for the background size.

**Comment by idleup** [comment]
I actually just tried this and it does work for some of the models but some of them it makes the details too small in the model to work with

**Comment by keithsw1111** [comment]
This is in the 3d beta
