### ISSUE TITLE
Hitting CTRL-Z too many times or too quickly causes crash

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#747]
Not sure if it is too many times or too quickly but it crashes if I try to do multiple undo's

**Comment by keithsw1111** [comment]
On which tab? The undo code is quite separate.

**Comment by dkulp** [comment]
And would have closed and opened a new sequence within that time frame?   I discovered the other day that the undo buffer wasn't cleared when a sequence is closed so it tries to undo stuff in the old sequence which is no longer there.  (now fixed for the next build)

**Comment by AzGilrock** [comment]
Matt I know you usually build the latest code.  Did this happen after you upgraded to Dan's checkin to fix the Undo?

**Comment by idleup** [comment]
This happened several times but only when I hit control z multiple times. If I did it once it worked fine. This was in the sequencer. I am wondering if it crashed because it was receiving multiple undo requests before the previous one completed or something like that. You are correct, I do pull and compile the latest code usually the last pull I did was about 2 days ago. I am not sure which commit it was though.

**Comment by AzGilrock** [comment]
Ok so long story short....try to make it happen in the latest code. :)

**Comment by ikke1981** [comment]
Hi, i had this problem last night. If necessary, i have a crash report...

**Comment by AzGilrock** [comment]
ikke1981....Matt builds the latest code checkins so unless you are building your own code you wouldn't have the Undo fix because it's not released yet.  Dan had already possibly fixed this issue before it was reported it's just that the next version was released to everyone yet.

**Comment by keithsw1111** [comment]
Can I close this?

**Comment by idleup** [comment]
Yes
