### ISSUE TITLE
Circles effect:'Update' button changes behavior

### ISSUE THREAD

**Issue by garyhopkins** [smeighan/xLights#750]
Pressing the 'Update' button changes the behavior of the effect even when none of the actual settings are being modified.
[Recording #1.zip](https://github.com/smeighan/xLights/files/604941/Recording.1.zip)

**Comment by AzGilrock** [comment]
Yes every time you update the Circles effect its going to randomly create the circles.  It's kind of strange to display circles on a single line model.  If you want those movements to be fixed in place I'd recommend using Morphs where you specify the exact motions.

**Comment by garyhopkins** [comment]
Ah, that makes sense, thank you Gil. I suppose if I was using this effect on a model that made more sense for circles that it would have been more obvious to me. I will definitely check out morphs!
