### ISSUE TITLE
Bug: Value Curve - Square Wave

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#751]
Adjusting the number of cycles doesn't always result in a on/off transition.  Sometimes the points are shifted and creates a ramp transition.

![square wave](https://cloud.githubusercontent.com/assets/12144876/20504257/30f37760-b00c-11e6-9d5e-1bb28feb1c6a.jpg)

**Comment by keithsw1111** [comment]
This is expected behaviour. Only one value can exist at any point in time so you will always get a transition. On short effects this will be effectively instantaneous. On really long effects it may be noticeable.

**Comment by kppankratz** [comment]
Even though a square wave implies an instant on/off, I can understand the only one value can exist at any point in time.  But the image above shows a inconsistency in the transition points.  Some appear to transition instantly, but other have a longer transition time between the on and off state.

1 cycle = instant transitions
2 cycles = instant transitions
3 cycles = mixture of ramps and instant transitions
4 cycles = instant transitions
5 cycles = instant transitions
6 cycles = mixture of ramps and instant transitions
7 cycles = mixture of ramps and instant transitions
8 cycles = mixture of ramps and instant transitions
9 cycles = mixture of ramps and instant transitions
10 cycles = instant transitions

These were based on a 2 second on effect.  I stretched it out a lot longer, and the results changed slightly, but were still inconsistent.  If I increased the cycle count to 18, some of the transitions actually looked like a letter W and not a up/down transition.  And for a square wave, that seems a bit extreme.

![square wave value curve](https://cloud.githubusercontent.com/assets/12144876/20584921/9d974660-b1bc-11e6-88ea-e6e724bcdae6.jpg)

**Comment by AzGilrock** [comment]
I think you are limited to 40 points horizontally.  If you reduce your cycles it will look better but 18 is pushing the limit of what can be created for a square wave with the VC. If you stick to cycle numbers that divide evenly into 40 it will look perfect.  So the algorithm to calculate the closest square wave based on the number of points we allow is correct.  The only thing we could do is increase the number of allowable points but we save all those points in the sequence file so it starts increasing the file size exponentially.  For now you should just realize the limitations and work within them.

**Comment by kppankratz** [comment]
I wasn't looking for an increase at all, only pointing out there are issues.  Simply doing a few cycles (3) is enough to bring out the inconsistencies.  But that does fall into the dived evenly into 40.

**Comment by keithsw1111** [comment]
I think there may be an issue here. I looked at the code last night and I suspect I could make it better to ensure as fast as possible transitions ... but they will never be instantaneous.

**Comment by keithsw1111** [comment]
Fixed in 2017.16
