### ISSUE TITLE
Consistent crash when trying to save models on Linux

### ISSUE THREAD

**Issue by m00dawg** [smeighan/xLights#752]
xLights seems to be crashing consistently when trying to save models using the latest git pull (commit 2693a07ae50d39fde39363f45c422b3216051655) on Linux. It looks like it may be saving the model changes before it crashes, however.

Debugging output doesn't show much:

tim@lindawg ~/Holiday Lights $ xLights -d
Layout - glVer:  3.3.0 NVIDIA 367.57  (GeForce GTX 1070/PCIe/SSE2)(NVIDIA Corporation)

Included the last few crash dump files as well as my models.
[xLights_dbgrpt-16005-20161124T094446.zip](https://github.com/smeighan/xLights/files/611712/xLights_dbgrpt-16005-20161124T094446.zip)
[xLights_dbgrpt-15285-20161124T093647.zip](https://github.com/smeighan/xLights/files/611711/xLights_dbgrpt-15285-20161124T093647.zip)
[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/611717/xlights_rgbeffects.zip)

**Comment by cjd** [comment]
This would crash on any platform - but is fixed now :)
