### ISSUE TITLE
Number following preset not reflecting layers

### ISSUE THREAD

**Issue by ccsuhr** [smeighan/xLights#753]
![presets 2](https://cloud.githubusercontent.com/assets/17096632/20640882/1f293c7e-b3b1-11e6-9664-b985fa32c0f2.png)
![presets](https://cloud.githubusercontent.com/assets/17096632/20640881/1f2901aa-b3b1-11e6-907d-11ebf4cb5a45.png)

**Comment by keithsw1111** [comment]
I will need your rgbeffects file to reproduce the problem.

**Comment by ccsuhr** [comment]
attached  Did it both on my windows 10 machine and My Fedora 25 machine
