### ISSUE TITLE
Test option Crash

### ISSUE THREAD

**Issue by itstheburns** [smeighan/xLights#754]
I've recently been introduced to xlights. I am using a LOR high voltage Gen3 controller running 1.08 firmware. When using the Test option, it finds the controller, I can cycle through the test patterns. When closing, it crashes and takes out windows.  Even after clicking Stop, both my Windows 10 laptop and Windows 8.1 desktop have crashed and forced a restart.

**Comment by keithsw1111** [comment]
Gil has fixed this ... it will be in 2017.1
