### ISSUE TITLE
Nudge effect "up" broken in 2016.51

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#755]
I'm having issues using the arrow keys to move an effect "up" in a layer.  I have to copy/paste as opposed to using the up key.    I know I'm still in 2016.51, but did not see this mentioned in any of the updated since .51.

**Comment by AzGilrock** [comment]
I saw something similar yesterday.  It only seemed to happen if you have the same effect showing up twice on the grid.  As in you have Arch1 on it's own row and you have Arch1 showing in an expanded group.  I collapsed the group and then the effect would move.  There's been so many issues and changes to try to make those stupid movement keys work I have no idea if its been that way a long time or recently changed.  If someone wants to try every version the last 6 months and narrow down when it changed that would be great.

**Comment by Clyde-L** [comment]
haha :)  It was working fin in .41 and .42.  That's where I hung out for a long time.  So it was after .42

**Comment by AzGilrock** [comment]
This is a situation similar to what I'm talking about.  When you select <Effect 1> there is no difference between selecting it at the upper or lower copy of it.  The effect ends up selected in both places.  We do not keep track of which one you clicked.  So when you try to move it up it gets blocked by <Effect 2> even though it looked like the spots above where you clicked the effect was open.

![selections](https://cloud.githubusercontent.com/assets/2024669/20711511/4159b794-b5fd-11e6-8717-ec6468b219c9.png)

**Comment by AzGilrock** [comment]
Just tried nudge up and it worked.

**Comment by Clyde-L** [comment]
I still have issues with it.  I'm missing the ability to move the cursor up and down once a timing cell is selected.  It "used to" work.  I don't have double groups in my setup the way you have shown above.  I avoid having doubles in any view.  I only use one view at the moment.

**Comment by AzGilrock** [comment]
Ok so its moving a cell highlight that's not working.  You said you couldn't move an effect but I can't get that to fail.

**Comment by AzGilrock** [comment]
Yes I see moving the cell highlight got broken at some point.

**Comment by AzGilrock** [comment]
Looks like it got broke in version 2016.44.  I "fixed" two other nudge problems in that release.  So fix 2 break 1.

   -- enh (gil)     Allow multiple selected effects to be moved up/down and nudged left/right.  Fixes #642.
   -- bug (gil)     Fix offscreen effects not moving when dragged or nudged left/right.  Fixes #637.
