### ISSUE TITLE
FPP update

### ISSUE THREAD

**Issue by RobertVan** [smeighan/xLights#757]
Seems when you upload to FPP and when using the LOR Dongle, it does not config the channels correctly.  It sets up the LOR dongle and places channel counts correctly but on the e1.31 side it starts the channels on the pixel controller back to "1" so that your LOR network and e1.31 overlap.

![15293224_631102834433_136305505_o](https://cloud.githubusercontent.com/assets/24252495/20717655/3230afee-b624-11e6-9249-f3233597a0cf.png)
![15293357_631101167773_1593733490_o](https://cloud.githubusercontent.com/assets/24252495/20717663/3619d946-b624-11e6-9caf-5898a7ed6f01.png)

![15233638_631101212683_52644238_o](https://cloud.githubusercontent.com/assets/24252495/20717640/2ae415aa-b624-11e6-938b-59e37a3def57.png)
#

**Comment by keithsw1111** [comment]
Can you help me by attaching 3 files.
1. The universes file generated by xlights in your show folder when you save the setup tab.
2. The universes file from the fpp when you have fpp setup and working correctly.
3. Your xlights_networks.xml file
Unfortunately I dont use any usb controllers and i am probably missing something in the setup for these controllers.
If you dont know how to acquire #2 above the easiest way is to ftp into the pi and grab it. I would generally use filezilla but in theory you could do it using the browser ... possibly something like ftp://fpp ... the unverses file will be in the media folder ... but i dont have the full path on me.

**Comment by AzGilrock** [comment]
Closing since its old and there was no user response to requests for feedback.
