### ISSUE TITLE
Copy and Paste Model on Layout

### ISSUE THREAD

**Issue by uzelessknowledge** [smeighan/xLights#759]
In version 53 the ability to copy a model and paste in the layout is not functioning. Kevin confirmed this is true, but it does work when he compiled his own code.

**Comment by AzGilrock** [comment]
I've been using the official v53 release so I've seen it working.

**Comment by stevegiron** [comment]
Are you guys referring to the Mac version?

**Comment by AzGilrock** [comment]
Yeah I was gonna say it helps to mention OS...if you don't I assume Windows.

**Comment by dkulp** [comment]
I believe it actually DOES work if you click again on the layout.  The first click to select the model is leaving the Tree view of stuff on the left as the active target.   Click again and you see the hilight selected model in the tree turn from blue to gray.  Hit copy. Hit past.   Should work.    I need to figure out why the tree is retaining the focus though.

**Comment by AzGilrock** [comment]
Yeah that reminds me I have had issues trying to select a model after opening the program.  It seems like once I can get one to highlight then it works fine from then on.

**Comment by uzelessknowledge** [comment]
Sorry, yes Mac. I tired clicking once and twice and clicking off the model to paste. 
I'll give it another try when back at the computer. 
Seems like something change though.

**Comment by keithsw1111** [comment]
I have similar issues Gil ... working around it though ... not enough time to look into it.

**Comment by AzGilrock** [comment]
Yeah I think the bottom line is if it doesn't highlight yellow don't expect it to Copy.

**Comment by uzelessknowledge** [comment]
I tired and it's not working.
https://youtu.be/s1z0SNA9gFc

**Comment by AzGilrock** [comment]
Can you use the keyboard shortcuts?  I'm not sure if clicking that menu bar changes focus.

**Comment by kppankratz** [comment]
What's really odd is if I download and run 53f I can duplicate what Travis is showing in his video.  I have managed to get it copy and paste a model, but not without a lot of clicking here and there hoping something will happen, but never a second/different model.  I've compiled the code as of Sunday and I can copy and paste without issues.  I have sent Travis a link to my compiled version to see if he can do the copy and paste on his machine.

**Comment by dkulp** [comment]
That's likely due to a different version of wxWidgets.   I got a new computer two weeks ago (new MacBook Pro with TouchBar) and part of setting it up was getting wxWidgets compiled.    3.1.0 doesn't compile with the latest XCode on Sierra (which is what I need for the TouchBar stuff) so had to go with the latest from master branch at github.   Quite possible that one of the changes between the 3.1.0 release and the latest on master has changed some of the wxTreeList behaviors.

**Comment by jwylie01** [comment]
I cannot copy and paste in version 53f either. Tried with menu and keyboard shortcuts. I'm runnign a MacBook Pro (early 2011 version) with OS X 10.11 installed

**Comment by uzelessknowledge** [comment]
Dan I see the alpha. Tried it and when pasting I get "XML parsing error: 'syntax error' at line 1"

**Comment by jwylie01** [comment]
I just got the same "XML parsing error" message in 53f as well. I wanted to restart everything and apply all the updates I could to make sure it wasn't related to anything like that.

**Comment by kppankratz** [comment]
I can't even launch 54 alpha.  I get the debug alert window.
![screen shot 2016-11-30 at 9 10 42 pm](https://cloud.githubusercontent.com/assets/12144876/20780628/0dbbd05c-b742-11e6-918c-107ffc07ba54.png)

**Comment by uzelessknowledge** [comment]
54alpha-2 still doesn't allow copy and paste and if you click in the open area twice and try to paste you still see the XML error.

**Comment by dkulp** [comment]
I just uploaded alpha3 that captures the copy/paste/cut events from the treeview.  I THINK that might allow those events to work OK in this case.   If you get a parsing error, open TextEdit or something and paste into there to see what is on the clipboard.  It's likely not even XML and might be an indication of where the data came from.   My cut feeling is the copy never worked and its just some other data.

**Comment by kppankratz** [comment]
It's working for me again.

**Comment by uzelessknowledge** [comment]
Yup that works. However, when you click a model the model is blue in the list. The model is yellow. Press delete and it don't delete. Must click the model again to make the listing turn gray and then you can delete. Just letting you know.

**Comment by keithsw1111** [comment]
Is this still a problem?

**Comment by kppankratz** [comment]
Still working for me.
