### ISSUE TITLE
Export .ESEQ ellipse doesn't open save window

### ISSUE THREAD

**Issue by uzelessknowledge** [smeighan/xLights#760]
When trying to export a model to a .eseq the ellipse doesn't open the save window. If you change the file type the save window can be opened for all other file types.
OS Mac Sierra 10.12.2
xLights v54 alpha 3.

**Comment by kppankratz** [comment]
When you right click on your model and select export model, you should get the following window where you can select the file format.  Type a file name and click OK.  Saves in your show directly.

![screen shot 2016-12-02 at 8 03 11 pm](https://cloud.githubusercontent.com/assets/12144876/20855987/af8eb212-b8ca-11e6-8ba3-1a06ca8655e5.png)

**Comment by uzelessknowledge** [comment]
Right. When you click the ellipse (...) the save window should open so you can choose the save location. No?
At least it worked that way early in the year when I created my Tune To. The other file types let you select a save location.
