### ISSUE TITLE
Random effects adds text to new timing track

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#761]
One universe, one model.  New sequence add random effects adds random text to timing track.

www.stevesimages.com/xl4/random.mp4

**Comment by AzGilrock** [comment]
We should charge for that feature. :)

**Comment by AzGilrock** [comment]
Steve can you try to reproduce this again.  I was about to try to fix it but I followed those steps and couldn't get it to happen.   Maybe we accidentally fixed it along the way.

**Comment by stevegiron** [comment]
Closing this out. Unable to reproduce and I don't use random except for demos.
