### ISSUE TITLE
error running make on fedora 25 current respository

### ISSUE THREAD

**Issue by ccsuhr** [smeighan/xLights#769]
[error fedora 25.txt](https://github.com/smeighan/xLights/files/639143/error.fedora.25.txt)

**Comment by cjd** [comment]
I updated the makefile so this should be fixed without needing cbp2make to be run

**Comment by ccsuhr** [comment]
[clsuhr@sirxlights-localdomain xLights]$ make
if test "`wx-config --release`" != "3.1"; \
then if test ! -d wxWidgets-3.1.0; \
then wget -c
https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.tar.bz2;
\
tar xvfj wxWidgets-3.1.0.tar.bz2; \
fi; \
sed '/^== Patch/d' README.linux |grep -v '^==' | patch
wxWidgets-3.1.0/src/gtk/button.cpp;\
cd wxWidgets-3.1.0;\
CXXFLAGS="-std=gnu++14" ./configure --enable-mediactrl
--enable-graphics_ctx --enable-monolithic --disable-shared
--disable-gtktest --disable-sdltest --with-gtk=2; \
make ;\
fi
if test -n "`cbp2make --version`"; \
then rm -f xLights/xLights.cbp.mak; \
fi
/bin/sh: cbp2make: command not found
make[1]: Entering directory '/home/clsuhr/GitHub/xLights/xLights'
g++  -o ../bin/xLights .objs_lr/models/PolyLineModel.o
.objs_lr/models/Shapes.o .objs_lr/models/SingleLineModel.o
.objs_lr/models/SphereModel.o .objs_lr/models/SpinnerModel.o
.objs_lr/models/StarModel.o .objs_lr/models/SubModel.o
.objs_lr/models/TreeModel.o .objs_lr/models/WholeHouseModel.o
.objs_lr/models/WindowFrameModel.o .objs_lr/models/CircleModel.o
.objs_lr/models/CustomModel.o .objs_lr/models/DmxModel.o
.objs_lr/models/IciclesModel.o .objs_lr/models/MatrixModel.o
.objs_lr/models/Model.o .objs_lr/models/ModelGroup.o
.objs_lr/models/ModelManager.o .objs_lr/models/ModelScreenLocation.o
.objs_lr/models/Node.o .objs_lr/serial.o
.objs_lr/sequencer/SequenceElements.o .objs_lr/sequencer/TimeLine.o
.objs_lr/sequencer/UndoManager.o .objs_lr/sequencer/Waveform.o
.objs_lr/sequencer/tabSequencer.o .objs_lr/tmGridCell.o
.objs_lr/vamp-hostsdk/Files.o .objs_lr/sequencer/EffectLayer.o
.objs_lr/models/WreathModel.o .objs_lr/sequencer/DragEffectBitmapButton.o
.objs_lr/sequencer/Effect.o .objs_lr/sequencer/EffectDropTarget.o
.objs_lr/sequencer/EffectsGrid.o .objs_lr/sequencer/Element.o
.objs_lr/sequencer/MainSequencer.o .objs_lr/sequencer/RowHeading.o
.objs_lr/effects/StrobeEffect.o .objs_lr/effects/SpirographEffect.o
.objs_lr/effects/SpirographPanel.o .objs_lr/effects/StateEffect.o
.objs_lr/effects/StatePanel.o .objs_lr/effects/SpiralsPanel.o
.objs_lr/effects/StrobePanel.o .objs_lr/effects/TendrilEffect.o
.objs_lr/effects/TendrilPanel.o .objs_lr/effects/TextEffect.o
.objs_lr/effects/ShockwaveEffect.o .objs_lr/effects/ShockwavePanel.o
.objs_lr/effects/SingleStrandEffect.o .objs_lr/effects/SingleStrandPanel.o
.objs_lr/effects/SnowflakesEffect.o .objs_lr/effects/TextPanel.o
.objs_lr/effects/SnowflakesPanel.o .objs_lr/effects/SnowstormEffect.o
.objs_lr/effects/SnowstormPanel.o .objs_lr/effects/SpiralsEffect.o
.objs_lr/effects/WavePanel.o .objs_lr/effects/assist/AssistPanel.o
.objs_lr/effects/assist/PicturesAssistPanel.o
.objs_lr/effects/assist/xlGridCanvasEmpty.o
.objs_lr/effects/assist/xlGridCanvasMorph.o
.objs_lr/effects/assist/xlGridCanvasPictures.o .objs_lr/heartbeat.o
.objs_lr/kiss_fft/kiss_fft.o .objs_lr/kiss_fft/tools/kiss_fftr.o
.objs_lr/models/ArchesModel.o .objs_lr/models/CandyCaneModel.o
.objs_lr/effects/VUMeterEffect.o .objs_lr/effects/TreeEffect.o
.objs_lr/effects/TreePanel.o .objs_lr/effects/TwinkleEffect.o
.objs_lr/effects/TwinklePanel.o .objs_lr/effects/VUMeterPanel.o
.objs_lr/effects/VideoEffect.o .objs_lr/effects/VideoPanel.o
.objs_lr/effects/WaveEffect.o .objs_lr/xlColorPickerFields.o
.objs_lr/xLightsMain.o .objs_lr/xLightsTimer.o .objs_lr/xLightsXmlFile.o
.objs_lr/xlColorCanvas.o .objs_lr/xlColorPicker.o .objs_lr/xlGLCanvas.o
.objs_lr/xlGridCanvas.o .objs_lr/xlSlider.o .objs_lr/xlights_out.o
.objs_lr/xLightsApp.o .objs_lr/xLightsImportChannelMapDialog.o
.objs_lr/vamp-hostsdk/acsymbols.o .objs_lr/vamp-hostsdk/host-c.o
.objs_lr/wxCheckedListCtrl.o .objs_lr/vamp-hostsdk/PluginBufferingAdapter.o
.objs_lr/vamp-hostsdk/PluginChannelAdapter.o
.objs_lr/vamp-hostsdk/PluginHostAdapter.o
.objs_lr/vamp-hostsdk/PluginInputDomainAdapter.o
.objs_lr/vamp-hostsdk/PluginLoader.o
.objs_lr/vamp-hostsdk/PluginSummarisingAdapter.o
.objs_lr/vamp-hostsdk/PluginWrapper.o .objs_lr/vamp-hostsdk/RealTime.o
.objs_lr/OptionChooser.o .objs_lr/NewTimingDialog.o
.objs_lr/NodesGridCellEditor.o .objs_lr/NoteImportDialog.o
.objs_lr/NullOutputDialog.o .objs_lr/NetInfo.o .objs_lr/PaletteMgmtDialog.o
.objs_lr/PerspectivesPanel.o .objs_lr/PhonemeDictionary.o
.objs_lr/PixelAppearanceDlg.o .objs_lr/ModelGroupPanel.o
.objs_lr/MIDI/Binasc.o .objs_lr/MIDI/MidiEvent.o
.objs_lr/MIDI/MidiEventList.o .objs_lr/MIDI/MidiFile.o
.objs_lr/MIDI/MidiMessage.o .objs_lr/ModelDimmingCurveDialog.o
.objs_lr/ModelFaceDialog.o .objs_lr/PixelBuffer.o .objs_lr/ModelPreview.o
.objs_lr/ModelStateDialog.o .objs_lr/ModelViewSelector.o
.objs_lr/MusicXML.o .objs_lr/SaveChangesDialog.o
.objs_lr/SeqElementMismatchDialog.o .objs_lr/SeqExportDialog.o
.objs_lr/SeqFileUtilities.o .objs_lr/SeqSettingsDialog.o
.objs_lr/SequenceData.o .objs_lr/SerialPortWithRate.o
.objs_lr/SevenSegmentDialog.o .objs_lr/ShowDatesDialog.o
.objs_lr/RenameTextDialog.o .objs_lr/PlaybackOptionsDialog.o
.objs_lr/PlayerFrame.o .objs_lr/PreviewModels.o .objs_lr/PreviewPane.o
.objs_lr/Render.o .objs_lr/RenderBuffer.o .objs_lr/RenderProgressDialog.o
.objs_lr/ResizeImageDialog.o .objs_lr/DimmingCurvePanel.o
.objs_lr/CurrentPreviewModels.o .objs_lr/CustomModelDialog.o
.objs_lr/DataLayer.o .objs_lr/DimmingCurve.o .objs_lr/ConvertLogDialog.o
.objs_lr/DisplayElementsPanel.o .objs_lr/DrawGLUtils.o
.objs_lr/DrawGLUtils21.o .objs_lr/DrawGLUtils31.o .objs_lr/E131Dialog.o
.objs_lr/ArtNetDialog.o .objs_lr/AudioManager.o .objs_lr/BitmapCache.o
.objs_lr/BufferPanel.o .objs_lr/ChannelLayoutDialog.o
.objs_lr/EffectAssist.o .objs_lr/Color.o .objs_lr/ColorCurve.o
.objs_lr/ColorCurveDialog.o .objs_lr/ColorPanel.o .objs_lr/ConvertDialog.o
.objs_lr/Image.o .objs_lr/Image_Loader.o .objs_lr/JobPool.o
.objs_lr/KeyBindings.o .objs_lr/GenerateCustomModelDialog.o
.objs_lr/LMSImportChannelMapDialog.o .objs_lr/LayoutGroup.o
.objs_lr/LayoutPanel.o .objs_lr/LorConvertDialog.o .objs_lr/LyricsDialog.o
.objs_lr/EffectIconPanel.o .objs_lr/EffectListDialog.o
.objs_lr/EffectTreeDialog.o .objs_lr/EffectsPanel.o
.objs_lr/StartChannelDialog.o .objs_lr/ExportModelSelect.o
.objs_lr/FPPConnectDialog.o .objs_lr/FileConverter.o
.objs_lr/FlickerFreeBitmapButton.o .objs_lr/effects/MarqueeEffect.o
.objs_lr/effects/LifeEffect.o .objs_lr/effects/LifePanel.o
.objs_lr/effects/LightningEffect.o .objs_lr/effects/LightningPanel.o
.objs_lr/effects/GlediatorPanel.o .objs_lr/effects/MarqueePanel.o
.objs_lr/effects/MeteorsEffect.o .objs_lr/effects/MeteorsPanel.o
.objs_lr/effects/MorphEffect.o .objs_lr/effects/FireEffect.o
.objs_lr/effects/FirePanel.o .objs_lr/effects/FireworksEffect.o
.objs_lr/effects/FireworksPanel.o .objs_lr/effects/GalaxyEffect.o
.objs_lr/effects/MorphPanel.o .objs_lr/effects/GalaxyPanel.o
.objs_lr/effects/GarlandsEffect.o .objs_lr/effects/GarlandsPanel.o
.objs_lr/effects/GlediatorEffect.o .objs_lr/effects/PicturesPanel.o
.objs_lr/effects/PinwheelEffect.o .objs_lr/effects/PinwheelPanel.o
.objs_lr/effects/PlasmaEffect.o .objs_lr/effects/PlasmaPanel.o
.objs_lr/effects/RenderableEffect.o .objs_lr/effects/RippleEffect.o
.objs_lr/effects/RipplePanel.o .objs_lr/effects/ShimmerEffect.o
.objs_lr/effects/ShimmerPanel.o .objs_lr/effects/OnEffect.o
.objs_lr/effects/MusicEffect.o .objs_lr/effects/MusicPanel.o
.objs_lr/effects/OffEffect.o .objs_lr/effects/OffPanel.o
.objs_lr/effects/OnPanel.o .objs_lr/effects/PianoEffect.o
.objs_lr/effects/PianoPanel.o .objs_lr/effects/PicturesEffect.o
.objs_lr/VideoReader.o .objs_lr/VAMPPluginDialog.o .objs_lr/ValueCurve.o
.objs_lr/ValueCurveButton.o .objs_lr/ValueCurveDialog.o
.objs_lr/TopEffectsPanel.o .objs_lr/ViewsDialog.o .objs_lr/WiringDialog.o
.objs_lr/XlightsDrawable.o .objs_lr/djdebug.o .objs_lr/effects/BarsEffect.o
.objs_lr/TabConvert.o .objs_lr/StrandNodeNamesDialog.o
.objs_lr/SubBufferPanel.o .objs_lr/SubModelsDialog.o
.objs_lr/SuperStarImportDialog.o .objs_lr/TabPreview.o
.objs_lr/TabSequence.o .objs_lr/TabSetup.o .objs_lr/TestDialog.o
.objs_lr/TimingPanel.o .objs_lr/effects/DMXEffect.o
.objs_lr/effects/DMXPanel.o .objs_lr/effects/EffectManager.o
.objs_lr/effects/EffectPanelUtils.o .objs_lr/effects/FacesEffect.o
.objs_lr/effects/FacesPanel.o .objs_lr/effects/FanEffect.o
.objs_lr/effects/FanPanel.o .objs_lr/effects/FillEffect.o
.objs_lr/effects/FillPanel.o .objs_lr/effects/CirclesPanel.o
.objs_lr/effects/BarsPanel.o .objs_lr/effects/ButterflyEffect.o
.objs_lr/effects/ButterflyPanel.o .objs_lr/effects/CirclesEffect.o
.objs_lr/AddShowDialog.o .objs_lr/effects/ColorWashEffect.o
.objs_lr/effects/ColorWashPanel.o .objs_lr/effects/CurtainEffect.o
.objs_lr/effects/CurtainPanel.o  -lGL -lGLU -lglut -ldl -lX11 `pkg-config
--libs libavformat libavcodec libavutil  libswresample libswscale`
`pkg-config --libs log4cpp` `sdl-config --libs` `wx-config --version=3.1
--libs std,media,gl,aui,propgrid` `pkg-config --libs gstreamer-1.0
gstreamer-video-1.0` -lexpat -rdynamic
.objs_lr/sequencer/MainSequencer.o: In function
`MainSequencer::~MainSequencer()':
MainSequencer.cpp:(.text+0x369): undefined reference to
`xlTouchBarSupport::~xlTouchBarSupport()'
.objs_lr/sequencer/MainSequencer.o: In function
`MainSequencer::SetupTouchBar(EffectManager&, ColorPanelTouchBar*)':
MainSequencer.cpp:(.text+0x7ee): undefined reference to
`EffectGridTouchBar::EffectGridTouchBar(xlTouchBarSupport&, EffectManager
const&, MainSequencer*, ColorPanelTouchBar*)'
.objs_lr/sequencer/MainSequencer.o: In function
`MainSequencer::MainSequencer(wxWindow*, int, wxPoint const&, wxSize
const&)':
MainSequencer.cpp:(.text+0x4732): undefined reference to
`xlTouchBarSupport::xlTouchBarSupport()'
MainSequencer.cpp:(.text+0x5708): undefined reference to
`xlTouchBarSupport::Init(wxWindow*)'
MainSequencer.cpp:(.text+0x5776): undefined reference to
`xlTouchBarSupport::~xlTouchBarSupport()'
.objs_lr/sequencer/MainSequencer.o: In function
`MainSequencer::SetupTouchBar(EffectManager&, ColorPanelTouchBar*)':
MainSequencer.cpp:(.text+0x80b): undefined reference to
`xlTouchBarSupport::SetActive(xlTouchBar*)'
.objs_lr/ColorPanel.o: In function
`ColorPanel::UpdateTouchBarSlider(wxScrollEvent&)':
ColorPanel.cpp:(.text+0xe7): undefined reference to
`ColorPanelTouchBar::SetSparkles(int)'
.objs_lr/ColorPanel.o: In function
`ColorPanel::SetupTouchBar(xlTouchBarSupport&)':
ColorPanel.cpp:(.text+0x382): undefined reference to
`ColorPanelTouchBar::ColorPanelTouchBar(std::function<void (int, xlColor)>,
std::function<void (int)>, xlTouchBarSupport&)'
.objs_lr/ColorPanel.o: In function
`ColorPanel::SetButtonColor(ColorCurveButton*,
std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> > const&, bool)':
ColorPanel.cpp:(.text+0x46a2): undefined reference to
`ColorPanelTouchBar::SetColor(int, wxBitmap const&, wxColour&)'
.objs_lr/ColorPanel.o: In function `ColorPanel::SetDefaultSettings()':
ColorPanel.cpp:(.text+0x4a44): undefined reference to
`ColorPanelTouchBar::SetSparkles(int)'
.objs_lr/ColorPanel.o: In function
`ColorPanel::OnCCChanged(wxCommandEvent&)':
ColorPanel.cpp:(.text+0x88a5): undefined reference to
`ColorPanelTouchBar::SetColor(int, wxBitmap const&, wxColour&)'
collect2: error: ld returned 1 exit status
xLights.cbp.mak:876: recipe for target 'out_linux_release' failed
make[1]: *** [out_linux_release] Error 1
make[1]: Leaving directory '/home/clsuhr/GitHub/xLights/xLights'
Makefile:29: recipe for target 'xLights' failed
make: *** [xLights] Error 2
