### ISSUE TITLE
Add X,Y coordinate text boxes for buffer corners.

### ISSUE THREAD

**Issue by jwylie01** [smeighan/xLights#770]
When trying to layer several waves together to create a stacked look it was hard to keep the buffer size the same between the layers when the corners extend beyond the window border. This caused my sine waves to each be different sizes and not align properly. Using multiple colors and a thicker wave didn't give me the look I wanted. Also layering waves of different thicknesses didn't give me what I wanted as well. 

If we had text boxes showing the current x, y coordinates of each of the corners that we can edit to adjust the buffer selection, then it would be easier to keep the buffer size the same between layers.

**Comment by AzGilrock** [comment]
You mean editing the XML file like me isn't sufficient.... :)

**Comment by jwylie01** [comment]
Didn't think of doing it that way but I would like to make it a little easier to do.

**Comment by AzGilrock** [comment]
Yeah I haven't actually done that but I've thought about it for the same reasons.

**Comment by dkulp** [comment]
Next thing your going to want is value curves on each......

**Comment by AzGilrock** [comment]
Now that's funny.

**Comment by jwylie01** [comment]
No value curves for me. I don't want to get into that much work right now.

**Comment by keithsw1111** [comment]
This is in 2016.56 ... right click subbuffer.
