### ISSUE TITLE
Saving effect presets shows 1 layer regardless of actual number of layers

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#775]
v53 Windows

New setup, single model. Regardless of the number of layers saved with a preset, the value shown next to the preset name is [1]

**Comment by AzGilrock** [comment]
I created one the other day and thought it stayed a [0].

**Comment by stevegiron** [comment]
It's a rating system now. Make a better effect for that value to increase.

**Comment by keithsw1111** [comment]
Duplicate of #753
