### ISSUE TITLE
Not a Bug: Copy and Paste Model Numbering

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#776]
MiniTree02 copy, pasted becomes
MiniTree02-1 Copy this one
becomes pasted as MiniTree02-1-2 

Maybe have a setting for how a person wants to number an item. And then use this to scan existing model names and find a next free number.  e.g.  <separator>NN where separator can be none or user defined.  And number of starting digits e.g. N or NN or NNN

**Comment by keithsw1111** [comment]
I believe this was fixed in 2017.22
