### ISSUE TITLE
Enh: OSX version does not allow effect preset imports of xlights_rgbeffects.xml files

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#777]
Please add this to the OSX version as it is there for Windows.

**Comment by dkulp** [comment]
What do you mean it's not there?  The import button is on the dialog and it seems to work for me.

**Comment by stevegiron** [comment]
xml files are greyed out on the user download version 53

![image](https://cloud.githubusercontent.com/assets/10568498/21276048/7e3407ac-c384-11e6-842f-1cf518141023.png)
