### ISSUE TITLE
Enh: Allow import of *.xml file for presets

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#778]
Please add *.xml for preset imports.

**Comment by keithsw1111** [comment]
I think it is still there ... it wasnt removed.

**Comment by stevegiron** [comment]
More specifically add the wildcard to the drop down option. 
http://www.stevesimages.com/xl4/preset-wildcard.mp4

**Comment by keithsw1111** [comment]
I believe we can close this ... there is no reason to have a *xml file. You either pull it from an rgbeffects file or you use an xpresets file which is the better way to do the sharing steve is trying to do.

**Comment by dkulp** [comment]
Actually, it is fixed.  On OSX, you can ONLY filter by extension.  Thus, to allow selecting xlights_rgbeffects.xml, we have to allow *.xml.

**Comment by stevegiron** [comment]
Thanks to both of you. Keith has sorted me out. I was sending out an
rgbeffects.xml file.  I have changed that to an xpresets file for all
effects. I was unaware the xpresets can contain groups and multiple effects.
