### ISSUE TITLE
crashing on one sequence

### ISSUE THREAD

**Issue by ctmcpeak700** [smeighan/xLights#779]
we have one sequence that every time we do anything (save, change or add effect, etc...) it has been crashing.  i was not having this issue before today.  any suggestions?
[xLights_dbgrpt-9760-20161214T155834.zip](https://github.com/smeighan/xLights/files/653299/xLights_dbgrpt-9760-20161214T155834.zip)

**Comment by dkulp** [comment]
This is crashing within ffmpeg while trying to process your "Go Fish Joy To The World.mp4" video.

**Comment by ctmcpeak700** [comment]
I tried removing the video and it still crashed.  My show is about to start for the night but I'll try again in the morning and post again if it's still crashing.

**Comment by keithsw1111** [comment]
If this is still a problem can you please package your sequence and send it to us otherwise I will need to close the ticket as there is not much else we can do with it.

**Comment by ctmcpeak700** [comment]
My apologies.  The issue is fixed.  It was operator error.

Sent from my iPhone

On May 2, 2017, at 11:43 PM, Keith Westley <notifications@github.com<mailto:notifications@github.com>> wrote:


If this is still a problem can you please package your sequence and send it to us otherwise I will need to close the ticket as there is not much else we can do with it.
