### ISSUE TITLE
Value Curves Broken on single strand effect

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#781]
Currently using 2016.51
I can not get any value curves to apply changes in the single strand effect.  Not sure if this was found yet.    Waiting till after the season to update to the newest version

Thanks
Clyde

**Comment by Clyde-L** [comment]
Played with this for a few hours.  Shut down and restarted computer, now working as it should?  Don't understand why it stopped responding.

**Comment by keithsw1111** [comment]
Neither do I but if we cant reproduce then it will be hard to fix.
