### ISSUE TITLE
Scheduler overlooks sequence 

### ISSUE THREAD

**Issue by ctmcpeak700** [smeighan/xLights#782]
I have a sequence that the scheduler won't play.  It's the first musical sequence in my show.  So now xLights will play my intro and then stop.  I can play the sequence from the sequencer tab and it plays just fine.  If it makes any difference, this is the same sequence that was causing xLights to crash a few days ago. I was finally able to save the sequence.  I have tried rendering, saving, and closing and restarting xLights.  Nothing has worked.

**Comment by stevegiron** [comment]
Help the helpers. Post the sequence somewhere so they can grab it and take a look. Post the link back here. They probably won't guess at it and most use the FPP anyhow.

**Comment by keithsw1111** [comment]
As the scheduler is about to be replaced with the new xSchedule module I am closing this.
