### ISSUE TITLE
Program freezes when performing a left click(select) then fast right click on model row

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#783]
I've repeated a freeze numerous time when left clicking on a row to select it... I'm inserting a layer.  Then I quickly right click to open the insert layer menu.  Instantly xlights responds with a "program not responding".  Sometimes I'll get a choice to ABORT/RETRY but that never works.

Thanks
Clyde

**Comment by stevegiron** [comment]
I've tried to recreate this and can't get it to do that for me. I normally just right click on a layer leaving out the step of left clicking first. I tried left and right clicking as fast as I can w/o issue.

**Comment by Clyde-L** [comment]
I know I do not intend to do the left, then right click... it's a habit from other software.  And dam it, now I can't get it to do it on purpose.  gurrrr.  Got to be something else I'm doing?

**Comment by keithsw1111** [comment]
Can I close this on Clyde.

**Comment by Clyde-L** [comment]
Yes....

On Thu, Aug 3, 2017 at 5:02 PM, Keith Westley <notifications@github.com<mailto:notifications@github.com>> wrote:

Can I close this on Clyde.
