### ISSUE TITLE
Shift Effects Issue

### ISSUE THREAD

**Issue by JMHaro** [smeighan/xLights#784]
I like the shift effects, so I'm trying to use it but there is one issue with them.  It only works on 'displayed' effects.  So if you have effects that are on lower nodes, they don't get shifted unless the Strand node is expanded.  I have a lot of AC lights where I have some props that are created around multiple AC channels so these channels are contained within the Strand1.  I don't know if I'm explaining myself correctly or if you understand what I mean.  But for instance I have icicles running down my driveway.  These icicles consist of 9 segments that I control each segment as a single channel.  The prop I have built for each side of my drive way is something like "DW Icicles Left" which has 9 strings Single Color.  So the prop gets built with a single item that contains 9 nodes.  And I set the features on these nodes directly.  See the attached document that has some images explaining it and showing the issue.  Thanks for the capability anyway.
[Shift Effects Issue.docx](https://github.com/smeighan/xLights/files/665401/Shift.Effects.Issue.docx)

**Comment by AzGilrock** [comment]
Sorry this isn't going to change.  Then entire infrastructure of the program only gives me an array of rows that aren't collapsed.

**Comment by AzGilrock** [comment]
I actually fixed this recently.  I misunderstood the issue back then but then ran into it myself and realized it wasn't acceptable to only shift visible effects.

**Comment by JMHaro** [comment]
Thank you.
