### ISSUE TITLE
Mac v55 crash on render

### ISSUE THREAD

**Issue by uzelessknowledge** [smeighan/xLights#785]
I have tried my sequences and some shared ones from Chris Debenham. Starting with v55 on the Mac some are crashing when rendering. When (if) I can get a sequence to render then I'm able to get the others that cause a crash to render without crashing. Attached is the last crash I had.
[xLights_dbgrpt-480-20161221T170511.zip](https://github.com/smeighan/xLights/files/667584/xLights_dbgrpt-480-20161221T170511.zip)

**Comment by keithsw1111** [comment]
This is mine ... it is crashing in the fireworks effect code I changed. I will take a look tonight

**Comment by dkulp** [comment]
Yea... you cannot do anything with the panel on the background render thread.    Those calls to set panel things need to be removed.

**Comment by keithsw1111** [comment]
I didnt think that was called on the render thread ... I thought I copied it from the faces effect .... need to look into it.

**Comment by uzelessknowledge** [comment]
Dan, assuming that was for Keith and not me?
