### ISSUE TITLE
Export/Import models

### ISSUE THREAD

**Issue by Phrog30** [smeighan/xLights#787]
I exported a model with submodels (photo #1), then imported into a new config (photo #2).  I noticed the order of submodels were different.  When I looked at the order of the model file it was correct (photo #3), so it looks like it is getting jumbled on the import.
![1](https://cloud.githubusercontent.com/assets/12203743/21489248/d4476cf2-cbad-11e6-9c03-727e5cbc2493.png)
![2](https://cloud.githubusercontent.com/assets/12203743/21489247/d4473322-cbad-11e6-9d6a-319ee4bf238a.png)
![3](https://cloud.githubusercontent.com/assets/12203743/21489249/d448f4fa-cbad-11e6-8716-42ca1c4aff26.png)

This is not a huge problem.  Just thought I would point it out.

Thanks,
James

**Comment by AzGilrock** [comment]
Just looks reversed to me.

**Comment by Phrog30** [comment]
Correct, I guess jumbled wasn't the best choice of words.

James Landwerlen

**Comment by AzGilrock** [comment]
I'm looking into it...I reproduced it.

**Comment by AzGilrock** [comment]
Ok I see why.  Note to anyone working with the wxXmlNode class.

Using this form of the constructor it insert child at the top:
```
    wxXmlNode *f = new wxXmlNode(ModelXml, wxXML_ELEMENT_NODE, "subModel");
```

So use this constructor and then the AddChild method to append it at the bottom:
```
    wxXmlNode *f = new wxXmlNode(wxXML_ELEMENT_NODE, "subModel");
    ModelXml->AddChild(f);

```

**Comment by AzGilrock** [comment]
Now I need to search whether this occurs in other places.
