### ISSUE TITLE
Bug:  New Buffer Selections

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#791]
I noticed with the additional buffer selections in the layer settings window that you can't select the presets any longer, new or previous, except two.  The only two I can get to work is the full buffer and the new oversized selection.

Self compiled/pre-release version as of 12/30 on Mac OS X.

**Comment by AzGilrock** [comment]
Can you show a screenshot.  I've built the latest code and I don't see any buffer selections.

**Comment by kppankratz** [comment]
![screen shot 2016-12-30 at 7 12 53 pm](https://cloud.githubusercontent.com/assets/12144876/21574988/11499c60-cec4-11e6-967c-cda92b024434.png)

**Comment by AzGilrock** [comment]
Ok thanks...I didn't even know we had that.   Gotta right-click in the window.

**Comment by AzGilrock** [comment]
Hmm...they all seem to work for me.  Maybe OSX issue only.

**Comment by kppankratz** [comment]
Very well could be a OS X issue.  Paging Dr. Dan.

**Comment by dkulp** [comment]
Yea.. likely an OSX issue...  On Windows, you can add the event handler to the root menu and it works for all the sub menus as well.   On OSX, you have to add it to each sub-menu.   That's been a problem in a few locations.

**Comment by cjd** [comment]
Just tested and it occurs on Linux as well (same issue as OSX - so once fixed on OSX should be fixed on linux as well)
