### ISSUE TITLE
Effect Settings Value Modifying - Enhancement

### ISSUE THREAD

**Issue by gmartens** [smeighan/xLights#792]
This example works with most effects. Basically it would be nice if instead of a value instantly going to it's minimum if the user puts in a value to low (or doesn't put a value in at all), it will leave the text box blank, allowing for the user to input the value they want, only after pressing return the minimum and maximum values will kick in, if the user has entered something too low/high.
Here is a video demonstrating.
[Youtube](https://www.youtube.com/watch?v=IOj_WcaDqaY&feature=youtu.be)

**Comment by keithsw1111** [comment]
Fixed
