### ISSUE TITLE
Enhancement Request: select nodes by clicking on them in the submodel dialog

### ISSUE THREAD

**Issue by Phrog30** [smeighan/xLights#794]
Currently, there is a tooltip that shows us the node number.  We can then type that node number in the node ranges text box.  Is it possible to also click on the node in the preview and have it entered into the text box?

Thanks,
James

**Comment by keithsw1111** [comment]
If we were to do so we would also need to add a comma as it would need to be valid but i suspect most users most of the time are entering channel ranges ... so does this really save that much effort?

**Comment by Phrog30** [comment]
Yes, it would save a lot of effort. I was modeling Matt Johnson's snowflake
the other day and most of what I was entering was not contiguous.

I would consider this a very low priority enhancement. What you currently
have is fine, but I think there is room to improve. Obviously, it's your
call on what is necessary. Thanks for considering.

James Landwerlen


On Jan 2, 2017 3:02 PM, "Keith Westley" <notifications@github.com> wrote:

If we were to do so we would also need to add a comma as it would need to
be valid but i suspect most users most of the time are entering channel
ranges ... so does this really save that much effort?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/smeighan/xLights/issues/794#issuecomment-270019967>,
or mute
the thread
