### ISSUE TITLE
Export inbuilt models as custom models

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#800]
In the layout tab, create a 3 layer star model.
Click on the element in the preview window, right click for node layout, 
(in my node layout in xlights the node layout did not match how it was strung on my star frame, it was close, and I did have the same start position on my frame as in the xlight node layout)
I would like to either:
be able to edit that node layout
or
be able to export that node layout, and either import it into a spreadsheet or import it into the custom model area, make my tweaks and save it as a custom model, or import / overwrite my star model.
Thanks for taking time to read this.  You all have done great work !!

**Comment by keithsw1111** [comment]
This will be in .22 ... for most models
