### ISSUE TITLE
Cursor freezes when deleting multiple models.

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#806]
I would be deleting a lot of models in my preview and after deleting a couple dozen xLights would present a double arrow cursor and not let me continue deleting models. I have recorded a video further showing the problem here: https://youtu.be/0OOwAon8gjE
No crash occurs.

**Comment by MrChristmas2000** [comment]
Further update, it looks like it happens after about deleting a large quantity of models, like around 80 or so before saving that you become unable to select any more models for deleting. You can save your work but again you have to restart xLights to continue editing.

**Comment by keithsw1111** [comment]
Tom ... do you know if this is still a problem. Some changes were made recently to model deletion.

**Comment by MrChristmas2000** [comment]
I have not tried it recently but I will give it a go and see what happens.

**Comment by keithsw1111** [comment]
Closing this on because no confirmation it is still a problem and the delete code has changed since this was raised. If it is still a problem we can reopen it.
