### ISSUE TITLE
BUG Another crash with LOR timings import

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#807]
This time it crashes when I right click and try to import
OS Win 7  xLights Version .56
New Sequence
Sel Audio File
Sel 40 fps
Sel timings
	50 ms
	Bar and Beat Track Beats
Done
The elements are not stacked the way I want them in Master View 
If I switch to my "Default" view, I don't get the timings I set up during the new sequence steps  from above.  
Spent time to restack my elements in Master View
Tried to import LOR timing and got the 
Abort Retry Ignore popup
Clicked ignore
Saved the sequence
Closed the program
Reloaded Program
Opened Sequence
Right clicked on timing tracks to import LOR timing marks
Again got Abort Retry Ignore and the message in the Window says 
An unhandled exception occurred  Press abort to terminate the program  Retry to exit the program normally and Ignore to try to continue
This time  clicked Abort  got the message ***Caught unhandled unknown exception, terminating
Clicked OK the program closed

**Comment by JoelDearing** [comment]
This appears to be a Win7 32 bit problem.  I got my hands on a Win7 64 bit computer and the program did not crash when I imported the LOR file.  The LOR file was just too big for the 32bit 4 mb memory (3.x) and xLights would crash with it.  Not sure if there is a fix for that.

**Comment by AzGilrock** [comment]
We haven't released a 64 bit version of xLights yet for Windows so it's 32-bit addressing no matter which version you use.  It would have been the amount of memory available on that machine.  I assume you mean 4 gb instead of 4 mb.  I believe with our large addressing option 3 gb is the max a 32bit process can use anyways.

**Comment by JoelDearing** [comment]
Yes, gb mem, not mb, duh huh.  I posted a rambling item on FB just now on the steps  I went through to get the timing onto the sequence and then crashed it on mapping.  Pt2 on this I copied sequence  back to the desktop, tried to use the mapping I created on the desktop, and it crashed again on the LMS file.  How can I get the model and mapping info to the 64 bit machine?

**Comment by AzGilrock** [comment]
If you are importing LOR files that are too big and cause a crash the only solution is to wait till we release the 64bit version of xLights on Windows or you need to run on a Mac.  You also were still trying to do imports during the new sequence wizard which we already established was a problem and fixed under another issue.  I don't see anything else we can do towards this issue so closing.
