### ISSUE TITLE
Left or Right vertical bar on effect when dragging hangs

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#81]
When I drag the left vertical bar of an effect to adjust the start timing mark, it does not always anchor when I release the left mouse button.  When this happens, the left timing hash will follow the mouse around until I click again or the app will crash.  Haven't seen this issue with the right timing hash.

**Comment by smeighan** [comment]
i cant duplicate this with latest mar 18th build. can you submit a short video?

**Comment by stevegiron** [comment]
I just recorded this and it happened instantly. No audio on this computer. Work flow was new sequence, pick audio file, 50ms timing, 50ms timing marks, added one model, and placed an effect to the grid. Move the effect simulating aligning to the waveform. Moving the left bar on the effect too much with cause a crash. 

video is at http://www.stevesimages.com/xl4/xl4-issue-81.mp4

**Comment by AzGilrock** [comment]
I think this is related to the change we need to do to allow the drag to continue once outside the bounds of the row.

**Comment by stevegiron** [comment]
It could be related, however keep in mind that this will crash even if the mouse cursor stays within the horizontal bounds of the model.

**Comment by AzGilrock** [comment]
I'm not sure we drink enough caffeine to reproduce this one....lol.

**Comment by stevegiron** [comment]
Crash with the right verticle bar today. Might be related to going out of bounds when dragging.

**Comment by AzGilrock** [comment]
We've fixed a few things that can cause crashes when dragging end points.  Try to cause this again.  I just fixed it so it doesn't hang when going past the bottom row boundary.

**Comment by stevegiron** [comment]
I tried to make it crash and it did not with the same workflow. Issue does indeed to be fixed. Thanks Gil!

**Comment by stevegiron** [comment]
A new side effect of dragging the effect endpoints is that now the waveform display goes away when you drag. If you click on the waveform area, the form shows again.

**Comment by AzGilrock** [comment]
Try 3.0.8.  I wasn't happy with the lag when dragging effect endpoints so I think I've improved it alot.  Part of that included doing a faster update of the waveform and timeline.  All machines may work different though.   I wasn't having the waveform blank out like your saying.  I should probably do testing on a weaker machine.  My main coding machine was my gaming rig with a $500 video card.

**Comment by stevegiron** [comment]
I should have been clear, the waveform going away while dragging AND once the dragging is stopped IS WITH 4.0.8.  It did not do this with 4.0.6 and I only used 4.0.7 for 30 minutes today.

**Comment by stevegiron** [comment]
Downgraded to 4.0.7 and the issue is not there.

**Comment by AzGilrock** [comment]
Yeah but 4.0.7 still has lag when dragging the marks right?  I'll have to install the actual build from Sean to see how it works because running the code in debug mode 4.0.8 is working great on my machine.

**Comment by stevegiron** [comment]
Update. Verified on computer #2 that the waveform goes away during and after an effect drag with 4.0.8.

**Comment by AzGilrock** [comment]
Test it again in 4.0.9.  It's standard when doing OpenGL to ignore Windows erase background events so I added that to all our OpenGL windows.  It eliminated flashing I was seeing in the Waveform whenever dragging an effect endpoint or resizing the application window size so it may fix this issue also.  You can see in this video why I was doing the changes and my recent checkin fixes the flashing of the Waveform.  Although my Waveform was flashing it never stayed disappeared.
https://www.youtube.com/watch?v=QiiUUSUGp0g

**Comment by stevegiron** [comment]
4.0.9 Does indeed cure the waveform redraw and the original issue. I'm closing this one.  Thanks!

**Comment by AzGilrock** [comment]
Cool cause I wasn't sure what else I would try. :)
