### ISSUE TITLE
New Sequence, Animation maximum duration?

### ISSUE THREAD

**Issue by neilsunw** [smeighan/xLights#811]
Is there a maximum **Sequence Duration** (seconds)?

I want to build a 2 or 3 hour closing animation for a show.

It looks like the time line goes negative with durations > 50,390 frames
or maximum 5039 seconds = ~83.98 minutes (short of my 3 hour goal)

- 5039 sec @ 10 fps works but 5040 sec will show negative time line rulings
- 2519 sec @ 20 fps works, but 2520 sec will show negative time line rulings
- 1259 sec @ 40 fps works, but 1260 sec will show negative time line rulings

Is there a code variable that is rolling over?

**Comment by AzGilrock** [comment]
Yes when things quit working and start to crash you've hit the limit.  Its not a specific number.  Anything over an hour is kinda crazy anyways so maybe I'll add an hour limit.

**Comment by keithsw1111** [comment]
Is this still a problem now we have 64bit?

**Comment by AzGilrock** [comment]
I don't think it was a 64bit limitation.  There is something that blows up in the display of the numbers on the Timeline but I'd need to double check it again.
