### ISSUE TITLE
Setup, network edit selection off by one

### ISSUE THREAD

**Issue by neilsunw** [smeighan/xLights#812]
"Setup" screen:
When I mouse pick an Output network line to edit, the Output network -1 will show up in the edit dialog.

i.e. Pick network 3 and network 2 shows up for edit (screen shot attached)
<img width="1134" alt="screen shot 2017-01-29 at 1 38 25 am" src="https://cloud.githubusercontent.com/assets/11142970/22408180/7b6bf33c-e642-11e6-8356-f0a345ea2f98.png">

**Comment by kppankratz** [comment]
Because of this bug, don't double click on the first entry.  xLights will crash.  Just found that out.
