### ISSUE TITLE
BUG: In Sequencing,  some lights will blink/flash, even though a command was not issued.

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#813]
Win 7 32 bit 4 gig of ram  xLights 2016.56

I had noticed this a time or two and thought it was me making mistakes.  I was laying in light flashes (just on and off) for finger snaps and hand claps on Wonderful Christmas Time.  These are AC LOR models, not pixels.  I would highlight a short column of cells that had the on / off effect and work my way through the song and paste the effect where a hand clap would happen.  Then go back and pick up a second paste of where the finger snaps would happen using a different set of elements.  At one point in the song everything, including pixels does a quick On/Off, even pixel models.  Looking at the sequencer window there are no commands in any of the pixel areas that I can see.  Attached is a pdf with three screen shots.

1st shows the wrong lights on in the house view, the 2nd shows a different view of my model list in the seq editor that confirms there are no commands in the pixel elements of mega tree, mega star, wreath and bow.  The 3rd screen shot is the next hand clap in the song and there everything is as expected.  
[012917 Screen Shot Of xLights Bug.pdf](https://github.com/smeighan/xLights/files/737948/012917.Screen.Shot.Of.xLights.Bug.pdf)

**Comment by AzGilrock** [comment]
This is one area where I don't believe you will find bugs and that is the rendering.  There are so many ways that this can happen.  Just showing those 3 screens is not enough to prove there are no effects causing that.  Every single model on the screen has strand and node layers that aren't visible that could be holding effects.  It would be quicker for you to inspect your sequence XML file and look for all the effects within that time range.

**Comment by keithsw1111** [comment]
Or export effects and load it up in excel.

But before you do that ... run check sequence and check you have no overlapping channels. Also renderall to ensure any old render data is removed. Other possibility is a data layer.

**Comment by JoelDearing** [comment]
Thank you for the follow up.  As I am still getting my legs with xLights, I have not done any effect layering. I did noticed that when I saved the sequence and the render command is run during save, I checked the sequence again at those time points and everything was as is should be.  So for the user when we are sequencing, have not rendered or saved, should it be expected that we are going to get odd artifacts like this in our sequence?  To get those "errors" before rendering makes it look like I have made a mistake and have to go chasing it down before I would consider saving it (my .02)    Inspecting the XML file, exporting effects and loading them in Excel are part of my learning curve.  I did run check sequence  for overlapping channels, and there are none, just a gap in universe numbering.    Looking forward to your feedback

**Comment by AzGilrock** [comment]
So long story short....the sequence was fine after it was rendered.  Some of what can cause that is changing next release so I don't really want to give all the explanation why it can happen.  Bottom line is the program would not be as efficient if we had to re-render every dependent model every time to touch a setting.  We show you what your working on not necessarily every other model your affecting.  Certain things like paste and undo don't always trigger rendering properly either.  Ultimately if something doesn't look right you need to render it and check again before you show up here.
