### ISSUE TITLE
Enhancement: Type-in Start Time for Video Effect

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#814]
Inside the video effect, the only way to adjust the start-time (if you don't want the video to start at 0:00) is to drag the slider to the time you want. However, when trying to sync videos to audio, it is very difficult to get the start time exactly right. Since I see many users syncing videos for P10 panels and other matrix-layouts, it would be much more user-friendly if we could type-in the start time to exactly where we need.

Thanks!

**Comment by keithsw1111** [comment]
Fixed
