### ISSUE TITLE
Render not showing progress

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#817]
When clicking Render while selecting the layout tab (and possibly other tabs), the render progress bar does not show the progress of the render.  When double clicking on the status bar, it doesn't show individual model progress.  

Using version 2017.2

Thanks 
Clyde L

**Comment by stevegiron** [comment]
What is soing?

**Comment by AzGilrock** [comment]
I think the best solution is we don't allow users to render when they aren't on the right tab and then we prevent them from leaving that tab while rendering.

**Comment by Clyde-L** [comment]
Obviously this doesn't amount to a huge bug.  It's not hurting anything.  But wanted to mention it.  If you want to lock it to the sequencer tab, do it.  Not much to worry about since it does it's job :)  Wanted to share the find is all
