### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#819]
Zip file attached.
Enjoy

But wait there's more.   
I get this error when trying to send you the zip file
We don’t support that file type. with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. 

Let me know how I can get it to you

**Comment by AzGilrock** [comment]
If you hit Ok when you got the debug report screen then we already have it uploaded to our crash report server.  If you want to submit a meaningful bug report it needs to include the steps to reproduce the problem.  I'm not going to accept just crash report files and issues title just "CRASH".
