### ISSUE TITLE
in release 2017.3 there no Skulltronix skull preview image 

### ISSUE THREAD

**Issue by JerryPlak** [smeighan/xLights#822]
under the Skulltronix skull setting there no preview image showing up.

**Comment by AzGilrock** [comment]
Working great for me so how do you recommend we proceed to figure this out?

**Comment by stevegiron** [comment]
Since the release is less than 72 hours old, there should be no tickets allowed.

**Comment by AzGilrock** [comment]
My reply was more of a subtle hint that there is not enough info to troubleshoot.  Is this happening on Windows, Mac, or Linux?  Is it the Layout Preview, Model Preview, or Whole House Preview?  Were the channel definitions defined?  Screenshot of all the model settings or the xlights_rgbeffects.xml file might help.

**Comment by JerryPlak** [comment]
This is on Windows 10, and it is in the layout preview.
I am attaching the xlights_rgbeffects.xml  also I noticed that the  "DmxStyle=" not showing up when I use the Skulltronix skull model !!  
![xlights2017_3](https://cloud.githubusercontent.com/assets/7828324/22902321/b119f42c-f202-11e6-8322-195838959fbc.jpg)

**Comment by AzGilrock** [comment]
Ok maybe I can try starting with a blank show folder.  One thing you may try is set # of channels to 18.  Maybe I forgot to set that as the default but I notice you have it set to 8 which might be causing the problem.

**Comment by JerryPlak** [comment]
updated file 
[xlights_rgbeffects (2).zip](https://github.com/smeighan/xLights/files/772418/xlights_rgbeffects.2.zip)

**Comment by stevegiron** [comment]
Just validating what Jerry has pointed out. I did change from default to 18 channels and now the blank model looks like this: 
![image](https://cloud.githubusercontent.com/assets/10568498/22908092/70f36960-f201-11e6-83d6-deaddde31dcb.png)

**Comment by stevegiron** [comment]
18 Channels fixes it. To get the face to show on the layout, you then need to change the default of 540 on Pan rotation to 400-ish  
![image](https://cloud.githubusercontent.com/assets/10568498/22908180/d9d9706e-f201-11e6-9899-a3d47daaa898.png)

**Comment by AzGilrock** [comment]
Yeah so some of the defaults need to be tweaked.

**Comment by AzGilrock** [comment]
But I did intend it to work with less channels so I'll have to see what blows it up.  Like if someone only has a 3 axis skull they should still be able to use it.

**Comment by AzGilrock** [comment]
So there is crash protection that exits the drawing function if any of the channels defined are greater than the # of channels set for the model.

**Comment by AzGilrock** [comment]
I've fixed the defaults.  The skull image will still disappear if you try to assign a channel number higher than the number of channels.  It doesn't crash the program so I think I'll leave it this way.  When you select the Skulltronix model style it will ask if you want to reset to defaults which will always allow you to restore to an operational condition.
