### ISSUE TITLE
Color Curve Issue

### ISSUE THREAD

**Issue by TKW1969** [smeighan/xLights#823]
In 2017.3 if you select the color curve on certain effects like morph or the fan affect it will cause the display of the effect to disappear in the time line. It's still there just not visible. Still shows went played. Change to solid color and it appears in timeline.

**Comment by stevegiron** [comment]
Confirmed. Gil, this happens only on the Fan, Galaxy and Morph effects when the Grid Icon value is set to ON and a color blend mode is set.

**Comment by AzGilrock** [comment]
I saw this ages ago.  If the curves even work at all on most of my effects its by accident.

**Comment by AzGilrock** [comment]
So it actually currently display black but only for color selections that have a curve.  So if you create a 4 color morph and only one of the colors is a curve you still see the other 3 colors.  Only the curve color is black.  I think the best I can do is default it to the first color of the gradient for the grid backgrounds.
