### ISSUE TITLE
Null/States Crashing xlights?

### ISSUE THREAD

**Issue by GrizAF** [smeighan/xLights#824]
Trying a unique design and I'm pretty sure this keeps crashing xlights.  The design revolves around using the state model to create gaps inbetween lights using the tree model.  The result should be a section of LEDs, then Pixels, then LEDs, etc.  My plan was to have one tree model with LED states, then overlay a second tree model with Pixel states.  If there is a simpler way to do this please let me know.  

This is my first crash report so i'm uploading all of the files and I took a screen shot of the "model" to show the concept.  This screen shot is only of LED states.  I haven't made it far enough to include the second later that would be pixels. 

Thanks for the help.

Griz

[backtrace.txt](https://github.com/smeighan/xLights/files/775368/backtrace.txt)
![capture](https://cloud.githubusercontent.com/assets/25779795/22950661/a3199dac-f2c3-11e6-87ec-d3bf8e0d2d5e.JPG)

**Comment by keithsw1111** [comment]
I need more than just the backtrace ... can you package logs when your sequence is open so we get all the relevant files.

**Comment by keithsw1111** [comment]
what exactly are led states vs pixel states?

**Comment by GrizAF** [comment]
The image is just of LEDs.  I would overlay a separate model rotated roughly 33 degrees using the same concept of states, but for pixels.

**Comment by GrizAF** [comment]
Is there a way to upload a .zip? Tried multiple methods and it says it's not a valid file

**Comment by keithsw1111** [comment]
I am sorry but I dont understand what you are getting at. By LEDs i assume you mean dumb strings of single colour LEDs. Maybe you could explain more about what you are trying to do ... because what you are doing I am struggling to understand.

I am guessing you have a tree ... maybe 2? Is it a combination pixel/LED tree? Why 33 degree rotation ... is that because the leds spiral around the pixels? So many possible interpretations.

**Comment by GrizAF** [comment]
Sorry.  I know this is a unique problem. 

Yes, but LEDs, I mean a section/state of the tree where the yellow (see picture) is LEDs/dumbstrings/single channel.  The white section on either side of the yellow would be pixels.  Given this is difficult to do on the same model, my plan was to create a second tree using the same state design, offset it, and those yellow states would be pixels.  When placed in xlights it would be rotated to the LEDs white section.  So on a layer by layer basis, the tree alternates between sections of LEDs, then pixels.

**Comment by keithsw1111** [comment]
Stepping back even further ... forget about xlights ... what are you actually building ... I am concerned you are trying to over model it in xlights to make it look exactly like what you are building when this may not be necessary. The idea of the state effect was the ability to use simple timing track labels to control which pixels turn on an off. I get the sense you are trying to use it as a mask to show a subset of pixels that actually exist vs what the model generates ... that is not really a valid use case and wouldnt likely work ... as the data for the other unused pixels is still generated.

**Comment by GrizAF** [comment]
Essentially, yes.  I am afraid that I am overthinking/modeling it.  I am working backwards from an existing design/build and trying to sequence it in xlights.  If there is an easier way for a tree to alternate sections from LEDs and Pixels please let me know.

**Comment by keithsw1111** [comment]
alternate vertical sections of LEDs and Pixels ... I would just create 2 trees ... one pixel and one led and put them in the same location in the preview offset enough that you can see both. It does not need to look exactly like it does in real life ... just close enough that you can imagine what it will look like when you sequence.

**Comment by GrizAF** [comment]
I understand what your saying and I have tried that.  Without the gap between the alternating LEDs and Pixels panels it is very difficult to sequence because I cannot see how the effects will show.

**Comment by keithsw1111** [comment]
I believe the crash included above has been fixed in either .8 or .9.

**Comment by keithsw1111** [comment]
No response so I am closing this.
