### ISSUE TITLE
Enhancement: 30FPS or User-Selectable Frame Rate

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#825]
Per the discussion with David, Jeff, and Kevin on the weekly chat:

We would love to add 30 FPS and/or user-selectable frame rates when creating a new sequence.

As an additional enhancement, the ability to change frame rates on an existing sequence would also be very nice (even if it makes a duplicate file in a different frame-rate or something).

**Comment by AzGilrock** [comment]
This enhancement is already on the list as #385.  I was planning to allow the user to type in the desired rate.
