### ISSUE TITLE
Enhancement Request: More control of view section

### ISSUE THREAD

**Issue by fstkaz** [smeighan/xLights#826]
It would make it great to be able to have the View area/ the area you do all the sequencing in to be able to undock that and make it bigger/longer. Would love to be able to stretch it out across a whole screen or more than one to make it where more can be seen.

**Comment by stevegiron** [comment]
You can drag xlights today across multiple monitors. If you hold the control button down while moving any of the other dockable windows, you can place them anywhere. You can even have them outside of the xLights main app window. That would leave you the sequencing tab free. Many folks put the dockable windows on Monitor 1, then stretch the sequencer across monitors 2,3.

**Comment by AzGilrock** [comment]
Yeah I'm closing this one.  I attached a screenshot showing evidence that you can do this already.  This is a screenshot across 2 monitors.

![double_wide](https://cloud.githubusercontent.com/assets/2024669/25766015/d6afe07a-31a4-11e7-8ca7-19b662bc4a97.png)
