### ISSUE TITLE
Light output isn't correct

### ISSUE THREAD

**Issue by PKingRoch** [smeighan/xLights#827]
I added a new E131 controller at 192.168.0.52 starting at universe 43 and containing 420 channels,  channels 13105 to 13524 in my mapping.  These 420 channels map to new props I have created for pixel trees.  The trees have a base prop of 50 pixels and a 20 pixel star prop for a total of 70 pixels for each tree.  I have 2 trees I am addressing on this universe for 140 pixels or 420 channels.  The last channel (pixel 140, blue channel) does not light when I output to my lights in test or sequence mode.  The models in the layout and the sequencer show that this channel will light, but output to lights appears to have an error where it is off by one.  Red & green channels output correctly, only the last blue is channel, 13524 is being truncated when the lights are being output.  xLights BETA Ver 2017.3.

**Comment by keithsw1111** [comment]
I am aware of this problem but have not managed to reproduce it to fix it. I am looking for more details.

Does it happen all the time. Can you share you setup and indicate exactly which channel is the issue.

**Comment by PKingRoch** [comment]
Happens all of the time here.  What would you like me to share as far as my setup?

**Comment by PKingRoch** [comment]
Here is my RGBeffects and networks files

[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/788851/xlights_rgbeffects.zip)

**Comment by keithsw1111** [comment]
please

**Comment by keithsw1111** [comment]
which specific channel has the problem?

**Comment by PKingRoch** [comment]
13524 output 44, E131 192.168.0.52, universe 43, channel 420  It's the Blue channel of the last pixel on the PT Star - 2

**Comment by PKingRoch** [comment]
Thanks Keith!!!
