### ISSUE TITLE
Enhancement Request: Edit Display Elements

### ISSUE THREAD

**Issue by dragonzpneuma** [smeighan/xLights#829]
Would love to see buttons added to the Edit Display Elements window for "Move To Top" and "Move To Bottom" (unless there's a hidden way to do this that I don't know about yet).  If you have a long list of models such as mine, it's a real pain to move it all the way from the bottom to the top.

Thanks,
Keith H.

**Comment by keithsw1111** [comment]
I am planning on totally reworking this dialog ... I doubt I will add this feature but I will be adding drag and drop with auto scrolling so this should solve the underlying issue.

**Comment by dragonzpneuma** [comment]
That sounds great Keith.  That will probably be an even better way.  Thanks for the quick response!!!!

Keith H.

**Comment by AzGilrock** [comment]
I believe if you hold shift you can select a group in the list.  So the hint is selecting everything below an item and hitting Move Up is the same as doing a Move to Bottom for that item.

**Comment by keithsw1111** [comment]
Not quite a move to bottom/top but you can drag and drop multiple items. When you add them you can also drag them to where you want them.
