### ISSUE TITLE
Request: Zoom level minimum for effect edge dragging

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#83]
Currently when dropping an effect, you must be zoomed in greater than 10 seconds wide to drag the effect edge slider to adjust the effect timing width. I noticed that once an effect has been moved, you can have a wider timing view and subsequently drag the effect edges when zoomed out wider, but not when the effect is initially dropped.

I would like to be able to drag the edges of an effect from the 10 second zoom level and wider.

**Comment by AzGilrock** [comment]
Yeah I haven't seen that before because I haven't been using small timing mark divisions.  If you use larger divisions I think you can grab the ends all the way zoomed out.  I'll have to look at the mouse hittest to see what's wrong.
