### ISSUE TITLE
Bug: Crash trying to select View menu items

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#831]
Mac OSX
Compiled code using latest pull from Github (Feb. 26th).

Under the Setup or Layout tab, selecting View - Windows - Display Elements, causes a crash.  The other options do not cause a crash initially.

After switching over to the Sequencer tab (no sequence open), and switching back to Setup or Layout, then trying to select any window option to display under the View menu will cause a crash.

Trying to select a perspective also causes crashes under the Setup and Layout tabs.

Can the view options menu be disabled while under the Setup and Layout tabs?

**Comment by AzGilrock** [comment]
If you're going to build your own code then its up to you to debug it.

**Comment by kppankratz** [comment]
Thank you for the words of wisdom.

Considering I can recreate this crash repeatedly using the official release from Dan, I don't think my compiling the code is the problem.  What I did find out with additional testing though, is I can only do this on the Mac, not PC.  Might be a problem with Linux as well?

**Comment by cjd** [comment]
I just gave it a test on linux and was unable to cause a crash through any of those steps

**Comment by kppankratz** [comment]
Maybe it's my system then?  Hopefully Dan can test it out and let me know.

**Comment by kppankratz** [comment]
On a new system of mine this does not happen any longer.
