### ISSUE TITLE
New Render Styles not working with color curve

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#834]
Playing with Dan's new render styles:

Per Model Default
Per Model Preview
Per Model Single Line

When activating a color curve, blending from red to green, the color and effect are not displayed in the display preview.   In the screen below I have 4 pixel matrix I have assigned the Single Strand effect.  The effects are not displayed.  I also tried this with a number of other effects such as Morph, Fade, and Butterfly.  When the color curve is selected, nothing is displayed. 

When selecting any other render style, the effects were rendered correctly.   Thank you for looking!

![screenshot 2017-03-07 11 19 38](https://cloud.githubusercontent.com/assets/12719816/23665967/f9c2dfbe-0327-11e7-9f14-5995163857bd.png)

**Comment by keithsw1111** [comment]
Is this still a problem clyde. I cant think why it would have ever been one so I suspect we have not fixed it. Can you send me a sequence that shows the problem?

**Comment by Clyde-L** [comment]
This is old and has been long since fixed.  Safe to close out.
