### ISSUE TITLE
Add ability to print and change text size on "Wiring View" screen in Custom Model

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#835]
The Wiring view is extremely useful once you have created a custom model but its purpose 99% of the time is to print and take with you to physically wire the element, not look at it on a screen. Please add additional functionality to this screen to change the size of the font (channel numbers are way too small) and also to print.

**Comment by keithsw1111** [comment]
To print right click and export the image. It won't sort your text size issue though. There you may need to get better glasses :)

**Comment by idleup** [comment]
Okay, I tried exporting and the image is at a funny aspect ratio, it is short and fat, not like it is in the custom model admin.

As for the text size increase, is that something that could be added easily? You print this and the numbers are not readable.

**Comment by keithsw1111** [comment]
I thought the image reflected the size of the window it was exported from ... but that is just from memory.

**Comment by stevegiron** [comment]
Don't you only need to know where pixel #1 is? Just follow the line for the
rest.

**Comment by idleup** [comment]
Steve - it is not that simple of a model.

Keith - It is not exporting at the size of the window. If it can be, that would be great.

**Comment by idleup** [comment]
So solve the issue of being feasible to print, it could be a simple as making the exported PNG use a white background with black text instead of black background with white text.

**Comment by keithsw1111** [comment]
Added the ability to change backgrount to white. I have also made image sizing more sensible. Exported image should have same proportions as the window you export from. Take a look in .15 and let me know if i can close this one.

**Comment by keithsw1111** [comment]
Text size can now also be adjusted using right click menu.
