### ISSUE TITLE
Feature Request: Ability to select Default Preview

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#836]
Previews are a wonderful tool for organizing multiple model groups or display setups.
The ability to select which preview is shown in the "house model" window while sequencing would be wonderful!

**Comment by AzGilrock** [comment]
That's not a new idea we discussed it when I created multiple previews.  You can already display any preview window so not much benefit gained by adding this.  I'm fearing it creates more problems when users forget they changed it and then complain something isn't showing up.

**Comment by jholmes09** [comment]
I agree that multiple preview windows are great, but since they are floating, UI organization gets difficult. Particularly with single-screen users, when you try to sequence, your preview disappears behind the main UI and getting it back up front is a pain. Even after you bring it back to the front, to play the part of the sequence you are working on requires you to hit the play button, which sends the preview window right back behind the main UI.

It is much more efficient to be able to make a change in the sequencer, glance at the preview, and then keep adjusting. 

Perhaps instead of selecting which one is "default," we are simply able to assign which one shows up where the default window is usually located? The difference being that the window would actually identify itself as whatever the preview was named (rather than just default) to help avoid confusion.

**Comment by AzGilrock** [comment]
Next release will allow the user to right-click the House Preview and switch it to any other custom previews they have created.
