### ISSUE TITLE
Previously saved preset now requires tweak to work

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#837]
A preset of 2 effects worked fine in 2016.51
This effect does not render or show in the preview with 2017.6.

See this video of the application of the preset and the results.
If you have the presets, it's in Preset Pack 1 named Pinfly. Looks like Pinfly2 does the same thing.

If you need the preset, I'll send it to your email address.

video at http://stevesimages.com/xl4/preset-mask.mp4

**Comment by keithsw1111** [comment]
If you want me to take a look send it to me.

**Comment by keithsw1111** [comment]
The behaviour has not actually changed at all. This is a side effect of blending across models. If you turn off blending across models in sequence settings then the original behaviour is restored. So in existing sequences users wont see any issues. In new sequences they will. I would argue there is actually a defect in your preset ... you didnt really want the bottom layer to use "1 is a mask" but when the only layer blending mode was within model it didnt matter so much.
