### ISSUE TITLE
Bug: FPP Connect Window Stuck Between Other Windows

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#838]
See attached image, the individual progress bar for uploads get stuck behind the main FPP window but in front of the primary XLights window.

The FPP Connect window and Xlights window seem to be locked to each-other but the upload progress bar floats.

<img width="1296" alt="screen shot 2017-03-15 at 5 03 32 pm" src="https://cloud.githubusercontent.com/assets/18503894/23972881/9eac0008-09a1-11e7-8f3a-11628ccb2475.png">

**Comment by keithsw1111** [comment]
I looked into this and this seems to be an artefact of wxWidgets. The code is doing all the right things setting parent windows ... I dont think we are going to be able to action a fix other than hoping some future upgrade to wxWidgets solves it.
