### ISSUE TITLE
Render All Seems to Hang

### ISSUE THREAD

**Issue by m00dawg** [smeighan/xLights#840]
Just updated to master via git and when I go to "Render All" (or if a save triggers it), it gets about 1/8th to 1/4th of the way (depending on the sequence) according to the progress bar, but just hangs. I tried to run with `xLights -d` but it doesn't show much:

```
tim@lindawg ~/git/xLights $ xLights -d
[mp3 @ 0x4a5b860] Skipping 0 bytes of junk at 71974.
[mjpeg @ 0x4a33660] Changeing bps to 8

(xLights:19439): Gtk-CRITICAL **: IA__gtk_window_resize: assertion 'width > 0' failed
Preview - glVer:  3.3.0 NVIDIA 375.20  (GeForce GTX 1070/PCIe/SSE2)(NVIDIA Corporation)
WaveForm - glVer:  3.3.0 NVIDIA 375.20  (GeForce GTX 1070/PCIe/SSE2)(NVIDIA Corporation)
EffectGrid - glVer:  3.3.0 NVIDIA 375.20  (GeForce GTX 1070/PCIe/SSE2)(NVIDIA Corporation)
TimeDisplay - glVer:  3.3.0 NVIDIA 375.20  (GeForce GTX 1070/PCIe/SSE2)(NVIDIA Corporation)
ModelPreview - glVer:  3.3.0 NVIDIA 375.20  (GeForce GTX 1070/PCIe/SSE2)(NVIDIA Corporation)
HELP!!!!
HELP!!!!
HELP!!!!
```

This is on Linux (Mint 18.1 specifically).

**Comment by keithsw1111** [comment]
log? version? package your sequence so we can see if it is reproducible.

**Comment by m00dawg** [comment]
It never wrote a log as far as I can tell since it never crashed. I think I had it sitting for at least 30 minutes just to make sure it wasn't just being really slow. The version I used was from git master, commit d1311f5b0c52062a7d7588a629c00030a3019958 (Wed Mar 22 13:39:57 2017 -0400).

**Comment by m00dawg** [comment]
Looks like all my sequences were affected, but here's a shorter one that has the problem that may be easy to use hopefully:

[Intro.zip](https://github.com/smeighan/xLights/files/863428/Intro.zip)

I'll also try to throw together a quick video so you can see it in action.

**Comment by dkulp** [comment]
I can confirm it's an issue.  Should just be on Linux with Text and Tendrils.   (the effects that cannot be rendered on the background thread) Working on a fix.

**Comment by m00dawg** [comment]
Post closed comment, pulled down new updates and, yep, I am able to run a Render operation now without issue. Thanks for the fix!
