### ISSUE TITLE
Bug: Crash Adjusting Gamma Setting

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#841]
I'm adjusting individual color gamma settings and I was consistently getting a crash after changing the Green gamma setting.  I would enter a value into the text field and click save which would be followed by a crash each time.  The setting was saved though, and this only happened with the Green channel.

Running OS X and xLights 2017.6+ (compiled from GitHub March 24th).
[xLights_dbgrpt-4996-20170324T191616.zip](https://github.com/smeighan/xLights/files/869499/xLights_dbgrpt-4996-20170324T191616.zip)
[xLights_dbgrpt-4972-20170324T191419.zip](https://github.com/smeighan/xLights/files/869500/xLights_dbgrpt-4972-20170324T191419.zip)

**Comment by kppankratz** [comment]
Crashed when adjusting red too.
[xLights_dbgrpt-5137-20170324T200302.zip](https://github.com/smeighan/xLights/files/869626/xLights_dbgrpt-5137-20170324T200302.zip)

**Comment by keithsw1111** [comment]
If you can do it so reliably can you video it crashing. I have tried to reproduce it and i am not seeing the crash. Maybe it is OSX specific but that seems unlikely.

**Comment by kppankratz** [comment]
I attempted to reproduce the crash today with the latest code and can't get the same results this time.  I'll close the ticket but can reopen in the future if I can reproduce it.
