### ISSUE TITLE
Sparkle Support

### ISSUE THREAD

**Issue by tonkaskippers** [smeighan/xLights#843]
Hello,
Would you be willing to enable Sparkle support for Mac (https://github.com/sparkle-project/Sparkle), and WinSparkle (https://github.com/vslavik/winsparkle) for Windows?  It would be nice to not have to download the new version manually every time a new one comes out.

**Comment by AzGilrock** [comment]
Never heard of it

**Comment by tonkaskippers** [comment]
It automatically checks for updates, and then downloads it with one click.

**Comment by tonkaskippers** [comment]
Hey, is there any interest in automatic updates to Xlights?  I found another framework developed by Google, for Chrome and Google Earth.

Mac:  https://code.google.com/archive/p/update-engine/
Windows: https://github.com/google/omaha

**Comment by AzGilrock** [comment]
I think we are happy with the way the program prompts to download new version now.
