### ISSUE TITLE
Channel count off?

### ISSUE THREAD

**Issue by FlyingPlanes99** [smeighan/xLights#844]
I'm new to the xlights family but when i just downloaded and installed 2017.9 and built a test set of 4 arches, the channels don't appear to be auto-populating in the layout tab properly.

I setup multiple arches each with 25 RGB nodes, which should have been 75 channels each, but if you look at the attachment, it's only auto-assigning 74 channels.  

![image](https://cloud.githubusercontent.com/assets/27301656/24924402/a3732554-1ec2-11e7-8639-14e973551c1f.png)

**Comment by AzGilrock** [comment]
No it looks correct.  The end channel will be the start channel + number of channels - 1.  When you add 75 to the start channel that results in the start channel of the next model.  If a model starts at 1 and ends on 3 that's 3 channels but you are adding 3 to 1 and saying it should end on 4.
