### ISSUE TITLE
2017.9 lms convert to xseq slow

### ISSUE THREAD

**Issue by FlyingPlanes99** [smeighan/xLights#845]
On my machine, if I do an LMS convert to xseq, it takes about 10 minutes, but if I do the same convert to fseq, it takes seconds and completes successfully.

Not sure if anyone else has seen this issue.

**Comment by dkulp** [comment]
Out of curiosity, why would anyone need the xseq?   Still using xLights v3 to play?

**Comment by FlyingPlanes99** [comment]
I was just testing the conversion to xseq's and noticed the time difference.
