### ISSUE TITLE
Feature request DM412 pixel support

### ISSUE THREAD

**Issue by skulltronix** [smeighan/xLights#846]
What would it take to get support for dmx412 pixels?  Thanks!

**Comment by AzGilrock** [comment]
Different pixel types are usually handled by hardware not xLights.  xLights has no idea which type of pixel the data is being sent to so I'm not sure what we would do.

**Comment by skulltronix** [comment]
Thanks Gil. I always thought it was software protocol but I can see that it would be the software in the hardware. 

Jerry Jewell
Skulltronix.com
916 600 2295

**Comment by AzGilrock** [comment]
I searched to find out what these were and main thing I found was your post on FalconChristmas.  Looks like Dave is saying these are 16 bit pixels and that he has handled that before with a lookup table.  If you're looking for true 16 bit support xLights would need to add a new pixel type that supports that data size.  Not sure how much work would be involved.  How do you talk to the pixels?  Is it standard DMX or a different protocol?  I couldn't tell if you were asking for a different interface type.

**Comment by skulltronix** [comment]
Hi
Right now I use Kibonode controllers. But they are large and bulky. I want to use picaps. 

Xlights works with Kibonode over e.131. Guess I wasn't very clear. 

Jerry Jewell
Skulltronix.com
916 600 2295

**Comment by skulltronix** [comment]
Me again,

 

The guy who knows everything about the dm412 is Chuck Sommerville. He’s in our group.

 

J

**Comment by keithsw1111** [comment]
I am with Gil on this one. 16 bit pixels are best handled using a 8 bit lookup table. The 16 bitness gives the option to choose the best numbers to represent 8 bit colour reflecting the fact that pixels dont respond in a linear fashion.

Making xLights fully 16bit aware would double processing for very little value ... especially as you would still need to add diming curves to address the issue described above.

The only place 16 bit has obvious value is in supporting DMX type elements that need more than 256 positions such as moving elements and I think he has that sorted with the servo effect.

**Comment by skulltronix** [comment]
Hi
Thanks, but I still have piles of these pixels and no way to use them :(

Best regards, 

Jerry Jewell
Skulltronix.com
916 600 2295

**Comment by keithsw1111** [comment]
Sure but it is the controller firmware you need updated not XLights.

**Comment by dpitts** [comment]
Jerry if you send me a small string, like 25, I can implement them in Falcon controllers.

**Comment by skulltronix** [comment]
Thank you!

Address please. 

Jerry Jewell
Skulltronix.com
916 600 2295

**Comment by skulltronix** [comment]
Hi Sean 
Any chance you've been able to work with the DM412 leds?

I'm hoping to get the display to Burning Man. 

Chuck Sommerville said you could contact him about the driver. He has a lot of experience with them. 

Thanks!  

Jerry Jewell
Skulltronix.com
916 600 2295

**Comment by AzGilrock** [comment]
Jerry it looks like you and Dave were supposed to hook up on getting the strings to work.  You keep talking to me, Sean, and Keith and we are just the software side of things.

**Comment by madsci1016** [comment]
Jerry,

Earlier you said you wanted to drive the DMX412 pixels from a PiCap. So the developers to pester would be the ones for FPP to support driving these pixels. 

I recently wrote a pixel driver for FPP, so I might be able to help. Though I can't find any reference on the DMX412 protocol. Do you have any detailed information on them? If so shoot me an email:  bill at billporter.info and let's take this offline.

**Comment by skulltronix** [comment]
Hi
Sean asked me for some dm412 pixels a while back to implement in the falcon controllers. But he's been busy. 

A quick search for dm412 led driver brings up several good links. 
Here is one:

http://www.siti.com.tw/product/spec/LED/SP-DM412-A.003.pdf

Also, Chuck Sommerville has direct experience and said he has some tips about timing issue. 

I have a large 3D display made using them and I'm stuck with the animation it came with. I'd like to use xlights. I also have some 4'x4' panels that I'd like use. 

Thanks !!
Jerry Jewell
Skulltronix.com
916 600 2295

**Comment by skulltronix** [comment]
Thanks Gil,

Sean actually asked me to send him some of the dm412 leds a few months ago so that he could implement them in the falcon controllers. Which I did. 
He's been pretty busy though. 

Which Dave?  

Jerry Jewell
Skulltronix.com
916 600 2295

**Comment by AzGilrock** [comment]
Sean has not asked you for pixels.  I think you are mistaking that the emails from Github have "smeighan/xLights" but that doesn't mean it's Sean talking.  Sean has not replied in this issue thread.  Dave has responded above with the profile name "dpitts".  That is Dave Pitts the creator of the Falcon controllers.  Sean does not develop hardware.

**Comment by skulltronix** [comment]
Omg. I'm so confused. Thanks for the explanation. 

Jerry Jewell
Skulltronix.com
916 600 2295
