### ISSUE TITLE
Deleting models causes erroneous messages to appear

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#85]
I created models that I'll never use in my display for testing purposes last year. With XL4a the startup messages remind us that the channel # exceeds the network config. (The last channel message erroneously displays way too high)

When I deleted some of the models, messages came up saying that other untouched models were way out of bounds. Subsequent repeat of the same process causes the same error message to come up on the same model but with a different last channel count #.

First message
![image](https://cloud.githubusercontent.com/assets/10568498/6756018/737be208-cee4-11e4-8813-053c5c1fe445.png)

I'm not a n00b, but went to verify anyhow.
![image](https://cloud.githubusercontent.com/assets/10568498/6756042/8e69af8c-cee4-11e4-8cb4-cd986ba62ad4.png)

Tried to exit the model menu and got this message
![image](https://cloud.githubusercontent.com/assets/10568498/6756236/aec58142-cee5-11e4-981f-0f1c375f3f18.png)

xml files are at http://www.stevesimages.com/xl4

To reproduce the error use my xml file and delete a WHM.. They can be identified by the grey out of the modify button when selecting them.

**Comment by stevegiron** [comment]
Third image should be this one. 
![image](https://cloud.githubusercontent.com/assets/10568498/6756188/695aed18-cee5-11e4-953d-69c32ffb6113.png)

**Comment by Boof63** [comment]
hi getting this error now in xl4.0.24.
Maybe same cause deleted models that didn't work (went custom)
What is the fix please?
Cheers Boof63

**Comment by stevegiron** [comment]
Have not seen this issue in the past few releases. Closing ticket for now.
