### ISSUE TITLE
R-G-B-W Test in the RGB Cycle tab in Test Lights does not show white.

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#850]
I have downloaded 2017.10 64bit and installed it. I am testing the falcon Picap via xLights.
FPP w/PiCap is in Bridge mode.  When I go to the Test Tool and select R-G-B-W, all I get is R-G-B-nothing, then it cycles through R-G-B-nothing.

I can send just white via the RGB tab.

**Comment by keithsw1111** [comment]
I dont think there is anything wrong here. I think you are looking for the A-B-C-All option. The R-G-B-W is designed for RGBW elements.

**Comment by keithsw1111** [comment]
Pat ... were you using this on an RGBW element or pixels ... if it was the latter we can close this one.
