### ISSUE TITLE
E.1.31 setup; Typing network name is makes UI sluggish (64-bit)

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#851]
If I try to type the network DNS name of a destination in the E1.31 setup the typeing is delayed,.. sluggish.
If I type an IP address, the numbers type just fine.
![image](https://cloud.githubusercontent.com/assets/8147459/25565634/517baafa-2d90-11e7-9f03-343619a6590e.png)

Is this new behavior? I tested Ver 2017.2 Jan 31 (32-bit) and typing DNS name is fine.

**Comment by keithsw1111** [comment]
Fixed

**Comment by dkulp** [comment]
Just to clarify...  with Keith's fix, it no longer will validate that the host name is correct or is resolvable.   Previously, if the hostname was not resolvable, the "ok" button wouldn't enable.   Now it no longer checks that so you need to make sure you enter the hostname correctly.

**Comment by keithsw1111** [comment]
True but I guess I decided for a controller validation does not make as much sense as say it does for fpp connect. I believe it will be common that people won't have their controllers plugged in when they define them.
