### ISSUE TITLE
Custom Model Resizing After Saving and Reopening

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#853]
I created a custom model in a new preview. I save the model and resize it to fill the background. I save the model and then go to another model or to the sequencing page, or close the program entirely. When I open the program back up and select that preview my model has changed in size or skewed itself.

**Comment by idleup** [comment]
In trying to duplicate the problem I found that you have to save the model, go to a different preview, create a new model, save it then return to the previous preview and the custom model has changed. If you do not modify or create another model then it stays as it should.

**Comment by AzGilrock** [comment]
Are you talking about viewing the preview in the Layout Page only?  Cause those previews can be activated in stand alone windows so I never know which version of the preview you mean when you say you select that preview.

**Comment by idleup** [comment]
Yes, it is the preview on the Layouts tab.

**Comment by AzGilrock** [comment]
I thought I saw it once but now I can't cause it.  Are you saying it's only a Custom model that does this?  You should be able to see the PreviewScaleX and PreviewScaleY values in the rgbeffects file and catch them changing when this happens.  Those values determine how it's scaled to the preview and right now we don't use different scales for the different previews.

**Comment by idleup** [comment]
For historical documentation purposes I will just reply to this issue with what the problem is even though we have already worked through the cause. It happens on custom models only and only when you drag the bounding box handles outside the preview window causing a PreviewScaleX value to be greater than 1.0

**Comment by AzGilrock** [comment]
This is able to happen on any model that is using a BoxedScreenLocation so think 4 corner box so it affected matrix, dmxmodel, wreath, windowframe, star, spinner, and custom.   In the past users were getting models with corners stuck off screen so this was a way to correct it without editing XML.  I'll remove the 1.0 limit for the model scale values because now you can make corrections in the property window if you need to make it smaller.
