### ISSUE TITLE
Custom Model Wiring View should not show in reverse if "Rear View" checkbox is not checked

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#854]
It would be more intuitive if the wiring view for custom models showed however the custom model layout grid shows it. Example, if I have the grid showing from the front, then I want the wiring view to show from the front, If I click the "Rear View" checkbox than I want the wiring view to also show it reversed. The way it is now it always shows as reversed in the Custom Model Wiring window.

**Comment by keithsw1111** [comment]
I disagree.

**Comment by idleup** [comment]
I don't understand how can you disagree that giving the user the option of showing the numbering from the front or the back is a bad thing. There is a checkbox there so they can view the model from the front or back doesn't it make sense that that functionality should extend to show they see it when they want to see the wiring view? The fact you closed this confuses me, can you please re-open this for someone else to pick up?

**Comment by AzGilrock** [comment]
Custom Model already has the ability to flip horizontal or vertical so you can already create a reverse wiring view.  To me its intuitive that a wiring view is always the view from the back where the wires exist.

**Comment by idleup** [comment]
So you are saying you can create a wiring view from either the front or the back already? I only see the ability to create a reverse view as the element would look from the back regardless if you have the model flipped... 

Let me give you one very practical example of why you would want a numbered model diagram from the front (i.e., wiring view). If you create sequences to use as diagnostic sequences, say one that does a slow chase pixel by pixel and you identify a problem with one of the pixels, it would be helpful to refer to a diagram where each pixel is numbered (as seen from the front of the element) to identify quickly which pixel you are looking at on the element that is not acting as expected. 

I am kind of surprised I am the only one who every needs to identify what number a specific pixel is when viewing the model from the front. As of now, I can only print out a model/pixel number reference as I would see it from the back...

**Comment by AzGilrock** [comment]
Yes the capability is already there.  Just hit the "Flip Vert" button and then "Wiring View" and you have the numbers listed from the front.  Yes you will need to hit "Flip Vert" to put it back.  That button permanently flips the numbers.  I added that feature because I created an Angel that faced right and didn't want to do a bunch of work to create another version that faced left.

**Comment by AzGilrock** [comment]
I've always figured the the numbered view from the front is what you already have listed in the cells so you can just copy that into a spreadsheet if you need the numbers from the front.

**Comment by idleup** [comment]
Thanks Gil, that will work.
