### ISSUE TITLE
Enhancement Request: Picture Effect

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#857]
Would it be possible to add value curves to the start/end position and start/end scale for the picture effect settings?

**Comment by keithsw1111** [comment]
It is on our list. It is not as simple as just adding a curve to startx, endx, starty, endy, startsize, endsize ... ideally we would have just an x, y and size value curve ... this is also not hard to build but building the conversion code for existing sequences is tricky. We dont want to break peoples sequences if we can avoid it.
