### ISSUE TITLE
All elements are duplicated and overlaid in a smaller box in House Preview

### ISSUE THREAD

**Issue by nathan815** [smeighan/xLights#861]
All of my elements seem to have been duplicated in a smaller "box" overlaid over my preview. Here's a screenshot: https://i.imgur.com/ycN74sp.png

Is there any fix for this?

**Comment by AzGilrock** [comment]
What version of xLights?

**Comment by AzGilrock** [comment]
It's usually you have a group that contains everything as a member of another group.

**Comment by AzGilrock** [comment]
If you look at this thread its exactly what you describe and was a problem in version 2016.56 so if you haven't upgraded to the latest that's your problem.

**Comment by nathan815** [comment]
Ah, yep, I still have 2016.56. Upgraded and it fixed the problem. Thanks!
