### ISSUE TITLE
Add Preview Window for Video if using MP4 for Media Track...

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#862]
The Media Track I am using for my sequence is an MP4 file and it is great you can use these instead of just audio files, but in order for it to be truly useful in sequencing I need a preview window that shows the video playing. I will open this preview window along side my other preview windows in order to see my pixels synchronize to the projection mapping.

**Comment by keithsw1111** [comment]
Most just add a dummy matrix to their display to do that.

**Comment by keithsw1111** [comment]
This was implemented a while back.
