### ISSUE TITLE
Bug: Preset export/import and Picture effect

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#863]
I'm using the Picture effect to create a preset for export.  Upon importing the preset I have noticed that not all the parameters come through correctly, more specifically the start/end scale parameters.  Upon importing the preset, those two parameters are set at 100% even though they were set differently during the export.

**Comment by AzGilrock** [comment]
Preset should use the same logic as copy/paste.  Does it paste ok?

**Comment by kppankratz** [comment]
The preset pastes fine, and appears as is.  I ran Beyond Compare with the xml code for the preset, saved version and the imported version, and the code matches.  But when I paste the imported preset, then the parameters change.  I'm sending the preset file to another user to see if they get the same result upon import then paste.  The following images show what the effect should look like (infinity mirror) and then the imported results.
![screen shot 2017-05-18 at 7 34 47 pm](https://cloud.githubusercontent.com/assets/12144876/26228703/8e9937e8-3c01-11e7-93dc-b348e9786a69.png)
![screen shot 2017-05-18 at 7 34 10 pm](https://cloud.githubusercontent.com/assets/12144876/26228717/a0bdebee-3c01-11e7-8c4d-8b8dfdeea009.png)

**Comment by kppankratz** [comment]
Here are the files needed to recreate this.  The preset I'm testing the import function on is the Scroll LR preset.  I'm placing this on a 96w x 128h matrix.  Pasting directly from the currently stored preset file works fine, but it when I export the preset, import it back into xLights and paste into a sequence, that is when some values are changing on the start and end scale.

[untitled folder.zip](https://github.com/smeighan/xLights/files/1012950/untitled.folder.zip)

**Comment by AzGilrock** [comment]
Ah I didn't really know you could export/import them.  Not my code.

**Comment by kppankratz** [comment]
I have verified this is an issue on a Windows based machine this morning too, not just my Mac setup.  The xml code for the preset contains the correct values for the start/end scale parameters, both before and after import into xLights.  It's only when I apply the newly imported preset that the parameters revert to 100% versus what is in xml code.

Once imported, I saved the setup, and opened the rgbeffects xml to verify that the correct parameters are indeed there for the preset.

**Comment by keithsw1111** [comment]
Can you send me the preset

**Comment by kppankratz** [comment]
Here's the exported preset file.  The original rgbeffects file should be in the zip folder I attached earlier.

[Preset-Test.zip](https://github.com/smeighan/xLights/files/1014607/Preset-Test.zip)

**Comment by keithsw1111** [comment]
OK ... I tested this as described and I dont see the problem. I created a new sequence. Added a picture effect. Set scaling start at 0 and end at 100. I saved it as a preset ... then I applied the preset ... it worked. I then created a new sequence and did it again ... it worked again.

Can you maybe record a video of the problem you are seeing and post a link to it on youtube/vimeo.

**Comment by AzGilrock** [comment]
I got a fix for this.  There was a bug in the preset import code where it's not adding the xLightsVersion attribute so it causes all imported presets to run through older effect upgrade code.
