### ISSUE TITLE
Bug: Effect Preset Window

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#864]
Under Mac OS X, the layer counts for all of the presets show 1 as the layer count even when there are multiple layers within the preset.  I haven't noticed this under Windows.
![screen shot 2017-05-18 at 5 27 52 pm](https://cloud.githubusercontent.com/assets/12144876/26226044/ba462110-3bef-11e7-8e54-831f17825a31.png)

**Comment by keithsw1111** [comment]
Can you share the preset file

**Comment by kppankratz** [comment]
Rgbeffects file with these presets.  Should be the same file under #863
[untitled.folder.zip](https://github.com/smeighan/xLights/files/1014613/untitled.folder.zip)

**Comment by kppankratz** [comment]
I compiled the code tonight and this is fixed now.
