### ISSUE TITLE
Lyric Import doesn't render correctly if Lyric contains single quote

### ISSUE THREAD

**Issue by ghormann** [smeighan/xLights#865]
Tested with 2017.14 x64 on Windows 7.

When importing Lyrics into a track, if the track contains a single quote (example below) the lines don't render correctly before and after the tick.  (The timing track becomes one solid color at full zoom instead of showing the words.)   However, you are able to double click on the phrase and edit it to remove the ticket prior to breaking into words and that seems to workaround the problem.

Let me tell you about this house
There’s one in every town
It’s the one, at Christmas-time,
Where folks all gather ‘round.
Most times of the year you’d pass by and not look back,
Oh, but in December it’ll stop you in your tracks

**Comment by AzGilrock** [comment]
Hmm...there are 4 single quotes in those lines but only the one in front of "round" on line 4 is causing the issue.

**Comment by AzGilrock** [comment]
Actually those characters do not look like single quotes.  If I view them in ANSI encoding in Notepad++ you can see they are some weird encoded characters.

![image](https://cloud.githubusercontent.com/assets/2024669/26526219/d3730ae2-4327-11e7-97e8-fa1358632d29.png)

**Comment by AzGilrock** [comment]
You can also see how the code for the one on the 4th line is different and that's the one causing a render issue.

**Comment by ghormann** [comment]
Would it be helpful to add a filter on Lyrics importer to skip any character that isn't standard ASCII? I could give a patch a shot....

**Comment by keithsw1111** [comment]
You would need to be careful not to exclude any characters that actually are in the dictionary files ... it isnt necessarily just a-z.

**Comment by ghormann** [comment]
Hi Keith,
Are you suggesting that such a filter actually parse the dictionary files at run time to identified supported characters, or are you suggesting to just be careful when building the function?  Taking a **quick** look at standard_dictionary and extended_dictionary, it would appear that a filter to excluded anything that is either (a) multi-byte or (b) < ascii(32) or (c) > ascii(126)  would work for the current dictionaries.

**Comment by AzGilrock** [comment]
The dictionaries are setup so that users can add their own stuff or use their own custom dictionaries.  We don't want to break other language support either.  It only seems like the text drawing routine that is having an issue so I would just strip it from the text before it's drawn not touch anything we are currently saving because that doesn't seem to be breaking anything.

**Comment by AzGilrock** [comment]
I think of this as a garbage in garbage out scenario.  You can just as easily delete the garage characters and fix this yourself.  I really don't like trying to make the program protect against everything a user can do to blow things up.

**Comment by ghormann** [comment]
In addition to being a visual issue, the words will not break down into phenoms until the character is removed. (Also easily corrected by the user.)   That said, I can accept the argument that no fix is needed and won't develop a patch.  I'm OK to close the issue.

**Comment by dkulp** [comment]
I would PERSONALLY be ok with a patch that does strip chars outside of 32-127.   The other issue is that the rendering of the chars IS limited to that range.   I believe the rendering should already be converting such things to spaces, but maybe that's not working correctly.

**Comment by dkulp** [comment]
Actually, wonder if it's a windows thing.  Seems to work "ok" on the mac:

<img width="1226" alt="screen shot 2017-05-29 at 8 41 35 pm" src="https://cloud.githubusercontent.com/assets/91569/26564491/69b9ce72-44af-11e7-9bd7-662f732af2e3.png">

**Comment by cjd** [comment]
It may be a 'problem' with the text control itself - on some platforms there is automatic quote substitution occurring.
This was disabled on OSX at one point (reenabled in oct last year - but that is after wxwidgets 3.1 used by xlights)
It is easy to work around if restricting to 7bit ascii-only. Just change:
            wxString line = dlgLyrics->TextCtrlLyrics->GetLineText(i).ToStdString();
to
            wxString line(dlgLyrics->TextCtrlLyrics->GetLineText(i).ToAscii()); 

But then it would impact locales which need the non-ascii chars

**Comment by cjd** [comment]
I just committed a quick workaround for the issue which 'should' avoid it for wchars such as those quotes.
It doesn't affect anything which passed conversion previously - only coming into play when ToStdString fails

**Comment by ghormann** [comment]
Thanks!

**Comment by cjd** [comment]
New push which is a 'smarter' fix - converts wide single/double quotes to ascii first before attempting conversion.
That should fix up this issue - but if we want to support unicode/wide chars properly the changes will be more extensive as std::string is used for effect name instead of std::wstring all over the place (a job for another day)

**Comment by dkulp** [comment]
FYI:  on the Mac, std:string works just fine for unicode strings.  I can type (or copy/paste from web sites) chinese or japanese or whatever into the import lyrics dialog and the result appears in the XML just fine.  The OpenGL rendering cannot RENDER those characters in the labels, but I can double click on the label and the unicode value appear in the dialog for editing. 

`<Effect label="吾輩は猫で∂る" startTime="10000" endTime="20000"></Effect>`
