### ISSUE TITLE
Enhancement Request - Sphere Model

### ISSUE THREAD

**Issue by tristalights** [smeighan/xLights#866]
Would really like to have a 360 Sphere model, or tweak existing 360 tree model to allow skewing to make it look like a sphere.

**Comment by AzGilrock** [comment]
So what formula should we use to know how many pixels are on each row of the sphere?

**Comment by keithsw1111** [comment]
Interestingly there is a hidden sphere model in the codebase ... I wonder what it does?

**Comment by AzGilrock** [comment]
Yeah I believe Sean started the Sphere model long time ago and never finished it.

**Comment by AzGilrock** [comment]
I just don't know all the parameters we would need to provide to cover all the variations of spheres users will build.

**Comment by tristalights** [comment]
Would it be possible to just duplicate the same parameters as the 360 mega tree but shape it as a sphere in models viewing/rendering purposes?

**Comment by AzGilrock** [comment]
Not everyone is going to build a sphere with the same number of pixels on every row.  We don't want to create a model that just works for you.

**Comment by keithsw1111** [comment]
This is done
