### ISSUE TITLE
Mapping not working on MAC (2017.15)

### ISSUE THREAD

**Issue by pstube731** [smeighan/xLights#868]
I've verified that it works on a PC but, the drag and drop feature is not working on the MAC. I only tried starting to use it on 2017.14 and 2017.15 and neither of them work.

**Comment by dkulp** [comment]
I just uploaded a 2017.15b that hopefully fixes this.   Can you try and close this if it does?

**Comment by pstube731** [comment]
Works perfect. Thank you!
