### ISSUE TITLE
Views Deletion - 

### ISSUE THREAD

**Issue by BrettG1981** [smeighan/xLights#869]
I am running the latest release version Xlights and I am new user.  

When I go to delete a View to only leave the Master view my XLights seems to crash and go into Debug mode and close.  

I also have noticed that when I go to start a new sequence of animation I have found there a multiple viewing options that do not exist??

Can you help.  It is getting quite annoying.  

Brett G

**Comment by AzGilrock** [comment]
We were already on top of this when reported by baf05.

**Comment by AzGilrock** [comment]
I verified where the problem was yesterday but I'm just coordinating with Keith for the best solution since he did some of the rework for that dialog.
