### ISSUE TITLE
If you delete all the models from a sequence and hit render-all, it renders forever.

### ISSUE THREAD

**Issue by jeffbuckalbany** [smeighan/xLights#872]
Hi Guys:
I Hit this small bug twice, while working on my models.  

Inside a sequence, if there were previously models but they have been removed from the sequence, the render all button is not grayed out and will cause xlights to render forever.  

Seems it just needs to have the render all button turn grey when there are no models present in a sequence that had them previously.  
This issue does not happen if you create an empty sequence - the button is grayed out correctly then.

**Comment by AzGilrock** [comment]
If you delete all your models from a sequence and then hit render all....here's your sign.

**Comment by keithsw1111** [comment]
Fixed for 2017.16
