### ISSUE TITLE
Enhancement Request: Test Light  - add intensity slider

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#873]
As a user I would like the ability to put Xlights in test mode and have the ability to adjust the overall output brightness.

Use Case: I am testing a 5v battery pack setup with ESPixelStick and some 5 volt nodes  I don't need 100% output, I'd like to ability to be able to adjust the output intensity from the "Test" menu only during testing.

Pat

**Comment by keithsw1111** [comment]
The existing sliders should give you the same capability. Just dont set them to 255.
