### ISSUE TITLE
Bug With Sound

### ISSUE THREAD

**Issue by livetoride** [smeighan/xLights#874]
I have noticed for example if i start xlights with my default sound device as the headphones, if i change that while i still have xlights open to the speakers it will only use the headphones for the sound. I don't know if its intentional or not but what ever sound device is default when starting xlights that's what it stays. It would be handy for me for that to be changed without having to exit xlights.

P.S - Doing a fantastic job everyone!

**Comment by keithsw1111** [comment]
There is really nothing we can do about this. This is down to the behaviour of your operating system.
