### ISSUE TITLE
Start channel in Layout not updating when node lengths change

### ISSUE THREAD

**Issue by lytnin00** [smeighan/xLights#877]
Using v 2017.17
To recreate ....
I have a new layout and made 3 trees of various dimensions.
- TreeA - 36x100
- TreeB - 24x100
- TreeC - 16x50

Start channels:
- TreeA - 1
- TreeB >TreeA:1
- TreeC > TreeB:1

THE BUG
Changing the node length of TreeA, causes the following items (in this case TreeB & TreeC), to keep the start channels they previously had.

Case 1 - If the node length increases, there are overlaps. Having the 'Overlap checks enabled' ticked didn't detect the overlap.
Running 'Tools > Check sequence', does detect the overlap.

Case 2 - If the node length decreases, no visible effect in preview.
Running 'Tools > Check sequence', does detect the large unused block.

Work around is to click on the start channel of the second item to get it to recalculate.

Cheers
Dave K

**Comment by keithsw1111** [comment]
I think this is fixed.
