### ISSUE TITLE
Bug: Picture Effect

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#882]
Trying to enter -100 in the end position field and xLights won't allow a fourth "digit" to be entered.  Only three spots are allowed.

![screen shot 2017-07-21 at 6 50 02 pm](https://user-images.githubusercontent.com/12144876/28486371-deb5ca08-6e46-11e7-98f4-e472940bbc09.png)

**Comment by kppankratz** [comment]
After the latest release addressing this, I still cannot enter -100 in either the x or y axis fields for the end position of the picture effect.  Not sure if other items affect this so I'm including a larger image showing the settings in the window.  Whenever you have time as this is not a big priority.
<img width="455" alt="screen shot 2017-07-27 at 7 32 28 pm" src="https://user-images.githubusercontent.com/12144876/28697580-94e5f414-7302-11e7-91a5-eb2b2ff9e097.png">

**Comment by keithsw1111** [comment]
I think I just changed start position. Doh
