### ISSUE TITLE
[Mac] Preview panels randomly move to main monitor

### ISSUE THREAD

**Issue by nathan815** [smeighan/xLights#884]
I like to have xLights on my external monitor (plugged into my MacBook Pro), and the house and model preview panels on my MacBook's screen so I can easily view them while sequencing. But the panels don't like to stay put on the screen. They will randomly move back over to the external monitor and sometimes even "redock" to the main xLights window in a very strange location (e.g. stretched out across the top of xLights right above the waveform). Sometimes it happens if I click one of the windows or just move my mouse over them, and other times it seems to just happen without any action.

**Comment by keithsw1111** [comment]
Is this still a current issue?

**Comment by AzGilrock** [comment]
The same issue is documented in more detail in #904 so I'm gonna close this one.
