### ISSUE TITLE
F10 Not working with subfolders enabled.

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#887]
This video should demonstrate the problem. When I press F10 or select backup from the menu xLights can not create associated folders for the backup.

https://youtu.be/KUtOHAOrYJQ

**Comment by keithsw1111** [comment]
Error 183:

ERROR_ALREADY_EXISTS
183 (0xB7)
Cannot create a file when that file already exists.

this can happen if you try to do a backup twice in the same minute ... could that be what you are seeing?

**Comment by keithsw1111** [comment]
Try in v21 ... I have tried to prevent these clashes.

**Comment by keithsw1111** [comment]
.21 will still help because it does some extra logging.

**Comment by MrChristmas2000** [comment]
Loaded up .21, same results. No change in the backup errors.

**Comment by AzGilrock** [comment]
In the video the first thing you show is a folder that you claim is the sequence folder but when you open xLights you are pointing to a completely different folder.  The first one is Q: and the second is D: and the paths are different so you had me all confused.

![image](https://user-images.githubusercontent.com/2024669/28756920-416e1a0a-752d-11e7-9953-7655c815684c.png)

**Comment by MrChristmas2000** [comment]
Ok, sorry about the minor confusion. I back all my main files up to a server with almost identical paths and I had copied the servers path and not the local machine path. I have produced a followup video that further demonstrates this subfolder backup failure. https://youtu.be/9lTK061lI0Q
