### ISSUE TITLE
ac cascade on 21

### ISSUE THREAD

**Issue by 1991mustang50** [smeighan/xLights#889]
selecting and pushing h on keyboard does nothing doesnt matter direction

**Comment by keithsw1111** [comment]
Yeah ... there is a bug here but to work around it press n first then h ... from memory.

**Comment by 1991mustang50** [comment]
Still nothing I just wait just reportingissue.

**Comment by keithsw1111** [comment]
Fixed for release in .22

**Comment by 1991mustang50** [comment]
Thank you for all your work!!
