### ISSUE TITLE
Bug: Missing Standard Value Curves - Mac version

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#890]
After watching a feature walk through video of Keith's from a week ago, I realized that the Mac version isn't showing the same function as the Windows counterpart.  I've included two screen shots showing the differences.

I'm using the most recent downloaded version from Dan.

<img width="522" alt="screen shot 2017-08-02 at 8 12 30 am" src="https://user-images.githubusercontent.com/12144876/28875303-bd46b18a-775a-11e7-9c43-a6f1b5a1fa91.png">
<img width="1025" alt="screen shot 2017-08-02 at 8 07 17 am" src="https://user-images.githubusercontent.com/12144876/28875312-c76e6770-775a-11e7-8e65-06c4b55c3bfb.png">

**Comment by AzGilrock** [comment]
What are you talking about those buttons?  The standard curves are in the drop-down.  I don't think I have those buttons on my Windows version.  I've never seen them.  Did you grab that from Keiths video or your own install?

**Comment by AzGilrock** [comment]
Are you sure Dan's release is in sync with the Windows release?  We don't guarantee that they are always the same its just when the volunteers decide to do the work.

**Comment by kppankratz** [comment]
I'm using 2017.21 downloaded from Dan's server.  The screen grab from Keith's video is showing 2017.20.

I typically use the drop down to select the curve, but I noticed that there was a difference since I did see them yesterday on the Windows version at work and didn't at home on the Mac.

**Comment by AzGilrock** [comment]
Ok but you hit your issue limit for the year already.  Shoulda saved it for a better one.

**Comment by dkulp** [comment]
Just need to get the valuecurves directory packaged with the resources... next build will have it.

**Comment by kppankratz** [comment]
Thank you Dan.  I pulled the latest code and compiled the program, and those presets are now there.
