### ISSUE TITLE
Bugs with layout tab

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#891]
I made a detailed video on the 3 bugs I found in the layout tab.  See the link below...

First is the auto copy-paste prop numbering, for when you past multiple copies of the same prop.  When I create the prop then copy it, the auto-naming feature adds a "-1, -2,-3"  Well, when I'm making 10 of something, I end up having to rename each model anyway. Is there a way to tell the prop what number to begin with when using the past feature?  Can it just start at -2 after the first?

Second, I noticed I had to keep resizing the Model | Start Channel | End Channel fields in the setup screen so I could see the end universe of the prop.  I then could re-number the start channel for that prop.

The next bug I found was after creating the pasted copy of a model, I would change the name of the prop.  Then directly after changing the name, I would click on the Start Chanel field to make the appropriate change.  That click would default back to the background of the layout tab, causing me to re-click on the model that was previously selected.

None of these are major bugs, just annoyances I experienced while setting up numerous display this summer.

https://youtu.be/6i3jlmF0A-s

**Comment by keithsw1111** [comment]
Bug 1 fixed.

**Comment by keithsw1111** [comment]
Bug 3 fixed.

**Comment by keithsw1111** [comment]
Bug 2 fixed.

**Comment by AzGilrock** [comment]
None of those are bugs.
