### ISSUE TITLE
Bug: Value Curves in Different Position Using the Same Settings

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#892]
I'm saving some value curves to apply to different effects and I noticed that for some reason they do not produce the same results.  I noticed this between the Fan and Pinwheel effects.

For simplicity sake, apply even a flat value curve to each effect using the same settings shows that the position of the effect is not the same.  In the case of the Pinwheel, you can only really place the effect in the upper right quadrant of the model using the value curves.

<img width="825" alt="screen shot 2017-08-06 at 3 06 39 pm" src="https://user-images.githubusercontent.com/12144876/29006750-96c563a8-7abb-11e7-9857-041196b7054c.png">
<img width="844" alt="screen shot 2017-08-06 at 3 06 06 pm" src="https://user-images.githubusercontent.com/12144876/29006751-99e81422-7abb-11e7-9b3f-c57e397a1924.png">

**Comment by AzGilrock** [comment]
Those are 2 different effects so their position is controlled differently inside each effect.  I have no idea which setting you were trying to modify with the value curves.

**Comment by kppankratz** [comment]
In the examples I'm showing the x axis position.  I apologize for not pointing that out.  With the Pinwheel, as soon as you try to apply a VC to either the x or y axis, the center point changes.  Because of this shift in the x and y center, you can never get the effect be go anywhere other than the top right quarter of the model.

The Fan effect works as expected with the VC's, but the Pinwheel does not.

**Comment by AzGilrock** [comment]
Two different people wrote the effects.  I wrote Fan so it uses a 0 to 100 range for position and is a percentage.  Pinwheel looks like it uses a -100 to +100 range for position.  The screenshot looks like the value curve for Pinwheel is showing 0 to 100 so maybe there is a bug in the value curves for any ranges that go negative.  It looked like the code attempted to set a negative range for the curve but its not being honored.

**Comment by AzGilrock** [comment]
Ok I'm not seeing the same thing.  When I drop a Pinwheel and click the value curve for the x-axis I get a -100 to +100 range and it seems to work fine.  I'm also not seeing any of those buttons you have on yours.
![image](https://user-images.githubusercontent.com/2024669/29056340-20d1502e-7bb7-11e7-921e-49d92bc51d00.png)

**Comment by AzGilrock** [comment]
Well it looks like you have to actually export a curve to get a button so I see one button now.  Everything appears to work fine are you sure you didn't click the wrong curve?

**Comment by AzGilrock** [comment]
Based on your screenshot I see the "Roto-Zoom" tab just above the value curve dialog so I'm going to assume you were probably trying to use the "Pivot Point X" curve.  That is not the correct curve for positioning the effects.  That is a pivot point for rotating the effect's render buffer.  You need to use the value curve on the effect setting panel called "X-axis Center" to move the Pinwheel.

**Comment by kppankratz** [comment]
I was only using the x and y position under the effect settings.  I did not touch Roto Zoom.  Based on what you were seeing, I played around a little more this morning with this.  A fresh start of xLights and the VC's work fine for positioning.  What I found is after I load a custom VC is where I'm seeing the center point change.   Turning off the VC reruns normal control and positions to the sliders.  Turning the VC back on after that once again changes the center point, even for the built in flat setting.  Flat at 0 initially is all the way to the left, as in your screen shot.  After applying a custom VC, selecting flat at 0 position is now in the center of the screen.

Here are the VC files I'm using.  Same as I posted in the FB group yesterday.  I only notice this on the Pinwheel effect though.

[Value Curves.zip](https://github.com/smeighan/xLights/files/1207773/Value.Curves.zip)

**Comment by AzGilrock** [comment]
Ok either or Keith or I will need to look at that.  My guess is that the presets are altering the range.

**Comment by AzGilrock** [comment]
Well not presets but whatever you called the saved VC's.

**Comment by keithsw1111** [comment]
I will need to take a look ... i suspect we are setting the limits wrongly (or more likely not setting them at all in some case which then defaults to 0-100 instead of -100-100)

**Comment by AzGilrock** [comment]
I thought I checked the PinwheelPanel code yesterday and saw it was setting the limits.  Question is whether loading the saved curve can alter the limits.

**Comment by keithsw1111** [comment]
The limits are stored in the preset ... so i dont think so ... but i need to check.

**Comment by AzGilrock** [comment]
Well isn't that the problem?  Someone creates a preset from Effect1 parameter XYZ which has a negative range and then tries to use it for Effect 2 parameter ABC.  Do the presets only show up for the exact value curve they were created within?

**Comment by keithsw1111** [comment]
Value curves are a property on the effect they were saved with ... so it should be ok. The only difference is the saved *.xvc files which are saved with a 0-100 range but when clicked are adjusted to the range of the setting they are being applied to.

**Comment by kppankratz** [comment]
Seems to work now with the new releases after 2017.24
