### ISSUE TITLE
Crash After saving new input setup

### ISSUE THREAD

**Issue by jerryszewc** [smeighan/xLights#894]
![ver 2017 22](https://user-images.githubusercontent.com/13650588/29047601-f893128e-7b91-11e7-884f-016bfc114082.PNG)
[xLights_dbgrpt-11708-20170807T165806.zip](https://github.com/smeighan/xLights/files/1206298/xLights_dbgrpt-11708-20170807T165806.zip)

**Comment by AzGilrock** [comment]
This was over a year ago does anyone still believe there to be a problem?

**Comment by keithsw1111** [comment]
Memory is a bit hazy but pretty sure we did fix the underlying cause of this. I havent seen crashes in that function in quite some time. Closing. If someone thinks it is still happening please reopen and attach a recent crash report.
