### ISSUE TITLE
Crash when trying to make a new sequence

### ISSUE THREAD

**Issue by KevD44** [smeighan/xLights#898]
[crash.pdf](https://github.com/smeighan/xLights/files/1236130/crash.pdf)
i keep getting a crash when i try to make a sequence.

**Comment by AzGilrock** [comment]
I can't open that PDF.  Adobe Acrobat says it's corrupted.  But we really need a zip file with a crash report.  Unless you give us the files and steps to cause the crash its useless posting this.  Also you didn't say which version you were using.

**Comment by AzGilrock** [comment]
Closing since no additional info was provided.
