### ISSUE TITLE
Implement ability to have multiple strings on custom models

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#902]
For large custom elements that have multiple physical strings and do not have contiguous addressing.

**Comment by AzGilrock** [comment]
That's already possible.  The numbers you put on the custom grid do not need to be contiguous.

**Comment by idleup** [comment]
So string #1 has start address #192.168.7.101:2:1 and string #2 has start address #192.168.7.104:37:1. How do you do that in the model? The start addresses are on different controllers and in different universes. What if the second string is a lower start channel? What if you add an element and the address for string #2 changes, you would have to manually revise every channel in the model right?

**Comment by AzGilrock** [comment]
So plan your universes better.  You are the one configuring it all so make the universes contiguous even though they are on 2 controllers.

**Comment by AzGilrock** [comment]
I think the mistake is people want to define their controller universes/channels and then act like they can't be changed.  I like to define everything in xLights and then let that drive how the controllers are configured instead of doing it the other way around.

**Comment by idleup** [comment]
I understand what you are saying but being able to assign start addresses to individual physical strings rather than rely on them being placed in continuous order while not explicitly defining anywhere in xLights that the string exists is confusing and harder to make changes.  Other elements have the ability to have multiple strings so in the name of consistency I think the request should stand so custom models have the same capability.

**Comment by AzGilrock** [comment]
Is there a reason you are using IP addresses in your start channels?  With 64,000 universes available not sure why you would need to have repeats.

**Comment by idleup** [comment]
I guess it is just habit to use the IP addresses. I can more easily tell what controller an element is plugged in to when scanning through my models when I see the IP. I also have an excel file that maps all my elements by IP address and gives me the universe start/end for each.

**Comment by AzGilrock** [comment]
Reason I ask is if you were using just native universe numbers you could pretty much guarantee that the gap between the 2 strings would never change after you figured out what offset you needed to add to half the numbers.  To support multiple strings it would obviously take a different notation to be entered in the cells.

**Comment by computergeek1507** [comment]
added in 2018.57
