### ISSUE TITLE
Edit Lyrics from Timing Marks

### ISSUE THREAD

**Issue by kwoodard** [smeighan/xLights#903]
When attempting to edit lyrics by double clicking on timing mark region, the "Edit Label" dialog no longer appears.  Instead, the sequence plays for the time period between the two timing marks.  This worked in the latest stable release (2017.14), but I just noticed this behavior in the latest release (2017.25).  Not sure when it was introduced.

**Comment by keithsw1111** [comment]
This is deliberate. There is an option in the settings menu to switch the behaviour back to the old behaviour or you can just shift-double click
