### ISSUE TITLE
Font size GUI bug

### ISSUE THREAD

**Issue by madsci1016** [smeighan/xLights#906]
In the font effect, increasing to a large font, like 72pt, triggers the gui to expand the 'Font' field to a size that pushes Start/Stop position boxes below the view of the window. 
![bugxlights](https://user-images.githubusercontent.com/1082294/29902038-41920e86-8dc1-11e7-8f47-e84c5ebb351a.PNG)

There is no way to scroll down to see them and no size you can expand the Effect settings box to to regain visibility of those fields.

**Comment by computergeek1507** [comment]
Fixed with ce232426cb6556a7628912bab2bbcd0ebd25dd6b
