### ISSUE TITLE
Effects don't appear on model but show when I play the sequence

### ISSUE THREAD

**Issue by broomy111** [smeighan/xLights#907]
Hey guys,

I'm on ver 25 and I was noticing that effects I had dropped on my sequence earlier in the day, I don't see on the mega tree anymore, but if I play the sequence, I can see the effects I had dropped on there.  With this sequence, at 31.50, is the area where the effect is playing and I don't see it in the sequencer. 
![image](https://user-images.githubusercontent.com/28641357/29955426-5f53bea0-8e94-11e7-8539-75d5dbf60a2d.png)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/1269166/xLightsProblem.zip)

Thanks

Kevin

**Comment by AzGilrock** [comment]
So I don't see anything on the tree in that time period when I play it.  Did you do a Render All first?
Also how was that "Poly" timing track created because it contains illegal timing effect overlaps.

**Comment by broomy111** [comment]
Hi Gil,

That was the polyphonic transcription and I accidental renamed it.  Here is
a link to the video.  After the pinwheel\ snowflakes on the mega tree,
there doesn't show the effects but it plays in the sequence.  Not sure what
I screwed up.  :-)


https://drive.google.com/file/d/0B6N6-an0lJKSUFhzUlRmUlYtbU0/view

**Comment by broomy111** [comment]
Hi Gil, I see now that the effect is showing at the strand level.  
![image](https://user-images.githubusercontent.com/28641357/29986074-aec1784c-8f16-11e7-98b6-637ace0a70de.png)

**Comment by AzGilrock** [comment]
So that's not effects that's just data.  But I don't see it so can't help you.
![image](https://user-images.githubusercontent.com/2024669/29991942-2e2ab53e-8f45-11e7-91b9-a2c35e5c7eb1.png)

**Comment by AzGilrock** [comment]
Are you sure you didn't change your render mode.  It defaults to Erase mode but if you changed it to Canvas mode it would leave artifacts like that.
![image](https://user-images.githubusercontent.com/2024669/29991959-7b84ee08-8f45-11e7-8abf-eb223a4023aa.png)

**Comment by broomy111** [comment]
I checked and my render modem is still default.  I'm syncing between 3 machines with Google drive and the larger my files get, its taking some time to sync and this might be causing my issues.  I'm moving to a locally stored show directory and see if things like this go away.  With that data left behind, is there anyway to get rid of it because doesn't look like I can just highlight it and delete it.

Thanks for checking on this Gil

**Comment by broomy111** [comment]
Last comment-  Solved -I moved my directory off of the google drive and its sitting locally and all that data that was on the mega tree went away, so looks like my syncing was causing issues.

Keeping it local from now  :-)


Thanks
