### ISSUE TITLE
Bug on Spiral Effect

### ISSUE THREAD

**Issue by RaceMedic** [smeighan/xLights#908]
I am using 2017.14 .....

When I am doing a spiral effect it is fine with 4 or 6 colors but when i try to use 5 colors it also adds a black line so it looks like a gap in it.  I find it in either 270 or 360 view.

Dave

**Comment by AzGilrock** [comment]
Here's a 5 color spiral on a tree with no black:

![image](https://user-images.githubusercontent.com/2024669/30256228-096c16d2-965e-11e7-931f-98f848312efb.png)

**Comment by AzGilrock** [comment]
You failed to tell us how many strands but I can guess it's not divisible by 5.  The reason you are seeing this is the same reason you can't split a nickel 3 ways.

This is also a duplicate of #370.
