### ISSUE TITLE
Crash on save of imported file. 4.0.1

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#91]
The crash file can be found here:
https://dl.dropboxusercontent.com/u/28041968/Nutcracker%20Testing/xLights_dbgrpt-4908-20150322T104103.zip

I have also included the .iseq in a zip here:
https://dl.dropboxusercontent.com/u/28041968/Nutcracker%20Testing/Carol%20of%20the%20Bells%20-%20MASTER%20FILE_12_09_2014.zip

The .xseq file for importing is here:
https://dl.dropboxusercontent.com/u/28041968/Nutcracker%20Testing/Carol%20of%20the%20Bells%20-%20MASTER%20FILE_12_09_2014.xseq

The video demonstrating this crash is here:
http://youtu.be/fnrf26Omx1k

I have tried this process on at least two different sequences with the same results.

**Comment by AzGilrock** [comment]
I just tried this out and didn't get it to fail yet.  I do notice the rendering issues appear to be fixed that were talked about in #80.  Is this crashing every time for you or is it intermittent?

**Comment by MrChristmas2000** [comment]
Ok, went back and deleted all sequences from the test folder.
Loaded up one that I had not yet tried. It imported, saved, and played ok.
Next I tried the Carol of the Bells one, and It imported, saved, and played ok.
Lastly I loaded my WIW sequence and it crashed at the same point as it had done earlier just like the video.
I am running on a W7 32b box which only has 3GB or ram that is usable.
I'll keep trying more of my sequences to see if it is just a random thing.

**Comment by MrChristmas2000** [comment]
More info.
Soma time it works, soma time it don't. :)
I even turned Areo on and off with no change in results.
Went back and tried to import one that had previously worked and it crashed the second time.
This was even after i rebooted the machine.

**Comment by AzGilrock** [comment]
I finally got your sequence to crash on save.  This is several times now that I've seen crashes related to the rendering of the Text effect.  There's some special code that tries to treat that effect differently because of the drawing context used and it appears to be causing a lot of problems.  Dan might be more familiar with what's going on with that part of the code.  I'm attaching a screenshot of the stack trace for the
![textcrash](https://cloud.githubusercontent.com/assets/2024669/6773969/fc1258ac-d0d5-11e4-8a97-ec9fc89528c0.jpg)
 crash I caught in the debugger.

**Comment by MrChristmas2000** [comment]
I can find the strangest bugs can't I.

**Comment by dkulp** [comment]
Can you re-try this?   I've never been able to reproduce this so I'm pretty much just taking shots in the dark.  :(

**Comment by AzGilrock** [comment]
I was wondering if the text render really needs to be put on the main thread.  The comment says we are doing that because of GDI but I don't believe we have GDI compiled into wxWidgets because I tried to use the wxGraphicsContext for something else and it wasn't avaiable.  Since we are using the wxMemoryDC for drawing the text maybe we don't need to do special threading.

**Comment by dkulp** [comment]
On the MAC and Linux, we DO use the wxGraphicsContext for drawing as that's the only way to not get the anti-aliased text that looks awful on low-res matrix displays.

**Comment by MrChristmas2000** [comment]
So does that mean I need a MAC or a Linux box in order to not get this failure?

**Comment by AzGilrock** [comment]
MAC probably handles the threading better than Windows.  My comment still applies for Windows.  Maybe we don't need to try to throw the task to the main thread on Windows.

**Comment by dkulp** [comment]
This was added in 3.6.9:

    -bug (dkulp) Move Text effect rendering back to main thread due GDI calls it makes (to get Font info and to render the text) which is required to be done on the main thread.

*THAT* said, one of my goals was to only have it render the bitmap/image for the text on the main thread at the first frame of the effect.   Then is should just be a matter of moving the bitmap around.     Never got around to doing that.

In any case, try with 4.0.3 whenever sean builds it.

**Comment by MrChristmas2000** [comment]
Waiting with baited breath. :)

**Comment by AzGilrock** [comment]
I got a crash first try at saving MrChristmas' sequence with no crash report produced.  I then ran in debugger and it crashed first attempt to save the same sequence.
![textcrash2](https://cloud.githubusercontent.com/assets/2024669/6794221/4b95a3aa-d18c-11e4-9795-d38c02d73532.jpg)

**Comment by dkulp** [comment]
Gil,  can you try again?   I cannot reproduce on Windows or Mac.  :(

**Comment by MrChristmas2000** [comment]
I get it randomly, I tried it again after installing the 4.0.2 ver tonight and tried one that failed last night on 4.0.1 and it imported completely without crashing. I don't have time to do it now but I'll try all the sequences tomorrow to see if 4.0.2 crashes. Will report results.

Also my machine is only a Win7 32b machine. Don't know for certain if that would make any difference or not..

**Comment by AzGilrock** [comment]
So I did 8 saves and only got 1 crash but the time I got it to crash I clicked on a text effect in the grid while it was in the middle of the save.  So I'm not sure if we're not locking something out we should be during the save.
![textcrash3](https://cloud.githubusercontent.com/assets/2024669/6794861/141f6632-d195-11e4-8fff-9e63e5b6360a.jpg)

**Comment by AzGilrock** [comment]
Other than the crash I caused by clicking I hadn't seen it do 5 consecutive saves in a row until now.

**Comment by MrChristmas2000** [comment]
I clicked on the sequence tab before I did the save if that makes any difference, but it didn't crash right after the new install.

**Comment by dkulp** [comment]
Gil:  when you screen capture the trace, can you make sure you grab the file and line columns like you did on the first capture above?   Thanks!

Clicking in the sequencer and adjusting things SHOULDN'T cause a crash, but it will likely cause the render to stop.  There is a short circuit in the rendering where if an effect changes, it gracefully stops.

**Comment by AzGilrock** [comment]
I did 10 more saves and couldn't get it to crash even when clicking on a few effects.

**Comment by MrChristmas2000** [comment]
I started down my list of sequences and the fifth one crashed. It seems to be a random occurrence. Maybe I am the only tester doing a data merge, who knows.
To keep things consistent I am only using the 'file open' icon to start the process and the 'file save' icon to save the sequence with the 'preview' window open so I can play the sequence once conversion occurs.

**Comment by AzGilrock** [comment]
Unless Sean put out a new version last night its not worth retesting this.  Dan made some fixes that I was testing out and it looked to greatly improve things.  I don't think the code your testing with has the change from after he asked me to test it out again.  I'm able to pull the changes and test before the releases happen.

**Comment by MrChristmas2000** [comment]
Ok no problem, I'll retest again when a new release is out.
If it goes away I'll just chalk it up to one of those mysteries of computing. LOL :)

**Comment by MrChristmas2000** [comment]
Looks like 4.04 fixed this. Three Cheers!!! :) :) :)
I imported all of my sequences without one crash.
I'll close this as an issue. Dan and Gill thanks for your assistance with this.
