### ISSUE TITLE
Submodel window missing

### ISSUE THREAD

**Issue by algerdes** [smeighan/xLights#910]
Click on model.  Click on "submodel" in properties window.  No window to put in submodel information appears, yet the screen appears to lock (model behavior?).  Pressing esc brings the main window back to availability.

I believe that the submodel window is outside of the viewing area.  I cannot find how to bring it back into view.

2017.27

**Comment by AzGilrock** [comment]
This sounds like the result of the 3 monitors with different resolution issue you just posted on the forum.  Firstly is this a Windows machine and which version OS?  If Windows do you see the submodel dialog when you alt-tab through all the windows?  And I don't mean does it bring it into view I just mean do you see it as you scroll through all the available windows?  If so then there are steps to bring that window into view that you can easily Google.  Just search for "How to move windows that open up off screen".

**Comment by algerdes** [comment]
This definitely has to do with the display configuration, and the last area that the model window was in.  I was able to recreate the display configuration to what I had used the last time I was in the submodel window and it was there.  I moved it to a new location, then reset the displays to what I am using now (physically).  

Since I go back and forth between the laptop, by itself, and the 2 and 3 monitor setup, I can see that there is a need to have a "reset" button.

**Comment by algerdes** [comment]
Windows 10, fully updated. 
No, the submodel window does not show up doing "alt-tab".  (Good idea to check that, thanks.)

**Comment by AzGilrock** [comment]
So you should be using "Perspectives" and then you just double-click the perspective to "reset" to which monitor configuration you have.

**Comment by algerdes** [comment]
FYI - the shift-move function of Windows does not work with the submodel window.  Not sure why, but it is probably something related to the submodel window not showing in the list of windows under alt-tab.  I do  know that the window always comes back to where it was last at in relationship to the home corner of the main window.  For example, if it was last at 2040 & 4000, it reappears there even if that location does not have a screen to display on.

Knowing this fact, I'll do what I need to do.

**Comment by keithsw1111** [comment]
Try starting xlights with the /w command line switch. This will wipe all of your settings but bring back the dialog.

**Comment by keithsw1111** [comment]
Alternatively bring it up .:: and when it should have focus hold down the windows key and hit the arrow keys several times. This moves windows between monitors.

**Comment by algerdes** [comment]
Great ideas.  I'll keep them all in mind. 
I'm going to close this one at this time.  You have much more important stuff to work on, I'm sure.
Thanks again.
