### ISSUE TITLE
Program crashes after moving from setup to layout tab

### ISSUE THREAD

**Issue by RobertBurton1** [smeighan/xLights#911]
While working on connections in the layout tab, I clicked on the setup tab. It then crashes. This has happened multiple times. 
[xLights_dbgrpt-2632-20170913T220719.zip](https://github.com/smeighan/xLights/files/1302456/xLights_dbgrpt-2632-20170913T220719.zip)

**Comment by keithsw1111** [comment]
I think i have already fixed this ... but check when .28 comes out.

**Comment by RobertBurton1** [comment]
Thanks Everyone!
