### ISSUE TITLE
Circles Effect

### ISSUE THREAD

**Issue by ebuechner** [smeighan/xLights#915]
When the check box for radial and Radial 3D are both checked together you can no longer use the color palette and it defaults to a rainbow pattern.

**Comment by stevegiron** [comment]
Set a color wash on the second layer and set the blending mode on the top
layer to additive, subtractive, average, min, max and you can change the
colors that way.

**Comment by AzGilrock** [comment]
I really don't know what that Radial3D option was supposed to do.  It's ignored unless you check the Radial box in the first place.  I went back to beginning of 2016 releases and it's always worked this way.

**Comment by AzGilrock** [comment]
Going through older issues to find ones to fix or close out.  I investigated this and the Circles effect does use the color palette but what happens is the Hue of the color is modified based on the effect state which is an internal representation of how far along the effect is in its duration.  This is how the effect has always worked so I don't want to change it on people.
