### ISSUE TITLE
Copy Error

### ISSUE THREAD

**Issue by jeremywilley** [smeighan/xLights#918]
![capture](https://user-images.githubusercontent.com/32086419/30576093-39480eda-9cba-11e7-98a8-9c5fafb3f24e.PNG)
Every time I try to copy a effect it crashes xlights. I have tried using ctrl+c and right click and copy.  I am on the latest beta

**Comment by keithsw1111** [comment]
Can you package up your sequence and send it to us. keithsw1111 at hotmail dot com

**Comment by keithsw1111** [comment]
Jeremy?

**Comment by jeremywilley** [comment]
I would but I had a hard drive failure. I reloaded everything and cannot reproduce it. I wonder if it was a corrupt dll  in Windows causing it. If it happens again I will package it all. At this point if needed close the thread. Thanks
