### ISSUE TITLE
Bug: Text effect and Buffer Value Curves

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#920]
Attempting to manipulate the text effect using some value curves on the buffer area.  The initial application of a VC seems to work initially.  After making an adjustment to the effect though, the effect stops showing up in the preview window.  Resetting the buffer and removing VC's does not correct the problem.

Then I noticed that the sequence cannot be closed, or the program cannot quit (have to force it to quit through the OS).  I've attached a link to a video showing this.  There is no audio.

I just noticed a menu option to force xLights to crash.  Once the program is in this state, if I force it to quit using the menu option, will the debug report possibly give you information needed to track this down and fix it?

I've only noticed this with the text effect so far.  I cannot reproduce using Butterfly.

https://www.dropbox.com/s/pbnb91bpip9tmmz/Untitled.zip?dl=0

**Comment by keithsw1111** [comment]
You must be running a debug build. The crash menu item should not by default appear in the release build unless a special file is present. That menu option is there to let me force a crash and test crash handling and status display.

**Comment by kppankratz** [comment]
Crash xLights in the release from Dan today, and when I compile for running myself.

**Comment by dkulp** [comment]
Well...   NDEBUG has never been defined for the Mac compiles.   We have DEBUG for debug builds, but not NDEBUG.   I just added it and will rebuild.    That explains the weird menu item.
