### ISSUE TITLE
Add optional play controls to the model preview

### ISSUE THREAD

**Issue by GrizAF** [smeighan/xLights#922]
Would it be possible to add the same playback controls from version 2017.26 on the model preview as well as the house preview?  If other members are like me I spend most time on the model preview opposed to the house preview.  

Thanks for all you do!

**Comment by keithsw1111** [comment]
I am not going to do this

**Comment by AzGilrock** [comment]
LOL...users are never satisfied are they? I veto this as well.  The only reason it was put on the House Preview is because users wanted to maximize that preview to full screen.  There should be no reason anyone needs the model preview to take up the whole computer screen.
