### ISSUE TITLE
Check Sequence Crash

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#923]
Simply trying to run the check sequence function and I'm crashing on macOS 10.12.6.  Running xLights release 29.

[xLights_dbgrpt-2315-20170919T165251.zip](https://github.com/smeighan/xLights/files/1319831/xLights_dbgrpt-2315-20170919T165251.zip)

**Comment by keithsw1111** [comment]
I dont know what you did Kevin but it makes no sense ...

2017-09-19 16:52:46,026 140736597918656 log_base [INFO] Quit
2017-09-19 16:52:46,026 140736597918656 log_base [INFO] xLights Closing
2017-09-19 16:52:46,026 140736597918656 log_base [DEBUG] Closing sequence.
2017-09-19 16:52:47,891 140736597918656 log_base [INFO] Aborting rendering ...
2017-09-19 16:52:51,517 140736597918656 log_base [CRIT] ^^^^^ xLights crashing on purpose ... bye bye cruel world.
2017-09-19 16:52:51,517 140736597918656 log_base [CRIT] Crash handler called.

You seem to have quit xLights and then the deliberatey crash function seems to have been called. weird. There is no way that happens in the code as I see it.

**Comment by kppankratz** [comment]
Open xLights.
Open sequence.
Attempt to run Check Sequence.
Crash.

That's it.  This is using Dan's release to rule out a compile issue on my end.  Here's another debug report using the above steps.

Now that I look at the different crash reports I have over the last day or so, the first one probably wasn't the correct one for this ticket, based on the time stamps.  My fault.  The first one is from when I was messing with the text effect and value curves, and xLights would not close sequence, or quit.  So I had to crash it (using the secret menu item that showed up) or force quit the program.

[xLights_dbgrpt-545-20170921T054751.zip](https://github.com/smeighan/xLights/files/1320866/xLights_dbgrpt-545-20170921T054751.zip)

**Comment by dkulp** [comment]
Can you re-compile and try now?    I *think* it has something to do with your IP address as it doesn't look like it could create the datagram properly or something.  Do you have a "Force Local IP" option set?

**Comment by kppankratz** [comment]
I will compile the code this afternoon when I get home and try it out.

**Comment by kppankratz** [comment]
Check sequence works now without crashing xLights. I do not have the Force Local IP option set.

The program also loads a lot faster with your other checkin too.
