### ISSUE TITLE
Enhancement:  Morph

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#924]
Just curious if there is a to reverse a morph without changing the sliders or using the effects assist?  Basically can a checkbox be added to switch the direction of the morph?  So 1a would switch with 2a, 1b would switch with 2b.  A morph direction could be reversed very quickly if this were possible.  I have multiple morphs with these single ribbons.  Using the buffer tab does not yield the result I'm looking for, which is a quick way to take sort of an explosive multi-layer morph and reverse it to an imploding morph.

Thanks for looking!

Clyde

**Comment by AzGilrock** [comment]
If its a full length morph I use the Quickset combobox to reverse directions.

**Comment by Clyde-L** [comment]
Well yes I do use that.  I'm talking about for specific points you've selected in the Effects Assist screen.  Having multiple layers of smaller morphs.  And having to re-draw them to create the opposite effect.

**Comment by stevegiron** [comment]
Clyde in your morph how to video, you stated to use the flip buffer feature. Does that work for you?

**Comment by Clyde-L** [comment]
No it did not Steve... here is a video describing exactly what I mean.  

https://www.youtube.com/watch?v=f-iGLP5Jq78&feature=youtu.be

**Comment by AzGilrock** [comment]
My main hesitation with adding a checkbox to reverse them is users will forget the box is checked and be complaining its not going the right way.

**Comment by Clyde-L** [comment]
Sounds like it could be done :)

PLEEEEEEEEEEEEEEEEEEEEASE ????? 

:)

:)

Gil you would be the best! 🥇

**Comment by keithsw1111** [comment]
I am not sure a checkbox is the best approach as I think it would be confusing. What would make more sense is a button on the effects panel or maybe a right click option in the assist window as it is more of an action to swap points.

**Comment by AzGilrock** [comment]
Yeah I kinda like using a button better.

**Comment by Clyde-L** [comment]
If you put it on the Effects Assist window as a right-click option, people won't easily find it, thus messing with it.  Putting a button on the effects panel would be a better option I think as well.

**Comment by stevegiron** [comment]
Finally an enhancement request that has merit! Nice one Clyde. Hope this one is implemented.

**Comment by computergeek1507** [comment]
It this what you had in mind?

![swap](https://user-images.githubusercontent.com/2293065/30978667-32bf34e4-a449-11e7-8b9a-bacb33a8290c.gif)

**Comment by computergeek1507** [comment]
Another Test Shape

![swap2](https://user-images.githubusercontent.com/2293065/30978912-fb2ecf52-a449-11e7-9b4d-e86db860b3cd.gif)

**Comment by AzGilrock** [comment]
Except I was gonna put it on the Options tab where there should already be room.

**Comment by AzGilrock** [comment]
Also I get nervous when someone who is not a regular developer tries to help with these panels.  There are a lot of rules you have to follow to make sure the positioning works on all 3 operating systems.

**Comment by Clyde-L** [comment]
Yes... that is the function I was hoping for computergeek.  Also Gil, I asked here because I knew that the Morph effect was your creation ;)  I  appreciate everyone's consideration! Thank you very much.

**Comment by computergeek1507** [comment]
@AzGilrock I moved the button to the Option Tap. If you want to try it, copy it, steal it. I was just seeing if I could help with a simple feature so you (and Keith, Dan etc.) can work on more important enhancements. I made a branch on my repo if you want to check it out.

https://github.com/computergeek1507/xLights/tree/morph_swap

Thanks,
Scott

**Comment by AzGilrock** [comment]
Yeah he hasn't learned when people put fingers on my code I tend to pull out the cleaver. :)

**Comment by AzGilrock** [comment]
If you're bored we can find you something to do. :)

**Comment by computergeek1507** [comment]
I would love to help where ever I can. I have tried to reach out to Sean with no luck and cannot send messages through github(At least I don't know how) to try to get in touch with other developers.

**Comment by computergeek1507** [comment]
@AzGilrock I tried my wxPanel changes on my Fedora and Windows install and the sizing was good. I do not have a Mac so I cannot verify for it.

Thanks,

**Comment by AzGilrock** [comment]
That one should be a simple change so just post the pull request.

**Comment by AzGilrock** [comment]
The main things that can get you into trouble is specifying specific sizes.  When there is a case for doing that it usually needs to be done in "dialog units".  I'm not even sure I remember all the so called "rules".  I usually re-learn them when I see Dan fix the code for Mac.

**Comment by keithsw1111** [comment]
Scott ... not sure your full name/contact details. Why dont you reach out to Gil or myself on facebook and we can connect you in.

**Comment by Clyde-L** [comment]
Thank you Scott!  Hope you still have your fingers left?  :)  Gil, this is wonderful.   You just made an amazing addition that will allow me to add extra options into the sequence I would have totally avoided any other time.  Would be great to have another developer jump in to help out with some of the load.
