### ISSUE TITLE
Enhancement request: Add a button in the UI that will launch calculator

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#925]
I think it may be handy to add a button in the UI or a Help Menu item that launches a calculator.
It should be able to know what OS is running and launch the appropriate executable. Windows, Mac, Linux

I also think it would be handy with the Authors permission ..., add a Menu item in About Menu that links to the Online Power calculator.

http://spikerlights.com/calcpower.aspx

**Comment by keithsw1111** [comment]
I disagree.

**Comment by cjd** [comment]
This is something which should be handled by your OS.
Most operating systems allow you to setup hotkeys to launch applications (my laptop even has a special 'calculator' key for this sort of thing
Doing this within xLights would duplicate such functionality.
