### ISSUE TITLE
Cannot select Alternate Lyrics Track

### ISSUE THREAD

**Issue by gizmohd** [smeighan/xLights#926]
I have multiple lyrics tracks in a sequence...   But when I attempt to select an alternate track insite the faces 'timing track' drop down, only the first track appears.
[Chipmunks HO HO HO.zip](https://github.com/smeighan/xLights/files/1327549/Chipmunks.HO.HO.HO.zip)

**Comment by AzGilrock** [comment]
The other 3 tracks only have words so they are not valid.  You must breakdown the words into phonemes before a track can be used.  The track must have 3 layers.
