### ISSUE TITLE
Setup TAB - Directories my observed issue

### ISSUE THREAD

**Issue by bluzervic** [smeighan/xLights#93]
When first setting up XL4.x.x  I selected the directories I wanted for music and FSEQ
However Save button stayed Grayed out.

Was able to use <file><select show folder> and then buttons were not grayed out.
Was able to save after.

-Blu

**Comment by AzGilrock** [comment]
Are you talking about the Save button down in the setup page or the Save Sequence button in the toolbar?  The music and fseq directories I don't believe have anything to do with where the setup is saved.  That still goes to the Show directory.

**Comment by bluzervic** [comment]
It is the directory change buttons under the setup tab to change the default directories where you setup the network configuration.

This only seems to occur on initial setup.

-Blu

**Comment by AzGilrock** [comment]
Yes I know which buttons you were using to set the default directories.  The part I didn't follow is what Save button is greyed out and why you expected it to not be greyed out?  My point was that setting those paths has nothing to do with Save so there's no reason to expect the state of any Save buttons to change.  Then you said "Was able to use and then buttons...."   What were you able to use?

**Comment by bluzervic** [comment]
OH I got ya, All the buttons under Lighting Networks are grayed out.
So effectively there is no way to save any changes made when hitting the change buttons

Example: Save Setup button  is grayed out

-Blu

**Comment by AzGilrock** [comment]
I don't know how to get them to the greyed out state.  I just tried starting with a blank directory for my show directory.  Was this the first time you've ever used Xlights on this PC?  Maybe there is something we put in the registry I don't know about.

**Comment by AzGilrock** [comment]
Ok I happened to be tracking down something for someone else and found out these are only greyed out if you've never run the program and setup your show directory.  We'll figure out how to fix this but the workaround is the first time you run the program click the button that looks like the xlights icon on the left side of the toolbar and set the Show directory.  That will setup the initial XML files and modify the button states.  If you try to set the other 2 directories before every establishing the show directory it will crash.
