### ISSUE TITLE
Import Effects Crash

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#930]
I'm trying to bring in Logan's Trolls sequence into my own layout.  Starting a new musical sequence and selecting the music file.  Using the Import Effects menu item to select the xml file.  Upon hitting Open, xLights crashes.

MacOS using xlights 2017.29
[xLights_dbgrpt-997-20170927T180826.zip](https://github.com/smeighan/xLights/files/1338950/xLights_dbgrpt-997-20170927T180826.zip)

**Comment by keithsw1111** [comment]
Maybe fixed Kevin ... can you build and try again.

**Comment by kppankratz** [comment]
It works again.  Thanks Keith!
