### ISSUE TITLE
Unhandled Exception 

### ISSUE THREAD

**Issue by algerdes** [smeighan/xLights#931]
When trying to open xLights (64 bit, 2017.29), I receive the error:
"***Caught unhandled unknown exception: terminating"
Last action I took was trying to change the show directory from my local computer to a shared drive on another computer.

I have reinstalled .29, but get the same error.
I have checked in each of the .xml files, but don't see anything that I recognize as a problem.

Thank you for any assistance you can give me.  It is crunch time and non-availability is NOT what I need right now.

**Comment by AzGilrock** [comment]
Yep it seems like anyone that like to use cloud based folders or something on another machine is asking for trouble.  Unfortunately uninstalling does not change the show folder location stored in the registry.  If that location is your problem you would probably need to be able to find that key in the registry and delete it.

**Comment by algerdes** [comment]
Where would I go looking Gil?

**Comment by AzGilrock** [comment]
Quickest way to get help is on our Facebook group.  I'm at work for at least another 7 hours.  I don't have the registry path memorized.  I'd look under local machine / Software / xLights or something along those lines.

**Comment by algerdes** [comment]
Thanks.  I’ll get on facebook.

(Not my favorite place.)

**Comment by algerdes** [comment]
Thanks for the reminder about the Facebook Group.  Steve G. replied with the registry group.  I removed the value for LastDir and things are now working again.

**Comment by keithsw1111** [comment]
Use the /w command line switch which will erase all current registry settings.

**Comment by algerdes** [comment]
Thanks Keith.  That one will go into my book of fixes as well.
