### ISSUE TITLE
xLights uninstall does not clean out registry entries  

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#932]
I've seen a few folks with corrupted xlights config files uninstall, install the latest to have it crash again recently.

InnoSetup does not delete registry entries created by default during the installation when doing the uninstall of xLights.
Suggest to Sean reconfigure the InnoSetup to delete the registry entries for a clean uninstall.

http://www.jrsoftware.org/ishelp/index.php?topic=registrysection

**Comment by AzGilrock** [comment]
Funny I was just going to comment on this topic for Al issue.

**Comment by keithsw1111** [comment]
This will be in .30
