### ISSUE TITLE
Delays when saving to windows network mapped drive

### ISSUE THREAD

**Issue by robjoyce1921** [smeighan/xLights#935]
On two different machines, I experience significant delays when saving sequences to a NAS drive that is mapped to a windows drive.   When saving or auto saving, a sequence that normally saves in under a second to the local drive, xlights to hang for 4-6 seconds when doing the network drive access.  This becomes a significant problem when autosave kicks in and freezes the software.  

Loads from the NAS drive seem to be normal speed.

Problem tracks to two different machines.

While I can work on a local machine, it would be good work directly on my NAS so the files are protected by the raid features of that storage system.   Thanks for the awesome software guys!

**Comment by keithsw1111** [comment]
Get a faster NAS drive ... this is really not something we can do anything about.

**Comment by stevegiron** [comment]
Configure the backup location to be on your NAS device. Each time you press F10, all xml files in your show folder will be copied to that location. Some folks press F10 hundreds of times during a sequencing session and that's quite ok.

**Comment by madsci1016** [comment]
I work from a folder synced with google drive. So it's always local file access to xlights, but syncs to multiple computers in the background.
