### ISSUE TITLE
Prop numbering

### ISSUE THREAD

**Issue by RobertVan** [smeighan/xLights#938]
I have notice that the props are only number by the first digit. So when going past 10 the number 1 gets mixed up then 20 brings the 2 up. Any way or this sorting by whole number instead of first digit.

**Comment by keithsw1111** [comment]
If you want them to sort correctly ... just add a leading zero.

**Comment by RobertVan** [comment]
Thanks

Please excuse brevity and mistakes as this was sent from my iPhone
