### ISSUE TITLE
Not an issue but feature request for MP3 Wave file display

### ISSUE THREAD

**Issue by bluzervic** [smeighan/xLights#94]
Would like to be able to increase size of wavefile in height so to be able to see breaks and changes withing the wave file. I believe LOR and Audacity already do this. 

Yes we can zoom in, but the Height dos not change and the granularity it is still hard to see breaks or changes within the wave file

-Blu

**Comment by stevegiron** [comment]
Small wave files means small (low) audio. I suggest that you use Audacity to Effect>Amplify. In this example I used 5db. The wave file is now larger and looks much better in NC. 
![image](https://cloud.githubusercontent.com/assets/10568498/8089945/e0ea9620-0f5f-11e5-906c-31e3ff78eed7.png)

**Comment by stevegiron** [comment]
Not an issue as the height of the wave is directly proportional to the volume in the audio file.
