### ISSUE TITLE
MacOS Debug Alerts

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#942]
I’m getting a couple of wxWidgets debug alerts that I’m hoping you can look into.  The first one happens when I try to quit xLights either by using the keyboard shortcut and/or the menu item.

The second one I’m getting is while I’m testing out some of the new shortcuts that Keith has added with the latest release.  This one happens when I right click in the time line to insert a marker for the navigation.

<img width="420" alt="screen shot 2017-10-03 at 9 10 10 pm" src="https://user-images.githubusercontent.com/12144876/31157354-eb40108a-a87f-11e7-84b6-69de2b9d84e0.png">
<img width="424" alt="screen shot 2017-10-01 at 12 19 18 pm" src="https://user-images.githubusercontent.com/12144876/31157358-ef89e4f4-a87f-11e7-8060-a75370285e2d.png">

**Comment by keithsw1111** [comment]
I think I fixed the first one.

**Comment by kppankratz** [comment]
Yes, the first one is fixed.  Thank you.

**Comment by kppankratz** [comment]
Second one is working now too.
