### ISSUE TITLE
Expand models list in Sequencer 

### ISSUE THREAD

**Issue by Duramadmax** [smeighan/xLights#944]
Some of my model names are larger than window list. would be nice to have capability to expand window

**Comment by keithsw1111** [comment]
Which window?

**Comment by Duramadmax** [comment]
In the sequencer tab, under the Master view pull down box you have the list of all your models...The models names are longer than the viewing capability of the window. Can we have the capability to enlarge window to the right to show more of the models names?

**Comment by Duramadmax** [comment]
[screen.pdf](https://github.com/smeighan/xLights/files/1367173/screen.pdf)

**Comment by Duramadmax** [comment]
[screen.pdf](https://github.com/smeighan/xLights/files/1367178/screen.pdf)

**Comment by keithsw1111** [comment]
You mean the row headings ... just hold your mouse over it and a tool tip will display the full model name if it doesnt fit in the available space.

While making the row heading resizable is desirable but there is already an issue for that #618

**Comment by Duramadmax** [comment]
Ok, gotcha...I new that but was looking for a more visual list. Thanks
