### ISSUE TITLE
pause issue

### ISSUE THREAD

**Issue by 1991mustang50** [smeighan/xLights#946]
if i press pause then play it will start over from start mark.

**Comment by keithsw1111** [comment]
By design I believe.

**Comment by 1991mustang50** [comment]
Oh ok sorry I just thought it would pickup where it was pause cause if it meant to start at beginning or mark stop wood work. The only difference between pause and stop is that pause keeps play line and stop doesnt

**Comment by keithsw1111** [comment]
Which pause

**Comment by 1991mustang50** [comment]
The one between play and stop.

**Comment by keithsw1111** [comment]
How are you unpasuing. You should be pressing pause again.

**Comment by AzGilrock** [comment]
I designed it to work exactly like Audacity and I believe it does that.
