### ISSUE TITLE
3 minor bugs... See included video :)

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#947]
Alright, I have 3 bugs to report
First, Copy and Paste with the mouse scroll wheel deactivates the right-click paste selection.

Second, the Layers Blending box... The Transition Slider is not resetting when selecting a different  effect.  It shows the last setting but moves the slider to the Zero-position.

Third, Time Line tags...  work perfect with the number keys on the upper row of the keyboard.  But when using the CTRL + Number Pad, the tags do not work.

https://www.youtube.com/watch?v=jPJlsoqM21s&feature=youtu.be

Thank you for everything Keith, Dan, Gil, and all.

**Comment by Clyde-L** [comment]
Alright, sorry to have 3 in 1 report... please forgive me

**Comment by AzGilrock** [comment]
No problem I couldn't understand them.  #1 sounds like quit using the scroll wheel and #3 sounds like don't use the numpad.  :)

**Comment by keithsw1111** [comment]
#2 and #3 I think I have fixed. Not sure about #1

**Comment by AzGilrock** [comment]
Ummm....no...not what I said.  Normal people don't use the scroll wheel for copy/paste and there are normal number keys you could use instead of numpad.
