### ISSUE TITLE
Repeated crashes editing last years sequence

### ISSUE THREAD

**Issue by AndyWylde** [smeighan/xLights#948]
This was editing a sequence I did last year to improve a few details.   Limited options shown for "Face" .   I did not have an outline on this face and the normal options were not present (such as show outline) although using Phenome or timing track was there nothing else was.   This crash happened 3 times in a row so I can reproduce it as needed.   Attaching last two crash reports.
[xLights_dbgrpt-24928-20171012T22224
[xLights_dbgrpt-23060-20171012T214831.zip](https://github.com/smeighan/xLights/files/1381520/xLights_dbgrpt-23060-20171012T214831.zip)
1.zip](https://github.com/smeighan/xLights/files/1381519/xLights_dbgrpt-24928-20171012T222241.zip)

Crash report attached, let me know what I can do to help track this down.

**Comment by keithsw1111** [comment]
Can you please move to 2017.32 ... I believe we may have fixed this already.

**Comment by AndyWylde** [comment]
Sorry for the slow response.  I am unable to duplicate this problem in 2017.32, thank you.  I did have a moment where a similar operation had a long pregnant pause but it seemed to recover and move on.  I was not able to duplicate that issue again so I would consider this closed.
