### ISSUE TITLE
Galaxy effect

### ISSUE THREAD

**Issue by ebuechner** [smeighan/xLights#949]
Galaxy effect fails to blend edges when you select reverse. 
I have no idea if this is something new or if it's always worked this way. 
I'm making the assumption that it should blend the edges in reverse the same as it would without the reverse box checked.

**Comment by AzGilrock** [comment]
Good catch I never noticed that.  Didn't seem like reverse could cause that when I read it but testing showed it to be true.  Took a few minutes but I figured out why.  The way I draw is I write into a temporary buffer and then I blend that buffer down into the main buffer every time the galaxy has rotated 90 degrees.  Problem was the reverse made the angle negative so it was never greater than 90.  So a simple absolute value of the angle in a few spots fixes it.  I also noticed the rounded head was drawing the wrong color when it was reversed so got that fixed also.
