### ISSUE TITLE
Model Preview does not display under Sequencer tab

### ISSUE THREAD

**Issue by bluzervic** [smeighan/xLights#95]
I see no display in the Model Preview while under the Sequence tab.

I did do a "Rendor All" and was able to see lights and it is working under the Preview tab

-Blu

**Comment by smeighan** [comment]
model preview (The xlights 3.6 F3) is just clicking on an effect in the sequencer area. click another effect and you get a preview of that effect. it will keep looping forever.

Right click a model and select play and it will start wherever teh scrubber line is in the waveform and play effects and music. This is the equivalent of the F4 preview from xlights 3.6.

is there a different preview than these two?

also, if an effect does not start immediately showing the animation, try hitting F5(update)

**Comment by smeighan** [comment]
did you try "View, Windows.Model Preview" to bring it back?

**Comment by jcmarksafb** [comment]
I see the preview window, it's just black and only has one pixel showing animating. The effect is playing fine on my lights tho.
 


     On Monday, March 23, 2015 2:25 PM, sean meighan <notifications@github.com> wrote:
   

 did you try "View, Windows.Model Preview" to bring it back?—

**Comment by jcmarksafb** [comment]
As an addition, I have 3 props in a new sequence but when I play the sequence only one prop will play on my lights. Is there something I'm missing  that will get all of the props to play on my display at the same time?
 


     On Monday, March 23, 2015 2:43 PM, John Marksbury <jcmarksafb@yahoo.com> wrote:
   

 I see the preview window, it's just black and only has one pixel showing animating. The effect is playing fine on my lights tho.
 


     On Monday, March 23, 2015 2:25 PM, sean meighan <notifications@github.com> wrote:
   

 did you try "View, Windows.Model Preview" to bring it back?—

**Comment by AzGilrock** [comment]
What type of model and size is it?  Do you have all the channels used in the model defined in your setup?  I don't know all the inner workings but I know I had a matrix that was cutoff in the Model Preview but played fine in the Preview tab and it was because I didn't have all the channels defined in the setup page.  I'm not sure why that didn't cause a problem for the Preview window.

**Comment by AzGilrock** [comment]
You mean playing to real hardware?  Are you playing from the Preview tab, Sequencer tab, or the Scheduler?

**Comment by jcmarksafb** [comment]
Yes all models are configured correctly, they play just fine on my real hardware one model at a time however. And the check out fine in the test tab as well. It will only play what ever model I have selected at the time on my real hardware, and will not play at all in the preview tab. I may be doing something wrong, but have tried many things.
 


     On Monday, March 23, 2015 2:56 PM, Gil Jones <notifications@github.com> wrote:
   

 You mean playing to real hardware? Are you playing from the Preview tab, Sequencer tab, or the Scheduler?—

**Comment by AzGilrock** [comment]
You can only play one model at a time on the Sequencer tab.  The preview on that page was meant to only preview a single effect or a single model.  The Preview tab is what should play all models.  Have you saved the sequence before you hit play on the Preview tab?  You gotta hit Save or Render All to write all the data out the arrays that the Preview tab uses to play.

**Comment by bluzervic** [comment]
To better describe what I see

1. I used an existing working Seq file from Xlights 3.x and it converted
2. I then hit the Render all button
3. The seq  runs under the Preview tab... no Problems
4. the models are defined properly and all channels match LOR, Raspberry Pi and Xlights
5. under the Sequence Tab the Preview did not display the model selected (example Micro-tree-1) using "play Model" however the lights for the model and music are working properly.

 I see a very small pixel lighting up..... It is entirely possible the model is displaying but it is so small it look like one pixel. Although I tend to think it is one pixel.

**Comment by jcmarksafb** [comment]
I have hit every save I can find. I understand that only one model will be in the model preview at a time and right now all I get is 1 pixel animating. Playing from the time line in sequencer only plays the model I have highlighted and doesn't play all the models together. The preview tab has my models in it, but will not play at all when I hit the play arrow. I have clicked on the save button in preview as well. If no one else is having these problems, it could be I'm doing something wrong, but version 3 and HLS are still working fine.Thanks for all your work and time.John
 


     On Monday, March 23, 2015 3:31 PM, Gil Jones <notifications@github.com> wrote:
   

 You can only play one model at a time on the Sequencer tab. The preview on that page was meant to only preview a single effect or a single model. The Preview tab is what should play all models. Have you saved the sequence before you hit play on the Preview tab? You gotta hit Save or Render All to write all the data out the arrays that the Preview tab uses to play.—

**Comment by bluzervic** [comment]
This looks resolved in XL 4.0.5, I am going to close it
