### ISSUE TITLE
Xlights Crash and multiple line trim (cut)

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#951]
See video https://youtu.be/vfvOPB0pCSA
I had some effects that went past the end of the song so I was trying to trim them. xLights crashed several times.
[What_does_the_fox_say_2017.zip](https://github.com/smeighan/xLights/files/1385087/What_does_the_fox_say_2017.zip)

Thanks
Pat

**Comment by patdelaney** [comment]
That was fast ... thanks

**Comment by AzGilrock** [comment]
Its easier to fix when it crashes for us too. :)

**Comment by AzGilrock** [comment]
By the way you really don't need to worry about trimming the effects.  That would happen automatically when the sequence is rendered.
