### ISSUE TITLE
Crash Report 2017.32 Using Sine Wave

### ISSUE THREAD

**Issue by dwbarnett** [smeighan/xLights#952]
Here's my crash report. I was experimenting with the sine wave effect.  I was going down the list of Layer selections.   When I selected one of the layer selctions, I got this crash.   I can't remember off hand which one it was, hoping the crash report will clarify.  It happened fast and unexpectant.

Best,
David
[xLights_dbgrpt-6660-20171015T021602.zip](https://github.com/smeighan/xLights/files/1385239/xLights_dbgrpt-6660-20171015T021602.zip)

**Comment by keithsw1111** [comment]
I am pretty sure I found your crash and fixed this one in .33
