### ISSUE TITLE
Multiple monitors, opening the Edit Display Element opens up a small very little box

### ISSUE THREAD

**Issue by bhensley86** [smeighan/xLights#958]
The app box when open appears on a different screen from the xlights tool and hidden behind other menus. First time using the menu, thought it was broken or just not displaying. Minized my windows items and had to drag it to the xlights menu and expand the size. When closed, then re-opened it appears correctly. 

i'm running 2017.33 on a windows 10 system. Two monitors at 1920 x 1200 resolution.

**Comment by dkulp** [comment]
This occurs on the Mac as well, but all the time, not just two monitors.   I haven't had time to look at it.

**Comment by AzGilrock** [comment]
I get a tiny window for several panels but its usually only a one time thing per show directory so I never considered it a big deal.

**Comment by nmiller0113** [comment]
I also see this problem on the Mac

**Comment by keithsw1111** [comment]
I think this is now fixed. Please reopen if not.
