### ISSUE TITLE
Bug(?): Effect Timing Menu does not support type-in values

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#959]
Not sure whether this is a bug or enhancement request but...

When you right-click an effect and select "timing," the Effect Timing menu only allows you to adjust values by clicking the arrow keys. You _are_ able to type-in any value you want but doing so does not change the values of the other two. Subsequently, pressing OK does not save your changes. The only current way to make adjustments is to click / click-hold one of the arrow keys so all three values change simultaneously. Then you can press-OK and the changes are reflected in the timeline.

**Comment by keithsw1111** [comment]
Test for gil

**Comment by keithsw1111** [comment]
I cant reproduce the problem ... can you be more specific.

**Comment by cinoan** [comment]
Just had a look at this and I can see the issue. If you type in a new duration it doesn't update the end time and it seems to be the start and end times that are used in placing the effect.
