### ISSUE TITLE
Perspectives not saving

### ISSUE THREAD

**Issue by jcmarksafb** [smeighan/xLights#96]
Might be me, but I can't save multiple perspectives in 4.0.2

**Comment by stevegiron** [comment]
Perspectives have been working fine for me, I use them often.

**Comment by AzGilrock** [comment]
I thought Perspectives were working also but I just noticed a problem.  I switched to a different Show directory and then switched back to the one I was in and all my Perspectives are gone.  Not sure of my exact steps and I may be restarted the program but we definitely have a problem to fix here.
