### ISSUE TITLE
scrolling up and down of models in sequence editor does not work [linux]

### ISSUE THREAD

**Issue by cp16net** [smeighan/xLights#961]
I found on version .33 of the linux app bundle has an issue with scrolling up and down in the sequence editor. So i see the scroll bar on the right moving up and down but the items (lyric tracks,models,groups, timing tracks) do not scroll up and down. However scrolling left to right works to advance the time of the sequence. 

This kinda bug seems a bit goofy. Could it be a version of wxwidgets you are using? just a random guess...

i had emailed this issue to @cjd but adding this bug here for reference.

**Comment by cjd** [comment]
Craig - what desktop environment/linux distro are you running?
I gave this a test with the same app bundle and it looks to be working (see https://youtu.be/0BK8ZIUFkGo for test run) so there must be something else getting in the way.
By any chance are you on wayland?

**Comment by cp16net** [comment]
Oh crap i see what the issue is... The timing/lyric tracks do not scroll. and on a smaller resolution screen i couldnt see the models/groups. i pushed it up as far as i could and i saw a single model line and scrolled and saw it move through them. (i have lots of tracks in the sequence i was looking at)
So this is not really an issue i guess if i had a higher resolution. :-/ silliness.

**Comment by AzGilrock** [comment]
I tried to say the same thing yesterday but GitHub wasn't working for me.

**Comment by AzGilrock** [comment]
Hurray I can finally comment.  Its been down for 3 days for me.
