### ISSUE TITLE
Models and Model Groups names allow for invalid characters

### ISSUE THREAD

**Issue by nmiller0113** [smeighan/xLights#962]
As reported [here](http://nutcracker123.com/forum/index.php?topic=4755.0) xLights allows for the use of invalid characters like comma's in models and model group names which can cause issues in some cases and in general should not be allowed.

**Comment by keithsw1111** [comment]
I am not sure this is true ... The Model class has a safe name function which strips a whole bunch of characters including:
,~!;<>"'&;|#@/\
Can you be more specific about how you entered these characters ... we may have missed a call to SafeModelName() ... or it may be an old file ... although this function has been there about a year.

**Comment by nmiller0113** [comment]
Keith, maybe it isn't.  Dan was mentioning that the comma's in my model groups was likely fouling it up though I haven't been home from the office to test out his theory.  I don't know if you got an opportunity to read the thread from the xLights forum I above but you may be able to see more clearly there as there is also a video.  Nonetheless I'll give it a run through here:

Setup - xLights BETA 2017.33 64 Mac (I also tested on the same 64bit version in Windows and had the same result)

I recorded this to better show / explain the issue.  Here is the [video link](https://drive.google.com/open?id=0B7E6agkvZj6wWW9Vd1p1alhpSUk)

I'll walk you through the video:

1. I show you that I've created the model group "Whole House No LM,GA,HF1" and what is inside of it
2. I then add the model group "Whole House No LM,GA,HF1" to the model group "Whole House" which appears to work until you click away and then back to find it added another model group in its place "Whole House No LM" which is obviously not what I selected
3. I show step 2 once more to prove I'm not crazy and clicked the wrong thing :)
4. Since it was adding / changing what I selected from "Whole House No LM,GA,HF1" to "Whole House No LM" I thought I'd try to add "Whole House No LM,GA,HF1" to the model group that it was changing it to "Whole House No LM" to see what happens.  As you can see, it immediately crashes xLights

**Comment by nmiller0113** [comment]
Gil just confirmed before I got home and had a chance to.  This is only happening to me because I've had it in my config for many years.  If I try to create a new model now with this it won't work.  Closing this issue as it is only a problem in configs that existed prior to the check.
