### ISSUE TITLE
Spirals effect isn't evenly spaced for Palette Rep of 5

### ISSUE THREAD

**Issue by MikeSoukup** [smeighan/xLights#965]
When I set the Palette Rep to 5 for the Spirals effect, the 5th spoke isn't drawn in the correct position, it's drawn where the 4th spoke was when Palette Rep was set to 4. So the spacing isn't even and there's a gap between the 5th & 1st spokes. This is on a wreath with render style set to default.

![spirals](https://user-images.githubusercontent.com/10994778/32086462-fc8aac6a-ba9a-11e7-9be0-3dde7b422b17.png)

**Comment by keithsw1111** [comment]
That looks correct. If your model isnt divisible by 5 then you are going to get a gap.

**Comment by MikeSoukup** [comment]
It would make more sense to distribute the gap as evenly as possible throughout the model, but that algorithm may be a bit more difficult.  If this is the expected behavior, feel free to close the issue.
