### ISSUE TITLE
Vixen 2.1 not importing properly

### ISSUE THREAD

**Issue by beatlerat** [smeighan/xLights#966]
Could not promote node effects and tried importing Vix2.1 into xLights.33 and it is off by one channel
![vix](https://user-images.githubusercontent.com/11862866/32130828-18f705e0-bb65-11e7-9651-e2ab4bebe8cb.jpg)
![xlights 33](https://user-images.githubusercontent.com/11862866/32130830-1c713056-bb65-11e7-9218-67d1f7ec0ecf.jpg)

**Comment by computergeek1507** [comment]
I tried it with a simple test vix file I made and it worked correctly for me with version 34. Maybe there is something specific in your vix file.

![image](https://user-images.githubusercontent.com/2293065/32131229-c9f82958-bb76-11e7-87d6-bda0dbd03c5d.png)

![image](https://user-images.githubusercontent.com/2293065/32131235-e2f35ca2-bb76-11e7-9903-10aeb28e89d6.png)

**Comment by beatlerat** [comment]
I am trying to import channels 11 through 20 in the vixen file into xLights.  I have done it in the past, but importing the .xml file yields the same results.  All of the other channels import fine.  I was on a zoom call 10/27 and everyone said the models looked fine.  Here is the .vix file
[Sequences.zip](https://github.com/smeighan/xLights/files/1424369/Sequences.zip)

**Comment by computergeek1507** [comment]
I see the same issue with your files. You should reopen the issue.

**Comment by beatlerat** [comment]
I must have accidentally closed this.  Reopening.

**Comment by keithsw1111** [comment]
Problem was we were not handling correctly the last partial frame which caused an off by one error.

**Comment by keithsw1111** [comment]
If you want to work around this in advance of the .35 release edit the .vix file and round up the sequence length to the next multiple of 50 milliseconds.
