### ISSUE TITLE
Dmx joystick

### ISSUE THREAD

**Issue by Kamal-Sonani** [smeighan/xLights#968]
1. Add some dmx head effects for spot lights(all wave,up,down,left right,circle) 
2. Joystick for set head manually ( doing x&y with slider takes too muvh time).

**Comment by AzGilrock** [comment]
For #1 you can just create your own value curve that does the motions you want and save them to be used later.  The heads are all so widely different I doubt we will take the time to be able to profile them all well enough to create a feature like that.  We already have users doing some great stuff with the current feature set.

For #2 the idea might sound great initially but I cannot envision what the interface or triggers would be to allow the joystick to affect a model as well as all the calibration parameters it would take to handle many different joysticks controlling many head types.
