### ISSUE TITLE
Setup USB Dongle Max Channels is 4095

### ISSUE THREAD

**Issue by TexasStingray** [smeighan/xLights#969]
When I add a new USB dongle it will not allow me to enter 4096 so it says 1 - 4095. Adding a second one start at 4096 - 8190 so it keeps loosing 1

**Comment by keithsw1111** [comment]
We need more information. What are you actually setting up.

**Comment by TexasStingray** [comment]
on the setup tab, add USB, open Setup USB Dialog Box. Set Network Type (protocol) to Pixelnet, Select com port, LAST CHANNEL 4096 OK button becomes disabled, Set LAST CHANNEL to 4095 OK button becomes enabled. Add a second USB and follow the same process 4095 is the max. then look at the channel mapping first USB is 1-4095, second one is 4096 to 8180

**Comment by TexasStingray** [comment]
![usbsetup](https://user-images.githubusercontent.com/3461522/32411368-b4a144be-c1a6-11e7-821c-cac4dd921257.png)

**Comment by keithsw1111** [comment]
This will be in .35
