### ISSUE TITLE
Alternate location to save the fseq file

### ISSUE THREAD

**Issue by jspiker77** [smeighan/xLights#970]
Enhancement request for the 2018 season. Would it be possible to add an option to select an alternate location to save the fseq file rather than in the show directory.

**Comment by stevegiron** [comment]
You only need the fseq when ready to play to lights. The more important file is the sequence.xml and that can be configured to back up to an alternate backup location. From there a simple render will generate the FSEQ.

**Comment by dkulp** [comment]
I've been thinking about implementing this for a while now.   My "Show" directory is a dropbox or cloud storage location, but the fseq file is not important to be stored there and takes up a ton of space.

**Comment by cjd** [comment]
I use NextCloud for my cloud storage and it allows you to exclude files based on filename/extension so I've excluded *.fseq to reduce usage.
Not sure if other cloud storage clients have similar functionality but might be helpful

**Comment by dkulp** [comment]
Neither DropBox or iCloud allow setting files to exclude.  It's entire folders.

**Comment by jspiker77** [comment]
The reason being is my show director is also is a dropbox storage location in addition I run xLights off my my SSD drive which is limited in space. Being able to save them in a separate location I could put them on a secondary drive away from my SSD and dropbox but will be able to grab them for the actual show.

**Comment by keithsw1111** [comment]
This will be in .12.
