### ISSUE TITLE
Sub-Models generating but not showing, untill Xlights restart

### ISSUE THREAD

**Issue by dwbarnett** [smeighan/xLights#971]
Confirmed by Richard Renn. If you create a model and or use existing model, then create sub-models; once saved they will not show on the layout screen or model in sequencer. Must close and reopen Xlights to see the sub-models and the dropdown arrow on the layout screen as well as the sequencer.

Best,
David Barnett

**Comment by keithsw1111** [comment]
This will be fixed in .12 or .13 when the submodels dialog changes make it into the release.
