### ISSUE TITLE
xlights PROD (ver 2017.32 32bit) oct 09,2017 crash reports with windows 7

### ISSUE THREAD

**Issue by rtedsei** [smeighan/xLights#972]
[xLights_dbgrpt-3576-20171105T155126.zip](https://github.com/smeighan/xLights/files/1444848/xLights_dbgrpt-3576-20171105T155126.zip)
[xLights_dbgrpt-3360-20171105T151620.zip](https://github.com/smeighan/xLights/files/1444849/xLights_dbgrpt-3360-20171105T151620.zip)
[xLights_dbgrpt-2748-20171105T220503.zip](https://github.com/smeighan/xLights/files/1444850/xLights_dbgrpt-2748-20171105T220503.zip)
[xLights_dbgrpt-2680-20171105T183224.zip](https://github.com/smeighan/xLights/files/1444851/xLights_dbgrpt-2680-20171105T183224.zip)
[xLights_dbgrpt-2512-20171104T214023.zip](https://github.com/smeighan/xLights/files/1444853/xLights_dbgrpt-2512-20171104T214023.zip)
[xLights_dbgrpt-1928-20171105T215530.zip](https://github.com/smeighan/xLights/files/1444854/xLights_dbgrpt-1928-20171105T215530.zip)
[xLights_dbgrpt-1772-20171104T225935.zip](https://github.com/smeighan/xLights/files/1444855/xLights_dbgrpt-1772-20171104T225935.zip)
[xLights_dbgrpt-288-20171105T182802.zip](https://github.com/smeighan/xLights/files/1444856/xLights_dbgrpt-288-20171105T182802.zip)

**Comment by keithsw1111** [comment]
Can you upgrade to .34 ... while I am not sure we have fixed this there has been some work done on this error that may help us isolate it. It clearly happens reasonably often on your machine ... is there any pattern to what you were doing when it happened?

**Comment by rtedsei** [comment]
Hi Keith,

Last night I decided to download and install the 64bit version hoping this
would help, however the same results occurred. The pattern that generates
the crash report is as follows;
Only occurs when I am in the sequencer window,  I select animation 20 or 50
fps then I start selecting a variety of sequences in particular the bar,
galaxy and butterfly effect. As I start playing with the various sequences
I have selected within a couple minutes the crash occurs.

I can say that the 64bit version seems to take longer before crashing. I
hope this helps. Tonight I will upgrade .34 and report my findings.

Sincerely,

Romeo.

**Comment by keithsw1111** [comment]
It shouldnt be the problem but have you considered fixing this problem:

WARN: Model 'MEGA TREE' starts on controller '' but ends at channel 10140 which is not on a controller.

**Comment by rtedsei** [comment]
Hi Keith,

Thanks very much for pointing the controller end channel mistake, will make
the correction.

FYI - I downloaded the .34 version and it seems to be more stable.  Will
keep monitoring it in the next few days.

You guys are awesome.

I will be donating to the xlights this evening.

Romeo.

**Comment by rtedsei** [comment]
Hi Keith,

Version .34 is much improved. Last night I actually did over 1hr of
sequence work with no crash.

Thanks for your help it is really appreciated.

Romeo.

**Comment by keithsw1111** [comment]
I am closing this issue as I dont see any further follow up hinted at in the last response.
