### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by bluzervic** [smeighan/xLights#98]
Under the Test Tab

Using the RGB Tab for Testing, Green does not work

On all except background selection (example: Chase 1/3) I see Blue and red but no green

Standard and RGB Cycle seem to work Properly

-Blu

**Comment by stevegiron** [comment]
Hello, I'm helping sort the issues and determine which issues are still valid. 
As of May-14 we are version 4.0.31. Is this issue still occurring?

**Comment by stevegiron** [comment]
Please update status on this or we will close this on 8/15.
