### ISSUE TITLE
xScheduler "buttons" not working on Iphone "plus" due to screen resolution

### ISSUE THREAD

**Issue by Ellis101** [smeighan/xLights#981]
The Buttons feature does not work in IPhone Safari on the Plus phones due to screen resolution conflict.

It does however work with Google Chrome browser App.

**Comment by BillyFrostick** [comment]
Could you provide a screenshot of whats going on? What IOS version are you running?

**Comment by Ellis101** [comment]
Just logged in via phone and now buttons are showing in Safari :/
