### ISSUE TITLE
Audio crash on sequencer

### ISSUE THREAD

**Issue by Daniluck** [smeighan/xLights#984]
Currently running 64 bit 2017.36

If I leave xLights open for a long period of time and not using it (1-2 hours), then come back and try to play the song, it wont play.  It time kind of flickers like it wants to start but it never does. I close xLights and re-open it will work.

It started when I upgraded to new Production release 2017.32.  I upgraded all the way to release 36 to see if that fixed the issue, but it didn't.

**Comment by AzGilrock** [comment]
Do you think giving us your log file might help?

**Comment by Daniluck** [comment]
[xLights_l4cpp_daniluck.txt](https://github.com/smeighan/xLights/files/1479740/xLights_l4cpp_daniluck.txt)
Attached is the log.  I was able to recreate the issue on 11-16-2017 @ approx. 1:28PM.  Hope this helps.

**Comment by keithsw1111** [comment]
I dont see anything in the log that suggests a problem with the audio ... maybe you could record a video for us of the problem.

**Comment by keithsw1111** [comment]
Without more information I am going to have to close this ticket.
