### ISSUE TITLE
Effect Assist doesn't work on groups

### ISSUE THREAD

**Issue by madsci1016** [smeighan/xLights#986]
Editing effects on groups I noticed I loose effect assist when the effect is on a group. The window is empty. Keith assumes its because effect assist is trying to figure out the size of the model to draw the grid. Would be nice if we could still use effect assist on groups, possibly using the size of the group grid to render the effect assist grid.

**Comment by AzGilrock** [comment]
Its works fine if you make the window large enough.  The problem is if the window is too small the cells don't have enough room for the minimum cell size.

**Comment by AzGilrock** [comment]
I always wanted to make that view zoomable and scrollable but with wxWidgets its a pain figuring a lot of that out.  I can't even get what's there to refresh correctly.

**Comment by madsci1016** [comment]
Yep that was it thanks Gil. Not a GUI person, but any though into the possibility in having the grid in the Effect assist window always scale to the size of the window?

**Comment by AzGilrock** [comment]
It normally does but when I created it I established a minimum cell size of 10 pixels.  I could make that smaller but at some point you won't have enough pixels in between lines.  If I got zoom working then I would just zoom in until it was the minimum cell size and then let you scroll.
