### ISSUE TITLE
Enhancement Request:  Effect Presets

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#987]
Is it possible, or even beneficial, to add the length of the effects saved in addition to the current layer count?   xxxxx (2L, 10s)

I see a number of "why isn't the presets working" questions and it comes down to trying to insert the presets into a too small of space on the sequencing grid.

**Comment by keithsw1111** [comment]
I am not sure that would help. I doubt anyone would notice/connect the two things together. Maybe we should display an error if they try to insert a preset and it doesnt fit. That would seem more appropriate.

**Comment by AzGilrock** [comment]
The thing is presets use the Paste logic so the error would need to happen for pasting also.  The way a paste works is it doesn't destroy data.  You can actually have effects in the middle of a paste get blocked but effects further down will paste.  It basically will paste every effect that doesn't hit an overlap.  So technically you could have a preset that is 20 seconds long and paste it into an area that has other effects as long as there is no clashing where those effects exist.

**Comment by stevegiron** [comment]
Keep this in mind as well. I've been creating a set of presets that are beats oriented. One merely needs to select the fit to cell option when applying the preset and those will always fit in the timing mark.
