### ISSUE TITLE
Creating a new folder, when importing sup file causes crash to desktop

### ISSUE THREAD

**Issue by dwbarnett** [smeighan/xLights#988]
This has happened 3 times.  Load up my working xml. Get all models sequenced as needed.

Then try an import of a sup file for my mega tree, everything is fine until I try and create a folder for the image files. Crash to desktop each time.  The file name is empty when trying to create folder. If foldr created outside of Xlights, everything works fine in Xlights.   Little frustrating to have to restart everything.

All is saved, so still have sequence, just have to redo tree again.
Best,
David

**Comment by AzGilrock** [comment]
No crash file, no log file, no fixie problem.

**Comment by dwbarnett** [comment]
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/1485159/xLights_l4cpp.log)
 Hey Gil, there was no crash file. Just went to desktop. Forgot about the log file. Have now enclosed. Hope it will help. I can work around by creating the folders first, then import. Seems to work OK

Best,
David

**Comment by keithsw1111** [comment]
Can you do a package logs and post it. There is something in your log file i would like to try to reproduce.

**Comment by dwbarnett** [comment]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/1486078/xLightsProblem.zip)
 Here Ya Go Keith, Hope it is helpful.
Best,
David

**Comment by keithsw1111** [comment]
Can you video the crash ... i tried to do what you described and it worked fine

**Comment by dwbarnett** [comment]
ok, Keith I’ll see what I can do for you
Thank You for your time. Im off today, if you wanted to try a zoom session

Best,
David

**Comment by dwbarnett** [comment]
Well, Keith don't know what to say at this point. I wanted to walk through this first, before I made a vid for you, so I wouldn't waste a lot of time.  Followed the above procedure for Wizards. crashed when trying to create folder for images.  Restarted Xlights. created again, this time it worked fine.  I don't know what to tell you at this point.   One time it crashes, the I redo it, no crash....slapping forehead.  I know I can work around by creating folder first, so that is what I'll do for now.   Perhaps we can try a zoom session some time.   

Best,
David

PS disn't see need to make vid, as now I can't continually duplicate either.

**Comment by keithsw1111** [comment]
Hard to reproduce problems are unfortunately hard to fix.

**Comment by dwbarnett** [comment]
Yep!
Happy Thanksgiving to you and yours Keith.
Best,
David

**Comment by dwbarnett** [comment]
if you want to try a zoom session sometime, let me know.

Best,
David

**Comment by keithsw1111** [comment]
I am typically in there late wednesday night your time and your friday/saturday night.

**Comment by dwbarnett** [comment]
OK Keith, I'll see if I can hook up with you Wed night.
Best,
David

**Comment by keithsw1111** [comment]
David ... should I close this? Or can we progress it to a resolution?

**Comment by dwbarnett** [comment]
Hi Keith, Happy New Year.  I had it happen the other day. But easy work around. Just create the folder first outside of Xlights, then no crash.

Seems I’m the only one having issues. I can work with it.

Best,
David

**Comment by AzGilrock** [comment]
Ok I say just reopen if you get another crash log.
