### ISSUE TITLE
Crash: Selecting "Per Model Single Line" for Spirals effect on all models

### ISSUE THREAD

**Issue by nathan815** [smeighan/xLights#990]
I was trying different layer settings styles for the Spirals effect applied to all of my models, and when I selected "Per Model Single Line" it caused xLights to crash.

Screenshot: https://i.imgur.com/wrgWEAl.png

I attached the debug report zip.

[xLights_dbgrpt-20877-20171121T180828.zip](https://github.com/smeighan/xLights/files/1493339/xLights_dbgrpt-20877-20171121T180828.zip)

**Comment by keithsw1111** [comment]
Are you using v2017.28 ... if so please upgrade to .37 and see if it still crashes ... bugs like this have been fixed relatively recently.

**Comment by computergeek1507** [comment]
Worked for me, on .37

![spiral](https://user-images.githubusercontent.com/2293065/33104544-c53affc4-cef6-11e7-8766-26901e2ddfcb.gif)

**Comment by nathan815** [comment]
Ah you're right I just updated. Thanks. I always forget to update it.
