### ISSUE TITLE
Batch render in 2017.37 failure

### ISSUE THREAD

**Issue by lithgowlights** [smeighan/xLights#991]
My show directory is Z:/lithgow_lights/ and sequences are in Z:/lithgow_lights/sequences/ directory. Batch render sees them, and allows me to tick the files but when it renders them, it places them in Z:/lithgow_lights/ directory.

Also the rendering does not complete properly. I have one test sequence used when installing the lights that is in the Z:/lithgow_lights/ directory and all the show sequences have the same fseq file size as that test animation, much smaller than the 200-600MB they should be. 

Tried both 1 and multiple files and they all fail to render correctly

**Comment by cp16net** [comment]
i can confirm this happens on mac as well.
