### ISSUE TITLE
Edit Display Elements

### ISSUE THREAD

**Issue by DGHayes** [smeighan/xLights#992]
Version 2017.32 64 Bit on Windows 10 Pro
When trying to open Edit Display Elements, a window flashes (like its opening) but it fails to load. Reloaded xLights to no avail. 
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/1495534/xLightsProblem.zip)

**Comment by DGHayes** [comment]
Just found a minute window (only showed up as background was black) which was the Edit Display Elements window in minute form. Dragged out to correct size. Not sure if it was packaged that way in this release.

**Comment by AzGilrock** [comment]
I see this a lot also but I think it only happens the first time for a new show directory and once it's sized it stays larger.  I know this has been mentioned a couple times so I can't remember if we already have an open issue for it.  Its something we do need to see if we can set a minimum size of why its not working.

**Comment by DGHayes** [comment]
Hi Az, do you need a screen capture of it on a new machine? It seems to locate on the model preview (black screen).

**Comment by AzGilrock** [comment]
No I know what the problem looks like.
