### ISSUE TITLE
xLights Crash - no but report

### ISSUE THREAD

**Issue by HonScottHMcCoy** [smeighan/xLights#993]
Just had xLights crash. A debug report dialog window came up. However, there is no report file in the directory as it states it created. I also don't know how to submit a bug report or this file (if the file would have been created).  What do I do now?

![image](https://user-images.githubusercontent.com/33946864/33194224-10cf4fe6-d094-11e7-993b-35a657b53e00.png)

**Comment by keithsw1111** [comment]
There is nothing we can do to resolve this with just this information.
