### ISSUE TITLE
Enhancement for Single Strand 

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#994]
Don't need this till after 2017!

Can a "Bounce to Middle" and "Bounce from Middle" be added into the Chase Types?

Thank you!

Merry Christmas :)

Clyde L

**Comment by computergeek1507** [comment]
How would these be different from "Dual Bounce"?

**Comment by Clyde-L** [comment]
It's dependent on where the bounce begins.  Say I want one arch to "dual bounce" starting in the center... and the other arch to "dual bounce" starting from the outside.  Currently the only way to do this is to offset the Single Strand effect on the timing grid.
