### ISSUE TITLE
Enhancement Request for xScheduler

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#995]
Can a tag-line be added to display the "current playing song/sequence/MP3/Video"?  Or am I missing something?

Thank you!

Merry Christmas :)

Clyde L

**Comment by keithsw1111** [comment]
Added where?

**Comment by Clyde-L** [comment]
Anywhere in the main player, possibly in the bottom margin.

**Comment by keithsw1111** [comment]
If you click on the playlist on the left pane doesnt it show you current and next song and timings on the right?

**Comment by Clyde-L** [comment]
I will look at that tonight.  Did not know it might be there.
