### ISSUE TITLE
Text effect does not work with Matrices when they are added to a group. Other effects (i.e.butterfly) do.

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#997]
Have 8 Matrices. 4 on one side of yard, 4 on other. When adding Matrices 1-4 to group "left matrix" and Matrices 5-8 to group "right matrix" and apply the Text effect on the group, the text is small, small, small, no matter what size font or style you tell it to use. If you add the SAME text effect to a single matrix (in this case, left matrix panel 1) it renders properly and outputs properly using the entire matrix.  HOWEVER: if you used the butterfly effect, or other effects, it WOULD render across all matrices correctly. 

What we had to do as a workaround, was create a CUSTOM model with all 4 matrices on the left, and all 4 on the right for it to render properly. 

We then took it one step further, and created "BIG ASS MATRIX" that has all 8 , custom model. .. :(

**Comment by keithsw1111** [comment]
This is well known and expected behaviour that wont change.

See tip of the day #055 ... https://xlights.org/tip-of-the-day-055/
