### ISSUE TITLE
Vertical Text Vector Movement Issues

### ISSUE THREAD

**Issue by pounce** [smeighan/xLights#998]
I found couple issues with the text effect when the movement is set to "vector" and the effect is set to "rotate down 90" on a tree model.  The text shifts to the left by two pixels from the start position to the end position even when x is set to 0 for both positions.  Another issue is when you set y to -200 for start position and y to 200 for the end position the effect does not finish with anything over 10 characters long.  The text should appear from the bottom and completely pass the top of the model before ending.   

Specifications:
16 x 50 pixel tree (180 degrees)
Xlights Version 2017.38 - 64bit - Windows 10

![vertical text settings](https://user-images.githubusercontent.com/34051094/33303279-1a424102-d3b7-11e7-9570-32f01f6ac271.PNG)

**Comment by AzGilrock** [comment]
You are using the special XL fonts that are designed to match SuperStar imports.  You should just switch to the normal OS fonts if you have issues.

**Comment by pounce** [comment]
I purchased a few SuperStar sequences from holidaysequences.com for my mega tree and that is how I discovered this issue.  All of those sequences use XL scrolling vertical text.  **How do I get the text to vertically scroll while the characters are facing up without using XL fonts?**

**Comment by AzGilrock** [comment]
Trying to match the Text has been a big problem.  I tried to make it better.  Sorry but I can't fix this problem till next year.  There is way to use the normal fonts to do pretty much anything.  If one of the rotation options in the effect don't work there is always the master rotation option in the RotoZoom tab.  Just gotta learn all the tools we provide.

**Comment by AzGilrock** [comment]
Plus tell me the name of the sequence so when I do work on this I can get it from them and make sure it matches after import.

**Comment by AzGilrock** [comment]
I had asked for the name of the sequence that wasn't importing properly.  Please reply or next time I visit this it will be closed.

**Comment by pounce** [comment]
Sorry for the late response.  I have been unsuccessful in modifying the x axis controls in RotoZoom to stop the scrolling text from rotating left.  [Here ](http://www.holidaysequences.com/16-PIX-Mavis-Staples-Christmas-Vacation-p/16pix-mscv.htm)is a link to the Christmas Vacation mega tree sequence.  I can send you a copy of the superstar file for testing purposes.

**Comment by AzGilrock** [comment]
I'm looking at older issues.  I've tested the settings in the first post here and I don't see it jump over any pixels so it seems to be fixed.  Also the expectation that -200 to +200 runs the text from top to bottom is just not in alignment with how the effect was designed.  That vector motion uses that 200 number as a percentage of the buffer size so yes it will change depending on the number of characters.  Also if you check the "Offsets in Pixels" it becomes a pixel offset instead of percentage offset.
