### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ebourgeault** [smeighan/xLights#999]
[xLights_dbgrpt-5016-20171130T222351.zip](https://github.com/smeighan/xLights/files/1520358/xLights_dbgrpt-5016-20171130T222351.zip)

[xLights_dbgrpt-4048-20171130T204242.zip](https://github.com/smeighan/xLights/files/1520357/xLights_dbgrpt-4048-20171130T204242.zip)

I am testing before building/adding megatree to display. When trying different effects on tree xlights crashes. Crash has happened multiple times, only when mega tree is in the layout. 
Windows 7, 64 bit laptop. Using xlights64 2017.32. I am new to this so it very well could be something I am doing wrong. 

[xLights_dbgrpt-3456-20171130T224300.zip](https://github.com/smeighan/xLights/files/1520356/xLights_dbgrpt-3456-20171130T224300.zip)

**Comment by keithsw1111** [comment]
Upgrade to .39. Odds are your problem has already been fixed

**Comment by AzGilrock** [comment]
We are up to version 2017.42 now.  Start a new issue if you have a crash with the latest version.
